const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
  reloadOnOnline: true,
  disable: process.env.NODE_ENV === "development",
  fallbacks: { document: "/offline.html" },
  workboxOptions: {
    disableDevLogs: true,
    runtimeCaching: [
      {
        // The app's JS/CSS chunks. The skill-tree question TEXT is bundled into
        // these per-subject chunks (each subject is a dynamic import), so a
        // generous cap is what makes practice work offline once a subject's
        // chunk has been fetched — keep it well above the chunk count so chunks
        // aren't evicted mid-term.
        urlPattern: /\/_next\/static\/.*/i,
        handler: "CacheFirst",
        options: {
          cacheName: "static-assets",
          expiration: { maxEntries: 600, maxAgeSeconds: 60 * 60 * 24 * 30 },
        },
      },
      {
        // Skill-tree subject diagrams (public/<slug>/*). Kept in their own
        // durable, high-capacity cache so a learner who downloads a subject for
        // offline use doesn't lose its diagrams to eviction. The full image set
        // across all subjects is ~420 files / ~6 MB (see public/offline-manifest.json,
        // regenerated by scripts/gen-offline-manifest.mjs), so 700 holds every
        // subject at once. Must precede the generic image rule below — Workbox
        // uses the first matching route.
        urlPattern: /\/(afrikaans|economics|geography|life-sciences|life-skills|natural-sciences-sp)\/[^?]+\.(?:png|jpg|jpeg|svg|webp)$/i,
        handler: "CacheFirst",
        options: {
          cacheName: "offline-subject-images",
          expiration: { maxEntries: 700, maxAgeSeconds: 60 * 60 * 24 * 90 },
        },
      },
      {
        urlPattern: /\/data\/.*\.json$/i,
        handler: "StaleWhileRevalidate",
        options: {
          cacheName: "lesson-data",
          expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 },
        },
      },
      {
        urlPattern: /^https?.*/,
        handler: "NetworkFirst",
        options: {
          cacheName: "pages",
          networkTimeoutSeconds: 10,
          expiration: { maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 },
        },
      },
      {
        urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/i,
        handler: "CacheFirst",
        options: {
          cacheName: "images",
          expiration: { maxEntries: 60, maxAgeSeconds: 60 * 60 * 24 * 30 },
        },
      },
      {
        urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
        handler: "CacheFirst",
        options: {
          cacheName: "google-fonts",
          expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
        },
      },
    ],
  },
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  serverExternalPackages: ["pdfmake"],
  webpack: (config, { isServer }) => {
    config.resolve.alias.canvas = false;
    if (isServer) {
      config.externals = [
        ...(Array.isArray(config.externals) ? config.externals : []),
        "pdfmake",
        "pdfmake/build/vfs_fonts",
      ];
    }
    return config;
  },
};

module.exports = withPWA(nextConfig);
