// ─── EMS SP — Grade 9 authored pools (A): The Economy ─────────────────────────
// Strand: The Economy (CAPS G9). Tap-only. Recipe: 10 MC · 4 TF · 4 CLOZE ·
// 1 sequence · 1 sort-buckets = 20. (Circular-flow & price-theory diagram items
// are flagged image_dependent in the tree and authored in a later pass; the
// concept items below need no image.)

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9 = {
  // ─── E1 · Term 1 — Economic systems ────────────────────────────────────────
  // A1 · The planned economy
  "EMS.G9.E1.A1": [
    MC("In a planned (command) economy, who mainly decides what is produced?", ["The government", "Private businesses alone", "Only households", "No one"], "The government",
      "In a planned economy the government decides what, how and for whom to produce.", "ERR_EMS_G9E1A1_DEF", 1),
    MC("Another name for a planned economy is a ____ economy.", ["command", "market", "free", "mixed"], "command",
      "A planned economy is also called a command economy.", "ERR_EMS_G9E1A1_COMMAND", 1),
    MC("In a planned economy, most resources and businesses are owned by ____.", ["the state", "private individuals", "foreign tourists", "no one"], "the state",
      "The state owns most resources and businesses in a planned economy.", "ERR_EMS_G9E1A1_STATE", 1),
    MC("An advantage of a planned economy is that ____.", ["the government can try to provide for everyone's basic needs", "prices are set only by supply and demand", "there is no government role", "businesses compete freely"], "the government can try to provide for everyone's basic needs",
      "A planned economy can aim to meet everyone's basic needs.", "ERR_EMS_G9E1A1_ADV", 2),
    MC("A disadvantage of a planned economy is that ____.", ["there is little choice and less incentive to work hard", "there is too much competition", "consumers have unlimited choice", "businesses set their own prices"], "there is little choice and less incentive to work hard",
      "Planned economies often have limited choice and weak incentives.", "ERR_EMS_G9E1A1_DIS", 2),
    MC("In a planned economy, prices are usually ____.", ["set by the government", "set only by businesses", "decided by tourists", "random"], "set by the government",
      "Government, not the market, sets prices in a planned economy.", "ERR_EMS_G9E1A1_PRICES", 2),
    MC("Which decision belongs to the government in a planned economy?", ["What goods to produce", "Nothing at all", "Only what colour to paint shops", "Only the weather"], "What goods to produce",
      "The government decides what, how and for whom to produce.", "ERR_EMS_G9E1A1_DECIDE", 2),
    MC("Where did planned economies historically develop?", ["In states like the former Soviet Union", "Only in South Africa", "Only in shops", "Nowhere"], "In states like the former Soviet Union",
      "Planned economies were used in states such as the former Soviet Union.", "ERR_EMS_G9E1A1_ORIGIN", 2),
    MC("A key feature of a planned economy is ____.", ["central government control of the economy", "no government at all", "only private ownership", "free competition only"], "central government control of the economy",
      "Central government control is the defining feature.", "ERR_EMS_G9E1A1_FEATURE", 2),
    MC("Why might a planned economy struggle to meet consumer wants?", ["Central planners cannot easily match what everyone wants", "Consumers have no wants", "There is too much choice", "Businesses compete too much"], "Central planners cannot easily match what everyone wants",
      "It is hard for central planners to match the varied wants of all consumers.", "ERR_EMS_G9E1A1_STRUGGLE", 3),
    TF("In a planned economy, the government decides what is produced.", "True",
      "The government makes the main production decisions.", "ERR_EMS_G9E1A1_TF1", 1),
    TF("A planned economy is also called a command economy.", "True",
      "Planned and command economy mean the same thing.", "ERR_EMS_G9E1A1_TF2", 1),
    TF("In a planned economy, private individuals own most businesses.", "False",
      "The state owns most businesses and resources in a planned economy.", "ERR_EMS_G9E1A1_TF3", 1),
    TF("Planned economies often give consumers little choice.", "True",
      "Limited choice is a common feature of planned economies.", "ERR_EMS_G9E1A1_TF4", 2),
    CLOZE("An economy where the government decides what to produce is a ____ economy.", ["planned", "market", "free", "mixed"], "planned",
      "A planned economy is government-directed.", "ERR_EMS_G9E1A1_CL1", 1),
    CLOZE("Another name for a planned economy is a ____ economy.", ["command", "market", "open", "free"], "command",
      "Planned = command economy.", "ERR_EMS_G9E1A1_CL2", 1),
    CLOZE("In a planned economy, the ____ owns most resources.", ["state", "shopper", "tourist", "bank"], "state",
      "The state owns most resources.", "ERR_EMS_G9E1A1_CL3", 1),
    CLOZE("In a planned economy, prices are set by the ____.", ["government", "market", "weather", "tourists"], "government",
      "Government sets prices in a planned economy.", "ERR_EMS_G9E1A1_CL4", 2),
    {
      question: "Sort each feature as 'Planned economy' or 'NOT a planned economy'.",
      input_type: "sort-buckets",
      buckets: [{ id: "planned", label: "Planned economy" }, { id: "not", label: "Not a planned economy" }],
      items: [
        { id: "i1", text: "Government decides what to produce", correct_bucket: "planned" },
        { id: "i2", text: "Prices set freely by supply and demand", correct_bucket: "not" },
        { id: "i3", text: "State owns most businesses", correct_bucket: "planned" },
        { id: "i4", text: "Private firms compete with no government role", correct_bucket: "not" },
      ],
      expected: "Government deciding production and state ownership are planned-economy features; free prices and private competition are not.",
      pass_threshold: 0.75,
      memo: "Planned = government decides and owns; free prices and private competition belong to a market economy.", error_signals: ["ERR_EMS_G9E1A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the flow of decisions in a planned economy in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The government plans what to produce" },
        { id: "b", text: "State-owned businesses produce it" },
        { id: "c", text: "The government sets the prices" },
        { id: "d", text: "Goods are distributed to the people" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Government plans, state produces, government prices, then goods are distributed.",
      error_signals: ["ERR_EMS_G9E1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · The market economy
  "EMS.G9.E1.A2": [
    MC("In a market economy, who mainly decides what is produced?", ["Buyers and sellers through supply and demand", "Only the government", "Only tourists", "No one"], "Buyers and sellers through supply and demand",
      "In a market economy, supply and demand guide what is produced.", "ERR_EMS_G9E1A2_DEF", 1),
    MC("In a market economy, most businesses are owned by ____.", ["private individuals", "the state", "tourists", "no one"], "private individuals",
      "Private individuals own businesses in a market economy.", "ERR_EMS_G9E1A2_PRIVATE", 1),
    MC("In a market economy, prices are mainly set by ____.", ["supply and demand", "the government alone", "the weather", "tourists"], "supply and demand",
      "Prices are determined by supply and demand in a market economy.", "ERR_EMS_G9E1A2_PRICES", 1),
    MC("An advantage of a market economy is ____.", ["consumers have lots of choice and businesses have incentives", "the government controls everything", "there is no competition", "prices never change"], "consumers have lots of choice and businesses have incentives",
      "Market economies offer choice and reward effort and innovation.", "ERR_EMS_G9E1A2_ADV", 2),
    MC("A disadvantage of a market economy is ____.", ["it can leave poorer people behind (inequality)", "everyone is always equal", "there is no choice", "the state owns everything"], "it can leave poorer people behind (inequality)",
      "Market economies can create inequality if some cannot afford goods.", "ERR_EMS_G9E1A2_DIS", 2),
    MC("Competition between businesses in a market economy can ____.", ["improve quality and lower prices", "remove all choice", "raise prices for no reason", "stop production"], "improve quality and lower prices",
      "Competition pushes firms to improve quality and keep prices down.", "ERR_EMS_G9E1A2_COMPETITION", 2),
    MC("In a market economy, what motivates businesses to produce?", ["The chance to earn profit", "Government orders only", "Nothing", "Tourist requests only"], "The chance to earn profit",
      "Profit is the main incentive in a market economy.", "ERR_EMS_G9E1A2_PROFIT", 2),
    MC("A market economy is also sometimes called a ____ economy.", ["free-market", "command", "planned", "state"], "free-market",
      "A market economy is also called a free-market economy.", "ERR_EMS_G9E1A2_FREE", 2),
    MC("Which decision is made by the market, not the government, in a market economy?", ["What goods get produced", "Nothing", "Only the national anthem", "Only the weather"], "What goods get produced",
      "The market decides production through supply and demand.", "ERR_EMS_G9E1A2_DECIDE", 2),
    MC("Why can a pure market economy be unfair to some people?", ["Those with little money may not afford basic goods", "Everyone earns the same", "There is no money", "Goods are always free"], "Those with little money may not afford basic goods",
      "In a pure market economy, low-income people may struggle to afford essentials.", "ERR_EMS_G9E1A2_UNFAIR", 3),
    TF("In a market economy, supply and demand decide what is produced.", "True",
      "Market forces guide production.", "ERR_EMS_G9E1A2_TF1", 1),
    TF("In a market economy, private individuals own most businesses.", "True",
      "Private ownership is a key feature.", "ERR_EMS_G9E1A2_TF2", 1),
    TF("In a market economy, the government sets all prices.", "False",
      "Prices are set by supply and demand, not the government.", "ERR_EMS_G9E1A2_TF3", 1),
    TF("Competition in a market economy can improve quality.", "True",
      "Competing firms tend to raise quality and keep prices down.", "ERR_EMS_G9E1A2_TF4", 2),
    CLOZE("An economy where supply and demand decide production is a ____ economy.", ["market", "planned", "command", "state"], "market",
      "A market economy is led by supply and demand.", "ERR_EMS_G9E1A2_CL1", 1),
    CLOZE("In a market economy, businesses are owned by ____ individuals.", ["private", "state", "foreign", "no"], "private",
      "Private ownership defines a market economy.", "ERR_EMS_G9E1A2_CL2", 1),
    CLOZE("In a market economy, prices are set by supply and ____.", ["demand", "government", "weather", "tourists"], "demand",
      "Supply and demand set prices.", "ERR_EMS_G9E1A2_CL3", 1),
    CLOZE("The main incentive for businesses in a market economy is ____.", ["profit", "loss", "tax", "rent"], "profit",
      "Profit motivates production.", "ERR_EMS_G9E1A2_CL4", 2),
    {
      question: "Sort each feature into 'Market economy' or 'Planned economy'.",
      input_type: "sort-buckets",
      buckets: [{ id: "market", label: "Market economy" }, { id: "planned", label: "Planned economy" }],
      items: [
        { id: "i1", text: "Prices set by supply and demand", correct_bucket: "market" },
        { id: "i2", text: "Government decides what to produce", correct_bucket: "planned" },
        { id: "i3", text: "Private ownership of businesses", correct_bucket: "market" },
        { id: "i4", text: "State owns most resources", correct_bucket: "planned" },
      ],
      expected: "Supply-and-demand prices and private ownership are market features; government decisions and state ownership are planned.",
      pass_threshold: 0.75,
      memo: "Market = private ownership + supply/demand; planned = state ownership + government decisions.", error_signals: ["ERR_EMS_G9E1A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the market-economy process in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Consumers demand certain goods" },
        { id: "b", text: "Private businesses produce them for profit" },
        { id: "c", text: "Supply and demand set the price" },
        { id: "d", text: "Competition pushes quality up and prices down" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Demand → private production for profit → supply/demand set price → competition improves quality.",
      error_signals: ["ERR_EMS_G9E1A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · The mixed economy and global economy
  "EMS.G9.E1.A3": [
    MC("What is a mixed economy?", ["A blend of market freedom and government involvement", "Only government control", "Only private business with no government", "An economy with no money"], "A blend of market freedom and government involvement",
      "A mixed economy combines private enterprise with a government role.", "ERR_EMS_G9E1A3_DEF", 1),
    MC("Most real countries today have a ____ economy.", ["mixed", "purely planned", "purely market", "moneyless"], "mixed",
      "Most countries blend market and government, making them mixed economies.", "ERR_EMS_G9E1A3_MOST", 1),
    MC("In a mixed economy, the government often ____.", ["provides some services and regulates business", "owns absolutely everything", "does nothing at all", "bans all private business"], "provides some services and regulates business",
      "Government provides public services and sets rules while private business operates.", "ERR_EMS_G9E1A3_GOVT", 2),
    MC("South Africa is best described as having a ____ economy.", ["mixed", "purely planned", "purely market", "barter-only"], "mixed",
      "South Africa has a mixed economy.", "ERR_EMS_G9E1A3_SA", 1),
    MC("What is the global economy?", ["The way countries' economies are connected through trade", "One single country's economy", "A type of bank", "A school subject only"], "The way countries' economies are connected through trade",
      "The global economy is the worldwide network of trade between countries.", "ERR_EMS_G9E1A3_GLOBAL", 2),
    MC("Why do countries trade with each other in the global economy?", ["To buy what they lack and sell what they produce well", "To avoid all contact", "Because trade is illegal", "To produce nothing"], "To buy what they lack and sell what they produce well",
      "Countries trade to obtain goods they lack and sell what they produce efficiently.", "ERR_EMS_G9E1A3_WHYTRADE", 2),
    MC("A benefit of a mixed economy is that ____.", ["it combines choice with some protection for the needy", "the state controls every price", "there are no businesses", "there is no government"], "it combines choice with some protection for the needy",
      "A mixed economy keeps market choice while government supports the needy.", "ERR_EMS_G9E1A3_BENEFIT", 2),
    MC("In the global economy, an event in one country can ____.", ["affect economies in other countries", "never affect anyone else", "only affect the weather", "stop all trade forever"], "affect economies in other countries",
      "Because economies are connected, events spread across borders.", "ERR_EMS_G9E1A3_CONNECT", 3),
    MC("Which mixes market and government features?", ["Private shops operate while government runs public hospitals", "The state owns every business", "No government exists at all", "There is no private business"], "Private shops operate while government runs public hospitals",
      "Private business plus government services is a mixed economy.", "ERR_EMS_G9E1A3_MIX_EX", 2),
    MC("Why do most countries choose a mixed economy?", ["To balance the strengths of markets and government", "Because markets always fail", "Because government always fails", "To remove all trade"], "To balance the strengths of markets and government",
      "A mixed economy balances market efficiency with government support.", "ERR_EMS_G9E1A3_WHYMIX", 3),
    TF("A mixed economy combines market freedom with government involvement.", "True",
      "It blends private enterprise and a government role.", "ERR_EMS_G9E1A3_TF1", 1),
    TF("Most countries today have a mixed economy.", "True",
      "Pure planned or pure market economies are rare; most are mixed.", "ERR_EMS_G9E1A3_TF2", 1),
    TF("The global economy means countries' economies are connected through trade.", "True",
      "Global trade links national economies.", "ERR_EMS_G9E1A3_TF3", 1),
    TF("In a mixed economy, the government plays no role at all.", "False",
      "In a mixed economy the government does play a role alongside private business.", "ERR_EMS_G9E1A3_TF4", 1),
    CLOZE("An economy that blends market and government is a ____ economy.", ["mixed", "planned", "command", "barter"], "mixed",
      "A mixed economy blends the two systems.", "ERR_EMS_G9E1A3_CL1", 1),
    CLOZE("South Africa has a ____ economy.", ["mixed", "planned", "command", "moneyless"], "mixed",
      "South Africa's economy is mixed.", "ERR_EMS_G9E1A3_CL2", 1),
    CLOZE("The worldwide network of trade between countries is the ____ economy.", ["global", "local", "planned", "single"], "global",
      "The global economy connects countries through trade.", "ERR_EMS_G9E1A3_CL3", 2),
    CLOZE("In a mixed economy, the government provides some ____ and regulates business.", ["services", "profits", "adverts", "shares"], "services",
      "Government provides public services in a mixed economy.", "ERR_EMS_G9E1A3_CL4", 2),
    {
      question: "Sort each economy by its main feature.",
      input_type: "sort-buckets",
      buckets: [{ id: "planned", label: "Planned" }, { id: "market", label: "Market" }, { id: "mixed", label: "Mixed" }],
      items: [
        { id: "i1", text: "Government decides and owns everything", correct_bucket: "planned" },
        { id: "i2", text: "Supply and demand decide, private ownership", correct_bucket: "market" },
        { id: "i3", text: "Private business plus government services", correct_bucket: "mixed" },
        { id: "i4", text: "Most real countries today", correct_bucket: "mixed" },
      ],
      expected: "Government-controls-all is planned; supply/demand with private ownership is market; a blend (and most countries) is mixed.",
      pass_threshold: 0.75,
      memo: "Planned = all government; market = all private + supply/demand; mixed = a blend (most countries).", error_signals: ["ERR_EMS_G9E1A3_SORT"], difficulty: 3,
    },
    {
      question: "Put these economic systems in order from most government control to least.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Planned (command) economy" },
        { id: "b", text: "Mixed economy with strong government role" },
        { id: "c", text: "Mixed economy with strong market role" },
        { id: "d", text: "Pure market (free-market) economy" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Government control falls from planned, through mixed economies, to a pure market economy.",
      error_signals: ["ERR_EMS_G9E1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── E2 · Term 1 — The circular flow ───────────────────────────────────────
  // A1 · Participants in the circular flow
  "EMS.G9.E2.A1": [
    MC("Who are the two main participants in the circular flow of a closed economy?", ["Households and businesses", "Tourists and banks", "Schools and hospitals", "Shops and the weather"], "Households and businesses",
      "A simple closed economy flows between households and businesses.", "ERR_EMS_G9E2A1_DEF", 1),
    MC("In the circular flow, households provide businesses with ____.", ["factors of production like labour", "free goods", "nothing", "tax only"], "factors of production like labour",
      "Households supply factors of production (e.g. labour) to businesses.", "ERR_EMS_G9E2A1_FACTORS", 2),
    MC("In the circular flow, businesses provide households with ____.", ["goods and services", "nothing", "only tax", "only loans"], "goods and services",
      "Businesses produce goods and services for households.", "ERR_EMS_G9E2A1_GOODS", 1),
    MC("A 'closed economy' is one that ____.", ["does not trade with other countries", "trades with the whole world", "has no people", "uses no money"], "does not trade with other countries",
      "A closed economy has no foreign trade — just households and businesses.", "ERR_EMS_G9E2A1_CLOSED", 2),
    MC("Households earn income by ____.", ["selling their factors of production", "doing nothing", "printing money", "paying businesses"], "selling their factors of production",
      "Households earn income (e.g. wages) by supplying labour and other factors.", "ERR_EMS_G9E2A1_INCOME", 2),
    MC("Businesses earn money when households ____.", ["buy their goods and services", "do nothing", "leave the country", "stop spending"], "buy their goods and services",
      "Household spending on goods and services is income for businesses.", "ERR_EMS_G9E2A1_SPEND", 2),
    MC("Why is it called a 'circular' flow?", ["Money and resources move in a continuous loop", "It is shaped like a square", "It only goes one way once", "It never moves"], "Money and resources move in a continuous loop",
      "Money, goods and factors circulate continuously between participants.", "ERR_EMS_G9E2A1_CIRCULAR", 2),
    MC("In a simple closed economy, households and businesses ____.", ["depend on each other", "never interact", "are the same thing", "ignore each other"], "depend on each other",
      "They rely on each other — one supplies labour, the other goods.", "ERR_EMS_G9E2A1_DEPEND", 1),
    MC("Which is an example of a household participating in the flow?", ["A worker earning wages and buying goods", "A factory paying tax abroad", "A tourist visiting", "A foreign exporter"], "A worker earning wages and buying goods",
      "A worker supplying labour and spending wages is a household in the flow.", "ERR_EMS_G9E2A1_EX", 2),
    MC("In a closed economy, there is no ____.", ["foreign trade", "household", "business", "money"], "foreign trade",
      "A closed economy excludes foreign trade.", "ERR_EMS_G9E2A1_NOFOREIGN", 2),
    TF("Households and businesses are the main participants in a closed economy's circular flow.", "True",
      "The simple flow is between households and businesses.", "ERR_EMS_G9E2A1_TF1", 1),
    TF("Households supply factors of production like labour to businesses.", "True",
      "Households provide labour and other factors.", "ERR_EMS_G9E2A1_TF2", 1),
    TF("A closed economy trades freely with other countries.", "False",
      "A closed economy has no foreign trade.", "ERR_EMS_G9E2A1_TF3", 1),
    TF("Businesses provide households with goods and services.", "True",
      "Businesses produce goods and services for households.", "ERR_EMS_G9E2A1_TF4", 1),
    CLOZE("The two main participants in a closed economy are households and ____.", ["businesses", "tourists", "banks", "schools"], "businesses",
      "Households and businesses are the participants.", "ERR_EMS_G9E2A1_CL1", 1),
    CLOZE("Households supply ____ of production, like labour, to businesses.", ["factors", "goods", "taxes", "adverts"], "factors",
      "Households supply factors of production.", "ERR_EMS_G9E2A1_CL2", 2),
    CLOZE("An economy with no foreign trade is a ____ economy.", ["closed", "open", "global", "mixed"], "closed",
      "A closed economy has no foreign trade.", "ERR_EMS_G9E2A1_CL3", 2),
    CLOZE("Businesses provide households with goods and ____.", ["services", "taxes", "loans", "adverts"], "services",
      "Businesses provide goods and services.", "ERR_EMS_G9E2A1_CL4", 1),
    {
      question: "Sort each role under 'Households' or 'Businesses'.",
      input_type: "sort-buckets",
      buckets: [{ id: "households", label: "Households" }, { id: "businesses", label: "Businesses" }],
      items: [
        { id: "i1", text: "Supply labour", correct_bucket: "households" },
        { id: "i2", text: "Produce goods and services", correct_bucket: "businesses" },
        { id: "i3", text: "Buy goods and services", correct_bucket: "households" },
        { id: "i4", text: "Pay wages for labour", correct_bucket: "businesses" },
      ],
      expected: "Households supply labour and buy goods; businesses produce goods and pay wages.",
      pass_threshold: 0.75,
      memo: "Households supply factors and consume; businesses produce and pay for factors.", error_signals: ["ERR_EMS_G9E2A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the circular flow between households and businesses in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Households supply labour to businesses" },
        { id: "b", text: "Businesses pay wages to households" },
        { id: "c", text: "Households spend wages on goods and services" },
        { id: "d", text: "Businesses receive that money as income" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Labour → wages → spending → business income — a continuous loop.",
      error_signals: ["ERR_EMS_G9E2A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Flows of money, goods and factors  (diagram items deferred via image flag)
  "EMS.G9.E2.A2": [
    MC("In the circular flow, money flows in ____ to goods and factors.", ["the opposite direction", "the same direction", "no direction", "a straight line only"], "the opposite direction",
      "Money flows one way while goods and factors flow the other — opposite directions.", "ERR_EMS_G9E2A2_OPPOSITE", 2),
    MC("Wages flowing from businesses to households are a flow of ____.", ["money", "goods", "factors", "tax"], "money",
      "Wages are a money flow from businesses to households.", "ERR_EMS_G9E2A2_WAGES", 1),
    MC("Labour flowing from households to businesses is a flow of ____.", ["a factor of production", "money", "goods", "tax"], "a factor of production",
      "Labour is a factor of production flowing to businesses.", "ERR_EMS_G9E2A2_LABOUR", 2),
    MC("Goods and services flow from ____ to ____.", ["businesses; households", "households; businesses", "banks; tourists", "schools; shops"], "businesses; households",
      "Businesses produce goods and services that flow to households.", "ERR_EMS_G9E2A2_GOODS", 1),
    MC("Spending by households on goods is a flow of ____ to businesses.", ["money", "labour", "factors", "goods"], "money",
      "Household spending is a money flow to businesses.", "ERR_EMS_G9E2A2_SPEND", 2),
    MC("The circular-flow diagram shows ____.", ["the two-way flows of money, goods and factors", "only one arrow", "the weather", "a shopping list"], "the two-way flows of money, goods and factors",
      "The diagram shows money flowing one way and goods/factors the other.", "ERR_EMS_G9E2A2_DIAGRAM", 2),
    MC("Which is a 'real' flow (not money)?", ["Labour and goods", "Wages and spending", "Cash payments", "Bank transfers"], "Labour and goods",
      "Real flows are goods and factors (like labour); money flows are the opposite.", "ERR_EMS_G9E2A2_REAL", 3),
    MC("Which is a money flow?", ["Wages and consumer spending", "Labour and goods", "Factors of production", "Raw materials"], "Wages and consumer spending",
      "Wages and spending are money flows.", "ERR_EMS_G9E2A2_MONEY", 2),
    MC("Why must the flows balance in a closed economy?", ["What households spend becomes business income, and wages return to households", "Because money disappears", "There is no reason", "Because goods vanish"], "What households spend becomes business income, and wages return to households",
      "Money circulates: spending becomes income, wages become spending — it loops.", "ERR_EMS_G9E2A2_BALANCE", 3),
    MC("The flows are drawn as arrows going in ____ around the loop.", ["two opposite directions", "one direction only", "no direction", "random directions"], "two opposite directions",
      "Money goes one way; goods and factors go the other.", "ERR_EMS_G9E2A2_ARROWS", 2),
    TF("Money flows in the opposite direction to goods and factors in the circular flow.", "True",
      "Money flows one way; goods and factors flow the other.", "ERR_EMS_G9E2A2_TF1", 1),
    TF("Wages are a money flow from businesses to households.", "True",
      "Businesses pay wages (money) to households.", "ERR_EMS_G9E2A2_TF2", 1),
    TF("Goods and services flow from households to businesses.", "False",
      "Goods and services flow from businesses to households.", "ERR_EMS_G9E2A2_TF3", 1),
    TF("Household spending is a money flow to businesses.", "True",
      "Spending sends money from households to businesses.", "ERR_EMS_G9E2A2_TF4", 1),
    CLOZE("Money flows in the ____ direction to goods and factors.", ["opposite", "same", "no", "random"], "opposite",
      "Money flows opposite to goods and factors.", "ERR_EMS_G9E2A2_CL1", 2),
    CLOZE("Wages are a flow of ____ from businesses to households.", ["money", "labour", "goods", "tax"], "money",
      "Wages are a money flow.", "ERR_EMS_G9E2A2_CL2", 1),
    CLOZE("Labour is a ____ flowing from households to businesses.", ["factor", "money", "good", "tax"], "factor",
      "Labour is a factor of production.", "ERR_EMS_G9E2A2_CL3", 2),
    CLOZE("Goods and services flow from businesses to ____.", ["households", "banks", "tourists", "schools"], "households",
      "Goods flow to households.", "ERR_EMS_G9E2A2_CL4", 1),
    {
      question: "Sort each flow into 'Money flow' or 'Real flow (goods/factors)'.",
      input_type: "sort-buckets",
      buckets: [{ id: "money", label: "Money flow" }, { id: "real", label: "Real flow (goods/factors)" }],
      items: [
        { id: "i1", text: "Wages paid to workers", correct_bucket: "money" },
        { id: "i2", text: "Labour supplied to a business", correct_bucket: "real" },
        { id: "i3", text: "Household spending on goods", correct_bucket: "money" },
        { id: "i4", text: "Goods delivered to households", correct_bucket: "real" },
      ],
      expected: "Wages and spending are money flows; labour and goods are real flows.",
      pass_threshold: 0.75,
      memo: "Money flows = wages and spending; real flows = labour and goods (the opposite direction).", error_signals: ["ERR_EMS_G9E2A2_SORT"], difficulty: 3,
    },
    {
      question: "Put one loop of money around the circular flow in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Business pays wages (money) to a household" },
        { id: "b", text: "The household spends the money on goods" },
        { id: "c", text: "The money becomes the business's income" },
        { id: "d", text: "The business uses it to pay wages again" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Wages → spending → business income → wages again — money loops continuously.",
      error_signals: ["ERR_EMS_G9E2A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── E3 · Term 2 — Price theory (diagram items deferred via image flag) ─────
  // A1 · The law of demand
  "EMS.G9.E3.A1": [
    MC("What does the law of demand say?", ["When the price rises, the quantity demanded usually falls", "When price rises, demand rises", "Price never affects demand", "Demand is always zero"], "When the price rises, the quantity demanded usually falls",
      "Higher prices generally reduce the quantity consumers want to buy.", "ERR_EMS_G9E3A1_DEF", 1),
    MC("If the price of a good falls, the quantity demanded usually ____.", ["rises", "falls", "stays exactly the same", "becomes zero"], "rises",
      "Lower prices usually increase the quantity demanded.", "ERR_EMS_G9E3A1_FALL", 1),
    MC("A demand schedule is ____.", ["a table of prices and the quantities demanded", "a type of advert", "a bank statement", "a wage slip"], "a table of prices and the quantities demanded",
      "A demand schedule lists quantities demanded at different prices.", "ERR_EMS_G9E3A1_SCHEDULE", 2),
    MC("The demand curve usually slopes ____.", ["downwards from left to right", "upwards from left to right", "straight up", "in a circle"], "downwards from left to right",
      "Because higher prices mean lower quantity demanded, the curve slopes down.", "ERR_EMS_G9E3A1_CURVE", 2),
    MC("At a higher price, consumers generally buy ____.", ["less", "more", "the same", "nothing ever"], "less",
      "Higher prices reduce the quantity demanded.", "ERR_EMS_G9E3A1_HIGHER", 1),
    MC("Which is an example of the law of demand?", ["A shop drops its price and sells more units", "A shop raises its price and sells more", "Price changes never affect sales", "Sales are always fixed"], "A shop drops its price and sells more units",
      "Lower price → more units sold illustrates the law of demand.", "ERR_EMS_G9E3A1_EX", 2),
    MC("'Quantity demanded' means ____.", ["how much consumers will buy at a given price", "how much is produced", "the cost to make a good", "the tax on a good"], "how much consumers will buy at a given price",
      "Quantity demanded is how much consumers buy at a particular price.", "ERR_EMS_G9E3A1_QD", 2),
    MC("Why do consumers buy less when prices rise?", ["Goods become less affordable", "Goods become free", "They have more money", "Prices do not matter"], "Goods become less affordable",
      "Higher prices make goods less affordable, lowering quantity demanded.", "ERR_EMS_G9E3A1_WHY", 2),
    MC("On a demand graph, price is usually on the ____ axis.", ["vertical (up-down)", "diagonal", "no", "circular"], "vertical (up-down)",
      "Price is plotted on the vertical axis, quantity on the horizontal.", "ERR_EMS_G9E3A1_AXIS", 3),
    MC("Which statement matches the law of demand?", ["Price up → quantity demanded down; price down → quantity demanded up", "Price up → demand up", "Price has no effect", "Demand is always the same"], "Price up → quantity demanded down; price down → quantity demanded up",
      "Price and quantity demanded move in opposite directions.", "ERR_EMS_G9E3A1_MATCH", 2),
    TF("According to the law of demand, higher prices usually mean lower quantity demanded.", "True",
      "Price and quantity demanded move in opposite directions.", "ERR_EMS_G9E3A1_TF1", 1),
    TF("A demand schedule is a table of prices and quantities demanded.", "True",
      "It lists quantity demanded at each price.", "ERR_EMS_G9E3A1_TF2", 1),
    TF("The demand curve usually slopes upwards.", "False",
      "The demand curve slopes downwards (higher price, lower quantity).", "ERR_EMS_G9E3A1_TF3", 1),
    TF("Lower prices usually increase the quantity demanded.", "True",
      "Cheaper goods are bought in greater quantity.", "ERR_EMS_G9E3A1_TF4", 1),
    CLOZE("The law of demand says higher prices lead to ____ quantity demanded.", ["lower", "higher", "the same", "no"], "lower",
      "Higher price → lower quantity demanded.", "ERR_EMS_G9E3A1_CL1", 1),
    CLOZE("A table of prices and quantities demanded is a demand ____.", ["schedule", "advert", "receipt", "wage"], "schedule",
      "A demand schedule is such a table.", "ERR_EMS_G9E3A1_CL2", 2),
    CLOZE("The demand curve slopes ____.", ["downwards", "upwards", "vertically", "in a circle"], "downwards",
      "The demand curve slopes down.", "ERR_EMS_G9E3A1_CL3", 2),
    CLOZE("When price falls, quantity demanded usually ____.", ["rises", "falls", "vanishes", "freezes"], "rises",
      "Lower price → higher quantity demanded.", "ERR_EMS_G9E3A1_CL4", 1),
    {
      question: "Sort each into 'Increases quantity demanded' or 'Decreases quantity demanded'.",
      input_type: "sort-buckets",
      buckets: [{ id: "up", label: "Increases quantity demanded" }, { id: "down", label: "Decreases quantity demanded" }],
      items: [
        { id: "i1", text: "The price drops", correct_bucket: "up" },
        { id: "i2", text: "The price rises", correct_bucket: "down" },
        { id: "i3", text: "A sale lowers the price", correct_bucket: "up" },
        { id: "i4", text: "The price is doubled", correct_bucket: "down" },
      ],
      expected: "Lower prices raise quantity demanded; higher prices lower it.",
      pass_threshold: 0.75,
      memo: "Law of demand: lower price → more demanded; higher price → less demanded.", error_signals: ["ERR_EMS_G9E3A1_SORT"], difficulty: 2,
    },
    {
      question: "Put this demand example in order (a shop running a sale).",
      input_type: "sequence",
      items: [
        { id: "a", text: "A shop lowers the price of a drink" },
        { id: "b", text: "The drink becomes more affordable" },
        { id: "c", text: "More customers want to buy it" },
        { id: "d", text: "Quantity demanded rises" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Lower price → more affordable → more buyers → quantity demanded rises.",
      error_signals: ["ERR_EMS_G9E3A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · The law of supply
  "EMS.G9.E3.A2": [
    MC("What does the law of supply say?", ["When the price rises, the quantity supplied usually rises", "When price rises, supply falls", "Price never affects supply", "Supply is always zero"], "When the price rises, the quantity supplied usually rises",
      "Higher prices encourage producers to supply more.", "ERR_EMS_G9E3A2_DEF", 1),
    MC("If the price of a good falls, the quantity supplied usually ____.", ["falls", "rises", "stays the same", "doubles"], "falls",
      "Lower prices usually reduce the quantity producers supply.", "ERR_EMS_G9E3A2_FALL", 1),
    MC("A supply schedule is ____.", ["a table of prices and quantities supplied", "an advert", "a bank loan", "a wage slip"], "a table of prices and quantities supplied",
      "A supply schedule lists quantities supplied at different prices.", "ERR_EMS_G9E3A2_SCHEDULE", 2),
    MC("The supply curve usually slopes ____.", ["upwards from left to right", "downwards from left to right", "in a circle", "straight down"], "upwards from left to right",
      "Higher prices → more supplied, so the supply curve slopes up.", "ERR_EMS_G9E3A2_CURVE", 2),
    MC("Why do producers supply more when prices rise?", ["Higher prices mean more profit, so they produce more", "They earn less", "Prices do not matter", "They produce nothing"], "Higher prices mean more profit, so they produce more",
      "Higher prices raise potential profit, encouraging more production.", "ERR_EMS_G9E3A2_WHY", 2),
    MC("Which is an example of the law of supply?", ["Prices rise, so a farmer plants more crops to sell", "Prices rise, so a farmer plants less", "Price never affects planting", "Farmers plant nothing"], "Prices rise, so a farmer plants more crops to sell",
      "Higher prices encourage producing more — the law of supply.", "ERR_EMS_G9E3A2_EX", 2),
    MC("'Quantity supplied' means ____.", ["how much producers will offer at a given price", "how much consumers buy", "the tax on a good", "the advert cost"], "how much producers will offer at a given price",
      "Quantity supplied is how much producers offer at a price.", "ERR_EMS_G9E3A2_QS", 2),
    MC("At a lower price, producers generally supply ____.", ["less", "more", "the same", "unlimited"], "less",
      "Lower prices reduce the quantity supplied.", "ERR_EMS_G9E3A2_LOWER", 1),
    MC("Which statement matches the law of supply?", ["Price up → quantity supplied up; price down → quantity supplied down", "Price up → supply down", "Price has no effect on supply", "Supply is always fixed"], "Price up → quantity supplied up; price down → quantity supplied down",
      "Price and quantity supplied move in the same direction.", "ERR_EMS_G9E3A2_MATCH", 2),
    MC("Demand and supply curves slope in ____ directions.", ["opposite", "the same", "no", "circular"], "opposite",
      "Demand slopes down; supply slopes up — opposite directions.", "ERR_EMS_G9E3A2_OPPOSITE", 3),
    TF("According to the law of supply, higher prices usually mean a higher quantity supplied.", "True",
      "Price and quantity supplied move in the same direction.", "ERR_EMS_G9E3A2_TF1", 1),
    TF("A supply schedule is a table of prices and quantities supplied.", "True",
      "It lists quantity supplied at each price.", "ERR_EMS_G9E3A2_TF2", 1),
    TF("The supply curve usually slopes downwards.", "False",
      "The supply curve slopes upwards (higher price, more supplied).", "ERR_EMS_G9E3A2_TF3", 1),
    TF("Producers usually supply more when they can earn a higher price.", "True",
      "Higher prices encourage more production.", "ERR_EMS_G9E3A2_TF4", 1),
    CLOZE("The law of supply says higher prices lead to ____ quantity supplied.", ["higher", "lower", "no", "the same"], "higher",
      "Higher price → higher quantity supplied.", "ERR_EMS_G9E3A2_CL1", 1),
    CLOZE("A table of prices and quantities supplied is a supply ____.", ["schedule", "advert", "receipt", "wage"], "schedule",
      "A supply schedule lists quantity supplied at each price.", "ERR_EMS_G9E3A2_CL2", 2),
    CLOZE("The supply curve slopes ____.", ["upwards", "downwards", "vertically", "in a circle"], "upwards",
      "The supply curve slopes up.", "ERR_EMS_G9E3A2_CL3", 2),
    CLOZE("When price rises, quantity supplied usually ____.", ["rises", "falls", "vanishes", "freezes"], "rises",
      "Higher price → more supplied.", "ERR_EMS_G9E3A2_CL4", 1),
    {
      question: "Sort each into 'Increases quantity supplied' or 'Decreases quantity supplied'.",
      input_type: "sort-buckets",
      buckets: [{ id: "up", label: "Increases quantity supplied" }, { id: "down", label: "Decreases quantity supplied" }],
      items: [
        { id: "i1", text: "The price rises", correct_bucket: "up" },
        { id: "i2", text: "The price falls", correct_bucket: "down" },
        { id: "i3", text: "Producers can earn more per unit", correct_bucket: "up" },
        { id: "i4", text: "The selling price drops sharply", correct_bucket: "down" },
      ],
      expected: "Higher prices raise quantity supplied; lower prices reduce it.",
      pass_threshold: 0.75,
      memo: "Law of supply: higher price → more supplied; lower price → less supplied.", error_signals: ["ERR_EMS_G9E3A2_SORT"], difficulty: 2,
    },
    {
      question: "Put this supply example in order (rising prices).",
      input_type: "sequence",
      items: [
        { id: "a", text: "The market price of tomatoes rises" },
        { id: "b", text: "Selling tomatoes becomes more profitable" },
        { id: "c", text: "Farmers plant and supply more" },
        { id: "d", text: "Quantity supplied rises" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Higher price → more profit → more produced → quantity supplied rises.",
      error_signals: ["ERR_EMS_G9E3A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Equilibrium and shifts
  "EMS.G9.E3.A3": [
    MC("What is the equilibrium price?", ["The price where quantity demanded equals quantity supplied", "The highest possible price", "The lowest possible price", "A price set by government"], "The price where quantity demanded equals quantity supplied",
      "Equilibrium is where demand and supply are equal.", "ERR_EMS_G9E3A3_DEF", 1),
    MC("At equilibrium, the demand and supply curves ____.", ["cross (intersect)", "never meet", "are parallel", "disappear"], "cross (intersect)",
      "Equilibrium is the point where the two curves cross.", "ERR_EMS_G9E3A3_CROSS", 2),
    MC("If demand increases (more people want a good), the price tends to ____.", ["rise", "fall", "vanish", "stay fixed forever"], "rise",
      "More demand usually pushes the price up.", "ERR_EMS_G9E3A3_DEMUP", 2),
    MC("If supply increases (more is available), the price tends to ____.", ["fall", "rise", "vanish", "stay fixed forever"], "fall",
      "More supply usually pushes the price down.", "ERR_EMS_G9E3A3_SUPUP", 2),
    MC("A 'change in quantity demanded' is caused by ____.", ["a change in the good's own price", "a new advert only", "the weather only", "nothing"], "a change in the good's own price",
      "Quantity demanded changes when the good's own price changes.", "ERR_EMS_G9E3A3_QD", 3),
    MC("If demand falls while supply stays the same, price tends to ____.", ["fall", "rise", "double", "stay forever"], "fall",
      "Less demand with steady supply pushes price down.", "ERR_EMS_G9E3A3_DEMDOWN", 2),
    MC("If supply falls (e.g. a drought) while demand stays the same, price tends to ____.", ["rise", "fall", "vanish", "stay fixed"], "rise",
      "Less supply with steady demand pushes price up.", "ERR_EMS_G9E3A3_SUPDOWN", 2),
    MC("Equilibrium is important because ____.", ["it is where the market 'clears' with no shortage or surplus", "it always means high prices", "it removes all trade", "it has no meaning"], "it is where the market 'clears' with no shortage or surplus",
      "At equilibrium there is no shortage or surplus — the market clears.", "ERR_EMS_G9E3A3_WHY", 3),
    MC("If the price is above equilibrium, there is usually a ____.", ["surplus (too much supply)", "shortage", "perfect balance", "no effect"], "surplus (too much supply)",
      "Above equilibrium, supply exceeds demand — a surplus.", "ERR_EMS_G9E3A3_SURPLUS", 3),
    MC("If the price is below equilibrium, there is usually a ____.", ["shortage (too little supply)", "surplus", "perfect balance", "no effect"], "shortage (too little supply)",
      "Below equilibrium, demand exceeds supply — a shortage.", "ERR_EMS_G9E3A3_SHORTAGE", 3),
    TF("Equilibrium is where quantity demanded equals quantity supplied.", "True",
      "It is the balance point of demand and supply.", "ERR_EMS_G9E3A3_TF1", 1),
    TF("At equilibrium the demand and supply curves cross.", "True",
      "Equilibrium is the intersection of the curves.", "ERR_EMS_G9E3A3_TF2", 1),
    TF("An increase in demand tends to lower the price.", "False",
      "An increase in demand tends to raise the price.", "ERR_EMS_G9E3A3_TF3", 1),
    TF("An increase in supply tends to lower the price.", "True",
      "More supply pushes the price down.", "ERR_EMS_G9E3A3_TF4", 2),
    CLOZE("The price where demand equals supply is the ____ price.", ["equilibrium", "highest", "lowest", "government"], "equilibrium",
      "Equilibrium price balances demand and supply.", "ERR_EMS_G9E3A3_CL1", 1),
    CLOZE("At equilibrium, the demand and supply curves ____.", ["cross", "vanish", "separate", "flip"], "cross",
      "The curves intersect at equilibrium.", "ERR_EMS_G9E3A3_CL2", 2),
    CLOZE("An increase in demand tends to make the price ____.", ["rise", "fall", "vanish", "freeze"], "rise",
      "More demand raises price.", "ERR_EMS_G9E3A3_CL3", 2),
    CLOZE("An increase in supply tends to make the price ____.", ["fall", "rise", "vanish", "freeze"], "fall",
      "More supply lowers price.", "ERR_EMS_G9E3A3_CL4", 2),
    {
      question: "Sort each change by its usual effect on the equilibrium price.",
      input_type: "sort-buckets",
      buckets: [{ id: "up", label: "Price tends to rise" }, { id: "down", label: "Price tends to fall" }],
      items: [
        { id: "i1", text: "Demand increases", correct_bucket: "up" },
        { id: "i2", text: "Supply increases", correct_bucket: "down" },
        { id: "i3", text: "A drought cuts supply", correct_bucket: "up" },
        { id: "i4", text: "Demand falls", correct_bucket: "down" },
      ],
      expected: "More demand or less supply raises price; more supply or less demand lowers it.",
      pass_threshold: 0.75,
      memo: "Price up: demand↑ or supply↓. Price down: supply↑ or demand↓.", error_signals: ["ERR_EMS_G9E3A3_SORT"], difficulty: 3,
    },
    {
      question: "Put the path to a new higher equilibrium price in order (demand rises).",
      input_type: "sequence",
      items: [
        { id: "a", text: "More consumers want the good (demand increases)" },
        { id: "b", text: "At the old price there is now a shortage" },
        { id: "c", text: "The price is bid upward" },
        { id: "d", text: "A new, higher equilibrium price is reached" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Demand rises → shortage at old price → price rises → new equilibrium.",
      error_signals: ["ERR_EMS_G9E3A3_SEQ"], difficulty: 3,
    },
  ],

  // ─── E4 · Term 3 — Trade unions ────────────────────────────────────────────
  // A1 · What trade unions are
  "EMS.G9.E4.A1": [
    MC("What is a trade union?", ["An organisation of workers who join together to protect their interests", "A type of business that sells goods", "A government department", "A bank"], "An organisation of workers who join together to protect their interests",
      "A trade union is workers organised together to protect and advance their interests.", "ERR_EMS_G9E4A1_DEF", 1),
    MC("Workers join a trade union mainly to ____.", ["bargain together for better wages and conditions", "pay more tax", "avoid all work", "compete with each other"], "bargain together for better wages and conditions",
      "Unions let workers bargain collectively for better pay and conditions.", "ERR_EMS_G9E4A1_WHY", 1),
    MC("'Collective bargaining' means ____.", ["workers negotiating as a group with employers", "each worker bargaining alone", "employers deciding everything", "no negotiation at all"], "workers negotiating as a group with employers",
      "Collective bargaining is group negotiation between workers and employers.", "ERR_EMS_G9E4A1_BARGAIN", 2),
    MC("Trade unions developed historically because ____.", ["individual workers had little power against employers", "workers had too much power", "there were no employers", "wages were always fair"], "individual workers had little power against employers",
      "Unions grew so workers could gain bargaining power together.", "ERR_EMS_G9E4A1_HISTORY", 2),
    MC("A trade union represents ____.", ["its worker members", "only the employer", "only the government", "only customers"], "its worker members",
      "A union represents the interests of its worker members.", "ERR_EMS_G9E4A1_REP", 1),
    MC("Which is something a trade union might negotiate?", ["Higher wages and safer conditions", "Lower wages for members", "Worse safety", "Fewer rights"], "Higher wages and safer conditions",
      "Unions negotiate for better pay and safer working conditions.", "ERR_EMS_G9E4A1_NEGOTIATE", 2),
    MC("Why is there 'strength in numbers' for a union?", ["Many workers together have more bargaining power than one alone", "One worker is stronger than many", "Numbers do not matter", "Employers prefer it"], "Many workers together have more bargaining power than one alone",
      "A united group has far more bargaining power than a single worker.", "ERR_EMS_G9E4A1_STRENGTH", 2),
    MC("A union member pays ____ to belong to the union.", ["membership fees (subscriptions)", "nothing ever", "tax to the union", "rent"], "membership fees (subscriptions)",
      "Members usually pay subscriptions to fund the union.", "ERR_EMS_G9E4A1_FEES", 2),
    MC("Which best describes a trade union?", ["A group of workers acting together for shared interests", "A single employer", "A shop selling goods", "A type of tax"], "A group of workers acting together for shared interests",
      "A union is workers organised for their shared interests.", "ERR_EMS_G9E4A1_CORRECT", 1),
    MC("Historically, unions helped workers gain ____.", ["rights like fair pay and safer workplaces", "fewer rights", "lower pay", "no voice"], "rights like fair pay and safer workplaces",
      "Unions historically won better pay, conditions and rights.", "ERR_EMS_G9E4A1_GAINS", 2),
    TF("A trade union is an organisation of workers protecting their interests.", "True",
      "Unions organise workers to protect their interests.", "ERR_EMS_G9E4A1_TF1", 1),
    TF("Collective bargaining means workers negotiate as a group.", "True",
      "It is group negotiation with employers.", "ERR_EMS_G9E4A1_TF2", 1),
    TF("Trade unions represent employers, not workers.", "False",
      "Trade unions represent workers, not employers.", "ERR_EMS_G9E4A1_TF3", 1),
    TF("Workers have more bargaining power together than alone.", "True",
      "There is strength in numbers in bargaining.", "ERR_EMS_G9E4A1_TF4", 1),
    CLOZE("An organisation of workers protecting their interests is a trade ____.", ["union", "shop", "bank", "tax"], "union",
      "A trade union organises workers.", "ERR_EMS_G9E4A1_CL1", 1),
    CLOZE("Workers negotiating together as a group is called ____ bargaining.", ["collective", "single", "private", "secret"], "collective",
      "Collective bargaining is group negotiation.", "ERR_EMS_G9E4A1_CL2", 2),
    CLOZE("A trade union represents its worker ____.", ["members", "owners", "customers", "suppliers"], "members",
      "Unions represent their members.", "ERR_EMS_G9E4A1_CL3", 1),
    CLOZE("Members usually pay ____ to belong to a union.", ["fees", "tax", "rent", "interest"], "fees",
      "Members pay subscription fees.", "ERR_EMS_G9E4A1_CL4", 2),
    {
      question: "Sort each statement as 'True of trade unions' or 'False of trade unions'.",
      input_type: "sort-buckets",
      buckets: [{ id: "true", label: "True of trade unions" }, { id: "false", label: "False of trade unions" }],
      items: [
        { id: "i1", text: "They represent workers", correct_bucket: "true" },
        { id: "i2", text: "They are owned by employers", correct_bucket: "false" },
        { id: "i3", text: "They use collective bargaining", correct_bucket: "true" },
        { id: "i4", text: "They aim to lower their members' wages", correct_bucket: "false" },
      ],
      expected: "Unions represent workers and bargain collectively; they are not employer-owned and do not aim to cut members' wages.",
      pass_threshold: 0.75,
      memo: "Unions = worker-led, collective bargaining, better pay/conditions.", error_signals: ["ERR_EMS_G9E4A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of forming and using a trade union in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Workers realise they have little power alone" },
        { id: "b", text: "They join together to form a union" },
        { id: "c", text: "The union bargains collectively with the employer" },
        { id: "d", text: "Workers gain better pay or conditions" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Alone they're weak → unite → bargain collectively → win better pay/conditions.",
      error_signals: ["ERR_EMS_G9E4A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · The role of trade unions
  "EMS.G9.E4.A2": [
    MC("Which is a role of a trade union?", ["Negotiating wages and working conditions for members", "Setting all of a country's tax", "Selling goods to the public", "Running the army"], "Negotiating wages and working conditions for members",
      "Unions negotiate pay and conditions on behalf of members.", "ERR_EMS_G9E4A2_ROLE", 1),
    MC("A 'strike' is when workers ____.", ["stop working to push for their demands", "work extra hours for free", "buy more goods", "pay more tax"], "stop working to push for their demands",
      "A strike is a work stoppage used to press demands.", "ERR_EMS_G9E4A2_STRIKE", 1),
    MC("How can trade unions affect businesses?", ["They can raise wage costs but also improve worker relations", "They have no effect at all", "They always close businesses", "They only sell products"], "They can raise wage costs but also improve worker relations",
      "Unions can increase wage costs but also improve cooperation and morale.", "ERR_EMS_G9E4A2_BUSINESS", 2),
    MC("A responsibility of a trade union is to ____.", ["act lawfully and in members' genuine interests", "break all laws", "ignore members", "harm the economy on purpose"], "act lawfully and in members' genuine interests",
      "Unions should act lawfully and truly serve members' interests.", "ERR_EMS_G9E4A2_RESP", 2),
    MC("How can trade unions contribute to sustainable growth?", ["By promoting fair pay and stable, productive workplaces", "By stopping all work forever", "By harming productivity always", "By removing all jobs"], "By promoting fair pay and stable, productive workplaces",
      "Fair pay and stable workplaces can support productivity and growth.", "ERR_EMS_G9E4A2_GROWTH", 2),
    MC("A possible downside of frequent strikes is ____.", ["lost production and income", "higher production", "more profit always", "no effect"], "lost production and income",
      "Strikes can cause lost production and income for firms and workers.", "ERR_EMS_G9E4A2_DOWNSIDE", 2),
    MC("Trade unions in South Africa are part of ____.", ["the country's labour relations system", "the school system only", "the tax court", "the weather service"], "the country's labour relations system",
      "Unions are part of South Africa's labour relations framework.", "ERR_EMS_G9E4A2_SA", 2),
    MC("Which is a benefit unions can bring workers?", ["Safer working conditions", "Lower wages", "Fewer rights", "Less safety"], "Safer working conditions",
      "Unions push for safer conditions and better treatment.", "ERR_EMS_G9E4A2_BENEFIT", 1),
    MC("How might a union and employer reach agreement without a strike?", ["Through negotiation and compromise", "By refusing to talk", "By ignoring each other", "Only by force"], "Through negotiation and compromise",
      "Negotiation and compromise can settle disputes without strikes.", "ERR_EMS_G9E4A2_NEGOTIATE", 2),
    MC("Why must unions balance demands with the health of the business?", ["If a business fails, members lose their jobs", "Businesses can never fail", "Members want the business to close", "There is no link"], "If a business fails, members lose their jobs",
      "Demands that sink a business cost members their jobs, so balance matters.", "ERR_EMS_G9E4A2_BALANCE", 3),
    TF("Trade unions negotiate wages and conditions for their members.", "True",
      "Negotiating pay and conditions is a core union role.", "ERR_EMS_G9E4A2_TF1", 1),
    TF("A strike is when workers stop working to push for demands.", "True",
      "Strikes are work stoppages used to press demands.", "ERR_EMS_G9E4A2_TF2", 1),
    TF("Trade unions can affect businesses' wage costs.", "True",
      "Union-negotiated wages can raise a business's costs.", "ERR_EMS_G9E4A2_TF3", 1),
    TF("Frequent strikes have no effect on production.", "False",
      "Strikes can cause significant lost production and income.", "ERR_EMS_G9E4A2_TF4", 1),
    CLOZE("Unions negotiate ____ and working conditions for members.", ["wages", "taxes", "adverts", "rent"], "wages",
      "Unions negotiate wages and conditions.", "ERR_EMS_G9E4A2_CL1", 1),
    CLOZE("A work stoppage to push for demands is a ____.", ["strike", "sale", "loan", "budget"], "strike",
      "A strike is a work stoppage.", "ERR_EMS_G9E4A2_CL2", 1),
    CLOZE("Fair pay and stable workplaces can support sustainable ____.", ["growth", "loss", "tax", "debt"], "growth",
      "These can support sustainable growth.", "ERR_EMS_G9E4A2_CL3", 2),
    CLOZE("Unions should act ____ and in members' genuine interests.", ["lawfully", "secretly", "harmfully", "carelessly"], "lawfully",
      "Unions should act lawfully and responsibly.", "ERR_EMS_G9E4A2_CL4", 2),
    {
      question: "Sort each effect of trade unions into 'Positive' or 'Negative' for the economy/business.",
      input_type: "sort-buckets",
      buckets: [{ id: "positive", label: "Positive effect" }, { id: "negative", label: "Negative effect" }],
      items: [
        { id: "i1", text: "Safer working conditions", correct_bucket: "positive" },
        { id: "i2", text: "Lost production during a long strike", correct_bucket: "negative" },
        { id: "i3", text: "Fairer wages and better morale", correct_bucket: "positive" },
        { id: "i4", text: "Higher wage costs that may reduce profit", correct_bucket: "negative" },
      ],
      expected: "Safer conditions and fairer wages are positive; lost production and higher costs are negative.",
      pass_threshold: 0.75,
      memo: "Unions bring benefits (safety, fair pay) and costs (strikes, higher wage costs).", error_signals: ["ERR_EMS_G9E4A2_SORT"], difficulty: 3,
    },
    {
      question: "Put a wage negotiation that avoids a strike in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The union presents its wage demand" },
        { id: "b", text: "The employer makes a counter-offer" },
        { id: "c", text: "Both sides negotiate and compromise" },
        { id: "d", text: "An agreement is reached without a strike" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Demand → counter-offer → compromise → agreement, avoiding a strike.",
      error_signals: ["ERR_EMS_G9E4A2_SEQ"], difficulty: 2,
    },
  ],
};

export default G9;
