// ─── EMS SP — Grade 9 authored pools (B): Financial Literacy (concepts) ───────
// Strand: Financial Literacy (CAPS G9) — CONCEPT-level pools only. The procedural
// "recording" skills (cash journals of a trading business, debtors/creditors
// journals, posting to ledgers, trial balances) are flagged deferred_recording in
// the tree and authored in a later pass, so they are intentionally absent here.
// Tap-only. Recipe: 10 MC · 4 TF · 4 CLOZE · 1 sequence · 1 sort-buckets = 20.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9B = {
  // ─── F1 · Term 1 — Cash journals (sole trader) ─────────────────────────────
  // A2 · Effect on the accounting equation  (A1 = deferred_recording)
  "EMS.G9.F1.A2": [
    MC("A trading business is one that ____.", ["buys and sells stock (goods) to make a profit", "only provides services", "makes nothing and sells nothing", "is owned by the state"], "buys and sells stock (goods) to make a profit",
      "A trading business buys and resells stock to make a profit.", "ERR_EMS_G9F1A2_DEF", 1),
    MC("When a trader receives cash for a sale, what happens to assets?", ["Cash (an asset) increases", "Cash decreases", "Liabilities increase", "Owner's equity falls"], "Cash (an asset) increases",
      "Receiving cash increases the asset 'cash/bank'.", "ERR_EMS_G9F1A2_SALE", 2),
    MC("When a trader pays rent in cash, what happens?", ["Cash falls and owner's equity falls (an expense)", "Cash rises", "Liabilities rise", "Nothing changes"], "Cash falls and owner's equity falls (an expense)",
      "Paying an expense reduces cash and reduces owner's equity.", "ERR_EMS_G9F1A2_RENT", 3),
    MC("The accounting equation a trader uses is ____.", ["Assets = Owner's equity + Liabilities", "Income = Rent − Tax", "Profit = Sales ÷ 2", "Cash = Stock × 3"], "Assets = Owner's equity + Liabilities",
      "Traders use the same equation: A = OE + L.", "ERR_EMS_G9F1A2_EQ", 1),
    MC("Every cash transaction of a trader keeps the equation ____.", ["balanced", "broken", "empty", "secret"], "balanced",
      "Each transaction keeps A = OE + L balanced.", "ERR_EMS_G9F1A2_BALANCE", 1),
    MC("If a trader buys stock for cash, what happens to total assets?", ["They stay the same (stock up, cash down)", "They rise", "They fall to zero", "Liabilities rise"], "They stay the same (stock up, cash down)",
      "Stock (asset) rises and cash (asset) falls — total assets unchanged.", "ERR_EMS_G9F1A2_STOCK", 3),
    MC("If a trader takes a cash loan, what happens?", ["Cash (asset) and the loan (liability) both rise", "Only owner's equity rises", "Assets fall", "Nothing changes"], "Cash (asset) and the loan (liability) both rise",
      "A cash loan raises both an asset (cash) and a liability (loan).", "ERR_EMS_G9F1A2_LOAN", 2),
    MC("Making a cash profit on a sale increases the owner's ____.", ["equity", "liabilities", "rent", "tax"], "equity",
      "Profit increases owner's equity.", "ERR_EMS_G9F1A2_PROFIT", 2),
    MC("Why does each transaction affect at least two items?", ["So the accounting equation stays balanced", "To break the books", "To hide cash", "No reason"], "So the accounting equation stays balanced",
      "Touching two items keeps both sides of the equation equal.", "ERR_EMS_G9F1A2_TWO", 2),
    MC("If a trader's assets rise by R200 and liabilities are unchanged, owner's equity ____.", ["rises by R200", "falls by R200", "stays the same", "doubles"], "rises by R200",
      "To keep A = OE + L balanced, owner's equity must rise by R200.", "ERR_EMS_G9F1A2_CALC", 3),
    TF("A trading business buys and sells stock to make a profit.", "True",
      "Traders buy and resell goods for profit.", "ERR_EMS_G9F1A2_TF1", 1),
    TF("Receiving cash for a sale increases the business's assets.", "True",
      "Cash received increases assets.", "ERR_EMS_G9F1A2_TF2", 1),
    TF("Paying rent in cash increases owner's equity.", "False",
      "Paying an expense like rent reduces cash and reduces owner's equity.", "ERR_EMS_G9F1A2_TF3", 2),
    TF("Every cash transaction keeps the accounting equation balanced.", "True",
      "Each transaction keeps A = OE + L balanced.", "ERR_EMS_G9F1A2_TF4", 1),
    CLOZE("A business that buys and sells stock is a ____ business.", ["trading", "service", "mining", "farming"], "trading",
      "Trading businesses buy and resell stock.", "ERR_EMS_G9F1A2_CL1", 1),
    CLOZE("Receiving cash from a sale makes cash, an ____, increase.", ["asset", "liability", "expense", "loan"], "asset",
      "Cash is an asset that rises when received.", "ERR_EMS_G9F1A2_CL2", 2),
    CLOZE("The trader's equation is Assets = Owner's equity + ____.", ["Liabilities", "Income", "Rent", "Tax"], "Liabilities",
      "A = OE + L.", "ERR_EMS_G9F1A2_CL3", 1),
    CLOZE("Buying stock for cash keeps total assets the ____.", ["same", "lower forever", "doubled", "zero"], "same",
      "Stock up, cash down — total assets unchanged.", "ERR_EMS_G9F1A2_CL4", 3),
    {
      question: "Sort each trader's cash transaction by its effect on TOTAL assets.",
      input_type: "sort-buckets",
      buckets: [{ id: "up", label: "Total assets increase" }, { id: "down", label: "Total assets decrease" }, { id: "same", label: "Total assets unchanged" }],
      items: [
        { id: "i1", text: "Cash received from a sale (at a profit)", correct_bucket: "up" },
        { id: "i2", text: "Pay rent in cash", correct_bucket: "down" },
        { id: "i3", text: "Buy stock for cash", correct_bucket: "same" },
        { id: "i4", text: "Take a cash loan from the bank", correct_bucket: "up" },
      ],
      expected: "A profitable sale and a loan raise assets; paying rent lowers them; buying stock for cash leaves the total unchanged.",
      pass_threshold: 0.75,
      memo: "Cash/loan in = assets up; expense out = assets down; asset-for-asset swap = unchanged.", error_signals: ["ERR_EMS_G9F1A2_SORT"], difficulty: 3,
    },
    {
      question: "Put the reasoning for a balanced trader transaction in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A cash transaction occurs" },
        { id: "b", text: "Identify the items it affects (e.g. cash and owner's equity)" },
        { id: "c", text: "Record equal changes on both sides" },
        { id: "d", text: "The accounting equation stays balanced" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Identify affected items, record equal changes, and the equation stays balanced.",
      error_signals: ["ERR_EMS_G9F1A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── F3 · Term 2 — Credit transactions: debtors (concept only) ─────────────
  // A1 · Credit sales, debtors and the NCA  (A2, A3 = deferred_recording)
  "EMS.G9.F3.A1": [
    MC("What is a credit sale?", ["A sale where the customer pays later, not immediately", "A sale paid in cash now", "A free gift", "A bank loan"], "A sale where the customer pays later, not immediately",
      "In a credit sale, the goods are taken now and paid for later.", "ERR_EMS_G9F3A1_DEF", 1),
    MC("Who is a 'debtor'?", ["A customer who owes the business money", "A supplier the business owes", "The bank", "The owner"], "A customer who owes the business money",
      "A debtor owes the business money for goods bought on credit.", "ERR_EMS_G9F3A1_DEBTOR", 1),
    MC("For the business, a debtor is recorded as a(n) ____.", ["asset (money owed to the business)", "liability", "expense", "loss"], "asset (money owed to the business)",
      "A debtor is an asset — money the business will receive.", "ERR_EMS_G9F3A1_ASSET", 2),
    MC("What is the National Credit Act (NCA)?", ["A law that protects people who buy on credit", "A tax on sales", "A type of bank", "An advert rule only"], "A law that protects people who buy on credit",
      "The NCA protects consumers and regulates credit in South Africa.", "ERR_EMS_G9F3A1_NCA", 2),
    MC("Why does the NCA matter for credit sales?", ["It helps prevent people taking on debt they cannot repay", "It bans all sales", "It removes all debtors", "It sets all prices"], "It helps prevent people taking on debt they cannot repay",
      "The NCA promotes responsible lending so people don't over-borrow.", "ERR_EMS_G9F3A1_WHYNCA", 2),
    MC("A 'debtors allowance' is given when ____.", ["a credit customer returns goods or gets a price reduction", "the business buys stock", "the owner invests capital", "rent is paid"], "a credit customer returns goods or gets a price reduction",
      "A debtors allowance covers returns or reductions on credit sales.", "ERR_EMS_G9F3A1_ALLOWANCE", 2),
    MC("Selling on credit can help a business by ____.", ["attracting customers who pay later", "scaring away all customers", "removing all sales", "raising no income"], "attracting customers who pay later",
      "Offering credit can attract customers who cannot pay all at once.", "ERR_EMS_G9F3A1_HELP", 2),
    MC("A risk of selling on credit is that ____.", ["some debtors may not pay", "the business always gets paid early", "there is no risk", "stock increases by itself"], "some debtors may not pay",
      "Credit carries the risk that some debtors fail to pay (bad debts).", "ERR_EMS_G9F3A1_RISK", 2),
    MC("When a debtor finally pays, the business's ____.", ["cash increases and the debtor's balance falls", "cash falls", "liabilities rise", "stock rises"], "cash increases and the debtor's balance falls",
      "Payment turns the debtor (owed amount) into cash received.", "ERR_EMS_G9F3A1_PAY", 3),
    MC("Which statement is correct?", ["A debtor owes the business; a credit sale is paid for later", "A debtor is owed by the business", "A credit sale is paid immediately", "A debtor is a supplier"], "A debtor owes the business; a credit sale is paid for later",
      "Debtors owe the business; credit sales are paid later.", "ERR_EMS_G9F3A1_CORRECT", 2),
    TF("In a credit sale, the customer pays later rather than immediately.", "True",
      "Credit sales are paid for later.", "ERR_EMS_G9F3A1_TF1", 1),
    TF("A debtor is a customer who owes the business money.", "True",
      "Debtors owe the business.", "ERR_EMS_G9F3A1_TF2", 1),
    TF("The National Credit Act protects people who buy on credit.", "True",
      "The NCA protects consumers and regulates credit.", "ERR_EMS_G9F3A1_TF3", 1),
    TF("A debtor is recorded as a liability of the business.", "False",
      "A debtor is an asset — money owed TO the business, not owed BY it.", "ERR_EMS_G9F3A1_TF4", 2),
    CLOZE("A sale where the customer pays later is a ____ sale.", ["credit", "cash", "free", "barter"], "credit",
      "Credit sales are paid for later.", "ERR_EMS_G9F3A1_CL1", 1),
    CLOZE("A customer who owes the business money is a ____.", ["debtor", "creditor", "supplier", "banker"], "debtor",
      "A debtor owes the business.", "ERR_EMS_G9F3A1_CL2", 1),
    CLOZE("The law protecting people who buy on credit is the National ____ Act.", ["Credit", "Tax", "Sales", "Trade"], "Credit",
      "The National Credit Act protects credit consumers.", "ERR_EMS_G9F3A1_CL3", 2),
    CLOZE("A debtor is an ____ of the business because the money will be received.", ["asset", "expense", "liability", "loss"], "asset",
      "A debtor is an asset (money owed to the business).", "ERR_EMS_G9F3A1_CL4", 2),
    {
      question: "Sort each into 'Debtor (owes the business)' or 'Not a debtor'.",
      input_type: "sort-buckets",
      buckets: [{ id: "debtor", label: "Debtor" }, { id: "not", label: "Not a debtor" }],
      items: [
        { id: "i1", text: "A customer who bought on credit and must pay later", correct_bucket: "debtor" },
        { id: "i2", text: "A supplier the business owes money to", correct_bucket: "not" },
        { id: "i3", text: "A client with an unpaid credit account", correct_bucket: "debtor" },
        { id: "i4", text: "The bank that gave the business a loan", correct_bucket: "not" },
      ],
      expected: "Credit customers who owe the business are debtors; suppliers and the bank are creditors, not debtors.",
      pass_threshold: 0.75,
      memo: "Debtor = owes the business (asset); supplier/bank you owe = creditor (liability).", error_signals: ["ERR_EMS_G9F3A1_SORT"], difficulty: 3,
    },
    {
      question: "Put a credit sale and its repayment in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The customer buys goods on credit" },
        { id: "b", text: "The customer becomes a debtor" },
        { id: "c", text: "Later the debtor pays the amount owed" },
        { id: "d", text: "The business receives the cash" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Credit sale → customer becomes a debtor → debtor pays → business receives cash.",
      error_signals: ["ERR_EMS_G9F3A1_SEQ"], difficulty: 2,
    },
  ],

  // ─── F4 · Term 3 — Credit transactions: creditors (concept only) ───────────
  // A1 · Creditors and creditors allowance  (A2, A3 = deferred_recording)
  "EMS.G9.F4.A1": [
    MC("Who is a 'creditor'?", ["A supplier the business owes money to", "A customer who owes the business", "The owner", "A bank teller"], "A supplier the business owes money to",
      "A creditor is someone the business owes money to.", "ERR_EMS_G9F4A1_DEF", 1),
    MC("For the business, a creditor is recorded as a(n) ____.", ["liability (money the business owes)", "asset", "income", "profit"], "liability (money the business owes)",
      "A creditor is a liability — money the business must pay.", "ERR_EMS_G9F4A1_LIABILITY", 2),
    MC("A 'creditors allowance' happens when ____.", ["the business returns goods to a supplier or gets a reduction", "a customer pays cash", "the owner invests capital", "rent is received"], "the business returns goods to a supplier or gets a reduction",
      "A creditors allowance covers goods returned to, or reductions from, a supplier.", "ERR_EMS_G9F4A1_ALLOWANCE", 2),
    MC("Buying stock on credit means the business ____.", ["receives goods now and pays the supplier later", "pays cash immediately", "gets goods for free", "sells to a debtor"], "receives goods now and pays the supplier later",
      "A credit purchase means paying the supplier later.", "ERR_EMS_G9F4A1_CREDITBUY", 2),
    MC("What is the difference between a debtor and a creditor?", ["A debtor owes the business; the business owes a creditor", "They are the same", "Both owe the business", "Both are owed by the business"], "A debtor owes the business; the business owes a creditor",
      "Debtor owes you; you owe a creditor.", "ERR_EMS_G9F4A1_DIFF", 2),
    MC("When the business pays a creditor, what happens?", ["Cash falls and the amount owed falls", "Cash rises", "The amount owed rises", "Nothing changes"], "Cash falls and the amount owed falls",
      "Paying a creditor reduces cash and reduces the liability owed.", "ERR_EMS_G9F4A1_PAY", 3),
    MC("Buying on credit can help a business by ____.", ["getting stock now and paying later", "paying for nothing", "removing all stock", "raising no value"], "getting stock now and paying later",
      "Credit lets a business obtain stock before it has the cash.", "ERR_EMS_G9F4A1_HELP", 2),
    MC("A risk of buying on credit is that ____.", ["the business must be able to pay the creditor later", "the business never owes anything", "there is no risk", "stock disappears"], "the business must be able to pay the creditor later",
      "The business must manage cash to pay creditors when due.", "ERR_EMS_G9F4A1_RISK", 2),
    MC("If the business returns faulty stock to a supplier, it receives a ____.", ["creditors allowance", "debtors allowance", "wage", "dividend"], "creditors allowance",
      "Returning goods to a supplier gives a creditors allowance.", "ERR_EMS_G9F4A1_RETURN", 2),
    MC("Which statement is correct?", ["A creditor is owed money by the business (a liability)", "A creditor owes the business", "A creditor is an asset", "A creditor is the owner"], "A creditor is owed money by the business (a liability)",
      "Creditors are owed by the business — a liability.", "ERR_EMS_G9F4A1_CORRECT", 2),
    TF("A creditor is a supplier the business owes money to.", "True",
      "The business owes its creditors.", "ERR_EMS_G9F4A1_TF1", 1),
    TF("A creditor is recorded as a liability.", "True",
      "Creditors are liabilities — money owed.", "ERR_EMS_G9F4A1_TF2", 1),
    TF("A creditor owes the business money.", "False",
      "The business owes the creditor; a debtor owes the business.", "ERR_EMS_G9F4A1_TF3", 2),
    TF("Returning goods to a supplier gives the business a creditors allowance.", "True",
      "A creditors allowance arises from returns to a supplier.", "ERR_EMS_G9F4A1_TF4", 2),
    CLOZE("A supplier the business owes money to is a ____.", ["creditor", "debtor", "customer", "banker"], "creditor",
      "Creditors are owed by the business.", "ERR_EMS_G9F4A1_CL1", 1),
    CLOZE("A creditor is recorded as a ____ of the business.", ["liability", "asset", "income", "profit"], "liability",
      "Creditors are liabilities.", "ERR_EMS_G9F4A1_CL2", 2),
    CLOZE("Returning goods to a supplier gives a ____ allowance.", ["creditors", "debtors", "wage", "rent"], "creditors",
      "Returns to a supplier give a creditors allowance.", "ERR_EMS_G9F4A1_CL3", 2),
    CLOZE("A debtor owes the business; the business owes a ____.", ["creditor", "debtor", "customer", "client"], "creditor",
      "You owe creditors; debtors owe you.", "ERR_EMS_G9F4A1_CL4", 1),
    {
      question: "Sort each into 'Debtor' or 'Creditor' (from the business's point of view).",
      input_type: "sort-buckets",
      buckets: [{ id: "debtor", label: "Debtor (owes the business)" }, { id: "creditor", label: "Creditor (business owes them)" }],
      items: [
        { id: "i1", text: "A customer who bought on credit", correct_bucket: "debtor" },
        { id: "i2", text: "A supplier of stock bought on credit", correct_bucket: "creditor" },
        { id: "i3", text: "A client with an unpaid account", correct_bucket: "debtor" },
        { id: "i4", text: "The wholesaler the business still must pay", correct_bucket: "creditor" },
      ],
      expected: "Credit customers are debtors (owe you); suppliers you must pay are creditors (you owe them).",
      pass_threshold: 0.75,
      memo: "Debtor = owes the business (asset); creditor = the business owes them (liability).", error_signals: ["ERR_EMS_G9F4A1_SORT"], difficulty: 3,
    },
    {
      question: "Put a credit purchase and its payment in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The business buys stock on credit" },
        { id: "b", text: "The supplier becomes a creditor" },
        { id: "c", text: "Later the business pays the creditor" },
        { id: "d", text: "The amount owed falls to zero" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Credit purchase → supplier becomes a creditor → business pays → amount owed cleared.",
      error_signals: ["ERR_EMS_G9F4A1_SEQ"], difficulty: 2,
    },
  ],
};

export default G9B;
