// ─── EMS SP — Grade 7 authored pools (B): Financial Literacy ──────────────────
// Strand: Financial Literacy (CAPS G7). Concept-level only (no journal recording
// in Grade 7). Tap-only: choice / true-false / cloze / sequence / sort-buckets.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7B = {
  // ─── F1 · Term 2 — Accounting concepts ─────────────────────────────────────
  // A1 · Capital, assets and liabilities
  "EMS.G7.F1.A1": [
    MC("What are 'assets'?", ["Things a person or business owns", "Money a business owes", "Wages paid to workers", "Taxes paid to government"], "Things a person or business owns",
      "Assets are the things you own that have value, like cash, equipment or a vehicle.", "ERR_EMS_G7F1A1_ASSETS", 1),
    MC("What is a 'liability'?", ["Money a person or business owes to others", "Cash a business owns", "Profit earned", "A free gift"], "Money a person or business owes to others",
      "A liability is a debt — money you owe to someone else, like a loan.", "ERR_EMS_G7F1A1_LIAB", 1),
    MC("What does 'capital' mean for a business owner?", ["The money or assets the owner puts into the business", "Money owed to a bank", "The wages of workers", "The rent on a shop"], "The money or assets the owner puts into the business",
      "Capital is the owner's own contribution of money or assets to start or run the business.", "ERR_EMS_G7F1A1_CAPITAL", 2),
    MC("Which of these is an asset?", ["A delivery van the business owns", "A loan the business must repay", "An unpaid electricity bill", "Money owed to a supplier"], "A delivery van the business owns",
      "A van the business owns is an asset; the others are debts (liabilities).", "ERR_EMS_G7F1A1_ASSET_EX", 1),
    MC("Which of these is a liability?", ["A bank loan that must be repaid", "Cash in the till", "A computer the business owns", "Stock on the shelves"], "A bank loan that must be repaid",
      "A loan to repay is a liability; cash, computers and stock are assets.", "ERR_EMS_G7F1A1_LIAB_EX", 1),
    MC("If a business owns a building worth R500 000, the building is recorded as a(n) ____.", ["asset", "liability", "expense", "loss"], "asset",
      "Something valuable the business owns, like a building, is an asset.", "ERR_EMS_G7F1A1_BUILDING", 1),
    MC("Mr Khumalo starts a shop using R20 000 of his own savings. That R20 000 is his ____.", ["capital", "liability", "loan", "tax"], "capital",
      "Money the owner puts into the business is the owner's capital.", "ERR_EMS_G7F1A1_OWN", 2),
    MC("Which list contains only assets?", ["Cash, vehicle, equipment", "Loan, cash, vehicle", "Equipment, debt, rent", "Cash, loan, tax"], "Cash, vehicle, equipment",
      "Cash, a vehicle and equipment are all owned items (assets).", "ERR_EMS_G7F1A1_ASSET_LIST", 2),
    MC("Why is it useful to know your assets and liabilities?", ["To see what you own and what you owe", "To avoid all record keeping", "To hide money", "To increase taxes"], "To see what you own and what you owe",
      "Knowing assets and liabilities shows your true financial position — what you own versus what you owe.", "ERR_EMS_G7F1A1_WHY", 2),
    MC("A friend lends a business R5 000. For the business, this R5 000 is a(n) ____.", ["liability", "asset", "capital", "profit"], "liability",
      "Borrowed money must be repaid, so it is a liability for the business.", "ERR_EMS_G7F1A1_BORROW", 2),
    TF("Assets are things you own; liabilities are things you owe.", "True",
      "This is the key distinction: assets = owned, liabilities = owed.", "ERR_EMS_G7F1A1_TF1", 1),
    TF("Capital is money the owner contributes to the business.", "True",
      "Capital is the owner's own investment of money or assets into the business.", "ERR_EMS_G7F1A1_TF2", 1),
    TF("A bank loan is an example of an asset.", "False",
      "A loan must be repaid, so it is a liability, not an asset.", "ERR_EMS_G7F1A1_TF3", 1),
    TF("Cash in the bank is an asset of the business.", "True",
      "Cash the business owns is one of its assets.", "ERR_EMS_G7F1A1_TF4", 1),
    CLOZE("Items a business owns, such as equipment and cash, are called ____.", ["assets", "liabilities", "expenses", "taxes"], "assets",
      "Assets are the valuable things a business owns.", "ERR_EMS_G7F1A1_CL1", 1),
    CLOZE("Money a business owes to others is called a ____.", ["liability", "asset", "profit", "wage"], "liability",
      "Liabilities are debts the business owes.", "ERR_EMS_G7F1A1_CL2", 1),
    CLOZE("The owner's own money put into the business is called ____.", ["capital", "rent", "tax", "stock"], "capital",
      "Capital is the owner's contribution to the business.", "ERR_EMS_G7F1A1_CL3", 2),
    CLOZE("A vehicle the business owns is an example of an ____.", ["asset", "expense", "owing", "income"], "asset",
      "An owned vehicle is an asset.", "ERR_EMS_G7F1A1_CL4", 1),
    {
      question: "Sort each item into 'Asset' or 'Liability'.",
      input_type: "sort-buckets",
      buckets: [{ id: "asset", label: "Asset (owned)" }, { id: "liability", label: "Liability (owed)" }],
      items: [
        { id: "i1", text: "Cash in the till", correct_bucket: "asset" },
        { id: "i2", text: "Bank loan to repay", correct_bucket: "liability" },
        { id: "i3", text: "Delivery vehicle", correct_bucket: "asset" },
        { id: "i4", text: "Money owed to a supplier", correct_bucket: "liability" },
      ],
      expected: "Cash and the vehicle are assets; the loan and money owed are liabilities.",
      pass_threshold: 0.75,
      memo: "Owned items are assets; debts owed to others are liabilities.", error_signals: ["ERR_EMS_G7F1A1_SORT"], difficulty: 2,
    },
    {
      question: "Put these steps of starting a small business in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The owner contributes capital" },
        { id: "b", text: "The business buys assets like equipment" },
        { id: "c", text: "The business may take a loan (a liability) if needed" },
        { id: "d", text: "The owner keeps records of what is owned and owed" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Capital comes first, then assets are bought, loans may be taken, and records track it all.",
      error_signals: ["ERR_EMS_G7F1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Income, expenses, profit and loss
  "EMS.G7.F1.A2": [
    MC("What is 'income'?", ["Money coming in to a person or business", "Money going out", "Debt that is owed", "Goods that are owned"], "Money coming in to a person or business",
      "Income is money received, such as sales, wages or interest.", "ERR_EMS_G7F1A2_INCOME", 1),
    MC("What is an 'expense'?", ["Money paid out to run a business or household", "Money received from sales", "Items the business owns", "A loan from a bank"], "Money paid out to run a business or household",
      "Expenses are the costs paid out, like rent, wages and electricity.", "ERR_EMS_G7F1A2_EXPENSE", 1),
    MC("How do you work out profit?", ["Income minus expenses", "Expenses minus income", "Income plus expenses", "Assets minus capital"], "Income minus expenses",
      "Profit = income − expenses. If income is greater, you make a profit.", "ERR_EMS_G7F1A2_PROFIT", 2),
    MC("When does a business make a loss?", ["When expenses are greater than income", "When income is greater than expenses", "When it owns assets", "When it has capital"], "When expenses are greater than income",
      "A loss happens when expenses exceed income — more money goes out than comes in.", "ERR_EMS_G7F1A2_LOSS", 2),
    MC("A stall earns R800 and spends R500. What is the profit?", ["R300", "R1 300", "R500", "R800"], "R300",
      "Profit = R800 − R500 = R300.", "ERR_EMS_G7F1A2_CALC", 2),
    MC("A stall earns R400 and spends R600. What is the result?", ["A loss of R200", "A profit of R200", "A profit of R1 000", "Break-even"], "A loss of R200",
      "Expenses (R600) are more than income (R400), so there is a loss of R200.", "ERR_EMS_G7F1A2_LOSSCALC", 2),
    MC("Which of these is income for a tuckshop?", ["Money from selling snacks", "Rent paid for the stall", "Electricity bill", "Wages paid to a helper"], "Money from selling snacks",
      "Sales of snacks bring money in, so that is income; the rest are expenses.", "ERR_EMS_G7F1A2_INC_EX", 1),
    MC("Which of these is an expense for a tuckshop?", ["Buying stock to sell", "Receiving money from a customer", "Owning a fridge", "Having cash in the till"], "Buying stock to sell",
      "Paying for stock is money going out — an expense.", "ERR_EMS_G7F1A2_EXP_EX", 1),
    MC("Why do businesses want income to be higher than expenses?", ["So they make a profit", "So they make a loss", "To owe more money", "To stop trading"], "So they make a profit",
      "When income beats expenses, the business earns a profit.", "ERR_EMS_G7F1A2_WHY", 1),
    MC("If income exactly equals expenses, the business ____.", ["breaks even (no profit, no loss)", "makes a big profit", "makes a big loss", "owes nothing ever"], "breaks even (no profit, no loss)",
      "When income equals expenses, the business breaks even — neither profit nor loss.", "ERR_EMS_G7F1A2_BREAKEVEN", 3),
    TF("Profit is what is left when income is greater than expenses.", "True",
      "Profit is the positive difference: income minus expenses.", "ERR_EMS_G7F1A2_TF1", 1),
    TF("A loss happens when income is greater than expenses.", "False",
      "A loss happens when expenses are greater than income, not the other way around.", "ERR_EMS_G7F1A2_TF2", 1),
    TF("Rent and wages are examples of expenses.", "True",
      "Rent and wages are costs paid out, so they are expenses.", "ERR_EMS_G7F1A2_TF3", 1),
    TF("Money received from selling goods is income.", "True",
      "Sales bring money in, which is income.", "ERR_EMS_G7F1A2_TF4", 1),
    CLOZE("Money received by a business is called ____.", ["income", "expenses", "debt", "loss"], "income",
      "Income is money flowing into the business.", "ERR_EMS_G7F1A2_CL1", 1),
    CLOZE("Money paid out to run a business is called ____.", ["expenses", "income", "capital", "profit"], "expenses",
      "Expenses are the costs paid out.", "ERR_EMS_G7F1A2_CL2", 1),
    CLOZE("Profit is income ____ expenses.", ["minus", "plus", "times", "divided by"], "minus",
      "Profit = income − expenses.", "ERR_EMS_G7F1A2_CL3", 2),
    CLOZE("When expenses are more than income, the business makes a ____.", ["loss", "profit", "saving", "gain"], "loss",
      "More out than in means a loss.", "ERR_EMS_G7F1A2_CL4", 2),
    {
      question: "Sort each item into 'Income' or 'Expense'.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Income" }, { id: "expense", label: "Expense" }],
      items: [
        { id: "i1", text: "Money from sales", correct_bucket: "income" },
        { id: "i2", text: "Paying rent", correct_bucket: "expense" },
        { id: "i3", text: "Interest received", correct_bucket: "income" },
        { id: "i4", text: "Buying packaging", correct_bucket: "expense" },
      ],
      expected: "Sales and interest are income; rent and packaging are expenses.",
      pass_threshold: 0.75,
      memo: "Income is money in; expenses are money out.", error_signals: ["ERR_EMS_G7F1A2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of working out profit in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Add up all income" },
        { id: "b", text: "Add up all expenses" },
        { id: "c", text: "Subtract expenses from income" },
        { id: "d", text: "See if the result is a profit or a loss" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Total income, total expenses, subtract, then check for profit or loss.",
      error_signals: ["ERR_EMS_G7F1A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Budgets, savings, banking and records
  "EMS.G7.F1.A3": [
    MC("What is a budget?", ["A plan for expected income and expenses", "A record of past sales only", "A type of bank loan", "A tax form"], "A plan for expected income and expenses",
      "A budget is a plan that estimates future income and expenses.", "ERR_EMS_G7F1A3_BUDGET", 1),
    MC("What does it mean to 'save'?", ["To keep some money for later instead of spending it", "To spend everything you earn", "To borrow money", "To pay tax"], "To keep some money for later instead of spending it",
      "Saving means setting money aside now to use in the future.", "ERR_EMS_G7F1A3_SAVE", 1),
    MC("Why do people and businesses keep financial records?", ["To track money coming in and going out", "To waste paper", "To avoid knowing their finances", "Only because it is fun"], "To track money coming in and going out",
      "Records track income and expenses so you know your true financial position.", "ERR_EMS_G7F1A3_RECORDS", 1),
    MC("What is a 'transaction'?", ["An exchange of money for goods or services", "A type of bank", "A budget plan", "A savings account"], "An exchange of money for goods or services",
      "A transaction is any deal where money is exchanged for goods or services.", "ERR_EMS_G7F1A3_TRANS", 2),
    MC("Which is a benefit of having a budget?", ["It helps you plan and avoid overspending", "It guarantees you become rich", "It removes all expenses", "It pays your bills for you"], "It helps you plan and avoid overspending",
      "A budget helps you plan spending so you don't run out of money.", "ERR_EMS_G7F1A3_BENEFIT", 2),
    MC("Where do most people keep their savings safely?", ["In a bank", "Under a mattress only", "In a rubbish bin", "Nowhere at all"], "In a bank",
      "A bank keeps savings safe and may pay interest.", "ERR_EMS_G7F1A3_BANK", 1),
    MC("Keeping records helps a business to ____.", ["see whether it is making a profit or loss", "ignore its money", "lose track of cash", "avoid all planning"], "see whether it is making a profit or loss",
      "Good records show income and expenses, revealing profit or loss.", "ERR_EMS_G7F1A3_RECORDS2", 2),
    MC("Which of these is a transaction?", ["Buying a loaf of bread for R15", "Thinking about money", "Reading a budget", "Owning a wallet"], "Buying a loaf of bread for R15",
      "Exchanging R15 for bread is a transaction.", "ERR_EMS_G7F1A3_TRANS_EX", 1),
    MC("Saving regularly, even small amounts, helps you to ____.", ["build up money for future needs", "spend more than you earn", "avoid all banks", "lose money"], "build up money for future needs",
      "Regular saving grows a sum you can use for future needs or emergencies.", "ERR_EMS_G7F1A3_REGULAR", 2),
    MC("A budget that plans to spend more than the income coming in is ____.", ["a problem, because it cannot balance", "always perfect", "the best kind", "not possible to write"], "a problem, because it cannot balance",
      "A budget should not plan to spend more than the income available, or it won't balance.", "ERR_EMS_G7F1A3_OVERSPEND", 3),
    TF("A budget is a plan for future income and expenses.", "True",
      "Budgets plan ahead for the money expected to come in and go out.", "ERR_EMS_G7F1A3_TF1", 1),
    TF("Saving means spending all your money immediately.", "False",
      "Saving is the opposite — keeping some money for later instead of spending it now.", "ERR_EMS_G7F1A3_TF2", 1),
    TF("Banks can keep your money safe and sometimes pay interest.", "True",
      "Banks store money securely and may add interest to savings.", "ERR_EMS_G7F1A3_TF3", 1),
    TF("Keeping financial records helps you understand your money.", "True",
      "Records show where money comes from and goes, helping you manage it.", "ERR_EMS_G7F1A3_TF4", 1),
    CLOZE("A plan for future income and expenses is called a ____.", ["budget", "loan", "tax", "receipt"], "budget",
      "A budget plans expected income and spending.", "ERR_EMS_G7F1A3_CL1", 1),
    CLOZE("Keeping money aside for the future is called ____.", ["saving", "spending", "borrowing", "owing"], "saving",
      "Saving sets money aside for later use.", "ERR_EMS_G7F1A3_CL2", 1),
    CLOZE("An exchange of money for goods or services is a ____.", ["transaction", "budget", "loan", "savings"], "transaction",
      "A transaction is any money-for-goods/services exchange.", "ERR_EMS_G7F1A3_CL3", 2),
    CLOZE("Writing down money received and paid out is called keeping ____.", ["records", "secrets", "wants", "needs"], "records",
      "Financial records track money in and out.", "ERR_EMS_G7F1A3_CL4", 1),
    {
      question: "Sort each item into 'Budgeting/Saving habit' or 'Poor money habit'.",
      input_type: "sort-buckets",
      buckets: [{ id: "good", label: "Good money habit" }, { id: "poor", label: "Poor money habit" }],
      items: [
        { id: "i1", text: "Planning a budget each month", correct_bucket: "good" },
        { id: "i2", text: "Spending everything with no plan", correct_bucket: "poor" },
        { id: "i3", text: "Saving a little each week", correct_bucket: "good" },
        { id: "i4", text: "Keeping no records at all", correct_bucket: "poor" },
      ],
      expected: "Budgeting and saving are good habits; spending with no plan and keeping no records are poor habits.",
      pass_threshold: 0.75,
      memo: "Planning, saving and record-keeping are good habits; no plan and no records are poor habits.", error_signals: ["ERR_EMS_G7F1A3_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of managing money in a sensible order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Make a budget for the month" },
        { id: "b", text: "Record income and expenses as they happen" },
        { id: "c", text: "Save any money left over" },
        { id: "d", text: "Check your records against your budget" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Plan a budget, record actual money, save the surplus, then compare records with the plan.",
      error_signals: ["ERR_EMS_G7F1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── F2 · Term 2 — Income and expenses ─────────────────────────────────────
  // A1 · Personal income
  "EMS.G7.F2.A1": [
    MC("What is personal income?", ["Money a person receives", "Money a person owes", "Goods a person owns", "A person's debts"], "Money a person receives",
      "Personal income is the money an individual receives, such as wages or pocket money.", "ERR_EMS_G7F2A1_DEF", 1),
    MC("Which of these is a type of personal income?", ["A salary from a job", "An electricity bill", "A loan repayment", "Rent you pay"], "A salary from a job",
      "A salary is money received for work — personal income; the others are money paid out.", "ERR_EMS_G7F2A1_SALARY", 1),
    MC("What is a 'wage'?", ["Money paid for work, often by the hour or week", "Money owed to a shop", "A type of tax", "A savings account"], "Money paid for work, often by the hour or week",
      "A wage is payment for work, often calculated hourly, daily or weekly.", "ERR_EMS_G7F2A1_WAGE", 1),
    MC("Interest earned on money in a savings account is a form of ____.", ["income", "expense", "debt", "tax"], "income",
      "Interest is money the bank pays you, so it is income.", "ERR_EMS_G7F2A1_INTEREST", 2),
    MC("Which is the difference between a salary and a wage?", ["A salary is usually a fixed monthly amount; a wage is often paid hourly or weekly", "They are exactly the same", "A salary is paid hourly; a wage is monthly", "A wage is never payment for work"], "A salary is usually a fixed monthly amount; a wage is often paid hourly or weekly",
      "Salaries are typically fixed monthly pay; wages are often hourly or weekly.", "ERR_EMS_G7F2A1_DIFF", 2),
    MC("Pocket money a learner receives is an example of their ____.", ["personal income", "personal expense", "liability", "tax"], "personal income",
      "Pocket money is money received, so it is personal income.", "ERR_EMS_G7F2A1_POCKET", 1),
    MC("Which of these would increase a person's income?", ["Getting a part-time job", "Paying more rent", "Buying more food", "Losing a job"], "Getting a part-time job",
      "A part-time job brings in more money, increasing income.", "ERR_EMS_G7F2A1_INCREASE", 1),
    MC("A person who is self-employed earns income from ____.", ["their own business or trade", "an electricity bill", "a loan they took", "the rent they pay"], "their own business or trade",
      "Self-employed people earn income from running their own business.", "ERR_EMS_G7F2A1_SELF", 2),
    MC("Which is NOT a source of personal income?", ["Paying for groceries", "A salary", "A wage", "Interest from savings"], "Paying for groceries",
      "Paying for groceries is spending (an expense), not income.", "ERR_EMS_G7F2A1_NOT", 2),
    MC("Why is it useful to know all your sources of income?", ["To plan how much you can spend and save", "To spend without thinking", "To avoid budgeting", "To ignore your money"], "To plan how much you can spend and save",
      "Knowing your income lets you plan spending and saving sensibly.", "ERR_EMS_G7F2A1_WHY", 2),
    TF("A salary is a form of personal income.", "True",
      "A salary is money received for work, so it is personal income.", "ERR_EMS_G7F2A1_TF1", 1),
    TF("Pocket money received by a learner is an expense.", "False",
      "Pocket money is money received, so it is income, not an expense.", "ERR_EMS_G7F2A1_TF2", 1),
    TF("Interest paid to you by a bank is a type of income.", "True",
      "Interest the bank pays you adds to your income.", "ERR_EMS_G7F2A1_TF3", 1),
    TF("People can have more than one source of income.", "True",
      "A person might earn a salary and also receive interest or run a side business.", "ERR_EMS_G7F2A1_TF4", 1),
    CLOZE("Money a person receives is called personal ____.", ["income", "expense", "debt", "loss"], "income",
      "Personal income is the money an individual receives.", "ERR_EMS_G7F2A1_CL1", 1),
    CLOZE("Money paid for work, often per hour or week, is a ____.", ["wage", "tax", "loan", "budget"], "wage",
      "A wage is payment for work, usually hourly or weekly.", "ERR_EMS_G7F2A1_CL2", 1),
    CLOZE("A fixed monthly payment for a job is usually called a ____.", ["salary", "wage", "tax", "fee"], "salary",
      "A salary is typically a fixed monthly amount.", "ERR_EMS_G7F2A1_CL3", 2),
    CLOZE("Money the bank pays you on your savings is called ____.", ["interest", "rent", "tax", "debt"], "interest",
      "Interest is what the bank pays you for keeping money with them.", "ERR_EMS_G7F2A1_CL4", 2),
    {
      question: "Sort each item into 'Personal income' or 'Not income'.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Personal income" }, { id: "not", label: "Not income" }],
      items: [
        { id: "i1", text: "A weekly wage", correct_bucket: "income" },
        { id: "i2", text: "Paying for airtime", correct_bucket: "not" },
        { id: "i3", text: "Interest from savings", correct_bucket: "income" },
        { id: "i4", text: "A monthly rent payment you make", correct_bucket: "not" },
      ],
      expected: "Wages and interest are income; paying for airtime or rent is spending.",
      pass_threshold: 0.75,
      memo: "Income is money received; payments you make are expenses, not income.", error_signals: ["ERR_EMS_G7F2A1_SORT"], difficulty: 1,
    },
    {
      question: "Put these income-earning steps in order for a learner doing a holiday job.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The learner finds a holiday job" },
        { id: "b", text: "They work the agreed hours" },
        { id: "c", text: "They receive a wage" },
        { id: "d", text: "They decide how much to spend and save" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Earning income: get the job, do the work, receive the wage, then plan spending and saving.",
      error_signals: ["ERR_EMS_G7F2A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · Personal expenses and net worth
  "EMS.G7.F2.A2": [
    MC("What is a personal expense?", ["Money a person spends", "Money a person receives", "Something a person owns for free", "A person's salary"], "Money a person spends",
      "A personal expense is money you pay out, like food, transport or airtime.", "ERR_EMS_G7F2A2_DEF", 1),
    MC("What does 'net worth' mean?", ["What you own minus what you owe", "Your total income only", "Your total expenses only", "The money in your pocket only"], "What you own minus what you owe",
      "Net worth = assets (what you own) − liabilities (what you owe).", "ERR_EMS_G7F2A2_NETWORTH", 2),
    MC("Which of these is a personal expense?", ["Buying lunch", "Receiving a salary", "Earning interest", "Getting pocket money"], "Buying lunch",
      "Buying lunch is spending money, so it is an expense.", "ERR_EMS_G7F2A2_EXP_EX", 1),
    MC("A person owns R5 000 in assets and owes R2 000. Their net worth is ____.", ["R3 000", "R7 000", "R2 000", "R5 000"], "R3 000",
      "Net worth = R5 000 − R2 000 = R3 000.", "ERR_EMS_G7F2A2_CALC", 2),
    MC("Which would increase a person's net worth?", ["Saving more and reducing debt", "Borrowing more money", "Spending all savings", "Increasing what they owe"], "Saving more and reducing debt",
      "More assets and less debt raise net worth.", "ERR_EMS_G7F2A2_INCREASE", 2),
    MC("A statement listing what you own and owe to work out net worth is a personal statement of ____.", ["net worth", "income", "sales", "tax"], "net worth",
      "A statement of net worth lists assets and liabilities to find net worth.", "ERR_EMS_G7F2A2_STATEMENT", 2),
    MC("Which is a fixed expense (roughly the same each month)?", ["Rent", "A once-off gift", "A surprise repair", "A lucky win"], "Rent",
      "Rent is usually a fixed, regular monthly expense.", "ERR_EMS_G7F2A2_FIXED", 2),
    MC("Spending less than you earn helps you to ____.", ["save and build net worth", "fall into debt", "lose all assets", "increase liabilities"], "save and build net worth",
      "Spending less than income lets you save, which builds net worth.", "ERR_EMS_G7F2A2_SPENDLESS", 2),
    MC("Which list contains only personal expenses?", ["Transport, food, airtime", "Salary, interest, wage", "Wage, food, salary", "Interest, transport, salary"], "Transport, food, airtime",
      "Transport, food and airtime are all things you pay for — expenses.", "ERR_EMS_G7F2A2_LIST", 2),
    MC("If your expenses are higher than your income every month, you will likely ____.", ["build up debt", "build up savings", "increase net worth", "pay no one"], "build up debt",
      "Spending more than you earn forces you to borrow, building debt.", "ERR_EMS_G7F2A2_DEBT", 3),
    TF("A personal expense is money you spend.", "True",
      "Expenses are money paid out.", "ERR_EMS_G7F2A2_TF1", 1),
    TF("Net worth is what you own minus what you owe.", "True",
      "Net worth = assets − liabilities.", "ERR_EMS_G7F2A2_TF2", 1),
    TF("Reducing your debt can increase your net worth.", "True",
      "Lower liabilities raise net worth, since net worth = assets − liabilities.", "ERR_EMS_G7F2A2_TF3", 2),
    TF("Buying food is a form of personal income.", "False",
      "Buying food is spending money, which is an expense, not income.", "ERR_EMS_G7F2A2_TF4", 1),
    CLOZE("Money a person spends is called a personal ____.", ["expense", "income", "asset", "wage"], "expense",
      "Personal expenses are the money you pay out.", "ERR_EMS_G7F2A2_CL1", 1),
    CLOZE("What you own minus what you owe is your ____ worth.", ["net", "gross", "total", "fixed"], "net",
      "Net worth = assets − liabilities.", "ERR_EMS_G7F2A2_CL2", 2),
    CLOZE("An expense that stays about the same each month, like rent, is a ____ expense.", ["fixed", "lucky", "surprise", "once-off"], "fixed",
      "Fixed expenses recur at roughly the same amount each period.", "ERR_EMS_G7F2A2_CL3", 2),
    CLOZE("To build savings, you should spend ____ than you earn.", ["less", "more", "double", "triple"], "less",
      "Spending less than you earn leaves money to save.", "ERR_EMS_G7F2A2_CL4", 1),
    {
      question: "Sort each item into 'Asset (owned)' or 'Liability (owed)' for working out net worth.",
      input_type: "sort-buckets",
      buckets: [{ id: "asset", label: "Asset (owned)" }, { id: "liability", label: "Liability (owed)" }],
      items: [
        { id: "i1", text: "Cash savings of R1 000", correct_bucket: "asset" },
        { id: "i2", text: "R300 owed to a friend", correct_bucket: "liability" },
        { id: "i3", text: "A bicycle you own", correct_bucket: "asset" },
        { id: "i4", text: "An unpaid phone account", correct_bucket: "liability" },
      ],
      expected: "Savings and the bicycle are assets; money owed to a friend and the phone account are liabilities.",
      pass_threshold: 0.75,
      memo: "Net worth uses assets (owned) minus liabilities (owed).", error_signals: ["ERR_EMS_G7F2A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of working out personal net worth in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "List everything you own (assets)" },
        { id: "b", text: "List everything you owe (liabilities)" },
        { id: "c", text: "Subtract what you owe from what you own" },
        { id: "d", text: "The answer is your net worth" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "List assets, list liabilities, subtract, and the result is net worth.",
      error_signals: ["ERR_EMS_G7F2A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Business income and expenses
  "EMS.G7.F2.A3": [
    MC("What is the main source of income for most businesses?", ["Money from selling goods or services", "Rent the business pays", "Wages paid to staff", "Electricity bills"], "Money from selling goods or services",
      "Most business income comes from selling goods or services to customers.", "ERR_EMS_G7F2A3_INCOME", 1),
    MC("Which of these is a business expense?", ["Paying wages to workers", "Receiving money from sales", "Owning a delivery van", "Earning interest"], "Paying wages to workers",
      "Wages are money paid out by the business — an expense.", "ERR_EMS_G7F2A3_EXP", 1),
    MC("Why might a business put some money into savings or investments?", ["To grow money and prepare for future needs", "To waste it", "To avoid all profit", "To stop trading"], "To grow money and prepare for future needs",
      "Saving or investing helps a business prepare for the future and grow its money.", "ERR_EMS_G7F2A3_INVEST", 2),
    MC("Which is a typical business income?", ["Service fees from customers", "The rent the business pays", "Staff wages", "The water bill"], "Service fees from customers",
      "Fees charged to customers bring money in — income.", "ERR_EMS_G7F2A3_INC_EX", 1),
    MC("Which is a typical business expense?", ["Rent for the shop", "Money from a sale", "A customer's payment", "Interest the business earns"], "Rent for the shop",
      "Rent is money the business pays out — an expense.", "ERR_EMS_G7F2A3_EXP_EX", 1),
    MC("A business earns R10 000 from sales and pays R7 000 in expenses. It made a ____.", ["profit of R3 000", "loss of R3 000", "profit of R17 000", "loss of R7 000"], "profit of R3 000",
      "Profit = R10 000 − R7 000 = R3 000.", "ERR_EMS_G7F2A3_CALC", 2),
    MC("Investing business profits wisely can help the business to ____.", ["grow in the future", "shrink to nothing", "avoid all income", "stop serving customers"], "grow in the future",
      "Wisely invested profits can fund growth and future stability.", "ERR_EMS_G7F2A3_GROW", 2),
    MC("Which would reduce a business's profit?", ["Higher expenses", "Higher sales", "More customers", "Lower costs"], "Higher expenses",
      "Rising expenses eat into profit; higher sales or lower costs would raise it.", "ERR_EMS_G7F2A3_REDUCE", 2),
    MC("Why must a business track both income and expenses?", ["To know whether it is making a profit", "To ignore its finances", "To lose money", "To avoid customers"], "To know whether it is making a profit",
      "Tracking both shows whether income beats expenses — that is, whether there is profit.", "ERR_EMS_G7F2A3_TRACK", 1),
    MC("A business that always spends more than it earns will eventually ____.", ["run into financial trouble", "become very rich", "pay no expenses", "have endless cash"], "run into financial trouble",
      "Persistently spending more than you earn leads to losses and financial trouble.", "ERR_EMS_G7F2A3_TROUBLE", 3),
    TF("Selling goods and services is the main income for most businesses.", "True",
      "Sales of goods and services are the main income source for businesses.", "ERR_EMS_G7F2A3_TF1", 1),
    TF("Wages and rent are examples of business expenses.", "True",
      "Wages and rent are costs paid out by the business — expenses.", "ERR_EMS_G7F2A3_TF2", 1),
    TF("Businesses can also save and invest some of their money.", "True",
      "Businesses, like people, can save and invest for future needs and growth.", "ERR_EMS_G7F2A3_TF3", 1),
    TF("A business makes a profit when its expenses are higher than its income.", "False",
      "That is a loss. Profit occurs when income is higher than expenses.", "ERR_EMS_G7F2A3_TF4", 1),
    CLOZE("Most business income comes from ____ goods and services.", ["selling", "buying", "owing", "renting"], "selling",
      "Selling goods and services brings money into the business.", "ERR_EMS_G7F2A3_CL1", 1),
    CLOZE("Wages, rent and electricity are business ____.", ["expenses", "income", "assets", "profits"], "expenses",
      "These are costs paid out — business expenses.", "ERR_EMS_G7F2A3_CL2", 1),
    CLOZE("Putting money aside to grow it for the future is called ____.", ["investing", "wasting", "owing", "spending"], "investing",
      "Investing puts money to work to grow it over time.", "ERR_EMS_G7F2A3_CL3", 2),
    CLOZE("A business makes a profit when income is ____ than expenses.", ["greater", "less", "equal", "lower"], "greater",
      "Profit happens when income is greater than expenses.", "ERR_EMS_G7F2A3_CL4", 2),
    {
      question: "Sort each item into 'Business income' or 'Business expense'.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Business income" }, { id: "expense", label: "Business expense" }],
      items: [
        { id: "i1", text: "Money from selling products", correct_bucket: "income" },
        { id: "i2", text: "Staff wages", correct_bucket: "expense" },
        { id: "i3", text: "Service fees from clients", correct_bucket: "income" },
        { id: "i4", text: "Shop rent", correct_bucket: "expense" },
      ],
      expected: "Sales and service fees are income; wages and rent are expenses.",
      pass_threshold: 0.75,
      memo: "Money from customers is income; money paid to run the business is expense.", error_signals: ["ERR_EMS_G7F2A3_SORT"], difficulty: 1,
    },
    {
      question: "Put the flow of money through a small business in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The business sells goods and earns income" },
        { id: "b", text: "It pays its expenses (wages, rent, stock)" },
        { id: "c", text: "It works out the profit that is left" },
        { id: "d", text: "It saves or invests some of the profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Earn income, pay expenses, find the profit, then save or invest part of it.",
      error_signals: ["ERR_EMS_G7F2A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── F3 · Term 2 — Budgets ─────────────────────────────────────────────────
  // A1 · Personal budget
  "EMS.G7.F3.A1": [
    MC("What is a personal budget?", ["A plan of your expected income and spending", "A record of a shop's sales", "A type of loan", "A government tax"], "A plan of your expected income and spending",
      "A personal budget plans how you will use your income on spending and saving.", "ERR_EMS_G7F3A1_DEF", 1),
    MC("Why is a personal budget useful?", ["It helps you avoid spending more than you earn", "It makes you spend more", "It hides your money", "It removes your income"], "It helps you avoid spending more than you earn",
      "A budget keeps your spending within your income, helping you avoid debt.", "ERR_EMS_G7F3A1_WHY", 1),
    MC("In a budget, what should you usually plan for first?", ["Needs like food and transport", "Wants like sweets", "Luxuries like games", "Unplanned spending"], "Needs like food and transport",
      "Budgets should cover essential needs before wants.", "ERR_EMS_G7F3A1_NEEDS", 2),
    MC("If your income is R200 and you plan to spend R250, your budget ____.", ["does not balance — you'd overspend", "balances perfectly", "saves R50", "earns R50"], "does not balance — you'd overspend",
      "Planning to spend more than you earn means the budget does not balance.", "ERR_EMS_G7F3A1_BALANCE", 2),
    MC("A good personal budget leaves room to ____.", ["save some money", "spend more than you have", "ignore your needs", "owe more"], "save some money",
      "A healthy budget plans for saving, not just spending.", "ERR_EMS_G7F3A1_SAVE", 2),
    MC("Which is the income side of a personal budget?", ["Pocket money and a part-time wage", "Bus fare and lunch money", "Airtime spending", "Savings goals"], "Pocket money and a part-time wage",
      "Income is the money coming in, like pocket money and wages.", "ERR_EMS_G7F3A1_INC", 1),
    MC("Which is the expense side of a personal budget?", ["Transport and food costs", "A wage you earn", "Interest you receive", "Pocket money in"], "Transport and food costs",
      "Expenses are what you plan to spend, like transport and food.", "ERR_EMS_G7F3A1_EXP", 1),
    MC("If you stick to your budget, you are more likely to ____.", ["meet your needs and reach savings goals", "run out of money early", "lose track of spending", "fall into debt"], "meet your needs and reach savings goals",
      "Sticking to a budget keeps spending in check and helps reach goals.", "ERR_EMS_G7F3A1_STICK", 2),
    MC("What should you do if your planned expenses are more than your income?", ["Cut some spending or increase income", "Spend even more", "Ignore the problem", "Stop budgeting"], "Cut some spending or increase income",
      "To balance the budget, reduce spending or find more income.", "ERR_EMS_G7F3A1_FIX", 2),
    MC("A learner budgets R100: R60 transport, R20 food, R20 saving. This budget ____.", ["balances and includes saving", "overspends", "ignores needs", "has no income"], "balances and includes saving",
      "R60 + R20 + R20 = R100, matching income, and it includes saving.", "ERR_EMS_G7F3A1_EXAMPLE", 3),
    TF("A personal budget plans your income and spending.", "True",
      "A budget is a plan for income and spending.", "ERR_EMS_G7F3A1_TF1", 1),
    TF("A budget should plan to spend more than you earn.", "False",
      "A good budget keeps spending within income, not above it.", "ERR_EMS_G7F3A1_TF2", 1),
    TF("Including savings in your budget is a good habit.", "True",
      "Planning to save is part of a healthy budget.", "ERR_EMS_G7F3A1_TF3", 1),
    TF("Needs should usually be budgeted for before wants.", "True",
      "Essential needs come before wants in a sensible budget.", "ERR_EMS_G7F3A1_TF4", 1),
    CLOZE("A plan of your income and spending is a personal ____.", ["budget", "loan", "receipt", "tax"], "budget",
      "A personal budget plans income and spending.", "ERR_EMS_G7F3A1_CL1", 1),
    CLOZE("In a budget, money coming in is your ____.", ["income", "expense", "debt", "saving"], "income",
      "Income is the money coming in.", "ERR_EMS_G7F3A1_CL2", 1),
    CLOZE("In a budget, money you plan to spend is your ____.", ["expenses", "income", "assets", "profit"], "expenses",
      "Expenses are the planned spending.", "ERR_EMS_G7F3A1_CL3", 1),
    CLOZE("A balanced budget means spending is not ____ than income.", ["more", "less", "equal", "lower"], "more",
      "A balanced budget keeps spending at or below income.", "ERR_EMS_G7F3A1_CL4", 2),
    {
      question: "Sort each entry into the 'Income' or 'Expense' side of a personal budget.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Income" }, { id: "expense", label: "Expense" }],
      items: [
        { id: "i1", text: "Weekly pocket money", correct_bucket: "income" },
        { id: "i2", text: "Taxi fare to school", correct_bucket: "expense" },
        { id: "i3", text: "Holiday job wage", correct_bucket: "income" },
        { id: "i4", text: "Money spent on lunch", correct_bucket: "expense" },
      ],
      expected: "Pocket money and wages are income; taxi fare and lunch are expenses.",
      pass_threshold: 0.75,
      memo: "Income is money in; expenses are planned money out.", error_signals: ["ERR_EMS_G7F3A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of making a personal budget in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Work out your total income" },
        { id: "b", text: "List your needs and their costs" },
        { id: "c", text: "Add any wants you can afford" },
        { id: "d", text: "Plan to save what is left over" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Income first, then needs, then affordable wants, then saving.",
      error_signals: ["ERR_EMS_G7F3A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Business budget
  "EMS.G7.F3.A2": [
    MC("What is a business budget?", ["A plan of a business's expected income and expenses", "A record of personal pocket money", "A type of tax form", "A loan agreement"], "A plan of a business's expected income and expenses",
      "A business budget plans the income and expenses the business expects.", "ERR_EMS_G7F3A2_DEF", 1),
    MC("How is a business budget similar to a personal budget?", ["Both plan income and expenses", "Both are only about pocket money", "Both ignore expenses", "Neither plans ahead"], "Both plan income and expenses",
      "Both kinds of budget plan expected income and expenses, just at different scales.", "ERR_EMS_G7F3A2_SIMILAR", 1),
    MC("How is a business budget different from a personal one?", ["It deals with the business's income and costs, often larger", "It is exactly the same in every way", "It never includes expenses", "It is only about one person's sweets"], "It deals with the business's income and costs, often larger",
      "A business budget covers business income and costs, usually larger and more complex.", "ERR_EMS_G7F3A2_DIFF", 2),
    MC("Why does a business prepare a budget?", ["To plan ahead and control spending", "To waste money", "To avoid making profit", "To stop selling"], "To plan ahead and control spending",
      "Budgets help a business plan and keep spending under control.", "ERR_EMS_G7F3A2_WHY", 1),
    MC("Which would appear on the income side of a business budget?", ["Expected sales", "Expected rent", "Expected wages", "Expected electricity"], "Expected sales",
      "Expected sales are income; rent, wages and electricity are expenses.", "ERR_EMS_G7F3A2_INC", 2),
    MC("Which would appear on the expense side of a business budget?", ["Expected stock purchases", "Expected sales income", "Customer payments", "Interest earned"], "Expected stock purchases",
      "Buying stock is a planned cost — an expense.", "ERR_EMS_G7F3A2_EXP", 2),
    MC("A business budget that plans for income to be higher than expenses expects a ____.", ["profit", "loss", "debt", "tax"], "profit",
      "If planned income beats planned expenses, the budget expects a profit.", "ERR_EMS_G7F3A2_PROFIT", 2),
    MC("If a business expects expenses to be higher than income, the budget warns of a possible ____.", ["loss", "profit", "bonus", "saving"], "loss",
      "Planned expenses above income signal a possible loss to address.", "ERR_EMS_G7F3A2_LOSS", 2),
    MC("How can a budget help a business avoid running out of money?", ["By planning income against expenses in advance", "By hiding the figures", "By spending randomly", "By ignoring costs"], "By planning income against expenses in advance",
      "Planning ahead shows whether money will be enough to cover costs.", "ERR_EMS_G7F3A2_CASH", 2),
    MC("A budget shows a shop expects R50 000 income and R45 000 expenses. The plan expects ____.", ["a R5 000 profit", "a R5 000 loss", "a R95 000 profit", "to break even"], "a R5 000 profit",
      "R50 000 − R45 000 = R5 000 expected profit.", "ERR_EMS_G7F3A2_CALC", 3),
    TF("A business budget plans expected income and expenses.", "True",
      "Like a personal budget, it plans income and expenses, for the business.", "ERR_EMS_G7F3A2_TF1", 1),
    TF("Budgets help businesses control spending and plan ahead.", "True",
      "Budgets are planning and control tools.", "ERR_EMS_G7F3A2_TF2", 1),
    TF("A business budget only lists income and never expenses.", "False",
      "A budget lists both income and expenses so the business can plan.", "ERR_EMS_G7F3A2_TF3", 1),
    TF("A business and a personal budget both plan for the future.", "True",
      "Both look ahead at expected income and spending.", "ERR_EMS_G7F3A2_TF4", 1),
    CLOZE("A plan of a business's income and expenses is a business ____.", ["budget", "receipt", "loan", "tax"], "budget",
      "A business budget plans the firm's income and expenses.", "ERR_EMS_G7F3A2_CL1", 1),
    CLOZE("Expected ____ appear on the income side of a business budget.", ["sales", "rent", "wages", "stock"], "sales",
      "Sales are the main income a business plans for.", "ERR_EMS_G7F3A2_CL2", 2),
    CLOZE("Expected rent and wages appear on the ____ side of a business budget.", ["expense", "income", "asset", "profit"], "expense",
      "Rent and wages are planned costs — expenses.", "ERR_EMS_G7F3A2_CL3", 2),
    CLOZE("If planned income is more than planned expenses, the budget expects a ____.", ["profit", "loss", "debt", "tax"], "profit",
      "Income above expenses means an expected profit.", "ERR_EMS_G7F3A2_CL4", 2),
    {
      question: "Sort each item into the 'Income' or 'Expense' side of a business budget.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Income" }, { id: "expense", label: "Expense" }],
      items: [
        { id: "i1", text: "Expected sales", correct_bucket: "income" },
        { id: "i2", text: "Wages to pay", correct_bucket: "expense" },
        { id: "i3", text: "Service fees expected", correct_bucket: "income" },
        { id: "i4", text: "Rent to pay", correct_bucket: "expense" },
      ],
      expected: "Expected sales and fees are income; wages and rent are expenses.",
      pass_threshold: 0.75,
      memo: "Money the business expects to receive is income; money it expects to pay is expense.", error_signals: ["ERR_EMS_G7F3A2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of preparing a business budget in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Estimate expected income (sales)" },
        { id: "b", text: "Estimate expected expenses (rent, wages, stock)" },
        { id: "c", text: "Compare income with expenses" },
        { id: "d", text: "Decide if a profit or loss is expected and adjust" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Estimate income, estimate expenses, compare them, then plan for the expected profit or loss.",
      error_signals: ["ERR_EMS_G7F3A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── F4 · Term 4 — Savings ─────────────────────────────────────────────────
  // A1 · Personal savings and its purpose
  "EMS.G7.F4.A1": [
    MC("What does it mean to save money?", ["To set money aside instead of spending it", "To spend all of it now", "To borrow it", "To owe it"], "To set money aside instead of spending it",
      "Saving means keeping money for later rather than spending it now.", "ERR_EMS_G7F4A1_DEF", 1),
    MC("Why is saving important?", ["It prepares you for future needs and emergencies", "It wastes money", "It increases debt", "It stops all income"], "It prepares you for future needs and emergencies",
      "Savings provide for future needs, goals and unexpected emergencies.", "ERR_EMS_G7F4A1_WHY", 1),
    MC("Which is a good reason to save?", ["To buy something important later", "To never use money again", "To lose money", "To avoid all banks"], "To buy something important later",
      "Saving lets you afford bigger or future purchases.", "ERR_EMS_G7F4A1_REASON", 1),
    MC("An 'emergency fund' is money saved for ____.", ["unexpected costs", "everyday sweets", "showing off", "wasting"], "unexpected costs",
      "An emergency fund covers surprise expenses like repairs or medical costs.", "ERR_EMS_G7F4A1_EMERGENCY", 2),
    MC("Saving small amounts regularly will ____ over time.", ["add up to a larger sum", "disappear", "always shrink", "become a debt"], "add up to a larger sum",
      "Regular small savings build into a meaningful amount over time.", "ERR_EMS_G7F4A1_REGULAR", 2),
    MC("Which habit helps you save?", ["Spending less than you earn", "Spending more than you earn", "Borrowing for wants", "Ignoring your budget"], "Spending less than you earn",
      "Spending less than you earn leaves money to save.", "ERR_EMS_G7F4A1_HABIT", 2),
    MC("Saving for a goal, like a bicycle, is an example of ____.", ["saving with a purpose", "wasting money", "borrowing", "paying tax"], "saving with a purpose",
      "Saving towards a specific goal gives your saving a clear purpose.", "ERR_EMS_G7F4A1_GOAL", 1),
    MC("Which is a benefit of having savings?", ["You can handle emergencies without borrowing", "You will always be in debt", "You can never buy anything", "You must pay more tax"], "You can handle emergencies without borrowing",
      "Savings let you cover surprises without taking on debt.", "ERR_EMS_G7F4A1_BENEFIT", 2),
    MC("If you spend everything you earn, you will have ____ for the future.", ["no savings", "huge savings", "more income", "lower expenses"], "no savings",
      "Spending all income leaves nothing to save for the future.", "ERR_EMS_G7F4A1_NOSAVE", 1),
    MC("Why might saving be difficult for some people?", ["Their income barely covers their needs", "They have too much money", "Saving is illegal", "Banks refuse savings"], "Their income barely covers their needs",
      "When income only just meets basic needs, there is little or nothing left to save.", "ERR_EMS_G7F4A1_HARD", 3),
    TF("Saving means keeping some money for later instead of spending it now.", "True",
      "Saving sets money aside for future use.", "ERR_EMS_G7F4A1_TF1", 1),
    TF("Saving has no purpose and is a waste of money.", "False",
      "Saving prepares for future needs, goals and emergencies — it is very useful.", "ERR_EMS_G7F4A1_TF2", 1),
    TF("Even small, regular savings can grow into a useful amount.", "True",
      "Saving small amounts often adds up over time.", "ERR_EMS_G7F4A1_TF3", 1),
    TF("An emergency fund is money saved for unexpected costs.", "True",
      "Emergency funds cover surprise expenses.", "ERR_EMS_G7F4A1_TF4", 1),
    CLOZE("Setting money aside for later instead of spending it is called ____.", ["saving", "spending", "borrowing", "owing"], "saving",
      "Saving keeps money for the future.", "ERR_EMS_G7F4A1_CL1", 1),
    CLOZE("Money saved for unexpected costs is an ____ fund.", ["emergency", "income", "expense", "interest"], "emergency",
      "An emergency fund is for surprises.", "ERR_EMS_G7F4A1_CL2", 2),
    CLOZE("To save, you should spend ____ than you earn.", ["less", "more", "double", "all"], "less",
      "Spending less than you earn leaves money to save.", "ERR_EMS_G7F4A1_CL3", 1),
    CLOZE("Saving towards a bicycle is saving with a clear ____.", ["purpose", "loss", "debt", "tax"], "purpose",
      "Saving for a specific goal gives it a purpose.", "ERR_EMS_G7F4A1_CL4", 1),
    {
      question: "Sort each into 'Helps you save' or 'Stops you saving'.",
      input_type: "sort-buckets",
      buckets: [{ id: "helps", label: "Helps you save" }, { id: "stops", label: "Stops you saving" }],
      items: [
        { id: "i1", text: "Putting aside R10 each week", correct_bucket: "helps" },
        { id: "i2", text: "Spending every cent you get", correct_bucket: "stops" },
        { id: "i3", text: "Setting a savings goal", correct_bucket: "helps" },
        { id: "i4", text: "Buying wants you can't afford", correct_bucket: "stops" },
      ],
      expected: "Putting money aside and setting goals help you save; overspending stops you.",
      pass_threshold: 0.75,
      memo: "Saving habits set money aside and plan goals; overspending leaves nothing to save.", error_signals: ["ERR_EMS_G7F4A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of saving for a goal in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Decide what you are saving for" },
        { id: "b", text: "Work out how much you need" },
        { id: "c", text: "Put aside a regular amount" },
        { id: "d", text: "Reach your goal and buy the item" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Choose the goal, work out the cost, save regularly, then reach the goal.",
      error_signals: ["ERR_EMS_G7F4A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · Banks and their services
  "EMS.G7.F4.A2": [
    MC("What is one main job of a bank?", ["To keep people's money safe", "To spend people's money", "To give money away for free", "To hide money forever"], "To keep people's money safe",
      "Banks keep money safe and allow people to save and make payments.", "ERR_EMS_G7F4A2_SAFE", 1),
    MC("What is 'interest' that a bank pays on savings?", ["Extra money the bank pays you for saving", "A fee you pay the bank", "A type of tax", "Money you owe"], "Extra money the bank pays you for saving",
      "Interest is the reward the bank pays you for keeping savings with them.", "ERR_EMS_G7F4A2_INTEREST", 2),
    MC("Which is a service banks provide?", ["Helping people make payments", "Selling groceries", "Cutting hair", "Fixing cars"], "Helping people make payments",
      "Banks help people pay, save and borrow — not sell groceries or cut hair.", "ERR_EMS_G7F4A2_SERVICE", 1),
    MC("Why might you keep savings in a bank instead of at home?", ["It is safer and can earn interest", "It is more dangerous", "It loses value faster", "Banks refuse savings"], "It is safer and can earn interest",
      "A bank is safer than home and may pay interest on your savings.", "ERR_EMS_G7F4A2_WHY", 2),
    MC("A bank can lend money to customers. This service is called giving a ____.", ["loan", "gift", "tax", "wage"], "loan",
      "When a bank lends money that must be repaid, it gives a loan.", "ERR_EMS_G7F4A2_LOAN", 1),
    MC("Using a bank card to pay in shops is an example of a bank's ____ service.", ["payment", "farming", "cooking", "building"], "payment",
      "Cards and electronic payments are part of a bank's payment services.", "ERR_EMS_G7F4A2_PAYMENT", 1),
    MC("Which of these does a bank NOT usually do?", ["Sell fresh vegetables", "Keep money safe", "Pay interest on savings", "Offer loans"], "Sell fresh vegetables",
      "Selling vegetables is not a bank service; the others are.", "ERR_EMS_G7F4A2_NOT", 2),
    MC("Interest paid by a bank is good for savers because it ____.", ["grows their savings over time", "shrinks their savings", "is a fee they pay", "removes their money"], "grows their savings over time",
      "Interest adds to savings, helping them grow over time.", "ERR_EMS_G7F4A2_GROW", 2),
    MC("When a bank lends you money, you usually pay back the loan plus ____.", ["interest", "nothing", "a gift", "more loans only"], "interest",
      "Borrowers repay the loan plus interest — the cost of borrowing.", "ERR_EMS_G7F4A2_REPAY", 2),
    MC("Which statement about banks is correct?", ["Banks keep money safe, pay interest on savings and offer loans", "Banks only hide money", "Banks never lend money", "Banks sell food"], "Banks keep money safe, pay interest on savings and offer loans",
      "Banks store money, pay interest and provide loans and payment services.", "ERR_EMS_G7F4A2_CORRECT", 3),
    TF("Banks keep people's money safe.", "True",
      "Keeping money safe is a core banking service.", "ERR_EMS_G7F4A2_TF1", 1),
    TF("Banks pay interest to people who save with them.", "True",
      "Savers usually earn interest on money kept in the bank.", "ERR_EMS_G7F4A2_TF2", 1),
    TF("Banks give money to everyone for free.", "False",
      "Banks lend money that must be repaid, usually with interest — not free gifts.", "ERR_EMS_G7F4A2_TF3", 1),
    TF("Making payments and offering loans are bank services.", "True",
      "Payments and loans are common services banks provide.", "ERR_EMS_G7F4A2_TF4", 1),
    CLOZE("Extra money the bank pays you for saving is called ____.", ["interest", "rent", "tax", "fee"], "interest",
      "Interest is the bank's reward for your savings.", "ERR_EMS_G7F4A2_CL1", 1),
    CLOZE("Money a bank lends that must be repaid is a ____.", ["loan", "gift", "wage", "saving"], "loan",
      "A loan is borrowed money that must be repaid.", "ERR_EMS_G7F4A2_CL2", 1),
    CLOZE("Keeping your money in a bank is ____ than keeping it at home.", ["safer", "riskier", "slower", "poorer"], "safer",
      "Banks are safer than keeping cash at home.", "ERR_EMS_G7F4A2_CL3", 1),
    CLOZE("Helping customers pay for things with cards is a bank ____ service.", ["payment", "farming", "cooking", "cleaning"], "payment",
      "Card and electronic payments are bank payment services.", "ERR_EMS_G7F4A2_CL4", 2),
    {
      question: "Sort each item into 'Bank service' or 'Not a bank service'.",
      input_type: "sort-buckets",
      buckets: [{ id: "service", label: "Bank service" }, { id: "not", label: "Not a bank service" }],
      items: [
        { id: "i1", text: "Keeping savings safe", correct_bucket: "service" },
        { id: "i2", text: "Selling vegetables", correct_bucket: "not" },
        { id: "i3", text: "Giving loans", correct_bucket: "service" },
        { id: "i4", text: "Cutting hair", correct_bucket: "not" },
      ],
      expected: "Keeping savings and giving loans are bank services; selling vegetables and cutting hair are not.",
      pass_threshold: 0.75,
      memo: "Banks save, lend and help with payments; they don't sell groceries or cut hair.", error_signals: ["ERR_EMS_G7F4A2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of earning interest on savings in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "You deposit money into a savings account" },
        { id: "b", text: "The bank keeps your money safe" },
        { id: "c", text: "The bank adds interest over time" },
        { id: "d", text: "Your savings grow to a larger amount" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Deposit, the bank safeguards it, interest is added, and savings grow.",
      error_signals: ["ERR_EMS_G7F4A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Opening accounts and savings schemes
  "EMS.G7.F4.A3": [
    MC("What is a savings account?", ["A bank account used to keep and grow savings", "A loan you must repay", "A shop's till", "A tax form"], "A bank account used to keep and grow savings",
      "A savings account holds your savings safely and usually earns interest.", "ERR_EMS_G7F4A3_DEF", 1),
    MC("What is a stokvel?", ["A community savings group where members contribute regularly", "A type of bank loan", "A government tax", "A shop"], "A community savings group where members contribute regularly",
      "A stokvel is a community savings scheme where members pool money regularly.", "ERR_EMS_G7F4A3_STOKVEL", 1),
    MC("Which is usually needed to open a bank account?", ["Identification documents", "A car", "A business", "A loan"], "Identification documents",
      "Banks usually require ID to open an account.", "ERR_EMS_G7F4A3_ID", 2),
    MC("A benefit of a stokvel is that ____.", ["members save together and support each other", "members lose their money", "no one ever contributes", "it replaces all banks"], "members save together and support each other",
      "Stokvels help members save collectively and support one another.", "ERR_EMS_G7F4A3_BENEFIT", 2),
    MC("Which is a formal financial institution?", ["A bank", "A spaza shop", "A taxi", "A market stall"], "A bank",
      "A bank is a formal financial institution; the others are not.", "ERR_EMS_G7F4A3_INSTITUTION", 1),
    MC("Why might someone join a community savings scheme?", ["To save with others towards shared goals", "To avoid saving", "To lose money on purpose", "To pay more tax"], "To save with others towards shared goals",
      "Community schemes help people save together, often for shared or seasonal needs.", "ERR_EMS_G7F4A3_WHY", 2),
    MC("Opening a savings account allows you to ____.", ["keep money safe and earn interest", "spend more than you have", "avoid all banks", "lose your savings"], "keep money safe and earn interest",
      "A savings account safeguards money and usually earns interest.", "ERR_EMS_G7F4A3_OPEN", 1),
    MC("Which is a difference between a bank and a stokvel?", ["A bank is a formal institution; a stokvel is a community group", "They are exactly the same", "A stokvel is a government department", "A bank never keeps money"], "A bank is a formal institution; a stokvel is a community group",
      "Banks are formal institutions; stokvels are informal community savings groups.", "ERR_EMS_G7F4A3_DIFF", 2),
    MC("Saving through both a bank and a stokvel shows that ____.", ["there are many ways to save", "saving is impossible", "only banks can hold money", "saving must be done alone"], "there are many ways to save",
      "People can save in many ways — banks, stokvels and other schemes.", "ERR_EMS_G7F4A3_MANY", 2),
    MC("A group of neighbours each pay R200 a month into a shared fund and take turns receiving the total. This is a ____.", ["stokvel", "bank loan", "tax", "salary"], "stokvel",
      "Members contributing and taking turns to receive the pool is a classic stokvel.", "ERR_EMS_G7F4A3_EXAMPLE", 3),
    TF("A savings account helps keep money safe and can earn interest.", "True",
      "Savings accounts safeguard money and usually pay interest.", "ERR_EMS_G7F4A3_TF1", 1),
    TF("A stokvel is a community savings scheme.", "True",
      "A stokvel is a group savings arrangement in the community.", "ERR_EMS_G7F4A3_TF2", 1),
    TF("You usually need identification to open a bank account.", "True",
      "Banks generally require ID documents to open an account.", "ERR_EMS_G7F4A3_TF3", 1),
    TF("There is only one possible way to save money.", "False",
      "There are many ways to save — banks, stokvels and other schemes.", "ERR_EMS_G7F4A3_TF4", 1),
    CLOZE("A bank account used to keep and grow savings is a ____ account.", ["savings", "loan", "tax", "shop"], "savings",
      "A savings account holds and grows your savings.", "ERR_EMS_G7F4A3_CL1", 1),
    CLOZE("A community savings group is called a ____.", ["stokvel", "bank", "tax", "loan"], "stokvel",
      "A stokvel is a community savings scheme.", "ERR_EMS_G7F4A3_CL2", 1),
    CLOZE("To open a bank account you usually need ____ documents.", ["identification", "cooking", "farming", "building"], "identification",
      "ID documents are normally needed to open an account.", "ERR_EMS_G7F4A3_CL3", 2),
    CLOZE("A bank is a formal financial ____.", ["institution", "stokvel", "market", "shop"], "institution",
      "Banks are formal financial institutions.", "ERR_EMS_G7F4A3_CL4", 1),
    {
      question: "Sort each into 'Formal (bank/institution)' or 'Community scheme'.",
      input_type: "sort-buckets",
      buckets: [{ id: "formal", label: "Formal institution" }, { id: "community", label: "Community scheme" }],
      items: [
        { id: "i1", text: "A commercial bank", correct_bucket: "formal" },
        { id: "i2", text: "A neighbourhood stokvel", correct_bucket: "community" },
        { id: "i3", text: "A savings account at a bank", correct_bucket: "formal" },
        { id: "i4", text: "A burial society savings group", correct_bucket: "community" },
      ],
      expected: "Banks and bank accounts are formal; stokvels and burial societies are community schemes.",
      pass_threshold: 0.75,
      memo: "Banks are formal institutions; stokvels and burial societies are community savings schemes.", error_signals: ["ERR_EMS_G7F4A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of opening and using a savings account in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Take your ID to the bank" },
        { id: "b", text: "Open a savings account" },
        { id: "c", text: "Deposit money regularly" },
        { id: "d", text: "Earn interest and watch your savings grow" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Bring ID, open the account, deposit regularly, and earn interest as savings grow.",
      error_signals: ["ERR_EMS_G7F4A3_SEQ"], difficulty: 1,
    },
  ],
};

export default G7B;
