// ─── EMS SP — Grade 9 authored pools (C): Entrepreneurship ────────────────────
// Strand: Entrepreneurship (CAPS G9). Tap-only. Recipe: 10 MC · 4 TF · 4 CLOZE ·
// 1 sequence · 1 sort-buckets = 20.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9C = {
  // ─── B1 · Term 2 — Sectors of the economy ──────────────────────────────────
  // A1 · Primary, secondary and tertiary sectors
  "EMS.G9.B1.A1": [
    MC("What does the primary sector do?", ["Takes raw materials from nature", "Makes finished products", "Provides services", "Only sells imported goods"], "Takes raw materials from nature",
      "The primary sector gathers raw materials — farming, mining, fishing, forestry.", "ERR_EMS_G9B1A1_PRIMARY", 1),
    MC("What does the secondary sector do?", ["Turns raw materials into finished products", "Mines minerals", "Provides services", "Grows crops"], "Turns raw materials into finished products",
      "The secondary sector manufactures — making goods from raw materials.", "ERR_EMS_G9B1A1_SECONDARY", 1),
    MC("What does the tertiary sector do?", ["Provides services", "Mines coal", "Grows wheat", "Makes steel"], "Provides services",
      "The tertiary sector provides services — shops, banks, transport, tourism.", "ERR_EMS_G9B1A1_TERTIARY", 1),
    MC("Mining is part of the ____ sector.", ["primary", "secondary", "tertiary", "no"], "primary",
      "Mining gathers raw materials, so it is primary.", "ERR_EMS_G9B1A1_MINING", 1),
    MC("A factory making cars is part of the ____ sector.", ["secondary", "primary", "tertiary", "no"], "secondary",
      "Manufacturing cars is secondary-sector activity.", "ERR_EMS_G9B1A1_FACTORY", 1),
    MC("A bank is part of the ____ sector.", ["tertiary", "primary", "secondary", "no"], "tertiary",
      "Banking is a service, so it is tertiary.", "ERR_EMS_G9B1A1_BANK", 1),
    MC("Which is a primary-sector activity?", ["Catching fish at sea", "Baking bread", "Selling insurance", "Repairing phones"], "Catching fish at sea",
      "Fishing gathers a raw material — primary sector.", "ERR_EMS_G9B1A1_FISH", 2),
    MC("Which is a secondary-sector activity?", ["Turning wheat into flour and bread", "Growing the wheat", "Driving a delivery taxi", "Selling tickets"], "Turning wheat into flour and bread",
      "Processing wheat into bread is manufacturing — secondary.", "ERR_EMS_G9B1A1_BREAD", 2),
    MC("Which is a tertiary-sector activity?", ["A tour guide showing visitors around", "Mining gold", "Farming maize", "Making furniture"], "A tour guide showing visitors around",
      "Tour guiding is a service — tertiary sector.", "ERR_EMS_G9B1A1_GUIDE", 2),
    MC("Which order matches the sectors to their work?", ["Primary–raw materials, secondary–manufacturing, tertiary–services", "Primary–services, secondary–farming, tertiary–mining", "All three do the same", "Primary–manufacturing only"], "Primary–raw materials, secondary–manufacturing, tertiary–services",
      "Primary gathers, secondary makes, tertiary serves.", "ERR_EMS_G9B1A1_MATCH", 2),
    TF("The primary sector takes raw materials from nature.", "True",
      "Farming, mining and fishing are primary-sector activities.", "ERR_EMS_G9B1A1_TF1", 1),
    TF("The secondary sector turns raw materials into finished products.", "True",
      "Manufacturing is the secondary sector.", "ERR_EMS_G9B1A1_TF2", 1),
    TF("The tertiary sector mines minerals.", "False",
      "Mining is primary; the tertiary sector provides services.", "ERR_EMS_G9B1A1_TF3", 1),
    TF("Shops and banks are part of the tertiary sector.", "True",
      "Shops and banks provide services — tertiary sector.", "ERR_EMS_G9B1A1_TF4", 1),
    CLOZE("The sector that takes raw materials from nature is the ____ sector.", ["primary", "secondary", "tertiary", "extra"], "primary",
      "Primary gathers raw materials.", "ERR_EMS_G9B1A1_CL1", 1),
    CLOZE("The sector that makes finished products is the ____ sector.", ["secondary", "primary", "tertiary", "extra"], "secondary",
      "Secondary manufactures goods.", "ERR_EMS_G9B1A1_CL2", 1),
    CLOZE("The sector that provides services is the ____ sector.", ["tertiary", "primary", "secondary", "extra"], "tertiary",
      "Tertiary provides services.", "ERR_EMS_G9B1A1_CL3", 1),
    CLOZE("Farming and mining belong to the ____ sector.", ["primary", "secondary", "tertiary", "service"], "primary",
      "Farming and mining are primary-sector activities.", "ERR_EMS_G9B1A1_CL4", 1),
    {
      question: "Sort each business into 'Primary', 'Secondary' or 'Tertiary' sector.",
      input_type: "sort-buckets",
      buckets: [{ id: "primary", label: "Primary" }, { id: "secondary", label: "Secondary" }, { id: "tertiary", label: "Tertiary" }],
      items: [
        { id: "i1", text: "A maize farm", correct_bucket: "primary" },
        { id: "i2", text: "A bakery making bread", correct_bucket: "secondary" },
        { id: "i3", text: "A bank", correct_bucket: "tertiary" },
        { id: "i4", text: "A gold mine", correct_bucket: "primary" },
      ],
      expected: "Farms and mines are primary; the bakery is secondary; the bank is tertiary.",
      pass_threshold: 0.75,
      memo: "Primary gathers, secondary makes, tertiary serves.", error_signals: ["ERR_EMS_G9B1A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the sectors in the order a product passes through them.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Primary: wheat is grown" },
        { id: "b", text: "Secondary: wheat is made into bread" },
        { id: "c", text: "Tertiary: a shop sells the bread" },
        { id: "d", text: "A delivery service brings it to the customer" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Raw material (primary) → manufacture (secondary) → sold and delivered (tertiary).",
      error_signals: ["ERR_EMS_G9B1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · How the sectors connect
  "EMS.G9.B1.A2": [
    MC("How are the three sectors related?", ["They depend on each other in a chain", "They never interact", "They compete to do the same job", "They are all the same sector"], "They depend on each other in a chain",
      "Each sector relies on the others — raw materials, manufacturing and services link up.", "ERR_EMS_G9B1A2_LINK", 1),
    MC("The secondary sector depends on the primary sector for ____.", ["raw materials", "services only", "nothing", "tourists"], "raw materials",
      "Manufacturers need raw materials from the primary sector.", "ERR_EMS_G9B1A2_RAW", 2),
    MC("The tertiary sector helps the others by ____.", ["selling, transporting and financing their goods", "mining their minerals", "growing their crops", "doing nothing"], "selling, transporting and financing their goods",
      "Services like retail, transport and banking support the other sectors.", "ERR_EMS_G9B1A2_SERVICES", 2),
    MC("Which skills are most needed in the tertiary sector?", ["Service and people skills", "Only mining skills", "Only farming skills", "No skills"], "Service and people skills",
      "Services rely heavily on people and customer-service skills.", "ERR_EMS_G9B1A2_SKILLS", 2),
    MC("Using resources sustainably across the sectors means ____.", ["not wasting them so they last", "using them up fast", "polluting freely", "ignoring waste"], "not wasting them so they last",
      "Sustainable use across sectors protects resources for the future.", "ERR_EMS_G9B1A2_SUSTAIN", 2),
    MC("If the primary sector fails to supply materials, the secondary sector will ____.", ["struggle to manufacture", "produce more", "be unaffected", "become primary"], "struggle to manufacture",
      "Without raw materials, manufacturing cannot continue.", "ERR_EMS_G9B1A2_FAIL", 2),
    MC("A car's journey shows the link because ____.", ["mined metal is made into a car, then sold by a dealer", "a car grows on a farm", "a car is only a service", "a car needs no sectors"], "mined metal is made into a car, then sold by a dealer",
      "Mining (primary) → manufacture (secondary) → dealership (tertiary).", "ERR_EMS_G9B1A2_CAR", 3),
    MC("Why does a strong tertiary sector matter?", ["It connects producers to customers through services", "It replaces all production", "It removes all jobs", "It has no role"], "It connects producers to customers through services",
      "Services link producers and consumers and keep the economy moving.", "ERR_EMS_G9B1A2_WHY", 2),
    MC("Which best shows the interrelationship of the sectors?", ["Each sector provides what the next needs", "Each sector works completely alone", "Only one sector matters", "The sectors are unrelated"], "Each sector provides what the next needs",
      "The sectors form a chain, each supplying the next.", "ERR_EMS_G9B1A2_CHAIN", 2),
    MC("Sustainable use of resources in all three sectors helps ____.", ["future generations and long-term growth", "waste resources faster", "stop the economy", "increase pollution"], "future generations and long-term growth",
      "Sustainability across sectors protects the future and supports growth.", "ERR_EMS_G9B1A2_FUTURE", 2),
    TF("The three sectors depend on each other.", "True",
      "Each sector relies on the others in a chain.", "ERR_EMS_G9B1A2_TF1", 1),
    TF("The secondary sector needs raw materials from the primary sector.", "True",
      "Manufacturers depend on primary-sector materials.", "ERR_EMS_G9B1A2_TF2", 1),
    TF("The tertiary sector mines and farms for the others.", "False",
      "The tertiary sector provides services; mining and farming are primary.", "ERR_EMS_G9B1A2_TF3", 1),
    TF("Sustainable resource use across sectors protects the future.", "True",
      "Sustainability keeps resources available for the future.", "ERR_EMS_G9B1A2_TF4", 1),
    CLOZE("The secondary sector depends on the primary sector for ____ materials.", ["raw", "service", "finished", "no"], "raw",
      "Manufacturers need raw materials.", "ERR_EMS_G9B1A2_CL1", 2),
    CLOZE("The tertiary sector ____ goods made by the secondary sector.", ["sells", "mines", "grows", "ignores"], "sells",
      "Services like retail sell manufactured goods.", "ERR_EMS_G9B1A2_CL2", 2),
    CLOZE("The three sectors are linked in a ____.", ["chain", "circle of one", "single shop", "void"], "chain",
      "They form a chain, each supplying the next.", "ERR_EMS_G9B1A2_CL3", 1),
    CLOZE("Using resources without wasting them across sectors is using them ____.", ["sustainably", "wastefully", "carelessly", "harmfully"], "sustainably",
      "Sustainable use protects resources.", "ERR_EMS_G9B1A2_CL4", 2),
    {
      question: "Sort each role to the sector that provides it in the chain.",
      input_type: "sort-buckets",
      buckets: [{ id: "primary", label: "Primary provides" }, { id: "secondary", label: "Secondary provides" }, { id: "tertiary", label: "Tertiary provides" }],
      items: [
        { id: "i1", text: "Raw cotton from a farm", correct_bucket: "primary" },
        { id: "i2", text: "Cotton made into shirts", correct_bucket: "secondary" },
        { id: "i3", text: "A shop selling the shirts", correct_bucket: "tertiary" },
        { id: "i4", text: "Transport delivering the shirts", correct_bucket: "tertiary" },
      ],
      expected: "Raw cotton is primary; making shirts is secondary; selling and transporting them is tertiary.",
      pass_threshold: 0.75,
      memo: "Primary supplies materials, secondary makes goods, tertiary sells and moves them.", error_signals: ["ERR_EMS_G9B1A2_SORT"], difficulty: 3,
    },
    {
      question: "Put a product's path through the connected sectors in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Primary sector supplies raw materials" },
        { id: "b", text: "Secondary sector manufactures the product" },
        { id: "c", text: "Tertiary sector transports and sells it" },
        { id: "d", text: "The customer buys the finished product" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Materials → manufacture → sell/transport → customer buys.",
      error_signals: ["ERR_EMS_G9B1A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── B2 · Term 3 — Functions of a business ─────────────────────────────────
  // A1 · The eight business functions
  "EMS.G9.B2.A1": [
    MC("What are the 'functions of a business'?", ["The different areas of work a business must carry out", "The owners of a business", "The customers of a business", "The taxes a business pays"], "The different areas of work a business must carry out",
      "Business functions are the main areas of activity, like marketing and finance.", "ERR_EMS_G9B2A1_DEF", 1),
    MC("The function that handles buying supplies is ____.", ["purchasing", "marketing", "finance", "production"], "purchasing",
      "The purchasing function buys the supplies the business needs.", "ERR_EMS_G9B2A1_PURCHASE", 1),
    MC("The function that handles promoting and selling is ____.", ["marketing", "purchasing", "finance", "administration"], "marketing",
      "Marketing promotes and sells the business's products.", "ERR_EMS_G9B2A1_MARKETING", 1),
    MC("The function that manages money is ____.", ["finance", "production", "marketing", "purchasing"], "finance",
      "The finance function manages the business's money.", "ERR_EMS_G9B2A1_FINANCE", 1),
    MC("The function that makes the goods is ____.", ["production", "finance", "public relations", "administration"], "production",
      "Production creates the goods (or delivers the service).", "ERR_EMS_G9B2A1_PRODUCTION", 1),
    MC("The function that manages staff is ____.", ["human resources", "purchasing", "production", "finance"], "human resources",
      "Human resources manages the people who work in the business.", "ERR_EMS_G9B2A1_HR", 1),
    MC("The function that handles the business's image and reputation is ____.", ["public relations", "production", "purchasing", "finance"], "public relations",
      "Public relations manages the business's image and relationships.", "ERR_EMS_G9B2A1_PR", 2),
    MC("The function that handles records and office systems is ____.", ["administration", "marketing", "production", "purchasing"], "administration",
      "Administration handles records, paperwork and office systems.", "ERR_EMS_G9B2A1_ADMIN", 2),
    MC("Identifying and reducing dangers to the business is the ____ function.", ["risk management", "marketing", "purchasing", "production"], "risk management",
      "Risk management identifies and reduces risks to the business.", "ERR_EMS_G9B2A1_RISK", 2),
    MC("Why does a business need several functions?", ["Different areas of work must all be done for it to run", "To waste time", "To avoid all work", "To confuse customers"], "Different areas of work must all be done for it to run",
      "Each function covers a needed area of work for the business to operate.", "ERR_EMS_G9B2A1_WHY", 2),
    TF("Business functions are the main areas of work a business carries out.", "True",
      "Functions are areas like marketing, finance and production.", "ERR_EMS_G9B2A1_TF1", 1),
    TF("The marketing function promotes and sells products.", "True",
      "Marketing promotes and sells.", "ERR_EMS_G9B2A1_TF2", 1),
    TF("The finance function makes the goods in the factory.", "False",
      "Production makes the goods; finance manages money.", "ERR_EMS_G9B2A1_TF3", 1),
    TF("Human resources manages the people who work in the business.", "True",
      "HR manages staff.", "ERR_EMS_G9B2A1_TF4", 1),
    CLOZE("The function that buys supplies is ____.", ["purchasing", "marketing", "finance", "production"], "purchasing",
      "Purchasing buys supplies.", "ERR_EMS_G9B2A1_CL1", 1),
    CLOZE("The function that manages money is ____.", ["finance", "purchasing", "production", "marketing"], "finance",
      "Finance manages money.", "ERR_EMS_G9B2A1_CL2", 1),
    CLOZE("The function that manages staff is human ____.", ["resources", "money", "products", "sales"], "resources",
      "Human resources manages people.", "ERR_EMS_G9B2A1_CL3", 1),
    CLOZE("The function that makes the goods is ____.", ["production", "finance", "purchasing", "admin"], "production",
      "Production makes the goods.", "ERR_EMS_G9B2A1_CL4", 1),
    {
      question: "Match each task to its business function.",
      input_type: "sort-buckets",
      buckets: [{ id: "marketing", label: "Marketing" }, { id: "finance", label: "Finance" }, { id: "hr", label: "Human resources" }, { id: "production", label: "Production" }],
      items: [
        { id: "i1", text: "Advertising and selling products", correct_bucket: "marketing" },
        { id: "i2", text: "Managing the money and budgets", correct_bucket: "finance" },
        { id: "i3", text: "Hiring and training staff", correct_bucket: "hr" },
        { id: "i4", text: "Making the goods", correct_bucket: "production" },
      ],
      expected: "Advertising = marketing; money = finance; staff = HR; making goods = production.",
      pass_threshold: 0.75,
      memo: "Each function owns its area: marketing sells, finance handles money, HR handles people, production makes goods.", error_signals: ["ERR_EMS_G9B2A1_SORT"], difficulty: 3,
    },
    {
      question: "Put these functions in the order a product often moves through them.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Purchasing buys raw materials" },
        { id: "b", text: "Production makes the goods" },
        { id: "c", text: "Marketing promotes and sells them" },
        { id: "d", text: "Finance records the money from sales" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Buy materials → make goods → market and sell → record the money.",
      error_signals: ["ERR_EMS_G9B2A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Characteristics of each function
  "EMS.G9.B2.A2": [
    MC("A characteristic of the marketing function is that it ____.", ["focuses on customers and selling", "makes the goods", "manages staff pay", "buys raw materials"], "focuses on customers and selling",
      "Marketing is customer- and sales-focused.", "ERR_EMS_G9B2A2_MARKETING", 1),
    MC("A characteristic of the finance function is that it ____.", ["keeps records of money and plans budgets", "advertises products", "hires staff", "mines minerals"], "keeps records of money and plans budgets",
      "Finance tracks money and plans budgets.", "ERR_EMS_G9B2A2_FINANCE", 1),
    MC("A characteristic of the production function is that it ____.", ["focuses on making goods efficiently", "sells to customers", "manages the company image", "pays the tax"], "focuses on making goods efficiently",
      "Production focuses on making goods efficiently.", "ERR_EMS_G9B2A2_PRODUCTION", 1),
    MC("A characteristic of human resources is that it ____.", ["looks after the people in the business", "makes the products", "buys stock", "advertises"], "looks after the people in the business",
      "HR looks after staff — hiring, training and wellbeing.", "ERR_EMS_G9B2A2_HR", 1),
    MC("A characteristic of public relations is that it ____.", ["builds the business's image and relationships", "makes the goods", "handles only money", "buys materials"], "builds the business's image and relationships",
      "PR manages image and relationships with the public.", "ERR_EMS_G9B2A2_PR", 2),
    MC("A characteristic of the purchasing function is that it ____.", ["finds good suppliers and buys at the right price", "sells to customers", "makes the goods", "pays salaries"], "finds good suppliers and buys at the right price",
      "Purchasing sources suppliers and buys inputs well.", "ERR_EMS_G9B2A2_PURCHASE", 2),
    MC("A characteristic of administration is that it ____.", ["keeps records and runs office systems", "makes goods", "advertises", "mines"], "keeps records and runs office systems",
      "Administration keeps records and runs office systems.", "ERR_EMS_G9B2A2_ADMIN", 2),
    MC("A characteristic of risk management is that it ____.", ["spots and reduces dangers to the business", "sells products", "hires staff", "makes goods"], "spots and reduces dangers to the business",
      "Risk management identifies and reduces risks.", "ERR_EMS_G9B2A2_RISK", 2),
    MC("Each function has its own ____.", ["focus and tasks", "owner", "country", "currency"], "focus and tasks",
      "Each function has a particular focus and set of tasks.", "ERR_EMS_G9B2A2_FOCUS", 1),
    MC("Which best describes the functions together?", ["Each has a different focus, but all support the business", "They all do the same job", "Only one matters", "They work against each other"], "Each has a different focus, but all support the business",
      "Functions differ in focus but together keep the business running.", "ERR_EMS_G9B2A2_TOGETHER", 2),
    TF("Marketing focuses on customers and selling.", "True",
      "Marketing is customer- and sales-focused.", "ERR_EMS_G9B2A2_TF1", 1),
    TF("Finance focuses on managing the business's money.", "True",
      "Finance handles money and budgets.", "ERR_EMS_G9B2A2_TF2", 1),
    TF("Production focuses on advertising the goods.", "False",
      "Production focuses on making goods; advertising is marketing.", "ERR_EMS_G9B2A2_TF3", 1),
    TF("Human resources focuses on the people in the business.", "True",
      "HR looks after the staff.", "ERR_EMS_G9B2A2_TF4", 1),
    CLOZE("The ____ function focuses on customers and selling.", ["marketing", "finance", "production", "purchasing"], "marketing",
      "Marketing focuses on customers and sales.", "ERR_EMS_G9B2A2_CL1", 1),
    CLOZE("The ____ function keeps records of money and budgets.", ["finance", "marketing", "production", "hr"], "finance",
      "Finance tracks money and budgets.", "ERR_EMS_G9B2A2_CL2", 1),
    CLOZE("The ____ function looks after the people in the business.", ["human-resources", "marketing", "production", "purchasing"], "human-resources",
      "HR looks after people.", "ERR_EMS_G9B2A2_CL3", 1),
    CLOZE("The ____ function focuses on making goods efficiently.", ["production", "finance", "marketing", "admin"], "production",
      "Production makes goods efficiently.", "ERR_EMS_G9B2A2_CL4", 1),
    {
      question: "Match each characteristic to its function.",
      input_type: "sort-buckets",
      buckets: [{ id: "purchasing", label: "Purchasing" }, { id: "pr", label: "Public relations" }, { id: "admin", label: "Administration" }, { id: "risk", label: "Risk management" }],
      items: [
        { id: "i1", text: "Finds suppliers and buys inputs", correct_bucket: "purchasing" },
        { id: "i2", text: "Builds the business's image", correct_bucket: "pr" },
        { id: "i3", text: "Keeps records and runs the office", correct_bucket: "admin" },
        { id: "i4", text: "Spots and reduces dangers", correct_bucket: "risk" },
      ],
      expected: "Buying inputs = purchasing; image = PR; records/office = administration; reducing dangers = risk management.",
      pass_threshold: 0.75,
      memo: "Each function has a distinct focus — match the task to the right one.", error_signals: ["ERR_EMS_G9B2A2_SORT"], difficulty: 3,
    },
    {
      question: "Put a new product launch through the functions in a sensible order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Purchasing buys the materials" },
        { id: "b", text: "Production makes the product" },
        { id: "c", text: "Marketing advertises it" },
        { id: "d", text: "Public relations manages the launch image" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Buy → make → advertise → manage the public image of the launch.",
      error_signals: ["ERR_EMS_G9B2A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Role and importance of the functions
  "EMS.G9.B2.A3": [
    MC("Why are all the business functions important?", ["The business needs every area working for it to succeed", "Only one function matters", "Functions are a waste", "They stop the business"], "The business needs every area working for it to succeed",
      "Each function covers a needed area; together they make the business work.", "ERR_EMS_G9B2A3_WHY", 1),
    MC("If the finance function fails, the business may ____.", ["run out of money or lose track of it", "make more profit", "need no money", "improve automatically"], "run out of money or lose track of it",
      "Without finance, money is mismanaged and the business can fail.", "ERR_EMS_G9B2A3_FINANCE_FAIL", 2),
    MC("If marketing fails, the business may ____.", ["struggle to attract customers and sell", "sell more easily", "need no customers", "grow faster"], "struggle to attract customers and sell",
      "Poor marketing means fewer customers and sales.", "ERR_EMS_G9B2A3_MARKETING_FAIL", 2),
    MC("The functions must ____ for the business to run smoothly.", ["work together as a team", "compete against each other", "ignore each other", "all do the same task"], "work together as a team",
      "Functions must coordinate like a team.", "ERR_EMS_G9B2A3_TEAM", 2),
    MC("Good human resources helps a business by ____.", ["keeping skilled, motivated staff", "removing all staff", "ignoring training", "lowering morale"], "keeping skilled, motivated staff",
      "Strong HR keeps capable, motivated employees.", "ERR_EMS_G9B2A3_HR", 2),
    MC("Why does production matter to the whole business?", ["Without goods to sell, there is nothing to earn from", "Production is unrelated to sales", "Goods sell themselves", "Production has no role"], "Without goods to sell, there is nothing to earn from",
      "If nothing is produced, there is nothing to sell or earn from.", "ERR_EMS_G9B2A3_PRODUCTION", 2),
    MC("If purchasing buys poor or overpriced materials, ____.", ["production costs rise and quality may drop", "profit always rises", "nothing changes", "sales always rise"], "production costs rise and quality may drop",
      "Bad purchasing raises costs and can hurt quality.", "ERR_EMS_G9B2A3_PURCHASE", 2),
    MC("Risk management is important because it ____.", ["protects the business from avoidable losses", "creates more dangers", "wastes money", "has no value"], "protects the business from avoidable losses",
      "Risk management reduces avoidable losses and threats.", "ERR_EMS_G9B2A3_RISK", 2),
    MC("Which statement is correct about the functions?", ["Each plays a role and they support one another", "Only marketing matters", "Functions never connect", "One function does everything"], "Each plays a role and they support one another",
      "All functions matter and support each other.", "ERR_EMS_G9B2A3_CORRECT", 1),
    MC("A business with weak coordination between functions may ____.", ["work inefficiently and lose customers", "always succeed", "need no functions", "grow effortlessly"], "work inefficiently and lose customers",
      "Poor coordination causes inefficiency and lost customers.", "ERR_EMS_G9B2A3_COORD", 3),
    TF("All the business functions are important for success.", "True",
      "Each function covers a needed area of the business.", "ERR_EMS_G9B2A3_TF1", 1),
    TF("The functions should work together as a team.", "True",
      "Coordination between functions keeps the business running.", "ERR_EMS_G9B2A3_TF2", 1),
    TF("Only the marketing function matters; the rest can be ignored.", "False",
      "Every function plays an important role; none can simply be ignored.", "ERR_EMS_G9B2A3_TF3", 1),
    TF("Good risk management can protect a business from losses.", "True",
      "Risk management reduces avoidable losses.", "ERR_EMS_G9B2A3_TF4", 1),
    CLOZE("The business functions must work ____ for the business to run well.", ["together", "alone", "against each other", "secretly"], "together",
      "Functions must coordinate as a team.", "ERR_EMS_G9B2A3_CL1", 1),
    CLOZE("If the ____ function fails, the business may run out of money.", ["finance", "marketing", "production", "purchasing"], "finance",
      "Finance manages money; its failure risks running out.", "ERR_EMS_G9B2A3_CL2", 2),
    CLOZE("Without ____, there are no goods to sell.", ["production", "marketing", "admin", "PR"], "production",
      "Production creates the goods to sell.", "ERR_EMS_G9B2A3_CL3", 2),
    CLOZE("Each function plays a ____ in the success of the business.", ["role", "loss", "tax", "debt"], "role",
      "Every function plays an important role.", "ERR_EMS_G9B2A3_CL4", 1),
    {
      question: "Sort each outcome into 'Functions working well' or 'A function failing'.",
      input_type: "sort-buckets",
      buckets: [{ id: "well", label: "Functions working well" }, { id: "fail", label: "A function failing" }],
      items: [
        { id: "i1", text: "Products are made and sold smoothly", correct_bucket: "well" },
        { id: "i2", text: "The business runs out of money", correct_bucket: "fail" },
        { id: "i3", text: "Staff are skilled and motivated", correct_bucket: "well" },
        { id: "i4", text: "No customers because of poor marketing", correct_bucket: "fail" },
      ],
      expected: "Smooth production/sales and motivated staff show functions working; running out of money or no customers shows a function failing.",
      pass_threshold: 0.75,
      memo: "Healthy functions = smooth operations; a failing function shows up as money, staff or customer problems.", error_signals: ["ERR_EMS_G9B2A3_SORT"], difficulty: 2,
    },
    {
      question: "Put this chain of failure in order when one function breaks down.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The finance function loses track of money" },
        { id: "b", text: "Bills and suppliers are not paid on time" },
        { id: "c", text: "Production and supplies are disrupted" },
        { id: "d", text: "The whole business suffers" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "One weak function (finance) can ripple out and harm the whole business.",
      error_signals: ["ERR_EMS_G9B2A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── B3 · Term 4 — Business plan ───────────────────────────────────────────
  // A1 · What a business plan is
  "EMS.G9.B3.A1": [
    MC("What is a business plan?", ["A written document describing what a business will do and how", "A single advert", "A bank statement", "A tax form"], "A written document describing what a business will do and how",
      "A business plan sets out what the business will do and how it will succeed.", "ERR_EMS_G9B3A1_DEF", 1),
    MC("Why do entrepreneurs write a business plan?", ["To plan the business and show others (like banks) the idea", "To waste paper", "To hide the idea", "To avoid all planning"], "To plan the business and show others (like banks) the idea",
      "A plan organises the idea and helps persuade banks or investors.", "ERR_EMS_G9B3A1_WHY", 1),
    MC("A business plan helps a bank decide whether to ____.", ["lend money to the business", "close the business", "ignore the business", "tax the business more"], "lend money to the business",
      "Banks use the plan to judge whether to lend.", "ERR_EMS_G9B3A1_BANK", 2),
    MC("Which is a component of a business plan?", ["A description of the product or service", "A grocery list only", "A random doodle", "A weather report"], "A description of the product or service",
      "Describing the product or service is a key component.", "ERR_EMS_G9B3A1_COMPONENT", 1),
    MC("A business plan usually includes the business's ____.", ["goals", "favourite colours", "lunch menu", "music playlist"], "goals",
      "Goals are an important component of the plan.", "ERR_EMS_G9B3A1_GOALS", 1),
    MC("Having a clear plan helps an entrepreneur to ____.", ["stay focused and measure progress", "lose direction", "avoid all goals", "ignore customers"], "stay focused and measure progress",
      "A plan keeps the entrepreneur focused and lets them track progress.", "ERR_EMS_G9B3A1_FOCUS", 2),
    MC("A business plan describes both what the business does and ____.", ["how it will do it", "nothing else", "only the owner's age", "only the weather"], "how it will do it",
      "It covers what the business does and how it will achieve it.", "ERR_EMS_G9B3A1_HOW", 2),
    MC("Which would NOT belong in a business plan?", ["A random unrelated holiday photo", "The product description", "The goals", "The marketing plan"], "A random unrelated holiday photo",
      "Unrelated content doesn't belong; product, goals and plans do.", "ERR_EMS_G9B3A1_NOT", 2),
    MC("A good business plan is ____.", ["clear, realistic and well organised", "vague and confusing", "secret and empty", "random"], "clear, realistic and well organised",
      "Good plans are clear, realistic and organised.", "ERR_EMS_G9B3A1_GOOD", 2),
    MC("Which statement is correct?", ["A business plan describes the business and how it will succeed", "A business plan is just one advert", "A business plan has no purpose", "A business plan is a tax return"], "A business plan describes the business and how it will succeed",
      "The plan describes the business and how it aims to succeed.", "ERR_EMS_G9B3A1_CORRECT", 1),
    TF("A business plan is a written document describing the business.", "True",
      "It sets out what the business will do and how.", "ERR_EMS_G9B3A1_TF1", 1),
    TF("Banks may use a business plan to decide whether to lend money.", "True",
      "Plans help banks judge whether to lend.", "ERR_EMS_G9B3A1_TF2", 1),
    TF("A business plan has no purpose and is never used.", "False",
      "A business plan guides the business and informs investors and banks.", "ERR_EMS_G9B3A1_TF3", 1),
    TF("A business plan usually includes the goals of the business.", "True",
      "Goals are a key component.", "ERR_EMS_G9B3A1_TF4", 1),
    CLOZE("A written document describing what a business will do is a business ____.", ["plan", "advert", "receipt", "tax"], "plan",
      "A business plan describes the business.", "ERR_EMS_G9B3A1_CL1", 1),
    CLOZE("Banks may read a business plan before deciding to ____.", ["lend", "close", "ignore", "tax"], "lend",
      "Plans inform lending decisions.", "ERR_EMS_G9B3A1_CL2", 2),
    CLOZE("A business plan describes the product and the business's ____.", ["goals", "snacks", "music", "weather"], "goals",
      "Goals are a key component.", "ERR_EMS_G9B3A1_CL3", 1),
    CLOZE("A good business plan is clear and ____.", ["realistic", "vague", "secret", "random"], "realistic",
      "Good plans are clear and realistic.", "ERR_EMS_G9B3A1_CL4", 2),
    {
      question: "Sort each item into 'Belongs in a business plan' or 'Does not belong'.",
      input_type: "sort-buckets",
      buckets: [{ id: "belongs", label: "Belongs in a business plan" }, { id: "not", label: "Does not belong" }],
      items: [
        { id: "i1", text: "A description of the product", correct_bucket: "belongs" },
        { id: "i2", text: "The business goals", correct_bucket: "belongs" },
        { id: "i3", text: "An unrelated holiday photo", correct_bucket: "not" },
        { id: "i4", text: "The marketing plan", correct_bucket: "belongs" },
      ],
      expected: "Product description, goals and marketing plan belong; unrelated photos do not.",
      pass_threshold: 0.75,
      memo: "A plan holds product, goals and plans — not unrelated content.", error_signals: ["ERR_EMS_G9B3A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the use of a business plan in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The entrepreneur has a business idea" },
        { id: "b", text: "They write a business plan" },
        { id: "c", text: "They show it to a bank or investor" },
        { id: "d", text: "They use it to guide and grow the business" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Idea → write the plan → show backers → use it to guide the business.",
      error_signals: ["ERR_EMS_G9B3A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · Format of a business plan
  "EMS.G9.B3.A2": [
    MC("What usually comes first in a business plan?", ["The front cover", "The conclusion", "The SWOT analysis", "The financial plan"], "The front cover",
      "The front cover comes first, then the table of contents and the rest.", "ERR_EMS_G9B3A2_COVER", 1),
    MC("The table of contents helps the reader to ____.", ["find each section easily", "hide the sections", "skip the plan", "pay tax"], "find each section easily",
      "The contents page helps readers navigate the plan.", "ERR_EMS_G9B3A2_CONTENTS", 1),
    MC("Which section describes what the business sells?", ["The description of the product or service", "The conclusion", "The front cover", "The SWOT only"], "The description of the product or service",
      "This section explains the product or service offered.", "ERR_EMS_G9B3A2_PRODUCT", 1),
    MC("The SWOT analysis in a plan looks at ____.", ["strengths, weaknesses, opportunities and threats", "only sales", "only the cover", "only the weather"], "strengths, weaknesses, opportunities and threats",
      "SWOT examines internal strengths/weaknesses and external opportunities/threats.", "ERR_EMS_G9B3A2_SWOT", 2),
    MC("What usually comes last in a business plan?", ["The conclusion", "The front cover", "The table of contents", "The product description"], "The conclusion",
      "The conclusion wraps up the plan at the end.", "ERR_EMS_G9B3A2_CONCLUSION", 1),
    MC("A 'production plan' in a business plan describes ____.", ["how the goods or services will be produced", "the front cover", "the lunch menu", "the weather"], "how the goods or services will be produced",
      "The production plan explains how products will be made.", "ERR_EMS_G9B3A2_PRODPLAN", 2),
    MC("A 'marketing plan' section describes ____.", ["how the business will promote and sell", "how to make tea", "the owner's hobbies", "the weather"], "how the business will promote and sell",
      "The marketing plan covers promotion and selling.", "ERR_EMS_G9B3A2_MKTPLAN", 2),
    MC("A 'management plan' section describes ____.", ["who will run the business and how", "the front cover only", "the snacks", "the music"], "who will run the business and how",
      "The management plan covers who runs the business and how.", "ERR_EMS_G9B3A2_MGMT", 2),
    MC("Why does a business plan follow a set format?", ["So it is organised and easy for readers to follow", "To confuse readers", "To hide information", "For no reason"], "So it is organised and easy for readers to follow",
      "A standard format makes the plan clear and easy to follow.", "ERR_EMS_G9B3A2_WHY", 2),
    MC("Which order is correct for a business plan?", ["Cover, contents, product, goals, plans, SWOT, conclusion", "Conclusion, cover, contents", "SWOT, cover, product", "Conclusion first, cover last"], "Cover, contents, product, goals, plans, SWOT, conclusion",
      "The plan runs from cover and contents through to the conclusion.", "ERR_EMS_G9B3A2_ORDER", 3),
    TF("The front cover is usually the first part of a business plan.", "True",
      "The cover comes first.", "ERR_EMS_G9B3A2_TF1", 1),
    TF("The conclusion usually comes at the end of the plan.", "True",
      "The conclusion wraps up the plan.", "ERR_EMS_G9B3A2_TF2", 1),
    TF("SWOT in a business plan stands for strengths, weaknesses, opportunities and threats.", "True",
      "SWOT = strengths, weaknesses, opportunities, threats.", "ERR_EMS_G9B3A2_TF3", 1),
    TF("A business plan has no particular order.", "False",
      "A business plan follows a clear, set order from cover to conclusion.", "ERR_EMS_G9B3A2_TF4", 1),
    CLOZE("The ____ cover is usually the first part of a business plan.", ["front", "back", "side", "middle"], "front",
      "The front cover comes first.", "ERR_EMS_G9B3A2_CL1", 1),
    CLOZE("The table of ____ helps the reader find each section.", ["contents", "snacks", "weather", "music"], "contents",
      "The table of contents aids navigation.", "ERR_EMS_G9B3A2_CL2", 1),
    CLOZE("The ____ analysis looks at strengths, weaknesses, opportunities and threats.", ["SWOT", "FIFO", "VAT", "PAYE"], "SWOT",
      "SWOT examines these four areas.", "ERR_EMS_G9B3A2_CL3", 2),
    CLOZE("The ____ usually comes at the end of a business plan.", ["conclusion", "cover", "contents", "product"], "conclusion",
      "The conclusion ends the plan.", "ERR_EMS_G9B3A2_CL4", 1),
    {
      question: "Sort each section into 'Near the start' or 'Near the end' of a business plan.",
      input_type: "sort-buckets",
      buckets: [{ id: "start", label: "Near the start" }, { id: "end", label: "Near the end" }],
      items: [
        { id: "i1", text: "Front cover", correct_bucket: "start" },
        { id: "i2", text: "Table of contents", correct_bucket: "start" },
        { id: "i3", text: "SWOT analysis", correct_bucket: "end" },
        { id: "i4", text: "Conclusion", correct_bucket: "end" },
      ],
      expected: "The cover and contents come near the start; the SWOT analysis and conclusion come near the end.",
      pass_threshold: 0.75,
      memo: "Start: cover, contents. End: SWOT, conclusion.", error_signals: ["ERR_EMS_G9B3A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the business plan sections in the usual order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Front cover and table of contents" },
        { id: "b", text: "Description of the product and goals" },
        { id: "c", text: "Production, marketing and management plans" },
        { id: "d", text: "SWOT analysis and conclusion" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Cover/contents → product and goals → the plans → SWOT and conclusion.",
      error_signals: ["ERR_EMS_G9B3A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · The financial plan
  "EMS.G9.B3.A3": [
    MC("What does the financial plan in a business plan show?", ["The expected costs, prices and profit of the business", "Only the front cover", "The owner's hobbies", "The weather forecast"], "The expected costs, prices and profit of the business",
      "The financial plan sets out costs, prices and expected profit.", "ERR_EMS_G9B3A3_DEF", 1),
    MC("A fixed cost is one that ____.", ["stays the same no matter how much is produced", "changes with each item", "is income", "is a profit"], "stays the same no matter how much is produced",
      "Fixed costs (like rent) don't change with output.", "ERR_EMS_G9B3A3_FIXED", 1),
    MC("A variable cost is one that ____.", ["changes with how much is produced", "never changes", "is always income", "is a profit"], "changes with how much is produced",
      "Variable costs (like materials) rise with output.", "ERR_EMS_G9B3A3_VARIABLE", 1),
    MC("The break-even point is where ____.", ["income exactly covers total costs (no profit, no loss)", "profit is highest", "costs are zero", "the business closes"], "income exactly covers total costs (no profit, no loss)",
      "Break-even is where income equals total costs.", "ERR_EMS_G9B3A3_BREAKEVEN", 2),
    MC("'Mark-up' is the amount added to the cost price to ____.", ["set a selling price and make a profit", "lower the price", "remove profit", "pay tax only"], "set a selling price and make a profit",
      "Mark-up is added to cost to set a profitable selling price.", "ERR_EMS_G9B3A3_MARKUP", 2),
    MC("If a product costs R40 and is marked up by R20, the selling price is ____.", ["R60", "R20", "R40", "R80"], "R60",
      "Selling price = cost + mark-up = R40 + R20 = R60.", "ERR_EMS_G9B3A3_CALC", 2),
    MC("Profit percentage compares profit to ____.", ["the cost or sales", "the weather", "the owner's age", "the front cover"], "the cost or sales",
      "Profit percentage relates profit to cost or sales.", "ERR_EMS_G9B3A3_PROFITPCT", 3),
    MC("Why include a financial plan?", ["To show the business can cover costs and make a profit", "To hide the numbers", "To avoid planning", "To confuse the bank"], "To show the business can cover costs and make a profit",
      "It shows the business is financially viable.", "ERR_EMS_G9B3A3_WHY", 2),
    MC("If selling price is below the cost to make an item, the business makes a ____ per item.", ["loss", "profit", "saving", "tax"], "loss",
      "Selling below cost means a loss per item.", "ERR_EMS_G9B3A3_LOSS", 2),
    MC("Reaching the break-even point means the business has ____.", ["covered its costs and starts making profit beyond it", "made a big loss", "no costs", "closed down"], "covered its costs and starts making profit beyond it",
      "Beyond break-even, further sales bring profit.", "ERR_EMS_G9B3A3_BEYOND", 3),
    TF("The financial plan shows the expected costs, prices and profit.", "True",
      "It covers costs, prices and expected profit.", "ERR_EMS_G9B3A3_TF1", 1),
    TF("A fixed cost stays the same regardless of how much is produced.", "True",
      "Fixed costs don't change with output.", "ERR_EMS_G9B3A3_TF2", 1),
    TF("The break-even point is where income equals total costs.", "True",
      "At break-even there is no profit and no loss.", "ERR_EMS_G9B3A3_TF3", 1),
    TF("Mark-up is subtracted from the cost price to lower it.", "False",
      "Mark-up is added to the cost price to set a profitable selling price.", "ERR_EMS_G9B3A3_TF4", 2),
    CLOZE("The financial plan shows costs, prices and expected ____.", ["profit", "weather", "hobbies", "music"], "profit",
      "It sets out expected profit.", "ERR_EMS_G9B3A3_CL1", 1),
    CLOZE("A cost that does not change with output is a ____ cost.", ["fixed", "variable", "selling", "profit"], "fixed",
      "Fixed costs stay the same.", "ERR_EMS_G9B3A3_CL2", 1),
    CLOZE("The point where income just covers costs is the ____ point.", ["break-even", "profit", "loss", "mark-up"], "break-even",
      "Break-even is where income = total costs.", "ERR_EMS_G9B3A3_CL3", 2),
    CLOZE("The amount added to the cost to set the selling price is the ____.", ["mark-up", "discount", "loss", "tax"], "mark-up",
      "Mark-up is added to cost to set the price.", "ERR_EMS_G9B3A3_CL4", 2),
    {
      question: "Sort each cost into 'Fixed cost' or 'Variable cost'.",
      input_type: "sort-buckets",
      buckets: [{ id: "fixed", label: "Fixed cost" }, { id: "variable", label: "Variable cost" }],
      items: [
        { id: "i1", text: "Monthly shop rent", correct_bucket: "fixed" },
        { id: "i2", text: "Materials used per item", correct_bucket: "variable" },
        { id: "i3", text: "A fixed monthly insurance fee", correct_bucket: "fixed" },
        { id: "i4", text: "Packaging used for each product", correct_bucket: "variable" },
      ],
      expected: "Rent and insurance are fixed; materials and packaging per item are variable.",
      pass_threshold: 0.75,
      memo: "Fixed costs stay the same; variable costs grow with each item made.", error_signals: ["ERR_EMS_G9B3A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of a simple financial plan in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Work out fixed and variable costs" },
        { id: "b", text: "Set a selling price using a mark-up" },
        { id: "c", text: "Calculate the break-even point" },
        { id: "d", text: "Estimate the expected profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Costs → selling price (mark-up) → break-even → expected profit.",
      error_signals: ["ERR_EMS_G9B3A3_SEQ"], difficulty: 3,
    },
  ],
};

export default G9C;
