// ─── EMS SP — Grade 8 authored pools (C): Entrepreneurship ────────────────────
// Strand: Entrepreneurship (CAPS G8). Tap-only. Recipe: 10 MC · 4 TF · 4 CLOZE ·
// 1 sequence · 1 sort-buckets = 20.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8C = {
  // ─── B1 · Term 2 — Factors of production ───────────────────────────────────
  // A1 · Capital
  "EMS.G8.B1.A1": [
    MC("What is 'capital' as a factor of production?", ["The money and equipment used to run a business", "The workers in a business", "The land a business uses", "The owner's ideas only"], "The money and equipment used to run a business",
      "Capital is the money, tools and equipment used to produce goods and services.", "ERR_EMS_G8B1A1_DEF", 1),
    MC("What is 'own capital'?", ["Money the owner puts into the business", "Money borrowed from a bank", "Money owed to suppliers", "Wages paid to staff"], "Money the owner puts into the business",
      "Own capital is the owner's own money invested in the business.", "ERR_EMS_G8B1A1_OWN", 1),
    MC("What is 'borrowed capital'?", ["Money borrowed, such as a bank loan", "The owner's own savings", "Free money", "Wages"], "Money borrowed, such as a bank loan",
      "Borrowed capital is money the business borrows and must repay.", "ERR_EMS_G8B1A1_BORROW", 1),
    MC("Which is an example of capital in a bakery?", ["The ovens and mixers", "The customers", "The weather", "The bakery's name only"], "The ovens and mixers",
      "Equipment like ovens and mixers is capital.", "ERR_EMS_G8B1A1_EX", 1),
    MC("Borrowed capital usually must be repaid with ____.", ["interest", "nothing", "extra free gifts", "more workers"], "interest",
      "Borrowed capital (like a loan) is repaid with interest.", "ERR_EMS_G8B1A1_INTEREST", 2),
    MC("Why does a business need capital?", ["To buy equipment and run operations", "To avoid producing", "To stop trading", "To lose money"], "To buy equipment and run operations",
      "Capital funds the equipment and running of the business.", "ERR_EMS_G8B1A1_WHY", 2),
    MC("An owner using R30 000 of savings to buy stock is using ____.", ["own capital", "borrowed capital", "labour", "natural resources"], "own capital",
      "The owner's own savings invested are own capital.", "ERR_EMS_G8B1A1_OWN_EX", 2),
    MC("A R50 000 bank loan to buy a delivery van is ____.", ["borrowed capital", "own capital", "labour", "land"], "borrowed capital",
      "A bank loan is borrowed capital.", "ERR_EMS_G8B1A1_BORROW_EX", 2),
    MC("Which is a risk of using too much borrowed capital?", ["The business must repay it with interest, even in hard times", "It is always free", "It never has to be repaid", "It removes all costs"], "The business must repay it with interest, even in hard times",
      "Borrowed capital must be repaid with interest, which is risky if income drops.", "ERR_EMS_G8B1A1_RISK", 3),
    MC("Capital as a factor of production is rewarded with ____.", ["interest", "wages", "rent", "nothing"], "interest",
      "Capital earns interest as its reward (factor payment).", "ERR_EMS_G8B1A1_REWARD", 2),
    TF("Capital includes the money and equipment used in a business.", "True",
      "Capital is the money, tools and equipment used to produce.", "ERR_EMS_G8B1A1_TF1", 1),
    TF("Own capital is money the owner contributes; borrowed capital is a loan.", "True",
      "Own capital is the owner's; borrowed capital is borrowed and repaid.", "ERR_EMS_G8B1A1_TF2", 1),
    TF("Borrowed capital never has to be repaid.", "False",
      "Borrowed capital must be repaid, usually with interest.", "ERR_EMS_G8B1A1_TF3", 1),
    TF("Machines and equipment are examples of capital.", "True",
      "Equipment used to produce is capital.", "ERR_EMS_G8B1A1_TF4", 1),
    CLOZE("Money and equipment used to run a business is the factor called ____.", ["capital", "labour", "land", "tax"], "capital",
      "Capital is money and equipment used in production.", "ERR_EMS_G8B1A1_CL1", 1),
    CLOZE("The owner's own money invested in the business is ____ capital.", ["own", "borrowed", "free", "public"], "own",
      "Own capital is the owner's contribution.", "ERR_EMS_G8B1A1_CL2", 1),
    CLOZE("A bank loan used in a business is ____ capital.", ["borrowed", "own", "free", "personal"], "borrowed",
      "Borrowed capital is borrowed money like a loan.", "ERR_EMS_G8B1A1_CL3", 1),
    CLOZE("Capital is rewarded with ____.", ["interest", "wages", "rent", "profit only"], "interest",
      "Interest is the reward to capital.", "ERR_EMS_G8B1A1_CL4", 2),
    {
      question: "Sort each into 'Own capital' or 'Borrowed capital'.",
      input_type: "sort-buckets",
      buckets: [{ id: "own", label: "Own capital" }, { id: "borrowed", label: "Borrowed capital" }],
      items: [
        { id: "i1", text: "The owner's personal savings put in", correct_bucket: "own" },
        { id: "i2", text: "A bank loan for equipment", correct_bucket: "borrowed" },
        { id: "i3", text: "Money the owner inherited and invested", correct_bucket: "own" },
        { id: "i4", text: "Credit from a supplier that must be repaid", correct_bucket: "borrowed" },
      ],
      expected: "The owner's own savings and inheritance are own capital; loans and supplier credit are borrowed.",
      pass_threshold: 0.75,
      memo: "Own capital comes from the owner; borrowed capital is borrowed and repaid with interest.", error_signals: ["ERR_EMS_G8B1A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of using capital to start a business in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Gather own capital (savings)" },
        { id: "b", text: "Borrow extra capital if needed" },
        { id: "c", text: "Buy equipment and stock" },
        { id: "d", text: "Use the capital to produce and earn income" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Use own capital, add borrowed capital if needed, buy equipment, then produce.",
      error_signals: ["ERR_EMS_G8B1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Labour
  "EMS.G8.B1.A2": [
    MC("What is 'labour' as a factor of production?", ["The human effort and work used to produce", "The money in a business", "The land used", "The owner's tools"], "The human effort and work used to produce",
      "Labour is the human effort, physical and mental, used in production.", "ERR_EMS_G8B1A2_DEF", 1),
    MC("What is unskilled labour?", ["Work needing little training", "Highly specialised expert work", "Work needing a university degree", "No work at all"], "Work needing little training",
      "Unskilled labour requires little training, like basic manual tasks.", "ERR_EMS_G8B1A2_UNSKILLED", 1),
    MC("What is skilled labour?", ["Work needing training, qualifications or expertise", "Work needing no training", "Work no one does", "Only manual lifting"], "Work needing training, qualifications or expertise",
      "Skilled labour needs training or expertise, like an electrician or accountant.", "ERR_EMS_G8B1A2_SKILLED", 1),
    MC("Semi-skilled labour falls ____ unskilled and skilled labour.", ["between", "far below", "far above", "outside"], "between",
      "Semi-skilled labour needs some training, between unskilled and fully skilled.", "ERR_EMS_G8B1A2_SEMI", 2),
    MC("Labour as a factor of production is rewarded with ____.", ["wages or salaries", "interest", "rent", "nothing"], "wages or salaries",
      "Labour earns wages or salaries as its reward.", "ERR_EMS_G8B1A2_REWARD", 1),
    MC("What are 'fair employment practices'?", ["Treating workers fairly and within the law", "Paying workers nothing", "Ignoring worker safety", "Forcing unpaid work"], "Treating workers fairly and within the law",
      "Fair employment practices mean treating workers justly and legally.", "ERR_EMS_G8B1A2_FAIR", 2),
    MC("A qualified doctor is an example of ____ labour.", ["skilled", "unskilled", "semi-skilled", "no"], "skilled",
      "A doctor's training makes this skilled labour.", "ERR_EMS_G8B1A2_DOCTOR", 1),
    MC("A worker carrying boxes with no special training is doing ____ labour.", ["unskilled", "skilled", "expert", "managerial"], "unskilled",
      "Basic manual work with little training is unskilled labour.", "ERR_EMS_G8B1A2_CARRY", 1),
    MC("Why are fair employment practices important?", ["They protect workers' rights and dignity", "They harm workers", "They are illegal", "They lower no risks"], "They protect workers' rights and dignity",
      "Fair practices protect workers and create a better workplace.", "ERR_EMS_G8B1A2_WHYFAIR", 2),
    MC("Which order shows labour from least to most training?", ["Unskilled, semi-skilled, skilled", "Skilled, semi-skilled, unskilled", "Semi-skilled, unskilled, skilled", "Skilled, unskilled, semi-skilled"], "Unskilled, semi-skilled, skilled",
      "Training increases from unskilled to semi-skilled to skilled.", "ERR_EMS_G8B1A2_ORDER", 2),
    TF("Labour is the human effort used in production.", "True",
      "Labour is the human work used to produce goods and services.", "ERR_EMS_G8B1A2_TF1", 1),
    TF("Skilled labour needs training or qualifications.", "True",
      "Skilled labour requires training or expertise.", "ERR_EMS_G8B1A2_TF2", 1),
    TF("Labour is rewarded with interest.", "False",
      "Labour is rewarded with wages or salaries; interest is the reward to capital.", "ERR_EMS_G8B1A2_TF3", 1),
    TF("Fair employment practices treat workers justly and lawfully.", "True",
      "Fair practices respect workers' rights and the law.", "ERR_EMS_G8B1A2_TF4", 1),
    CLOZE("The human effort used to produce is the factor called ____.", ["labour", "capital", "land", "tax"], "labour",
      "Labour is human effort in production.", "ERR_EMS_G8B1A2_CL1", 1),
    CLOZE("Work needing little training is ____ labour.", ["unskilled", "skilled", "expert", "managerial"], "unskilled",
      "Unskilled labour needs little training.", "ERR_EMS_G8B1A2_CL2", 1),
    CLOZE("Work needing qualifications or expertise is ____ labour.", ["skilled", "unskilled", "semi", "no"], "skilled",
      "Skilled labour needs training or expertise.", "ERR_EMS_G8B1A2_CL3", 1),
    CLOZE("Labour is rewarded with ____.", ["wages", "interest", "rent", "profit only"], "wages",
      "Wages or salaries reward labour.", "ERR_EMS_G8B1A2_CL4", 1),
    {
      question: "Sort each job into 'Unskilled', 'Semi-skilled' or 'Skilled' labour.",
      input_type: "sort-buckets",
      buckets: [{ id: "unskilled", label: "Unskilled" }, { id: "semi", label: "Semi-skilled" }, { id: "skilled", label: "Skilled" }],
      items: [
        { id: "i1", text: "Sweeping a floor", correct_bucket: "unskilled" },
        { id: "i2", text: "Operating a till after short training", correct_bucket: "semi" },
        { id: "i3", text: "Qualified electrician", correct_bucket: "skilled" },
        { id: "i4", text: "Carrying boxes with no training", correct_bucket: "unskilled" },
      ],
      expected: "Sweeping and carrying boxes are unskilled; a trained cashier is semi-skilled; an electrician is skilled.",
      pass_threshold: 0.75,
      memo: "More training = more skilled: unskilled → semi-skilled → skilled.", error_signals: ["ERR_EMS_G8B1A2_SORT"], difficulty: 2,
    },
    {
      question: "Put labour types in order from least to most training needed.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Unskilled labour" },
        { id: "b", text: "Semi-skilled labour" },
        { id: "c", text: "Skilled labour" },
        { id: "d", text: "Highly specialised expert" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Training rises from unskilled to semi-skilled to skilled to specialised expert.",
      error_signals: ["ERR_EMS_G8B1A2_SEQ"], difficulty: 1,
    },
  ],

  // A3 · Natural resources and entrepreneurship
  "EMS.G8.B1.A3": [
    MC("What are 'natural resources' as a factor of production?", ["Things from nature used to produce, like land, water and minerals", "Money in a bank", "Workers' wages", "A business plan"], "Things from nature used to produce, like land, water and minerals",
      "Natural resources are gifts of nature — land, water, minerals — used in production.", "ERR_EMS_G8B1A3_DEF", 1),
    MC("Natural resources (land) are rewarded with ____.", ["rent", "wages", "interest", "nothing"], "rent",
      "Land/natural resources earn rent as their factor reward.", "ERR_EMS_G8B1A3_RENT", 2),
    MC("What does the entrepreneur contribute as a factor of production?", ["The idea, risk-taking and organising of the other factors", "Only money", "Only land", "Only labour"], "The idea, risk-taking and organising of the other factors",
      "The entrepreneur supplies the idea, takes the risk and combines the other factors.", "ERR_EMS_G8B1A3_ENTREP", 2),
    MC("The entrepreneur is rewarded with ____.", ["profit", "wages", "rent", "interest"], "profit",
      "The entrepreneur's reward is profit.", "ERR_EMS_G8B1A3_PROFIT", 2),
    MC("Which is a natural resource?", ["Water used by a bottling plant", "A bank loan", "A factory worker", "A delivery van"], "Water used by a bottling plant",
      "Water from nature is a natural resource; the others are capital or labour.", "ERR_EMS_G8B1A3_EX", 1),
    MC("How many factors of production are there in total?", ["Four", "Two", "Six", "Ten"], "Four",
      "The four factors are land (natural resources), labour, capital and entrepreneurship.", "ERR_EMS_G8B1A3_FOUR", 1),
    MC("The factor that combines and organises all the others is ____.", ["entrepreneurship", "land", "labour", "capital"], "entrepreneurship",
      "The entrepreneur brings together land, labour and capital.", "ERR_EMS_G8B1A3_COMBINE", 2),
    MC("Minerals mined from the ground are an example of ____.", ["natural resources", "capital", "labour", "profit"], "natural resources",
      "Minerals are natural resources.", "ERR_EMS_G8B1A3_MINERALS", 1),
    MC("Why must natural resources be used sustainably?", ["Many cannot be replaced once used up", "They are unlimited", "They are useless", "They cost nothing"], "Many cannot be replaced once used up",
      "Many natural resources are limited or non-renewable, so they must be used sustainably.", "ERR_EMS_G8B1A3_SUSTAIN", 3),
    MC("Which correctly matches a factor to its reward?", ["Labour–wages, capital–interest, land–rent, entrepreneur–profit", "All factors earn wages", "All factors earn rent", "All factors earn profit"], "Labour–wages, capital–interest, land–rent, entrepreneur–profit",
      "Each factor has its own reward: wages, interest, rent and profit.", "ERR_EMS_G8B1A3_MATCH", 3),
    TF("Land, water and minerals are natural resources.", "True",
      "These come from nature and are natural resources.", "ERR_EMS_G8B1A3_TF1", 1),
    TF("The entrepreneur takes the risk and organises the other factors.", "True",
      "The entrepreneur brings the idea, takes risk and combines the factors.", "ERR_EMS_G8B1A3_TF2", 1),
    TF("The entrepreneur is rewarded with rent.", "False",
      "The entrepreneur earns profit; rent is the reward to land/natural resources.", "ERR_EMS_G8B1A3_TF3", 1),
    TF("There are four factors of production.", "True",
      "Land, labour, capital and entrepreneurship are the four factors.", "ERR_EMS_G8B1A3_TF4", 1),
    CLOZE("Things from nature used to produce, like minerals, are ____ resources.", ["natural", "borrowed", "human", "financial"], "natural",
      "Natural resources come from nature.", "ERR_EMS_G8B1A3_CL1", 1),
    CLOZE("Land and natural resources are rewarded with ____.", ["rent", "wages", "interest", "profit"], "rent",
      "Rent rewards land/natural resources.", "ERR_EMS_G8B1A3_CL2", 2),
    CLOZE("The person who takes the risk and combines the factors is the ____.", ["entrepreneur", "worker", "landlord", "banker"], "entrepreneur",
      "The entrepreneur organises the other factors.", "ERR_EMS_G8B1A3_CL3", 2),
    CLOZE("The entrepreneur is rewarded with ____.", ["profit", "rent", "wages", "interest"], "profit",
      "Profit rewards the entrepreneur.", "ERR_EMS_G8B1A3_CL4", 2),
    {
      question: "Match each factor of production to its reward.",
      input_type: "sort-buckets",
      buckets: [{ id: "wages", label: "Wages" }, { id: "interest", label: "Interest" }, { id: "rent", label: "Rent" }, { id: "profit", label: "Profit" }],
      items: [
        { id: "i1", text: "Labour", correct_bucket: "wages" },
        { id: "i2", text: "Capital", correct_bucket: "interest" },
        { id: "i3", text: "Land / natural resources", correct_bucket: "rent" },
        { id: "i4", text: "Entrepreneurship", correct_bucket: "profit" },
      ],
      expected: "Labour earns wages, capital earns interest, land earns rent, entrepreneurship earns profit.",
      pass_threshold: 0.75,
      memo: "Wages–labour, interest–capital, rent–land, profit–entrepreneur.", error_signals: ["ERR_EMS_G8B1A3_SORT"], difficulty: 3,
    },
    {
      question: "Put the factors of production together in the order an entrepreneur uses them.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The entrepreneur has a business idea" },
        { id: "b", text: "They gather capital (money and equipment)" },
        { id: "c", text: "They hire labour and obtain natural resources" },
        { id: "d", text: "The factors combine to produce goods for profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Idea first, then capital, then labour and resources, combining to produce for profit.",
      error_signals: ["ERR_EMS_G8B1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── B2 · Term 3 — Forms of ownership ──────────────────────────────────────
  // A1 · Sole trader and partnership
  "EMS.G8.B2.A1": [
    MC("What is a sole trader?", ["A business owned by one person", "A business owned by shareholders", "A government department", "A club"], "A business owned by one person",
      "A sole trader is a business owned and run by one person.", "ERR_EMS_G8B2A1_SOLE", 1),
    MC("What is a partnership?", ["A business owned by two or more people together", "A business owned by one person", "A listed company", "A bank"], "A business owned by two or more people together",
      "A partnership is owned by two or more people who share it.", "ERR_EMS_G8B2A1_PARTNER", 1),
    MC("An advantage of a sole trader is that ____.", ["the owner makes all decisions quickly", "profits must be split many ways", "it needs many owners", "it must be a big company"], "the owner makes all decisions quickly",
      "A sole owner can decide quickly and keeps all the profit.", "ERR_EMS_G8B2A1_SOLE_ADV", 2),
    MC("A disadvantage of a sole trader is that ____.", ["the owner carries all the risk alone", "profits are shared with many", "there are too many owners", "decisions are slow"], "the owner carries all the risk alone",
      "The sole owner bears all the risk and losses alone.", "ERR_EMS_G8B2A1_SOLE_DIS", 2),
    MC("An advantage of a partnership is that ____.", ["partners share work, skills and capital", "one person does everything alone", "no one shares ideas", "it cannot raise money"], "partners share work, skills and capital",
      "Partners pool skills, work and capital.", "ERR_EMS_G8B2A1_PART_ADV", 2),
    MC("A disadvantage of a partnership is that ____.", ["partners may disagree and must share profits", "there is only one owner", "no skills are shared", "no capital is available"], "partners may disagree and must share profits",
      "Partners can disagree, and profits are split between them.", "ERR_EMS_G8B2A1_PART_DIS", 2),
    MC("A hairdresser who owns and runs her salon alone is a ____.", ["sole trader", "partnership", "company", "close corporation"], "sole trader",
      "One owner running the business is a sole trader.", "ERR_EMS_G8B2A1_SALON", 1),
    MC("Two friends who open and co-own a coffee shop form a ____.", ["partnership", "sole trader", "public company", "government body"], "partnership",
      "Two co-owners form a partnership.", "ERR_EMS_G8B2A1_COFFEE", 1),
    MC("In a sole trader, the profits ____.", ["all belong to the one owner", "are split among shareholders", "go to the government", "are shared with partners"], "all belong to the one owner",
      "A sole trader keeps all the profit (and bears all losses).", "ERR_EMS_G8B2A1_PROFIT", 2),
    MC("Which statement is correct?", ["A sole trader has one owner; a partnership has two or more", "Both have exactly one owner", "Both must be companies", "A partnership has only one owner"], "A sole trader has one owner; a partnership has two or more",
      "Sole trader = one owner; partnership = two or more.", "ERR_EMS_G8B2A1_CORRECT", 1),
    TF("A sole trader is owned by one person.", "True",
      "Sole traders have a single owner.", "ERR_EMS_G8B2A1_TF1", 1),
    TF("A partnership is owned by two or more people.", "True",
      "Partnerships have two or more owners.", "ERR_EMS_G8B2A1_TF2", 1),
    TF("In a sole trader, profits are shared among many shareholders.", "False",
      "A sole trader keeps all the profit; sharing among shareholders describes a company.", "ERR_EMS_G8B2A1_TF3", 1),
    TF("Partners can share skills and capital but may also disagree.", "True",
      "Partnerships pool resources but can have disagreements.", "ERR_EMS_G8B2A1_TF4", 2),
    CLOZE("A business owned by one person is a ____ trader.", ["sole", "joint", "public", "group"], "sole",
      "A sole trader has one owner.", "ERR_EMS_G8B2A1_CL1", 1),
    CLOZE("A business owned by two or more people is a ____.", ["partnership", "sole trader", "company", "club"], "partnership",
      "A partnership has two or more owners.", "ERR_EMS_G8B2A1_CL2", 1),
    CLOZE("A sole trader keeps ____ the profit.", ["all", "none", "half only", "a tenth of"], "all",
      "The sole owner keeps all the profit.", "ERR_EMS_G8B2A1_CL3", 2),
    CLOZE("In a partnership, profits are ____ among the partners.", ["shared", "ignored", "taxed away", "destroyed"], "shared",
      "Partners share the profits.", "ERR_EMS_G8B2A1_CL4", 1),
    {
      question: "Sort each feature under 'Sole trader' or 'Partnership'.",
      input_type: "sort-buckets",
      buckets: [{ id: "sole", label: "Sole trader" }, { id: "partner", label: "Partnership" }],
      items: [
        { id: "i1", text: "One owner makes all decisions", correct_bucket: "sole" },
        { id: "i2", text: "Two or more owners share the work", correct_bucket: "partner" },
        { id: "i3", text: "All profit goes to a single owner", correct_bucket: "sole" },
        { id: "i4", text: "Owners pool their skills and capital", correct_bucket: "partner" },
      ],
      expected: "One owner and all-profit-to-one are sole-trader features; shared work and pooled capital are partnership features.",
      pass_threshold: 0.75,
      memo: "Sole trader = one owner, all profit/risk; partnership = shared ownership, work and profit.", error_signals: ["ERR_EMS_G8B2A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of forming a partnership in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Two or more people agree to start a business together" },
        { id: "b", text: "They each contribute capital and skills" },
        { id: "c", text: "They run the business together" },
        { id: "d", text: "They share the profits" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Agree to partner, contribute, run it together, then share the profits.",
      error_signals: ["ERR_EMS_G8B2A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · Companies and close corporations
  "EMS.G8.B2.A2": [
    MC("What is a company?", ["A business that is a separate legal 'person', owned by shareholders", "A business owned by one person only", "A government department", "A stokvel"], "A business that is a separate legal 'person', owned by shareholders",
      "A company is a separate legal entity owned by shareholders.", "ERR_EMS_G8B2A2_COMPANY", 1),
    MC("Who owns a company?", ["Shareholders", "Only the manager", "The government", "Customers"], "Shareholders",
      "Shareholders own a company through their shares.", "ERR_EMS_G8B2A2_SHARE", 1),
    MC("What is the difference between a private and a public company?", ["A public company can sell shares to the general public; a private one cannot", "They are identical", "A private company is bigger always", "Public companies have no shareholders"], "A public company can sell shares to the general public; a private one cannot",
      "Public companies can offer shares to the public; private companies cannot.", "ERR_EMS_G8B2A2_PUBPRIV", 2),
    MC("A close corporation (CC) was traditionally owned by ____.", ["a small number of members", "thousands of strangers", "the government", "no one"], "a small number of members",
      "Close corporations were owned by a small number of members.", "ERR_EMS_G8B2A2_CC", 2),
    MC("An advantage of a company is that ____.", ["it can raise large amounts of capital by selling shares", "it can never grow", "it has no owners", "it cannot employ anyone"], "it can raise large amounts of capital by selling shares",
      "Companies can raise big capital by issuing shares.", "ERR_EMS_G8B2A2_ADV", 2),
    MC("'Limited liability' means shareholders ____.", ["can only lose what they invested, not their personal belongings", "must pay all the company's debts personally", "owe nothing ever", "own no shares"], "can only lose what they invested, not their personal belongings",
      "Limited liability limits a shareholder's loss to their investment.", "ERR_EMS_G8B2A2_LIABILITY", 3),
    MC("Shares listed on the stock exchange belong to a ____ company.", ["public", "private", "sole", "partnership"], "public",
      "Only public companies list shares for the public to buy.", "ERR_EMS_G8B2A2_LISTED", 2),
    MC("A disadvantage of a large company is that ____.", ["it has more rules, paperwork and reporting", "it can never raise capital", "it has no owners", "it cannot hire staff"], "it has more rules, paperwork and reporting",
      "Companies face more regulation and reporting requirements.", "ERR_EMS_G8B2A2_DIS", 2),
    MC("Why might a business become a company rather than a sole trader?", ["To raise more capital and limit owners' risk", "To have fewer options", "To avoid all growth", "To remove all owners"], "To raise more capital and limit owners' risk",
      "Companies can raise more capital and offer limited liability.", "ERR_EMS_G8B2A2_WHY", 2),
    MC("Which statement is correct?", ["A company is a separate legal person owned by shareholders", "A company has no owners", "A company is the same as a sole trader", "Companies cannot raise capital"], "A company is a separate legal person owned by shareholders",
      "A company is a separate legal entity owned by shareholders.", "ERR_EMS_G8B2A2_CORRECT", 1),
    TF("A company is a separate legal entity owned by shareholders.", "True",
      "Companies are separate legal 'persons' owned by shareholders.", "ERR_EMS_G8B2A2_TF1", 1),
    TF("A public company can sell shares to the general public.", "True",
      "Public companies may offer shares to the public.", "ERR_EMS_G8B2A2_TF2", 1),
    TF("Limited liability means owners risk their personal belongings for all company debts.", "False",
      "Limited liability limits loss to the amount invested, protecting personal belongings.", "ERR_EMS_G8B2A2_TF3", 1),
    TF("Companies usually have more paperwork and rules than a sole trader.", "True",
      "Companies face more regulation and reporting.", "ERR_EMS_G8B2A2_TF4", 2),
    CLOZE("A business that is a separate legal person owned by shareholders is a ____.", ["company", "sole trader", "stokvel", "household"], "company",
      "A company is a separate legal entity.", "ERR_EMS_G8B2A2_CL1", 1),
    CLOZE("Owners of a company are called ____.", ["shareholders", "partners", "tenants", "customers"], "shareholders",
      "Shareholders own companies.", "ERR_EMS_G8B2A2_CL2", 1),
    CLOZE("A ____ company can sell shares to the general public.", ["public", "private", "sole", "closed"], "public",
      "Public companies offer shares to the public.", "ERR_EMS_G8B2A2_CL3", 2),
    CLOZE("Companies can raise large ____ by selling shares.", ["capital", "rent", "wages", "tax"], "capital",
      "Selling shares raises capital.", "ERR_EMS_G8B2A2_CL4", 2),
    {
      question: "Sort each into 'Private company' or 'Public company'.",
      input_type: "sort-buckets",
      buckets: [{ id: "private", label: "Private company" }, { id: "public", label: "Public company" }],
      items: [
        { id: "i1", text: "Cannot sell shares to the general public", correct_bucket: "private" },
        { id: "i2", text: "Shares listed on the stock exchange", correct_bucket: "public" },
        { id: "i3", text: "Owned by a limited group of shareholders", correct_bucket: "private" },
        { id: "i4", text: "The public can buy its shares", correct_bucket: "public" },
      ],
      expected: "No public shares and a limited group = private; listed shares the public can buy = public.",
      pass_threshold: 0.75,
      memo: "Private companies keep shares within a small group; public companies sell shares to the public.", error_signals: ["ERR_EMS_G8B2A2_SORT"], difficulty: 2,
    },
    {
      question: "Put forms of ownership in order from fewest to most owners (typically).",
      input_type: "sequence",
      items: [
        { id: "a", text: "Sole trader (one owner)" },
        { id: "b", text: "Partnership (a few owners)" },
        { id: "c", text: "Private company (a limited group)" },
        { id: "d", text: "Public company (many shareholders)" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Owners increase from sole trader, to partnership, to private company, to public company.",
      error_signals: ["ERR_EMS_G8B2A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Ownership and job creation
  "EMS.G8.B2.A3": [
    MC("How can businesses help create jobs?", ["By growing and employing more workers", "By closing down", "By firing everyone", "By never trading"], "By growing and employing more workers",
      "As businesses grow, they hire more workers, creating jobs.", "ERR_EMS_G8B2A3_JOBS", 1),
    MC("Why can larger forms of ownership often create more jobs?", ["They can raise more capital and grow bigger", "They always stay tiny", "They cannot hire", "They avoid all growth"], "They can raise more capital and grow bigger",
      "Companies can raise more capital, grow and employ more people.", "ERR_EMS_G8B2A3_LARGE", 2),
    MC("Sustainable job creation means jobs that ____.", ["can last over the long term", "disappear in a day", "harm the environment", "pay nothing"], "can last over the long term",
      "Sustainable jobs last and keep providing income over time.", "ERR_EMS_G8B2A3_SUSTAIN", 2),
    MC("How can a business use natural resources sustainably?", ["By not wasting them and protecting them for the future", "By using them up as fast as possible", "By polluting freely", "By ignoring waste"], "By not wasting them and protecting them for the future",
      "Sustainable use avoids waste and protects resources for the future.", "ERR_EMS_G8B2A3_RESOURCE", 2),
    MC("A small business that grows into a company may ____.", ["employ many more people", "always stay one person", "create no jobs", "shrink to nothing"], "employ many more people",
      "Growth from small business to company can create many jobs.", "ERR_EMS_G8B2A3_GROW", 2),
    MC("Why is job creation important for a country?", ["It reduces unemployment and poverty", "It increases poverty", "It removes income", "It has no effect"], "It reduces unemployment and poverty",
      "More jobs reduce unemployment and poverty.", "ERR_EMS_G8B2A3_WHY", 1),
    MC("Which form of ownership can usually raise the most capital to expand and hire?", ["A public company", "A sole trader", "A one-person stall", "A hobby"], "A public company",
      "Public companies can raise large capital by selling shares, supporting expansion.", "ERR_EMS_G8B2A3_PUBLIC", 2),
    MC("A business that protects resources while creating jobs supports ____.", ["sustainable development", "pollution", "unemployment", "waste"], "sustainable development",
      "Creating jobs while protecting resources is sustainable development.", "ERR_EMS_G8B2A3_DEV", 3),
    MC("Even a sole trader contributes to the economy by ____.", ["providing a job for the owner and possibly a few others", "creating no value", "removing all jobs", "stopping trade"], "providing a job for the owner and possibly a few others",
      "Sole traders create at least the owner's job, and sometimes a few more.", "ERR_EMS_G8B2A3_SOLE", 2),
    MC("Which combination best supports the economy long term?", ["Creating sustainable jobs and using resources wisely", "Wasting resources and cutting jobs", "Polluting and firing staff", "Closing all businesses"], "Creating sustainable jobs and using resources wisely",
      "Sustainable jobs plus wise resource use support the economy over time.", "ERR_EMS_G8B2A3_COMBO", 2),
    TF("Businesses can create jobs as they grow.", "True",
      "Growing businesses employ more workers.", "ERR_EMS_G8B2A3_TF1", 1),
    TF("Larger forms of ownership can often raise more capital to expand.", "True",
      "Companies can raise more capital and grow, creating jobs.", "ERR_EMS_G8B2A3_TF2", 1),
    TF("Sustainable jobs are jobs that last over the long term.", "True",
      "Sustainable jobs keep providing income over time.", "ERR_EMS_G8B2A3_TF3", 1),
    TF("Creating jobs has no effect on poverty.", "False",
      "Creating jobs reduces unemployment and poverty.", "ERR_EMS_G8B2A3_TF4", 1),
    CLOZE("As businesses grow, they can create more ____.", ["jobs", "pollution", "debt", "losses"], "jobs",
      "Growth lets businesses employ more people.", "ERR_EMS_G8B2A3_CL1", 1),
    CLOZE("Jobs that last over the long term are ____ jobs.", ["sustainable", "temporary", "once-off", "broken"], "sustainable",
      "Sustainable jobs keep providing income.", "ERR_EMS_G8B2A3_CL2", 2),
    CLOZE("A ____ company can raise large capital by selling shares to grow.", ["public", "sole", "single", "tiny"], "public",
      "Public companies raise capital by selling shares.", "ERR_EMS_G8B2A3_CL3", 2),
    CLOZE("Using resources without wasting them is using them ____.", ["sustainably", "carelessly", "wastefully", "harmfully"], "sustainably",
      "Sustainable use protects resources for the future.", "ERR_EMS_G8B2A3_CL4", 2),
    {
      question: "Sort each into 'Helps create lasting jobs / sustainability' or 'Harms it'.",
      input_type: "sort-buckets",
      buckets: [{ id: "helps", label: "Helps" }, { id: "harms", label: "Harms" }],
      items: [
        { id: "i1", text: "A company expanding and hiring more staff", correct_bucket: "helps" },
        { id: "i2", text: "Wasting natural resources", correct_bucket: "harms" },
        { id: "i3", text: "Using resources sustainably", correct_bucket: "helps" },
        { id: "i4", text: "A business closing and firing workers", correct_bucket: "harms" },
      ],
      expected: "Expanding and sustainable use help; wasting resources and closing down harm.",
      pass_threshold: 0.75,
      memo: "Growth and sustainability create lasting jobs; waste and closures destroy them.", error_signals: ["ERR_EMS_G8B2A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the path from business growth to job creation in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A business chooses a form of ownership that can raise capital" },
        { id: "b", text: "It raises capital and expands" },
        { id: "c", text: "It hires more workers" },
        { id: "d", text: "Unemployment in the community falls" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Choose a growth-friendly ownership form, raise capital, hire more, and reduce unemployment.",
      error_signals: ["ERR_EMS_G8B2A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── B3 · Term 4 — Levels and functions of management ──────────────────────
  // A1 · Levels of management
  "EMS.G8.B3.A1": [
    MC("How many broad levels of management are there in a business?", ["Three (top, middle, lower)", "One", "Ten", "None"], "Three (top, middle, lower)",
      "Management is usually grouped into top, middle and lower levels.", "ERR_EMS_G8B3A1_THREE", 1),
    MC("What does top management mainly do?", ["Plans the overall direction of the business", "Sweeps the floors", "Serves every customer personally", "Drives every delivery"], "Plans the overall direction of the business",
      "Top management sets the overall vision and major plans.", "ERR_EMS_G8B3A1_TOP", 1),
    MC("What does lower (first-line) management mainly do?", ["Supervises workers day to day", "Sets the company's vision", "Owns all the shares", "Decides national strategy"], "Supervises workers day to day",
      "Lower management supervises the daily work of staff.", "ERR_EMS_G8B3A1_LOWER", 1),
    MC("Middle management usually ____.", ["turns top management's plans into action for teams", "owns the company", "does no planning", "ignores top management"], "turns top management's plans into action for teams",
      "Middle management carries out top-level plans through teams.", "ERR_EMS_G8B3A1_MIDDLE", 2),
    MC("A supervisor checking that shop assistants do their tasks is ____ management.", ["lower", "top", "middle only", "no"], "lower",
      "Day-to-day supervision is lower management.", "ERR_EMS_G8B3A1_SUPERVISOR", 1),
    MC("The managing director planning a 5-year strategy is part of ____ management.", ["top", "lower", "first-line", "no"], "top",
      "Long-term strategy is top management's role.", "ERR_EMS_G8B3A1_MD", 2),
    MC("Why does a business have different levels of management?", ["So planning, organising and supervising happen at the right level", "To confuse staff", "To avoid all work", "To remove all decisions"], "So planning, organising and supervising happen at the right level",
      "Different levels handle big-picture planning down to daily supervision.", "ERR_EMS_G8B3A1_WHY", 2),
    MC("Which level is closest to the everyday workers?", ["Lower management", "Top management", "The board only", "Shareholders"], "Lower management",
      "Lower (first-line) management works most directly with everyday staff.", "ERR_EMS_G8B3A1_CLOSEST", 2),
    MC("Which order goes from highest to lowest authority?", ["Top, middle, lower", "Lower, middle, top", "Middle, top, lower", "Lower, top, middle"], "Top, middle, lower",
      "Authority decreases from top, to middle, to lower management.", "ERR_EMS_G8B3A1_ORDER", 2),
    MC("Decisions affecting the whole business are usually made by ____.", ["top management", "lower management", "individual workers", "customers"], "top management",
      "Whole-business decisions are top management's responsibility.", "ERR_EMS_G8B3A1_WHOLE", 2),
    TF("Management is usually grouped into top, middle and lower levels.", "True",
      "These are the three broad management levels.", "ERR_EMS_G8B3A1_TF1", 1),
    TF("Top management plans the overall direction of the business.", "True",
      "Top management sets vision and major plans.", "ERR_EMS_G8B3A1_TF2", 1),
    TF("Lower management sets the company's long-term strategy.", "False",
      "Long-term strategy is top management; lower management supervises daily work.", "ERR_EMS_G8B3A1_TF3", 1),
    TF("Middle management connects top plans with the teams doing the work.", "True",
      "Middle management turns plans into action through teams.", "ERR_EMS_G8B3A1_TF4", 2),
    CLOZE("The three levels of management are top, middle and ____.", ["lower", "outer", "side", "extra"], "lower",
      "Top, middle and lower are the three levels.", "ERR_EMS_G8B3A1_CL1", 1),
    CLOZE("____ management sets the overall direction of the business.", ["Top", "Lower", "First-line", "No"], "Top",
      "Top management sets the overall direction.", "ERR_EMS_G8B3A1_CL2", 1),
    CLOZE("____ management supervises workers day to day.", ["Lower", "Top", "Senior", "Executive"], "Lower",
      "Lower management supervises daily work.", "ERR_EMS_G8B3A1_CL3", 1),
    CLOZE("____ management turns top plans into action for teams.", ["Middle", "Top", "Lower", "No"], "Middle",
      "Middle management carries out plans through teams.", "ERR_EMS_G8B3A1_CL4", 2),
    {
      question: "Sort each role into 'Top', 'Middle' or 'Lower' management.",
      input_type: "sort-buckets",
      buckets: [{ id: "top", label: "Top" }, { id: "middle", label: "Middle" }, { id: "lower", label: "Lower" }],
      items: [
        { id: "i1", text: "Managing director setting strategy", correct_bucket: "top" },
        { id: "i2", text: "Department manager organising a team", correct_bucket: "middle" },
        { id: "i3", text: "Shift supervisor checking daily tasks", correct_bucket: "lower" },
        { id: "i4", text: "Board planning the company's future", correct_bucket: "top" },
      ],
      expected: "Strategy and board planning are top; organising teams is middle; daily supervision is lower.",
      pass_threshold: 0.75,
      memo: "Top sets direction, middle organises teams, lower supervises daily work.", error_signals: ["ERR_EMS_G8B3A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the management levels in order from highest to lowest authority.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Top management" },
        { id: "b", text: "Middle management" },
        { id: "c", text: "Lower (first-line) management" },
        { id: "d", text: "Workers carrying out tasks" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Authority flows from top, to middle, to lower management, then to the workers.",
      error_signals: ["ERR_EMS_G8B3A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · Management tasks
  "EMS.G8.B3.A2": [
    MC("What are the four main management tasks?", ["Planning, organising, leading and controlling", "Buying, selling, eating and sleeping", "Only planning", "Only controlling"], "Planning, organising, leading and controlling",
      "The four management tasks are planning, organising, leading and controlling.", "ERR_EMS_G8B3A2_FOUR", 1),
    MC("What is 'planning' in management?", ["Deciding goals and how to reach them", "Punishing workers", "Ignoring the future", "Spending randomly"], "Deciding goals and how to reach them",
      "Planning sets goals and the steps to achieve them.", "ERR_EMS_G8B3A2_PLAN", 1),
    MC("What is 'organising' in management?", ["Arranging people and resources to carry out the plan", "Avoiding all work", "Throwing away resources", "Ignoring staff"], "Arranging people and resources to carry out the plan",
      "Organising arranges people and resources to put the plan into action.", "ERR_EMS_G8B3A2_ORG", 1),
    MC("What is 'leading' in management?", ["Guiding and motivating workers", "Ignoring workers", "Sitting alone", "Hiding from staff"], "Guiding and motivating workers",
      "Leading guides and motivates people to do their work well.", "ERR_EMS_G8B3A2_LEAD", 1),
    MC("What is 'controlling' in management?", ["Checking progress and fixing problems", "Doing nothing", "Avoiding feedback", "Ignoring results"], "Checking progress and fixing problems",
      "Controlling checks results against the plan and corrects problems.", "ERR_EMS_G8B3A2_CONTROL", 1),
    MC("Setting a sales target for the year is an example of ____.", ["planning", "controlling", "leading", "organising"], "planning",
      "Setting goals/targets is planning.", "ERR_EMS_G8B3A2_PLAN_EX", 2),
    MC("Motivating a team to work hard is an example of ____.", ["leading", "controlling", "planning", "organising"], "leading",
      "Motivating people is part of leading.", "ERR_EMS_G8B3A2_LEAD_EX", 2),
    MC("Checking whether the sales target was met is an example of ____.", ["controlling", "planning", "organising", "leading"], "controlling",
      "Comparing results to the plan is controlling.", "ERR_EMS_G8B3A2_CONTROL_EX", 2),
    MC("Assigning staff to tasks and providing the tools they need is ____.", ["organising", "controlling", "leading", "planning"], "organising",
      "Arranging people and resources is organising.", "ERR_EMS_G8B3A2_ORG_EX", 2),
    MC("Why are the four management tasks important?", ["They help a business run smoothly and reach its goals", "They waste time", "They stop the business", "They remove all goals"], "They help a business run smoothly and reach its goals",
      "Together the tasks keep the business organised and on track.", "ERR_EMS_G8B3A2_WHY", 2),
    TF("Planning, organising, leading and controlling are the four management tasks.", "True",
      "These are the four core management tasks.", "ERR_EMS_G8B3A2_TF1", 1),
    TF("Controlling means checking progress and fixing problems.", "True",
      "Controlling compares results to the plan and corrects issues.", "ERR_EMS_G8B3A2_TF2", 1),
    TF("Leading means ignoring and avoiding workers.", "False",
      "Leading means guiding and motivating workers, not ignoring them.", "ERR_EMS_G8B3A2_TF3", 1),
    TF("Planning happens before organising and controlling.", "True",
      "You plan first, then organise to act, and control to check results.", "ERR_EMS_G8B3A2_TF4", 2),
    CLOZE("Deciding goals and how to reach them is ____.", ["planning", "controlling", "leading", "organising"], "planning",
      "Planning sets goals and steps.", "ERR_EMS_G8B3A2_CL1", 1),
    CLOZE("Arranging people and resources to act is ____.", ["organising", "planning", "leading", "controlling"], "organising",
      "Organising arranges resources to carry out the plan.", "ERR_EMS_G8B3A2_CL2", 1),
    CLOZE("Guiding and motivating workers is ____.", ["leading", "controlling", "planning", "organising"], "leading",
      "Leading guides and motivates people.", "ERR_EMS_G8B3A2_CL3", 1),
    CLOZE("Checking progress and correcting problems is ____.", ["controlling", "planning", "leading", "organising"], "controlling",
      "Controlling checks and corrects results.", "ERR_EMS_G8B3A2_CL4", 1),
    {
      question: "Sort each action under the management task it shows.",
      input_type: "sort-buckets",
      buckets: [{ id: "planning", label: "Planning" }, { id: "organising", label: "Organising" }, { id: "leading", label: "Leading" }, { id: "controlling", label: "Controlling" }],
      items: [
        { id: "i1", text: "Setting next month's targets", correct_bucket: "planning" },
        { id: "i2", text: "Assigning staff to their tasks", correct_bucket: "organising" },
        { id: "i3", text: "Motivating the team", correct_bucket: "leading" },
        { id: "i4", text: "Checking if targets were met", correct_bucket: "controlling" },
      ],
      expected: "Targets = planning; assigning staff = organising; motivating = leading; checking results = controlling.",
      pass_threshold: 0.75,
      memo: "Plan (goals), organise (resources), lead (motivate), control (check).", error_signals: ["ERR_EMS_G8B3A2_SORT"], difficulty: 3,
    },
    {
      question: "Put the management tasks in their usual order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Plan the goals" },
        { id: "b", text: "Organise people and resources" },
        { id: "c", text: "Lead and motivate the team" },
        { id: "d", text: "Control: check results and correct problems" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Plan, organise, lead, then control — the management cycle.",
      error_signals: ["ERR_EMS_G8B3A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Management styles
  "EMS.G8.B3.A3": [
    MC("What is an autocratic management style?", ["The manager makes decisions alone and tells staff what to do", "Staff make all decisions", "No one makes any decisions", "Customers decide everything"], "The manager makes decisions alone and tells staff what to do",
      "Autocratic managers decide alone and direct staff.", "ERR_EMS_G8B3A3_AUTO", 1),
    MC("What is a democratic (participatory) style?", ["The manager involves staff in decisions", "The manager decides everything alone", "No one is in charge", "Staff are ignored"], "The manager involves staff in decisions",
      "Democratic managers involve staff and seek their input.", "ERR_EMS_G8B3A3_DEMO", 1),
    MC("What is a laissez-faire (free-reign) style?", ["The manager gives staff freedom to decide how to work", "The manager controls every detail", "Staff have no freedom", "No work happens"], "The manager gives staff freedom to decide how to work",
      "Laissez-faire managers give staff freedom with little direct control.", "ERR_EMS_G8B3A3_LAISSEZ", 2),
    MC("Which style is best when quick, firm decisions are needed in an emergency?", ["Autocratic", "Laissez-faire", "No management", "None ever"], "Autocratic",
      "Autocratic decisions can be fast, useful in emergencies.", "ERR_EMS_G8B3A3_EMERGENCY", 2),
    MC("Which style usually makes staff feel most involved?", ["Democratic", "Autocratic", "No leadership", "Ignoring staff"], "Democratic",
      "Involving staff in decisions makes them feel valued.", "ERR_EMS_G8B3A3_INVOLVED", 2),
    MC("A characteristic of good management is ____.", ["clear communication and fairness", "ignoring staff", "unfair treatment", "no planning"], "clear communication and fairness",
      "Good managers communicate clearly and treat staff fairly.", "ERR_EMS_G8B3A3_GOOD", 1),
    MC("A laissez-faire style works best when staff are ____.", ["skilled and self-motivated", "untrained and unsure", "unwilling to work", "brand new with no skills"], "skilled and self-motivated",
      "Free-reign suits skilled, self-motivated staff who need little direction.", "ERR_EMS_G8B3A3_LAISSEZ_WHEN", 3),
    MC("A manager who never lets staff give input is using a(n) ____ style.", ["autocratic", "democratic", "participatory", "free-reign"], "autocratic",
      "Deciding alone with no input is autocratic.", "ERR_EMS_G8B3A3_AUTO_EX", 2),
    MC("Which is a possible downside of an autocratic style?", ["Staff may feel undervalued", "Staff feel too involved", "Decisions are too slow", "Too much freedom"], "Staff may feel undervalued",
      "Always deciding alone can make staff feel undervalued.", "ERR_EMS_G8B3A3_AUTO_DIS", 2),
    MC("Which best matches styles to their idea?", ["Autocratic = 'I decide'; democratic = 'we decide'; laissez-faire = 'you decide'", "All three mean the same", "Autocratic = 'you decide'", "Democratic = 'I decide alone'"], "Autocratic = 'I decide'; democratic = 'we decide'; laissez-faire = 'you decide'",
      "These short phrases capture each style's approach to decisions.", "ERR_EMS_G8B3A3_MATCH", 3),
    TF("An autocratic manager makes decisions alone.", "True",
      "Autocratic managers decide alone and direct staff.", "ERR_EMS_G8B3A3_TF1", 1),
    TF("A democratic manager involves staff in decisions.", "True",
      "Democratic managers seek staff input.", "ERR_EMS_G8B3A3_TF2", 1),
    TF("A laissez-faire manager controls every small detail.", "False",
      "Laissez-faire managers give staff freedom and avoid controlling every detail.", "ERR_EMS_G8B3A3_TF3", 1),
    TF("Good management includes clear communication and fairness.", "True",
      "Clear communication and fairness are marks of good management.", "ERR_EMS_G8B3A3_TF4", 1),
    CLOZE("A manager who decides alone uses an ____ style.", ["autocratic", "democratic", "free-reign", "shared"], "autocratic",
      "Deciding alone is autocratic.", "ERR_EMS_G8B3A3_CL1", 1),
    CLOZE("A manager who involves staff uses a ____ style.", ["democratic", "autocratic", "controlling", "strict"], "democratic",
      "Involving staff is democratic.", "ERR_EMS_G8B3A3_CL2", 1),
    CLOZE("A manager who gives staff freedom uses a ____ (free-reign) style.", ["laissez-faire", "autocratic", "strict", "controlling"], "laissez-faire",
      "Giving staff freedom is laissez-faire.", "ERR_EMS_G8B3A3_CL3", 2),
    CLOZE("Good managers communicate clearly and treat staff ____.", ["fairly", "harshly", "unfairly", "rudely"], "fairly",
      "Fair treatment is part of good management.", "ERR_EMS_G8B3A3_CL4", 1),
    {
      question: "Sort each example into 'Autocratic', 'Democratic' or 'Laissez-faire'.",
      input_type: "sort-buckets",
      buckets: [{ id: "auto", label: "Autocratic" }, { id: "demo", label: "Democratic" }, { id: "laissez", label: "Laissez-faire" }],
      items: [
        { id: "i1", text: "The manager decides alone and gives orders", correct_bucket: "auto" },
        { id: "i2", text: "The manager asks the team to vote on a plan", correct_bucket: "demo" },
        { id: "i3", text: "The manager lets skilled staff choose how to work", correct_bucket: "laissez" },
        { id: "i4", text: "The manager involves everyone before deciding", correct_bucket: "demo" },
      ],
      expected: "Deciding alone = autocratic; voting/involving = democratic; giving freedom = laissez-faire.",
      pass_threshold: 0.75,
      memo: "'I decide' = autocratic; 'we decide' = democratic; 'you decide' = laissez-faire.", error_signals: ["ERR_EMS_G8B3A3_SORT"], difficulty: 3,
    },
    {
      question: "Put these styles in order from most manager control to most staff freedom.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Autocratic (manager decides everything)" },
        { id: "b", text: "Democratic (manager and staff decide together)" },
        { id: "c", text: "Laissez-faire (staff decide how to work)" },
        { id: "d", text: "Staff working with full freedom" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Control decreases from autocratic, to democratic, to laissez-faire and full freedom.",
      error_signals: ["ERR_EMS_G8B3A3_SEQ"], difficulty: 2,
    },
  ],
};

export default G8C;
