// ─── EMS SP — Grade 8 authored pools (A): The Economy ─────────────────────────
// Strand: The Economy (CAPS G8). Tap-only: choice / true-false / cloze /
// sequence / sort-buckets. Recipe: 10 MC · 4 TF · 4 CLOZE · 1 sequence · 1 sort.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8 = {
  // ─── E1 · Term 1 — Government ───────────────────────────────────────────────
  // A1 · Levels of government
  "EMS.G8.E1.A1": [
    MC("What is government?", ["The body that makes and enforces a country's laws and provides services", "A type of private business", "A bank for citizens", "A shop in a mall"], "The body that makes and enforces a country's laws and provides services",
      "Government runs the country — making laws, providing services and managing public resources.", "ERR_EMS_G8E1A1_DEF", 1),
    MC("How many main levels of government does South Africa have?", ["Three", "One", "Five", "Ten"], "Three",
      "South Africa has three levels: national, provincial and local government.", "ERR_EMS_G8E1A1_THREE", 1),
    MC("Which is the national level of government mainly responsible for?", ["The whole country", "Only one street", "A single shop", "One household"], "The whole country",
      "National government deals with matters affecting the entire country.", "ERR_EMS_G8E1A1_NATIONAL", 1),
    MC("Which level of government runs a province like Gauteng or the Western Cape?", ["Provincial government", "Local government", "A private company", "A household"], "Provincial government",
      "Provincial government manages matters within a province.", "ERR_EMS_G8E1A1_PROVINCIAL", 1),
    MC("Which level of government runs towns and cities (e.g. a municipality)?", ["Local government", "National government", "Provincial government", "A bank"], "Local government",
      "Local government (municipalities) handles town and city services.", "ERR_EMS_G8E1A1_LOCAL", 1),
    MC("Collecting rubbish and supplying water to a town is usually the job of ____.", ["local government", "national government", "a private bank", "another country"], "local government",
      "Day-to-day services like water and refuse are local government duties.", "ERR_EMS_G8E1A1_SERVICES", 2),
    MC("Which matter is most likely handled by national government?", ["Defence of the country", "Fixing one town's potholes", "Collecting one suburb's bins", "Running one local clinic"], "Defence of the country",
      "Country-wide matters such as defence are national government responsibilities.", "ERR_EMS_G8E1A1_NAT_EX", 2),
    MC("Why does a country need different levels of government?", ["To manage matters at national, provincial and local scale", "To confuse citizens", "To avoid all services", "To remove all laws"], "To manage matters at national, provincial and local scale",
      "Different levels handle issues best dealt with at their scale, from country-wide to local.", "ERR_EMS_G8E1A1_WHY", 2),
    MC("A municipality is part of which level of government?", ["Local", "National", "Provincial", "International"], "Local",
      "Municipalities are local government.", "ERR_EMS_G8E1A1_MUNI", 1),
    MC("Which statement correctly orders government from widest to narrowest area?", ["National, provincial, local", "Local, provincial, national", "Provincial, national, local", "Local, national, provincial"], "National, provincial, local",
      "National covers the whole country, provincial a province, and local a town or city.", "ERR_EMS_G8E1A1_ORDER", 2),
    TF("South Africa has national, provincial and local levels of government.", "True",
      "These are the three levels of government.", "ERR_EMS_G8E1A1_TF1", 1),
    TF("Local government is responsible for the whole country.", "False",
      "Local government handles towns and cities; the whole country is national government's role.", "ERR_EMS_G8E1A1_TF2", 1),
    TF("Provincial government manages matters within a province.", "True",
      "Provincial government deals with province-level matters.", "ERR_EMS_G8E1A1_TF3", 1),
    TF("Government makes and enforces laws and provides public services.", "True",
      "These are core functions of government.", "ERR_EMS_G8E1A1_TF4", 1),
    CLOZE("The level of government that runs the whole country is ____ government.", ["national", "local", "private", "personal"], "national",
      "National government handles country-wide matters.", "ERR_EMS_G8E1A1_CL1", 1),
    CLOZE("A municipality is part of ____ government.", ["local", "national", "provincial", "global"], "local",
      "Municipalities are local government.", "ERR_EMS_G8E1A1_CL2", 1),
    CLOZE("A province is run by ____ government.", ["provincial", "local", "national", "foreign"], "provincial",
      "Provincial government runs a province.", "ERR_EMS_G8E1A1_CL3", 1),
    CLOZE("Government provides public ____ such as water, health and education.", ["services", "profits", "loans", "adverts"], "services",
      "Government supplies public services to citizens.", "ERR_EMS_G8E1A1_CL4", 1),
    {
      question: "Sort each responsibility to its level of government.",
      input_type: "sort-buckets",
      buckets: [{ id: "national", label: "National" }, { id: "provincial", label: "Provincial" }, { id: "local", label: "Local" }],
      items: [
        { id: "i1", text: "Defending the country", correct_bucket: "national" },
        { id: "i2", text: "Running a province's schools", correct_bucket: "provincial" },
        { id: "i3", text: "Collecting a town's refuse", correct_bucket: "local" },
        { id: "i4", text: "Supplying water to a municipality's homes", correct_bucket: "local" },
      ],
      expected: "Defence is national; provincial schools are provincial; refuse and water are local.",
      pass_threshold: 0.75,
      memo: "National = whole country; provincial = a province; local = a town/city.", error_signals: ["ERR_EMS_G8E1A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the levels of government in order from the widest area to the smallest.",
      input_type: "sequence",
      items: [
        { id: "a", text: "National (the whole country)" },
        { id: "b", text: "Provincial (a province)" },
        { id: "c", text: "Local (a municipality)" },
        { id: "d", text: "The households the municipality serves" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "From widest to smallest: national, provincial, local, then the households served.",
      error_signals: ["ERR_EMS_G8E1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Government and households
  "EMS.G8.E1.A2": [
    MC("How does government act as a producer for households?", ["By providing services like water, electricity and roads", "By only taking money", "By buying nothing", "By closing schools"], "By providing services like water, electricity and roads",
      "Government produces public services that households use, such as water and roads.", "ERR_EMS_G8E1A2_PRODUCER", 1),
    MC("How can government act as a consumer in relation to households?", ["By buying goods and services, including people's labour", "By never spending", "By refusing to employ anyone", "By giving away free factories"], "By buying goods and services, including people's labour",
      "Government consumes by employing people and buying goods and services.", "ERR_EMS_G8E1A2_CONSUMER", 2),
    MC("When government employs a nurse from a household, government is acting as a ____.", ["consumer (buyer of labour)", "producer only", "bank", "shop"], "consumer (buyer of labour)",
      "Employing labour means government is consuming (buying) that labour.", "ERR_EMS_G8E1A2_EMPLOY", 2),
    MC("Which is a service government provides to households?", ["Public schooling", "Private profit", "Shop discounts", "Company shares"], "Public schooling",
      "Public schooling is a government service for households.", "ERR_EMS_G8E1A2_SCHOOL", 1),
    MC("Households pay government mainly through ____.", ["taxes", "gifts", "loans to citizens", "free donations only"], "taxes",
      "Households fund government services largely through taxes.", "ERR_EMS_G8E1A2_TAX", 2),
    MC("Why do households rely on government services?", ["Some services are best provided for everyone together", "Households can never buy anything", "Government owns all households", "Households produce nothing"], "Some services are best provided for everyone together",
      "Shared services like roads and clinics are efficiently provided to all by government.", "ERR_EMS_G8E1A2_RELY", 2),
    MC("Government building a clinic that families use shows government as a ____.", ["producer of services", "consumer only", "private firm", "household"], "producer of services",
      "Providing a clinic is government producing a public service.", "ERR_EMS_G8E1A2_CLINIC", 1),
    MC("A household provides government with ____ when its members work in the public service.", ["labour", "taxes only", "nothing", "shares"], "labour",
      "Household members supply labour to government as public-service workers.", "ERR_EMS_G8E1A2_LABOUR", 2),
    MC("Which best describes the relationship between government and households?", ["They exchange services, labour and taxes with each other", "They never interact", "Households control government's budget directly", "Government ignores households"], "They exchange services, labour and taxes with each other",
      "Government provides services and employs labour; households pay taxes and supply labour.", "ERR_EMS_G8E1A2_RELATION", 3),
    MC("Free basic water provided to poor households is an example of government as a ____.", ["producer of a service", "consumer of labour", "private business", "bank"], "producer of a service",
      "Supplying free basic water is government producing a public service.", "ERR_EMS_G8E1A2_WATER", 2),
    TF("Government provides services such as water, roads and schooling to households.", "True",
      "These are public services government produces for households.", "ERR_EMS_G8E1A2_TF1", 1),
    TF("Government can act as a consumer by employing people from households.", "True",
      "Employing labour is a form of government consumption.", "ERR_EMS_G8E1A2_TF2", 1),
    TF("Households pay for many government services through taxes.", "True",
      "Taxes from households help fund government services.", "ERR_EMS_G8E1A2_TF3", 1),
    TF("Government only takes from households and never provides anything.", "False",
      "Government provides many services to households in return for taxes.", "ERR_EMS_G8E1A2_TF4", 1),
    CLOZE("Government acts as a ____ when it supplies services like roads and water.", ["producer", "consumer", "bank", "shop"], "producer",
      "Supplying services is government producing.", "ERR_EMS_G8E1A2_CL1", 1),
    CLOZE("Government acts as a ____ when it buys goods or employs workers.", ["consumer", "producer", "saver", "lender"], "consumer",
      "Buying and employing is government consuming.", "ERR_EMS_G8E1A2_CL2", 2),
    CLOZE("Households help fund government services by paying ____.", ["taxes", "rent", "shares", "gifts"], "taxes",
      "Taxes are the main way households fund government.", "ERR_EMS_G8E1A2_CL3", 1),
    CLOZE("When a household member works as a teacher in a public school, they supply ____ to government.", ["labour", "tax", "stock", "profit"], "labour",
      "Public-service workers supply labour to government.", "ERR_EMS_G8E1A2_CL4", 2),
    {
      question: "Sort each action into 'Government as producer' or 'Government as consumer' (towards households).",
      input_type: "sort-buckets",
      buckets: [{ id: "producer", label: "Government as producer" }, { id: "consumer", label: "Government as consumer" }],
      items: [
        { id: "i1", text: "Building public roads", correct_bucket: "producer" },
        { id: "i2", text: "Employing a household member as a nurse", correct_bucket: "consumer" },
        { id: "i3", text: "Running public clinics", correct_bucket: "producer" },
        { id: "i4", text: "Buying labour from households", correct_bucket: "consumer" },
      ],
      expected: "Building roads and running clinics are producing; employing and buying labour are consuming.",
      pass_threshold: 0.75,
      memo: "Producing = supplying services; consuming = buying goods/labour from households.", error_signals: ["ERR_EMS_G8E1A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the exchange between households and government in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Households earn income and pay taxes" },
        { id: "b", text: "Government collects the tax revenue" },
        { id: "c", text: "Government provides services like schools and roads" },
        { id: "d", text: "Households use those services" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Households pay tax, government collects it, provides services, and households use them.",
      error_signals: ["ERR_EMS_G8E1A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Government and businesses
  "EMS.G8.E1.A3": [
    MC("How can government act as a consumer towards businesses?", ["By buying goods and services from them", "By never buying anything", "By closing all businesses", "By giving away free goods"], "By buying goods and services from them",
      "Government buys goods and services from businesses, acting as a consumer.", "ERR_EMS_G8E1A3_CONSUMER", 1),
    MC("How can government act as a producer towards businesses?", ["By providing services like roads and electricity they use", "By only taxing them", "By buying nothing", "By banning all trade"], "By providing services like roads and electricity they use",
      "Government produces infrastructure and services businesses rely on.", "ERR_EMS_G8E1A3_PRODUCER", 2),
    MC("When government buys computers from a company, government is a ____.", ["consumer", "producer only", "household", "bank"], "consumer",
      "Buying computers makes government a consumer of that business's goods.", "ERR_EMS_G8E1A3_BUY", 1),
    MC("Businesses pay government ____ on their profits and sales.", ["taxes", "gifts", "rent only", "wages"], "taxes",
      "Businesses pay taxes to government on profits and sales.", "ERR_EMS_G8E1A3_TAX", 2),
    MC("Government building roads that businesses use to transport goods is government as a ____.", ["producer of services", "consumer of goods", "private firm", "household"], "producer of services",
      "Providing roads is government producing a service businesses use.", "ERR_EMS_G8E1A3_ROADS", 2),
    MC("Why is good infrastructure (roads, electricity) important for businesses?", ["It helps them produce and deliver goods", "It stops them trading", "It removes all customers", "It raises no value"], "It helps them produce and deliver goods",
      "Reliable infrastructure lets businesses operate and deliver efficiently.", "ERR_EMS_G8E1A3_INFRA", 2),
    MC("Which is an example of government as a consumer of business output?", ["Buying office furniture from a supplier", "Building a public road", "Running a public school", "Defending the country"], "Buying office furniture from a supplier",
      "Purchasing furniture from a supplier is consuming a business's goods.", "ERR_EMS_G8E1A3_CONS_EX", 2),
    MC("Government can support businesses by ____.", ["providing services and a stable environment to trade", "banning all trade", "removing all roads", "taking all profits"], "providing services and a stable environment to trade",
      "Government supports business through infrastructure, services and stable rules.", "ERR_EMS_G8E1A3_SUPPORT", 2),
    MC("Which shows government as both consumer and producer for businesses?", ["It buys their goods AND provides roads they use", "It only ignores them", "It only closes them", "It does nothing at all"], "It buys their goods AND provides roads they use",
      "Government consumes business goods and produces services businesses depend on.", "ERR_EMS_G8E1A3_BOTH", 3),
    MC("Taxes paid by businesses help government to ____.", ["fund public services", "lose money", "stop providing services", "avoid all spending"], "fund public services",
      "Business taxes help fund the services government provides.", "ERR_EMS_G8E1A3_FUND", 2),
    TF("Government can buy goods and services from businesses.", "True",
      "Government is a consumer when it purchases from businesses.", "ERR_EMS_G8E1A3_TF1", 1),
    TF("Government provides infrastructure that businesses use.", "True",
      "Roads, electricity and other services support businesses.", "ERR_EMS_G8E1A3_TF2", 1),
    TF("Businesses never pay any tax to government.", "False",
      "Businesses pay taxes on profits and sales.", "ERR_EMS_G8E1A3_TF3", 1),
    TF("Government can be both a consumer of business goods and a producer of services.", "True",
      "It buys from businesses and provides services they use.", "ERR_EMS_G8E1A3_TF4", 2),
    CLOZE("Government acts as a ____ when it buys goods from businesses.", ["consumer", "producer", "saver", "lender"], "consumer",
      "Buying from businesses is consuming.", "ERR_EMS_G8E1A3_CL1", 1),
    CLOZE("Government acts as a ____ when it provides roads and electricity to businesses.", ["producer", "consumer", "bank", "shop"], "producer",
      "Providing infrastructure is producing services.", "ERR_EMS_G8E1A3_CL2", 1),
    CLOZE("Businesses pay ____ to government on their profits.", ["tax", "rent", "wages", "shares"], "tax",
      "Businesses pay tax on profits and sales.", "ERR_EMS_G8E1A3_CL3", 1),
    CLOZE("Good ____, like roads and power, helps businesses operate.", ["infrastructure", "advertising", "saving", "bartering"], "infrastructure",
      "Infrastructure supports business activity.", "ERR_EMS_G8E1A3_CL4", 2),
    {
      question: "Sort each into 'Government as producer' or 'Government as consumer' (towards businesses).",
      input_type: "sort-buckets",
      buckets: [{ id: "producer", label: "Government as producer" }, { id: "consumer", label: "Government as consumer" }],
      items: [
        { id: "i1", text: "Building roads businesses use", correct_bucket: "producer" },
        { id: "i2", text: "Buying uniforms from a factory", correct_bucket: "consumer" },
        { id: "i3", text: "Supplying electricity infrastructure", correct_bucket: "producer" },
        { id: "i4", text: "Ordering computers from a supplier", correct_bucket: "consumer" },
      ],
      expected: "Roads and electricity are producing; buying uniforms and computers is consuming.",
      pass_threshold: 0.75,
      memo: "Producing = providing services/infrastructure; consuming = buying business goods.", error_signals: ["ERR_EMS_G8E1A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the exchange between government and a business in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Government provides roads and electricity" },
        { id: "b", text: "A business uses them to produce goods" },
        { id: "c", text: "Government buys some of the goods" },
        { id: "d", text: "The business pays tax on its profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Government provides infrastructure, the business produces and sells (some to government), then pays tax.",
      error_signals: ["ERR_EMS_G8E1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── E2 · Term 1 — The National Budget ─────────────────────────────────────
  // A1 · Government revenue: tax
  "EMS.G8.E2.A1": [
    MC("What is government revenue?", ["The money government receives, mainly from taxes", "Money government throws away", "A private company's profit", "A household's savings"], "The money government receives, mainly from taxes",
      "Government revenue is the income government collects, largely through taxes.", "ERR_EMS_G8E2A1_DEF", 1),
    MC("What is direct tax?", ["Tax charged directly on income or profits", "Tax added to the price of goods", "A gift to government", "A bank fee"], "Tax charged directly on income or profits",
      "Direct tax is paid directly on income or profit, like income tax.", "ERR_EMS_G8E2A1_DIRECT", 1),
    MC("What is indirect tax?", ["Tax added to the price of goods and services", "Tax on a person's salary", "A tax on company profits", "A free service"], "Tax added to the price of goods and services",
      "Indirect tax is added to what you buy, like VAT.", "ERR_EMS_G8E2A1_INDIRECT", 1),
    MC("VAT (Value-Added Tax) is an example of ____.", ["indirect tax", "direct tax", "a government service", "a household saving"], "indirect tax",
      "VAT is added to prices of goods and services, so it is indirect tax.", "ERR_EMS_G8E2A1_VAT", 2),
    MC("Income tax on a person's salary is an example of ____.", ["direct tax", "indirect tax", "a gift", "a loan"], "direct tax",
      "Income tax is charged directly on income, so it is direct tax.", "ERR_EMS_G8E2A1_INCOMETAX", 2),
    MC("Why does government collect taxes?", ["To pay for public services", "To waste money", "To avoid serving citizens", "To close schools"], "To pay for public services",
      "Tax revenue funds public services like health, education and roads.", "ERR_EMS_G8E2A1_WHY", 1),
    MC("Which is the main source of government revenue?", ["Taxes", "Lottery tickets only", "Selling sweets", "Gifts from other countries only"], "Taxes",
      "Taxes are the main source of government revenue.", "ERR_EMS_G8E2A1_SOURCE", 1),
    MC("When you pay extra on a shop item because of VAT, you are paying ____.", ["indirect tax", "direct tax", "income tax", "a wage"], "indirect tax",
      "VAT added at the till is an indirect tax.", "ERR_EMS_G8E2A1_TILL", 2),
    MC("Which statement about direct and indirect tax is correct?", ["Direct tax is on income/profit; indirect tax is on spending", "Both are only on income", "Both are only on spending", "They are the same thing"], "Direct tax is on income/profit; indirect tax is on spending",
      "Direct tax targets income/profit; indirect tax targets spending on goods/services.", "ERR_EMS_G8E2A1_COMPARE", 3),
    MC("More people earning and spending usually means government collects ____.", ["more tax revenue", "less tax revenue", "no tax", "only gifts"], "more tax revenue",
      "More income and spending generally raises tax revenue.", "ERR_EMS_G8E2A1_MORE", 2),
    TF("Taxes are the main source of government revenue.", "True",
      "Government revenue comes mainly from taxes.", "ERR_EMS_G8E2A1_TF1", 1),
    TF("Direct tax is charged on income or profits.", "True",
      "Direct tax targets income and profits.", "ERR_EMS_G8E2A1_TF2", 1),
    TF("VAT is a direct tax on your salary.", "False",
      "VAT is an indirect tax added to goods and services, not a direct tax on salary.", "ERR_EMS_G8E2A1_TF3", 1),
    TF("Tax revenue helps pay for public services.", "True",
      "Government uses tax revenue to fund public services.", "ERR_EMS_G8E2A1_TF4", 1),
    CLOZE("Money government receives, mostly from taxes, is government ____.", ["revenue", "expense", "saving", "loss"], "revenue",
      "Government revenue is the income it collects.", "ERR_EMS_G8E2A1_CL1", 1),
    CLOZE("Tax charged on income or profit is ____ tax.", ["direct", "indirect", "free", "hidden"], "direct",
      "Direct tax is on income/profit.", "ERR_EMS_G8E2A1_CL2", 1),
    CLOZE("Tax added to the price of goods, like VAT, is ____ tax.", ["indirect", "direct", "income", "profit"], "indirect",
      "Indirect tax is added to spending.", "ERR_EMS_G8E2A1_CL3", 2),
    CLOZE("Government collects tax to pay for public ____.", ["services", "profits", "shares", "gifts"], "services",
      "Tax funds public services.", "ERR_EMS_G8E2A1_CL4", 1),
    {
      question: "Sort each tax into 'Direct tax' or 'Indirect tax'.",
      input_type: "sort-buckets",
      buckets: [{ id: "direct", label: "Direct tax" }, { id: "indirect", label: "Indirect tax" }],
      items: [
        { id: "i1", text: "Income tax on a salary", correct_bucket: "direct" },
        { id: "i2", text: "VAT on groceries", correct_bucket: "indirect" },
        { id: "i3", text: "Tax on company profits", correct_bucket: "direct" },
        { id: "i4", text: "Tax added to the price of fuel", correct_bucket: "indirect" },
      ],
      expected: "Income and company-profit taxes are direct; VAT and fuel tax are indirect.",
      pass_threshold: 0.75,
      memo: "Direct = on income/profit; indirect = added to what you buy.", error_signals: ["ERR_EMS_G8E2A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the flow of tax money in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "People earn income and businesses make profit" },
        { id: "b", text: "They pay direct and indirect taxes" },
        { id: "c", text: "Government collects the tax revenue" },
        { id: "d", text: "Government spends it on public services" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Earn/spend → pay tax → government collects revenue → funds public services.",
      error_signals: ["ERR_EMS_G8E2A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Government expenditure
  "EMS.G8.E2.A2": [
    MC("What is government expenditure?", ["The money government spends on services and projects", "The money government collects", "A household's savings", "A company's profit"], "The money government spends on services and projects",
      "Government expenditure is the spending government does on public services and projects.", "ERR_EMS_G8E2A2_DEF", 1),
    MC("Which is an example of government expenditure?", ["Paying teachers' salaries", "Collecting income tax", "A shop's profit", "A household's wage"], "Paying teachers' salaries",
      "Paying public-sector salaries is government spending.", "ERR_EMS_G8E2A2_EX", 1),
    MC("On which of these does government spend money?", ["Health, education and housing", "Only on itself secretly", "Nothing at all", "Private company profits"], "Health, education and housing",
      "Government spends on public services like health, education and housing.", "ERR_EMS_G8E2A2_AREAS", 1),
    MC("A social grant paid to a person in need is part of government ____.", ["expenditure", "revenue", "profit", "saving"], "expenditure",
      "Grants are money government pays out — expenditure.", "ERR_EMS_G8E2A2_GRANT", 2),
    MC("Why does government spend on education?", ["To build skills and improve the country's future", "To waste money", "To stop people learning", "To make a private profit"], "To build skills and improve the country's future",
      "Education spending builds skills and supports the country's development.", "ERR_EMS_G8E2A2_EDU", 2),
    MC("Spending on roads, bridges and electricity is spending on ____.", ["infrastructure", "groceries", "company shares", "advertising"], "infrastructure",
      "Roads, bridges and power are infrastructure.", "ERR_EMS_G8E2A2_INFRA", 2),
    MC("Which is NOT usually government expenditure?", ["A private shop's stock purchases", "Public hospital funding", "Police services", "School building"], "A private shop's stock purchases",
      "A private shop's stock is its own expense, not government expenditure.", "ERR_EMS_G8E2A2_NOT", 2),
    MC("Government spending on security includes ____.", ["police and defence", "private company profits", "household groceries", "shop advertising"], "police and defence",
      "Security spending covers police and defence services.", "ERR_EMS_G8E2A2_SECURITY", 1),
    MC("If government spends more than it collects in revenue, it has a ____.", ["budget deficit", "budget surplus", "profit", "saving"], "budget deficit",
      "Spending more than revenue produces a budget deficit.", "ERR_EMS_G8E2A2_DEFICIT", 3),
    MC("Why must government plan its expenditure carefully?", ["Its revenue is limited and needs must be prioritised", "Money is unlimited", "Services don't matter", "It has no income"], "Its revenue is limited and needs must be prioritised",
      "Limited revenue means government must prioritise where to spend.", "ERR_EMS_G8E2A2_PLAN", 2),
    TF("Government expenditure is the money government spends on services.", "True",
      "Expenditure is government's spending on public services and projects.", "ERR_EMS_G8E2A2_TF1", 1),
    TF("Social grants and salaries are forms of government expenditure.", "True",
      "Both are money government pays out.", "ERR_EMS_G8E2A2_TF2", 1),
    TF("Government spends money on health, education and security.", "True",
      "These are major areas of government expenditure.", "ERR_EMS_G8E2A2_TF3", 1),
    TF("Government expenditure means the tax it collects.", "False",
      "Collected tax is revenue; expenditure is what government spends.", "ERR_EMS_G8E2A2_TF4", 1),
    CLOZE("The money government spends on services is government ____.", ["expenditure", "revenue", "profit", "saving"], "expenditure",
      "Expenditure is government spending.", "ERR_EMS_G8E2A2_CL1", 1),
    CLOZE("Money paid to people in need, like a child-support grant, is a social ____.", ["grant", "tax", "loan", "share"], "grant",
      "Social grants support people in need.", "ERR_EMS_G8E2A2_CL2", 2),
    CLOZE("Roads, bridges and power lines are examples of ____.", ["infrastructure", "groceries", "shares", "adverts"], "infrastructure",
      "These are infrastructure that government funds.", "ERR_EMS_G8E2A2_CL3", 2),
    CLOZE("Government spends on ____ such as schools and universities.", ["education", "shopping", "advertising", "gambling"], "education",
      "Education is a major area of government spending.", "ERR_EMS_G8E2A2_CL4", 1),
    {
      question: "Sort each into 'Government expenditure' or 'Government revenue'.",
      input_type: "sort-buckets",
      buckets: [{ id: "expenditure", label: "Expenditure (spending)" }, { id: "revenue", label: "Revenue (income)" }],
      items: [
        { id: "i1", text: "Paying nurses' salaries", correct_bucket: "expenditure" },
        { id: "i2", text: "Collecting VAT", correct_bucket: "revenue" },
        { id: "i3", text: "Building a school", correct_bucket: "expenditure" },
        { id: "i4", text: "Receiving income tax", correct_bucket: "revenue" },
      ],
      expected: "Salaries and building schools are expenditure; collecting VAT and income tax is revenue.",
      pass_threshold: 0.75,
      memo: "Expenditure is money out; revenue is money in (tax).", error_signals: ["ERR_EMS_G8E2A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of government spending in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Government collects tax revenue" },
        { id: "b", text: "It plans a budget of where to spend" },
        { id: "c", text: "It spends on services like health and education" },
        { id: "d", text: "Citizens benefit from the services" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Collect revenue, plan the budget, spend on services, and citizens benefit.",
      error_signals: ["ERR_EMS_G8E2A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · The budget, growth and inequality
  "EMS.G8.E2.A3": [
    MC("What is the National Budget?", ["Government's plan for its revenue and spending for the year", "A single shop's accounts", "A household's grocery list", "A company's advert"], "Government's plan for its revenue and spending for the year",
      "The National Budget plans the country's government revenue and expenditure for the year.", "ERR_EMS_G8E2A3_DEF", 1),
    MC("How can the National Budget help economic growth?", ["By spending on infrastructure and services that support the economy", "By stopping all spending", "By closing schools", "By banning trade"], "By spending on infrastructure and services that support the economy",
      "Spending on roads, education and services helps the economy grow.", "ERR_EMS_G8E2A3_GROWTH", 2),
    MC("How can the budget help reduce inequality?", ["By spending more on services for poorer communities", "By ignoring the poor", "By taxing no one", "By removing all grants"], "By spending more on services for poorer communities",
      "Directing spending and grants to poorer communities helps reduce inequality.", "ERR_EMS_G8E2A3_INEQ", 2),
    MC("Social grants in the budget mainly help to ____.", ["support people with low or no income", "make rich people richer", "fund private profits", "increase inequality"], "support people with low or no income",
      "Grants provide income support to the poor, reducing inequality.", "ERR_EMS_G8E2A3_GRANTS", 2),
    MC("Who presents South Africa's National Budget?", ["The Minister of Finance", "A shop owner", "A school principal", "A bank teller"], "The Minister of Finance",
      "The Minister of Finance presents the National Budget.", "ERR_EMS_G8E2A3_MINISTER", 1),
    MC("Spending on education and skills in the budget can ____ over time.", ["reduce inequality and support growth", "increase poverty", "stop the economy", "remove all jobs"], "reduce inequality and support growth",
      "Education spending builds skills, supporting growth and reducing inequality.", "ERR_EMS_G8E2A3_EDU", 2),
    MC("A budget that invests in infrastructure can help businesses by ____.", ["making it easier to produce and transport goods", "blocking all roads", "removing electricity", "banning trade"], "making it easier to produce and transport goods",
      "Infrastructure spending supports business activity and growth.", "ERR_EMS_G8E2A3_INFRA", 2),
    MC("Why does the budget have to make choices?", ["Government revenue is limited, so it cannot fund everything fully", "Money is unlimited", "Nothing costs anything", "There are no needs"], "Government revenue is limited, so it cannot fund everything fully",
      "Limited revenue forces the budget to prioritise spending.", "ERR_EMS_G8E2A3_CHOICES", 2),
    MC("Which best shows the budget reducing inequality AND supporting growth?", ["Funding schools and clinics in poor areas while building roads", "Cutting all services", "Spending only on the wealthy", "Stopping all infrastructure"], "Funding schools and clinics in poor areas while building roads",
      "Targeted services reduce inequality, while infrastructure supports growth.", "ERR_EMS_G8E2A3_BOTH", 3),
    MC("The National Budget is best described as a tool to ____.", ["plan spending to grow the economy and address inequality", "waste public money", "avoid all planning", "hide government income"], "plan spending to grow the economy and address inequality",
      "The budget plans revenue and spending to grow the economy and tackle inequality.", "ERR_EMS_G8E2A3_TOOL", 2),
    TF("The National Budget is government's plan for revenue and spending.", "True",
      "It plans the year's government income and expenditure.", "ERR_EMS_G8E2A3_TF1", 1),
    TF("Spending on infrastructure can support economic growth.", "True",
      "Infrastructure helps the economy produce and grow.", "ERR_EMS_G8E2A3_TF2", 1),
    TF("The budget can be used to help reduce inequality.", "True",
      "Targeted spending and grants help reduce inequality.", "ERR_EMS_G8E2A3_TF3", 1),
    TF("The National Budget only lists income and ignores spending.", "False",
      "The budget plans both revenue and expenditure.", "ERR_EMS_G8E2A3_TF4", 1),
    CLOZE("Government's yearly plan for revenue and spending is the National ____.", ["Budget", "Bank", "Shop", "Wage"], "Budget",
      "The National Budget plans government finances for the year.", "ERR_EMS_G8E2A3_CL1", 1),
    CLOZE("Spending on roads and power, called ____, can support growth.", ["infrastructure", "advertising", "gambling", "shares"], "infrastructure",
      "Infrastructure spending supports economic growth.", "ERR_EMS_G8E2A3_CL2", 2),
    CLOZE("Social ____ in the budget support people with low income.", ["grants", "taxes", "profits", "loans"], "grants",
      "Grants give income support to the poor.", "ERR_EMS_G8E2A3_CL3", 2),
    CLOZE("The budget can help redress economic ____ by spending on poorer communities.", ["inequality", "growth", "profit", "saving"], "inequality",
      "Targeted spending helps reduce inequality.", "ERR_EMS_G8E2A3_CL4", 2),
    {
      question: "Sort each budget choice by its main aim.",
      input_type: "sort-buckets",
      buckets: [{ id: "growth", label: "Mainly supports growth" }, { id: "inequality", label: "Mainly reduces inequality" }],
      items: [
        { id: "i1", text: "Building new roads and ports", correct_bucket: "growth" },
        { id: "i2", text: "Paying child-support grants", correct_bucket: "inequality" },
        { id: "i3", text: "Investing in electricity supply", correct_bucket: "growth" },
        { id: "i4", text: "Funding clinics in poor areas", correct_bucket: "inequality" },
      ],
      expected: "Roads, ports and electricity support growth; grants and clinics in poor areas reduce inequality.",
      pass_threshold: 0.75,
      memo: "Infrastructure tends to drive growth; targeted social spending reduces inequality.", error_signals: ["ERR_EMS_G8E2A3_SORT"], difficulty: 3,
    },
    {
      question: "Put the National Budget process in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Government estimates its revenue (mostly tax)" },
        { id: "b", text: "It plans expenditure on services and projects" },
        { id: "c", text: "The Minister of Finance presents the budget" },
        { id: "d", text: "Spending supports growth and addresses inequality" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Estimate revenue, plan spending, present the budget, then spending drives growth and fairness.",
      error_signals: ["ERR_EMS_G8E2A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── E3 · Term 1 — Standard of living ──────────────────────────────────────
  // A1 · Lifestyles and types of society
  "EMS.G8.E3.A1": [
    MC("What does 'standard of living' mean?", ["How comfortably people are able to live", "How tall people are", "How many people there are", "The weather in an area"], "How comfortably people are able to live",
      "Standard of living describes how comfortably and well people are able to live.", "ERR_EMS_G8E3A1_DEF", 1),
    MC("A self-sufficient society is one that ____.", ["produces most of what it needs itself", "buys everything from abroad", "produces nothing", "has no people"], "produces most of what it needs itself",
      "A self-sufficient society meets most of its own needs through its own production.", "ERR_EMS_G8E3A1_SELF", 2),
    MC("A modern society usually has ____.", ["advanced technology and many services", "no technology at all", "no trade", "no money"], "advanced technology and many services",
      "Modern societies typically have advanced technology, services and trade.", "ERR_EMS_G8E3A1_MODERN", 1),
    MC("A rural society is mostly found in ____.", ["the countryside", "big city centres", "factories only", "shopping malls"], "the countryside",
      "Rural societies are based in the countryside, often around farming.", "ERR_EMS_G8E3A1_RURAL", 1),
    MC("Which usually improves a person's standard of living?", ["Access to good services, income and education", "Less income and no services", "No schooling", "Poor healthcare"], "Access to good services, income and education",
      "Better income, services and education raise standard of living.", "ERR_EMS_G8E3A1_IMPROVE", 2),
    MC("Which is a sign of a higher standard of living?", ["Reliable access to clean water and electricity", "No access to water", "No healthcare", "No schooling"], "Reliable access to clean water and electricity",
      "Reliable basic services indicate a higher standard of living.", "ERR_EMS_G8E3A1_SIGN", 2),
    MC("A society that grows its own food and makes its own goods is best described as ____.", ["self-sufficient", "modern industrial", "purely urban", "fully imported"], "self-sufficient",
      "Producing your own food and goods is self-sufficiency.", "ERR_EMS_G8E3A1_SELF_EX", 2),
    MC("Why do standards of living differ between communities?", ["Differences in income, services and opportunities", "Everyone lives identically", "Living standards never differ", "Only the weather matters"], "Differences in income, services and opportunities",
      "Income, services and opportunities vary, so living standards differ.", "ERR_EMS_G8E3A1_DIFFER", 2),
    MC("Which lifestyle factor is part of standard of living?", ["Quality of housing and access to services", "Favourite colour", "Choice of music only", "Shoe size"], "Quality of housing and access to services",
      "Housing quality and service access are part of living standards.", "ERR_EMS_G8E3A1_FACTOR", 2),
    MC("A community moving from no electricity to reliable power has likely seen its standard of living ____.", ["rise", "fall", "disappear", "stay exactly the same"], "rise",
      "Gaining reliable electricity raises the standard of living.", "ERR_EMS_G8E3A1_RISE", 3),
    TF("Standard of living describes how comfortably people are able to live.", "True",
      "It measures how well and comfortably people live.", "ERR_EMS_G8E3A1_TF1", 1),
    TF("A self-sufficient society produces most of what it needs itself.", "True",
      "Self-sufficiency means meeting your own needs through your own production.", "ERR_EMS_G8E3A1_TF2", 1),
    TF("Access to services like water and electricity affects standard of living.", "True",
      "Basic services are a key part of living standards.", "ERR_EMS_G8E3A1_TF3", 1),
    TF("Every community in a country has exactly the same standard of living.", "False",
      "Living standards differ with income, services and opportunities.", "ERR_EMS_G8E3A1_TF4", 1),
    CLOZE("How comfortably people are able to live is their standard of ____.", ["living", "weather", "height", "music"], "living",
      "Standard of living measures how comfortably people live.", "ERR_EMS_G8E3A1_CL1", 1),
    CLOZE("A society that meets most of its own needs is ____.", ["self-sufficient", "modern", "urban", "imported"], "self-sufficient",
      "Self-sufficient societies produce most of what they need.", "ERR_EMS_G8E3A1_CL2", 2),
    CLOZE("A society based in the countryside is a ____ society.", ["rural", "urban", "modern", "factory"], "rural",
      "Rural societies are countryside-based.", "ERR_EMS_G8E3A1_CL3", 1),
    CLOZE("Good income, education and services usually ____ standard of living.", ["raise", "lower", "remove", "hide"], "raise",
      "These factors raise living standards.", "ERR_EMS_G8E3A1_CL4", 2),
    {
      question: "Sort each into 'Higher standard of living' or 'Lower standard of living'.",
      input_type: "sort-buckets",
      buckets: [{ id: "higher", label: "Higher standard of living" }, { id: "lower", label: "Lower standard of living" }],
      items: [
        { id: "i1", text: "Reliable clean water and electricity", correct_bucket: "higher" },
        { id: "i2", text: "No access to healthcare", correct_bucket: "lower" },
        { id: "i3", text: "Good schools nearby", correct_bucket: "higher" },
        { id: "i4", text: "No proper housing", correct_bucket: "lower" },
      ],
      expected: "Clean water, electricity and schools point to a higher standard; no healthcare or housing points to lower.",
      pass_threshold: 0.75,
      memo: "Access to services, education and housing raises living standards; lack of them lowers it.", error_signals: ["ERR_EMS_G8E3A1_SORT"], difficulty: 2,
    },
    {
      question: "Put societies in order from least to most reliant on trade and technology.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A self-sufficient society making its own goods" },
        { id: "b", text: "A rural society with some trade" },
        { id: "c", text: "A growing town with shops and services" },
        { id: "d", text: "A modern society with advanced technology and trade" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "From self-sufficient, to rural with trade, to a town, to a modern high-tech society.",
      error_signals: ["ERR_EMS_G8E3A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Development, environment and unemployment
  "EMS.G8.E3.A2": [
    MC("How can development sometimes harm the environment?", ["Through pollution and using up natural resources", "By cleaning all air for free", "By creating no waste", "By never using resources"], "Through pollution and using up natural resources",
      "Development can cause pollution and deplete resources if not managed carefully.", "ERR_EMS_G8E3A2_HARM", 1),
    MC("What is unemployment?", ["When people who want to work cannot find jobs", "When everyone has a job", "When people refuse to spend", "When businesses make profit"], "When people who want to work cannot find jobs",
      "Unemployment is when willing workers cannot find jobs.", "ERR_EMS_G8E3A2_UNEMP", 1),
    MC("Why is high unemployment a problem for standard of living?", ["People without jobs earn little or no income", "It raises everyone's income", "It improves services", "It has no effect"], "People without jobs earn little or no income",
      "Without jobs, people lack income, lowering their standard of living.", "ERR_EMS_G8E3A2_WHY", 2),
    MC("Using resources productively means ____.", ["getting good value and not wasting them", "wasting as much as possible", "never using them", "polluting on purpose"], "getting good value and not wasting them",
      "Productive use gets value from resources without waste.", "ERR_EMS_G8E3A2_PRODUCTIVE", 2),
    MC("Which helps promote a healthy environment?", ["Reducing pollution and using resources wisely", "Dumping waste in rivers", "Wasting electricity", "Cutting all forests"], "Reducing pollution and using resources wisely",
      "Cutting pollution and using resources wisely protect the environment.", "ERR_EMS_G8E3A2_HEALTHY", 1),
    MC("Development that improves life but protects the environment is called ____.", ["sustainable development", "wasteful growth", "pollution", "unemployment"], "sustainable development",
      "Sustainable development improves lives while protecting the environment.", "ERR_EMS_G8E3A2_SUSTAIN", 2),
    MC("Creating more jobs usually helps standard of living because ____.", ["more people earn income", "fewer people earn income", "incomes fall", "services close"], "more people earn income",
      "More jobs mean more incomes, raising living standards.", "ERR_EMS_G8E3A2_JOBS", 2),
    MC("Which is an environmental cost of careless development?", ["Air and water pollution", "Cleaner rivers", "More forests", "Better air for free"], "Air and water pollution",
      "Careless development can pollute air and water.", "ERR_EMS_G8E3A2_COST", 2),
    MC("Balancing development with protecting the environment matters because ____.", ["future generations also need resources", "resources are unlimited", "the environment doesn't matter", "pollution is harmless"], "future generations also need resources",
      "We must protect resources and the environment for the future.", "ERR_EMS_G8E3A2_BALANCE", 3),
    MC("High unemployment combined with pollution would ____ a community's standard of living.", ["lower", "raise", "not affect", "double"], "lower",
      "Joblessness and pollution both reduce well-being and living standards.", "ERR_EMS_G8E3A2_COMBO", 2),
    TF("Development can harm the environment if it is not managed carefully.", "True",
      "Unmanaged development can pollute and deplete resources.", "ERR_EMS_G8E3A2_TF1", 1),
    TF("Unemployment means people who want jobs cannot find them.", "True",
      "Unemployment is willing workers without jobs.", "ERR_EMS_G8E3A2_TF2", 1),
    TF("Creating jobs can improve people's standard of living.", "True",
      "Jobs provide income, raising living standards.", "ERR_EMS_G8E3A2_TF3", 1),
    TF("Using resources productively means wasting as much as possible.", "False",
      "Productive use avoids waste and gets good value from resources.", "ERR_EMS_G8E3A2_TF4", 1),
    CLOZE("When willing workers cannot find jobs, there is ____.", ["unemployment", "employment", "profit", "growth"], "unemployment",
      "Unemployment is the lack of jobs for those who want them.", "ERR_EMS_G8E3A2_CL1", 1),
    CLOZE("Development that protects the environment for the future is ____ development.", ["sustainable", "wasteful", "harmful", "careless"], "sustainable",
      "Sustainable development balances progress with protection.", "ERR_EMS_G8E3A2_CL2", 2),
    CLOZE("Pollution and using up resources are ____ costs of development.", ["environmental", "income", "tax", "profit"], "environmental",
      "These are environmental costs.", "ERR_EMS_G8E3A2_CL3", 2),
    CLOZE("More jobs usually ____ a community's standard of living.", ["raise", "lower", "remove", "hide"], "raise",
      "Jobs bring income, raising living standards.", "ERR_EMS_G8E3A2_CL4", 1),
    {
      question: "Sort each into 'Helps standard of living / environment' or 'Harms it'.",
      input_type: "sort-buckets",
      buckets: [{ id: "helps", label: "Helps" }, { id: "harms", label: "Harms" }],
      items: [
        { id: "i1", text: "Creating sustainable jobs", correct_bucket: "helps" },
        { id: "i2", text: "Polluting rivers", correct_bucket: "harms" },
        { id: "i3", text: "Using resources wisely", correct_bucket: "helps" },
        { id: "i4", text: "High unemployment", correct_bucket: "harms" },
      ],
      expected: "Jobs and wise resource use help; pollution and unemployment harm.",
      pass_threshold: 0.75,
      memo: "Jobs and sustainability help; pollution and unemployment harm living standards.", error_signals: ["ERR_EMS_G8E3A2_SORT"], difficulty: 2,
    },
    {
      question: "Put this chain about development and the environment in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A community develops new industry" },
        { id: "b", text: "Jobs are created and incomes rise" },
        { id: "c", text: "Pollution risks the environment if unmanaged" },
        { id: "d", text: "Sustainable choices protect resources for the future" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Development brings jobs, but also pollution risk, so sustainable choices are needed.",
      error_signals: ["ERR_EMS_G8E3A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── E4 · Term 2 — Markets ─────────────────────────────────────────────────
  // A1 · The goods and services market
  "EMS.G8.E4.A1": [
    MC("What is a market in economics?", ["Where buyers and sellers trade goods or services", "Only a building with stalls", "A type of tax", "A government office"], "Where buyers and sellers trade goods or services",
      "A market is anywhere buyers and sellers come together to trade.", "ERR_EMS_G8E4A1_DEF", 1),
    MC("In the goods and services market, households usually ____.", ["buy goods and services", "sell factories", "print money", "collect tax"], "buy goods and services",
      "In the goods market, households are the buyers of goods and services.", "ERR_EMS_G8E4A1_HH", 1),
    MC("In the goods and services market, businesses usually ____.", ["sell goods and services", "buy households", "collect all tax", "print money"], "sell goods and services",
      "Businesses are the sellers in the goods and services market.", "ERR_EMS_G8E4A1_BUS", 1),
    MC("Buying bread at a shop takes place in the ____ market.", ["goods and services", "factor", "labour", "financial"], "goods and services",
      "Buying a finished product like bread is in the goods and services market.", "ERR_EMS_G8E4A1_BREAD", 2),
    MC("A market does NOT need to be ____.", ["a single physical building", "buyers", "sellers", "something to trade"], "a single physical building",
      "Markets can be online or anywhere — they just need buyers, sellers and something to trade.", "ERR_EMS_G8E4A1_NOTBUILDING", 2),
    MC("Online shopping is an example of a ____ market.", ["goods and services", "factor", "labour only", "financial only"], "goods and services",
      "Buying products online is still the goods and services market.", "ERR_EMS_G8E4A1_ONLINE", 2),
    MC("In the goods and services market, money flows from ____.", ["households to businesses", "businesses to nowhere", "government to nobody", "shops to factories only"], "households to businesses",
      "Households pay businesses for goods and services, so money flows that way.", "ERR_EMS_G8E4A1_MONEY", 2),
    MC("Which is traded in the goods and services market?", ["A haircut and a loaf of bread", "A worker's labour", "A bank loan", "A factory's land"], "A haircut and a loaf of bread",
      "Finished goods and services (bread, haircuts) are traded here.", "ERR_EMS_G8E4A1_TRADED", 2),
    MC("Why is the goods and services market important?", ["It is where people buy what they need and want", "It removes all trade", "It stops businesses selling", "It only handles labour"], "It is where people buy what they need and want",
      "It is where consumers get the goods and services they need and want.", "ERR_EMS_G8E4A1_IMPORTANT", 2),
    MC("A spaza shop selling cooldrinks to customers operates in the ____ market.", ["goods and services", "factor", "labour", "financial"], "goods and services",
      "Selling cooldrinks (a good) is the goods and services market.", "ERR_EMS_G8E4A1_SPAZA", 1),
    TF("A market is where buyers and sellers trade.", "True",
      "Markets bring buyers and sellers together to trade.", "ERR_EMS_G8E4A1_TF1", 1),
    TF("In the goods and services market, households buy and businesses sell.", "True",
      "Households are buyers; businesses are sellers of goods and services.", "ERR_EMS_G8E4A1_TF2", 1),
    TF("A market must always be a physical building.", "False",
      "Markets can be online or anywhere buyers and sellers meet.", "ERR_EMS_G8E4A1_TF3", 1),
    TF("Buying a finished good like bread happens in the goods and services market.", "True",
      "Finished goods are traded in the goods and services market.", "ERR_EMS_G8E4A1_TF4", 1),
    CLOZE("A place where buyers and sellers trade is a ____.", ["market", "tax", "budget", "loan"], "market",
      "A market is where trade happens.", "ERR_EMS_G8E4A1_CL1", 1),
    CLOZE("In the goods and services market, households are the ____.", ["buyers", "sellers", "factories", "banks"], "buyers",
      "Households buy goods and services.", "ERR_EMS_G8E4A1_CL2", 1),
    CLOZE("In the goods and services market, businesses are the ____.", ["sellers", "buyers", "households", "banks"], "sellers",
      "Businesses sell goods and services.", "ERR_EMS_G8E4A1_CL3", 1),
    CLOZE("Buying a haircut happens in the ____ and services market.", ["goods", "factor", "labour", "financial"], "goods",
      "Services like haircuts are traded in the goods and services market.", "ERR_EMS_G8E4A1_CL4", 2),
    {
      question: "Sort each into 'Goods and services market' or 'Not the goods and services market'.",
      input_type: "sort-buckets",
      buckets: [{ id: "gsm", label: "Goods & services market" }, { id: "not", label: "Not this market" }],
      items: [
        { id: "i1", text: "Buying groceries", correct_bucket: "gsm" },
        { id: "i2", text: "A business hiring a worker", correct_bucket: "not" },
        { id: "i3", text: "Paying for a bus ride", correct_bucket: "gsm" },
        { id: "i4", text: "Taking out a bank loan", correct_bucket: "not" },
      ],
      expected: "Groceries and a bus ride are goods/services; hiring labour or a loan are factor/financial markets.",
      pass_threshold: 0.75,
      memo: "The goods and services market trades finished products and services, not labour or finance.", error_signals: ["ERR_EMS_G8E4A1_SORT"], difficulty: 2,
    },
    {
      question: "Put a goods-and-services market transaction in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A business offers a good for sale" },
        { id: "b", text: "A household decides to buy it" },
        { id: "c", text: "The household pays the business" },
        { id: "d", text: "The household receives the good" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Business offers, household chooses, pays, and receives the good.",
      error_signals: ["ERR_EMS_G8E4A1_SEQ"], difficulty: 1,
    },
  ],

  // A2 · The factor market
  "EMS.G8.E4.A2": [
    MC("What is traded in the factor market?", ["Factors of production, like labour and finance", "Only finished bread", "Only haircuts", "Only sweets"], "Factors of production, like labour and finance",
      "The factor market trades factors of production, such as labour and capital/finance.", "ERR_EMS_G8E4A2_DEF", 1),
    MC("In the labour market, households mainly ____.", ["sell their labour to businesses", "buy finished goods", "print money", "collect tax"], "sell their labour to businesses",
      "Households supply (sell) labour; businesses buy it.", "ERR_EMS_G8E4A2_LABOUR", 1),
    MC("What do workers receive for selling their labour?", ["Wages or salaries", "Free goods", "Taxes", "Shares only"], "Wages or salaries",
      "Workers earn wages or salaries for their labour.", "ERR_EMS_G8E4A2_WAGE", 1),
    MC("The financial market is where ____ is borrowed and lent.", ["money (finance)", "bread", "haircuts", "vegetables"], "money (finance)",
      "The financial market deals in money — borrowing, lending and investing.", "ERR_EMS_G8E4A2_FINANCE", 2),
    MC("A business hiring a new worker is taking part in the ____ market.", ["labour (factor)", "goods and services", "financial only", "vegetable"], "labour (factor)",
      "Hiring labour happens in the labour part of the factor market.", "ERR_EMS_G8E4A2_HIRE", 2),
    MC("A business borrowing money from a bank uses the ____ market.", ["financial", "goods and services", "labour", "vegetable"], "financial",
      "Borrowing money happens in the financial market.", "ERR_EMS_G8E4A2_BORROW", 2),
    MC("In the factor market, the flow of labour goes from ____.", ["households to businesses", "businesses to nobody", "shops to factories only", "banks to nowhere"], "households to businesses",
      "Households supply labour to businesses in the factor market.", "ERR_EMS_G8E4A2_FLOW", 2),
    MC("Which is part of the factor market?", ["The labour market and the financial market", "The bread market only", "The sweet market", "The toy market"], "The labour market and the financial market",
      "The factor market includes the labour and financial markets.", "ERR_EMS_G8E4A2_PARTS", 2),
    MC("How is the factor market different from the goods and services market?", ["It trades factors of production, not finished goods", "It only sells bread", "It is exactly the same", "It trades only haircuts"], "It trades factors of production, not finished goods",
      "The factor market trades inputs (labour, finance); the goods market trades finished products.", "ERR_EMS_G8E4A2_DIFF", 3),
    MC("Interest paid on a loan is a price in the ____ market.", ["financial", "labour", "goods", "vegetable"], "financial",
      "Interest is the cost of borrowing money in the financial market.", "ERR_EMS_G8E4A2_INTEREST", 2),
    TF("The factor market trades factors of production like labour and finance.", "True",
      "It deals in inputs such as labour and capital/finance.", "ERR_EMS_G8E4A2_TF1", 1),
    TF("In the labour market, households sell their labour to businesses.", "True",
      "Households supply labour; businesses buy it.", "ERR_EMS_G8E4A2_TF2", 1),
    TF("The financial market is where money is borrowed and lent.", "True",
      "It deals in finance — borrowing, lending and investing.", "ERR_EMS_G8E4A2_TF3", 1),
    TF("Buying a loaf of bread happens in the factor market.", "False",
      "Bread is a finished good, traded in the goods and services market, not the factor market.", "ERR_EMS_G8E4A2_TF4", 1),
    CLOZE("The market for factors of production like labour and finance is the ____ market.", ["factor", "goods", "sweet", "toy"], "factor",
      "The factor market trades factors of production.", "ERR_EMS_G8E4A2_CL1", 1),
    CLOZE("Households sell their ____ in the labour market.", ["labour", "bread", "money", "land only"], "labour",
      "Households supply labour in the labour market.", "ERR_EMS_G8E4A2_CL2", 1),
    CLOZE("Money is borrowed and lent in the ____ market.", ["financial", "goods", "labour", "vegetable"], "financial",
      "The financial market deals in money.", "ERR_EMS_G8E4A2_CL3", 2),
    CLOZE("Workers earn ____ for selling their labour.", ["wages", "tax", "shares", "rent"], "wages",
      "Labour earns wages or salaries.", "ERR_EMS_G8E4A2_CL4", 1),
    {
      question: "Sort each into 'Labour market' or 'Financial market'.",
      input_type: "sort-buckets",
      buckets: [{ id: "labour", label: "Labour market" }, { id: "financial", label: "Financial market" }],
      items: [
        { id: "i1", text: "A company hires a cashier", correct_bucket: "labour" },
        { id: "i2", text: "A business takes a bank loan", correct_bucket: "financial" },
        { id: "i3", text: "A worker is paid a salary", correct_bucket: "labour" },
        { id: "i4", text: "A person invests savings for interest", correct_bucket: "financial" },
      ],
      expected: "Hiring and paying workers is the labour market; loans and investing are the financial market.",
      pass_threshold: 0.75,
      memo: "Labour market trades work for wages; financial market trades money for interest.", error_signals: ["ERR_EMS_G8E4A2_SORT"], difficulty: 2,
    },
    {
      question: "Sort each transaction into 'Goods & services market' or 'Factor market'.",
      input_type: "sort-buckets",
      buckets: [{ id: "gsm", label: "Goods & services market" }, { id: "factor", label: "Factor market" }],
      items: [
        { id: "i1", text: "Buying a phone", correct_bucket: "gsm" },
        { id: "i2", text: "A business hiring staff", correct_bucket: "factor" },
        { id: "i3", text: "Paying for a meal", correct_bucket: "gsm" },
        { id: "i4", text: "Borrowing money to start a business", correct_bucket: "factor" },
      ],
      expected: "Buying a phone or meal is the goods market; hiring staff or borrowing money is the factor market.",
      pass_threshold: 0.75,
      memo: "Finished products = goods/services market; labour and finance = factor market.", error_signals: ["ERR_EMS_G8E4A2_SORT2"], difficulty: 3,
    },
  ],
};

export default G8;
