// ─── EMS SP — Grade 8 authored pools (B): Financial Literacy (concepts) ───────
// Strand: Financial Literacy (CAPS G8) — CONCEPT-level pools only. The procedural
// "recording" skills (entering/closing journals, posting to the ledger, preparing
// a trial balance) are flagged deferred_recording in the tree and are authored in
// a later pass, so they are intentionally absent here.
// Tap-only. Recipe: 10 MC · 4 TF · 4 CLOZE · 1 sequence · 1 sort-buckets = 20.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8B = {
  // ─── F1 · Term 1 — Accounting concepts ─────────────────────────────────────
  // A1 · Sole trader, debit and credit
  "EMS.G8.F1.A1": [
    MC("What is a sole trader?", ["A business owned and run by one person", "A business owned by shareholders", "A government department", "A bank"], "A business owned and run by one person",
      "A sole trader is a one-owner business — the simplest form for keeping accounts.", "ERR_EMS_G8F1A1_SOLE", 1),
    MC("In accounting, every transaction has two sides called ____.", ["debit and credit", "profit and loss", "income and rent", "buy and hold"], "debit and credit",
      "Each transaction is recorded with a debit side and a credit side.", "ERR_EMS_G8F1A1_DRCR", 1),
    MC("On which side of an account is the debit traditionally placed?", ["The left side", "The right side", "The top only", "The bottom only"], "The left side",
      "By convention, debit entries go on the left of an account.", "ERR_EMS_G8F1A1_LEFT", 2),
    MC("On which side is the credit traditionally placed?", ["The right side", "The left side", "The middle", "Nowhere"], "The right side",
      "Credit entries go on the right of an account.", "ERR_EMS_G8F1A1_RIGHT", 2),
    MC("Why does a sole trader keep accounting records?", ["To track the business's money and know its profit", "To hide money", "To avoid all planning", "To confuse customers"], "To track the business's money and know its profit",
      "Records let the owner track money and work out profit or loss.", "ERR_EMS_G8F1A1_WHY", 1),
    MC("For every debit entry, there must be an equal ____.", ["credit entry", "debit entry", "tax entry", "profit entry"], "credit entry",
      "Double-entry means each debit has an equal and opposite credit.", "ERR_EMS_G8F1A1_EQUAL", 2),
    MC("Who is responsible for a sole trader's debts?", ["The owner personally", "Shareholders", "The government", "Customers"], "The owner personally",
      "A sole trader's owner is personally responsible for the business's debts.", "ERR_EMS_G8F1A1_DEBT", 2),
    MC("The words 'debit' and 'credit' are used to ____.", ["record the two sides of each transaction", "set prices", "advertise products", "pay tax only"], "record the two sides of each transaction",
      "Debit and credit record the two sides of every transaction.", "ERR_EMS_G8F1A1_USE", 2),
    MC("Which statement is correct about a sole trader?", ["It has one owner who keeps the profit and carries the risk", "It has thousands of owners", "It pays no attention to records", "It is a public company"], "It has one owner who keeps the profit and carries the risk",
      "A sole trader's single owner keeps profit and carries the risk.", "ERR_EMS_G8F1A1_CORRECT", 2),
    MC("In double-entry bookkeeping, total debits should always ____ total credits.", ["equal", "be less than", "be more than", "be unrelated to"], "equal",
      "Total debits must equal total credits — that is the balance check.", "ERR_EMS_G8F1A1_BALANCE", 3),
    TF("A sole trader is a business owned by one person.", "True",
      "Sole traders have a single owner.", "ERR_EMS_G8F1A1_TF1", 1),
    TF("Every transaction has a debit side and a credit side.", "True",
      "Double-entry records each transaction with a debit and a credit.", "ERR_EMS_G8F1A1_TF2", 1),
    TF("Debit means the right side of an account.", "False",
      "Debit is the left side; credit is the right side.", "ERR_EMS_G8F1A1_TF3", 1),
    TF("Total debits should equal total credits.", "True",
      "Debits and credits must balance in double-entry bookkeeping.", "ERR_EMS_G8F1A1_TF4", 2),
    CLOZE("A business owned by one person is a ____ trader.", ["sole", "joint", "public", "group"], "sole",
      "A sole trader has one owner.", "ERR_EMS_G8F1A1_CL1", 1),
    CLOZE("The two sides of every transaction are debit and ____.", ["credit", "profit", "rent", "tax"], "credit",
      "Debit and credit are the two sides.", "ERR_EMS_G8F1A1_CL2", 1),
    CLOZE("Debit is recorded on the ____ side of an account.", ["left", "right", "top", "bottom"], "left",
      "Debit = left, credit = right.", "ERR_EMS_G8F1A1_CL3", 2),
    CLOZE("Credit is recorded on the ____ side of an account.", ["right", "left", "middle", "outside"], "right",
      "Credit entries go on the right.", "ERR_EMS_G8F1A1_CL4", 2),
    {
      question: "Sort each into 'Debit side' or 'Credit side' of an account.",
      input_type: "sort-buckets",
      buckets: [{ id: "debit", label: "Debit (left)" }, { id: "credit", label: "Credit (right)" }],
      items: [
        { id: "i1", text: "Left side of the account", correct_bucket: "debit" },
        { id: "i2", text: "Right side of the account", correct_bucket: "credit" },
        { id: "i3", text: "Where debits are written", correct_bucket: "debit" },
        { id: "i4", text: "Where credits are written", correct_bucket: "credit" },
      ],
      expected: "Debit is the left side; credit is the right side.",
      pass_threshold: 0.75,
      memo: "Debit = left side; credit = right side of an account.", error_signals: ["ERR_EMS_G8F1A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the idea of recording a transaction in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A transaction takes place" },
        { id: "b", text: "It is recorded with a debit on one account" },
        { id: "c", text: "And an equal credit on another account" },
        { id: "d", text: "Total debits equal total credits" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "A transaction is recorded as an equal debit and credit, keeping the books balanced.",
      error_signals: ["ERR_EMS_G8F1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · The accounting equation
  "EMS.G8.F1.A2": [
    MC("What is the accounting equation?", ["Assets = Owner's equity + Liabilities", "Income = Rent + Tax", "Profit = Sales × 2", "Debit = Credit × 3"], "Assets = Owner's equity + Liabilities",
      "The accounting equation is A = OE + L.", "ERR_EMS_G8F1A2_EQ", 1),
    MC("In A = OE + L, what does 'A' stand for?", ["Assets", "Advertising", "Accounts", "Amounts"], "Assets",
      "A stands for Assets — what the business owns.", "ERR_EMS_G8F1A2_A", 1),
    MC("In A = OE + L, what does 'OE' stand for?", ["Owner's equity", "Other expenses", "Open economy", "Output earned"], "Owner's equity",
      "OE is Owner's equity — the owner's stake in the business.", "ERR_EMS_G8F1A2_OE", 1),
    MC("In A = OE + L, what does 'L' stand for?", ["Liabilities", "Labour", "Losses", "Land"], "Liabilities",
      "L stands for Liabilities — what the business owes.", "ERR_EMS_G8F1A2_L", 1),
    MC("The accounting equation must always ____.", ["balance", "increase", "decrease", "disappear"], "balance",
      "Both sides of the equation must always be equal (balance).", "ERR_EMS_G8F1A2_BALANCE", 2),
    MC("If assets are R10 000 and liabilities are R4 000, owner's equity is ____.", ["R6 000", "R14 000", "R4 000", "R10 000"], "R6 000",
      "OE = A − L = R10 000 − R4 000 = R6 000.", "ERR_EMS_G8F1A2_CALC", 2),
    MC("Owner's equity is best described as ____.", ["the owner's share of the business", "money owed to a bank", "the total of all expenses", "the rent paid"], "the owner's share of the business",
      "Owner's equity is the owner's claim on the business's assets.", "ERR_EMS_G8F1A2_OE_DEF", 2),
    MC("If a business has assets of R8 000 and owner's equity of R5 000, liabilities are ____.", ["R3 000", "R13 000", "R5 000", "R8 000"], "R3 000",
      "L = A − OE = R8 000 − R5 000 = R3 000.", "ERR_EMS_G8F1A2_CALC2", 3),
    MC("Why is the accounting equation useful?", ["It shows the business always balances what it owns against equity and debt", "It hides the figures", "It removes all records", "It sets prices"], "It shows the business always balances what it owns against equity and debt",
      "It shows assets are always financed by owner's equity plus liabilities.", "ERR_EMS_G8F1A2_WHY", 2),
    MC("Which is another correct form of the equation?", ["Owner's equity = Assets − Liabilities", "Assets = Liabilities − Owner's equity", "Liabilities = Assets + Owner's equity", "Assets = Income"], "Owner's equity = Assets − Liabilities",
      "Rearranging A = OE + L gives OE = A − L.", "ERR_EMS_G8F1A2_REARRANGE", 3),
    TF("The accounting equation is Assets = Owner's equity + Liabilities.", "True",
      "A = OE + L is the accounting equation.", "ERR_EMS_G8F1A2_TF1", 1),
    TF("Assets are what the business owns.", "True",
      "Assets are the resources the business owns.", "ERR_EMS_G8F1A2_TF2", 1),
    TF("Liabilities are what the business owns.", "False",
      "Liabilities are what the business owes; assets are what it owns.", "ERR_EMS_G8F1A2_TF3", 1),
    TF("The two sides of the accounting equation must always be equal.", "True",
      "The equation always balances.", "ERR_EMS_G8F1A2_TF4", 1),
    CLOZE("The accounting equation is Assets = Owner's equity + ____.", ["Liabilities", "Income", "Rent", "Tax"], "Liabilities",
      "A = OE + L.", "ERR_EMS_G8F1A2_CL1", 1),
    CLOZE("Assets are what the business ____.", ["owns", "owes", "earns", "rents"], "owns",
      "Assets are owned resources.", "ERR_EMS_G8F1A2_CL2", 1),
    CLOZE("Liabilities are what the business ____.", ["owes", "owns", "earns", "saves"], "owes",
      "Liabilities are debts owed.", "ERR_EMS_G8F1A2_CL3", 1),
    CLOZE("Owner's equity = Assets ____ Liabilities.", ["minus", "plus", "times", "divided by"], "minus",
      "OE = A − L.", "ERR_EMS_G8F1A2_CL4", 2),
    {
      question: "Sort each item into 'Asset', 'Liability' or 'Owner's equity'.",
      input_type: "sort-buckets",
      buckets: [{ id: "asset", label: "Asset" }, { id: "liability", label: "Liability" }, { id: "equity", label: "Owner's equity" }],
      items: [
        { id: "i1", text: "Cash in the bank", correct_bucket: "asset" },
        { id: "i2", text: "A loan to repay", correct_bucket: "liability" },
        { id: "i3", text: "Capital invested by the owner", correct_bucket: "equity" },
        { id: "i4", text: "Equipment the business owns", correct_bucket: "asset" },
      ],
      expected: "Cash and equipment are assets; a loan is a liability; the owner's capital is owner's equity.",
      pass_threshold: 0.75,
      memo: "Owned = asset; owed = liability; owner's stake = owner's equity.", error_signals: ["ERR_EMS_G8F1A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of using the accounting equation in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Add up the assets" },
        { id: "b", text: "Add up the liabilities" },
        { id: "c", text: "Subtract liabilities from assets" },
        { id: "d", text: "The answer is owner's equity" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Assets − Liabilities = Owner's equity.",
      error_signals: ["ERR_EMS_G8F1A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Effect of transactions on the equation
  "EMS.G8.F1.A3": [
    MC("If the owner deposits more capital as cash, what happens?", ["Assets increase and owner's equity increases", "Assets fall and liabilities rise", "Nothing changes", "Liabilities increase only"], "Assets increase and owner's equity increases",
      "More cash (asset) and a bigger owner's stake (equity) both rise — the equation stays balanced.", "ERR_EMS_G8F1A3_CAPITAL", 2),
    MC("Every transaction affects ____ of the accounting equation.", ["at least two parts", "only one part", "no parts", "exactly five parts"], "at least two parts",
      "Each transaction touches at least two parts, keeping A = OE + L balanced.", "ERR_EMS_G8F1A3_TWO", 1),
    MC("If the business buys equipment for cash, what happens to assets?", ["One asset (equipment) rises while another (cash) falls", "Assets disappear", "Liabilities rise", "Owner's equity falls"], "One asset (equipment) rises while another (cash) falls",
      "Cash falls and equipment rises — total assets stay the same.", "ERR_EMS_G8F1A3_SWAP", 2),
    MC("If the business takes a bank loan in cash, what happens?", ["Assets (cash) increase and liabilities increase", "Assets fall", "Owner's equity falls", "Nothing changes"], "Assets (cash) increase and liabilities increase",
      "Cash rises (asset up) and the loan is a new liability — both sides rise equally.", "ERR_EMS_G8F1A3_LOAN", 2),
    MC("After any transaction, the accounting equation must still ____.", ["balance", "grow only", "shrink only", "break"], "balance",
      "The equation must remain balanced after every transaction.", "ERR_EMS_G8F1A3_BALANCE", 1),
    MC("If the business pays off part of a loan with cash, what happens?", ["Assets (cash) fall and liabilities fall", "Assets rise", "Owner's equity rises", "Nothing changes"], "Assets (cash) fall and liabilities fall",
      "Cash falls (asset down) and the loan owed falls (liability down) — still balanced.", "ERR_EMS_G8F1A3_REPAY", 2),
    MC("Earning income (a profit) generally increases ____.", ["owner's equity", "liabilities only", "nothing", "loans"], "owner's equity",
      "Profit increases owner's equity (the owner's stake in the business).", "ERR_EMS_G8F1A3_PROFIT", 3),
    MC("Paying an expense in cash generally ____.", ["reduces assets and reduces owner's equity", "increases assets", "increases owner's equity", "increases liabilities"], "reduces assets and reduces owner's equity",
      "An expense reduces cash (asset) and reduces owner's equity (profit/stake).", "ERR_EMS_G8F1A3_EXPENSE", 3),
    MC("Why must a transaction touch at least two parts of the equation?", ["So the equation stays balanced", "To break the books", "To hide money", "There is no reason"], "So the equation stays balanced",
      "Touching two parts keeps both sides equal, so the equation stays balanced.", "ERR_EMS_G8F1A3_WHY", 2),
    MC("If assets increase by R500 and liabilities do not change, owner's equity must ____.", ["increase by R500", "fall by R500", "stay the same", "double"], "increase by R500",
      "To keep A = OE + L balanced, if assets rise R500 and liabilities are unchanged, owner's equity rises R500.", "ERR_EMS_G8F1A3_CALC", 3),
    TF("Every transaction affects at least two parts of the accounting equation.", "True",
      "Each transaction touches two or more parts, keeping it balanced.", "ERR_EMS_G8F1A3_TF1", 1),
    TF("Buying equipment for cash changes the make-up of assets but not their total.", "True",
      "Cash down, equipment up — total assets stay the same.", "ERR_EMS_G8F1A3_TF2", 2),
    TF("Taking a loan in cash increases both assets and liabilities.", "True",
      "Cash rises (asset) and the loan is a new liability.", "ERR_EMS_G8F1A3_TF3", 2),
    TF("After a transaction, the accounting equation can be left unbalanced.", "False",
      "The equation must always remain balanced after every transaction.", "ERR_EMS_G8F1A3_TF4", 1),
    CLOZE("Each transaction must keep the accounting equation in ____.", ["balance", "profit", "loss", "debt"], "balance",
      "The equation stays balanced after every transaction.", "ERR_EMS_G8F1A3_CL1", 1),
    CLOZE("Buying equipment for cash makes equipment rise and cash ____.", ["fall", "rise", "stay", "double"], "fall",
      "Cash falls while equipment rises; total assets unchanged.", "ERR_EMS_G8F1A3_CL2", 2),
    CLOZE("Taking a loan in cash increases assets and ____.", ["liabilities", "owner's equity", "income", "rent"], "liabilities",
      "The loan is a new liability while cash (asset) rises.", "ERR_EMS_G8F1A3_CL3", 2),
    CLOZE("Earning a profit increases the owner's ____.", ["equity", "debt", "rent", "tax"], "equity",
      "Profit increases owner's equity.", "ERR_EMS_G8F1A3_CL4", 3),
    {
      question: "Sort each transaction by its effect on total assets.",
      input_type: "sort-buckets",
      buckets: [{ id: "up", label: "Total assets increase" }, { id: "down", label: "Total assets decrease" }, { id: "same", label: "Total assets unchanged" }],
      items: [
        { id: "i1", text: "Owner deposits extra capital in cash", correct_bucket: "up" },
        { id: "i2", text: "Pay an expense in cash", correct_bucket: "down" },
        { id: "i3", text: "Buy equipment for cash", correct_bucket: "same" },
        { id: "i4", text: "Take a cash loan from the bank", correct_bucket: "up" },
      ],
      expected: "Extra capital and a loan raise assets; paying an expense lowers them; buying equipment for cash leaves the total unchanged.",
      pass_threshold: 0.75,
      memo: "Watch total assets: capital/loan in = up; expense out = down; asset-for-asset swap = unchanged.", error_signals: ["ERR_EMS_G8F1A3_SORT"], difficulty: 3,
    },
    {
      question: "Put the reasoning for keeping the equation balanced in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A transaction happens" },
        { id: "b", text: "Identify which parts it affects" },
        { id: "c", text: "Record equal changes so both sides match" },
        { id: "d", text: "The equation stays balanced" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Identify the affected parts, record equal changes, and the equation stays balanced.",
      error_signals: ["ERR_EMS_G8F1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── F2 · Term 1 — Source documents ────────────────────────────────────────
  // A1 · Receipts and deposit slips
  "EMS.G8.F2.A1": [
    MC("What is a source document?", ["The written proof that a transaction took place", "A type of advert", "A business plan", "A tax law"], "The written proof that a transaction took place",
      "Source documents are the paper (or digital) proof that a transaction happened.", "ERR_EMS_G8F2A1_DEF", 1),
    MC("What is a receipt?", ["Proof that money was received", "Proof that goods were made", "A loan agreement", "A tax return"], "Proof that money was received",
      "A receipt is issued as proof that money was received.", "ERR_EMS_G8F2A1_RECEIPT", 1),
    MC("What is a deposit slip used for?", ["Proof that money was paid into a bank account", "Proof of advertising", "A staff timesheet", "A delivery note"], "Proof that money was paid into a bank account",
      "A deposit slip is proof of money deposited into a bank account.", "ERR_EMS_G8F2A1_DEPOSIT", 1),
    MC("A till slip (cash register slip) is given to ____.", ["a customer as proof of a cash sale", "the government as tax", "the bank as a loan", "a supplier as an order"], "a customer as proof of a cash sale",
      "A till slip proves a cash sale to the customer.", "ERR_EMS_G8F2A1_TILL", 2),
    MC("Why are source documents important?", ["They provide evidence to record transactions accurately", "They hide transactions", "They replace money", "They set prices"], "They provide evidence to record transactions accurately",
      "Source documents give the evidence used to record transactions correctly.", "ERR_EMS_G8F2A1_WHY", 1),
    MC("When a business receives cash from a customer, it issues a ____.", ["receipt", "deposit slip", "cheque", "invoice"], "receipt",
      "A receipt proves money was received from the customer.", "ERR_EMS_G8F2A1_ISSUE", 2),
    MC("A deposit slip would be completed when ____.", ["paying cash into the bank", "buying stock on credit", "advertising", "hiring staff"], "paying cash into the bank",
      "Deposit slips are used when banking (depositing) money.", "ERR_EMS_G8F2A1_WHEN", 2),
    MC("Which document proves money came IN to the business?", ["A receipt", "A purchase order", "A job advert", "A staff roster"], "A receipt",
      "A receipt proves money received (in).", "ERR_EMS_G8F2A1_IN", 2),
    MC("Keeping source documents helps a business to ____.", ["keep accurate records and check its accounts", "lose information", "avoid recording", "confuse the bank"], "keep accurate records and check its accounts",
      "Documents support accurate records and checking of accounts.", "ERR_EMS_G8F2A1_KEEP", 2),
    MC("Which best describes the link between a receipt and the records?", ["The receipt is the evidence used to record the money received", "The receipt replaces all records", "The receipt is an advert", "The receipt sets the price"], "The receipt is the evidence used to record the money received",
      "The receipt is the source document evidencing the recorded transaction.", "ERR_EMS_G8F2A1_LINK", 3),
    TF("A source document is the proof that a transaction took place.", "True",
      "Source documents evidence transactions.", "ERR_EMS_G8F2A1_TF1", 1),
    TF("A receipt is proof that money was received.", "True",
      "Receipts prove money received.", "ERR_EMS_G8F2A1_TF2", 1),
    TF("A deposit slip is used to advertise products.", "False",
      "A deposit slip proves money paid into a bank account, not advertising.", "ERR_EMS_G8F2A1_TF3", 1),
    TF("Source documents help a business keep accurate records.", "True",
      "They provide the evidence for accurate records.", "ERR_EMS_G8F2A1_TF4", 1),
    CLOZE("The written proof that a transaction happened is a ____ document.", ["source", "secret", "tax", "advert"], "source",
      "Source documents prove transactions.", "ERR_EMS_G8F2A1_CL1", 1),
    CLOZE("Proof that money was received is a ____.", ["receipt", "deposit slip", "invoice", "cheque"], "receipt",
      "A receipt proves money received.", "ERR_EMS_G8F2A1_CL2", 1),
    CLOZE("Proof that money was paid into the bank is a ____ slip.", ["deposit", "till", "wage", "order"], "deposit",
      "A deposit slip proves a bank deposit.", "ERR_EMS_G8F2A1_CL3", 1),
    CLOZE("A cash register slip given to a customer is a ____ slip.", ["till", "deposit", "loan", "pay"], "till",
      "A till slip proves a cash sale.", "ERR_EMS_G8F2A1_CL4", 2),
    {
      question: "Sort each document by what it proves.",
      input_type: "sort-buckets",
      buckets: [{ id: "received", label: "Money received" }, { id: "banked", label: "Money banked" }],
      items: [
        { id: "i1", text: "A receipt", correct_bucket: "received" },
        { id: "i2", text: "A deposit slip", correct_bucket: "banked" },
        { id: "i3", text: "A till slip for a cash sale", correct_bucket: "received" },
        { id: "i4", text: "A bank deposit record", correct_bucket: "banked" },
      ],
      expected: "Receipts and till slips prove money received; deposit slips prove money banked.",
      pass_threshold: 0.75,
      memo: "Receipts/till slips = received; deposit slips = banked.", error_signals: ["ERR_EMS_G8F2A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of a cash sale and banking in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Customer pays cash" },
        { id: "b", text: "A receipt or till slip is issued" },
        { id: "c", text: "The cash is taken to the bank" },
        { id: "d", text: "A deposit slip records the banking" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Cash received → receipt/till slip → banked → deposit slip.",
      error_signals: ["ERR_EMS_G8F2A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Cheques and counterfoils
  "EMS.G8.F2.A2": [
    MC("What is a cheque?", ["A written instruction to a bank to pay money from an account", "A receipt for cash", "A type of advert", "A bank statement"], "A written instruction to a bank to pay money from an account",
      "A cheque instructs the bank to pay a stated amount from the writer's account.", "ERR_EMS_G8F2A2_DEF", 1),
    MC("What is a cheque counterfoil?", ["The stub kept as a record of the cheque written", "The advert for a cheque", "A receipt for cash", "A bank's profit"], "The stub kept as a record of the cheque written",
      "The counterfoil is the stub kept as a record of the cheque.", "ERR_EMS_G8F2A2_COUNTERFOIL", 1),
    MC("Why keep a cheque counterfoil?", ["As a record of the payment made", "To advertise", "To hide payments", "To set prices"], "As a record of the payment made",
      "The counterfoil records what was paid, to whom and when.", "ERR_EMS_G8F2A2_WHY", 1),
    MC("A cheque is used to make a ____.", ["payment", "sale", "deposit only", "loan only"], "payment",
      "A cheque is a way of paying money out.", "ERR_EMS_G8F2A2_PAYMENT", 1),
    MC("Which document proves money went OUT by cheque?", ["The cheque counterfoil", "A receipt for cash received", "A job advert", "A staff roster"], "The cheque counterfoil",
      "The counterfoil records the cheque payment (money out).", "ERR_EMS_G8F2A2_OUT", 2),
    MC("The person who writes and signs a cheque is the ____.", ["account holder making the payment", "bank manager only", "customer receiving cash", "government"], "account holder making the payment",
      "The account holder writes and signs the cheque to pay.", "ERR_EMS_G8F2A2_WRITER", 2),
    MC("A cheque tells the bank to pay money from ____.", ["the writer's account", "the receiver's wages", "the government", "a shop's till"], "the writer's account",
      "The cheque draws money from the writer's bank account.", "ERR_EMS_G8F2A2_FROM", 2),
    MC("Which pair correctly matches the documents?", ["Cheque = payment instruction; counterfoil = the record kept", "Cheque = record kept; counterfoil = advert", "Both are receipts for cash", "Both are deposit slips"], "Cheque = payment instruction; counterfoil = the record kept",
      "The cheque instructs payment; the counterfoil is the record kept.", "ERR_EMS_G8F2A2_PAIR", 3),
    MC("Cheques are a source document for ____ transactions.", ["payment (money out)", "money received only", "advertising", "hiring"], "payment (money out)",
      "Cheques document payments — money going out.", "ERR_EMS_G8F2A2_SOURCE", 2),
    MC("If a business pays a supplier by cheque, it keeps the ____ as proof.", ["counterfoil", "advert", "till slip", "deposit slip"], "counterfoil",
      "The counterfoil is the proof/record of the cheque payment.", "ERR_EMS_G8F2A2_KEEP", 2),
    TF("A cheque is a written instruction to a bank to pay money.", "True",
      "A cheque tells the bank to pay an amount from the account.", "ERR_EMS_G8F2A2_TF1", 1),
    TF("A counterfoil is the stub kept as a record of a cheque.", "True",
      "The counterfoil records the cheque written.", "ERR_EMS_G8F2A2_TF2", 1),
    TF("A cheque is used to receive money into the business.", "False",
      "A cheque is used to pay money out, not to receive it.", "ERR_EMS_G8F2A2_TF3", 1),
    TF("The counterfoil helps the business keep a record of its payments.", "True",
      "It records each cheque payment made.", "ERR_EMS_G8F2A2_TF4", 1),
    CLOZE("A written instruction to a bank to pay money is a ____.", ["cheque", "receipt", "deposit slip", "invoice"], "cheque",
      "A cheque instructs the bank to pay.", "ERR_EMS_G8F2A2_CL1", 1),
    CLOZE("The stub kept as a record of a cheque is the ____.", ["counterfoil", "receipt", "till slip", "deposit slip"], "counterfoil",
      "The counterfoil records the cheque.", "ERR_EMS_G8F2A2_CL2", 1),
    CLOZE("A cheque is used to make a ____.", ["payment", "deposit", "sale", "profit"], "payment",
      "A cheque pays money out.", "ERR_EMS_G8F2A2_CL3", 1),
    CLOZE("A cheque draws money from the ____ account.", ["writer's", "bank's own", "government's", "customer's wage"], "writer's",
      "The cheque pays from the writer's account.", "ERR_EMS_G8F2A2_CL4", 2),
    {
      question: "Sort each document by money direction.",
      input_type: "sort-buckets",
      buckets: [{ id: "in", label: "Money IN (received)" }, { id: "out", label: "Money OUT (paid)" }],
      items: [
        { id: "i1", text: "A receipt", correct_bucket: "in" },
        { id: "i2", text: "A cheque counterfoil", correct_bucket: "out" },
        { id: "i3", text: "A till slip for a sale", correct_bucket: "in" },
        { id: "i4", text: "A cheque written to a supplier", correct_bucket: "out" },
      ],
      expected: "Receipts and till slips are money in; cheques and counterfoils are money out.",
      pass_threshold: 0.75,
      memo: "Receipts/till slips = money in; cheques/counterfoils = money out.", error_signals: ["ERR_EMS_G8F2A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of paying a supplier by cheque in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Decide to pay the supplier" },
        { id: "b", text: "Write and sign the cheque" },
        { id: "c", text: "Fill in the counterfoil as a record" },
        { id: "d", text: "Give the cheque to the supplier" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Write the cheque, record it on the counterfoil, then hand the cheque over.",
      error_signals: ["ERR_EMS_G8F2A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Bank statements and invoices
  "EMS.G8.F2.A3": [
    MC("What is a bank statement?", ["A record from the bank of all activity on an account", "A receipt for one cash sale", "An advert", "A business plan"], "A record from the bank of all activity on an account",
      "A bank statement lists all the deposits, payments and the balance on an account.", "ERR_EMS_G8F2A3_DEF", 1),
    MC("What is a cash invoice?", ["A document showing details of a cash sale or purchase", "A loan agreement", "A staff roster", "A tax law"], "A document showing details of a cash sale or purchase",
      "A cash invoice shows the details (items, amounts) of a cash transaction.", "ERR_EMS_G8F2A3_INVOICE", 1),
    MC("A bank statement shows ____.", ["money in, money out and the balance", "only adverts", "only staff names", "only prices in shops"], "money in, money out and the balance",
      "Statements show deposits, withdrawals and the running balance.", "ERR_EMS_G8F2A3_SHOWS", 1),
    MC("Why is a bank statement useful to a business?", ["To check its records against the bank's records", "To advertise", "To hide money", "To set prices"], "To check its records against the bank's records",
      "Businesses compare their records to the statement to check accuracy.", "ERR_EMS_G8F2A3_WHY", 2),
    MC("An invoice usually lists ____.", ["the items, quantities and amounts of a transaction", "only the weather", "only a company logo", "nothing useful"], "the items, quantities and amounts of a transaction",
      "Invoices detail items, quantities and amounts.", "ERR_EMS_G8F2A3_LIST", 2),
    MC("Who issues a bank statement?", ["The bank", "The customer", "The supplier", "The government"], "The bank",
      "The bank issues the statement to the account holder.", "ERR_EMS_G8F2A3_ISSUER", 1),
    MC("Comparing your records to the bank statement helps spot ____.", ["errors or missing transactions", "more customers", "new adverts", "better prices"], "errors or missing transactions",
      "Comparing helps find errors or transactions you missed.", "ERR_EMS_G8F2A3_ERRORS", 2),
    MC("A cash invoice is a source document for ____.", ["a cash sale or purchase", "advertising", "hiring staff", "paying tax only"], "a cash sale or purchase",
      "A cash invoice documents a cash sale or purchase.", "ERR_EMS_G8F2A3_SOURCE", 2),
    MC("If your records show a payment but the bank statement does not yet, you should ____.", ["check the difference and find out why", "ignore it", "delete your records", "stop banking"], "check the difference and find out why",
      "Differences should be investigated to keep records accurate.", "ERR_EMS_G8F2A3_DIFF", 3),
    MC("Which statement is correct?", ["A bank statement summarises account activity; an invoice details a transaction", "They are the same document", "An invoice is issued by the bank", "A statement lists only one sale"], "A bank statement summarises account activity; an invoice details a transaction",
      "Statements summarise the account; invoices detail individual transactions.", "ERR_EMS_G8F2A3_CORRECT", 2),
    TF("A bank statement records all activity on a bank account.", "True",
      "It lists deposits, payments and the balance.", "ERR_EMS_G8F2A3_TF1", 1),
    TF("A cash invoice shows the details of a cash transaction.", "True",
      "Invoices detail the items and amounts of a transaction.", "ERR_EMS_G8F2A3_TF2", 1),
    TF("A bank statement is issued by the customer to the bank.", "False",
      "The bank issues the statement to the customer.", "ERR_EMS_G8F2A3_TF3", 1),
    TF("Comparing records to a bank statement helps catch errors.", "True",
      "It helps spot mistakes or missing transactions.", "ERR_EMS_G8F2A3_TF4", 2),
    CLOZE("A record from the bank of all account activity is a bank ____.", ["statement", "receipt", "advert", "invoice"], "statement",
      "A bank statement summarises account activity.", "ERR_EMS_G8F2A3_CL1", 1),
    CLOZE("A document showing the details of a cash sale is a cash ____.", ["invoice", "receipt", "cheque", "statement"], "invoice",
      "A cash invoice details a cash transaction.", "ERR_EMS_G8F2A3_CL2", 1),
    CLOZE("A bank statement shows money in, money out and the ____.", ["balance", "advert", "logo", "price"], "balance",
      "It shows the running balance.", "ERR_EMS_G8F2A3_CL3", 2),
    CLOZE("The ____ issues a bank statement to the account holder.", ["bank", "customer", "supplier", "shop"], "bank",
      "The bank issues the statement.", "ERR_EMS_G8F2A3_CL4", 1),
    {
      question: "Sort each into 'Bank statement' or 'Invoice'.",
      input_type: "sort-buckets",
      buckets: [{ id: "statement", label: "Bank statement" }, { id: "invoice", label: "Invoice" }],
      items: [
        { id: "i1", text: "Summarises all account activity", correct_bucket: "statement" },
        { id: "i2", text: "Lists items and amounts of one sale", correct_bucket: "invoice" },
        { id: "i3", text: "Issued by the bank", correct_bucket: "statement" },
        { id: "i4", text: "Details a single purchase", correct_bucket: "invoice" },
      ],
      expected: "Account-wide summaries from the bank are statements; item-by-item details of one transaction are invoices.",
      pass_threshold: 0.75,
      memo: "Statement = whole account from the bank; invoice = details of one transaction.", error_signals: ["ERR_EMS_G8F2A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of checking records against a bank statement in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Receive the bank statement" },
        { id: "b", text: "Compare it with your own records" },
        { id: "c", text: "Spot any differences" },
        { id: "d", text: "Investigate and correct errors" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Get the statement, compare, spot differences, then investigate and correct.",
      error_signals: ["ERR_EMS_G8F2A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── F3 · Term 2 — The accounting cycle ────────────────────────────────────
  // A1 · Steps of the accounting cycle
  "EMS.G8.F3.A1": [
    MC("What is the accounting cycle?", ["The order of steps from a transaction to financial statements", "A type of bicycle", "A budget for a year", "A bank loan"], "The order of steps from a transaction to financial statements",
      "The accounting cycle is the sequence from a transaction through to the financial statements.", "ERR_EMS_G8F3A1_DEF", 1),
    MC("What is the first step of the accounting cycle?", ["A transaction takes place", "Preparing financial statements", "Drawing a trial balance", "Posting to the ledger"], "A transaction takes place",
      "Everything begins with a transaction.", "ERR_EMS_G8F3A1_FIRST", 1),
    MC("What provides the proof to record a transaction?", ["A source document", "An advert", "A wage slip only", "A weather report"], "A source document",
      "Source documents provide the evidence to record a transaction.", "ERR_EMS_G8F3A1_SOURCE", 1),
    MC("After source documents, transactions are first written into ____.", ["journals", "the trial balance", "financial statements", "adverts"], "journals",
      "Transactions are recorded in journals before posting to the ledger.", "ERR_EMS_G8F3A1_JOURNAL", 2),
    MC("From the journals, entries are posted to the ____.", ["General Ledger", "advert board", "bank statement", "till slip"], "General Ledger",
      "Journal entries are posted to the General Ledger accounts.", "ERR_EMS_G8F3A1_LEDGER", 2),
    MC("A list checking that total debits equal total credits is the ____.", ["Trial Balance", "advert", "receipt", "deposit slip"], "Trial Balance",
      "The Trial Balance checks that debits equal credits before statements.", "ERR_EMS_G8F3A1_TB", 2),
    MC("The final output of the cycle is the ____.", ["financial statements", "first transaction", "source document", "advert"], "financial statements",
      "The cycle ends with financial statements like the Income Statement.", "ERR_EMS_G8F3A1_STATEMENTS", 2),
    MC("Why follow the accounting cycle in order?", ["So records are accurate and statements are reliable", "To confuse staff", "To skip records", "To avoid accuracy"], "So records are accurate and statements are reliable",
      "Following the steps keeps records accurate and statements reliable.", "ERR_EMS_G8F3A1_WHY", 2),
    MC("Which step comes between the journals and the Trial Balance?", ["Posting to the General Ledger", "Issuing an advert", "Hiring staff", "Receiving a bank statement"], "Posting to the General Ledger",
      "Journals → General Ledger → Trial Balance.", "ERR_EMS_G8F3A1_BETWEEN", 3),
    MC("The accounting cycle repeats ____.", ["each accounting period", "only once ever", "never", "only on holidays"], "each accounting period",
      "The cycle repeats every accounting period.", "ERR_EMS_G8F3A1_REPEAT", 2),
    TF("The accounting cycle is the order of steps from a transaction to financial statements.", "True",
      "It runs from a transaction through to the financial statements.", "ERR_EMS_G8F3A1_TF1", 1),
    TF("Source documents come before journals in the cycle.", "True",
      "Documents provide evidence, then transactions are journalised.", "ERR_EMS_G8F3A1_TF2", 1),
    TF("Financial statements are prepared before any transaction happens.", "False",
      "Statements come last, after transactions are recorded and balanced.", "ERR_EMS_G8F3A1_TF3", 1),
    TF("The Trial Balance checks that total debits equal total credits.", "True",
      "It is a check that debits and credits balance.", "ERR_EMS_G8F3A1_TF4", 2),
    CLOZE("The order of steps from a transaction to statements is the accounting ____.", ["cycle", "advert", "budget", "loan"], "cycle",
      "It is the accounting cycle.", "ERR_EMS_G8F3A1_CL1", 1),
    CLOZE("Transactions are first written into ____ before the ledger.", ["journals", "adverts", "statements", "slips"], "journals",
      "Journals come before the ledger.", "ERR_EMS_G8F3A1_CL2", 2),
    CLOZE("Journal entries are posted to the General ____.", ["Ledger", "Advert", "Slip", "Budget"], "Ledger",
      "Entries post to the General Ledger.", "ERR_EMS_G8F3A1_CL3", 2),
    CLOZE("A check that debits equal credits is the ____ Balance.", ["Trial", "Bank", "Cash", "Final"], "Trial",
      "The Trial Balance checks debits = credits.", "ERR_EMS_G8F3A1_CL4", 2),
    {
      question: "Sort each into 'Start of the cycle' or 'End of the cycle'.",
      input_type: "sort-buckets",
      buckets: [{ id: "start", label: "Start of the cycle" }, { id: "end", label: "End of the cycle" }],
      items: [
        { id: "i1", text: "A transaction takes place", correct_bucket: "start" },
        { id: "i2", text: "Financial statements are prepared", correct_bucket: "end" },
        { id: "i3", text: "A source document is created", correct_bucket: "start" },
        { id: "i4", text: "The Trial Balance is drawn up", correct_bucket: "end" },
      ],
      expected: "Transactions and source documents start the cycle; the Trial Balance and statements come near the end.",
      pass_threshold: 0.75,
      memo: "Start: transaction → source document. End: trial balance → statements.", error_signals: ["ERR_EMS_G8F3A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the accounting cycle in the correct order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A transaction happens" },
        { id: "b", text: "A source document is created" },
        { id: "c", text: "It is recorded in a journal" },
        { id: "d", text: "Posted to the ledger, then a trial balance and financial statements" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Transaction → source document → journal → ledger → trial balance → statements.",
      error_signals: ["ERR_EMS_G8F3A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Purpose of the cash journals
  "EMS.G8.F3.A2": [
    MC("What is the purpose of the Cash Journals?", ["To record all the cash a business receives and pays", "To advertise the business", "To hire staff", "To set prices"], "To record all the cash a business receives and pays",
      "Cash journals record cash received and cash paid out.", "ERR_EMS_G8F3A2_DEF", 1),
    MC("The Cash Receipts Journal records ____.", ["cash the business receives", "cash the business pays out", "staff names", "adverts"], "cash the business receives",
      "The CRJ records money coming in.", "ERR_EMS_G8F3A2_CRJ", 1),
    MC("The Cash Payments Journal records ____.", ["cash the business pays out", "cash the business receives", "customers' birthdays", "adverts"], "cash the business pays out",
      "The CPJ records money going out.", "ERR_EMS_G8F3A2_CPJ", 1),
    MC("Why are the cash journals important for a service business?", ["They keep an organised record of all cash in and out", "They hide cash", "They replace the bank", "They advertise services"], "They keep an organised record of all cash in and out",
      "They organise the record of cash flowing in and out.", "ERR_EMS_G8F3A2_WHY", 2),
    MC("The cash journals are an early step in the ____.", ["accounting cycle", "advertising plan", "hiring process", "tax law"], "accounting cycle",
      "Journals come early in the accounting cycle.", "ERR_EMS_G8F3A2_CYCLE", 2),
    MC("Which journal would record money received from a customer for a service?", ["Cash Receipts Journal", "Cash Payments Journal", "Advert log", "Staff roster"], "Cash Receipts Journal",
      "Money received goes in the CRJ.", "ERR_EMS_G8F3A2_REC_EX", 2),
    MC("Which journal would record paying the rent in cash?", ["Cash Payments Journal", "Cash Receipts Journal", "Advert log", "Wage list"], "Cash Payments Journal",
      "Cash paid out (rent) goes in the CPJ.", "ERR_EMS_G8F3A2_PAY_EX", 2),
    MC("A service business mainly earns money by ____.", ["providing services", "manufacturing goods", "reselling stock", "mining"], "providing services",
      "A service business earns from services, which the cash journals help record.", "ERR_EMS_G8F3A2_SERVICE", 1),
    MC("Keeping cash journals helps the owner to ____.", ["see how much cash came in and went out", "ignore the cash", "lose track", "avoid records"], "see how much cash came in and went out",
      "Cash journals show the flow of cash in and out.", "ERR_EMS_G8F3A2_HELP", 2),
    MC("Which statement is correct about the cash journals?", ["The CRJ is for cash received; the CPJ is for cash paid", "Both record only payments", "Both record only receipts", "They are the same journal"], "The CRJ is for cash received; the CPJ is for cash paid",
      "CRJ = receipts (in); CPJ = payments (out).", "ERR_EMS_G8F3A2_CORRECT", 2),
    TF("The cash journals record cash received and cash paid.", "True",
      "They record cash in (CRJ) and cash out (CPJ).", "ERR_EMS_G8F3A2_TF1", 1),
    TF("The Cash Receipts Journal records money the business receives.", "True",
      "The CRJ records cash received.", "ERR_EMS_G8F3A2_TF2", 1),
    TF("The Cash Payments Journal records money the business receives.", "False",
      "The CPJ records money paid out, not received.", "ERR_EMS_G8F3A2_TF3", 1),
    TF("The cash journals are part of the accounting cycle.", "True",
      "Journals are an early step in the accounting cycle.", "ERR_EMS_G8F3A2_TF4", 1),
    CLOZE("The journals that record cash in and out are the ____ journals.", ["cash", "advert", "wage", "tax"], "cash",
      "Cash journals record cash in and out.", "ERR_EMS_G8F3A2_CL1", 1),
    CLOZE("The Cash ____ Journal records cash received.", ["Receipts", "Payments", "Advert", "Wage"], "Receipts",
      "The CRJ records receipts (cash in).", "ERR_EMS_G8F3A2_CL2", 1),
    CLOZE("The Cash ____ Journal records cash paid out.", ["Payments", "Receipts", "Advert", "Wage"], "Payments",
      "The CPJ records payments (cash out).", "ERR_EMS_G8F3A2_CL3", 1),
    CLOZE("Cash journals are an early step in the accounting ____.", ["cycle", "advert", "budget", "loan"], "cycle",
      "Journals come early in the accounting cycle.", "ERR_EMS_G8F3A2_CL4", 2),
    {
      question: "Sort each transaction into 'Cash Receipts Journal' or 'Cash Payments Journal'.",
      input_type: "sort-buckets",
      buckets: [{ id: "crj", label: "Cash Receipts Journal" }, { id: "cpj", label: "Cash Payments Journal" }],
      items: [
        { id: "i1", text: "Cash received for a service", correct_bucket: "crj" },
        { id: "i2", text: "Paying rent in cash", correct_bucket: "cpj" },
        { id: "i3", text: "Cash banked from a customer", correct_bucket: "crj" },
        { id: "i4", text: "Paying wages in cash", correct_bucket: "cpj" },
      ],
      expected: "Money received goes in the CRJ; money paid out goes in the CPJ.",
      pass_threshold: 0.75,
      memo: "CRJ = cash in; CPJ = cash out.", error_signals: ["ERR_EMS_G8F3A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the role of the cash journals in the cycle in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A cash transaction occurs" },
        { id: "b", text: "A source document proves it" },
        { id: "c", text: "It is recorded in the CRJ or CPJ" },
        { id: "d", text: "Later it is posted to the ledger" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Cash transaction → source document → cash journal → later posted to the ledger.",
      error_signals: ["ERR_EMS_G8F3A2_SEQ"], difficulty: 2,
    },
  ],

  // ─── F4 · Term 2 — Cash Receipts Journal (concept only) ────────────────────
  // A1 · Concept and columns of the CRJ  (A2, A3 = deferred_recording)
  "EMS.G8.F4.A1": [
    MC("What is the Cash Receipts Journal (CRJ)?", ["A journal that records all cash received by the business", "A journal of cash paid out", "A list of adverts", "A staff roster"], "A journal that records all cash received by the business",
      "The CRJ records all cash the business receives.", "ERR_EMS_G8F4A1_DEF", 1),
    MC("Which transactions belong in the CRJ?", ["Cash coming in", "Cash going out", "Staff birthdays", "Advert designs"], "Cash coming in",
      "Only cash received is recorded in the CRJ.", "ERR_EMS_G8F4A1_IN", 1),
    MC("Why does the CRJ have columns?", ["To organise different types of money received", "To make it look nice only", "To hide totals", "To confuse readers"], "To organise different types of money received",
      "Columns group different kinds of receipts for easy totalling.", "ERR_EMS_G8F4A1_COLUMNS", 2),
    MC("A 'bank' column in the CRJ usually shows ____.", ["the total cash banked", "staff names", "advert costs", "the weather"], "the total cash banked",
      "The bank column totals the cash deposited/banked.", "ERR_EMS_G8F4A1_BANK", 2),
    MC("The CRJ is used by a ____ business in Grade 8.", ["service", "mining", "manufacturing only", "farming only"], "service",
      "In Grade 8 the CRJ is studied for a service business.", "ERR_EMS_G8F4A1_SERVICE", 1),
    MC("Recording receipts in one journal helps the business to ____.", ["see all its income in an organised way", "lose track of income", "avoid records", "hide money"], "see all its income in an organised way",
      "The CRJ organises all receipts in one place.", "ERR_EMS_G8F4A1_HELP", 2),
    MC("Which is an example of an entry that would appear in the CRJ?", ["Cash received for services rendered", "Cash paid for rent", "A staff leave form", "An advert poster"], "Cash received for services rendered",
      "Service income received in cash is a CRJ entry.", "ERR_EMS_G8F4A1_EX", 2),
    MC("The CRJ is part of the ____.", ["accounting cycle", "advertising plan", "hiring process", "tax court"], "accounting cycle",
      "The CRJ is one of the journals in the accounting cycle.", "ERR_EMS_G8F4A1_CYCLE", 1),
    MC("Columns in the CRJ are totalled so the business can ____.", ["add up each type of receipt", "ignore the money", "lose the totals", "avoid banking"], "add up each type of receipt",
      "Totalling columns sums each category of receipt.", "ERR_EMS_G8F4A1_TOTAL", 2),
    MC("Which statement is correct about the CRJ?", ["It records cash received and uses columns to organise it", "It records cash paid out", "It is the same as a bank statement", "It records only adverts"], "It records cash received and uses columns to organise it",
      "The CRJ records cash received, organised in columns.", "ERR_EMS_G8F4A1_CORRECT", 2),
    TF("The CRJ records all cash received by the business.", "True",
      "The CRJ is for cash received.", "ERR_EMS_G8F4A1_TF1", 1),
    TF("The CRJ records cash paid out.", "False",
      "Cash paid out goes in the Cash Payments Journal, not the CRJ.", "ERR_EMS_G8F4A1_TF2", 1),
    TF("Columns help organise different types of receipts in the CRJ.", "True",
      "Columns group receipts by type for easy totalling.", "ERR_EMS_G8F4A1_TF3", 2),
    TF("The CRJ is part of the accounting cycle.", "True",
      "It is one of the journals in the cycle.", "ERR_EMS_G8F4A1_TF4", 1),
    CLOZE("The journal that records cash received is the Cash ____ Journal.", ["Receipts", "Payments", "Advert", "Wage"], "Receipts",
      "The CRJ records cash received.", "ERR_EMS_G8F4A1_CL1", 1),
    CLOZE("The CRJ records cash coming ____.", ["in", "out", "down", "nowhere"], "in",
      "The CRJ is for cash in.", "ERR_EMS_G8F4A1_CL2", 1),
    CLOZE("Different types of receipts are organised using ____ in the CRJ.", ["columns", "adverts", "photos", "logos"], "columns",
      "Columns organise the receipts.", "ERR_EMS_G8F4A1_CL3", 2),
    CLOZE("In Grade 8 the CRJ is studied for a ____ business.", ["service", "mining", "farming", "import"], "service",
      "The Grade 8 CRJ is for a service business.", "ERR_EMS_G8F4A1_CL4", 1),
    {
      question: "Sort each into 'Belongs in the CRJ' or 'Does not belong in the CRJ'.",
      input_type: "sort-buckets",
      buckets: [{ id: "crj", label: "Belongs in the CRJ" }, { id: "not", label: "Does NOT belong in the CRJ" }],
      items: [
        { id: "i1", text: "Cash received for a service", correct_bucket: "crj" },
        { id: "i2", text: "Paying rent in cash", correct_bucket: "not" },
        { id: "i3", text: "Cash banked from sales", correct_bucket: "crj" },
        { id: "i4", text: "Paying wages in cash", correct_bucket: "not" },
      ],
      expected: "Cash received belongs in the CRJ; cash paid out belongs in the CPJ instead.",
      pass_threshold: 0.75,
      memo: "CRJ = cash received only; payments go in the CPJ.", error_signals: ["ERR_EMS_G8F4A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the idea of using the CRJ in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The business receives cash" },
        { id: "b", text: "A receipt or till slip proves it" },
        { id: "c", text: "It is entered in the CRJ in the right column" },
        { id: "d", text: "Columns are totalled at month-end" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Cash received → source document → recorded in the CRJ column → columns totalled.",
      error_signals: ["ERR_EMS_G8F4A1_SEQ"], difficulty: 2,
    },
  ],

  // ─── F5 · Term 3 — Cash Payments Journal (concept only) ────────────────────
  // A1 · Concept and columns of the CPJ  (A2, A3 = deferred_recording)
  "EMS.G8.F5.A1": [
    MC("What is the Cash Payments Journal (CPJ)?", ["A journal that records all cash paid out by the business", "A journal of cash received", "A list of customers", "An advert log"], "A journal that records all cash paid out by the business",
      "The CPJ records all cash the business pays out.", "ERR_EMS_G8F5A1_DEF", 1),
    MC("Which transactions belong in the CPJ?", ["Cash going out", "Cash coming in", "Staff birthdays", "Advert ideas"], "Cash going out",
      "Only cash paid out is recorded in the CPJ.", "ERR_EMS_G8F5A1_OUT", 1),
    MC("Why does the CPJ have columns?", ["To organise different types of payments", "To look pretty only", "To hide totals", "To confuse staff"], "To organise different types of payments",
      "Columns group different kinds of payments for easy totalling.", "ERR_EMS_G8F5A1_COLUMNS", 2),
    MC("Which is an example of a CPJ entry?", ["Paying rent in cash", "Cash received for a service", "A staff leave form", "An advert poster"], "Paying rent in cash",
      "Paying rent (cash out) is a CPJ entry.", "ERR_EMS_G8F5A1_EX", 2),
    MC("The CPJ is used by a ____ business in Grade 8.", ["service", "mining", "manufacturing only", "import only"], "service",
      "In Grade 8 the CPJ is studied for a service business.", "ERR_EMS_G8F5A1_SERVICE", 1),
    MC("Recording payments in one journal helps the business to ____.", ["see all its spending in an organised way", "lose track of spending", "avoid records", "hide payments"], "see all its spending in an organised way",
      "The CPJ organises all payments in one place.", "ERR_EMS_G8F5A1_HELP", 2),
    MC("Which column might a CPJ have?", ["A 'bank' column for total cash paid", "A 'weather' column", "A 'birthday' column", "A 'colour' column"], "A 'bank' column for total cash paid",
      "The bank column totals the cash paid out.", "ERR_EMS_G8F5A1_BANK", 2),
    MC("The CPJ is part of the ____.", ["accounting cycle", "advertising plan", "hiring process", "tax court"], "accounting cycle",
      "The CPJ is one of the journals in the accounting cycle.", "ERR_EMS_G8F5A1_CYCLE", 1),
    MC("The CRJ and CPJ together record ____.", ["all the cash in and out of the business", "only adverts", "only staff names", "only prices"], "all the cash in and out of the business",
      "CRJ (in) and CPJ (out) together capture all cash flows.", "ERR_EMS_G8F5A1_TOGETHER", 2),
    MC("Which statement is correct about the CPJ?", ["It records cash paid out and uses columns to organise it", "It records cash received", "It is the same as a receipt", "It records only adverts"], "It records cash paid out and uses columns to organise it",
      "The CPJ records cash paid out, organised in columns.", "ERR_EMS_G8F5A1_CORRECT", 2),
    TF("The CPJ records all cash paid out by the business.", "True",
      "The CPJ is for cash paid out.", "ERR_EMS_G8F5A1_TF1", 1),
    TF("The CPJ records cash received.", "False",
      "Cash received goes in the CRJ, not the CPJ.", "ERR_EMS_G8F5A1_TF2", 1),
    TF("Columns help organise different types of payments in the CPJ.", "True",
      "Columns group payments by type.", "ERR_EMS_G8F5A1_TF3", 2),
    TF("The CRJ and CPJ together capture all the cash in and out.", "True",
      "Together they record all cash flows.", "ERR_EMS_G8F5A1_TF4", 2),
    CLOZE("The journal that records cash paid out is the Cash ____ Journal.", ["Payments", "Receipts", "Advert", "Wage"], "Payments",
      "The CPJ records cash paid out.", "ERR_EMS_G8F5A1_CL1", 1),
    CLOZE("The CPJ records cash going ____.", ["out", "in", "up", "nowhere"], "out",
      "The CPJ is for cash out.", "ERR_EMS_G8F5A1_CL2", 1),
    CLOZE("Different types of payments are organised using ____ in the CPJ.", ["columns", "adverts", "photos", "logos"], "columns",
      "Columns organise the payments.", "ERR_EMS_G8F5A1_CL3", 2),
    CLOZE("The CRJ records cash in; the CPJ records cash ____.", ["out", "in", "up", "down only"], "out",
      "CRJ = in, CPJ = out.", "ERR_EMS_G8F5A1_CL4", 1),
    {
      question: "Sort each into 'Belongs in the CPJ' or 'Belongs in the CRJ'.",
      input_type: "sort-buckets",
      buckets: [{ id: "cpj", label: "Belongs in the CPJ" }, { id: "crj", label: "Belongs in the CRJ" }],
      items: [
        { id: "i1", text: "Paying rent in cash", correct_bucket: "cpj" },
        { id: "i2", text: "Cash received for a service", correct_bucket: "crj" },
        { id: "i3", text: "Paying wages in cash", correct_bucket: "cpj" },
        { id: "i4", text: "Cash banked from customers", correct_bucket: "crj" },
      ],
      expected: "Payments (rent, wages) belong in the CPJ; receipts belong in the CRJ.",
      pass_threshold: 0.75,
      memo: "CPJ = cash out; CRJ = cash in.", error_signals: ["ERR_EMS_G8F5A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the idea of using the CPJ in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The business pays out cash" },
        { id: "b", text: "A cheque counterfoil or receipt proves it" },
        { id: "c", text: "It is entered in the CPJ in the right column" },
        { id: "d", text: "Columns are totalled at month-end" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Cash paid → source document → recorded in the CPJ column → columns totalled.",
      error_signals: ["ERR_EMS_G8F5A1_SEQ"], difficulty: 2,
    },
  ],

  // ─── F6 · Term 4 — General Ledger & Trial Balance (concept only) ───────────
  // A1 · Double-entry and T-accounts  (A2, A3 = deferred_recording)
  "EMS.G8.F6.A1": [
    MC("What is the double-entry principle?", ["Every transaction is recorded with an equal debit and credit", "Every transaction is written once", "Only income is recorded", "Only payments are recorded"], "Every transaction is recorded with an equal debit and credit",
      "Double-entry records each transaction twice — a debit and an equal credit.", "ERR_EMS_G8F6A1_DEF", 1),
    MC("Why is it called 'double' entry?", ["Each transaction has two sides: debit and credit", "It is written in two books only", "It doubles the money", "It is done twice a year"], "Each transaction has two sides: debit and credit",
      "Two sides — a debit and a credit — give double-entry its name.", "ERR_EMS_G8F6A1_WHY", 1),
    MC("What is a 'T-account'?", ["A way of drawing an account with a debit and credit side", "A type of teacup", "A tax form", "A till slip"], "A way of drawing an account with a debit and credit side",
      "A T-account is the T-shaped layout showing debit (left) and credit (right) sides.", "ERR_EMS_G8F6A1_TACCOUNT", 1),
    MC("In a T-account, the debit side is on the ____.", ["left", "right", "top", "bottom"], "left",
      "Debit is the left side of the T-account.", "ERR_EMS_G8F6A1_LEFT", 2),
    MC("In a T-account, the credit side is on the ____.", ["right", "left", "middle", "outside"], "right",
      "Credit is the right side of the T-account.", "ERR_EMS_G8F6A1_RIGHT", 2),
    MC("The General Ledger is ____.", ["the book containing all the accounts", "a single receipt", "an advert", "a bank statement"], "the book containing all the accounts",
      "The General Ledger holds all the business's accounts.", "ERR_EMS_G8F6A1_LEDGER", 2),
    MC("Under double-entry, total debits must ____ total credits.", ["equal", "be less than", "be more than", "be unrelated to"], "equal",
      "Debits must equal credits — the books stay balanced.", "ERR_EMS_G8F6A1_EQUAL", 2),
    MC("Why use double-entry?", ["It keeps the books balanced and helps catch errors", "It hides money", "It avoids accuracy", "It removes records"], "It keeps the books balanced and helps catch errors",
      "Double-entry keeps the equation balanced and helps detect mistakes.", "ERR_EMS_G8F6A1_USE", 2),
    MC("Each account in the General Ledger can be drawn as a ____.", ["T-account", "till slip", "cheque", "deposit slip"], "T-account",
      "Ledger accounts are often drawn as T-accounts.", "ERR_EMS_G8F6A1_DRAW", 2),
    MC("Which statement is correct?", ["Double-entry records a debit and an equal credit for each transaction", "Double-entry records only debits", "Double-entry records only credits", "Double-entry ignores credits"], "Double-entry records a debit and an equal credit for each transaction",
      "Each transaction has an equal debit and credit under double-entry.", "ERR_EMS_G8F6A1_CORRECT", 1),
    TF("Double-entry records each transaction with a debit and an equal credit.", "True",
      "Every transaction has two equal sides.", "ERR_EMS_G8F6A1_TF1", 1),
    TF("A T-account has a debit side and a credit side.", "True",
      "The T-account shows debit (left) and credit (right).", "ERR_EMS_G8F6A1_TF2", 1),
    TF("In a T-account, the credit side is on the left.", "False",
      "Credit is on the right; debit is on the left.", "ERR_EMS_G8F6A1_TF3", 1),
    TF("The General Ledger contains all the business's accounts.", "True",
      "The General Ledger holds all the accounts.", "ERR_EMS_G8F6A1_TF4", 1),
    CLOZE("Recording each transaction with an equal debit and credit is the ____-entry principle.", ["double", "single", "triple", "half"], "double",
      "It is the double-entry principle.", "ERR_EMS_G8F6A1_CL1", 1),
    CLOZE("An account drawn with a debit and credit side is a ____-account.", ["T", "X", "Y", "Z"], "T",
      "A T-account shows the two sides.", "ERR_EMS_G8F6A1_CL2", 1),
    CLOZE("The book that contains all the accounts is the General ____.", ["Ledger", "Slip", "Advert", "Budget"], "Ledger",
      "The General Ledger holds all accounts.", "ERR_EMS_G8F6A1_CL3", 2),
    CLOZE("Under double-entry, total debits must ____ total credits.", ["equal", "beat", "halve", "double"], "equal",
      "Debits equal credits.", "ERR_EMS_G8F6A1_CL4", 2),
    {
      question: "Sort each into 'Debit side' or 'Credit side' of a T-account.",
      input_type: "sort-buckets",
      buckets: [{ id: "debit", label: "Debit side (left)" }, { id: "credit", label: "Credit side (right)" }],
      items: [
        { id: "i1", text: "Left side of the T-account", correct_bucket: "debit" },
        { id: "i2", text: "Right side of the T-account", correct_bucket: "credit" },
        { id: "i3", text: "Where the debit entry goes", correct_bucket: "debit" },
        { id: "i4", text: "Where the credit entry goes", correct_bucket: "credit" },
      ],
      expected: "Debit is the left side; credit is the right side of the T-account.",
      pass_threshold: 0.75,
      memo: "T-account: debit = left, credit = right.", error_signals: ["ERR_EMS_G8F6A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the idea of double-entry in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A transaction takes place" },
        { id: "b", text: "One account is debited" },
        { id: "c", text: "Another account is credited by the same amount" },
        { id: "d", text: "Total debits equal total credits" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Debit one account, credit another by the same amount, and debits equal credits.",
      error_signals: ["ERR_EMS_G8F6A1_SEQ"], difficulty: 2,
    },
  ],
};

export default G8B;
