// ─── EMS SP — Grade 7 authored pools (C): Entrepreneurship ────────────────────
// Strand: Entrepreneurship (CAPS G7). Tap-only: choice / true-false / cloze /
// sequence / sort-buckets. Recipe: 10 MC · 4 TF · 4 CLOZE · 1 sequence · 1 sort.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7C = {
  // ─── B1 · Term 1 — Businesses ──────────────────────────────────────────────
  // A1 · Formal and informal businesses
  "EMS.G7.B1.A1": [
    MC("What is a formal business?", ["A registered business that pays tax and follows rules", "An unregistered street trader", "A business that breaks the law", "A business with no owner"], "A registered business that pays tax and follows rules",
      "A formal business is registered with the authorities, pays tax and follows regulations.", "ERR_EMS_G7B1A1_FORMAL", 1),
    MC("What is an informal business?", ["A small, usually unregistered business", "A large registered company", "A government department", "A bank"], "A small, usually unregistered business",
      "Informal businesses are usually small and not formally registered, like a street vendor.", "ERR_EMS_G7B1A1_INFORMAL", 1),
    MC("Which is an example of an informal business?", ["A street vendor selling fruit", "A registered supermarket chain", "A licensed bank", "A listed company"], "A street vendor selling fruit",
      "A street vendor is typically informal and unregistered.", "ERR_EMS_G7B1A1_INFORMAL_EX", 1),
    MC("Which is an advantage of a formal business?", ["It can access bank loans more easily", "It never pays tax", "It cannot grow", "It has no records"], "It can access bank loans more easily",
      "Formal businesses, being registered, can more easily get loans and contracts.", "ERR_EMS_G7B1A1_FORMAL_ADV", 2),
    MC("Which is an advantage of an informal business?", ["It is easy and cheap to start", "It always pays the most tax", "It needs lots of paperwork", "It must be a big company"], "It is easy and cheap to start",
      "Informal businesses are quick and cheap to start with little paperwork.", "ERR_EMS_G7B1A1_INFORMAL_ADV", 2),
    MC("Which is a disadvantage of an informal business?", ["It often cannot get bank loans easily", "It pays too much tax", "It has too many employees", "It must follow many rules"], "It often cannot get bank loans easily",
      "Because they are unregistered, informal businesses struggle to access loans.", "ERR_EMS_G7B1A1_INFORMAL_DIS", 2),
    MC("A spaza shop that is not registered is an example of a(n) ____ business.", ["informal", "formal", "listed", "government"], "informal",
      "An unregistered spaza shop is an informal business.", "ERR_EMS_G7B1A1_SPAZA", 1),
    MC("Which of these would most likely be a formal business?", ["A registered clothing factory", "A pavement sweet seller", "An unregistered car wash", "A backyard tuck box"], "A registered clothing factory",
      "A registered factory is a formal business; the others are informal.", "ERR_EMS_G7B1A1_FORMAL_EX", 2),
    MC("A disadvantage of a formal business is that ____.", ["it has more paperwork and must pay tax", "it can never get loans", "it is always illegal", "it cannot hire staff"], "it has more paperwork and must pay tax",
      "Formal businesses face more rules, paperwork and tax obligations.", "ERR_EMS_G7B1A1_FORMAL_DIS", 2),
    MC("Why does the government prefer businesses to become formal?", ["They pay tax and follow consumer-protection rules", "They avoid all customers", "They never make profit", "They cannot create jobs"], "They pay tax and follow consumer-protection rules",
      "Formal businesses pay tax and follow rules that protect workers and customers.", "ERR_EMS_G7B1A1_GOVT", 3),
    TF("A formal business is registered and pays tax.", "True",
      "Formal businesses are registered and meet tax and legal requirements.", "ERR_EMS_G7B1A1_TF1", 1),
    TF("An informal business is usually large and listed on the stock exchange.", "False",
      "Informal businesses are usually small and unregistered, not large listed companies.", "ERR_EMS_G7B1A1_TF2", 1),
    TF("Informal businesses are usually quick and cheap to start.", "True",
      "With little paperwork, informal businesses are easy and cheap to start.", "ERR_EMS_G7B1A1_TF3", 1),
    TF("Formal businesses can usually access bank loans more easily than informal ones.", "True",
      "Being registered helps formal businesses qualify for loans.", "ERR_EMS_G7B1A1_TF4", 2),
    CLOZE("A registered business that pays tax is a ____ business.", ["formal", "informal", "secret", "illegal"], "formal",
      "Formal businesses are registered and pay tax.", "ERR_EMS_G7B1A1_CL1", 1),
    CLOZE("A small, unregistered business is an ____ business.", ["informal", "formal", "listed", "official"], "informal",
      "Informal businesses are small and usually unregistered.", "ERR_EMS_G7B1A1_CL2", 1),
    CLOZE("A street vendor is usually part of the ____ sector of the economy.", ["informal", "formal", "banking", "mining"], "informal",
      "Street vendors are typical of the informal sector.", "ERR_EMS_G7B1A1_CL3", 2),
    CLOZE("Formal businesses must follow rules and pay ____.", ["tax", "nothing", "rent only", "gifts"], "tax",
      "Formal businesses pay tax and follow regulations.", "ERR_EMS_G7B1A1_CL4", 1),
    {
      question: "Sort each business into 'Formal' or 'Informal'.",
      input_type: "sort-buckets",
      buckets: [{ id: "formal", label: "Formal" }, { id: "informal", label: "Informal" }],
      items: [
        { id: "i1", text: "A registered supermarket", correct_bucket: "formal" },
        { id: "i2", text: "A pavement fruit seller", correct_bucket: "informal" },
        { id: "i3", text: "A licensed restaurant", correct_bucket: "formal" },
        { id: "i4", text: "An unregistered backyard barber", correct_bucket: "informal" },
      ],
      expected: "Registered shops and licensed restaurants are formal; pavement sellers and unregistered barbers are informal.",
      pass_threshold: 0.75,
      memo: "Formal = registered, taxed, regulated; informal = small and unregistered.", error_signals: ["ERR_EMS_G7B1A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of making a business formal in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "An informal trader decides to grow" },
        { id: "b", text: "They register the business officially" },
        { id: "c", text: "They keep records and pay tax" },
        { id: "d", text: "They can now access loans and bigger contracts" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Becoming formal: decide to grow, register, keep records and pay tax, then access loans and contracts.",
      error_signals: ["ERR_EMS_G7B1A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Types of businesses
  "EMS.G7.B1.A2": [
    MC("What does a trading business do?", ["Buys goods and sells them", "Makes raw materials into products", "Only provides services", "Grows crops only"], "Buys goods and sells them",
      "A trading business buys finished goods and sells them to customers.", "ERR_EMS_G7B1A2_TRADING", 1),
    MC("What does a manufacturing business do?", ["Makes goods from raw materials", "Only resells finished goods", "Provides haircuts", "Drives taxis"], "Makes goods from raw materials",
      "A manufacturing business turns raw materials into finished products.", "ERR_EMS_G7B1A2_MANUF", 1),
    MC("What does a service business do?", ["Provides useful actions for customers", "Makes goods in a factory", "Sells products from shelves", "Mines minerals"], "Provides useful actions for customers",
      "A service business provides services, like repairs, transport or hairdressing.", "ERR_EMS_G7B1A2_SERVICE", 1),
    MC("A bakery that bakes and sells its own bread is mainly a ____ business.", ["manufacturing", "trading", "service", "mining"], "manufacturing",
      "Baking bread from ingredients is manufacturing (making goods).", "ERR_EMS_G7B1A2_BAKERY", 2),
    MC("A shop that buys clothes from a factory and sells them is a ____ business.", ["trading", "manufacturing", "service", "farming"], "trading",
      "Buying finished clothes to resell is trading.", "ERR_EMS_G7B1A2_SHOP", 2),
    MC("A hair salon is an example of a ____ business.", ["service", "manufacturing", "trading", "mining"], "service",
      "A salon provides a service (haircuts), so it is a service business.", "ERR_EMS_G7B1A2_SALON", 1),
    MC("Which type of business changes raw materials into new products?", ["Manufacturing", "Trading", "Service", "Reselling"], "Manufacturing",
      "Manufacturing transforms raw materials into finished goods.", "ERR_EMS_G7B1A2_CHANGE", 1),
    MC("A taxi company that transports passengers is a ____ business.", ["service", "trading", "manufacturing", "farming"], "service",
      "Transport is a service, so a taxi company is a service business.", "ERR_EMS_G7B1A2_TAXI", 1),
    MC("Which business buys finished goods to resell at a higher price?", ["A trading business", "A manufacturing business", "A service business", "A mining business"], "A trading business",
      "Trading businesses buy goods and resell them to make a profit.", "ERR_EMS_G7B1A2_RESELL", 2),
    MC("A furniture factory that makes tables and a shop that resells them show ____.", ["a manufacturer and a trader", "two service businesses", "two manufacturers", "two traders"], "a manufacturer and a trader",
      "The factory manufactures; the shop trades the finished tables.", "ERR_EMS_G7B1A2_BOTH", 3),
    TF("A trading business buys and resells goods.", "True",
      "Trading businesses buy goods and sell them on.", "ERR_EMS_G7B1A2_TF1", 1),
    TF("A manufacturing business provides only services, never goods.", "False",
      "Manufacturers make goods; service businesses provide services.", "ERR_EMS_G7B1A2_TF2", 1),
    TF("A service business provides actions or tasks rather than physical goods.", "True",
      "Service businesses sell useful actions, like repairs or transport.", "ERR_EMS_G7B1A2_TF3", 1),
    TF("Both formal and informal businesses can be trading, manufacturing or service businesses.", "True",
      "All three types exist in both the formal and informal sectors.", "ERR_EMS_G7B1A2_TF4", 2),
    CLOZE("A business that buys and resells goods is a ____ business.", ["trading", "manufacturing", "service", "mining"], "trading",
      "Trading businesses buy and resell goods.", "ERR_EMS_G7B1A2_CL1", 1),
    CLOZE("A business that makes goods from raw materials is a ____ business.", ["manufacturing", "trading", "service", "farming"], "manufacturing",
      "Manufacturing businesses make goods.", "ERR_EMS_G7B1A2_CL2", 1),
    CLOZE("A business that provides haircuts or repairs is a ____ business.", ["service", "trading", "manufacturing", "mining"], "service",
      "Service businesses provide useful actions.", "ERR_EMS_G7B1A2_CL3", 1),
    CLOZE("A factory turning wood into chairs is doing ____.", ["manufacturing", "trading", "servicing", "farming"], "manufacturing",
      "Turning raw materials into products is manufacturing.", "ERR_EMS_G7B1A2_CL4", 2),
    {
      question: "Sort each business into 'Trading', 'Manufacturing' or 'Service'.",
      input_type: "sort-buckets",
      buckets: [{ id: "trading", label: "Trading" }, { id: "manufacturing", label: "Manufacturing" }, { id: "service", label: "Service" }],
      items: [
        { id: "i1", text: "A clothing shop reselling jeans", correct_bucket: "trading" },
        { id: "i2", text: "A bakery baking bread", correct_bucket: "manufacturing" },
        { id: "i3", text: "A plumber fixing pipes", correct_bucket: "service" },
        { id: "i4", text: "A factory making shoes", correct_bucket: "manufacturing" },
      ],
      expected: "Reselling jeans is trading; baking and shoe-making are manufacturing; plumbing is a service.",
      pass_threshold: 0.75,
      memo: "Trading resells goods; manufacturing makes goods; service provides actions.", error_signals: ["ERR_EMS_G7B1A2_SORT"], difficulty: 2,
    },
    {
      question: "Put the journey of a loaf of bread through business types in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A farm grows wheat (raw material)" },
        { id: "b", text: "A bakery manufactures bread from flour" },
        { id: "c", text: "A shop trades (resells) the bread" },
        { id: "d", text: "A delivery service brings it to a customer" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Raw material → manufacturing → trading → service brings it to the buyer.",
      error_signals: ["ERR_EMS_G7B1A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Businesses, disasters and epidemics
  "EMS.G7.B1.A3": [
    MC("How can a business act as a producer?", ["By making or supplying goods and services", "By only buying things", "By never trading", "By closing down"], "By making or supplying goods and services",
      "Businesses produce by making or supplying goods and services for customers.", "ERR_EMS_G7B1A3_PRODUCER", 1),
    MC("How can a business also act as a consumer?", ["By buying supplies and resources it needs", "By never spending money", "By only selling", "By avoiding suppliers"], "By buying supplies and resources it needs",
      "Businesses consume too — they buy materials, electricity and services.", "ERR_EMS_G7B1A3_CONSUMER", 1),
    MC("How might a natural disaster, like a flood, affect a business?", ["It can damage stock and stop trading", "It always increases profit", "It has no effect", "It guarantees more customers"], "It can damage stock and stop trading",
      "Disasters can destroy stock and premises and halt trading, causing losses.", "ERR_EMS_G7B1A3_DISASTER", 1),
    MC("How might a health epidemic affect a business?", ["Fewer customers and staff may be able to work", "More staff than ever", "No change at all", "Guaranteed higher sales"], "Fewer customers and staff may be able to work",
      "An epidemic can reduce customers and keep staff at home, hurting business.", "ERR_EMS_G7B1A3_EPIDEMIC", 2),
    MC("Why are businesses important as producers in a community?", ["They supply goods and services people need", "They remove all jobs", "They never sell anything", "They only cause harm"], "They supply goods and services people need",
      "As producers, businesses provide the goods and services a community relies on.", "ERR_EMS_G7B1A3_IMPORTANT", 2),
    MC("A drought reduces a farm's harvest. As a producer, the farm will likely ____.", ["produce and sell less", "produce much more", "stop being affected", "gain free crops"], "produce and sell less",
      "A drought cuts the harvest, so the farm produces and sells less.", "ERR_EMS_G7B1A3_DROUGHT", 2),
    MC("During an epidemic, a business buying extra cleaning supplies is acting as a ____.", ["consumer", "producer only", "bank", "government"], "consumer",
      "Buying supplies makes the business a consumer of those goods.", "ERR_EMS_G7B1A3_BUYING", 2),
    MC("Which is a way a business might survive a disaster?", ["Having savings or insurance to recover", "Ignoring the damage", "Refusing to plan", "Spending all its money"], "Having savings or insurance to recover",
      "Savings and insurance help a business recover after a disaster.", "ERR_EMS_G7B1A3_SURVIVE", 2),
    MC("Why do disasters and epidemics affect both formal and informal businesses?", ["Both depend on customers, supplies and staff", "Only formal businesses have customers", "Informal businesses have no costs", "Neither needs people"], "Both depend on customers, supplies and staff",
      "All businesses rely on customers, supplies and workers, so both types are affected.", "ERR_EMS_G7B1A3_BOTH", 3),
    MC("A business that is both producing goods and buying supplies shows that a business can be ____.", ["both a producer and a consumer", "only a consumer", "only a producer", "neither"], "both a producer and a consumer",
      "Businesses produce goods and consume supplies, so they are both.", "ERR_EMS_G7B1A3_BOTHROLE", 2),
    TF("Businesses can be both producers and consumers.", "True",
      "They produce goods/services and consume supplies and resources.", "ERR_EMS_G7B1A3_TF1", 1),
    TF("Natural disasters can damage a business's stock and premises.", "True",
      "Floods, fires and storms can destroy stock and buildings.", "ERR_EMS_G7B1A3_TF2", 1),
    TF("A health epidemic always increases a business's profits.", "False",
      "Epidemics usually reduce customers and disrupt staff, often lowering profits.", "ERR_EMS_G7B1A3_TF3", 1),
    TF("Both formal and informal businesses can be affected by disasters.", "True",
      "Disasters affect all businesses that rely on customers, supplies and staff.", "ERR_EMS_G7B1A3_TF4", 1),
    CLOZE("When a business makes or supplies goods, it acts as a ____.", ["producer", "consumer", "bank", "tax"], "producer",
      "Supplying goods makes a business a producer.", "ERR_EMS_G7B1A3_CL1", 1),
    CLOZE("When a business buys supplies it needs, it acts as a ____.", ["consumer", "producer", "saver", "lender"], "consumer",
      "Buying supplies makes a business a consumer.", "ERR_EMS_G7B1A3_CL2", 1),
    CLOZE("A flood that destroys stock is an example of a natural ____.", ["disaster", "profit", "budget", "service"], "disaster",
      "Floods are natural disasters that can harm businesses.", "ERR_EMS_G7B1A3_CL3", 1),
    CLOZE("A widespread disease that affects many people is an ____.", ["epidemic", "asset", "income", "export"], "epidemic",
      "An epidemic is a widespread outbreak of disease.", "ERR_EMS_G7B1A3_CL4", 2),
    {
      question: "Sort each role into 'Business as producer' or 'Business as consumer'.",
      input_type: "sort-buckets",
      buckets: [{ id: "producer", label: "Business as producer" }, { id: "consumer", label: "Business as consumer" }],
      items: [
        { id: "i1", text: "Baking bread to sell", correct_bucket: "producer" },
        { id: "i2", text: "Buying flour and electricity", correct_bucket: "consumer" },
        { id: "i3", text: "Offering a repair service", correct_bucket: "producer" },
        { id: "i4", text: "Paying for cleaning supplies", correct_bucket: "consumer" },
      ],
      expected: "Baking and offering services are producing; buying flour and supplies is consuming.",
      pass_threshold: 0.75,
      memo: "Producing = making/supplying; consuming = buying what the business needs.", error_signals: ["ERR_EMS_G7B1A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the effect of a flood on a small shop in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A flood damages the shop and its stock" },
        { id: "b", text: "The shop cannot trade for a while" },
        { id: "c", text: "The shop loses income" },
        { id: "d", text: "The owner uses savings or insurance to recover" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Disaster → trading stops → income is lost → savings or insurance help recovery.",
      error_signals: ["ERR_EMS_G7B1A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── B2 · Term 3 — The entrepreneur ────────────────────────────────────────
  // A1 · Who is an entrepreneur?
  "EMS.G7.B2.A1": [
    MC("Who is an entrepreneur?", ["A person who starts and runs a business, taking risks for profit", "A person who only saves money", "A person who never works", "A government official"], "A person who starts and runs a business, taking risks for profit",
      "An entrepreneur spots an opportunity and takes a risk to start a business for profit.", "ERR_EMS_G7B2A1_DEF", 1),
    MC("Which is a characteristic of a good entrepreneur?", ["Willing to take calculated risks", "Afraid to ever try anything", "Never plans", "Gives up easily"], "Willing to take calculated risks",
      "Entrepreneurs take sensible, calculated risks to pursue opportunities.", "ERR_EMS_G7B2A1_RISK", 1),
    MC("An entrepreneur who keeps trying after a setback shows ____.", ["perseverance", "laziness", "fear", "carelessness"], "perseverance",
      "Perseverance — not giving up — is a key entrepreneurial trait.", "ERR_EMS_G7B2A1_PERSEVERE", 2),
    MC("Which characteristic helps an entrepreneur find new ideas?", ["Creativity", "Boredom", "Avoiding all thinking", "Copying nothing useful"], "Creativity",
      "Creativity helps entrepreneurs spot opportunities and new solutions.", "ERR_EMS_G7B2A1_CREATIVE", 1),
    MC("What does it mean that an entrepreneur takes a 'risk'?", ["They might lose money if the business fails", "They are guaranteed to succeed", "They never spend anything", "They avoid all decisions"], "They might lose money if the business fails",
      "Starting a business risks the owner's money and time if it does not succeed.", "ERR_EMS_G7B2A1_RISKMEAN", 2),
    MC("An entrepreneur is mainly motivated by the chance to ____.", ["make a profit", "lose money", "avoid customers", "stop working"], "make a profit",
      "Entrepreneurs aim to make a profit from their business.", "ERR_EMS_G7B2A1_PROFIT", 1),
    MC("Which person is acting like an entrepreneur?", ["A learner who starts selling cupcakes to make a profit", "A learner who only watches TV", "A person refusing to plan", "Someone avoiding all risk"], "A learner who starts selling cupcakes to make a profit",
      "Spotting a chance and starting a small business is entrepreneurial.", "ERR_EMS_G7B2A1_EXAMPLE", 1),
    MC("Good entrepreneurs are usually willing to ____.", ["work hard and learn from mistakes", "give up at the first problem", "ignore customers", "avoid all effort"], "work hard and learn from mistakes",
      "Hard work and learning from mistakes help entrepreneurs succeed.", "ERR_EMS_G7B2A1_HARDWORK", 2),
    MC("Which is NOT a typical characteristic of an entrepreneur?", ["Giving up at the smallest difficulty", "Confidence", "Creativity", "Willingness to take risks"], "Giving up at the smallest difficulty",
      "Giving up easily is the opposite of the perseverance entrepreneurs need.", "ERR_EMS_G7B2A1_NOT", 2),
    MC("Why is risk-taking part of being an entrepreneur?", ["Starting a business has no guarantee of success", "Success is always certain", "Risk means no effort", "Risk avoids profit"], "Starting a business has no guarantee of success",
      "Because outcomes are uncertain, entrepreneurs accept the risk of loss for the chance of profit.", "ERR_EMS_G7B2A1_WHYRISK", 3),
    TF("An entrepreneur starts and runs a business, taking risks to make a profit.", "True",
      "That is the core definition of an entrepreneur.", "ERR_EMS_G7B2A1_TF1", 1),
    TF("Entrepreneurs never take any risks.", "False",
      "Taking calculated risks is a key part of being an entrepreneur.", "ERR_EMS_G7B2A1_TF2", 1),
    TF("Creativity and perseverance are useful entrepreneurial characteristics.", "True",
      "Creativity finds ideas and perseverance keeps the entrepreneur going.", "ERR_EMS_G7B2A1_TF3", 1),
    TF("Entrepreneurs usually hope to make a profit.", "True",
      "Profit is a main motivation for entrepreneurs.", "ERR_EMS_G7B2A1_TF4", 1),
    CLOZE("A person who starts a business and takes risks for profit is an ____.", ["entrepreneur", "employee", "customer", "official"], "entrepreneur",
      "An entrepreneur starts and runs a business, taking risks for profit.", "ERR_EMS_G7B2A1_CL1", 1),
    CLOZE("Not giving up when things get hard shows ____.", ["perseverance", "laziness", "fear", "boredom"], "perseverance",
      "Perseverance is sticking with it through difficulties.", "ERR_EMS_G7B2A1_CL2", 2),
    CLOZE("Coming up with fresh ideas shows ____.", ["creativity", "carelessness", "fear", "doubt"], "creativity",
      "Creativity is the ability to think of new ideas.", "ERR_EMS_G7B2A1_CL3", 1),
    CLOZE("Entrepreneurs accept the ____ that a business might not succeed.", ["risk", "profit", "tax", "salary"], "risk",
      "Risk is the chance of loss entrepreneurs accept.", "ERR_EMS_G7B2A1_CL4", 2),
    {
      question: "Sort each trait into 'Helps an entrepreneur' or 'Holds them back'.",
      input_type: "sort-buckets",
      buckets: [{ id: "helps", label: "Helps an entrepreneur" }, { id: "holds", label: "Holds them back" }],
      items: [
        { id: "i1", text: "Creativity", correct_bucket: "helps" },
        { id: "i2", text: "Giving up easily", correct_bucket: "holds" },
        { id: "i3", text: "Willingness to take calculated risks", correct_bucket: "helps" },
        { id: "i4", text: "Fear of trying anything new", correct_bucket: "holds" },
      ],
      expected: "Creativity and risk-taking help; giving up and fear hold an entrepreneur back.",
      pass_threshold: 0.75,
      memo: "Positive traits: creativity, perseverance, risk-taking. Negative: giving up, fear of trying.", error_signals: ["ERR_EMS_G7B2A1_SORT"], difficulty: 1,
    },
    {
      question: "Put the start of an entrepreneur's journey in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Spot a need or opportunity" },
        { id: "b", text: "Come up with a business idea" },
        { id: "c", text: "Take a risk and start the business" },
        { id: "d", text: "Work hard to make a profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "See an opportunity, form an idea, take the risk to start, then work for profit.",
      error_signals: ["ERR_EMS_G7B2A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Entrepreneurial skills and actions
  "EMS.G7.B2.A2": [
    MC("Which is an important entrepreneurial skill?", ["Planning and organising", "Avoiding all decisions", "Ignoring customers", "Refusing to learn"], "Planning and organising",
      "Planning and organising help an entrepreneur run a business well.", "ERR_EMS_G7B2A2_PLAN", 1),
    MC("The entrepreneurial action of getting supplies or stock is called ____.", ["buying", "selling", "saving", "taxing"], "buying",
      "Buying inputs and stock is a key entrepreneurial action.", "ERR_EMS_G7B2A2_BUY", 1),
    MC("Offering goods to customers in exchange for money is called ____.", ["selling", "buying", "producing", "saving"], "selling",
      "Selling exchanges goods for money with customers.", "ERR_EMS_G7B2A2_SELL", 1),
    MC("Making the product or service the business offers is called ____.", ["producing", "buying", "taxing", "saving"], "producing",
      "Producing is creating the goods or services to sell.", "ERR_EMS_G7B2A2_PRODUCE", 1),
    MC("The aim of buying, producing and selling well is to ____.", ["make a profit", "make a loss", "avoid customers", "stop trading"], "make a profit",
      "Done well, these actions help the entrepreneur make a profit.", "ERR_EMS_G7B2A2_PROFIT", 2),
    MC("Which skill helps an entrepreneur deal well with customers?", ["Good communication", "Rudeness", "Ignoring people", "Silence"], "Good communication",
      "Communication helps entrepreneurs understand and serve customers.", "ERR_EMS_G7B2A2_COMM", 1),
    MC("Managing money carefully in a business shows ____ skills.", ["financial", "cooking", "driving", "sporting"], "financial",
      "Handling money well is a financial skill entrepreneurs need.", "ERR_EMS_G7B2A2_FIN", 2),
    MC("An entrepreneur buys cheap, produces well and sells at a fair price. This helps them ____.", ["earn a profit", "guarantee a loss", "avoid all sales", "pay no costs"], "earn a profit",
      "Buying low, producing efficiently and selling well supports profit.", "ERR_EMS_G7B2A2_CHAIN", 2),
    MC("Which is an entrepreneurial action, not just a skill?", ["Selling products to customers", "Being confident", "Being creative", "Being patient"], "Selling products to customers",
      "Selling is an action; confidence, creativity and patience are skills/traits.", "ERR_EMS_G7B2A2_ACTION", 2),
    MC("Why does an entrepreneur need both skills and actions?", ["Skills guide the actions of buying, producing and selling", "Skills replace all actions", "Actions need no skills", "Neither matters"], "Skills guide the actions of buying, producing and selling",
      "Skills like planning and communication guide the key actions for profit.", "ERR_EMS_G7B2A2_WHY", 3),
    TF("Buying, producing and selling are key entrepreneurial actions.", "True",
      "These actions move the business towards making a profit.", "ERR_EMS_G7B2A2_TF1", 1),
    TF("Good communication is a useful entrepreneurial skill.", "True",
      "Communicating well helps entrepreneurs serve customers and lead staff.", "ERR_EMS_G7B2A2_TF2", 1),
    TF("An entrepreneur sells goods in order to make a loss.", "False",
      "Entrepreneurs sell to make a profit, not a loss.", "ERR_EMS_G7B2A2_TF3", 1),
    TF("Planning and managing money are important entrepreneurial skills.", "True",
      "Planning and financial management help a business run well.", "ERR_EMS_G7B2A2_TF4", 1),
    CLOZE("Getting stock or supplies is the action of ____.", ["buying", "selling", "saving", "taxing"], "buying",
      "Buying brings in the inputs the business needs.", "ERR_EMS_G7B2A2_CL1", 1),
    CLOZE("Exchanging goods for money with customers is ____.", ["selling", "buying", "producing", "saving"], "selling",
      "Selling exchanges goods for money.", "ERR_EMS_G7B2A2_CL2", 1),
    CLOZE("Making the goods or services to offer is ____.", ["producing", "buying", "taxing", "owing"], "producing",
      "Producing creates the product or service.", "ERR_EMS_G7B2A2_CL3", 1),
    CLOZE("Buying, producing and selling well help the entrepreneur make a ____.", ["profit", "loss", "tax", "debt"], "profit",
      "These actions aim at making a profit.", "ERR_EMS_G7B2A2_CL4", 2),
    {
      question: "Sort each into 'Skill' or 'Action' of an entrepreneur.",
      input_type: "sort-buckets",
      buckets: [{ id: "skill", label: "Skill" }, { id: "action", label: "Action" }],
      items: [
        { id: "i1", text: "Communicating well", correct_bucket: "skill" },
        { id: "i2", text: "Buying stock", correct_bucket: "action" },
        { id: "i3", text: "Planning and organising", correct_bucket: "skill" },
        { id: "i4", text: "Selling to customers", correct_bucket: "action" },
      ],
      expected: "Communicating and planning are skills; buying and selling are actions.",
      pass_threshold: 0.75,
      memo: "Skills (planning, communication) guide the actions (buying, producing, selling).", error_signals: ["ERR_EMS_G7B2A2_SORT"], difficulty: 2,
    },
    {
      question: "Put an entrepreneur's actions in the usual order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Buy materials or stock" },
        { id: "b", text: "Produce the goods or service" },
        { id: "c", text: "Sell to customers" },
        { id: "d", text: "Make a profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Buy, produce, sell, and profit — the core actions of an entrepreneur.",
      error_signals: ["ERR_EMS_G7B2A2_SEQ"], difficulty: 1,
    },
  ],

  // ─── B3 · Term 3 — Starting a business ─────────────────────────────────────
  // A1 · SWOT and setting goals
  "EMS.G7.B3.A1": [
    MC("What does the 'S' in SWOT stand for?", ["Strengths", "Sales", "Savings", "Services"], "Strengths",
      "In SWOT, S is Strengths — what the business does well.", "ERR_EMS_G7B3A1_S", 1),
    MC("What does the 'W' in SWOT stand for?", ["Weaknesses", "Wages", "Wants", "Wealth"], "Weaknesses",
      "W is Weaknesses — areas where the business is not strong.", "ERR_EMS_G7B3A1_W", 1),
    MC("What does the 'O' in SWOT stand for?", ["Opportunities", "Orders", "Owners", "Outputs"], "Opportunities",
      "O is Opportunities — outside chances the business could use.", "ERR_EMS_G7B3A1_O", 1),
    MC("What does the 'T' in SWOT stand for?", ["Threats", "Taxes", "Trades", "Tools"], "Threats",
      "T is Threats — outside dangers that could harm the business.", "ERR_EMS_G7B3A1_T", 1),
    MC("Strengths and weaknesses are usually ____ the business.", ["inside", "outside", "far from", "unrelated to"], "inside",
      "Strengths and weaknesses are internal factors, inside the business.", "ERR_EMS_G7B3A1_INSIDE", 2),
    MC("Opportunities and threats are usually ____ the business.", ["outside", "inside", "owned by", "hidden in"], "outside",
      "Opportunities and threats are external factors, outside the business.", "ERR_EMS_G7B3A1_OUTSIDE", 2),
    MC("Why do entrepreneurs set goals?", ["To give the business clear targets to work towards", "To waste time", "To avoid planning", "To confuse staff"], "To give the business clear targets to work towards",
      "Goals set clear targets that guide the business's efforts.", "ERR_EMS_G7B3A1_GOALS", 1),
    MC("A good goal should be ____.", ["clear and achievable", "vague and impossible", "secret and random", "never measured"], "clear and achievable",
      "Good goals are clear and realistic so progress can be measured.", "ERR_EMS_G7B3A1_GOOD", 2),
    MC("'A skilled baker' would appear under which part of a bakery's SWOT?", ["Strengths", "Threats", "Opportunities", "Taxes"], "Strengths",
      "A skilled baker is an internal advantage — a strength.", "ERR_EMS_G7B3A1_STRENGTH_EX", 2),
    MC("'A new competitor opening nearby' is an example of a ____.", ["threat", "strength", "opportunity", "goal"], "threat",
      "A new competitor is an external danger — a threat.", "ERR_EMS_G7B3A1_THREAT_EX", 2),
    TF("SWOT stands for Strengths, Weaknesses, Opportunities and Threats.", "True",
      "SWOT analyses internal strengths/weaknesses and external opportunities/threats.", "ERR_EMS_G7B3A1_TF1", 1),
    TF("Strengths and weaknesses are inside the business.", "True",
      "They are internal factors the business can control.", "ERR_EMS_G7B3A1_TF2", 1),
    TF("Setting clear goals helps a business know what to work towards.", "True",
      "Goals provide direction and targets.", "ERR_EMS_G7B3A1_TF3", 1),
    TF("A threat is something good that helps the business grow.", "False",
      "A threat is an outside danger; an opportunity is the helpful outside factor.", "ERR_EMS_G7B3A1_TF4", 2),
    CLOZE("In SWOT, S stands for ____.", ["strengths", "sales", "savings", "services"], "strengths",
      "S is Strengths.", "ERR_EMS_G7B3A1_CL1", 1),
    CLOZE("In SWOT, T stands for ____.", ["threats", "taxes", "trades", "tools"], "threats",
      "T is Threats.", "ERR_EMS_G7B3A1_CL2", 1),
    CLOZE("Opportunities and threats come from ____ the business.", ["outside", "inside", "within", "below"], "outside",
      "They are external factors.", "ERR_EMS_G7B3A1_CL3", 2),
    CLOZE("A clear, achievable target a business works towards is a ____.", ["goal", "threat", "tax", "loss"], "goal",
      "Goals are targets the business aims to reach.", "ERR_EMS_G7B3A1_CL4", 1),
    {
      question: "Sort each factor into the correct SWOT box.",
      input_type: "sort-buckets",
      buckets: [{ id: "strength", label: "Strength (inside, good)" }, { id: "weakness", label: "Weakness (inside, bad)" }, { id: "opportunity", label: "Opportunity (outside, good)" }, { id: "threat", label: "Threat (outside, bad)" }],
      items: [
        { id: "i1", text: "A loyal team of skilled staff", correct_bucket: "strength" },
        { id: "i2", text: "Old, broken equipment", correct_bucket: "weakness" },
        { id: "i3", text: "A growing demand for the product", correct_bucket: "opportunity" },
        { id: "i4", text: "A new competing shop nearby", correct_bucket: "threat" },
      ],
      expected: "Skilled staff = strength; broken equipment = weakness; growing demand = opportunity; new competitor = threat.",
      pass_threshold: 0.75,
      memo: "Inside-good = strength; inside-bad = weakness; outside-good = opportunity; outside-bad = threat.", error_signals: ["ERR_EMS_G7B3A1_SORT"], difficulty: 3,
    },
    {
      question: "Put the steps of planning with SWOT and goals in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "List the business's strengths and weaknesses" },
        { id: "b", text: "List outside opportunities and threats" },
        { id: "c", text: "Use the SWOT to set clear goals" },
        { id: "d", text: "Work towards achieving the goals" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Analyse inside factors, then outside factors, set goals from the SWOT, then pursue them.",
      error_signals: ["ERR_EMS_G7B3A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Advertising
  "EMS.G7.B3.A2": [
    MC("What is advertising?", ["Telling people about a product to encourage them to buy", "Hiding a product from customers", "Refusing to sell anything", "Paying tax"], "Telling people about a product to encourage them to buy",
      "Advertising informs and persuades people to buy a product or service.", "ERR_EMS_G7B3A2_DEF", 1),
    MC("Which is an advertising medium?", ["A poster", "A bank loan", "A tax form", "A budget"], "A poster",
      "Posters are an advertising medium; loans, tax forms and budgets are not.", "ERR_EMS_G7B3A2_MEDIUM", 1),
    MC("Why do businesses advertise?", ["To attract customers and increase sales", "To lose customers", "To hide their products", "To pay more tax"], "To attract customers and increase sales",
      "Advertising aims to draw customers and boost sales.", "ERR_EMS_G7B3A2_WHY", 1),
    MC("Which of these is an advertising medium used today?", ["Social media", "A savings account", "A trial balance", "A stokvel"], "Social media",
      "Social media is a common modern advertising medium.", "ERR_EMS_G7B3A2_SOCIAL", 1),
    MC("A good advert should be ____.", ["clear and honest", "confusing and false", "secret", "boring on purpose"], "clear and honest",
      "Good advertising is clear, honest and appealing to customers.", "ERR_EMS_G7B3A2_GOOD", 2),
    MC("Which is a principle of good advertising?", ["Reaching the right audience", "Misleading customers", "Hiding the price always", "Annoying everyone"], "Reaching the right audience",
      "Good advertising targets the right audience with a clear message.", "ERR_EMS_G7B3A2_PRINCIPLE", 2),
    MC("Advertising on the radio reaches people who ____.", ["are listening to that station", "never use any media", "only read books", "avoid all sound"], "are listening to that station",
      "Radio adverts reach the station's listeners.", "ERR_EMS_G7B3A2_RADIO", 1),
    MC("Why should an advert be honest?", ["So customers trust the business", "So customers feel cheated", "To break the law", "To lose sales"], "So customers trust the business",
      "Honest adverts build trust and a good reputation.", "ERR_EMS_G7B3A2_HONEST", 2),
    MC("A business selling to teenagers might best advertise on ____.", ["social media", "a notice in a retirement home", "a farming newsletter", "a tax website"], "social media",
      "Choosing media that the target audience uses (social media for teens) is effective.", "ERR_EMS_G7B3A2_TARGET", 3),
    MC("Which is a benefit of effective advertising for a small business?", ["More people learn about the product", "Fewer people know the product", "Sales always fall", "Costs are hidden"], "More people learn about the product",
      "Effective advertising spreads awareness, which can grow sales.", "ERR_EMS_G7B3A2_BENEFIT", 1),
    TF("Advertising tells people about a product to encourage them to buy.", "True",
      "Advertising informs and persuades potential customers.", "ERR_EMS_G7B3A2_TF1", 1),
    TF("Posters, radio and social media are advertising media.", "True",
      "These are all channels used to advertise.", "ERR_EMS_G7B3A2_TF2", 1),
    TF("A good advert should mislead customers.", "False",
      "Good advertising is honest; misleading customers harms trust and may be illegal.", "ERR_EMS_G7B3A2_TF3", 1),
    TF("Choosing the right audience makes advertising more effective.", "True",
      "Reaching the people most likely to buy improves results.", "ERR_EMS_G7B3A2_TF4", 2),
    CLOZE("Telling people about a product to get them to buy is called ____.", ["advertising", "saving", "taxing", "budgeting"], "advertising",
      "Advertising promotes a product to customers.", "ERR_EMS_G7B3A2_CL1", 1),
    CLOZE("A poster or radio advert is an advertising ____.", ["medium", "tax", "loan", "budget"], "medium",
      "A medium is a channel used to carry the advert.", "ERR_EMS_G7B3A2_CL2", 1),
    CLOZE("Good adverts should be clear and ____.", ["honest", "false", "secret", "confusing"], "honest",
      "Honesty builds customer trust.", "ERR_EMS_G7B3A2_CL3", 2),
    CLOZE("Reaching the right ____ is a principle of good advertising.", ["audience", "tax", "loss", "debt"], "audience",
      "Targeting the right audience makes advertising effective.", "ERR_EMS_G7B3A2_CL4", 2),
    {
      question: "Sort each into 'Advertising medium' or 'Not advertising'.",
      input_type: "sort-buckets",
      buckets: [{ id: "medium", label: "Advertising medium" }, { id: "not", label: "Not advertising" }],
      items: [
        { id: "i1", text: "A street poster", correct_bucket: "medium" },
        { id: "i2", text: "A bank statement", correct_bucket: "not" },
        { id: "i3", text: "A social media post promoting a sale", correct_bucket: "medium" },
        { id: "i4", text: "A trial balance", correct_bucket: "not" },
      ],
      expected: "Posters and social media posts are advertising media; bank statements and trial balances are not.",
      pass_threshold: 0.75,
      memo: "Advertising media spread a sales message; financial records do not.", error_signals: ["ERR_EMS_G7B3A2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of advertising a school market stall in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Decide who your customers are" },
        { id: "b", text: "Choose a suitable medium (e.g. posters)" },
        { id: "c", text: "Create a clear, honest advert" },
        { id: "d", text: "Share it so customers come to buy" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Know your audience, choose the medium, make a clear honest advert, then share it.",
      error_signals: ["ERR_EMS_G7B3A2_SEQ"], difficulty: 2,
    },
  ],

  // A3 · Simple cost calculation
  "EMS.G7.B3.A3": [
    MC("What is a fixed cost?", ["A cost that stays the same no matter how much you make", "A cost that changes with each item", "Money you earn", "A type of profit"], "A cost that stays the same no matter how much you make",
      "Fixed costs (like rent) stay the same whether you produce a little or a lot.", "ERR_EMS_G7B3A3_FIXED", 1),
    MC("What is a variable cost?", ["A cost that changes with how much you produce", "A cost that never changes", "Income from sales", "A bank loan"], "A cost that changes with how much you produce",
      "Variable costs (like ingredients) rise as you make more.", "ERR_EMS_G7B3A3_VAR", 1),
    MC("Which is a fixed cost for a stall?", ["The rent for the table", "The flour used per cake", "The icing per cake", "The wrapping per item"], "The rent for the table",
      "Stall rent is fixed; ingredients and wrapping change with quantity.", "ERR_EMS_G7B3A3_FIXED_EX", 2),
    MC("Which is a variable cost for baking cupcakes?", ["Ingredients for each cupcake", "Monthly oven hire", "The fixed table rent", "A once-off licence fee"], "Ingredients for each cupcake",
      "Ingredients cost more as you bake more — a variable cost.", "ERR_EMS_G7B3A3_VAR_EX", 2),
    MC("Selling price should usually be set ____ the cost of making the item.", ["higher than", "lower than", "equal to", "unrelated to"], "higher than",
      "To make a profit, the selling price must be above the cost to make it.", "ERR_EMS_G7B3A3_PRICE", 2),
    MC("If a cupcake costs R5 to make and you sell it for R8, the profit per cupcake is ____.", ["R3", "R13", "R5", "R8"], "R3",
      "Profit per item = selling price − cost = R8 − R5 = R3.", "ERR_EMS_G7B3A3_CALC", 2),
    MC("If you sell an item for less than it costs to make, you will make a ____.", ["loss", "profit", "saving", "tax"], "loss",
      "Selling below cost means a loss on each item.", "ERR_EMS_G7B3A3_LOSS", 2),
    MC("Total cost is usually fixed costs ____ variable costs.", ["plus", "minus", "times only", "divided by"], "plus",
      "Total cost = fixed costs + variable costs.", "ERR_EMS_G7B3A3_TOTAL", 2),
    MC("Why must you know your costs before setting a price?", ["To make sure the price covers costs and leaves a profit", "To set the price randomly", "To always sell at a loss", "To ignore the customer"], "To make sure the price covers costs and leaves a profit",
      "Knowing costs ensures the price covers them and leaves a profit.", "ERR_EMS_G7B3A3_WHY", 2),
    MC("A stall pays R50 rent (fixed) and R2 per item (variable). Making 20 items costs ____ in total.", ["R90", "R50", "R40", "R52"], "R90",
      "Total = R50 + (R2 × 20) = R50 + R40 = R90.", "ERR_EMS_G7B3A3_TOTALCALC", 3),
    TF("A fixed cost stays the same regardless of how many items you make.", "True",
      "Fixed costs do not change with output.", "ERR_EMS_G7B3A3_TF1", 1),
    TF("A variable cost changes as you produce more.", "True",
      "Variable costs rise with more production.", "ERR_EMS_G7B3A3_TF2", 1),
    TF("To make a profit, sell each item for less than it costs to make.", "False",
      "You must sell for more than the cost to make a profit.", "ERR_EMS_G7B3A3_TF3", 1),
    TF("Total cost is the sum of fixed and variable costs.", "True",
      "Total cost = fixed + variable costs.", "ERR_EMS_G7B3A3_TF4", 2),
    CLOZE("A cost that does not change with output, like rent, is a ____ cost.", ["fixed", "variable", "selling", "profit"], "fixed",
      "Fixed costs stay the same regardless of how much you make.", "ERR_EMS_G7B3A3_CL1", 1),
    CLOZE("A cost that rises as you make more, like ingredients, is a ____ cost.", ["variable", "fixed", "selling", "saving"], "variable",
      "Variable costs change with the amount produced.", "ERR_EMS_G7B3A3_CL2", 1),
    CLOZE("Profit per item = selling price ____ cost price.", ["minus", "plus", "times", "divided by"], "minus",
      "Profit per item = selling price − cost.", "ERR_EMS_G7B3A3_CL3", 2),
    CLOZE("To earn a profit, the selling price must be ____ than the cost.", ["higher", "lower", "equal", "smaller"], "higher",
      "Selling above cost produces a profit.", "ERR_EMS_G7B3A3_CL4", 2),
    {
      question: "Sort each cost into 'Fixed cost' or 'Variable cost' for a cupcake stall.",
      input_type: "sort-buckets",
      buckets: [{ id: "fixed", label: "Fixed cost" }, { id: "variable", label: "Variable cost" }],
      items: [
        { id: "i1", text: "Monthly stall rent", correct_bucket: "fixed" },
        { id: "i2", text: "Flour and sugar per cupcake", correct_bucket: "variable" },
        { id: "i3", text: "A once-off table fee", correct_bucket: "fixed" },
        { id: "i4", text: "Paper cases per cupcake", correct_bucket: "variable" },
      ],
      expected: "Rent and the table fee are fixed; ingredients and paper cases are variable.",
      pass_threshold: 0.75,
      memo: "Fixed costs stay the same; variable costs grow with each item made.", error_signals: ["ERR_EMS_G7B3A3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of pricing a product in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Add up fixed and variable costs" },
        { id: "b", text: "Work out the cost to make one item" },
        { id: "c", text: "Add a mark-up for profit" },
        { id: "d", text: "Set the selling price" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Total the costs, find the cost per item, add a profit mark-up, then set the price.",
      error_signals: ["ERR_EMS_G7B3A3_SEQ"], difficulty: 2,
    },
  ],

  // ─── B4 · Term 3 — Entrepreneur's Day ──────────────────────────────────────
  // A1 · Hosting Entrepreneur's Day
  "EMS.G7.B4.A1": [
    MC("What is the main aim of an Entrepreneur's Day at school?", ["To plan, make and sell products like real entrepreneurs", "To avoid all selling", "To waste a school day", "To pay tax"], "To plan, make and sell products like real entrepreneurs",
      "Entrepreneur's Day lets learners practise running a small business for real.", "ERR_EMS_G7B4A1_AIM", 1),
    MC("What should you prepare before Entrepreneur's Day?", ["A plan and a budget", "Nothing at all", "Only a nap", "A tax return"], "A plan and a budget",
      "Planning and budgeting are key preparation steps for the event.", "ERR_EMS_G7B4A1_PREP", 1),
    MC("Why make a budget for Entrepreneur's Day?", ["To plan income and costs and aim for a profit", "To overspend", "To ignore costs", "To lose money"], "To plan income and costs and aim for a profit",
      "A budget helps you plan costs and price so you can make a profit.", "ERR_EMS_G7B4A1_BUDGET", 2),
    MC("Using recycled materials for your stall can help by ____.", ["lowering your costs", "raising your costs", "wasting money", "breaking the law"], "lowering your costs",
      "Recycled materials are often cheaper, reducing costs.", "ERR_EMS_G7B4A1_RECYCLE", 2),
    MC("A good product to sell on the day is one that ____.", ["customers want and you can make affordably", "no one wants", "costs more than it sells for", "cannot be made"], "customers want and you can make affordably",
      "Choose something in demand that you can make at a cost below its selling price.", "ERR_EMS_G7B4A1_PRODUCT", 2),
    MC("Which is part of planning your stall?", ["Deciding your product and price", "Refusing to plan", "Ignoring customers", "Hiding your stall"], "Deciding your product and price",
      "Planning includes choosing the product, price and how to attract customers.", "ERR_EMS_G7B4A1_PLAN", 1),
    MC("Advertising your stall helps to ____.", ["attract customers", "scare customers away", "hide your products", "lower interest"], "attract customers",
      "Advertising draws customers to your stall.", "ERR_EMS_G7B4A1_ADVERT", 1),
    MC("If your costs are R40 and you sell goods for R100, your profit is ____.", ["R60", "R140", "R40", "R100"], "R60",
      "Profit = income − costs = R100 − R40 = R60.", "ERR_EMS_G7B4A1_PROFIT", 2),
    MC("Why use a budget and recycled materials together?", ["To keep costs low and increase profit", "To spend as much as possible", "To make a guaranteed loss", "To avoid selling"], "To keep costs low and increase profit",
      "Low costs from budgeting and recycling leave more room for profit.", "ERR_EMS_G7B4A1_COMBO", 3),
    MC("Good customer service on the day means ____.", ["being friendly and helpful to buyers", "ignoring customers", "being rude", "hiding prices"], "being friendly and helpful to buyers",
      "Friendly, helpful service encourages people to buy.", "ERR_EMS_G7B4A1_SERVICE", 1),
    TF("Entrepreneur's Day lets learners practise running a real small business.", "True",
      "It is hands-on practice in planning, making and selling.", "ERR_EMS_G7B4A1_TF1", 1),
    TF("A budget helps you plan your costs and aim for a profit.", "True",
      "Budgets plan income and costs to support a profit.", "ERR_EMS_G7B4A1_TF2", 1),
    TF("Using recycled materials usually increases your costs.", "False",
      "Recycled materials usually lower costs, not raise them.", "ERR_EMS_G7B4A1_TF3", 1),
    TF("Advertising your stall can help attract more customers.", "True",
      "Promotion brings more buyers to your stall.", "ERR_EMS_G7B4A1_TF4", 1),
    CLOZE("Before the day, you should prepare a plan and a ____.", ["budget", "loss", "tax", "loan"], "budget",
      "A budget is key preparation for the event.", "ERR_EMS_G7B4A1_CL1", 1),
    CLOZE("Using ____ materials can lower the cost of your stall.", ["recycled", "expensive", "imported", "wasted"], "recycled",
      "Recycled materials are often cheaper.", "ERR_EMS_G7B4A1_CL2", 1),
    CLOZE("Telling others about your stall is called ____.", ["advertising", "saving", "taxing", "budgeting"], "advertising",
      "Advertising attracts customers to your stall.", "ERR_EMS_G7B4A1_CL3", 1),
    CLOZE("Profit on the day = income ____ costs.", ["minus", "plus", "times", "divided by"], "minus",
      "Profit = income − costs.", "ERR_EMS_G7B4A1_CL4", 2),
    {
      question: "Sort each task into 'Before the day' or 'On the day'.",
      input_type: "sort-buckets",
      buckets: [{ id: "before", label: "Before the day" }, { id: "onday", label: "On the day" }],
      items: [
        { id: "i1", text: "Write a plan and budget", correct_bucket: "before" },
        { id: "i2", text: "Sell to customers at the stall", correct_bucket: "onday" },
        { id: "i3", text: "Make the products", correct_bucket: "before" },
        { id: "i4", text: "Give friendly customer service", correct_bucket: "onday" },
      ],
      expected: "Planning, budgeting and making products happen before; selling and service happen on the day.",
      pass_threshold: 0.75,
      memo: "Prepare (plan, budget, make) before; sell and serve customers on the day.", error_signals: ["ERR_EMS_G7B4A1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of hosting an Entrepreneur's Day stall in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Plan your product and budget" },
        { id: "b", text: "Make your products (using recycled materials where possible)" },
        { id: "c", text: "Advertise your stall" },
        { id: "d", text: "Sell on the day and work out your profit" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Plan and budget, make products, advertise, then sell and calculate profit.",
      error_signals: ["ERR_EMS_G7B4A1_SEQ"], difficulty: 2,
    },
  ],

  // A2 · Income and expenditure statement
  "EMS.G7.B4.A2": [
    MC("What does an income and expenditure statement show?", ["The money that came in and went out, and the profit or loss", "Only what you own", "Only your wants", "A bank's interest rates"], "The money that came in and went out, and the profit or loss",
      "It lists income and expenses to show whether you made a profit or a loss.", "ERR_EMS_G7B4A2_DEF", 1),
    MC("On the statement, money from sales is recorded as ____.", ["income", "expenditure", "a loss", "a liability"], "income",
      "Sales bring money in, recorded as income.", "ERR_EMS_G7B4A2_INCOME", 1),
    MC("On the statement, money spent on materials is recorded as ____.", ["expenditure", "income", "profit", "an asset"], "expenditure",
      "Money paid out, like for materials, is expenditure.", "ERR_EMS_G7B4A2_EXP", 1),
    MC("How do you find the profit on the statement?", ["Income minus expenditure", "Expenditure minus income", "Income plus expenditure", "Income times expenditure"], "Income minus expenditure",
      "Profit = total income − total expenditure.", "ERR_EMS_G7B4A2_PROFIT", 2),
    MC("If income is R300 and expenditure is R200, the result is a ____.", ["profit of R100", "loss of R100", "profit of R500", "loss of R200"], "profit of R100",
      "R300 − R200 = R100 profit.", "ERR_EMS_G7B4A2_CALC", 2),
    MC("If income is R150 and expenditure is R220, the result is a ____.", ["loss of R70", "profit of R70", "profit of R370", "loss of R150"], "loss of R70",
      "Expenditure (R220) exceeds income (R150), so there is a R70 loss.", "ERR_EMS_G7B4A2_LOSS", 2),
    MC("Why prepare an income and expenditure statement after Entrepreneur's Day?", ["To see if the stall made a profit or loss", "To hide the results", "To avoid learning", "To pay more tax"], "To see if the stall made a profit or loss",
      "The statement shows the real result of the day's trading.", "ERR_EMS_G7B4A2_WHY", 1),
    MC("Which item belongs under expenditure?", ["Money spent on packaging", "Money received from a customer", "Profit earned", "Sales income"], "Money spent on packaging",
      "Packaging is a cost paid out — expenditure.", "ERR_EMS_G7B4A2_EXP_EX", 1),
    MC("A statement shows income R500 and expenditure R500. The result is ____.", ["break-even (no profit, no loss)", "a big profit", "a big loss", "impossible"], "break-even (no profit, no loss)",
      "Equal income and expenditure means breaking even.", "ERR_EMS_G7B4A2_BREAKEVEN", 3),
    MC("What can you learn from a loss on the statement?", ["Costs were higher than income, so adjust next time", "Nothing useful", "To stop recording", "To spend even more"], "Costs were higher than income, so adjust next time",
      "A loss shows costs beat income — useful feedback to improve next time.", "ERR_EMS_G7B4A2_LEARN", 2),
    TF("An income and expenditure statement shows profit or loss.", "True",
      "It compares income and expenditure to reveal profit or loss.", "ERR_EMS_G7B4A2_TF1", 1),
    TF("Profit is income minus expenditure.", "True",
      "Profit = income − expenditure.", "ERR_EMS_G7B4A2_TF2", 1),
    TF("Money spent on materials is recorded as income.", "False",
      "Money spent is expenditure, not income.", "ERR_EMS_G7B4A2_TF3", 1),
    TF("If expenditure is greater than income, the result is a loss.", "True",
      "When you spend more than you earn, you make a loss.", "ERR_EMS_G7B4A2_TF4", 1),
    CLOZE("A statement showing money in, money out and the profit or loss is an income and ____ statement.", ["expenditure", "savings", "tax", "asset"], "expenditure",
      "It is an income and expenditure statement.", "ERR_EMS_G7B4A2_CL1", 1),
    CLOZE("Money received from sales is recorded as ____.", ["income", "expenditure", "loss", "debt"], "income",
      "Sales are income.", "ERR_EMS_G7B4A2_CL2", 1),
    CLOZE("Profit = income ____ expenditure.", ["minus", "plus", "times", "divided by"], "minus",
      "Profit = income − expenditure.", "ERR_EMS_G7B4A2_CL3", 2),
    CLOZE("When expenditure is more than income, you make a ____.", ["loss", "profit", "saving", "gain"], "loss",
      "Spending more than you earn is a loss.", "ERR_EMS_G7B4A2_CL4", 2),
    {
      question: "Sort each item into 'Income' or 'Expenditure' on the statement.",
      input_type: "sort-buckets",
      buckets: [{ id: "income", label: "Income" }, { id: "expenditure", label: "Expenditure" }],
      items: [
        { id: "i1", text: "Cash from selling cupcakes", correct_bucket: "income" },
        { id: "i2", text: "Money spent on ingredients", correct_bucket: "expenditure" },
        { id: "i3", text: "Money received at the stall", correct_bucket: "income" },
        { id: "i4", text: "Money spent on packaging", correct_bucket: "expenditure" },
      ],
      expected: "Cash from sales is income; money spent on ingredients and packaging is expenditure.",
      pass_threshold: 0.75,
      memo: "Income is money received; expenditure is money paid out.", error_signals: ["ERR_EMS_G7B4A2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of drawing up the statement in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Add up all income from sales" },
        { id: "b", text: "Add up all expenditure (costs)" },
        { id: "c", text: "Subtract expenditure from income" },
        { id: "d", text: "Record the profit or loss" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Total income, total expenditure, subtract, then record profit or loss.",
      error_signals: ["ERR_EMS_G7B4A2_SEQ"], difficulty: 2,
    },
  ],
};

export default G7C;
