// ─── Life Orientation SP — Grade 9 authored pools (part 1: DS · HE · CR) ─────
//
// Keyed by skill id → question array. Refs auto-assigned by the generator.
// Tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
// Each pool holds exactly 20 items (18 simple + 1 sort + 1 sequence).
//
// CAPS Grade 9 topics here:
//   Development of the self in society · Health, social & environmental
//   responsibility · Constitutional rights & responsibilities

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9 = {
  // ════════════════ DEVELOPMENT OF THE SELF IN SOCIETY (Term 1) ════════════════
  // DS.A1 · Goal-setting and lifestyle choices
  "LO.G9.DS.A1": [
    MC("What is goal-setting?",
      ["Deciding what you want to achieve and planning how", "Waiting for things to happen", "Copying others' plans", "Avoiding all decisions"], "Deciding what you want to achieve and planning how",
      "Goal-setting means deciding what you want to achieve and planning how to get there.", "ERR_LO_G9DSA1_DEF", 1),
    TF("A personal lifestyle choice is a decision about how you live, like diet or activity.", "True",
      "Lifestyle choices are personal decisions about how you live — diet, activity, habits and friends.", "ERR_LO_G9DSA1_LIFESTYLE", 1),
    MC("Which can INFLUENCE personal lifestyle choices?",
      ["Media, family, friends, culture and community", "Only the weather", "Shoe size", "The school bell"], "Media, family, friends, culture and community",
      "Lifestyle choices are influenced by media, environment, friends, family, culture and community.", "ERR_LO_G9DSA1_INFLUENCE", 2),
    CLOZE("Making a decision based on facts and thought is an ____ decision.",
      ["informed", "impulsive", "random", "forced"], "informed",
      "Informed decisions are based on accurate information and careful thought.", "ERR_LO_G9DSA1_INFORMED", 1),
    MC("What does being ASSERTIVE help you do with lifestyle choices?",
      ["Stand firm on your decisions calmly and confidently", "Give in to every pressure", "Be aggressive and rude", "Avoid all choices"], "Stand firm on your decisions calmly and confidently",
      "Assertiveness lets you make and defend your choices confidently and firmly.", "ERR_LO_G9DSA1_ASSERTIVE", 2),
    TF("A SMART goal is specific, measurable, achievable, relevant and time-bound.", "True",
      "SMART goals are specific, measurable, achievable, relevant and time-bound.", "ERR_LO_G9DSA1_SMART", 2),
    MC("Which is a POSITIVE influence on lifestyle choices?",
      ["A friend who encourages exercise and study", "A friend who pushes drugs", "Pressure to skip school", "Pressure to break the law"], "A friend who encourages exercise and study",
      "Positive influences encourage healthy choices like exercise and study.", "ERR_LO_G9DSA1_POSITIVE", 1),
    CLOZE("A goal you want to reach soon is a ____-term goal.",
      ["short", "never", "fake", "lost"], "short",
      "Short-term goals are achieved soon; long-term goals take longer to reach.", "ERR_LO_G9DSA1_SHORT", 1),
    TF("Outside influences should always decide your lifestyle for you.", "False",
      "While influences matter, you should make your own informed, assertive choices.", "ERR_LO_G9DSA1_OWN", 1),
    MC("Naledi's friends pressure her to skip training. Using assertiveness, she should…",
      ["calmly stick to her goal and say no", "give in to avoid conflict", "shout at them", "quit her sport"], "calmly stick to her goal and say no",
      "Assertively sticking to her goal protects her lifestyle choice without aggression.", "ERR_LO_G9DSA1_SCENARIO", 3),
    MC("Why set goals for your lifestyle?",
      ["They give direction and motivation", "They limit you for no reason", "They waste time", "They remove all choice"], "They give direction and motivation",
      "Goals give direction and motivation toward the life you want.", "ERR_LO_G9DSA1_WHY", 2),
    TF("Reviewing and adjusting your goals over time is a good habit.", "True",
      "Reviewing and adjusting goals keeps them realistic and relevant.", "ERR_LO_G9DSA1_REVIEW", 1),
    CLOZE("Recognising both positive and negative ____ helps you choose wisely.",
      ["influences", "songs", "colours", "snacks"], "influences",
      "Knowing positive and negative influences helps you make wise lifestyle choices.", "ERR_LO_G9DSA1_INFLUENCES", 1),
    MC("A negative influence on lifestyle choices could be…",
      ["pressure to use substances or skip school", "encouragement to study", "support for healthy eating", "a coach motivating you"], "pressure to use substances or skip school",
      "Negative influences push unhealthy or risky choices.", "ERR_LO_G9DSA1_NEGATIVE", 1),
    TF("Confident, firm decision-making is part of assertiveness.", "True",
      "Assertiveness includes making confident, firm decisions.", "ERR_LO_G9DSA1_FIRM", 1),
    MC("Which is the best response to an influence you disagree with?",
      ["Weigh it, then make your own informed choice", "Always follow it", "Always reject everything", "Ignore all thinking"], "Weigh it, then make your own informed choice",
      "Weighing influences and choosing for yourself leads to good decisions.", "ERR_LO_G9DSA1_RESPONSE", 2),
    MC("A realistic short-term goal for a learner could be…",
      ["improving a subject mark by next term", "becoming world champion overnight", "never studying again", "ignoring all goals"], "improving a subject mark by next term",
      "Realistic short-term goals are specific and achievable, like improving a mark by next term.", "ERR_LO_G9DSA1_REALISTIC", 2),
    {
      question: "Sort each influence on lifestyle choices into POSITIVE or NEGATIVE.",
      input_type: "sort-buckets",
      buckets: [{ id: "pos", label: "Positive" }, { id: "neg", label: "Negative" }],
      items: [
        { id: "i1", text: "A mentor encouraging your goals", correct_bucket: "pos" },
        { id: "i2", text: "Family supporting healthy habits", correct_bucket: "pos" },
        { id: "i3", text: "Pressure to use drugs", correct_bucket: "neg" },
        { id: "i4", text: "Friends daring you to break the law", correct_bucket: "neg" },
      ],
      expected: "Mentors and supportive family are positive; pressure to use drugs or break the law is negative.",
      pass_threshold: 0.75,
      memo: "Positive influences encourage healthy goals; negative ones push risky behaviour.",
      error_signals: ["ERR_LO_G9DSA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps of setting and reaching a personal goal in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Decide on a clear, realistic goal" },
        { id: "s2", text: "Make a plan with smaller steps" },
        { id: "s3", text: "Take action and track your progress" },
        { id: "s4", text: "Review and adjust the goal as needed" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Decide on a clear goal, plan smaller steps, act and track progress, then review and adjust.",
      memo: "Reach goals by deciding, planning, acting and reviewing.",
      error_signals: ["ERR_LO_G9DSA1_SEQ"], difficulty: 2,
    },
    MC("The key idea of goal-setting and lifestyle choices is to…",
      ["make your own informed, assertive choices about how you live", "let others decide for you", "avoid all goals", "act without thinking"], "make your own informed, assertive choices about how you live",
      "Goal-setting and lifestyle choices are about making your own informed, assertive decisions.", "ERR_LO_G9DSA1_SUMMARY", 2),
  ],

  // DS.A2 · Sexual behaviour and sexual health
  "LO.G9.DS.A2": [
    MC("What is a RISK FACTOR for unhealthy sexual behaviour?",
      ["Peer pressure and substance use", "Doing homework", "Eating breakfast", "Playing sport"], "Peer pressure and substance use",
      "Risk factors include peer pressure, substance use and lack of information.", "ERR_LO_G9DSA2_RISK", 1),
    TF("Abstinence is the most effective way to avoid pregnancy and STIs.", "True",
      "Abstinence is the most effective way to prevent pregnancy and sexually transmitted infections.", "ERR_LO_G9DSA2_ABSTINENCE", 1),
    MC("Which is a possible result of unhealthy sexual behaviour?",
      ["Teenage pregnancy or STIs", "Better health", "Higher marks", "More free time"], "Teenage pregnancy or STIs",
      "Unhealthy sexual behaviour can lead to teenage pregnancy, STIs, HIV and emotional harm.", "ERR_LO_G9DSA2_RESULTS", 1),
    CLOZE("Infections passed through sexual contact are called ____.",
      ["STIs", "colds", "allergies", "fevers"], "STIs",
      "Sexually transmitted infections (STIs) are passed through sexual contact.", "ERR_LO_G9DSA2_STI", 1),
    MC("Which factor can influence personal sexual behaviour?",
      ["Family, friends, peers and community norms", "The weather only", "Shoe size", "The day of the week"], "Family, friends, peers and community norms",
      "Family, friends, peers and community norms all influence personal behaviour.", "ERR_LO_G9DSA2_INFLUENCE", 2),
    TF("Teenage pregnancy can have serious consequences for the teen parents and the child.", "True",
      "Teenage pregnancy can have adverse consequences for the teen parents and their children.", "ERR_LO_G9DSA2_PREGNANCY", 1),
    MC("A strategy to deal with unhealthy sexual behaviour is…",
      ["abstinence and changing risky behaviour", "ignoring the risks", "more risky behaviour", "hiding from information"], "abstinence and changing risky behaviour",
      "Strategies include abstinence and changing risky behaviour, plus getting support.", "ERR_LO_G9DSA2_STRATEGY", 2),
    CLOZE("Things that lower your risk, like good support, are ____ factors.",
      ["protective", "harmful", "risky", "secret"], "protective",
      "Protective factors, like support and information, lower the risk of harmful behaviour.", "ERR_LO_G9DSA2_PROTECTIVE", 2),
    TF("It is unwise to seek accurate information about sexual health.", "False",
      "Seeking accurate information helps you make safe, healthy decisions.", "ERR_LO_G9DSA2_INFO", 1),
    MC("Where can a teenager find support and protection against risky behaviour?",
      ["A clinic, counsellor or trusted community structure", "Nowhere", "Only from rumours", "By staying silent"], "A clinic, counsellor or trusted community structure",
      "Clinics, counsellors and community structures offer support and protection.", "ERR_LO_G9DSA2_SUPPORT", 2),
    MC("Sipho feels pressured into risky behaviour 'to prove himself.' The healthiest response is to…",
      ["stay firm on his values and seek support if needed", "give in to the pressure", "act recklessly", "ignore the risks"], "stay firm on his values and seek support if needed",
      "Standing firm on values and seeking support is the healthiest, safest response.", "ERR_LO_G9DSA2_SCENARIO", 3),
    TF("Substance use can increase the chance of risky sexual behaviour.", "True",
      "Substance use lowers judgement and can increase risky sexual behaviour.", "ERR_LO_G9DSA2_SUBSTANCE", 2),
    CLOZE("Choosing not to have sex is called ____.",
      ["abstinence", "pressure", "risk", "stigma"], "abstinence",
      "Abstinence means choosing not to have sex, the most effective protection.", "ERR_LO_G9DSA2_ABSTAIN", 1),
    MC("Why is it important to know the consequences of risky behaviour?",
      ["So you can make informed, protective choices", "It makes no difference", "It increases risk", "It is none of your business"], "So you can make informed, protective choices",
      "Knowing consequences helps you make informed, protective choices.", "ERR_LO_G9DSA2_KNOW", 2),
    TF("Low self-image can be both a cause and a result of unhealthy sexual behaviour.", "True",
      "Low self-image can lead to and result from unhealthy sexual behaviour.", "ERR_LO_G9DSA2_SELFIMAGE", 2),
    MC("Caring community structures can offer young people…",
      ["protection and resilience against high-risk behaviour", "more pressure to take risks", "no help at all", "only judgement"], "protection and resilience against high-risk behaviour",
      "Supportive community structures build resilience against high-risk behaviour.", "ERR_LO_G9DSA2_COMMUNITY", 2),
    MC("Which is the most reliable source of sexual-health information?",
      ["A clinic nurse or health professional", "An unverified social post", "A playground rumour", "A guess"], "A clinic nurse or health professional",
      "Health professionals give the most reliable sexual-health information.", "ERR_LO_G9DSA2_SOURCE", 2),
    {
      question: "Sort each factor into RISK or PROTECTIVE for sexual health.",
      input_type: "sort-buckets",
      buckets: [{ id: "risk", label: "Risk factor" }, { id: "protect", label: "Protective factor" }],
      items: [
        { id: "i1", text: "Substance use", correct_bucket: "risk" },
        { id: "i2", text: "Pressure from peers", correct_bucket: "risk" },
        { id: "i3", text: "Accurate information and support", correct_bucket: "protect" },
        { id: "i4", text: "Strong personal values", correct_bucket: "protect" },
      ],
      expected: "Substance use and peer pressure are risks; accurate info and strong values are protective.",
      pass_threshold: 0.75,
      memo: "Risk factors raise the chance of harm; protective factors lower it.",
      error_signals: ["ERR_LO_G9DSA2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps for making a safe, healthy decision under pressure in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Know your own values and goals" },
        { id: "s2", text: "Recognise the risk in the situation" },
        { id: "s3", text: "Make a firm, informed choice" },
        { id: "s4", text: "Seek support if you need it" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Know your values, recognise the risk, make a firm informed choice, then seek support if needed.",
      memo: "Decide safely by knowing your values, spotting risk, choosing firmly and seeking support.",
      error_signals: ["ERR_LO_G9DSA2_SEQ"], difficulty: 2,
    },
    MC("The key message about sexual health is to make…",
      ["informed, value-based choices that protect your health and future", "risky choices to fit in", "no choices at all", "choices based only on pressure"], "informed, value-based choices that protect your health and future",
      "Sexual health is protected by informed, value-based choices.", "ERR_LO_G9DSA2_SUMMARY", 2),
  ],

  // DS.A3 · Challenging situations
  "LO.G9.DS.A3": [
    MC("Which is an example of a CHALLENGING emotional situation?",
      ["Grief after losing a loved one", "Winning a small prize", "A sunny day", "A good night's sleep"], "Grief after losing a loved one",
      "Challenging situations include depression, grief, loss, trauma and crisis.", "ERR_LO_G9DSA3_DEF", 1),
    TF("Depression is more than ordinary sadness and can need support to manage.", "True",
      "Depression is a serious low mood, more than ordinary sadness, that often needs support.", "ERR_LO_G9DSA3_DEPRESSION", 1),
    MC("What is 'grief'?",
      ["Deep sadness, usually after a loss", "A type of food", "A sport", "A school subject"], "Deep sadness, usually after a loss",
      "Grief is the deep sadness people feel after a loss, such as a death.", "ERR_LO_G9DSA3_GRIEF", 1),
    CLOZE("A sudden, very difficult event that overwhelms a person is a ____.",
      ["crisis", "holiday", "hobby", "habit"], "crisis",
      "A crisis is a sudden, overwhelming event that is hard to cope with.", "ERR_LO_G9DSA3_CRISIS", 1),
    MC("Which is a HEALTHY way to cope with strong emotions?",
      ["Talk to someone you trust", "Use alcohol or drugs", "Bottle it up alone", "Take it out on others"], "Talk to someone you trust",
      "Healthy coping includes talking to trusted people, not using substances or harming others.", "ERR_LO_G9DSA3_HEALTHY", 1),
    TF("Using alcohol or drugs to cope is a counterproductive coping technique.", "True",
      "Using alcohol or drugs is counterproductive — it worsens problems rather than solving them.", "ERR_LO_G9DSA3_COUNTER", 2),
    MC("What can CAUSE trauma?",
      ["A frightening or harmful experience", "A relaxing holiday", "A good meal", "A nap"], "A frightening or harmful experience",
      "Trauma can result from frightening or harmful experiences like accidents or abuse.", "ERR_LO_G9DSA3_TRAUMA", 2),
    CLOZE("Reaching out to a counsellor or trusted adult is asking for ____.",
      ["help", "trouble", "money", "fame"], "help",
      "Asking a counsellor or trusted adult for help is a healthy response to difficult emotions.", "ERR_LO_G9DSA3_HELP", 1),
    TF("Asking for help when you are struggling is a sign of strength.", "True",
      "Reaching out for help takes courage and is a sign of strength, not weakness.", "ERR_LO_G9DSA3_STRENGTH", 1),
    MC("A friend seems very low for weeks and talks about hopelessness. You should…",
      ["encourage them to get help and tell a trusted adult", "ignore it", "promise total secrecy", "tell them to 'snap out of it'"], "encourage them to get help and tell a trusted adult",
      "Persistent hopelessness needs support; encourage help and involve a trusted adult.", "ERR_LO_G9DSA3_SCENARIO", 3),
    MC("Which is a problem-solving step for dealing with a tough emotion?",
      ["Name the feeling and think of healthy responses", "Pretend it does not exist", "React without thinking", "Blame everyone else"], "Name the feeling and think of healthy responses",
      "Problem-solving means naming the feeling and choosing healthy responses.", "ERR_LO_G9DSA3_PROBLEMSOLVE", 2),
    TF("Everyone faces difficult emotions at some point; they are part of life.", "True",
      "Difficult emotions are a normal part of life that everyone faces sometimes.", "ERR_LO_G9DSA3_NORMAL", 1),
    CLOZE("Ongoing low mood and loss of interest can be signs of ____.",
      ["depression", "excitement", "energy", "joy"], "depression",
      "Ongoing low mood and loss of interest can be signs of depression.", "ERR_LO_G9DSA3_SIGNS", 2),
    MC("Where can a teenager get help for serious emotional difficulties?",
      ["A counsellor, clinic or helpline like SADAG", "Nowhere", "Only from strangers online", "By staying silent"], "A counsellor, clinic or helpline like SADAG",
      "Counsellors, clinics and helplines like SADAG offer help for emotional difficulties.", "ERR_LO_G9DSA3_RESOURCES", 2),
    TF("Talking about feelings can help reduce their power over you.", "True",
      "Expressing feelings to someone you trust can ease their intensity.", "ERR_LO_G9DSA3_TALK", 1),
    MC("Which healthy strategy can help manage stress and strong emotions?",
      ["Exercise, rest, and talking to someone", "Isolating completely", "Using substances", "Ignoring the feeling forever"], "Exercise, rest, and talking to someone",
      "Exercise, rest and talking are healthy strategies to manage stress and emotions.", "ERR_LO_G9DSA3_STRATEGY", 1),
    {
      question: "Sort each coping response into HEALTHY or COUNTERPRODUCTIVE.",
      input_type: "sort-buckets",
      buckets: [{ id: "healthy", label: "Healthy" }, { id: "counter", label: "Counterproductive" }],
      items: [
        { id: "i1", text: "Talking to a counsellor", correct_bucket: "healthy" },
        { id: "i2", text: "Exercising and resting", correct_bucket: "healthy" },
        { id: "i3", text: "Drinking alcohol to forget", correct_bucket: "counter" },
        { id: "i4", text: "Bottling it all up alone", correct_bucket: "counter" },
      ],
      expected: "Counselling and exercise are healthy; using alcohol or bottling up are counterproductive.",
      pass_threshold: 0.75,
      memo: "Healthy coping faces feelings with support; counterproductive coping avoids or numbs them.",
      error_signals: ["ERR_LO_G9DSA3_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for responding to a difficult emotion in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Notice and name the emotion" },
        { id: "s2", text: "Choose a healthy way to respond" },
        { id: "s3", text: "Talk to someone you trust" },
        { id: "s4", text: "Get professional help if it continues" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Notice and name the emotion, choose a healthy response, talk to someone, then get help if it continues.",
      memo: "Handle hard emotions by naming them, responding healthily, talking, and getting help if needed.",
      error_signals: ["ERR_LO_G9DSA3_SEQ"], difficulty: 2,
    },
    TF("It is okay to need time to recover from grief or loss.", "True",
      "Recovering from grief or loss takes time, and that is normal and healthy.", "ERR_LO_G9DSA3_TIME", 1),
    MC("The key message about challenging situations is that…",
      ["healthy coping and seeking help are signs of strength", "you must cope alone", "substances help you cope", "feelings should be ignored"], "healthy coping and seeking help are signs of strength",
      "Healthy coping and asking for help are signs of strength, not weakness.", "ERR_LO_G9DSA3_SUMMARY", 2),
  ],

  // ════════════ HEALTH, SOCIAL & ENVIRONMENTAL RESPONSIBILITY (Term 3) ══════════
  // HE.A1 · Volunteerism
  "LO.G9.HE.A1": [
    MC("What is volunteerism?",
      ["Giving your time to help others without being paid", "Working only for money", "Doing nothing", "Helping only yourself"], "Giving your time to help others without being paid",
      "Volunteerism is freely giving your time and effort to help others and the community.", "ERR_LO_G9HEA1_DEF", 1),
    TF("Volunteers usually work without being paid.", "True",
      "Volunteers give their time freely, usually without payment.", "ERR_LO_G9HEA1_UNPAID", 1),
    MC("Which is an example of volunteering?",
      ["Helping at a soup kitchen", "Being paid for a full-time job", "Watching TV all day", "Ignoring those in need"], "Helping at a soup kitchen",
      "Volunteering includes unpaid help like working at a soup kitchen or cleaning a park.", "ERR_LO_G9HEA1_EXAMPLE", 1),
    CLOZE("Organisations that help society without making profit are ____ organisations.",
      ["non-profit", "for-profit", "secret", "private"], "non-profit",
      "Non-profit and community-based organisations help society rather than make profit.", "ERR_LO_G9HEA1_NONPROFIT", 2),
    MC("How does volunteering benefit the COMMUNITY?",
      ["It meets needs and improves social and environmental health", "It harms the community", "It has no effect", "It only helps the volunteer"], "It meets needs and improves social and environmental health",
      "Volunteering meets community needs and improves social and environmental health.", "ERR_LO_G9HEA1_COMMUNITY", 2),
    TF("Volunteering can also benefit the volunteer, building skills and confidence.", "True",
      "Volunteers gain skills, experience, confidence and a sense of purpose.", "ERR_LO_G9HEA1_VOLUNTEER", 1),
    MC("Which is a 'community-based organisation'?",
      ["A local group helping its own community", "A foreign government", "A large bank", "A school exam"], "A local group helping its own community",
      "Community-based organisations are local groups that serve their own communities.", "ERR_LO_G9HEA1_CBO", 2),
    CLOZE("Helping people who are less ____ is a common volunteer activity.",
      ["privileged", "happy", "tall", "busy"], "privileged",
      "Volunteers often help those who are less privileged or in need.", "ERR_LO_G9HEA1_PRIVILEGED", 1),
    TF("Volunteering is both an individual and a community responsibility.", "True",
      "Caring for others is both a personal and a shared community responsibility.", "ERR_LO_G9HEA1_RESPONSIBILITY", 1),
    MC("A group helping people affected by HIV and AIDS is doing volunteer work that…",
      ["supports health and dignity in the community", "harms the community", "has no value", "spreads stigma"], "supports health and dignity in the community",
      "Helping those affected by HIV and AIDS supports community health and dignity.", "ERR_LO_G9HEA1_HIV", 2),
    MC("Why might a young person choose to volunteer?",
      ["To help others, gain skills and make a difference", "To earn a salary", "To avoid all effort", "To harm the community"], "To help others, gain skills and make a difference",
      "Young people volunteer to help others, build skills and make a positive difference.", "ERR_LO_G9HEA1_WHY", 2),
    TF("Volunteer work can support sustainable development.", "True",
      "Volunteering can contribute to social, environmental and sustainable development.", "ERR_LO_G9HEA1_SUSTAINABLE", 2),
    CLOZE("Caring for the environment, like a clean-up, is ____ volunteering.",
      ["environmental", "financial", "selfish", "secret"], "environmental",
      "Environmental volunteering includes activities like clean-ups and tree planting.", "ERR_LO_G9HEA1_ENVIRONMENTAL", 1),
    MC("Which is a type of volunteer activity?",
      ["Tutoring younger learners for free", "Charging high fees", "Refusing to help", "Ignoring needs"], "Tutoring younger learners for free",
      "Free tutoring, caring for the sick, and clean-ups are all volunteer activities.", "ERR_LO_G9HEA1_TYPE", 1),
    TF("Even small acts of volunteering can make a real difference.", "True",
      "Small, consistent volunteer efforts add up to real community benefit.", "ERR_LO_G9HEA1_SMALL", 1),
    MC("Naledi wants to volunteer but has little time. A realistic option is to…",
      ["help with a short local project on weekends", "promise huge commitments she can't keep", "do nothing", "wait until she is an adult"], "help with a short local project on weekends",
      "Realistic, manageable volunteering fits her time while still making a difference.", "ERR_LO_G9HEA1_SCENARIO", 3),
    {
      question: "Sort each activity into VOLUNTEER work or PAID/NON-volunteer work.",
      input_type: "sort-buckets",
      buckets: [{ id: "volunteer", label: "Volunteer work" }, { id: "paid", label: "Paid / non-volunteer" }],
      items: [
        { id: "i1", text: "Cleaning a park for free", correct_bucket: "volunteer" },
        { id: "i2", text: "Helping at a shelter unpaid", correct_bucket: "volunteer" },
        { id: "i3", text: "Working a paid weekend job", correct_bucket: "paid" },
        { id: "i4", text: "Running a business for profit", correct_bucket: "paid" },
      ],
      expected: "Free park clean-ups and unpaid shelter help are volunteering; paid jobs and profit businesses are not.",
      pass_threshold: 0.75,
      memo: "Volunteering is unpaid help for others; paid work is done for income.",
      error_signals: ["ERR_LO_G9HEA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for starting a volunteer project in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Identify a need you care about" },
        { id: "s2", text: "Find or form a group to help" },
        { id: "s3", text: "Plan and carry out the activity" },
        { id: "s4", text: "Reflect on the difference made" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Identify a need, find a group, plan and act, then reflect on the difference made.",
      memo: "Volunteer well by identifying a need, gathering helpers, acting and reflecting.",
      error_signals: ["ERR_LO_G9HEA1_SEQ"], difficulty: 2,
    },
    TF("Volunteering can build skills that are useful in future work.", "True",
      "Volunteering builds skills, experience and confidence useful in future work.", "ERR_LO_G9HEA1_SKILLS", 1),
    MC("The key message about volunteerism is that it…",
      ["benefits both the community and the volunteer", "only wastes time", "helps no one", "harms communities"], "benefits both the community and the volunteer",
      "Volunteering benefits the community and the volunteer alike.", "ERR_LO_G9HEA1_SUMMARY", 2),
  ],

  // HE.A2 · Violence and safety
  "LO.G9.HE.A2": [
    MC("Which is a common act of violence that can happen in communities?",
      ["Assault or robbery", "Sharing a meal", "Playing a fair game", "Helping a neighbour"], "Assault or robbery",
      "Common acts of violence include assault, robbery, bullying and abuse.", "ERR_LO_G9HEA2_DEF", 1),
    TF("Violence can occur at home, at school and in the community.", "True",
      "Violence can happen in many places — home, school and the wider community.", "ERR_LO_G9HEA2_PLACES", 1),
    MC("Which can be a REASON violence occurs in communities?",
      ["Poverty, substance abuse and unresolved conflict", "Kindness", "Cooperation", "Respect"], "Poverty, substance abuse and unresolved conflict",
      "Violence is linked to poverty, substance abuse, inequality and unresolved conflict.", "ERR_LO_G9HEA2_REASONS", 2),
    CLOZE("Solving disagreements without violence uses conflict-____ skills.",
      ["management", "starting", "ignoring", "hiding"], "management",
      "Conflict-management skills help resolve disagreements peacefully.", "ERR_LO_G9HEA2_CONFLICT", 2),
    MC("Which is an ALTERNATIVE to violence?",
      ["Problem-solving and managing conflict calmly", "Fighting back harder", "Revenge", "Threats"], "Problem-solving and managing conflict calmly",
      "Alternatives to violence include problem-solving and calm conflict management.", "ERR_LO_G9HEA2_ALTERNATIVE", 1),
    TF("Violence can harm both individual and community health and safety.", "True",
      "Violence damages the health and safety of individuals and whole communities.", "ERR_LO_G9HEA2_IMPACT", 1),
    MC("How can you protect yourself and others from violence?",
      ["Avoid risky situations and know where to get help", "Carry a weapon", "Seek revenge", "Ignore all danger"], "Avoid risky situations and know where to get help",
      "Protection means avoiding risky situations and knowing where to find help.", "ERR_LO_G9HEA2_PROTECT", 2),
    CLOZE("Reporting violence to the ____ can help keep people safe.",
      ["police", "shops", "tourists", "weather"], "police",
      "Reporting violence to the police or other authorities helps keep people safe.", "ERR_LO_G9HEA2_POLICE", 1),
    TF("Responding to violence with more violence usually solves the problem.", "False",
      "Meeting violence with violence usually worsens it; peaceful solutions work better.", "ERR_LO_G9HEA2_MOREVIOLENCE", 1),
    MC("Two learners are about to fight over an insult. A peaceful response is to…",
      ["calm down, talk it out or involve a teacher", "throw the first punch", "encourage the fight", "spread the insult further"], "calm down, talk it out or involve a teacher",
      "Calming down, talking, or getting a teacher resolves conflict without violence.", "ERR_LO_G9HEA2_SCENARIO", 3),
    MC("Which national programme aim helps reduce violence?",
      ["Safety and health promotion programmes", "Programmes that encourage crime", "No programmes", "Ignoring safety"], "Safety and health promotion programmes",
      "National health and safety promotion programmes help reduce violence and harm.", "ERR_LO_G9HEA2_PROGRAMME", 2),
    TF("Unmanaged anger can increase the risk of violence.", "True",
      "Anger that is not managed well can lead to violence; managing it reduces the risk.", "ERR_LO_G9HEA2_ANGER", 2),
    CLOZE("Where to find ____ includes the police, clinics and helplines.",
      ["help", "trouble", "snacks", "fame"], "help",
      "Knowing where to find help — police, clinics, helplines — is key to staying safe.", "ERR_LO_G9HEA2_HELP", 1),
    MC("Why is it important to understand the impact of violence?",
      ["It motivates choosing peaceful alternatives", "It has no purpose", "It encourages violence", "It is irrelevant"], "It motivates choosing peaceful alternatives",
      "Understanding violence's harm motivates choosing peaceful alternatives.", "ERR_LO_G9HEA2_UNDERSTAND", 2),
    TF("Schools can promote safety with clear rules and anti-bullying programmes.", "True",
      "Clear rules and anti-bullying programmes help schools promote safety.", "ERR_LO_G9HEA2_SCHOOL", 1),
    MC("A good first response when you feel anger rising in a conflict is to…",
      ["pause, breathe, and step back before reacting", "shout immediately", "throw something", "insult the other person"], "pause, breathe, and step back before reacting",
      "Pausing and stepping back helps you respond calmly instead of violently.", "ERR_LO_G9HEA2_PAUSE", 2),
    {
      question: "Sort each response to conflict into PEACEFUL or VIOLENT.",
      input_type: "sort-buckets",
      buckets: [{ id: "peace", label: "Peaceful" }, { id: "violent", label: "Violent" }],
      items: [
        { id: "i1", text: "Talking it out calmly", correct_bucket: "peace" },
        { id: "i2", text: "Asking a teacher to mediate", correct_bucket: "peace" },
        { id: "i3", text: "Throwing a punch", correct_bucket: "violent" },
        { id: "i4", text: "Threatening the other person", correct_bucket: "violent" },
      ],
      expected: "Talking calmly and mediation are peaceful; punching and threatening are violent.",
      pass_threshold: 0.75,
      memo: "Peaceful responses solve conflict; violent ones escalate it.",
      error_signals: ["ERR_LO_G9HEA2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for managing a conflict without violence in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Stay calm and step back" },
        { id: "s2", text: "Listen to understand the problem" },
        { id: "s3", text: "Look for a fair solution together" },
        { id: "s4", text: "Get help if it cannot be resolved" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Stay calm, listen to the problem, find a fair solution, then get help if needed.",
      memo: "Manage conflict by staying calm, listening, solving fairly and seeking help if needed.",
      error_signals: ["ERR_LO_G9HEA2_SEQ"], difficulty: 2,
    },
    TF("Knowing where to find help is an important part of staying safe.", "True",
      "Knowing where to find help — police, clinics, helplines — is key to safety.", "ERR_LO_G9HEA2_KNOWHELP", 1),
    MC("The key message about violence and safety is that…",
      ["conflict can be solved peacefully and help is available", "violence is the only answer", "nothing can be done", "revenge is best"], "conflict can be solved peacefully and help is available",
      "Conflict can be managed peacefully, and help is always available.", "ERR_LO_G9HEA2_SUMMARY", 2),
  ],

  // ════════════ CONSTITUTIONAL RIGHTS & RESPONSIBILITIES (Term 2) ═══════════════
  // CR.A1 · Citizens' rights and national days
  "LO.G9.CR.A1": [
    MC("Respecting others' rights includes respecting people who are…",
      ["living with disabilities or with HIV and AIDS", "exactly like you only", "from your area only", "your friends only"], "living with disabilities or with HIV and AIDS",
      "We must respect everyone's rights, including people living with disabilities and HIV and AIDS.", "ERR_LO_G9CRA1_DEF", 1),
    TF("Citizens have both rights and responsibilities.", "True",
      "Citizenship means having rights and matching responsibilities toward others.", "ERR_LO_G9CRA1_BOTH", 1),
    MC("What does Human Rights Day commemorate in South Africa?",
      ["The importance and protection of human rights", "A sports event", "A shopping sale", "A school holiday only"], "The importance and protection of human rights",
      "Human Rights Day commemorates human rights and those who fought for them.", "ERR_LO_G9CRA1_HRDAY", 2),
    CLOZE("Freedom Day celebrates South Africa's first democratic ____ in 1994.",
      ["elections", "exams", "holidays", "matches"], "elections",
      "Freedom Day celebrates the first democratic elections of 1994.", "ERR_LO_G9CRA1_FREEDOM", 2),
    MC("Why does South Africa celebrate national days?",
      ["To remember important events and shared values", "To cause division", "For no reason", "To ignore history"], "To remember important events and shared values",
      "National days mark important events and remind us of shared values.", "ERR_LO_G9CRA1_WHY", 2),
    TF("Heritage Day celebrates the diverse cultures of South Africa.", "True",
      "Heritage Day celebrates South Africa's diverse cultural heritage.", "ERR_LO_G9CRA1_HERITAGE", 1),
    MC("Respecting the rights of people with disabilities means…",
      ["including them and removing barriers", "excluding them", "ignoring their needs", "mocking them"], "including them and removing barriers",
      "Respect means including people with disabilities and removing barriers to participation.", "ERR_LO_G9CRA1_DISABILITY", 2),
    CLOZE("Youth Day remembers the role of ____ in the struggle for freedom.",
      ["students", "tourists", "shops", "referees"], "students",
      "Youth Day remembers the students of the 1976 uprising and the role of youth.", "ERR_LO_G9CRA1_YOUTH", 2),
    TF("Nelson Mandela Day encourages people to give time to help others.", "True",
      "Mandela Day encourages acts of service and helping others in the community.", "ERR_LO_G9CRA1_MANDELA", 1),
    MC("A learner uses a wheelchair and the class outing venue has stairs only. The rights-respecting response is to…",
      ["choose an accessible venue so everyone can join", "leave them behind", "ignore the problem", "tell them not to come"], "choose an accessible venue so everyone can join",
      "Choosing an accessible venue respects the learner's right to participate equally.", "ERR_LO_G9CRA1_SCENARIO", 3),
    MC("What is a responsibility that comes with the right to vote (as an adult)?",
      ["To make an informed, responsible choice", "To sell your vote", "To skip voting always", "To vote many times"], "To make an informed, responsible choice",
      "The right to vote carries the responsibility to make an informed, honest choice.", "ERR_LO_G9CRA1_VOTE", 2),
    TF("Respecting others' rights helps create a fair and inclusive society.", "True",
      "Respecting everyone's rights builds a fair, inclusive society.", "ERR_LO_G9CRA1_INCLUSIVE", 1),
    CLOZE("Reconciliation Day promotes national ____ and healing.",
      ["unity", "division", "conflict", "anger"], "unity",
      "The Day of Reconciliation promotes national unity and healing of past divisions.", "ERR_LO_G9CRA1_RECONCILE", 2),
    MC("Planning a local celebration of a national day helps citizens to…",
      ["remember its meaning and build community", "forget history", "divide people", "waste resources"], "remember its meaning and build community",
      "Celebrating national days helps citizens remember their meaning and build community.", "ERR_LO_G9CRA1_CELEBRATE", 2),
    TF("People living with HIV and AIDS have the same rights as everyone else.", "True",
      "People living with HIV and AIDS have equal rights and deserve respect and inclusion.", "ERR_LO_G9CRA1_HIVRIGHTS", 1),
    MC("Which is a way to show responsible citizenship?",
      ["Respecting others' rights and obeying just laws", "Ignoring others' rights", "Breaking the law", "Excluding people"], "Respecting others' rights and obeying just laws",
      "Responsible citizens respect rights and obey just laws.", "ERR_LO_G9CRA1_CITIZENSHIP", 2),
    {
      question: "Sort each into RESPECTING rights or DISRESPECTING rights.",
      input_type: "sort-buckets",
      buckets: [{ id: "respect", label: "Respecting" }, { id: "disrespect", label: "Disrespecting" }],
      items: [
        { id: "i1", text: "Making an event wheelchair-accessible", correct_bucket: "respect" },
        { id: "i2", text: "Including a learner with HIV normally", correct_bucket: "respect" },
        { id: "i3", text: "Excluding someone for being different", correct_bucket: "disrespect" },
        { id: "i4", text: "Mocking a person's disability", correct_bucket: "disrespect" },
      ],
      expected: "Accessibility and inclusion respect rights; exclusion and mockery disrespect them.",
      pass_threshold: 0.75,
      memo: "Respecting rights means including everyone; disrespect excludes or demeans.",
      error_signals: ["ERR_LO_G9CRA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for planning a local national-day celebration in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Choose the national day and its meaning" },
        { id: "s2", text: "Plan inclusive activities" },
        { id: "s3", text: "Hold the celebration with the community" },
        { id: "s4", text: "Reflect on what was learned and shared" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Choose the day and its meaning, plan inclusive activities, hold the event, then reflect.",
      memo: "Celebrate well by choosing the day's meaning, planning inclusively, holding it and reflecting.",
      error_signals: ["ERR_LO_G9CRA1_SEQ"], difficulty: 2,
    },
    TF("Women's Day honours the role of women in South Africa's history.", "True",
      "Women's Day commemorates the 1956 women's march and the role of women in our history.", "ERR_LO_G9CRA1_WOMEN", 1),
    MC("The key idea of citizens' rights and national days is that…",
      ["we respect everyone's rights and remember our shared history", "rights are only for some", "history should be forgotten", "national days mean nothing"], "we respect everyone's rights and remember our shared history",
      "Responsible citizenship respects everyone's rights and honours our shared history.", "ERR_LO_G9CRA1_SUMMARY", 2),
  ],

  // CR.A2 · Constitutional values
  "LO.G9.CR.A2": [
    MC("Which is a value stated in the South African Constitution?",
      ["Human dignity, equality and freedom", "Greed and division", "Discrimination", "Dishonesty"], "Human dignity, equality and freedom",
      "Constitutional values include human dignity, equality, freedom, non-racialism and non-sexism.", "ERR_LO_G9CRA2_DEF", 1),
    TF("Equality and human dignity are core constitutional values.", "True",
      "Equality and human dignity are central values of the Constitution.", "ERR_LO_G9CRA2_CORE", 1),
    MC("What is a POSITIVE role model?",
      ["Someone whose good example is worth following", "Someone who breaks the law", "Someone who harms others", "Someone who lies"], "Someone whose good example is worth following",
      "A positive role model sets a good example worth following.", "ERR_LO_G9CRA2_POSITIVE", 1),
    CLOZE("Treating everyone as equal upholds the value of ____.",
      ["equality", "greed", "division", "prejudice"], "equality",
      "Equality means treating everyone fairly and as equals, a core constitutional value.", "ERR_LO_G9CRA2_EQUALITY", 1),
    MC("Who can be a role model for constitutional values?",
      ["Parents and community leaders", "Only celebrities", "Nobody", "Only the wealthy"], "Parents and community leaders",
      "Parents, teachers and community leaders can model constitutional values.", "ERR_LO_G9CRA2_WHO", 2),
    TF("Applying constitutional values in daily life means living them, not just knowing them.", "True",
      "Values matter most when applied in daily actions, not just known in theory.", "ERR_LO_G9CRA2_APPLY", 1),
    MC("Which action shows the value of human dignity?",
      ["Treating others with respect and worth", "Humiliating people", "Bullying", "Discriminating"], "Treating others with respect and worth",
      "Respecting others' worth upholds the value of human dignity.", "ERR_LO_G9CRA2_DIGNITY", 1),
    CLOZE("A society that rejects racism upholds the value of non-____.",
      ["racialism", "sense", "stop", "fiction"], "racialism",
      "Non-racialism is a constitutional value rejecting racism.", "ERR_LO_G9CRA2_NONRACIAL", 2),
    TF("A NEGATIVE role model can lead others toward harmful choices.", "True",
      "Negative role models can influence others toward harmful behaviour.", "ERR_LO_G9CRA2_NEGATIVE", 1),
    MC("A leader treats all community members fairly regardless of background. This models…",
      ["equality and human dignity", "discrimination", "greed", "division"], "equality and human dignity",
      "Fair treatment of all models equality and human dignity.", "ERR_LO_G9CRA2_SCENARIO", 3),
    MC("Why are constitutional values important for daily life?",
      ["They guide fair, respectful treatment of one another", "They are only for courts", "They have no use", "They divide people"], "They guide fair, respectful treatment of one another",
      "Constitutional values guide how we treat one another fairly and respectfully.", "ERR_LO_G9CRA2_WHY", 2),
    TF("Freedom, as a constitutional value, comes with respecting others' freedom.", "True",
      "Freedom is balanced by the responsibility to respect others' freedom.", "ERR_LO_G9CRA2_FREEDOM", 2),
    CLOZE("Living constitutional values builds a fair and ____ society.",
      ["just", "cruel", "divided", "violent"], "just",
      "Applying constitutional values builds a fair and just society.", "ERR_LO_G9CRA2_JUST", 1),
    MC("Which is a good way for a learner to apply constitutional values?",
      ["Stand up against unfair discrimination at school", "Join in bullying", "Ignore unfairness", "Exclude others"], "Stand up against unfair discrimination at school",
      "Standing against discrimination applies constitutional values in daily life.", "ERR_LO_G9CRA2_LEARNER", 2),
    TF("Non-sexism, treating all genders equally, is a constitutional value.", "True",
      "Non-sexism — equal treatment of all genders — is a constitutional value.", "ERR_LO_G9CRA2_NONSEXISM", 1),
    MC("A celebrity who cheats and brags about it is acting as a…",
      ["negative role model", "positive role model", "constitutional hero", "good example"], "negative role model",
      "Behaviour like cheating and bragging makes someone a negative role model.", "ERR_LO_G9CRA2_BADMODEL", 2),
    {
      question: "Sort each action into UPHOLDS or VIOLATES constitutional values.",
      input_type: "sort-buckets",
      buckets: [{ id: "uphold", label: "Upholds values" }, { id: "violate", label: "Violates values" }],
      items: [
        { id: "i1", text: "Treating everyone equally", correct_bucket: "uphold" },
        { id: "i2", text: "Respecting human dignity", correct_bucket: "uphold" },
        { id: "i3", text: "Racist discrimination", correct_bucket: "violate" },
        { id: "i4", text: "Humiliating others", correct_bucket: "violate" },
      ],
      expected: "Equality and respect uphold values; racism and humiliation violate them.",
      pass_threshold: 0.75,
      memo: "Constitutional values are upheld by equality and dignity; violated by discrimination and cruelty.",
      error_signals: ["ERR_LO_G9CRA2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for applying a constitutional value when you see unfairness in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise the value being broken (e.g. equality)" },
        { id: "s2", text: "Decide on a safe, respectful response" },
        { id: "s3", text: "Speak up or report the unfairness" },
        { id: "s4", text: "Support fair treatment going forward" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise the value broken, decide a respectful response, speak up or report, then support fairness.",
      memo: "Apply values by recognising the breach, responding respectfully, speaking up and supporting fairness.",
      error_signals: ["ERR_LO_G9CRA2_SEQ"], difficulty: 2,
    },
    TF("Constitutional values matter most when we live them every day.", "True",
      "Values like equality and dignity matter most when applied in daily actions.", "ERR_LO_G9CRA2_DAILY", 1),
    MC("The key idea of constitutional values is that they…",
      ["guide fair and respectful treatment of everyone", "are only for courtrooms", "can be ignored", "favour some over others"], "guide fair and respectful treatment of everyone",
      "Constitutional values guide fair, respectful treatment of all people.", "ERR_LO_G9CRA2_SUMMARY", 2),
  ],

  // CR.A3 · Religions and peace
  "LO.G9.CR.A3": [
    MC("How can religions contribute to PEACE?",
      ["By teaching compassion, forgiveness and respect", "By encouraging conflict", "By spreading hatred", "By ignoring others"], "By teaching compassion, forgiveness and respect",
      "Religions can promote peace by teaching compassion, forgiveness and respect for others.", "ERR_LO_G9CRA3_DEF", 1),
    TF("Many religions teach values of peace and caring for others.", "True",
      "Peace, compassion and care for others are values taught by many religions.", "ERR_LO_G9CRA3_VALUES", 1),
    MC("Which is a peaceful contribution religions can make?",
      ["Encouraging forgiveness and reconciliation", "Encouraging revenge", "Spreading division", "Promoting violence"], "Encouraging forgiveness and reconciliation",
      "Encouraging forgiveness and reconciliation is a peaceful religious contribution.", "ERR_LO_G9CRA3_CONTRIBUTION", 1),
    CLOZE("Letting go of anger and choosing not to seek revenge is ____.",
      ["forgiveness", "hatred", "violence", "greed"], "forgiveness",
      "Forgiveness — letting go of anger — is a value that supports peace.", "ERR_LO_G9CRA3_FORGIVE", 2),
    MC("How can people of different religions promote peace together?",
      ["Through respect, dialogue and cooperation", "Through conflict", "By refusing to talk", "By mocking each other"], "Through respect, dialogue and cooperation",
      "Interfaith respect, dialogue and cooperation promote peace.", "ERR_LO_G9CRA3_INTERFAITH", 2),
    TF("Respecting beliefs different from your own helps promote peace.", "True",
      "Respecting different beliefs reduces conflict and promotes peace.", "ERR_LO_G9CRA3_RESPECT", 1),
    MC("Which is an example of a religion promoting peace in society?",
      ["Leading reconciliation after conflict", "Starting fights", "Encouraging hatred", "Dividing communities"], "Leading reconciliation after conflict",
      "Faith leaders helping reconciliation after conflict is a peace-promoting example.", "ERR_LO_G9CRA3_EXAMPLE", 2),
    CLOZE("Caring for others, even strangers, shows ____.",
      ["compassion", "cruelty", "greed", "anger"], "compassion",
      "Compassion — caring for others — is a peace-promoting value across religions.", "ERR_LO_G9CRA3_COMPASSION", 1),
    TF("Religion can never play a role in building peace.", "False",
      "Religions often play an important role in building and promoting peace.", "ERR_LO_G9CRA3_NEVER", 1),
    MC("Two religious groups in a town organise a joint charity drive. This promotes…",
      ["cooperation and peace between communities", "division", "conflict", "intolerance"], "cooperation and peace between communities",
      "Joint charity work builds cooperation and peace between communities.", "ERR_LO_G9CRA3_SCENARIO", 3),
    MC("Why is tolerance important among different religions?",
      ["It allows people to live together peacefully", "It causes fighting", "It is unimportant", "It spreads hate"], "It allows people to live together peacefully",
      "Tolerance lets people of different faiths live together in peace.", "ERR_LO_G9CRA3_TOLERANCE", 2),
    TF("Peace among religions is built on mutual respect, not sameness.", "True",
      "Religious peace comes from mutual respect, not from everyone being the same.", "ERR_LO_G9CRA3_MUTUAL", 2),
    CLOZE("Talking and listening between faiths is called inter-faith ____.",
      ["dialogue", "silence", "conflict", "war"], "dialogue",
      "Interfaith dialogue — talking and listening — builds understanding and peace.", "ERR_LO_G9CRA3_DIALOGUE", 2),
    MC("A peaceful response to someone insulting your religion is to…",
      ["respond calmly and explain respectfully", "insult their religion back", "start a fight", "spread hatred"], "respond calmly and explain respectfully",
      "Responding calmly and respectfully promotes peace even when provoked.", "ERR_LO_G9CRA3_RESPONSE", 2),
    TF("Helping the poor is a peace-building value shared by many religions.", "True",
      "Caring for the poor is a shared value that builds social peace.", "ERR_LO_G9CRA3_POOR", 1),
    MC("Which attitude best supports peace between faiths?",
      ["Respect and willingness to understand", "Prejudice", "Refusal to listen", "Contempt"], "Respect and willingness to understand",
      "Respect and the willingness to understand others support peace.", "ERR_LO_G9CRA3_ATTITUDE", 1),
    {
      question: "Sort each action into PROMOTES peace or HARMS peace.",
      input_type: "sort-buckets",
      buckets: [{ id: "peace", label: "Promotes peace" }, { id: "harm", label: "Harms peace" }],
      items: [
        { id: "i1", text: "Interfaith dialogue", correct_bucket: "peace" },
        { id: "i2", text: "Joint charity work", correct_bucket: "peace" },
        { id: "i3", text: "Mocking another religion", correct_bucket: "harm" },
        { id: "i4", text: "Spreading religious hatred", correct_bucket: "harm" },
      ],
      expected: "Dialogue and joint charity promote peace; mockery and hatred harm it.",
      pass_threshold: 0.75,
      memo: "Respect and cooperation build peace; mockery and hatred destroy it.",
      error_signals: ["ERR_LO_G9CRA3_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for an interfaith peace project in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Find common values across the faiths" },
        { id: "s2", text: "Plan a shared project (e.g. charity)" },
        { id: "s3", text: "Work together respectfully" },
        { id: "s4", text: "Celebrate the peace and unity built" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Find common values, plan a shared project, work together respectfully, then celebrate the unity built.",
      memo: "Build peace by finding common values, planning together, cooperating and celebrating unity.",
      error_signals: ["ERR_LO_G9CRA3_SEQ"], difficulty: 2,
    },
    TF("Respecting beliefs different from your own helps build peace.", "True",
      "Respecting different beliefs reduces conflict and helps build peace.", "ERR_LO_G9CRA3_RESPECT2", 1),
    MC("The key idea of religions and peace is that faith can…",
      ["encourage compassion, forgiveness and cooperation", "only cause conflict", "do nothing useful", "spread hatred"], "encourage compassion, forgiveness and cooperation",
      "Religions can encourage compassion, forgiveness and cooperation that build peace.", "ERR_LO_G9CRA3_SUMMARY", 2),
  ],

  // CR.A4 · Sport ethics
  "LO.G9.CR.A4": [
    MC("What are 'sport ethics'?",
      ["Honest, fair and respectful behaviour in sport", "Winning by cheating", "Doping to win", "Hurting opponents"], "Honest, fair and respectful behaviour in sport",
      "Sport ethics means honesty, fair play and respect in all physical activities.", "ERR_LO_G9CRA4_DEF", 1),
    TF("Cheating and doping go against sport ethics.", "True",
      "Cheating and doping violate sport ethics, which value honesty and fairness.", "ERR_LO_G9CRA4_CHEAT", 1),
    MC("Which is ETHICAL behaviour in sport?",
      ["Respecting opponents and officials", "Diving to fool the referee", "Using banned drugs", "Injuring opponents on purpose"], "Respecting opponents and officials",
      "Respecting opponents and officials is ethical sporting behaviour.", "ERR_LO_G9CRA4_ETHICAL", 1),
    CLOZE("Using banned substances to perform better is called ____.",
      ["doping", "training", "stretching", "resting"], "doping",
      "Doping — using banned performance drugs — is cheating and is against sport ethics.", "ERR_LO_G9CRA4_DOPING", 2),
    MC("Why are sport ethics important?",
      ["They keep sport fair, safe and respectful", "They help cheats win", "They ruin sport", "They serve no purpose"], "They keep sport fair, safe and respectful",
      "Sport ethics keep competition fair, safe and respectful for all.", "ERR_LO_G9CRA4_WHY", 1),
    TF("Respecting the rules is part of sport ethics.", "True",
      "Following the rules honestly is a key part of sport ethics.", "ERR_LO_G9CRA4_RULES", 1),
    MC("Which is UNETHICAL in sport?",
      ["Bribing an official", "Shaking hands after a match", "Congratulating winners", "Following the rules"], "Bribing an official",
      "Bribing officials is corrupt and unethical in sport.", "ERR_LO_G9CRA4_UNETHICAL", 2),
    CLOZE("Treating opponents and referees well shows ____ in sport.",
      ["respect", "cheating", "anger", "greed"], "respect",
      "Respect for opponents and officials is central to sport ethics.", "ERR_LO_G9CRA4_RESPECT", 1),
    TF("Sport ethics apply to all physical activities, not just professional sport.", "True",
      "Ethical behaviour applies in all physical activities, at every level.", "ERR_LO_G9CRA4_ALL", 1),
    MC("A teammate offers you a banned substance to boost performance. The ethical choice is to…",
      ["refuse and report it if needed", "take it secretly", "share it with others", "use it just once"], "refuse and report it if needed",
      "Refusing doping and reporting it upholds sport ethics and protects health.", "ERR_LO_G9CRA4_SCENARIO", 3),
    MC("What does 'integrity' mean in sport?",
      ["Being honest and fair even when no one is watching", "Cheating quietly", "Winning at all costs", "Breaking rules cleverly"], "Being honest and fair even when no one is watching",
      "Integrity is being honest and fair, even when no one is watching.", "ERR_LO_G9CRA4_INTEGRITY", 2),
    TF("Accepting defeat graciously is part of ethical sport.", "True",
      "Accepting defeat with grace and respect is part of ethical sport.", "ERR_LO_G9CRA4_DEFEAT", 1),
    CLOZE("Playing honestly and within the rules shows good ____.",
      ["sportsmanship", "cheating", "luck", "secrets"], "sportsmanship",
      "Good sportsmanship means playing honestly and within the rules.", "ERR_LO_G9CRA4_SPORTSMANSHIP", 1),
    MC("Why is doping dangerous as well as unethical?",
      ["It can harm health and gives an unfair advantage", "It improves health", "It is always safe", "It is fair to others"], "It can harm health and gives an unfair advantage",
      "Doping harms health and is unfair, making it both dangerous and unethical.", "ERR_LO_G9CRA4_DANGER", 2),
    TF("Encouraging fair play in others is part of good sport ethics.", "True",
      "Promoting fair play in others reflects good personal sport ethics.", "ERR_LO_G9CRA4_ENCOURAGE", 1),
    MC("A player dives to trick the referee into a penalty. This is…",
      ["unethical, against fair play", "smart and ethical", "good sportsmanship", "within the spirit of sport"], "unethical, against fair play",
      "Diving to deceive the referee is cheating and against sport ethics.", "ERR_LO_G9CRA4_DIVE", 2),
    {
      question: "Sort each behaviour into ETHICAL or UNETHICAL in sport.",
      input_type: "sort-buckets",
      buckets: [{ id: "ethical", label: "Ethical" }, { id: "unethical", label: "Unethical" }],
      items: [
        { id: "i1", text: "Respecting the referee's decision", correct_bucket: "ethical" },
        { id: "i2", text: "Congratulating the winners", correct_bucket: "ethical" },
        { id: "i3", text: "Doping to win", correct_bucket: "unethical" },
        { id: "i4", text: "Deliberately injuring an opponent", correct_bucket: "unethical" },
      ],
      expected: "Respecting officials and congratulating winners are ethical; doping and injuring are unethical.",
      pass_threshold: 0.75,
      memo: "Ethical sport is honest and respectful; unethical sport cheats and harms.",
      error_signals: ["ERR_LO_G9CRA4_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for handling an offer to cheat in sport in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise the offer breaks the rules" },
        { id: "s2", text: "Refuse firmly" },
        { id: "s3", text: "Explain why you compete fairly" },
        { id: "s4", text: "Report it if it continues" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise it breaks the rules, refuse firmly, explain fair competition, then report if needed.",
      memo: "Handle cheating offers by recognising, refusing, explaining and reporting.",
      error_signals: ["ERR_LO_G9CRA4_SEQ"], difficulty: 2,
    },
    TF("Sport ethics and honesty matter even when no one is watching.", "True",
      "Integrity means being honest and fair even when no one is watching.", "ERR_LO_G9CRA4_WATCHING", 1),
    MC("The key idea of sport ethics is to…",
      ["compete honestly, fairly and with respect", "win by any means", "cheat cleverly", "harm opponents"], "compete honestly, fairly and with respect",
      "Sport ethics means competing honestly, fairly and with respect.", "ERR_LO_G9CRA4_SUMMARY", 2),
  ],
};

export default G9;
