// ─── Life Orientation SP — Grade 7 authored pools (part 1: DS · HE) ──────────
//
// Keyed by skill id → question array. Refs are auto-assigned by the generator
// (build-life-orientation-sp.mjs), so questions here omit `ref`. Every item is
// tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
// LO is decision-based, so many `choice` stems pose a real-life situation and
// ask for the best response.
//
// Mechanic payload shapes (see types/life-orientation-sp.ts):
//   choice/true-false/cloze : options[] + expected
//   sequence                : items[{id,text}] + expected_order[ids]
//   sort-buckets            : buckets[{id,label}] + items[{id,text,correct_bucket}] + pass_threshold
//
// CAPS Grade 7 topics here:
//   Development of the self in society · Health, social & environmental responsibility

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7 = {
  // ════════════════ DEVELOPMENT OF THE SELF IN SOCIETY (Term 1) ════════════════
  // DS.A1 · Self-image
  "LO.G7.DS.A1": [
    MC("What does the term 'self-image' mean?",
      ["The way you see and feel about yourself", "How rich your family is", "The clothes you own", "Your school marks only"], "The way you see and feel about yourself",
      "Self-image is the picture you hold of yourself — your view of your own worth, looks and abilities.", "ERR_LO_G7DSA1_DEF", 1),
    TF("A positive self-image means thinking you are perfect and never make mistakes.", "False",
      "A healthy self-image is realistic — you value yourself while accepting that everyone has flaws and can grow.", "ERR_LO_G7DSA1_PERFECT", 1),
    MC("Thabo keeps telling himself 'I am hopeless at everything.' What is the BEST way for him to build a healthier self-image?",
      ["Notice his real strengths and speak kindly to himself", "Compare himself to others all day", "Give up on schoolwork", "Wait for others to praise him first"], "Notice his real strengths and speak kindly to himself",
      "Recognising your genuine strengths and using positive self-talk builds a healthier self-image.", "ERR_LO_G7DSA1_BUILD", 2),
    CLOZE("Treating yourself with kindness and valuing your own worth is called respect for ____.",
      ["self", "money", "fashion", "fame"], "self",
      "Respect for self means valuing who you are; it is the foundation of a healthy self-image.", "ERR_LO_G7DSA1_RESPECTSELF", 1),
    MC("Which action shows RESPECT for others' self-image?",
      ["Encouraging a classmate who is nervous", "Laughing at someone's accent", "Spreading a rumour", "Ignoring a new learner"], "Encouraging a classmate who is nervous",
      "Encouraging and including others lifts their self-image; mocking or excluding harms it.", "ERR_LO_G7DSA1_RESPECTOTHERS", 1),
    TF("Respecting diversity means valuing people who are different from you.", "True",
      "Respect for diversity means accepting and valuing differences in culture, looks, ability and beliefs.", "ERR_LO_G7DSA1_DIVERSITY", 1),
    MC("Which of these is a personal STRENGTH you might list when thinking about yourself?",
      ["I am a loyal friend", "I own the latest phone", "My cousin is famous", "I live in a big house"], "I am a loyal friend",
      "Personal strengths are qualities inside you, like loyalty or kindness — not possessions.", "ERR_LO_G7DSA1_STRENGTH", 2),
    CLOZE("Your interests, abilities and ____ all make up who you are.",
      ["potential", "shoes", "money", "address"], "potential",
      "Knowing your interests, abilities and potential helps you understand and value yourself.", "ERR_LO_G7DSA1_POTENTIAL", 1),
    MC("A friend says something unkind about your appearance. Which response protects your self-image without hurting them?",
      ["Calmly say it hurt you and that you value yourself", "Insult them back harder", "Believe it and feel worthless", "Never speak to anyone again"], "Calmly say it hurt you and that you value yourself",
      "Assertively naming the hurt while still valuing yourself protects your self-image and the relationship.", "ERR_LO_G7DSA1_RESPONSE", 3),
    TF("The way your family and friends treat you can influence your self-image.", "True",
      "Relationships with self, family and friends all shape how you see yourself.", "ERR_LO_G7DSA1_RELATIONSHIPS", 1),
    MC("Which is a POSITIVE action that strengthens your self-image?",
      ["Setting a small goal and achieving it", "Quitting whenever something is hard", "Putting yourself down", "Only noticing your faults"], "Setting a small goal and achieving it",
      "Achieving goals, however small, gives a sense of competence that strengthens self-image.", "ERR_LO_G7DSA1_POSITIVEACTION", 2),
    CLOZE("Believing in your own abilities gives you self-____.",
      ["confidence", "doubt", "pity", "blame"], "confidence",
      "Self-confidence is trusting your own abilities; it grows from positive experiences and self-talk.", "ERR_LO_G7DSA1_CONFIDENCE", 1),
    MC("Why is a healthy self-image important for a teenager?",
      ["It helps you make good choices and resist pressure", "It guarantees you will be rich", "It means you never feel sad", "It stops all change"], "It helps you make good choices and resist pressure",
      "A healthy self-image supports good decision-making and the confidence to resist harmful pressure.", "ERR_LO_G7DSA1_WHY", 2),
    TF("Putting other people down is a good way to feel better about yourself.", "False",
      "Tearing others down damages relationships and does not build a genuine, lasting self-image.", "ERR_LO_G7DSA1_PUTDOWN", 1),
    MC("Which sentence is an example of POSITIVE self-talk?",
      ["'I can improve if I keep trying'", "'I always fail'", "'There is no point'", "'Everyone is better than me'"], "'I can improve if I keep trying'",
      "Positive self-talk focuses on growth and effort, which builds a healthy self-image.", "ERR_LO_G7DSA1_SELFTALK", 2),
    MC("A new learner joins your class and seems shy. What helps THEIR self-image most?",
      ["Welcome them and introduce them to others", "Stare and whisper about them", "Leave them to sit alone", "Tease their uniform"], "Welcome them and introduce them to others",
      "Including and welcoming others shows respect and helps build their self-image.", "ERR_LO_G7DSA1_NEWLEARNER", 1),
    TF("Accepting that you have both strengths and weaknesses is part of a healthy self-image.", "True",
      "Self-acceptance — owning both strengths and weaknesses — is central to a realistic, healthy self-image.", "ERR_LO_G7DSA1_ACCEPT", 1),
    CLOZE("Showing you value other people's worth is called respect for ____.",
      ["others", "yourself", "winning", "rules"], "others",
      "Respect for others means valuing their worth, feelings and differences.", "ERR_LO_G7DSA1_RESPECTOTHERS2", 1),
    MC("Which is the BEST long-term way to improve self-image?",
      ["Build real skills and treat yourself and others well", "Buy expensive things", "Win every argument", "Avoid all challenges"], "Build real skills and treat yourself and others well",
      "Genuine self-image grows from real competence and respectful relationships, not from possessions or winning.", "ERR_LO_G7DSA1_LONGTERM", 3),
    {
      question: "Sort each action into whether it BUILDS UP or BREAKS DOWN self-image.",
      input_type: "sort-buckets",
      buckets: [{ id: "build", label: "Builds up" }, { id: "break", label: "Breaks down" }],
      items: [
        { id: "i1", text: "Praising a friend's effort", correct_bucket: "build" },
        { id: "i2", text: "Setting and reaching a goal", correct_bucket: "build" },
        { id: "i3", text: "Bullying someone online", correct_bucket: "break" },
        { id: "i4", text: "Constantly criticising yourself", correct_bucket: "break" },
      ],
      expected: "Praise and reaching goals build self-image; bullying and harsh self-criticism break it down.",
      pass_threshold: 0.75,
      memo: "Encouragement and achievement build self-image; cruelty and harsh self-criticism damage it.",
      error_signals: ["ERR_LO_G7DSA1_SORT"], difficulty: 2,
    },
  ],

  // DS.A2 · Puberty and gender constructs
  "LO.G7.DS.A2": [
    MC("What is puberty?",
      ["The stage when the body changes from a child's into an adult's", "A type of school subject", "A sickness you must treat", "A kind of sport"], "The stage when the body changes from a child's into an adult's",
      "Puberty is the natural stage when the body matures from childhood toward adulthood.", "ERR_LO_G7DSA2_DEF", 1),
    TF("Everyone goes through puberty at exactly the same age.", "False",
      "Puberty starts and progresses at different ages for different people — there is no single 'correct' time.", "ERR_LO_G7DSA2_SAMEAGE", 1),
    MC("Which of these is a PHYSICAL change during puberty?",
      ["Body hair grows", "You forget your name", "You shrink in height", "Your eyes change colour"], "Body hair grows",
      "Physical changes in puberty include growth, body hair, and the body maturing — these are normal.", "ERR_LO_G7DSA2_PHYSICAL", 1),
    MC("Which of these is an EMOTIONAL change many teenagers notice during puberty?",
      ["Stronger and changing moods", "Becoming a baby again", "Never feeling anything", "Losing all memory"], "Stronger and changing moods",
      "Mood changes and stronger emotions are common emotional changes during puberty.", "ERR_LO_G7DSA2_EMOTIONAL", 1),
    CLOZE("The physical and emotional changes of puberty are completely ____.",
      ["normal", "dangerous", "rare", "wrong"], "normal",
      "These changes are a normal, healthy part of growing up that everyone experiences.", "ERR_LO_G7DSA2_NORMAL", 1),
    TF("It is respectful to tease someone about how their body is changing.", "False",
      "Teasing about body changes is disrespectful and harmful; we should respect our own and others' changes.", "ERR_LO_G7DSA2_TEASE", 1),
    MC("A friend feels embarrassed about changes in their body. What is the kind, respectful response?",
      ["Reassure them that the changes are normal for everyone", "Laugh and tell others", "Tell them something is wrong with them", "Ignore them completely"], "Reassure them that the changes are normal for everyone",
      "Reassurance and respect help a friend feel safe; the changes are normal for everyone.", "ERR_LO_G7DSA2_FRIEND", 2),
    CLOZE("Ideas a society has about how boys and girls 'should' behave are called gender ____.",
      ["constructs", "puberty", "diseases", "muscles"], "constructs",
      "Gender constructs are society's ideas about how boys and girls should act — they are learned, not fixed.", "ERR_LO_G7DSA2_CONSTRUCT", 2),
    TF("Boys are not allowed to cry or show emotion — this is a healthy rule.", "False",
      "The idea that boys must not show emotion is a harmful gender stereotype; everyone has feelings.", "ERR_LO_G7DSA2_STEREOTYPE", 2),
    MC("Which statement challenges an unfair gender stereotype?",
      ["Both girls and boys can be leaders and carers", "Only boys can be strong", "Only girls can cook", "Girls cannot do science"], "Both girls and boys can be leaders and carers",
      "People of any gender can lead, care, cook or do science; rigid roles are unfair stereotypes.", "ERR_LO_G7DSA2_CHALLENGE", 2),
    MC("How do puberty changes affect relationships with friends and family?",
      ["Feelings and reactions may change, so communication matters more", "Relationships stay exactly the same", "You must end all friendships", "Family stops caring"], "Feelings and reactions may change, so communication matters more",
      "Changing emotions can affect relationships, so honest communication and patience help.", "ERR_LO_G7DSA2_RELATIONSHIPS", 2),
    TF("Keeping clean and looking after your body is important during puberty.", "True",
      "Good hygiene becomes especially important during puberty as the body changes.", "ERR_LO_G7DSA2_HYGIENE", 1),
    CLOZE("Accepting the changes in your body shows ____ for yourself.",
      ["respect", "anger", "fear", "shame"], "respect",
      "Accepting your body's changes is a way of respecting yourself.", "ERR_LO_G7DSA2_RESPECT", 1),
    MC("Which is the healthiest attitude toward puberty?",
      ["It is a natural stage I can understand and accept", "It is shameful and secret", "It means something is wrong", "I should fight against it"], "It is a natural stage I can understand and accept",
      "Understanding and accepting puberty as natural leads to the healthiest attitude.", "ERR_LO_G7DSA2_ATTITUDE", 2),
    TF("Girls and boys both experience physical and emotional changes during puberty.", "True",
      "Both girls and boys go through physical and emotional changes, though some differ.", "ERR_LO_G7DSA2_BOTH", 1),
    MC("Where can a teenager get trustworthy information about puberty?",
      ["A parent, teacher, nurse or reliable health book", "Rumours from the playground", "Random comments online with no source", "Guessing alone"], "A parent, teacher, nurse or reliable health book",
      "Trusted adults and reliable health sources give accurate information about puberty.", "ERR_LO_G7DSA2_INFO", 2),
    MC("A classmate says 'real men don't ask for help.' Why is this idea a problem?",
      ["It stops boys getting support they need", "It is good advice", "It helps boys stay healthy", "It has no effect"], "It stops boys getting support they need",
      "This harmful gender construct discourages help-seeking, which can hurt mental and physical health.", "ERR_LO_G7DSA2_MENHELP", 3),
    TF("Appreciating and accepting yourself and others is part of growing up well.", "True",
      "Self-acceptance and accepting others are healthy parts of development during puberty.", "ERR_LO_G7DSA2_APPRECIATE", 1),
    {
      question: "Sort each change into PHYSICAL or EMOTIONAL.",
      input_type: "sort-buckets",
      buckets: [{ id: "phys", label: "Physical" }, { id: "emot", label: "Emotional" }],
      items: [
        { id: "i1", text: "Growing taller", correct_bucket: "phys" },
        { id: "i2", text: "Voice deepening", correct_bucket: "phys" },
        { id: "i3", text: "Feeling moody more often", correct_bucket: "emot" },
        { id: "i4", text: "Becoming more self-conscious", correct_bucket: "emot" },
      ],
      expected: "Growing taller and a deepening voice are physical; moodiness and self-consciousness are emotional.",
      pass_threshold: 0.75,
      memo: "Physical changes affect the body; emotional changes affect feelings and moods.",
      error_signals: ["ERR_LO_G7DSA2_SORT"], difficulty: 2,
    },
    TF("Comparing your body to other people's can cause needless worry during puberty.", "True",
      "Everyone develops at their own pace, so comparing yourself to others often causes unnecessary worry.", "ERR_LO_G7DSA2_COMPARE", 2),
  ],

  // DS.A3 · Peer pressure
  "LO.G7.DS.A3": [
    MC("What is peer pressure?",
      ["Influence from people your own age to act in a certain way", "Pressure from teachers only", "A type of exam", "Stress about the weather"], "Influence from people your own age to act in a certain way",
      "Peer pressure is the influence that people of your own age group have on your choices and behaviour.", "ERR_LO_G7DSA3_DEF", 1),
    TF("Peer pressure is always negative.", "False",
      "Peer pressure can be positive (friends encouraging study or sport) or negative (pushing risky behaviour).", "ERR_LO_G7DSA3_ALWAYSNEG", 1),
    MC("Which is an example of NEGATIVE peer pressure?",
      ["Friends daring you to skip class", "Friends helping you revise", "A friend encouraging exercise", "A friend praising your art"], "Friends daring you to skip class",
      "Negative peer pressure pushes you toward harmful or risky behaviour like skipping class.", "ERR_LO_G7DSA3_NEGATIVE", 1),
    MC("Which is an example of POSITIVE peer pressure?",
      ["A friend who motivates you to join a study group", "Friends pressuring you to smoke", "Friends daring you to steal", "Friends mocking your goals"], "A friend who motivates you to join a study group",
      "Positive peer pressure encourages healthy, helpful choices.", "ERR_LO_G7DSA3_POSITIVE", 1),
    CLOZE("Saying 'no' in a calm, confident and firm way is being ____.",
      ["assertive", "aggressive", "shy", "rude"], "assertive",
      "Assertiveness means standing up for yourself calmly and confidently, without being aggressive.", "ERR_LO_G7DSA3_ASSERTIVE", 2),
    MC("Friends pressure Lerato to bunk school. Which response is ASSERTIVE?",
      ["'No thanks, I'm going to class' said calmly", "Shouting and shoving them", "Going along to avoid the fuss", "Crying and running away"], "'No thanks, I'm going to class' said calmly",
      "An assertive response is calm, clear and firm — neither aggressive nor giving in.", "ERR_LO_G7DSA3_RESPONSE", 2),
    TF("Negotiation skills include being able to disagree in a constructive way.", "True",
      "Negotiation means working out a solution and being able to disagree respectfully and constructively.", "ERR_LO_G7DSA3_NEGOTIATE", 1),
    MC("Peer pressure may push teenagers toward which risky behaviour?",
      ["Using substances or bullying", "Doing homework", "Eating breakfast", "Sleeping well"], "Using substances or bullying",
      "Negative peer pressure can push toward substances, crime, unhealthy behaviour and bullying.", "ERR_LO_G7DSA3_RISKY", 1),
    CLOZE("If pressure becomes too much, it is wise to find ____.",
      ["help", "trouble", "money", "fame"], "help",
      "Knowing where to find help — a trusted adult, counsellor or helpline — is an important coping skill.", "ERR_LO_G7DSA3_HELP", 1),
    MC("Who is a good person to ask for help with serious peer pressure?",
      ["A trusted teacher, parent or school counsellor", "The very people pressuring you", "Nobody — keep it secret", "A stranger online"], "A trusted teacher, parent or school counsellor",
      "Trusted adults like teachers, parents and counsellors can help you handle serious pressure.", "ERR_LO_G7DSA3_WHOHELP", 2),
    TF("Giving in to negative peer pressure is the only way to keep friends.", "False",
      "Real friends respect your choices; you can keep good friends while refusing harmful pressure.", "ERR_LO_G7DSA3_KEEPFRIENDS", 2),
    MC("What is the difference between being assertive and being aggressive?",
      ["Assertive is calm and firm; aggressive is hostile and forceful", "They are exactly the same", "Assertive means staying silent", "Aggressive means being polite"], "Assertive is calm and firm; aggressive is hostile and forceful",
      "Assertiveness respects everyone; aggression tries to dominate or harm.", "ERR_LO_G7DSA3_VSAGG", 2),
    MC("A friend keeps pushing you to share answers in a test. The BEST coping skill is to…",
      ["firmly refuse and explain it is cheating", "give in quietly", "copy so they stop", "report nothing and feel guilty"], "firmly refuse and explain it is cheating",
      "Refusing firmly and explaining your reason is an assertive, honest coping skill.", "ERR_LO_G7DSA3_TEST", 2),
    TF("Coping skills help you handle pressure without harming yourself or others.", "True",
      "Coping skills like assertiveness and seeking help manage pressure in healthy ways.", "ERR_LO_G7DSA3_COPING", 1),
    CLOZE("Being able to influence others toward good choices is ____ peer pressure.",
      ["positive", "negative", "secret", "illegal"], "positive",
      "You can be a positive influence on your peers, encouraging good choices.", "ERR_LO_G7DSA3_POSINFLUENCE", 1),
    MC("Which sign suggests a friendship is unhealthy?",
      ["They only want you around if you do what they say", "They respect your 'no'", "They support your goals", "They listen to you"], "They only want you around if you do what they say",
      "Conditional friendship that punishes your 'no' is a sign of unhealthy pressure.", "ERR_LO_G7DSA3_UNHEALTHY", 2),
    MC("Sipho is dared to bully a younger learner to 'prove' he is cool. The responsible choice is to…",
      ["refuse and, if needed, report the bullying", "do it once to fit in", "watch silently", "join in a little"], "refuse and, if needed, report the bullying",
      "Refusing and reporting protects the younger learner and shows responsible courage.", "ERR_LO_G7DSA3_BULLY", 3),
    TF("Practising what you will say in advance can make it easier to resist pressure.", "True",
      "Rehearsing a firm response ahead of time makes assertiveness easier in the moment.", "ERR_LO_G7DSA3_REHEARSE", 1),
    {
      question: "Put the steps for handling negative peer pressure in a sensible order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise the pressure is pushing you toward something harmful" },
        { id: "s2", text: "Decide on your own values and what you want" },
        { id: "s3", text: "Say no calmly and firmly (be assertive)" },
        { id: "s4", text: "If it continues, walk away and find help" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise the pressure, decide your values, refuse assertively, then walk away and find help if needed.",
      memo: "First notice the pressure, know your own mind, refuse assertively, and seek help if it continues.",
      error_signals: ["ERR_LO_G7DSA3_SEQ"], difficulty: 2,
    },
    MC("Why are negotiation skills useful with peers?",
      ["They let you disagree and still keep respect", "They force others to obey you", "They help you win every fight", "They avoid all conversation"], "They let you disagree and still keep respect",
      "Negotiation lets you disagree constructively while keeping the relationship respectful.", "ERR_LO_G7DSA3_NEGUSE", 2),
  ],

  // DS.A4 · Personal diet and nutrition
  "LO.G7.DS.A4": [
    MC("What does 'nutrition' refer to?",
      ["The food and nutrients your body needs to stay healthy", "The price of food only", "The colour of your plate", "How fast you eat"], "The food and nutrients your body needs to stay healthy",
      "Nutrition is about the nutrients in food that the body needs to grow and stay healthy.", "ERR_LO_G7DSA4_DEF", 1),
    TF("A balanced diet includes a variety of food groups in the right amounts.", "True",
      "A balanced diet provides variety from all food groups in suitable amounts.", "ERR_LO_G7DSA4_BALANCED", 1),
    MC("Which factor can influence the food a person chooses?",
      ["Culture, cost and what is available", "The day of the week only", "Their shoe size", "The colour of their bag"], "Culture, cost and what is available",
      "Diet choices are shaped by ecological, social, economic, cultural and political factors.", "ERR_LO_G7DSA4_FACTORS", 2),
    CLOZE("Foods that give the body energy and help it grow are full of ____.",
      ["nutrients", "plastic", "noise", "colours"], "nutrients",
      "Nutrients (like protein, carbohydrates, vitamins) give energy and help the body grow and repair.", "ERR_LO_G7DSA4_NUTRIENTS", 1),
    MC("Which is the healthier swap to improve a diet?",
      ["Fruit instead of sweets as a snack", "More fizzy drinks instead of water", "Skipping breakfast", "Adding extra sugar"], "Fruit instead of sweets as a snack",
      "Swapping sweets for fruit improves nutritional value — a simple, healthy change.", "ERR_LO_G7DSA4_SWAP", 1),
    TF("Drinking water instead of sugary drinks is a good way to improve your diet.", "True",
      "Choosing water over sugary drinks reduces sugar intake and improves health.", "ERR_LO_G7DSA4_WATER", 1),
    MC("Why might two families eat very different meals?",
      ["Different cultures, budgets and what foods they can get", "One family is better than the other", "Food has no link to culture", "Everyone must eat the same"], "Different cultures, budgets and what foods they can get",
      "Culture, income and availability all shape what different families eat.", "ERR_LO_G7DSA4_DIFFERENT", 2),
    CLOZE("Eating too much sugar and fatty food can lead to ____ problems.",
      ["health", "musical", "spelling", "weather"], "health",
      "Poor diet high in sugar and fat is linked to health problems like obesity and diabetes.", "ERR_LO_G7DSA4_HEALTHPROB", 1),
    MC("Which is the BEST description of a plan for healthy eating habits?",
      ["Eat varied, balanced meals and limit junk food", "Eat only one food forever", "Skip meals to save time", "Eat sweets at every meal"], "Eat varied, balanced meals and limit junk food",
      "A healthy-eating plan means variety, balance and limiting junk food.", "ERR_LO_G7DSA4_PLAN", 2),
    TF("Cost is one economic factor that affects what people can eat.", "True",
      "Economic factors like cost and income strongly affect food choices.", "ERR_LO_G7DSA4_COST", 1),
    MC("Fruit and vegetables are important mainly because they…",
      ["provide vitamins and fibre for good health", "are always the cheapest", "taste like sweets", "have no nutrients"], "provide vitamins and fibre for good health",
      "Fruit and vegetables supply vitamins, minerals and fibre that keep the body healthy.", "ERR_LO_G7DSA4_FRUITVEG", 1),
    MC("Naledi wants to improve her diet on a tight budget. A realistic step is to…",
      ["choose affordable, filling foods like beans, samp and seasonal veg", "buy only expensive imported snacks", "stop eating to save money", "eat fast food daily"], "choose affordable, filling foods like beans, samp and seasonal veg",
      "Affordable staples like beans, samp and seasonal vegetables improve nutrition on a budget.", "ERR_LO_G7DSA4_BUDGET", 3),
    TF("Eating a wide variety of foods helps you get different nutrients.", "True",
      "Variety helps ensure you get the full range of nutrients your body needs.", "ERR_LO_G7DSA4_VARIETY", 1),
    CLOZE("A meal with protein, carbohydrates and vegetables is more ____ than chips alone.",
      ["balanced", "expensive", "colourful", "salty"], "balanced",
      "Combining food groups makes a meal more balanced and nutritious.", "ERR_LO_G7DSA4_BALANCE2", 2),
    MC("Which is a SOCIAL factor that influences diet?",
      ["Family traditions and what friends eat", "The temperature of the room", "The size of your feet", "The day's date"], "Family traditions and what friends eat",
      "Social factors include family customs and the eating habits of those around you.", "ERR_LO_G7DSA4_SOCIAL", 2),
    TF("Healthy eating has no effect on your energy or concentration at school.", "False",
      "Good nutrition improves energy and concentration, helping you learn better.", "ERR_LO_G7DSA4_ENERGY", 1),
    MC("Skipping breakfast often leads to…",
      ["low energy and poor concentration", "better marks", "more height", "stronger eyesight"], "low energy and poor concentration",
      "Skipping breakfast can lower energy and concentration during the school day.", "ERR_LO_G7DSA4_BREAKFAST", 2),
    {
      question: "Sort each choice into HEALTHIER or LESS HEALTHY.",
      input_type: "sort-buckets",
      buckets: [{ id: "good", label: "Healthier" }, { id: "bad", label: "Less healthy" }],
      items: [
        { id: "i1", text: "A bowl of fruit", correct_bucket: "good" },
        { id: "i2", text: "A glass of water", correct_bucket: "good" },
        { id: "i3", text: "A large fizzy drink", correct_bucket: "bad" },
        { id: "i4", text: "A packet of sweets for lunch", correct_bucket: "bad" },
      ],
      expected: "Fruit and water are healthier; fizzy drinks and sweets for lunch are less healthy.",
      pass_threshold: 0.75,
      memo: "Whole foods and water are healthier; sugary drinks and sweets are less nutritious.",
      error_signals: ["ERR_LO_G7DSA4_SORT"], difficulty: 1,
    },
    MC("A 'personal diet plan' is useful because it…",
      ["helps you set realistic goals to eat better", "forces everyone to eat the same", "is only for athletes", "replaces all food with pills"], "helps you set realistic goals to eat better",
      "A personal plan sets realistic, individual goals to improve eating habits.", "ERR_LO_G7DSA4_PERSONALPLAN", 2),
    TF("Eating a healthy breakfast can improve your concentration at school.", "True",
      "A good breakfast gives steady energy that improves concentration and learning.", "ERR_LO_G7DSA4_BREAKFAST2", 1),
  ],

  // ════════════ HEALTH, SOCIAL & ENVIRONMENTAL RESPONSIBILITY (Term 3) ══════════
  // HE.A1 · Substance abuse
  "LO.G7.HE.A1": [
    MC("What is substance abuse?",
      ["The harmful or unsafe use of drugs, alcohol or other substances", "Drinking water", "Eating vegetables", "Doing exercise"], "The harmful or unsafe use of drugs, alcohol or other substances",
      "Substance abuse is using drugs, alcohol or other substances in harmful, unsafe ways.", "ERR_LO_G7HEA1_DEF", 1),
    TF("Alcohol and tobacco are examples of substances that can be abused.", "True",
      "Alcohol and tobacco, along with illegal drugs and some medicines, can be abused.", "ERR_LO_G7HEA1_EXAMPLES", 1),
    MC("Which is a possible SYMPTOM of substance abuse?",
      ["Sudden change in behaviour and dropping marks", "Reading more books", "Eating healthy meals", "Sleeping normally"], "Sudden change in behaviour and dropping marks",
      "Warning signs include behaviour changes, falling marks, mood swings and withdrawal.", "ERR_LO_G7HEA1_SYMPTOM", 2),
    CLOZE("Catching a problem early is called early ____.",
      ["detection", "payment", "cooking", "running"], "detection",
      "Early detection means noticing the warning signs early so help can be given sooner.", "ERR_LO_G7HEA1_DETECTION", 1),
    MC("Which is a PERSONAL (intrapersonal) factor that may contribute to substance abuse?",
      ["Low self-esteem or stress", "Sunny weather", "A new timetable", "A long holiday"], "Low self-esteem or stress",
      "Intrapersonal factors come from within, like low self-esteem, stress or curiosity.", "ERR_LO_G7HEA1_INTRA", 2),
    MC("Which is an INTERPERSONAL factor that may contribute to substance abuse?",
      ["Pressure from friends who use substances", "Your own private thoughts", "Your height", "The school bell"], "Pressure from friends who use substances",
      "Interpersonal factors involve other people, like peer pressure or family use.", "ERR_LO_G7HEA1_INTER", 2),
    TF("Protective factors are things that lower the chance of substance abuse.", "True",
      "Protective factors — like good self-esteem, supportive family and hobbies — reduce the risk.", "ERR_LO_G7HEA1_PROTECTIVE", 1),
    MC("Which is a PROTECTIVE factor against substance abuse?",
      ["Strong self-esteem and supportive friends", "Boredom and isolation", "Easy access to drugs", "No goals at all"], "Strong self-esteem and supportive friends",
      "Self-esteem, support, goals and healthy hobbies protect against substance abuse.", "ERR_LO_G7HEA1_PROTECTEX", 2),
    CLOZE("Stopping a problem before it starts is called ____.",
      ["prevention", "celebration", "decoration", "imagination"], "prevention",
      "Prevention means taking steps to stop substance abuse before it begins.", "ERR_LO_G7HEA1_PREVENTION", 1),
    TF("Substance abuse only affects the person using; it never affects family or friends.", "False",
      "Substance abuse harms the user and also affects family, friends and the community.", "ERR_LO_G7HEA1_ONLYUSER", 1),
    MC("A friend shows sudden mood swings, skips school and avoids old friends. These could be…",
      ["warning signs worth talking to a trusted adult about", "always nothing to worry about", "proof they are fine", "a reason to gossip"], "warning signs worth talking to a trusted adult about",
      "Such changes can be warning signs; the caring response is to involve a trusted adult.", "ERR_LO_G7HEA1_WARNING", 3),
    MC("What is the healthiest way to deal with stress instead of using substances?",
      ["Exercise, talk to someone, or use a hobby", "Use alcohol to forget", "Bottle it up alone", "Smoke to relax"], "Exercise, talk to someone, or use a hobby",
      "Healthy coping (exercise, talking, hobbies) handles stress without the harm of substances.", "ERR_LO_G7HEA1_STRESS", 2),
    TF("Saying no to substances is easier when you have planned what to say.", "True",
      "Having a refusal plan ready makes it easier to say no in the moment.", "ERR_LO_G7HEA1_REFUSE", 1),
    CLOZE("Substances that change how the brain and body work can cause ____.",
      ["harm", "wealth", "height", "talent"], "harm",
      "Abused substances change brain and body function and can cause serious harm.", "ERR_LO_G7HEA1_HARM", 1),
    MC("Where can someone struggling with substance abuse find help?",
      ["A clinic, counsellor or helpline like SANCA", "Nowhere at all", "Only from dealers", "By keeping it secret forever"], "A clinic, counsellor or helpline like SANCA",
      "Clinics, counsellors and organisations like SANCA offer help, care and support.", "ERR_LO_G7HEA1_HELP", 2),
    TF("Curiosity and wanting to fit in are reasons some young people try substances.", "True",
      "Curiosity and the wish to fit in are common reasons young people first try substances.", "ERR_LO_G7HEA1_CURIOSITY", 1),
    MC("Why is prevention better than treatment for substance abuse?",
      ["It stops the harm before it happens", "It costs more and helps less", "It is impossible", "It only helps adults"], "It stops the harm before it happens",
      "Prevention avoids the harm altogether, which is better than treating it later.", "ERR_LO_G7HEA1_PREVBETTER", 2),
    {
      question: "Sort each item into a RISK factor or a PROTECTIVE factor for substance abuse.",
      input_type: "sort-buckets",
      buckets: [{ id: "risk", label: "Risk factor" }, { id: "protect", label: "Protective factor" }],
      items: [
        { id: "i1", text: "Low self-esteem", correct_bucket: "risk" },
        { id: "i2", text: "Friends who use drugs", correct_bucket: "risk" },
        { id: "i3", text: "Supportive family", correct_bucket: "protect" },
        { id: "i4", text: "Healthy hobbies and goals", correct_bucket: "protect" },
      ],
      expected: "Low self-esteem and drug-using friends are risks; supportive family and healthy hobbies are protective.",
      pass_threshold: 0.75,
      memo: "Risk factors raise the chance of abuse; protective factors lower it.",
      error_signals: ["ERR_LO_G7HEA1_SORT"], difficulty: 2,
    },
    MC("Which choice best reduces a teenager's likelihood of substance abuse?",
      ["Joining positive activities and building strong support", "Spending time only with users", "Hiding all feelings", "Avoiding all adults"], "Joining positive activities and building strong support",
      "Positive activities and supportive relationships are strong protective factors.", "ERR_LO_G7HEA1_REDUCE", 2),
    TF("It is brave, not weak, to ask for help with a substance-abuse problem.", "True",
      "Reaching out for help takes courage and is the first step toward recovery.", "ERR_LO_G7HEA1_ASKHELP", 1),
  ],

  // HE.A2 · Environmental health
  "LO.G7.HE.A2": [
    MC("What does 'environmental health' mean?",
      ["Keeping our surroundings clean and safe so people stay healthy", "Only the health of animals", "The weather forecast", "Cleaning your room once"], "Keeping our surroundings clean and safe so people stay healthy",
      "Environmental health is about keeping our surroundings clean and safe to protect people's health.", "ERR_LO_G7HEA2_DEF", 1),
    TF("Pollution and dirty water are examples of environmental health problems.", "True",
      "Pollution, dirty water, litter and poor sanitation are environmental health problems.", "ERR_LO_G7HEA2_EXAMPLES", 1),
    MC("Which is a LOCAL environmental health problem a community might face?",
      ["Litter and overflowing rubbish", "A planet in another galaxy", "A maths test", "A football match"], "Litter and overflowing rubbish",
      "Litter, dumping, polluted water and poor sanitation are common local problems.", "ERR_LO_G7HEA2_LOCAL", 1),
    CLOZE("A clear set of steps to solve a problem is called an action ____.",
      ["plan", "movie", "song", "snack"], "plan",
      "An action plan lists the steps a community or person will take to solve a problem.", "ERR_LO_G7HEA2_PLAN", 1),
    MC("Which is a good community action to improve environmental health?",
      ["Organise a clean-up and recycle waste", "Dump rubbish in the river", "Burn plastic in the street", "Ignore the problem"], "Organise a clean-up and recycle waste",
      "Clean-ups and recycling are positive actions that improve environmental health.", "ERR_LO_G7HEA2_ACTION", 1),
    TF("Recycling helps reduce waste and protect the environment.", "True",
      "Recycling reduces waste sent to landfill and protects the environment.", "ERR_LO_G7HEA2_RECYCLE", 1),
    MC("Why is clean water important for environmental health?",
      ["Dirty water spreads disease", "Water has no effect on health", "Clean water tastes worse", "Only animals need water"], "Dirty water spreads disease",
      "Unsafe water spreads diseases like cholera, so clean water is vital for health.", "ERR_LO_G7HEA2_WATER", 2),
    CLOZE("Working out the cause and steps of a problem uses problem-____ skills.",
      ["solving", "making", "hiding", "ignoring"], "solving",
      "Problem-solving skills help you find causes and plan actions to fix a problem.", "ERR_LO_G7HEA2_PROBLEMSOLVE", 1),
    MC("An 'environmentally sound choice' is one that…",
      ["protects rather than harms the environment", "creates the most waste", "uses the most plastic", "pollutes the cheapest way"], "protects rather than harms the environment",
      "Environmentally sound choices protect the environment and reduce harm.", "ERR_LO_G7HEA2_SOUND", 2),
    TF("One person's actions can never make a difference to the environment.", "False",
      "Individual actions add up; each person's choices do make a difference.", "ERR_LO_G7HEA2_ONEPERSON", 1),
    MC("Your area has a litter problem near the school. A good FIRST step in an action plan is to…",
      ["identify the problem and its causes", "give up immediately", "blame everyone and do nothing", "make more litter"], "identify the problem and its causes",
      "A good action plan starts by clearly identifying the problem and its causes.", "ERR_LO_G7HEA2_FIRSTSTEP", 2),
    MC("Which individual habit helps the environment most?",
      ["Reducing, reusing and recycling waste", "Throwing litter on the ground", "Leaving taps running", "Wasting electricity"], "Reducing, reusing and recycling waste",
      "Reduce, reuse, recycle is a key individual habit that protects the environment.", "ERR_LO_G7HEA2_HABIT", 1),
    TF("Poor sanitation, like blocked drains, can cause health problems in a community.", "True",
      "Poor sanitation spreads germs and disease, harming community health.", "ERR_LO_G7HEA2_SANITATION", 1),
    CLOZE("Putting waste in the right bin instead of the street reduces ____.",
      ["pollution", "homework", "rainfall", "sunshine"], "pollution",
      "Correct waste disposal reduces pollution and keeps the area healthier.", "ERR_LO_G7HEA2_POLLUTION", 1),
    MC("A community project to clean a polluted stream is an example of…",
      ["taking responsibility for environmental health", "wasting time", "causing pollution", "ignoring the law"], "taking responsibility for environmental health",
      "Community clean-up projects show responsibility for environmental health.", "ERR_LO_G7HEA2_PROJECT", 2),
    {
      question: "Put the steps of an environmental health action plan in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Identify the environmental problem" },
        { id: "s2", text: "Find out what is causing it" },
        { id: "s3", text: "Plan and carry out an action to fix it" },
        { id: "s4", text: "Check whether the problem improved" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Identify the problem, find the cause, take action, then check if it improved.",
      memo: "A sound action plan: identify, find the cause, act, then evaluate the result.",
      error_signals: ["ERR_LO_G7HEA2_SEQ"], difficulty: 2,
    },
    TF("Planting trees and keeping public spaces clean improve environmental health.", "True",
      "Greening and cleaning public spaces improve both the environment and people's health.", "ERR_LO_G7HEA2_TREES", 1),
    MC("Why should communities work TOGETHER on environmental health?",
      ["Shared effort solves big problems faster", "One person must do everything", "It is against the law", "Teamwork makes pollution worse"], "Shared effort solves big problems faster",
      "Working together pools effort and resources, solving environmental problems faster.", "ERR_LO_G7HEA2_TOGETHER", 2),
    {
      question: "Sort each action into HELPS the environment or HARMS it.",
      input_type: "sort-buckets",
      buckets: [{ id: "help", label: "Helps" }, { id: "harm", label: "Harms" }],
      items: [
        { id: "i1", text: "Recycling bottles", correct_bucket: "help" },
        { id: "i2", text: "Picking up litter", correct_bucket: "help" },
        { id: "i3", text: "Dumping waste in a river", correct_bucket: "harm" },
        { id: "i4", text: "Burning plastic in the open", correct_bucket: "harm" },
      ],
      expected: "Recycling and picking up litter help; dumping waste and burning plastic harm.",
      pass_threshold: 0.75,
      memo: "Reducing waste and cleaning up help the environment; dumping and burning harm it.",
      error_signals: ["ERR_LO_G7HEA2_SORT"], difficulty: 1,
    },
    TF("Saving water and electricity is part of caring for the environment.", "True",
      "Conserving water and electricity reduces waste and protects the environment.", "ERR_LO_G7HEA2_CONSERVE", 1),
  ],

  // HE.A3 · Common diseases
  "LO.G7.HE.A3": [
    MC("Which of these is a common disease covered in Grade 7 Life Orientation?",
      ["Tuberculosis (TB)", "A broken pencil", "A flat tyre", "A power cut"], "Tuberculosis (TB)",
      "Common diseases studied include TB, diabetes, epilepsy, obesity, anorexia and HIV and AIDS.", "ERR_LO_G7HEA3_DISEASE", 1),
    TF("Diabetes is a condition that affects how the body controls blood sugar.", "True",
      "Diabetes affects how the body manages blood sugar (glucose).", "ERR_LO_G7HEA3_DIABETES", 1),
    MC("What is TB (tuberculosis) mainly an illness of?",
      ["The lungs", "The teeth", "The hair", "The fingernails"], "The lungs",
      "TB is an infectious disease that mainly affects the lungs but is treatable with medication.", "ERR_LO_G7HEA3_TB", 1),
    CLOZE("A disease you can pass to others is described as ____.",
      ["infectious", "imaginary", "musical", "permanent"], "infectious",
      "Infectious (communicable) diseases, like TB, can spread from person to person.", "ERR_LO_G7HEA3_INFECTIOUS", 2),
    MC("Which factor can contribute to many common diseases?",
      ["Poor eating habits and physical inactivity", "Reading books", "Drinking water", "Sleeping enough"], "Poor eating habits and physical inactivity",
      "Causes include social, economic and environmental factors plus poor diet, inactivity, alcohol and tobacco.", "ERR_LO_G7HEA3_CAUSE", 2),
    TF("HIV and AIDS can be managed so that a person lives a long, healthy life.", "True",
      "With treatment, diet and a positive attitude, people with HIV can live long, healthy lives.", "ERR_LO_G7HEA3_HIVMANAGE", 1),
    MC("Anorexia is best described as…",
      ["an eating disorder where a person eats too little", "a broken bone", "a type of cold", "an allergy to dust"], "an eating disorder where a person eats too little",
      "Anorexia is a serious eating disorder involving extreme food restriction.", "ERR_LO_G7HEA3_ANOREXIA", 2),
    MC("Epilepsy is a condition that affects the…",
      ["brain, sometimes causing seizures", "feet only", "hair colour", "sense of smell"], "brain, sometimes causing seizures",
      "Epilepsy affects the brain and can cause seizures, but it can be managed with medication.", "ERR_LO_G7HEA3_EPILEPSY", 2),
    CLOZE("Obesity is linked to eating too much unhealthy food and too little ____.",
      ["exercise", "sleep", "homework", "water"], "exercise",
      "Obesity is linked to poor diet and lack of physical activity.", "ERR_LO_G7HEA3_OBESITY", 1),
    TF("People living with a chronic disease deserve care, support and no discrimination.", "True",
      "People with chronic illnesses deserve care and support, not stigma or discrimination.", "ERR_LO_G7HEA3_SUPPORT", 1),
    MC("Where can a family find reliable health information and services?",
      ["A clinic, hospital or qualified health worker", "A random rumour", "A guess from a friend", "Nowhere"], "A clinic, hospital or qualified health worker",
      "Clinics, hospitals and health workers are reliable sources of health information and services.", "ERR_LO_G7HEA3_RESOURCES", 2),
    MC("A good strategy for living well with a chronic disease like diabetes is to…",
      ["follow treatment, eat well and stay active", "ignore the doctor", "stop all medication suddenly", "hide the condition and avoid care"], "follow treatment, eat well and stay active",
      "Managing a chronic disease means following treatment, eating well and staying active.", "ERR_LO_G7HEA3_STRATEGY", 2),
    TF("Tobacco and alcohol use can increase the risk of several diseases.", "True",
      "Tobacco and alcohol use raise the risk of many diseases, including lung and heart disease.", "ERR_LO_G7HEA3_TOBACCO", 1),
    CLOZE("Care and ____ help people cope with a serious illness.",
      ["support", "blame", "teasing", "silence"], "support",
      "Care and support help people cope physically and emotionally with illness.", "ERR_LO_G7HEA3_CARE", 1),
    MC("Why is early treatment of TB important?",
      ["It cures the person and stops it spreading to others", "It makes TB worse", "It has no benefit", "It only helps adults"], "It cures the person and stops it spreading to others",
      "Early TB treatment cures the patient and prevents spread to others.", "ERR_LO_G7HEA3_EARLYTB", 2),
    MC("Which lifestyle choice helps PREVENT many common diseases?",
      ["Eating healthily and being active", "Smoking daily", "Never exercising", "Eating only junk food"], "Eating healthily and being active",
      "A healthy diet and regular activity help prevent many common diseases.", "ERR_LO_G7HEA3_PREVENT", 1),
    TF("You can tell exactly who is living with HIV just by looking at them.", "False",
      "You cannot tell who has HIV by appearance; assuming so causes unfair stigma.", "ERR_LO_G7HEA3_LOOKHIV", 2),
    {
      question: "Sort each item into a CAUSE/RISK or a HEALTHY PREVENTION for common diseases.",
      input_type: "sort-buckets",
      buckets: [{ id: "risk", label: "Cause / risk" }, { id: "prevent", label: "Healthy prevention" }],
      items: [
        { id: "i1", text: "Smoking tobacco", correct_bucket: "risk" },
        { id: "i2", text: "Eating mostly junk food", correct_bucket: "risk" },
        { id: "i3", text: "Regular exercise", correct_bucket: "prevent" },
        { id: "i4", text: "A balanced diet", correct_bucket: "prevent" },
      ],
      expected: "Smoking and junk food are risks; exercise and a balanced diet help prevent disease.",
      pass_threshold: 0.75,
      memo: "Smoking and poor diet raise disease risk; exercise and balanced eating help prevent it.",
      error_signals: ["ERR_LO_G7HEA3_SORT"], difficulty: 2,
    },
    MC("A classmate has epilepsy. The kind and correct attitude is to…",
      ["treat them normally and know how to help if a seizure happens", "avoid and exclude them", "make fun of the condition", "tell them to 'just stop'"], "treat them normally and know how to help if a seizure happens",
      "People with epilepsy should be treated normally; knowing basic first aid helps in a seizure.", "ERR_LO_G7HEA3_EPILEPSYKIND", 2),
    TF("Going for regular check-ups can catch many diseases early.", "True",
      "Regular health check-ups help detect diseases early, when they are easier to treat.", "ERR_LO_G7HEA3_CHECKUP", 1),
  ],
};

export default G7;
