// ─── Life Orientation SP — Grade 7 authored pools (part 2: CR · WW) ──────────
//
// Keyed by skill id → question array. Refs auto-assigned by the generator.
// Tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
//
// CAPS Grade 7 topics here:
//   Constitutional rights & responsibilities · World of work

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7B = {
  // ════════════ CONSTITUTIONAL RIGHTS & RESPONSIBILITIES (Term 2) ═══════════════
  // CR.A1 · Human rights in the Constitution
  "LO.G7.CR.A1": [
    MC("What is the Constitution of South Africa?",
      ["The highest law that sets out everyone's rights", "A school rule book", "A sports magazine", "A list of names"], "The highest law that sets out everyone's rights",
      "The Constitution is South Africa's highest law; the Bill of Rights lists the rights of all people.", "ERR_LO_G7CRA1_DEF", 1),
    TF("The Bill of Rights protects the rights of everyone in South Africa.", "True",
      "The Bill of Rights in the Constitution protects the rights of all people in the country.", "ERR_LO_G7CRA1_BOR", 1),
    MC("Which is a human right in the Constitution?",
      ["The right to education", "The right to cheat", "The right to bully", "The right to steal"], "The right to education",
      "Rights include education, equality, dignity and safety — not the 'right' to harm others.", "ERR_LO_G7CRA1_RIGHT", 1),
    CLOZE("Every right comes with a ____ to respect the same right in others.",
      ["responsibility", "reward", "holiday", "prize"], "responsibility",
      "Rights carry responsibilities — you must respect others' rights as you claim your own.", "ERR_LO_G7CRA1_RESPONSIBILITY", 2),
    MC("You have the right to education. What is your matching RESPONSIBILITY?",
      ["Attend school and let others learn too", "Disturb the class", "Skip school often", "Stop others from learning"], "Attend school and let others learn too",
      "The responsibility that matches the right to education is to attend and not stop others learning.", "ERR_LO_G7CRA1_MATCH", 2),
    TF("Human rights apply only to adults, not to children.", "False",
      "Human rights apply to everyone, including children, who also have special protections.", "ERR_LO_G7CRA1_CHILDREN", 1),
    MC("The right to equality means…",
      ["everyone is treated fairly and without unfair discrimination", "some people are above the law", "only rich people have rights", "boys have more rights than girls"], "everyone is treated fairly and without unfair discrimination",
      "Equality means fair treatment for all and protection from unfair discrimination.", "ERR_LO_G7CRA1_EQUALITY", 2),
    CLOZE("The right to be treated with respect and worth is the right to human ____.",
      ["dignity", "money", "fame", "speed"], "dignity",
      "Human dignity is the right to be valued and treated with respect.", "ERR_LO_G7CRA1_DIGNITY", 1),
    MC("Someone says hurtful things about a classmate's religion. Which right is being disrespected?",
      ["Freedom of religion and dignity", "The right to fast cars", "The right to win games", "The right to extra homework"], "Freedom of religion and dignity",
      "Mocking someone's religion disrespects their freedom of religion and dignity.", "ERR_LO_G7CRA1_VIOLATION", 2),
    TF("Respecting human rights helps build a fair and peaceful society.", "True",
      "When everyone respects rights, society becomes fairer and more peaceful.", "ERR_LO_G7CRA1_FAIR", 1),
    MC("Applying your rights responsibly means…",
      ["using your rights without taking away others' rights", "doing whatever you want", "ignoring other people", "breaking the law"], "using your rights without taking away others' rights",
      "Responsible use of rights respects the equal rights of everyone else.", "ERR_LO_G7CRA1_APPLY", 2),
    MC("The right to freedom of speech allows you to…",
      ["share your opinions respectfully", "spread lies that harm others", "threaten people", "bully online"], "share your opinions respectfully",
      "Freedom of speech lets you express views, but not to harm, threaten or spread hate.", "ERR_LO_G7CRA1_SPEECH", 2),
    TF("Freedom of speech means you can say anything, even hateful threats.", "False",
      "Freedom of speech has limits; it does not protect hate speech, threats or incitement to harm.", "ERR_LO_G7CRA1_LIMITS", 2),
    CLOZE("A document inside the Constitution listing our rights is the Bill of ____.",
      ["Rights", "Sales", "Health", "Sports"], "Rights",
      "The Bill of Rights is the part of the Constitution that lists fundamental rights.", "ERR_LO_G7CRA1_BILL", 1),
    MC("Why is it important that everyone knows their rights?",
      ["So they can claim them and respect others' rights", "So they can break the law", "So they can ignore others", "So they can avoid school"], "So they can claim them and respect others' rights",
      "Knowing your rights lets you stand up for them and respect the rights of others.", "ERR_LO_G7CRA1_KNOW", 2),
    TF("Children have the right to be protected from abuse and neglect.", "True",
      "The Constitution gives children special rights, including protection from abuse and neglect.", "ERR_LO_G7CRA1_PROTECTION", 1),
    MC("Which action shows you are taking RESPONSIBILITY for others' rights?",
      ["Standing up against unfair treatment of a classmate", "Joining in to tease them", "Looking away from bullying", "Spreading rumours"], "Standing up against unfair treatment of a classmate",
      "Defending others against unfair treatment is taking responsibility for their rights.", "ERR_LO_G7CRA1_STANDUP", 2),
    {
      question: "Match each RIGHT with its matching RESPONSIBILITY by ordering the responsibilities to fit Right 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(for Right to education) Attend school and respect others' learning" },
        { id: "s2", text: "(for Right to safety) Do not harm or threaten others" },
        { id: "s3", text: "(for Right to a clean environment) Do not litter or pollute" },
        { id: "s4", text: "(for Freedom of religion) Respect others' beliefs" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Education→attend and respect learning; safety→do not harm; environment→do not pollute; religion→respect beliefs.",
      memo: "Each right has a matching responsibility: respect the same right in everyone else.",
      error_signals: ["ERR_LO_G7CRA1_SEQ"], difficulty: 2,
    },
    MC("The best summary of rights and responsibilities is…",
      ["my rights end where another person's rights begin", "I can do anything I like", "rules are only for others", "rights have no limits"], "my rights end where another person's rights begin",
      "Your freedom is balanced by respect for everyone else's equal rights.", "ERR_LO_G7CRA1_SUMMARY", 3),
    TF("The Constitution protects people of all races, genders and religions equally.", "True",
      "The Constitution protects everyone equally, regardless of race, gender or religion.", "ERR_LO_G7CRA1_ALLEQUAL", 1),
  ],

  // CR.A2 · Fair play in sport
  "LO.G7.CR.A2": [
    MC("What does 'fair play' in sport mean?",
      ["Playing honestly and respecting the rules and others", "Winning by any means", "Cheating quietly", "Ignoring the referee"], "Playing honestly and respecting the rules and others",
      "Fair play means honesty, respecting the rules, opponents and officials, win or lose.", "ERR_LO_G7CRA2_DEF", 1),
    TF("Respect for your opponents is part of fair play.", "True",
      "Respecting opponents, teammates and officials is central to fair play.", "ERR_LO_G7CRA2_RESPECT", 1),
    MC("Which action shows fair play?",
      ["Helping an injured opponent up", "Tripping a player on purpose", "Lying to the referee", "Insulting the other team"], "Helping an injured opponent up",
      "Helping an opponent and showing respect are clear signs of fair play.", "ERR_LO_G7CRA2_ACTION", 1),
    CLOZE("Believing your teammates will do their part is called ____.",
      ["trust", "fear", "cheating", "anger"], "trust",
      "Trust in teammates is a value that helps a team play and work well together.", "ERR_LO_G7CRA2_TRUST", 1),
    MC("Your team loses a close game. The fair-play response is to…",
      ["congratulate the winners respectfully", "accuse them of cheating", "storm off angrily", "refuse to shake hands"], "congratulate the winners respectfully",
      "Accepting defeat graciously and congratulating winners shows fair play.", "ERR_LO_G7CRA2_LOSE", 2),
    TF("Respect for difference means valuing players of all backgrounds and abilities.", "True",
      "Fair play includes respect for difference — valuing all players regardless of background or ability.", "ERR_LO_G7CRA2_DIFFERENCE", 1),
    MC("Why are rules important in sport?",
      ["They keep the game fair and safe for everyone", "They help one team cheat", "They make sport boring on purpose", "They have no purpose"], "They keep the game fair and safe for everyone",
      "Rules keep sport fair and safe, so everyone has an equal chance.", "ERR_LO_G7CRA2_RULES", 1),
    MC("A teammate wants to cheat to win. The fair-play choice is to…",
      ["refuse and remind them to play honestly", "help them cheat", "stay silent and allow it", "join in to win"], "refuse and remind them to play honestly",
      "Refusing to cheat and encouraging honesty upholds fair play and the team's integrity.", "ERR_LO_G7CRA2_CHEAT", 2),
    CLOZE("Good sportspersons show respect even when they ____.",
      ["lose", "cheat", "quit", "hide"], "lose",
      "True sportsmanship shows respect in both victory and defeat.", "ERR_LO_G7CRA2_SPORTSMANSHIP", 2),
    TF("Mocking a weaker player is acceptable as long as your team wins.", "False",
      "Mocking others is never fair play, regardless of the result.", "ERR_LO_G7CRA2_MOCK", 1),
    MC("Fair play teaches values that are useful…",
      ["in everyday life, not just on the field", "only during matches", "only to professionals", "to nobody"], "in everyday life, not just on the field",
      "Values like honesty and respect from sport carry into everyday life.", "ERR_LO_G7CRA2_LIFE", 2),
    MC("Which is an example of UNFAIR play?",
      ["Deliberately injuring an opponent", "Following the rules", "Respecting the referee", "Encouraging teammates"], "Deliberately injuring an opponent",
      "Intentionally harming an opponent is a serious breach of fair play.", "ERR_LO_G7CRA2_UNFAIR", 1),
    TF("Accepting a referee's decision, even when you disagree, shows good values.", "True",
      "Respecting officials' decisions, even in disagreement, is part of fair play.", "ERR_LO_G7CRA2_REFEREE", 1),
    CLOZE("Playing by the rules and being honest shows good ____.",
      ["values", "tricks", "secrets", "luck"], "values",
      "Honesty and rule-following reflect good personal values in sport.", "ERR_LO_G7CRA2_VALUES", 1),
    MC("How can a captain encourage fair play in a team?",
      ["Set an example of honesty and respect", "Reward cheating", "Mock weaker players", "Argue with every call"], "Set an example of honesty and respect",
      "Leaders set the tone; modelling honesty and respect encourages team fair play.", "ERR_LO_G7CRA2_CAPTAIN", 2),
    TF("Trust and respect help a team work well together.", "True",
      "Trust and respect among players build teamwork and performance.", "ERR_LO_G7CRA2_TEAMWORK", 1),
    MC("Including a player who is new or less skilled shows…",
      ["respect for difference and good sportsmanship", "weakness", "poor strategy only", "unfairness"], "respect for difference and good sportsmanship",
      "Including all players shows respect for difference and good sportsmanship.", "ERR_LO_G7CRA2_INCLUDE", 2),
    {
      question: "Sort each behaviour into FAIR PLAY or UNFAIR PLAY.",
      input_type: "sort-buckets",
      buckets: [{ id: "fair", label: "Fair play" }, { id: "unfair", label: "Unfair play" }],
      items: [
        { id: "i1", text: "Shaking hands after the match", correct_bucket: "fair" },
        { id: "i2", text: "Respecting the referee's call", correct_bucket: "fair" },
        { id: "i3", text: "Deliberately tripping an opponent", correct_bucket: "unfair" },
        { id: "i4", text: "Lying about the score", correct_bucket: "unfair" },
      ],
      expected: "Handshakes and respecting calls are fair play; tripping and lying are unfair play.",
      pass_threshold: 0.75,
      memo: "Fair play is honest and respectful; unfair play cheats or harms.",
      error_signals: ["ERR_LO_G7CRA2_SORT"], difficulty: 1,
    },
    MC("The deeper purpose of fair play is to…",
      ["build character, respect and trust", "guarantee you always win", "make sport pointless", "remove all competition"], "build character, respect and trust",
      "Fair play builds character, respect and trust that last beyond the game.", "ERR_LO_G7CRA2_PURPOSE", 2),
    TF("Cheering on your own team while still respecting opponents is good sportsmanship.", "True",
      "You can support your team enthusiastically while still respecting the other side.", "ERR_LO_G7CRA2_CHEER", 1),
  ],

  // CR.A3 · Dealing with abuse
  "LO.G7.CR.A3": [
    MC("What is abuse?",
      ["When someone harms, hurts or mistreats another person", "A friendly game", "A type of food", "A school subject"], "When someone harms, hurts or mistreats another person",
      "Abuse is when someone harms, hurts or mistreats another person physically, emotionally or otherwise.", "ERR_LO_G7CRA3_DEF", 1),
    TF("Abuse can happen between adults and children, or between peers.", "True",
      "Abuse can occur in many relationships, including adult–child and peer–peer.", "ERR_LO_G7CRA3_CONTEXTS", 1),
    MC("Which is a sign of a threatening or risky situation?",
      ["Someone tries to get you alone and makes you uncomfortable", "A friend invites you to study", "A teacher gives a fair test", "A coach runs practice"], "Someone tries to get you alone and makes you uncomfortable",
      "Feeling unsafe, pressured or isolated by someone can be a warning sign of a risky situation.", "ERR_LO_G7CRA3_RISKY", 2),
    CLOZE("If something feels wrong or unsafe, you should tell a ____ adult.",
      ["trusted", "stranger", "random", "famous"], "trusted",
      "Telling a trusted adult is a key way to protect yourself in risky situations.", "ERR_LO_G7CRA3_TRUSTED", 1),
    TF("Abuse is always the victim's fault.", "False",
      "Abuse is never the victim's fault; the responsibility lies with the person who chooses to abuse.", "ERR_LO_G7CRA3_NOTFAULT", 1),
    MC("How can abuse affect a person's health and relationships?",
      ["It can harm their emotions, trust and wellbeing", "It improves their health", "It has no effect at all", "It only affects strangers"], "It can harm their emotions, trust and wellbeing",
      "Abuse can deeply harm emotional health, trust and relationships.", "ERR_LO_G7CRA3_EFFECTS", 2),
    MC("Why is communication important in healthy relationships?",
      ["It helps solve problems without violence", "It causes more fights", "It is unnecessary", "It hides the truth"], "It helps solve problems without violence",
      "Open communication promotes healthy, non-violent relationships.", "ERR_LO_G7CRA3_COMMUNICATION", 2),
    CLOZE("A place where abuse victims can get help and safety is a place of ____.",
      ["protection", "danger", "secrecy", "silence"], "protection",
      "Places of protection (clinics, police, shelters, helplines) offer safety and help to victims.", "ERR_LO_G7CRA3_PROTECTION", 1),
    TF("You should keep abuse a secret to avoid trouble.", "False",
      "Keeping abuse secret allows it to continue; telling a trusted adult is the safe choice.", "ERR_LO_G7CRA3_SECRET", 2),
    MC("Lerato's older neighbour keeps touching her in a way that feels wrong. What should she do?",
      ["Tell a trusted adult and seek help immediately", "Keep quiet and hope it stops", "Blame herself", "Tell no one ever"], "Tell a trusted adult and seek help immediately",
      "She should tell a trusted adult straight away; it is not her fault and help is available.", "ERR_LO_G7CRA3_SCENARIO", 3),
    MC("Which is a place victims of abuse can contact for help?",
      ["Childline or the police", "A sweet shop", "A football club only", "Nobody"], "Childline or the police",
      "Organisations like Childline and the police help and protect victims of abuse.", "ERR_LO_G7CRA3_HELPLINE", 2),
    TF("Bullying by peers is a form of abuse.", "True",
      "Repeated bullying that harms or intimidates someone is a form of abuse.", "ERR_LO_G7CRA3_BULLYING", 1),
    MC("How can you protect yourself from threatening situations?",
      ["Stay aware, avoid being isolated, and tell someone you trust", "Keep it all secret", "Go alone to risky places", "Ignore your gut feeling"], "Stay aware, avoid being isolated, and tell someone you trust",
      "Awareness, avoiding isolation and telling a trusted person help protect you.", "ERR_LO_G7CRA3_PROTECTSELF", 2),
    CLOZE("Hurting someone with words, like constant insults, is ____ abuse.",
      ["emotional", "healthy", "physical-only", "imaginary"], "emotional",
      "Emotional abuse uses words and behaviour, like insults and threats, to harm someone.", "ERR_LO_G7CRA3_EMOTIONAL", 2),
    MC("A friend tells you they are being abused at home. The best response is to…",
      ["listen, believe them and help them tell a trusted adult", "promise to keep it a total secret", "tell them it is their fault", "ignore it"], "listen, believe them and help them tell a trusted adult",
      "Listen, believe, and help them reach a trusted adult or helpline — do not keep dangerous secrets.", "ERR_LO_G7CRA3_FRIEND", 3),
    TF("Reporting abuse can help stop it and protect the victim.", "True",
      "Reporting abuse to trusted adults or authorities can stop it and protect the victim.", "ERR_LO_G7CRA3_REPORT", 1),
    MC("Which feeling might warn you that a situation is unsafe?",
      ["A strong gut feeling that something is wrong", "Feeling relaxed and happy", "Feeling proud of good work", "Feeling sleepy at night"], "A strong gut feeling that something is wrong",
      "Trusting a strong 'something is wrong' feeling can help keep you safe.", "ERR_LO_G7CRA3_GUT", 2),
    {
      question: "Put the steps for responding to a risky or abusive situation in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise the situation feels threatening or wrong" },
        { id: "s2", text: "Remove yourself from danger if you safely can" },
        { id: "s3", text: "Tell a trusted adult what happened" },
        { id: "s4", text: "Get ongoing help and support" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise the danger, get to safety, tell a trusted adult, then get ongoing support.",
      memo: "Recognise, get safe, tell a trusted adult, and seek ongoing help.",
      error_signals: ["ERR_LO_G7CRA3_SEQ"], difficulty: 2,
    },
    MC("Healthy, non-violent relationships are built on…",
      ["respect, trust and good communication", "fear and control", "secrets and threats", "shouting and force"], "respect, trust and good communication",
      "Respect, trust and communication are the foundation of healthy, non-violent relationships.", "ERR_LO_G7CRA3_HEALTHY", 2),
    TF("Asking for help after abuse is a sign of strength, not weakness.", "True",
      "Seeking help takes courage and is the right step toward safety and healing.", "ERR_LO_G7CRA3_STRENGTH", 1),
  ],

  // CR.A4 · Oral traditions and scriptures of religions
  "LO.G7.CR.A4": [
    MC("What are 'oral traditions' in religion?",
      ["Stories and teachings passed on by word of mouth", "Written exam papers", "Sports rules", "Cooking recipes only"], "Stories and teachings passed on by word of mouth",
      "Oral traditions are teachings and stories passed down by speaking, from generation to generation.", "ERR_LO_G7CRA4_DEF", 1),
    TF("Scriptures are the sacred writings of a religion.", "True",
      "Scriptures are a religion's sacred or holy writings.", "ERR_LO_G7CRA4_SCRIPTURE", 1),
    MC("Which is a major religion practised in South Africa?",
      ["Christianity", "Football", "Chess", "Cooking"], "Christianity",
      "Major religions in South Africa include Judaism, Christianity, Islam, Hinduism, Buddhism and African religion.", "ERR_LO_G7CRA4_RELIGIONS", 1),
    MC("The sacred text of Islam is the…",
      ["Qur'an", "Times table", "Phone book", "Atlas"], "Qur'an",
      "The Qur'an is the holy scripture of Islam.", "ERR_LO_G7CRA4_QURAN", 2),
    MC("The sacred text central to Judaism is the…",
      ["Torah", "Dictionary", "Calendar", "Recipe book"], "Torah",
      "The Torah is a central sacred text in Judaism.", "ERR_LO_G7CRA4_TORAH", 2),
    CLOZE("African religion often passes on values through stories, proverbs and ____ traditions.",
      ["oral", "written-only", "musical-only", "secret"], "oral",
      "African religion strongly uses oral traditions — stories, proverbs and spoken teachings.", "ERR_LO_G7CRA4_AFRICAN", 2),
    TF("Different religions can teach similar values, like kindness and respect.", "True",
      "Many religions share values such as kindness, honesty, respect and caring for others.", "ERR_LO_G7CRA4_SHARED", 1),
    MC("Why do religions use stories and scriptures?",
      ["To teach values and guide how people live", "To make exams harder", "To sell tickets", "To confuse people"], "To teach values and guide how people live",
      "Stories and scriptures pass on values and guidance for living well.", "ERR_LO_G7CRA4_WHY", 2),
    CLOZE("Treating people of other religions with ____ helps everyone live in peace.",
      ["respect", "rudeness", "suspicion", "fear"], "respect",
      "Respecting other religions promotes peace and tolerance in a diverse society.", "ERR_LO_G7CRA4_RESPECT", 1),
    MC("The Bhagavad Gita and Vedas are sacred texts associated with…",
      ["Hinduism", "Judaism", "Islam", "Buddhism"], "Hinduism",
      "The Vedas and Bhagavad Gita are sacred Hindu scriptures.", "ERR_LO_G7CRA4_HINDU", 3),
    TF("It is respectful to learn about religions different from your own.", "True",
      "Learning about other religions builds understanding and respect.", "ERR_LO_G7CRA4_LEARN", 1),
    MC("A classmate follows a different religion from you. The respectful attitude is to…",
      ["be curious and respectful of their beliefs", "tell them their religion is wrong", "exclude them", "mock their practices"], "be curious and respectful of their beliefs",
      "Respect and openness toward different beliefs build a tolerant society.", "ERR_LO_G7CRA4_ATTITUDE", 2),
    MC("Buddhism's teachings are often linked to the…",
      ["teachings of the Buddha", "rules of cricket", "national anthem", "weather report"], "teachings of the Buddha",
      "Buddhism follows the teachings of the Buddha, often shared through stories and texts.", "ERR_LO_G7CRA4_BUDDHA", 2),
    CLOZE("Sacred stories are often passed from ____ to grandchildren.",
      ["grandparents", "strangers", "computers", "shops"], "grandparents",
      "Oral traditions pass through generations, often from grandparents to grandchildren.", "ERR_LO_G7CRA4_GENERATIONS", 1),
    TF("Respecting religious diversity is part of respecting human rights.", "True",
      "Freedom of religion is a constitutional right; respecting diversity upholds it.", "ERR_LO_G7CRA4_RIGHTS", 1),
    MC("How do oral traditions and scriptures help a community?",
      ["They pass on shared values, identity and guidance", "They divide people on purpose", "They have no real use", "They replace all laws"], "They pass on shared values, identity and guidance",
      "They give a community shared values, identity and guidance across generations.", "ERR_LO_G7CRA4_COMMUNITY", 2),
    {
      question: "Sort each sacred text with its religion by ordering the texts to match Religion 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Christianity) The Bible" },
        { id: "s2", text: "(Islam) The Qur'an" },
        { id: "s3", text: "(Judaism) The Torah" },
        { id: "s4", text: "(Hinduism) The Vedas" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Christianity→Bible, Islam→Qur'an, Judaism→Torah, Hinduism→Vedas.",
      memo: "Each major religion has its own sacred scriptures.",
      error_signals: ["ERR_LO_G7CRA4_SEQ"], difficulty: 2,
    },
    TF("All religions must be the same for people to live together peacefully.", "False",
      "People of different religions can live peacefully together through mutual respect, not sameness.", "ERR_LO_G7CRA4_SAME", 2),
    MC("The MAIN value most religions encourage toward others is…",
      ["compassion and respect", "greed", "dishonesty", "revenge"], "compassion and respect",
      "Compassion and respect for others are values shared across the major religions.", "ERR_LO_G7CRA4_VALUE", 2),
    TF("Freedom of religion means people may follow the faith of their choice, or none.", "True",
      "The Constitution protects freedom of religion, including the choice to follow no religion.", "ERR_LO_G7CRA4_FREEDOM", 1),
  ],

  // ════════════════════════════ WORLD OF WORK (Term 2) ═════════════════════════
  // WW.A1 · Reading, studying and memory skills
  "LO.G7.WW.A1": [
    MC("Why is reading with understanding important for studying?",
      ["It helps you learn and remember information", "It wastes time", "It has no effect on marks", "It only matters in English"], "It helps you learn and remember information",
      "Reading with understanding helps you learn, remember and apply information across subjects.", "ERR_LO_G7WWA1_DEF", 1),
    TF("Reading for enjoyment can also improve your vocabulary and skills.", "True",
      "Reading for pleasure builds vocabulary, comprehension and general knowledge.", "ERR_LO_G7WWA1_ENJOY", 1),
    MC("Which is a good MEMORY skill for studying?",
      ["Repeating and testing yourself on key facts", "Reading once and hoping", "Never reviewing", "Studying while distracted"], "Repeating and testing yourself on key facts",
      "Active recall — testing yourself — and repetition strengthen memory.", "ERR_LO_G7WWA1_MEMORY", 2),
    CLOZE("The ability to bring information back to mind is called ____.",
      ["recall", "running", "cooking", "sleeping"], "recall",
      "Recall is being able to retrieve information from memory when you need it.", "ERR_LO_G7WWA1_RECALL", 1),
    MC("Which study habit helps you concentrate best?",
      ["A quiet space with no distractions", "Studying with loud TV on", "Checking your phone constantly", "Studying while walking in a crowd"], "A quiet space with no distractions",
      "A quiet, distraction-free space helps concentration and learning.", "ERR_LO_G7WWA1_CONCENTRATE", 1),
    TF("Making a summary in your own words helps you understand and remember.", "True",
      "Summarising in your own words deepens understanding and aids memory.", "ERR_LO_G7WWA1_SUMMARY", 1),
    MC("Which is a memory aid that links new facts to something familiar?",
      ["A mnemonic or rhyme", "A blank page", "A locked drawer", "An empty bag"], "A mnemonic or rhyme",
      "Mnemonics and rhymes link new information to familiar patterns, aiding recall.", "ERR_LO_G7WWA1_MNEMONIC", 2),
    CLOZE("Going over work again to keep it fresh is called ____.",
      ["revision", "deletion", "vacation", "decoration"], "revision",
      "Revision means reviewing work regularly so it stays in memory.", "ERR_LO_G7WWA1_REVISION", 1),
    MC("Sipho reads a page once and forgets it by the next day. A better strategy is to…",
      ["review and self-test over several days", "read it once more loudly", "give up studying", "copy without thinking"], "review and self-test over several days",
      "Spacing revision and self-testing over days greatly improves long-term memory.", "ERR_LO_G7WWA1_STRATEGY", 2),
    TF("Cramming everything the night before is the best way to remember long-term.", "False",
      "Cramming may help short-term, but spaced revision over time is far better for lasting memory.", "ERR_LO_G7WWA1_CRAM", 2),
    MC("Reading for understanding means you should…",
      ["think about the meaning, not just the words", "read as fast as possible", "skip every hard word", "ignore the topic"], "think about the meaning, not just the words",
      "Reading for understanding focuses on meaning, not just decoding words.", "ERR_LO_G7WWA1_UNDERSTAND", 2),
    MC("Which tool helps organise ideas visually for memory?",
      ["A mind map", "A blank wall", "A locked box", "A heavy bag"], "A mind map",
      "Mind maps organise ideas visually, helping understanding and recall.", "ERR_LO_G7WWA1_MINDMAP", 2),
    TF("Getting enough sleep helps your brain remember what you studied.", "True",
      "Sleep helps the brain consolidate memories, improving recall.", "ERR_LO_G7WWA1_SLEEP", 1),
    CLOZE("Asking yourself questions about a text is called active ____.",
      ["reading", "ignoring", "sleeping", "eating"], "reading",
      "Active reading — questioning the text — improves comprehension and memory.", "ERR_LO_G7WWA1_ACTIVE", 2),
    MC("Why does reading widely help in many subjects?",
      ["It builds vocabulary and background knowledge", "It only helps in art", "It harms maths", "It has no effect"], "It builds vocabulary and background knowledge",
      "Wide reading builds vocabulary and knowledge that help across all subjects.", "ERR_LO_G7WWA1_WIDE", 2),
    TF("Highlighting and making notes can help you focus on key points.", "True",
      "Highlighting and note-making focus attention on the most important points.", "ERR_LO_G7WWA1_NOTES", 1),
    MC("Which is the BEST first step when studying a new chapter?",
      ["Skim the headings to get an overview", "Memorise every word at once", "Start at the last page", "Skip it entirely"], "Skim the headings to get an overview",
      "Skimming headings first gives an overview that makes detailed reading easier.", "ERR_LO_G7WWA1_FIRSTSTEP", 2),
    {
      question: "Put these study steps in an effective order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Skim the headings for an overview" },
        { id: "s2", text: "Read carefully for understanding" },
        { id: "s3", text: "Summarise the key points in your own words" },
        { id: "s4", text: "Test yourself to check recall" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Skim, read for understanding, summarise, then self-test.",
      memo: "Overview first, then read deeply, summarise, and test your recall.",
      error_signals: ["ERR_LO_G7WWA1_SEQ"], difficulty: 2,
    },
    MC("Good reading and study skills are important because they…",
      ["help you succeed in school and future work", "only matter in primary school", "are a waste of effort", "stop you learning"], "help you succeed in school and future work",
      "Strong reading and study skills support success in school and in the world of work.", "ERR_LO_G7WWA1_FUTURE", 1),
    TF("Taking short breaks during long study sessions can help you focus better.", "True",
      "Short, planned breaks help the brain rest and keep concentration high.", "ERR_LO_G7WWA1_BREAKS", 1),
  ],

  // WW.A2 · Career fields
  "LO.G7.WW.A2": [
    MC("What is a 'career field'?",
      ["A group of related jobs and careers", "A single job only", "A sports ground", "A type of exam"], "A group of related jobs and careers",
      "A career field is a group of related jobs that share interests, skills or subjects.", "ERR_LO_G7WWA2_DEF", 1),
    TF("Different career fields need different school subjects.", "True",
      "Each career field tends to require certain school subjects and skills.", "ERR_LO_G7WWA2_SUBJECTS", 1),
    MC("Which subjects are usually important for a career in HEALTH (like nursing)?",
      ["Life Sciences and other sciences", "Only physical education", "Only art", "No subjects at all"], "Life Sciences and other sciences",
      "Health careers usually require Life Sciences and related science subjects.", "ERR_LO_G7WWA2_HEALTH", 2),
    CLOZE("The things you are good at are your ____.",
      ["abilities", "fears", "excuses", "snacks"], "abilities",
      "Abilities are what you can do well; matching them to a field helps you choose a career.", "ERR_LO_G7WWA2_ABILITIES", 1),
    MC("Why should you think about your INTERESTS when choosing a career field?",
      ["You are more likely to enjoy and succeed at work you find interesting", "Interests never matter", "Money is the only thing", "Interests stop you working"], "You are more likely to enjoy and succeed at work you find interesting",
      "Matching interests to a field makes work more enjoyable and sustainable.", "ERR_LO_G7WWA2_INTERESTS", 2),
    TF("A career field has its own challenges as well as opportunities.", "True",
      "Each field offers opportunities but also challenges to consider before choosing.", "ERR_LO_G7WWA2_CHALLENGES", 1),
    MC("Which describes the 'work environment' of a career?",
      ["Where and how the work is done", "The colour of the building only", "The lunch menu", "The weather"], "Where and how the work is done",
      "Work environment is the setting and conditions in which a job is done.", "ERR_LO_G7WWA2_ENVIRONMENT", 2),
    MC("Engineering and building careers usually need which subject?",
      ["Mathematics", "No maths at all", "Only music", "Only history"], "Mathematics",
      "Engineering and technical careers usually require Mathematics and sciences.", "ERR_LO_G7WWA2_MATHS", 2),
    CLOZE("How long you must study for a career is its ____ of study.",
      ["duration", "colour", "price", "weather"], "duration",
      "Duration of study is the length of training or education a career requires.", "ERR_LO_G7WWA2_DURATION", 1),
    TF("You should think about the requirements of a career before choosing it.", "True",
      "Knowing the subjects, schooling and skills a career needs helps you plan and choose wisely.", "ERR_LO_G7WWA2_REQUIRE", 1),
    MC("Where can you find information about careers and study options?",
      ["Career guidance services, websites and counsellors", "Only by guessing", "Nowhere", "Only from one friend"], "Career guidance services, websites and counsellors",
      "Career guidance, reliable websites and counsellors are good sources of career and study information.", "ERR_LO_G7WWA2_SOURCES", 2),
    MC("Naledi loves helping people and is strong in Life Sciences. A suitable field could be…",
      ["health care, like nursing or medicine", "no field at all", "something she dislikes", "a field needing only art"], "health care, like nursing or medicine",
      "Matching her interest in helping people and her science strength points to health care.", "ERR_LO_G7WWA2_MATCH", 3),
    TF("Some careers need university; others need a college diploma or apprenticeship.", "True",
      "Different careers need different paths — university, college diplomas or apprenticeships.", "ERR_LO_G7WWA2_PATHS", 2),
    CLOZE("Jobs in farming, food and nature are in the ____ career field.",
      ["agricultural", "musical", "medical", "legal"], "agricultural",
      "Agricultural careers deal with farming, food production and natural resources.", "ERR_LO_G7WWA2_AGRI", 2),
    MC("Why is it useful to explore career fields in Grade 7?",
      ["It helps you plan subjects and goals early", "It is too early to matter", "It locks you in forever", "It has no benefit"], "It helps you plan subjects and goals early",
      "Exploring fields early helps you plan subject choices and set goals.", "ERR_LO_G7WWA2_EXPLORE", 2),
    TF("The only thing that matters when choosing a career is how much money it pays.", "False",
      "Pay matters, but so do interests, abilities, work environment and opportunities.", "ERR_LO_G7WWA2_MONEY", 2),
    MC("Which pairing of interest and field makes the best sense?",
      ["Enjoys fixing engines → mechanical/technical field", "Hates numbers → accounting", "Fears blood → surgery", "Dislikes people → sales only"], "Enjoys fixing engines → mechanical/technical field",
      "Good career choices align genuine interests and abilities with the field's demands.", "ERR_LO_G7WWA2_PAIR", 2),
    {
      question: "Sort each career into the BEST-matching field.",
      input_type: "sort-buckets",
      buckets: [{ id: "health", label: "Health field" }, { id: "tech", label: "Engineering/technical field" }],
      items: [
        { id: "i1", text: "Nurse", correct_bucket: "health" },
        { id: "i2", text: "Doctor", correct_bucket: "health" },
        { id: "i3", text: "Civil engineer", correct_bucket: "tech" },
        { id: "i4", text: "Electrician", correct_bucket: "tech" },
      ],
      expected: "Nurse and doctor are health careers; civil engineer and electrician are engineering/technical.",
      pass_threshold: 0.75,
      memo: "Careers group into fields by the kind of work and subjects they share.",
      error_signals: ["ERR_LO_G7WWA2_SORT"], difficulty: 1,
    },
    MC("Considering 'opportunities within a field' means looking at…",
      ["the chances to find work and grow in that field", "the field's lunch breaks", "the colour of uniforms", "nothing important"], "the chances to find work and grow in that field",
      "Opportunities mean the availability of jobs and room to advance in a field.", "ERR_LO_G7WWA2_OPPORTUNITIES", 2),
    TF("It is fine to be interested in more than one career field at this stage.", "True",
      "Exploring several fields is healthy in Grade 7; you narrow your choices over time.", "ERR_LO_G7WWA2_MANY", 1),
  ],

  // WW.A3 · Career simulation and the value of work
  "LO.G7.WW.A3": [
    MC("What is the 'value of work' in a person's life?",
      ["Work helps meet needs and gives purpose and dignity", "Work has no value", "Work is only about boredom", "Work stops all growth"], "Work helps meet needs and gives purpose and dignity",
      "Work helps fulfil personal needs and gives purpose, dignity and a sense of contribution.", "ERR_LO_G7WWA3_DEF", 1),
    TF("A 'dress code' is the kind of clothing suitable for a particular job.", "True",
      "A dress code is the expected clothing for a job, like a uniform or smart wear.", "ERR_LO_G7WWA3_DRESS", 1),
    MC("Which tools would a CARPENTER most likely use?",
      ["Saw, hammer and measuring tape", "Stethoscope", "Paintbrush only", "Microscope"], "Saw, hammer and measuring tape",
      "Each career uses particular tools; a carpenter uses a saw, hammer and tape.", "ERR_LO_G7WWA3_TOOLS", 1),
    CLOZE("The place where a person does their job is their place of ____.",
      ["employment", "holiday", "sleeping", "shopping"], "employment",
      "The place of employment is where the work happens — office, hospital, site, etc.", "ERR_LO_G7WWA3_PLACE", 1),
    MC("Why does work help fulfil personal needs?",
      ["It can provide income, skills and a sense of achievement", "It removes all needs", "It only causes stress", "It has no benefits"], "It can provide income, skills and a sense of achievement",
      "Work provides income to meet needs, plus skills, achievement and self-worth.", "ERR_LO_G7WWA3_NEEDS", 2),
    TF("Different careers require different personality characteristics.", "True",
      "Careers suit different personalities; for example, a counsellor needs patience and empathy.", "ERR_LO_G7WWA3_PERSONALITY", 1),
    MC("A nurse's typical work environment includes…",
      ["a clinic or hospital", "a football stadium", "a recording studio", "a courtroom only"], "a clinic or hospital",
      "A nurse usually works in a clinic or hospital, caring for patients.", "ERR_LO_G7WWA3_NURSE", 2),
    MC("Which personality trait suits a career as a TEACHER?",
      ["Patience and good communication", "Dislike of people", "Refusal to explain things", "Impatience"], "Patience and good communication",
      "Teaching suits patient, communicative people who enjoy helping others learn.", "ERR_LO_G7WWA3_TEACHER", 2),
    CLOZE("Jobs that are similar to one another are called ____ careers.",
      ["related", "broken", "secret", "random"], "related",
      "Related careers share similar tasks, skills or fields.", "ERR_LO_G7WWA3_RELATED", 1),
    TF("Knowing the school subjects a career needs helps you prepare for it.", "True",
      "Knowing the required subjects lets you choose and prepare for a career path.", "ERR_LO_G7WWA3_SUBJECTS", 1),
    MC("A 'career simulation' activity means you…",
      ["pretend to do a real career to learn what it involves", "sleep through the lesson", "copy answers", "avoid all careers"], "pretend to do a real career to learn what it involves",
      "A career simulation lets you role-play a job to understand its tasks, tools and requirements.", "ERR_LO_G7WWA3_SIMULATION", 2),
    MC("Why is it useful to learn a career's requirements before Grade 9?",
      ["So you can choose the right subjects in time", "It is pointless", "It locks you in forever", "It wastes time"], "So you can choose the right subjects in time",
      "Knowing requirements early helps you choose suitable subjects in Grade 10.", "ERR_LO_G7WWA3_EARLY", 2),
    TF("Work can give a person a sense of dignity and self-worth.", "True",
      "Beyond income, work provides dignity, purpose and self-worth.", "ERR_LO_G7WWA3_DIGNITY", 1),
    CLOZE("A doctor or electrician must meet the schooling ____ for that career.",
      ["requirements", "colours", "snacks", "songs"], "requirements",
      "Requirements are the schooling, subjects and training a career demands.", "ERR_LO_G7WWA3_REQUIRE", 1),
    MC("Which best shows the 'value of work in fulfilling potential'?",
      ["A person using their talents in a job they find meaningful", "A person doing nothing all day", "Avoiding all effort", "Refusing to learn"], "A person using their talents in a job they find meaningful",
      "Meaningful work lets people use their talents and reach their potential.", "ERR_LO_G7WWA3_POTENTIAL", 3),
    TF("Every job, no matter how simple, has dignity and value.", "True",
      "All honest work has dignity and contributes value to society.", "ERR_LO_G7WWA3_ALLJOBS", 1),
    MC("Which is part of exploring a career through simulation?",
      ["Finding out its tools, dress code and where to study", "Ignoring all details", "Only watching TV", "Guessing with no research"], "Finding out its tools, dress code and where to study",
      "A simulation explores a career's tools, dress code, environment and study path.", "ERR_LO_G7WWA3_EXPLORE", 2),
    {
      question: "Match each worker with their typical tool by ordering the tools to fit Worker 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Doctor) Stethoscope" },
        { id: "s2", text: "(Carpenter) Hammer" },
        { id: "s3", text: "(Electrician) Wire stripper" },
        { id: "s4", text: "(Chef) Cooking knife" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Doctor→stethoscope, carpenter→hammer, electrician→wire stripper, chef→knife.",
      memo: "Each career uses particular tools suited to its work.",
      error_signals: ["ERR_LO_G7WWA3_SEQ"], difficulty: 2,
    },
    MC("The MAIN reason to research a career before choosing it is to…",
      ["make an informed choice that fits you", "waste your time", "copy a friend", "avoid thinking"], "make an informed choice that fits you",
      "Researching a career helps you make an informed choice that suits your interests and abilities.", "ERR_LO_G7WWA3_INFORMED", 2),
    TF("Honest work in any career can give a person dignity and purpose.", "True",
      "All honest work has dignity and can give a person purpose and self-worth.", "ERR_LO_G7WWA3_DIGNITY2", 1),
  ],
};

export default G7B;
