// ─── Life Orientation SP — Grade 8 authored pools (part 2: CR · WW) ──────────
//
// Keyed by skill id → question array. Refs auto-assigned by the generator.
// Tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
// Each pool holds exactly 20 items.
//
// CAPS Grade 8 topics here:
//   Constitutional rights & responsibilities · World of work

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8B = {
  // ════════════ CONSTITUTIONAL RIGHTS & RESPONSIBILITIES (Term 4) ═══════════════
  // CR.A1 · Nation building
  "LO.G8.CR.A1": [
    MC("What does 'nation building' mean?",
      ["Working together across differences to build one united country", "Building only houses", "Dividing people by group", "Ignoring other cultures"], "Working together across differences to build one united country",
      "Nation building means uniting people of different backgrounds to build one country.", "ERR_LO_G8CRA1_DEF", 1),
    TF("Nation building can happen at home, at school and in the community.", "True",
      "Nation building can be promoted in different contexts: home, school and community.", "ERR_LO_G8CRA1_CONTEXTS", 1),
    MC("Which action promotes nation building?",
      ["Respecting and including people of all cultures", "Excluding people who differ", "Spreading division", "Mocking other groups"], "Respecting and including people of all cultures",
      "Respect, inclusion and cooperation across cultures promote nation building.", "ERR_LO_G8CRA1_ACTION", 1),
    CLOZE("Bringing people together as one despite differences builds national ____.",
      ["unity", "division", "conflict", "hatred"], "unity",
      "Nation building creates national unity from diversity.", "ERR_LO_G8CRA1_UNITY", 1),
    MC("How did Nelson Mandela contribute to nation building?",
      ["He promoted reconciliation and unity", "He encouraged division", "He ignored all groups", "He refused to forgive"], "He promoted reconciliation and unity",
      "Mandela promoted forgiveness, reconciliation and unity — key to nation building.", "ERR_LO_G8CRA1_MANDELA", 2),
    TF("Both women and men, as individuals and groups, can build the nation.", "True",
      "Nation building includes the contributions of women and men, individuals and groups.", "ERR_LO_G8CRA1_WOMENMEN", 1),
    MC("Which national symbol helps unite South Africans?",
      ["The national flag and anthem", "A single sports brand", "One private company", "A school's badge"], "The national flag and anthem",
      "Shared symbols like the flag and anthem help build a sense of national unity.", "ERR_LO_G8CRA1_SYMBOLS", 2),
    CLOZE("Healing past divisions and rebuilding trust is called ____.",
      ["reconciliation", "revenge", "separation", "conflict"], "reconciliation",
      "Reconciliation heals past divisions and rebuilds trust between people.", "ERR_LO_G8CRA1_RECONCILE", 2),
    MC("A school project where different cultures share their food and music promotes…",
      ["unity and respect for diversity", "division", "competition only", "exclusion"], "unity and respect for diversity",
      "Sharing cultures builds understanding, unity and respect for diversity.", "ERR_LO_G8CRA1_PROJECT", 2),
    TF("Nation building requires everyone to give up their own culture.", "False",
      "Nation building unites people while still respecting and celebrating their different cultures.", "ERR_LO_G8CRA1_GIVEUP", 2),
    MC("Why is nation building important for South Africa?",
      ["It heals past divisions and builds a peaceful society", "It causes conflict", "It has no benefit", "It divides people further"], "It heals past divisions and builds a peaceful society",
      "Nation building helps heal South Africa's past divisions and build peace.", "ERR_LO_G8CRA1_WHY", 2),
    MC("An ordinary citizen can build the nation by…",
      ["volunteering and treating all people with respect", "ignoring the community", "spreading hatred", "excluding others"], "volunteering and treating all people with respect",
      "Everyday acts of respect and service contribute to nation building.", "ERR_LO_G8CRA1_CITIZEN", 2),
    TF("Sport, like supporting a national team, can promote unity.", "True",
      "Shared national sporting moments can bring people together and promote unity.", "ERR_LO_G8CRA1_SPORT", 1),
    CLOZE("Many cultures living together in respect shows 'unity in ____'.",
      ["diversity", "conflict", "silence", "secrecy"], "diversity",
      "'Unity in diversity' means being united while respecting many cultures.", "ERR_LO_G8CRA1_DIVERSITY", 1),
    MC("Which attitude best supports nation building?",
      ["Tolerance and willingness to work with others", "Prejudice and division", "Refusing all cooperation", "Looking down on others"], "Tolerance and willingness to work with others",
      "Tolerance and cooperation are attitudes that support nation building.", "ERR_LO_G8CRA1_ATTITUDE", 2),
    TF("Learning about other cultures can reduce prejudice.", "True",
      "Understanding other cultures reduces prejudice and supports unity.", "ERR_LO_G8CRA1_PREJUDICE", 1),
    {
      question: "Sort each action into PROMOTES nation building or HARMS it.",
      input_type: "sort-buckets",
      buckets: [{ id: "promote", label: "Promotes" }, { id: "harm", label: "Harms" }],
      items: [
        { id: "i1", text: "Celebrating Heritage Day together", correct_bucket: "promote" },
        { id: "i2", text: "Respecting all languages", correct_bucket: "promote" },
        { id: "i3", text: "Spreading racist jokes", correct_bucket: "harm" },
        { id: "i4", text: "Excluding people who differ", correct_bucket: "harm" },
      ],
      expected: "Celebrating heritage and respecting languages promote; racism and exclusion harm nation building.",
      pass_threshold: 0.75,
      memo: "Inclusion and respect build the nation; prejudice and exclusion break it down.",
      error_signals: ["ERR_LO_G8CRA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for a class nation-building project in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Decide on a unifying theme (e.g. our cultures)" },
        { id: "s2", text: "Invite everyone to share their heritage" },
        { id: "s3", text: "Hold the event with respect and inclusion" },
        { id: "s4", text: "Reflect on what united the group" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Choose a unifying theme, invite sharing, hold an inclusive event, then reflect on what united you.",
      memo: "Build unity by choosing a shared theme, inviting participation, including all, and reflecting.",
      error_signals: ["ERR_LO_G8CRA1_SEQ"], difficulty: 2,
    },
    MC("The core idea of nation building is…",
      ["many people, one united and respectful nation", "one group ruling all others", "everyone staying apart", "constant conflict"], "many people, one united and respectful nation",
      "Nation building unites diverse people into one respectful nation.", "ERR_LO_G8CRA1_SUMMARY", 2),
    TF("Respecting all of South Africa's official languages supports nation building.", "True",
      "Valuing every official language helps people feel included and builds national unity.", "ERR_LO_G8CRA1_LANGUAGE", 1),
  ],

  // CR.A2 · Human rights violations
  "LO.G8.CR.A2": [
    MC("What is a human rights VIOLATION?",
      ["When someone's rights are denied or taken away", "When rights are respected", "A type of sport", "A school holiday"], "When someone's rights are denied or taken away",
      "A human rights violation happens when a person's rights are denied or taken away.", "ERR_LO_G8CRA2_DEF", 1),
    TF("Unfair discrimination is a type of human rights violation.", "True",
      "Unfair discrimination denies people equal rights and is a violation.", "ERR_LO_G8CRA2_DISCRIM", 1),
    MC("Which is an example of a human rights violation?",
      ["Stopping a child from going to school", "Letting a child attend school", "Respecting freedom of religion", "Treating people equally"], "Stopping a child from going to school",
      "Denying education violates a person's right to education.", "ERR_LO_G8CRA2_EXAMPLE", 1),
    CLOZE("Treating people unfairly because of race or gender is unfair ____.",
      ["discrimination", "kindness", "equality", "respect"], "discrimination",
      "Unfair discrimination treats people unequally based on things like race or gender.", "ERR_LO_G8CRA2_DISCRIMINATION", 1),
    MC("Which is a COUNTER-STRATEGY to human rights violations?",
      ["Reporting and standing up against the violation", "Ignoring it", "Joining in", "Keeping silent"], "Reporting and standing up against the violation",
      "Counter-strategies include reporting, speaking up and supporting victims.", "ERR_LO_G8CRA2_COUNTER", 2),
    TF("Slavery and forced labour are serious human rights violations.", "True",
      "Slavery and forced labour deny basic freedoms and are grave violations.", "ERR_LO_G8CRA2_SLAVERY", 1),
    MC("Where can a violation of human rights be reported?",
      ["The police or the Human Rights Commission", "Nowhere", "Only to friends", "Kept secret always"], "The police or the Human Rights Commission",
      "Violations can be reported to the police or the South African Human Rights Commission.", "ERR_LO_G8CRA2_REPORT", 2),
    CLOZE("Speaking up for someone whose rights are denied is called being an ____.",
      ["advocate", "enemy", "bystander", "observer"], "advocate",
      "An advocate speaks and acts to defend others' rights.", "ERR_LO_G8CRA2_ADVOCATE", 2),
    TF("Doing nothing while someone's rights are violated helps the situation.", "False",
      "Staying silent allows violations to continue; speaking up and reporting help.", "ERR_LO_G8CRA2_SILENCE", 1),
    MC("A worker is denied pay because of their religion. This is…",
      ["a human rights violation that can be reported", "fair treatment", "good business", "not a rights issue"], "a human rights violation that can be reported",
      "Denying pay due to religion is unfair discrimination — a reportable violation.", "ERR_LO_G8CRA2_SCENARIO", 3),
    MC("Why is it important to know about human rights violations?",
      ["So you can recognise, prevent and report them", "So you can ignore them", "So you can commit them", "It is not important"], "So you can recognise, prevent and report them",
      "Knowing about violations helps you recognise, prevent and report them.", "ERR_LO_G8CRA2_KNOW", 2),
    TF("Bullying that targets someone's race or religion can be a rights violation.", "True",
      "Targeting someone's race or religion through bullying violates their dignity and rights.", "ERR_LO_G8CRA2_BULLY", 2),
    CLOZE("Organisations that protect rights help ____ victims of violations.",
      ["support", "harm", "ignore", "blame"], "support",
      "Rights organisations support and protect victims of violations.", "ERR_LO_G8CRA2_ORGS", 1),
    MC("Which is a positive counter-strategy a school can use?",
      ["Teaching respect and having anti-bullying rules", "Allowing discrimination", "Ignoring complaints", "Punishing victims"], "Teaching respect and having anti-bullying rules",
      "Education about respect and clear anti-bullying rules counter rights violations.", "ERR_LO_G8CRA2_SCHOOL", 2),
    TF("Everyone has a role in protecting human rights, not just the government.", "True",
      "Protecting rights is everyone's responsibility, not only the government's.", "ERR_LO_G8CRA2_EVERYONE", 1),
    MC("The best response if you witness a clear rights violation is to…",
      ["safely report it to a trusted authority", "join in", "laugh", "pretend you saw nothing"], "safely report it to a trusted authority",
      "Reporting to a trusted authority is the responsible response to a violation.", "ERR_LO_G8CRA2_WITNESS", 2),
    {
      question: "Sort each into a human RIGHTS VIOLATION or RESPECT for rights.",
      input_type: "sort-buckets",
      buckets: [{ id: "violation", label: "Rights violation" }, { id: "respect", label: "Respect for rights" }],
      items: [
        { id: "i1", text: "Denying someone a job because of race", correct_bucket: "violation" },
        { id: "i2", text: "Forcing a child to work instead of school", correct_bucket: "violation" },
        { id: "i3", text: "Treating all customers equally", correct_bucket: "respect" },
        { id: "i4", text: "Allowing freedom of religion", correct_bucket: "respect" },
      ],
      expected: "Race-based denial and child labour are violations; equal treatment and freedom of religion respect rights.",
      pass_threshold: 0.75,
      memo: "Violations deny rights; respect upholds equality, freedom and dignity.",
      error_signals: ["ERR_LO_G8CRA2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps for responding to a human rights violation in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise that a right is being violated" },
        { id: "s2", text: "Stay safe and gather the facts" },
        { id: "s3", text: "Report it to a trusted authority" },
        { id: "s4", text: "Support the victim" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise the violation, stay safe and gather facts, report it, then support the victim.",
      memo: "Respond by recognising, staying safe, reporting and supporting the victim.",
      error_signals: ["ERR_LO_G8CRA2_SEQ"], difficulty: 2,
    },
    MC("The key message about human rights violations is that they should be…",
      ["recognised, opposed and reported", "ignored and allowed", "celebrated", "kept secret"], "recognised, opposed and reported",
      "Violations should be recognised, opposed and reported to protect everyone's rights.", "ERR_LO_G8CRA2_SUMMARY", 2),
    TF("Knowing your rights helps you recognise when they, or others' rights, are violated.", "True",
      "Understanding your rights lets you spot and respond to violations against yourself and others.", "ERR_LO_G8CRA2_AWARE", 1),
  ],

  // CR.A3 · Gender equity
  "LO.G8.CR.A3": [
    MC("What does 'gender equity' mean?",
      ["Fair and equal treatment of all genders", "Treating one gender as better", "Ignoring fairness", "Only helping boys"], "Fair and equal treatment of all genders",
      "Gender equity means fair, equal treatment and opportunities for all genders.", "ERR_LO_G8CRA3_DEF", 1),
    TF("Girls and boys should have equal opportunities in sport and education.", "True",
      "Gender equity means equal opportunities in education, sport and life.", "ERR_LO_G8CRA3_EQUAL", 1),
    MC("Which is an example of a gender-equity issue in sport?",
      ["Girls' teams getting far fewer resources than boys'", "Both teams sharing facilities fairly", "Equal coaching for all", "Fair match scheduling"], "Girls' teams getting far fewer resources than boys'",
      "Unequal resources between girls' and boys' sport is a gender-equity issue.", "ERR_LO_G8CRA3_SPORT", 2),
    CLOZE("Violence aimed at someone because of their gender is gender-based ____.",
      ["violence", "support", "equality", "respect"], "violence",
      "Gender-based violence (GBV) is violence directed at someone because of their gender.", "ERR_LO_G8CRA3_GBV", 1),
    MC("Gender-based violence and rape are…",
      ["serious crimes with serious consequences", "minor matters", "acceptable behaviour", "private and fine"], "serious crimes with serious consequences",
      "GBV and rape are serious crimes; the law protects victims and punishes offenders.", "ERR_LO_G8CRA3_CRIME", 2),
    TF("Gender-based violence can have emotional, health and social impacts on victims.", "True",
      "GBV harms victims emotionally, physically and socially.", "ERR_LO_G8CRA3_IMPACT", 1),
    MC("Which helps PREVENT violence against women and girls?",
      ["Respect, equality and enforcing the law", "Ignoring the problem", "Blaming victims", "Excusing abusers"], "Respect, equality and enforcing the law",
      "Prevention rests on respect, equality, education and enforcing laws like the Sexual Offences Act.", "ERR_LO_G8CRA3_PREVENT", 2),
    CLOZE("Victims of gender-based violence can find safety and help at a ____.",
      ["shelter", "stadium", "shop", "library"], "shelter",
      "Shelters, the police and helplines offer safety and help to victims of GBV.", "ERR_LO_G8CRA3_SHELTER", 1),
    TF("Gender stereotypes, like 'girls can't lead', support gender equity.", "False",
      "Harmful stereotypes work against gender equity by limiting people unfairly.", "ERR_LO_G8CRA3_STEREOTYPE", 2),
    MC("A girl is told she 'can't' study engineering because she is a girl. This is…",
      ["an unfair gender stereotype she has every right to challenge", "good advice", "a fair rule", "a law"], "an unfair gender stereotype she has every right to challenge",
      "Telling someone they can't pursue a field due to gender is an unfair stereotype.", "ERR_LO_G8CRA3_SCENARIO", 3),
    MC("Where can a victim of gender-based violence find help?",
      ["The police, a clinic, or a GBV helpline", "Nowhere", "Only from the abuser", "By staying silent"], "The police, a clinic, or a GBV helpline",
      "Police, clinics and GBV helplines provide help and safety for victims.", "ERR_LO_G8CRA3_HELP", 2),
    TF("Boys and men can also be affected by gender-based violence.", "True",
      "While women and girls are most affected, boys and men can also experience GBV.", "ERR_LO_G8CRA3_BOYS", 2),
    CLOZE("South Africa has a law on sexual ____ to protect victims.",
      ["offences", "holidays", "sports", "subjects"], "offences",
      "The Sexual Offences Act protects victims and sets out penalties for offenders.", "ERR_LO_G8CRA3_LAW", 2),
    MC("Which attitude best supports gender equity?",
      ["Respecting all genders as equal", "Believing one gender is superior", "Excusing GBV", "Limiting girls' choices"], "Respecting all genders as equal",
      "Treating all genders as equal is the foundation of gender equity.", "ERR_LO_G8CRA3_ATTITUDE", 1),
    TF("Reporting gender-based violence helps protect the victim and others.", "True",
      "Reporting GBV helps protect victims and can prevent further harm.", "ERR_LO_G8CRA3_REPORT", 1),
    MC("How can schools promote gender equity?",
      ["Equal opportunities and zero tolerance for abuse", "Favouring one gender", "Ignoring complaints", "Allowing harassment"], "Equal opportunities and zero tolerance for abuse",
      "Equal opportunities and zero tolerance for abuse promote gender equity at school.", "ERR_LO_G8CRA3_SCHOOL", 2),
    {
      question: "Sort each into PROMOTES gender equity or WORKS AGAINST it.",
      input_type: "sort-buckets",
      buckets: [{ id: "promote", label: "Promotes equity" }, { id: "against", label: "Works against it" }],
      items: [
        { id: "i1", text: "Equal pay for equal work", correct_bucket: "promote" },
        { id: "i2", text: "Girls and boys both leading projects", correct_bucket: "promote" },
        { id: "i3", text: "Saying 'cooking is only for girls'", correct_bucket: "against" },
        { id: "i4", text: "Excusing gender-based violence", correct_bucket: "against" },
      ],
      expected: "Equal pay and shared leadership promote equity; gender stereotypes and excusing GBV work against it.",
      pass_threshold: 0.75,
      memo: "Equity grows from equal treatment; stereotypes and excusing violence undermine it.",
      error_signals: ["ERR_LO_G8CRA3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps for safely helping a friend who reports gender-based violence in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Listen and believe them" },
        { id: "s2", text: "Reassure them it is not their fault" },
        { id: "s3", text: "Help them reach a trusted adult or helpline" },
        { id: "s4", text: "Support them as they get help" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Listen and believe, reassure it is not their fault, help them reach help, then support them.",
      memo: "Support a survivor by believing them, reassuring them, connecting them to help and staying supportive.",
      error_signals: ["ERR_LO_G8CRA3_SEQ"], difficulty: 2,
    },
    MC("The key message of gender equity is that…",
      ["everyone deserves equal respect, rights and safety", "one gender should dominate", "violence is acceptable", "stereotypes should rule"], "everyone deserves equal respect, rights and safety",
      "Gender equity means equal respect, rights and safety for everyone.", "ERR_LO_G8CRA3_SUMMARY", 2),
    TF("Gender-based violence is never the victim's fault.", "True",
      "Responsibility for gender-based violence always lies with the abuser, never the victim.", "ERR_LO_G8CRA3_NOTFAULT", 1),
  ],

  // CR.A4 · Cultural diversity in South Africa
  "LO.G8.CR.A4": [
    MC("What does 'cultural diversity' mean?",
      ["Many different cultures living in one society", "Everyone having the same culture", "One culture only", "No culture at all"], "Many different cultures living in one society",
      "Cultural diversity means many different cultures existing together in a society.", "ERR_LO_G8CRA4_DEF", 1),
    TF("South Africa is often called the 'Rainbow Nation' because of its diversity.", "True",
      "South Africa's many cultures earned it the nickname 'Rainbow Nation'.", "ERR_LO_G8CRA4_RAINBOW", 1),
    MC("Which is part of a culture?",
      ["Language, traditions and beliefs", "Only the weather", "A person's height", "A school bell"], "Language, traditions and beliefs",
      "Culture includes language, traditions, beliefs, food, music and customs.", "ERR_LO_G8CRA4_PARTS", 1),
    CLOZE("Valuing cultures different from your own shows ____ for diversity.",
      ["respect", "fear", "dislike", "suspicion"], "respect",
      "Respecting cultures different from your own is key to living in a diverse society.", "ERR_LO_G8CRA4_RESPECT", 1),
    MC("How can cultural norms and values influence behaviour?",
      ["They shape what people see as acceptable and important", "They have no effect", "They only affect food", "They never change"], "They shape what people see as acceptable and important",
      "Cultural norms and values influence attitudes, choices and behaviour.", "ERR_LO_G8CRA4_INFLUENCE", 2),
    TF("Learning about other cultures can enrich your own understanding.", "True",
      "Understanding diverse cultures enriches society and individuals.", "ERR_LO_G8CRA4_ENRICH", 1),
    MC("'Celebrate unity in diversity' means we should…",
      ["respect differences and enjoy what we share", "force everyone to be the same", "ignore other cultures", "compete over cultures"], "respect differences and enjoy what we share",
      "Unity in diversity means respecting differences while celebrating common bonds.", "ERR_LO_G8CRA4_UNITY", 2),
    CLOZE("Practices passed down in a culture, like ceremonies, are ____.",
      ["traditions", "mistakes", "accidents", "rules-only"], "traditions",
      "Traditions are cultural practices passed down through generations.", "ERR_LO_G8CRA4_TRADITIONS", 1),
    TF("Respecting difference includes respecting culture, religion and gender.", "True",
      "Respect for difference covers culture, religion and gender.", "ERR_LO_G8CRA4_DIFFERENCE", 1),
    MC("A classmate eats different food for cultural reasons. The respectful response is to…",
      ["be curious and respectful, not mocking", "laugh at the food", "tell them they are wrong", "refuse to sit near them"], "be curious and respectful, not mocking",
      "Curiosity and respect, not mockery, honour cultural difference.", "ERR_LO_G8CRA4_SCENARIO", 2),
    MC("Why is cultural diversity a strength for South Africa?",
      ["It brings varied ideas, talents and traditions together", "It causes only problems", "It has no value", "It should be removed"], "It brings varied ideas, talents and traditions together",
      "Diversity brings together varied ideas, talents and traditions, enriching society.", "ERR_LO_G8CRA4_STRENGTH", 2),
    TF("Stereotyping a whole culture is fair if it is 'just a joke'.", "False",
      "Stereotyping a culture is disrespectful and harmful, even as a 'joke'.", "ERR_LO_G8CRA4_STEREOTYPE", 2),
    CLOZE("Treating people of all cultures as equal upholds the value of ____.",
      ["equality", "division", "prejudice", "fear"], "equality",
      "Equality means treating people of all cultures fairly and as equals.", "ERR_LO_G8CRA4_EQUALITY", 1),
    MC("Which event celebrates South Africa's cultural diversity?",
      ["Heritage Day", "A maths test", "A power cut", "A traffic jam"], "Heritage Day",
      "Heritage Day celebrates the diverse cultures and heritage of South Africa.", "ERR_LO_G8CRA4_HERITAGE", 1),
    TF("Diverse cultural norms can relate to personal and community issues.", "True",
      "Cultural norms and values relate to many personal and community matters.", "ERR_LO_G8CRA4_NORMS", 1),
    MC("How should you respond if a tradition differs from your own beliefs?",
      ["Respect it while still holding your own values", "Demand they stop", "Mock it publicly", "Refuse to learn about it"], "Respect it while still holding your own values",
      "You can respect others' traditions while keeping your own values.", "ERR_LO_G8CRA4_RESPONSE", 2),
    {
      question: "Sort each response to cultural difference into RESPECTFUL or DISRESPECTFUL.",
      input_type: "sort-buckets",
      buckets: [{ id: "respect", label: "Respectful" }, { id: "disrespect", label: "Disrespectful" }],
      items: [
        { id: "i1", text: "Learning a greeting in a friend's language", correct_bucket: "respect" },
        { id: "i2", text: "Asking politely about a tradition", correct_bucket: "respect" },
        { id: "i3", text: "Mocking someone's accent", correct_bucket: "disrespect" },
        { id: "i4", text: "Stereotyping a whole group", correct_bucket: "disrespect" },
      ],
      expected: "Learning a greeting and asking politely are respectful; mocking and stereotyping are disrespectful.",
      pass_threshold: 0.75,
      memo: "Curiosity and politeness respect culture; mockery and stereotypes disrespect it.",
      error_signals: ["ERR_LO_G8CRA4_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for building respect in a diverse class in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Learn about the cultures around you" },
        { id: "s2", text: "Listen to others' experiences" },
        { id: "s3", text: "Treat everyone with equal respect" },
        { id: "s4", text: "Celebrate both differences and shared bonds" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Learn about cultures, listen, treat everyone equally, then celebrate differences and shared bonds.",
      memo: "Respect grows from learning, listening, equal treatment and celebrating unity in diversity.",
      error_signals: ["ERR_LO_G8CRA4_SEQ"], difficulty: 2,
    },
    MC("The key message about cultural diversity is that it is…",
      ["a strength to be respected and celebrated", "a problem to be removed", "something to fear", "unimportant"], "a strength to be respected and celebrated",
      "Cultural diversity is a strength to respect and celebrate.", "ERR_LO_G8CRA4_SUMMARY", 2),
    TF("Learning a few words in a classmate's home language is a sign of respect.", "True",
      "Making an effort with someone's language shows genuine respect for their culture.", "ERR_LO_G8CRA4_LANGUAGE", 1),
  ],

  // CR.A5 · Religions and social development
  "LO.G8.CR.A5": [
    MC("What is 'social development'?",
      ["Improving people's wellbeing and communities", "Building roads only", "Making profit only", "Ignoring the poor"], "Improving people's wellbeing and communities",
      "Social development means improving people's wellbeing and the life of communities.", "ERR_LO_G8CRA5_DEF", 1),
    TF("Religious organisations often help people in need in their communities.", "True",
      "Many religious organisations contribute to social development through charity and care.", "ERR_LO_G8CRA5_HELP", 1),
    MC("Which is a way religious organisations contribute to social development?",
      ["Running soup kitchens and shelters", "Increasing poverty", "Ignoring the needy", "Causing harm"], "Running soup kitchens and shelters",
      "Religious groups run soup kitchens, shelters, clinics and schools that aid social development.", "ERR_LO_G8CRA5_WAYS", 1),
    CLOZE("Giving help to those in need, often through charity, is called ____.",
      ["outreach", "selfishness", "neglect", "greed"], "outreach",
      "Outreach is reaching out to help those in need, often through charity work.", "ERR_LO_G8CRA5_OUTREACH", 2),
    MC("A faith-based group provides free meals to homeless people. This supports…",
      ["social development and care for the vulnerable", "harm to the community", "no real benefit", "discrimination"], "social development and care for the vulnerable",
      "Providing meals to the homeless supports social development and care for the vulnerable.", "ERR_LO_G8CRA5_MEALS", 2),
    TF("Helping others is a value found across many religions.", "True",
      "Caring for others and charity are values shared by many religions.", "ERR_LO_G8CRA5_VALUE", 1),
    MC("Which service might a religious organisation provide?",
      ["Education, healthcare or disaster relief", "Spreading conflict", "Increasing hunger", "Excluding the poor"], "Education, healthcare or disaster relief",
      "Religious organisations may provide education, healthcare and disaster relief.", "ERR_LO_G8CRA5_SERVICES", 2),
    CLOZE("Organisations that help society without aiming for profit are ____-profit.",
      ["non", "high", "fast", "for"], "non",
      "Non-profit organisations work to help society rather than to make profit.", "ERR_LO_G8CRA5_NONPROFIT", 2),
    TF("Only the government can contribute to social development.", "False",
      "Religious groups, NGOs and individuals all contribute to social development, not just government.", "ERR_LO_G8CRA5_GOVTONLY", 1),
    MC("How can young people support religious or community social development?",
      ["Volunteer time and help with projects", "Refuse to help", "Mock charities", "Do nothing"], "Volunteer time and help with projects",
      "Volunteering time and helping with projects supports social development.", "ERR_LO_G8CRA5_YOUTH", 2),
    MC("During a flood, a religious group shelters and feeds families. This is an example of…",
      ["disaster relief and social care", "causing harm", "self-interest", "discrimination"], "disaster relief and social care",
      "Sheltering and feeding flood victims is disaster relief and social care.", "ERR_LO_G8CRA5_DISASTER", 2),
    TF("Caring for the poor and sick is a common contribution of religions.", "True",
      "Caring for the poor and sick is a frequent religious contribution to society.", "ERR_LO_G8CRA5_POOR", 1),
    CLOZE("People who help others without being paid are ____.",
      ["volunteers", "employers", "customers", "tourists"], "volunteers",
      "Volunteers give their time freely to help others and their community.", "ERR_LO_G8CRA5_VOLUNTEER", 1),
    MC("Why are the contributions of religious organisations valuable to society?",
      ["They support people that other services may miss", "They harm communities", "They have no value", "They only help themselves"], "They support people that other services may miss",
      "Religious organisations often reach and support people other services may miss.", "ERR_LO_G8CRA5_VALUABLE", 2),
    TF("Different religions can work together to help a community.", "True",
      "People of different religions can cooperate to support their community.", "ERR_LO_G8CRA5_TOGETHER", 1),
    MC("Building a clinic or school is an example of contributing to…",
      ["long-term social development", "social harm", "personal profit only", "nothing useful"], "long-term social development",
      "Building clinics and schools contributes to long-term social development.", "ERR_LO_G8CRA5_LONGTERM", 2),
    {
      question: "Sort each action into SUPPORTS social development or DOES NOT.",
      input_type: "sort-buckets",
      buckets: [{ id: "supports", label: "Supports development" }, { id: "not", label: "Does not" }],
      items: [
        { id: "i1", text: "Running a free clinic", correct_bucket: "supports" },
        { id: "i2", text: "Feeding the homeless", correct_bucket: "supports" },
        { id: "i3", text: "Ignoring those in need", correct_bucket: "not" },
        { id: "i4", text: "Excluding the poor", correct_bucket: "not" },
      ],
      expected: "Clinics and feeding programmes support development; ignoring or excluding the needy does not.",
      pass_threshold: 0.75,
      memo: "Social development helps the vulnerable; neglect and exclusion do not.",
      error_signals: ["ERR_LO_G8CRA5_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for a youth community-service project in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Identify a need in the community" },
        { id: "s2", text: "Plan a project to help" },
        { id: "s3", text: "Carry out the project with others" },
        { id: "s4", text: "Reflect on the difference made" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Identify a need, plan a project, carry it out with others, then reflect on the impact.",
      memo: "Serve well by identifying a need, planning, acting together and reflecting.",
      error_signals: ["ERR_LO_G8CRA5_SEQ"], difficulty: 2,
    },
    MC("The key message is that religions and community groups can…",
      ["make a real, positive difference in society", "only cause problems", "do nothing useful", "harm development"], "make a real, positive difference in society",
      "Religious and community organisations can make a real, positive difference to society.", "ERR_LO_G8CRA5_SUMMARY", 2),
    TF("Young people can contribute to social development by volunteering their time.", "True",
      "Volunteering time and skills lets young people contribute to social development.", "ERR_LO_G8CRA5_YOUTH2", 1),
  ],

  // ════════════════════════════ WORLD OF WORK (Term 2) ═════════════════════════
  // WW.A1 · Learning styles
  "LO.G8.WW.A1": [
    MC("What is a 'learning style'?",
      ["The way a person learns best", "A type of clothing", "A school subject", "A sport"], "The way a person learns best",
      "A learning style is the way an individual learns and takes in information best.", "ERR_LO_G8WWA1_DEF", 1),
    TF("Visual, aural, kinesthetic and reading/writing are types of learning styles.", "True",
      "Common learning styles include visual, aural, kinesthetic, and reading/writing.", "ERR_LO_G8WWA1_TYPES", 1),
    MC("A VISUAL learner learns best by…",
      ["seeing diagrams, charts and pictures", "only listening", "only moving", "ignoring images"], "seeing diagrams, charts and pictures",
      "Visual learners learn best through seeing — diagrams, charts and images.", "ERR_LO_G8WWA1_VISUAL", 1),
    CLOZE("A learner who learns best by listening is an ____ learner.",
      ["aural", "frozen", "silent", "blind"], "aural",
      "Aural (auditory) learners learn best by listening — to explanations, discussions or recordings.", "ERR_LO_G8WWA1_AURAL", 1),
    MC("A KINESTHETIC learner learns best by…",
      ["doing and moving — hands-on activities", "only reading silently", "only watching", "sitting still always"], "doing and moving — hands-on activities",
      "Kinesthetic learners learn best by doing — hands-on, practical activities.", "ERR_LO_G8WWA1_KINESTHETIC", 1),
    TF("Knowing your learning style can help you study more effectively.", "True",
      "Knowing your learning style lets you choose study methods that work best for you.", "ERR_LO_G8WWA1_EFFECTIVE", 1),
    MC("A READING/WRITING learner learns best by…",
      ["reading notes and writing summaries", "only moving around", "avoiding all text", "only listening"], "reading notes and writing summaries",
      "Reading/writing learners learn best through reading and writing text.", "ERR_LO_G8WWA1_READWRITE", 1),
    CLOZE("Most people learn using a ____ of styles, not just one.",
      ["mix", "lack", "ban", "fear"], "mix",
      "Many people use a mix of learning styles rather than only one.", "ERR_LO_G8WWA1_MIX", 2),
    TF("There is one 'best' learning style that is right for everyone.", "False",
      "No single style suits everyone; people differ and often blend styles.", "ERR_LO_G8WWA1_BEST", 2),
    MC("Sipho remembers things best when he draws diagrams. His style is likely…",
      ["visual", "aural", "kinesthetic only", "none"], "visual",
      "Learning best from drawing diagrams points to a visual learning style.", "ERR_LO_G8WWA1_IDENTIFY", 2),
    MC("How can a kinesthetic learner study spelling effectively?",
      ["Write or trace the words while saying them", "Sit completely still", "Only listen once", "Avoid practice"], "Write or trace the words while saying them",
      "Kinesthetic learners benefit from movement, like writing or tracing while learning.", "ERR_LO_G8WWA1_APPLY", 2),
    TF("Applying your own learning style means choosing study methods that suit you.", "True",
      "Applying your learning style means picking study methods that match how you learn best.", "ERR_LO_G8WWA1_OWNSTYLE", 1),
    CLOZE("A learner who likes group discussion may favour the ____ style.",
      ["aural", "visual-only", "still", "silent"], "aural",
      "Enjoying discussion suggests an aural (listening and speaking) preference.", "ERR_LO_G8WWA1_DISCUSS", 2),
    MC("Why is it useful to use more than one learning style?",
      ["It reinforces learning in different ways", "It wastes time", "It confuses the brain", "It has no benefit"], "It reinforces learning in different ways",
      "Using several styles reinforces learning through different channels.", "ERR_LO_G8WWA1_MULTI", 2),
    TF("A visual learner might use colour-coded notes and mind maps.", "True",
      "Colour-coding and mind maps suit visual learners well.", "ERR_LO_G8WWA1_TOOLS", 1),
    MC("How can knowing learning styles help in the world of work?",
      ["It helps you learn new job skills efficiently", "It is useless at work", "It stops learning", "It only matters at school"], "It helps you learn new job skills efficiently",
      "Knowing how you learn helps you pick up new job skills efficiently.", "ERR_LO_G8WWA1_WORK", 2),
    {
      question: "Match each learner to a fitting study method by ordering the methods for Learner 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Visual) Use diagrams and colour-coded notes" },
        { id: "s2", text: "(Aural) Listen to and discuss the material" },
        { id: "s3", text: "(Kinesthetic) Do hands-on activities" },
        { id: "s4", text: "(Reading/Writing) Read and write summaries" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Visual→diagrams, aural→listen/discuss, kinesthetic→hands-on, reading/writing→read and summarise.",
      memo: "Each learning style has study methods that suit it best.",
      error_signals: ["ERR_LO_G8WWA1_SEQ"], difficulty: 2,
    },
    {
      question: "Sort each study method into VISUAL or KINESTHETIC.",
      input_type: "sort-buckets",
      buckets: [{ id: "visual", label: "Visual" }, { id: "kinesthetic", label: "Kinesthetic" }],
      items: [
        { id: "i1", text: "Drawing a mind map", correct_bucket: "visual" },
        { id: "i2", text: "Using colour-coded charts", correct_bucket: "visual" },
        { id: "i3", text: "Building a model to learn", correct_bucket: "kinesthetic" },
        { id: "i4", text: "Acting out a process", correct_bucket: "kinesthetic" },
      ],
      expected: "Mind maps and charts are visual; building models and acting out are kinesthetic.",
      pass_threshold: 0.75,
      memo: "Visual methods use seeing; kinesthetic methods use doing and moving.",
      error_signals: ["ERR_LO_G8WWA1_SORT"], difficulty: 1,
    },
    MC("The main benefit of knowing your learning style is that you can…",
      ["study and learn in the way that works best for you", "avoid all studying", "copy others exactly", "stop learning new things"], "study and learn in the way that works best for you",
      "Knowing your learning style lets you learn in the way that works best for you.", "ERR_LO_G8WWA1_SUMMARY", 2),
    TF("Most people learn best by combining several learning styles.", "True",
      "Combining styles reinforces learning and suits how most people actually learn.", "ERR_LO_G8WWA1_COMBINE", 1),
  ],

  // WW.A2 · Six career categories
  "LO.G8.WW.A2": [
    MC("How many main career categories are studied in Grade 8 LO?",
      ["Six", "Two", "Twenty", "One"], "Six",
      "The six career categories are investigative, enterprising, realistic, artistic, conventional and social.", "ERR_LO_G8WWA2_SIX", 1),
    TF("The six career categories include 'investigative' and 'artistic'.", "True",
      "The six categories are investigative, enterprising, realistic, artistic, conventional and social.", "ERR_LO_G8WWA2_LIST", 1),
    MC("Someone who loves solving puzzles and research suits which category?",
      ["Investigative", "Artistic", "Realistic", "Conventional"], "Investigative",
      "Investigative careers suit people who enjoy research, analysis and solving problems.", "ERR_LO_G8WWA2_INVESTIGATIVE", 2),
    CLOZE("A person who loves art, music or design fits the ____ category.",
      ["artistic", "realistic", "conventional", "investigative"], "artistic",
      "Artistic careers suit creative people who enjoy art, music, writing or design.", "ERR_LO_G8WWA2_ARTISTIC", 2),
    MC("A 'realistic' career type usually involves…",
      ["practical, hands-on or outdoor work", "only office paperwork", "only acting", "only research"], "practical, hands-on or outdoor work",
      "Realistic careers involve practical, hands-on or outdoor work, like building or farming.", "ERR_LO_G8WWA2_REALISTIC", 2),
    TF("A 'social' career type involves helping and working with people.", "True",
      "Social careers involve helping, teaching or caring for people.", "ERR_LO_G8WWA2_SOCIAL", 1),
    MC("An 'enterprising' person is likely to enjoy…",
      ["leading, persuading and starting projects", "only following orders", "avoiding people", "only manual labour"], "leading, persuading and starting projects",
      "Enterprising careers suit people who like leading, persuading and business.", "ERR_LO_G8WWA2_ENTERPRISING", 2),
    CLOZE("A 'conventional' person enjoys organised work with data and ____.",
      ["detail", "chaos", "danger", "guessing"], "detail",
      "Conventional careers suit people who like organised, detailed work with data and records.", "ERR_LO_G8WWA2_CONVENTIONAL", 2),
    TF("Knowing your career category can guide your subject choices.", "True",
      "Matching your category to careers helps guide subject and study choices.", "ERR_LO_G8WWA2_GUIDE", 1),
    MC("Naledi loves caring for people and is patient. A fitting category is…",
      ["social", "realistic only", "conventional only", "none"], "social",
      "Patience and caring for people fit the social career category.", "ERR_LO_G8WWA2_MATCH", 2),
    MC("How does work meet South Africa's social and economic needs?",
      ["It provides services, goods and jobs people need", "It has no effect", "It only helps the worker", "It harms the economy"], "It provides services, goods and jobs people need",
      "Work provides services, goods and jobs that meet social and economic needs.", "ERR_LO_G8WWA2_NEEDS", 2),
    TF("Identifying needs in your community can reveal useful career paths.", "True",
      "Community needs point to careers that can meet those needs.", "ERR_LO_G8WWA2_COMMUNITY", 2),
    CLOZE("Different categories need different thinking and ____ skills.",
      ["learning", "sleeping", "eating", "running"], "learning",
      "Each career category requires particular thinking and learning skills.", "ERR_LO_G8WWA2_SKILLS", 1),
    MC("Which school subjects suit an investigative (science) career?",
      ["Sciences and Mathematics", "Only physical education", "No subjects", "Only art"], "Sciences and Mathematics",
      "Investigative science careers usually need sciences and mathematics.", "ERR_LO_G8WWA2_SUBJECTS", 2),
    TF("A person can have interests that fit more than one career category.", "True",
      "Many people's interests span more than one category.", "ERR_LO_G8WWA2_MULTI", 1),
    MC("Why match your interests and abilities to a career category?",
      ["You are more likely to enjoy and do well at the work", "It locks you in forever", "Interests do not matter", "Only pay matters"], "You are more likely to enjoy and do well at the work",
      "Matching interests and abilities to a category leads to more enjoyable, successful work.", "ERR_LO_G8WWA2_WHY", 2),
    {
      question: "Match each career to its category by ordering the categories for Career 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Scientist) Investigative" },
        { id: "s2", text: "(Graphic designer) Artistic" },
        { id: "s3", text: "(Builder) Realistic" },
        { id: "s4", text: "(Nurse) Social" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Scientist→investigative, graphic designer→artistic, builder→realistic, nurse→social.",
      memo: "Careers fall into categories based on the kind of work and interests they involve.",
      error_signals: ["ERR_LO_G8WWA2_SEQ"], difficulty: 2,
    },
    {
      question: "Sort each career into the SOCIAL or REALISTIC category.",
      input_type: "sort-buckets",
      buckets: [{ id: "social", label: "Social" }, { id: "realistic", label: "Realistic" }],
      items: [
        { id: "i1", text: "Teacher", correct_bucket: "social" },
        { id: "i2", text: "Counsellor", correct_bucket: "social" },
        { id: "i3", text: "Plumber", correct_bucket: "realistic" },
        { id: "i4", text: "Mechanic", correct_bucket: "realistic" },
      ],
      expected: "Teacher and counsellor are social; plumber and mechanic are realistic.",
      pass_threshold: 0.75,
      memo: "Social careers help people; realistic careers are practical and hands-on.",
      error_signals: ["ERR_LO_G8WWA2_SORT"], difficulty: 1,
    },
    MC("The main use of the six career categories is to…",
      ["help you explore careers that match your interests", "force one job on everyone", "limit your choices", "replace school subjects"], "help you explore careers that match your interests",
      "The categories help you explore careers matching your interests and abilities.", "ERR_LO_G8WWA2_SUMMARY", 2),
    TF("A person's interests can fit more than one career category.", "True",
      "Many people have interests spanning several career categories, which widens their options.", "ERR_LO_G8WWA2_SPAN", 1),
  ],

  // WW.A3 · School subjects and decision-making
  "LO.G8.WW.A3": [
    MC("How can your performance in school subjects help with career choices?",
      ["Strong subjects can point to suitable careers", "Subjects have no link to careers", "Only sport matters", "Marks are irrelevant"], "Strong subjects can point to suitable careers",
      "Your strengths in subjects hint at careers that may suit your abilities.", "ERR_LO_G8WWA3_DEF", 1),
    TF("Your interests and abilities are both worth considering for a career.", "True",
      "Good career decisions weigh both interests and abilities.", "ERR_LO_G8WWA3_BOTH", 1),
    MC("Which is a THEORETICAL type of learning activity?",
      ["Reading and discussing ideas", "Building a wall", "Running a race", "Planting a tree"], "Reading and discussing ideas",
      "Theoretical activities involve ideas, reading and discussion rather than hands-on work.", "ERR_LO_G8WWA3_THEORY", 2),
    CLOZE("Doing experiments and building models are ____ activities.",
      ["practical", "imaginary", "boring", "secret"], "practical",
      "Practical activities are hands-on, like experiments and building models.", "ERR_LO_G8WWA3_PRACTICAL", 1),
    MC("Why think about the 'demands' of a subject?",
      ["Different subjects need different thinking and skills", "Subjects have no demands", "All subjects are identical", "It does not matter"], "Different subjects need different thinking and skills",
      "Each subject demands particular thinking and learning skills.", "ERR_LO_G8WWA3_DEMANDS", 2),
    TF("Good decision-making considers your strengths, interests and goals.", "True",
      "Sound decisions weigh your strengths, interests, abilities and goals.", "ERR_LO_G8WWA3_DECISION", 1),
    MC("What is the FIRST step in a good decision-making process?",
      ["Understand the decision and gather information", "Choose randomly", "Copy a friend", "Avoid deciding"], "Understand the decision and gather information",
      "Good decisions start with understanding the choice and gathering information.", "ERR_LO_G8WWA3_FIRSTSTEP", 2),
    CLOZE("A subject you both enjoy and do well in matches your interest and ____.",
      ["ability", "fear", "height", "address"], "ability",
      "A subject you enjoy and do well in matches both interest and ability.", "ERR_LO_G8WWA3_ABILITY", 1),
    TF("Choosing a career direction should ignore what you are good at.", "False",
      "Your abilities matter; ignoring them leads to poor career decisions.", "ERR_LO_G8WWA3_IGNORE", 2),
    MC("Sipho loves Mathematics and solving problems but dislikes art. A sensible direction is…",
      ["a maths- or science-based field", "a pure fine-art career", "something he dislikes", "ignoring his strengths"], "a maths- or science-based field",
      "Matching his maths strength and problem-solving interest points to a maths/science field.", "ERR_LO_G8WWA3_SCENARIO", 3),
    MC("Which is a GROUP learning activity?",
      ["A team project", "Silent reading alone", "A solo test", "Studying by yourself"], "A team project",
      "Group activities, like team projects, involve working with others.", "ERR_LO_G8WWA3_GROUP", 1),
    TF("Knowing how you like to learn can help you choose suitable subjects.", "True",
      "Understanding your learning preferences helps with subject and career choices.", "ERR_LO_G8WWA3_LEARNPREF", 1),
    CLOZE("Choosing a career that fits your strength, ability, interest and ____ leads to satisfaction.",
      ["passion", "boredom", "fear", "luck"], "passion",
      "Decisions linking strength, ability, interest and passion lead to satisfying careers.", "ERR_LO_G8WWA3_PASSION", 2),
    MC("Why gather information before making a career-related decision?",
      ["To make an informed choice, not a guess", "To waste time", "To avoid deciding", "Information is useless"], "To make an informed choice, not a guess",
      "Gathering information leads to informed decisions rather than guesses.", "ERR_LO_G8WWA3_INFO", 2),
    TF("It is wise to consider several options before deciding on a direction.", "True",
      "Weighing several options leads to better decisions than choosing the first idea.", "ERR_LO_G8WWA3_OPTIONS", 1),
    MC("A balanced decision considers…",
      ["interests, abilities, demands and goals together", "only what friends do", "only money", "nothing in particular"], "interests, abilities, demands and goals together",
      "Balanced decisions weigh interests, abilities, subject demands and goals.", "ERR_LO_G8WWA3_BALANCED", 2),
    {
      question: "Put the steps of a good decision-making process in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Understand the decision to be made" },
        { id: "s2", text: "Gather information and options" },
        { id: "s3", text: "Weigh the options against your strengths and goals" },
        { id: "s4", text: "Make the choice and review it later" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Understand the decision, gather options, weigh them against strengths and goals, then choose and review.",
      memo: "Decide well by understanding, gathering options, weighing them, and choosing then reviewing.",
      error_signals: ["ERR_LO_G8WWA3_SEQ"], difficulty: 2,
    },
    {
      question: "Sort each learning activity into THEORETICAL or PRACTICAL.",
      input_type: "sort-buckets",
      buckets: [{ id: "theory", label: "Theoretical" }, { id: "practical", label: "Practical" }],
      items: [
        { id: "i1", text: "Discussing a poem", correct_bucket: "theory" },
        { id: "i2", text: "Reading about history", correct_bucket: "theory" },
        { id: "i3", text: "Doing a science experiment", correct_bucket: "practical" },
        { id: "i4", text: "Wiring a circuit", correct_bucket: "practical" },
      ],
      expected: "Discussing and reading are theoretical; experiments and wiring are practical.",
      pass_threshold: 0.75,
      memo: "Theoretical work uses ideas and text; practical work is hands-on.",
      error_signals: ["ERR_LO_G8WWA3_SORT"], difficulty: 1,
    },
    MC("The key idea linking school subjects and careers is to…",
      ["use your strengths and interests to guide informed choices", "ignore your marks", "pick a career by chance", "avoid all decisions"], "use your strengths and interests to guide informed choices",
      "Use your subject strengths and interests to make informed career decisions.", "ERR_LO_G8WWA3_SUMMARY", 2),
    TF("Considering several options leads to better decisions than choosing the first idea.", "True",
      "Weighing several options before deciding leads to better, more informed choices.", "ERR_LO_G8WWA3_WEIGH", 1),
  ],
};

export default G8B;
