// ─── Life Orientation SP — Grade 8 authored pools (part 1: DS · HE) ──────────
//
// Keyed by skill id → question array. Refs auto-assigned by the generator.
// Tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
// Each pool holds exactly 20 items.
//
// CAPS Grade 8 topics here:
//   Development of the self in society · Health, social & environmental responsibility

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8 = {
  // ════════════════ DEVELOPMENT OF THE SELF IN SOCIETY (Term 1) ════════════════
  // DS.A1 · Self-concept and self-motivation
  "LO.G8.DS.A1": [
    MC("What is 'self-concept'?",
      ["The overall idea you have about who you are", "Your shoe size", "Your home address", "Your school timetable"], "The overall idea you have about who you are",
      "Self-concept is the overall picture and understanding you have of yourself.", "ERR_LO_G8DSA1_DEF", 1),
    TF("Self-motivation means pushing yourself to act without needing others to force you.", "True",
      "Self-motivation is the inner drive to act and reach goals without outside pressure.", "ERR_LO_G8DSA1_MOTIV", 1),
    MC("Which factor can INFLUENCE self-concept formation?",
      ["Family, friends, media, culture and religion", "Only the weather", "The day of the week", "Your bag colour"], "Family, friends, media, culture and religion",
      "Self-concept is shaped by media, environment, friends, family, culture, religion and community.", "ERR_LO_G8DSA1_FACTORS", 2),
    CLOZE("Encouraging yourself with kind, hopeful words is called positive self-____.",
      ["talk", "doubt", "harm", "pity"], "talk",
      "Positive self-talk uses encouraging words to build confidence and motivation.", "ERR_LO_G8DSA1_SELFTALK", 1),
    MC("Which is an example of POSITIVE self-talk?",
      ["'I worked hard and I can improve'", "'I'm useless'", "'I'll never manage'", "'Everyone is better than me'"], "'I worked hard and I can improve'",
      "Positive self-talk focuses on effort and growth, boosting motivation.", "ERR_LO_G8DSA1_EXAMPLE", 1),
    TF("Each person is unique, with their own mix of strengths and qualities.", "True",
      "Individuality and uniqueness mean everyone has their own strengths and qualities.", "ERR_LO_G8DSA1_UNIQUE", 1),
    MC("How can media influence a teenager's self-concept?",
      ["It can set unrealistic ideals to compare against", "It cannot affect anyone", "It only shows the truth", "It improves self-image automatically"], "It can set unrealistic ideals to compare against",
      "Media can present unrealistic ideals; comparing yourself to them can harm self-concept.", "ERR_LO_G8DSA1_MEDIA", 2),
    CLOZE("Reaching a goal you set gives you a sense of personal ____.",
      ["achievement", "boredom", "failure", "fear"], "achievement",
      "Personal achievements strengthen self-concept and self-motivation.", "ERR_LO_G8DSA1_ACHIEVE", 1),
    MC("A strategy to EXTEND your personal potential is to…",
      ["set goals and keep learning new skills", "stop trying anything new", "avoid all challenges", "copy others exactly"], "set goals and keep learning new skills",
      "Setting goals and learning new skills helps you extend your potential.", "ERR_LO_G8DSA1_EXTEND", 2),
    TF("Comparing yourself constantly to others usually strengthens self-concept.", "False",
      "Constant comparison often damages self-concept; focusing on your own growth is healthier.", "ERR_LO_G8DSA1_COMPARE", 2),
    MC("Thandi failed a test and thinks 'I'm stupid.' A healthier, motivating thought is…",
      ["'I can study differently and do better next time'", "'I should give up'", "'I'll never pass anything'", "'It's hopeless'"], "'I can study differently and do better next time'",
      "Reframing setbacks as chances to improve protects self-concept and keeps motivation alive.", "ERR_LO_G8DSA1_REFRAME", 3),
    MC("Which is an INTERNAL source of motivation?",
      ["Personal pride in doing your best", "A teacher's punishment", "A cash reward only", "Fear of others"], "Personal pride in doing your best",
      "Internal (intrinsic) motivation comes from within, like pride and personal satisfaction.", "ERR_LO_G8DSA1_INTERNAL", 2),
    TF("Your culture and religion can be part of how you see yourself.", "True",
      "Culture and religion are among the influences that shape self-concept.", "ERR_LO_G8DSA1_CULTURE", 1),
    CLOZE("Believing you can improve with effort is called a growth ____.",
      ["mindset", "excuse", "problem", "ending"], "mindset",
      "A growth mindset is the belief that ability can grow with effort and practice.", "ERR_LO_G8DSA1_MINDSET", 2),
    MC("Why is self-motivation important for success?",
      ["It keeps you working toward goals even when it is hard", "It makes work impossible", "It removes all goals", "It only matters to adults"], "It keeps you working toward goals even when it is hard",
      "Self-motivation keeps you pursuing goals through difficulties.", "ERR_LO_G8DSA1_WHY", 2),
    TF("Supportive friends and family can strengthen a positive self-concept.", "True",
      "Encouraging relationships help build a healthy, positive self-concept.", "ERR_LO_G8DSA1_SUPPORT", 1),
    MC("Which habit best builds long-term self-motivation?",
      ["Setting small goals and celebrating progress", "Waiting for others to push you", "Giving up at the first setback", "Avoiding all goals"], "Setting small goals and celebrating progress",
      "Small goals and recognising progress build lasting self-motivation.", "ERR_LO_G8DSA1_HABIT", 2),
    {
      question: "Sort each statement into POSITIVE or NEGATIVE self-talk.",
      input_type: "sort-buckets",
      buckets: [{ id: "pos", label: "Positive self-talk" }, { id: "neg", label: "Negative self-talk" }],
      items: [
        { id: "i1", text: "'I can learn from this mistake'", correct_bucket: "pos" },
        { id: "i2", text: "'I'm getting better with practice'", correct_bucket: "pos" },
        { id: "i3", text: "'I always fail at everything'", correct_bucket: "neg" },
        { id: "i4", text: "'There's no point in trying'", correct_bucket: "neg" },
      ],
      expected: "Learning from mistakes and improving are positive; 'always fail' and 'no point' are negative.",
      pass_threshold: 0.75,
      memo: "Positive self-talk builds motivation; negative self-talk drains it.",
      error_signals: ["ERR_LO_G8DSA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for staying self-motivated toward a goal in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Set a clear, realistic goal" },
        { id: "s2", text: "Break it into smaller steps" },
        { id: "s3", text: "Work on the steps and track progress" },
        { id: "s4", text: "Reward yourself and set the next goal" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Set a goal, break it down, work and track progress, then reward yourself and continue.",
      memo: "Self-motivation grows from clear goals, small steps, tracking progress and rewarding success.",
      error_signals: ["ERR_LO_G8DSA1_SEQ"], difficulty: 2,
    },
    MC("The best summary of a healthy self-concept is…",
      ["knowing and valuing your real strengths and accepting growth areas", "thinking you are perfect", "believing you are worthless", "ignoring who you are"], "knowing and valuing your real strengths and accepting growth areas",
      "A healthy self-concept is realistic: valuing strengths while accepting room to grow.", "ERR_LO_G8DSA1_SUMMARY", 2),
  ],

  // DS.A2 · Sexuality
  "LO.G8.DS.A2": [
    MC("In Life Orientation, 'sexuality' is best understood as…",
      ["a natural part of who you are as a person", "something shameful to hide", "only about physical acts", "unimportant to identity"], "a natural part of who you are as a person",
      "Sexuality is a natural part of being human, linked to feelings, identity and values.", "ERR_LO_G8DSA2_DEF", 1),
    TF("Personal feelings can affect how a person understands their sexuality.", "True",
      "Personal feelings are part of understanding one's sexuality.", "ERR_LO_G8DSA2_FEELINGS", 1),
    MC("Which can INFLUENCE a young person's view of their sexuality?",
      ["Friends, family, culture and media", "Only the school bell", "Their shoe size", "The weather"], "Friends, family, culture and media",
      "Friends, peers, family, culture and media all influence how someone understands sexuality.", "ERR_LO_G8DSA2_INFLUENCE", 2),
    CLOZE("Working out who you are as a person is called identity ____.",
      ["formation", "deletion", "copying", "hiding"], "formation",
      "Identity formation is the process of working out who you are, including your values.", "ERR_LO_G8DSA2_IDENTITY", 2),
    MC("How can media create pressure around sexuality?",
      ["By showing unrealistic ideas as if they are normal", "By telling only facts", "By having no influence", "By improving self-image automatically"], "By showing unrealistic ideas as if they are normal",
      "Media can present unrealistic or pressured ideas about sexuality and relationships.", "ERR_LO_G8DSA2_MEDIA", 2),
    TF("Family and community norms can shape attitudes toward sexuality.", "True",
      "Family and community norms are important influences on attitudes toward sexuality.", "ERR_LO_G8DSA2_NORMS", 1),
    MC("A healthy attitude to questions about your own development is to…",
      ["seek accurate information from trusted adults", "rely only on rumours", "feel ashamed and ask no one", "guess alone"], "seek accurate information from trusted adults",
      "Trusted adults and reliable sources give accurate information for healthy understanding.", "ERR_LO_G8DSA2_INFO", 2),
    CLOZE("Respecting your own ____ and choices is part of healthy development.",
      ["values", "fears", "secrets", "marks"], "values",
      "Knowing and respecting your own values helps you make healthy choices.", "ERR_LO_G8DSA2_VALUES", 1),
    TF("Peers can pressure each other about relationships and sexuality.", "True",
      "Peer influence and pressure can affect choices about relationships and sexuality.", "ERR_LO_G8DSA2_PEERS", 1),
    MC("Why is it important to make your OWN informed choices about your body and relationships?",
      ["They affect your health, future and wellbeing", "They never matter", "Others should decide for you", "Choices have no effect"], "They affect your health, future and wellbeing",
      "Informed personal choices protect your health, future and wellbeing.", "ERR_LO_G8DSA2_CHOICES", 2),
    MC("A friend feels confused about the changes and feelings of growing up. A caring response is to…",
      ["reassure them it is normal and suggest a trusted adult to talk to", "laugh at them", "spread it as gossip", "tell them to keep it secret forever"], "reassure them it is normal and suggest a trusted adult to talk to",
      "Reassurance and pointing to a trusted adult support a friend respectfully.", "ERR_LO_G8DSA2_FRIEND", 3),
    TF("Cultural values can influence how people think about sexuality.", "True",
      "Cultural values are among the influences that shape views on sexuality.", "ERR_LO_G8DSA2_CULTURE", 1),
    CLOZE("Pressure from friends to act a certain way is ____ pressure.",
      ["peer", "weather", "exam", "traffic"], "peer",
      "Peer pressure can influence decisions about relationships and behaviour.", "ERR_LO_G8DSA2_PEERPRESS", 1),
    MC("Problem-solving skills help with identity and sexuality by…",
      ["helping you think through choices calmly", "removing all decisions", "forcing quick risky choices", "ignoring consequences"], "helping you think through choices calmly",
      "Problem-solving skills help you weigh options and make calm, informed choices.", "ERR_LO_G8DSA2_PROBLEMSOLVE", 2),
    TF("It is healthy to respect that people develop and feel things at different paces.", "True",
      "People mature and feel things at different paces; respecting this is healthy.", "ERR_LO_G8DSA2_PACE", 1),
    MC("Which is the most reliable source of information about your development?",
      ["A nurse, doctor, teacher or parent", "An unverified social media post", "A playground rumour", "A random guess"], "A nurse, doctor, teacher or parent",
      "Health professionals and trusted adults give reliable information.", "ERR_LO_G8DSA2_SOURCE", 2),
    {
      question: "Sort each into a HEALTHY or UNHEALTHY way to handle questions about growing up.",
      input_type: "sort-buckets",
      buckets: [{ id: "healthy", label: "Healthy" }, { id: "unhealthy", label: "Unhealthy" }],
      items: [
        { id: "i1", text: "Ask a trusted adult or health worker", correct_bucket: "healthy" },
        { id: "i2", text: "Use reliable, age-appropriate information", correct_bucket: "healthy" },
        { id: "i3", text: "Believe every rumour from friends", correct_bucket: "unhealthy" },
        { id: "i4", text: "Feel ashamed and ask no one", correct_bucket: "unhealthy" },
      ],
      expected: "Asking trusted adults and using reliable info are healthy; believing rumours or hiding in shame are not.",
      pass_threshold: 0.75,
      memo: "Reliable information and trusted adults are healthy; rumours and shame are not.",
      error_signals: ["ERR_LO_G8DSA2_SORT"], difficulty: 2,
    },
    TF("Understanding influences on your choices helps you make your own healthy decisions.", "True",
      "Recognising what influences you helps you make independent, healthy decisions.", "ERR_LO_G8DSA2_AWARE", 1),
    MC("The healthiest overall attitude to sexuality at this age is to…",
      ["understand it as natural and make informed, value-based choices", "feel ashamed of it", "let media decide for you", "ignore your own values"], "understand it as natural and make informed, value-based choices",
      "Seeing sexuality as natural and making informed, value-based choices is healthiest.", "ERR_LO_G8DSA2_SUMMARY", 2),
    TF("Different people develop and feel things at different paces, and that is normal.", "True",
      "Everyone matures at their own pace; respecting this is part of healthy development.", "ERR_LO_G8DSA2_PACE2", 1),
  ],

  // DS.A3 · Relationships and friendships
  "LO.G8.DS.A3": [
    MC("What is the basis of a HEALTHY relationship?",
      ["Respect, trust and good communication", "Control and fear", "Lies and secrets", "Jealousy and threats"], "Respect, trust and good communication",
      "Healthy relationships are built on respect, trust, honesty and communication.", "ERR_LO_G8DSA3_DEF", 1),
    TF("Relationships happen at home, at school and in the community.", "True",
      "We have relationships in many settings — home, school and community.", "ERR_LO_G8DSA3_SETTINGS", 1),
    MC("Which is an APPROPRIATE way to start a friendship?",
      ["Be friendly, show interest and find common ground", "Pretend to be someone else", "Buy people's friendship", "Threaten them"], "Be friendly, show interest and find common ground",
      "Genuine friendliness and shared interests are healthy ways to start a friendship.", "ERR_LO_G8DSA3_INITIATE", 1),
    CLOZE("Keeping a friendship going over time is called ____ a relationship.",
      ["sustaining", "ending", "breaking", "hiding"], "sustaining",
      "Sustaining a relationship means keeping it healthy and strong over time.", "ERR_LO_G8DSA3_SUSTAIN", 2),
    MC("How can you SUSTAIN a healthy friendship?",
      ["Communicate, support each other and resolve conflict respectfully", "Ignore each other", "Compete and put each other down", "Keep score of favours"], "Communicate, support each other and resolve conflict respectfully",
      "Communication, support and respectful conflict resolution sustain friendships.", "ERR_LO_G8DSA3_MAINTAIN", 2),
    TF("Being able to disagree in a constructive way is a useful communication skill.", "True",
      "Constructive disagreement keeps relationships honest and respectful.", "ERR_LO_G8DSA3_DISAGREE", 1),
    MC("Which sign suggests a friendship is UNHEALTHY?",
      ["One person controls or constantly criticises the other", "They respect each other", "They support each other's goals", "They communicate openly"], "One person controls or constantly criticises the other",
      "Control, constant criticism or disrespect are signs of an unhealthy relationship.", "ERR_LO_G8DSA3_UNHEALTHY", 2),
    CLOZE("Ending a relationship kindly and respectfully shows ____.",
      ["maturity", "cruelty", "weakness", "anger"], "maturity",
      "Ending a relationship respectfully, without cruelty, shows maturity.", "ERR_LO_G8DSA3_MATURITY", 2),
    TF("It is sometimes healthy to end a relationship that is harmful.", "True",
      "Ending a harmful relationship, done respectfully, can be a healthy choice.", "ERR_LO_G8DSA3_END", 1),
    MC("Two friends disagree about plans. The healthiest approach is to…",
      ["talk it out and find a fair compromise", "give each other the silent treatment", "spread rumours", "end the friendship instantly"], "talk it out and find a fair compromise",
      "Talking openly and compromising resolves conflict and protects the friendship.", "ERR_LO_G8DSA3_CONFLICT", 2),
    MC("Which is an example of GOOD communication in a relationship?",
      ["Listening and saying how you feel honestly", "Shouting over the other person", "Ignoring their feelings", "Lying to avoid talks"], "Listening and saying how you feel honestly",
      "Listening and honest expression are signs of good communication.", "ERR_LO_G8DSA3_COMMUNICATE", 1),
    TF("Trust, once broken, can sometimes be rebuilt with honesty and time.", "True",
      "With honesty, effort and time, broken trust can sometimes be rebuilt.", "ERR_LO_G8DSA3_TRUST", 2),
    CLOZE("Treating a friend the way you would like to be treated shows mutual ____.",
      ["respect", "control", "fear", "envy"], "respect",
      "Mutual respect — treating each other well — is central to healthy relationships.", "ERR_LO_G8DSA3_RESPECT", 1),
    MC("A friend pressures you to drop another friend 'or else.' This is a sign of…",
      ["a controlling, unhealthy friendship", "a caring friend", "good communication", "healthy compromise"], "a controlling, unhealthy friendship",
      "Ultimatums and control are signs of an unhealthy, controlling friendship.", "ERR_LO_G8DSA3_CONTROL", 3),
    TF("Healthy friendships allow each person to have other friends and interests.", "True",
      "Healthy friendships are not possessive; each person keeps their own friends and interests.", "ERR_LO_G8DSA3_SPACE", 1),
    MC("Appropriate behaviour in a relationship includes…",
      ["honesty, kindness and respecting boundaries", "jealousy and control", "lying and threats", "ignoring the other person"], "honesty, kindness and respecting boundaries",
      "Honesty, kindness and respecting boundaries are appropriate relationship behaviours.", "ERR_LO_G8DSA3_BEHAVIOUR", 2),
    {
      question: "Sort each behaviour into HEALTHY or UNHEALTHY in a friendship.",
      input_type: "sort-buckets",
      buckets: [{ id: "healthy", label: "Healthy" }, { id: "unhealthy", label: "Unhealthy" }],
      items: [
        { id: "i1", text: "Supporting each other's goals", correct_bucket: "healthy" },
        { id: "i2", text: "Listening when there is a problem", correct_bucket: "healthy" },
        { id: "i3", text: "Controlling who the other can see", correct_bucket: "unhealthy" },
        { id: "i4", text: "Constant insults and put-downs", correct_bucket: "unhealthy" },
      ],
      expected: "Support and listening are healthy; controlling and insulting are unhealthy.",
      pass_threshold: 0.75,
      memo: "Healthy relationships support and respect; unhealthy ones control and demean.",
      error_signals: ["ERR_LO_G8DSA3_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for resolving a disagreement with a friend in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Calm down before talking" },
        { id: "s2", text: "Listen to each other's side" },
        { id: "s3", text: "Look for a fair compromise" },
        { id: "s4", text: "Agree and move on respectfully" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Calm down, listen to both sides, find a fair compromise, then agree and move on.",
      memo: "Resolve conflict by calming down, listening, compromising and moving on respectfully.",
      error_signals: ["ERR_LO_G8DSA3_SEQ"], difficulty: 2,
    },
    MC("The deeper purpose of learning relationship skills is to…",
      ["build healthy, respectful connections throughout life", "win every argument", "avoid all people", "control others"], "build healthy, respectful connections throughout life",
      "Relationship skills help you build healthy, respectful connections for life.", "ERR_LO_G8DSA3_PURPOSE", 2),
    TF("In a healthy friendship, both people feel respected and free to be themselves.", "True",
      "Mutual respect and freedom to be yourself are signs of a healthy friendship.", "ERR_LO_G8DSA3_FREE", 1),
  ],

  // ════════════ HEALTH, SOCIAL & ENVIRONMENTAL RESPONSIBILITY (Term 2) ══════════
  // HE.A1 · Social factors in substance abuse
  "LO.G8.HE.A1": [
    MC("Which is a SOCIAL factor that can contribute to substance abuse?",
      ["Community attitudes and media influence", "A person's height", "The colour of their bag", "The school timetable"], "Community attitudes and media influence",
      "Social factors include community norms and media that can encourage substance use.", "ERR_LO_G8HEA1_DEF", 1),
    TF("Media can sometimes make alcohol or drug use look attractive.", "True",
      "Media images can glamorise substances, influencing young people.", "ERR_LO_G8HEA1_MEDIA", 1),
    MC("What is a 'refusal skill'?",
      ["The ability to say no clearly and confidently", "A way to give in politely", "A type of dance", "A study method"], "The ability to say no clearly and confidently",
      "Refusal skills let you say no to substances clearly and confidently.", "ERR_LO_G8HEA1_REFUSAL", 1),
    CLOZE("Saying 'No thanks, I don't do that' in a firm, calm way is a ____ skill.",
      ["refusal", "cooking", "drawing", "spelling"], "refusal",
      "A firm, calm 'no' is a refusal skill that helps resist pressure.", "ERR_LO_G8HEA1_SKILL", 1),
    MC("Which is a SHORT-TERM consequence of substance abuse?",
      ["Poor judgement and accidents", "A long, healthy life", "Better marks", "More energy"], "Poor judgement and accidents",
      "Short-term consequences include poor judgement, accidents and risky behaviour.", "ERR_LO_G8HEA1_SHORT", 2),
    MC("Which is a LONG-TERM consequence of substance abuse?",
      ["Addiction and health damage", "Improved health", "Stronger friendships", "Higher marks"], "Addiction and health damage",
      "Long-term consequences include addiction, health damage and harm to relationships.", "ERR_LO_G8HEA1_LONG", 2),
    TF("Substance abuse can be linked to crime and violence.", "True",
      "Substance abuse is linked to crime, violence and poor educational outcomes.", "ERR_LO_G8HEA1_CRIME", 1),
    CLOZE("Treatment programmes that help people recover from addiction provide ____.",
      ["rehabilitation", "punishment", "decoration", "celebration"], "rehabilitation",
      "Rehabilitation helps people recover from substance dependence.", "ERR_LO_G8HEA1_REHAB", 2),
    MC("Where can someone find help, care and support for a substance problem?",
      ["A clinic, counsellor or SANCA", "Only from dealers", "Nowhere", "By staying silent"], "A clinic, counsellor or SANCA",
      "Clinics, counsellors and SANCA offer help, care and support.", "ERR_LO_G8HEA1_HELP", 2),
    TF("Saying no to substances is a sign of weakness.", "False",
      "Refusing substances shows strength and good decision-making, not weakness.", "ERR_LO_G8HEA1_WEAK", 1),
    MC("At a party, friends pressure Sipho to drink. The BEST refusal is to…",
      ["calmly say no and suggest something else to do", "drink so they stop", "shout and storm off", "pretend and sip it anyway"], "calmly say no and suggest something else to do",
      "A calm, firm refusal with an alternative resists pressure while keeping the peace.", "ERR_LO_G8HEA1_SCENARIO", 3),
    MC("How does the community influence substance abuse?",
      ["Easy access and acceptance can increase use", "Communities never matter", "It always prevents use", "It has no effect"], "Easy access and acceptance can increase use",
      "Community factors like easy access and acceptance can increase substance use.", "ERR_LO_G8HEA1_COMMUNITY", 2),
    TF("Decision-making skills help a person avoid substance abuse.", "True",
      "Good decision-making helps people weigh consequences and avoid substance abuse.", "ERR_LO_G8HEA1_DECISION", 1),
    CLOZE("Substance abuse can lead to poor results and dropping out of ____.",
      ["school", "sleep", "breakfast", "music"], "school",
      "Substance abuse is linked to poor educational outcomes and dropping out.", "ERR_LO_G8HEA1_SCHOOL", 1),
    MC("Why is it important to know where to find help?",
      ["So you or a friend can get support early", "It is never needed", "Only adults need help", "Help makes things worse"], "So you or a friend can get support early",
      "Knowing where to find help means support can come early, before harm worsens.", "ERR_LO_G8HEA1_KNOWHELP", 2),
    TF("Supporting a friend to get help is a caring, responsible action.", "True",
      "Helping a friend reach support is caring and responsible.", "ERR_LO_G8HEA1_FRIENDHELP", 1),
    {
      question: "Sort each consequence of substance abuse into SHORT-TERM or LONG-TERM.",
      input_type: "sort-buckets",
      buckets: [{ id: "short", label: "Short-term" }, { id: "long", label: "Long-term" }],
      items: [
        { id: "i1", text: "Poor judgement at a party", correct_bucket: "short" },
        { id: "i2", text: "An accident while intoxicated", correct_bucket: "short" },
        { id: "i3", text: "Addiction", correct_bucket: "long" },
        { id: "i4", text: "Lasting damage to health", correct_bucket: "long" },
      ],
      expected: "Poor judgement and accidents are short-term; addiction and health damage are long-term.",
      pass_threshold: 0.75,
      memo: "Some harms appear immediately; others build up over the long term.",
      error_signals: ["ERR_LO_G8HEA1_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of a good refusal in a tricky situation in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Recognise the pressure and the risk" },
        { id: "s2", text: "Say no clearly and calmly" },
        { id: "s3", text: "Suggest an alternative or excuse to leave" },
        { id: "s4", text: "Remove yourself from the situation" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Recognise the risk, refuse clearly, offer an alternative, then leave the situation.",
      memo: "Refuse well by recognising the risk, saying no, offering an alternative and leaving.",
      error_signals: ["ERR_LO_G8HEA1_SEQ"], difficulty: 2,
    },
    MC("The best way to avoid substance abuse is to…",
      ["build strong refusal skills and positive support", "spend time only with users", "hide all problems", "rely on luck"], "build strong refusal skills and positive support",
      "Refusal skills and positive support are the best protection against substance abuse.", "ERR_LO_G8HEA1_SUMMARY", 2),
    TF("Helping a friend reach support for a substance problem is a caring, responsible act.", "True",
      "Supporting a friend to get help is caring and responsible, not a betrayal.", "ERR_LO_G8HEA1_CARING", 1),
  ],

  // HE.A2 · Environmental health issues
  "LO.G8.HE.A2": [
    MC("Why do governments make LAWS to protect environmental health?",
      ["To stop pollution and protect people and nature", "To make life harder", "To raise no benefit", "To help factories pollute"], "To stop pollution and protect people and nature",
      "Environmental laws aim to reduce pollution and protect people and the environment.", "ERR_LO_G8HEA2_DEF", 1),
    TF("Following environmental laws is part of being a responsible citizen.", "True",
      "Obeying environmental laws and policies is part of responsible citizenship.", "ERR_LO_G8HEA2_CITIZEN", 1),
    MC("What is 'Earth Day' about?",
      ["Caring for and protecting the planet", "Celebrating pollution", "Buying more plastic", "Wasting resources"], "Caring for and protecting the planet",
      "Earth Day raises awareness about protecting and preserving the environment.", "ERR_LO_G8HEA2_EARTHDAY", 1),
    CLOZE("A set of planned actions to improve the environment is an environmental health ____.",
      ["programme", "holiday", "snack", "song"], "programme",
      "An environmental health programme is a planned set of actions to improve the environment.", "ERR_LO_G8HEA2_PROGRAMME", 1),
    MC("Which is a way of 'being kinder to Earth'?",
      ["Reduce, reuse and recycle", "Dump waste in rivers", "Waste water and power", "Burn rubbish in the open"], "Reduce, reuse and recycle",
      "Reduce, reuse, recycle and conserving resources are ways to be kinder to Earth.", "ERR_LO_G8HEA2_KINDER", 1),
    TF("Laws and policies can be used to address an environmental issue.", "True",
      "Applying laws and policies is one way to address environmental issues.", "ERR_LO_G8HEA2_LAWS", 1),
    MC("Air pollution is mainly harmful because it…",
      ["damages health and the environment", "improves breathing", "cleans the air", "has no effect"], "damages health and the environment",
      "Air pollution harms human health and the environment.", "ERR_LO_G8HEA2_AIR", 2),
    CLOZE("Protecting nature so future generations can enjoy it is called ____ of the environment.",
      ["preservation", "destruction", "pollution", "wasting"], "preservation",
      "Preservation means protecting the environment for the future.", "ERR_LO_G8HEA2_PRESERVE", 2),
    MC("A school wants to run an environmental health programme. A good first action is to…",
      ["identify a local environmental problem to target", "ignore the surroundings", "create more litter", "do nothing"], "identify a local environmental problem to target",
      "A good programme starts by identifying a specific local environmental problem.", "ERR_LO_G8HEA2_FIRSTSTEP", 2),
    TF("Individuals can support environmental laws through their daily choices.", "True",
      "Everyday choices, like recycling and saving water, support environmental protection.", "ERR_LO_G8HEA2_DAILY", 1),
    MC("Which everyday action best reduces waste?",
      ["Reusing containers and recycling", "Buying extra single-use plastic", "Throwing away usable items", "Littering"], "Reusing containers and recycling",
      "Reusing and recycling reduce waste sent to landfill.", "ERR_LO_G8HEA2_WASTE", 1),
    MC("Why involve the whole community in an environmental programme?",
      ["Shared effort makes a bigger, lasting difference", "One person should do all", "Teamwork makes it worse", "It is illegal"], "Shared effort makes a bigger, lasting difference",
      "Community involvement makes environmental programmes more effective and lasting.", "ERR_LO_G8HEA2_COMMUNITY", 2),
    TF("Saving electricity reduces pollution from power stations.", "True",
      "Using less electricity reduces the pollution created in generating it.", "ERR_LO_G8HEA2_ELECTRICITY", 2),
    CLOZE("Cutting down too many trees, or ____, harms the environment.",
      ["deforestation", "recycling", "planting", "cleaning"], "deforestation",
      "Deforestation — clearing too many trees — damages ecosystems and the climate.", "ERR_LO_G8HEA2_DEFOREST", 2),
    MC("How does honouring Earth Day help year-round?",
      ["It reminds people to keep good environmental habits", "It only matters one day", "It encourages pollution", "It has no effect"], "It reminds people to keep good environmental habits",
      "Earth Day reminds people to keep environmentally friendly habits all year.", "ERR_LO_G8HEA2_HABITS", 2),
    TF("Environmental health and human health are closely connected.", "True",
      "A healthy environment supports human health; pollution harms both.", "ERR_LO_G8HEA2_CONNECT", 1),
    {
      question: "Sort each action into PROTECTS the environment or DAMAGES it.",
      input_type: "sort-buckets",
      buckets: [{ id: "protect", label: "Protects" }, { id: "damage", label: "Damages" }],
      items: [
        { id: "i1", text: "Recycling and composting", correct_bucket: "protect" },
        { id: "i2", text: "Saving water", correct_bucket: "protect" },
        { id: "i3", text: "Illegal dumping", correct_bucket: "damage" },
        { id: "i4", text: "Polluting a river", correct_bucket: "damage" },
      ],
      expected: "Recycling and saving water protect; dumping and polluting damage the environment.",
      pass_threshold: 0.75,
      memo: "Conserving and recycling protect the environment; dumping and pollution damage it.",
      error_signals: ["ERR_LO_G8HEA2_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for running an environmental health programme in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Identify a local environmental issue" },
        { id: "s2", text: "Plan actions and assign tasks" },
        { id: "s3", text: "Carry out the programme" },
        { id: "s4", text: "Review the results and improve" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Identify the issue, plan actions, carry them out, then review and improve.",
      memo: "An environmental programme: identify, plan, act, then review.",
      error_signals: ["ERR_LO_G8HEA2_SEQ"], difficulty: 2,
    },
    MC("The main message of environmental responsibility is that…",
      ["everyone shares the duty to protect the environment", "only the government must act", "the environment looks after itself", "pollution does not matter"], "everyone shares the duty to protect the environment",
      "Protecting the environment is a shared responsibility for everyone.", "ERR_LO_G8HEA2_SUMMARY", 2),
    TF("Small daily habits, like recycling, add up to a big environmental difference.", "True",
      "Everyday habits across many people add up to a large positive environmental impact.", "ERR_LO_G8HEA2_HABITS2", 1),
  ],

  // HE.A3 · Decisions about HIV and AIDS
  "LO.G8.HE.A3": [
    MC("What does HIV stand for in simple terms?",
      ["A virus that weakens the body's immune system", "A type of food", "A school subject", "A kind of exercise"], "A virus that weakens the body's immune system",
      "HIV is a virus that attacks the immune system; with treatment it can be managed.", "ERR_LO_G8HEA3_DEF", 1),
    TF("With medication and healthy living, a person with HIV can live a long life.", "True",
      "Treatment, a good diet and healthy living let people with HIV live long, healthy lives.", "ERR_LO_G8HEA3_LIVELONG", 1),
    MC("Which helps MANAGE HIV?",
      ["Taking medication as prescribed and eating well", "Stopping all treatment", "Ignoring the condition", "Eating only junk food"], "Taking medication as prescribed and eating well",
      "Managing HIV means taking medication correctly, eating well and living healthily.", "ERR_LO_G8HEA3_MANAGE", 2),
    CLOZE("Medication that helps control HIV is called ____ treatment (ARVs).",
      ["antiretroviral", "magical", "imaginary", "musical"], "antiretroviral",
      "Antiretroviral (ARV) treatment helps control HIV and keeps people healthy.", "ERR_LO_G8HEA3_ARV", 2),
    MC("Which is a way to PREVENT the spread of HIV?",
      ["Abstinence and safe, responsible choices", "Sharing needles", "Ignoring information", "Stigmatising others"], "Abstinence and safe, responsible choices",
      "Prevention includes abstinence and safe, informed, responsible choices.", "ERR_LO_G8HEA3_PREVENT", 2),
    TF("You can tell who has HIV just by looking at them.", "False",
      "You cannot tell who has HIV by appearance; assuming so causes unfair stigma.", "ERR_LO_G8HEA3_LOOK", 1),
    MC("How should we treat people living with HIV and AIDS?",
      ["With care, respect and no discrimination", "By avoiding and excluding them", "By mocking them", "By spreading rumours"], "With care, respect and no discrimination",
      "People with HIV deserve care, respect and freedom from discrimination.", "ERR_LO_G8HEA3_CARE", 1),
    CLOZE("Unfair judgement of people with HIV is called ____.",
      ["stigma", "support", "kindness", "respect"], "stigma",
      "Stigma is unfair judgement; it harms people and discourages testing and treatment.", "ERR_LO_G8HEA3_STIGMA", 2),
    TF("Caring for someone with HIV includes emotional support, not just medicine.", "True",
      "Care includes emotional support and respect, alongside medical treatment.", "ERR_LO_G8HEA3_EMOTIONAL", 1),
    MC("A classmate is known to be HIV positive. The responsible, kind attitude is to…",
      ["treat them as a normal friend and support them", "avoid and exclude them", "tell everyone as gossip", "tease them"], "treat them as a normal friend and support them",
      "Treating them normally and offering support is responsible and kind; HIV is not spread by everyday contact.", "ERR_LO_G8HEA3_SCENARIO", 3),
    MC("Responsible decision-making about health means…",
      ["thinking through consequences before acting", "acting without thought", "letting others decide everything", "ignoring the facts"], "thinking through consequences before acting",
      "Responsible decisions weigh consequences and the facts before acting.", "ERR_LO_G8HEA3_DECISION", 2),
    TF("HIV can be spread by sharing food or hugging.", "False",
      "HIV is not spread by everyday contact like sharing food, hugging or shaking hands.", "ERR_LO_G8HEA3_EVERYDAY", 2),
    CLOZE("Knowing your status by getting ____ is a responsible health choice.",
      ["tested", "lost", "angry", "rich"], "tested",
      "Getting tested means you know your status and can get treatment and prevent spread.", "ERR_LO_G8HEA3_TEST", 2),
    MC("Why is it important to have accurate information about HIV and AIDS?",
      ["It helps prevent infection and reduce stigma", "It makes no difference", "It increases fear only", "It helps spread rumours"], "It helps prevent infection and reduce stigma",
      "Accurate information helps prevent infection and reduces harmful stigma.", "ERR_LO_G8HEA3_INFO", 2),
    TF("Supporting people living with HIV helps them stay healthy and hopeful.", "True",
      "Support helps people with HIV stick to treatment and stay healthy and hopeful.", "ERR_LO_G8HEA3_SUPPORT", 1),
    MC("A safety issue linked to HIV care is to…",
      ["handle blood and wounds carefully and hygienically", "share needles", "ignore cuts", "avoid all hygiene"], "handle blood and wounds carefully and hygienically",
      "Careful, hygienic handling of blood and wounds is an important safety measure.", "ERR_LO_G8HEA3_SAFETY", 2),
    {
      question: "Sort each statement into TRUE or FALSE about HIV and AIDS.",
      input_type: "sort-buckets",
      buckets: [{ id: "true", label: "True" }, { id: "false", label: "False" }],
      items: [
        { id: "i1", text: "HIV can be managed with ARV treatment", correct_bucket: "true" },
        { id: "i2", text: "People with HIV deserve respect and care", correct_bucket: "true" },
        { id: "i3", text: "HIV spreads by hugging", correct_bucket: "false" },
        { id: "i4", text: "You can tell who has HIV by looking", correct_bucket: "false" },
      ],
      expected: "ARV treatment and deserving respect are true; spreading by hugging or telling by looks are false.",
      pass_threshold: 0.75,
      memo: "Know the facts: HIV is manageable and not spread by everyday contact; stigma is based on myths.",
      error_signals: ["ERR_LO_G8HEA3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps of responsible action around HIV health in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Get accurate information" },
        { id: "s2", text: "Make safe, informed choices" },
        { id: "s3", text: "Get tested to know your status" },
        { id: "s4", text: "Get treatment and support if needed" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Get accurate info, make safe choices, get tested, then get treatment and support if needed.",
      memo: "Responsible steps: be informed, choose safely, test, and access treatment and support.",
      error_signals: ["ERR_LO_G8HEA3_SEQ"], difficulty: 2,
    },
    MC("The key message about HIV and AIDS is that it should be met with…",
      ["facts, prevention, treatment and compassion", "fear and stigma", "silence and shame", "rumours and blame"], "facts, prevention, treatment and compassion",
      "HIV is best met with accurate facts, prevention, treatment and compassion.", "ERR_LO_G8HEA3_SUMMARY", 2),
    TF("Knowing your HIV status through testing lets you get treatment and stay healthy.", "True",
      "Testing means you know your status and can access treatment early to stay healthy.", "ERR_LO_G8HEA3_TESTING", 1),
  ],
};

export default G8;
