// ─── Life Orientation SP — Grade 9 authored pools (part 2: WW) ───────────────
//
// Keyed by skill id → question array. Refs auto-assigned by the generator.
// Tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
// Each pool holds exactly 20 items (18 simple + 1 sort + 1 sequence).
//
// CAPS Grade 9 topic here: World of work (the heaviest WW year — 6 skills).

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9B = {
  // ════════════════════════════ WORLD OF WORK (Term 1 & 3) ════════════════════
  // WW.A1 · Time-management skills
  "LO.G9.WW.A1": [
    MC("What is time management?",
      ["Planning how to use your time effectively", "Wasting time", "Avoiding all tasks", "Ignoring deadlines"], "Planning how to use your time effectively",
      "Time management means planning and using your time effectively and efficiently.", "ERR_LO_G9WWA1_DEF", 1),
    TF("Being accountable means taking responsibility for your tasks and deadlines.", "True",
      "Accountability means taking responsibility for carrying out your tasks and meeting deadlines.", "ERR_LO_G9WWA1_ACCOUNTABLE", 1),
    MC("Which is a good time-management habit?",
      ["Making a to-do list and prioritising tasks", "Leaving everything to the last minute", "Ignoring your schedule", "Doing only easy tasks"], "Making a to-do list and prioritising tasks",
      "To-do lists and prioritising help you organise and use time well.", "ERR_LO_G9WWA1_HABIT", 1),
    CLOZE("Putting the most important tasks first is called ____.",
      ["prioritising", "delaying", "ignoring", "guessing"], "prioritising",
      "Prioritising means doing the most important tasks first.", "ERR_LO_G9WWA1_PRIORITISE", 1),
    MC("What is 'procrastination'?",
      ["Delaying tasks you should be doing", "Finishing early", "Planning ahead", "Working hard"], "Delaying tasks you should be doing",
      "Procrastination is delaying tasks, which harms time management.", "ERR_LO_G9WWA1_PROCRASTINATE", 2),
    TF("A study timetable can help you use your time efficiently.", "True",
      "A timetable helps allocate time to tasks and use it efficiently.", "ERR_LO_G9WWA1_TIMETABLE", 1),
    MC("How can you organise your work effectively?",
      ["Break big tasks into smaller steps with deadlines", "Do it all at once at the end", "Avoid planning", "Work randomly"], "Break big tasks into smaller steps with deadlines",
      "Breaking work into smaller steps with deadlines makes it manageable.", "ERR_LO_G9WWA1_ORGANISE", 2),
    CLOZE("Using time well, without waste, is using time ____.",
      ["efficiently", "carelessly", "slowly", "randomly"], "efficiently",
      "Using time efficiently means getting things done without wasting it.", "ERR_LO_G9WWA1_EFFICIENT", 1),
    TF("Good time management reduces stress and improves results.", "True",
      "Managing time well lowers stress and improves performance.", "ERR_LO_G9WWA1_STRESS", 1),
    MC("Sipho has three assignments due. The best time-management step is to…",
      ["plan and start with the most urgent or important", "ignore them all", "do only the easiest", "leave them to the last night"], "plan and start with the most urgent or important",
      "Planning and starting with the most urgent or important task manages competing deadlines.", "ERR_LO_G9WWA1_SCENARIO", 3),
    MC("Why is accountability important at school and work?",
      ["Others rely on you to do your part", "It does not matter", "It avoids responsibility", "It causes problems"], "Others rely on you to do your part",
      "Accountability matters because others rely on you to do your part well and on time.", "ERR_LO_G9WWA1_WHY", 2),
    TF("Multitasking on everything at once is always the most efficient approach.", "False",
      "Trying to do everything at once often reduces quality; focused, prioritised work is better.", "ERR_LO_G9WWA1_MULTITASK", 2),
    CLOZE("Setting a ____ for a task helps you finish it on time.",
      ["deadline", "snack", "song", "holiday"], "deadline",
      "Setting deadlines helps you complete tasks on time.", "ERR_LO_G9WWA1_DEADLINE", 1),
    MC("Which tool helps you manage your time?",
      ["A planner or calendar", "A locked drawer", "A blank wall", "A heavy bag"], "A planner or calendar",
      "Planners and calendars help you schedule and track tasks.", "ERR_LO_G9WWA1_TOOL", 1),
    TF("Taking short, planned breaks can improve focus and productivity.", "True",
      "Short breaks help maintain focus and productivity over long study sessions.", "ERR_LO_G9WWA1_BREAKS", 1),
    MC("Which habit wastes time?",
      ["Constant distractions from your phone", "Following a plan", "Prioritising tasks", "Setting deadlines"], "Constant distractions from your phone",
      "Constant distractions, like an unmanaged phone, waste time.", "ERR_LO_G9WWA1_WASTE", 1),
    {
      question: "Sort each habit into GOOD or POOR time management.",
      input_type: "sort-buckets",
      buckets: [{ id: "good", label: "Good" }, { id: "poor", label: "Poor" }],
      items: [
        { id: "i1", text: "Prioritising important tasks", correct_bucket: "good" },
        { id: "i2", text: "Using a study timetable", correct_bucket: "good" },
        { id: "i3", text: "Leaving everything to the last minute", correct_bucket: "poor" },
        { id: "i4", text: "Constant phone distractions", correct_bucket: "poor" },
      ],
      expected: "Prioritising and timetables are good; last-minute work and distractions are poor.",
      pass_threshold: 0.75,
      memo: "Good time management plans and prioritises; poor management delays and gets distracted.",
      error_signals: ["ERR_LO_G9WWA1_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for managing your time around a busy week in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "List all tasks and deadlines" },
        { id: "s2", text: "Prioritise by importance and urgency" },
        { id: "s3", text: "Schedule time for each task" },
        { id: "s4", text: "Review and adjust the plan" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "List tasks, prioritise them, schedule time for each, then review and adjust.",
      memo: "Manage time by listing, prioritising, scheduling and reviewing.",
      error_signals: ["ERR_LO_G9WWA1_SEQ"], difficulty: 2,
    },
    TF("Good time management is a skill that helps at school and at work.", "True",
      "Time-management skills are valuable both at school and in the workplace.", "ERR_LO_G9WWA1_WORK", 1),
    MC("The key idea of time management is to…",
      ["plan and prioritise so you use time well", "leave everything to chance", "avoid all planning", "ignore deadlines"], "plan and prioritise so you use time well",
      "Time management means planning and prioritising to use your time well.", "ERR_LO_G9WWA1_SUMMARY", 2),
  ],

  // WW.A2 · Reading and writing for purpose
  "LO.G9.WW.A2": [
    MC("Why read and write for DIFFERENT purposes?",
      ["Different tasks need different reading and writing skills", "Reading is always the same", "Writing has no purpose", "Skills never change"], "Different tasks need different reading and writing skills",
      "Reading and writing for different purposes builds flexible, useful communication skills.", "ERR_LO_G9WWA2_DEF", 1),
    TF("Keeping a journal is a way to practise writing and reflect.", "True",
      "Journaling builds writing skills and helps you reflect on experiences.", "ERR_LO_G9WWA2_JOURNAL", 1),
    MC("What is 'summarising'?",
      ["Writing the main points briefly in your own words", "Copying the whole text", "Ignoring the text", "Adding extra unrelated ideas"], "Writing the main points briefly in your own words",
      "Summarising means stating the main points briefly in your own words.", "ERR_LO_G9WWA2_SUMMARISE", 1),
    CLOZE("Reading to find specific information quickly is called ____.",
      ["scanning", "sleeping", "drawing", "guessing"], "scanning",
      "Scanning is reading quickly to find specific information.", "ERR_LO_G9WWA2_SCAN", 2),
    MC("Which writing purpose is for a SCHOOL REPORT?",
      ["To inform clearly and factually", "To confuse the reader", "To entertain only with jokes", "To hide information"], "To inform clearly and factually",
      "A report's purpose is to inform clearly and factually.", "ERR_LO_G9WWA2_REPORT", 2),
    TF("Reading for pleasure and reading to study can use different approaches.", "True",
      "Reading for pleasure is relaxed; reading to study is more active and focused.", "ERR_LO_G9WWA2_APPROACHES", 1),
    MC("How does summarising help you study?",
      ["It captures key points so they are easier to revise", "It makes notes longer", "It removes understanding", "It wastes time"], "It captures key points so they are easier to revise",
      "Summaries capture key points, making revision easier and quicker.", "ERR_LO_G9WWA2_STUDY", 2),
    CLOZE("Reading quickly to get the general idea is called ____.",
      ["skimming", "scanning-only", "copying", "ignoring"], "skimming",
      "Skimming is reading quickly to get the overall idea of a text.", "ERR_LO_G9WWA2_SKIM", 2),
    TF("Improving your reading and writing helps in almost every subject.", "True",
      "Strong reading and writing skills help across nearly all subjects and in work.", "ERR_LO_G9WWA2_SUBJECTS", 1),
    MC("Naledi must write a formal letter and also a personal diary entry. She should…",
      ["use a formal style for the letter and a personal style for the diary", "use slang in both", "write both identically", "skip both"], "use a formal style for the letter and a personal style for the diary",
      "Matching style to purpose — formal for a letter, personal for a diary — is the skill here.", "ERR_LO_G9WWA2_SCENARIO", 3),
    MC("Which is the purpose of PERSUASIVE writing?",
      ["To convince the reader of a point of view", "To list random facts", "To confuse readers", "To say nothing"], "To convince the reader of a point of view",
      "Persuasive writing aims to convince the reader of a viewpoint.", "ERR_LO_G9WWA2_PERSUASIVE", 2),
    TF("Writing notes in your own words helps you understand and remember.", "True",
      "Putting ideas in your own words deepens understanding and memory.", "ERR_LO_G9WWA2_OWNWORDS", 1),
    CLOZE("A daily record of your thoughts and experiences is a ____.",
      ["journal", "textbook", "menu", "timetable"], "journal",
      "A journal is a personal record of thoughts and experiences.", "ERR_LO_G9WWA2_JOURNAL2", 1),
    MC("How can you improve your writing skills?",
      ["Practise regularly and read widely", "Never write", "Avoid all reading", "Copy without thinking"], "Practise regularly and read widely",
      "Regular practice and wide reading improve writing skills.", "ERR_LO_G9WWA2_IMPROVE", 1),
    TF("Different audiences may need different writing styles.", "True",
      "Writing should suit its audience — formal for officials, casual for friends.", "ERR_LO_G9WWA2_AUDIENCE", 2),
    MC("Which reading skill suits finding one fact in a long article?",
      ["Scanning for the specific detail", "Reading every word slowly", "Ignoring the article", "Memorising it all"], "Scanning for the specific detail",
      "Scanning quickly locates a specific fact without reading everything.", "ERR_LO_G9WWA2_FINDFACT", 2),
    {
      question: "Sort each reading approach with its purpose by ordering them for Purpose 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Get the general idea) Skim the text" },
        { id: "s2", text: "(Find a specific fact) Scan the text" },
        { id: "s3", text: "(Study deeply) Read carefully and summarise" },
        { id: "s4", text: "(Relax) Read for pleasure" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "General idea→skim, specific fact→scan, study→read carefully and summarise, relax→read for pleasure.",
      memo: "Match the reading approach to your purpose: skim, scan, study or read for pleasure.",
      error_signals: ["ERR_LO_G9WWA2_SEQ"], difficulty: 2,
    },
    {
      question: "Sort each writing task into FORMAL or INFORMAL style.",
      input_type: "sort-buckets",
      buckets: [{ id: "formal", label: "Formal" }, { id: "informal", label: "Informal" }],
      items: [
        { id: "i1", text: "A job application letter", correct_bucket: "formal" },
        { id: "i2", text: "A school report", correct_bucket: "formal" },
        { id: "i3", text: "A text to a friend", correct_bucket: "informal" },
        { id: "i4", text: "A personal diary entry", correct_bucket: "informal" },
      ],
      expected: "Application letters and reports are formal; texts to friends and diary entries are informal.",
      pass_threshold: 0.75,
      memo: "Match style to purpose: formal for official writing, informal for personal writing.",
      error_signals: ["ERR_LO_G9WWA2_SORT"], difficulty: 1,
    },
    MC("The main idea of reading and writing for purpose is to…",
      ["match your skills to the task and audience", "write the same way always", "avoid reading", "ignore the purpose"], "match your skills to the task and audience",
      "Reading and writing for purpose means matching your approach to the task and audience.", "ERR_LO_G9WWA2_SUMMARY", 2),
    TF("Regular practice and wide reading both improve your writing.", "True",
      "Writing improves with regular practice and reading widely.", "ERR_LO_G9WWA2_PRACTICE", 1),
  ],

  // WW.A3 · Options after Grade 9
  "LO.G9.WW.A3": [
    MC("What does NSC stand for?",
      ["National Senior Certificate", "National Sports Club", "New School Card", "National Sales Council"], "National Senior Certificate",
      "The NSC is the National Senior Certificate, earned in Grades 10–12 at school.", "ERR_LO_G9WWA3_NSC", 1),
    TF("The NSC is obtained by completing Grades 10, 11 and 12 at school.", "True",
      "The National Senior Certificate is earned by completing Grades 10–12.", "ERR_LO_G9WWA3_NSCGRADES", 1),
    MC("What does NCV stand for?",
      ["National Certificate (Vocational)", "New Career Visit", "National Class Voucher", "No Career Value"], "National Certificate (Vocational)",
      "The NCV is the National Certificate (Vocational), offered at FET/TVET colleges.", "ERR_LO_G9WWA3_NCV", 1),
    CLOZE("The NCV is studied at ____ (TVET) colleges.",
      ["FET", "primary", "nursery", "sports"], "FET",
      "The NCV is offered at FET (TVET) colleges and is more practical and career-focused.", "ERR_LO_G9WWA3_FET", 2),
    MC("A key difference between the NSC and NCV is that the NCV is…",
      ["more practical and career-focused", "only theory", "the same as the NSC", "not a real qualification"], "more practical and career-focused",
      "The NCV is more practical and vocational, while the NSC is more academic.", "ERR_LO_G9WWA3_DIFF", 2),
    TF("Choosing between the NSC and NCV is an important decision after Grade 9.", "True",
      "After Grade 9, choosing between the NSC and NCV is an important decision.", "ERR_LO_G9WWA3_DECISION", 1),
    MC("Which path might suit a learner who prefers hands-on, vocational training?",
      ["The NCV at a TVET college", "The academic NSC only", "Leaving school with nothing", "No further study"], "The NCV at a TVET college",
      "Hands-on learners may prefer the practical NCV at a TVET college.", "ERR_LO_G9WWA3_HANDSON", 2),
    CLOZE("Thinking about how a choice affects your future is weighing its ____.",
      ["implications", "colours", "snacks", "weather"], "implications",
      "Implications are the future effects of a choice, important to weigh.", "ERR_LO_G9WWA3_IMPLICATIONS", 2),
    TF("A learner who wants to go to university usually follows the NSC path.", "True",
      "The NSC, with the right subjects, is the usual route to university.", "ERR_LO_G9WWA3_UNIVERSITY", 2),
    MC("Sipho loves practical work and wants to become a qualified electrician soon. A fitting option is…",
      ["the NCV at a TVET college", "an academic-only route he dislikes", "dropping out", "ignoring all options"], "the NCV at a TVET college",
      "An NCV at a TVET college fits a learner aiming for a practical trade like electrician.", "ERR_LO_G9WWA3_SCENARIO", 3),
    MC("Why is it important to know your options after Grade 9?",
      ["So you can choose the path that fits your goals", "Options do not matter", "To avoid all decisions", "It has no benefit"], "So you can choose the path that fits your goals",
      "Knowing your options lets you choose the path that best fits your goals.", "ERR_LO_G9WWA3_WHY", 2),
    TF("Both the NSC and NCV can lead to further study or work.", "True",
      "Both qualifications can open paths to further study or employment.", "ERR_LO_G9WWA3_BOTH", 1),
    CLOZE("A choice between the NSC and NCV should match your interests and ____.",
      ["goals", "fears", "height", "address"], "goals",
      "Your path should match your interests and future goals.", "ERR_LO_G9WWA3_GOALS", 1),
    MC("Which is a good way to research your options?",
      ["Speak to a career counsellor and visit colleges", "Guess randomly", "Copy a friend's choice", "Ignore all advice"], "Speak to a career counsellor and visit colleges",
      "Counsellors and college visits give reliable information to choose well.", "ERR_LO_G9WWA3_RESEARCH", 2),
    TF("It is wise to consider your strengths before choosing a path.", "True",
      "Considering your strengths helps you choose a suitable path.", "ERR_LO_G9WWA3_STRENGTHS", 1),
    MC("Leaving school without any qualification usually makes finding work…",
      ["harder", "easier", "guaranteed", "automatic"], "harder",
      "Leaving without a qualification usually makes finding good work harder.", "ERR_LO_G9WWA3_DROPOUT", 2),
    {
      question: "Sort each feature under the NSC or the NCV.",
      input_type: "sort-buckets",
      buckets: [{ id: "nsc", label: "NSC" }, { id: "ncv", label: "NCV" }],
      items: [
        { id: "i1", text: "Done at school in Grades 10–12", correct_bucket: "nsc" },
        { id: "i2", text: "More academic route to university", correct_bucket: "nsc" },
        { id: "i3", text: "Studied at a TVET college", correct_bucket: "ncv" },
        { id: "i4", text: "More practical and vocational", correct_bucket: "ncv" },
      ],
      expected: "School Grades 10–12 and academic route are NSC; TVET college and practical/vocational are NCV.",
      pass_threshold: 0.75,
      memo: "The NSC is school-based and academic; the NCV is college-based and vocational.",
      error_signals: ["ERR_LO_G9WWA3_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps for choosing your path after Grade 9 in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Think about your interests, strengths and goals" },
        { id: "s2", text: "Research the NSC and NCV options" },
        { id: "s3", text: "Weigh the implications of each" },
        { id: "s4", text: "Make an informed choice" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Consider your goals, research the options, weigh the implications, then make an informed choice.",
      memo: "Choose your path by knowing your goals, researching options, weighing implications and deciding.",
      error_signals: ["ERR_LO_G9WWA3_SEQ"], difficulty: 2,
    },
    TF("Both the NSC and the NCV are valid, recognised qualifications.", "True",
      "The NSC and NCV are both valid, recognised qualifications that can lead to study or work.", "ERR_LO_G9WWA3_VALID", 1),
    MC("The key idea about options after Grade 9 is to…",
      ["choose the path that best fits your goals and strengths", "drop out", "choose at random", "copy a friend's path"], "choose the path that best fits your goals and strengths",
      "Choose the post-Grade-9 path that best fits your goals and strengths.", "ERR_LO_G9WWA3_SUMMARY", 2),
  ],

  // WW.A4 · Knowledge of the world of work
  "LO.G9.WW.A4": [
    MC("Which is a RIGHT workers have in the workplace?",
      ["To be treated fairly and work in safe conditions", "To be abused", "To be paid nothing", "To be discriminated against"], "To be treated fairly and work in safe conditions",
      "Workers have rights to fair treatment, safe conditions and fair pay.", "ERR_LO_G9WWA4_RIGHTS", 1),
    TF("Workers have responsibilities as well as rights.", "True",
      "Workers have responsibilities, like doing their job well, alongside their rights.", "ERR_LO_G9WWA4_BOTH", 1),
    MC("Which is a RESPONSIBILITY of a worker?",
      ["Doing the job honestly and on time", "Stealing from the employer", "Skipping work without reason", "Ignoring safety rules"], "Doing the job honestly and on time",
      "Workers are responsible for doing their job honestly, reliably and safely.", "ERR_LO_G9WWA4_RESPONSIBILITY", 1),
    CLOZE("A chance to get a job or advance at work is an ____.",
      ["opportunity", "obstacle", "excuse", "accident"], "opportunity",
      "Opportunities are chances to get work or advance in a career.", "ERR_LO_G9WWA4_OPPORTUNITY", 1),
    MC("Why is it important to know your rights at work?",
      ["So you can protect yourself from unfair treatment", "So you can break rules", "It is never useful", "To avoid all work"], "So you can protect yourself from unfair treatment",
      "Knowing your rights helps you recognise and resist unfair treatment.", "ERR_LO_G9WWA4_KNOW", 2),
    TF("Workplaces should be free from unfair discrimination.", "True",
      "Workers have the right to a workplace free from unfair discrimination.", "ERR_LO_G9WWA4_DISCRIM", 1),
    MC("Which is part of professional, responsible work behaviour?",
      ["Being punctual and reliable", "Arriving late often", "Ignoring instructions", "Being dishonest"], "Being punctual and reliable",
      "Punctuality, reliability and honesty are responsible work behaviours.", "ERR_LO_G9WWA4_PROFESSIONAL", 1),
    CLOZE("Workers have a right to fair ____ for the work they do.",
      ["pay", "punishment", "blame", "silence"], "pay",
      "Workers have a right to fair pay for their work.", "ERR_LO_G9WWA4_PAY", 1),
    TF("Safe working conditions are a right, not a favour.", "True",
      "A safe working environment is a worker's right.", "ERR_LO_G9WWA4_SAFE", 1),
    MC("An employer asks Naledi to work without any safety gear on a dangerous task. She has the right to…",
      ["request proper safety measures", "be put in danger", "say nothing and risk harm", "be fired for asking"], "request proper safety measures",
      "Workers have a right to safe conditions and can request proper safety measures.", "ERR_LO_G9WWA4_SCENARIO", 3),
    MC("Which is an example of an opportunity in the workplace?",
      ["A chance to train and get promoted", "Being denied all growth", "Being mistreated", "Losing your rights"], "A chance to train and get promoted",
      "Training and promotion are opportunities to grow in the workplace.", "ERR_LO_G9WWA4_GROW", 2),
    TF("Teamwork and good communication are valued in most workplaces.", "True",
      "Most workplaces value teamwork and good communication.", "ERR_LO_G9WWA4_TEAMWORK", 1),
    CLOZE("Following workplace ____ rules helps prevent accidents.",
      ["safety", "lunch", "fashion", "music"], "safety",
      "Following safety rules helps prevent workplace accidents.", "ERR_LO_G9WWA4_SAFETY", 1),
    MC("Why are responsibilities important in the world of work?",
      ["Reliable workers keep workplaces running well", "They are pointless", "Only rights matter", "They harm the worker"], "Reliable workers keep workplaces running well",
      "Responsibilities keep workplaces running smoothly and build trust.", "ERR_LO_G9WWA4_WHY", 2),
    TF("Knowing the world of work helps you prepare for future jobs.", "True",
      "Understanding work rights, responsibilities and opportunities prepares you for jobs.", "ERR_LO_G9WWA4_PREPARE", 1),
    MC("If a worker faces unfair treatment, they can…",
      ["report it to a union or the labour authorities", "do nothing", "accept abuse", "quit and stay silent only"], "report it to a union or the labour authorities",
      "Workers can report unfair treatment to unions or labour authorities.", "ERR_LO_G9WWA4_REPORT", 2),
    {
      question: "Sort each into a worker's RIGHT or a worker's RESPONSIBILITY.",
      input_type: "sort-buckets",
      buckets: [{ id: "right", label: "Right" }, { id: "responsibility", label: "Responsibility" }],
      items: [
        { id: "i1", text: "To be paid fairly", correct_bucket: "right" },
        { id: "i2", text: "To work in safe conditions", correct_bucket: "right" },
        { id: "i3", text: "To do the job honestly", correct_bucket: "responsibility" },
        { id: "i4", text: "To follow safety rules", correct_bucket: "responsibility" },
      ],
      expected: "Fair pay and safe conditions are rights; doing the job honestly and following safety rules are responsibilities.",
      pass_threshold: 0.75,
      memo: "Rights are what workers are owed; responsibilities are what workers must do.",
      error_signals: ["ERR_LO_G9WWA4_SORT"], difficulty: 1,
    },
    {
      question: "Put the steps for responding to unfair treatment at work in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Know your rights as a worker" },
        { id: "s2", text: "Raise the issue with your employer" },
        { id: "s3", text: "Report to a union or labour authority if unresolved" },
        { id: "s4", text: "Seek further help or advice" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Know your rights, raise it with your employer, report to a union or authority, then seek further help.",
      memo: "Respond to unfair treatment by knowing your rights, raising it, reporting and seeking help.",
      error_signals: ["ERR_LO_G9WWA4_SEQ"], difficulty: 2,
    },
    TF("Understanding work rights and responsibilities prepares you for future jobs.", "True",
      "Knowing your rights, responsibilities and opportunities prepares you for the world of work.", "ERR_LO_G9WWA4_PREPARE2", 1),
    MC("The key idea about the world of work is that it involves…",
      ["rights, responsibilities and opportunities together", "rights only", "responsibilities only", "nothing to prepare for"], "rights, responsibilities and opportunities together",
      "The world of work involves rights, responsibilities and opportunities together.", "ERR_LO_G9WWA4_SUMMARY", 2),
  ],

  // WW.A5 · Career and subject choices
  "LO.G9.WW.A5": [
    MC("Why are Grade 10 subject choices important?",
      ["They open or close paths to certain careers", "They have no effect", "They only matter for sport", "They can never be changed at all"], "They open or close paths to certain careers",
      "Subject choices in Grade 10 can open or close paths to certain careers.", "ERR_LO_G9WWA5_DEF", 1),
    TF("Some careers require specific school subjects.", "True",
      "Many careers require particular subjects, like Maths or Physical Sciences.", "ERR_LO_G9WWA5_REQUIRE", 1),
    MC("Which subjects does an engineering career usually need?",
      ["Mathematics and Physical Sciences", "No subjects", "Only languages", "Only art"], "Mathematics and Physical Sciences",
      "Engineering usually requires Mathematics and Physical Sciences.", "ERR_LO_G9WWA5_ENGINEER", 2),
    CLOZE("Choosing subjects linked to a career you want is making an ____ choice.",
      ["informed", "random", "careless", "blind"], "informed",
      "Linking subject choices to your career goal is an informed decision.", "ERR_LO_G9WWA5_INFORMED", 1),
    MC("How should you choose your Grade 10 subjects?",
      ["Based on interests, abilities and career goals", "By copying a friend", "At random", "By avoiding all thought"], "Based on interests, abilities and career goals",
      "Subject choices should reflect your interests, abilities and career goals.", "ERR_LO_G9WWA5_HOW", 2),
    TF("Your strengths and weaknesses are worth considering when choosing subjects.", "True",
      "Considering your strengths and weaknesses helps you choose suitable subjects.", "ERR_LO_G9WWA5_STRENGTHS", 1),
    MC("Naledi wants to be a doctor. Which subjects should she prioritise?",
      ["Life Sciences, Physical Sciences and Mathematics", "Only art subjects", "No science at all", "Only physical education"], "Life Sciences, Physical Sciences and Mathematics",
      "Medicine requires Life Sciences, Physical Sciences and Mathematics.", "ERR_LO_G9WWA5_DOCTOR", 2),
    CLOZE("Decision-making skills help you choose subjects step by ____.",
      ["step", "luck", "guess", "force"], "step",
      "Good decision-making chooses subjects step by step, weighing the options.", "ERR_LO_G9WWA5_STEP", 1),
    TF("It is wise to research careers before choosing subjects.", "True",
      "Researching careers first helps you choose the right subjects for them.", "ERR_LO_G9WWA5_RESEARCH", 1),
    MC("Sipho is unsure which subjects to take. The best step is to…",
      ["research careers and talk to a career counsellor", "pick randomly", "copy a friend", "decide with no information"], "research careers and talk to a career counsellor",
      "Researching careers and consulting a counsellor leads to informed subject choices.", "ERR_LO_G9WWA5_SCENARIO", 3),
    MC("Which links careers and subjects correctly?",
      ["Accountant → Mathematics and Accounting", "Pilot → no subjects needed", "Engineer → only art", "Nurse → no science"], "Accountant → Mathematics and Accounting",
      "An accountant needs Mathematics and Accounting; careers link to specific subjects.", "ERR_LO_G9WWA5_LINK", 2),
    TF("Once chosen, subject choices have no effect on future study options.", "False",
      "Subject choices strongly affect which courses and careers you can pursue later.", "ERR_LO_G9WWA5_EFFECT", 2),
    CLOZE("A subject you enjoy and do well in matches your interest and ____.",
      ["ability", "fear", "height", "luck"], "ability",
      "The best subject choices match both your interest and your ability.", "ERR_LO_G9WWA5_ABILITY", 1),
    MC("Why consider your interests when choosing subjects?",
      ["You work harder at subjects you enjoy", "Interests never matter", "Only marks matter", "Enjoyment is irrelevant"], "You work harder at subjects you enjoy",
      "You tend to work harder and do better at subjects you enjoy.", "ERR_LO_G9WWA5_INTEREST", 2),
    TF("Talking to people in a career can help you understand its subject needs.", "True",
      "People working in a career can explain the subjects and skills it requires.", "ERR_LO_G9WWA5_TALK", 1),
    MC("A balanced subject choice considers…",
      ["interests, abilities, career goals and requirements", "only what is easiest", "only friends' choices", "nothing at all"], "interests, abilities, career goals and requirements",
      "Balanced choices weigh interests, abilities, goals and career requirements.", "ERR_LO_G9WWA5_BALANCED", 2),
    {
      question: "Match each career with a key subject by ordering the subjects for Career 1→4.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "(Doctor) Life Sciences" },
        { id: "s2", text: "(Engineer) Physical Sciences" },
        { id: "s3", text: "(Accountant) Accounting" },
        { id: "s4", text: "(Translator) Languages" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Doctor→Life Sciences, engineer→Physical Sciences, accountant→Accounting, translator→Languages.",
      memo: "Careers link to key subjects that you must choose in Grade 10.",
      error_signals: ["ERR_LO_G9WWA5_SEQ"], difficulty: 2,
    },
    {
      question: "Sort each factor into RELEVANT or NOT RELEVANT to choosing subjects.",
      input_type: "sort-buckets",
      buckets: [{ id: "relevant", label: "Relevant" }, { id: "not", label: "Not relevant" }],
      items: [
        { id: "i1", text: "Your career goal", correct_bucket: "relevant" },
        { id: "i2", text: "Your abilities and interests", correct_bucket: "relevant" },
        { id: "i3", text: "Which subject your friend picked", correct_bucket: "not" },
        { id: "i4", text: "The colour of the textbook", correct_bucket: "not" },
      ],
      expected: "Career goals, abilities and interests are relevant; a friend's pick and textbook colour are not.",
      pass_threshold: 0.75,
      memo: "Choose subjects on your own goals, abilities and interests — not on trivial factors.",
      error_signals: ["ERR_LO_G9WWA5_SORT"], difficulty: 1,
    },
    MC("The key idea of career and subject choices is to…",
      ["align subjects with your career goals and strengths", "choose by chance", "ignore your future", "copy others"], "align subjects with your career goals and strengths",
      "Align your subject choices with your career goals and strengths.", "ERR_LO_G9WWA5_SUMMARY", 2),
    TF("Researching a career before choosing subjects leads to better decisions.", "True",
      "Researching careers first helps you choose subjects that fit your goals.", "ERR_LO_G9WWA5_RESEARCH2", 1),
  ],

  // WW.A6 · Funding and lifelong learning
  "LO.G9.WW.A6": [
    MC("What is a 'bursary'?",
      ["Money given to help pay for study", "A type of exam", "A school subject", "A sport"], "Money given to help pay for study",
      "A bursary is financial aid given to help pay for study, often not repaid.", "ERR_LO_G9WWA6_BURSARY", 1),
    TF("A student loan must usually be paid back, often after you start working.", "True",
      "A student loan is borrowed money that must be repaid, usually once you work.", "ERR_LO_G9WWA6_LOAN", 1),
    MC("Which is a study and career FUNDING provider?",
      ["NSFAS or a company bursary scheme", "A sweet shop", "A football club only", "A taxi rank"], "NSFAS or a company bursary scheme",
      "Funding providers include NSFAS, bursaries, scholarships and student loans.", "ERR_LO_G9WWA6_PROVIDER", 2),
    CLOZE("Money awarded for good academic results is often called a ____.",
      ["scholarship", "fine", "fee", "loan"], "scholarship",
      "A scholarship is funding awarded, often for strong academic or other achievement.", "ERR_LO_G9WWA6_SCHOLARSHIP", 2),
    MC("What does NSFAS help with?",
      ["Funding for tertiary study for eligible students", "Free cars", "Sports tickets", "Nothing"], "Funding for tertiary study for eligible students",
      "NSFAS provides funding for eligible students' tertiary study.", "ERR_LO_G9WWA6_NSFAS", 2),
    TF("Lifelong learning means continuing to learn and grow after school.", "True",
      "Lifelong learning is the idea of continuing to learn throughout your life.", "ERR_LO_G9WWA6_LIFELONG", 1),
    MC("Why is lifelong learning important?",
      ["The world and jobs keep changing, so we keep learning", "Learning should stop at school", "It has no value", "It wastes time"], "The world and jobs keep changing, so we keep learning",
      "Because the world and jobs change, lifelong learning keeps your skills relevant.", "ERR_LO_G9WWA6_WHY", 2),
    CLOZE("Setting goals for learning you will keep doing is planning for ____ learning.",
      ["lifelong", "no", "fake", "lost"], "lifelong",
      "Planning for lifelong learning means setting goals to keep learning over time.", "ERR_LO_G9WWA6_PLAN", 1),
    TF("A bursary often does not need to be repaid, unlike a loan.", "True",
      "Bursaries usually need not be repaid, while loans must be.", "ERR_LO_G9WWA6_REPAY", 2),
    MC("Naledi wants to study but cannot afford it. A sensible step is to…",
      ["apply for bursaries, NSFAS or scholarships", "give up on study", "do nothing", "assume it is impossible"], "apply for bursaries, NSFAS or scholarships",
      "Applying for bursaries, NSFAS or scholarships can make study affordable.", "ERR_LO_G9WWA6_SCENARIO", 3),
    MC("Which is a way to keep learning after school (lifelong learning)?",
      ["Short courses, reading and on-the-job training", "Never learning again", "Avoiding all new skills", "Ignoring change"], "Short courses, reading and on-the-job training",
      "Lifelong learning includes short courses, reading and learning at work.", "ERR_LO_G9WWA6_WAYS", 2),
    TF("Researching funding early gives you more time to apply successfully.", "True",
      "Researching funding early leaves time to meet requirements and deadlines.", "ERR_LO_G9WWA6_EARLY", 1),
    CLOZE("People who keep learning can adapt to new ____ in the workplace.",
      ["skills", "weather", "snacks", "colours"], "skills",
      "Lifelong learners adapt by gaining new skills as the workplace changes.", "ERR_LO_G9WWA6_SKILLS", 1),
    MC("Why might an employer value a lifelong learner?",
      ["They keep improving and adapting", "They refuse to grow", "They resist all change", "They never learn"], "They keep improving and adapting",
      "Employers value lifelong learners who keep improving and adapting.", "ERR_LO_G9WWA6_EMPLOYER", 2),
    TF("Goal-setting helps you plan your own lifelong learning.", "True",
      "Setting goals helps you plan and pursue lifelong learning.", "ERR_LO_G9WWA6_GOALS", 1),
    MC("Which is the best reason to plan for lifelong learning now?",
      ["It prepares you to grow and adapt your whole life", "Learning stops after school", "It is pointless", "Only children learn"], "It prepares you to grow and adapt your whole life",
      "Planning for lifelong learning prepares you to grow and adapt throughout life.", "ERR_LO_G9WWA6_REASON", 2),
    {
      question: "Sort each funding type by whether it is usually REPAID or NOT REPAID.",
      input_type: "sort-buckets",
      buckets: [{ id: "repaid", label: "Usually repaid" }, { id: "not", label: "Usually not repaid" }],
      items: [
        { id: "i1", text: "Student loan", correct_bucket: "repaid" },
        { id: "i2", text: "Bank study loan", correct_bucket: "repaid" },
        { id: "i3", text: "Bursary", correct_bucket: "not" },
        { id: "i4", text: "Scholarship", correct_bucket: "not" },
      ],
      expected: "Loans are usually repaid; bursaries and scholarships usually are not.",
      pass_threshold: 0.75,
      memo: "Loans must be repaid; bursaries and scholarships usually do not.",
      error_signals: ["ERR_LO_G9WWA6_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps for funding your further study in order.",
      input_type: "sequence",
      items: [
        { id: "s1", text: "Decide what you want to study" },
        { id: "s2", text: "Research funding options (NSFAS, bursaries)" },
        { id: "s3", text: "Check requirements and deadlines" },
        { id: "s4", text: "Apply on time" },
      ],
      expected_order: ["s1", "s2", "s3", "s4"],
      expected: "Decide what to study, research funding, check requirements and deadlines, then apply on time.",
      memo: "Fund your study by deciding, researching options, checking requirements and applying on time.",
      error_signals: ["ERR_LO_G9WWA6_SEQ"], difficulty: 2,
    },
    TF("Applying for funding early gives you the best chance of success.", "True",
      "Applying early leaves time to meet requirements and deadlines, improving your chances.", "ERR_LO_G9WWA6_EARLY2", 1),
    MC("The key idea of funding and lifelong learning is that you can…",
      ["fund your studies and keep learning throughout life", "only learn at school", "never afford study", "stop growing after Grade 12"], "fund your studies and keep learning throughout life",
      "With funding options and lifelong learning, you can study and keep growing for life.", "ERR_LO_G9WWA6_SUMMARY", 2),
  ],
};

export default G9B;
