// ─── Social Sciences SP — Grade 7 question pools, batch B ─────────────────────
// Additional items appended to sssp-g7.mjs (concatenated by the generator) to
// bring each pool to ~20. New facts/angles; no repeats of batch A. Tap-only.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7B = {
  // ── H1.A1 Trade across the Sahara ──
  "SSSP.G7.H1.A1": [
    MC("The Sahara is the world's largest hot ____.", ["desert", "forest", "ocean", "mountain range"], "desert",
      "The Sahara is the largest hot desert, which is why crossing it needed camels and caravans.", "ERR_SSSP_G7H1A1_B01", 1),
    TF("Ostrich feathers were among the goods traded from West Africa.", "True",
      "Gold, ivory, enslaved people and ostrich feathers were traded out of West Africa.", "ERR_SSSP_G7H1A1_B02", 2),
    MC("Trade goods from Europe and North Africa entered West Africa in exchange for gold and other goods. This makes the Sahara trade an example of:",
      ["Long-distance exchange between regions", "Local village bartering only", "Trade by sea", "A modern railway"], "Long-distance exchange between regions",
      "Goods crossed the whole desert between regions — long-distance trade.", "ERR_SSSP_G7H1A1_B03", 2),
    CLOZE("Traders relied on oases — places in the desert with ____.", ["water", "gold", "snow", "factories"], "water",
      "Oases provided water, vital rest stops on the desert crossing.", "ERR_SSSP_G7H1A1_B04", 2),
    TF("Without camels, crossing the Sahara for trade would have been far harder.", "True",
      "Camels made the desert crossing possible, so they were central to the trade.", "ERR_SSSP_G7H1A1_B05", 1),
    MC("The spread of Islam along the trade routes is an example of trade carrying:",
      ["Ideas and religion, not just goods", "Only gold", "Only salt", "Nothing but danger"], "Ideas and religion, not just goods",
      "Trade routes carried ideas and religion as well as goods.", "ERR_SSSP_G7H1A1_B06", 2),
    MC("Which best describes a caravan route?", ["A regular path traders followed across the desert", "A type of camel", "A West African king", "A kind of salt"], "A regular path traders followed across the desert",
      "Caravan routes were the established paths traders used across the Sahara.", "ERR_SSSP_G7H1A1_B07", 1),
    TF("Trade made some West African towns wealthy and important.", "True",
      "Trade wealth helped towns like Timbuktu grow rich and important.", "ERR_SSSP_G7H1A1_B08", 1),
    MC("Why did traders value gold from West Africa so highly?", ["It was rare and beautiful and did not rust", "It was common everywhere", "It was used as food", "It melted in the sun"], "It was rare and beautiful and did not rust",
      "Gold's rarity and lasting shine made it highly valued.", "ERR_SSSP_G7H1A1_B09", 1),
    CLOZE("Goods moving in both directions made the Sahara a busy ____ route.", ["trade", "war", "river", "rail"], "trade",
      "The Sahara was a busy two-way trade route.", "ERR_SSSP_G7H1A1_B10", 1),
    TF("North Africa borders the Mediterranean Sea, linking Saharan trade to Europe.", "True",
      "Goods reached the Mediterranean and Europe through North Africa.", "ERR_SSSP_G7H1A1_B11", 2),
    MC("A historian studying Saharan trade might use which source?", ["Travellers' written accounts", "A modern cellphone", "A weather satellite", "A football score"], "Travellers' written accounts",
      "Written accounts by travellers are valuable historical sources.", "ERR_SSSP_G7H1A1_B12", 2),
  ],
  // ── H1.A2 The kingdom of Mali ──
  "SSSP.G7.H1.A2": [
    MC("Mali grew wealthy mainly by controlling trade in gold and ____.", ["salt", "tea", "oil", "coal"], "salt",
      "Mali controlled the trade in gold and salt, the two great Saharan goods.", "ERR_SSSP_G7H1A2_B01", 1),
    TF("Mansa is a title meaning king or emperor.", "True",
      "'Mansa' was the title of Mali's rulers, meaning king or emperor.", "ERR_SSSP_G7H1A2_B02", 2),
    MC("Mansa Musa's journey passed through which famous Egyptian city on the way to Mecca?", ["Cairo", "London", "Rome", "Cape Town"], "Cairo",
      "Mansa Musa's pilgrimage passed through Cairo, where his spending became legendary.", "ERR_SSSP_G7H1A2_B03", 3),
    CLOZE("Mali was a powerful ____ in West Africa in the 14th century.", ["kingdom", "island", "desert", "ocean"], "kingdom",
      "Mali was a powerful West African kingdom at its height in the 1300s.", "ERR_SSSP_G7H1A2_B04", 1),
    TF("Mali's wealth allowed it to support learning and grand buildings.", "True",
      "Trade wealth funded mosques, learning and grand architecture in Mali.", "ERR_SSSP_G7H1A2_B05", 2),
    MC("Mansa Musa is best remembered as a ruler who was:", ["Extremely wealthy and a devout Muslim", "A poor farmer", "A European explorer", "A sea captain"], "Extremely wealthy and a devout Muslim",
      "He is remembered for his vast wealth and his Muslim faith.", "ERR_SSSP_G7H1A2_B06", 1),
    MC("A pilgrimage to Mecca is one of the duties of which faith?", ["Islam", "Hinduism", "Buddhism", "None"], "Islam",
      "The hajj to Mecca is a duty for Muslims who are able to make it.", "ERR_SSSP_G7H1A2_B07", 2),
    TF("Mali had no trade links with North Africa.", "False",
      "Mali traded heavily across the Sahara with North Africa.", "ERR_SSSP_G7H1A2_B08", 1),
    MC("The Great Mosque built in Mali shows the kingdom's:", ["Wealth and Muslim faith", "Poverty", "Sea power", "Lack of religion"], "Wealth and Muslim faith",
      "Building a great mosque displayed Mali's wealth and Islamic faith.", "ERR_SSSP_G7H1A2_B09", 2),
    CLOZE("Mansa Musa ruled in the early ____ century.", ["14th", "1st", "19th", "20th"], "14th",
      "Mansa Musa ruled Mali at its height in the early 14th century (1300s).", "ERR_SSSP_G7H1A2_B10", 2),
    TF("Mali's gold was important far beyond West Africa.", "True",
      "Mali's gold was valued across North Africa, the Mediterranean and beyond.", "ERR_SSSP_G7H1A2_B11", 2),
    MC("Why do we know about Mansa Musa today?", ["His wealth and pilgrimage were widely recorded", "He wrote modern books", "He appeared on TV", "Nobody recorded him"], "His wealth and pilgrimage were widely recorded",
      "Accounts of his famous pilgrimage spread his fame and preserved his story.", "ERR_SSSP_G7H1A2_B12", 2),
  ],
  // ── H1.A3 Timbuktu ──
  "SSSP.G7.H1.A3": [
    MC("Timbuktu is located near which great African river?", ["The Niger", "The Nile", "The Thames", "The Orange"], "The Niger",
      "Timbuktu lies near the Niger River, aiding its trade.", "ERR_SSSP_G7H1A3_B01", 3),
    TF("Timbuktu had famous centres of Islamic learning.", "True",
      "Timbuktu's mosques and schools were renowned centres of Islamic learning.", "ERR_SSSP_G7H1A3_B02", 1),
    MC("Manuscripts are valuable to historians because they:", ["Record knowledge from the past", "Predict the future", "Show the weather", "Are made of gold"], "Record knowledge from the past",
      "Manuscripts preserve past knowledge, making them precious historical sources.", "ERR_SSSP_G7H1A3_B03", 2),
    CLOZE("Timbuktu attracted students and ____ from far away.", ["scholars", "soldiers", "sailors", "miners"], "scholars",
      "Scholars travelled to Timbuktu to study and teach.", "ERR_SSSP_G7H1A3_B04", 2),
    TF("Salt and gold were both traded at Timbuktu.", "True",
      "Timbuktu was a market where salt was exchanged for gold.", "ERR_SSSP_G7H1A3_B05", 1),
    MC("Being a World Heritage Site means Timbuktu is recognised as:", ["Important to all of humanity", "A modern shopping centre", "A private home", "A gold mine"], "Important to all of humanity",
      "World Heritage status marks a place of outstanding value to all humanity.", "ERR_SSSP_G7H1A3_B06", 2),
    MC("The Timbuktu manuscripts deal with subjects such as:", ["Astronomy, medicine and law", "Modern football", "Space travel", "Television"], "Astronomy, medicine and law",
      "The manuscripts cover astronomy, medicine, law, history and more.", "ERR_SSSP_G7H1A3_B07", 2),
    TF("Preserving the manuscripts protects African history and knowledge.", "True",
      "Conserving the manuscripts safeguards a record of African scholarship.", "ERR_SSSP_G7H1A3_B08", 1),
    MC("Timbuktu's importance shows that Africa had:", ["Centres of learning and trade long ago", "No history before Europeans", "Only deserts", "No trade"], "Centres of learning and trade long ago",
      "Timbuktu proves Africa had advanced centres of trade and learning long ago.", "ERR_SSSP_G7H1A3_B09", 2),
    CLOZE("Timbuktu sat on a major ____ route across the Sahara.", ["caravan", "railway", "shipping", "flight"], "caravan",
      "Timbuktu was a key stop on the trans-Saharan caravan route.", "ERR_SSSP_G7H1A3_B10", 1),
    TF("Leo Africanus visited Timbuktu and wrote about it.", "True",
      "Leo Africanus described Timbuktu after visiting it, in his 1550 book.", "ERR_SSSP_G7H1A3_B11", 2),
    MC("Why is it important to study places like Timbuktu?", ["They challenge the false idea that Africa had no rich history", "They are modern cities", "They have no value", "They are in Europe"], "They challenge the false idea that Africa had no rich history",
      "Timbuktu reminds us of Africa's rich past of learning and trade.", "ERR_SSSP_G7H1A3_B12", 3),
  ],
  // ── H2.A1 West Africa & slavery before Europeans ──
  "SSSP.G7.H2.A1": [
    MC("West African kingdoms before Europeans were often organised around:", ["Trade, farming and rulers", "Factories", "Railways", "Oil wells"], "Trade, farming and rulers",
      "These societies had rulers, farming and busy trade long before Europeans.", "ERR_SSSP_G7H2A1_B01", 1),
    TF("The Atlantic slave trade forced far more people across the ocean than earlier West African slavery moved.", "True",
      "The Atlantic trade was vastly larger in scale than earlier West African slavery.", "ERR_SSSP_G7H2A1_B02", 2),
    MC("Why is it important to know West Africa had organised societies before Europeans?", ["It corrects the false idea that Africa had no history", "It proves Africa was empty", "It shows Europeans built everything", "It has no value"], "It corrects the false idea that Africa had no history",
      "Knowing this corrects the myth that Africa lacked its own rich history.", "ERR_SSSP_G7H2A1_B03", 2),
    CLOZE("Before the Atlantic trade, West Africa traded across the ____ Desert.", ["Sahara", "Kalahari", "Gobi", "Arctic"], "Sahara",
      "West Africa was already linked to the world by trans-Saharan trade.", "ERR_SSSP_G7H2A1_B04", 2),
    TF("All forms of slavery are exactly the same.", "False",
      "Slavery took different forms; Atlantic plantation slavery was uniquely vast and brutal.", "ERR_SSSP_G7H2A1_B05", 2),
    MC("Comparing slavery before and after Europeans is an example of which history skill?", ["Comparing change over time", "Drawing maps", "Counting money", "Measuring rainfall"], "Comparing change over time",
      "Comparing the two is using the skill of change and continuity over time.", "ERR_SSSP_G7H2A1_B06", 3),
    MC("West African societies had their own:", ["Languages, cultures and trade", "European factories", "Nothing of value", "Modern cities only"], "Languages, cultures and trade",
      "They had rich languages, cultures and trade of their own.", "ERR_SSSP_G7H2A1_B07", 1),
    TF("European demand for plantation labour greatly increased the scale of slavery.", "True",
      "Europe's plantation economy drove the huge expansion of the Atlantic slave trade.", "ERR_SSSP_G7H2A1_B08", 2),
    MC("A 'kingdom' is a society ruled by a:", ["King or queen", "Company", "Factory owner", "Sea captain"], "King or queen",
      "A kingdom is ruled by a king or queen — West Africa had several.", "ERR_SSSP_G7H2A1_B09", 1),
    CLOZE("The Atlantic slave trade moved people across the ____ Ocean.", ["Atlantic", "Pacific", "Indian", "Arctic"], "Atlantic",
      "The trade carried people across the Atlantic to the Americas.", "ERR_SSSP_G7H2A1_B10", 1),
    TF("Trade in West Africa existed only after Europeans arrived.", "False",
      "West Africa had thriving trade long before Europeans came.", "ERR_SSSP_G7H2A1_B11", 1),
    MC("Studying West Africa before the slave trade helps us understand:", ["What was lost and changed by the trade", "Modern Europe only", "Nothing", "The weather"], "What was lost and changed by the trade",
      "It shows what these societies were like before the trade disrupted them.", "ERR_SSSP_G7H2A1_B12", 2),
  ],
  // ── H2.A2 Slavery in the American South ──
  "SSSP.G7.H2.A2": [
    MC("Tobacco, rice and sugar cane were grown on:", ["Plantations", "City streets", "Ships", "Mountains"], "Plantations",
      "These cash crops were grown on plantations with enslaved labour.", "ERR_SSSP_G7H2A2_B01", 1),
    TF("Enslaved people were treated as property to be bought and sold.", "True",
      "Under slavery, people were owned as property and sold at markets.", "ERR_SSSP_G7H2A2_B02", 1),
    MC("Cotton from the American South was important to industry in:", ["Britain", "Mali", "the Sahara", "Timbuktu"], "Britain",
      "Southern cotton fed British textile factories.", "ERR_SSSP_G7H2A2_B03", 2),
    CLOZE("The forced ocean voyage of enslaved Africans was the Middle ____.", ["Passage", "Market", "Plantation", "Kingdom"], "Passage",
      "The Middle Passage was the brutal Atlantic crossing.", "ERR_SSSP_G7H2A2_B04", 1),
    TF("Many enslaved people died during the Middle Passage.", "True",
      "Overcrowding, disease and cruelty killed many during the crossing.", "ERR_SSSP_G7H2A2_B05", 1),
    MC("Why did plantation owners want enslaved labour rather than paid workers?", ["To increase profit by not paying wages", "To be kind", "To build schools", "To explore"], "To increase profit by not paying wages",
      "Forced, unpaid labour increased plantation profits.", "ERR_SSSP_G7H2A2_B06", 2),
    MC("Raw materials from plantations were turned into goods in:", ["Factories", "Deserts", "Oceans", "Caves"], "Factories",
      "Plantation raw materials were processed in factories, often in Britain.", "ERR_SSSP_G7H2A2_B07", 2),
    TF("The slave trade linked Africa, the Americas and Europe.", "True",
      "The Atlantic trade connected three continents in a system of forced labour and goods.", "ERR_SSSP_G7H2A2_B08", 2),
    MC("A plantation was a:", ["Large farm growing one main crop", "Small city", "Type of ship", "Gold mine"], "Large farm growing one main crop",
      "Plantations were large farms focused on a single cash crop.", "ERR_SSSP_G7H2A2_B09", 1),
    CLOZE("Enslaved people were sold at a slave ____.", ["market", "school", "park", "library"], "market",
      "Enslaved people were bought and sold at slave markets.", "ERR_SSSP_G7H2A2_B10", 1),
    TF("Slavery in the American South was gentle and fair.", "False",
      "Plantation slavery was harsh, cruel and based on force.", "ERR_SSSP_G7H2A2_B11", 1),
    MC("The huge profits from plantation crops mainly benefited:", ["Owners, and economies in America and Britain", "The enslaved people", "West Africa", "Nobody"], "Owners, and economies in America and Britain",
      "Profits flowed to owners and to the American and British economies.", "ERR_SSSP_G7H2A2_B12", 2),
  ],
  // ── H2.A3 Impact on enslaved people ──
  "SSSP.G7.H2.A3": [
    MC("Spirituals and work songs were part of enslaved people's:", ["Culture and survival", "Weapons", "Wages", "Plantations"], "Culture and survival",
      "Songs and stories helped enslaved communities endure and keep their culture.", "ERR_SSSP_G7H2A3_B01", 2),
    TF("The Underground Railroad used safe houses to help escapees.", "True",
      "Safe houses and secret routes formed the Underground Railroad.", "ERR_SSSP_G7H2A3_B02", 2),
    MC("Harriet Tubman is admired because she:", ["Escaped and returned to free others", "Owned plantations", "Led an army", "Built ships"], "Escaped and returned to free others",
      "After escaping, Tubman risked her life to free many others.", "ERR_SSSP_G7H2A3_B03", 2),
    CLOZE("Nat Turner led a slave ____ in 1831.", ["revolt", "market", "song", "trade"], "revolt",
      "Nat Turner's 1831 revolt was an armed uprising against slavery.", "ERR_SSSP_G7H2A3_B04", 2),
    TF("Resisting slavery could be very dangerous.", "True",
      "Resistance risked brutal punishment or death, so many forms were secret.", "ERR_SSSP_G7H2A3_B05", 1),
    MC("Pretending to be sick to avoid work was a form of:", ["Quiet resistance", "Open war", "Trade", "Farming"], "Quiet resistance",
      "Feigning illness was a subtle, passive form of resistance.", "ERR_SSSP_G7H2A3_B06", 2),
    MC("The story of the Amistad involves enslaved people who:", ["Rebelled aboard a ship", "Built a plantation", "Crossed the Sahara", "Founded Mali"], "Rebelled aboard a ship",
      "The Amistad captives rebelled aboard the slave ship in 1839.", "ERR_SSSP_G7H2A3_B07", 3),
    TF("Some white people, like John Brown, also fought against slavery.", "True",
      "Abolitionists such as John Brown fought to end slavery.", "ERR_SSSP_G7H2A3_B08", 2),
    MC("Keeping their own stories and beliefs helped enslaved people to:", ["Hold on to their identity", "Escape instantly", "Buy land", "Become owners"], "Hold on to their identity",
      "Culture and faith helped enslaved people keep their identity and hope.", "ERR_SSSP_G7H2A3_B09", 2),
    CLOZE("Helping enslaved people escape to free areas was the work of the Underground ____.", ["Railroad", "Market", "Plantation", "Mosque"], "Railroad",
      "The Underground Railroad helped people escape to freedom.", "ERR_SSSP_G7H2A3_B10", 1),
    TF("Escaping slavery was easy and safe.", "False",
      "Escape was extremely dangerous, with severe punishment if caught.", "ERR_SSSP_G7H2A3_B11", 1),
    MC("Studying resistance shows that enslaved people:", ["Actively fought their conditions in many ways", "Accepted slavery happily", "Had no feelings", "Did nothing"], "Actively fought their conditions in many ways",
      "Resistance proves enslaved people constantly struggled against their bondage.", "ERR_SSSP_G7H2A3_B12", 2),
  ],
  // ── H2.A4 Impact on economies ──
  "SSSP.G7.H2.A4": [
    MC("The slave trade is part of why some economies grew rich while others were:", ["Damaged and weakened", "Made equal", "Left unchanged", "All strengthened"], "Damaged and weakened",
      "It enriched some while damaging West Africa — an unequal outcome.", "ERR_SSSP_G7H2A4_B01", 1),
    TF("Profits from slavery helped fund Britain's growth.", "True",
      "Slave-trade and plantation profits helped finance Britain's economic growth.", "ERR_SSSP_G7H2A4_B02", 2),
    MC("Losing millions of young people harmed West Africa's:", ["Workforce and societies", "Deserts", "Position on the map", "Climate"], "Workforce and societies",
      "Losing so many young people robbed West Africa of workers and weakened societies.", "ERR_SSSP_G7H2A4_B03", 2),
    CLOZE("The slave trade had ____ effects on different regions.", ["unequal", "equal", "no", "tiny"], "unequal",
      "Its effects were deeply unequal — wealth for some, devastation for others.", "ERR_SSSP_G7H2A4_B04", 1),
    TF("The transatlantic slave trade affected three continents.", "True",
      "Africa, the Americas and Europe were all tied into the trade.", "ERR_SSSP_G7H2A4_B05", 1),
    MC("Cheap raw materials from plantations helped power which revolution in Britain?", ["The Industrial Revolution", "The French Revolution", "The Mineral Revolution", "The space race"], "The Industrial Revolution",
      "Plantation raw materials helped fuel Britain's Industrial Revolution.", "ERR_SSSP_G7H2A4_B06", 3),
    MC("Why do historians call the slave trade's effects on West Africa long-lasting?", ["The harm continued for generations", "It ended the next day", "It helped West Africa", "It had no effect"], "The harm continued for generations",
      "The damage to West African societies lasted for generations.", "ERR_SSSP_G7H2A4_B07", 3),
    TF("Britain and America were the regions that gained most economically.", "True",
      "Britain and America gained the most wealth from the trade.", "ERR_SSSP_G7H2A4_B08", 1),
    MC("The slave trade shows how economic gain can be built on:", ["Great human suffering", "Fair wages", "Free choice", "Equal trade"], "Great human suffering",
      "The wealth created rested on the suffering of enslaved people.", "ERR_SSSP_G7H2A4_B09", 2),
    CLOZE("West Africa suffered lasting ____ from the slave trade.", ["damage", "wealth", "trade", "peace"], "damage",
      "West Africa suffered deep, lasting damage.", "ERR_SSSP_G7H2A4_B10", 1),
    TF("Everyone involved in the slave trade benefited equally.", "False",
      "The benefits and the suffering fell on different regions — it was deeply unequal.", "ERR_SSSP_G7H2A4_B11", 1),
    MC("Understanding the economic effects helps us see that history shapes:", ["Inequalities that can last today", "Only the past", "The weather", "Nothing now"], "Inequalities that can last today",
      "Historic injustices like the slave trade still shape inequalities today.", "ERR_SSSP_G7H2A4_B12", 3),
  ],
  // ── H3.A1 Indigenous peoples of the Cape ──
  "SSSP.G7.H3.A1": [
    MC("The Khoikhoi kept herds of:", ["Cattle and sheep", "Camels", "Elephants", "Horses"], "Cattle and sheep",
      "The Khoikhoi were herders of cattle and sheep.", "ERR_SSSP_G7H3A1_B01", 1),
    TF("The San lived by hunting wild animals and gathering plants.", "True",
      "The San were hunter-gatherers, living off wild animals and plants.", "ERR_SSSP_G7H3A1_B02", 1),
    MC("African farmers settled to the east of the Cape because the area had:", ["Summer rainfall for their crops", "Gold", "No people", "Cooler deserts"], "Summer rainfall for their crops",
      "Their crops needed summer rain, found in the eastern regions.", "ERR_SSSP_G7H3A1_B03", 2),
    CLOZE("Sorghum and ____ were crops grown by African farmers.", ["millet", "rice", "wheat", "tea"], "millet",
      "Sorghum and millet were staple crops needing summer rainfall.", "ERR_SSSP_G7H3A1_B04", 3),
    TF("The Cape had several different groups of people before 1652.", "True",
      "Khoikhoi, San and (to the east) African farmers all lived in the region.", "ERR_SSSP_G7H3A1_B05", 1),
    MC("Hunter-gatherers usually moved around because they:", ["Followed animals and seasonal plants", "Owned factories", "Mined gold", "Built cities"], "Followed animals and seasonal plants",
      "The San moved to follow game and seasonal food sources.", "ERR_SSSP_G7H3A1_B06", 2),
    MC("Herders like the Khoikhoi moved to find:", ["Grazing and water for their animals", "Gold", "Factories", "Ships"], "Grazing and water for their animals",
      "Herders moved to fresh grazing and water for their herds.", "ERR_SSSP_G7H3A1_B07", 2),
    TF("The San left rock art that tells us about their lives.", "True",
      "San rock paintings are an important source about their culture and beliefs.", "ERR_SSSP_G7H3A1_B08", 2),
    MC("Knowing about these groups corrects the false idea that the Cape was:", ["Empty before settlers came", "Full of cities", "Covered in ice", "In Europe"], "Empty before settlers came",
      "The land was already home to several peoples, not empty.", "ERR_SSSP_G7H3A1_B09", 2),
    CLOZE("The Khoikhoi were ____, while the San were hunter-gatherers.", ["herders", "farmers", "sailors", "miners"], "herders",
      "Khoikhoi herders and San hunter-gatherers lived at the Cape.", "ERR_SSSP_G7H3A1_B10", 1),
    TF("Climate affected where different groups could live and farm.", "True",
      "Rainfall and climate shaped where farming and herding were possible.", "ERR_SSSP_G7H3A1_B11", 2),
    MC("Rock art is an example of a historical:", ["Source about the past", "Modern painting", "Weather report", "Map scale"], "Source about the past",
      "Rock art is a primary source telling us about San life.", "ERR_SSSP_G7H3A1_B12", 2),
  ],
  // ── H3.A2 Dutch settlement and the VOC ──
  "SSSP.G7.H3.A2": [
    MC("The VOC was a powerful trading company from which country?", ["The Netherlands", "Britain", "France", "Portugal"], "The Netherlands",
      "The VOC was the Dutch East India Company, from the Netherlands.", "ERR_SSSP_G7H3A2_B01", 1),
    TF("The Cape station supplied fresh food and water to passing ships.", "True",
      "The station provided fresh supplies to VOC ships on the long voyage to the East.", "ERR_SSSP_G7H3A2_B02", 1),
    MC("Jan van Riebeeck led the first VOC settlement at the Cape in:", ["1652", "1488", "1820", "1910"], "1652",
      "Van Riebeeck established the VOC station in 1652.", "ERR_SSSP_G7H3A2_B03", 2),
    CLOZE("Former Company workers allowed to farm were called free ____.", ["burghers", "slaves", "sailors", "kings"], "burghers",
      "Free burghers were ex-VOC servants released to farm.", "ERR_SSSP_G7H3A2_B04", 2),
    TF("The Huguenots brought skills in farming and wine-making.", "True",
      "French Huguenot settlers added farming and wine-making skills.", "ERR_SSSP_G7H3A2_B05", 2),
    MC("The Cape was useful to the VOC because it lay on the route between Europe and:", ["the East (Asia)", "America", "Antarctica", "the Sahara"], "the East (Asia)",
      "The Cape was a halfway stop on the Europe-to-Asia sea route.", "ERR_SSSP_G7H3A2_B06", 2),
    MC("As free burghers farmed and expanded, they increasingly needed:", ["Land and labour", "Ships", "Gold mines", "Factories"], "Land and labour",
      "Farming expansion drove demand for land and labour, including enslaved people.", "ERR_SSSP_G7H3A2_B07", 3),
    TF("The Huguenots were fleeing religious persecution in France.", "True",
      "Huguenots were Protestants who fled persecution in Catholic France.", "ERR_SSSP_G7H3A2_B08", 2),
    MC("The VOC's main interest was:", ["Trade and profit", "Spreading democracy", "Exploring space", "Building schools"], "Trade and profit",
      "The VOC was a trading company focused on profit.", "ERR_SSSP_G7H3A2_B09", 1),
    CLOZE("The year ____ marks the start of permanent European settlement at the Cape.", ["1652", "1488", "1948", "1994"], "1652",
      "1652 began permanent Dutch settlement at the Cape.", "ERR_SSSP_G7H3A2_B10", 1),
    TF("The arrival of the VOC had no effect on the Khoikhoi.", "False",
      "VOC settlement increasingly took Khoikhoi land and disrupted their lives.", "ERR_SSSP_G7H3A2_B11", 2),
    MC("Free burghers selling produce to the VOC shows the settlement was becoming:", ["A farming colony, not just a supply stop", "A gold-mining town", "A university", "A naval base only"], "A farming colony, not just a supply stop",
      "Over time the Cape grew from a supply stop into a settled farming colony.", "ERR_SSSP_G7H3A2_B12", 3),
  ],
  // ── H3.A3 Slavery at the Cape ──
  "SSSP.G7.H3.A3": [
    MC("Enslaved people at the Cape were brought to do:", ["Farm and household labour", "Government work", "Trading on ships", "Teaching"], "Farm and household labour",
      "They were forced to do the hard labour of farms and homes.", "ERR_SSSP_G7H3A3_B01", 1),
    TF("Cape slaves came mainly from the Atlantic plantation trade.", "False",
      "Cape slaves came largely from the Indian Ocean world (East Africa, Madagascar, Asia).", "ERR_SSSP_G7H3A3_B02", 2),
    MC("The Afrikaans language was influenced by:", ["Enslaved people and many cultures at the Cape", "Only the Dutch", "Only the British", "Nobody"], "Enslaved people and many cultures at the Cape",
      "Afrikaans developed from the mixing of Dutch with the languages of enslaved and local people.", "ERR_SSSP_G7H3A3_B03", 3),
    CLOZE("Many enslaved people brought ____ to the Cape, now part of its heritage.", ["Islam", "the VOC", "gold", "ships"], "Islam",
      "Islam, brought by enslaved people from Asia, became part of Cape heritage.", "ERR_SSSP_G7H3A3_B04", 2),
    TF("Slave resistance at the Cape was punished harshly.", "True",
      "Resistance was met with severe punishment under the slave system.", "ERR_SSSP_G7H3A3_B05", 2),
    MC("Enslaved people at the Cape had:", ["No freedom and few rights", "Full citizenship", "Their own farms", "The vote"], "No freedom and few rights",
      "Enslaved people were owned and had no freedom or rights.", "ERR_SSSP_G7H3A3_B06", 1),
    MC("The legacy of Cape slavery includes:", ["Cultural, religious and language influences", "Gold mines", "Railways", "Nothing"], "Cultural, religious and language influences",
      "Cape slavery shaped religion (Islam), language (Afrikaans) and culture.", "ERR_SSSP_G7H3A3_B07", 2),
    TF("Slavery shaped the society and culture of the Cape deeply.", "True",
      "Slavery left deep marks on Cape society, culture, religion and language.", "ERR_SSSP_G7H3A3_B08", 2),
    MC("Where enslaved people came from shows the Cape was linked to:", ["The Indian Ocean world", "Only Europe", "Only America", "No other place"], "The Indian Ocean world",
      "Cape slavery connected it to East Africa, Madagascar and Asia.", "ERR_SSSP_G7H3A3_B09", 3),
    CLOZE("Enslaved people had no ____ to leave or choose their work.", ["freedom", "food", "names", "language"], "freedom",
      "Lack of freedom was the central reality of slavery.", "ERR_SSSP_G7H3A3_B10", 1),
    TF("The story of enslaved people is an important part of South African history.", "True",
      "The history of slavery is a vital part of understanding South Africa.", "ERR_SSSP_G7H3A3_B11", 1),
    MC("Studying slavery at the Cape helps us understand:", ["The roots of inequality and culture in South Africa", "Only the weather", "European history only", "Nothing"], "The roots of inequality and culture in South Africa",
      "Cape slavery helps explain later inequality and the country's mixed culture.", "ERR_SSSP_G7H3A3_B12", 3),
  ],
  // ── H3.A4 Expanding frontiers and dispossession ──
  "SSSP.G7.H3.A4": [
    MC("Trekboers were always on the move because they:", ["Sought new grazing land", "Worked in mines", "Sailed ships", "Built cities"], "Sought new grazing land",
      "Trekboers moved inland constantly to find grazing for their livestock.", "ERR_SSSP_G7H3A4_B01", 1),
    TF("As trekboers expanded, the Khoikhoi lost grazing land and independence.", "True",
      "The frontier's spread dispossessed the Khoikhoi of land and freedom.", "ERR_SSSP_G7H3A4_B02", 1),
    MC("A mission station aimed mainly to:", ["Spread Christianity", "Mine gold", "Build ships", "Trade enslaved people"], "Spread Christianity",
      "Mission stations spread Christianity and offered settled communities.", "ERR_SSSP_G7H3A4_B03", 2),
    CLOZE("Genadendal (1738) was the first ____ station in southern Africa.", ["mission", "police", "gold", "railway"], "mission",
      "Genadendal was the first mission station in southern Africa.", "ERR_SSSP_G7H3A4_B04", 2),
    TF("Dispossession means people being deprived of their land.", "True",
      "Dispossession is the loss of land — central to the frontier story.", "ERR_SSSP_G7H3A4_B05", 1),
    MC("Bleek and Lloyd helped preserve which culture's stories?", ["The San", "The Dutch", "The British", "The VOC"], "The San",
      "Bleek and Lloyd recorded San language and folklore.", "ERR_SSSP_G7H3A4_B06", 3),
    MC("Losing their land forced many Khoikhoi to become:", ["Servants for settlers", "Kings", "Sea captains", "Factory owners"], "Servants for settlers",
      "Dispossessed Khoikhoi often had to work as servants for trekboers.", "ERR_SSSP_G7H3A4_B07", 2),
    TF("The frontier was a place where different groups met, traded and clashed.", "True",
      "Frontiers were zones of contact — trade, mixing and conflict.", "ERR_SSSP_G7H3A4_B08", 2),
    MC("The expansion of settlement is an example of a long-term:", ["Cause of conflict over land", "Peace treaty", "Trade fair", "Sea voyage"], "Cause of conflict over land",
      "Expanding settlement created long-term conflict over land.", "ERR_SSSP_G7H3A4_B09", 3),
    CLOZE("Trekboers moved with their livestock, slaves and ____.", ["servants", "ships", "factories", "kings"], "servants",
      "Trekboers travelled with their livestock, enslaved people and servants.", "ERR_SSSP_G7H3A4_B10", 2),
    TF("The work of Bleek and Lloyd is a valuable record of San heritage.", "True",
      "Their records preserve precious San language and stories.", "ERR_SSSP_G7H3A4_B11", 2),
    MC("Dispossession of land had consequences that:", ["Lasted long into the future", "Ended immediately", "Helped indigenous people", "Were tiny"], "Lasted long into the future",
      "Land dispossession had deep, long-lasting consequences.", "ERR_SSSP_G7H3A4_B12", 2),
  ],
  // ── H4.A1 British arrival ──
  "SSSP.G7.H4.A1": [
    MC("The 1820 Settlers were immigrants from:", ["Britain", "the Netherlands", "France", "Portugal"], "Britain",
      "The 1820 Settlers were British immigrants brought to the eastern Cape.", "ERR_SSSP_G7H4A1_B01", 2),
    TF("British rule brought English language and laws to the Cape.", "True",
      "Under Britain, English language and British laws spread at the Cape.", "ERR_SSSP_G7H4A1_B02", 2),
    MC("More settlers on the frontier increased pressure on:", ["Land belonging to indigenous people", "The ocean", "Gold mines", "Factories"], "Land belonging to indigenous people",
      "More settlers meant more pressure on indigenous land, fuelling conflict.", "ERR_SSSP_G7H4A1_B03", 2),
    CLOZE("Britain took the Cape from the ____ in the early 1800s.", ["Dutch", "French", "Xhosa", "Zulu"], "Dutch",
      "Britain took control of the Cape from the Dutch.", "ERR_SSSP_G7H4A1_B04", 1),
    TF("The British placed 1820 settlers near the eastern frontier as a buffer.", "True",
      "The 1820 Settlers were placed on the eastern frontier partly as a buffer zone.", "ERR_SSSP_G7H4A1_B05", 3),
    MC("A 'frontier' is best described as:", ["A border zone where groups meet", "The middle of a city", "A type of ship", "A gold mine"], "A border zone where groups meet",
      "A frontier is the edge zone where different groups meet and often clash.", "ERR_SSSP_G7H4A1_B06", 2),
    MC("British control of the Cape was part of Britain's growing:", ["Empire", "desert", "navy school", "gold supply"], "Empire",
      "The Cape became part of the expanding British Empire.", "ERR_SSSP_G7H4A1_B07", 2),
    TF("Power at the Cape moved from the Dutch to the British.", "True",
      "Control of the Cape shifted from the Dutch VOC to Britain.", "ERR_SSSP_G7H4A1_B08", 1),
    MC("Expanding European settlement usually led to:", ["More conflict with indigenous people", "Lasting peace", "Fewer settlers", "No change"], "More conflict with indigenous people",
      "Expanding settlement increased conflict with indigenous communities.", "ERR_SSSP_G7H4A1_B09", 2),
    CLOZE("The early ____ century is when Britain expanded settlement at the Cape.", ["19th", "14th", "17th", "21st"], "19th",
      "British expansion at the Cape took off in the early 19th century.", "ERR_SSSP_G7H4A1_B10", 1),
    TF("British settlers had no impact on the eastern frontier.", "False",
      "British settlers added to land pressure and frontier conflict.", "ERR_SSSP_G7H4A1_B11", 1),
    MC("The arrival of the British is an example of:", ["A change in who held power", "A natural disaster", "A trade fair", "A peace treaty"], "A change in who held power",
      "It marked a change in colonial power at the Cape.", "ERR_SSSP_G7H4A1_B12", 2),
  ],
  // ── H4.A2 The eastern frontier ──
  "SSSP.G7.H4.A2": [
    MC("The frontier wars were fought over control of:", ["Land and cattle", "Gold mines", "Ships", "Factories"], "Land and cattle",
      "The frontier wars were struggles over land and cattle.", "ERR_SSSP_G7H4A2_B01", 1),
    TF("Chief Maqoma was a Xhosa leader who resisted the British.", "True",
      "Maqoma led Xhosa resistance against British expansion.", "ERR_SSSP_G7H4A2_B02", 1),
    MC("The Great Trek took the Boers away from the Cape to escape:", ["British rule", "the Xhosa", "gold", "the sea"], "British rule",
      "Many Boers trekked inland to escape British control.", "ERR_SSSP_G7H4A2_B03", 2),
    CLOZE("Slavery was abolished in the British Cape in ____.", ["1836", "1652", "1948", "1994"], "1836",
      "Britain abolished Cape slavery in 1836.", "ERR_SSSP_G7H4A2_B04", 2),
    TF("The abolition of slavery angered some Boer slave-owners.", "True",
      "Ending slavery angered Boer slave-owners, a factor behind the Great Trek.", "ERR_SSSP_G7H4A2_B05", 3),
    MC("Andries Stockenström was a colonial:", ["Official and soldier", "Xhosa chief", "Sea captain", "Gold miner"], "Official and soldier",
      "Stockenström was a colonial official and soldier on the eastern frontier.", "ERR_SSSP_G7H4A2_B06", 2),
    MC("The repeated wars on the eastern frontier show a relationship of:", ["Conflict over land", "Friendship", "Trade only", "Peace"], "Conflict over land",
      "The eastern frontier was defined by repeated conflict over land.", "ERR_SSSP_G7H4A2_B07", 2),
    TF("The Xhosa simply gave up their land without resistance.", "False",
      "The Xhosa resisted strongly in a series of frontier wars.", "ERR_SSSP_G7H4A2_B08", 1),
    MC("Inboekselings were people who were:", ["Bound into forced labour", "Free landowners", "Sea traders", "British officials"], "Bound into forced labour",
      "Inboekselings were people, often children, bound into forced labour.", "ERR_SSSP_G7H4A2_B09", 3),
    CLOZE("The ____ resisted British rule on the eastern frontier.", ["Xhosa", "Dutch", "French", "British"], "Xhosa",
      "The Xhosa led resistance on the eastern frontier.", "ERR_SSSP_G7H4A2_B10", 1),
    TF("The Great Trek moved Boers into the interior of southern Africa.", "True",
      "The Great Trek took Boers inland, away from the British Cape.", "ERR_SSSP_G7H4A2_B11", 1),
    MC("A 'case study' like Maqoma helps us:", ["Understand the bigger story through one example", "Ignore history", "Measure rainfall", "Draw maps"], "Understand the bigger story through one example",
      "A case study uses one example to illuminate the wider history.", "ERR_SSSP_G7H4A2_B12", 2),
  ],
  // ── H4.A3 The northern frontier ──
  "SSSP.G7.H4.A3": [
    MC("The Kora and Griqua often included:", ["People of mixed descent and runaway slaves", "British soldiers only", "Xhosa kings", "VOC directors"], "People of mixed descent and runaway slaves",
      "The Kora and Griqua were communities of mixed descent and runaway slaves.", "ERR_SSSP_G7H4A3_B01", 2),
    TF("The Tswana built large stone-walled towns on the northern frontier.", "True",
      "Tswana towns of stone, like Kaditshwene, were among the region's largest settlements.", "ERR_SSSP_G7H4A3_B02", 3),
    MC("Robert Moffat was based at which mission station?", ["Kuruman", "Genadendal", "Cape Town", "Sharpeville"], "Kuruman",
      "Moffat worked at the Kuruman mission station.", "ERR_SSSP_G7H4A3_B03", 2),
    CLOZE("The Tswana traded ivory, hides, iron and ____ on the northern frontier.", ["copper", "gold coins", "tea", "oil"], "copper",
      "The Tswana traded ivory, hides, iron and copper.", "ERR_SSSP_G7H4A3_B04", 2),
    TF("The northern frontier was shaped mainly by trade and missions.", "True",
      "Trade and missionary contact, more than war, shaped the northern frontier.", "ERR_SSSP_G7H4A3_B05", 2),
    MC("Some Tswana towns held thousands of people, showing they were:", ["Large, organised settlements", "Empty", "European cities", "Gold mines"], "Large, organised settlements",
      "Large Tswana towns prove these were big, organised African settlements.", "ERR_SSSP_G7H4A3_B06", 2),
    MC("Missionaries on the frontier often also acted as:", ["A link for trade and contact", "Soldiers only", "Kings", "Sea captains"], "A link for trade and contact",
      "Missionaries were often a point of trade and contact between groups.", "ERR_SSSP_G7H4A3_B07", 3),
    TF("Only Cape Town was a similar size to the largest Tswana towns at the time.", "True",
      "By 1820 only Cape Town rivalled the biggest Tswana towns in size.", "ERR_SSSP_G7H4A3_B08", 3),
    MC("Goods like tobacco and pack oxen came from the Cape to the:", ["Kora and Griqua", "British navy", "Xhosa kings only", "Dutch in Europe"], "Kora and Griqua",
      "The Kora and Griqua traded Cape goods like tobacco and oxen.", "ERR_SSSP_G7H4A3_B09", 2),
    CLOZE("Robert Moffat worked as a ____ at Kuruman.", ["missionary", "miner", "soldier", "trader"], "missionary",
      "Moffat was a missionary at Kuruman.", "ERR_SSSP_G7H4A3_B10", 1),
    TF("The northern frontier had no large African settlements.", "False",
      "Large Tswana towns showed the northern frontier had big African settlements.", "ERR_SSSP_G7H4A3_B11", 1),
    MC("Comparing the eastern and northern frontiers shows that contact could mean:", ["Both conflict and trade", "Only war", "Only peace", "Nothing"], "Both conflict and trade",
      "Frontiers involved both conflict and trade, in different mixes.", "ERR_SSSP_G7H4A3_B12", 2),
  ],

  // ── G1.A1 Local and street maps ──
  "SSSP.G7.G1.A1": [
    MC("A map symbol is:", ["A small picture standing for a real feature", "A type of road", "A grid number", "A scale bar"], "A small picture standing for a real feature",
      "Symbols are small pictures that stand for real features; the key explains them.", "ERR_SSSP_G7G1A1_B01", 1),
    TF("A street map usually shows the names of roads.", "True",
      "Street maps label roads so you can find and follow them.", "ERR_SSSP_G7G1A1_B02", 1),
    MC("To find a place quickly in a street guide you use the:", ["Index", "Scale bar", "North arrow", "Title only"], "Index",
      "The index lists places with grid references for quick finding.", "ERR_SSSP_G7G1A1_B03", 1),
    CLOZE("A grid divides a map into ____ to help locate places.", ["blocks", "colours", "roads", "symbols"], "blocks",
      "The grid splits the map into blocks for easy reference.", "ERR_SSSP_G7G1A1_B04", 1),
    TF("Local maps are useful for finding your way in your own area.", "True",
      "Local maps help you find places and routes in your own area.", "ERR_SSSP_G7G1A1_B05", 1),
    MC("Reading a grid reference, the first letter or number usually refers to the:", ["Column (across)", "Colour", "Title", "Scale"], "Column (across)",
      "You read across (column) first, then up (row).", "ERR_SSSP_G7G1A1_B06", 2),
    MC("Which is most useful for finding a friend's house in a suburb?", ["A local street map", "A world map", "A globe", "A weather map"], "A local street map",
      "A local street map shows the detail you need to find a house.", "ERR_SSSP_G7G1A1_B07", 1),
    TF("A map's key and grid work together to help you find places.", "True",
      "The key explains symbols and the grid locates them — together they help you read the map.", "ERR_SSSP_G7G1A1_B08", 2),
    MC("A place at grid reference B2 will be found:", ["In block B2 of the grid", "Outside the map", "At the title", "On the scale bar"], "In block B2 of the grid",
      "B2 points to the block where column B and row 2 meet.", "ERR_SSSP_G7G1A1_B09", 2),
    CLOZE("The list of places with their grid references is the map's ____.", ["index", "scale", "key", "border"], "index",
      "The index lists places and their grid references.", "ERR_SSSP_G7G1A1_B10", 1),
    TF("You can describe a route by naming the streets to follow on a map.", "True",
      "Following the streets on a map, you can describe a route clearly.", "ERR_SSSP_G7G1A1_B11", 1),
    MC("Street maps are an example of which kind of map?", ["Large-scale local maps", "World maps", "Climate maps", "Population maps"], "Large-scale local maps",
      "Street maps are large-scale maps of a small local area.", "ERR_SSSP_G7G1A1_B12", 2),
  ],
  // ── G1.A2 Sketch maps and routes ──
  "SSSP.G7.G1.A2": [
    MC("If you face north, south is:", ["Behind you", "On your right", "On your left", "Above you"], "Behind you",
      "Facing north, south is directly behind you.", "ERR_SSSP_G7G1A2_B01", 1),
    TF("Northeast is the direction between north and east.", "True",
      "Northeast lies halfway between north and east.", "ERR_SSSP_G7G1A2_B02", 2),
    MC("A sketch map is:", ["A simple hand-drawn map", "A satellite photo", "A globe", "A weather chart"], "A simple hand-drawn map",
      "A sketch map is a simple drawing showing the main features.", "ERR_SSSP_G7G1A2_B03", 1),
    CLOZE("On most maps, ____ is at the top.", ["north", "south", "east", "west"], "north",
      "By convention, north is at the top of most maps.", "ERR_SSSP_G7G1A2_B04", 1),
    TF("Estimating distances helps when giving someone directions.", "True",
      "Telling someone roughly how far to go makes directions clearer.", "ERR_SSSP_G7G1A2_B05", 2),
    MC("Which direction is between south and west?", ["Southwest", "Northeast", "Northwest", "Southeast"], "Southwest",
      "Southwest lies between south and west.", "ERR_SSSP_G7G1A2_B06", 2),
    MC("A key on a sketch map should explain the:", ["Symbols used", "Weather", "Price", "Date"], "Symbols used",
      "The key explains the symbols drawn on the map.", "ERR_SSSP_G7G1A2_B07", 1),
    TF("A sketch map does not need to be perfectly to scale to be useful.", "True",
      "Sketch maps show the main idea simply; they need not be exactly to scale.", "ERR_SSSP_G7G1A2_B08", 2),
    MC("To turn from facing east to facing north you turn:", ["Left (anti-clockwise)", "Right (clockwise)", "Around fully", "Down"], "Left (anti-clockwise)",
      "From east, turning left (anti-clockwise) faces you north.", "ERR_SSSP_G7G1A2_B09", 3),
    CLOZE("The four main directions are north, east, south and ____.", ["west", "up", "centre", "down"], "west",
      "North, east, south and west are the four cardinal directions.", "ERR_SSSP_G7G1A2_B10", 1),
    TF("A north arrow and a key make a sketch map easier to read.", "True",
      "A north arrow and key help others understand your sketch map.", "ERR_SSSP_G7G1A2_B11", 1),
    MC("Good route directions include:", ["Turns, directions and rough distances", "Only the weather", "Only the date", "Just a price"], "Turns, directions and rough distances",
      "Clear directions give turns, compass directions and rough distances.", "ERR_SSSP_G7G1A2_B12", 2),
  ],
  // ── G1.A3 Distance and scale ──
  "SSSP.G7.G1.A3": [
    MC("On a map with scale '1 cm = 5 km', 4 cm represents:", ["20 km", "9 km", "5 km", "1 km"], "20 km",
      "4 cm × 5 km per cm = 20 km.", "ERR_SSSP_G7G1A3_B01", 2),
    TF("A small-scale map shows a large area with less detail.", "True",
      "Small-scale maps cover large areas but show less detail.", "ERR_SSSP_G7G1A3_B02", 2),
    MC("A line scale (bar scale) is useful because you can:", ["Measure distances directly against it", "Tell the time", "See the weather", "Read names"], "Measure distances directly against it",
      "You measure a map distance and compare it to the line scale.", "ERR_SSSP_G7G1A3_B03", 1),
    CLOZE("Scale links map distance to ____ distance.", ["real", "imaginary", "no", "future"], "real",
      "Scale connects distance on the map to the real distance on the ground.", "ERR_SSSP_G7G1A3_B04", 1),
    TF("A direct route is a straight line between two points.", "True",
      "A direct route is the straight-line distance between two places.", "ERR_SSSP_G7G1A3_B05", 1),
    MC("To measure a curved river's length you would use:", ["A piece of string", "A straight ruler only", "A thermometer", "A clock"], "A piece of string",
      "String follows the curves, then is measured against the scale.", "ERR_SSSP_G7G1A3_B06", 2),
    MC("On scale '1 cm = 2 km', a road measuring 5 cm is really:", ["10 km", "5 km", "2 km", "7 km"], "10 km",
      "5 cm × 2 km per cm = 10 km.", "ERR_SSSP_G7G1A3_B07", 2),
    TF("Estimating then measuring helps you check your answer.", "True",
      "Estimating first lets you check whether your measured answer is sensible.", "ERR_SSSP_G7G1A3_B08", 1),
    MC("Which map would show more detail of one school?", ["A large-scale map", "A world map", "A globe", "A climate map"], "A large-scale map",
      "Large-scale maps show small areas in greater detail.", "ERR_SSSP_G7G1A3_B09", 2),
    CLOZE("A ____ scale draws a marked line you measure against.", ["line", "word", "ratio", "colour"], "line",
      "A line (bar) scale is a marked line for measuring distances.", "ERR_SSSP_G7G1A3_B10", 1),
    TF("Different maps can use different scales.", "True",
      "Maps use different scales depending on the area and detail needed.", "ERR_SSSP_G7G1A3_B11", 1),
    MC("Why is scale important on a map?", ["It lets you work out real distances", "It shows the weather", "It tells the time", "It names roads"], "It lets you work out real distances",
      "Without scale you could not work out real distances from a map.", "ERR_SSSP_G7G1A3_B12", 1),
  ],
  // ── G1.A4 Places in the news ──
  "SSSP.G7.G1.A4": [
    MC("Lines of latitude include the equator at:", ["0 degrees", "90 degrees", "180 degrees", "45 degrees"], "0 degrees",
      "The equator is the 0° line of latitude.", "ERR_SSSP_G7G1A4_B01", 2),
    TF("Longitude lines run from the North Pole to the South Pole.", "True",
      "Lines of longitude run north–south, between the poles.", "ERR_SSSP_G7G1A4_B02", 2),
    MC("A place north of the equator has a latitude that is:", ["North", "South", "East", "West"], "North",
      "Places north of the equator have northern latitudes.", "ERR_SSSP_G7G1A4_B03", 2),
    CLOZE("Latitude and longitude are measured in ____.", ["degrees", "metres", "litres", "hours"], "degrees",
      "Both are measured in degrees.", "ERR_SSSP_G7G1A4_B04", 1),
    TF("Knowing a place's latitude and longitude lets you find it on any world map.", "True",
      "Latitude and longitude together pinpoint a place anywhere on Earth.", "ERR_SSSP_G7G1A4_B05", 1),
    MC("Following news events on a map helps you understand:", ["Where and why things happen", "The price of bread", "The time of day", "Your homework"], "Where and why things happen",
      "Mapping the news builds understanding of where and why events occur.", "ERR_SSSP_G7G1A4_B06", 1),
    MC("The line of longitude at 0 degrees is the:", ["Prime Meridian", "Equator", "Tropic of Cancer", "Date line"], "Prime Meridian",
      "The Prime Meridian is the 0° line of longitude.", "ERR_SSSP_G7G1A4_B07", 3),
    TF("South Africa lies south of the equator.", "True",
      "South Africa is in the Southern Hemisphere, south of the equator.", "ERR_SSSP_G7G1A4_B08", 2),
    MC("A grid of latitude and longitude covers:", ["The whole globe", "Only one country", "Only the oceans", "Only cities"], "The whole globe",
      "Latitude and longitude form a grid over the entire globe.", "ERR_SSSP_G7G1A4_B09", 2),
    CLOZE("The ____ divides the Earth into Northern and Southern Hemispheres.", ["equator", "Prime Meridian", "date line", "axis"], "equator",
      "The equator separates the Northern and Southern Hemispheres.", "ERR_SSSP_G7G1A4_B10", 2),
    TF("A latitude of 0° and longitude of 0° is a single point on Earth.", "True",
      "Where the equator and Prime Meridian cross is one exact point.", "ERR_SSSP_G7G1A4_B11", 2),
    MC("Why are world maps useful for the news?", ["They put global events in their place", "They print the news", "They cool the planet", "They tell the time"], "They put global events in their place",
      "World maps help locate and make sense of global news events.", "ERR_SSSP_G7G1A4_B12", 1),
  ],
  // ── G2.A1 Structure of the earth ──
  "SSSP.G7.G2.A1": [
    MC("The mantle is the layer:", ["Between the crust and the core", "On the very outside", "At the exact centre", "Above the crust"], "Between the crust and the core",
      "The mantle is the thick layer between crust and core.", "ERR_SSSP_G7G2A1_B01", 1),
    TF("The crust is thin compared with the layers below it.", "True",
      "The crust is a thin skin compared with the much thicker mantle and core.", "ERR_SSSP_G7G2A1_B02", 1),
    MC("The core is described as:", ["Very hot", "Very cold", "Made of ice", "Empty"], "Very hot",
      "The core is the very hot centre of the Earth.", "ERR_SSSP_G7G2A1_B03", 1),
    CLOZE("The Earth's outer layer is the ____.", ["crust", "mantle", "core", "sky"], "crust",
      "The crust is the outer layer where we live.", "ERR_SSSP_G7G2A1_B04", 1),
    TF("Tectonic plates are pieces of the crust.", "True",
      "The crust is broken into moving tectonic plates.", "ERR_SSSP_G7G2A1_B05", 1),
    MC("Plate movements happen:", ["Very slowly over long periods", "In seconds", "Once a year exactly", "Never"], "Very slowly over long periods",
      "Plates move only a few centimetres a year — very slowly.", "ERR_SSSP_G7G2A1_B06", 2),
    MC("Earthquakes and volcanoes are linked to:", ["Plate movement", "Rainfall", "The moon", "Tides"], "Plate movement",
      "Both are caused by movements at plate boundaries.", "ERR_SSSP_G7G2A1_B07", 2),
    TF("The crust is the hottest layer of the Earth.", "False",
      "The core, not the crust, is the hottest layer.", "ERR_SSSP_G7G2A1_B08", 2),
    MC("Which order is correct from outside to centre?", ["Crust, mantle, core", "Core, mantle, crust", "Mantle, crust, core", "Crust, core, mantle"], "Crust, mantle, core",
      "Outside to centre: crust, mantle, core.", "ERR_SSSP_G7G2A1_B09", 1),
    CLOZE("Pieces of the crust that move are called tectonic ____.", ["plates", "rivers", "winds", "tides"], "plates",
      "The moving crustal pieces are tectonic plates.", "ERR_SSSP_G7G2A1_B10", 1),
    TF("Understanding the Earth's layers helps explain volcanoes and earthquakes.", "True",
      "Knowing about plates and layers explains why volcanoes and earthquakes occur.", "ERR_SSSP_G7G2A1_B11", 2),
    MC("Most volcanic and earthquake activity occurs:", ["At plate boundaries", "In the middle of plates", "In the sky", "In rivers"], "At plate boundaries",
      "Activity concentrates at the edges where plates meet.", "ERR_SSSP_G7G2A1_B12", 2),
  ],
  // ── G2.A2 Volcanoes ──
  "SSSP.G7.G2.A2": [
    MC("When a volcano erupts, lava is:", ["Molten rock pouring out", "Frozen water", "Solid metal", "Cold mud"], "Molten rock pouring out",
      "Lava is molten rock that flows out during an eruption.", "ERR_SSSP_G7G2A2_B01", 1),
    TF("Volcanic ash can be thrown high into the air during an eruption.", "True",
      "Eruptions can blast ash high into the atmosphere.", "ERR_SSSP_G7G2A2_B02", 1),
    MC("Volcanoes mostly form:", ["Along plate boundaries", "In the middle of flat plains", "In cities", "Underwater only"], "Along plate boundaries",
      "Volcanoes mostly form where tectonic plates meet.", "ERR_SSSP_G7G2A2_B03", 2),
    CLOZE("Molten rock underground is called ____.", ["magma", "lava", "ash", "soil"], "magma",
      "Underground it is magma; once erupted it becomes lava.", "ERR_SSSP_G7G2A2_B04", 2),
    TF("Volcanic eruptions can destroy homes and farmland nearby.", "True",
      "Lava and ash can bury and destroy nearby homes and farmland.", "ERR_SSSP_G7G2A2_B05", 1),
    MC("A map of the world's volcanoes shows them:", ["In lines along plate edges", "Spread evenly everywhere", "Only at the poles", "Only in deserts"], "In lines along plate edges",
      "Volcanoes line up along the plate boundaries.", "ERR_SSSP_G7G2A2_B06", 2),
    MC("Why do volcanoes form where plates meet?", ["Magma can rise through gaps and weaknesses", "Because of rain", "Because of the moon", "Because of cities"], "Magma can rise through gaps and weaknesses",
      "At plate edges, magma can rise through cracks and erupt.", "ERR_SSSP_G7G2A2_B07", 3),
    TF("Volcanic soil can be very fertile for farming.", "True",
      "Weathered volcanic ash makes rich, fertile soil for farming.", "ERR_SSSP_G7G2A2_B08", 2),
    MC("An advantage that draws people to live near volcanoes is:", ["Fertile soil", "More earthquakes", "Colder weather", "Less water"], "Fertile soil",
      "Fertile volcanic soil attracts farmers despite the risk.", "ERR_SSSP_G7G2A2_B09", 3),
    CLOZE("A volcano is an opening where molten rock reaches the ____.", ["surface", "core", "sky", "sea floor only"], "surface",
      "A volcano is where magma reaches the Earth's surface.", "ERR_SSSP_G7G2A2_B10", 1),
    TF("Volcanoes never occur near earthquakes.", "False",
      "Volcanoes and earthquakes often occur together along plate boundaries.", "ERR_SSSP_G7G2A2_B11", 1),
    MC("Studying volcano locations helps people to:", ["Understand and prepare for the hazard", "Cause eruptions", "Stop plates moving", "Predict elections"], "Understand and prepare for the hazard",
      "Knowing where volcanoes are helps communities prepare.", "ERR_SSSP_G7G2A2_B12", 2),
  ],
  // ── G2.A3 Earthquakes ──
  "SSSP.G7.G2.A3": [
    MC("Earthquakes happen when plates:", ["Suddenly move or slip", "Stop existing", "Get rained on", "Freeze"], "Suddenly move or slip",
      "A sudden slip of plates releases energy as an earthquake.", "ERR_SSSP_G7G2A3_B01", 1),
    TF("Strong earthquakes can damage roads, bridges and buildings.", "True",
      "Earthquakes can destroy infrastructure like roads, bridges and buildings.", "ERR_SSSP_G7G2A3_B02", 1),
    MC("After an earthquake, people may be displaced, meaning they:", ["Lose their homes and must move", "Win prizes", "Get richer", "Stay exactly where they are"], "Lose their homes and must move",
      "Displacement means losing homes and having to move away.", "ERR_SSSP_G7G2A3_B03", 2),
    CLOZE("An undersea earthquake may trigger a giant wave called a ____.", ["tsunami", "drought", "breeze", "tide"], "tsunami",
      "Undersea quakes can cause tsunamis.", "ERR_SSSP_G7G2A3_B04", 2),
    TF("Stronger buildings can reduce earthquake damage.", "True",
      "Buildings designed to resist shaking reduce damage and save lives.", "ERR_SSSP_G7G2A3_B05", 2),
    MC("Communities near plate boundaries are at higher earthquake risk because:", ["That is where most earthquakes happen", "They have more rain", "They are richer", "They are far from the sea"], "That is where most earthquakes happen",
      "Most earthquakes occur at plate boundaries, raising local risk.", "ERR_SSSP_G7G2A3_B06", 2),
    MC("An earthquake drill helps people to:", ["Know what to do and stay safer", "Cause an earthquake", "Predict the weather", "Build plates"], "Know what to do and stay safer",
      "Practising drills helps people respond safely when a quake strikes.", "ERR_SSSP_G7G2A3_B07", 2),
    TF("Nothing can be done to prepare for earthquakes.", "False",
      "Strong buildings, drills and planning all help communities prepare.", "ERR_SSSP_G7G2A3_B08", 1),
    MC("Earthquakes can cause fires when they:", ["Break gas pipes and power lines", "Bring heavy rain", "Cool the ground", "Plant trees"], "Break gas pipes and power lines",
      "Broken gas and power lines can spark fires after a quake.", "ERR_SSSP_G7G2A3_B09", 3),
    CLOZE("Earthquakes are caused by movement in the Earth's ____.", ["crust", "sky", "oceans only", "clouds"], "crust",
      "Movement in the crust at plate boundaries causes earthquakes.", "ERR_SSSP_G7G2A3_B10", 1),
    TF("Disease can spread after an earthquake if water and sanitation are damaged.", "True",
      "Damaged water and sanitation after a quake can spread disease.", "ERR_SSSP_G7G2A3_B11", 2),
    MC("Why do some earthquakes cause more deaths than others of similar size?", ["Differences in buildings and preparation", "The day of the week", "The colour of the soil", "The price of food"], "Differences in buildings and preparation",
      "Weaker buildings and poor preparation lead to more deaths.", "ERR_SSSP_G7G2A3_B12", 3),
  ],
  // ── G2.A4 Floods ──
  "SSSP.G7.G2.A4": [
    MC("A flood happens when:", ["Water covers land that is usually dry", "The land dries out", "A volcano erupts", "An earthquake stops"], "Water covers land that is usually dry",
      "A flood is water covering normally dry land.", "ERR_SSSP_G7G2A4_B01", 1),
    TF("Cutting down forests can increase the risk of flooding.", "True",
      "Without trees to soak up and slow water, flooding becomes more likely.", "ERR_SSSP_G7G2A4_B02", 2),
    MC("A floodplain is:", ["Low, flat land near a river that floods", "A high mountain", "A desert", "A city centre"], "Low, flat land near a river that floods",
      "Floodplains are low areas beside rivers that flood easily.", "ERR_SSSP_G7G2A4_B03", 2),
    CLOZE("Early warning systems help reduce the ____ of floods.", ["impact", "rainfall", "rivers", "soil"], "impact",
      "Warnings help people prepare, reducing flood impact.", "ERR_SSSP_G7G2A4_B04", 2),
    TF("Floods can damage crops and cause food shortages.", "True",
      "Floods can ruin crops, leading to food shortages.", "ERR_SSSP_G7G2A4_B05", 1),
    MC("Why do some communities suffer more from floods?", ["They live on floodplains or have weak defences", "They have more sun", "They are far from rivers", "They have more schools"], "They live on floodplains or have weak defences",
      "Living on floodplains with weak defences raises flood risk.", "ERR_SSSP_G7G2A4_B06", 2),
    MC("Good drainage helps prevent floods by:", ["Carrying water away quickly", "Holding water on the land", "Adding more rain", "Removing all rivers"], "Carrying water away quickly",
      "Drainage channels carry water away, reducing flooding.", "ERR_SSSP_G7G2A4_B07", 2),
    TF("Dirty flood water can make people sick.", "True",
      "Flood water often carries dirt and disease that can make people sick.", "ERR_SSSP_G7G2A4_B08", 1),
    MC("A South African flood case study should be:", ["A real flood that happened in South Africa", "An imaginary flood", "A flood in Europe", "A volcano"], "A real flood that happened in South Africa",
      "CAPS asks for a real South African flood case study.", "ERR_SSSP_G7G2A4_B09", 2),
    CLOZE("Planting trees and keeping vegetation can ____ flood risk.", ["lower", "raise", "remove rivers from", "double"], "lower",
      "Vegetation soaks up and slows water, lowering flood risk.", "ERR_SSSP_G7G2A4_B10", 2),
    TF("People can do nothing to reduce flood damage.", "False",
      "Warnings, drainage, vegetation and wise building all reduce flood damage.", "ERR_SSSP_G7G2A4_B11", 1),
    MC("Floods and droughts are both examples of:", ["Natural hazards linked to water", "Volcanoes", "Earthquakes", "Trade routes"], "Natural hazards linked to water",
      "Both floods and droughts are water-related natural hazards.", "ERR_SSSP_G7G2A4_B12", 2),
  ],
  // ── G3.A1 Population concepts ──
  "SSSP.G7.G3.A1": [
    MC("If births are fewer than deaths, the population will:", ["Shrink", "Grow", "Stay the same", "Double"], "Shrink",
      "Fewer births than deaths means the population shrinks.", "ERR_SSSP_G7G3A1_B01", 2),
    TF("Life expectancy tends to be higher where health care is good.", "True",
      "Good health care raises life expectancy.", "ERR_SSSP_G7G3A1_B02", 2),
    MC("Infant mortality measures the death of:", ["Babies under one year old", "Old people", "Teenagers", "Adults"], "Babies under one year old",
      "Infant mortality counts deaths of babies under one year.", "ERR_SSSP_G7G3A1_B03", 1),
    CLOZE("Birth rate and death rate are measured per ____ people.", ["1 000", "10", "5", "100 000"], "1 000",
      "Both are measured per 1 000 people per year.", "ERR_SSSP_G7G3A1_B04", 2),
    TF("Population can also change because of people moving in or out (migration).", "True",
      "Migration changes population, alongside births and deaths.", "ERR_SSSP_G7G3A1_B05", 2),
    MC("A country with birth rate 12 and death rate 12 has natural growth of:", ["Zero", "24", "144", "12"], "Zero",
      "12 births minus 12 deaths = zero natural growth.", "ERR_SSSP_G7G3A1_B06", 2),
    MC("Life expectancy of 80 means people can expect to live to about:", ["80 years", "8 years", "800 years", "18 years"], "80 years",
      "Life expectancy of 80 means an average lifespan of about 80 years.", "ERR_SSSP_G7G3A1_B07", 1),
    TF("Higher death rates always mean a falling population.", "False",
      "A high birth rate can outweigh a high death rate, so population may still grow.", "ERR_SSSP_G7G3A1_B08", 3),
    MC("Population growth rate tells us:", ["How fast a population is changing", "The map scale", "The weather", "The time"], "How fast a population is changing",
      "Growth rate shows how fast a population is rising or falling.", "ERR_SSSP_G7G3A1_B09", 1),
    CLOZE("The average number of years people live is called life ____.", ["expectancy", "rate", "scale", "index"], "expectancy",
      "Life expectancy is the average lifespan.", "ERR_SSSP_G7G3A1_B10", 1),
    TF("These measures help us compare different countries' populations.", "True",
      "Rates like birth, death and life expectancy let us compare populations.", "ERR_SSSP_G7G3A1_B11", 2),
    MC("A very high infant mortality rate is a sign of:", ["Poor health conditions", "Wealth", "Good schools", "Low birth rate"], "Poor health conditions",
      "High infant mortality usually signals poor health conditions.", "ERR_SSSP_G7G3A1_B12", 2),
  ],
  // ── G3.A2 Factors affecting birth and death rates ──
  "SSSP.G7.G3.A2": [
    MC("Clean water and sanitation tend to:", ["Lower the death rate", "Raise the death rate", "Stop births", "Cause floods"], "Lower the death rate",
      "Clean water and sanitation reduce disease and lower death rates.", "ERR_SSSP_G7G3A2_B01", 2),
    TF("The Black Death was a pandemic that raised death rates in the past.", "True",
      "The Black Death killed huge numbers, sharply raising death rates.", "ERR_SSSP_G7G3A2_B02", 2),
    MC("In wealthier societies, families often have:", ["Fewer children", "Many more children", "No families", "Only sons"], "Fewer children",
      "Wealthier families often choose to have fewer children.", "ERR_SSSP_G7G3A2_B03", 3),
    CLOZE("HIV/AIDS, malaria and ____ are diseases that affect death rates.", ["tuberculosis", "sunshine", "wealth", "education"], "tuberculosis",
      "Diseases like TB, malaria and HIV/AIDS raise death rates.", "ERR_SSSP_G7G3A2_B04", 2),
    TF("Government policy can encourage or discourage having children.", "True",
      "Policies (like China's former one-child policy) can change the birth rate.", "ERR_SSSP_G7G3A2_B05", 2),
    MC("War usually affects population by:", ["Raising the death rate", "Lowering the death rate", "Stopping migration", "Adding rainfall"], "Raising the death rate",
      "War causes deaths and disrupts food and health, raising death rates.", "ERR_SSSP_G7G3A2_B06", 2),
    MC("Improved medicine usually:", ["Lowers the death rate", "Raises the death rate", "Stops all births", "Causes earthquakes"], "Lowers the death rate",
      "Better medicine keeps people alive longer, lowering death rates.", "ERR_SSSP_G7G3A2_B07", 1),
    TF("Beliefs and attitudes can influence how many children families want.", "True",
      "Cultural and religious beliefs shape family size and the birth rate.", "ERR_SSSP_G7G3A2_B08", 2),
    MC("Why are birth and death rates sometimes linked?", ["High child death can lead families to have more children", "They never connect", "Births cause deaths", "Deaths cause births directly"], "High child death can lead families to have more children",
      "Where child death is common, families may have more children — the rates interact.", "ERR_SSSP_G7G3A2_B09", 3),
    CLOZE("A widespread disease outbreak is called a ____.", ["pandemic", "drought", "harvest", "migration"], "pandemic",
      "A pandemic is a widespread disease outbreak that raises death rates.", "ERR_SSSP_G7G3A2_B10", 2),
    TF("Economic conditions can influence both birth and death rates.", "True",
      "Wealth and poverty affect both how many children families have and how long people live.", "ERR_SSSP_G7G3A2_B11", 2),
    MC("Family planning programmes mainly affect the:", ["Birth rate", "Volcano rate", "Tide rate", "Map scale"], "Birth rate",
      "Family planning influences how many children are born — the birth rate.", "ERR_SSSP_G7G3A2_B12", 2),
  ],
  // ── G3.A3 World population growth ──
  "SSSP.G7.G3.A3": [
    MC("For thousands of years, world population grew:", ["Very slowly", "Extremely fast", "Not at all", "In reverse"], "Very slowly",
      "Population grew slowly for most of history before recent rapid growth.", "ERR_SSSP_G7G3A3_B01", 2),
    TF("Better farming meant more food and supported more people.", "True",
      "Increased food production allowed the population to grow.", "ERR_SSSP_G7G3A3_B02", 1),
    MC("Vaccines and medicine helped population grow by:", ["Reducing deaths from disease", "Raising the birth rate only", "Cooling the planet", "Causing floods"], "Reducing deaths from disease",
      "Controlling disease reduced deaths, helping population grow.", "ERR_SSSP_G7G3A3_B03", 2),
    CLOZE("A line graph shows population ____ over time.", ["change", "colour", "scale", "names"], "change",
      "A line graph shows how population changes over time.", "ERR_SSSP_G7G3A3_B04", 1),
    TF("World population is now in the billions.", "True",
      "World population has grown into the billions in recent times.", "ERR_SSSP_G7G3A3_B05", 1),
    MC("On a population graph, a steeper line means:", ["Faster growth", "Slower growth", "No change", "A falling population"], "Faster growth",
      "A steeper upward line means population is growing faster.", "ERR_SSSP_G7G3A3_B06", 2),
    MC("Refrigeration helped population growth by:", ["Reducing food spoilage", "Raising deaths", "Cooling the Earth", "Stopping farming"], "Reducing food spoilage",
      "Refrigeration kept food fresh longer, improving nutrition.", "ERR_SSSP_G7G3A3_B07", 2),
    TF("Improved sanitation helped reduce the spread of disease.", "True",
      "Clean sanitation reduced disease, lowering deaths and aiding growth.", "ERR_SSSP_G7G3A3_B08", 2),
    MC("The sharp rise in population is mostly due to:", ["Falling death rates", "Rising death rates", "Fewer births", "Volcanoes"], "Falling death rates",
      "Rapid growth came mainly from falling death rates as health improved.", "ERR_SSSP_G7G3A3_B09", 3),
    CLOZE("Increased food ____ supported a growing population.", ["production", "spoilage", "shortage", "prices"], "production",
      "More food production supported more people.", "ERR_SSSP_G7G3A3_B10", 1),
    TF("Reading graphs is an important geography skill.", "True",
      "Interpreting graphs is a key skill for studying population and other data.", "ERR_SSSP_G7G3A3_B11", 1),
    MC("Scientific progress affected population mainly by:", ["Helping people live longer", "Making the Earth bigger", "Stopping the seasons", "Adding more land"], "Helping people live longer",
      "Science (medicine, sanitation) helped people live longer, growing the population.", "ERR_SSSP_G7G3A3_B12", 2),
  ],
  // ── G4.A1 Natural resources ──
  "SSSP.G7.G4.A1": [
    MC("Which is NOT a natural resource?", ["A plastic toy", "Water", "Soil", "Forests"], "A plastic toy",
      "A plastic toy is made by people; water, soil and forests come from nature.", "ERR_SSSP_G7G4A1_B01", 1),
    TF("Fresh water is a vital natural resource.", "True",
      "Fresh water is one of the most important natural resources.", "ERR_SSSP_G7G4A1_B02", 1),
    MC("Soil is a natural resource because it:", ["Supports plants and farming", "Is man-made", "Comes from factories", "Is a kind of metal"], "Supports plants and farming",
      "Soil is a natural resource essential for growing food.", "ERR_SSSP_G7G4A1_B03", 1),
    CLOZE("Using a resource wastefully and harmfully is called ____ it.", ["abusing", "conserving", "mapping", "counting"], "abusing",
      "Abusing a resource means using it harmfully or wastefully.", "ERR_SSSP_G7G4A1_B04", 2),
    TF("Over-fishing can reduce fish populations badly.", "True",
      "Catching fish faster than they breed reduces their populations.", "ERR_SSSP_G7G4A1_B05", 2),
    MC("Forests provide resources such as:", ["Wood and habitat for animals", "Plastic", "Steel", "Petrol"], "Wood and habitat for animals",
      "Forests give wood and shelter for wildlife — natural resources.", "ERR_SSSP_G7G4A1_B06", 1),
    MC("Wise use of natural resources means:", ["Not damaging or wasting them", "Using them all up fast", "Ignoring them", "Polluting them"], "Not damaging or wasting them",
      "Wise use protects resources from damage and waste.", "ERR_SSSP_G7G4A1_B07", 2),
    TF("Air is a natural resource that can be polluted.", "True",
      "Air is a natural resource and can be harmed by pollution.", "ERR_SSSP_G7G4A1_B08", 1),
    MC("Marine life is found in the:", ["Sea", "Desert", "Factory", "City"], "Sea",
      "Marine life lives in the sea and is a natural resource.", "ERR_SSSP_G7G4A1_B09", 1),
    CLOZE("Water, air, soil and forests are all examples of ____ resources.", ["natural", "factory", "imported", "plastic"], "natural",
      "These all come from nature, making them natural resources.", "ERR_SSSP_G7G4A1_B10", 1),
    TF("Natural resources will last forever no matter how we use them.", "False",
      "Many resources can be damaged or used up if not used wisely.", "ERR_SSSP_G7G4A1_B11", 1),
    MC("Why is it important to look after natural resources?", ["So they stay healthy and available", "To use them up faster", "To make them disappear", "Because they are useless"], "So they stay healthy and available",
      "Looking after resources keeps them available for everyone, now and later.", "ERR_SSSP_G7G4A1_B12", 1),
  ],
  // ── G4.A2 Management and conservation ──
  "SSSP.G7.G4.A2": [
    MC("A national park is an example of a:", ["Conservation area", "Factory", "Shopping mall", "Gold mine"], "Conservation area",
      "National parks protect nature and are conservation areas.", "ERR_SSSP_G7G4A2_B01", 1),
    TF("Eco-tourism can provide income while protecting nature.", "True",
      "Eco-tourism brings income in ways that support conservation.", "ERR_SSSP_G7G4A2_B02", 2),
    MC("A marine reserve protects:", ["Sea life and habitats", "City streets", "Gold mines", "Factories"], "Sea life and habitats",
      "Marine reserves protect ocean life and habitats.", "ERR_SSSP_G7G4A2_B03", 2),
    CLOZE("Protecting and carefully managing nature is called ____.", ["conservation", "pollution", "mining", "trade"], "conservation",
      "Conservation is the careful protection and management of nature.", "ERR_SSSP_G7G4A2_B04", 1),
    TF("Conservation areas can help endangered animals survive.", "True",
      "Protected areas give endangered animals a safer place to survive.", "ERR_SSSP_G7G4A2_B05", 1),
    MC("Community conservation projects can benefit local people by:", ["Creating jobs and income", "Removing all wildlife", "Polluting rivers", "Closing schools"], "Creating jobs and income",
      "Community projects can create jobs while protecting nature.", "ERR_SSSP_G7G4A2_B06", 2),
    MC("One reason for conservation is to:", ["Protect resources for the future", "Use everything now", "Pollute more", "Remove all parks"], "Protect resources for the future",
      "Conservation keeps resources healthy for future generations.", "ERR_SSSP_G7G4A2_B07", 1),
    TF("Tourists visiting nature reserves can support conservation through fees.", "True",
      "Entry fees from eco-tourism can fund conservation work.", "ERR_SSSP_G7G4A2_B08", 2),
    MC("Why might fishing be limited in a marine reserve?", ["To let fish populations recover", "To catch more fish", "To pollute the sea", "To raise sea levels"], "To let fish populations recover",
      "Limiting fishing lets fish breed and recover.", "ERR_SSSP_G7G4A2_B09", 2),
    CLOZE("Tourism that respects and protects nature is called ____-tourism.", ["eco", "mass", "space", "city"], "eco",
      "Eco-tourism is nature-respecting tourism.", "ERR_SSSP_G7G4A2_B10", 1),
    TF("Conservation and using resources can be balanced through careful management.", "True",
      "Careful management lets people use resources while conserving them.", "ERR_SSSP_G7G4A2_B11", 2),
    MC("Conservation areas need a clear:", ["Purpose and management plan", "Shopping centre", "Gold mine", "Factory"], "Purpose and management plan",
      "Conservation areas work best with a clear purpose and management plan.", "ERR_SSSP_G7G4A2_B12", 3),
  ],
  // ── G4.A3 Water in South Africa ──
  "SSSP.G7.G4.A3": [
    MC("South Africa's water supply is best described as:", ["Scarce and needing careful use", "Unlimited", "Mostly wasted with no harm", "Only for industry"], "Scarce and needing careful use",
      "South Africa is dry, so water is scarce and must be used carefully.", "ERR_SSSP_G7G4A3_B01", 1),
    TF("A catchment area collects rainwater that feeds rivers.", "True",
      "Catchment areas gather rainfall that flows into rivers.", "ERR_SSSP_G7G4A3_B02", 2),
    MC("Wetlands are valuable because they:", ["Store and clean water and support wildlife", "Waste water", "Cause droughts", "Have no use"], "Store and clean water and support wildlife",
      "Wetlands store and filter water and shelter wildlife.", "ERR_SSSP_G7G4A3_B03", 2),
    CLOZE("Farming, industry and ____ users all use South Africa's water.", ["domestic", "ocean", "foreign", "imaginary"], "domestic",
      "Agricultural, industrial and domestic (home) users all share the water.", "ERR_SSSP_G7G4A3_B04", 1),
    TF("Saving water at home helps the whole country's supply.", "True",
      "Every household saving water helps the scarce national supply.", "ERR_SSSP_G7G4A3_B05", 1),
    MC("Healthy rivers depend on caring for their:", ["Catchment areas", "Factories", "Roads", "Shops"], "Catchment areas",
      "Caring for catchment areas keeps rivers healthy.", "ERR_SSSP_G7G4A3_B06", 2),
    MC("Why are wetlands disappearing a problem?", ["We lose their water storage and cleaning", "We gain more water", "Rivers get cleaner", "Nothing happens"], "We lose their water storage and cleaning",
      "Losing wetlands means losing their water storage and natural cleaning.", "ERR_SSSP_G7G4A3_B07", 3),
    TF("Agriculture is usually the biggest user of South Africa's water.", "True",
      "Farming is generally the largest user of the country's water.", "ERR_SSSP_G7G4A3_B08", 2),
    MC("Responsible water use means:", ["Not wasting water", "Using as much as possible", "Polluting rivers", "Draining wetlands"], "Not wasting water",
      "Responsible use means avoiding waste and pollution.", "ERR_SSSP_G7G4A3_B09", 1),
    CLOZE("In a dry country, water must be ____ and shared carefully.", ["conserved", "wasted", "polluted", "ignored"], "conserved",
      "In a dry country water must be conserved and shared wisely.", "ERR_SSSP_G7G4A3_B10", 1),
    TF("Industry uses no water in South Africa.", "False",
      "Industry is one of the three main users of water, with farming and homes.", "ERR_SSSP_G7G4A3_B11", 1),
    MC("Conserving wetlands and catchments helps ensure:", ["A reliable water supply for the future", "More droughts", "Less clean water", "More pollution"], "A reliable water supply for the future",
      "Protecting wetlands and catchments secures future water supply.", "ERR_SSSP_G7G4A3_B12", 2),
  ],
};

export default G7B;
