// ─── Social Sciences SP — Grade 8 authored question pools ─────────────────────
// CAPS Grade 8: History — Industrial Revolution · Mineral Revolution · Scramble
// for Africa · World War I. Geography — Maps & globes · Climate regions ·
// Settlement & urbanisation · Transport & trade. Tap-only; refs auto-assigned.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8 = {
  // ─── H1 · Term 1 — The Industrial Revolution ───────────────────────────────
  "SSSP.G8.H1.A1": [
    MC("The Industrial Revolution was a change from making goods by hand to making them:",
      ["In factories using machines", "In small home workshops only", "On farms only", "Not at all"], "In factories using machines",
      "The Industrial Revolution moved production from hand and home into factories using machines.", "ERR_SSSP_G8H1A1_DEF", 1),
    TF("Before the Industrial Revolution, most people worked on farms or in small home industries.", "True",
      "The earlier economy was based on farming and cottage (home) industries.", "ERR_SSSP_G8H1A1_BEFORE", 1),
    CLOZE("As factories grew, many people moved to cities — a process called ____.",
      ["urbanisation", "irrigation", "migration north", "globalisation"], "urbanisation",
      "Urbanisation is the growth of cities as people move in for factory work.", "ERR_SSSP_G8H1A1_URBAN", 2),
    MC("What were living conditions like for many working-class people during the Industrial Revolution?",
      ["Overcrowded housing and poverty", "Large comfortable homes", "Free luxury flats", "No work at all"], "Overcrowded housing and poverty",
      "Workers often lived in overcrowded, poor housing in the fast-growing industrial cities.", "ERR_SSSP_G8H1A1_LIVING", 2),
    TF("Children worked long hours in mills and mines during the Industrial Revolution.", "True",
      "Child labour was common and dangerous in the factories and mines of this period.", "ERR_SSSP_G8H1A1_CHILD", 1),
    MC("Workers formed trade unions mainly to:",
      ["Improve their wages and working conditions", "Build more factories", "Lower their own pay", "Close the schools"], "Improve their wages and working conditions",
      "Trade unions organised workers to push for better pay and conditions.", "ERR_SSSP_G8H1A1_UNION", 2),
    MC("The Luddites were workers who protested by:",
      ["Breaking the new machines", "Building railways", "Mining diamonds", "Joining the navy"], "Breaking the new machines",
      "The Luddites smashed machines they blamed for taking their jobs.", "ERR_SSSP_G8H1A1_LUDDITE", 3),
    TF("The Industrial Revolution increased the wealth and power of Britain.", "True",
      "Industrialisation made Britain richer and more powerful, including as a colonial power.", "ERR_SSSP_G8H1A1_WEALTH", 1),
    MC("A 'cottage industry' means goods were made:",
      ["At home by hand", "In huge factories", "By robots", "Underground"], "At home by hand",
      "Cottage industry = small-scale making of goods at home by hand, before factories.", "ERR_SSSP_G8H1A1_COTTAGE", 2),
  ],
  "SSSP.G8.H1.A2": [
    MC("Indentured labourers were brought from India to work on sugar plantations in which British colony?",
      ["Natal", "Cape Town", "Kimberley", "London"], "Natal",
      "Indian indentured labourers were brought to Natal to work the sugar plantations.", "ERR_SSSP_G8H1A2_NATAL", 1),
    TF("Indenture was a fixed-term work contract, often under very harsh conditions.", "True",
      "Indenture bound workers to years of labour under harsh conditions — not slavery, but very hard.", "ERR_SSSP_G8H1A2_INDENTURE", 2),
    MC("Why was labour imported to Natal's sugar plantations?",
      ["The independent Zulu kingdom meant local labour was hard to force", "There were no people in Natal", "Sugar grew itself", "The British liked travel"], "The independent Zulu kingdom meant local labour was hard to force",
      "With the Zulu kingdom still independent, planters imported indentured Indian labour for the cane fields.", "ERR_SSSP_G8H1A2_WHY", 3),
    CLOZE("Workers bound by a fixed-term contract to labour for years were called ____ labourers.",
      ["indentured", "free", "skilled", "migrant"], "indentured",
      "Indentured labourers worked under binding contracts for a set number of years.", "ERR_SSSP_G8H1A2_CLOZE", 1),
    MC("'Passenger Indians' (from 1869) were Indians who came to South Africa:",
      ["Paying their own way, often as traders", "As soldiers", "As indentured workers only", "By force"], "Paying their own way, often as traders",
      "Passenger Indians paid their own passage and often came as traders, unlike indentured labourers.", "ERR_SSSP_G8H1A2_PASSENGER", 3),
    TF("There was a strong demand for sugar in Britain at this time.", "True",
      "British demand for sugar drove the expansion of Natal's sugar plantations.", "ERR_SSSP_G8H1A2_SUGAR", 1),
    MC("India at this time was itself ruled as a colony of which country?",
      ["Britain", "France", "Portugal", "the Netherlands"], "Britain",
      "India was a British colony, which is why labour could be moved within the empire.", "ERR_SSSP_G8H1A2_INDIA", 2),
    TF("Indentured labourers lived and worked in comfortable, easy conditions.", "False",
      "Indentured labourers faced harsh living and working conditions on the plantations.", "ERR_SSSP_G8H1A2_HARSH", 1),
  ],
  "SSSP.G8.H1.A3": [
    MC("Diamonds were discovered in which South African town in 1867?",
      ["Kimberley", "Johannesburg", "Cape Town", "Durban"], "Kimberley",
      "The 1867 diamond discovery at Kimberley began South Africa's Mineral Revolution.", "ERR_SSSP_G8H1A3_KIMBERLEY", 1),
    TF("Diamonds are valuable partly because they are rare and hard.", "True",
      "Diamonds are rare and the hardest natural material, which makes them valuable.", "ERR_SSSP_G8H1A3_VALUE", 1),
    MC("As diamond diggings got deeper, what happened to small individual claimholders?",
      ["Many were squeezed out as big companies took over", "They all became rich kings", "They moved to Britain", "Nothing changed"], "Many were squeezed out as big companies took over",
      "Deep mining needed money and machines, so big companies bought out small claimholders.", "ERR_SSSP_G8H1A3_CLAIMS", 2),
    MC("Which company, formed by Cecil John Rhodes, came to dominate diamond mining?",
      ["De Beers Consolidated Mines", "De Beers Sugar Company", "The VOC", "Anglo Bank"], "De Beers Consolidated Mines",
      "Rhodes's De Beers Consolidated Mines gained a near-monopoly over diamond mining.", "ERR_SSSP_G8H1A3_DEBEERS", 2),
    CLOZE("When one company controls the supply of a product, this is called a ____.",
      ["monopoly", "democracy", "union", "colony"], "monopoly",
      "A monopoly is control of a market by a single company — as De Beers had with diamonds.", "ERR_SSSP_G8H1A3_MONOPOLY", 2),
    TF("Cecil John Rhodes and Barney Barnato were important figures in diamond mining.", "True",
      "Rhodes and Barnato were leading rivals and then partners in the diamond industry.", "ERR_SSSP_G8H1A3_RHODES", 2),
    MC("Controlling the supply of diamonds allowed companies to control the:",
      ["Price of diamonds", "Weather", "Tides", "Population of Britain"], "Price of diamonds",
      "By limiting supply, the diamond monopoly kept prices high.", "ERR_SSSP_G8H1A3_PRICE", 2),
    MC("Black claimholders at Kimberley generally:",
      ["Lost their claims and rights over time", "Took over the mines", "Became company directors", "Were left alone"], "Lost their claims and rights over time",
      "Black claimholders were squeezed out and lost rights as control tightened.", "ERR_SSSP_G8H1A3_BLACK", 3),
    TF("Diamond wealth increased Britain's interest in controlling South Africa.", "True",
      "New diamond wealth pulled Britain deeper into controlling the region.", "ERR_SSSP_G8H1A3_INTEREST", 1),
  ],

  // ─── H2 · Term 2 — The Mineral Revolution in South Africa ──────────────────
  "SSSP.G8.H2.A1": [
    MC("The closed compound system was used to:",
      ["House and control black mineworkers", "Store diamonds", "Train teachers", "Build ships"], "House and control black mineworkers",
      "Closed compounds housed black migrant workers under tight control near the mines.", "ERR_SSSP_G8H2A1_COMPOUND", 2),
    TF("Mining created a demand for cheap, controllable labour.", "True",
      "Mines needed large amounts of cheap labour, which shaped harsh labour controls.", "ERR_SSSP_G8H2A1_LABOUR", 1),
    MC("African kingdoms like the Pedi and Zulu lost their independence in which period?",
      ["The late 1870s", "The 1650s", "The 1990s", "The 1400s"], "The late 1870s",
      "By 1879 the Zulu and Pedi were defeated, opening the way for greater labour control.", "ERR_SSSP_G8H2A1_KINGDOMS", 2),
    CLOZE("Workers who travel from their homes to work in the mines and return are called ____ workers.",
      ["migrant", "indentured", "free", "skilled"], "migrant",
      "Migrant workers left rural homes to work in the mines and returned periodically.", "ERR_SSSP_G8H2A1_MIGRANT", 2),
    TF("Defeating independent African kingdoms made it easier to force people into mine labour.", "True",
      "Once kingdoms lost independence, men were more easily pushed into migrant mine labour.", "ERR_SSSP_G8H2A1_DEFEAT", 3),
    MC("Land dispossession affected African societies by:",
      ["Forcing many men to seek work in the mines", "Making them all wealthy", "Giving them factories", "Ending all farming"], "Forcing many men to seek work in the mines",
      "Losing land pushed many African men into wage labour on the mines.", "ERR_SSSP_G8H2A1_DISPOSSESS", 3),
    MC("The Xhosa were defeated in 1878 as part of:",
      ["The expansion of colonial control", "The Industrial Revolution in Britain", "World War I", "The Great Trek"], "The expansion of colonial control",
      "The 1878 defeat of the Xhosa was part of growing colonial and labour control.", "ERR_SSSP_G8H2A1_XHOSA", 2),
    TF("Increasing control over black workers was a key feature of the Mineral Revolution.", "True",
      "Tighter control over black labour — compounds, passes, migrancy — defined the era.", "ERR_SSSP_G8H2A1_CONTROL", 1),
  ],
  "SSSP.G8.H2.A2": [
    MC("Deep-level gold was discovered on the Witwatersrand in which year?",
      ["1886", "1652", "1948", "1994"], "1886",
      "The 1886 gold discovery on the Witwatersrand transformed South Africa.", "ERR_SSSP_G8H2A2_1886", 1),
    TF("Deep-level gold mining was expensive and needed large companies.", "True",
      "Mining deep gold required huge investment, so big companies and the Chamber of Mines formed.", "ERR_SSSP_G8H2A2_DEEP", 2),
    MC("The wealthy mine owners on the Witwatersrand were known as the:",
      ["Randlords", "Trekboers", "Burghers", "Luddites"], "Randlords",
      "The Randlords were the rich mine-owners of the Witwatersrand gold fields.", "ERR_SSSP_G8H2A2_RANDLORDS", 2),
    CLOZE("The city of ____ grew rapidly around the Witwatersrand gold mines.",
      ["Johannesburg", "Cape Town", "Durban", "Kimberley"], "Johannesburg",
      "Johannesburg sprang up and boomed because of the Witwatersrand gold.", "ERR_SSSP_G8H2A2_JOBURG", 1),
    TF("Conditions for workers deep underground in the gold mines were dangerous.", "True",
      "Underground gold mining was hot, deep and dangerous for the workers.", "ERR_SSSP_G8H2A2_COND", 1),
    MC("The migrant labour system meant that many mineworkers:",
      ["Left families in rural reserves and lived in compounds", "Owned the mines", "Lived in mansions", "Worked from home"], "Left families in rural reserves and lived in compounds",
      "Men migrated to the mines, living in compounds while families stayed in the reserves.", "ERR_SSSP_G8H2A2_MIGRANT", 2),
    MC("The migrant labour system increased the burden on women in the reserves because:",
      ["They had to run households and farms alone", "They became Randlords", "They moved to the mines too", "They stopped working"], "They had to run households and farms alone",
      "With men away at the mines, women carried the work of households and farms in the reserves.", "ERR_SSSP_G8H2A2_WOMEN", 3),
    TF("The Chamber of Mines was formed by mine owners to organise the gold-mining industry.", "True",
      "Owners formed the Chamber of Mines to coordinate the industry, including labour and wages.", "ERR_SSSP_G8H2A2_CHAMBER", 2),
    MC("Why is gold valuable?",
      ["It is rare, attractive and does not rust", "It is very common", "It rusts quickly", "It grows on trees"], "It is rare, attractive and does not rust",
      "Gold is rare, beautiful and does not corrode, which makes it precious.", "ERR_SSSP_G8H2A2_VALUE", 1),
  ],
  "SSSP.G8.H2.A3": [
    MC("The Mineral Revolution is called a 'turning point' because it:",
      ["Reshaped power, land and labour in South Africa", "Had no lasting effect", "Only affected Britain", "Lasted one week"], "Reshaped power, land and labour in South Africa",
      "Minerals transformed South Africa's economy, power and labour patterns for the 20th century.", "ERR_SSSP_G8H2A3_TURNING", 2),
    MC("The Union of South Africa was formed in which year?",
      ["1910", "1867", "1886", "1948"], "1910",
      "The Union of South Africa was created in 1910, joining the colonies under one government.", "ERR_SSSP_G8H2A3_UNION", 1),
    TF("The South African Native National Congress (SANNC), later the ANC, was formed in 1912.", "True",
      "The SANNC was founded in 1912 and was later renamed the ANC.", "ERR_SSSP_G8H2A3_SANNC", 2),
    MC("The 1913 Land Act mainly did what?",
      ["Limited the land black South Africans could own", "Gave everyone equal land", "Ended all farming", "Created the gold mines"], "Limited the land black South Africans could own",
      "The 1913 Land Act restricted black South Africans to a small share of the land.", "ERR_SSSP_G8H2A3_LAND", 2),
    CLOZE("The ____ of South Africa in 1910 joined the colonies under one government.",
      ["Union", "Republic", "Empire", "Federation"], "Union",
      "The 1910 Union united the four colonies into one country under British dominion.", "ERR_SSSP_G8H2A3_CLOZE", 1),
    {
      question: "Put these events in the correct order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Diamonds discovered at Kimberley (1867)" },
        { id: "b", text: "Gold discovered on the Witwatersrand (1886)" },
        { id: "c", text: "Union of South Africa (1910)" },
        { id: "d", text: "Natives Land Act (1913)" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Diamonds (1867) → gold (1886) → Union (1910) → Land Act (1913): the chain of the Mineral Revolution.", error_signals: ["ERR_SSSP_G8H2A3_SEQ"], difficulty: 3,
    },
    TF("The Mineral Revolution shifted the balance of power away from African kingdoms.", "True",
      "Mining wealth and colonial defeats shifted power away from independent African kingdoms.", "ERR_SSSP_G8H2A3_POWER", 2),
    MC("The Bambatha Rebellion of 1906 was:",
      ["An armed uprising against colonial rule and taxes", "A gold-mining company", "A British law", "A trade union"], "An armed uprising against colonial rule and taxes",
      "The 1906 Bambatha Rebellion was a revolt against colonial taxes and control.", "ERR_SSSP_G8H2A3_BAMBATHA", 3),
  ],

  // ─── H3 · Term 3 — The Scramble for Africa ─────────────────────────────────
  "SSSP.G8.H3.A1": [
    MC("At the Berlin Conference of 1884, European powers:",
      ["Divided Africa among themselves", "Gave Africa independence", "Ended all trade", "Built African railways for free"], "Divided Africa among themselves",
      "At Berlin (1884) European powers carved up Africa between them, with no African input.", "ERR_SSSP_G8H3A1_BERLIN", 1),
    TF("African leaders were NOT invited to the Berlin Conference.", "True",
      "Africans were not consulted as Europeans divided the continent at Berlin.", "ERR_SSSP_G8H3A1_NOTINVITED", 1),
    MC("Which advantage helped Europeans colonise Africa quickly?",
      ["Better weapons and technology", "Larger African armies", "African support for colonisation", "Magic"], "Better weapons and technology",
      "Superior weapons, transport and medicine let Europeans colonise Africa rapidly.", "ERR_SSSP_G8H3A1_WEAPONS", 2),
    CLOZE("The rush by European powers to take over African land is called the ____ for Africa.",
      ["Scramble", "Union", "Trek", "Charter"], "Scramble",
      "The 'Scramble for Africa' was the rapid European race to colonise the continent.", "ERR_SSSP_G8H3A1_CLOZE", 1),
    MC("Which was a cause of European colonisation of Africa?",
      ["Wanting raw materials and markets", "A shortage of land in Africa", "African requests to be colonised", "A lack of European interest"], "Wanting raw materials and markets",
      "Europeans wanted Africa's raw materials, markets and prestige — key causes of colonisation.", "ERR_SSSP_G8H3A1_CAUSE", 2),
    TF("Colonisation changed the borders and rulers of most of Africa.", "True",
      "Colonisation imposed new borders and European rulers across nearly all of Africa.", "ERR_SSSP_G8H3A1_BORDERS", 1),
    MC("By the early 1900s, most of Africa was:",
      ["Under European colonial control", "Fully independent", "Uninhabited", "Ruled by one African king"], "Under European colonial control",
      "By the early 20th century almost all of Africa was under European control.", "ERR_SSSP_G8H3A1_RESULT", 2),
    TF("European colonisation of Africa was part of a wider global process of European expansion.", "True",
      "The Scramble for Africa was part of Europe's worldwide colonial expansion.", "ERR_SSSP_G8H3A1_GLOBAL", 2),
  ],
  "SSSP.G8.H3.A2": [
    MC("The Ashanti kingdom was located in which part of Africa?",
      ["West Africa (modern Ghana)", "South Africa", "Egypt", "Kenya"], "West Africa (modern Ghana)",
      "The Ashanti kingdom was in West Africa, in what is now Ghana.", "ERR_SSSP_G8H3A2_WHERE", 1),
    TF("The British colonised the Ashanti area as the 'Gold Coast'.", "True",
      "The British took over the Ashanti region and ruled it as the Gold Coast colony.", "ERR_SSSP_G8H3A2_GOLDCOAST", 1),
    MC("Before colonisation, the Ashanti had early contact with Europeans mainly as:",
      ["Traders", "Tourists", "Soldiers only", "Missionaries only"], "Traders",
      "The Ashanti first met Europeans through trade along the West African coast.", "ERR_SSSP_G8H3A2_TRADE", 2),
    CLOZE("Today the land of the old Ashanti kingdom is the independent country of ____.",
      ["Ghana", "Nigeria", "Mali", "Egypt"], "Ghana",
      "The former Gold Coast became the independent country of Ghana.", "ERR_SSSP_G8H3A2_GHANA", 2),
    TF("The Ashanti resisted British colonisation.", "True",
      "The Ashanti fought to defend their kingdom against British takeover.", "ERR_SSSP_G8H3A2_RESIST", 2),
    MC("Why is the Ashanti kingdom used as a case study of the Scramble for Africa?",
      ["It shows in detail how one African kingdom was colonised", "It was never colonised", "It colonised Europe", "It had no history"], "It shows in detail how one African kingdom was colonised",
      "The Ashanti are a detailed example of the wider process of colonisation.", "ERR_SSSP_G8H3A2_CASE", 2),
    MC("A result of colonisation for the Ashanti was:",
      ["Loss of independence to Britain", "Becoming the rulers of Britain", "Gaining gold mines in Europe", "No change"], "Loss of independence to Britain",
      "Colonisation cost the Ashanti their independence to the British Empire.", "ERR_SSSP_G8H3A2_RESULT", 2),
  ],

  // ─── H4 · Term 4 — World War I (1914–1918) ─────────────────────────────────
  "SSSP.G8.H4.A1": [
    MC("What event was the immediate spark for World War I?",
      ["The assassination of Archduke Franz Ferdinand at Sarajevo", "The sinking of the Titanic", "The Berlin Conference", "The discovery of gold"], "The assassination of Archduke Franz Ferdinand at Sarajevo",
      "The 1914 assassination at Sarajevo was the spark that set off World War I.", "ERR_SSSP_G8H4A1_SPARK", 1),
    TF("Long-term causes of World War I included nationalism, empires and alliances.", "True",
      "Nationalism, rival empires, arms races and alliances built up tension before the war.", "ERR_SSSP_G8H4A1_LONGTERM", 2),
    MC("In World War I, Britain and its allies were known as the:",
      ["Allied Powers", "Central Powers", "Axis Powers", "Trekboers"], "Allied Powers",
      "Britain's side was the Allied Powers, opposed by the Central Powers.", "ERR_SSSP_G8H4A1_ALLIES", 2),
    CLOZE("Strong pride in and loyalty to one's nation is called ____.",
      ["nationalism", "socialism", "colonialism", "urbanisation"], "nationalism",
      "Nationalism — intense national pride and rivalry — was a major cause of the war.", "ERR_SSSP_G8H4A1_NATIONALISM", 2),
    TF("A system of alliances meant a conflict between two countries could pull in many others.", "True",
      "Alliances meant an attack on one nation dragged its partners into war too.", "ERR_SSSP_G8H4A1_ALLIANCE", 2),
    MC("The competition between countries to build up armies and navies is called an:",
      ["Arms race", "Trade fair", "Election", "Alliance"], "Arms race",
      "The arms race saw nations build ever-bigger militaries before the war.", "ERR_SSSP_G8H4A1_ARMS", 2),
    MC("Germany and its partners in World War I were called the:",
      ["Central Powers", "Allied Powers", "Randlords", "Huguenots"], "Central Powers",
      "Germany's side was the Central Powers.", "ERR_SSSP_G8H4A1_CENTRAL", 1),
    TF("World War I broke out in 1914.", "True",
      "World War I began in 1914 and ended in 1918.", "ERR_SSSP_G8H4A1_1914", 1),
  ],
  "SSSP.G8.H4.A2": [
    MC("Soldiers on the Western Front mostly fought from:",
      ["Trenches", "Tall towers", "Ships only", "Aeroplanes only"], "Trenches",
      "The Western Front was dominated by brutal trench warfare.", "ERR_SSSP_G8H4A2_TRENCH", 1),
    TF("Conscription means forcing men by law to join the army.", "True",
      "Conscription is compulsory military service required by law.", "ERR_SSSP_G8H4A2_CONSCRIPT", 2),
    MC("Propaganda during the war was used to:",
      ["Persuade people to support the war effort", "Predict the weather", "Build trenches", "Mine gold"], "Persuade people to support the war effort",
      "Governments used propaganda to win public support and encourage enlistment.", "ERR_SSSP_G8H4A2_PROPAGANDA", 2),
    CLOZE("The South African ship the ____ sank in 1917 with great loss of life.",
      ["Mendi", "Amistad", "Titanic", "Beagle"], "Mendi",
      "The sinking of the SS Mendi in 1917 killed many South African servicemen.", "ERR_SSSP_G8H4A2_MENDI", 2),
    MC("The Battle of Delville Wood (1916) involved soldiers from:",
      ["South Africa", "Only Britain", "Only France", "Australia only"], "South Africa",
      "South African troops fought and died at Delville Wood in 1916.", "ERR_SSSP_G8H4A2_DELVILLE", 2),
    TF("A conscientious objector is someone who refuses to fight for reasons of conscience.", "True",
      "Conscientious objectors refuse to fight because of their beliefs or conscience.", "ERR_SSSP_G8H4A2_OBJECTOR", 3),
    MC("Trench warfare often led to:",
      ["Long, deadly stalemates with little ground gained", "Quick, easy victories", "No casualties", "Comfortable conditions"], "Long, deadly stalemates with little ground gained",
      "Trench warfare produced long, deadly deadlocks with huge casualties for little gain.", "ERR_SSSP_G8H4A2_STALEMATE", 2),
    TF("South Africans took part in World War I.", "True",
      "South Africa was involved in World War I, at Delville Wood and through the Mendi, among others.", "ERR_SSSP_G8H4A2_SA", 1),
  ],
  "SSSP.G8.H4.A3": [
    MC("During World War I, the role of women in Britain changed as they:",
      ["Took jobs in factories and other workplaces", "Stopped working entirely", "Became generals", "Left the country"], "Took jobs in factories and other workplaces",
      "With men at the front, women filled factory and other jobs in large numbers.", "ERR_SSSP_G8H4A3_WORK", 1),
    TF("Emmeline Pankhurst campaigned for women's right to vote in Britain.", "True",
      "Pankhurst was a leader of the campaign for women's suffrage (the vote).", "ERR_SSSP_G8H4A3_PANKHURST", 2),
    CLOZE("The campaign for women's right to vote is called the ____ movement.",
      ["suffrage", "trench", "trade union", "temperance"], "suffrage",
      "The suffrage movement fought for women's right to vote.", "ERR_SSSP_G8H4A3_SUFFRAGE", 2),
    MC("Why did women's wartime work strengthen the case for giving them the vote?",
      ["It showed women's important contribution to society", "It proved women could not work", "It had nothing to do with voting", "It lowered wages"], "It showed women's important contribution to society",
      "Women's vital wartime work strengthened arguments that they deserved the vote.", "ERR_SSSP_G8H4A3_CASE", 3),
    TF("Before World War I, women in Britain could already all vote.", "False",
      "Women could not yet vote on equal terms; that came partly as a result of the war years.", "ERR_SSSP_G8H4A3_BEFORE", 2),
    MC("The changing role of women during the war is an example of:",
      ["Social change caused by war", "A military battle", "A peace treaty", "A trade route"], "Social change caused by war",
      "War changed society, including the roles and rights of women.", "ERR_SSSP_G8H4A3_CHANGE", 2),
    TF("Women worked in munitions (weapons) factories during the war.", "True",
      "Many women worked in munitions and other factories to support the war effort.", "ERR_SSSP_G8H4A3_MUNITIONS", 1),
  ],
  "SSSP.G8.H4.A4": [
    MC("The treaty that ended World War I and punished Germany was the Treaty of:",
      ["Versailles", "Vereeniging", "Rome", "Berlin"], "Versailles",
      "The 1919 Treaty of Versailles ended the war and imposed harsh terms on Germany.", "ERR_SSSP_G8H4A4_VERSAILLES", 1),
    TF("The Treaty of Versailles punished Germany harshly.", "True",
      "Versailles blamed Germany and imposed heavy punishments — land, money and military limits.", "ERR_SSSP_G8H4A4_HARSH", 1),
    MC("In what year was the Treaty of Versailles signed?",
      ["1919", "1914", "1886", "1945"], "1919",
      "The Treaty of Versailles was signed in 1919, the year after the war ended.", "ERR_SSSP_G8H4A4_1919", 2),
    CLOZE("The harsh terms of the Treaty of ____ would help cause resentment in Germany later.",
      ["Versailles", "Union", "Berlin", "Natal"], "Versailles",
      "German anger at the Versailles terms fed later instability — picked up again in Grade 9.", "ERR_SSSP_G8H4A4_CLOZE", 2),
    TF("Germany was defeated in World War I.", "True",
      "Germany and the Central Powers were defeated, leading to the Treaty of Versailles.", "ERR_SSSP_G8H4A4_DEFEAT", 1),
    MC("Why is the Treaty of Versailles important for later history?",
      ["German resentment of it helped lead to World War II", "It ended all wars forever", "It created the gold mines", "It had no effect"], "German resentment of it helped lead to World War II",
      "Resentment at Versailles contributed to the rise of Nazism and World War II.", "ERR_SSSP_G8H4A4_LATER", 3),
    TF("The Treaty of Versailles will be studied again in Grade 9.", "True",
      "The treaty is revisited in Grade 9 when studying the rise of Nazi Germany.", "ERR_SSSP_G8H4A4_GR9", 1),
  ],

  // ─── G1 · Term 1 — Maps & globes [image items deferred] ────────────────────
  "SSSP.G8.G1.A1": [
    MC("Latitude and longitude are measured in:",
      ["Degrees and minutes", "Metres and litres", "Hours only", "Kilograms"], "Degrees and minutes",
      "Latitude and longitude are measured in degrees (°) and minutes (').", "ERR_SSSP_G8G1A1_DEGREES", 1),
    TF("A ratio scale like 1:50 000 means 1 unit on the map equals 50 000 of the same units on the ground.", "True",
      "1:50 000 means 1 cm on the map represents 50 000 cm (500 m) in real life.", "ERR_SSSP_G8G1A1_RATIO", 2),
    MC("The atlas index helps you to:",
      ["Find the page and location of a place", "Measure rainfall", "Tell the time", "Draw graphs"], "Find the page and location of a place",
      "An atlas index lists places with the page and grid to find them.", "ERR_SSSP_G8G1A1_INDEX", 1),
    CLOZE("A scale written as numbers like 1:50 000 is called a ____ scale.",
      ["ratio", "line", "word", "colour"], "ratio",
      "A ratio (number) scale expresses the relationship as 1 : a number.", "ERR_SSSP_G8G1A1_CLOZE", 2),
    MC("On a 1:100 000 map, 1 cm represents how much real distance?",
      ["1 km", "100 km", "10 m", "1 m"], "1 km",
      "1:100 000 means 1 cm = 100 000 cm = 1 km.", "ERR_SSSP_G8G1A1_CALC", 3),
    TF("Different maps in an atlas can use different scales (world, regional, local).", "True",
      "Atlases use small scales for the world and larger scales for local areas.", "ERR_SSSP_G8G1A1_SCALES", 2),
    MC("Which scale would show the MOST detail of a small area?",
      ["A large-scale map (e.g. 1:10 000)", "A world map", "A 1:1 000 000 map", "A globe"], "A large-scale map (e.g. 1:10 000)",
      "Large-scale maps (small area) show the most detail.", "ERR_SSSP_G8G1A1_DETAIL", 3),
  ],
  "SSSP.G8.G1.A2": [
    MC("Day and night are caused by the earth:",
      ["Rotating (spinning) on its axis", "Orbiting the sun", "Being tilted", "Getting bigger"], "Rotating (spinning) on its axis",
      "The earth's daily spin on its axis causes day and night.", "ERR_SSSP_G8G1A2_DAYNIGHT", 1),
    TF("The seasons are caused by the tilt of the earth's axis as it orbits the sun.", "True",
      "The earth's tilt, combined with its orbit, gives us the seasons.", "ERR_SSSP_G8G1A2_SEASONS", 2),
    MC("The world is divided into time ____ because different places see the sun at different times.",
      ["zones", "oceans", "deserts", "plates"], "zones",
      "Time zones account for the sun reaching different longitudes at different times.", "ERR_SSSP_G8G1A2_ZONES", 2),
    CLOZE("The earth spins once on its ____ roughly every 24 hours.",
      ["axis", "orbit", "equator", "surface"], "axis",
      "One full spin on its axis takes about 24 hours — a day.", "ERR_SSSP_G8G1A2_AXIS", 1),
    TF("When it is day on one side of the earth, it is night on the opposite side.", "True",
      "As the earth spins, one side faces the sun (day) while the other faces away (night).", "ERR_SSSP_G8G1A2_OPPOSITE", 1),
    MC("An equinox is a time when:",
      ["Day and night are roughly equal in length", "It is always dark", "The earth stops spinning", "There is no sun"], "Day and night are roughly equal in length",
      "At an equinox, day and night are about equal everywhere.", "ERR_SSSP_G8G1A2_EQUINOX", 3),
    MC("Which causes the seasons — the earth's spin or its tilt and orbit?",
      ["Its tilt and orbit around the sun", "Its daily spin", "Its size", "Its colour"], "Its tilt and orbit around the sun",
      "Spin gives day/night; tilt + orbit give the seasons.", "ERR_SSSP_G8G1A2_WHICH", 2),
    TF("South Africa has its own standard time.", "True",
      "South African Standard Time is the country's official time zone.", "ERR_SSSP_G8G1A2_SAST", 1),
  ],
  "SSSP.G8.G1.A3": [
    MC("Satellite images are pictures of the earth taken from:",
      ["Space", "Under the ocean", "Inside caves", "Aeroplanes on the runway"], "Space",
      "Satellite images are taken from satellites in space orbiting the earth.", "ERR_SSSP_G8G1A3_SPACE", 1),
    TF("Satellite images can show water, vegetation, land use and cloud patterns.", "True",
      "Satellites reveal features like water, plants, land use and clouds.", "ERR_SSSP_G8G1A3_SHOW", 1),
    MC("Which of these is a real-world use of satellite images?",
      ["Tracking weather and clouds", "Cooling the planet", "Causing earthquakes", "Printing money"], "Tracking weather and clouds",
      "Satellite images are used to track weather, land use, disasters and more.", "ERR_SSSP_G8G1A3_USE", 2),
    CLOZE("Green areas on a satellite image usually show ____.",
      ["vegetation", "water", "deserts", "cities"], "vegetation",
      "Green typically marks vegetation; blue water; brown/grey bare land or cities.", "ERR_SSSP_G8G1A3_GREEN", 2),
    TF("A tool like Google Earth uses satellite images.", "True",
      "Google Earth displays satellite imagery of the whole planet.", "ERR_SSSP_G8G1A3_GOOGLE", 1),
    MC("Satellite images are useful because they:",
      ["Show large areas of the earth from above", "Only show one street", "Cannot show clouds", "Show the earth's core"], "Show large areas of the earth from above",
      "Satellites give a wide overhead view of large areas, useful for many purposes.", "ERR_SSSP_G8G1A3_WIDE", 2),
  ],

  // ─── G2 · Term 2 — Climate regions ─────────────────────────────────────────
  "SSSP.G8.G2.A1": [
    MC("Which factor means places near the equator are generally hotter?",
      ["Latitude (distance from the equator)", "Distance from a river", "The day of the week", "Population size"], "Latitude (distance from the equator)",
      "Latitude is a key control: places near the equator receive more direct sun and are hotter.", "ERR_SSSP_G8G2A1_LAT", 1),
    TF("Places at a higher altitude (height) are generally cooler.", "True",
      "Temperature drops as you go higher, so high-altitude places are cooler.", "ERR_SSSP_G8G2A1_ALT", 1),
    MC("Being close to the sea tends to make a place's climate:",
      ["Milder (cooler summers, warmer winters)", "More extreme", "Have no seasons", "Hotter every day"], "Milder (cooler summers, warmer winters)",
      "The sea moderates temperatures, giving coastal places milder climates.", "ERR_SSSP_G8G2A1_SEA", 2),
    CLOZE("____ is the height of the land above sea level, and it affects temperature.",
      ["Altitude", "Latitude", "Longitude", "Humidity"], "Altitude",
      "Altitude (height above sea level) lowers temperature as it increases.", "ERR_SSSP_G8G2A1_CLOZE", 1),
    TF("Ocean currents can influence the temperature and rainfall of nearby coasts.", "True",
      "Warm and cold ocean currents affect the temperature and rainfall of coasts.", "ERR_SSSP_G8G2A1_CURRENTS", 2),
    MC("Mountains can affect rainfall by:",
      ["Forcing air to rise, cool and drop rain", "Heating the whole country", "Stopping the seasons", "Lowering latitude"], "Forcing air to rise, cool and drop rain",
      "Air forced up over mountains cools and releases rain on the windward side (relief rainfall).", "ERR_SSSP_G8G2A1_MOUNTAIN", 3),
    {
      question: "Sort each factor by what it most directly controls.",
      input_type: "sort-buckets",
      buckets: [{ id: "temp", label: "Affects temperature" }, { id: "both", label: "Affects rainfall too" }],
      items: [
        { id: "i1", text: "Altitude (height above sea level)", correct_bucket: "temp" },
        { id: "i2", text: "Latitude (distance from equator)", correct_bucket: "temp" },
        { id: "i3", text: "Mountains (relief)", correct_bucket: "both" },
        { id: "i4", text: "Ocean currents", correct_bucket: "both" },
      ],
      expected: "Altitude and latitude mainly affect temperature; mountains and currents affect rainfall too.",
      pass_threshold: 0.75,
      memo: "All five factors shape temperature; mountains and currents strongly shape rainfall as well.", error_signals: ["ERR_SSSP_G8G2A1_SORT"], difficulty: 3,
    },
  ],
  "SSSP.G8.G2.A2": [
    MC("Why is the coast of Durban generally warmer in winter than inland Johannesburg?",
      ["Durban is at the coast and lower altitude", "Durban is further from the equator", "Johannesburg is at the sea", "Durban has more factories"], "Durban is at the coast and lower altitude",
      "Coastal, low-lying Durban stays milder than high-altitude, inland Johannesburg.", "ERR_SSSP_G8G2A2_DURBAN", 3),
    TF("South Africa's interior plateau is high in altitude, which keeps it cooler.", "True",
      "The high interior plateau's altitude keeps it cooler than the warm coasts.", "ERR_SSSP_G8G2A2_PLATEAU", 2),
    MC("The west coast of South Africa is influenced by a cold ocean current called the:",
      ["Benguela current", "Agulhas current", "Gulf Stream", "Mozambique current"], "Benguela current",
      "The cold Benguela current cools the west coast and keeps it dry.", "ERR_SSSP_G8G2A2_BENGUELA", 3),
    CLOZE("The east coast of South Africa is warmed by the ____ current.",
      ["Agulhas", "Benguela", "Arctic", "Pacific"], "Agulhas",
      "The warm Agulhas current warms the east coast and brings moisture.", "ERR_SSSP_G8G2A2_AGULHAS", 3),
    TF("Different parts of South Africa have different climates.", "True",
      "South Africa has varied climates because the controlling factors differ across the country.", "ERR_SSSP_G8G2A2_VARIED", 1),
    MC("Upington, far inland in the west, is known for being:",
      ["Hot and dry", "Cold and wet", "Mild and rainy all year", "Snowy"], "Hot and dry",
      "Inland western places like Upington are hot and dry.", "ERR_SSSP_G8G2A2_UPINGTON", 2),
    MC("Which two factors best explain Cape Town's milder, wetter winters?",
      ["Coastal location and a winter-rainfall pattern", "High altitude and the equator", "Distance from the sea", "Cold currents only"], "Coastal location and a winter-rainfall pattern",
      "Cape Town is coastal with a Mediterranean-style winter-rainfall climate.", "ERR_SSSP_G8G2A2_CAPETOWN", 3),
  ],
  "SSSP.G8.G2.A3": [
    MC("What is the difference between weather and climate?",
      ["Weather is day-to-day; climate is the long-term average", "They are exactly the same", "Climate is today's weather", "Weather is measured in years"], "Weather is day-to-day; climate is the long-term average",
      "Weather is what's happening now; climate is the long-run average pattern.", "ERR_SSSP_G8G2A3_DIFF", 1),
    TF("Temperature, humidity, wind and precipitation are all elements of weather.", "True",
      "Weather is described by temperature, humidity, wind and precipitation (rain etc.).", "ERR_SSSP_G8G2A3_ELEMENTS", 1),
    MC("A desert climate is mainly:",
      ["Very dry, with little rainfall", "Very wet all year", "Always freezing", "Always mild"], "Very dry, with little rainfall",
      "Deserts are defined by very low rainfall.", "ERR_SSSP_G8G2A3_DESERT", 1),
    CLOZE("A ____ climate is mild with wet winters and dry summers, like around the Mediterranean Sea.",
      ["Mediterranean", "polar", "tropical", "desert"], "Mediterranean",
      "Mediterranean climates have mild, wet winters and warm, dry summers.", "ERR_SSSP_G8G2A3_MED", 3),
    {
      question: "Use the climate data. Station X: warmest month 26°C, coldest 24°C, rain every month. Which climate type?",
      input_type: "data-interpret",
      data: { table: [["Feature", "Value"], ["Warmest month", "26°C"], ["Coldest month", "24°C"], ["Rainfall", "High, all year"]] },
      options: ["Tropical", "Polar", "Desert", "Mediterranean"],
      expected: "Tropical",
      memo: "Hot all year with high rainfall every month points to a tropical climate.", error_signals: ["ERR_SSSP_G8G2A3_DATA"], difficulty: 3,
    },
    TF("Climate regions of the world can be shown on a map.", "True",
      "World climate maps show where different climate types occur.", "ERR_SSSP_G8G2A3_MAP", 1),
    MC("A polar climate is:",
      ["Very cold", "Very hot", "Mild and wet", "Dry and warm"], "Very cold",
      "Polar climates near the poles are extremely cold.", "ERR_SSSP_G8G2A3_POLAR", 1),
    MC("Bar and line graphs are commonly used to show a place's:",
      ["Temperature and rainfall", "Population only", "Gold output", "Election results"], "Temperature and rainfall",
      "Climate graphs use bars for rainfall and a line for temperature.", "ERR_SSSP_G8G2A3_GRAPH", 2),
  ],

  // ─── G3 · Term 3 — Settlement & urbanisation [some image items deferred] ───
  "SSSP.G8.G3.A1": [
    MC("The central business district (CBD) of a city is mainly used for:",
      ["Shops, offices and business", "Heavy farming", "Mining only", "Wildlife reserves"], "Shops, offices and business",
      "The CBD is the city's centre of shops, offices and business.", "ERR_SSSP_G8G3A1_CBD", 1),
    TF("Urban settlements have different land-use zones, such as residential and industrial areas.", "True",
      "Cities are divided into zones: business, industry, residential and recreation.", "ERR_SSSP_G8G3A1_ZONES", 1),
    MC("Which is an example of a rural settlement type?",
      ["A farming village", "A central business district", "A shopping mall", "An airport terminal"], "A farming village",
      "Rural settlements include farming, mining, forestry and fishing communities.", "ERR_SSSP_G8G3A1_RURAL", 1),
    CLOZE("Areas of a city where people live are called ____ areas.",
      ["residential", "industrial", "business", "mining"], "residential",
      "Residential areas are where people live, ranging from high- to low-income.", "ERR_SSSP_G8G3A1_RESIDENTIAL", 1),
    TF("Heavy industry is usually placed in the middle of residential suburbs.", "False",
      "Heavy industry is usually zoned away from homes, often on the city's edge.", "ERR_SSSP_G8G3A1_INDUSTRY", 2),
    MC("Mining, forestry and fishing settlements are examples of:",
      ["Rural settlements", "City centres", "Shopping districts", "Office parks"], "Rural settlements",
      "These resource-based settlements are types of rural settlement.", "ERR_SSSP_G8G3A1_TYPES", 2),
    MC("Why do cities separate land into zones?",
      ["To organise different activities sensibly", "To cause traffic", "To remove all houses", "To stop trade"], "To organise different activities sensibly",
      "Zoning organises a city so different activities (homes, work, industry) fit together.", "ERR_SSSP_G8G3A1_WHY", 2),
  ],
  "SSSP.G8.G3.A2": [
    MC("A vertical aerial photograph is taken:",
      ["Straight down from above", "At an angle from the side", "From ground level", "From under the sea"], "Straight down from above",
      "Vertical aerial photos look straight down, like a map view.", "ERR_SSSP_G8G3A2_VERTICAL", 2),
    TF("An oblique aerial photograph is taken at an angle and shows the sides of features.", "True",
      "Oblique photos are taken at an angle, showing features' sides, like a bird's-eye view.", "ERR_SSSP_G8G3A2_OBLIQUE", 2),
    MC("Aerial photographs are useful for identifying:",
      ["Land use and features from above", "The earth's core", "Underground gold", "Tomorrow's weather"], "Land use and features from above",
      "Aerial photos help identify natural and built features and land use from above.", "ERR_SSSP_G8G3A2_USE", 1),
    CLOZE("A photo taken straight down from above is a ____ aerial photograph.",
      ["vertical", "oblique", "ground", "satellite"], "vertical",
      "Straight-down = vertical; angled = oblique.", "ERR_SSSP_G8G3A2_CLOZE", 1),
    TF("Aerial photographs can show both natural features (like rivers) and constructed features (like roads).", "True",
      "Aerial photos reveal natural features and human-made (constructed) features alike.", "ERR_SSSP_G8G3A2_FEATURES", 1),
    MC("Which would be easier to identify on a vertical aerial photo of a town?",
      ["The pattern of streets and buildings", "The smell of the air", "The names of the people", "The temperature"], "The pattern of streets and buildings",
      "Overhead photos clearly show the layout of streets and buildings.", "ERR_SSSP_G8G3A2_PATTERN", 2),
  ],
  "SSSP.G8.G3.A3": [
    MC("Urbanisation is the process of:",
      ["People moving to and cities growing", "Cities shrinking", "Farms expanding", "Rivers drying up"], "People moving to and cities growing",
      "Urbanisation is the growth of cities as people move from rural areas.", "ERR_SSSP_G8G3A3_DEF", 1),
    TF("'Pull factors' are things that attract people to cities, like jobs.", "True",
      "Pull factors (jobs, services) draw people toward cities.", "ERR_SSSP_G8G3A3_PULL", 2),
    MC("A 'push factor' driving people from rural areas could be:",
      ["Lack of jobs or land in the countryside", "Better hospitals in the city", "City entertainment", "Bright city lights"], "Lack of jobs or land in the countryside",
      "Push factors (poverty, no land, no work) drive people away from rural areas.", "ERR_SSSP_G8G3A3_PUSH", 2),
    CLOZE("Things that attract people to the city are ____ factors.",
      ["pull", "push", "climate", "tidal"], "pull",
      "Pull factors attract; push factors drive away.", "ERR_SSSP_G8G3A3_CLOZE", 1),
    {
      question: "Sort each reason for moving as a PUSH (from the countryside) or PULL (toward the city) factor.",
      input_type: "sort-buckets",
      buckets: [{ id: "push", label: "Push (away from rural)" }, { id: "pull", label: "Pull (toward city)" }],
      items: [
        { id: "i1", text: "No jobs on the farm", correct_bucket: "push" },
        { id: "i2", text: "Drought ruins crops", correct_bucket: "push" },
        { id: "i3", text: "Better hospitals in the city", correct_bucket: "pull" },
        { id: "i4", text: "More job opportunities in the city", correct_bucket: "pull" },
      ],
      expected: "No jobs and drought push people away; hospitals and jobs pull them to the city.",
      pass_threshold: 0.75,
      memo: "Push factors drive people out of rural areas; pull factors attract them to cities.", error_signals: ["ERR_SSSP_G8G3A3_SORT"], difficulty: 3,
    },
    MC("A social issue caused by rapid city growth is:",
      ["Shortage of housing and services", "Too few people", "Too much farmland", "No traffic at all"], "Shortage of housing and services",
      "Rapid urban growth strains housing, water, health care and other services.", "ERR_SSSP_G8G3A3_ISSUE", 2),
    TF("Apartheid laws controlled where black South Africans could live and move.", "True",
      "Apartheid population controls restricted black South Africans' movement and residence, shaping urbanisation.", "ERR_SSSP_G8G3A3_APARTHEID", 2),
  ],

  // ─── G4 · Term 4 — Transport & trade ───────────────────────────────────────
  "SSSP.G8.G4.A1": [
    MC("People trade mainly because:",
      ["Different places have different goods and needs", "Everyone has exactly the same things", "Trade is illegal", "It uses up resources"], "Different places have different goods and needs",
      "Trade lets places exchange what they have for what they need.", "ERR_SSSP_G8G4A1_WHY", 1),
    TF("Trade and transport are closely linked: goods must be moved to be traded.", "True",
      "Transport carries traded goods between places, so trade depends on transport.", "ERR_SSSP_G8G4A1_LINK", 1),
    MC("Which mode of transport is best for carrying heavy goods across oceans?",
      ["Sea (ships)", "Air (planes)", "Bicycle", "On foot"], "Sea (ships)",
      "Ships carry large, heavy loads across oceans cheaply, ideal for bulky goods.", "ERR_SSSP_G8G4A1_SEA", 2),
    CLOZE("Oil and gas are often moved long distances through a ____.",
      ["pipeline", "ship only", "bicycle", "footpath"], "pipeline",
      "Pipelines efficiently move liquids and gases like oil over long distances.", "ERR_SSSP_G8G4A1_PIPELINE", 2),
    TF("Air transport is the fastest way to move goods over long distances.", "True",
      "Air transport is fastest but more expensive, good for urgent or light goods.", "ERR_SSSP_G8G4A1_AIR", 1),
    {
      question: "Sort each cargo with the most suitable transport mode.",
      input_type: "sort-buckets",
      buckets: [{ id: "sea", label: "Sea (ship)" }, { id: "air", label: "Air (plane)" }, { id: "pipe", label: "Pipeline" }],
      items: [
        { id: "i1", text: "Thousands of tonnes of coal across an ocean", correct_bucket: "sea" },
        { id: "i2", text: "Urgent medicine to another country fast", correct_bucket: "air" },
        { id: "i3", text: "Crude oil from the coast to a refinery inland", correct_bucket: "pipe" },
      ],
      expected: "Bulk coal by sea, urgent medicine by air, oil by pipeline.",
      pass_threshold: 0.66,
      memo: "Match the cargo to the mode: bulky → sea, urgent/light → air, liquid → pipeline.", error_signals: ["ERR_SSSP_G8G4A1_SORT"], difficulty: 3,
    },
    MC("Which are the five main modes of transport in this topic?",
      ["Sea, air, road, rail and pipeline", "Only road and rail", "Only ships", "Walking and running"], "Sea, air, road, rail and pipeline",
      "The main modes are sea, air, road, rail and pipeline.", "ERR_SSSP_G8G4A1_MODES", 1),
  ],
  "SSSP.G8.G4.A2": [
    MC("A harbour (port) is important for trade because it:",
      ["Connects sea transport with land transport", "Mines gold", "Grows crops", "Predicts weather"], "Connects sea transport with land transport",
      "Harbours link ships to road, rail and pipelines, moving goods in and out of a country.", "ERR_SSSP_G8G4A2_HARBOUR", 1),
    TF("South Africa exports many goods through its harbours.", "True",
      "South Africa's harbours handle large volumes of imports and exports.", "ERR_SSSP_G8G4A2_EXPORTS", 1),
    MC("Which is a major South African harbour?",
      ["Durban", "Johannesburg", "Kimberley", "Upington"], "Durban",
      "Durban is one of South Africa's busiest harbours; Johannesburg is inland.", "ERR_SSSP_G8G4A2_DURBAN", 2),
    CLOZE("A ____ ship is a specialised vessel that carries standard steel boxes of cargo.",
      ["container", "passenger", "fishing", "sailing"], "container",
      "Container ships carry goods in standard steel containers for easy handling.", "ERR_SSSP_G8G4A2_CONTAINER", 2),
    TF("Road and rail transport link harbours to the rest of the country.", "True",
      "Roads, railways and pipelines connect harbours to inland areas.", "ERR_SSSP_G8G4A2_LINKS", 1),
    MC("An advantage of rail transport over road for heavy goods is that it:",
      ["Can carry large loads efficiently over long distances", "Is always door-to-door", "Needs no tracks", "Is best for short trips in cities"], "Can carry large loads efficiently over long distances",
      "Rail moves heavy bulk loads efficiently over long distances; road is more flexible for short trips.", "ERR_SSSP_G8G4A2_RAIL", 3),
    MC("Why might a harbour be located where it is?",
      ["A sheltered, deep natural bay", "High in the mountains", "In the middle of a desert", "Far from any water"], "A sheltered, deep natural bay",
      "Harbours need sheltered, deep water for ships, often a natural bay.", "ERR_SSSP_G8G4A2_LOCATION", 2),
  ],
  "SSSP.G8.G4.A3": [
    MC("A 'commuter' is a person who:",
      ["Travels regularly between home and work", "Lives at their workplace", "Never travels", "Mines gold"], "Travels regularly between home and work",
      "Commuters travel between home and work, usually daily.", "ERR_SSSP_G8G4A3_COMMUTER", 1),
    TF("Minibus taxis are an important form of transport for many South African commuters.", "True",
      "Minibus taxis carry large numbers of South African commuters every day.", "ERR_SSSP_G8G4A3_TAXI", 1),
    MC("Which is a transport problem in many cities?",
      ["Traffic congestion and pollution", "Too few cars", "Empty roads", "No need to travel"], "Traffic congestion and pollution",
      "Congestion, cost and pollution are common urban transport problems.", "ERR_SSSP_G8G4A3_PROBLEM", 1),
    CLOZE("Buses and trains shared by many people are forms of ____ transport.",
      ["public", "private", "air", "sea"], "public",
      "Public transport (buses, trains) is shared by many commuters.", "ERR_SSSP_G8G4A3_PUBLIC", 1),
    MC("A 'park and ride' scheme helps reduce congestion by letting people:",
      ["Park their cars and use public transport into the city", "Drive into the busiest streets", "Build more parking in the CBD", "Avoid all transport"], "Park their cars and use public transport into the city",
      "Park and ride lets commuters leave cars and take public transport, easing congestion.", "ERR_SSSP_G8G4A3_PARKRIDE", 3),
    TF("Bus and cycle lanes are strategies to improve urban transport.", "True",
      "Dedicated bus and cycle lanes are public-transit strategies to ease congestion.", "ERR_SSSP_G8G4A3_LANES", 2),
    MC("Why is reducing private car use in cities helpful?",
      ["It can cut congestion and pollution", "It increases traffic jams", "It raises pollution", "It has no benefit"], "It can cut congestion and pollution",
      "Fewer private cars means less congestion and pollution.", "ERR_SSSP_G8G4A3_REDUCE", 2),
  ],
};

export default G8;
