// ─── Social Sciences SP — Grade 9 question pools, batch B ─────────────────────
// Appended to sssp-g9.mjs to bring each pool to ~20. New angles; no repeats.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9B = {
  // ── H1.A1 Rise of Nazi Germany ──
  "SSSP.G9.H1.A1": [
    MC("The Nazi Party was led by:", ["Adolf Hitler", "Joseph Stalin", "Winston Churchill", "Charles de Gaulle"], "Adolf Hitler",
      "Hitler led the Nazi Party to power in Germany.", "ERR_SSSP_G9H1A1_B01", 1),
    TF("The Weimar Republic struggled with economic problems and instability.", "True",
      "The Weimar Republic faced severe economic and political instability.", "ERR_SSSP_G9H1A1_B02", 2),
    MC("The Great Depression began in:", ["1929", "1914", "1948", "1990"], "1929",
      "The Great Depression began in 1929, causing mass hardship.", "ERR_SSSP_G9H1A1_B03", 2),
    CLOZE("Hardship and fear helped the Nazis win ____ in the early 1930s.", ["support", "wars", "deserts", "gold"], "support",
      "Economic hardship helped the Nazis win public support.", "ERR_SSSP_G9H1A1_B04", 2),
    TF("The Nuremberg Laws removed rights from Jewish people.", "True",
      "The 1935 Nuremberg Laws stripped Jewish people of basic rights.", "ERR_SSSP_G9H1A1_B05", 1),
    MC("A dictatorship is a government where power is held by:", ["One leader or party with no real opposition", "Many parties freely", "The people directly", "No one"], "One leader or party with no real opposition",
      "A dictatorship concentrates power in one leader or party, crushing opposition.", "ERR_SSSP_G9H1A1_B06", 2),
    MC("Concentration camps were first used by the Nazis to hold:", ["Political opponents and others", "Tourists", "Soldiers only", "Children at school"], "Political opponents and others",
      "Early camps held political opponents and other targeted groups.", "ERR_SSSP_G9H1A1_B07", 3),
    TF("The Nazis allowed free elections and a free press once in power.", "False",
      "The Nazis ended free elections and a free press, building a dictatorship.", "ERR_SSSP_G9H1A1_B08", 2),
    MC("The Treaty of Versailles fed Nazi support because Germans felt it was:", ["Unfair and humiliating", "Too generous", "Perfectly fair", "Unimportant"], "Unfair and humiliating",
      "Resentment at the unfair-feeling Versailles treaty helped the Nazis.", "ERR_SSSP_G9H1A1_B09", 3),
    CLOZE("Germany's democracy before Hitler was the ____ Republic.", ["Weimar", "Roman", "Soviet", "French"], "Weimar",
      "The Weimar Republic was Germany's pre-Nazi democracy.", "ERR_SSSP_G9H1A1_B10", 2),
    TF("A fascist state limits individual rights and freedom.", "True",
      "Fascist states restrict rights and crush dissent.", "ERR_SSSP_G9H1A1_B11", 1),
    MC("Why study how the Nazis came to power?", ["To understand how democracies can fail", "To copy them", "It has no value", "To learn the weather"], "To understand how democracies can fail",
      "Studying the Nazis' rise warns how democracies can fail.", "ERR_SSSP_G9H1A1_B12", 3),
  ],
  // ── H1.A2 WWII in Europe ──
  "SSSP.G9.H1.A2": [
    MC("World War II in Europe ended in:", ["1945", "1918", "1929", "1960"], "1945",
      "The war in Europe ended in 1945.", "ERR_SSSP_G9H1A2_B01", 1),
    TF("The Holocaust was the systematic murder of millions, including six million Jews.", "True",
      "The Holocaust murdered millions, including about six million Jews.", "ERR_SSSP_G9H1A2_B02", 1),
    MC("The Allies in WWII included:", ["Britain, the USA and the USSR", "Germany and Italy", "Only Japan", "Mali and Ghana"], "Britain, the USA and the USSR",
      "The Allies included Britain, the USA and the USSR, against the Axis.", "ERR_SSSP_G9H1A2_B03", 2),
    CLOZE("The Nazi genocide of Jews and others is called the ____.", ["Holocaust", "Versailles", "Blitz", "Union"], "Holocaust",
      "The Holocaust was the Nazi genocide.", "ERR_SSSP_G9H1A2_B04", 1),
    TF("Dietrich Bonhoeffer resisted the Nazis through the Confessing Church.", "True",
      "Bonhoeffer was a Christian who resisted Nazism through the Confessing Church.", "ERR_SSSP_G9H1A2_B05", 3),
    MC("Genocide means:", ["The deliberate murder of a whole group of people", "A type of treaty", "A battle", "A weapon"], "The deliberate murder of a whole group of people",
      "Genocide is the deliberate destruction of a whole group of people.", "ERR_SSSP_G9H1A2_B06", 2),
    MC("The Warsaw Ghetto Uprising showed that victims of the Nazis:", ["Resisted bravely", "Did nothing", "Supported the Nazis", "Left Europe"], "Resisted bravely",
      "The uprising showed brave resistance by Jewish people in the ghetto.", "ERR_SSSP_G9H1A2_B07", 3),
    TF("The 'Final Solution' was the Nazi plan to murder Europe's Jews.", "True",
      "The 'Final Solution' was the Nazi plan for the genocide of Jews.", "ERR_SSSP_G9H1A2_B08", 2),
    MC("Germany and its partners in WWII were the:", ["Axis powers", "Allied powers", "Central powers", "Randlords"], "Axis powers",
      "Germany, Italy and Japan formed the Axis powers.", "ERR_SSSP_G9H1A2_B09", 1),
    CLOZE("Sophie Scholl was part of the ____ Rose resistance movement.", ["White", "Red", "Black", "Blue"], "White",
      "Sophie Scholl was part of the White Rose movement.", "ERR_SSSP_G9H1A2_B10", 3),
    TF("Some people inside Nazi Germany risked their lives to resist.", "True",
      "Resisters like the White Rose risked everything to oppose the Nazis.", "ERR_SSSP_G9H1A2_B11", 1),
    MC("Studying the Holocaust helps us understand the dangers of:", ["Prejudice and unchecked hatred", "Good weather", "Trade routes", "Map scales"], "Prejudice and unchecked hatred",
      "The Holocaust warns of where prejudice and hatred can lead.", "ERR_SSSP_G9H1A2_B12", 3),
  ],
  // ── H1.A3 WWII in the Pacific ──
  "SSSP.G9.H1.A3": [
    MC("Pearl Harbour, attacked by Japan, is in:", ["Hawaii (USA)", "Japan", "Germany", "South Africa"], "Hawaii (USA)",
      "Pearl Harbour is a US naval base in Hawaii.", "ERR_SSSP_G9H1A3_B01", 2),
    TF("Japan's attack on Pearl Harbour brought the USA into WWII.", "True",
      "The 1941 attack on Pearl Harbour drew the USA into the war.", "ERR_SSSP_G9H1A3_B02", 1),
    MC("Japan expanded aggressively across:", ["Asia and the Pacific", "Europe only", "Africa only", "the Sahara"], "Asia and the Pacific",
      "Japan expanded across Asia and the Pacific during the war.", "ERR_SSSP_G9H1A3_B03", 2),
    CLOZE("Japanese ____ in the USA were forced into internment camps.", ["Americans", "soldiers", "tourists", "sailors"], "Americans",
      "Japanese Americans were forced into internment camps.", "ERR_SSSP_G9H1A3_B04", 2),
    TF("Japan committed atrocities during its expansion in China.", "True",
      "Japan committed serious atrocities during its expansion, especially in China.", "ERR_SSSP_G9H1A3_B05", 2),
    MC("Allied prisoners of war held by Japan faced:", ["Harsh conditions", "Comfortable hotels", "Freedom", "High wages"], "Harsh conditions",
      "Allied POWs in Japanese camps faced harsh, brutal conditions.", "ERR_SSSP_G9H1A3_B06", 2),
    MC("Interning Japanese Americans was based mainly on:", ["Fear and prejudice, not proof of disloyalty", "Clear evidence of crimes", "Their own request", "A fair trial each"], "Fear and prejudice, not proof of disloyalty",
      "Internment was driven by fear and prejudice, not proof of disloyalty.", "ERR_SSSP_G9H1A3_B07", 3),
    TF("The Pacific war was fought mainly between the USA and Japan.", "True",
      "The Pacific theatre was largely the USA (and allies) against Japan.", "ERR_SSSP_G9H1A3_B08", 1),
    MC("Pearl Harbour was attacked in:", ["1941", "1918", "1929", "1960"], "1941",
      "Japan attacked Pearl Harbour in 1941.", "ERR_SSSP_G9H1A3_B09", 2),
    CLOZE("Holding people in camps because of fear is an example of ____.", ["injustice", "fairness", "freedom", "trade"], "injustice",
      "Interning people based on fear, not guilt, was an injustice.", "ERR_SSSP_G9H1A3_B10", 2),
    TF("Wars can lead governments to treat groups of their own people unfairly.", "True",
      "The internment of Japanese Americans shows wars can lead to unfair treatment.", "ERR_SSSP_G9H1A3_B11", 2),
    MC("The Pacific war reminds us that World War II was:", ["A truly global conflict", "Only in Europe", "A small local war", "Imaginary"], "A truly global conflict",
      "Fighting across Europe, Asia and the Pacific made WWII a global conflict.", "ERR_SSSP_G9H1A3_B12", 2),
  ],
  // ── H2.A1 Tension after WWII ──
  "SSSP.G9.H2.A1": [
    MC("After WWII the world's two superpowers were the USA and the:", ["USSR", "UK", "Japan", "France"], "USSR",
      "The USA and USSR became the two Cold War superpowers.", "ERR_SSSP_G9H2A1_B01", 1),
    TF("Communism and capitalism are different economic and political systems.", "True",
      "Communism (state control) and capitalism (private ownership) are opposing systems.", "ERR_SSSP_G9H2A1_B02", 1),
    MC("The USA was the leading example of:", ["Capitalism", "Communism", "Fascism", "Feudalism"], "Capitalism",
      "The USA championed capitalism.", "ERR_SSSP_G9H2A1_B03", 2),
    CLOZE("The USSR was the leading ____ power.", ["communist", "capitalist", "fascist", "colonial"], "communist",
      "The USSR led the communist side.", "ERR_SSSP_G9H2A1_B04", 2),
    TF("The USA and USSR trusted each other completely after the war.", "False",
      "They deeply distrusted each other, which drove the Cold War.", "ERR_SSSP_G9H2A1_B05", 1),
    MC("'Superpower' describes a country that is:", ["Extremely powerful in the world", "Very small", "Without an army", "Imaginary"], "Extremely powerful in the world",
      "A superpower is an extremely powerful nation, like the USA and USSR.", "ERR_SSSP_G9H2A1_B06", 1),
    MC("Under communism, the economy is mainly controlled by:", ["The state", "Private owners", "Foreign companies", "No one"], "The state",
      "Under communism the state controls the economy.", "ERR_SSSP_G9H2A1_B07", 2),
    TF("During WWII, the USA and USSR were on the same side against the Axis.", "True",
      "They were wartime allies before becoming Cold War rivals.", "ERR_SSSP_G9H2A1_B08", 2),
    MC("Tension grew after WWII because the superpowers had:", ["Opposing systems and aims", "Identical governments", "No armies", "The same leader"], "Opposing systems and aims",
      "Opposing systems and aims created post-war tension.", "ERR_SSSP_G9H2A1_B09", 2),
    CLOZE("Capitalism is based on private ownership and free ____.", ["markets", "armies", "deserts", "kings"], "markets",
      "Capitalism rests on private ownership and free markets.", "ERR_SSSP_G9H2A1_B10", 2),
    TF("The rivalry between the USA and USSR shaped world events for decades.", "True",
      "The Cold War rivalry shaped global events for over forty years.", "ERR_SSSP_G9H2A1_B11", 1),
    MC("The post-war distrust between the superpowers led to the:", ["Cold War", "Industrial Revolution", "Scramble for Africa", "Great Trek"], "Cold War",
      "Their distrust led to the Cold War.", "ERR_SSSP_G9H2A1_B12", 1),
  ],
  // ── H2.A2 Atomic bombs ──
  "SSSP.G9.H2.A2": [
    MC("The atomic bombs were dropped on which two cities?", ["Hiroshima and Nagasaki", "Tokyo and Osaka", "Berlin and Munich", "Cape Town and Durban"], "Hiroshima and Nagasaki",
      "Hiroshima and Nagasaki were struck by atomic bombs in 1945.", "ERR_SSSP_G9H2A2_B01", 1),
    TF("The atomic bombings led to Japan's surrender.", "True",
      "After the bombings, Japan surrendered, ending WWII.", "ERR_SSSP_G9H2A2_B02", 1),
    MC("The atomic bomb caused destruction that was:", ["On a vast new scale", "Very small", "Harmless", "Like ordinary bombs"], "On a vast new scale",
      "Atomic bombs caused destruction on a completely new scale.", "ERR_SSSP_G9H2A2_B03", 2),
    CLOZE("The use of atomic bombs opened the ____ Age.", ["Nuclear", "Stone", "Industrial", "Middle"], "Nuclear",
      "The bombings opened the Nuclear Age.", "ERR_SSSP_G9H2A2_B04", 1),
    TF("Historians still debate whether dropping the bombs was justified.", "True",
      "The justification for the bombings is still debated.", "ERR_SSSP_G9H2A2_B05", 2),
    MC("The USA argued the bombs would:", ["End the war quickly and avoid an invasion", "Start a new war", "Help Japan win", "Cool the climate"], "End the war quickly and avoid an invasion",
      "The USA argued the bombs would end the war fast and avoid a costly invasion.", "ERR_SSSP_G9H2A2_B06", 3),
    MC("The bombings killed:", ["Many thousands of civilians", "Only soldiers", "No one", "Only buildings"], "Many thousands of civilians",
      "The bombings killed many thousands, including civilians.", "ERR_SSSP_G9H2A2_B07", 2),
    TF("Nuclear weapons are far more powerful than ordinary bombs.", "True",
      "Nuclear weapons are vastly more powerful than conventional bombs.", "ERR_SSSP_G9H2A2_B08", 1),
    MC("Different views on the bombings show the history skill of:", ["Considering more than one perspective", "Drawing maps", "Counting money", "Measuring rainfall"], "Considering more than one perspective",
      "Debating the bombings uses multi-perspective historical thinking.", "ERR_SSSP_G9H2A2_B09", 3),
    CLOZE("The atomic bomb ended the war in the ____.", ["Pacific", "Atlantic", "Sahara", "Arctic"], "Pacific",
      "The atomic bombings ended the Pacific war against Japan.", "ERR_SSSP_G9H2A2_B10", 2),
    TF("The Nuclear Age raised new fears about the power of weapons.", "True",
      "The Nuclear Age brought new fears of immensely destructive weapons.", "ERR_SSSP_G9H2A2_B11", 2),
    MC("The atomic bombings are a turning point because they:", ["Began an age of nuclear weapons", "Ended all weapons", "Had no effect", "Started WWI"], "Began an age of nuclear weapons",
      "They opened the dangerous age of nuclear weapons.", "ERR_SSSP_G9H2A2_B12", 2),
  ],
  // ── H2.A3 The Cold War: areas of conflict ──
  "SSSP.G9.H2.A3": [
    MC("The 'Cold War' is called 'cold' because the superpowers:", ["Did not fight each other directly", "Fought in cold weather", "Used ice weapons", "Were friendly"], "Did not fight each other directly",
      "It was 'cold' because the superpowers avoided direct war.", "ERR_SSSP_G9H2A3_B01", 2),
    TF("The arms race involved building nuclear weapons.", "True",
      "The arms race included building up nuclear arsenals.", "ERR_SSSP_G9H2A3_B02", 1),
    MC("The space race included the goal of reaching:", ["The Moon", "The Sun", "Mali", "the sea floor"], "The Moon",
      "The space race included the goal of landing on the Moon.", "ERR_SSSP_G9H2A3_B03", 2),
    CLOZE("The Berlin ____ was built in 1961 to divide the city.", ["Wall", "Bridge", "Tower", "Harbour"], "Wall",
      "The Berlin Wall, built in 1961, divided the city.", "ERR_SSSP_G9H2A3_B04", 1),
    TF("Germany was divided into East and West after WWII.", "True",
      "Germany was split into East and West, with Berlin also divided.", "ERR_SSSP_G9H2A3_B05", 2),
    MC("A 'proxy' way the superpowers competed was through:", ["Influence and rivalry around the world", "Direct invasion of each other", "Friendly trade only", "Sharing a government"], "Influence and rivalry around the world",
      "They competed for influence worldwide rather than fighting directly.", "ERR_SSSP_G9H2A3_B06", 3),
    MC("The Berlin Wall separated:", ["East and West Berlin", "Two oceans", "Africa and Europe", "Two planets"], "East and West Berlin",
      "The Wall separated communist East Berlin from West Berlin.", "ERR_SSSP_G9H2A3_B07", 2),
    TF("The arms and space races were forms of competition without direct war.", "True",
      "These races were ways to compete without fighting directly.", "ERR_SSSP_G9H2A3_B08", 1),
    MC("The Cold War rivalry was between:", ["The USA and the USSR", "Britain and France", "Mali and Ghana", "Japan and China"], "The USA and the USSR",
      "The Cold War was between the USA and the USSR.", "ERR_SSSP_G9H2A3_B09", 1),
    CLOZE("The competition to build more weapons was the ____ race.", ["arms", "space", "human", "trade"], "arms",
      "The arms race was the competition to build more weapons.", "ERR_SSSP_G9H2A3_B10", 1),
    TF("The Berlin Wall became a symbol of the divided world.", "True",
      "The Wall symbolised the divide between communist East and capitalist West.", "ERR_SSSP_G9H2A3_B11", 2),
    MC("The space race showed Cold War rivalry through:", ["Competing achievements in space", "Direct battles in space", "Sharing rockets", "Ending all science"], "Competing achievements in space",
      "The space race was a rivalry over achievements in space.", "ERR_SSSP_G9H2A3_B12", 2),
  ],
  // ── H2.A4 End of the Cold War ──
  "SSSP.G9.H2.A4": [
    MC("The Berlin Wall fell in:", ["1989", "1961", "1945", "1914"], "1989",
      "The Berlin Wall fell in 1989.", "ERR_SSSP_G9H2A4_B01", 1),
    TF("The Soviet Union broke apart in 1991.", "True",
      "The USSR collapsed in 1991.", "ERR_SSSP_G9H2A4_B02", 1),
    MC("The fall of the Berlin Wall symbolised:", ["The end of the Cold War divide", "The start of WWII", "A new arms race", "The Scramble for Africa"], "The end of the Cold War divide",
      "The Wall's fall symbolised the end of the Cold War divide.", "ERR_SSSP_G9H2A4_B03", 2),
    CLOZE("After 1991 the ____ no longer existed as one country.", ["USSR", "USA", "UK", "EU"], "USSR",
      "The USSR ceased to exist after 1991.", "ERR_SSSP_G9H2A4_B04", 2),
    TF("The end of the Cold War reduced the threat of superpower conflict.", "True",
      "The Cold War's end eased the long superpower standoff.", "ERR_SSSP_G9H2A4_B05", 2),
    MC("The end of the Cold War affected South Africa by:", ["Reducing outside backing for apartheid", "Starting apartheid", "Building the Berlin Wall", "Causing WWII"], "Reducing outside backing for apartheid",
      "The Cold War's end was one factor easing South Africa toward change.", "ERR_SSSP_G9H2A4_B06", 3),
    MC("The Wall falling in 1989 came:", ["Before the USSR collapsed in 1991", "After the USSR collapsed", "In the same week", "In 1945"], "Before the USSR collapsed in 1991",
      "The Wall fell in 1989, two years before the USSR collapsed in 1991.", "ERR_SSSP_G9H2A4_B07", 2),
    TF("The Cold War lasted for over forty years.", "True",
      "The Cold War ran from after WWII until around 1990 — over forty years.", "ERR_SSSP_G9H2A4_B08", 2),
    MC("The collapse of the USSR meant communism:", ["Lost much of its global power", "Took over the world", "Began for the first time", "Had no effect"], "Lost much of its global power",
      "The USSR's collapse greatly reduced communism's global power.", "ERR_SSSP_G9H2A4_B09", 3),
    CLOZE("The fall of the ____ in 1989 marked the Cold War's end.", ["Berlin Wall", "Union", "Treaty", "Empire"], "Berlin Wall",
      "The fall of the Berlin Wall marked the Cold War's end.", "ERR_SSSP_G9H2A4_B10", 1),
    TF("World events in 1989–1991 reshaped global politics.", "True",
      "The Wall's fall and the USSR's collapse reshaped world politics.", "ERR_SSSP_G9H2A4_B11", 1),
    MC("Why does the end of the Cold War matter for South Africa's history?", ["It was one factor that helped end apartheid", "It started apartheid", "It built the gold mines", "It had no link"], "It was one factor that helped end apartheid",
      "The Cold War's end helped create conditions for ending apartheid.", "ERR_SSSP_G9H2A4_B12", 3),
  ],
  // ── H3.A1 Human rights and the myth of race ──
  "SSSP.G9.H3.A1": [
    MC("The Universal Declaration of Human Rights was adopted in:", ["1948", "1910", "1976", "1994"], "1948",
      "The UN adopted the Universal Declaration of Human Rights in 1948.", "ERR_SSSP_G9H3A1_B01", 2),
    TF("Human rights belong to all people simply because they are human.", "True",
      "Human rights are universal — they belong to everyone.", "ERR_SSSP_G9H3A1_B02", 1),
    MC("Scientists describe 'race' as:", ["A social idea, not a biological fact", "A separate species", "A type of country", "A language"], "A social idea, not a biological fact",
      "Science treats 'race' as a social construct, not a biological reality.", "ERR_SSSP_G9H3A1_B03", 2),
    CLOZE("Studies of human ____ show we share common African ancestors.", ["evolution", "weather", "trade", "geography"], "evolution",
      "Human evolution shows our shared African ancestry.", "ERR_SSSP_G9H3A1_B04", 2),
    TF("Apartheid used physical appearance to classify people into groups.", "True",
      "Apartheid sorted people by superficial physical features — a false basis.", "ERR_SSSP_G9H3A1_B05", 2),
    MC("The UDHR was a response to the horrors of:", ["World War II", "the Great Trek", "the gold rush", "the Berlin Conference"], "World War II",
      "The UDHR followed WWII's horrors, aiming to protect human rights.", "ERR_SSSP_G9H3A1_B06", 2),
    MC("Racism is best described as:", ["Unfair treatment based on the idea of 'race'", "A fair system", "A type of climate", "A trade route"], "Unfair treatment based on the idea of 'race'",
      "Racism is unfair treatment based on the false idea of 'race'.", "ERR_SSSP_G9H3A1_B07", 1),
    TF("Understanding our common ancestry can challenge racist ideas.", "True",
      "Common ancestry shows humans are closely related, undercutting racism.", "ERR_SSSP_G9H3A1_B08", 2),
    MC("All humans today descend from ancestors who lived in:", ["Africa", "Europe", "Asia only", "the Americas"], "Africa",
      "Modern humans descend from ancestors who lived in Africa.", "ERR_SSSP_G9H3A1_B09", 3),
    CLOZE("Treating people unfairly because of 'race' is called ____.", ["racism", "tourism", "nationalism", "socialism"], "racism",
      "Such unfair treatment is racism.", "ERR_SSSP_G9H3A1_B10", 1),
    TF("Human rights documents try to protect people from injustice.", "True",
      "Human rights documents like the UDHR aim to protect people from injustice.", "ERR_SSSP_G9H3A1_B11", 1),
    MC("Why is it important to know 'race' is not biological?", ["It removes the false basis for racism", "It supports apartheid", "It changes the weather", "It has no value"], "It removes the false basis for racism",
      "Knowing 'race' is a social idea removes the false basis for racism.", "ERR_SSSP_G9H3A1_B12", 3),
  ],
  // ── H3.A2 1948 apartheid laws ──
  "SSSP.G9.H3.A2": [
    MC("Apartheid means:", ["'Apartness' — enforced racial separation", "Equality for all", "Free trade", "A type of mine"], "'Apartness' — enforced racial separation",
      "Apartheid (Afrikaans for 'apartness') was enforced racial separation.", "ERR_SSSP_G9H3A2_B01", 1),
    TF("The National Party won the 1948 election and built apartheid.", "True",
      "The National Party won in 1948 and built the apartheid system.", "ERR_SSSP_G9H3A2_B02", 1),
    MC("The Group Areas Act controlled:", ["Where people of different races could live", "Voting for all", "Gold prices", "School subjects"], "Where people of different races could live",
      "The Group Areas Act forced racial groups into separate areas.", "ERR_SSSP_G9H3A2_B03", 2),
    CLOZE("People removed from ____ are a famous example of the Group Areas Act.", ["Sophiatown", "Soweto", "Sharpeville", "Langa"], "Sophiatown",
      "Sophiatown's removal is a famous Group Areas Act case.", "ERR_SSSP_G9H3A2_B04", 2),
    TF("Pass laws controlled the movement of black South Africans.", "True",
      "Pass laws forced black South Africans to carry passes and restricted movement.", "ERR_SSSP_G9H3A2_B05", 2),
    MC("Forced removals meant people were:", ["Made to leave their homes", "Given new mansions", "Allowed to stay", "Sent overseas to study"], "Made to leave their homes",
      "Forced removals made people leave their homes against their will.", "ERR_SSSP_G9H3A2_B06", 2),
    MC("Bantustans (homelands) were used to:", ["Confine many black South Africans to set areas", "Give equal land", "Build gold mines", "Welcome tourists"], "Confine many black South Africans to set areas",
      "Bantustans confined black South Africans to set 'homelands'.", "ERR_SSSP_G9H3A2_B07", 3),
    TF("Apartheid laws gave equal rights to all South Africans.", "False",
      "Apartheid laws denied rights to the black majority while privileging the white minority.", "ERR_SSSP_G9H3A2_B08", 1),
    MC("Segregation in South Africa:", ["Existed before 1948 but apartheid made it total law", "Began only in 1994", "Never existed", "Ended in 1948"], "Existed before 1948 but apartheid made it total law",
      "Segregation predated 1948; apartheid made it total, systematic law.", "ERR_SSSP_G9H3A2_B09", 3),
    CLOZE("The ____ Party came to power in 1948 and built apartheid.", ["National", "Communist", "Labour", "Freedom"], "National",
      "The National Party built apartheid after 1948.", "ERR_SSSP_G9H3A2_B10", 1),
    TF("Apartheid affected nearly every part of people's daily lives.", "True",
      "Apartheid controlled where people lived, worked, learned and travelled.", "ERR_SSSP_G9H3A2_B11", 1),
    MC("The people of Mogopa were forcibly removed to:", ["Bophuthatswana", "Britain", "Cape Town's CBD", "Soweto"], "Bophuthatswana",
      "The people of Mogopa were forcibly removed to the Bophuthatswana bantustan.", "ERR_SSSP_G9H3A2_B12", 3),
  ],
  // ── H3.A3 1950s resistance ──
  "SSSP.G9.H3.A3": [
    MC("The Defiance Campaign involved deliberately:", ["Breaking unjust apartheid laws peacefully", "Starting a war", "Mining gold", "Leaving the country"], "Breaking unjust apartheid laws peacefully",
      "The Defiance Campaign peacefully defied unjust apartheid laws.", "ERR_SSSP_G9H3A3_B01", 2),
    TF("The Freedom Charter declared that South Africa belongs to all who live in it.", "True",
      "The Freedom Charter declared South Africa belongs to all its people.", "ERR_SSSP_G9H3A3_B02", 2),
    MC("The Women's March of 1956 was to the:", ["Union Buildings in Pretoria", "gold mines", "harbour", "Berlin Wall"], "Union Buildings in Pretoria",
      "Women marched to the Union Buildings in 1956 against pass laws.", "ERR_SSSP_G9H3A3_B03", 3),
    CLOZE("Albert ____ was an ANC leader awarded the Nobel Peace Prize.", ["Luthuli", "Verwoerd", "Rhodes", "Botha"], "Luthuli",
      "Albert Luthuli, an ANC leader, won the Nobel Peace Prize.", "ERR_SSSP_G9H3A3_B04", 3),
    TF("Helen Joseph and Lillian Ngoyi were leaders in the resistance.", "True",
      "Joseph and Ngoyi were prominent leaders, including in the Women's March.", "ERR_SSSP_G9H3A3_B05", 2),
    MC("Non-violent resistance means opposing injustice:", ["Without using violence", "With weapons", "By leaving quietly", "By doing nothing"], "Without using violence",
      "Non-violent resistance opposes injustice peacefully.", "ERR_SSSP_G9H3A3_B06", 1),
    MC("The Treason Trial was used by the government to:", ["Charge resistance leaders", "Reward protesters", "End apartheid", "Free prisoners"], "Charge resistance leaders",
      "The Treason Trial charged resistance leaders to try to silence them.", "ERR_SSSP_G9H3A3_B07", 2),
    TF("Mahatma Gandhi's ideas influenced non-violent resistance in South Africa.", "True",
      "Gandhi's philosophy of non-violence influenced the struggle.", "ERR_SSSP_G9H3A3_B08", 2),
    MC("The slogan of the Women's March warned that those who strike a woman strike:", ["A rock", "A wall", "the sea", "the sky"], "A rock",
      "'You strike a woman, you strike a rock' was the Women's March slogan.", "ERR_SSSP_G9H3A3_B09", 3),
    CLOZE("The 1955 ____ Charter set out a vision of a free South Africa.", ["Freedom", "Union", "Berlin", "Land"], "Freedom",
      "The 1955 Freedom Charter set out the struggle's vision.", "ERR_SSSP_G9H3A3_B10", 2),
    TF("1950s resistance was generally peaceful and well organised.", "True",
      "1950s resistance was mostly organised and non-violent.", "ERR_SSSP_G9H3A3_B11", 1),
    MC("These campaigns show ordinary people could:", ["Organise to oppose injustice", "Do nothing", "Only obey", "Leave history alone"], "Organise to oppose injustice",
      "The campaigns show people organising to resist injustice.", "ERR_SSSP_G9H3A3_B12", 2),
  ],
  // ── H4.A1 Sharpeville ──
  "SSSP.G9.H4.A1": [
    MC("Sharpeville is remembered for a:", ["Massacre of protesters in 1960", "Gold discovery", "Peace treaty", "Trade fair"], "Massacre of protesters in 1960",
      "Sharpeville is remembered for the 1960 massacre of protesters.", "ERR_SSSP_G9H4A1_B01", 1),
    TF("People at Sharpeville were protesting against the pass laws.", "True",
      "Protesters at Sharpeville opposed the pass laws.", "ERR_SSSP_G9H4A1_B02", 1),
    MC("The PAC, which organised the protest, was formed in:", ["1959", "1912", "1976", "1994"], "1959",
      "The PAC was formed in 1959 and organised the anti-pass protests.", "ERR_SSSP_G9H4A1_B03", 2),
    CLOZE("21 March is now ____ Day in South Africa, recalling Sharpeville.", ["Human Rights", "Youth", "Freedom", "Workers'"], "Human Rights",
      "21 March is Human Rights Day, marking the Sharpeville massacre.", "ERR_SSSP_G9H4A1_B04", 3),
    TF("After Sharpeville the government banned organisations like the ANC and PAC.", "True",
      "Following Sharpeville, the ANC and PAC were banned.", "ERR_SSSP_G9H4A1_B05", 2),
    MC("Sharpeville drew international attention to:", ["Apartheid's brutality", "South African gold", "the Berlin Wall", "WWII"], "Apartheid's brutality",
      "Sharpeville drew world attention to apartheid's brutality.", "ERR_SSSP_G9H4A1_B06", 2),
    MC("A consequence of Sharpeville was that some movements:", ["Turned to armed struggle", "Disbanded forever", "Joined the government", "Left the country happily"], "Turned to armed struggle",
      "When peaceful protest met violence, some turned to armed struggle.", "ERR_SSSP_G9H4A1_B07", 3),
    TF("Sharpeville was a minor event with no lasting effect.", "False",
      "Sharpeville was a major turning point with lasting effects.", "ERR_SSSP_G9H4A1_B08", 1),
    MC("Banning the ANC and PAC forced them to:", ["Operate secretly or from exile", "Join parliament", "Stop completely", "Become companies"], "Operate secretly or from exile",
      "Banned movements had to work underground or from exile.", "ERR_SSSP_G9H4A1_B09", 3),
    CLOZE("Sharpeville took place in ____.", ["1960", "1948", "1976", "1994"], "1960",
      "The Sharpeville massacre occurred in 1960.", "ERR_SSSP_G9H4A1_B10", 1),
    TF("Sharpeville increased both repression and resistance.", "True",
      "Sharpeville led to harsher repression and stronger resistance.", "ERR_SSSP_G9H4A1_B11", 2),
    MC("Pass laws required black South Africans to:", ["Carry a pass to move in certain areas", "Vote freely", "Own land freely", "Travel abroad"], "Carry a pass to move in certain areas",
      "Pass laws forced black South Africans to carry passes controlling their movement.", "ERR_SSSP_G9H4A1_B12", 2),
  ],
  // ── H4.A2 Soweto uprising ──
  "SSSP.G9.H4.A2": [
    MC("The Soweto uprising began on:", ["16 June 1976", "21 March 1960", "27 April 1994", "11 February 1990"], "16 June 1976",
      "The Soweto uprising began on 16 June 1976.", "ERR_SSSP_G9H4A2_B01", 1),
    TF("Students protested being forced to learn in Afrikaans.", "True",
      "A key grievance was the forced use of Afrikaans as a medium of instruction.", "ERR_SSSP_G9H4A2_B02", 1),
    MC("16 June is commemorated today as:", ["Youth Day", "Workers' Day", "Heritage Day", "Freedom Day"], "Youth Day",
      "16 June is Youth Day, honouring the 1976 students.", "ERR_SSSP_G9H4A2_B03", 2),
    CLOZE("The Soweto protests spread to other parts of the ____.", ["country", "ocean", "desert", "world only"], "country",
      "The protests spread across the country.", "ERR_SSSP_G9H4A2_B04", 2),
    TF("Many young people were killed during the Soweto uprising.", "True",
      "Police violence killed many young protesters during the uprising.", "ERR_SSSP_G9H4A2_B05", 2),
    MC("The uprising drew global attention to:", ["The injustice of apartheid", "South African gold", "WWII", "the space race"], "The injustice of apartheid",
      "Soweto drew international attention to apartheid's injustice.", "ERR_SSSP_G9H4A2_B06", 2),
    MC("A longer-term effect of 1976 was:", ["Stronger resistance to apartheid", "The end of all protest", "The start of mining", "Germany's defeat"], "Stronger resistance to apartheid",
      "Soweto energised resistance against apartheid.", "ERR_SSSP_G9H4A2_B07", 2),
    TF("The Soweto uprising was led mainly by school students.", "True",
      "School students led the 1976 Soweto uprising.", "ERR_SSSP_G9H4A2_B08", 1),
    MC("Why did students protest learning in Afrikaans?", ["They saw it as the language of the oppressor and a barrier to learning", "They preferred no school", "They wanted longer holidays", "It was too easy"], "They saw it as the language of the oppressor and a barrier to learning",
      "Students rejected Afrikaans-medium teaching as oppressive and a barrier to learning.", "ERR_SSSP_G9H4A2_B09", 3),
    CLOZE("The Soweto uprising happened in ____.", ["1976", "1960", "1948", "1994"], "1976",
      "The Soweto uprising occurred in 1976.", "ERR_SSSP_G9H4A2_B10", 1),
    TF("Young people played a major role in the struggle against apartheid.", "True",
      "Youth, especially in 1976, played a major role in the struggle.", "ERR_SSSP_G9H4A2_B11", 1),
    MC("The bravery of 1976 students is remembered to:", ["Honour their role in the struggle", "Forget the past", "Praise apartheid", "End all schools"], "Honour their role in the struggle",
      "Youth Day honours the students' role in the struggle.", "ERR_SSSP_G9H4A2_B12", 2),
  ],
  // ── H4.A3 Mandela & democracy ──
  "SSSP.G9.H4.A3": [
    MC("Nelson Mandela was released from prison in:", ["1990", "1976", "1960", "1948"], "1990",
      "Mandela was released in 1990.", "ERR_SSSP_G9H4A3_B01", 1),
    TF("The first democratic election in South Africa was in 1994.", "True",
      "South Africa's first democratic election was held in 1994.", "ERR_SSSP_G9H4A3_B02", 1),
    MC("Before 1994, who could not vote in national elections?", ["The black majority", "White South Africans", "Everyone", "No one"], "The black majority",
      "Under apartheid the black majority was denied the national vote.", "ERR_SSSP_G9H4A3_B03", 2),
    CLOZE("In 1990 the government ____ the ANC and other movements.", ["unbanned", "banned", "ignored", "joined"], "unbanned",
      "In 1990 the ANC and others were unbanned.", "ERR_SSSP_G9H4A3_B04", 2),
    TF("International sanctions put pressure on the apartheid government.", "True",
      "External pressure, including sanctions, helped push for change.", "ERR_SSSP_G9H4A3_B05", 2),
    MC("The transition to democracy involved:", ["Negotiations between leaders", "A foreign invasion", "A new world war", "The Scramble for Africa"], "Negotiations between leaders",
      "The transition involved negotiations, despite some violence.", "ERR_SSSP_G9H4A3_B06", 2),
    MC("Nelson Mandela became South Africa's:", ["First democratically elected president", "Last apartheid leader", "Gold-mine owner", "Army general"], "First democratically elected president",
      "Mandela became South Africa's first democratically elected president in 1994.", "ERR_SSSP_G9H4A3_B07", 2),
    TF("The end of apartheid was achieved by internal and external pressure together.", "True",
      "Both internal resistance and external pressure helped end apartheid.", "ERR_SSSP_G9H4A3_B08", 2),
    MC("The 1994 election was historic because:", ["All South Africans could vote for the first time", "Only some could vote", "No one voted", "It was cancelled"], "All South Africans could vote for the first time",
      "1994 was the first election in which all South Africans could vote.", "ERR_SSSP_G9H4A3_B09", 1),
    CLOZE("Mandela's autobiography is called Long Walk to ____.", ["Freedom", "Power", "Versailles", "Mecca"], "Freedom",
      "Mandela's autobiography is Long Walk to Freedom.", "ERR_SSSP_G9H4A3_B10", 2),
    TF("There was some violence during the transition years of 1990–1994.", "True",
      "The transition mixed negotiation with periods of violence before 1994.", "ERR_SSSP_G9H4A3_B11", 2),
    MC("The coming of democracy in 1994 is studied again in more depth in:", ["Grade 12", "Grade 1", "Grade 4", "never again"], "Grade 12",
      "The coming of democracy is revisited in detail in Grade 12.", "ERR_SSSP_G9H4A3_B12", 1),
  ],
  // ── G1.A1 Contour lines ──
  "SSSP.G9.G1.A1": [
    MC("Each contour line is labelled with a:", ["Height value", "Temperature", "Population", "Date"], "Height value",
      "Contour lines are labelled with their height above sea level.", "ERR_SSSP_G9G1A1_B01", 2),
    TF("Contour lines never cross each other.", "True",
      "Contour lines do not cross, because one point has only one height.", "ERR_SSSP_G9G1A1_B02", 3),
    MC("A hill is shown by contour lines that:", ["Form closed loops, higher in the centre", "Run in straight parallel lines", "Are coloured blue", "Cross each other"], "Form closed loops, higher in the centre",
      "A hill appears as closed contour loops with higher values inside.", "ERR_SSSP_G9G1A1_B03", 3),
    CLOZE("Contours that are close together show a ____ slope.", ["steep", "gentle", "flat", "downhill only"], "steep",
      "Closely spaced contours mean a steep slope.", "ERR_SSSP_G9G1A1_B04", 2),
    TF("A flat area has few or widely spaced contour lines.", "True",
      "Flat land has few, widely spaced contours.", "ERR_SSSP_G9G1A1_B05", 2),
    MC("Contour lines help us understand the land's:", ["Shape and height", "Temperature", "Population", "History"], "Shape and height",
      "Contours reveal the shape and height of the land.", "ERR_SSSP_G9G1A1_B06", 1),
    MC("A river valley shown by contours usually forms a:", ["V-shape pointing uphill", "Perfect circle", "Straight line", "Square"], "V-shape pointing uphill",
      "Contours crossing a valley make a V that points uphill (upstream).", "ERR_SSSP_G9G1A1_B07", 3),
    TF("The 'contour interval' is the height difference between contour lines.", "True",
      "The contour interval is the fixed height difference between successive contours.", "ERR_SSSP_G9G1A1_B08", 3),
    MC("A spur is:", ["A piece of high land sticking out", "A deep lake", "A type of road", "A city"], "A piece of high land sticking out",
      "A spur is high land that juts out, shown by contours pointing downhill.", "ERR_SSSP_G9G1A1_B09", 3),
    CLOZE("Contour lines join places of equal ____.", ["height", "rainfall", "population", "temperature"], "height",
      "Contour lines join points of equal height.", "ERR_SSSP_G9G1A1_B10", 1),
    TF("You can describe the gradient (steepness) of a slope from contour spacing.", "True",
      "Contour spacing tells you how steep or gentle a slope is.", "ERR_SSSP_G9G1A1_B11", 2),
    MC("Why are contour lines useful?", ["They show the shape of land on a flat map", "They show the weather", "They name the streets", "They give the time"], "They show the shape of land on a flat map",
      "Contours let a flat map show the 3D shape of the land.", "ERR_SSSP_G9G1A1_B12", 1),
  ],
  // ── G1.A2 Orthophoto maps ──
  "SSSP.G9.G1.A2": [
    MC("An orthophoto map combines a photo with:", ["Map accuracy and contour lines", "A weather report", "A globe", "A graph"], "Map accuracy and contour lines",
      "Orthophoto maps add map accuracy and contours to an aerial photo.", "ERR_SSSP_G9G1A2_B01", 2),
    TF("Orthophoto maps are corrected so distances are true to scale.", "True",
      "Orthophoto maps are corrected to scale, so distances are accurate.", "ERR_SSSP_G9G1A2_B02", 2),
    MC("Compared with a topographic map, an orthophoto map shows:", ["Real photographic detail", "Only symbols", "Only contours", "No detail"], "Real photographic detail",
      "Orthophoto maps show real photographic detail of an area.", "ERR_SSSP_G9G1A2_B03", 2),
    CLOZE("Orthophoto maps are made from ____ aerial photographs.", ["vertical", "oblique", "ground", "hand-drawn"], "vertical",
      "They are made from vertical aerial photographs.", "ERR_SSSP_G9G1A2_B04", 2),
    TF("Height is shown on an orthophoto map using contour lines.", "True",
      "Contour lines added to the orthophoto show height.", "ERR_SSSP_G9G1A2_B05", 2),
    MC("An advantage of an orthophoto map is that you can:", ["See real features and measure distances", "Smell the area", "Hear the traffic", "Taste the soil"], "See real features and measure distances",
      "You see real features and can measure true distances on an orthophoto map.", "ERR_SSSP_G9G1A2_B06", 2),
    MC("A common scale for orthophoto maps is:", ["1:10 000", "1:1 000 000", "1:2", "1:50"], "1:10 000",
      "Orthophoto maps are often at a large scale like 1:10 000.", "ERR_SSSP_G9G1A2_B07", 3),
    TF("Orthophoto maps and ordinary photos are exactly the same.", "False",
      "Unlike ordinary photos, orthophoto maps are corrected to scale with contours added.", "ERR_SSSP_G9G1A2_B08", 2),
    MC("Cross-referencing an orthophoto map and a topographic map helps you:", ["Understand an area more fully", "Change the land", "Predict elections", "Stop erosion"], "Understand an area more fully",
      "Using both together gives a fuller understanding of an area.", "ERR_SSSP_G9G1A2_B09", 2),
    CLOZE("An orthophoto map is corrected so distances are true to ____.", ["scale", "colour", "time", "weather"], "scale",
      "It is corrected to true scale.", "ERR_SSSP_G9G1A2_B10", 2),
    TF("Orthophoto maps are useful for planning and studying small areas in detail.", "True",
      "Their detail and accuracy make orthophoto maps useful for studying small areas.", "ERR_SSSP_G9G1A2_B11", 1),
    MC("Orthophoto maps help bridge the gap between a photo and a:", ["Topographic map", "Globe", "Graph", "Weather chart"], "Topographic map",
      "Orthophoto maps combine the strengths of a photo and a topographic map.", "ERR_SSSP_G9G1A2_B12", 3),
  ],
  // ── G1.A3 Topographic maps ──
  "SSSP.G9.G1.A3": [
    MC("A topographic map shows the shape of the land using:", ["Contour lines", "Photographs only", "Sound", "Colours of the sky"], "Contour lines",
      "Topographic maps use contour lines to show land shape and height.", "ERR_SSSP_G9G1A3_B01", 1),
    TF("Symbols on a topographic map stand for real features.", "True",
      "Map symbols represent real features; the key explains them.", "ERR_SSSP_G9G1A3_B02", 1),
    MC("On a 1:50 000 map, 4 cm represents:", ["2 km", "4 km", "50 km", "200 m"], "2 km",
      "1 cm = 0.5 km, so 4 cm = 2 km.", "ERR_SSSP_G9G1A3_B03", 3),
    CLOZE("A river is a ____ feature on a topographic map.", ["natural", "constructed", "weather", "human-made"], "natural",
      "Rivers are natural features.", "ERR_SSSP_G9G1A3_B04", 1),
    TF("Coordinates help locate an exact point on a topographic map.", "True",
      "Coordinates pinpoint exact positions on the map.", "ERR_SSSP_G9G1A3_B05", 2),
    MC("A dam shown on a topographic map is a:", ["Constructed feature", "Natural feature", "Weather symbol", "Contour line"], "Constructed feature",
      "A dam is a human-made (constructed) feature.", "ERR_SSSP_G9G1A3_B06", 2),
    MC("The line scale on a topographic map lets you:", ["Measure real distances", "Tell the time", "See the weather", "Read names only"], "Measure real distances",
      "The line scale lets you measure real distances on the map.", "ERR_SSSP_G9G1A3_B07", 2),
    TF("Height on a topographic map can be read from contour lines and spot heights.", "True",
      "Contour lines and spot heights show elevation on a topographic map.", "ERR_SSSP_G9G1A3_B08", 2),
    MC("To read a topographic map well, you first learn the:", ["Key (legend)", "Author", "Price", "Date"], "Key (legend)",
      "Learning the key first lets you interpret all the symbols.", "ERR_SSSP_G9G1A3_B09", 1),
    CLOZE("A 1:50 000 map means 1 cm represents ____ m on the ground.", ["500", "50", "5", "5000"], "500",
      "1:50 000 means 1 cm = 50 000 cm = 500 m.", "ERR_SSSP_G9G1A3_B10", 3),
    TF("Topographic maps show only natural features.", "False",
      "Topographic maps show both natural and constructed features.", "ERR_SSSP_G9G1A3_B11", 1),
    MC("Topographic maps are useful for:", ["Understanding the landscape and planning", "Cooking", "Telling jokes", "Playing music"], "Understanding the landscape and planning",
      "Topographic maps help understand landscapes and plan activities.", "ERR_SSSP_G9G1A3_B12", 1),
  ],
  // ── G1.A4 Interpreting maps and photographs ──
  "SSSP.G9.G1.A4": [
    MC("Describing a 'settlement pattern' means describing its:", ["Shape, size and location", "Temperature", "History", "Population's ages"], "Shape, size and location",
      "Settlement pattern covers the shape, size and location of a settlement.", "ERR_SSSP_G9G1A4_B01", 2),
    TF("A map shows height well, while a photo shows real detail well.", "True",
      "Maps show height (contours); photos show real detail — they complement each other.", "ERR_SSSP_G9G1A4_B02", 2),
    MC("Cross-referencing sources means:", ["Comparing information from more than one source", "Using only one source", "Ignoring sources", "Drawing only"], "Comparing information from more than one source",
      "Cross-referencing compares information across sources.", "ERR_SSSP_G9G1A4_B03", 2),
    CLOZE("Whether land is used for farming or housing is its land ____.", ["use", "height", "scale", "symbol"], "use",
      "Land use is how an area of land is used.", "ERR_SSSP_G9G1A4_B04", 1),
    TF("Maps and photos of the same area must always match exactly to be useful.", "False",
      "It helps but isn't essential — comparing an area shown different ways is still worthwhile.", "ERR_SSSP_G9G1A4_B05", 3),
    MC("A large settlement spread out along a road has a settlement shape that is:", ["Linear (in a line)", "Circular", "Random dots", "Underground"], "Linear (in a line)",
      "A settlement strung along a road has a linear shape.", "ERR_SSSP_G9G1A4_B06", 3),
    MC("Combining a map and a photo helps you:", ["Build a fuller picture of the area", "Change the weather", "Cause floods", "Predict prices"], "Build a fuller picture of the area",
      "Together they give a fuller, cross-checked picture of the area.", "ERR_SSSP_G9G1A4_B07", 2),
    TF("You can identify land use from both maps and photographs.", "True",
      "Both maps and photos can reveal how land is used.", "ERR_SSSP_G9G1A4_B08", 1),
    MC("Describing the 'landscape' means describing the land's:", ["Shape and features", "Smell", "History only", "Future prices"], "Shape and features",
      "Landscape description covers the land's shape and features.", "ERR_SSSP_G9G1A4_B09", 1),
    CLOZE("A settlement's ____ tells you whether it is large or small.", ["size", "smell", "age", "religion"], "size",
      "Size tells you how large or small a settlement is.", "ERR_SSSP_G9G1A4_B10", 1),
    TF("Interpreting maps and photos is an important geographical skill.", "True",
      "Reading and comparing maps and photos is a key geographical skill.", "ERR_SSSP_G9G1A4_B11", 1),
    MC("Why use several sources together?", ["Each shows different useful information", "To waste time", "To confuse people", "There is no reason"], "Each shows different useful information",
      "Different sources reveal different information, giving a fuller understanding.", "ERR_SSSP_G9G1A4_B12", 2),
  ],
  // ── G2.A1 Meaning and measuring development ──
  "SSSP.G9.G2.A1": [
    MC("A more developed country usually has:", ["Higher income, health and education", "No schools", "No hospitals", "Lower life expectancy"], "Higher income, health and education",
      "More developed countries tend to have higher income, health and education.", "ERR_SSSP_G9G2A1_B01", 1),
    TF("The HDI gives a score between 0 and 1.", "True",
      "The HDI ranges from 0 (low) to 1 (high development).", "ERR_SSSP_G9G2A1_B02", 2),
    MC("Life expectancy is part of the HDI because it reflects:", ["Health", "Wealth only", "Map scale", "Climate"], "Health",
      "Life expectancy reflects a population's health, part of the HDI.", "ERR_SSSP_G9G2A1_B03", 2),
    CLOZE("The Human Development ____ measures development.", ["Index", "Map", "Scale", "Treaty"], "Index",
      "The Human Development Index (HDI) measures development.", "ERR_SSSP_G9G2A1_B04", 1),
    TF("Development is only about money.", "False",
      "Development includes health, education and well-being, not just money.", "ERR_SSSP_G9G2A1_B05", 1),
    MC("Education is part of the HDI because it reflects:", ["Knowledge and skills in a population", "The weather", "Map scale", "Gold reserves"], "Knowledge and skills in a population",
      "Education levels reflect a population's knowledge and skills.", "ERR_SSSP_G9G2A1_B06", 2),
    MC("A country with HDI of 0.40 is generally:", ["Less developed", "Highly developed", "Average", "Unmeasurable"], "Less developed",
      "An HDI of 0.40 indicates lower development.", "ERR_SSSP_G9G2A1_B07", 2),
    TF("Comparing HDI scores helps rank countries by development.", "True",
      "HDI scores let us compare and rank countries' development.", "ERR_SSSP_G9G2A1_B08", 2),
    MC("Development also has an ____ side, like protecting the environment.", ["environmental", "musical", "imaginary", "historical only"], "environmental",
      "True development includes an environmental dimension.", "ERR_SSSP_G9G2A1_B09", 2),
    CLOZE("The HDI combines income, education and ____.", ["life expectancy", "rainfall", "altitude", "longitude"], "life expectancy",
      "HDI blends income, education and life expectancy.", "ERR_SSSP_G9G2A1_B10", 2),
    TF("A high life expectancy usually goes with good health care.", "True",
      "Good health care tends to raise life expectancy.", "ERR_SSSP_G9G2A1_B11", 1),
    MC("Why measure development with more than just income?", ["A fuller picture of people's well-being", "To confuse people", "There is no reason", "To raise prices"], "A fuller picture of people's well-being",
      "Using health and education too gives a fuller picture of well-being.", "ERR_SSSP_G9G2A1_B12", 2),
  ],
  // ── G2.A2 Factors affecting development ──
  "SSSP.G9.G2.A2": [
    MC("Colonialism affected development by:", ["Shaping economies to serve colonisers", "Helping all colonies equally", "Having no effect", "Building free hospitals"], "Shaping economies to serve colonisers",
      "Colonial economies were shaped to serve the colonisers, affecting later development.", "ERR_SSSP_G9G2A2_B01", 2),
    TF("Good education and health care support a country's development.", "True",
      "Strong education and health care help development.", "ERR_SSSP_G9G2A2_B02", 1),
    MC("Political instability tends to:", ["Hold back development", "Speed up development", "Have no effect", "Build schools"], "Hold back development",
      "Instability and conflict hold back development.", "ERR_SSSP_G9G2A2_B03", 2),
    CLOZE("Unfair ____ can keep some countries poorer.", ["trade", "weather", "maps", "rivers"], "trade",
      "Unfair trade can keep countries poorer.", "ERR_SSSP_G9G2A2_B04", 2),
    TF("Technology and industry can boost a country's development.", "True",
      "Access to technology and industry can boost development.", "ERR_SSSP_G9G2A2_B05", 1),
    MC("There is usually no single cause of underdevelopment because:", ["Many factors interact", "Only gold matters", "Only weather matters", "It is random"], "Many factors interact",
      "Underdevelopment comes from many interacting factors.", "ERR_SSSP_G9G2A2_B06", 2),
    MC("Better health care helps development by:", ["Keeping people healthy and productive", "Lowering education", "Causing war", "Raising prices"], "Keeping people healthy and productive",
      "Healthy people are more productive, aiding development.", "ERR_SSSP_G9G2A2_B07", 2),
    TF("History, like colonialism, can still affect development today.", "True",
      "Historical factors like colonialism continue to shape development.", "ERR_SSSP_G9G2A2_B08", 2),
    MC("War harms development because it:", ["Destroys lives, infrastructure and stability", "Builds schools", "Improves trade", "Raises life expectancy"], "Destroys lives, infrastructure and stability",
      "War destroys lives, infrastructure and stability, harming development.", "ERR_SSSP_G9G2A2_B09", 2),
    CLOZE("Political ____ provides the security needed for development.", ["stability", "instability", "conflict", "war"], "stability",
      "Political stability provides security for development.", "ERR_SSSP_G9G2A2_B10", 2),
    TF("All countries developed in exactly the same way.", "False",
      "Countries developed differently because of different histories and factors.", "ERR_SSSP_G9G2A2_B11", 1),
    MC("Understanding the factors helps us see development as:", ["Complex, with many causes", "Simple and random", "Caused by one thing", "Impossible to study"], "Complex, with many causes",
      "Development is complex, shaped by many causes.", "ERR_SSSP_G9G2A2_B12", 3),
  ],
  // ── G2.A3 Opportunities for development ──
  "SSSP.G9.G2.A3": [
    MC("Fairer trade helps poorer countries by giving them:", ["Better prices for their goods", "Lower prices", "No trade", "More debt"], "Better prices for their goods",
      "Fairer trade gives developing countries better prices for their goods.", "ERR_SSSP_G9G2A3_B01", 2),
    TF("Sustainable development tries not to harm future generations.", "True",
      "Sustainable development meets today's needs without harming the future.", "ERR_SSSP_G9G2A3_B02", 2),
    MC("Alternative development means countries can:", ["Follow paths other than heavy industrialisation", "Only build factories", "Stop developing", "Mine only gold"], "Follow paths other than heavy industrialisation",
      "Alternative development explores paths beyond heavy industrialisation.", "ERR_SSSP_G9G2A3_B03", 3),
    CLOZE("Development that lasts and protects the future is ____ development.", ["sustainable", "rapid", "unfair", "colonial"], "sustainable",
      "Sustainable development can continue without harming the future.", "ERR_SSSP_G9G2A3_B04", 1),
    TF("Community-based projects can support local development.", "True",
      "Local, community-based projects are one route to development.", "ERR_SSSP_G9G2A3_B05", 1),
    MC("A critical view of development asks whether it truly:", ["Improves quality of life and respects the planet", "Only builds factories", "Is always good", "Cannot be judged"], "Improves quality of life and respects the planet",
      "A critical view asks if development really improves lives and respects the planet.", "ERR_SSSP_G9G2A3_B06", 3),
    MC("Education and training programmes help development by:", ["Building people's skills", "Lowering skills", "Causing war", "Raising prices"], "Building people's skills",
      "Education and training build the skills a country needs to develop.", "ERR_SSSP_G9G2A3_B07", 2),
    TF("More equal trade relationships can create development opportunities.", "True",
      "Fairer trade creates opportunities for development.", "ERR_SSSP_G9G2A3_B08", 2),
    MC("Sustainable development balances economic, social and:", ["Environmental needs", "Only profit", "Only factories", "Only gold"], "Environmental needs",
      "Sustainable development balances economic, social and environmental needs.", "ERR_SSSP_G9G2A3_B09", 2),
    CLOZE("Rural ____ programmes can improve life in the countryside.", ["development", "decline", "pollution", "erosion"], "development",
      "Rural development programmes improve life in rural areas.", "ERR_SSSP_G9G2A3_B10", 2),
    TF("There is only one way for every country to develop.", "False",
      "Countries can develop in different ways suited to their situations.", "ERR_SSSP_G9G2A3_B11", 2),
    MC("Opportunities for development include:", ["Fair trade, sustainability and community projects", "More war", "Less education", "Unfair trade"], "Fair trade, sustainability and community projects",
      "Fairer trade, sustainability and community projects are development opportunities.", "ERR_SSSP_G9G2A3_B12", 2),
  ],
  // ── G3.A1 Weathering ──
  "SSSP.G9.G3.A1": [
    MC("Weathering breaks down rock:", ["Where it is, without moving it", "By carrying it away", "By building mountains", "By heating the core"], "Where it is, without moving it",
      "Weathering breaks rock in place; moving it is erosion.", "ERR_SSSP_G9G3A1_B01", 1),
    TF("Freeze-thaw is a kind of physical weathering.", "True",
      "Water freezing and thawing in cracks (freeze-thaw) is physical weathering.", "ERR_SSSP_G9G3A1_B02", 2),
    MC("Acid rain dissolving rock is an example of:", ["Chemical weathering", "Physical weathering", "Biological weathering", "Erosion"], "Chemical weathering",
      "Acid reacting with rock is chemical weathering.", "ERR_SSSP_G9G3A1_B03", 2),
    CLOZE("Tree roots breaking rock apart is ____ weathering.", ["biological", "physical", "chemical", "wind"], "biological",
      "Living things breaking rock is biological weathering.", "ERR_SSSP_G9G3A1_B04", 2),
    TF("Mining and pollution can speed up weathering.", "True",
      "Human activities like mining and pollution can speed up weathering.", "ERR_SSSP_G9G3A1_B05", 2),
    MC("Physical weathering changes rock by:", ["Breaking it into smaller pieces", "Changing its chemistry", "Moving it downhill", "Melting it"], "Breaking it into smaller pieces",
      "Physical weathering breaks rock into smaller pieces without changing its chemistry.", "ERR_SSSP_G9G3A1_B06", 2),
    MC("Chemical weathering changes the rock's:", ["Minerals", "Size only", "Location", "Colour only"], "Minerals",
      "Chemical weathering changes the minerals that make up the rock.", "ERR_SSSP_G9G3A1_B07", 2),
    TF("Weathering and erosion are exactly the same thing.", "False",
      "Weathering breaks rock in place; erosion moves it — they are different.", "ERR_SSSP_G9G3A1_B08", 1),
    MC("Rust forming on rock containing iron is an example of:", ["Chemical weathering", "Physical weathering", "Erosion", "Deposition"], "Chemical weathering",
      "Rusting (oxidation) is a chemical weathering process.", "ERR_SSSP_G9G3A1_B09", 3),
    CLOZE("Weathering breaks rock ____ it is, without moving it.", ["where", "after", "before", "while"], "where",
      "Weathering breaks rock where it is.", "ERR_SSSP_G9G3A1_B10", 1),
    TF("Plants and animals can cause biological weathering.", "True",
      "Living things, like roots and burrowing animals, cause biological weathering.", "ERR_SSSP_G9G3A1_B11", 1),
    MC("Why is weathering important?", ["It helps form soil and shape landscapes", "It causes elections", "It tells the time", "It has no effect"], "It helps form soil and shape landscapes",
      "Weathering helps form soil and shape the landscape over time.", "ERR_SSSP_G9G3A1_B12", 2),
  ],
  // ── G3.A2 Erosion and deposition ──
  "SSSP.G9.G3.A2": [
    MC("Erosion is the process of:", ["Wearing away and carrying off material", "Breaking rock in place", "Building mountains", "Heating the core"], "Wearing away and carrying off material",
      "Erosion wears away and transports material; weathering just breaks it in place.", "ERR_SSSP_G9G3A2_B01", 1),
    TF("A river can both erode and deposit material along its course.", "True",
      "Rivers erode in some places and deposit material in others.", "ERR_SSSP_G9G3A2_B02", 2),
    MC("Waves wearing away a cliff is an example of:", ["Coastal erosion", "Deposition", "Weathering only", "Volcanism"], "Coastal erosion",
      "Waves wearing away a cliff is erosion by the sea.", "ERR_SSSP_G9G3A2_B03", 2),
    CLOZE("Material dropped by a river at its mouth can form a ____.", ["delta", "cliff", "dune", "mountain"], "delta",
      "A delta forms from river deposition at the mouth.", "ERR_SSSP_G9G3A2_B04", 3),
    TF("Wind can shape the land by erosion and deposition.", "True",
      "Wind erodes loose material and deposits it, e.g. as dunes.", "ERR_SSSP_G9G3A2_B05", 2),
    MC("Glaciers (moving ice) shape land by:", ["Eroding and depositing material", "Heating rock", "Causing earthquakes", "Doing nothing"], "Eroding and depositing material",
      "Glaciers erode the land and deposit material as they move and melt.", "ERR_SSSP_G9G3A2_B06", 3),
    MC("Deposition is when carried material is:", ["Dropped in a new place", "Broken up", "Heated", "Carried away forever"], "Dropped in a new place",
      "Deposition drops carried material in a new place.", "ERR_SSSP_G9G3A2_B07", 1),
    TF("Sand dunes are formed by wind deposition.", "True",
      "Wind deposits sand to build dunes.", "ERR_SSSP_G9G3A2_B08", 2),
    MC("Which agent of erosion is most important in a desert?", ["Wind", "Ice", "Heavy river flow", "Snow"], "Wind",
      "In dry deserts, wind is a major agent of erosion and deposition.", "ERR_SSSP_G9G3A2_B09", 3),
    CLOZE("Rivers, sea, ice and ____ are all agents of erosion.", ["wind", "fire", "light", "sound"], "wind",
      "Wind, along with rivers, sea and ice, erodes the land.", "ERR_SSSP_G9G3A2_B10", 1),
    TF("Erosion and deposition together reshape the Earth's surface over time.", "True",
      "Erosion and deposition continually reshape landscapes over time.", "ERR_SSSP_G9G3A2_B11", 1),
    MC("The difference between erosion and weathering is that erosion:", ["Moves material; weathering breaks it in place", "Breaks it in place", "Builds rock", "Melts rock"], "Moves material; weathering breaks it in place",
      "Erosion transports material; weathering breaks it where it is.", "ERR_SSSP_G9G3A2_B12", 2),
  ],
  // ── G3.A3 People and soil erosion ──
  "SSSP.G9.G3.A3": [
    MC("Soil erosion is harmful because it:", ["Removes fertile topsoil needed for farming", "Adds more soil", "Cools the land", "Builds mountains"], "Removes fertile topsoil needed for farming",
      "Erosion strips fertile topsoil, harming farming.", "ERR_SSSP_G9G3A3_B01", 1),
    TF("Overgrazing removes the plants that protect the soil.", "True",
      "Too many animals strip plant cover, exposing soil to erosion.", "ERR_SSSP_G9G3A3_B02", 2),
    MC("Ploughing straight down a steep slope can:", ["Speed up soil erosion", "Stop erosion", "Add nutrients", "Cool the soil"], "Speed up soil erosion",
      "Ploughing down a slope lets water run fast and erode soil.", "ERR_SSSP_G9G3A3_B03", 3),
    CLOZE("Plant ____ helps hold soil in place and reduce erosion.", ["cover", "removal", "burning", "cutting"], "cover",
      "Plant cover holds soil and reduces erosion.", "ERR_SSSP_G9G3A3_B04", 2),
    TF("Construction and mining can cause soil erosion.", "True",
      "Clearing land for construction and mining exposes soil to erosion.", "ERR_SSSP_G9G3A3_B05", 2),
    MC("One way to reduce soil erosion on a slope is:", ["Planting along the contour or terracing", "Removing all plants", "Ploughing down the slope", "Overgrazing"], "Planting along the contour or terracing",
      "Contour planting and terracing slow water and reduce erosion.", "ERR_SSSP_G9G3A3_B06", 3),
    MC("Soil erosion can reduce a region's:", ["Ability to grow food", "Number of volcanoes", "Map scale", "Time zones"], "Ability to grow food",
      "Eroded soil grows less food, threatening food supply.", "ERR_SSSP_G9G3A3_B07", 2),
    TF("Wind can also cause soil erosion on bare land.", "True",
      "Wind blows away soil from bare, dry land.", "ERR_SSSP_G9G3A3_B08", 1),
    MC("Trees help reduce soil erosion because their roots:", ["Hold the soil together", "Loosen the soil", "Heat the soil", "Remove the soil"], "Hold the soil together",
      "Tree roots bind the soil, reducing erosion.", "ERR_SSSP_G9G3A3_B09", 2),
    CLOZE("Putting too many animals on land causes ____.", ["overgrazing", "reforestation", "irrigation", "terracing"], "overgrazing",
      "Too many animals on the land causes overgrazing and erosion.", "ERR_SSSP_G9G3A3_B10", 2),
    TF("People can both cause and reduce soil erosion.", "True",
      "Human actions can cause erosion or, with care, reduce it.", "ERR_SSSP_G9G3A3_B11", 1),
    MC("A case study of agriculture and erosion shows that farming can:", ["Damage soil if done poorly", "Never affect soil", "Always improve soil", "Cause earthquakes"], "Damage soil if done poorly",
      "Poor farming can damage soil through erosion.", "ERR_SSSP_G9G3A3_B12", 2),
  ],
  // ── G4.A1 Resource use ──
  "SSSP.G9.G4.A1": [
    MC("Solar and wind energy are examples of:", ["Renewable resources", "Non-renewable resources", "Minerals", "Fossil fuels"], "Renewable resources",
      "Sun and wind are renewable — they don't run out.", "ERR_SSSP_G9G4A1_B01", 1),
    TF("Fossil fuels like coal and oil are non-renewable.", "True",
      "Coal and oil take millions of years to form and cannot be quickly replaced.", "ERR_SSSP_G9G4A1_B02", 1),
    MC("Over-grazing damages land by:", ["Removing too much plant cover", "Adding plants", "Cooling the soil", "Building soil"], "Removing too much plant cover",
      "Over-grazing strips plant cover, damaging the land.", "ERR_SSSP_G9G4A1_B03", 2),
    CLOZE("Resources that can be replaced if used carefully are ____.", ["renewable", "non-renewable", "endless", "wasted"], "renewable",
      "Renewable resources can be replaced if used carefully.", "ERR_SSSP_G9G4A1_B04", 1),
    TF("Over-fishing can collapse fish populations.", "True",
      "Catching fish faster than they breed can collapse their populations.", "ERR_SSSP_G9G4A1_B05", 2),
    MC("Why should non-renewable resources be used carefully?", ["They cannot be replaced once used up", "They refill instantly", "They are endless", "They are worthless"], "They cannot be replaced once used up",
      "Non-renewables are finite, so careful use matters.", "ERR_SSSP_G9G4A1_B06", 2),
    MC("Water can be a renewable resource if it is:", ["Used and managed carefully", "Wasted freely", "Polluted heavily", "Never used"], "Used and managed carefully",
      "Water can renew if used and managed carefully, but can be over-used or polluted.", "ERR_SSSP_G9G4A1_B07", 3),
    TF("Unwise use of resources can harm the environment.", "True",
      "Using resources unwisely damages the environment.", "ERR_SSSP_G9G4A1_B08", 1),
    MC("Coal is used mainly to:", ["Produce energy", "Grow food", "Clean water", "Build roads only"], "Produce energy",
      "Coal is burned mainly to produce energy.", "ERR_SSSP_G9G4A1_B09", 2),
    CLOZE("Once used up, ____ resources cannot be replaced.", ["non-renewable", "renewable", "solar", "wind"], "non-renewable",
      "Non-renewable resources cannot be replaced once used up.", "ERR_SSSP_G9G4A1_B10", 1),
    TF("Renewable resources can still be damaged if used carelessly.", "True",
      "Even renewable resources (like fish or water) can be harmed by careless use.", "ERR_SSSP_G9G4A1_B11", 2),
    MC("The effects of unwise resource use include:", ["Over-fishing and over-grazing", "More resources", "Cleaner oceans", "Richer soil"], "Over-fishing and over-grazing",
      "Over-fishing and over-grazing are effects of unwise resource use.", "ERR_SSSP_G9G4A1_B12", 2),
  ],
  // ── G4.A2 Sustainable use of resources ──
  "SSSP.G9.G4.A2": [
    MC("Sustainable use means using resources so they:", ["Last into the future", "Run out fast", "Are wasted", "Disappear"], "Last into the future",
      "Sustainable use keeps resources available for the future.", "ERR_SSSP_G9G4A2_B01", 1),
    TF("Recycling helps reduce pressure on resources.", "True",
      "Recycling reuses materials, reducing pressure on resources.", "ERR_SSSP_G9G4A2_B02", 1),
    MC("Sustainable fishing means catching fish:", ["At a rate they can replace", "Faster than they breed", "Until none are left", "Only at night"], "At a rate they can replace",
      "Sustainable fishing keeps catches within the rate fish can replace.", "ERR_SSSP_G9G4A2_B03", 2),
    CLOZE("'Reduce, reuse and ____' is a guide to sustainable living.", ["recycle", "remove", "ruin", "rush"], "recycle",
      "Reduce, reuse and recycle guide sustainable living.", "ERR_SSSP_G9G4A2_B04", 1),
    TF("Governments, businesses and individuals all have a role in sustainability.", "True",
      "Everyone — governments, businesses and individuals — can choose sustainable use.", "ERR_SSSP_G9G4A2_B05", 1),
    MC("Lowering your carbon footprint means:", ["Releasing less carbon through your choices", "Walking less", "Using more energy", "Cutting more trees"], "Releasing less carbon through your choices",
      "A lower carbon footprint means choices that release less carbon.", "ERR_SSSP_G9G4A2_B06", 2),
    MC("Sustainable grazing means:", ["Not putting too many animals on the land", "Adding as many animals as possible", "Removing all plants", "Ploughing slopes"], "Not putting too many animals on the land",
      "Limiting animal numbers prevents overgrazing — sustainable grazing.", "ERR_SSSP_G9G4A2_B07", 2),
    TF("Sustainability balances environmental, social and economic needs.", "True",
      "Sustainability balances environmental, social and economic needs together.", "ERR_SSSP_G9G4A2_B08", 2),
    MC("Using renewable energy like solar power is more sustainable because it:", ["Does not run out", "Runs out quickly", "Pollutes heavily", "Costs the Earth nothing to ignore"], "Does not run out",
      "Renewable energy like solar does not run out, making it sustainable.", "ERR_SSSP_G9G4A2_B09", 2),
    CLOZE("Sustainable use meets today's needs without harming the ____.", ["future", "past", "present only", "weather"], "future",
      "Sustainable use protects the future while meeting present needs.", "ERR_SSSP_G9G4A2_B10", 1),
    TF("Individuals can do nothing to help sustainability.", "False",
      "Individuals can save energy, recycle and choose wisely to help sustainability.", "ERR_SSSP_G9G4A2_B11", 1),
    MC("Why aim for sustainable resource use?", ["So resources remain for future generations", "To use everything now", "To pollute more", "There is no reason"], "So resources remain for future generations",
      "Sustainable use ensures resources remain for the future.", "ERR_SSSP_G9G4A2_B12", 2),
  ],
  // ── G4.A3 Food resources and food security ──
  "SSSP.G9.G4.A3": [
    MC("Food security means people:", ["Reliably have enough safe food", "Grow only one crop", "Never eat", "Import all food"], "Reliably have enough safe food",
      "Food security means reliable access to enough safe food.", "ERR_SSSP_G9G4A3_B01", 1),
    TF("Technology can help increase food production.", "True",
      "New technology and methods can raise food production.", "ERR_SSSP_G9G4A3_B02", 1),
    MC("Factory farming raises animals:", ["At high density", "In tiny numbers", "In the wild only", "In the sea"], "At high density",
      "Factory farming raises livestock at high density.", "ERR_SSSP_G9G4A3_B03", 2),
    CLOZE("Changing crops in a lab to improve them is genetic ____.", ["modification", "erosion", "weathering", "trade"], "modification",
      "Genetic modification changes crops to improve traits.", "ERR_SSSP_G9G4A3_B04", 3),
    TF("Sustainable farming aims to protect the land for the future.", "True",
      "Sustainable farming produces food while protecting the land long-term.", "ERR_SSSP_G9G4A3_B05", 2),
    MC("A concern about factory farming is:", ["Animal welfare and the environment", "Too little food", "No resources used", "It is illegal everywhere"], "Animal welfare and the environment",
      "Factory farming raises concerns about animal welfare and environmental impact.", "ERR_SSSP_G9G4A3_B06", 3),
    MC("Food security can be measured at the local, regional and ____ levels.", ["global", "underground", "underwater", "imaginary"], "global",
      "Food security applies at local, regional and global levels.", "ERR_SSSP_G9G4A3_B07", 2),
    TF("Every method of producing food has both advantages and disadvantages.", "True",
      "Each food-production method has trade-offs to weigh up.", "ERR_SSSP_G9G4A3_B08", 2),
    MC("Genetic modification of crops is:", ["Debated, with benefits and concerns", "Always harmful", "Always perfect", "Never used"], "Debated, with benefits and concerns",
      "GM crops are debated, with both benefits and concerns.", "ERR_SSSP_G9G4A3_B09", 3),
    CLOZE("Having reliable access to enough safe food is food ____.", ["security", "scale", "trade", "erosion"], "security",
      "Reliable access to enough safe food is food security.", "ERR_SSSP_G9G4A3_B10", 1),
    TF("Sustainable farming and food security are linked goals.", "True",
      "Sustainable farming supports long-term food security.", "ERR_SSSP_G9G4A3_B11", 2),
    MC("Thinking critically about food production means weighing:", ["Social, environmental, health and ethical issues", "Only profit", "Only taste", "Nothing"], "Social, environmental, health and ethical issues",
      "Food production should be judged on social, environmental, health and ethical grounds.", "ERR_SSSP_G9G4A3_B12", 3),
  ],
};

export default G9B;
