// ─── Social Sciences SP — Grade 8 question pools, batch B ─────────────────────
// Appended to sssp-g8.mjs to bring each pool to ~20. New angles; no repeats.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8B = {
  // ── H1.A1 Changes during the Industrial Revolution in Britain ──
  "SSSP.G8.H1.A1": [
    MC("The Industrial Revolution began in which country?", ["Britain", "South Africa", "Mali", "Japan"], "Britain",
      "The Industrial Revolution began in Britain before spreading.", "ERR_SSSP_G8H1A1_B01", 1),
    TF("Steam power was an important new technology of the Industrial Revolution.", "True",
      "Steam engines powered factories, mines and transport during the Industrial Revolution.", "ERR_SSSP_G8H1A1_B02", 2),
    MC("Factories brought many workers together in one place to use:", ["Machines", "Camels", "Sailing ships", "Spears"], "Machines",
      "Factories gathered workers to operate machines under one roof.", "ERR_SSSP_G8H1A1_B03", 1),
    CLOZE("Many people moved from the countryside to ____ to find factory work.", ["cities", "deserts", "oceans", "forests"], "cities",
      "Workers moved to growing industrial cities for factory jobs.", "ERR_SSSP_G8H1A1_B04", 1),
    TF("Working-class housing in industrial cities was often overcrowded.", "True",
      "Rapid city growth led to overcrowded, poor working-class housing.", "ERR_SSSP_G8H1A1_B05", 1),
    MC("Child labour in mills and mines was:", ["Common and dangerous", "Rare and safe", "Illegal from the start", "Well paid"], "Common and dangerous",
      "Children worked long, dangerous hours in mills and mines.", "ERR_SSSP_G8H1A1_B06", 2),
    MC("The Swing Riots were protests by:", ["Agricultural workers", "Factory owners", "Sailors", "Bankers"], "Agricultural workers",
      "The Swing Riots were protests by farm (agricultural) workers.", "ERR_SSSP_G8H1A1_B07", 3),
    TF("Trade unions were formed to protect workers' interests.", "True",
      "Workers formed unions to push for better wages and conditions.", "ERR_SSSP_G8H1A1_B08", 1),
    MC("The Grand National Consolidated Trades Union (1833) was an early:", ["Workers' organisation", "Mining company", "Government", "Bank"], "Workers' organisation",
      "It was an early large-scale workers' union.", "ERR_SSSP_G8H1A1_B09", 3),
    CLOZE("Before factories, goods were made by hand in small ____ industries.", ["cottage", "factory", "mining", "shipping"], "cottage",
      "Cottage industries made goods by hand at home before factories.", "ERR_SSSP_G8H1A1_B10", 2),
    TF("The Industrial Revolution had both positive and negative effects on people's lives.", "True",
      "It brought new goods and wealth but also poverty, pollution and harsh working conditions.", "ERR_SSSP_G8H1A1_B11", 2),
    MC("Industrialisation increased Britain's:", ["Power and wealth", "Deserts", "Sailing only", "Farming only"], "Power and wealth",
      "Industrialisation made Britain wealthier and more powerful.", "ERR_SSSP_G8H1A1_B12", 1),
  ],
  // ── H1.A2 Southern Africa by 1860 ──
  "SSSP.G8.H1.A2": [
    MC("Indentured Indian labourers worked mainly on which crop in Natal?", ["Sugar", "Wheat", "Cotton", "Rice"], "Sugar",
      "They worked the sugar plantations of Natal.", "ERR_SSSP_G8H1A2_B01", 1),
    TF("Natal was a British colony.", "True",
      "Natal was under British colonial control.", "ERR_SSSP_G8H1A2_B02", 1),
    MC("Indentured labourers signed contracts to work for:", ["A fixed number of years", "One day", "Their whole life with pay", "No time at all"], "A fixed number of years",
      "Indenture bound workers for a fixed term of years.", "ERR_SSSP_G8H1A2_B03", 2),
    CLOZE("Indian labour was imported partly because the ____ kingdom was still independent.", ["Zulu", "Xhosa", "Sotho", "Tswana"], "Zulu",
      "With the Zulu kingdom independent, local labour was hard to force, so labour was imported.", "ERR_SSSP_G8H1A2_B04", 3),
    TF("Some Indians came to South Africa as free 'passenger' immigrants.", "True",
      "Passenger Indians paid their own way, often as traders, unlike indentured labourers.", "ERR_SSSP_G8H1A2_B05", 2),
    MC("Demand for sugar came mainly from:", ["Britain", "Mali", "the Sahara", "Antarctica"], "Britain",
      "British demand for sugar drove Natal's sugar industry.", "ERR_SSSP_G8H1A2_B06", 2),
    MC("Indentured labourers' conditions were:", ["Hard and tightly controlled", "Luxurious", "Completely free", "Like owning a farm"], "Hard and tightly controlled",
      "Indentured workers faced hard, tightly controlled conditions.", "ERR_SSSP_G8H1A2_B07", 2),
    TF("Indian immigration added to the diversity of South Africa's population.", "True",
      "Indian immigration contributed to South Africa's diverse population.", "ERR_SSSP_G8H1A2_B08", 1),
    MC("India and Natal were linked because both were part of the:", ["British Empire", "Dutch Republic", "Mali kingdom", "Roman Empire"], "British Empire",
      "Both being in the British Empire allowed labour to move between them.", "ERR_SSSP_G8H1A2_B09", 2),
    CLOZE("Workers bound by contract for a set term were called ____ labourers.", ["indentured", "free", "skilled", "migrant"], "indentured",
      "These were indentured labourers.", "ERR_SSSP_G8H1A2_B10", 1),
    TF("Passenger Indians were exactly the same as indentured labourers.", "False",
      "Passenger Indians paid their own way and were not bound by indenture contracts.", "ERR_SSSP_G8H1A2_B11", 2),
    MC("The 'Passenger Indians' arrived from:", ["1869 onwards", "1652", "1948", "1994"], "1869 onwards",
      "Passenger Indians came from 1869 onwards.", "ERR_SSSP_G8H1A2_B12", 3),
  ],
  // ── H1.A3 Diamond mining in Kimberley ──
  "SSSP.G8.H1.A3": [
    MC("Diamonds are valued because they are:", ["Rare and very hard", "Common and soft", "Easy to make", "Used as food"], "Rare and very hard",
      "Diamonds are rare and the hardest natural material, making them valuable.", "ERR_SSSP_G8H1A3_B01", 1),
    TF("As diggings got deeper, mining needed more money and machinery.", "True",
      "Deeper mining required heavy investment, favouring big companies.", "ERR_SSSP_G8H1A3_B02", 2),
    MC("The 'one person, one claim' rule changed as:", ["Big companies bought up claims", "Everyone stayed equal", "Mining stopped", "Claims were banned"], "Big companies bought up claims",
      "Over time, big companies bought out small claimholders.", "ERR_SSSP_G8H1A3_B03", 2),
    CLOZE("Cecil John Rhodes formed the company ____ Consolidated Mines.", ["De Beers", "Anglo", "VOC", "Union"], "De Beers",
      "Rhodes formed De Beers Consolidated Mines.", "ERR_SSSP_G8H1A3_B04", 1),
    TF("A monopoly let companies control the price of diamonds.", "True",
      "Controlling supply through monopoly let companies keep diamond prices high.", "ERR_SSSP_G8H1A3_B05", 2),
    MC("Kimberley is famous for its huge man-made hole called the:", ["Big Hole", "Grand Canyon", "Great Rift", "Blue Lagoon"], "Big Hole",
      "Kimberley's 'Big Hole' is the famous diamond-mining excavation.", "ERR_SSSP_G8H1A3_B06", 3),
    MC("Diamond wealth increased Britain's interest in:", ["Controlling South Africa", "Leaving Africa", "Mining in Britain only", "Farming"], "Controlling South Africa",
      "Diamond wealth pulled Britain toward controlling South Africa.", "ERR_SSSP_G8H1A3_B07", 2),
    TF("Black claimholders gradually lost their claims and rights.", "True",
      "Black claimholders were squeezed out and lost rights over time.", "ERR_SSSP_G8H1A3_B08", 2),
    MC("Barney Barnato was, like Rhodes, a:", ["Diamond magnate", "Xhosa chief", "Sea captain", "Missionary"], "Diamond magnate",
      "Barnato was a rival and partner of Rhodes in the diamond industry.", "ERR_SSSP_G8H1A3_B09", 3),
    CLOZE("Control of supply by one company is called a ____.", ["monopoly", "democracy", "colony", "union"], "monopoly",
      "A monopoly is one company's control of supply.", "ERR_SSSP_G8H1A3_B10", 2),
    TF("Diamond mining began South Africa's Mineral Revolution.", "True",
      "The 1867 diamond find at Kimberley started the Mineral Revolution.", "ERR_SSSP_G8H1A3_B11", 1),
    MC("Companies regulated the supply of diamonds in order to:", ["Keep prices high", "Lower prices", "Give diamonds away", "Stop mining"], "Keep prices high",
      "Limiting supply kept diamond prices high and profits large.", "ERR_SSSP_G8H1A3_B12", 2),
  ],
  // ── H2.A1 Labour control and land expansion ──
  "SSSP.G8.H2.A1": [
    MC("Closed compounds were used to house and:", ["Control black mineworkers", "Reward owners", "Store gold", "Train teachers"], "Control black mineworkers",
      "Closed compounds tightly controlled black migrant mineworkers.", "ERR_SSSP_G8H2A1_B01", 1),
    TF("Migrant labour meant men left rural homes to work in distant mines.", "True",
      "Migrant workers travelled from rural homes to the mines and back.", "ERR_SSSP_G8H2A1_B02", 1),
    MC("The defeat of African kingdoms made it easier to:", ["Force people into mine labour", "Build schools", "Share land equally", "End mining"], "Force people into mine labour",
      "Losing independence pushed people into wage labour on the mines.", "ERR_SSSP_G8H2A1_B03", 2),
    CLOZE("The Zulu kingdom was defeated in ____.", ["1879", "1652", "1948", "1994"], "1879",
      "The Zulu were defeated in 1879.", "ERR_SSSP_G8H2A1_B04", 2),
    TF("Land dispossession pushed many men to seek work in the mines.", "True",
      "Losing land forced many African men into migrant mine labour.", "ERR_SSSP_G8H2A1_B05", 2),
    MC("Closed compounds were 'closed' because workers:", ["Were kept inside under control", "Could come and go freely", "Owned them", "Lived in towns"], "Were kept inside under control",
      "Closed compounds confined workers under strict control.", "ERR_SSSP_G8H2A1_B06", 2),
    MC("The Pedi kingdom lost its independence in the:", ["Late 1870s", "1650s", "1990s", "1400s"], "Late 1870s",
      "The Pedi were defeated in the late 1870s.", "ERR_SSSP_G8H2A1_B07", 3),
    TF("Increasing control over black labour was central to the Mineral Revolution.", "True",
      "Tighter labour control defined the Mineral Revolution era.", "ERR_SSSP_G8H2A1_B08", 1),
    MC("The compound system was first developed at the:", ["Kimberley diamond mines", "Cape harbour", "Natal sugar farms", "Witwatersrand only"], "Kimberley diamond mines",
      "The compound system began in Kimberley's diamond mines, then spread to gold.", "ERR_SSSP_G8H2A1_B09", 3),
    CLOZE("Workers who travelled to the mines and returned home were ____ labourers.", ["migrant", "free", "indentured", "skilled"], "migrant",
      "These were migrant labourers.", "ERR_SSSP_G8H2A1_B10", 1),
    TF("Mining had no need for large amounts of labour.", "False",
      "Mining needed huge amounts of cheap labour, shaping harsh controls.", "ERR_SSSP_G8H2A1_B11", 1),
    MC("Defeating African kingdoms and taking land served the mines by:", ["Creating a forced labour supply", "Reducing profits", "Ending mining", "Helping farmers"], "Creating a forced labour supply",
      "Conquest and land loss created the labour supply the mines needed.", "ERR_SSSP_G8H2A1_B12", 3),
  ],
  // ── H2.A2 Deep-level gold mining ──
  "SSSP.G8.H2.A2": [
    MC("Gold on the Witwatersrand was found:", ["Deep underground", "Floating on rivers", "On the surface only", "In the sea"], "Deep underground",
      "Witwatersrand gold lay deep underground, needing expensive mining.", "ERR_SSSP_G8H2A2_B01", 1),
    TF("Johannesburg grew because of the gold mines.", "True",
      "Johannesburg boomed around the Witwatersrand gold mines.", "ERR_SSSP_G8H2A2_B02", 1),
    MC("Deep mining needed big companies because it was:", ["Expensive and complex", "Cheap and easy", "Done by hand quickly", "Illegal"], "Expensive and complex",
      "Deep gold mining was costly and complex, so big companies formed.", "ERR_SSSP_G8H2A2_B03", 2),
    CLOZE("The wealthy gold-mine owners were called the ____.", ["Randlords", "Trekboers", "Huguenots", "Luddites"], "Randlords",
      "The Randlords were the rich Witwatersrand mine owners.", "ERR_SSSP_G8H2A2_B04", 2),
    TF("Conditions for workers deep in the gold mines were dangerous and hard.", "True",
      "Underground gold mining was hot, deep and dangerous.", "ERR_SSSP_G8H2A2_B05", 1),
    MC("With men away at the mines, women in the reserves had to:", ["Run households and farms alone", "Become Randlords", "Move to Europe", "Stop working"], "Run households and farms alone",
      "Women carried the burden of households and farms while men were at the mines.", "ERR_SSSP_G8H2A2_B06", 3),
    MC("The Chamber of Mines was formed by:", ["Mine owners", "Workers", "The Xhosa", "Missionaries"], "Mine owners",
      "Owners formed the Chamber of Mines to organise the industry.", "ERR_SSSP_G8H2A2_B07", 2),
    TF("White and black workers were treated the same in the mines.", "False",
      "There was a sharp divide, with skilled jobs and better pay reserved for white workers.", "ERR_SSSP_G8H2A2_B08", 2),
    MC("Gold was discovered on the Witwatersrand in:", ["1886", "1867", "1948", "1994"], "1886",
      "Gold was found on the Witwatersrand in 1886.", "ERR_SSSP_G8H2A2_B09", 1),
    CLOZE("The city of ____ grew rapidly around the gold mines.", ["Johannesburg", "Kimberley", "Durban", "Cape Town"], "Johannesburg",
      "Johannesburg grew quickly around the gold mines.", "ERR_SSSP_G8H2A2_B10", 1),
    TF("Migrant workers in the gold mines lived in compounds.", "True",
      "Migrant gold-mine workers were housed in compounds, like at Kimberley.", "ERR_SSSP_G8H2A2_B11", 1),
    MC("Forms of labour resistance in the mines included:", ["Strikes and protests", "Owning the mines", "Setting prices", "Doing nothing"], "Strikes and protests",
      "Workers resisted harsh conditions through strikes and protests.", "ERR_SSSP_G8H2A2_B12", 3),
  ],
  // ── H2.A3 Mineral Revolution as a turning point ──
  "SSSP.G8.H2.A3": [
    MC("The Union of South Africa (1910) joined:", ["The colonies under one government", "Africa and Europe", "Mali and Timbuktu", "Two oceans"], "The colonies under one government",
      "The 1910 Union united the colonies into one country.", "ERR_SSSP_G8H2A3_B01", 1),
    TF("The SANNC was formed in 1912 to defend African rights.", "True",
      "The SANNC (later the ANC) formed in 1912 to defend African rights.", "ERR_SSSP_G8H2A3_B02", 2),
    MC("The 1913 Land Act limited:", ["Land black South Africans could own", "Gold mining", "Sugar farming", "The Union"], "Land black South Africans could own",
      "The 1913 Land Act restricted black land ownership to a small share.", "ERR_SSSP_G8H2A3_B03", 2),
    CLOZE("The SANNC was later renamed the ____.", ["ANC", "PAC", "VOC", "NP"], "ANC",
      "The SANNC was later renamed the African National Congress (ANC).", "ERR_SSSP_G8H2A3_B04", 1),
    TF("The Mineral Revolution shaped South Africa for the whole 20th century.", "True",
      "Patterns of land, labour and power from mining shaped the century ahead.", "ERR_SSSP_G8H2A3_B05", 2),
    MC("The 1913 Land Act is a foundation of later:", ["Racial segregation", "Free elections", "Equal land sharing", "World peace"], "Racial segregation",
      "The Land Act laid foundations for later racial segregation.", "ERR_SSSP_G8H2A3_B06", 3),
    MC("The defeat of the Boer Republics happened in:", ["1902", "1652", "1976", "1994"], "1902",
      "The South African (Anglo-Boer) War ended with the Boer Republics' defeat in 1902.", "ERR_SSSP_G8H2A3_B07", 3),
    TF("The Mineral Revolution had no effect on the balance of power.", "False",
      "It shifted power away from African kingdoms toward colonial and mining interests.", "ERR_SSSP_G8H2A3_B08", 1),
    MC("The Satyagraha Campaign (1913–1914) is linked to which leader?", ["Mahatma Gandhi", "Cecil Rhodes", "Shaka", "Jan van Riebeeck"], "Mahatma Gandhi",
      "Gandhi led the Satyagraha (non-violent resistance) campaign in South Africa.", "ERR_SSSP_G8H2A3_B09", 3),
    CLOZE("The ____ of South Africa was formed in 1910.", ["Union", "Republic", "Empire", "Colony"], "Union",
      "The Union of South Africa formed in 1910.", "ERR_SSSP_G8H2A3_B10", 1),
    TF("Comparing maps of 1860 and 1913 shows how much African land was lost.", "True",
      "Maps of 1860 vs 1913 show major loss of African land and independence.", "ERR_SSSP_G8H2A3_B11", 2),
    MC("Why is the Mineral Revolution called a 'turning point'?", ["It changed land, labour and power lastingly", "It lasted one day", "It had no effect", "It only affected Britain"], "It changed land, labour and power lastingly",
      "It is a turning point because it reshaped land, labour and power for generations.", "ERR_SSSP_G8H2A3_B12", 2),
  ],
  // ── H3.A1 European colonisation of Africa ──
  "SSSP.G8.H3.A1": [
    MC("The Berlin Conference took place in:", ["1884", "1652", "1948", "1994"], "1884",
      "European powers met at the Berlin Conference in 1884.", "ERR_SSSP_G8H3A1_B01", 1),
    TF("European powers used borders that ignored African peoples and kingdoms.", "True",
      "Colonial borders were drawn for European convenience, cutting across African societies.", "ERR_SSSP_G8H3A1_B02", 2),
    MC("A major aim of colonisation was to gain:", ["Raw materials and markets", "More deserts", "African universities", "Nothing"], "Raw materials and markets",
      "Europeans wanted Africa's raw materials and markets for their goods.", "ERR_SSSP_G8H3A1_B03", 2),
    CLOZE("The rapid European takeover of Africa is called the ____ for Africa.", ["Scramble", "Trek", "Union", "Charter"], "Scramble",
      "It is known as the Scramble for Africa.", "ERR_SSSP_G8H3A1_B04", 1),
    TF("Africans resisted colonisation in many places.", "True",
      "Many African peoples resisted European colonisation.", "ERR_SSSP_G8H3A1_B05", 1),
    MC("Maxim guns and railways helped Europeans because they gave:", ["A military and transport advantage", "African support", "Better farming", "More rain"], "A military and transport advantage",
      "Superior weapons and transport gave Europeans a big advantage.", "ERR_SSSP_G8H3A1_B06", 3),
    MC("A 'colony' is a territory:", ["Ruled by a foreign power", "That is fully independent", "With no people", "Under the sea"], "Ruled by a foreign power",
      "A colony is land ruled by a foreign power.", "ERR_SSSP_G8H3A1_B07", 1),
    TF("Colonisation changed African economies to serve European needs.", "True",
      "Colonies were reshaped to supply Europe with raw materials.", "ERR_SSSP_G8H3A1_B08", 2),
    MC("Colonial borders sometimes split single peoples between:", ["Different colonies", "Different planets", "Oceans only", "Cities only"], "Different colonies",
      "Arbitrary borders split peoples across different colonies.", "ERR_SSSP_G8H3A1_B09", 3),
    CLOZE("At Berlin, European powers ____ Africa among themselves.", ["divided", "freed", "united", "ignored"], "divided",
      "They divided Africa between the European powers.", "ERR_SSSP_G8H3A1_B10", 1),
    TF("Colonisation of Africa was part of worldwide European expansion.", "True",
      "It was part of Europe's global colonial expansion.", "ERR_SSSP_G8H3A1_B11", 2),
    MC("A lasting effect of colonisation was:", ["New borders that still exist today", "No change at all", "African rule of Europe", "The end of all trade"], "New borders that still exist today",
      "Many of today's African borders date from colonisation.", "ERR_SSSP_G8H3A1_B12", 2),
  ],
  // ── H3.A2 Ashanti case study ──
  "SSSP.G8.H3.A2": [
    MC("The Ashanti kingdom was known for its wealth in:", ["Gold", "Diamonds", "Oil", "Coal"], "Gold",
      "The Ashanti were famed for their gold wealth — hence the 'Gold Coast'.", "ERR_SSSP_G8H3A2_B01", 2),
    TF("The British eventually colonised the Ashanti area.", "True",
      "Britain colonised the Ashanti region as the Gold Coast.", "ERR_SSSP_G8H3A2_B02", 1),
    MC("The Ashanti first met Europeans through:", ["Coastal trade", "Air travel", "Railways", "Space"], "Coastal trade",
      "Early contact came through trade on the West African coast.", "ERR_SSSP_G8H3A2_B03", 2),
    CLOZE("The Ashanti kingdom became the modern country of ____.", ["Ghana", "Egypt", "Kenya", "Mali"], "Ghana",
      "The former Gold Coast is now Ghana.", "ERR_SSSP_G8H3A2_B04", 1),
    TF("The Ashanti resisted British takeover before being colonised.", "True",
      "The Ashanti fought to defend their kingdom against the British.", "ERR_SSSP_G8H3A2_B05", 2),
    MC("Using the Ashanti as a case study means:", ["Studying one example in detail", "Ignoring history", "Drawing maps", "Counting money"], "Studying one example in detail",
      "A case study examines one example closely to understand the bigger picture.", "ERR_SSSP_G8H3A2_B06", 2),
    MC("A result of colonisation for the Ashanti was:", ["Loss of independence", "Becoming an empire over Europe", "Gaining gold mines in Britain", "No change"], "Loss of independence",
      "The Ashanti lost their independence to Britain.", "ERR_SSSP_G8H3A2_B07", 2),
    TF("The British benefited from the Gold Coast's resources.", "True",
      "Britain profited from the Gold Coast's gold and other resources.", "ERR_SSSP_G8H3A2_B08", 2),
    MC("The name 'Gold Coast' came from the region's:", ["Gold trade", "Cold weather", "Sandy beaches", "Tall mountains"], "Gold trade",
      "The 'Gold Coast' was named for its gold trade.", "ERR_SSSP_G8H3A2_B09", 2),
    CLOZE("The Ashanti were located in ____ Africa.", ["West", "South", "North", "East"], "West",
      "The Ashanti kingdom was in West Africa.", "ERR_SSSP_G8H3A2_B10", 1),
    TF("The Ashanti had no contact with Europeans before colonisation.", "False",
      "The Ashanti traded with Europeans long before being colonised.", "ERR_SSSP_G8H3A2_B11", 1),
    MC("Ghana later became important as:", ["An independent African country", "A European colony forever", "A desert with no people", "Part of Britain"], "An independent African country",
      "Ghana gained independence and became a notable African nation.", "ERR_SSSP_G8H3A2_B12", 3),
  ],
  // ── H4.A1 Why WWI broke out ──
  "SSSP.G8.H4.A1": [
    MC("World War I lasted from:", ["1914 to 1918", "1939 to 1945", "1899 to 1902", "1948 to 1960"], "1914 to 1918",
      "World War I ran from 1914 to 1918.", "ERR_SSSP_G8H4A1_B01", 1),
    TF("Competition for colonies and empire was a long-term cause of the war.", "True",
      "Rivalry over colonies and empire built up tension before 1914.", "ERR_SSSP_G8H4A1_B02", 2),
    MC("The assassination at Sarajevo killed:", ["Archduke Franz Ferdinand", "Hitler", "Mandela", "Rhodes"], "Archduke Franz Ferdinand",
      "The Archduke's assassination at Sarajevo sparked the war.", "ERR_SSSP_G8H4A1_B03", 2),
    CLOZE("Pride in and rivalry between nations is called ____.", ["nationalism", "tourism", "socialism", "farming"], "nationalism",
      "Nationalism, a long-term cause, is intense national pride and rivalry.", "ERR_SSSP_G8H4A1_B04", 2),
    TF("Building up armies and navies (militarism) was a cause of tension.", "True",
      "The military build-up (militarism) increased tension before the war.", "ERR_SSSP_G8H4A1_B05", 2),
    MC("Alliances were dangerous because they could:", ["Pull many countries into one conflict", "Prevent all wars", "End trade", "Cool the planet"], "Pull many countries into one conflict",
      "Alliances meant a small conflict could drag many nations into war.", "ERR_SSSP_G8H4A1_B06", 2),
    MC("Britain and France fought on the side called the:", ["Allies", "Central Powers", "Axis", "Trekboers"], "Allies",
      "Britain and France were among the Allied Powers.", "ERR_SSSP_G8H4A1_B07", 1),
    TF("The immediate cause and the long-term causes of WWI were the same thing.", "False",
      "The spark (Sarajevo) was the immediate cause; nationalism, alliances and militarism were long-term causes.", "ERR_SSSP_G8H4A1_B08", 2),
    MC("Germany and Austria-Hungary belonged to the:", ["Central Powers", "Allies", "Randlords", "VOC"], "Central Powers",
      "Germany and Austria-Hungary were Central Powers.", "ERR_SSSP_G8H4A1_B09", 2),
    CLOZE("The murder at Sarajevo was the ____ cause that set off the war.", ["immediate", "long-term", "economic", "natural"], "immediate",
      "Sarajevo was the immediate trigger of the war.", "ERR_SSSP_G8H4A1_B10", 2),
    TF("Tensions had been building in Europe for years before 1914.", "True",
      "Long-term tensions built up for years before the spark in 1914.", "ERR_SSSP_G8H4A1_B11", 1),
    MC("Why did one assassination lead to a world war?", ["Alliances dragged many nations in", "It destroyed Europe instantly", "Everyone wanted peace", "There were no causes"], "Alliances dragged many nations in",
      "The system of alliances turned a local crisis into a world war.", "ERR_SSSP_G8H4A1_B12", 3),
  ],
  // ── H4.A2 Experiences of WWI ──
  "SSSP.G8.H4.A2": [
    MC("The Western Front was known for its system of:", ["Trenches", "Skyscrapers", "Railways only", "Harbours"], "Trenches",
      "The Western Front was a line of opposing trenches.", "ERR_SSSP_G8H4A2_B01", 1),
    TF("New weapons like machine guns made WWI especially deadly.", "True",
      "Machine guns and artillery made WWI battles extremely deadly.", "ERR_SSSP_G8H4A2_B02", 2),
    MC("The SS Mendi disaster killed many:", ["South African servicemen", "British generals", "Sailors from Mali", "Farmers"], "South African servicemen",
      "The sinking of the Mendi in 1917 killed many South African servicemen.", "ERR_SSSP_G8H4A2_B03", 2),
    CLOZE("Forcing men by law to join the army is called ____.", ["conscription", "propaganda", "trade", "migration"], "conscription",
      "Conscription is compulsory military service.", "ERR_SSSP_G8H4A2_B04", 2),
    TF("Propaganda was used to keep up public support for the war.", "True",
      "Governments used propaganda to maintain public support and recruitment.", "ERR_SSSP_G8H4A2_B05", 2),
    MC("Conscientious objectors refused to fight because of their:", ["Conscience or beliefs", "Laziness", "Wealth", "Age only"], "Conscience or beliefs",
      "Conscientious objectors refused to fight on grounds of conscience.", "ERR_SSSP_G8H4A2_B06", 3),
    MC("South African troops fought at the Battle of:", ["Delville Wood", "Sharpeville", "Kimberley", "Soweto"], "Delville Wood",
      "South Africans fought and died at Delville Wood in 1916.", "ERR_SSSP_G8H4A2_B07", 2),
    TF("Trench conditions were often muddy, cold and full of disease.", "True",
      "Trenches were grim — muddy, cold and disease-ridden.", "ERR_SSSP_G8H4A2_B08", 1),
    MC("Music and poetry from the war often expressed:", ["The suffering and emotions of soldiers", "Recipes", "Map scales", "Gold prices"], "The suffering and emotions of soldiers",
      "War poetry and music captured soldiers' suffering and feelings.", "ERR_SSSP_G8H4A2_B09", 3),
    CLOZE("Soldiers on the Western Front mostly fought from ____.", ["trenches", "ships", "planes", "towers"], "trenches",
      "They fought from trenches.", "ERR_SSSP_G8H4A2_B10", 1),
    TF("South Africa was not involved in World War I at all.", "False",
      "South Africa took part, including at Delville Wood and through the Mendi.", "ERR_SSSP_G8H4A2_B11", 1),
    MC("Why is the Mendi remembered in South Africa today?", ["It honours the men who died serving in WWI", "It was a great victory", "It discovered gold", "It started apartheid"], "It honours the men who died serving in WWI",
      "The Mendi is remembered to honour the South Africans who died.", "ERR_SSSP_G8H4A2_B12", 2),
  ],
  // ── H4.A3 Women in Britain during WWI ──
  "SSSP.G8.H4.A3": [
    MC("During the war, women took on jobs previously done by:", ["Men who had gone to fight", "Children", "Foreign armies", "Robots"], "Men who had gone to fight",
      "Women filled jobs left by men who went to fight.", "ERR_SSSP_G8H4A3_B01", 1),
    TF("Women worked in factories making weapons during the war.", "True",
      "Many women worked in munitions (weapons) factories.", "ERR_SSSP_G8H4A3_B02", 1),
    MC("Emmeline Pankhurst is remembered as a leader of the:", ["Suffrage (votes for women) movement", "Mining industry", "Army", "VOC"], "Suffrage (votes for women) movement",
      "Pankhurst led the campaign for women's right to vote.", "ERR_SSSP_G8H4A3_B03", 2),
    CLOZE("Women's work in the war strengthened their claim to the ____.", ["vote", "army", "mines", "trenches"], "vote",
      "Their wartime contribution strengthened the case for women's vote.", "ERR_SSSP_G8H4A3_B04", 2),
    TF("The war years helped change attitudes about what women could do.", "True",
      "Women's wartime work challenged old ideas about women's roles.", "ERR_SSSP_G8H4A3_B05", 2),
    MC("Suffragettes campaigned mainly for:", ["The right to vote", "More wars", "Lower wages", "Less education"], "The right to vote",
      "Suffragettes campaigned for women's right to vote.", "ERR_SSSP_G8H4A3_B06", 1),
    MC("The change in women's roles during the war is an example of:", ["Social change", "A battle", "A treaty", "A trade route"], "Social change",
      "It was a major social change brought by the war.", "ERR_SSSP_G8H4A3_B07", 2),
    TF("After the war, women's contributions were quickly forgotten and had no effect.", "False",
      "Their contributions helped advance the cause of women's rights, including the vote.", "ERR_SSSP_G8H4A3_B08", 2),
    MC("Women also served the war effort as:", ["Nurses caring for the wounded", "Generals leading armies", "Kings", "Sea captains"], "Nurses caring for the wounded",
      "Many women served as nurses caring for wounded soldiers.", "ERR_SSSP_G8H4A3_B09", 2),
    CLOZE("The movement for women's right to vote is called the ____ movement.", ["suffrage", "trench", "union", "trade"], "suffrage",
      "The suffrage movement sought votes for women.", "ERR_SSSP_G8H4A3_B10", 1),
    TF("Women's roles in society were affected by the experience of the war.", "True",
      "The war reshaped ideas about women's roles in society.", "ERR_SSSP_G8H4A3_B11", 1),
    MC("Why did the war strengthen the argument for women's rights?", ["Women proved their importance to society", "Women stopped working", "It had nothing to do with rights", "It lowered wages"], "Women proved their importance to society",
      "Women's vital contribution strengthened arguments for their rights.", "ERR_SSSP_G8H4A3_B12", 2),
  ],
  // ── H4.A4 Treaty of Versailles ──
  "SSSP.G8.H4.A4": [
    MC("The Treaty of Versailles was signed in:", ["1919", "1914", "1886", "1945"], "1919",
      "The Treaty of Versailles was signed in 1919.", "ERR_SSSP_G8H4A4_B01", 1),
    TF("The treaty blamed Germany for the war and demanded payments.", "True",
      "Versailles blamed Germany and demanded heavy reparations (payments).", "ERR_SSSP_G8H4A4_B02", 2),
    MC("The treaty also limited Germany's:", ["Army and military", "Schools", "Farms", "Population"], "Army and military",
      "Versailles imposed strict limits on Germany's military.", "ERR_SSSP_G8H4A4_B03", 2),
    CLOZE("Germany lost ____ as part of the treaty's terms.", ["land", "rain", "rivers", "language"], "land",
      "Germany lost territory under the Versailles terms.", "ERR_SSSP_G8H4A4_B04", 2),
    TF("Many Germans felt the treaty was unfair and humiliating.", "True",
      "Germans widely resented the harsh, humiliating treaty terms.", "ERR_SSSP_G8H4A4_B05", 2),
    MC("German resentment of the treaty later helped the rise of:", ["Hitler and the Nazis", "the VOC", "the Ashanti", "the Randlords"], "Hitler and the Nazis",
      "Anger at Versailles helped the Nazis gain support.", "ERR_SSSP_G8H4A4_B06", 3),
    MC("The treaty was meant to:", ["Settle the peace after WWI", "Start WWI", "Create the gold mines", "Build the Berlin Wall"], "Settle the peace after WWI",
      "Versailles was the peace settlement after World War I.", "ERR_SSSP_G8H4A4_B07", 1),
    TF("The harshness of the treaty had no consequences later.", "False",
      "Its harshness fed resentment that contributed to World War II.", "ERR_SSSP_G8H4A4_B08", 2),
    MC("'Reparations' in the treaty were:", ["Payments Germany had to make", "New colonies for Germany", "Free weapons", "Gold mines"], "Payments Germany had to make",
      "Reparations were payments Germany was forced to make.", "ERR_SSSP_G8H4A4_B09", 3),
    CLOZE("The Treaty of Versailles ended World War ____.", ["I", "II", "III", "Cold"], "I",
      "Versailles ended World War I.", "ERR_SSSP_G8H4A4_B10", 1),
    TF("The Treaty of Versailles will connect to the Grade 9 study of Nazi Germany.", "True",
      "Versailles links forward to the Grade 9 study of Hitler's rise.", "ERR_SSSP_G8H4A4_B11", 1),
    MC("A peace treaty that is too harsh can:", ["Create future resentment and conflict", "Guarantee peace forever", "Have no effect", "End all nations"], "Create future resentment and conflict",
      "An overly harsh treaty can breed resentment and future conflict.", "ERR_SSSP_G8H4A4_B12", 3),
  ],
  // ── G1.A1 Maps and atlases ──
  "SSSP.G8.G1.A1": [
    MC("An atlas is a:", ["Book of maps", "Type of globe", "Weather station", "Compass"], "Book of maps",
      "An atlas is a collection (book) of maps.", "ERR_SSSP_G8G1A1_B01", 1),
    TF("Latitude lines run east–west and measure distance north or south.", "True",
      "Lines of latitude run east–west, measuring north–south position.", "ERR_SSSP_G8G1A1_B02", 2),
    MC("On a 1:50 000 map, 1 cm represents:", ["500 m", "50 km", "5 km", "5 m"], "500 m",
      "1:50 000 means 1 cm = 50 000 cm = 500 m.", "ERR_SSSP_G8G1A1_B03", 3),
    CLOZE("Lines of ____ run north–south and measure east or west position.", ["longitude", "latitude", "scale", "contour"], "longitude",
      "Longitude lines run north–south, measuring east–west position.", "ERR_SSSP_G8G1A1_B04", 2),
    TF("A smaller scale (like 1:1 000 000) covers a larger area with less detail.", "True",
      "Smaller-scale maps cover larger areas with less detail.", "ERR_SSSP_G8G1A1_B05", 2),
    MC("To find a town's page and position in an atlas you use the:", ["Index", "Cover", "Scale bar only", "North arrow only"], "Index",
      "The atlas index lists places with their page and grid.", "ERR_SSSP_G8G1A1_B06", 1),
    MC("A ratio scale of 1:25 000 shows more detail than:", ["1:250 000", "1:10 000", "1:5 000", "1:1 000"], "1:250 000",
      "1:25 000 is larger-scale (more detail) than 1:250 000.", "ERR_SSSP_G8G1A1_B07", 3),
    TF("Degrees can be divided into smaller units called minutes.", "True",
      "Each degree of latitude or longitude is divided into 60 minutes.", "ERR_SSSP_G8G1A1_B08", 2),
    MC("Calculating distance between two towns on a map needs the:", ["Scale", "Title", "Date", "Author"], "Scale",
      "You use the map's scale to convert map distance to real distance.", "ERR_SSSP_G8G1A1_B09", 1),
    CLOZE("A scale written as 1:100 000 is a ____ scale.", ["ratio", "line", "word", "colour"], "ratio",
      "1:100 000 is a ratio (number) scale.", "ERR_SSSP_G8G1A1_B10", 2),
    TF("Atlases contain maps at world, regional and local scales.", "True",
      "Atlases use a range of scales from world to local.", "ERR_SSSP_G8G1A1_B11", 1),
    MC("Latitude and longitude together let you give a place's:", ["Exact location", "Temperature", "Population", "Religion"], "Exact location",
      "Latitude and longitude pinpoint a place's exact location.", "ERR_SSSP_G8G1A1_B12", 1),
  ],
  // ── G1.A2 The globe ──
  "SSSP.G8.G1.A2": [
    MC("Time zones exist because:", ["The Earth spins, so the sun reaches places at different times", "Clocks are different", "Countries dislike each other", "The moon controls clocks"], "The Earth spins, so the sun reaches places at different times",
      "As the Earth spins, the sun reaches different longitudes at different times, so we use time zones.", "ERR_SSSP_G8G1A2_B01", 2),
    TF("The Earth's tilt causes the seasons as it orbits the sun.", "True",
      "The Earth's tilt, with its orbit, causes the seasons.", "ERR_SSSP_G8G1A2_B02", 2),
    MC("One full rotation of the Earth on its axis takes about:", ["24 hours", "1 hour", "1 year", "1 month"], "24 hours",
      "The Earth spins once in about 24 hours — a day.", "ERR_SSSP_G8G1A2_B03", 1),
    CLOZE("The Earth's journey around the sun takes about one ____.", ["year", "day", "hour", "week"], "year",
      "One orbit (revolution) of the sun takes about a year.", "ERR_SSSP_G8G1A2_B04", 2),
    TF("When it is summer in the Southern Hemisphere, it is winter in the Northern Hemisphere.", "True",
      "Because of the tilt, the hemispheres have opposite seasons.", "ERR_SSSP_G8G1A2_B05", 3),
    MC("The international date line is roughly opposite the:", ["Prime Meridian", "Equator", "South Pole", "Tropic of Capricorn"], "Prime Meridian",
      "The date line lies roughly opposite the Prime Meridian, near 180°.", "ERR_SSSP_G8G1A2_B06", 3),
    MC("A solstice is when:", ["Day or night is at its longest", "Day and night are equal", "The Earth stops", "There is no sun"], "Day or night is at its longest",
      "At a solstice, one hemisphere has its longest day and the other its longest night.", "ERR_SSSP_G8G1A2_B07", 3),
    TF("The Earth's spin causes day and night.", "True",
      "The daily spin gives us day and night.", "ERR_SSSP_G8G1A2_B08", 1),
    MC("South African Standard Time is:", ["The official time used in South Africa", "A global clock", "A type of map", "The same as UK time"], "The official time used in South Africa",
      "South African Standard Time is the country's official time.", "ERR_SSSP_G8G1A2_B09", 1),
    CLOZE("The angle of the Earth's ____ helps cause the seasons.", ["axis", "equator", "orbit speed", "core"], "axis",
      "The tilt (angle) of the Earth's axis helps cause the seasons.", "ERR_SSSP_G8G1A2_B10", 2),
    TF("Different places on Earth can have different times of day at the same moment.", "True",
      "Time zones mean different longitudes have different local times at once.", "ERR_SSSP_G8G1A2_B11", 1),
    MC("A globe is useful because it shows the Earth's:", ["True round shape", "Flat shape", "Weather only", "Time only"], "True round shape",
      "A globe shows the Earth's true spherical shape without distortion.", "ERR_SSSP_G8G1A2_B12", 2),
  ],
  // ── G1.A3 Satellite images ──
  "SSSP.G8.G1.A3": [
    MC("Satellites that take images of Earth orbit in:", ["Space", "The ocean", "Caves", "Forests"], "Space",
      "Imaging satellites orbit Earth in space.", "ERR_SSSP_G8G1A3_B01", 1),
    TF("Satellite images can help track storms and weather.", "True",
      "Weather satellites track clouds and storms.", "ERR_SSSP_G8G1A3_B02", 1),
    MC("Blue areas on a satellite image usually show:", ["Water", "Forests", "Cities", "Deserts"], "Water",
      "Blue usually indicates water on a satellite image.", "ERR_SSSP_G8G1A3_B03", 2),
    CLOZE("Satellite images can show land ____, such as farms and cities.", ["use", "scale", "names", "prices"], "use",
      "Satellite images reveal land use like farms and cities.", "ERR_SSSP_G8G1A3_B04", 2),
    TF("Satellite images give a view of large areas from above.", "True",
      "Satellites provide a wide overhead view of large areas.", "ERR_SSSP_G8G1A3_B05", 1),
    MC("Satellite images are useful in disasters because they can show:", ["Floods and damage over a wide area", "The price of food", "People's names", "The time"], "Floods and damage over a wide area",
      "After disasters, satellites show floods and damage across wide areas.", "ERR_SSSP_G8G1A3_B06", 2),
    MC("Google Earth is an example of a tool that uses:", ["Satellite imagery", "Hand-drawn maps only", "Sound recordings", "Weather balloons only"], "Satellite imagery",
      "Google Earth displays satellite imagery of the planet.", "ERR_SSSP_G8G1A3_B07", 1),
    TF("Satellite images can show how vegetation changes over time.", "True",
      "Repeated images show how vegetation and land change over time.", "ERR_SSSP_G8G1A3_B08", 2),
    MC("Compared with a ground photo, a satellite image shows:", ["A much larger area", "More smell", "More sound", "The exact temperature"], "A much larger area",
      "Satellite images cover far larger areas than a ground-level photo.", "ERR_SSSP_G8G1A3_B09", 2),
    CLOZE("Green on a satellite image usually means ____.", ["vegetation", "water", "city", "desert"], "vegetation",
      "Green generally indicates vegetation.", "ERR_SSSP_G8G1A3_B10", 1),
    TF("Satellite images are never useful for farming.", "False",
      "Farmers use satellite images to monitor crops and land.", "ERR_SSSP_G8G1A3_B11", 1),
    MC("Satellite images help scientists monitor:", ["The environment and changes on Earth", "Election results", "Football scores", "Music charts"], "The environment and changes on Earth",
      "Scientists use satellite images to monitor the environment and change.", "ERR_SSSP_G8G1A3_B12", 2),
  ],
  // ── G2.A1 Factors influencing temperature and rainfall ──
  "SSSP.G8.G2.A1": [
    MC("As you climb a mountain, the temperature usually:", ["Falls", "Rises", "Stays the same", "Doubles"], "Falls",
      "Temperature falls with altitude, so higher places are cooler.", "ERR_SSSP_G8G2A1_B01", 1),
    TF("Places far inland often have more extreme temperatures than coastal places.", "True",
      "Inland places have hotter summers and colder winters than the milder coast.", "ERR_SSSP_G8G2A1_B02", 2),
    MC("The sea affects coastal climate by:", ["Making temperatures milder", "Making it colder all year", "Stopping rain", "Removing wind"], "Making temperatures milder",
      "The sea moderates coastal temperatures, making them milder.", "ERR_SSSP_G8G2A1_B03", 2),
    CLOZE("Distance from the ____ (latitude) affects how hot a place is.", ["equator", "sea", "mountains", "city"], "equator",
      "Latitude — distance from the equator — strongly affects temperature.", "ERR_SSSP_G8G2A1_B04", 1),
    TF("A warm ocean current can make a nearby coast warmer and wetter.", "True",
      "Warm currents can raise temperature and rainfall on nearby coasts.", "ERR_SSSP_G8G2A1_B05", 2),
    MC("Air forced up over a mountain cools and may produce:", ["Rain", "Drought", "Earthquakes", "Sunshine only"], "Rain",
      "Rising air over mountains cools and can release rain (relief rainfall).", "ERR_SSSP_G8G2A1_B06", 3),
    MC("A cold ocean current near a coast tends to make it:", ["Cooler and drier", "Hotter and wetter", "Snowy", "Tropical"], "Cooler and drier",
      "Cold currents cool the coast and reduce rainfall.", "ERR_SSSP_G8G2A1_B07", 3),
    TF("Latitude is the only factor that affects temperature.", "False",
      "Altitude, distance from the sea, currents and mountains all matter too.", "ERR_SSSP_G8G2A1_B08", 1),
    MC("Highveld areas of South Africa are cooler mainly because of their:", ["High altitude", "Closeness to the equator", "Sea breezes", "Low latitude"], "High altitude",
      "The high-altitude Highveld is cooler because of its height.", "ERR_SSSP_G8G2A1_B09", 3),
    CLOZE("Height above sea level is called ____.", ["altitude", "latitude", "longitude", "humidity"], "altitude",
      "Altitude is height above sea level.", "ERR_SSSP_G8G2A1_B10", 1),
    TF("Mountains can create a wetter side and a drier side.", "True",
      "Mountains give a wet windward side and a drier sheltered side.", "ERR_SSSP_G8G2A1_B11", 3),
    MC("Understanding these factors helps explain why places have:", ["Different climates", "The same climate everywhere", "No weather", "No seasons"], "Different climates",
      "These factors explain why climates differ from place to place.", "ERR_SSSP_G8G2A1_B12", 1),
  ],
  // ── G2.A2 South Africa's climate ──
  "SSSP.G8.G2.A2": [
    MC("The interior plateau of South Africa is generally:", ["Cooler because it is high", "Hot because it is at the coast", "Snowy all year", "Below sea level"], "Cooler because it is high",
      "The high interior plateau is cooler because of its altitude.", "ERR_SSSP_G8G2A2_B01", 2),
    TF("Cape Town has a winter-rainfall climate.", "True",
      "Cape Town gets most of its rain in winter (a Mediterranean-type climate).", "ERR_SSSP_G8G2A2_B02", 2),
    MC("Durban is warm and humid partly because of the:", ["Warm Agulhas current", "Cold Benguela current", "High altitude", "Distance from the sea"], "Warm Agulhas current",
      "The warm Agulhas current keeps Durban warm and humid.", "ERR_SSSP_G8G2A2_B03", 3),
    CLOZE("The west coast is cooled and dried by the cold ____ current.", ["Benguela", "Agulhas", "Gulf", "Indian"], "Benguela",
      "The cold Benguela current cools and dries the west coast.", "ERR_SSSP_G8G2A2_B04", 3),
    TF("Most of South Africa receives its rain in summer.", "True",
      "Most of South Africa is a summer-rainfall region (the Cape being an exception).", "ERR_SSSP_G8G2A2_B05", 2),
    MC("Upington in the west is generally:", ["Hot and dry", "Cold and wet", "Tropical", "Snowy"], "Hot and dry",
      "Inland western Upington is hot and dry.", "ERR_SSSP_G8G2A2_B06", 1),
    MC("Why does Johannesburg have cooler temperatures than Durban?", ["Higher altitude inland", "It is at the coast", "Closer to the equator", "Warm currents"], "Higher altitude inland",
      "High-altitude inland Johannesburg is cooler than coastal Durban.", "ERR_SSSP_G8G2A2_B07", 3),
    TF("South Africa has the same climate everywhere.", "False",
      "South Africa has varied climates due to differences in altitude, sea, currents and latitude.", "ERR_SSSP_G8G2A2_B08", 1),
    MC("Coastal cities tend to have:", ["Milder temperatures than inland", "More extreme temperatures", "No rain ever", "Snow all year"], "Milder temperatures than inland",
      "The sea keeps coastal cities milder than inland places.", "ERR_SSSP_G8G2A2_B09", 2),
    CLOZE("The warm ____ current flows down South Africa's east coast.", ["Agulhas", "Benguela", "Arctic", "Pacific"], "Agulhas",
      "The warm Agulhas current flows along the east coast.", "ERR_SSSP_G8G2A2_B10", 3),
    TF("Altitude and ocean currents both help explain South Africa's climates.", "True",
      "Altitude, currents, latitude and distance from the sea shape South Africa's climates.", "ERR_SSSP_G8G2A2_B11", 2),
    MC("Comparing places like Cape Town and Durban shows that climate depends on:", ["Several factors working together", "Only the day of the week", "Only the population", "Nothing"], "Several factors working together",
      "Climate at each place results from several factors combined.", "ERR_SSSP_G8G2A2_B12", 2),
  ],
  // ── G2.A3 Climate around the world ──
  "SSSP.G8.G2.A3": [
    MC("Weather describes conditions:", ["Day to day", "Over many years", "On other planets", "In the past only"], "Day to day",
      "Weather is the day-to-day state of the atmosphere.", "ERR_SSSP_G8G2A3_B01", 1),
    TF("Climate is the average weather of a place over many years.", "True",
      "Climate is the long-term average of weather.", "ERR_SSSP_G8G2A3_B02", 1),
    MC("A tropical climate is:", ["Hot and wet", "Cold and dry", "Mild with dry summers", "Freezing"], "Hot and wet",
      "Tropical climates are hot with high rainfall.", "ERR_SSSP_G8G2A3_B03", 1),
    CLOZE("A ____ climate has very low rainfall.", ["desert", "tropical", "polar", "temperate"], "desert",
      "Desert climates are very dry.", "ERR_SSSP_G8G2A3_B04", 1),
    TF("Polar climates are found near the North and South Poles.", "True",
      "Polar climates occur near the poles and are very cold.", "ERR_SSSP_G8G2A3_B05", 1),
    MC("Humidity is a measure of:", ["Moisture in the air", "Temperature only", "Wind speed", "Air pressure only"], "Moisture in the air",
      "Humidity measures how much moisture is in the air.", "ERR_SSSP_G8G2A3_B06", 2),
    MC("Climate graphs usually show rainfall as bars and temperature as a:", ["Line", "Pie", "Photo", "Map"], "Line",
      "Climate graphs use rainfall bars and a temperature line.", "ERR_SSSP_G8G2A3_B07", 2),
    TF("A temperate climate is mild, without extreme heat or cold.", "True",
      "Temperate climates are mild, avoiding extremes.", "ERR_SSSP_G8G2A3_B08", 2),
    MC("Climate regions can be linked to the factors that control:", ["Temperature and rainfall", "Population only", "Gold prices", "Election results"], "Temperature and rainfall",
      "Climate regions follow the factors controlling temperature and rainfall.", "ERR_SSSP_G8G2A3_B09", 3),
    CLOZE("The elements of weather include temperature, wind, humidity and ____.", ["precipitation", "population", "altitude only", "longitude"], "precipitation",
      "Precipitation (rain, snow) is an element of weather.", "ERR_SSSP_G8G2A3_B10", 2),
    TF("A world climate map shows where different climate types occur.", "True",
      "World climate maps display the locations of climate types.", "ERR_SSSP_G8G2A3_B11", 1),
    MC("The difference between weather and climate is mainly about:", ["Time scale (short vs long term)", "Temperature only", "Where you live", "Nothing"], "Time scale (short vs long term)",
      "Weather is short-term; climate is the long-term average.", "ERR_SSSP_G8G2A3_B12", 2),
  ],
  // ── G3.A1 Settlement and land use ──
  "SSSP.G8.G3.A1": [
    MC("A 'settlement' is:", ["A place where people live", "A type of map", "A weather pattern", "A trade route"], "A place where people live",
      "A settlement is a place where people live, from a village to a city.", "ERR_SSSP_G8G3A1_B01", 1),
    TF("Light and heavy industry are usually placed in separate zones.", "True",
      "Cities zone light and heavy industry separately, often away from homes.", "ERR_SSSP_G8G3A1_B02", 2),
    MC("Recreation areas in a city are for:", ["Sport and leisure", "Heavy mining", "Growing wheat", "Shipping only"], "Sport and leisure",
      "Recreation zones provide for sport and leisure.", "ERR_SSSP_G8G3A1_B03", 1),
    CLOZE("The busy commercial centre of a city is the ____.", ["CBD", "farm", "harbour", "reserve"], "CBD",
      "The central business district (CBD) is the city's commercial centre.", "ERR_SSSP_G8G3A1_B04", 1),
    TF("Forestry and fishing settlements are types of rural settlement.", "True",
      "Rural settlements include farming, mining, forestry and fishing communities.", "ERR_SSSP_G8G3A1_B05", 1),
    MC("Residential areas can be:", ["High-, middle- and low-income", "Only for industry", "Only shops", "Only farms"], "High-, middle- and low-income",
      "Residential zones range from high- to low-income areas.", "ERR_SSSP_G8G3A1_B06", 2),
    MC("Zoning a city helps to:", ["Organise activities and reduce conflict", "Cause traffic", "Remove all homes", "Stop trade"], "Organise activities and reduce conflict",
      "Zoning organises activities so they fit together better.", "ERR_SSSP_G8G3A1_B07", 2),
    TF("All settlements are the same size and type.", "False",
      "Settlements vary from tiny villages to huge cities, urban and rural.", "ERR_SSSP_G8G3A1_B08", 1),
    MC("A mining town is an example of a:", ["Rural settlement based on a resource", "City CBD", "Shopping centre", "Recreation zone"], "Rural settlement based on a resource",
      "Mining towns are resource-based rural settlements.", "ERR_SSSP_G8G3A1_B09", 2),
    CLOZE("Areas where people live are called ____ areas.", ["residential", "industrial", "commercial", "mining"], "residential",
      "Residential areas are where people live.", "ERR_SSSP_G8G3A1_B10", 1),
    TF("Land use describes how an area of land is used.", "True",
      "Land use is what an area of land is used for (homes, shops, industry, etc.).", "ERR_SSSP_G8G3A1_B11", 1),
    MC("Heavy industry is often placed on the city's edge to:", ["Keep pollution and noise away from homes", "Be near schools", "Block the harbour", "Stop trade"], "Keep pollution and noise away from homes",
      "Heavy industry is zoned away from homes to reduce pollution and noise nuisance.", "ERR_SSSP_G8G3A1_B12", 3),
  ],
  // ── G3.A2 Land use on aerial photographs ──
  "SSSP.G8.G3.A2": [
    MC("A vertical aerial photo looks like a:", ["Map view from straight above", "Side view", "Globe", "Graph"], "Map view from straight above",
      "Vertical aerial photos give a straight-down, map-like view.", "ERR_SSSP_G8G3A2_B01", 2),
    TF("Oblique aerial photos are taken at an angle.", "True",
      "Oblique photos are taken at an angle, showing the sides of features.", "ERR_SSSP_G8G3A2_B02", 2),
    MC("Aerial photographs can show:", ["Natural and built features", "The temperature", "People's names", "The time of day"], "Natural and built features",
      "Aerial photos reveal natural and built (constructed) features.", "ERR_SSSP_G8G3A2_B03", 1),
    CLOZE("A straight-down aerial photo is a ____ photo.", ["vertical", "oblique", "ground", "globe"], "vertical",
      "A straight-down photo is vertical.", "ERR_SSSP_G8G3A2_B04", 1),
    TF("Aerial photos help identify land use in a settlement.", "True",
      "Aerial photos help you see and identify land use in settlements.", "ERR_SSSP_G8G3A2_B05", 1),
    MC("Which would be easiest to spot on an aerial photo of a city?", ["Roads and building patterns", "The smell of the air", "The history of the city", "People's thoughts"], "Roads and building patterns",
      "Roads and building patterns are clearly visible from above.", "ERR_SSSP_G8G3A2_B06", 2),
    MC("An oblique photo is useful because it shows:", ["The sides and shapes of features", "Only the tops", "The underground", "Nothing useful"], "The sides and shapes of features",
      "Oblique photos show the sides and 3D shapes of features.", "ERR_SSSP_G8G3A2_B07", 2),
    TF("A river is a natural feature visible on an aerial photo.", "True",
      "Rivers are natural features clearly seen on aerial photos.", "ERR_SSSP_G8G3A2_B08", 1),
    MC("Land-use maps often use:", ["Shading and colours for different zones", "Only words", "Only photos", "Only numbers"], "Shading and colours for different zones",
      "Shaded land-use maps show different zones by colour.", "ERR_SSSP_G8G3A2_B09", 2),
    CLOZE("A road is a ____ (human-made) feature on an aerial photo.", ["constructed", "natural", "weather", "climate"], "constructed",
      "Roads are constructed (human-made) features.", "ERR_SSSP_G8G3A2_B10", 2),
    TF("Aerial photos can only be taken from straight above.", "False",
      "Aerial photos can be vertical (straight down) or oblique (at an angle).", "ERR_SSSP_G8G3A2_B11", 1),
    MC("Comparing an aerial photo with a map helps you:", ["Understand the area better", "Change the weather", "Cause floods", "Predict prices"], "Understand the area better",
      "Combining photo and map gives a fuller understanding of an area.", "ERR_SSSP_G8G3A2_B12", 2),
  ],
  // ── G3.A3 Urbanisation ──
  "SSSP.G8.G3.A3": [
    MC("Urbanisation means the growth of:", ["Cities and towns", "Deserts", "Oceans", "Forests"], "Cities and towns",
      "Urbanisation is the growth of cities as people move in.", "ERR_SSSP_G8G3A3_B01", 1),
    TF("A drought that ruins crops is a push factor driving people to cities.", "True",
      "Drought and crop failure push people from rural areas to cities.", "ERR_SSSP_G8G3A3_B02", 2),
    MC("Better jobs and services in a city are examples of:", ["Pull factors", "Push factors", "Climate factors", "Tidal factors"], "Pull factors",
      "Jobs and services pull people toward the city.", "ERR_SSSP_G8G3A3_B03", 2),
    CLOZE("Reasons that drive people away from rural areas are ____ factors.", ["push", "pull", "climate", "tidal"], "push",
      "Push factors drive people away from rural areas.", "ERR_SSSP_G8G3A3_B04", 1),
    TF("Rapid city growth can lead to a shortage of housing and services.", "True",
      "Fast urban growth strains housing, water, health care and other services.", "ERR_SSSP_G8G3A3_B05", 1),
    MC("Apartheid laws affected urbanisation by:", ["Controlling where black South Africans could live", "Giving everyone free housing", "Ending all cities", "Building more parks"], "Controlling where black South Africans could live",
      "Apartheid population controls restricted black South Africans' movement and residence.", "ERR_SSSP_G8G3A3_B06", 3),
    MC("Informal settlements often grow because:", ["People move to cities faster than housing is built", "Cities have empty houses", "There is too little work", "People dislike cities"], "People move to cities faster than housing is built",
      "When migration outpaces housing, informal settlements grow.", "ERR_SSSP_G8G3A3_B07", 3),
    TF("Urbanisation only happens in South Africa.", "False",
      "Urbanisation happens across the world, not only in South Africa.", "ERR_SSSP_G8G3A3_B08", 1),
    MC("A pull factor for cities is:", ["Better health care", "Drought", "No jobs", "Poor schools"], "Better health care",
      "Better health care is a pull factor attracting people to cities.", "ERR_SSSP_G8G3A3_B09", 1),
    CLOZE("The fast growth of cities can strain ____ provision like water and housing.", ["service", "weather", "climate", "ocean"], "service",
      "Rapid growth strains the provision of services like water and housing.", "ERR_SSSP_G8G3A3_B10", 2),
    TF("Migration to cities is driven by both push and pull factors.", "True",
      "People move because of push factors (rural problems) and pull factors (city attractions).", "ERR_SSSP_G8G3A3_B11", 1),
    MC("A social issue linked to urbanisation is:", ["Access to housing and health care", "Volcanoes", "Map scales", "Tides"], "Access to housing and health care",
      "Urbanisation raises social issues like housing and health-care access.", "ERR_SSSP_G8G3A3_B12", 2),
  ],
  // ── G4.A1 Trade and transport around the world ──
  "SSSP.G8.G4.A1": [
    MC("Rail transport is well suited to carrying:", ["Heavy goods over land", "Letters by air", "Oil through the sea", "People across oceans"], "Heavy goods over land",
      "Rail efficiently moves heavy goods overland.", "ERR_SSSP_G8G4A1_B01", 2),
    TF("Road transport is flexible and can deliver door to door.", "True",
      "Road transport is flexible, reaching destinations directly.", "ERR_SSSP_G8G4A1_B02", 1),
    MC("Trade happens because places have:", ["Different goods and needs", "Exactly the same things", "No goods", "No needs"], "Different goods and needs",
      "Trade lets places exchange what they have for what they need.", "ERR_SSSP_G8G4A1_B03", 1),
    CLOZE("Liquids like oil are best moved by ____.", ["pipeline", "bicycle", "foot", "sailing ship"], "pipeline",
      "Pipelines efficiently move liquids like oil.", "ERR_SSSP_G8G4A1_B04", 2),
    TF("Air transport is usually cheaper than sea transport for heavy goods.", "False",
      "Air is faster but more expensive; sea is cheaper for heavy bulk goods.", "ERR_SSSP_G8G4A1_B05", 2),
    MC("Which is the slowest but cheapest for very heavy cargo?", ["Sea", "Air", "Pipeline for solids", "Rocket"], "Sea",
      "Sea transport is slow but cheap for very heavy cargo.", "ERR_SSSP_G8G4A1_B06", 2),
    MC("Transport and trade are linked because:", ["Goods must be moved to be traded", "Trade stops transport", "They are unrelated", "Transport ends trade"], "Goods must be moved to be traded",
      "Transport moves traded goods, so the two are linked.", "ERR_SSSP_G8G4A1_B07", 1),
    TF("Different goods suit different modes of transport.", "True",
      "The best mode depends on the goods — bulky, urgent, liquid, etc.", "ERR_SSSP_G8G4A1_B08", 1),
    MC("Urgent, valuable goods are often sent by:", ["Air", "Pipeline", "Slow ship", "Ox-wagon"], "Air",
      "Air is chosen for urgent, valuable goods despite the cost.", "ERR_SSSP_G8G4A1_B09", 2),
    CLOZE("The five main transport modes are sea, air, road, rail and ____.", ["pipeline", "rocket", "balloon", "cable"], "pipeline",
      "The five modes are sea, air, road, rail and pipeline.", "ERR_SSSP_G8G4A1_B10", 1),
    TF("Trade only happens within one country.", "False",
      "Trade happens within countries and between them, around the world.", "ERR_SSSP_G8G4A1_B11", 1),
    MC("Choosing a transport mode depends on:", ["Cost, speed and the type of goods", "Only the weather", "Only the colour", "Only the day"], "Cost, speed and the type of goods",
      "Cost, speed and the goods all decide the best transport mode.", "ERR_SSSP_G8G4A1_B12", 2),
  ],
  // ── G4.A2 Trade and transport in South Africa ──
  "SSSP.G8.G4.A2": [
    MC("Goods leaving a country to be sold abroad are called:", ["Exports", "Imports", "Reserves", "Tariffs"], "Exports",
      "Exports are goods sold to other countries.", "ERR_SSSP_G8G4A2_B01", 2),
    TF("Goods brought into a country from abroad are imports.", "True",
      "Imports are goods bought from other countries.", "ERR_SSSP_G8G4A2_B02", 1),
    MC("Harbours are usually located where there is:", ["Sheltered, deep water", "A high mountain", "A desert", "A busy CBD only"], "Sheltered, deep water",
      "Harbours need sheltered, deep water for ships.", "ERR_SSSP_G8G4A2_B03", 2),
    CLOZE("Roads, railways and ____ link South Africa's harbours to inland areas.", ["pipelines", "rivers only", "footpaths", "runways"], "pipelines",
      "Roads, railways and pipelines connect harbours inland.", "ERR_SSSP_G8G4A2_B04", 2),
    TF("South Africa trades with countries around the world.", "True",
      "South Africa imports and exports goods globally through its harbours.", "ERR_SSSP_G8G4A2_B05", 1),
    MC("A container ship is designed to carry:", ["Standard steel boxes of cargo", "Only oil", "Only passengers", "Only cars"], "Standard steel boxes of cargo",
      "Container ships carry goods in standard steel containers.", "ERR_SSSP_G8G4A2_B06", 2),
    MC("An advantage of road transport over rail is that it:", ["Can deliver directly to many places", "Carries the heaviest bulk best", "Needs no roads", "Is best across oceans"], "Can deliver directly to many places",
      "Road transport is flexible and delivers directly door to door.", "ERR_SSSP_G8G4A2_B07", 3),
    TF("Johannesburg is a major South African harbour.", "False",
      "Johannesburg is inland; harbours like Durban and Cape Town are on the coast.", "ERR_SSSP_G8G4A2_B08", 1),
    MC("Future transport networks need to consider:", ["Growing demand and efficiency", "Less trade", "Removing all roads", "Stopping ships"], "Growing demand and efficiency",
      "Planning future transport means meeting growing demand efficiently.", "ERR_SSSP_G8G4A2_B09", 3),
    CLOZE("A ____ ship carries oil and other liquids.", ["tanker", "container", "passenger", "fishing"], "tanker",
      "Tankers carry oil and other liquids.", "ERR_SSSP_G8G4A2_B10", 2),
    TF("Harbours connect sea transport to land transport.", "True",
      "Harbours link ships with road, rail and pipelines.", "ERR_SSSP_G8G4A2_B11", 1),
    MC("A harbour case study looks at one harbour's:", ["Location, exports and links", "Weather only", "History only", "Population only"], "Location, exports and links",
      "A harbour case study examines its location, trade and transport links.", "ERR_SSSP_G8G4A2_B12", 2),
  ],
  // ── G4.A3 People and transport in urban areas ──
  "SSSP.G8.G4.A3": [
    MC("Traffic congestion means:", ["Roads are too full of vehicles", "Roads are empty", "There are no cars", "Everyone walks"], "Roads are too full of vehicles",
      "Congestion is when roads are overcrowded with vehicles.", "ERR_SSSP_G8G4A3_B01", 1),
    TF("Public transport can carry many people in fewer vehicles than private cars.", "True",
      "Buses and trains move many people in fewer vehicles, easing congestion.", "ERR_SSSP_G8G4A3_B02", 2),
    MC("A bus rapid transit system aims to:", ["Move many commuters quickly on dedicated routes", "Add more private cars", "Close all roads", "Stop public transport"], "Move many commuters quickly on dedicated routes",
      "Rapid transit systems move many commuters efficiently on dedicated routes.", "ERR_SSSP_G8G4A3_B03", 3),
    CLOZE("Cars and minibus taxis are forms of ____ transport.", ["private", "public", "air", "sea"], "private",
      "Private transport includes cars and minibus taxis (vs shared public transport).", "ERR_SSSP_G8G4A3_B04", 2),
    TF("Transport can cause air pollution in cities.", "True",
      "Vehicle exhaust contributes to urban air pollution.", "ERR_SSSP_G8G4A3_B05", 1),
    MC("Cycle lanes encourage people to:", ["Travel by bicycle safely", "Drive more cars", "Stop moving", "Use aeroplanes"], "Travel by bicycle safely",
      "Cycle lanes make cycling safer, easing congestion and pollution.", "ERR_SSSP_G8G4A3_B06", 2),
    MC("Car-free zones in city centres aim to:", ["Reduce traffic and pollution", "Increase traffic", "Remove pedestrians", "Add more parking"], "Reduce traffic and pollution",
      "Car-free zones cut traffic and pollution in busy centres.", "ERR_SSSP_G8G4A3_B07", 3),
    TF("Commuting costs are a transport issue for many workers.", "True",
      "The cost of commuting is a real burden for many workers.", "ERR_SSSP_G8G4A3_B08", 1),
    MC("Subsidised public transport helps commuters by:", ["Lowering the cost of travel", "Raising fares", "Removing buses", "Banning trains"], "Lowering the cost of travel",
      "Subsidies lower the cost of public transport for commuters.", "ERR_SSSP_G8G4A3_B09", 2),
    CLOZE("Buses and trains shared by many people are ____ transport.", ["public", "private", "air", "sea"], "public",
      "Public transport is shared by many commuters.", "ERR_SSSP_G8G4A3_B10", 1),
    TF("Reducing private car use can lower congestion and pollution.", "True",
      "Fewer private cars means less congestion and cleaner air.", "ERR_SSSP_G8G4A3_B11", 1),
    MC("Why do cities encourage public transport and cycling?", ["To ease congestion and pollution", "To increase traffic jams", "To raise pollution", "To remove commuters"], "To ease congestion and pollution",
      "Public transport and cycling help reduce congestion and pollution.", "ERR_SSSP_G8G4A3_B12", 2),
  ],
};

export default G8B;
