// ─── Social Sciences SP — Grade 9 authored question pools ─────────────────────
// CAPS Grade 9: History — World War II · Nuclear Age & Cold War · Turning points
// 1948 & 1950s · Turning points 1960, 1976 & 1994. Geography — Topographic &
// orthophoto map skills · Development issues · Surface forces · Resource use &
// sustainability. Tap-only; refs auto-assigned.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9 = {
  // ─── H1 · Term 1 — World War II ────────────────────────────────────────────
  "SSSP.G9.H1.A1": [
    MC("Who became the dictator of Nazi Germany?",
      ["Adolf Hitler", "Winston Churchill", "Joseph Stalin", "Nelson Mandela"], "Adolf Hitler",
      "Adolf Hitler led the Nazi Party and became dictator of Germany.", "ERR_SSSP_G9H1A1_HITLER", 1),
    TF("The Great Depression of 1929 caused severe hardship that helped the Nazis gain support.", "True",
      "The economic crisis after 1929 created hardship the Nazis exploited to win support.", "ERR_SSSP_G9H1A1_DEPRESSION", 2),
    MC("The democratic government of Germany before Hitler was the:",
      ["Weimar Republic", "Roman Empire", "Soviet Union", "Third Reich"], "Weimar Republic",
      "The Weimar Republic was Germany's democracy that failed, opening the way for Hitler.", "ERR_SSSP_G9H1A1_WEIMAR", 2),
    CLOZE("The 1935 ____ Laws stripped Jewish people of basic rights in Germany.",
      ["Nuremberg", "Versailles", "Berlin", "Union"], "Nuremberg",
      "The 1935 Nuremberg Laws removed the rights of Jewish people, a step toward persecution.", "ERR_SSSP_G9H1A1_NUREMBERG", 2),
    MC("A fascist state like Nazi Germany is best described as:",
      ["A dictatorship that crushes opposition and rights", "A democracy with free elections", "A kingdom with no leader", "A peaceful republic"], "A dictatorship that crushes opposition and rights",
      "Fascism is a dictatorship that suppresses opposition and individual rights.", "ERR_SSSP_G9H1A1_FASCIST", 2),
    TF("The Nazis persecuted Jewish people, Roma, disabled people and political opponents.", "True",
      "The Nazis persecuted many groups, including Jews, Roma, disabled people and opponents.", "ERR_SSSP_G9H1A1_PERSECUTE", 1),
    MC("The Enabling Act of 1933 helped Hitler by:",
      ["Giving him power to make laws without parliament", "Ending his rule", "Restoring democracy", "Freeing prisoners"], "Giving him power to make laws without parliament",
      "The Enabling Act let Hitler rule by decree, cementing his dictatorship.", "ERR_SSSP_G9H1A1_ENABLING", 3),
    TF("The Weimar Republic was a strong, stable democracy that easily survived.", "False",
      "The Weimar Republic was weak and unstable, and it failed — allowing Hitler to take power.", "ERR_SSSP_G9H1A1_WEAK", 2),
    MC("How was a fascist state different from a democracy?",
      ["It removed free elections and silenced opponents", "It had more elections", "It protected all rights", "It had no leader"], "It removed free elections and silenced opponents",
      "Unlike a democracy, a fascist state ends free elections and silences opposition.", "ERR_SSSP_G9H1A1_DIFF", 2),
  ],
  "SSSP.G9.H1.A2": [
    MC("The Holocaust refers to:",
      ["The Nazi genocide of millions of Jews and others", "A famous battle", "A peace treaty", "A type of weapon"], "The Nazi genocide of millions of Jews and others",
      "The Holocaust was the Nazi genocide of six million Jews and millions of others.", "ERR_SSSP_G9H1A2_HOLOCAUST", 1),
    TF("In World War II, Germany was part of the Axis powers.", "True",
      "Germany, Italy and Japan formed the Axis powers, opposed by the Allies.", "ERR_SSSP_G9H1A2_AXIS", 1),
    MC("'Lebensraum' was Hitler's idea of:",
      ["Gaining 'living space' by expanding into other lands", "Sharing land equally", "Protecting Jewish people", "Ending the war"], "Gaining 'living space' by expanding into other lands",
      "Lebensraum ('living space') was the Nazi aim to seize territory from others.", "ERR_SSSP_G9H1A2_LEBENSRAUM", 3),
    CLOZE("The Nazi plan to murder Europe's Jews was called the 'Final ____'.",
      ["Solution", "Treaty", "Answer", "Order"], "Solution",
      "The Nazis called their genocide plan the 'Final Solution'.", "ERR_SSSP_G9H1A2_SOLUTION", 2),
    MC("Sophie Scholl and the White Rose are examples of:",
      ["Resistance to Nazism inside Germany", "Nazi leaders", "Allied generals", "Weapons"], "Resistance to Nazism inside Germany",
      "Sophie Scholl's White Rose movement resisted the Nazis from within Germany.", "ERR_SSSP_G9H1A2_WHITEROSE", 3),
    TF("Some Germans resisted the Nazis despite great danger.", "True",
      "Groups like the White Rose and figures like Bonhoeffer resisted Nazism at great risk.", "ERR_SSSP_G9H1A2_RESIST", 2),
    MC("The Warsaw Ghetto Uprising was:",
      ["Jewish resistance against the Nazis", "A Nazi victory parade", "A peace conference", "A trade fair"], "Jewish resistance against the Nazis",
      "The Warsaw Ghetto Uprising was a brave Jewish revolt against Nazi persecution.", "ERR_SSSP_G9H1A2_WARSAW", 3),
    TF("Extermination camps were places where the Nazis murdered people on a massive scale.", "True",
      "Extermination (death) camps were sites of mass murder during the Holocaust.", "ERR_SSSP_G9H1A2_CAMPS", 1),
  ],
  "SSSP.G9.H1.A3": [
    MC("Which event brought the United States into World War II?",
      ["The Japanese attack on Pearl Harbour", "The Treaty of Versailles", "The Berlin Conference", "The Great Trek"], "The Japanese attack on Pearl Harbour",
      "Japan's 1941 attack on Pearl Harbour drew the USA into the war.", "ERR_SSSP_G9H1A3_PEARL", 1),
    TF("In the Pacific, the USA fought mainly against Japan.", "True",
      "The Pacific war was largely between the USA (and allies) and Japan.", "ERR_SSSP_G9H1A3_JAPAN", 1),
    MC("Japanese Americans during the war were:",
      ["Forced into internment camps in the USA", "Made generals", "Given free land", "Sent to Europe to fight"], "Forced into internment camps in the USA",
      "The USA forced Japanese Americans into internment camps, fearing disloyalty.", "ERR_SSSP_G9H1A3_INTERNMENT", 2),
    CLOZE("Japan's surprise attack on the US naval base at ____ Harbour brought the USA into the war.",
      ["Pearl", "Sydney", "Cape", "Durban"], "Pearl",
      "Pearl Harbour, in Hawaii, was the US base Japan attacked in 1941.", "ERR_SSSP_G9H1A3_CLOZE", 1),
    TF("Japan expanded aggressively in Asia during the war.", "True",
      "Japan expanded across Asia and the Pacific, committing atrocities, especially in China.", "ERR_SSSP_G9H1A3_EXPAND", 2),
    MC("Allied soldiers captured by Japan were often held in:",
      ["Prisoner-of-war camps", "Luxury hotels", "Schools", "Their own homes"], "Prisoner-of-war camps",
      "Captured Allied troops were held in harsh Japanese prisoner-of-war camps.", "ERR_SSSP_G9H1A3_POW", 2),
    TF("The internment of Japanese Americans shows that wars can lead to unfair treatment of people based on their background.", "True",
      "Interning Japanese Americans, despite no proof of disloyalty, was an injustice driven by fear.", "ERR_SSSP_G9H1A3_INJUSTICE", 3),
  ],

  // ─── H2 · Term 2 — The Nuclear Age & the Cold War ──────────────────────────
  "SSSP.G9.H2.A1": [
    MC("After World War II, the two rival superpowers were the USA and the:",
      ["USSR (Soviet Union)", "United Kingdom", "Japan", "Germany"], "USSR (Soviet Union)",
      "The Cold War rivalry was between the USA and the USSR (Soviet Union).", "ERR_SSSP_G9H2A1_USSR", 1),
    TF("The USA followed capitalism while the USSR followed communism.", "True",
      "The USA championed capitalism; the USSR championed communism — the heart of the rivalry.", "ERR_SSSP_G9H2A1_ISMS", 1),
    CLOZE("Under ____, the state controls the economy and aims to share wealth, as in the USSR.",
      ["communism", "capitalism", "fascism", "feudalism"], "communism",
      "Communism, the USSR's system, has the state control the economy.", "ERR_SSSP_G9H2A1_COMMUNISM", 2),
    MC("Capitalism is an economic system based on:",
      ["Private ownership and free markets", "State ownership of everything", "No money at all", "Only farming"], "Private ownership and free markets",
      "Capitalism rests on private ownership and free markets, the USA's system.", "ERR_SSSP_G9H2A1_CAPITALISM", 2),
    TF("The USA and USSR had been allies during World War II.", "True",
      "They fought together against the Axis, then became Cold War rivals after the war.", "ERR_SSSP_G9H2A1_ALLIES", 2),
    MC("Why did tension grow between the USA and USSR after 1945?",
      ["Deep distrust between their opposing systems", "They spoke the same language", "They shared a government", "They had no armies"], "Deep distrust between their opposing systems",
      "Opposing ideologies and mutual distrust drove the post-war tension.", "ERR_SSSP_G9H2A1_TENSION", 2),
  ],
  "SSSP.G9.H2.A2": [
    MC("World War II in the Pacific ended after the USA dropped atomic bombs on which country?",
      ["Japan", "Germany", "Italy", "Russia"], "Japan",
      "Atomic bombs on Hiroshima and Nagasaki led to Japan's surrender, ending the war.", "ERR_SSSP_G9H2A2_JAPAN", 1),
    TF("The atomic bomb was a vastly more powerful weapon than anything used before.", "True",
      "Atomic bombs caused destruction on a completely new scale, opening the Nuclear Age.", "ERR_SSSP_G9H2A2_POWER", 1),
    CLOZE("The two Japanese cities destroyed by atomic bombs were Hiroshima and ____.",
      ["Nagasaki", "Tokyo", "Osaka", "Kyoto"], "Nagasaki",
      "Hiroshima and Nagasaki were the two cities struck by atomic bombs in 1945.", "ERR_SSSP_G9H2A2_NAGASAKI", 2),
    MC("Why did the USA say it dropped the atomic bombs?",
      ["To end the war quickly and avoid a costly invasion", "To start the war", "To help Japan", "To test the weather"], "To end the war quickly and avoid a costly invasion",
      "The USA argued the bombs would end the war fast and avoid a deadly invasion of Japan.", "ERR_SSSP_G9H2A2_WHY", 3),
    TF("Whether dropping the atomic bombs was justified is still debated by historians.", "True",
      "Historians still debate whether using the atomic bombs was justified — a multi-perspective issue.", "ERR_SSSP_G9H2A2_DEBATE", 2),
    MC("The use of atomic bombs marked the beginning of the:",
      ["Nuclear Age", "Stone Age", "Industrial Revolution", "Middle Ages"], "Nuclear Age",
      "The atomic bombings opened the Nuclear Age of immensely powerful weapons.", "ERR_SSSP_G9H2A2_NUCLEAR", 1),
  ],
  "SSSP.G9.H2.A3": [
    MC("The term 'Cold War' means a conflict that was:",
      ["A rivalry without direct fighting between the superpowers", "Fought in cold weather", "A war over ice", "A short, hot battle"], "A rivalry without direct fighting between the superpowers",
      "The Cold War was rivalry and tension without direct superpower fighting.", "ERR_SSSP_G9H2A3_DEF", 1),
    TF("The arms race was a competition to build more and better weapons.", "True",
      "The USA and USSR raced to build bigger arsenals, including nuclear weapons.", "ERR_SSSP_G9H2A3_ARMS", 1),
    MC("The 'space race' was a competition to:",
      ["Achieve milestones in space exploration", "Mine the moon for gold", "Build the most ships", "Grow the most crops"], "Achieve milestones in space exploration",
      "The superpowers competed to lead in space, e.g. satellites and reaching the moon.", "ERR_SSSP_G9H2A3_SPACE", 2),
    CLOZE("In 1961 a wall was built dividing the city of ____ during the Cold War.",
      ["Berlin", "London", "Moscow", "Cape Town"], "Berlin",
      "The Berlin Wall, built in 1961, divided the city and symbolised the Cold War.", "ERR_SSSP_G9H2A3_BERLIN", 2),
    TF("Germany was divided after World War II.", "True",
      "Germany was split, with the Berlin Wall later dividing the city itself.", "ERR_SSSP_G9H2A3_DIVIDE", 2),
    MC("The Berlin Wall became a symbol of:",
      ["The division between East and West", "World peace", "Free trade", "The space race"], "The division between East and West",
      "The Wall symbolised the divide between the communist East and capitalist West.", "ERR_SSSP_G9H2A3_SYMBOL", 2),
    MC("The arms and space races are examples of Cold War:",
      ["Competition without direct war", "Friendly cooperation", "Trade agreements", "Peace treaties"], "Competition without direct war",
      "These races were ways the superpowers competed without fighting directly.", "ERR_SSSP_G9H2A3_COMPETE", 2),
  ],
  "SSSP.G9.H2.A4": [
    MC("The Berlin Wall fell in which year, near the end of the Cold War?",
      ["1989", "1945", "1961", "1914"], "1989",
      "The fall of the Berlin Wall in 1989 marked the Cold War's end.", "ERR_SSSP_G9H2A4_1989", 1),
    TF("The Soviet Union (USSR) collapsed in 1991.", "True",
      "The USSR broke apart in 1991, ending the Cold War era.", "ERR_SSSP_G9H2A4_USSR", 1),
    CLOZE("The fall of the Berlin ____ in 1989 symbolised the end of the Cold War.",
      ["Wall", "Empire", "Republic", "Bridge"], "Wall",
      "The Berlin Wall's fall in 1989 was a powerful symbol of the Cold War ending.", "ERR_SSSP_G9H2A4_WALL", 1),
    MC("Put these end-of-Cold-War events in order: Wall falls, USSR collapses.",
      ["Wall falls (1989), then USSR collapses (1991)", "USSR collapses then Wall falls", "Both in 1945", "Both in 2000"], "Wall falls (1989), then USSR collapses (1991)",
      "The Wall fell in 1989; the Soviet Union collapsed two years later in 1991.", "ERR_SSSP_G9H2A4_ORDER", 2),
    TF("The end of the Cold War reduced tension between the former superpowers.", "True",
      "With the Cold War over, the long superpower standoff eased.", "ERR_SSSP_G9H2A4_EASE", 2),
    MC("The end of the Cold War around 1990 also affected South Africa by:",
      ["Reducing outside support for apartheid and aiding change", "Starting apartheid", "Building the Berlin Wall", "Causing World War II"], "Reducing outside support for apartheid and aiding change",
      "The Cold War's end was one factor that helped push South Africa toward democracy.", "ERR_SSSP_G9H2A4_SA", 3),
  ],

  // ─── H3 · Term 3 — Turning points: 1948 & the 1950s ────────────────────────
  "SSSP.G9.H3.A1": [
    MC("The Universal Declaration of Human Rights was adopted after which event?",
      ["World War II", "The Great Trek", "The discovery of gold", "The Berlin Conference"], "World War II",
      "After World War II's horrors, the UN adopted the Universal Declaration of Human Rights (1948).", "ERR_SSSP_G9H3A1_UDHR", 2),
    TF("Scientists say that 'race' is a social idea, not a biological fact.", "True",
      "Science shows 'race' is a social construct, not a real biological division of humans.", "ERR_SSSP_G9H3A1_RACE", 2),
    MC("The study of human evolution shows that all people:",
      ["Share a common African ancestry", "Come from different species", "Have no shared ancestors", "Were created in Europe"], "Share a common African ancestry",
      "Human evolution shows we all share common ancestors who lived in Africa.", "ERR_SSSP_G9H3A1_ANCESTRY", 2),
    CLOZE("Treating people unfairly because of their 'race' is called ____.",
      ["racism", "nationalism", "tourism", "socialism"], "racism",
      "Racism is unfair treatment of people based on the idea of 'race'.", "ERR_SSSP_G9H3A1_RACISM", 1),
    TF("Apartheid ideology used physical appearance to classify people into 'population groups'.", "True",
      "Apartheid sorted people by superficial physical features into 'race' categories — a false basis.", "ERR_SSSP_G9H3A1_CLASSIFY", 3),
    MC("Why does understanding human evolution challenge racism?",
      ["It shows all humans are closely related", "It proves races are separate species", "It supports apartheid", "It has nothing to say"], "It shows all humans are closely related",
      "Common ancestry shows humans are one closely related family, undercutting racist ideas.", "ERR_SSSP_G9H3A1_CHALLENGE", 3),
  ],
  "SSSP.G9.H3.A2": [
    MC("The National Party came to power and began apartheid in which year?",
      ["1948", "1910", "1976", "1994"], "1948",
      "The National Party won power in 1948 and built the apartheid system.", "ERR_SSSP_G9H3A2_1948", 1),
    TF("Apartheid was a system of strict racial segregation enforced by law.", "True",
      "Apartheid legally separated people by 'race' and gave power to the white minority.", "ERR_SSSP_G9H3A2_DEF", 1),
    MC("The Group Areas Act forced people to:",
      ["Live in separate areas by 'race'", "Choose any neighbourhood", "Vote freely", "Own gold mines"], "Live in separate areas by 'race'",
      "The Group Areas Act forced racial groups into separate residential areas.", "ERR_SSSP_G9H3A2_GROUP", 2),
    CLOZE("The forced removal of the community of ____ is a famous case of the Group Areas Act.",
      ["Sophiatown", "Soweto", "Sharpeville", "Langa"], "Sophiatown",
      "Sophiatown's people were forcibly removed under the Group Areas Act.", "ERR_SSSP_G9H3A2_SOPHIATOWN", 2),
    TF("Racial segregation existed in South Africa even before 1948.", "True",
      "Segregation existed before 1948; apartheid then made it total and systematic law.", "ERR_SSSP_G9H3A2_BEFORE", 2),
    MC("The Bantustans (homelands) were areas where the government:",
      ["Forced many black South Africans to live", "Gave everyone equal rights", "Built gold mines", "Welcomed tourists only"], "Forced many black South Africans to live",
      "Bantustans were 'homelands' to which black South Africans were assigned and forcibly removed.", "ERR_SSSP_G9H3A2_BANTUSTAN", 3),
    TF("Apartheid laws affected where people could live, work and travel.", "True",
      "Apartheid laws controlled almost every part of black South Africans' lives.", "ERR_SSSP_G9H3A2_AFFECT", 1),
  ],
  "SSSP.G9.H3.A3": [
    MC("The Defiance Campaign of the 1950s was an example of:",
      ["Non-violent resistance to apartheid", "An armed war", "A government policy", "A trade deal"], "Non-violent resistance to apartheid",
      "The Defiance Campaign used non-violent protest against apartheid laws.", "ERR_SSSP_G9H3A3_DEFIANCE", 2),
    TF("The Freedom Charter set out a vision of a free and equal South Africa.", "True",
      "The 1955 Freedom Charter declared the demands and vision of a non-racial South Africa.", "ERR_SSSP_G9H3A3_CHARTER", 2),
    MC("The 1956 Women's March was a protest against:",
      ["Pass laws", "Gold mining", "The Berlin Wall", "World War II"], "Pass laws",
      "Thousands of women marched in 1956 against the pass laws that controlled movement.", "ERR_SSSP_G9H3A3_MARCH", 2),
    CLOZE("Albert Luthuli and ____ Ngoyi were leaders in the resistance of the 1950s.",
      ["Lillian", "Helen", "Sophie", "Emily"], "Lillian",
      "Lillian Ngoyi was a leader in the 1950s resistance, including the Women's March.", "ERR_SSSP_G9H3A3_NGOYI", 3),
    MC("The influence of Mahatma Gandhi on the resistance was in the use of:",
      ["Non-violent protest", "Atomic weapons", "Trench warfare", "Gold mining"], "Non-violent protest",
      "Gandhi's philosophy of non-violent resistance influenced the anti-apartheid struggle.", "ERR_SSSP_G9H3A3_GANDHI", 3),
    TF("In the 1950s, much resistance to apartheid was organised and non-violent.", "True",
      "1950s resistance was largely organised, mass-based and non-violent.", "ERR_SSSP_G9H3A3_NONVIOLENT", 1),
    MC("The Treason Trial of the 1950s was the government's attempt to:",
      ["Charge and silence resistance leaders", "Reward protesters", "End apartheid", "Free all prisoners"], "Charge and silence resistance leaders",
      "The Treason Trial charged many resistance leaders, trying to silence the movement.", "ERR_SSSP_G9H3A3_TREASON", 3),
  ],

  // ─── H4 · Term 4 — Turning points: 1960, 1976 & 1994 ───────────────────────
  "SSSP.G9.H4.A1": [
    MC("The Sharpeville massacre took place in which year?",
      ["1960", "1948", "1976", "1994"], "1960",
      "The Sharpeville massacre of 1960 was a turning point in the struggle.", "ERR_SSSP_G9H4A1_1960", 1),
    TF("At Sharpeville, police opened fire on people protesting against pass laws.", "True",
      "Police fired on unarmed pass-law protesters at Sharpeville, killing many.", "ERR_SSSP_G9H4A1_PASS", 1),
    MC("The PAC, formed in 1959, was involved in the protests around:",
      ["Sharpeville and Langa", "World War II", "The gold mines", "The Berlin Wall"], "Sharpeville and Langa",
      "The PAC organised the anti-pass protests at Sharpeville and Langa in 1960.", "ERR_SSSP_G9H4A1_PAC", 2),
    CLOZE("The 1960 ____ massacre led to greater repression and resistance.",
      ["Sharpeville", "Soweto", "Sophiatown", "Versailles"], "Sharpeville",
      "Sharpeville (1960) was a turning point that intensified both repression and resistance.", "ERR_SSSP_G9H4A1_CLOZE", 1),
    TF("After Sharpeville, the government increased its repression of opposition.", "True",
      "Sharpeville led to harsher government repression, including banning organisations.", "ERR_SSSP_G9H4A1_REPRESSION", 2),
    MC("A longer-term consequence of Sharpeville was that some resistance movements:",
      ["Turned to armed struggle", "Gave up forever", "Joined the government", "Left South Africa happily"], "Turned to armed struggle",
      "After peaceful protest was met with violence, some movements turned to armed struggle.", "ERR_SSSP_G9H4A1_ARMED", 3),
  ],
  "SSSP.G9.H4.A2": [
    MC("The Soweto uprising began on 16 June of which year?",
      ["1976", "1960", "1948", "1994"], "1976",
      "The Soweto uprising began on 16 June 1976.", "ERR_SSSP_G9H4A2_1976", 1),
    TF("A key cause of the Soweto uprising was the forced use of Afrikaans as a language of instruction.", "True",
      "Students protested the forced use of Afrikaans for teaching, among other grievances.", "ERR_SSSP_G9H4A2_AFRIKAANS", 2),
    MC("Who led the 1976 Soweto protests?",
      ["School students", "Mine owners", "Soldiers", "Foreign tourists"], "School students",
      "The Soweto uprising was led by school students protesting their schooling and apartheid.", "ERR_SSSP_G9H4A2_STUDENTS", 1),
    CLOZE("16 June is now remembered in South Africa as Youth ____.",
      ["Day", "Week", "March", "Trial"], "Day",
      "16 June is commemorated as Youth Day in honour of the 1976 students.", "ERR_SSSP_G9H4A2_YOUTHDAY", 2),
    TF("Protests that began in Soweto spread to other parts of the country.", "True",
      "The 1976 protests spread nationwide, deepening the crisis for the apartheid state.", "ERR_SSSP_G9H4A2_SPREAD", 2),
    MC("A longer-term consequence of 1976 was:",
      ["Stronger resistance and international attention", "The end of all protest", "The start of gold mining", "Germany's defeat"], "Stronger resistance and international attention",
      "Soweto energised resistance and drew global attention to apartheid.", "ERR_SSSP_G9H4A2_CONSEQUENCE", 2),
    {
      question: "Put these South African turning points in the correct order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "National Party comes to power (1948)" },
        { id: "b", text: "Sharpeville massacre (1960)" },
        { id: "c", text: "Soweto uprising (1976)" },
        { id: "d", text: "First democratic election (1994)" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "1948 → 1960 → 1976 → 1994: key turning points from apartheid's start to democracy.", error_signals: ["ERR_SSSP_G9H4A2_SEQ"], difficulty: 2,
    },
  ],
  "SSSP.G9.H4.A3": [
    MC("Nelson Mandela was released from prison in which year?",
      ["1990", "1976", "1960", "1948"], "1990",
      "Mandela was released in 1990, opening the way to negotiations and democracy.", "ERR_SSSP_G9H4A3_1990", 1),
    TF("In 1990 the government unbanned liberation movements like the ANC.", "True",
      "In 1990 the ANC and other movements were unbanned, and Mandela was released.", "ERR_SSSP_G9H4A3_UNBAN", 1),
    MC("South Africa's first democratic election was held in which year?",
      ["1994", "1990", "1976", "1948"], "1994",
      "The first democratic, non-racial election was held in 1994.", "ERR_SSSP_G9H4A3_1994", 1),
    CLOZE("In 1994 South Africans of all races voted in the country's first ____ election.",
      ["democratic", "colonial", "apartheid", "secret"], "democratic",
      "1994 brought South Africa's first democratic election, open to all.", "ERR_SSSP_G9H4A3_CLOZE", 1),
    TF("Pressure inside and outside South Africa helped bring about the end of apartheid.", "True",
      "Internal resistance and external pressure (like sanctions) together helped end apartheid.", "ERR_SSSP_G9H4A3_PRESSURE", 2),
    MC("The period 1990–1994 in South Africa involved:",
      ["Negotiations, some violence, and then democratic elections", "Only peaceful celebrations", "A new world war", "The start of apartheid"], "Negotiations, some violence, and then democratic elections",
      "The transition mixed negotiation and violence before the 1994 election.", "ERR_SSSP_G9H4A3_TRANSITION", 2),
    MC("Nelson Mandela's autobiography is called:",
      ["Long Walk to Freedom", "Mein Kampf", "The Freedom Charter", "Description of Africa"], "Long Walk to Freedom",
      "Mandela's life story is told in 'Long Walk to Freedom'.", "ERR_SSSP_G9H4A3_BOOK", 2),
  ],

  // ─── G1 · Term 1 — Map skills: topographic & orthophoto [image deferred] ───
  "SSSP.G9.G1.A1": [
    MC("Contour lines on a map join places of equal:",
      ["Height above sea level", "Temperature", "Population", "Rainfall"], "Height above sea level",
      "Contour lines connect points of the same height, showing the shape of the land.", "ERR_SSSP_G9G1A1_HEIGHT", 1),
    TF("Contour lines that are close together show a steep slope.", "True",
      "Closely spaced contours mean the land rises sharply — a steep slope.", "ERR_SSSP_G9G1A1_STEEP", 2),
    MC("Contour lines that are far apart show:",
      ["A gentle slope", "A steep cliff", "A river", "A road"], "A gentle slope",
      "Widely spaced contours mean a gentle slope.", "ERR_SSSP_G9G1A1_GENTLE", 2),
    CLOZE("Lines on a map joining points of equal height are called ____ lines.",
      ["contour", "grid", "latitude", "scale"], "contour",
      "Contour lines show height and the shape of the land.", "ERR_SSSP_G9G1A1_CLOZE", 1),
    TF("Contour lines can help you identify river valleys and spurs.", "True",
      "The pattern of contours reveals valleys, spurs, hills and ridges.", "ERR_SSSP_G9G1A1_VALLEY", 2),
    MC("If contour lines are very close on one side of a hill and far apart on the other, the hill is:",
      ["Steep on one side, gentle on the other", "Flat all over", "Underwater", "The same on both sides"], "Steep on one side, gentle on the other",
      "Close contours = steep; far apart = gentle, so the slopes differ on each side.", "ERR_SSSP_G9G1A1_DIFF", 3),
  ],
  "SSSP.G9.G1.A2": [
    MC("An orthophoto map is made from:",
      ["Vertical aerial photographs corrected to map scale", "Hand drawings only", "Satellite weather data", "Old paintings"], "Vertical aerial photographs corrected to map scale",
      "Orthophoto maps are aerial photos corrected so distances are true to scale.", "ERR_SSSP_G9G1A2_DEF", 2),
    TF("Orthophoto maps usually have contour lines added to show height.", "True",
      "Orthophoto maps add contour lines so you can read height as well as detail.", "ERR_SSSP_G9G1A2_CONTOUR", 2),
    MC("An advantage of an orthophoto map over an ordinary photo is that you can:",
      ["Measure true distances on it", "Smell the area", "Hear the traffic", "Change the weather"], "Measure true distances on it",
      "Because it's corrected to scale, you can measure real distances on an orthophoto map.", "ERR_SSSP_G9G1A2_MEASURE", 3),
    CLOZE("An orthophoto map is based on a ____ aerial photograph.",
      ["vertical", "oblique", "ground-level", "hand-drawn"], "vertical",
      "Orthophoto maps come from vertical (straight-down) aerial photographs.", "ERR_SSSP_G9G1A2_CLOZE", 2),
    TF("Orthophoto maps show real detail of an area, like a photograph.", "True",
      "Orthophoto maps combine photographic detail with map accuracy.", "ERR_SSSP_G9G1A2_DETAIL", 1),
    MC("The typical scale of an orthophoto map mentioned in CAPS is:",
      ["1:10 000", "1:1 000 000", "1:50", "1:5"], "1:10 000",
      "Orthophoto maps are commonly at a large scale such as 1:10 000.", "ERR_SSSP_G9G1A2_SCALE", 3),
  ],
  "SSSP.G9.G1.A3": [
    MC("On a topographic map, symbols are explained in the:",
      ["Key (legend)", "Index", "Title only", "Scale bar"], "Key (legend)",
      "The key (legend) explains what each topographic map symbol means.", "ERR_SSSP_G9G1A3_KEY", 1),
    TF("A 1:50 000 topographic map shows natural and constructed (human-made) features.", "True",
      "Topographic maps show both natural features (rivers, hills) and built features (roads, towns).", "ERR_SSSP_G9G1A3_FEATURES", 1),
    MC("On a 1:50 000 map, how much real distance does 2 cm represent?",
      ["1 km", "2 km", "50 km", "100 m"], "1 km",
      "1:50 000 means 1 cm = 0.5 km, so 2 cm = 1 km.", "ERR_SSSP_G9G1A3_CALC", 3),
    CLOZE("Numbers used to give the exact position of a feature on a topographic map are called ____.",
      ["coordinates", "contours", "symbols", "scales"], "coordinates",
      "Coordinates (using grid references or latitude/longitude) locate features exactly.", "ERR_SSSP_G9G1A3_COORD", 2),
    TF("Contour patterns on a topographic map can show hills, ridges and valleys.", "True",
      "By reading contour patterns you can recognise hills, ridges, valleys and spurs.", "ERR_SSSP_G9G1A3_PATTERN", 2),
    MC("To measure distance accurately on a topographic map you use the:",
      ["Scale (line or ratio)", "Title", "Date", "Colour key only"], "Scale (line or ratio)",
      "The map's scale lets you convert map distance to real distance.", "ERR_SSSP_G9G1A3_SCALE", 2),
    MC("Which is a 'constructed' (human-made) feature on a topographic map?",
      ["A road", "A river", "A hill", "A forest"], "A road",
      "Roads, towns and dams are constructed features; rivers, hills and forests are natural.", "ERR_SSSP_G9G1A3_CONSTRUCTED", 2),
  ],
  "SSSP.G9.G1.A4": [
    MC("Cross-referencing a map and an aerial photo of the same area helps you to:",
      ["Understand the landscape more fully", "Change the landscape", "Cause erosion", "Predict elections"], "Understand the landscape more fully",
      "Using a map and photo together gives a fuller, cross-checked understanding of an area.", "ERR_SSSP_G9G1A4_CROSS", 2),
    TF("Settlement patterns (shape, size, location) can be identified from maps and photos.", "True",
      "Maps and photos let you describe a settlement's shape, size and location.", "ERR_SSSP_G9G1A4_SETTLEMENT", 2),
    MC("Describing the 'landscape' from a map means describing:",
      ["The shape and features of the land", "The weather forecast", "The population's ages", "The prices in shops"], "The shape and features of the land",
      "Describing the landscape means the land's shape, height and features.", "ERR_SSSP_G9G1A4_LANDSCAPE", 1),
    CLOZE("How land is used — for farming, housing or industry — is called land ____.",
      ["use", "height", "scale", "symbol"], "use",
      "Land use describes what an area of land is used for.", "ERR_SSSP_G9G1A4_LANDUSE", 1),
    TF("A topographic map and an aerial photo must always be of exactly the same area to be useful together.", "False",
      "It helps but isn't essential — comparing an area shown in different ways is still very worthwhile.", "ERR_SSSP_G9G1A4_SAMEAREA", 3),
    MC("Identifying whether a settlement is large or small from a map is describing its:",
      ["Size", "Temperature", "Age", "Religion"], "Size",
      "Size is one feature of a settlement you can read from a map or photo.", "ERR_SSSP_G9G1A4_SIZE", 1),
  ],

  // ─── G2 · Term 2 — Development issues ──────────────────────────────────────
  "SSSP.G9.G2.A1": [
    MC("'Development' is about improving people's:",
      ["Quality of life and well-being", "Number of volcanoes", "Distance from the equator", "Map scale"], "Quality of life and well-being",
      "Development means improving quality of life — economic, social and environmental well-being.", "ERR_SSSP_G9G2A1_DEF", 1),
    TF("The Human Development Index (HDI) measures development using more than just income.", "True",
      "The HDI combines life expectancy, education and income — not income alone.", "ERR_SSSP_G9G2A1_HDI", 2),
    MC("Which three things does the HDI combine?",
      ["Life expectancy, education and income", "Rainfall, height and population", "Gold, diamonds and oil", "Wind, sun and rain"], "Life expectancy, education and income",
      "HDI blends life expectancy, education and per-capita income into one score.", "ERR_SSSP_G9G2A1_THREE", 2),
    CLOZE("A country with a high HDI generally has good health, education and ____.",
      ["income", "rainfall", "altitude", "coastline"], "income",
      "High-HDI countries score well on health, education and income.", "ERR_SSSP_G9G2A1_INCOME", 2),
    {
      question: "Use the data. Which country has the highest HDI? A: 0.92, B: 0.55, C: 0.70.",
      input_type: "data-interpret",
      data: { table: [["Country", "HDI"], ["A", "0.92"], ["B", "0.55"], ["C", "0.70"]] },
      options: ["Country A", "Country B", "Country C", "They are equal"],
      expected: "Country A",
      memo: "HDI runs from 0 to 1; the highest value (0.92) is Country A — the most developed.", error_signals: ["ERR_SSSP_G9G2A1_DATA"], difficulty: 2,
    },
    TF("Development includes economic, social and environmental aspects.", "True",
      "True development balances economic, social and environmental well-being.", "ERR_SSSP_G9G2A1_ASPECTS", 1),
    MC("A country ranked 'low development' on a world HDI map usually has:",
      ["Lower income, health and education levels", "The highest incomes", "The best hospitals", "No problems"], "Lower income, health and education levels",
      "Low-development countries tend to have lower income, health and education.", "ERR_SSSP_G9G2A1_LOW", 2),
  ],
  "SSSP.G9.G2.A2": [
    MC("Which historical factor helps explain why some countries are less developed?",
      ["Colonialism", "Having an HDI", "The space race", "Tourism"], "Colonialism",
      "Colonialism is a key historical factor shaping today's development differences.", "ERR_SSSP_G9G2A2_COLONIAL", 2),
    TF("Unfair trade can keep some countries poorer than others.", "True",
      "Unequal, unfair trade relationships can hold back a country's development.", "ERR_SSSP_G9G2A2_TRADE", 2),
    MC("Which factor generally HELPS a country to develop?",
      ["Good education and health", "Constant war", "Unfair trade against it", "Political instability"], "Good education and health",
      "Strong education and health support development; war and instability hold it back.", "ERR_SSSP_G9G2A2_HELP", 2),
    CLOZE("Political ____ — a stable, peaceful government — supports development.",
      ["stability", "instability", "conflict", "collapse"], "stability",
      "Political stability gives the security needed for development.", "ERR_SSSP_G9G2A2_STABILITY", 2),
    {
      question: "Sort each factor by whether it usually HELPS or HARMS development.",
      input_type: "sort-buckets",
      buckets: [{ id: "help", label: "Helps development" }, { id: "harm", label: "Harms development" }],
      items: [
        { id: "i1", text: "Good schools and hospitals", correct_bucket: "help" },
        { id: "i2", text: "Political stability", correct_bucket: "help" },
        { id: "i3", text: "War and conflict", correct_bucket: "harm" },
        { id: "i4", text: "Unfair trade against the country", correct_bucket: "harm" },
      ],
      expected: "Education, health and stability help; war and unfair trade harm development.",
      pass_threshold: 0.75,
      memo: "Health, education and stability build development; conflict and unfair trade undermine it.", error_signals: ["ERR_SSSP_G9G2A2_SORT"], difficulty: 3,
    },
    TF("Technology and industrialisation can affect a country's level of development.", "True",
      "Access to technology and industry is an important factor in development.", "ERR_SSSP_G9G2A2_TECH", 1),
    MC("There is no single cause of development differences because:",
      ["Many factors work together", "Only gold matters", "Only the weather matters", "It is random"], "Many factors work together",
      "Development differences come from many interacting factors, not one cause.", "ERR_SSSP_G9G2A2_MANY", 2),
  ],
  "SSSP.G9.G2.A3": [
    MC("'Fairer trade' would help development by:",
      ["Giving poorer countries better prices for their goods", "Lowering their prices further", "Banning all trade", "Helping only rich countries"], "Giving poorer countries better prices for their goods",
      "More equal trade gives developing countries fairer prices and a better chance to grow.", "ERR_SSSP_G9G2A3_FAIR", 2),
    TF("Sustainable development meets today's needs without harming future generations.", "True",
      "Sustainable development balances today's needs with the needs of the future.", "ERR_SSSP_G9G2A3_SUSTAIN", 2),
    MC("'Alternative development' suggests that countries:",
      ["Do not all have to copy heavy industrialisation", "Must build the most factories", "Should stop developing", "Must mine more gold"], "Do not all have to copy heavy industrialisation",
      "Alternative development looks for paths beyond just heavy industrialisation.", "ERR_SSSP_G9G2A3_ALT", 3),
    CLOZE("Development that lasts and protects the future is called ____ development.",
      ["sustainable", "rapid", "unfair", "colonial"], "sustainable",
      "Sustainable development is development that can continue without harming the future.", "ERR_SSSP_G9G2A3_CLOZE", 1),
    TF("Community-based projects can be one way to support development.", "True",
      "Local, community-based projects are one approach to improving development.", "ERR_SSSP_G9G2A3_COMMUNITY", 1),
    MC("Why think critically about 'development'?",
      ["It should improve quality of life and care for the poor and planet", "It only means more factories", "It is always good no matter what", "It cannot be measured"], "It should improve quality of life and care for the poor and planet",
      "A critical view asks whether development truly improves lives and respects the planet.", "ERR_SSSP_G9G2A3_CRITICAL", 3),
  ],

  // ─── G3 · Term 3 — Surface forces that shape the earth ─────────────────────
  "SSSP.G9.G3.A1": [
    MC("Weathering is the process that:",
      ["Breaks down rock where it is", "Moves rock to new places", "Builds mountains", "Causes earthquakes"], "Breaks down rock where it is",
      "Weathering breaks rock down in place; it does not move it (that's erosion).", "ERR_SSSP_G9G3A1_DEF", 1),
    TF("Physical weathering breaks rock into smaller pieces without changing what it is made of.", "True",
      "Physical weathering breaks rock apart mechanically, without changing its chemistry.", "ERR_SSSP_G9G3A1_PHYSICAL", 2),
    MC("Chemical weathering changes rock by:",
      ["Reacting with water or acids to change its minerals", "Freezing only", "Wind only", "Sunlight only"], "Reacting with water or acids to change its minerals",
      "Chemical weathering alters the minerals in rock through reactions with water or acids.", "ERR_SSSP_G9G3A1_CHEMICAL", 2),
    CLOZE("When plant roots grow into and break apart rock, this is ____ weathering.",
      ["biological", "chemical", "physical", "wind"], "biological",
      "Biological weathering involves living things, like roots, breaking rock.", "ERR_SSSP_G9G3A1_BIO", 2),
    TF("Human activities can speed up weathering.", "True",
      "Activities like mining and pollution can increase the rate of weathering.", "ERR_SSSP_G9G3A1_HUMAN", 2),
    {
      question: "Sort each example into the correct type of weathering.",
      input_type: "sort-buckets",
      buckets: [{ id: "phys", label: "Physical" }, { id: "chem", label: "Chemical" }, { id: "bio", label: "Biological" }],
      items: [
        { id: "i1", text: "Water freezes in a crack and splits the rock", correct_bucket: "phys" },
        { id: "i2", text: "Acid rain dissolves limestone", correct_bucket: "chem" },
        { id: "i3", text: "Tree roots break apart a rock", correct_bucket: "bio" },
      ],
      expected: "Freezing = physical, acid = chemical, roots = biological.",
      pass_threshold: 0.66,
      memo: "Physical = mechanical breaking; chemical = changing minerals; biological = living things.", error_signals: ["ERR_SSSP_G9G3A1_SORT"], difficulty: 3,
    },
    MC("Which is an example of physical weathering?",
      ["Water freezing and thawing in cracks", "Acid dissolving rock", "Roots splitting rock", "Rust forming"], "Water freezing and thawing in cracks",
      "Freeze-thaw is a classic example of physical weathering.", "ERR_SSSP_G9G3A1_EXAMPLE", 2),
  ],
  "SSSP.G9.G3.A2": [
    MC("Erosion is different from weathering because erosion:",
      ["Moves the broken material away", "Only breaks rock in place", "Builds new rock", "Heats the earth"], "Moves the broken material away",
      "Weathering breaks rock in place; erosion carries the loosened material away.", "ERR_SSSP_G9G3A2_DEF", 1),
    TF("Rivers, the sea, wind and ice can all cause erosion.", "True",
      "Moving water, waves, wind and ice are all agents of erosion.", "ERR_SSSP_G9G3A2_AGENTS", 1),
    MC("Deposition happens when:",
      ["Material that was carried is dropped in a new place", "Rock is broken up", "Mountains rise", "Volcanoes erupt"], "Material that was carried is dropped in a new place",
      "Deposition is the dropping of eroded material in a new location.", "ERR_SSSP_G9G3A2_DEPOSITION", 2),
    CLOZE("A river drops sand and mud, building up a flat fertile area at its mouth called a ____.",
      ["delta", "cliff", "dune", "glacier"], "delta",
      "A delta is land built by river deposition at the mouth of a river.", "ERR_SSSP_G9G3A2_DELTA", 3),
    TF("Wind can both erode and deposit material, for example forming sand dunes.", "True",
      "Wind erodes loose material and deposits it elsewhere, building features like dunes.", "ERR_SSSP_G9G3A2_WIND", 2),
    {
      question: "Sort each as an example of EROSION or DEPOSITION.",
      input_type: "sort-buckets",
      buckets: [{ id: "ero", label: "Erosion" }, { id: "dep", label: "Deposition" }],
      items: [
        { id: "i1", text: "Waves wear away a cliff", correct_bucket: "ero" },
        { id: "i2", text: "A river drops sand to form a delta", correct_bucket: "dep" },
        { id: "i3", text: "Wind blows soil off a bare field", correct_bucket: "ero" },
        { id: "i4", text: "Wind builds a sand dune", correct_bucket: "dep" },
      ],
      expected: "Wearing away = erosion; dropping/building up = deposition.",
      pass_threshold: 0.75,
      memo: "Erosion wears away and carries off; deposition drops material to build new features.", error_signals: ["ERR_SSSP_G9G3A2_SORT"], difficulty: 3,
    },
    MC("Moving ice (a glacier) shapes the land by:",
      ["Eroding and depositing material as it moves", "Heating the rock", "Causing earthquakes", "Doing nothing"], "Eroding and depositing material as it moves",
      "Glaciers erode the land they pass over and deposit material as they melt.", "ERR_SSSP_G9G3A2_ICE", 2),
  ],
  "SSSP.G9.G3.A3": [
    MC("Which human activity is a major cause of soil erosion?",
      ["Poor farming practices", "Reading maps", "Drawing contour lines", "Studying history"], "Poor farming practices",
      "Poor farming, construction and mining strip and loosen soil, causing erosion.", "ERR_SSSP_G9G3A3_FARMING", 1),
    TF("Removing vegetation makes soil erosion worse.", "True",
      "Plants hold soil together; removing them lets soil wash or blow away more easily.", "ERR_SSSP_G9G3A3_VEG", 1),
    MC("Overgrazing by too many animals causes soil erosion because it:",
      ["Strips away the plants that protect the soil", "Adds more plants", "Cools the soil", "Builds new soil"], "Strips away the plants that protect the soil",
      "Overgrazing removes the protective plant cover, exposing soil to erosion.", "ERR_SSSP_G9G3A3_OVERGRAZE", 2),
    CLOZE("When fertile topsoil is washed or blown away, farmland loses its ____.",
      ["fertility", "height", "scale", "colour"], "fertility",
      "Losing topsoil means losing fertility, which harms farming.", "ERR_SSSP_G9G3A3_FERTILITY", 2),
    TF("Soil erosion can reduce the amount of food a region can produce.", "True",
      "Eroded, less fertile soil produces less food, threatening food supply.", "ERR_SSSP_G9G3A3_FOOD", 2),
    MC("Which practice would help REDUCE soil erosion on farmland?",
      ["Planting cover crops and trees", "Removing all plants", "Ploughing straight down a steep slope", "Overgrazing"], "Planting cover crops and trees",
      "Cover crops, trees and careful methods protect soil and reduce erosion.", "ERR_SSSP_G9G3A3_REDUCE", 3),
    TF("Construction and mining can also contribute to soil erosion.", "True",
      "Clearing land for construction and mining exposes soil and adds to erosion.", "ERR_SSSP_G9G3A3_MINING", 1),
  ],

  // ─── G4 · Term 4 — Resource use & sustainability ───────────────────────────
  "SSSP.G9.G4.A1": [
    MC("A renewable resource is one that:",
      ["Can be replaced or refilled if used carefully", "Can never run out no matter what", "Always runs out instantly", "Is always man-made"], "Can be replaced or refilled if used carefully",
      "Renewable resources (like forests, fish) can recover if used carefully.", "ERR_SSSP_G9G4A1_RENEW", 1),
    TF("Coal and oil are non-renewable resources.", "True",
      "Coal and oil take millions of years to form, so they are non-renewable.", "ERR_SSSP_G9G4A1_NONRENEW", 1),
    MC("Over-fishing the oceans is a problem because it:",
      ["Uses fish faster than they can breed and recover", "Adds more fish", "Cools the ocean", "Has no effect"], "Uses fish faster than they can breed and recover",
      "Over-fishing takes fish faster than they can reproduce, depleting the resource.", "ERR_SSSP_G9G4A1_OVERFISH", 2),
    CLOZE("Resources that run out and cannot be replaced are called ____ resources.",
      ["non-renewable", "renewable", "endless", "free"], "non-renewable",
      "Non-renewable resources cannot be replaced once used up.", "ERR_SSSP_G9G4A1_CLOZE", 1),
    {
      question: "Sort each resource as renewable or non-renewable.",
      input_type: "sort-buckets",
      buckets: [{ id: "ren", label: "Renewable" }, { id: "non", label: "Non-renewable" }],
      items: [
        { id: "i1", text: "Solar (sun) energy", correct_bucket: "ren" },
        { id: "i2", text: "Wind energy", correct_bucket: "ren" },
        { id: "i3", text: "Coal", correct_bucket: "non" },
        { id: "i4", text: "Oil", correct_bucket: "non" },
      ],
      expected: "Sun and wind are renewable; coal and oil are non-renewable.",
      pass_threshold: 0.75,
      memo: "Renewable sources (sun, wind) refill naturally; fossil fuels (coal, oil) do not.", error_signals: ["ERR_SSSP_G9G4A1_SORT"], difficulty: 2,
    },
    TF("Overgrazing land is an example of unwise resource use.", "True",
      "Overgrazing damages the land, an example of using a resource unwisely.", "ERR_SSSP_G9G4A1_OVERGRAZE", 1),
    MC("Why should non-renewable resources be used carefully?",
      ["Once used up they cannot be replaced", "They refill instantly", "They are unlimited", "They are worthless"], "Once used up they cannot be replaced",
      "Non-renewables are finite, so careful use makes them last longer.", "ERR_SSSP_G9G4A1_CARE", 2),
  ],
  "SSSP.G9.G4.A2": [
    MC("Sustainable use of a resource means using it:",
      ["So it can keep being available in the future", "Up as fast as possible", "Only once", "Never"], "So it can keep being available in the future",
      "Sustainable use keeps a resource available for the future.", "ERR_SSSP_G9G4A2_DEF", 1),
    TF("Sustainable fishing means catching fish at a rate they can replace.", "True",
      "Sustainable fishing keeps catches within the level fish can naturally replace.", "ERR_SSSP_G9G4A2_FISHING", 2),
    MC("Who has a role in choosing more sustainable resource use?",
      ["Individuals, businesses and governments", "Only governments", "Only children", "Nobody"], "Individuals, businesses and governments",
      "Everyone — individuals, businesses and governments — can choose more sustainable use.", "ERR_SSSP_G9G4A2_WHO", 2),
    CLOZE("Reducing the amount of carbon we release helps lower our carbon ____.",
      ["footprint", "scale", "contour", "index"], "footprint",
      "Your 'carbon footprint' is the amount of carbon your activities release.", "ERR_SSSP_G9G4A2_FOOTPRINT", 2),
    TF("Sustainable land use for grazing means not putting too many animals on the land.", "True",
      "Limiting animal numbers prevents overgrazing, keeping grazing land sustainable.", "ERR_SSSP_G9G4A2_GRAZING", 2),
    MC("Which choice helps reduce pressure on resources?",
      ["Reducing, reusing and recycling", "Wasting more", "Using non-renewables faster", "Throwing everything away"], "Reducing, reusing and recycling",
      "Reduce, reuse and recycle all lower the pressure on resources.", "ERR_SSSP_G9G4A2_RRR", 1),
    TF("Sustainability is only about the environment and never about people or the economy.", "False",
      "Sustainability balances environmental, social and economic needs together.", "ERR_SSSP_G9G4A2_BALANCE", 3),
  ],
  "SSSP.G9.G4.A3": [
    MC("Food security means that people:",
      ["Have reliable access to enough safe food", "Grow only one crop", "Eat only imported food", "Never farm"], "Have reliable access to enough safe food",
      "Food security means everyone reliably has enough safe, nutritious food.", "ERR_SSSP_G9G4A3_DEF", 1),
    TF("Science and technology can increase food production.", "True",
      "New methods and technology can raise how much food is produced.", "ERR_SSSP_G9G4A3_TECH", 1),
    MC("Genetic modification of crops is used to:",
      ["Change crops, for example to resist pests or grow more", "Cool the planet", "Cause floods", "Stop all farming"], "Change crops, for example to resist pests or grow more",
      "GM crops are altered to improve traits like pest resistance or yield, though it is debated.", "ERR_SSSP_G9G4A3_GM", 3),
    CLOZE("Raising many animals close together at high density is called factory ____.",
      ["farming", "fishing", "mining", "trading"], "farming",
      "Factory farming raises livestock at high density to produce a lot of food.", "ERR_SSSP_G9G4A3_FACTORY", 2),
    TF("There can be advantages and disadvantages to different ways of producing food.", "True",
      "Each food-production method has trade-offs — economic, environmental, health and ethical.", "ERR_SSSP_G9G4A3_TRADEOFF", 2),
    MC("Sustainable farming aims to:",
      ["Produce food in ways that protect the land for the future", "Use up all the soil quickly", "Ignore the environment", "Stop growing food"], "Produce food in ways that protect the land for the future",
      "Sustainable farming produces food while protecting soil and the environment for the future.", "ERR_SSSP_G9G4A3_SUSTAIN", 2),
    MC("Why might people be concerned about factory farming?",
      ["Animal welfare and environmental effects", "It produces no food", "It uses no resources", "It is illegal everywhere"], "Animal welfare and environmental effects",
      "Factory farming raises concerns about animal welfare and environmental impact.", "ERR_SSSP_G9G4A3_CONCERN", 3),
  ],
};

export default G9;
