// ─── Social Sciences SP — Grade 7 authored question pools ─────────────────────
//
// Keyed by skill id → question array. Refs are auto-assigned by the generator
// (build-social-sciences-sp.mjs), so questions here omit `ref`. Every item is
// tap-only: choice / true-false / cloze / sequence / sort-buckets /
// highlight-source. No free-text.
//
// Mechanic payload shapes (see types/social-sciences-sp.ts):
//   choice/true-false/cloze : options[] + expected
//   sequence                : items[{id,text}] + expected_order[ids]
//   sort-buckets            : buckets[{id,label}] + items[{id,text,correct_bucket}]
//   highlight-source        : source_text + task + targets[{phrase,reason}] + min_correct/max_wrong
//
// CAPS Grade 7 History (Senior Phase): Mali & Timbuktu · Transatlantic slave
// trade · Colonisation of the Cape · Conflict on the Cape frontiers.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7 = {
  // ─── H1 · Term 1 — The kingdom of Mali & Timbuktu ──────────────────────────
  "SSSP.G7.H1.A1": [
    MC("Which animal carried goods across the Sahara Desert in the trans-Saharan trade?",
      ["Camels", "Horses", "Donkeys", "Oxen"], "Camels",
      "Camels can travel long distances across the desert with little water, so traders moved goods in camel caravans.", "ERR_SSSP_G7H1_CARAVAN", 1),
    TF("Salt was carried south across the Sahara and exchanged for gold.", "True",
      "Salt was scarce in West Africa but gold was plentiful, so salt moving south was swapped for gold moving north.", "ERR_SSSP_G7H1_SALT_GOLD", 1),
    MC("Which of these was NOT a major good traded across the Sahara?",
      ["Tea from China", "Gold", "Salt", "Ivory"], "Tea from China",
      "Sahara trade moved gold, salt, ivory, enslaved people and ostrich feathers — not tea from China.", "ERR_SSSP_G7H1_GOODS", 2),
    MC("Islam spread into West Africa mainly through which group of people?",
      ["Traders crossing the Sahara", "European missionaries", "Atlantic sailors", "Roman soldiers"], "Traders crossing the Sahara",
      "Muslim traders carried their religion along the caravan routes, so Islam spread into West Africa through trade.", "ERR_SSSP_G7H1_ISLAM", 2),
    CLOZE("A group of camels and traders travelling together across the desert was called a ____.",
      ["caravan", "convoy", "fleet", "herd"], "caravan",
      "A caravan is a group of traders and pack animals travelling together for safety across the desert.", "ERR_SSSP_G7H1_CARAVAN_WORD", 1),
    TF("Trans-Saharan trade connected West Africa with North Africa and the Mediterranean.", "True",
      "Goods, ideas and religion flowed between West Africa and North Africa across the Sahara trade routes.", "ERR_SSSP_G7H1_CONNECT", 1),
    MC("Why was salt so valuable in West Africa?",
      ["It was scarce and needed to preserve food", "It was used as money everywhere", "It could only be mined in Europe", "It was used to make weapons"], "It was scarce and needed to preserve food",
      "Salt was rare in West Africa and essential for preserving food and health, which made it extremely valuable.", "ERR_SSSP_G7H1_SALT_VALUE", 2),
    {
      question: "Put these steps of a trans-Saharan trade journey in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Traders load salt onto camels in North Africa" },
        { id: "b", text: "The caravan crosses the Sahara Desert" },
        { id: "c", text: "Salt is exchanged for gold in West Africa" },
        { id: "d", text: "Gold is carried back north to the Mediterranean" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Salt went south, was swapped for gold, and the gold travelled north — the heart of the trans-Saharan trade.",
      error_signals: ["ERR_SSSP_G7H1_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each item by the direction it usually travelled in the Sahara trade.",
      input_type: "sort-buckets",
      buckets: [{ id: "south", label: "Carried SOUTH into West Africa" }, { id: "north", label: "Carried NORTH out of West Africa" }],
      items: [
        { id: "i1", text: "Salt", correct_bucket: "south" },
        { id: "i2", text: "Gold", correct_bucket: "north" },
        { id: "i3", text: "Ivory", correct_bucket: "north" },
        { id: "i4", text: "Goods from the Mediterranean", correct_bucket: "south" },
      ],
      expected: "Salt and Mediterranean goods came south; gold and ivory went north.",
      pass_threshold: 0.75,
      memo: "West Africa sent out its gold and ivory, and received salt and manufactured goods from the north.", error_signals: ["ERR_SSSP_G7H1_DIRECTION"], difficulty: 3,
    },
    MC("The trans-Saharan trade helped which kind of settlement to grow in West Africa?",
      ["Wealthy trading towns and cities", "Fishing villages on the Atlantic", "Mountain monasteries", "Roman forts"], "Wealthy trading towns and cities",
      "Trade brought wealth that allowed towns and cities like Timbuktu to grow into important centres.", "ERR_SSSP_G7H1_TOWNS", 2),
    TF("Camel caravans usually crossed the Sahara alone with a single trader.", "False",
      "Crossing the desert was dangerous, so traders travelled together in large caravans for safety.", "ERR_SSSP_G7H1_ALONE", 1),
    MC("Roughly when did Islam begin spreading across North Africa into West Africa via traders?",
      ["From around the 9th century", "From around the 1<sup>st</sup> century", "From the 18th century", "From the 20th century"], "From around the 9th century",
      "From about the 9th century, Muslim traders spread Islam south along the caravan routes into West Africa.", "ERR_SSSP_G7H1_WHEN_ISLAM", 3),
  ],
  "SSSP.G7.H1.A2": [
    MC("Who was the famous ruler of Mali at the height of its power in the early 14th century?",
      ["Mansa Musa", "Leo Africanus", "Cecil Rhodes", "Shaka"], "Mansa Musa",
      "Mansa Musa ruled Mali at its richest and most powerful, in the early 1300s.", "ERR_SSSP_G7H1A2_RULER", 1),
    TF("Mansa Musa made a famous pilgrimage (hajj) to Mecca.", "True",
      "Mansa Musa's pilgrimage to Mecca was so rich that it became famous across the world.", "ERR_SSSP_G7H1A2_HAJJ", 1),
    MC("Mansa Musa's wealth came mainly from Mali's control of which resource?",
      ["Gold", "Oil", "Diamonds", "Coal"], "Gold",
      "Mali's power rested on its control of West African gold, which made its rulers extremely wealthy.", "ERR_SSSP_G7H1A2_GOLD", 1),
    CLOZE("A great ____ was built in the kingdom of Mali as a place of Muslim worship.",
      ["mosque", "cathedral", "temple", "palace"], "mosque",
      "Mali's rulers were Muslim and built grand mosques, including the famous Great Mosque.", "ERR_SSSP_G7H1A2_MOSQUE", 1),
    MC("Which religion did Mansa Musa follow?",
      ["Islam", "Christianity", "Hinduism", "Buddhism"], "Islam",
      "Mansa Musa was a Muslim ruler, which is why he made the pilgrimage to Mecca.", "ERR_SSSP_G7H1A2_RELIGION", 1),
    TF("Mansa Musa's pilgrimage showed the world how wealthy the kingdom of Mali was.", "True",
      "He travelled with so much gold that his journey advertised Mali's enormous wealth to other lands.", "ERR_SSSP_G7H1A2_SHOW", 2),
    MC("Where was Mecca, the destination of Mansa Musa's pilgrimage?",
      ["Arabia", "Spain", "India", "China"], "Arabia",
      "Mecca, the holiest city of Islam, is in Arabia — a very long journey from Mali.", "ERR_SSSP_G7H1A2_MECCA", 2),
    MC("Which statement best describes the kingdom of Mali under Mansa Musa?",
      ["A wealthy, well-organised Muslim kingdom", "A small group of hunter-gatherers", "A European colony", "An empty desert with no people"], "A wealthy, well-organised Muslim kingdom",
      "Mali was a large, rich and well-run kingdom whose ruler was a devout Muslim.", "ERR_SSSP_G7H1A2_DESCRIBE", 2),
    TF("Mali was located in West Africa.", "True",
      "The kingdom of Mali lay in West Africa, controlling the gold and the trade routes of the region.", "ERR_SSSP_G7H1A2_WHERE", 1),
    CLOZE("Mansa Musa's journey to Mecca is known as a ____.",
      ["pilgrimage", "crusade", "safari", "expedition"], "pilgrimage",
      "A pilgrimage is a religious journey to a holy place — for Muslims, the hajj to Mecca.", "ERR_SSSP_G7H1A2_PILGRIM", 1),
    MC("Why is Mansa Musa often described as one of the richest people in history?",
      ["He controlled vast amounts of gold", "He owned many factories", "He sold oil to Europe", "He printed his own money"], "He controlled vast amounts of gold",
      "His control over West Africa's gold made him fabulously wealthy by any measure.", "ERR_SSSP_G7H1A2_RICH", 2),
    TF("Mali's rulers had no interest in religion or learning.", "False",
      "Mali's Muslim rulers supported religion and learning, funding mosques and centres of study.", "ERR_SSSP_G7H1A2_LEARNING", 2),
  ],
  "SSSP.G7.H1.A3": [
    MC("Timbuktu was famous as a centre of both trade and ____.",
      ["learning", "fishing", "shipbuilding", "gold mining"], "learning",
      "Timbuktu was known for trade AND for learning — scholars studied many subjects there.", "ERR_SSSP_G7H1A3_LEARNING", 1),
    TF("Timbuktu lay on the trans-Saharan caravan route.", "True",
      "Timbuktu's position on the caravan route made it a busy meeting point for traders.", "ERR_SSSP_G7H1A3_ROUTE", 1),
    MC("Which traveller wrote descriptions of Timbuktu in his book 'Description of Africa' (1550)?",
      ["Leo Africanus", "Marco Polo", "Jan van Riebeeck", "David Livingstone"], "Leo Africanus",
      "Leo Africanus described his travels to Timbuktu in his famous 1550 book.", "ERR_SSSP_G7H1A3_LEO", 2),
    MC("At Timbuktu, salt brought across the desert was traded mainly for what?",
      ["Gold", "Iron", "Cattle", "Cloth"], "Gold",
      "Like the wider Sahara trade, salt arriving in Timbuktu was exchanged for gold.", "ERR_SSSP_G7H1A3_SALTGOLD", 1),
    MC("Which subjects were studied by scholars in Timbuktu?",
      ["Mathematics, astronomy, medicine and law", "Only farming", "Only military training", "Only painting"], "Mathematics, astronomy, medicine and law",
      "Timbuktu's scholars studied mathematics, astronomy, medicine, law, history and more.", "ERR_SSSP_G7H1A3_SUBJECTS", 2),
    TF("The Timbuktu manuscripts are old handwritten books that record the city's learning.", "True",
      "The manuscripts are precious handwritten records of the scholarship of Timbuktu, now being preserved.", "ERR_SSSP_G7H1A3_MANUSCRIPTS", 2),
    MC("Why is Timbuktu recognised as a World Heritage Site today?",
      ["Its great history of trade and learning", "Its modern skyscrapers", "Its gold mines", "Its beaches"], "Its great history of trade and learning",
      "Timbuktu is a World Heritage Site because of its outstanding history as a centre of trade and learning.", "ERR_SSSP_G7H1A3_HERITAGE", 2),
    CLOZE("Old handwritten books preserved in Timbuktu are called ____.",
      ["manuscripts", "newspapers", "posters", "maps"], "manuscripts",
      "Manuscripts are handwritten documents — Timbuktu's are a treasured record of African scholarship.", "ERR_SSSP_G7H1A3_MANU_WORD", 1),
    TF("South African scholars have helped to preserve the Timbuktu manuscripts.", "True",
      "South Africa collaborated on a project to help conserve and study the Timbuktu manuscripts.", "ERR_SSSP_G7H1A3_SA", 2),
    MC("Which two things made Timbuktu important?",
      ["Trade and learning", "War and farming", "Fishing and mining", "Sailing and weaving"], "Trade and learning",
      "Remember Timbuktu for two things together: it was a trade centre and a centre of learning.", "ERR_SSSP_G7H1A3_TWO", 1),
    {
      question: "In this description, tap the phrases that show Timbuktu was a centre of LEARNING.",
      input_type: "highlight-source",
      source_text: "Timbuktu stood on the caravan route where salt was traded for gold. Its scholars studied mathematics and astronomy, and its libraries held thousands of manuscripts.",
      task: "Select the phrases about learning (not trade).",
      targets: [
        { phrase: "scholars studied mathematics and astronomy", reason: "Scholarship is about learning." },
        { phrase: "libraries held thousands of manuscripts", reason: "Libraries and manuscripts show a centre of learning." },
      ],
      min_correct: 1, max_wrong: 1,
      memo: "The scholars, libraries and manuscripts all point to learning; the salt-for-gold line is about trade.", error_signals: ["ERR_SSSP_G7H1A3_HIGHLIGHT"], difficulty: 3,
    },
    TF("Timbuktu was a poor, unknown village with no contact with other places.", "False",
      "Timbuktu was a famous, wealthy and connected city known across the Muslim world for trade and learning.", "ERR_SSSP_G7H1A3_POOR", 1),
  ],

  // ─── H2 · Term 2 — The Transatlantic slave trade ───────────────────────────
  "SSSP.G7.H2.A1": [
    MC("Did slavery exist in West Africa before Europeans arrived?",
      ["Yes, but it was different from Atlantic slavery", "No, it was completely unknown", "Only in Europe", "Only after 1900"], "Yes, but it was different from Atlantic slavery",
      "Forms of slavery existed in West Africa before Europeans, but the Atlantic trade was far larger and more brutal.", "ERR_SSSP_G7H2A1_BEFORE", 2),
    TF("The transatlantic slave trade was much larger than slavery that existed in West Africa before Europeans.", "True",
      "The Atlantic trade forcibly moved millions of people — far more than earlier West African slavery.", "ERR_SSSP_G7H2A1_SCALE", 2),
    MC("Before the European slave trade, West Africa was home to what?",
      ["Organised societies, kingdoms and trade", "Only empty land", "Only European colonies", "Only deserts with no people"], "Organised societies, kingdoms and trade",
      "West Africa had well-organised societies, kingdoms and busy trade long before Europeans arrived.", "ERR_SSSP_G7H2A1_SOCIETIES", 1),
    TF("West Africa had no contact with trade before Europeans came.", "False",
      "West Africa already had rich trade networks, including the trans-Saharan trade, before the Atlantic trade.", "ERR_SSSP_G7H2A1_TRADE", 1),
    MC("How was slavery in West Africa generally different from later Atlantic slavery?",
      ["Enslaved people could sometimes keep rights or status", "It moved people across the ocean", "It used plantations in America", "It lasted only one day"], "Enslaved people could sometimes keep rights or status",
      "In some West African societies enslaved people kept certain rights — unlike the harsh, permanent plantation slavery of the Americas.", "ERR_SSSP_G7H2A1_DIFF", 3),
    CLOZE("West Africa was organised into ____ and societies with their own rulers and trade.",
      ["kingdoms", "factories", "colonies", "railways"], "kingdoms",
      "West Africa had kingdoms with their own rulers, trade and culture before European contact.", "ERR_SSSP_G7H2A1_KINGDOMS", 1),
    MC("Which earlier trade route already linked West Africa to the wider world?",
      ["The trans-Saharan trade", "The Suez Canal", "The transatlantic railway", "The Silk Road to Japan"], "The trans-Saharan trade",
      "The trans-Saharan trade had long connected West Africa northwards across the desert.", "ERR_SSSP_G7H2A1_SAHARA", 2),
    TF("The arrival of Europeans changed the scale and nature of slavery in West Africa dramatically.", "True",
      "European demand for plantation labour turned slavery into a vast, brutal trade across the Atlantic.", "ERR_SSSP_G7H2A1_CHANGE", 2),
  ],
  "SSSP.G7.H2.A2": [
    MC("Enslaved people in the American South were forced to work mainly on what?",
      ["Plantations", "Factories", "Ships only", "Schools"], "Plantations",
      "Most enslaved people in the American South worked on large farms called plantations.", "ERR_SSSP_G7H2A2_PLANT", 1),
    MC("Which of these was a major plantation crop in the American South?",
      ["Cotton", "Rice", "Sugar cane", "All of these"], "All of these",
      "Cotton, rice, sugar cane and tobacco were all grown on plantations using enslaved labour.", "ERR_SSSP_G7H2A2_CROPS", 2),
    CLOZE("The terrible sea voyage that carried enslaved Africans across the Atlantic was called the ____ Passage.",
      ["Middle", "Final", "First", "Royal"], "Middle",
      "The Middle Passage was the brutal Atlantic crossing in which many enslaved people died.", "ERR_SSSP_G7H2A2_MIDDLE", 2),
    TF("Plantation owners used enslaved labour because it was cheap and they did not have to pay wages.", "True",
      "Enslaved people were not paid, so plantation owners used their forced labour to make large profits.", "ERR_SSSP_G7H2A2_CHEAP", 2),
    {
      question: "Put the stages of the transatlantic slave trade in the correct order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "People are captured in West Africa" },
        { id: "b", text: "They are sold to European traders on the coast" },
        { id: "c", text: "They cross the Atlantic on the Middle Passage" },
        { id: "d", text: "They are sold and forced to work on plantations" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Capture → sale on the coast → Middle Passage → plantation labour: the path of the Atlantic slave trade.", error_signals: ["ERR_SSSP_G7H2A2_SEQ"], difficulty: 2,
    },
    MC("Where were enslaved people captured before being shipped across the Atlantic?",
      ["West Africa", "Europe", "South America", "Australia"], "West Africa",
      "Enslaved people were captured in West Africa and transported across the Atlantic to the Americas.", "ERR_SSSP_G7H2A2_CAPTURE", 1),
    TF("Conditions on the Middle Passage were comfortable for the enslaved people.", "False",
      "The Middle Passage was overcrowded, cruel and deadly — conditions were horrific.", "ERR_SSSP_G7H2A2_COND", 1),
    MC("Raw materials like cotton produced by enslaved people were mostly sent to be made into goods where?",
      ["Factories in Britain", "Mali", "Timbuktu", "China"], "Factories in Britain",
      "Plantation raw materials such as cotton fed Britain's factories, linking slavery to the Industrial Revolution.", "ERR_SSSP_G7H2A2_RAW", 3),
    MC("A place where enslaved people were bought and sold was called a slave ____.",
      ["market", "school", "harbour", "factory"], "market",
      "Enslaved people were treated as property and sold at slave markets.", "ERR_SSSP_G7H2A2_MARKET", 1),
    TF("Millions of enslaved Africans were taken across the Atlantic to the Americas.", "True",
      "Over the centuries of the trade, millions of Africans were forcibly transported across the Atlantic.", "ERR_SSSP_G7H2A2_MILLIONS", 2),
    MC("Why did plantation owners want a large number of enslaved workers?",
      ["Growing crops like cotton and sugar needed heavy labour", "To teach in schools", "To build churches", "To explore the desert"], "Growing crops like cotton and sugar needed heavy labour",
      "Plantation crops needed huge amounts of hard labour, which owners forced enslaved people to provide.", "ERR_SSSP_G7H2A2_WHY", 2),
  ],
  "SSSP.G7.H2.A3": [
    MC("Which of these was a way enslaved people quietly resisted slavery?",
      ["Working slowly or breaking tools", "Buying their own plantations", "Voting in elections", "Joining the army"], "Working slowly or breaking tools",
      "Quiet (passive) resistance included working slowly, breaking tools and pretending not to understand.", "ERR_SSSP_G7H2A3_PASSIVE", 2),
    MC("Who was the enslaved woman who escaped and then helped many others reach freedom?",
      ["Harriet Tubman", "Emily Pankhurst", "Lillian Ngoyi", "Helen Joseph"], "Harriet Tubman",
      "Harriet Tubman escaped slavery and guided many others to freedom via the Underground Railroad.", "ERR_SSSP_G7H2A3_TUBMAN", 2),
    MC("What was the Underground Railroad?",
      ["A secret network of routes and safe houses for escaping slaves", "A train under the ground", "A type of plantation", "A slave market"], "A secret network of routes and safe houses for escaping slaves",
      "The Underground Railroad was a secret network helping enslaved people escape to free areas.", "ERR_SSSP_G7H2A3_UGRR", 2),
    TF("Nat Turner led a slave revolt in 1831.", "True",
      "Nat Turner's revolt of 1831 was a famous armed uprising against slavery.", "ERR_SSSP_G7H2A3_TURNER", 2),
    MC("The Amistad mutiny of 1839 was led by which captured African?",
      ["Joseph Cinque", "Nat Turner", "John Brown", "Mansa Musa"], "Joseph Cinque",
      "Joseph Cinque led the famous rebellion aboard the slave ship Amistad in 1839.", "ERR_SSSP_G7H2A3_CINQUE", 3),
    {
      question: "Sort each act of resistance as passive (quiet) or active (open).",
      input_type: "sort-buckets",
      buckets: [{ id: "passive", label: "Passive / quiet resistance" }, { id: "active", label: "Active / open resistance" }],
      items: [
        { id: "i1", text: "Working slowly on purpose", correct_bucket: "passive" },
        { id: "i2", text: "Breaking tools", correct_bucket: "passive" },
        { id: "i3", text: "Armed rebellion", correct_bucket: "active" },
        { id: "i4", text: "Escaping along the Underground Railroad", correct_bucket: "active" },
      ],
      expected: "Slow work and breaking tools are passive; rebellion and escape are active.",
      pass_threshold: 0.75,
      memo: "Resistance ranged from quiet sabotage (passive) to open revolt and escape (active).", error_signals: ["ERR_SSSP_G7H2A3_SORT"], difficulty: 3,
    },
    TF("Enslaved people kept their culture alive through songs and stories.", "True",
      "Songs, stories and faith helped enslaved communities keep their culture and hope alive.", "ERR_SSSP_G7H2A3_CULTURE", 1),
    MC("John Brown is remembered for his mission to do what?",
      ["Abolish (end) slavery", "Build plantations", "Trade gold", "Map the Sahara"], "Abolish (end) slavery",
      "John Brown fought to abolish slavery, even leading an armed raid for the cause.", "ERR_SSSP_G7H2A3_BROWN", 2),
    CLOZE("Running away from a plantation to escape slavery is an example of ____ resistance.",
      ["active", "passive", "peaceful", "legal"], "active",
      "Escaping was a bold, active form of resistance against slavery.", "ERR_SSSP_G7H2A3_ESCAPE", 2),
    MC("Why did enslaved people resist in many different ways rather than one way?",
      ["Open rebellion was dangerous, so they also used safer quiet methods", "They were not allowed to rebel openly only on Sundays", "They preferred singing to freedom", "They had no reason to resist"], "Open rebellion was dangerous, so they also used safer quiet methods",
      "Open revolt risked death, so resistance ranged from quiet sabotage to escape to rebellion.", "ERR_SSSP_G7H2A3_WHY", 3),
    TF("Resistance to slavery only ever took the form of large armed revolts.", "False",
      "Most resistance was quieter — go-slows, sabotage, escape — alongside the rarer armed revolts.", "ERR_SSSP_G7H2A3_ONLY", 2),
  ],
  "SSSP.G7.H2.A4": [
    MC("Which regions gained great wealth from the transatlantic slave trade?",
      ["America and Britain", "Mali and Timbuktu", "Australia and India", "China and Japan"], "America and Britain",
      "America and Britain profited enormously, while West Africa suffered lasting harm.", "ERR_SSSP_G7H2A4_GAIN", 1),
    TF("The slave trade caused lasting harm to West Africa.", "True",
      "West Africa lost millions of people and suffered deep, lasting economic and social damage.", "ERR_SSSP_G7H2A4_HARM", 1),
    MC("How did the slave trade help Britain's economy?",
      ["Profits and raw materials helped fund its growth and factories", "It gave Britain gold mines in Africa", "It built Britain's deserts", "It had no effect at all"], "Profits and raw materials helped fund its growth and factories",
      "Slave-trade profits and plantation raw materials fed Britain's growing economy and industry.", "ERR_SSSP_G7H2A4_BRITAIN", 2),
    MC("What did West Africa lose because of the slave trade?",
      ["Millions of young people and stability", "Its deserts", "Its position on the map", "Nothing"], "Millions of young people and stability",
      "Losing millions of mostly young people robbed West Africa of workers, families and stability.", "ERR_SSSP_G7H2A4_LOSS", 2),
    CLOZE("The slave trade brought wealth to Britain and America but ____ to West Africa.",
      ["damage", "wealth", "factories", "gold"], "damage",
      "One side grew rich while the other suffered lasting damage — an unequal and unjust exchange.", "ERR_SSSP_G7H2A4_DAMAGE", 1),
    TF("The slave trade affected the economies of three regions: West Africa, America and Britain.", "True",
      "The trade tied together West Africa, the Americas and Britain in an Atlantic economy built on enslaved labour.", "ERR_SSSP_G7H2A4_THREE", 2),
    {
      question: "Sort each outcome by who experienced it from the slave trade.",
      input_type: "sort-buckets",
      buckets: [{ id: "gain", label: "Britain & America" }, { id: "lose", label: "West Africa" }],
      items: [
        { id: "i1", text: "Profits from selling plantation goods", correct_bucket: "gain" },
        { id: "i2", text: "Cheap raw materials for factories", correct_bucket: "gain" },
        { id: "i3", text: "Loss of millions of young people", correct_bucket: "lose" },
        { id: "i4", text: "Damage to societies and stability", correct_bucket: "lose" },
      ],
      expected: "Britain and America gained profits and materials; West Africa lost people and stability.",
      pass_threshold: 0.75,
      memo: "The trade enriched Britain and America while devastating West Africa.", error_signals: ["ERR_SSSP_G7H2A4_SORT"], difficulty: 3,
    },
    MC("Why is the transatlantic slave trade described as 'unequal' in its effects?",
      ["It enriched some regions while devastating another", "Everyone gained equally", "Only Britain lost out", "It had no economic effect"], "It enriched some regions while devastating another",
      "The benefits and the suffering fell on different regions, making the trade deeply unequal.", "ERR_SSSP_G7H2A4_UNEQUAL", 2),
  ],

  // ─── H3 · Term 3 — Colonisation of the Cape (17th–18th C) ───────────────────
  "SSSP.G7.H3.A1": [
    MC("Which people were herders living at the Cape when the Dutch arrived?",
      ["The Khoikhoi", "The Zulu", "The Dutch", "The British"], "The Khoikhoi",
      "The Khoikhoi were herders living at the Cape long before the Dutch arrived in 1652.", "ERR_SSSP_G7H3A1_KHOI", 1),
    MC("The San people of the Cape mainly lived as what?",
      ["Hunter-gatherers", "Factory workers", "Sailors", "Gold miners"], "Hunter-gatherers",
      "The San were hunter-gatherers, living by hunting animals and gathering plants.", "ERR_SSSP_G7H3A1_SAN", 1),
    TF("African farmers were settled to the east of the Cape, in the summer-rainfall areas.", "True",
      "African farmers settled in the wetter summer-rainfall areas to the east, suited to their crops.", "ERR_SSSP_G7H3A1_FARMERS", 2),
    MC("Why did African farmers settle to the east rather than at the Cape itself?",
      ["Their crops (sorghum, millet) needed summer rainfall", "They disliked the sea", "The Dutch forced them", "There was gold in the east"], "Their crops (sorghum, millet) needed summer rainfall",
      "Crops like sorghum and millet needed summer rain, so farmers settled in the eastern summer-rainfall zone.", "ERR_SSSP_G7H3A1_RAIN", 3),
    CLOZE("The ____ were herders, while the San were hunter-gatherers at the Cape.",
      ["Khoikhoi", "Zulu", "Boers", "British"], "Khoikhoi",
      "Khoikhoi = herders; San = hunter-gatherers. Both lived at the Cape before colonisation.", "ERR_SSSP_G7H3A1_CLOZE", 1),
    TF("The Cape was empty of people before the Dutch arrived.", "False",
      "The Khoikhoi, San and (to the east) African farmers already lived in the region.", "ERR_SSSP_G7H3A1_EMPTY", 1),
    {
      question: "Match each group to how they lived. Sort them into the correct way of life.",
      input_type: "sort-buckets",
      buckets: [{ id: "herd", label: "Herders" }, { id: "hunt", label: "Hunter-gatherers" }, { id: "farm", label: "Crop farmers" }],
      items: [
        { id: "i1", text: "Khoikhoi", correct_bucket: "herd" },
        { id: "i2", text: "San", correct_bucket: "hunt" },
        { id: "i3", text: "African farmers (to the east)", correct_bucket: "farm" },
      ],
      expected: "Khoikhoi = herders, San = hunter-gatherers, African farmers = crop farmers.",
      pass_threshold: 0.66,
      memo: "Three ways of life met around the Cape: herding, hunting-gathering and crop farming.", error_signals: ["ERR_SSSP_G7H3A1_SORT"], difficulty: 2,
    },
    MC("In which century did the Dutch arrive to settle at the Cape?",
      ["The 17th century", "The 14th century", "The 19th century", "The 20th century"], "The 17th century",
      "The Dutch established their station at the Cape in 1652, in the 17th century.", "ERR_SSSP_G7H3A1_CENTURY", 2),
  ],
  "SSSP.G7.H3.A2": [
    MC("Which company set up a station at the Cape in 1652?",
      ["The Dutch East India Company (VOC)", "The British Army", "De Beers", "The Royal Navy"], "The Dutch East India Company (VOC)",
      "The VOC (Dutch East India Company) set up the Cape station in 1652.", "ERR_SSSP_G7H3A2_VOC", 1),
    MC("Why did the VOC want a station at the Cape?",
      ["As a refreshment stop for ships sailing to the East", "To mine gold", "To build factories", "To start a university"], "As a refreshment stop for ships sailing to the East",
      "The Cape was a halfway refreshment station supplying VOC ships on the long route to the East.", "ERR_SSSP_G7H3A2_WHY", 2),
    TF("The VOC first came to the Cape mainly to grow rich farms, not to supply ships.", "False",
      "The VOC's first aim was a supply stop for passing ships, not large-scale farming.", "ERR_SSSP_G7H3A2_AIM", 2),
    MC("Free burghers were what?",
      ["Former VOC employees allowed to farm for themselves", "Enslaved people", "Visiting sailors", "Khoikhoi herders"], "Former VOC employees allowed to farm for themselves",
      "Free burghers were ex-Company servants released to farm and sell produce to the VOC.", "ERR_SSSP_G7H3A2_BURGHER", 2),
    MC("The French Huguenots who came to the Cape were known for which skill?",
      ["Wine-making and farming", "Gold mining", "Shipbuilding", "Printing"], "Wine-making and farming",
      "French Huguenot immigrants added farming and wine-making skills at the Cape.", "ERR_SSSP_G7H3A2_HUG", 2),
    CLOZE("The ____ set up the Cape station in 1652 as a refreshment stop on the route to the East.",
      ["VOC", "ANC", "SANNC", "PAC"], "VOC",
      "The VOC (Dutch East India Company) founded the Cape station in 1652.", "ERR_SSSP_G7H3A2_CLOZE", 1),
    TF("The Huguenots were religious refugees from France.", "True",
      "The Huguenots were French Protestants who fled religious persecution, some settling at the Cape.", "ERR_SSSP_G7H3A2_REFUGEE", 2),
    MC("What did 'free burghers' do that the VOC depended on?",
      ["Produced food to supply the Company and its ships", "Ruled the Netherlands", "Captained the ships", "Mined diamonds"], "Produced food to supply the Company and its ships",
      "Free burghers farmed to supply food to the VOC and passing ships.", "ERR_SSSP_G7H3A2_FOOD", 2),
    MC("The year 1652 is important because it marks the start of what at the Cape?",
      ["Permanent European (Dutch) settlement", "The Industrial Revolution", "Apartheid", "Union of South Africa"], "Permanent European (Dutch) settlement",
      "1652 marks the start of permanent Dutch settlement at the Cape.", "ERR_SSSP_G7H3A2_1652", 1),
  ],
  "SSSP.G7.H3.A3": [
    MC("Why were enslaved people brought to the Cape?",
      ["To provide labour for the settlement and farms", "To rule the colony", "To trade gold", "To teach at schools"], "To provide labour for the settlement and farms",
      "The VOC and free burghers brought enslaved people to do the labour of the settlement and farms.", "ERR_SSSP_G7H3A3_WHY", 1),
    MC("Where did most enslaved people at the Cape come from?",
      ["East Africa, Madagascar and parts of Asia", "Britain", "North America", "the Sahara"], "East Africa, Madagascar and parts of Asia",
      "Cape slaves came mostly from East Africa, Madagascar and Asia — not the Atlantic trade.", "ERR_SSSP_G7H3A3_ORIGIN", 2),
    TF("Slavery at the Cape was the same as the transatlantic slave trade to America.", "False",
      "Cape slavery drew from the Indian Ocean world, not the Atlantic plantation system — a different system.", "ERR_SSSP_G7H3A3_DIFF", 2),
    MC("Which religion was spread at the Cape partly through enslaved people from Asia?",
      ["Islam", "Buddhism", "Hinduism only", "None"], "Islam",
      "Many enslaved people from Asia were Muslim, and Islam became part of the Cape's heritage.", "ERR_SSSP_G7H3A3_ISLAM", 2),
    MC("The development of which language was shaped partly by enslaved people at the Cape?",
      ["Afrikaans", "Zulu", "English", "French"], "Afrikaans",
      "Enslaved people contributed to the development of the Afrikaans language at the Cape.", "ERR_SSSP_G7H3A3_AFR", 3),
    TF("Enslaved people at the Cape sometimes resisted their conditions.", "True",
      "Despite harsh control, enslaved people at the Cape resisted in various ways, met with severe punishment.", "ERR_SSSP_G7H3A3_RESIST", 2),
    CLOZE("Enslaved people brought to the Cape helped shape the religion of ____ and the Afrikaans language.",
      ["Islam", "Christianity", "Hinduism", "Judaism"], "Islam",
      "The legacy of Cape slavery includes Islam and contributions to Afrikaans.", "ERR_SSSP_G7H3A3_CLOZE", 2),
    MC("What is one lasting legacy of slavery at the Cape?",
      ["Cultural and religious heritage, including Islam", "Gold mines", "The VOC's wine farms only", "Nothing at all"], "Cultural and religious heritage, including Islam",
      "Cape slavery left a deep cultural and religious legacy, including Islam and influences on Afrikaans.", "ERR_SSSP_G7H3A3_LEGACY", 2),
    TF("Enslaved people had freedom to leave the Cape whenever they wished.", "False",
      "Enslaved people were owned and controlled, with no freedom to leave — that is what slavery meant.", "ERR_SSSP_G7H3A3_FREE", 1),
  ],
  "SSSP.G7.H3.A4": [
    MC("Who were the trekboers?",
      ["Dutch settlers who moved inland as roaming farmers", "British soldiers", "Khoikhoi herders", "French sailors"], "Dutch settlers who moved inland as roaming farmers",
      "Trekboers were Dutch settler farmers who moved inland with their livestock, slaves and servants.", "ERR_SSSP_G7H3A4_TREK", 1),
    TF("As settlers moved inland, indigenous people lost land and independence.", "True",
      "The expanding frontier dispossessed the Khoikhoi and San of land and freedom.", "ERR_SSSP_G7H3A4_DISPOSSESS", 1),
    MC("Genadendal (founded 1738) was the first what in southern Africa?",
      ["Mission station", "Gold mine", "University", "Harbour"], "Mission station",
      "Genadendal, founded in 1738, was the first mission station in southern Africa.", "ERR_SSSP_G7H3A4_GENADENDAL", 2),
    MC("What happened to the Khoikhoi as the trekboers expanded?",
      ["They were dispossessed and many became servants", "They became VOC directors", "They moved to Europe", "They grew wealthy from gold"], "They were dispossessed and many became servants",
      "Losing their land, many Khoikhoi were forced into service for the trekboers.", "ERR_SSSP_G7H3A4_KHOI", 2),
    CLOZE("Roaming Dutch settler farmers who moved inland with their livestock were called ____.",
      ["trekboers", "burghers", "Huguenots", "missionaries"], "trekboers",
      "Trekboers were the mobile settler farmers of the expanding Cape frontier.", "ERR_SSSP_G7H3A4_CLOZE", 1),
    TF("The expansion of the Cape frontier had no effect on the people already living there.", "False",
      "The frontier's expansion dispossessed indigenous people of land and independence — a major effect.", "ERR_SSSP_G7H3A4_EFFECT", 1),
    MC("A mission station like Genadendal was set up mainly to do what?",
      ["Spread Christianity and offer a settled community", "Mine gold", "Build ships", "Trade enslaved people"], "Spread Christianity and offer a settled community",
      "Mission stations spread Christianity and provided settled communities, sometimes for dispossessed people.", "ERR_SSSP_G7H3A4_MISSION", 2),
    MC("William Bleek and Lucy Lloyd are remembered for recording what?",
      ["San (Bushman) language and stories", "Gold prices", "Ship routes", "Apartheid laws"], "San (Bushman) language and stories",
      "Bleek and Lloyd recorded San language and folklore, preserving a precious record of San culture.", "ERR_SSSP_G7H3A4_BLEEK", 3),
    TF("Land dispossession was a major consequence of the expanding Cape frontier.", "True",
      "Indigenous people losing their land — dispossession — was a central consequence of frontier expansion.", "ERR_SSSP_G7H3A4_LAND", 2),
  ],

  // ─── H4 · Term 4 — Conflict on the Cape frontiers (early 19th C) ───────────
  "SSSP.G7.H4.A1": [
    MC("In the early 19th century, which power took control of the Cape from the Dutch?",
      ["Britain", "France", "Portugal", "Spain"], "Britain",
      "Britain took over the Cape, so power shifted from the Dutch VOC to the British.", "ERR_SSSP_G7H4A1_BRITAIN", 1),
    TF("British control led to more European settlement at the Cape in the early 1800s.", "True",
      "Under Britain, European settlement expanded, including the 1820 settlers.", "ERR_SSSP_G7H4A1_SETTLE", 1),
    CLOZE("In the early 1800s the ____ took over the Cape Colony from the Dutch.",
      ["British", "French", "Zulu", "Portuguese"], "British",
      "The British takeover marked a new colonial power at the Cape.", "ERR_SSSP_G7H4A1_CLOZE", 1),
    MC("The arrival of the British meant the frontier of European settlement did what?",
      ["Expanded further", "Disappeared", "Stayed exactly the same", "Moved back to the sea"], "Expanded further",
      "Under British rule, European settlement and its frontier pushed further outward.", "ERR_SSSP_G7H4A1_EXPAND", 2),
    TF("Power at the Cape shifted from the Dutch VOC to Britain in the early 19th century.", "True",
      "The early 1800s saw the Cape pass from Dutch VOC control to the British Empire.", "ERR_SSSP_G7H4A1_SHIFT", 1),
    MC("More European settlers arriving usually increased what on the frontier?",
      ["Competition for land", "The size of the desert", "The number of VOC ships", "The price of salt"], "Competition for land",
      "More settlers meant more pressure and competition for land, fuelling frontier conflict.", "ERR_SSSP_G7H4A1_LAND", 2),
  ],
  "SSSP.G7.H4.A2": [
    MC("The frontier wars on the eastern frontier were mainly between settlers and which people?",
      ["The Xhosa", "The Khoikhoi only", "The French", "The Zulu of Natal"], "The Xhosa",
      "The eastern frontier saw repeated wars between European settlers and the Xhosa.", "ERR_SSSP_G7H4A2_XHOSA", 1),
    MC("Chief Maqoma (1798–1873) is remembered for what?",
      ["Leading Xhosa resistance to British rule", "Founding the VOC", "Discovering gold", "Building Genadendal"], "Leading Xhosa resistance to British rule",
      "Maqoma was a Xhosa leader who resisted British expansion on the eastern frontier.", "ERR_SSSP_G7H4A2_MAQOMA", 2),
    TF("Andries Stockenström was a colonial official involved on the eastern frontier.", "True",
      "Stockenström was a soldier and official deeply involved in eastern-frontier affairs.", "ERR_SSSP_G7H4A2_STOCK", 2),
    MC("The Great Trek was the movement of which group into the interior?",
      ["The Boers", "The Xhosa", "The British", "The Khoikhoi"], "The Boers",
      "The Great Trek saw Boers (Dutch-descended farmers) move into the interior, away from British rule.", "ERR_SSSP_G7H4A2_TREK", 2),
    MC("Slavery was abolished in the British Cape in which year?",
      ["1836", "1652", "1948", "1994"], "1836",
      "Britain abolished slavery in the Cape in 1836, a major change for the colony.", "ERR_SSSP_G7H4A2_ABOLISH", 2),
    TF("The eastern frontier was peaceful, with no conflict between settlers and the Xhosa.", "False",
      "The eastern frontier was marked by repeated frontier wars between settlers and the Xhosa.", "ERR_SSSP_G7H4A2_PEACE", 1),
    CLOZE("Repeated wars between settlers and the Xhosa on the eastern frontier are called ____ wars.",
      ["frontier", "world", "civil", "cold"], "frontier",
      "These conflicts over land on the colony's edge are known as the frontier wars.", "ERR_SSSP_G7H4A2_CLOZE", 1),
    MC("What were most frontier wars fundamentally about?",
      ["Control of land", "Control of the sea", "Religion only", "Gold mining"], "Control of land",
      "At their heart, the frontier wars were struggles over land between settlers and the Xhosa.", "ERR_SSSP_G7H4A2_ABOUT", 2),
    MC("Why did some Boers leave the Cape on the Great Trek?",
      ["To escape British rule and find new land", "To work in gold mines", "To join the VOC", "To study in Timbuktu"], "To escape British rule and find new land",
      "Many Boers trekked inland to escape British control and seek land of their own.", "ERR_SSSP_G7H4A2_WHYTREK", 2),
  ],
  "SSSP.G7.H4.A3": [
    MC("Who were the Griqua?",
      ["People of mixed descent who traded on the northern frontier", "British soldiers", "Xhosa chiefs", "VOC directors"], "People of mixed descent who traded on the northern frontier",
      "The Griqua were communities of mixed descent and runaway slaves who traded on the northern frontier.", "ERR_SSSP_G7H4A3_GRIQUA", 2),
    TF("Trade was an important feature of the northern frontier of European settlement.", "True",
      "The northern frontier was shaped by trade between the Kora, Griqua, Tswana and the Cape.", "ERR_SSSP_G7H4A3_TRADE", 1),
    MC("The Tswana traded which goods with the Kora and Griqua?",
      ["Ivory, hides, iron and copper", "Cars and oil", "Tea and silk", "Diamonds and gold coins"], "Ivory, hides, iron and copper",
      "The Tswana traded ivory, hides, skins, iron and copper on the northern frontier.", "ERR_SSSP_G7H4A3_TSWANA", 2),
    MC("Robert Moffat (1795–1883) worked at Kuruman as a what?",
      ["Missionary", "Diamond miner", "Sea captain", "VOC governor"], "Missionary",
      "Robert Moffat was a missionary based at Kuruman on the northern frontier.", "ERR_SSSP_G7H4A3_MOFFAT", 2),
    TF("Some Tswana towns of the early 19th century were among the largest settlements in southern Africa.", "True",
      "Towns like Kaditshwene held thousands of people — among the largest in the region at the time.", "ERR_SSSP_G7H4A3_TOWNS", 3),
    CLOZE("On the northern frontier, ____ and missionaries were important alongside traders.",
      ["the Griqua", "the Zulu", "the British navy", "the Huguenots"], "the Griqua",
      "Griqua traders and missionaries shaped contact on the northern frontier.", "ERR_SSSP_G7H4A3_CLOZE", 2),
    MC("How did the northern frontier differ from the eastern frontier?",
      ["It was shaped more by trade and missions than by repeated wars", "It had no people", "It was under the sea", "It was in Europe"], "It was shaped more by trade and missions than by repeated wars",
      "The northern frontier was marked more by trade and mission contact than the eastern frontier's wars.", "ERR_SSSP_G7H4A3_DIFF", 3),
    MC("Manufactured goods, tobacco and pack oxen were traded FROM the Cape to which groups?",
      ["The Kora and Griqua", "The British in London", "The Xhosa kings only", "The Dutch in the Netherlands"], "The Kora and Griqua",
      "The Kora and Griqua traded Cape goods like tobacco and oxen on the northern frontier.", "ERR_SSSP_G7H4A3_KORA", 2),
    TF("Missionaries had no role on the northern frontier.", "False",
      "Missionaries such as Robert Moffat played an important role on the northern frontier.", "ERR_SSSP_G7H4A3_MISSION", 1),
  ],

  // ─── G1 · Term 1 — Map skills (local maps) [image items deferred] ──────────
  "SSSP.G7.G1.A1": [
    MC("On a street map, what do the lines forming a grid help you to do?",
      ["Find and describe the location of places", "Measure temperature", "Show the weather", "Count the population"], "Find and describe the location of places",
      "A grid divides the map into blocks so you can give and find the location of places.", "ERR_SSSP_G7G1A1_GRID", 1),
    TF("A map index helps you find which grid block a place is in.", "True",
      "The index lists places with a grid reference so you can look them up quickly on the map.", "ERR_SSSP_G7G1A1_INDEX", 1),
    CLOZE("To read a grid reference, you read along the bottom first, then ____.",
      ["up the side", "diagonally", "backwards", "around the edge"], "up the side",
      "Grid references go 'along the corridor, then up the stairs' — across the bottom, then up the side.", "ERR_SSSP_G7G1A1_READ", 2),
    MC("What is the main purpose of a street map?",
      ["To show roads and help you find places and routes", "To show the layers of the earth", "To record rainfall", "To show ocean depth"], "To show roads and help you find places and routes",
      "A street map shows roads and places so you can locate them and plan routes.", "ERR_SSSP_G7G1A1_PURPOSE", 1),
    TF("A street guide's index usually lists places in alphabetical order with a grid reference.", "True",
      "Indexes are alphabetical and give each place a grid reference for quick finding.", "ERR_SSSP_G7G1A1_ALPHA", 1),
    MC("If a place is listed as 'C4' in the index, what does C4 tell you?",
      ["The grid block where you will find it", "Its population", "Its height above sea level", "Its temperature"], "The grid block where you will find it",
      "A reference like C4 points to the grid block on the map where the place is found.", "ERR_SSSP_G7G1A1_C4", 2),
    MC("Why are local and street maps useful in everyday life?",
      ["They help people find places and plan journeys", "They predict earthquakes", "They show the whole world at once", "They measure rainfall"], "They help people find places and plan journeys",
      "Local maps help with everyday tasks like finding an address or planning a route.", "ERR_SSSP_G7G1A1_USE", 1),
    TF("You can use a street map to describe a route from one place to another.", "True",
      "Following streets on the map, you can describe the route a person should take.", "ERR_SSSP_G7G1A1_ROUTE", 1),
  ],
  "SSSP.G7.G1.A2": [
    MC("Which three things should a good sketch map include?",
      ["A key, a scale and a north arrow", "A photo, a date and a price", "A graph, a table and a title only", "Rainfall, temperature and wind"], "A key, a scale and a north arrow",
      "A clear sketch map needs a key (to explain symbols), a scale and a north arrow.", "ERR_SSSP_G7G1A2_THREE", 1),
    TF("A north arrow on a map shows which direction is north.", "True",
      "The north arrow tells you which way is north so you can work out other directions.", "ERR_SSSP_G7G1A2_NORTH", 1),
    MC("If north is at the top of the map, which direction is on the right?",
      ["East", "West", "South", "North"], "East",
      "With north at the top: right is east, left is west, bottom is south. ('Never Eat Soggy Worms' = N, E, S, W clockwise.)", "ERR_SSSP_G7G1A2_EAST", 2),
    CLOZE("The four main compass directions are north, south, east and ____.",
      ["west", "up", "left", "centre"], "west",
      "North, south, east and west are the four cardinal (main) compass directions.", "ERR_SSSP_G7G1A2_WEST", 1),
    MC("A 'key' (legend) on a sketch map does what?",
      ["Explains what the symbols mean", "Locks the map", "Shows the price", "Gives the date"], "Explains what the symbols mean",
      "The key (legend) explains what each symbol on the map stands for.", "ERR_SSSP_G7G1A2_KEY", 1),
    TF("When explaining a route, it helps to use compass directions and estimate distances.", "True",
      "Good route directions use compass directions ('go east') and rough distances ('about 2 km').", "ERR_SSSP_G7G1A2_EXPLAIN", 2),
    {
      question: "Put these directions for a route in a sensible order from start to finish.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Start at the school gate" },
        { id: "b", text: "Walk east for about 500 m" },
        { id: "c", text: "Turn north at the shop" },
        { id: "d", text: "Arrive at the clinic on your left" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Clear route directions go step by step from the start point to the destination.", error_signals: ["ERR_SSSP_G7G1A2_SEQ"], difficulty: 2,
    },
    MC("Which direction is exactly opposite to east?",
      ["West", "North", "South", "Up"], "West",
      "East and west are opposites, as are north and south.", "ERR_SSSP_G7G1A2_OPP", 1),
  ],
  "SSSP.G7.G1.A3": [
    MC("What does the scale of a map tell you?",
      ["How distances on the map relate to real distances", "The temperature", "The population", "The time of day"], "How distances on the map relate to real distances",
      "Scale links a distance on the map to the real distance on the ground.", "ERR_SSSP_G7G1A3_SCALE", 1),
    TF("A line scale (bar scale) lets you measure real distances on a map.", "True",
      "You compare a distance on the map to the line scale to read off the real distance.", "ERR_SSSP_G7G1A3_LINE", 1),
    MC("To measure the distance of a winding road on a map, the best tool is:",
      ["A piece of string", "A thermometer", "A calculator only", "A compass needle"], "A piece of string",
      "Lay string along the winding road, then straighten it against the scale to get the distance.", "ERR_SSSP_G7G1A3_STRING", 2),
    CLOZE("A ____ scale uses words, such as '1 cm represents 1 km'.",
      ["word", "line", "ratio", "colour"], "word",
      "A word scale states the relationship in words, e.g. '1 cm represents 1 km'.", "ERR_SSSP_G7G1A3_WORD", 1),
    MC("A 'large-scale' map shows a small area with:",
      ["A lot of detail", "Very little detail", "The whole world", "Only the oceans"], "A lot of detail",
      "Large-scale maps zoom in on a small area and show lots of detail.", "ERR_SSSP_G7G1A3_LARGE", 3),
    TF("You should always check a distance you estimated by measuring it accurately.", "True",
      "Estimating first and then measuring accurately is good practice for map distances.", "ERR_SSSP_G7G1A3_CHECK", 1),
    MC("If a map's word scale says '1 cm represents 2 km', how far is 3 cm on the map in real life?",
      ["6 km", "3 km", "2 km", "9 km"], "6 km",
      "3 cm × 2 km per cm = 6 km on the ground.", "ERR_SSSP_G7G1A3_CALC", 2),
    TF("A straight-line (direct) route between two places is usually shorter than a winding road between them.", "True",
      "The direct line is the shortest distance; a winding road covers more ground.", "ERR_SSSP_G7G1A3_DIRECT", 2),
  ],
  "SSSP.G7.G1.A4": [
    MC("Lines of latitude on a globe run in which direction?",
      ["East–west (across)", "Up and down only", "Diagonally", "In circles around cities"], "East–west (across)",
      "Lines of latitude run east–west and measure how far north or south a place is.", "ERR_SSSP_G7G1A4_LAT", 2),
    MC("Lines of longitude measure how far ____ a place is.",
      ["east or west", "north or south", "up or down", "hot or cold"], "east or west",
      "Lines of longitude run north–south and measure how far east or west a place is.", "ERR_SSSP_G7G1A4_LONG", 2),
    TF("Latitude and longitude together can give the exact location of a place in the news.", "True",
      "A latitude and a longitude cross at one point, pinpointing a place's exact location.", "ERR_SSSP_G7G1A4_EXACT", 1),
    CLOZE("The line of latitude at 0° is called the ____.",
      ["equator", "prime meridian", "tropic", "axis"], "equator",
      "The equator is the 0° line of latitude, halfway between the poles.", "ERR_SSSP_G7G1A4_EQUATOR", 2),
    MC("Why is it useful to locate places in the news on a world map?",
      ["It helps you understand where events happen and why", "It changes the news", "It measures rainfall", "It predicts the future"], "It helps you understand where events happen and why",
      "Placing news events on a map builds understanding of where and why things happen.", "ERR_SSSP_G7G1A4_NEWS", 1),
    TF("Degrees are the units used to measure latitude and longitude.", "True",
      "Latitude and longitude are measured in degrees (°).", "ERR_SSSP_G7G1A4_DEGREES", 1),
    MC("A place's latitude tells you how far it is from which line?",
      ["The equator", "The nearest city", "The coast", "The prime meridian"], "The equator",
      "Latitude measures distance north or south of the equator.", "ERR_SSSP_G7G1A4_FROM", 2),
  ],

  // ─── G2 · Term 2 — Volcanoes, earthquakes & floods ─────────────────────────
  "SSSP.G7.G2.A1": [
    MC("What are the three main layers of the earth, from outside to inside?",
      ["Crust, mantle, core", "Core, crust, mantle", "Mantle, core, crust", "Crust, core, mantle"], "Crust, mantle, core",
      "From outside in: crust (thin skin), mantle (thick middle), core (hot centre).", "ERR_SSSP_G7G2A1_LAYERS", 1),
    TF("The crust is the thin outer layer of the earth.", "True",
      "The crust is the earth's thin, solid outer skin, where we live.", "ERR_SSSP_G7G2A1_CRUST", 1),
    CLOZE("The earth's crust is broken into large pieces called tectonic ____.",
      ["plates", "rivers", "valleys", "layers"], "plates",
      "The crust is split into tectonic plates that slowly move.", "ERR_SSSP_G7G2A1_PLATES", 1),
    MC("The hot centre of the earth is called the:",
      ["Core", "Crust", "Mantle", "Surface"], "Core",
      "The core is the very hot centre of the earth.", "ERR_SSSP_G7G2A1_CORE", 1),
    {
      question: "Order the earth's layers from the surface down to the centre.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Crust" },
        { id: "b", text: "Mantle" },
        { id: "c", text: "Core" },
      ],
      expected_order: ["a", "b", "c"],
      memo: "From the surface inward: crust, then mantle, then core.", error_signals: ["ERR_SSSP_G7G2A1_SEQ"], difficulty: 2,
    },
    TF("Tectonic plates move very quickly, several metres every day.", "False",
      "Tectonic plates move extremely slowly — only a few centimetres a year.", "ERR_SSSP_G7G2A1_SPEED", 2),
    MC("Why does the movement of tectonic plates matter for this topic?",
      ["It causes volcanoes and earthquakes", "It causes rain", "It changes the seasons", "It creates rivers"], "It causes volcanoes and earthquakes",
      "Plate movements at plate edges cause most volcanoes and earthquakes.", "ERR_SSSP_G7G2A1_WHY", 2),
  ],
  "SSSP.G7.G2.A2": [
    MC("Where do most volcanoes occur?",
      ["Along the edges of tectonic plates", "In the middle of flat plains", "Only in deserts", "Only at the equator"], "Along the edges of tectonic plates",
      "Most volcanoes line up along tectonic plate boundaries.", "ERR_SSSP_G7G2A2_WHERE", 1),
    TF("A volcano is an opening in the earth's crust where molten rock can reach the surface.", "True",
      "Volcanoes are openings where magma (molten rock) erupts onto the surface.", "ERR_SSSP_G7G2A2_DEF", 1),
    CLOZE("Molten rock below the surface is called magma; once it erupts it is called ____.",
      ["lava", "ash", "water", "ice"], "lava",
      "Underground it is magma; once it pours out it is called lava.", "ERR_SSSP_G7G2A2_LAVA", 2),
    MC("Volcanoes occur because of activity linked to what?",
      ["Movements of tectonic plates", "Ocean tides", "The phases of the moon", "Wind patterns"], "Movements of tectonic plates",
      "Volcanic activity is driven by plate movements deep in the earth.", "ERR_SSSP_G7G2A2_PLATES", 2),
    TF("Volcanoes and earthquakes often happen in the same regions.", "True",
      "Both cluster along plate boundaries, so they often occur in the same areas.", "ERR_SSSP_G7G2A2_SAME", 2),
    MC("On a world map, the pattern of volcanoes mostly matches the pattern of what?",
      ["Tectonic plate boundaries", "Major cities", "Deserts", "Rivers"], "Tectonic plate boundaries",
      "Mapping volcanoes reveals the lines of the plate boundaries.", "ERR_SSSP_G7G2A2_MAP", 2),
    MC("Which is a possible effect of a volcanic eruption?",
      ["Lava and ash damaging the area", "Lower sea levels worldwide", "An immediate ice age", "Faster plate movement"], "Lava and ash damaging the area",
      "Eruptions can bury land in lava and ash, causing serious local damage.", "ERR_SSSP_G7G2A2_EFFECT", 1),
  ],
  "SSSP.G7.G2.A3": [
    MC("What causes earthquakes?",
      ["Movement of tectonic plates", "Heavy rain", "Strong wind", "Ocean tides"], "Movement of tectonic plates",
      "Earthquakes happen when tectonic plates move or grind against each other.", "ERR_SSSP_G7G2A3_CAUSE", 1),
    TF("An earthquake is a sudden shaking of the ground.", "True",
      "An earthquake is the sudden shaking of the ground caused by movement in the crust.", "ERR_SSSP_G7G2A3_DEF", 1),
    MC("Which of these can be an effect of a strong earthquake?",
      ["Damaged buildings and loss of life", "Better roads", "More rainfall", "Cooler weather"], "Damaged buildings and loss of life",
      "Earthquakes can destroy buildings and infrastructure and cause injury and loss of life.", "ERR_SSSP_G7G2A3_EFFECT", 1),
    CLOZE("An undersea earthquake can cause a giant wave called a ____.",
      ["tsunami", "tide", "current", "breeze"], "tsunami",
      "A tsunami is a huge wave that can be triggered by an undersea earthquake.", "ERR_SSSP_G7G2A3_TSUNAMI", 2),
    MC("Why are some communities at higher risk from earthquakes than others?",
      ["They are near plate boundaries or have weaker buildings", "They have more rain", "They are far from the sea", "They have more schools"], "They are near plate boundaries or have weaker buildings",
      "Risk is higher near plate boundaries and where buildings are not built to resist shaking.", "ERR_SSSP_G7G2A3_RISK", 3),
    TF("There is nothing people can do to reduce the impact of earthquakes.", "False",
      "People reduce impact by building stronger structures, planning and preparing emergency responses.", "ERR_SSSP_G7G2A3_REDUCE", 2),
    {
      question: "Sort each item as a CAUSE or an EFFECT of an earthquake.",
      input_type: "sort-buckets",
      buckets: [{ id: "cause", label: "Cause" }, { id: "effect", label: "Effect" }],
      items: [
        { id: "i1", text: "Tectonic plates grinding past each other", correct_bucket: "cause" },
        { id: "i2", text: "Buildings collapsing", correct_bucket: "effect" },
        { id: "i3", text: "People displaced from their homes", correct_bucket: "effect" },
        { id: "i4", text: "Movement deep in the earth's crust", correct_bucket: "cause" },
      ],
      expected: "Plate movement is the cause; collapsed buildings and displaced people are effects.",
      pass_threshold: 0.75,
      memo: "Causes come from plate movement; effects are the damage and disruption that follow.", error_signals: ["ERR_SSSP_G7G2A3_SORT"], difficulty: 3,
    },
    MC("Preparing for earthquakes (drills, strong buildings) is an example of what?",
      ["Reducing the impact of a hazard", "Causing earthquakes", "Predicting the weather", "Increasing the risk"], "Reducing the impact of a hazard",
      "Preparation and strong building reduce the impact when an earthquake strikes.", "ERR_SSSP_G7G2A3_PREP", 2),
  ],
  "SSSP.G7.G2.A4": [
    MC("Which of these is a common cause of floods?",
      ["Unusually heavy rain", "Strong sunshine", "Cold nights", "Low tides"], "Unusually heavy rain",
      "Heavy rain is a leading cause of floods, especially when the land cannot absorb it.", "ERR_SSSP_G7G2A4_CAUSE", 1),
    TF("Removing vegetation can make flooding worse.", "True",
      "Without plants to soak up and slow water, rain runs off faster and flooding worsens.", "ERR_SSSP_G7G2A4_VEG", 2),
    MC("Which is an effect of a serious flood?",
      ["Damage to homes and loss of life", "Better harvests every time", "Cooler climate worldwide", "More tectonic plates"], "Damage to homes and loss of life",
      "Floods can damage homes, fields and infrastructure and cause injury, disease and loss of life.", "ERR_SSSP_G7G2A4_EFFECT", 1),
    CLOZE("When soil is washed away by flood water, this is called soil ____.",
      ["erosion", "rotation", "fertility", "saturation"], "erosion",
      "Flood water washing soil away is soil erosion, which harms farmland.", "ERR_SSSP_G7G2A4_EROSION", 2),
    TF("Building on a floodplain can put people at higher risk of flooding.", "True",
      "Settling on low land near rivers (floodplains) increases the risk of being flooded.", "ERR_SSSP_G7G2A4_PLAIN", 2),
    MC("How can a community reduce the impact of floods?",
      ["Early warnings, drainage and avoiding building on floodplains", "Planting fewer trees", "Removing all drains", "Building on river banks"], "Early warnings, drainage and avoiding building on floodplains",
      "Warnings, good drainage and sensible building reduce flood impact.", "ERR_SSSP_G7G2A4_REDUCE", 2),
    MC("Besides heavy rain, which event can also cause flooding?",
      ["A tsunami from an undersea earthquake", "A sunny day", "A cold front with no rain", "A full moon alone"], "A tsunami from an undersea earthquake",
      "Tsunamis (from undersea earthquakes) can flood coastal areas.", "ERR_SSSP_G7G2A4_TSUNAMI", 3),
    TF("Floods can spread disease as well as damage property.", "True",
      "Dirty flood water can spread disease, on top of damaging homes and fields.", "ERR_SSSP_G7G2A4_DISEASE", 1),
  ],

  // ─── G3 · Term 3 — Population growth & change ───────────────────────────────
  "SSSP.G7.G3.A1": [
    MC("The birth rate measures the number of:",
      ["Babies born per 1 000 people per year", "Deaths per year", "People who move house", "Schools built"], "Babies born per 1 000 people per year",
      "Birth rate = the number of live births per 1 000 people in a year.", "ERR_SSSP_G7G3A1_BIRTH", 1),
    MC("The death rate measures the number of:",
      ["Deaths per 1 000 people per year", "Births per year", "Marriages per year", "Houses built"], "Deaths per 1 000 people per year",
      "Death rate = the number of deaths per 1 000 people in a year.", "ERR_SSSP_G7G3A1_DEATH", 1),
    TF("Population growth happens when the birth rate is higher than the death rate.", "True",
      "If more are born than die, the population grows (ignoring migration).", "ERR_SSSP_G7G3A1_GROWTH", 2),
    CLOZE("____ mortality rate is the number of babies who die before their first birthday.",
      ["Infant", "Adult", "Old-age", "School"], "Infant",
      "Infant mortality measures deaths of babies under one year old.", "ERR_SSSP_G7G3A1_INFANT", 2),
    MC("Life expectancy is:",
      ["The average number of years a person is expected to live", "The number of births", "The size of a city", "The number of schools"], "The average number of years a person is expected to live",
      "Life expectancy is the average lifespan people in a place can expect.", "ERR_SSSP_G7G3A1_LIFE", 1),
    TF("A high infant mortality rate usually points to poorer health conditions.", "True",
      "Many babies dying young usually signals poorer health care and living conditions.", "ERR_SSSP_G7G3A1_POOR", 2),
    {
      question: "A country has a birth rate of 30 and a death rate of 10 per 1 000. Is its population growing or shrinking?",
      input_type: "choice",
      options: ["Growing", "Shrinking", "Staying exactly the same", "Cannot tell"], expected: "Growing",
      memo: "Births (30) are higher than deaths (10), so the population is growing.", error_signals: ["ERR_SSSP_G7G3A1_CALC"], difficulty: 2,
    },
    MC("Which two measures are subtracted to find natural population growth?",
      ["Birth rate minus death rate", "Death rate minus birth rate", "Births plus deaths", "Life expectancy minus age"], "Birth rate minus death rate",
      "Natural growth = birth rate − death rate (migration is separate).", "ERR_SSSP_G7G3A1_NATURAL", 2),
  ],
  "SSSP.G7.G3.A2": [
    MC("Which of these can lower the death rate in a country?",
      ["Better health care", "More war", "More disease", "Less food"], "Better health care",
      "Improved health care helps people live longer, lowering the death rate.", "ERR_SSSP_G7G3A2_HEALTH", 1),
    TF("Widespread disease such as HIV/AIDS or malaria can raise the death rate.", "True",
      "Serious widespread illness raises the death rate.", "ERR_SSSP_G7G3A2_DISEASE", 1),
    MC("A government policy (like China's former one-child policy) can affect what?",
      ["The birth rate", "The height of mountains", "The number of volcanoes", "The earth's tilt"], "The birth rate",
      "Government policy can encourage or limit births, changing the birth rate.", "ERR_SSSP_G7G3A2_POLICY", 2),
    CLOZE("Wars and conflict tend to ____ the death rate.",
      ["raise", "lower", "freeze", "remove"], "raise",
      "Conflict causes deaths and disrupts health and food supply, raising the death rate.", "ERR_SSSP_G7G3A2_WAR", 2),
    MC("Family needs, attitudes and beliefs mainly influence which rate?",
      ["The birth rate", "The volcano rate", "The rainfall rate", "The tide rate"], "The birth rate",
      "How many children families want is shaped by needs, attitudes and beliefs, affecting birth rate.", "ERR_SSSP_G7G3A2_FAMILY", 2),
    {
      question: "Sort each factor by whether it mainly affects the BIRTH rate or the DEATH rate.",
      input_type: "sort-buckets",
      buckets: [{ id: "birth", label: "Mainly the birth rate" }, { id: "death", label: "Mainly the death rate" }],
      items: [
        { id: "i1", text: "Government policy on family size", correct_bucket: "birth" },
        { id: "i2", text: "Beliefs about how many children to have", correct_bucket: "birth" },
        { id: "i3", text: "A deadly disease outbreak", correct_bucket: "death" },
        { id: "i4", text: "Better hospitals and medicine", correct_bucket: "death" },
      ],
      expected: "Policy and beliefs affect births; disease and health care affect deaths.",
      pass_threshold: 0.75,
      memo: "Some factors push mainly on births, others mainly on deaths — though some link together.", error_signals: ["ERR_SSSP_G7G3A2_SORT"], difficulty: 3,
    },
    TF("Better economic status and wealth often lead families to have fewer children.", "True",
      "In wealthier conditions, families often choose to have fewer children, lowering the birth rate.", "ERR_SSSP_G7G3A2_ECON", 3),
    MC("Why might a high risk of death lead to a higher birth rate in some societies?",
      ["Families may have more children expecting some may not survive", "Because deaths create births", "Because hospitals force it", "It never does"], "Families may have more children expecting some may not survive",
      "Where child death is common, families may have more children — the rates are inter-related.", "ERR_SSSP_G7G3A2_LINK", 3),
  ],
  "SSSP.G7.G3.A3": [
    MC("For most of history, world population grew very slowly. When did it start to rise sharply?",
      ["In the last few hundred years", "10 000 years ago", "In the year 1 AD", "It has always been the same"], "In the last few hundred years",
      "World population stayed low for ages, then climbed steeply only in recent centuries.", "ERR_SSSP_G7G3A3_RISE", 2),
    TF("Increased food production helped the world's population to grow.", "True",
      "More food meant fewer people starved, helping the population grow.", "ERR_SSSP_G7G3A3_FOOD", 1),
    MC("Which scientific development helped reduce deaths and grow the population?",
      ["Better control of disease and improved sanitation", "The invention of the volcano", "Faster plate movement", "Longer days"], "Better control of disease and improved sanitation",
      "Understanding disease, better medicine and clean sanitation cut death rates.", "ERR_SSSP_G7G3A3_SANITATION", 2),
    CLOZE("A line ____ is often used to show how world population has changed over time.",
      ["graph", "map", "key", "scale"], "graph",
      "A line graph shows the trend of population over time clearly.", "ERR_SSSP_G7G3A3_GRAPH", 1),
    {
      question: "Use the data. World population (billions): 1800 → 1, 1927 → 2, 1974 → 4, 2011 → 7. What is the trend?",
      input_type: "data-interpret",
      data: { table: [["Year", "Population (billions)"], ["1800", "1"], ["1927", "2"], ["1974", "4"], ["2011", "7"]] },
      options: ["It is rising, and rising faster over time", "It is falling steadily", "It stays the same", "It rises then falls"],
      expected: "It is rising, and rising faster over time",
      memo: "The numbers climb and the jumps get bigger and quicker — population is rising at a faster rate.", error_signals: ["ERR_SSSP_G7G3A3_DATA"], difficulty: 3,
    },
    TF("Improved health care was one reason world population grew quickly.", "True",
      "Better health care kept more people alive longer, boosting population growth.", "ERR_SSSP_G7G3A3_HEALTH", 1),
    MC("Refrigeration and canned food helped population growth by:",
      ["Keeping food safe for longer", "Causing earthquakes", "Cooling the planet", "Raising the death rate"], "Keeping food safe for longer",
      "Preserving food (canning, refrigeration) reduced spoilage and improved nutrition.", "ERR_SSSP_G7G3A3_FRIDGE", 2),
    MC("Reading a population line graph, a steep upward slope means population is:",
      ["Growing quickly", "Falling quickly", "Not changing", "Disappearing"], "Growing quickly",
      "A steep upward line on the graph shows rapid population growth.", "ERR_SSSP_G7G3A3_SLOPE", 2),
  ],

  // ─── G4 · Term 4 — Natural resources & conservation (SA) ───────────────────
  "SSSP.G7.G4.A1": [
    MC("Which of these is a natural resource?",
      ["Water", "A cellphone", "A factory", "A road"], "Water",
      "Natural resources come from nature — water, air, soil, forests, animals and marine life.", "ERR_SSSP_G7G4A1_DEF", 1),
    TF("Forests, soil and marine life are all natural resources.", "True",
      "Forests, soil, water, air, animals and marine life are all natural resources.", "ERR_SSSP_G7G4A1_LIST", 1),
    MC("'Abuse' of a natural resource means:",
      ["Using it in a harmful, wasteful way", "Protecting it carefully", "Counting it", "Mapping it"], "Using it in a harmful, wasteful way",
      "Abusing a resource means using it wastefully or in ways that damage it.", "ERR_SSSP_G7G4A1_ABUSE", 2),
    CLOZE("Air, water, soil and forests are examples of ____ resources.",
      ["natural", "man-made", "factory", "imported"], "natural",
      "These all come from nature, so they are natural resources.", "ERR_SSSP_G7G4A1_CLOZE", 1),
    MC("Why should natural resources be used carefully?",
      ["So they are not damaged or used up", "Because they are unlimited", "To make them disappear", "Because they cost nothing"], "So they are not damaged or used up",
      "Careful use protects resources so they last and stay healthy.", "ERR_SSSP_G7G4A1_CARE", 1),
    TF("Marine life is an example of a natural resource that can be over-used.", "True",
      "Fish and other marine life can be over-harvested, so they must be used responsibly.", "ERR_SSSP_G7G4A1_MARINE", 2),
    MC("Cutting down a whole forest without replanting is an example of:",
      ["Abusing a resource", "Conserving a resource", "Mapping a resource", "Counting a resource"], "Abusing a resource",
      "Destroying a forest without replacing it abuses the resource.", "ERR_SSSP_G7G4A1_FOREST", 2),
  ],
  "SSSP.G7.G4.A2": [
    MC("Conservation means:",
      ["Protecting and carefully managing the environment and resources", "Using everything up quickly", "Building more factories", "Ignoring nature"], "Protecting and carefully managing the environment and resources",
      "Conservation is the careful protection and management of nature and resources.", "ERR_SSSP_G7G4A2_DEF", 1),
    TF("A nature reserve or marine reserve is an example of a conservation area.", "True",
      "Conservation areas, including marine reserves, protect plants, animals and habitats.", "ERR_SSSP_G7G4A2_RESERVE", 1),
    MC("Eco-tourism is tourism that:",
      ["Respects nature and supports conservation", "Destroys habitats", "Mines for gold", "Builds factories in parks"], "Respects nature and supports conservation",
      "Eco-tourism lets people enjoy nature in ways that support conservation and communities.", "ERR_SSSP_G7G4A2_ECO", 2),
    CLOZE("Setting aside land to protect plants and animals creates a ____ area.",
      ["conservation", "mining", "industrial", "shopping"], "conservation",
      "Protected land for nature is a conservation area.", "ERR_SSSP_G7G4A2_CLOZE", 1),
    MC("A community conservation project usually aims to:",
      ["Protect nature while benefiting local people", "Remove all the wildlife", "Pollute the rivers", "Stop all tourism"], "Protect nature while benefiting local people",
      "Community projects protect nature while bringing benefits, such as jobs, to local people.", "ERR_SSSP_G7G4A2_COMMUNITY", 2),
    TF("One reason for conservation is to protect resources for future generations.", "True",
      "Conservation keeps resources healthy now and for people in the future.", "ERR_SSSP_G7G4A2_FUTURE", 1),
    MC("Why might a marine reserve ban fishing in certain areas?",
      ["To let fish populations recover and survive", "To raise sea levels", "To create earthquakes", "To increase pollution"], "To let fish populations recover and survive",
      "No-fishing zones let fish breed and recover, protecting the resource.", "ERR_SSSP_G7G4A2_MARINE", 2),
  ],
  "SSSP.G7.G4.A3": [
    MC("South Africa is generally a country with:",
      ["Limited water — it is fairly dry", "Far too much water", "No need to save water", "Oceans of fresh drinking water"], "Limited water — it is fairly dry",
      "South Africa is a dry country, so water is scarce and must be shared and saved.", "ERR_SSSP_G7G4A3_DRY", 1),
    TF("Looking after catchment areas helps keep rivers healthy.", "True",
      "Catchment areas collect water for rivers, so caring for them protects river health.", "ERR_SSSP_G7G4A3_CATCH", 2),
    MC("Which group is a major user of South Africa's water?",
      ["Agriculture (farming)", "Only schools", "Only tourists", "Nobody"], "Agriculture (farming)",
      "Farming is one of the biggest users of South Africa's water, along with industry and homes.", "ERR_SSSP_G7G4A3_AGRI", 2),
    CLOZE("Wetlands are disappearing, which is why their ____ is necessary.",
      ["conservation", "removal", "pollution", "draining"], "conservation",
      "Wetlands are valuable and shrinking, so conservation is needed to protect them.", "ERR_SSSP_G7G4A3_WETLAND", 2),
    {
      question: "Use the pie data. SA water use: agriculture 60%, domestic 25%, industry 15%. Who uses the MOST water?",
      input_type: "data-interpret",
      data: { table: [["User", "Share of water"], ["Agriculture", "60%"], ["Domestic (homes)", "25%"], ["Industry", "15%"]] },
      options: ["Agriculture", "Domestic", "Industry", "They are equal"],
      expected: "Agriculture",
      memo: "Agriculture's 60% is the largest share — farming uses the most water.", error_signals: ["ERR_SSSP_G7G4A3_DATA"], difficulty: 2,
    },
    TF("Using water responsibly at home is one way to help conserve South Africa's water.", "True",
      "Domestic users saving water helps conserve the country's scarce supply.", "ERR_SSSP_G7G4A3_HOME", 1),
    MC("Why is wetland conservation important?",
      ["Wetlands clean water and support wildlife", "Wetlands cause droughts", "Wetlands waste water", "Wetlands have no value"], "Wetlands clean water and support wildlife",
      "Wetlands filter and store water and support wildlife, so they are worth protecting.", "ERR_SSSP_G7G4A3_WHY", 2),
  ],
};

export default G7;
