// ─── Technology SP — Grade 7 authored pools (part 2: ES · PR) ────────────────
// Electrical Systems & Control (Term 3) · Processing, Society & Environment (T4).
// Refs auto-assigned by build-technology-sp.mjs. Tap-only; no free text.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7B = {
  // ════════════ ELECTRICAL SYSTEMS & CONTROL (Term 3) ═════════════════════════
  // ES.A1 · Magnetism & magnetic materials
  "TECH.G7.ES.A1": [
    MC("What is a magnet?",
      ["An object that can attract certain metals", "An object that gives off light", "A type of battery", "A liquid"], "An object that can attract certain metals",
      "A magnet attracts certain metals such as iron, steel and nickel.", "ERR_TECH_G7ESA1_DEF", 1),
    MC("Which metal is attracted by a magnet?",
      ["Iron", "Copper", "Aluminium", "Lead"], "Iron",
      "Iron (and steel and nickel) is magnetic; copper, aluminium, lead and brass are not.", "ERR_TECH_G7ESA1_IRON", 1),
    MC("Which material is NOT attracted by a magnet?",
      ["Plastic", "Iron", "Steel", "Nickel"], "Plastic",
      "Non-metals like plastic, wood and paper are not magnetic; iron, steel and nickel are.", "ERR_TECH_G7ESA1_PLASTIC", 1),
    TF("Steel is an iron alloy and is attracted by a magnet.", "True",
      "Steel is mostly iron, so it is magnetic.", "ERR_TECH_G7ESA1_STEEL", 1),
    TF("Copper and aluminium are strongly attracted by magnets.", "False",
      "Copper and aluminium are NOT attracted by magnets, even though they are metals.", "ERR_TECH_G7ESA1_COPPER", 2),
    MC("Two common shapes of permanent magnet are…",
      ["bar and horseshoe", "round and square only", "tall and short", "wet and dry"], "bar and horseshoe",
      "Bar magnets and horseshoe magnets are common permanent-magnet shapes.", "ERR_TECH_G7ESA1_SHAPES", 1),
    CLOZE("Metals like iron, steel and ____ are attracted by a magnet.",
      ["nickel", "copper", "plastic", "wood"], "nickel",
      "Iron, steel and nickel are magnetic; copper, aluminium, lead and brass are not.", "ERR_TECH_G7ESA1_NICKEL", 2),
    MC("Iron filings sprinkled near a magnet line up to show…",
      ["the magnetic field", "the temperature", "the colour", "the sound"], "the magnetic field",
      "Iron filings reveal the shape of the magnetic field around a magnet.", "ERR_TECH_G7ESA1_FIELD", 2),
    TF("A magnet can attract some metals but not non-metals.", "True",
      "Only certain metals (iron, steel, nickel) are magnetic; non-metals are never attracted.", "ERR_TECH_G7ESA1_NONMETAL", 1),
    MC("Why must you avoid a copper-coated steel paper clip when testing magnets?",
      ["The steel inside still sticks, giving a wrong result", "Copper is magnetic", "It is too heavy", "It is poisonous"], "The steel inside still sticks, giving a wrong result",
      "A copper-coated steel clip sticks because of the steel inside, which can confuse the test.", "ERR_TECH_G7ESA1_COATED", 3),
    CLOZE("The region around a magnet where it can attract metals is its magnetic ____.",
      ["field", "colour", "weight", "sound"], "field",
      "The magnetic field is the region where the magnet's force acts.", "ERR_TECH_G7ESA1_FIELDWORD", 2),
    MC("A scrap dealer can use a magnet to separate…",
      ["iron and steel from copper and aluminium", "water from oil", "red from blue", "hot from cold"], "iron and steel from copper and aluminium",
      "A magnet picks up magnetic metals (iron/steel), separating them from non-magnetic ones.", "ERR_TECH_G7ESA1_SCRAP", 2),
    TF("Wood and paper are attracted by a strong magnet.", "False",
      "Wood and paper are non-metals and are never attracted by a magnet.", "ERR_TECH_G7ESA1_WOOD", 1),
    MC("Which set lists ONLY magnetic materials?",
      ["Iron, steel, nickel", "Copper, plastic, wood", "Aluminium, lead, brass", "Paper, glass, water"], "Iron, steel, nickel",
      "Iron, steel and nickel are magnetic; the other lists are non-magnetic.", "ERR_TECH_G7ESA1_SET", 2),
    {
      question: "Sort each material into 'Attracted by a magnet' or 'Not attracted'.",
      input_type: "sort-buckets",
      buckets: [{ id: "yes", label: "Attracted" }, { id: "no", label: "Not attracted" }],
      items: [
        { id: "i1", text: "Iron nail", correct_bucket: "yes" },
        { id: "i2", text: "Copper wire", correct_bucket: "no" },
        { id: "i3", text: "Steel paper clip", correct_bucket: "yes" },
        { id: "i4", text: "Aluminium can", correct_bucket: "no" },
        { id: "i5", text: "Plastic ruler", correct_bucket: "no" },
      ],
      expected: "Iron and steel are attracted; copper, aluminium and plastic are not.",
      pass_threshold: 0.7,
      memo: "Magnetic: iron, steel, nickel. Not magnetic: copper, aluminium, lead, brass, and all non-metals.", error_signals: ["ERR_TECH_G7ESA1_SORT"], difficulty: 2,
    },
    MC("A horseshoe magnet is shaped like a U mainly to…",
      ["bring both poles close together for a stronger pull", "look interesting", "be heavier", "store water"], "bring both poles close together for a stronger pull",
      "The U-shape brings both poles near the object, giving a stronger pull.", "ERR_TECH_G7ESA1_HORSESHOE", 3),
    TF("Some metals stick to magnets and some do not.", "True",
      "Only certain metals (iron, steel, nickel) are magnetic; many metals are not.", "ERR_TECH_G7ESA1_SOME", 1),
    MC("To test which metals are magnetic, you would…",
      ["hold a magnet near each sample and see which stick", "weigh each sample", "paint each sample", "heat each sample"], "hold a magnet near each sample and see which stick",
      "A simple fair test: bring a magnet near each metal and record which are attracted.", "ERR_TECH_G7ESA1_TEST", 2),
    CLOZE("Bar and ____ are two common shapes of permanent magnet.",
      ["horseshoe", "circle", "triangle", "square"], "horseshoe",
      "Bar and horseshoe magnets are the common permanent-magnet shapes.", "ERR_TECH_G7ESA1_BAR", 1),
    MC("Recycling scrap metal is valuable to society, but is harmed by…",
      ["thieves who steal copper wire and manhole covers", "honest gleaners", "magnets", "schools"], "thieves who steal copper wire and manhole covers",
      "Honest scrap collecting helps society; metal theft (copper wire, manhole covers) is the criminal downside.", "ERR_TECH_G7ESA1_THEFT", 2),
  ],

  // ES.A2 · Simple electric circuits & symbols
  "TECH.G7.ES.A2": [
    MC("What must a simple electric circuit have to work?",
      ["A complete loop with a power source", "A broken wire", "Only a switch", "Only a bulb"], "A complete loop with a power source",
      "A circuit needs an unbroken loop from a power source through conductors to an output.", "ERR_TECH_G7ESA2_LOOP", 1),
    MC("Which part is the energy SOURCE in a simple circuit?",
      ["The cell (battery)", "The bulb", "The wire", "The switch"], "The cell (battery)",
      "The cell (battery) supplies the electrical energy.", "ERR_TECH_G7ESA2_SOURCE", 1),
    MC("What does a switch do in a circuit?",
      ["Opens or closes the circuit to control it", "Stores light", "Makes heat only", "Holds the wires"], "Opens or closes the circuit to control it",
      "A switch opens (off) or closes (on) the circuit to control the flow of current.", "ERR_TECH_G7ESA2_SWITCH", 1),
    MC("Which is an OUTPUT device in a simple circuit?",
      ["A light bulb or buzzer", "The cell", "The switch", "The wire"], "A light bulb or buzzer",
      "Output devices (bulb, buzzer, motor) turn electrical energy into light, sound or movement.", "ERR_TECH_G7ESA2_OUTPUT", 1),
    MC("What is a conductor?",
      ["A material that lets electricity flow through it", "A material that blocks electricity", "A type of magnet", "A kind of plastic"], "A material that lets electricity flow through it",
      "A conductor (like copper wire) lets electric current flow; an insulator blocks it.", "ERR_TECH_G7ESA2_CONDUCTOR", 1),
    TF("If there is a break in the loop, the current cannot flow.", "True",
      "A break in the circuit stops the current — the loop must be complete.", "ERR_TECH_G7ESA2_BREAK", 1),
    CLOZE("A device drawn as a circle with a cross is the symbol for a ____.",
      ["lamp", "cell", "switch", "wire"], "lamp",
      "The lamp/bulb symbol is a circle with a cross inside.", "ERR_TECH_G7ESA2_LAMPSYM", 2),
    MC("Why do we use symbols when drawing a circuit?",
      ["So everyone can read the circuit the same simple way", "To make it longer", "To hide the design", "To waste ink"], "So everyone can read the circuit the same simple way",
      "Standard symbols let anyone read a circuit diagram quickly and clearly.", "ERR_TECH_G7ESA2_WHYSYM", 2),
    MC("Copper wire is used in circuits because it is a good…",
      ["conductor", "insulator", "magnet", "battery"], "conductor",
      "Copper conducts electricity well, so it is used for wires.", "ERR_TECH_G7ESA2_COPPER", 1),
    TF("Plastic around a wire is an insulator that keeps the current inside.", "True",
      "The plastic coating is an insulator; it stops the current escaping and protects the user.", "ERR_TECH_G7ESA2_INSULATOR", 1),
    MC("In the GET band, circuits must be battery powered with a maximum of…",
      ["9 volts DC", "240 volts AC", "1000 volts", "no limit"], "9 volts DC",
      "Safety rule: GET circuits use batteries up to 9V DC only.", "ERR_TECH_G7ESA2_9V", 2),
    CLOZE("A material that does NOT let electricity flow is an ____.",
      ["insulator", "conductor", "output", "input"], "insulator",
      "Insulators (plastic, rubber) block current; conductors (metals) allow it.", "ERR_TECH_G7ESA2_INSWORD", 1),
    MC("Which is the correct order of parts in a simple lighting circuit?",
      ["Cell → switch → bulb → back to cell", "Bulb only", "Switch with no power", "Two bulbs and no wire"], "Cell → switch → bulb → back to cell",
      "Current flows from the cell, through the switch and bulb, and back to the cell — a complete loop.", "ERR_TECH_G7ESA2_ORDER", 2),
    TF("A buzzer is an output device that turns electricity into sound.", "True",
      "A buzzer is an output that converts electrical energy into sound.", "ERR_TECH_G7ESA2_BUZZER", 1),
    {
      question: "Sort each component by its job in a circuit.",
      input_type: "sort-buckets",
      buckets: [{ id: "src", label: "Power source" }, { id: "ctrl", label: "Control" }, { id: "out", label: "Output" }],
      items: [
        { id: "i1", text: "Cell / battery", correct_bucket: "src" },
        { id: "i2", text: "Switch", correct_bucket: "ctrl" },
        { id: "i3", text: "Light bulb", correct_bucket: "out" },
        { id: "i4", text: "Buzzer", correct_bucket: "out" },
      ],
      expected: "The cell is the source; the switch is the control; the bulb and buzzer are outputs.",
      pass_threshold: 0.75,
      memo: "Source = cell; control = switch; output = bulb, buzzer or motor.", error_signals: ["ERR_TECH_G7ESA2_SORT"], difficulty: 2,
    },
    {
      question: "Put the steps to make a bulb light up in order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Connect a wire from the cell to the switch" },
        { id: "b", text: "Connect the switch to the bulb" },
        { id: "c", text: "Connect the bulb back to the cell" },
        { id: "d", text: "Close the switch so current flows" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Build a complete loop (cell → switch → bulb → cell), then close the switch to let current flow.",
      error_signals: ["ERR_TECH_G7ESA2_SEQUENCE"], difficulty: 2,
    },
    MC("Which would NOT conduct electricity?",
      ["A rubber band", "A copper wire", "A steel nail", "An aluminium strip"], "A rubber band",
      "Rubber is an insulator; copper, steel and aluminium are conductors.", "ERR_TECH_G7ESA2_NONCOND", 2),
    TF("A circuit diagram uses agreed symbols instead of pictures of the real parts.", "True",
      "Circuit diagrams use standard symbols, which are quicker and clearer than drawings of the parts.", "ERR_TECH_G7ESA2_DIAGRAM", 1),
    MC("If a bulb does not light, a likely cause is…",
      ["a break in the circuit or the switch is off", "the wire is too short by 1mm", "the room is too bright", "the cell is the wrong colour"], "a break in the circuit or the switch is off",
      "A bulb won't light if the loop is broken or the switch is open (off).", "ERR_TECH_G7ESA2_FAULT", 2),
    CLOZE("A complete, unbroken path for current is called a ____.",
      ["circuit", "magnet", "lever", "shell"], "circuit",
      "A circuit is the complete loop the current flows around.", "ERR_TECH_G7ESA2_CIRCUITWORD", 1),
  ],

  // ES.A3 · Electromagnets
  "TECH.G7.ES.A3": [
    MC("How do you make a simple electromagnet?",
      ["Coil insulated wire around an iron core and pass current through it", "Rub two magnets together", "Heat a copper coin", "Shine a light on iron"], "Coil insulated wire around an iron core and pass current through it",
      "An electromagnet is made by coiling insulated wire (a solenoid) around an iron core and switching on current.", "ERR_TECH_G7ESA3_MAKE", 1),
    TF("An electromagnet is magnetic only while current flows through the coil.", "True",
      "Switch the current off and the magnetism fades — that is the key feature of an electromagnet.", "ERR_TECH_G7ESA3_ONLYWHEN", 1),
    MC("What is a big ADVANTAGE of an electromagnet over a permanent magnet?",
      ["You can switch it on and off", "It is always magnetic", "It never needs power", "It is invisible"], "You can switch it on and off",
      "An electromagnet can be turned on and off, unlike a permanent magnet.", "ERR_TECH_G7ESA3_ADV", 2),
    MC("A coil of wire used to make an electromagnet is called a…",
      ["solenoid", "resistor", "battery", "lever"], "solenoid",
      "A solenoid is a coil of wire; current through it creates a magnetic field.", "ERR_TECH_G7ESA3_SOLENOID", 2),
    MC("Why is a 'soft' iron core used instead of a hard steel bolt?",
      ["Soft iron magnetises and demagnetises easily", "Steel is cheaper", "Iron is lighter", "Steel cannot conduct"], "Soft iron magnetises and demagnetises easily",
      "Soft iron loses its magnetism quickly when the current stops, which is what you want.", "ERR_TECH_G7ESA3_SOFTIRON", 3),
    TF("Using a longer coil of wire makes an electromagnet stronger.", "True",
      "More turns of wire (a longer coil) make the electromagnet stronger.", "ERR_TECH_G7ESA3_LONGER", 2),
    CLOZE("An electromagnet's magnetism disappears when you switch the current ____.",
      ["off", "on", "up", "blue"], "off",
      "Switch off the current and the magnetic field fades away.", "ERR_TECH_G7ESA3_OFF", 1),
    MC("Adding more cells (more voltage) to an electromagnet usually…",
      ["increases its strength a little", "switches off the magnetism", "changes its colour", "cools it down"], "increases its strength a little",
      "More current (from more cells) increases the electromagnet's strength somewhat.", "ERR_TECH_G7ESA3_MORECELLS", 2),
    MC("A scrap-yard crane uses an electromagnet to…",
      ["pick up and then drop steel by switching it on and off", "make light", "play music", "cool the metal"], "pick up and then drop steel by switching it on and off",
      "An electromagnet lets the crane grab steel and release it by switching the current off.", "ERR_TECH_G7ESA3_CRANE", 2),
    TF("Electromagnets are used in many modern technologies like motors and bells.", "True",
      "Electromagnetism is behind motors, bells, speakers and many devices.", "ERR_TECH_G7ESA3_USES", 1),
    CLOZE("Wire is coiled around an iron ____ to make an electromagnet.",
      ["core", "battery", "switch", "shell"], "core",
      "The iron core, wrapped in a coil, concentrates the magnetic field.", "ERR_TECH_G7ESA3_CORE", 1),
    MC("Which change would NOT make an electromagnet stronger?",
      ["Switching the current off", "Adding more turns of wire", "Using more cells", "Using a soft iron core"], "Switching the current off",
      "Switching off the current removes the magnetism entirely — it cannot make it stronger.", "ERR_TECH_G7ESA3_NOTSTRONGER", 2),
    TF("The insulation (plastic) on the coil wire stops the coils short-circuiting each other.", "True",
      "Insulated wire keeps the current flowing around the coil instead of jumping between turns.", "ERR_TECH_G7ESA3_INSULATION", 2),
    {
      question: "Order the steps to build and use a simple electromagnet.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Wind insulated copper wire around an iron core" },
        { id: "b", text: "Connect the wire ends to a cell and a switch" },
        { id: "c", text: "Close the switch so current flows and it becomes magnetic" },
        { id: "d", text: "Open the switch to release the load" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Coil the wire on the core, connect to a cell and switch, close to magnetise, open to release.",
      error_signals: ["ERR_TECH_G7ESA3_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each statement: does it describe an electromagnet or a permanent magnet?",
      input_type: "sort-buckets",
      buckets: [{ id: "em", label: "Electromagnet" }, { id: "pm", label: "Permanent magnet" }],
      items: [
        { id: "i1", text: "Can be switched on and off", correct_bucket: "em" },
        { id: "i2", text: "Is always magnetic", correct_bucket: "pm" },
        { id: "i3", text: "Needs an electric current to work", correct_bucket: "em" },
        { id: "i4", text: "A bar or horseshoe magnet", correct_bucket: "pm" },
      ],
      expected: "Electromagnets switch on/off and need current; permanent magnets are always magnetic.",
      pass_threshold: 0.75,
      memo: "Electromagnet = magnetic only with current, switchable. Permanent magnet = always magnetic.", error_signals: ["ERR_TECH_G7ESA3_SORT"], difficulty: 2,
    },
    MC("Adding a light bulb to the electromagnet circuit can…",
      ["show when the magnet is switched on", "make it permanent", "cool the core", "remove the coil"], "show when the magnet is switched on",
      "A bulb in the circuit acts as an indicator that the electromagnet is on.", "ERR_TECH_G7ESA3_INDICATOR", 2),
    TF("A nail can be used as the iron core of a simple electromagnet.", "True",
      "A 'relatively soft' iron nail works as a simple core (softer than a hard steel bolt).", "ERR_TECH_G7ESA3_NAIL", 1),
    MC("The main parts of an electromagnet are…",
      ["a coil of wire, an iron core and a power source", "a lens and a mirror", "a magnet and a spring", "a gear and a belt"], "a coil of wire, an iron core and a power source",
      "An electromagnet needs a coil (solenoid), an iron core, and a current source.", "ERR_TECH_G7ESA3_PARTS", 1),
    CLOZE("More turns of wire and more cells make an electromagnet ____.",
      ["stronger", "weaker", "colder", "quieter"], "stronger",
      "Both more coils and more current strengthen an electromagnet.", "ERR_TECH_G7ESA3_STRONGER", 2),
    MC("Why is the ability to switch off useful for a scrap-sorting magnet?",
      ["It can release the metals it has picked up", "It uses no electricity", "It looks better", "It is permanent"], "It can release the metals it has picked up",
      "Switching off lets the electromagnet drop the sorted metal — a permanent magnet could not.", "ERR_TECH_G7ESA3_RELEASE", 2),
  ],

  // ════════════ PROCESSING, SOCIETY & ENVIRONMENT (Term 4) ════════════════════
  // PR.A1 · Processing food
  "TECH.G7.PR.A1": [
    MC("What does 'processing' mean in Technology?",
      ["Changing raw materials into a more useful product", "Throwing materials away", "Looking at materials only", "Painting materials"], "Changing raw materials into a more useful product",
      "Processing changes raw materials into a more useful form — like turning flour into bread.", "ERR_TECH_G7PRA1_DEF", 1),
    MC("Processing food means…",
      ["preparing or changing food so it is useful to eat", "growing the food only", "selling the food only", "drawing the food"], "preparing or changing food so it is useful to eat",
      "Food processing prepares or changes ingredients into edible, useful products.", "ERR_TECH_G7PRA1_FOOD", 1),
    TF("A nutritious meal gives the body the food it needs to stay healthy.", "True",
      "Nutritious food supplies the nutrients the body needs for health.", "ERR_TECH_G7PRA1_NUTRITIOUS", 1),
    MC("When designing emergency food for a refugee camp, an important factor is that the food is…",
      ["nutritious and easy to prepare in basic conditions", "very fancy", "hard to cook", "only for decoration"], "nutritious and easy to prepare in basic conditions",
      "Emergency food must be nutritious and preparable under the basic conditions of a camp.", "ERR_TECH_G7PRA1_EMERGENCY", 2),
    CLOZE("Changing raw ingredients into a meal is an example of food ____.",
      ["processing", "drawing", "selling", "weighing"], "processing",
      "Turning ingredients into a meal is processing.", "ERR_TECH_G7PRA1_PROCESSWORD", 1),
    MC("Why write down the 'sequence of manufacture' for preparing food?",
      ["So the steps are done in the right order", "To use more paper", "To hide the recipe", "To waste time"], "So the steps are done in the right order",
      "A sequence of manufacture lists the steps in the correct order so the product is made properly.", "ERR_TECH_G7PRA1_SEQUENCE_WHY", 2),
    MC("When evaluating a prepared food item, you might judge its…",
      ["flavour, texture and nutritional value", "weight in kilometres", "colour of the plate only", "price of the table"], "flavour, texture and nutritional value",
      "Food is evaluated on flavour, texture and nutritional value.", "ERR_TECH_G7PRA1_EVALUATE", 2),
    TF("A design brief for emergency food should state the types and quantities of food needed.", "True",
      "The brief sets out what food is needed and how much, for the number of people.", "ERR_TECH_G7PRA1_BRIEF", 2),
    MC("Feeding 100 refugees needs you to think about…",
      ["the quantity of ingredients needed", "the colour of the tent", "the time of sunset", "the brand of pencil"], "the quantity of ingredients needed",
      "Designing food for 100 people means working out the quantities of ingredients.", "ERR_TECH_G7PRA1_QUANTITY", 2),
    CLOZE("The order in which steps are done to make a product is the sequence of ____.",
      ["manufacture", "colours", "names", "weather"], "manufacture",
      "The sequence of manufacture is the ordered list of making steps.", "ERR_TECH_G7PRA1_MANUFACTURE", 2),
    {
      question: "Put the steps of preparing a simple food item in a sensible order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "List and gather the ingredients" },
        { id: "b", text: "Measure out the quantities needed" },
        { id: "c", text: "Combine and prepare the item" },
        { id: "d", text: "Taste and evaluate the result" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Gather ingredients, measure them, prepare the item, then evaluate it — a sensible sequence of manufacture.",
      error_signals: ["ERR_TECH_G7PRA1_SEQUENCE"], difficulty: 2,
    },
    TF("Processing can make raw materials safer, tastier or last longer.", "True",
      "Processing often improves safety, taste or shelf life of raw materials.", "ERR_TECH_G7PRA1_BENEFIT", 1),
    MC("Which is an example of processing a raw material into food?",
      ["Grinding wheat into flour and baking bread", "Looking at a field of wheat", "Photographing wheat", "Selling raw wheat unchanged"], "Grinding wheat into flour and baking bread",
      "Grinding and baking change the raw wheat into a useful product — processing.", "ERR_TECH_G7PRA1_WHEAT", 2),
    MC("A balanced emergency meal should mainly provide…",
      ["energy and nutrients to keep people healthy", "sweets only", "decoration", "entertainment"], "energy and nutrients to keep people healthy",
      "Emergency meals must supply energy and nutrients for health.", "ERR_TECH_G7PRA1_BALANCED", 2),
    {
      question: "Sort each activity: is it 'Processing food' or not?",
      input_type: "sort-buckets",
      buckets: [{ id: "yes", label: "Processing food" }, { id: "no", label: "Not processing food" }],
      items: [
        { id: "i1", text: "Cooking maize into porridge", correct_bucket: "yes" },
        { id: "i2", text: "Drying fruit to make it last", correct_bucket: "yes" },
        { id: "i3", text: "Looking at a tomato", correct_bucket: "no" },
        { id: "i4", text: "Drawing a picture of a loaf", correct_bucket: "no" },
      ],
      expected: "Cooking maize and drying fruit change the food (processing); looking and drawing do not.",
      pass_threshold: 0.75,
      memo: "Processing changes the raw material; simply observing or drawing it does not.", error_signals: ["ERR_TECH_G7PRA1_SORT"], difficulty: 2,
    },
    TF("Refugees in an emergency mainly need shelter, food and clean water.", "True",
      "Basic emergency needs are shelter, food and water.", "ERR_TECH_G7PRA1_NEEDS", 1),
    MC("Why must emergency food be easy to prepare?",
      ["Camp conditions are basic, with limited equipment", "To make it cost more", "To slow people down", "There is no reason"], "Camp conditions are basic, with limited equipment",
      "In a camp, cooking facilities are basic, so the food must be simple to prepare.", "ERR_TECH_G7PRA1_EASY", 2),
    CLOZE("Food is evaluated on flavour, texture and ____ value.",
      ["nutritional", "musical", "magnetic", "electrical"], "nutritional",
      "Nutritional value is a key way to evaluate food.", "ERR_TECH_G7PRA1_NUTVALUE", 2),
    MC("Designing food for many people is part of the design process because you must…",
      ["investigate needs, write a brief, make and evaluate", "skip straight to eating", "only draw it", "ignore the people"], "investigate needs, write a brief, make and evaluate",
      "Even food design follows the design process: investigate, brief, make, evaluate.", "ERR_TECH_G7PRA1_DESIGNPROCESS", 2),
    TF("A 'design brief' for food sets out what is needed before you start cooking.", "True",
      "The design brief states the requirements (types and quantities of food) before making begins.", "ERR_TECH_G7PRA1_BRIEFFIRST", 1),
  ],

  // PR.A2 · Materials & textiles
  "TECH.G7.PR.A2": [
    MC("A textile is best described as…",
      ["a cloth or fabric material", "a type of metal", "a kind of battery", "a magnet"], "a cloth or fabric material",
      "A textile is a cloth or fabric, like canvas, cotton or wool.", "ERR_TECH_G7PRA2_DEF", 1),
    MC("Which property would matter most for a tent fabric in the rain?",
      ["Waterproofing", "Bright colour", "Sweet smell", "Loud sound"], "Waterproofing",
      "A tent fabric must be waterproof to keep the rain out.", "ERR_TECH_G7PRA2_WATERPROOF", 1),
    TF("Different materials are chosen for different jobs based on their properties.", "True",
      "We pick materials by their properties (strength, waterproofing, flexibility) to suit the job.", "ERR_TECH_G7PRA2_PROPERTIES", 1),
    MC("Why investigate the 'burning characteristics' of a textile for firefighters?",
      ["So the clothing resists catching fire", "To make it colourful", "To make it cheaper", "To make it heavier"], "So the clothing resists catching fire",
      "Firefighters need fabrics that resist burning, so burning behaviour is investigated.", "ERR_TECH_G7PRA2_BURNING", 2),
    MC("Canvas can be made waterproof by…",
      ["treating it with a waterproofing chemical", "leaving it in the sun", "cutting holes in it", "freezing it"], "treating it with a waterproofing chemical",
      "Applying a waterproofing chemical stops water passing through canvas.", "ERR_TECH_G7PRA2_CHEMICAL", 2),
    CLOZE("Cloth or fabric used to make clothing and shelters is called a ____.",
      ["textile", "metal", "magnet", "gear"], "textile",
      "Textiles are fabrics used for clothing, tents and more.", "ERR_TECH_G7PRA2_TEXTILEWORD", 1),
    MC("Specialised workers like firefighters wear clothing made of textiles that are…",
      ["heat- and flame-resistant", "easy to burn", "see-through", "made of paper"], "heat- and flame-resistant",
      "Firefighters' clothing must resist heat and flames.", "ERR_TECH_G7PRA2_FIREFIGHTER", 2),
    TF("A material's properties decide whether it is suitable for a particular use.", "True",
      "Suitability for a use depends on the material's properties.", "ERR_TECH_G7PRA2_SUITABLE", 1),
    MC("Which property helps a raincoat keep you dry?",
      ["It is waterproof", "It is magnetic", "It conducts electricity", "It glows"], "It is waterproof",
      "A waterproof material keeps water out — essential for a raincoat.", "ERR_TECH_G7PRA2_RAINCOAT", 1),
    MC("For NSRI sea-rescue clothing, an important property is that it is…",
      ["water-resistant and keeps the wearer warm", "very heavy", "bright pink only", "made of glass"], "water-resistant and keeps the wearer warm",
      "Sea-rescue clothing must resist water and keep the wearer warm.", "ERR_TECH_G7PRA2_NSRI", 2),
    CLOZE("A material that does not let water through is ____.",
      ["waterproof", "magnetic", "electric", "musical"], "waterproof",
      "Waterproof = water cannot pass through.", "ERR_TECH_G7PRA2_WPWORD", 1),
    TF("All textiles burn at the same speed.", "False",
      "Different textiles have different burning characteristics — some resist fire far better.", "ERR_TECH_G7PRA2_BURNSAME", 2),
    MC("To choose a fabric for an emergency shelter, you would test it for…",
      ["strength and waterproofing", "taste", "musical sound", "magnetism"], "strength and waterproofing",
      "Shelter fabric must be strong and waterproof to protect people.", "ERR_TECH_G7PRA2_SHELTER", 2),
    {
      question: "Sort each property by whether it suits a rain shelter fabric.",
      input_type: "sort-buckets",
      buckets: [{ id: "good", label: "Good for a rain shelter" }, { id: "bad", label: "Not helpful" }],
      items: [
        { id: "i1", text: "Waterproof", correct_bucket: "good" },
        { id: "i2", text: "Strong and tear-resistant", correct_bucket: "good" },
        { id: "i3", text: "Full of holes", correct_bucket: "bad" },
        { id: "i4", text: "Dissolves in water", correct_bucket: "bad" },
      ],
      expected: "Waterproof and strong are good; full of holes or dissolving in water are not.",
      pass_threshold: 0.75,
      memo: "Match the material's properties to the job: a shelter fabric must be waterproof and strong.", error_signals: ["ERR_TECH_G7PRA2_SORT"], difficulty: 2,
    },
    MC("Which material property means it can bend without breaking?",
      ["Flexibility", "Hardness", "Brittleness", "Magnetism"], "Flexibility",
      "Flexibility is the ability to bend without breaking.", "ERR_TECH_G7PRA2_FLEX", 2),
    TF("Choosing the wrong material can make a product fail at its job.", "True",
      "A material whose properties don't suit the job can cause the product to fail.", "ERR_TECH_G7PRA2_FAIL", 1),
    MC("A good shelter material should be…",
      ["sturdy, waterproof and easy to transport", "heavy and fragile", "see-through and weak", "made only of paper"], "sturdy, waterproof and easy to transport",
      "Shelter material should be sturdy, waterproof and easy to move and erect.", "ERR_TECH_G7PRA2_GOODSHELTER", 2),
    CLOZE("Firefighters need clothing made from ____-resistant textiles.",
      ["flame", "water", "magnet", "sound"], "flame",
      "Flame-resistant textiles protect firefighters from burning.", "ERR_TECH_G7PRA2_FLAME", 2),
    MC("Why test materials before using them in a design?",
      ["To check they have the right properties for the job", "To waste them", "To colour them", "There is no reason"], "To check they have the right properties for the job",
      "Testing confirms a material's properties suit the design before you commit to it.", "ERR_TECH_G7PRA2_TEST", 1),
    TF("Canvas is a textile that can be treated to become waterproof.", "True",
      "Canvas can be chemically treated to make it waterproof for tents and covers.", "ERR_TECH_G7PRA2_CANVAS", 1),
  ],

  // PR.A3 · Indigenous technology
  "TECH.G7.PR.A3": [
    MC("What is 'indigenous technology'?",
      ["Knowledge and methods developed by local people over time", "Brand-new computers", "Imported machines", "Space rockets"], "Knowledge and methods developed by local people over time",
      "Indigenous technology is the knowledge and methods local/traditional communities developed over generations.", "ERR_TECH_G7PRA3_DEF", 1),
    TF("Indigenous builders often use local materials that are readily available.", "True",
      "Indigenous building uses materials that are local, available and appropriate.", "ERR_TECH_G7PRA3_LOCAL", 1),
    MC("A common feature of indigenous building materials is that they are…",
      ["environmentally friendly and appropriate to the area", "always imported", "always made of plastic", "very expensive"], "environmentally friendly and appropriate to the area",
      "Indigenous materials tend to be environmentally friendly and suited to the local climate.", "ERR_TECH_G7PRA3_ENVFRIENDLY", 2),
    MC("Why is indigenous knowledge valuable to study?",
      ["It shows clever, sustainable ways to meet needs", "It is always wrong", "It uses the most energy", "It harms the planet"], "It shows clever, sustainable ways to meet needs",
      "Indigenous knowledge offers clever, sustainable, low-impact ways to meet needs.", "ERR_TECH_G7PRA3_VALUE", 2),
    CLOZE("Indigenous building often uses ____ materials found nearby.",
      ["local", "imported", "plastic", "metal"], "local",
      "Indigenous builders use locally available materials.", "ERR_TECH_G7PRA3_LOCALWORD", 1),
    MC("An example of an indigenous building material is…",
      ["mud, grass or reeds", "steel girders", "concrete blocks", "glass panels"], "mud, grass or reeds",
      "Traditional houses often use mud, grass, thatch and reeds — local natural materials.", "ERR_TECH_G7PRA3_EXAMPLE", 2),
    TF("Indigenous people have the right to protection of their traditional knowledge (intellectual property).", "True",
      "Indigenous intellectual property rights protect traditional knowledge and methods.", "ERR_TECH_G7PRA3_IP", 2),
    MC("Compared with informal-settlement shacks, indigenous houses are often…",
      ["better suited to the climate and environment", "always weaker", "made of imported steel", "less suitable"], "better suited to the climate and environment",
      "Indigenous designs are often well suited to local climate using appropriate materials.", "ERR_TECH_G7PRA3_COMPARE", 3),
    CLOZE("Using materials that do not harm nature makes a design environmentally ____.",
      ["friendly", "harmful", "expensive", "heavy"], "friendly",
      "Environmentally friendly designs avoid harming nature.", "ERR_TECH_G7PRA3_FRIENDLYWORD", 1),
    MC("Why do indigenous designs often suit the local climate well?",
      ["They were developed over time to fit local conditions", "They were copied from cities", "They ignore the weather", "They use only glass"], "They were developed over time to fit local conditions",
      "Generations of refining mean indigenous designs fit local conditions and climate.", "ERR_TECH_G7PRA3_CLIMATE", 2),
    TF("Thatch (dried grass) roofing is an example of indigenous building technology.", "True",
      "Thatch roofing is a traditional, indigenous building method using local grass.", "ERR_TECH_G7PRA3_THATCH", 1),
    MC("Sustainable use of materials means…",
      ["using resources so they last for the future", "using them all up at once", "wasting them", "burning them"], "using resources so they last for the future",
      "Sustainability means using resources carefully so they remain for the future.", "ERR_TECH_G7PRA3_SUSTAIN", 2),
    {
      question: "Sort each material into 'Indigenous/local' or 'Modern/manufactured'.",
      input_type: "sort-buckets",
      buckets: [{ id: "indig", label: "Indigenous/local" }, { id: "modern", label: "Modern/manufactured" }],
      items: [
        { id: "i1", text: "Thatch grass", correct_bucket: "indig" },
        { id: "i2", text: "Mud bricks", correct_bucket: "indig" },
        { id: "i3", text: "Steel sheeting", correct_bucket: "modern" },
        { id: "i4", text: "Factory-made glass", correct_bucket: "modern" },
      ],
      expected: "Thatch and mud bricks are indigenous/local; steel and factory glass are modern/manufactured.",
      pass_threshold: 0.75,
      memo: "Indigenous materials are local and natural (thatch, mud); modern materials are manufactured (steel, glass).", error_signals: ["ERR_TECH_G7PRA3_SORT"], difficulty: 2,
    },
    MC("Learning from indigenous technology can help modern designers to…",
      ["build in more sustainable, low-cost ways", "waste more materials", "ignore the environment", "make things harder"], "build in more sustainable, low-cost ways",
      "Indigenous methods inspire sustainable, affordable, low-impact modern design.", "ERR_TECH_G7PRA3_LEARN", 2),
    TF("Indigenous technology never has anything useful to teach modern engineers.", "False",
      "Indigenous technology offers valuable, sustainable lessons for modern design.", "ERR_TECH_G7PRA3_USEFUL", 2),
    MC("Different coexisting 'knowledge systems' means…",
      ["both modern and traditional knowledge can be valued together", "only one can be right", "knowledge is useless", "ignoring the past"], "both modern and traditional knowledge can be valued together",
      "We can value modern science and indigenous knowledge side by side.", "ERR_TECH_G7PRA3_COEXIST", 3),
    CLOZE("Traditional knowledge passed down by local people is ____ knowledge.",
      ["indigenous", "imported", "digital", "foreign"], "indigenous",
      "Indigenous knowledge is the traditional knowledge of local communities.", "ERR_TECH_G7PRA3_INDIGWORD", 1),
    MC("Why are indigenous materials often a good environmental choice?",
      ["They are local, natural and biodegradable", "They travel far to arrive", "They never break down", "They pollute heavily"], "They are local, natural and biodegradable",
      "Local, natural materials use little transport and break down naturally.", "ERR_TECH_G7PRA3_GOODENV", 2),
    TF("Indigenous houses are usually built from materials found close by.", "True",
      "Indigenous building relies on nearby, readily available materials.", "ERR_TECH_G7PRA3_NEARBY", 1),
    MC("Respecting indigenous intellectual property means…",
      ["giving credit and rights for traditional knowledge", "copying it freely without thanks", "destroying it", "ignoring it"], "giving credit and rights for traditional knowledge",
      "Indigenous IP rights mean traditional knowledge is credited and protected.", "ERR_TECH_G7PRA3_RESPECT", 2),
  ],

  // PR.A4 · Impact & bias in technology
  "TECH.G7.PR.A4": [
    MC("Technology can have which kinds of impact on society?",
      ["Both positive and negative", "Only positive", "Only negative", "None at all"], "Both positive and negative",
      "Technology has both positive and negative impacts on people and the environment.", "ERR_TECH_G7PRA4_BOTH", 1),
    MC("What is 'bias' in technology?",
      ["When a product favours or disadvantages a group of people", "When a product is colourful", "When a product is cheap", "When a product is heavy"], "When a product favours or disadvantages a group of people",
      "Bias means a technology unfairly favours some groups or disadvantages others.", "ERR_TECH_G7PRA4_BIAS", 1),
    TF("Recycling scrap metal can be valuable to society.", "True",
      "Recycling metal saves resources and creates value — a positive impact.", "ERR_TECH_G7PRA4_RECYCLE", 1),
    MC("A negative impact of technology could be…",
      ["pollution of the environment", "cleaner water", "more jobs", "better health"], "pollution of the environment",
      "Pollution is a negative impact technology can have on the environment.", "ERR_TECH_G7PRA4_NEGATIVE", 1),
    MC("A positive impact of technology could be…",
      ["faster communication and better medicine", "more pollution", "more waste", "more theft"], "faster communication and better medicine",
      "Better communication and medicine are positive impacts of technology.", "ERR_TECH_G7PRA4_POSITIVE", 1),
    CLOZE("When a design unfairly favours one group over another, it shows ____.",
      ["bias", "colour", "weight", "sound"], "bias",
      "Bias is unfair favouring or disadvantaging of groups by a technology.", "ERR_TECH_G7PRA4_BIASWORD", 1),
    TF("Stealing copper cables is a negative, criminal impact linked to scrap metal.", "True",
      "Cable theft is a criminal, negative impact tied to the scrap-metal trade.", "ERR_TECH_G7PRA4_THEFT", 2),
    MC("A school recycling scheme can raise funds by…",
      ["collecting and selling recyclable waste", "burning all the rubbish", "ignoring waste", "burying waste in class"], "collecting and selling recyclable waste",
      "Collecting cans, paper and plastic for recycling can raise funds and reduce waste.", "ERR_TECH_G7PRA4_SCHEME", 2),
    MC("A product that only works for right-handed people shows…",
      ["bias against left-handed people", "good design for all", "no impact", "low cost"], "bias against left-handed people",
      "A right-handed-only product disadvantages left-handed users — that is bias.", "ERR_TECH_G7PRA4_LEFTHAND", 3),
    CLOZE("Reusing and recycling materials helps the ____.",
      ["environment", "noise", "colour", "weight"], "environment",
      "Recycling and reusing reduce waste and protect the environment.", "ERR_TECH_G7PRA4_ENV", 1),
    TF("We should weigh up both the good and bad effects of a technology.", "True",
      "Good technology decisions weigh positive and negative impacts together.", "ERR_TECH_G7PRA4_WEIGH", 1),
    MC("Which is the BEST way to reduce technology's impact on the environment?",
      ["Reduce, reuse and recycle materials", "Throw everything away", "Use as much as possible", "Burn all waste"], "Reduce, reuse and recycle materials",
      "Reduce, reuse, recycle lowers waste and environmental impact.", "ERR_TECH_G7PRA4_3R", 2),
    {
      question: "Sort each effect of technology as 'Positive' or 'Negative'.",
      input_type: "sort-buckets",
      buckets: [{ id: "pos", label: "Positive impact" }, { id: "neg", label: "Negative impact" }],
      items: [
        { id: "i1", text: "Recycling creates jobs and saves resources", correct_bucket: "pos" },
        { id: "i2", text: "Factory smoke pollutes the air", correct_bucket: "neg" },
        { id: "i3", text: "Medicine cures more diseases", correct_bucket: "pos" },
        { id: "i4", text: "Cable theft cuts off phone lines", correct_bucket: "neg" },
      ],
      expected: "Recycling and medicine are positive; pollution and theft are negative.",
      pass_threshold: 0.75,
      memo: "Technology brings both benefits (jobs, medicine) and harms (pollution, crime) — weigh both.", error_signals: ["ERR_TECH_G7PRA4_SORT"], difficulty: 2,
    },
    MC("Sorting recyclable metal into types (e.g. ferrous and non-ferrous) is useful because…",
      ["it improves the scrap value", "it makes it heavier", "it wastes time", "there is no reason"], "it improves the scrap value",
      "Sorting metals by type raises their recycling value.", "ERR_TECH_G7PRA4_SORTVALUE", 2),
    TF("A technology that helps one group but harms another shows bias.", "True",
      "Helping some while harming others is a sign of bias in technology.", "ERR_TECH_G7PRA4_HELPHARM", 2),
    MC("Why think about the environment when designing a product?",
      ["So the product does not damage the planet", "To make it cost more", "To slow production", "There is no reason"], "So the product does not damage the planet",
      "Considering the environment helps avoid lasting damage to the planet.", "ERR_TECH_G7PRA4_WHYENV", 1),
    CLOZE("Cans, paper and plastic can all be collected for ____.",
      ["recycling", "burning", "burying", "hiding"], "recycling",
      "These materials are recyclable and can be collected to be reused.", "ERR_TECH_G7PRA4_RECYCLEWORD", 1),
    MC("An example of weighing impacts is comparing landline and mobile phones for…",
      ["their advantages and disadvantages to society", "their colour only", "their weight only", "their taste"], "their advantages and disadvantages to society",
      "Comparing landline vs mobile means weighing each one's pros and cons for society.", "ERR_TECH_G7PRA4_COMPARE", 2),
    TF("Good designers think about how their product affects different groups in society.", "True",
      "Thinking about effects on different groups helps avoid bias and harm.", "ERR_TECH_G7PRA4_THINK", 1),
    MC("The 'three Rs' for caring for the environment are…",
      ["reduce, reuse, recycle", "run, rest, repeat", "read, write, rule", "red, round, rough"], "reduce, reuse, recycle",
      "Reduce, reuse and recycle are the three Rs of environmental care.", "ERR_TECH_G7PRA4_THREERS", 1),
  ],
};

export default G7B;
