// ─── Technology SP — Grade 8 authored pools (part 1: DG · ST · MS) ───────────
// Graphics & Drawing · Structures (Term 1) · Mechanical Systems & Control (T3).
// Refs auto-assigned by build-technology-sp.mjs. Tap-only; no free text.
// Image-dependent skills (DG.A1, DG.A2, ST.A1) carry text-answerable items only;
// image-only questions are HELD (see TECHNOLOGY_SP_IMAGE_MANIFEST.md).

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8 = {
  // ════════════════════ GRAPHICS & DRAWING ════════════════════════════════════
  // DG.A1 · Graphics conventions (IMAGE-DEPENDENT — text items only)
  "TECH.G8.DG.A1": [
    MC("What is a centre line used to show on a drawing?",
      ["The centre of a circle, hole or symmetrical part", "A hidden edge", "A visible outline", "A dimension"], "The centre of a circle, hole or symmetrical part",
      "A centre line marks the centre of circles, holes and symmetrical features.", "ERR_TECH_G8DGA1_CENTRE", 1),
    MC("A centre line is drawn as a…",
      ["chain line (long dash, dot, long dash)", "thick solid line", "wavy line", "double line"], "chain line (long dash, dot, long dash)",
      "Centre lines use a chain line — alternating long dashes and dots.", "ERR_TECH_G8DGA1_CHAIN", 2),
    MC("In what unit are dimensions usually given on these drawings?",
      ["Millimetres (mm)", "Kilometres", "Litres", "Degrees Celsius"], "Millimetres (mm)",
      "Technical drawings normally use millimetres for dimensions.", "ERR_TECH_G8DGA1_MM", 1),
    MC("'Scaling down' a drawing means…",
      ["drawing the object smaller than real size", "drawing it bigger than real size", "the same size", "removing dimensions"], "drawing the object smaller than real size",
      "Scaling down draws a large object smaller so it fits the page.", "ERR_TECH_G8DGA1_SCALEDOWN", 2),
    MC("'Scaling up' a drawing means…",
      ["drawing a small object larger than real size", "drawing it smaller", "the same size", "hiding it"], "drawing a small object larger than real size",
      "Scaling up draws a tiny object bigger so its detail can be seen.", "ERR_TECH_G8DGA1_SCALEUP", 2),
    TF("Conventions are agreed rules so that any reader understands a drawing the same way.", "True",
      "Conventions (line types, scale, dimensions) are shared rules for clear communication.", "ERR_TECH_G8DGA1_CONVENTION", 1),
    CLOZE("Dimensions on a technical drawing are usually given in ____.",
      ["millimetres", "litres", "seconds", "degrees"], "millimetres",
      "Millimetres (mm) are the standard unit for dimensions.", "ERR_TECH_G8DGA1_MMWORD", 1),
    MC("A scale of 2:1 means the drawing is…",
      ["twice the size of the real object", "half the size", "the same size", "five times bigger"], "twice the size of the real object",
      "2:1 means 2 units on the drawing equal 1 real unit — the drawing is double size.", "ERR_TECH_G8DGA1_21", 3),
    TF("Hidden detail is shown with a dashed line, even in Grade 8.", "True",
      "Dashed lines for hidden detail is a convention that continues across the grades.", "ERR_TECH_G8DGA1_HIDDEN", 1),
    CLOZE("A long-dash-dot line that marks the middle of a part is a ____ line.",
      ["centre", "hidden", "outline", "border"], "centre",
      "The chain (long-dash-dot) line is the centre line.", "ERR_TECH_G8DGA1_CENTREWORD", 2),
    MC("Why dimension a drawing in mm rather than guessing sizes?",
      ["So the part is made to the exact size", "To use more ink", "To slow the maker", "There is no reason"], "So the part is made to the exact size",
      "Exact dimensions let the maker build the part to the correct size.", "ERR_TECH_G8DGA1_WHYDIM", 1),
    MC("A drawing of a tiny watch gear is best drawn using…",
      ["scaling up", "scaling down", "no scale", "hidden lines only"], "scaling up",
      "A very small object is scaled up so its detail is visible.", "ERR_TECH_G8DGA1_WATCH", 2),
    TF("Outlines are still drawn as thick, dark lines in Grade 8.", "True",
      "Thick dark outlines for visible edges remain a convention.", "ERR_TECH_G8DGA1_OUTLINE", 1),
    CLOZE("Drawing a big bridge small enough to fit on paper uses scaling ____.",
      ["down", "up", "off", "out"], "down",
      "Large objects are scaled down to fit the page.", "ERR_TECH_G8DGA1_DOWNWORD", 1),
    MC("Which is NOT a normal drawing convention?",
      ["Writing dimensions in random units each time", "Using mm for dimensions", "Dashed lines for hidden detail", "Chain lines for centres"], "Writing dimensions in random units each time",
      "Conventions require a consistent unit (mm); random units break the convention.", "ERR_TECH_G8DGA1_NOTCONV", 2),
    MC("A scale of 1:1 means…",
      ["the drawing is the same size as the object", "the drawing is bigger", "the drawing is smaller", "there is no object"], "the drawing is the same size as the object",
      "1:1 is full size — the drawing matches the real object exactly.", "ERR_TECH_G8DGA1_11", 2),
  ],

  // DG.A2 · Isometric & two-point perspective (IMAGE-DEPENDENT — text items only)
  "TECH.G8.DG.A2": [
    MC("Isometric drawing shows three sides of an object using lines that go up at…",
      ["30 degrees", "90 degrees", "10 degrees", "60 degrees"], "30 degrees",
      "Isometric drawing uses 30° lines for the two receding directions.", "ERR_TECH_G8DGA2_30", 2),
    MC("In isometric drawing, vertical edges are drawn…",
      ["vertical (straight up)", "at 45 degrees", "horizontal", "curved"], "vertical (straight up)",
      "Isometric keeps verticals vertical, with the other two directions at 30°.", "ERR_TECH_G8DGA2_VERTICAL", 2),
    MC("How many vanishing points does a two-point perspective drawing use?",
      ["Two", "One", "Three", "None"], "Two",
      "Two-point perspective uses two vanishing points, one on each side.", "ERR_TECH_G8DGA2_TWOVP", 1),
    TF("Two-point perspective makes a drawing look realistic, with sides shrinking towards two points.", "True",
      "Two-point perspective gives realism, with edges converging to two vanishing points.", "ERR_TECH_G8DGA2_REALISM", 2),
    MC("Isometric drawing is often done on…",
      ["an isometric (30°) grid", "blank paper only", "lined writing paper", "graph paper for maths sums"], "an isometric (30°) grid",
      "An isometric grid of 30° lines helps draw isometric views accurately.", "ERR_TECH_G8DGA2_GRID", 2),
    CLOZE("Isometric drawings use lines at ____ degrees for the receding sides.",
      ["30", "45", "60", "90"], "30",
      "Isometric uses 30° for the two receding directions.", "ERR_TECH_G8DGA2_30WORD", 2),
    MC("Which technique keeps the SAME scale along all three isometric axes?",
      ["Isometric", "Two-point perspective", "Single-point perspective", "Oblique"], "Isometric",
      "Isometric keeps equal scale on all three axes, unlike perspective which shrinks with distance.", "ERR_TECH_G8DGA2_EQUALSCALE", 3),
    TF("In perspective drawing, things look smaller as they get further away.", "True",
      "Perspective shrinks objects with distance, towards the vanishing point(s).", "ERR_TECH_G8DGA2_SHRINK", 1),
    MC("Adding colour, texture and shading to a drawing mainly…",
      ["makes it look more realistic", "changes its size", "removes dimensions", "hides it"], "makes it look more realistic",
      "Shading, colour and texture add realism to a 3D drawing.", "ERR_TECH_G8DGA2_SHADING", 1),
    CLOZE("A realistic 3D drawing using two vanishing points is ____-point perspective.",
      ["two", "one", "no", "three"], "two",
      "Two vanishing points = two-point perspective.", "ERR_TECH_G8DGA2_TWOWORD", 1),
    MC("Why might a designer use isometric rather than perspective for a working idea?",
      ["Isometric keeps true measurements along the axes", "Perspective is always wrong", "Isometric uses no lines", "Perspective is faster to measure"], "Isometric keeps true measurements along the axes",
      "Isometric keeps measurable, equal scales, which helps with sizing.", "ERR_TECH_G8DGA2_WHYISO", 3),
    TF("Shadows can be added to a perspective drawing to make it more realistic.", "True",
      "Shadows enhance realism in perspective drawings.", "ERR_TECH_G8DGA2_SHADOW", 2),
    MC("Both isometric and perspective are ways of drawing in…",
      ["3D", "2D", "1D", "words"], "3D",
      "Isometric and perspective are both 3D drawing techniques.", "ERR_TECH_G8DGA2_3D", 1),
    CLOZE("Vertical edges in an isometric drawing stay ____.",
      ["vertical", "flat", "curved", "diagonal"], "vertical",
      "Isometric keeps verticals vertical.", "ERR_TECH_G8DGA2_VERTWORD", 2),
    MC("Single-point perspective differs from two-point perspective because it uses…",
      ["one vanishing point instead of two", "no vanishing points", "three vanishing points", "only colour"], "one vanishing point instead of two",
      "Single-point uses one vanishing point; two-point uses two.", "ERR_TECH_G8DGA2_ONEVTWO", 2),
    TF("A 30° set square helps draw isometric lines.", "True",
      "A 30°/60° set square is used to draw the 30° isometric lines.", "ERR_TECH_G8DGA2_SETSQUARE", 2),
  ],

  // DG.A3 · Developments (nets)
  "TECH.G8.DG.A3": [
    MC("What is a 'development' (net) in drawing?",
      ["The flat shape that folds up into a 3D object", "A coloured picture", "A hidden line", "A dimension"], "The flat shape that folds up into a 3D object",
      "A development (net) is the flattened-out surface that folds into the 3D object.", "ERR_TECH_G8DGA3_DEF", 1),
    MC("A development of a cube would show…",
      ["six connected squares that fold into a box", "one square only", "a circle", "a triangle only"], "six connected squares that fold into a box",
      "A cube's net is six squares joined so they fold up into the cube.", "ERR_TECH_G8DGA3_CUBE", 2),
    TF("A net is used to plan how to make packaging from a flat sheet.", "True",
      "Nets show how to cut and fold a flat sheet into a 3D container.", "ERR_TECH_G8DGA3_PACKAGING", 1),
    MC("Why are tabs (flaps) added to a development?",
      ["So the edges can be glued or joined", "For decoration only", "To add weight", "To remove faces"], "So the edges can be glued or joined",
      "Tabs give a surface for glue so the folded faces join together.", "ERR_TECH_G8DGA3_TABS", 2),
    MC("A development of a cylinder (like a tin) is made of…",
      ["a rectangle and two circles", "three squares", "one triangle", "four circles"], "a rectangle and two circles",
      "A cylinder unrolls into a rectangle (the curved side) plus two circles (the ends).", "ERR_TECH_G8DGA3_CYLINDER", 3),
    CLOZE("The flat layout that folds into a box is called a ____.",
      ["net", "shadow", "dimension", "scale"], "net",
      "A net (development) folds into a 3D shape.", "ERR_TECH_G8DGA3_NETWORD", 1),
    TF("The fold lines on a development should be drawn so you know where to bend.", "True",
      "Fold lines show where to crease the flat sheet to form the 3D shape.", "ERR_TECH_G8DGA3_FOLDLINES", 2),
    MC("Designing packaging starts with thinking about…",
      ["the product that must fit inside", "the colour of the room", "the day of the week", "the price of paper clips"], "the product that must fit inside",
      "Packaging is designed to suit and protect the product inside.", "ERR_TECH_G8DGA3_PRODUCT", 2),
    MC("Which everyday item is made from a flat development that is folded up?",
      ["A cereal box", "A glass marble", "A metal ball", "A brick"], "A cereal box",
      "A cereal box is cut and folded from a flat development.", "ERR_TECH_G8DGA3_CEREAL", 1),
    CLOZE("Flaps added so faces can be glued are called ____.",
      ["tabs", "holes", "dots", "scales"], "tabs",
      "Tabs are the glue flaps on a development.", "ERR_TECH_G8DGA3_TABWORD", 2),
    TF("A development must have the correct number of faces to fold into the 3D shape.", "True",
      "If faces are missing or extra, the net won't fold correctly into the object.", "ERR_TECH_G8DGA3_FACES", 2),
    MC("The main purpose of drawing a development is to…",
      ["plan how to cut and fold a flat sheet into a 3D object", "decorate the page", "store data", "make a magnet"], "plan how to cut and fold a flat sheet into a 3D object",
      "Developments plan how flat material becomes a 3D container or part.", "ERR_TECH_G8DGA3_PURPOSE", 1),
    MC("How many square faces does the net of a cube have?",
      ["Six", "Four", "Eight", "Two"], "Six",
      "A cube has six faces, so its net has six squares.", "ERR_TECH_G8DGA3_SIX", 1),
    CLOZE("Lines that show where to bend a net are ____ lines.",
      ["fold", "hidden", "centre", "wavy"], "fold",
      "Fold lines mark where to crease the development.", "ERR_TECH_G8DGA3_FOLDWORD", 2),
    {
      question: "Order the steps to make a cardboard box from a development.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Draw the development (net) with tabs" },
        { id: "b", text: "Cut out the flat shape" },
        { id: "c", text: "Fold along the fold lines" },
        { id: "d", text: "Glue the tabs to form the box" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Draw the net, cut it out, fold along the lines, then glue the tabs into a box.",
      error_signals: ["ERR_TECH_G8DGA3_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each shape as part of the net of a CUBE or a CYLINDER.",
      input_type: "sort-buckets",
      buckets: [{ id: "cube", label: "Cube net" }, { id: "cyl", label: "Cylinder net" }],
      items: [
        { id: "i1", text: "Six squares", correct_bucket: "cube" },
        { id: "i2", text: "A rectangle (curved side)", correct_bucket: "cyl" },
        { id: "i3", text: "Two circles (the ends)", correct_bucket: "cyl" },
        { id: "i4", text: "Square faces joined in a cross", correct_bucket: "cube" },
      ],
      expected: "A cube's net is six squares; a cylinder's net is a rectangle plus two circles.",
      pass_threshold: 0.75,
      memo: "Cube net = 6 squares; cylinder net = 1 rectangle (the wrap-around) + 2 circles (the ends).", error_signals: ["ERR_TECH_G8DGA3_SORT"], difficulty: 3,
    },
    TF("Packaging design must protect the product and use material efficiently.", "True",
      "Good packaging protects the product while not wasting material.", "ERR_TECH_G8DGA3_EFFICIENT", 2),
    MC("A development is also useful because it helps you…",
      ["work out how much material is needed", "change the weather", "store electricity", "make sound"], "work out how much material is needed",
      "Laying out the net shows the total area of material required.", "ERR_TECH_G8DGA3_MATERIAL", 2),
    MC("If a net is missing one face, the folded shape will…",
      ["have a gap / not close up properly", "be stronger", "be heavier", "be a perfect box"], "have a gap / not close up properly",
      "A missing face leaves an opening — the shape won't close correctly.", "ERR_TECH_G8DGA3_MISSING", 2),
    CLOZE("A cylinder's curved surface unrolls into a ____.",
      ["rectangle", "circle", "triangle", "cube"], "rectangle",
      "The curved side of a cylinder unrolls flat into a rectangle.", "ERR_TECH_G8DGA3_RECT", 3),
  ],

  // ════════════════════════ STRUCTURES (Term 1) ═══════════════════════════════
  // ST.A1 · Frame members & roof trusses (IMAGE-DEPENDENT — text items only)
  "TECH.G8.ST.A1": [
    MC("What is a 'structural member'?",
      ["One of the bars or parts that make up a frame", "A club you join", "A type of glue", "A colour"], "One of the bars or parts that make up a frame",
      "A structural member is one of the bars/parts that make up a frame structure.", "ERR_TECH_G8STA1_MEMBER", 1),
    MC("In a roof truss, a 'tie' is a member that is mainly in…",
      ["tension (being pulled)", "compression (being pushed)", "no force", "rotation"], "tension (being pulled)",
      "A tie resists being pulled apart — it is in tension.", "ERR_TECH_G8STA1_TIE", 2),
    MC("In a roof truss, a 'strut' is a member that is mainly in…",
      ["compression (being pushed/squashed)", "tension", "no force", "twisting"], "compression (being pushed/squashed)",
      "A strut resists being pushed/squashed — it is in compression.", "ERR_TECH_G8STA1_STRUT", 2),
    MC("The sloping top members of a roof truss are called…",
      ["rafters", "ties", "axles", "pulleys"], "rafters",
      "Rafters are the sloping top members of a roof truss.", "ERR_TECH_G8STA1_RAFTER", 2),
    MC("The horizontal bottom member of a roof truss is the…",
      ["tie beam", "rafter", "king post tip", "wheel"], "tie beam",
      "The tie beam is the horizontal bottom member, held in tension.", "ERR_TECH_G8STA1_TIEBEAM", 2),
    TF("A king post is a central vertical member in a roof truss.", "True",
      "The king post is the central upright member of a truss.", "ERR_TECH_G8STA1_KINGPOST", 2),
    CLOZE("A member being pulled is in ____.",
      ["tension", "compression", "torsion", "shear"], "tension",
      "Tension is a pulling (stretching) force.", "ERR_TECH_G8STA1_TENSIONWORD", 1),
    CLOZE("A member being squashed is in ____.",
      ["compression", "tension", "torsion", "bending"], "compression",
      "Compression is a pushing (squashing) force.", "ERR_TECH_G8STA1_COMPWORD", 1),
    MC("Why are pylons and trusses full of triangles?",
      ["Triangulation makes them rigid and strong", "For decoration", "To use more steel", "To make them heavier"], "Triangulation makes them rigid and strong",
      "Triangulation (cross-bracing) gives frames their rigidity and strength.", "ERR_TECH_G8STA1_TRIANGULATION", 2),
    TF("A queen post truss has two upright posts instead of one central post.", "True",
      "A queen post truss uses two vertical posts (rather than the single king post).", "ERR_TECH_G8STA1_QUEEN", 3),
    MC("Different pylon designs that all carry power lines safely show that…",
      ["many designs can solve the same problem", "only one design ever works", "designs never matter", "all pylons are identical"], "many designs can solve the same problem",
      "A range of pylon designs can each solve the same problem effectively.", "ERR_TECH_G8STA1_VARIETY", 2),
    MC("Internal cross-bracing is added to a frame to…",
      ["stiffen it and stop it racking (leaning over)", "make it colourful", "add weight", "remove members"], "stiffen it and stop it racking (leaning over)",
      "Cross-bracing triangulates a frame so it doesn't rack (lean) under load.", "ERR_TECH_G8STA1_BRACING", 2),
    CLOZE("The sloping top members of a truss are called ____.",
      ["rafters", "ties", "axles", "cams"], "rafters",
      "Rafters are the sloping top members.", "ERR_TECH_G8STA1_RAFTERWORD", 2),
    TF("Ties and struts experience different forces in a truss.", "True",
      "Ties are in tension; struts are in compression — different forces.", "ERR_TECH_G8STA1_DIFF", 2),
    {
      question: "Sort each truss member by the force it mainly carries.",
      input_type: "sort-buckets",
      buckets: [{ id: "ten", label: "Tension (pulled)" }, { id: "comp", label: "Compression (pushed)" }],
      items: [
        { id: "i1", text: "Tie", correct_bucket: "ten" },
        { id: "i2", text: "Strut", correct_bucket: "comp" },
        { id: "i3", text: "Tie beam", correct_bucket: "ten" },
      ],
      expected: "A tie and tie beam are in tension; a strut is in compression.",
      pass_threshold: 0.66,
      memo: "Ties (and tie beams) are pulled = tension; struts are pushed = compression.", error_signals: ["ERR_TECH_G8STA1_SORT"], difficulty: 3,
    },
    MC("Why does a roof truss use sloping rafters and a horizontal tie beam together?",
      ["The shape spreads the roof load and stays rigid", "It looks nice only", "To use less wood by accident", "There is no reason"], "The shape spreads the roof load and stays rigid",
      "The triangular truss shape spreads the load and stays rigid under the roof weight.", "ERR_TECH_G8STA1_SHAPE", 3),
  ],

  // ST.A2 · Forces acting on members
  "TECH.G8.ST.A2": [
    MC("Which force tries to PULL a material apart?",
      ["Tension", "Compression", "Torsion", "Shear"], "Tension",
      "Tension is a pulling force that stretches a material.", "ERR_TECH_G8STA2_TENSION", 1),
    MC("Which force tries to SQUASH a material?",
      ["Compression", "Tension", "Torsion", "Shear"], "Compression",
      "Compression is a pushing force that squashes a material.", "ERR_TECH_G8STA2_COMPRESSION", 1),
    MC("Which force tries to TWIST a material?",
      ["Torsion", "Tension", "Compression", "Bending"], "Torsion",
      "Torsion is a twisting force.", "ERR_TECH_G8STA2_TORSION", 1),
    MC("Which force acts when two parts slide past each other, like scissors cutting?",
      ["Shear", "Tension", "Compression", "Torsion"], "Shear",
      "Shear acts when parts slide past each other in opposite directions.", "ERR_TECH_G8STA2_SHEAR", 2),
    MC("When a beam bends under a load, the top is squashed and the bottom is…",
      ["stretched (in tension)", "also squashed", "twisted", "removed"], "stretched (in tension)",
      "In a loaded beam, the top is in compression and the bottom is in tension.", "ERR_TECH_G8STA2_BENDING", 3),
    TF("A rope holding a hanging weight is in tension.", "True",
      "A rope holding a load is pulled tight — it is in tension.", "ERR_TECH_G8STA2_ROPE", 1),
    TF("A column holding up a roof is mainly in compression.", "True",
      "A column carries weight pushing down on it — compression.", "ERR_TECH_G8STA2_COLUMN", 1),
    CLOZE("A pulling force that stretches a material is called ____.",
      ["tension", "compression", "shear", "torsion"], "tension",
      "Tension stretches; compression squashes.", "ERR_TECH_G8STA2_TENWORD", 1),
    CLOZE("A twisting force is called ____.",
      ["torsion", "tension", "compression", "shear"], "torsion",
      "Torsion is a twisting force.", "ERR_TECH_G8STA2_TORWORD", 1),
    MC("Turning a door handle or a screwdriver applies which force to the shaft?",
      ["Torsion", "Tension", "Shear", "Bending"], "Torsion",
      "Twisting a shaft applies torsion.", "ERR_TECH_G8STA2_SCREWDRIVER", 2),
    MC("A punch cutting a hole through metal applies which force?",
      ["Shear", "Tension", "Torsion", "Bending"], "Shear",
      "A punch shears the metal, making parts slide past each other.", "ERR_TECH_G8STA2_PUNCH", 3),
    TF("Bending involves both compression and tension at the same time.", "True",
      "A bending beam is compressed on one side and stretched (tension) on the other.", "ERR_TECH_G8STA2_BOTH", 2),
    MC("A bookshelf sagging under heavy books is mainly experiencing…",
      ["bending", "torsion", "shear", "no force"], "bending",
      "A sagging shelf is bending under the load.", "ERR_TECH_G8STA2_SHELF", 2),
    CLOZE("Two forces that make parts slide past each other cause ____.",
      ["shear", "tension", "torsion", "lift"], "shear",
      "Shear makes layers/parts slide past one another.", "ERR_TECH_G8STA2_SHEARWORD", 2),
    {
      question: "Match each example to the main force acting on it.",
      input_type: "sort-buckets",
      buckets: [{ id: "ten", label: "Tension" }, { id: "comp", label: "Compression" }, { id: "tor", label: "Torsion" }, { id: "sh", label: "Shear" }],
      items: [
        { id: "i1", text: "A tow rope pulling a car", correct_bucket: "ten" },
        { id: "i2", text: "A pillar under a heavy roof", correct_bucket: "comp" },
        { id: "i3", text: "Twisting a screwdriver", correct_bucket: "tor" },
        { id: "i4", text: "Scissors cutting paper", correct_bucket: "sh" },
      ],
      expected: "Rope = tension; pillar = compression; screwdriver = torsion; scissors = shear.",
      pass_threshold: 0.75,
      memo: "Tension pulls, compression squashes, torsion twists, shear slides parts past each other.", error_signals: ["ERR_TECH_G8STA2_SORT"], difficulty: 3,
    },
    MC("Adding ribs or folds to a flat sheet helps it resist…",
      ["bending", "rusting", "magnetism", "colour fading"], "bending",
      "Ribs and folds stiffen a sheet so it resists bending.", "ERR_TECH_G8STA2_RIBS", 2),
    TF("Concrete is strong in compression but weak in tension.", "True",
      "Concrete handles squashing (compression) well but cracks when stretched (tension), so it is reinforced.", "ERR_TECH_G8STA2_CONCRETE", 3),
    MC("A chair leg pressed by someone sitting on the chair is in…",
      ["compression", "tension", "torsion", "no force"], "compression",
      "The chair leg is squashed by the weight — compression.", "ERR_TECH_G8STA2_CHAIRLEG", 1),
    CLOZE("In a loaded beam, the bottom fibres are usually in ____.",
      ["tension", "torsion", "shear", "no force"], "tension",
      "The bottom of a bending beam is stretched — in tension.", "ERR_TECH_G8STA2_BEAMBOTTOM", 3),
    MC("Knowing the forces on members helps a designer to…",
      ["choose the right material and shape for each part", "pick a nice colour", "decide the weather", "name the building"], "choose the right material and shape for each part",
      "Understanding forces lets designers pick materials/shapes that resist them.", "ERR_TECH_G8STA2_WHY", 2),
  ],

  // ST.A3 · Structures that span space
  "TECH.G8.ST.A3": [
    MC("A 'beam' is a structural member that…",
      ["spans a gap and carries a load across it", "stores electricity", "spins around", "holds liquid"], "spans a gap and carries a load across it",
      "A beam spans across a gap and carries the load between its supports.", "ERR_TECH_G8STA3_BEAM", 1),
    MC("A steel I-beam (girder) is shaped like an 'I' to…",
      ["be strong and stiff while saving material", "look like a letter", "be heavier", "rust faster"], "be strong and stiff while saving material",
      "The I-shape puts material where it resists bending best, saving weight.", "ERR_TECH_G8STA3_IBEAM", 3),
    MC("A concrete beam over a door or window is called a…",
      ["lintel", "rafter", "cam", "pulley"], "lintel",
      "A lintel is the beam that spans over a door or window opening.", "ERR_TECH_G8STA3_LINTEL", 2),
    MC("In a suspension bridge, the deck mainly hangs from…",
      ["cables", "wheels", "magnets", "gears"], "cables",
      "A suspension bridge hangs its deck from large cables.", "ERR_TECH_G8STA3_SUSPENSION", 2),
    MC("An arch is good at spanning because it carries load mainly in…",
      ["compression", "tension", "torsion", "shear"], "compression",
      "An arch directs the load into compression along its curve, down to the supports.", "ERR_TECH_G8STA3_ARCH", 3),
    MC("A cantilever is a beam that is…",
      ["supported at one end and sticks out", "supported at both ends", "floating freely", "made of rope"], "supported at one end and sticks out",
      "A cantilever is fixed at one end and projects out, like a diving board.", "ERR_TECH_G8STA3_CANTILEVER", 2),
    TF("A diving board is an everyday example of a cantilever.", "True",
      "A diving board is fixed at one end and sticks out — a cantilever.", "ERR_TECH_G8STA3_DIVING", 1),
    CLOZE("A beam that spans over a window opening is a ____.",
      ["lintel", "rafter", "cam", "tie"], "lintel",
      "A lintel spans over a door or window.", "ERR_TECH_G8STA3_LINTELWORD", 2),
    TF("Arches have been used for centuries in buildings, bridges and dam walls.", "True",
      "Arches are an ancient and reliable way to span gaps in many structures.", "ERR_TECH_G8STA3_ANCIENT", 1),
    MC("A cable-stayed bridge supports its deck with…",
      ["straight cables running directly to towers", "magnets", "wheels", "rubber bands"], "straight cables running directly to towers",
      "Cable-stayed bridges use straight cables from the deck to the towers.", "ERR_TECH_G8STA3_CABLESTAYED", 2),
    MC("Why use an arch instead of a flat beam for a large stone span?",
      ["Stone is strong in compression, which an arch uses", "Stone is strong in tension", "Arches use no material", "Beams cannot be made of stone"], "Stone is strong in compression, which an arch uses",
      "Stone resists compression well, and an arch keeps the stone in compression.", "ERR_TECH_G8STA3_WHYARCH", 3),
    CLOZE("A beam fixed at one end that projects outward is a ____.",
      ["cantilever", "lintel", "arch", "cable"], "cantilever",
      "A cantilever is fixed at one end and projects out.", "ERR_TECH_G8STA3_CANTWORD", 2),
    TF("A simple beam bridge rests on supports (piers) at each end.", "True",
      "A beam-and-column bridge spans between supports at each end.", "ERR_TECH_G8STA3_BEAMBRIDGE", 1),
    MC("A girder is best described as a…",
      ["large strong beam, often an I-beam", "small magnet", "rope", "wheel"], "large strong beam, often an I-beam",
      "A girder is a large, strong beam (often I-shaped) used in big structures.", "ERR_TECH_G8STA3_GIRDER", 2),
    {
      question: "Match each way of spanning to its example.",
      input_type: "sort-buckets",
      buckets: [{ id: "beam", label: "Beam" }, { id: "arch", label: "Arch" }, { id: "cant", label: "Cantilever" }, { id: "susp", label: "Suspension" }],
      items: [
        { id: "i1", text: "Concrete lintel over a door", correct_bucket: "beam" },
        { id: "i2", text: "Curved stone bridge", correct_bucket: "arch" },
        { id: "i3", text: "Diving board", correct_bucket: "cant" },
        { id: "i4", text: "Deck hung from big cables", correct_bucket: "susp" },
      ],
      expected: "Lintel = beam; curved stone bridge = arch; diving board = cantilever; cable-hung deck = suspension.",
      pass_threshold: 0.75,
      memo: "Beams rest on supports, arches curve in compression, cantilevers stick out from one end, suspension decks hang from cables.", error_signals: ["ERR_TECH_G8STA3_SORT"], difficulty: 3,
    },
    MC("Which spanning method is best for a very LONG bridge across a wide river?",
      ["Suspension or cable-stayed bridge", "A single short beam", "A solid wall", "A cantilever only"], "Suspension or cable-stayed bridge",
      "Very long spans use suspension or cable-stayed designs to cross wide gaps.", "ERR_TECH_G8STA3_LONG", 2),
    TF("An I-beam uses its shape to resist bending without being solid all through.", "True",
      "The I-shape concentrates material where bending stress is highest, saving weight.", "ERR_TECH_G8STA3_ISHAPE", 3),
    CLOZE("A bridge whose deck hangs from big main cables is a ____ bridge.",
      ["suspension", "beam", "arch", "solid"], "suspension",
      "Suspension bridges hang the deck from main cables.", "ERR_TECH_G8STA3_SUSPWORD", 2),
    MC("The main job of all these (beams, arches, cantilevers, bridges) is to…",
      ["span a gap and carry a load across it", "make electricity", "store water", "make sound"], "span a gap and carry a load across it",
      "All these structures span gaps and carry loads across them.", "ERR_TECH_G8STA3_SPAN", 1),
    MC("Why is a cylinder (like a pipe or can) a strong way to span or support?",
      ["The round shape resists bending in all directions", "It is solid all through", "It is always heavier", "It has corners"], "The round shape resists bending in all directions",
      "A tube's round cross-section resists bending well for its weight — a strong, efficient shape.", "ERR_TECH_G8STA3_TUBE", 3),
  ],

  // ST.A4 · Structural failure
  "TECH.G8.ST.A4": [
    MC("What are the three main ways a structure can fail?",
      ["Fracture, bending and toppling", "Painting, drawing and folding", "Heating, cooling and freezing", "Running, jumping and resting"], "Fracture, bending and toppling",
      "Structures fail by fracturing, bending (flexing) or toppling over.", "ERR_TECH_G8STA4_THREE", 1),
    MC("'Fracture' of a member happens because of a lack of…",
      ["strength", "colour", "stability", "weight"], "strength",
      "Fracture (breaking) is caused by a lack of strength.", "ERR_TECH_G8STA4_FRACTURE", 2),
    MC("Bending or buckling of a structure is caused by a lack of…",
      ["stiffness (rigidity)", "colour", "strength", "weight"], "stiffness (rigidity)",
      "Bending/buckling is caused by a lack of stiffness (rigidity).", "ERR_TECH_G8STA4_BENDING", 2),
    MC("Toppling over is caused by a lack of…",
      ["stability", "strength", "stiffness", "colour"], "stability",
      "Toppling is caused by a lack of stability (e.g. top-heavy, narrow base).", "ERR_TECH_G8STA4_TOPPLING", 2),
    TF("A structure can be strong but still topple if it is unstable.", "True",
      "Strength prevents breaking; stability prevents toppling — they are different.", "ERR_TECH_G8STA4_STRONGTOPPLE", 2),
    CLOZE("A member that snaps under load has failed by ____.",
      ["fracture", "toppling", "rusting", "colour"], "fracture",
      "Snapping/breaking is fracture, due to lack of strength.", "ERR_TECH_G8STA4_FRACWORD", 1),
    MC("A tall, narrow, top-heavy tower is most likely to fail by…",
      ["toppling", "rusting", "fracturing only", "melting"], "toppling",
      "Top-heavy, narrow structures topple — a stability failure.", "ERR_TECH_G8STA4_TALLNARROW", 2),
    MC("A thin shelf that sags badly but does not break has failed by…",
      ["bending (lack of stiffness)", "fracture", "toppling", "rusting"], "bending (lack of stiffness)",
      "A sagging shelf has bent — it lacks stiffness even if it hasn't broken.", "ERR_TECH_G8STA4_SAG", 2),
    TF("Adding triangulation can help prevent bending failure.", "True",
      "Triangulation increases stiffness, helping prevent bending/buckling.", "ERR_TECH_G8STA4_TRI", 2),
    CLOZE("Failing by leaning over and falling is called ____.",
      ["toppling", "fracture", "bending", "rusting"], "toppling",
      "Toppling is falling over — a stability failure.", "ERR_TECH_G8STA4_TOPWORD", 1),
    MC("To stop a structure fracturing, you could…",
      ["use a stronger material or thicker member", "paint it", "make it taller", "narrow the base"], "use a stronger material or thicker member",
      "Increasing strength (stronger or thicker members) prevents fracture.", "ERR_TECH_G8STA4_FIXFRAC", 2),
    MC("To stop a tower toppling, you could…",
      ["widen the base and lower the weight", "make it taller and narrower", "add top weight", "paint it"], "widen the base and lower the weight",
      "Widening the base and lowering the centre of gravity improve stability.", "ERR_TECH_G8STA4_FIXTOPPLE", 2),
    TF("Buckling is a kind of bending failure in members under compression.", "True",
      "A slender member in compression can buckle — a bending-type failure.", "ERR_TECH_G8STA4_BUCKLE", 3),
    {
      question: "Match each failure to its missing quality.",
      input_type: "sort-buckets",
      buckets: [{ id: "str", label: "Lacks strength" }, { id: "stiff", label: "Lacks stiffness" }, { id: "stab", label: "Lacks stability" }],
      items: [
        { id: "i1", text: "A beam snaps in two", correct_bucket: "str" },
        { id: "i2", text: "A shelf sags in the middle", correct_bucket: "stiff" },
        { id: "i3", text: "A tall tower tips over", correct_bucket: "stab" },
        { id: "i4", text: "A thin strut buckles sideways", correct_bucket: "stiff" },
      ],
      expected: "Snapping = lacks strength; sagging/buckling = lacks stiffness; tipping over = lacks stability.",
      pass_threshold: 0.75,
      memo: "Fracture = no strength; bending/buckling = no stiffness; toppling = no stability.", error_signals: ["ERR_TECH_G8STA4_SORT"], difficulty: 3,
    },
    MC("Why do designers test models to failure?",
      ["To learn how and why a structure fails and improve it", "To waste materials", "To break things for fun", "There is no reason"], "To learn how and why a structure fails and improve it",
      "Testing to failure reveals weaknesses so the design can be improved.", "ERR_TECH_G8STA4_TEST", 2),
    TF("Strength, stiffness and stability are three different things a structure may need.", "True",
      "Strength (won't break), stiffness (won't bend), stability (won't topple) are distinct needs.", "ERR_TECH_G8STA4_THREEQUAL", 1),
    MC("A bridge that flexes too much in the wind is failing in…",
      ["stiffness", "strength", "colour", "weight"], "stiffness",
      "Excess flexing is a stiffness (rigidity) problem.", "ERR_TECH_G8STA4_FLEX", 2),
    CLOZE("A structure that does not break, bend or topple is well ____.",
      ["designed", "painted", "coloured", "named"], "designed",
      "Resisting all three failures is the mark of a well-designed structure.", "ERR_TECH_G8STA4_WELLDESIGN", 1),
    MC("Reinforcing concrete with steel mainly helps it resist…",
      ["tension and so reduce fracture/cracking", "rust", "colour change", "magnetism"], "tension and so reduce fracture/cracking",
      "Steel adds tensile strength to concrete, reducing cracking/fracture.", "ERR_TECH_G8STA4_REINFORCE", 3),
    MC("A model bridge collapses the moment a load is added in the middle. It most likely lacked…",
      ["strength (it fractured)", "colour", "a nice shape", "paint"], "strength (it fractured)",
      "A sudden break under load is a fracture — the structure lacked strength.", "ERR_TECH_G8STA4_COLLAPSE", 2),
  ],

  // ════════════════ MECHANICAL SYSTEMS & CONTROL (Term 3) ═════════════════════
  // MS.A1 · Simple mechanisms: wedge, wheel & axle
  "TECH.G8.MS.A1": [
    MC("A wedge is a simple machine that…",
      ["splits or lifts by being driven in", "stores electricity", "spins forever", "holds liquid"], "splits or lifts by being driven in",
      "A wedge is driven into something to split or lift it — like an axe or door wedge.", "ERR_TECH_G8MSA1_WEDGE", 1),
    MC("A wedge is really a moving form of which simple machine?",
      ["The inclined plane (ramp)", "The pulley", "The gear", "The magnet"], "The inclined plane (ramp)",
      "A wedge is a moving inclined plane.", "ERR_TECH_G8MSA1_INCLINED", 2),
    MC("Which is an example of a wedge?",
      ["A knife blade", "A bicycle wheel", "A pulley", "A battery"], "A knife blade",
      "A knife blade is a wedge that splits material apart.", "ERR_TECH_G8MSA1_KNIFE", 1),
    MC("A wheel and axle makes work easier by…",
      ["turning a small effort at the rim into a larger turning force", "storing light", "making sound", "cooling things"], "turning a small effort at the rim into a larger turning force",
      "A large wheel turning a small axle gives a mechanical advantage.", "ERR_TECH_G8MSA1_WHEELAXLE", 2),
    MC("Which is an example of a wheel and axle?",
      ["A door handle", "A knife", "A ramp", "A wedge"], "A door handle",
      "A door handle (wheel) turns a spindle (axle) — a wheel-and-axle.", "ERR_TECH_G8MSA1_DOORHANDLE", 2),
    TF("A ramp (inclined plane) lets you raise a load with less effort over a longer distance.", "True",
      "An inclined plane trades a longer push for less effort to raise a load.", "ERR_TECH_G8MSA1_RAMP", 1),
    CLOZE("A knife blade and an axe head are examples of a ____.",
      ["wedge", "pulley", "gear", "magnet"], "wedge",
      "Both are wedges — moving inclined planes that split material.", "ERR_TECH_G8MSA1_WEDGEWORD", 1),
    MC("Pushing a heavy box up a ramp instead of lifting it straight up…",
      ["needs less effort but over a longer distance", "needs more effort", "is impossible", "uses electricity"], "needs less effort but over a longer distance",
      "The ramp reduces the effort needed, but you push over a greater distance.", "ERR_TECH_G8MSA1_BOX", 2),
    TF("All complex machines are built from combinations of simple mechanisms.", "True",
      "Complex machines combine simple mechanisms like wedges, wheels, levers and gears.", "ERR_TECH_G8MSA1_COMBINE", 1),
    CLOZE("A large wheel fixed to a small ____ forms a wheel-and-axle.",
      ["axle", "magnet", "battery", "rope"], "axle",
      "A wheel-and-axle is a wheel fixed to an axle.", "ERR_TECH_G8MSA1_AXLEWORD", 1),
    MC("A doorknob is easier to turn than the bare spindle because…",
      ["the wider wheel gives a mechanical advantage", "it is colourful", "it is heavier", "it is magnetic"], "the wider wheel gives a mechanical advantage",
      "The wide knob (wheel) gives leverage over the thin spindle (axle).", "ERR_TECH_G8MSA1_KNOB", 2),
    MC("A screw can be thought of as a wedge wrapped around a…",
      ["cylinder", "magnet", "battery", "rope"], "cylinder",
      "A screw thread is an inclined plane (wedge) wrapped around a cylinder.", "ERR_TECH_G8MSA1_SCREW", 3),
    TF("A steering wheel turning a steering column is a wheel-and-axle.", "True",
      "The steering wheel (wheel) turns the column (axle) — a wheel-and-axle.", "ERR_TECH_G8MSA1_STEERING", 2),
    {
      question: "Sort each object as a 'Wedge' or a 'Wheel and axle'.",
      input_type: "sort-buckets",
      buckets: [{ id: "wedge", label: "Wedge" }, { id: "wa", label: "Wheel and axle" }],
      items: [
        { id: "i1", text: "Axe head", correct_bucket: "wedge" },
        { id: "i2", text: "Door handle", correct_bucket: "wa" },
        { id: "i3", text: "Chisel tip", correct_bucket: "wedge" },
        { id: "i4", text: "Steering wheel", correct_bucket: "wa" },
      ],
      expected: "Axe head and chisel are wedges; door handle and steering wheel are wheel-and-axle.",
      pass_threshold: 0.75,
      memo: "Wedges split/lift (axe, chisel); wheel-and-axle turns (door handle, steering wheel).", error_signals: ["ERR_TECH_G8MSA1_SORT"], difficulty: 2,
    },
    MC("The main reason to use a simple machine is to…",
      ["gain a mechanical advantage / make work easier", "make work harder", "use more energy", "look good"], "gain a mechanical advantage / make work easier",
      "Simple machines give a mechanical advantage, making work easier.", "ERR_TECH_G8MSA1_MA", 1),
    TF("A doorstop wedge holds a door by jamming under it.", "True",
      "A door wedge is jammed under the door to hold it in place.", "ERR_TECH_G8MSA1_DOORSTOP", 1),
    MC("A wheelbarrow wheel turning on its axle is an example of…",
      ["a wheel and axle", "a wedge", "a gear train", "a magnet"], "a wheel and axle",
      "The wheel turning on its axle is a wheel-and-axle mechanism.", "ERR_TECH_G8MSA1_BARROWWHEEL", 1),
    CLOZE("A ramp is also called an inclined ____.",
      ["plane", "wheel", "gear", "rope"], "plane",
      "A ramp is an inclined plane — a simple machine.", "ERR_TECH_G8MSA1_PLANE", 1),
    MC("A longer, gentler ramp compared with a short, steep one needs…",
      ["less effort but a longer push", "more effort", "no effort", "electricity"], "less effort but a longer push",
      "A gentler ramp reduces effort but increases the distance pushed.", "ERR_TECH_G8MSA1_GENTLE", 2),
    TF("The teeth of a gear can be thought of as small wedges.", "True",
      "Gear teeth act like little wedges that push the next gear along.", "ERR_TECH_G8MSA1_GEARTEETH", 3),
  ],

  // MS.A2 · Gears: counter-rotation & idlers
  "TECH.G8.MS.A2": [
    MC("What is a gear?",
      ["A toothed wheel that meshes with another to pass on movement", "A type of battery", "A kind of rope", "A magnet"], "A toothed wheel that meshes with another to pass on movement",
      "A gear is a toothed wheel; meshing teeth pass rotation from one gear to another.", "ERR_TECH_G8MSA2_DEF", 1),
    MC("When two spur gears mesh directly, they turn…",
      ["in opposite directions", "in the same direction", "not at all", "only once"], "in opposite directions",
      "Directly meshed gears counter-rotate — they turn opposite ways.", "ERR_TECH_G8MSA2_COUNTER", 1),
    MC("What does an IDLER gear do between two gears?",
      ["Makes the driver and driven gears turn the SAME way", "Stops all movement", "Stores power", "Changes colour"], "Makes the driver and driven gears turn the SAME way",
      "An idler gear reverses the direction once more, so driver and driven turn the same way.", "ERR_TECH_G8MSA2_IDLER", 2),
    TF("An idler gear changes the direction of rotation but not the overall gear ratio between driver and driven.", "True",
      "An idler only changes direction; it does not change the driver-to-driven gear ratio.", "ERR_TECH_G8MSA2_NORATIO", 3),
    MC("The gear that is turned by the power source is the…",
      ["driver gear", "driven gear", "idler", "axle"], "driver gear",
      "The driver gear is turned by the input/power; it drives the others.", "ERR_TECH_G8MSA2_DRIVER", 2),
    MC("The gear that receives the movement is the…",
      ["driven gear", "driver gear", "idler", "wedge"], "driven gear",
      "The driven gear is the one that receives the motion from the driver.", "ERR_TECH_G8MSA2_DRIVEN", 2),
    TF("Two directly meshed gears of the same size turn at the same speed but opposite directions.", "True",
      "Equal-size meshed gears turn at equal speed, in opposite directions.", "ERR_TECH_G8MSA2_EQUAL", 2),
    CLOZE("Gears that mesh directly turn in ____ directions.",
      ["opposite", "the same", "no", "random"], "opposite",
      "Directly meshed gears counter-rotate (opposite directions).", "ERR_TECH_G8MSA2_OPPWORD", 1),
    MC("Why might an idler gear be made of harder material?",
      ["It rotates more times (if smaller) and wears faster", "It is decorative", "It is heavier", "It stores charge"], "It rotates more times (if smaller) and wears faster",
      "A small idler spins more often, so harder material resists the extra wear.", "ERR_TECH_G8MSA2_HARDER", 3),
    MC("Bevel gears are used to…",
      ["transfer rotation through a 90° corner", "store electricity", "make light", "stop motion"], "transfer rotation through a 90° corner",
      "Bevel gears turn the axis of rotation through 90°.", "ERR_TECH_G8MSA2_BEVEL", 2),
    TF("A bicycle uses gears to transfer the pedalling motion to the wheel.", "True",
      "Bicycle gears (chain wheels and cogs) transfer pedalling to the rear wheel.", "ERR_TECH_G8MSA2_BICYCLE", 1),
    CLOZE("A gear placed between two others to make them turn the same way is an ____.",
      ["idler", "axle", "anchor", "arch"], "idler",
      "An idler gear makes the driver and driven gears turn the same way.", "ERR_TECH_G8MSA2_IDLERWORD", 2),
    MC("If a driver gear turns clockwise and meshes directly with a driven gear, the driven gear turns…",
      ["anticlockwise", "clockwise", "not at all", "both ways"], "anticlockwise",
      "Directly meshed gears counter-rotate, so the driven gear turns the opposite way.", "ERR_TECH_G8MSA2_CW", 2),
    {
      question: "Order what happens when a driver gear meshes with one idler and then a driven gear.",
      input_type: "sequence",
      items: [
        { id: "a", text: "The driver gear turns clockwise" },
        { id: "b", text: "The idler turns anticlockwise" },
        { id: "c", text: "The driven gear turns clockwise (same as driver)" },
      ],
      expected_order: ["a", "b", "c"],
      memo: "Each mesh reverses direction, so after an idler the driven gear turns the SAME way as the driver.",
      error_signals: ["ERR_TECH_G8MSA2_SEQUENCE"], difficulty: 3,
    },
    {
      question: "Sort each statement as TRUE of an idler gear or NOT.",
      input_type: "sort-buckets",
      buckets: [{ id: "yes", label: "True of an idler" }, { id: "no", label: "Not true of an idler" }],
      items: [
        { id: "i1", text: "It makes driver and driven turn the same way", correct_bucket: "yes" },
        { id: "i2", text: "It changes the gear ratio between driver and driven", correct_bucket: "no" },
        { id: "i3", text: "It sits between the driver and driven gears", correct_bucket: "yes" },
        { id: "i4", text: "It stops the gears turning", correct_bucket: "no" },
      ],
      expected: "An idler sits between gears and makes them turn the same way; it does NOT change the ratio or stop motion.",
      pass_threshold: 0.75,
      memo: "Idler = changes direction (same way), sits in the middle; it does not alter the overall ratio.", error_signals: ["ERR_TECH_G8MSA2_SORT"], difficulty: 3,
    },
    MC("Spur gears have teeth that are…",
      ["straight and cut on the rim", "round and smooth", "made of rope", "magnetic"], "straight and cut on the rim",
      "Spur gears have straight teeth cut on the edge of the wheel.", "ERR_TECH_G8MSA2_SPUR", 2),
    TF("Gear teeth must be the same size and spacing to mesh properly.", "True",
      "Meshing gears need matching tooth size and spacing (the same module).", "ERR_TECH_G8MSA2_MESH", 2),
    MC("The chain wheel and cogs on a bicycle are a type of…",
      ["gear system", "magnet", "lever only", "shell structure"], "gear system",
      "A bicycle's chain wheel and cogs form a gear system.", "ERR_TECH_G8MSA2_CHAINWHEEL", 1),
    CLOZE("Bevel gears change the axis of rotation through ____ degrees.",
      ["90", "45", "180", "10"], "90",
      "Bevel gears turn rotation through a 90° corner.", "ERR_TECH_G8MSA2_90", 2),
    MC("Two meshed gears stay synchronised because…",
      ["their teeth lock together", "they are glued", "they are magnetic", "they are painted"], "their teeth lock together",
      "Interlocking teeth keep meshed gears moving together exactly.", "ERR_TECH_G8MSA2_LOCK", 2),
  ],

  // MS.A3 · Gear ratios: velocity & force
  "TECH.G8.MS.A3": [
    MC("If a small gear drives a larger gear, the larger gear turns…",
      ["slower but with more force", "faster with less force", "at the same speed", "not at all"], "slower but with more force",
      "Driving a larger gear reduces speed but increases turning force (torque).", "ERR_TECH_G8MSA3_SLOWERFORCE", 2),
    MC("If a large gear drives a smaller gear, the smaller gear turns…",
      ["faster but with less force", "slower with more force", "the same speed", "backwards only"], "faster but with less force",
      "Driving a smaller gear increases speed but reduces force.", "ERR_TECH_G8MSA3_FASTERLESS", 2),
    TF("In gears, if speed increases, the turning force decreases, and vice versa.", "True",
      "Gears trade speed for force: more speed means less force, and the reverse.", "ERR_TECH_G8MSA3_TRADE", 2),
    MC("A driver gear has 10 teeth and the driven gear has 30 teeth. The gear ratio is…",
      ["3:1", "1:3", "10:30 the same as 5:1", "30:1"], "3:1",
      "30 driven ÷ 10 driver = 3, so the ratio is 3:1 (the driven turns once for every 3 turns of the driver).", "ERR_TECH_G8MSA3_RATIO31", 3),
    MC("With a 3:1 reduction, when the driver turns 3 times the driven turns…",
      ["1 time", "3 times", "9 times", "0 times"], "1 time",
      "A 3:1 reduction means the driven gear turns once for every 3 turns of the driver.", "ERR_TECH_G8MSA3_TURNS", 3),
    MC("A driver of 20 teeth meshes with a driven of 10 teeth. The driven turns…",
      ["twice for each turn of the driver (faster)", "half as fast", "the same speed", "not at all"], "twice for each turn of the driver (faster)",
      "20 ÷ 10 = 2, so the smaller driven gear turns twice for each driver turn — faster.", "ERR_TECH_G8MSA3_DOUBLE", 3),
    TF("To get more turning force (torque), you gear down (small drives large).", "True",
      "Gearing down (small driving large) increases force at the cost of speed.", "ERR_TECH_G8MSA3_GEARDOWN", 3),
    CLOZE("When a small gear drives a big one, speed goes down and force goes ____.",
      ["up", "down", "away", "to zero"], "up",
      "Small-drives-large: lower speed, higher force.", "ERR_TECH_G8MSA3_UPWORD", 2),
    MC("The 'velocity ratio' of a gear pair compares their…",
      ["rotational speeds", "colours", "weights", "prices"], "rotational speeds",
      "Velocity ratio compares the speeds of the driver and driven gears.", "ERR_TECH_G8MSA3_VR", 2),
    MC("Why does a heavy truck use low gears to pull away?",
      ["Low gears give more turning force to move the load", "Low gears use no fuel", "Low gears are faster", "Low gears are quieter only"], "Low gears give more turning force to move the load",
      "Low gears multiply force to get a heavy load moving.", "ERR_TECH_G8MSA3_TRUCK", 3),
    TF("Bevel gears can also change speed and force when they are different sizes.", "True",
      "Unequal bevel gears change speed/force as well as turning the axis 90°.", "ERR_TECH_G8MSA3_BEVEL", 3),
    CLOZE("A gear ratio of 4:1 multiplies the turning force about ____ times.",
      ["4", "1", "2", "8"], "4",
      "A 4:1 reduction multiplies force roughly four times (while cutting speed to a quarter).", "ERR_TECH_G8MSA3_FOUR", 3),
    MC("To make an output spin FASTER than the input, you should…",
      ["let a large gear drive a small gear", "let a small gear drive a large gear", "use equal gears", "remove the gears"], "let a large gear drive a small gear",
      "Large-drives-small increases output speed (gearing up).", "ERR_TECH_G8MSA3_FASTER", 2),
    {
      question: "Sort each gear set-up by its effect on the output.",
      input_type: "sort-buckets",
      buckets: [{ id: "force", label: "More force, less speed" }, { id: "speed", label: "More speed, less force" }],
      items: [
        { id: "i1", text: "Small gear drives large gear", correct_bucket: "force" },
        { id: "i2", text: "Large gear drives small gear", correct_bucket: "speed" },
        { id: "i3", text: "10-tooth drives 40-tooth", correct_bucket: "force" },
        { id: "i4", text: "40-tooth drives 10-tooth", correct_bucket: "speed" },
      ],
      expected: "Small-drives-large gives more force, less speed; large-drives-small gives more speed, less force.",
      pass_threshold: 0.75,
      memo: "Gear down (small→large) = more force; gear up (large→small) = more speed.", error_signals: ["ERR_TECH_G8MSA3_SORT"], difficulty: 3,
    },
    MC("A driver of 15 teeth and a driven of 45 teeth give a ratio of…",
      ["3:1", "1:3", "45:15 only", "2:1"], "3:1",
      "45 ÷ 15 = 3, so the ratio is 3:1.", "ERR_TECH_G8MSA3_1545", 3),
    TF("Changing gear sizes lets a designer choose between speed and force.", "True",
      "Selecting gear sizes lets the designer trade speed for force as needed.", "ERR_TECH_G8MSA3_CHOOSE", 2),
    MC("If two gears are the SAME size, the output has…",
      ["the same speed and force as the input (just reversed direction)", "double speed", "double force", "no movement"], "the same speed and force as the input (just reversed direction)",
      "Equal gears keep speed and force the same; only the direction reverses.", "ERR_TECH_G8MSA3_SAME", 2),
    CLOZE("Gearing 'down' trades speed for more ____.",
      ["force", "colour", "weight", "noise"], "force",
      "Gearing down sacrifices speed to gain force.", "ERR_TECH_G8MSA3_FORCEWORD", 2),
    MC("A clock's hands need a gear system mainly to…",
      ["change the speed of rotation precisely", "make force", "make light", "store energy"], "change the speed of rotation precisely",
      "Clock gears reduce speed precisely so hands move at the right rates.", "ERR_TECH_G8MSA3_CLOCK", 3),
    TF("The output force of a gear train rises when the velocity (speed) ratio reduces the speed.", "True",
      "Reducing speed through gears raises the output force — the trade-off works both ways.", "ERR_TECH_G8MSA3_TRADE2", 3),
  ],

  // MS.A4 · Cams & cranks
  "TECH.G8.MS.A4": [
    MC("What does a CAM do?",
      ["Changes rotary motion into up-and-down (reciprocating) motion", "Stores electricity", "Makes a magnet", "Cools water"], "Changes rotary motion into up-and-down (reciprocating) motion",
      "A cam converts rotary motion into reciprocating (up-and-down) motion of a follower.", "ERR_TECH_G8MSA4_CAM", 2),
    MC("The part that rests on a cam and moves up and down is the…",
      ["follower", "axle", "idler", "tie"], "follower",
      "The follower sits on the cam and is pushed up and down as the cam turns.", "ERR_TECH_G8MSA4_FOLLOWER", 2),
    MC("A CRANK changes…",
      ["rotary motion into reciprocating motion (and back)", "light into sound", "heat into cold", "nothing"], "rotary motion into reciprocating motion (and back)",
      "A crank converts between rotary and reciprocating motion.", "ERR_TECH_G8MSA4_CRANK", 2),
    MC("Which is an example of a crank?",
      ["A bicycle pedal arm", "A door handle wheel", "A magnet", "A battery"], "A bicycle pedal arm",
      "A bicycle pedal arm is a crank turning leg push into wheel rotation.", "ERR_TECH_G8MSA4_PEDAL", 2),
    TF("A cam shaped like a snail (snail cam) gives a smooth rise and a sudden drop.", "True",
      "A snail cam rises smoothly then drops sharply as it turns.", "ERR_TECH_G8MSA4_SNAIL", 3),
    MC("An eccentric wheel (a circle turning off-centre) used as a cam gives…",
      ["a smooth, even up-and-down motion", "a sudden stop", "no motion", "rotation only"], "a smooth, even up-and-down motion",
      "An eccentric (off-centre) wheel gives a smooth, regular reciprocating motion.", "ERR_TECH_G8MSA4_ECCENTRIC", 3),
    CLOZE("A cam turns rotary motion into ____ motion.",
      ["reciprocating", "electrical", "magnetic", "circular"], "reciprocating",
      "A cam produces reciprocating (back-and-forth/up-and-down) motion.", "ERR_TECH_G8MSA4_RECIPWORD", 2),
    MC("Reciprocating motion means movement that is…",
      ["back and forth (or up and down) repeatedly", "round and round", "in one direction forever", "still"], "back and forth (or up and down) repeatedly",
      "Reciprocating motion goes back and forth (or up and down) repeatedly.", "ERR_TECH_G8MSA4_RECIPDEF", 1),
    TF("Cams are used in engines to open and close valves.", "True",
      "Engine camshafts use cams to push the valves open and closed.", "ERR_TECH_G8MSA4_ENGINE", 2),
    CLOZE("The part that follows the shape of a cam is called the ____.",
      ["follower", "driver", "idler", "rafter"], "follower",
      "The follower rides on the cam's edge and moves up and down.", "ERR_TECH_G8MSA4_FOLLOWERWORD", 2),
    MC("Both cams and cranks are used to…",
      ["change the type of motion in a machine", "store electricity", "make light", "cool things"], "change the type of motion in a machine",
      "Cams and cranks both change the type of motion (rotary↔reciprocating).", "ERR_TECH_G8MSA4_BOTH", 2),
    MC("A hand drill turned by a handle uses a crank to…",
      ["turn the handle's motion into rotation of the bit", "store energy", "make heat", "make a magnet"], "turn the handle's motion into rotation of the bit",
      "The crank handle converts hand movement into rotation of the drill bit.", "ERR_TECH_G8MSA4_DRILL", 2),
    TF("A crank is an adaptation of a second-class lever.", "True",
      "CAPS describes the crank as an adapted second-class lever.", "ERR_TECH_G8MSA4_LEVER", 2),
    {
      question: "Sort each mechanism by what it does.",
      input_type: "sort-buckets",
      buckets: [{ id: "cam", label: "Cam (rotary → up/down)" }, { id: "crank", label: "Crank (rotary ↔ back/forth)" }],
      items: [
        { id: "i1", text: "Engine valve lifter", correct_bucket: "cam" },
        { id: "i2", text: "Bicycle pedal arm", correct_bucket: "crank" },
        { id: "i3", text: "Snail cam and follower", correct_bucket: "cam" },
        { id: "i4", text: "Hand-drill turning handle", correct_bucket: "crank" },
      ],
      expected: "Valve lifters and snail cams are cams; pedal arms and drill handles are cranks.",
      pass_threshold: 0.75,
      memo: "Cam: rotary → reciprocating with a follower. Crank: rotary ↔ reciprocating via an arm.", error_signals: ["ERR_TECH_G8MSA4_SORT"], difficulty: 3,
    },
    MC("As a cam rotates once, the follower…",
      ["completes one full up-and-down cycle", "spins around", "stays still", "disappears"], "completes one full up-and-down cycle",
      "Each full turn of the cam moves the follower through one rise-and-fall cycle.", "ERR_TECH_G8MSA4_CYCLE", 3),
    TF("Compared with an eccentric wheel, a snail cam gives a more sudden drop.", "True",
      "A snail cam rises gradually then drops suddenly; an eccentric gives an even motion.", "ERR_TECH_G8MSA4_COMPARE", 3),
    MC("Which everyday machine uses a crank to turn rotary motion into reciprocating motion?",
      ["A sewing machine needle drive", "A simple magnet", "A torch bulb", "A glass jar"], "A sewing machine needle drive",
      "A sewing machine uses a crank to drive the needle up and down.", "ERR_TECH_G8MSA4_SEWING", 3),
    CLOZE("An off-centre circular cam is called an ____ wheel.",
      ["eccentric", "even", "empty", "electric"], "eccentric",
      "An eccentric wheel is a circle mounted off-centre, used as a smooth cam.", "ERR_TECH_G8MSA4_ECCWORD", 3),
    MC("Cams and cranks are examples of mechanisms that…",
      ["change the direction or type of movement", "store data", "make electricity", "filter water"], "change the direction or type of movement",
      "These mechanisms change the type/direction of motion in a machine.", "ERR_TECH_G8MSA4_CHANGE", 1),
    TF("A follower can be lifted by a cam and pulled back down by gravity or a spring.", "True",
      "The cam lifts the follower; gravity or a spring returns it as the cam turns.", "ERR_TECH_G8MSA4_SPRING", 2),
  ],

  // MS.A5 · Mechanical advantage calculations
  "TECH.G8.MS.A5": [
    MC("Mechanical advantage (MA) is calculated as…",
      ["load ÷ effort", "effort ÷ load", "load + effort", "load × effort"], "load ÷ effort",
      "MA = load ÷ effort. An MA above 1 means a small effort moves a bigger load.", "ERR_TECH_G8MSA5_FORMULA", 1),
    MC("A lever lifts a 100 N load with an effort of 25 N. The MA is…",
      ["4", "2", "0.25", "125"], "4",
      "MA = load ÷ effort = 100 ÷ 25 = 4.", "ERR_TECH_G8MSA5_CALC4", 2),
    MC("A lever lifts a 60 N load with a 20 N effort. The MA is…",
      ["3", "40", "1200", "0.33"], "3",
      "MA = 60 ÷ 20 = 3.", "ERR_TECH_G8MSA5_CALC3", 2),
    TF("An MA greater than 1 means the machine multiplies your effort.", "True",
      "MA > 1 means the load is bigger than the effort — the machine multiplies force.", "ERR_TECH_G8MSA5_GT1", 2),
    MC("If MA is less than 1, the machine…",
      ["needs more effort than the load (but may gain speed/distance)", "is broken", "needs no effort", "is always best"], "needs more effort than the load (but may gain speed/distance)",
      "MA < 1 means effort exceeds load — you trade force for speed or distance (like a third-class lever).", "ERR_TECH_G8MSA5_LT1", 3),
    MC("For gears, MA can be found from the ratio of…",
      ["driven teeth ÷ driver teeth", "colour ÷ weight", "speed ÷ price", "length × width"], "driven teeth ÷ driver teeth",
      "Gear MA ≈ driven teeth ÷ driver teeth (a larger driven gear gives more force).", "ERR_TECH_G8MSA5_GEARMA", 2),
    MC("A driver gear of 10 teeth turns a driven gear of 40 teeth. The force MA is about…",
      ["4", "0.25", "400", "30"], "4",
      "40 ÷ 10 = 4, so the force is multiplied about 4 times.", "ERR_TECH_G8MSA5_GEAR4", 3),
    TF("In Grade 8 you calculate MA using ratios, not by 'taking moments'.", "True",
      "CAPS Grade 8 uses simple ratios for MA, not the moments method.", "ERR_TECH_G8MSA5_NOMOMENTS", 2),
    CLOZE("Mechanical advantage = load ÷ ____.",
      ["effort", "speed", "colour", "weight"], "effort",
      "MA = load ÷ effort.", "ERR_TECH_G8MSA5_DIVEFFORT", 1),
    MC("A wheelbarrow lets a 30 N effort lift a 120 N load. The MA is…",
      ["4", "90", "150", "0.25"], "4",
      "MA = 120 ÷ 30 = 4.", "ERR_TECH_G8MSA5_BARROW", 2),
    MC("A lever has an effort arm of 80 cm and a load arm of 20 cm. The MA is…",
      ["4 (80 ÷ 20)", "0.25", "60", "1600"], "4 (80 ÷ 20)",
      "MA for a lever = effort arm ÷ load arm = 80 ÷ 20 = 4.", "ERR_TECH_G8MSA5_ARMS", 3),
    TF("A longer effort arm gives a bigger mechanical advantage on a lever.", "True",
      "Increasing the effort arm relative to the load arm increases MA.", "ERR_TECH_G8MSA5_LONGARM", 2),
    MC("If the load and effort are equal, the MA is…",
      ["1", "0", "2", "100"], "1",
      "Equal load and effort give MA = 1 — no force multiplication.", "ERR_TECH_G8MSA5_MA1", 2),
    CLOZE("For gears, MA is about the driven teeth divided by the ____ teeth.",
      ["driver", "idler", "biggest", "smallest"], "driver",
      "Gear MA ≈ driven teeth ÷ driver teeth.", "ERR_TECH_G8MSA5_DRIVERWORD", 2),
    {
      question: "Sort each result by whether the machine multiplies force.",
      input_type: "sort-buckets",
      buckets: [{ id: "mult", label: "Multiplies force (MA > 1)" }, { id: "not", label: "Does not multiply force (MA ≤ 1)" }],
      items: [
        { id: "i1", text: "Load 100 N, effort 20 N", correct_bucket: "mult" },
        { id: "i2", text: "Load 50 N, effort 50 N", correct_bucket: "not" },
        { id: "i3", text: "Load 90 N, effort 30 N", correct_bucket: "mult" },
        { id: "i4", text: "Load 10 N, effort 40 N", correct_bucket: "not" },
      ],
      expected: "MA = load÷effort: 100/20=5 and 90/30=3 multiply force; 50/50=1 and 10/40=0.25 do not.",
      pass_threshold: 0.75,
      memo: "Work out load ÷ effort. Above 1 multiplies force; 1 or below does not.", error_signals: ["ERR_TECH_G8MSA5_SORT"], difficulty: 3,
    },
    MC("A machine with MA = 5 lifts a 200 N load. The effort needed is…",
      ["40 N", "1000 N", "205 N", "5 N"], "40 N",
      "Effort = load ÷ MA = 200 ÷ 5 = 40 N.", "ERR_TECH_G8MSA5_EFFORTCALC", 3),
    TF("MA has no units because it is a ratio of two forces.", "True",
      "MA = force ÷ force, so the units cancel and MA is just a number.", "ERR_TECH_G8MSA5_NOUNITS", 3),
    MC("Gearing up for speed (large drives small) usually gives an MA that is…",
      ["less than 1", "greater than 1", "exactly 5", "exactly 10"], "less than 1",
      "Gearing up for speed reduces force, giving an MA below 1.", "ERR_TECH_G8MSA5_GEARUP", 3),
    CLOZE("If MA is 3 and the effort is 20 N, the load lifted is ____ N.",
      ["60", "23", "17", "6.7"], "60",
      "Load = MA × effort = 3 × 20 = 60 N.", "ERR_TECH_G8MSA5_LOADCALC", 3),
    MC("Why calculate MA before building a machine?",
      ["To check it can move the load with the effort available", "To choose a colour", "To waste time", "There is no reason"], "To check it can move the load with the effort available",
      "Calculating MA confirms the machine can do the job with the available effort.", "ERR_TECH_G8MSA5_WHY", 2),
  ],

  // MS.A6 · Systems diagrams
  "TECH.G8.MS.A6": [
    MC("A systems diagram breaks a system into three parts:",
      ["input, process and output", "red, blue and green", "start, stop and pause", "top, middle and bottom"], "input, process and output",
      "A system is modelled as input → process → output.", "ERR_TECH_G8MSA6_IPO", 1),
    MC("In a system, the INPUT is…",
      ["what goes in to start the system", "the final result", "the middle action", "the colour"], "what goes in to start the system",
      "The input is what enters the system (energy, material, a signal).", "ERR_TECH_G8MSA6_INPUT", 1),
    MC("In a system, the OUTPUT is…",
      ["the result that comes out", "what goes in", "the process", "the casing"], "the result that comes out",
      "The output is the result the system produces.", "ERR_TECH_G8MSA6_OUTPUT", 1),
    MC("In a system, the PROCESS is…",
      ["what happens to change the input into the output", "what goes in", "what comes out", "the colour"], "what happens to change the input into the output",
      "The process is the action that turns the input into the output.", "ERR_TECH_G8MSA6_PROCESS", 1),
    TF("Drawing a systems diagram helps you understand how a machine works.", "True",
      "Systems diagrams break a machine into clear input-process-output parts to understand it.", "ERR_TECH_G8MSA6_UNDERSTAND", 1),
    CLOZE("A system is modelled as input → process → ____.",
      ["output", "colour", "weight", "price"], "output",
      "The third part of a system is the output.", "ERR_TECH_G8MSA6_OUTWORD", 1),
    MC("For a bicycle, the INPUT is best described as…",
      ["the rider pedalling", "the wheel turning", "the gear train", "the speed reached"], "the rider pedalling",
      "The rider's pedalling is the input that drives the bicycle system.", "ERR_TECH_G8MSA6_BIKEINPUT", 2),
    MC("For a bicycle, the OUTPUT is best described as…",
      ["the rear wheel turning to move the bike", "the rider's legs", "the chain", "the brakes only"], "the rear wheel turning to move the bike",
      "The output is the rear wheel turning to move the bicycle.", "ERR_TECH_G8MSA6_BIKEOUT", 2),
    TF("In a bicycle, the chain and gears are part of the PROCESS that transfers motion.", "True",
      "The chain and gears process the input (pedalling) into the output (wheel turning).", "ERR_TECH_G8MSA6_BIKEPROCESS", 2),
    MC("Analysing a machine by breaking it into input-process-output is called…",
      ["systems analysis", "painting", "guessing", "weighing"], "systems analysis",
      "Breaking a machine into input-process-output is systems analysis.", "ERR_TECH_G8MSA6_ANALYSIS", 2),
    CLOZE("The action that turns the input into the output is the ____.",
      ["process", "input", "output", "colour"], "process",
      "The process is the middle step that converts input to output.", "ERR_TECH_G8MSA6_PROCWORD", 1),
    MC("For an electric fan: input = electricity, process = motor spins, output =…",
      ["moving air (a breeze)", "the plug", "the wall", "the switch"], "moving air (a breeze)",
      "The fan's output is moving air; electricity is the input and the spinning motor is the process.", "ERR_TECH_G8MSA6_FAN", 2),
    {
      question: "Sort each part of an electric kettle into input, process or output.",
      input_type: "sort-buckets",
      buckets: [{ id: "in", label: "Input" }, { id: "proc", label: "Process" }, { id: "out", label: "Output" }],
      items: [
        { id: "i1", text: "Electricity supplied", correct_bucket: "in" },
        { id: "i2", text: "Heating element warms the water", correct_bucket: "proc" },
        { id: "i3", text: "Hot/boiled water", correct_bucket: "out" },
      ],
      expected: "Electricity is the input; the heating element is the process; hot water is the output.",
      pass_threshold: 0.66,
      memo: "Input = electricity; process = the element heating; output = boiled water.", error_signals: ["ERR_TECH_G8MSA6_SORT"], difficulty: 2,
    },
    {
      question: "Order the flow through a simple system.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Input enters the system" },
        { id: "b", text: "Process changes the input" },
        { id: "c", text: "Output comes out" },
      ],
      expected_order: ["a", "b", "c"],
      memo: "A system flows: input → process → output.",
      error_signals: ["ERR_TECH_G8MSA6_SEQUENCE"], difficulty: 1,
    },
    MC("A gear train with a 4:1 reduction would be drawn in a systems diagram with the process being…",
      ["the gears reducing speed and increasing force", "the colour of the gears", "the price", "the noise only"], "the gears reducing speed and increasing force",
      "The process box describes what the gears do: reduce speed, increase force.", "ERR_TECH_G8MSA6_GEARPROC", 3),
    TF("A systems diagram can describe both mechanical and electrical machines.", "True",
      "Input-process-output applies to mechanical, electrical and many other systems.", "ERR_TECH_G8MSA6_GENERAL", 2),
    MC("Why is breaking a machine into a system useful for designers?",
      ["It makes a complex machine easier to plan and fix", "It changes the colour", "It adds weight", "It wastes time"], "It makes a complex machine easier to plan and fix",
      "Modelling a machine as a system clarifies how to plan, build and fix it.", "ERR_TECH_G8MSA6_WHY", 2),
    CLOZE("For a torch: input = battery energy, process = bulb glows, output = ____.",
      ["light", "sound", "heat only", "water"], "light",
      "A torch's output is light; the battery is the input and the glowing bulb is the process.", "ERR_TECH_G8MSA6_TORCH", 2),
    MC("Which is the correct order in a systems diagram?",
      ["Input, then process, then output", "Output, then input, then process", "Process, then output, then input", "All at once"], "Input, then process, then output",
      "Systems flow input → process → output, in that order.", "ERR_TECH_G8MSA6_ORDER", 1),
    TF("The output of one system can become the input of another system.", "True",
      "Systems can be chained — one system's output feeds the next system's input.", "ERR_TECH_G8MSA6_CHAIN", 3),
  ],
};

export default G8;
