// ─── Technology SP — Grade 9 authored pools (part 2: ES · PR) ────────────────
// Electrical/Electronic Systems (Term 3) · Processing (Term 4).
// Refs auto-assigned by build-technology-sp.mjs. Tap-only; no free text.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9B = {
  // ════════════ ELECTRICAL / ELECTRONIC SYSTEMS (Term 3) ══════════════════════
  // ES.A1 · Ohm's law (quantitative)
  "TECH.G9.ES.A1": [
    MC("Ohm's law is written as…",
      ["V = I × R", "V = I + R", "V = I − R", "V = I ÷ R only"], "V = I × R",
      "Ohm's law: voltage = current × resistance (V = IR).", "ERR_TECH_G9ESA1_FORMULA", 1),
    MC("In V = IR, what does V stand for?",
      ["Voltage (potential difference) in volts", "Volume", "Velocity", "Value"], "Voltage (potential difference) in volts",
      "V is the voltage (potential difference), measured in volts.", "ERR_TECH_G9ESA1_V", 1),
    MC("In V = IR, what does I stand for?",
      ["Current in amperes", "Inches", "Intensity of light", "Input"], "Current in amperes",
      "I is the current, measured in amperes (A).", "ERR_TECH_G9ESA1_I", 1),
    MC("In V = IR, what does R stand for?",
      ["Resistance in ohms", "Radius", "Rate", "Resistor count"], "Resistance in ohms",
      "R is the resistance, measured in ohms (Ω).", "ERR_TECH_G9ESA1_R", 1),
    MC("A current of 2 A flows through a 5 Ω resistor. The voltage is…",
      ["10 V", "2.5 V", "7 V", "3 V"], "10 V",
      "V = IR = 2 × 5 = 10 V.", "ERR_TECH_G9ESA1_CALCV", 2),
    MC("A 12 V supply drives a current through a 4 Ω resistor. The current is…",
      ["3 A", "48 A", "8 A", "16 A"], "3 A",
      "I = V ÷ R = 12 ÷ 4 = 3 A.", "ERR_TECH_G9ESA1_CALCI", 2),
    MC("A 6 V supply pushes 2 A through a resistor. Its resistance is…",
      ["3 Ω", "12 Ω", "8 Ω", "4 Ω"], "3 Ω",
      "R = V ÷ I = 6 ÷ 2 = 3 Ω.", "ERR_TECH_G9ESA1_CALCR", 2),
    TF("To find current, rearrange Ohm's law to I = V ÷ R.", "True",
      "From V = IR, current I = V ÷ R.", "ERR_TECH_G9ESA1_REARRI", 2),
    CLOZE("To find resistance from Ohm's law, use R = V ÷ ____.",
      ["I", "R", "V", "P"], "I",
      "R = V ÷ I.", "ERR_TECH_G9ESA1_REARRR", 2),
    MC("If voltage doubles and resistance stays the same, the current…",
      ["doubles", "halves", "stays the same", "becomes zero"], "doubles",
      "With constant R, current is proportional to voltage, so doubling V doubles I.", "ERR_TECH_G9ESA1_DOUBLE", 3),
    MC("A 9 V battery and a 3 Ω resistor give a current of…",
      ["3 A", "27 A", "12 A", "6 A"], "3 A",
      "I = V ÷ R = 9 ÷ 3 = 3 A.", "ERR_TECH_G9ESA1_93", 2),
    TF("Resistance is measured in ohms, shown by the symbol Ω.", "True",
      "Resistance uses the ohm (Ω) as its unit.", "ERR_TECH_G9ESA1_OHMUNIT", 1),
    MC("A resistor of 10 Ω carries 0.5 A. The voltage across it is…",
      ["5 V", "20 V", "10.5 V", "0.05 V"], "5 V",
      "V = IR = 0.5 × 10 = 5 V.", "ERR_TECH_G9ESA1_HALFAMP", 3),
    CLOZE("Current is measured in ____.",
      ["amperes", "volts", "ohms", "watts"], "amperes",
      "Current is measured in amperes (A).", "ERR_TECH_G9ESA1_AMPS", 1),
    {
      question: "Sort each quantity with its correct unit.",
      input_type: "sort-buckets",
      buckets: [{ id: "v", label: "Volts (V)" }, { id: "a", label: "Amperes (A)" }, { id: "o", label: "Ohms (Ω)" }],
      items: [
        { id: "i1", text: "Voltage / potential difference", correct_bucket: "v" },
        { id: "i2", text: "Current", correct_bucket: "a" },
        { id: "i3", text: "Resistance", correct_bucket: "o" },
      ],
      expected: "Voltage is in volts, current in amperes, resistance in ohms.",
      pass_threshold: 0.66,
      memo: "V = volts (voltage); A = amperes (current); Ω = ohms (resistance).", error_signals: ["ERR_TECH_G9ESA1_SORT"], difficulty: 2,
    },
    MC("Testing Ohm's law, as you add more cells (more voltage) to a fixed resistor, the current…",
      ["increases", "decreases", "stays the same", "stops"], "increases",
      "More voltage across the same resistance gives more current.", "ERR_TECH_G9ESA1_MORECELLS", 2),
    TF("If you plot voltage against current for a fixed resistor, you get a straight line.", "True",
      "For a fixed resistor, V is proportional to I — a straight-line graph.", "ERR_TECH_G9ESA1_GRAPH", 3),
    MC("A device that measures current is an…",
      ["ammeter", "voltmeter", "ohmmeter only", "thermometer"], "ammeter",
      "An ammeter measures current (amperes).", "ERR_TECH_G9ESA1_AMMETER", 2),
    MC("A device that measures voltage is a…",
      ["voltmeter", "ammeter", "ruler", "scale"], "voltmeter",
      "A voltmeter measures voltage (potential difference).", "ERR_TECH_G9ESA1_VOLTMETER", 2),
    CLOZE("Ohm's law links voltage, current and ____.",
      ["resistance", "colour", "weight", "length"], "resistance",
      "Ohm's law links V, I and R.", "ERR_TECH_G9ESA1_LINK", 1),
  ],

  // ES.A2 · Resistor colour codes
  "TECH.G9.ES.A2": [
    MC("Why do many resistors use coloured bands?",
      ["The bands show the resistor's value in ohms", "For decoration", "To show the price", "To show the weight"], "The bands show the resistor's value in ohms",
      "Colour bands code the resistor's resistance value (and tolerance).", "ERR_TECH_G9ESA2_WHY", 1),
    MC("On a colour-coded resistor, the LAST band usually shows the…",
      ["tolerance (accuracy)", "first digit", "voltage", "current"], "tolerance (accuracy)",
      "The final band gives the tolerance — how accurate the value is.", "ERR_TECH_G9ESA2_TOLERANCE", 2),
    MC("'Tolerance' of a resistor means…",
      ["how much the real value may differ from the marked value", "how hot it gets", "its colour", "its weight"], "how much the real value may differ from the marked value",
      "Tolerance is the allowed percentage difference from the stated value.", "ERR_TECH_G9ESA2_TOLDEF", 2),
    TF("Low-value resistors sometimes have their value printed in numbers instead of colour bands.", "True",
      "Some resistors print the value as numbers rather than using colour bands.", "ERR_TECH_G9ESA2_NUMBERS", 1),
    MC("The first bands on a resistor give the…",
      ["digits of the value", "tolerance only", "voltage", "temperature"], "digits of the value",
      "The first bands give the significant digits of the resistance.", "ERR_TECH_G9ESA2_DIGITS", 2),
    TF("Resistance is measured in ohms (Ω).", "True",
      "Resistor values are given in ohms.", "ERR_TECH_G9ESA2_OHMS", 1),
    CLOZE("The accuracy band on a resistor shows its ____.",
      ["tolerance", "voltage", "current", "weight"], "tolerance",
      "The tolerance band shows how accurate the value is.", "ERR_TECH_G9ESA2_TOLWORD", 2),
    MC("A resistor with a ±5% tolerance marked 100 Ω could really be…",
      ["between 95 Ω and 105 Ω", "exactly 100 Ω only", "between 0 and 200 Ω", "anything at all"], "between 95 Ω and 105 Ω",
      "±5% of 100 Ω is ±5 Ω, so the real value is 95–105 Ω.", "ERR_TECH_G9ESA2_RANGE", 3),
    MC("Why does a resistor have a tolerance at all?",
      ["Manufacturing is never perfectly exact", "To raise the price", "To add colour", "There is no reason"], "Manufacturing is never perfectly exact",
      "Tolerance allows for small, unavoidable manufacturing differences.", "ERR_TECH_G9ESA2_WHYTOL", 2),
    TF("Colour codes let you read a resistor's value without a meter.", "True",
      "Reading the bands tells you the value without needing a meter.", "ERR_TECH_G9ESA2_NOMETER", 1),
    MC("A resistor limits the ____ in a circuit.",
      ["current", "colour", "weight", "length"], "current",
      "A resistor opposes and limits the current.", "ERR_TECH_G9ESA2_LIMIT", 1),
    CLOZE("Higher-value resistors are coded using coloured ____.",
      ["bands", "wires", "screws", "magnets"], "bands",
      "Colour bands code higher-value resistors.", "ERR_TECH_G9ESA2_BANDS", 1),
    MC("Putting a resistor in series with an LED is done to…",
      ["limit the current so the LED is not damaged", "make it brighter forever", "store energy", "change its colour"], "limit the current so the LED is not damaged",
      "A series resistor limits current to protect the LED.", "ERR_TECH_G9ESA2_LEDRESISTOR", 3),
    {
      question: "Sort each statement as TRUE or FALSE about resistor colour codes.",
      input_type: "sort-buckets",
      buckets: [{ id: "true", label: "True" }, { id: "false", label: "False" }],
      items: [
        { id: "i1", text: "Bands show the value in ohms", correct_bucket: "true" },
        { id: "i2", text: "The last band shows tolerance", correct_bucket: "true" },
        { id: "i3", text: "The bands show the price", correct_bucket: "false" },
        { id: "i4", text: "Colour codes show the resistor's weight", correct_bucket: "false" },
      ],
      expected: "Bands show value and tolerance; they do not show price or weight.",
      pass_threshold: 0.75,
      memo: "Colour bands code resistance value and tolerance — not price or weight.", error_signals: ["ERR_TECH_G9ESA2_SORT"], difficulty: 2,
    },
    MC("A tighter tolerance (e.g. ±1%) means the resistor is…",
      ["more accurate", "less accurate", "more colourful", "heavier"], "more accurate",
      "A smaller tolerance percentage means a more accurate value.", "ERR_TECH_G9ESA2_TIGHTER", 3),
    TF("Reading colour codes is a skill that helps you pick the right resistor for a circuit.", "True",
      "Knowing colour codes lets you choose the correct resistor value.", "ERR_TECH_G9ESA2_SKILL", 1),
    MC("The unit symbol Ω stands for…",
      ["ohms", "volts", "amperes", "watts"], "ohms",
      "Ω is the symbol for ohms, the unit of resistance.", "ERR_TECH_G9ESA2_OMEGA", 1),
    CLOZE("Some low-value resistors print the value in ____ instead of colour bands.",
      ["numbers", "pictures", "songs", "smells"], "numbers",
      "Low-value resistors sometimes print numbers instead of bands.", "ERR_TECH_G9ESA2_NUMWORD", 1),
    MC("If a resistor's value is too high for a circuit, the current will be…",
      ["too low", "too high", "unchanged", "negative"], "too low",
      "Higher resistance reduces current, so too high a value gives too little current.", "ERR_TECH_G9ESA2_TOOHIGH", 3),
    TF("Choosing the correct resistor value protects components and makes a circuit work properly.", "True",
      "The right resistor sets the correct current, protecting parts and making the circuit work.", "ERR_TECH_G9ESA2_CORRECT", 2),
  ],

  // ES.A3 · Electronic components
  "TECH.G9.ES.A3": [
    MC("A DIODE allows current to flow…",
      ["in one direction only", "in both directions", "never", "only sideways"], "in one direction only",
      "A diode lets current flow one way only.", "ERR_TECH_G9ESA3_DIODE", 1),
    MC("An LED is a diode that also…",
      ["gives off light", "makes sound", "stores water", "spins"], "gives off light",
      "An LED (Light Emitting Diode) gives off light and conducts one way only.", "ERR_TECH_G9ESA3_LED", 1),
    MC("An LED is often used as…",
      ["an indicator that a circuit is ON", "a heavy weight", "a magnet", "a spring"], "an indicator that a circuit is ON",
      "LEDs are commonly used as ON indicators.", "ERR_TECH_G9ESA3_INDICATOR", 1),
    MC("A TRANSISTOR can act as…",
      ["a switch or an amplifier", "a magnet", "a battery", "a gear"], "a switch or an amplifier",
      "A transistor can switch a circuit or amplify a small current into a larger one.", "ERR_TECH_G9ESA3_TRANSISTOR", 2),
    MC("A transistor can amplify a small current from a sensor into a…",
      ["larger current", "smaller voltage only", "magnetic field only", "sound only"], "larger current",
      "A transistor amplifies a small input current into a larger output current.", "ERR_TECH_G9ESA3_AMPLIFY", 2),
    MC("A CAPACITOR is a component that can…",
      ["store and release electrical energy", "give off light", "make a magnet", "cut metal"], "store and release electrical energy",
      "A capacitor stores electrical energy and releases it later.", "ERR_TECH_G9ESA3_CAPACITOR", 1),
    TF("At this level only the npn-type transistor is used.", "True",
      "CAPS Grade 9 uses the npn-type transistor.", "ERR_TECH_G9ESA3_NPN", 2),
    CLOZE("A component that lets current flow one way only is a ____.",
      ["diode", "capacitor", "resistor", "switch"], "diode",
      "A diode allows current in one direction only.", "ERR_TECH_G9ESA3_DIODEWORD", 1),
    TF("An LED must usually be connected the right way round to light up.", "True",
      "Because an LED is a diode, it only works when connected the correct way round.", "ERR_TECH_G9ESA3_POLARITY", 2),
    CLOZE("A component that stores and releases charge is a ____.",
      ["capacitor", "diode", "resistor", "lamp"], "capacitor",
      "A capacitor stores and releases electrical charge.", "ERR_TECH_G9ESA3_CAPWORD", 1),
    MC("A transistor used as a switch is turned on by…",
      ["a small current to its base", "a magnet", "sunlight only", "heat only"], "a small current to its base",
      "A small base current switches the transistor on, allowing a larger current to flow.", "ERR_TECH_G9ESA3_BASE", 3),
    MC("Which component would you use to make a small 'power on' light?",
      ["An LED", "A capacitor", "A motor", "A resistor only"], "An LED",
      "An LED is ideal as a small indicator light.", "ERR_TECH_G9ESA3_POWERLIGHT", 2),
    TF("A diode connected the wrong way round will block the current.", "True",
      "A reverse-connected diode blocks current — it only conducts one way.", "ERR_TECH_G9ESA3_REVERSE", 2),
    {
      question: "Match each component to what it does.",
      input_type: "sort-buckets",
      buckets: [{ id: "oneway", label: "Current one way" }, { id: "switchamp", label: "Switch / amplify" }, { id: "store", label: "Store energy" }],
      items: [
        { id: "i1", text: "Diode", correct_bucket: "oneway" },
        { id: "i2", text: "LED", correct_bucket: "oneway" },
        { id: "i3", text: "Transistor", correct_bucket: "switchamp" },
        { id: "i4", text: "Capacitor", correct_bucket: "store" },
      ],
      expected: "Diodes and LEDs pass current one way; a transistor switches/amplifies; a capacitor stores energy.",
      pass_threshold: 0.75,
      memo: "Diode/LED = one-way current; transistor = switch or amplifier; capacitor = stores energy.", error_signals: ["ERR_TECH_G9ESA3_SORT"], difficulty: 3,
    },
    MC("Why put a resistor in series with an LED?",
      ["To limit the current and protect the LED", "To make it a magnet", "To store energy", "To cool it"], "To limit the current and protect the LED",
      "A series resistor limits current so the LED is not damaged.", "ERR_TECH_G9ESA3_RESISTOR", 2),
    TF("A capacitor can keep a small light glowing briefly after the power is switched off.", "True",
      "A charged capacitor releases its stored energy, keeping a light on briefly.", "ERR_TECH_G9ESA3_RELEASE", 3),
    MC("Transistors are important in electronics because they can…",
      ["control larger currents using small signals", "store water", "make wind", "weigh objects"], "control larger currents using small signals",
      "Transistors let small signals control larger currents — key to electronics.", "ERR_TECH_G9ESA3_CONTROL", 2),
    CLOZE("An LED is a special diode that gives off ____.",
      ["light", "sound", "heat only", "water"], "light",
      "An LED gives off light while conducting one way.", "ERR_TECH_G9ESA3_LIGHTWORD", 1),
    MC("A burglar alarm might use a transistor to…",
      ["turn a small sensor signal into a loud alarm", "store water", "make light only", "cool the room"], "turn a small sensor signal into a loud alarm",
      "A transistor amplifies a small sensor signal to drive a loud alarm.", "ERR_TECH_G9ESA3_ALARM", 3),
    TF("Diodes, LEDs, transistors and capacitors are all electronic components.", "True",
      "These are all common electronic components used in circuits.", "ERR_TECH_G9ESA3_ALL", 1),
  ],

  // ES.A4 · Sensors
  "TECH.G9.ES.A4": [
    MC("A sensor is a component that…",
      ["responds to a change like light, heat or moisture", "makes light", "stores energy", "spins a wheel"], "responds to a change like light, heat or moisture",
      "Sensors are input devices that respond to changes in light, heat, moisture, etc.", "ERR_TECH_G9ESA4_DEF", 1),
    MC("An LDR (Light Dependent Resistor) changes its resistance with…",
      ["light", "sound", "weight", "colour of the wire"], "light",
      "An LDR's resistance changes with the amount of light falling on it.", "ERR_TECH_G9ESA4_LDR", 1),
    MC("In bright light, an LDR's resistance is…",
      ["low", "high", "infinite", "negative"], "low",
      "Bright light lowers an LDR's resistance; darkness raises it.", "ERR_TECH_G9ESA4_LDRBRIGHT", 2),
    MC("In the dark, an LDR's resistance is…",
      ["high", "low", "zero", "negative"], "high",
      "In darkness an LDR has high resistance.", "ERR_TECH_G9ESA4_LDRDARK", 2),
    MC("A thermistor changes its resistance with…",
      ["temperature", "light", "sound", "moisture"], "temperature",
      "A thermistor's resistance changes with temperature.", "ERR_TECH_G9ESA4_THERMISTOR", 1),
    TF("A negative temperature coefficient thermistor's resistance decreases as it gets hotter.", "True",
      "A −t thermistor drops in resistance as temperature rises.", "ERR_TECH_G9ESA4_NTC", 3),
    MC("A touch or moisture detector works when…",
      ["a wet finger or moisture bridges a gap to complete the circuit", "it is dry", "it is dark", "it is cold"], "a wet finger or moisture bridges a gap to complete the circuit",
      "Moisture (like a wet finger) bridges contacts to complete the circuit.", "ERR_TECH_G9ESA4_MOISTURE", 2),
    CLOZE("An ____ is a sensor whose resistance changes with light.",
      ["LDR", "LED", "NPN", "AC"], "LDR",
      "An LDR (Light Dependent Resistor) changes resistance with light.", "ERR_TECH_G9ESA4_LDRWORD", 1),
    CLOZE("A ____ is a sensor whose resistance changes with temperature.",
      ["thermistor", "diode", "capacitor", "resistor"], "thermistor",
      "A thermistor responds to temperature.", "ERR_TECH_G9ESA4_THERMWORD", 1),
    MC("A streetlight that switches on automatically at night likely uses an…",
      ["LDR", "LED only", "capacitor only", "motor"], "LDR",
      "An LDR senses darkness and switches the streetlight on.", "ERR_TECH_G9ESA4_STREETLIGHT", 2),
    MC("A fire alarm that responds to heat likely uses a…",
      ["thermistor", "LDR", "moisture detector", "magnet"], "thermistor",
      "A thermistor senses the rise in temperature for a heat alarm.", "ERR_TECH_G9ESA4_FIREALARM", 2),
    TF("Sensors are input devices that give a circuit information about its surroundings.", "True",
      "Sensors are inputs that tell the circuit about light, heat, moisture, etc.", "ERR_TECH_G9ESA4_INPUT", 1),
    MC("A rain detector that closes a window when it gets wet uses a…",
      ["moisture sensor", "LDR", "thermistor", "diode only"], "moisture sensor",
      "A moisture sensor detects rain to trigger the window action.", "ERR_TECH_G9ESA4_RAIN", 2),
    {
      question: "Match each sensor to what it detects.",
      input_type: "sort-buckets",
      buckets: [{ id: "light", label: "Light" }, { id: "heat", label: "Temperature" }, { id: "wet", label: "Moisture/touch" }],
      items: [
        { id: "i1", text: "LDR", correct_bucket: "light" },
        { id: "i2", text: "Thermistor", correct_bucket: "heat" },
        { id: "i3", text: "Moisture detector", correct_bucket: "wet" },
      ],
      expected: "LDR senses light; thermistor senses temperature; moisture detector senses wetness.",
      pass_threshold: 0.66,
      memo: "LDR ↔ light; thermistor ↔ temperature; moisture detector ↔ wetness/touch.", error_signals: ["ERR_TECH_G9ESA4_SORT"], difficulty: 2,
    },
    MC("A sensor's small signal is often boosted by a…",
      ["transistor", "magnet", "pulley", "lever"], "transistor",
      "A transistor amplifies a sensor's small signal to drive an output.", "ERR_TECH_G9ESA4_TRANSISTOR", 3),
    TF("An LDR can be used to make a light come on automatically when it gets dark.", "True",
      "As darkness raises the LDR's resistance, a circuit can switch a light on.", "ERR_TECH_G9ESA4_AUTO", 2),
    MC("A positive temperature coefficient (+t) thermistor's resistance, as it heats up,…",
      ["increases", "decreases", "stays the same", "becomes zero"], "increases",
      "A +t thermistor's resistance increases with temperature.", "ERR_TECH_G9ESA4_PTC", 3),
    CLOZE("A component bridged by a wet finger to complete a circuit is a touch/____ detector.",
      ["moisture", "light", "heat", "sound"], "moisture",
      "A moisture/touch detector is completed by moisture bridging the gap.", "ERR_TECH_G9ESA4_MOISTWORD", 2),
    MC("Sensors make devices 'automatic' because they let a circuit…",
      ["react to changes by itself", "need a person to switch it", "make light only", "store water"], "react to changes by itself",
      "Sensors let circuits respond automatically to changes in their surroundings.", "ERR_TECH_G9ESA4_AUTOMATIC", 2),
    TF("An LDR, a thermistor and a moisture detector are all input (sensor) devices.", "True",
      "All three are sensors — input devices that detect changes.", "ERR_TECH_G9ESA4_ALLINPUT", 1),
  ],

  // ES.A5 · Switches & circuit logic
  "TECH.G9.ES.A5": [
    MC("A switch in a circuit is used to…",
      ["open or close the circuit (control current)", "store energy", "give off light", "make a magnet"], "open or close the circuit (control current)",
      "A switch controls the current by opening or closing the circuit.", "ERR_TECH_G9ESA5_DEF", 1),
    MC("'SPST' stands for…",
      ["single pole, single throw", "small plastic short tube", "switch power so toggle", "single plug strong tab"], "single pole, single throw",
      "SPST = single pole, single throw — a basic on/off switch.", "ERR_TECH_G9ESA5_SPST", 2),
    MC("An SPDT switch can…",
      ["connect one input to one of two outputs", "only turn off", "store charge", "make light"], "connect one input to one of two outputs",
      "SPDT (single pole, double throw) selects between two outputs.", "ERR_TECH_G9ESA5_SPDT", 3),
    MC("Two switches in SERIES give which logic?",
      ["AND (both must be on)", "OR (either on)", "NOT", "none"], "AND (both must be on)",
      "Series switches both must be closed for current — AND logic.", "ERR_TECH_G9ESA5_SERIESAND", 2),
    MC("Two switches in PARALLEL give which logic?",
      ["OR (either on)", "AND (both on)", "NOT", "none"], "OR (either on)",
      "Parallel switches let current flow if either is closed — OR logic.", "ERR_TECH_G9ESA5_PARALLELOR", 2),
    TF("A push switch only makes contact while it is being pressed.", "True",
      "A push (momentary) switch conducts only while pressed.", "ERR_TECH_G9ESA5_PUSH", 1),
    CLOZE("Switches in series act like an ____ gate.",
      ["AND", "OR", "OFF", "NO"], "AND",
      "Series switches = AND logic (both needed).", "ERR_TECH_G9ESA5_ANDWORD", 2),
    CLOZE("Switches in parallel act like an ____ gate.",
      ["OR", "AND", "NOT", "OFF"], "OR",
      "Parallel switches = OR logic (either works).", "ERR_TECH_G9ESA5_ORWORD", 2),
    MC("'DPDT' means a switch has…",
      ["double pole, double throw", "no poles", "one throw only", "no throws"], "double pole, double throw",
      "DPDT = double pole, double throw — it switches two circuits between two positions.", "ERR_TECH_G9ESA5_DPDT", 3),
    MC("A machine that runs only when a guard is closed AND the start button is pressed uses…",
      ["AND logic (series)", "OR logic (parallel)", "no logic", "a capacitor"], "AND logic (series)",
      "Both conditions required = AND logic, done with switches in series.", "ERR_TECH_G9ESA5_SAFETY", 3),
    MC("A light that can be switched on by either of two doorways uses…",
      ["OR logic (parallel)", "AND logic (series)", "no switch", "a motor"], "OR logic (parallel)",
      "Either switch turning the light on = OR logic, done with switches in parallel.", "ERR_TECH_G9ESA5_TWODOORS", 3),
    TF("Conventional current is taken to flow from the positive to the negative terminal.", "True",
      "Conventional current flows from + to − around the circuit.", "ERR_TECH_G9ESA5_CONVENTIONAL", 2),
    CLOZE("A basic on/off switch is a single pole, single ____ (SPST).",
      ["throw", "wire", "cell", "lamp"], "throw",
      "SPST = single pole, single throw.", "ERR_TECH_G9ESA5_THROW", 2),
    {
      question: "Sort each set-up by its logic.",
      input_type: "sort-buckets",
      buckets: [{ id: "and", label: "AND" }, { id: "or", label: "OR" }],
      items: [
        { id: "i1", text: "Two switches in series", correct_bucket: "and" },
        { id: "i2", text: "Two switches in parallel", correct_bucket: "or" },
        { id: "i3", text: "Both conditions needed", correct_bucket: "and" },
        { id: "i4", text: "Either condition works", correct_bucket: "or" },
      ],
      expected: "Series / both-needed = AND; parallel / either-works = OR.",
      pass_threshold: 0.75,
      memo: "Series switches = AND; parallel switches = OR.", error_signals: ["ERR_TECH_G9ESA5_SORT"], difficulty: 2,
    },
    MC("Lamps connected in series share the supply so that…",
      ["if one breaks, all go out", "they get brighter", "they never go out", "they store charge"], "if one breaks, all go out",
      "In series, a break anywhere stops the whole circuit, so all lamps go out.", "ERR_TECH_G9ESA5_SERIESLAMPS", 3),
    TF("Lamps in parallel keep working even if one of them fails.", "True",
      "In parallel, each lamp has its own path, so others stay on if one fails.", "ERR_TECH_G9ESA5_PARALLELLAMPS", 3),
    MC("A two-way light switch (top and bottom of stairs) uses…",
      ["SPDT switches", "only SPST", "a capacitor", "a thermistor"], "SPDT switches",
      "Stairway two-way switching uses SPDT switches to control one light from two places.", "ERR_TECH_G9ESA5_STAIRS", 3),
    CLOZE("Conventional current flows from positive to ____.",
      ["negative", "positive", "neutral", "sideways"], "negative",
      "Conventional current is taken to flow + to −.", "ERR_TECH_G9ESA5_NEGATIVE", 2),
    MC("Adding a second switch in parallel to a lamp circuit lets you…",
      ["turn the lamp on from two places", "make the lamp brighter forever", "store energy", "remove the lamp"], "turn the lamp on from two places",
      "A parallel switch (OR logic) lets either switch turn the lamp on.", "ERR_TECH_G9ESA5_SECOND", 2),
    TF("Switches are control devices in a circuit.", "True",
      "Switches control the flow of current — they are control devices.", "ERR_TECH_G9ESA5_CONTROL", 1),
  ],

  // ES.A6 · Simple electronic circuits
  "TECH.G9.ES.A6": [
    MC("A basic 'LED indicator' circuit usually includes an LED, a switch, a battery and a…",
      ["resistor to limit current", "motor", "magnet", "gear"], "resistor to limit current",
      "An LED indicator circuit uses a series resistor to limit current and protect the LED.", "ERR_TECH_G9ESA6_LEDCIRCUIT", 2),
    MC("In a dark-detector circuit, which sensor switches a buzzer or light?",
      ["An LDR", "A motor", "A magnet", "A gear"], "An LDR",
      "An LDR detects darkness and triggers the output in a dark-detector circuit.", "ERR_TECH_G9ESA6_LDRCIRCUIT", 2),
    MC("A heat-warning circuit would most likely use a…",
      ["thermistor", "LDR", "moisture sensor", "pulley"], "thermistor",
      "A thermistor senses temperature for a heat-warning circuit.", "ERR_TECH_G9ESA6_THERMCIRCUIT", 2),
    TF("In Grade 9, learners assemble and connect given circuits rather than design the electronics from scratch.", "True",
      "CAPS: learners build and find a use for a GIVEN circuit, not design the electronics themselves.", "ERR_TECH_G9ESA6_GIVEN", 2),
    MC("A capacitor added to an LED circuit can…",
      ["keep the LED glowing briefly after switch-off", "make it a magnet", "cool the LED", "add weight"], "keep the LED glowing briefly after switch-off",
      "A charged capacitor releases energy, keeping the LED on briefly after the switch opens.", "ERR_TECH_G9ESA6_CAPACITOR", 3),
    MC("A transistor in a sensor circuit is used to…",
      ["switch on a larger output from a small sensor signal", "store water", "make wind", "weigh the sensor"], "switch on a larger output from a small sensor signal",
      "The transistor amplifies the sensor's small signal to drive an output like a buzzer.", "ERR_TECH_G9ESA6_TRANSISTOR", 3),
    CLOZE("An LED circuit needs a series ____ to limit the current.",
      ["resistor", "magnet", "motor", "switch-only"], "resistor",
      "A series resistor limits the LED's current.", "ERR_TECH_G9ESA6_RESISTOR", 2),
    TF("A given circuit must be incorporated into a useful device that meets a need.", "True",
      "Learners build the given circuit into a device that addresses a real need.", "ERR_TECH_G9ESA6_DEVICE", 2),
    MC("A circuit with an LDR and a buzzer could be used as…",
      ["a light-triggered alarm", "a water pump", "a magnet", "a gearbox"], "a light-triggered alarm",
      "An LDR-and-buzzer circuit can warn when light (or its absence) is detected.", "ERR_TECH_G9ESA6_ALARM", 2),
    MC("Why connect components in the correct order and polarity?",
      ["So the circuit works and parts are not damaged", "To use more wire", "To add colour", "There is no reason"], "So the circuit works and parts are not damaged",
      "Correct connections and polarity make the circuit work and protect components.", "ERR_TECH_G9ESA6_CORRECT", 2),
    TF("An LED will not light if it is connected the wrong way round.", "True",
      "As a diode, the LED only conducts (and lights) the correct way round.", "ERR_TECH_G9ESA6_POLARITY", 2),
    CLOZE("A circuit using a thermistor can respond to changes in ____.",
      ["temperature", "light", "sound", "weight"], "temperature",
      "A thermistor circuit responds to temperature.", "ERR_TECH_G9ESA6_TEMP", 2),
    {
      question: "Match each simple circuit to its job.",
      input_type: "sort-buckets",
      buckets: [{ id: "light", label: "Reacts to light" }, { id: "heat", label: "Reacts to heat" }, { id: "indicate", label: "Shows power is on" }],
      items: [
        { id: "i1", text: "LDR + buzzer", correct_bucket: "light" },
        { id: "i2", text: "Thermistor + transistor + buzzer", correct_bucket: "heat" },
        { id: "i3", text: "LED + resistor + switch", correct_bucket: "indicate" },
      ],
      expected: "LDR circuit reacts to light; thermistor circuit reacts to heat; LED+resistor shows power is on.",
      pass_threshold: 0.66,
      memo: "Match the sensor to the job: LDR (light), thermistor (heat), LED indicator (power on).", error_signals: ["ERR_TECH_G9ESA6_SORT"], difficulty: 3,
    },
    {
      question: "Order the steps to assemble and use a given electronic circuit.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Study the given circuit and the need it must meet" },
        { id: "b", text: "Connect the components in the correct order and polarity" },
        { id: "c", text: "Test that the circuit works" },
        { id: "d", text: "Build it into a device that meets the need" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Understand the circuit and need, connect it correctly, test it, then build it into a useful device.",
      error_signals: ["ERR_TECH_G9ESA6_SEQUENCE"], difficulty: 2,
    },
    MC("A circuit that turns a light on at dusk uses an LDR because the LDR…",
      ["senses the falling light level", "makes light", "stores charge", "spins"], "senses the falling light level",
      "The LDR senses the drop in light and the circuit switches the light on.", "ERR_TECH_G9ESA6_DUSK", 3),
    TF("A simple electronic circuit can combine a sensor, a transistor and an output device.", "True",
      "Many circuits use a sensor input, a transistor to switch, and an output like a buzzer.", "ERR_TECH_G9ESA6_COMBINE", 2),
    MC("The output device in a simple alarm circuit is often a…",
      ["buzzer or bell", "resistor", "sensor", "switch"], "buzzer or bell",
      "A buzzer or bell is the output that warns in an alarm circuit.", "ERR_TECH_G9ESA6_OUTPUT", 1),
    CLOZE("Learners are expected to ____ a given circuit and find a use for it.",
      ["assemble", "ignore", "destroy", "sell"], "assemble",
      "Learners assemble a given circuit and design a use for it.", "ERR_TECH_G9ESA6_ASSEMBLE", 2),
    MC("Why draw the circuit diagram before connecting the real parts?",
      ["It guides correct, safe connection", "To waste time", "To add colour", "There is no reason"], "It guides correct, safe connection",
      "A circuit diagram guides you to connect the real components correctly.", "ERR_TECH_G9ESA6_DIAGRAM", 2),
    TF("Combining electronic components lets a circuit sense, decide and act.", "True",
      "Sensors sense, transistors/logic decide, outputs act — combined in a working circuit.", "ERR_TECH_G9ESA6_SENSEACT", 2),
  ],

  // ════════════════════════ PROCESSING (Term 4) ═══════════════════════════════
  // PR.A1 · Preserving metals
  "TECH.G9.PR.A1": [
    MC("Why do we protect metals like iron from corrosion?",
      ["Rust weakens them over time", "Rust makes them stronger", "Rust looks good", "There is no reason"], "Rust weakens them over time",
      "Corrosion (rust) weakens metal over time, so we protect it.", "ERR_TECH_G9PRA1_WHY", 1),
    MC("Painting a metal protects it by…",
      ["sealing out air and moisture", "adding electricity", "making it magnetic", "heating it"], "sealing out air and moisture",
      "Paint forms a barrier that keeps air and moisture off the metal.", "ERR_TECH_G9PRA1_PAINT", 1),
    MC("Galvanising protects steel by coating it with…",
      ["zinc", "gold", "paper", "plastic foam"], "zinc",
      "Galvanising coats steel with zinc to prevent rust.", "ERR_TECH_G9PRA1_GALVANISE", 1),
    MC("Electroplating coats a metal with a thin layer of another metal using…",
      ["electricity", "wind", "sunlight", "sound"], "electricity",
      "Electroplating uses an electric current to deposit a thin metal coating.", "ERR_TECH_G9PRA1_ELECTROPLATE", 2),
    TF("Corrosion is the gradual damage of metal by reacting with its surroundings.", "True",
      "Corrosion is the slow chemical damage of metal by air and moisture.", "ERR_TECH_G9PRA1_CORROSION", 1),
    CLOZE("Coating steel with zinc to stop rust is called ____.",
      ["galvanising", "painting", "drying", "pickling"], "galvanising",
      "Galvanising is a protective zinc coating.", "ERR_TECH_G9PRA1_GALVWORD", 1),
    MC("Why might you electroplate a cheap metal spoon with silver?",
      ["To make it look good and resist tarnish", "To make it heavier only", "To make it rust", "To make it magnetic"], "To make it look good and resist tarnish",
      "Electroplating adds an attractive, protective layer (like silver) to a cheaper base.", "ERR_TECH_G9PRA1_SPOON", 2),
    TF("Rust forms on iron mainly when it is exposed to air and water.", "True",
      "Iron rusts in the presence of oxygen and moisture.", "ERR_TECH_G9PRA1_AIRWATER", 1),
    CLOZE("Coating a metal with a thin layer of another metal using electricity is ____.",
      ["electroplating", "galvanising", "painting", "drying"], "electroplating",
      "Electroplating uses electricity to deposit a metal coating.", "ERR_TECH_G9PRA1_ELECWORD", 2),
    MC("Which method uses an electric current to coat the metal?",
      ["Electroplating", "Painting", "Galvanising (dipping)", "Oiling"], "Electroplating",
      "Electroplating is the method that uses an electric current.", "ERR_TECH_G9PRA1_WHICHELEC", 2),
    TF("Protecting metal extends the life of products and structures.", "True",
      "Preventing corrosion makes metal products and structures last longer.", "ERR_TECH_G9PRA1_LIFE", 1),
    MC("Galvanised steel is often used outdoors because it…",
      ["resists rust well", "rusts faster", "is lighter than air", "glows"], "resists rust well",
      "The zinc coating makes galvanised steel resist rust outdoors.", "ERR_TECH_G9PRA1_OUTDOORS", 2),
    {
      question: "Match each metal-protecting method to how it works.",
      input_type: "sort-buckets",
      buckets: [{ id: "barrier", label: "Barrier coating" }, { id: "zinc", label: "Zinc coating" }, { id: "elec", label: "Uses electricity" }],
      items: [
        { id: "i1", text: "Painting", correct_bucket: "barrier" },
        { id: "i2", text: "Galvanising", correct_bucket: "zinc" },
        { id: "i3", text: "Electroplating", correct_bucket: "elec" },
      ],
      expected: "Painting is a barrier; galvanising is a zinc coating; electroplating uses electricity.",
      pass_threshold: 0.66,
      memo: "Paint = barrier; galvanise = zinc dip; electroplate = electric metal coating.", error_signals: ["ERR_TECH_G9PRA1_SORT"], difficulty: 2,
    },
    MC("Preserving metals is an example of 'processing' because it…",
      ["treats a material to make it last and be more useful", "throws it away", "ignores it", "weighs it"], "treats a material to make it last and be more useful",
      "Treating metal to extend its life is a form of processing.", "ERR_TECH_G9PRA1_PROCESSING", 2),
    TF("Oiling or greasing moving metal parts also helps prevent rust.", "True",
      "A film of oil or grease keeps moisture off and helps prevent rust.", "ERR_TECH_G9PRA1_OIL", 2),
    MC("Stainless steel resists corrosion because of the metals mixed into it (an alloy). This shows that…",
      ["changing a material's make-up can protect it", "all steel rusts equally", "rust is unavoidable", "coatings never work"], "changing a material's make-up can protect it",
      "Alloying (as in stainless steel) is another way to resist corrosion.", "ERR_TECH_G9PRA1_ALLOY", 3),
    CLOZE("A protective layer of ____ keeps air and water off a painted metal.",
      ["paint", "rust", "water", "air"], "paint",
      "The paint layer keeps air and water off the metal.", "ERR_TECH_G9PRA1_PAINTWORD", 1),
    MC("The main aim of all these methods (paint, galvanise, electroplate) is to…",
      ["stop the metal corroding", "make it rust", "add weight", "change the weather"], "stop the metal corroding",
      "All these methods aim to prevent corrosion.", "ERR_TECH_G9PRA1_AIM", 1),
    TF("A scratch in paint can let rust start, so coatings must be kept intact.", "True",
      "Damaged coatings expose the metal, letting corrosion begin at the scratch.", "ERR_TECH_G9PRA1_SCRATCH", 2),
    MC("Which is the best reason to galvanise a steel roof sheet?",
      ["It will be outdoors in rain and must resist rust", "It must be heavy", "It must glow", "It must be magnetic"], "It will be outdoors in rain and must resist rust",
      "A roof sheet faces rain, so galvanising protects it from rust.", "ERR_TECH_G9PRA1_ROOF", 2),
  ],

  // PR.A2 · Preserving food
  "TECH.G9.PR.A2": [
    MC("Why do we preserve food?",
      ["To make it last longer without spoiling", "To make it spoil faster", "To make it heavier", "To change its colour only"], "To make it last longer without spoiling",
      "Food preservation slows spoilage so food lasts longer.", "ERR_TECH_G9PRA2_WHY", 1),
    MC("Storing grain keeps it good by keeping it…",
      ["dry and protected from pests", "wet", "warm and damp", "in the rain"], "dry and protected from pests",
      "Dry, pest-free storage stops grain from rotting or being eaten.", "ERR_TECH_G9PRA2_GRAIN", 1),
    MC("Pickling preserves food using…",
      ["vinegar or brine (acid/salt)", "sunlight only", "magnets", "electricity"], "vinegar or brine (acid/salt)",
      "Pickling uses an acid (vinegar) or salty brine to preserve food.", "ERR_TECH_G9PRA2_PICKLING", 2),
    MC("Drying preserves food by removing…",
      ["water (so microbes cannot grow)", "colour", "weight only", "salt"], "water (so microbes cannot grow)",
      "Drying removes water that microbes need to grow, so food keeps longer.", "ERR_TECH_G9PRA2_DRYING", 2),
    MC("Salting preserves food because salt…",
      ["draws out water and stops microbes growing", "adds water", "makes it rot", "adds colour"], "draws out water and stops microbes growing",
      "Salt draws water out of food and microbes, preventing spoilage.", "ERR_TECH_G9PRA2_SALTING", 2),
    TF("Biltong is an example of meat preserved by drying and salting.", "True",
      "Biltong is dried, salted meat — a traditional preserved food.", "ERR_TECH_G9PRA2_BILTONG", 1),
    CLOZE("Removing water from food to preserve it is called ____.",
      ["drying", "wetting", "freezing-only", "painting"], "drying",
      "Drying removes water to preserve food.", "ERR_TECH_G9PRA2_DRYWORD", 1),
    MC("Food spoils mainly because of the growth of…",
      ["micro-organisms (bacteria and mould)", "metals", "magnets", "plastics"], "micro-organisms (bacteria and mould)",
      "Microbes (bacteria, mould) cause food to spoil; preservation slows them.", "ERR_TECH_G9PRA2_MICROBES", 2),
    TF("Most micro-organisms need moisture to grow, which is why drying preserves food.", "True",
      "Microbes need water; removing it (drying) stops them growing.", "ERR_TECH_G9PRA2_MOISTURE", 2),
    CLOZE("Preserving food in vinegar or brine is called ____.",
      ["pickling", "drying", "galvanising", "painting"], "pickling",
      "Pickling uses vinegar or brine.", "ERR_TECH_G9PRA2_PICKLEWORD", 2),
    MC("Storing grain in a sealed silo also protects it from…",
      ["rats and insects", "sunlight only", "magnets", "electricity"], "rats and insects",
      "Sealed storage keeps pests like rats and insects out of grain.", "ERR_TECH_G9PRA2_PESTS", 2),
    TF("Preserving food is a form of processing that makes a raw material last longer.", "True",
      "Preservation processes food so it stays useful for longer.", "ERR_TECH_G9PRA2_PROCESSING", 1),
    {
      question: "Match each preserved food to the method used.",
      input_type: "sort-buckets",
      buckets: [{ id: "dry", label: "Drying/salting" }, { id: "pickle", label: "Pickling" }, { id: "store", label: "Dry storage" }],
      items: [
        { id: "i1", text: "Biltong", correct_bucket: "dry" },
        { id: "i2", text: "Pickled onions", correct_bucket: "pickle" },
        { id: "i3", text: "Maize kept in a sealed silo", correct_bucket: "store" },
        { id: "i4", text: "Dried fruit", correct_bucket: "dry" },
      ],
      expected: "Biltong and dried fruit use drying/salting; pickled onions use pickling; silo maize is dry storage.",
      pass_threshold: 0.75,
      memo: "Drying/salting removes water; pickling uses acid/brine; dry storage keeps grain dry and pest-free.", error_signals: ["ERR_TECH_G9PRA2_SORT"], difficulty: 2,
    },
    MC("Indigenous communities have preserved food for generations, showing that preservation is…",
      ["traditional knowledge as well as modern technology", "only modern", "useless", "never used"], "traditional knowledge as well as modern technology",
      "Food preservation is both indigenous knowledge and modern technology.", "ERR_TECH_G9PRA2_INDIGENOUS", 2),
    TF("Drying meat in the sun and wind is a traditional preservation method.", "True",
      "Sun- and wind-drying of meat is a long-standing traditional method.", "ERR_TECH_G9PRA2_SUNDRY", 1),
    MC("Which method would best preserve fresh herbs for months?",
      ["Drying them", "Leaving them wet", "Painting them", "Galvanising them"], "Drying them",
      "Drying herbs removes water so they keep for months.", "ERR_TECH_G9PRA2_HERBS", 2),
    CLOZE("Salt preserves food by drawing out ____.",
      ["water", "colour", "salt", "air"], "water",
      "Salt draws water out, which stops microbes growing.", "ERR_TECH_G9PRA2_WATERWORD", 2),
    MC("Why might only some preservation methods be done practically in class?",
      ["Some, like drying/salting, take time to finish", "They are illegal", "They need no materials", "They are too easy"], "Some, like drying/salting, take time to finish",
      "Drying/salting takes time, so it is evaluated once completed; others are done in class.", "ERR_TECH_G9PRA2_TIME", 2),
    TF("Preserving food helps reduce waste and makes food available out of season.", "True",
      "Preservation reduces waste and keeps food available when fresh supplies are low.", "ERR_TECH_G9PRA2_WASTE", 1),
    MC("The common idea behind drying, salting and pickling is to…",
      ["stop micro-organisms spoiling the food", "add micro-organisms", "make food rot", "add water"], "stop micro-organisms spoiling the food",
      "All three slow or stop the microbes that spoil food.", "ERR_TECH_G9PRA2_COMMON", 2),
  ],

  // PR.A3 · Plastics: types & properties
  "TECH.G9.PR.A3": [
    MC("A THERMOPLASTIC is a plastic that…",
      ["softens when heated and can be reshaped", "never melts", "is always metal", "cannot be recycled"], "softens when heated and can be reshaped",
      "Thermoplastics soften when heated and can be remoulded and recycled.", "ERR_TECH_G9PRA3_THERMO", 1),
    MC("A THERMOSET plastic is one that…",
      ["sets hard and does not soften again when heated", "always melts easily", "is liquid", "is a metal"], "sets hard and does not soften again when heated",
      "Thermosets set permanently and do not soften on reheating.", "ERR_TECH_G9PRA3_THERMOSET", 2),
    TF("Thermoplastics can be melted and remoulded, which makes them easier to recycle.", "True",
      "Because they soften when heated, thermoplastics are easier to recycle.", "ERR_TECH_G9PRA3_RECYCLE", 2),
    MC("Plastic identification codes are used to…",
      ["help sort plastics for recycling", "show the price", "show the weight", "decorate them"], "help sort plastics for recycling",
      "Recycling codes identify the plastic type so it can be sorted for recycling.", "ERR_TECH_G9PRA3_CODES", 1),
    MC("Which is a useful property of many plastics?",
      ["Light, waterproof and can be moulded", "Heavy and always rusting", "Magnetic and brittle", "Always conducts electricity"], "Light, waterproof and can be moulded",
      "Plastics are typically light, waterproof and easily moulded.", "ERR_TECH_G9PRA3_PROPERTIES", 2),
    TF("Most plastics are good electrical insulators.", "True",
      "Plastics generally do not conduct electricity — good insulators.", "ERR_TECH_G9PRA3_INSULATOR", 2),
    CLOZE("A plastic that softens when heated is a ____.",
      ["thermoplastic", "thermoset", "metal", "ceramic"], "thermoplastic",
      "Thermoplastics soften when heated.", "ERR_TECH_G9PRA3_THERMOWORD", 1),
    MC("A pot handle that must stay hard even when hot is best made of a…",
      ["thermoset plastic", "thermoplastic that melts", "thin foil", "wet paper"], "thermoset plastic",
      "Thermosets keep their shape when hot, suiting a pot handle.", "ERR_TECH_G9PRA3_HANDLE", 3),
    TF("Identifying a plastic's code helps make sure it is recycled correctly.", "True",
      "Sorting by code ensures plastics are recycled with the right type.", "ERR_TECH_G9PRA3_SORTCODE", 1),
    CLOZE("A plastic that sets hard and will not soften again is a ____.",
      ["thermoset", "thermoplastic", "metal", "fabric"], "thermoset",
      "Thermosets set permanently hard.", "ERR_TECH_G9PRA3_SETWORD", 2),
    MC("Plastic bottles are usually made from a thermoplastic so they can be…",
      ["melted down and remade into new products", "never reused", "turned into metal", "made magnetic"], "melted down and remade into new products",
      "Thermoplastic bottles can be melted and remade — good for recycling.", "ERR_TECH_G9PRA3_BOTTLE", 2),
    MC("A disadvantage of many plastics is that they…",
      ["do not biodegrade and can pollute", "rot in a day", "are always heavy", "conduct electricity"], "do not biodegrade and can pollute",
      "Many plastics persist as litter because they do not biodegrade.", "ERR_TECH_G9PRA3_DISADVANTAGE", 2),
    {
      question: "Sort each plastic as 'Thermoplastic' or 'Thermoset'.",
      input_type: "sort-buckets",
      buckets: [{ id: "tp", label: "Thermoplastic (softens when heated)" }, { id: "ts", label: "Thermoset (stays hard)" }],
      items: [
        { id: "i1", text: "Plastic drink bottle", correct_bucket: "tp" },
        { id: "i2", text: "Plastic shopping bag", correct_bucket: "tp" },
        { id: "i3", text: "Pot/pan handle", correct_bucket: "ts" },
        { id: "i4", text: "Electrical plug casing", correct_bucket: "ts" },
      ],
      expected: "Bottles and bags are thermoplastics; pot handles and plug casings are thermosets.",
      pass_threshold: 0.75,
      memo: "Thermoplastics (bottles, bags) soften and remould; thermosets (handles, plug casings) stay hard.", error_signals: ["ERR_TECH_G9PRA3_SORT"], difficulty: 3,
    },
    MC("Why are plastics widely used for packaging?",
      ["They are light, cheap, waterproof and mouldable", "They are heavy and costly", "They rust", "They conduct electricity"], "They are light, cheap, waterproof and mouldable",
      "Plastics' light, cheap, waterproof, mouldable nature suits packaging.", "ERR_TECH_G9PRA3_PACKAGING", 2),
    TF("Knowing a plastic's properties helps a designer choose the right one for a product.", "True",
      "Matching plastic properties to the product is part of good design.", "ERR_TECH_G9PRA3_CHOOSE", 1),
    MC("Electrical plugs are often made of thermoset plastic because it…",
      ["stays hard and insulates even when warm", "melts when warm", "conducts electricity", "rusts"], "stays hard and insulates even when warm",
      "Thermosets stay hard and insulating even when warm — safe for plugs.", "ERR_TECH_G9PRA3_PLUG", 3),
    CLOZE("Recycling ____ printed on plastics help sort them.",
      ["codes", "songs", "smells", "weights"], "codes",
      "Recycling codes identify the plastic type for sorting.", "ERR_TECH_G9PRA3_CODEWORD", 1),
    MC("Most plastics are made from…",
      ["oil (petroleum) products", "iron ore", "wood only", "water only"], "oil (petroleum) products",
      "Most plastics are made from petroleum (oil) products.", "ERR_TECH_G9PRA3_OIL", 2),
    TF("Sorting plastics by type before recycling produces better-quality recycled material.", "True",
      "Sorting by type keeps recycled plastic pure and more useful.", "ERR_TECH_G9PRA3_QUALITY", 2),
    MC("The two main families of plastic are…",
      ["thermoplastics and thermosets", "metals and ceramics", "liquids and gases", "woods and fabrics"], "thermoplastics and thermosets",
      "Plastics are grouped as thermoplastics and thermosets.", "ERR_TECH_G9PRA3_TWOFAMILIES", 1),
  ],

  // PR.A4 · Recycling plastics
  "TECH.G9.PR.A4": [
    MC("The 'three Rs' of caring for the environment are…",
      ["reduce, reuse, recycle", "run, rest, repeat", "read, write, rule", "red, round, rough"], "reduce, reuse, recycle",
      "Reduce, reuse, recycle is the order of preference for cutting waste.", "ERR_TECH_G9PRA4_3R", 1),
    MC("'Reduce' means…",
      ["use less in the first place", "use more", "throw away faster", "bury waste"], "use less in the first place",
      "Reduce means using less so there is less to deal with later.", "ERR_TECH_G9PRA4_REDUCE", 1),
    MC("'Reuse' means…",
      ["use an item again instead of throwing it away", "melt everything", "bury it", "burn it"], "use an item again instead of throwing it away",
      "Reuse means using an item again rather than discarding it.", "ERR_TECH_G9PRA4_REUSE", 1),
    MC("'Recycle' means…",
      ["process used material into new products", "throw it in the sea", "burn it in the open", "ignore it"], "process used material into new products",
      "Recycling reprocesses used material into new products.", "ERR_TECH_G9PRA4_RECYCLE", 1),
    MC("Waste plastic is often recycled by first being made into…",
      ["pellets that are remelted into new products", "metal bars", "glass", "paper"], "pellets that are remelted into new products",
      "Plastic is shredded and made into pellets, which are remelted into new items.", "ERR_TECH_G9PRA4_PELLETS", 2),
    TF("Recycling plastic reduces the need for new oil-based raw materials.", "True",
      "Recycling reuses plastic, reducing demand for new oil-based plastic.", "ERR_TECH_G9PRA4_OIL", 2),
    CLOZE("Shredded plastic is melted into small ____ for re-use.",
      ["pellets", "bars", "sheets-only", "wires"], "pellets",
      "Recycled plastic is formed into pellets for remoulding.", "ERR_TECH_G9PRA4_PELLETWORD", 2),
    MC("A systems diagram of plastic recycling would have the input as…",
      ["waste plastic", "new products", "the machine only", "the colour"], "waste plastic",
      "Waste plastic is the input; the process is shredding/melting; the output is new products.", "ERR_TECH_G9PRA4_INPUT", 2),
    MC("Moulding recycled pellets means…",
      ["shaping melted plastic into new products", "burning the pellets", "burying the pellets", "painting them"], "shaping melted plastic into new products",
      "Moulding shapes the melted recycled plastic into new products.", "ERR_TECH_G9PRA4_MOULDING", 2),
    TF("The best of the three Rs to do first is 'reduce', because using less avoids waste entirely.", "True",
      "Reducing comes first — using less avoids creating the waste at all.", "ERR_TECH_G9PRA4_REDUCEFIRST", 2),
    CLOZE("Turning used plastic into new products is called ____.",
      ["recycling", "reducing", "burning", "burying"], "recycling",
      "Recycling reprocesses used plastic into new products.", "ERR_TECH_G9PRA4_RECYCLEWORD", 1),
    MC("Cutting, bending and joining plastic are skills used to…",
      ["make a plastic product", "grow plants", "store water", "make a magnet"], "make a plastic product",
      "Measuring, cutting, bending and joining are how a plastic item is made.", "ERR_TECH_G9PRA4_SKILLS", 2),
    {
      question: "Order the steps to recycle plastic into a new product.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Collect and sort waste plastic" },
        { id: "b", text: "Shred and melt it into pellets" },
        { id: "c", text: "Mould the pellets into a new product" },
        { id: "d", text: "Use the new recycled product" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Collect and sort, shred/melt into pellets, mould into a new product, then use it.",
      error_signals: ["ERR_TECH_G9PRA4_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each action under the correct 'R'.",
      input_type: "sort-buckets",
      buckets: [{ id: "reduce", label: "Reduce" }, { id: "reuse", label: "Reuse" }, { id: "recycle", label: "Recycle" }],
      items: [
        { id: "i1", text: "Buy a drink in a refillable bottle", correct_bucket: "reduce" },
        { id: "i2", text: "Use an old jar to store screws", correct_bucket: "reuse" },
        { id: "i3", text: "Send plastic bottles to be made into pellets", correct_bucket: "recycle" },
        { id: "i4", text: "Choose products with less packaging", correct_bucket: "reduce" },
      ],
      expected: "Refillable bottles and less packaging reduce; reusing a jar is reuse; sending bottles for pellets is recycling.",
      pass_threshold: 0.75,
      memo: "Reduce = use less; reuse = use again; recycle = reprocess into something new.", error_signals: ["ERR_TECH_G9PRA4_SORT"], difficulty: 3,
    },
    MC("Remanufacturing waste plastic into pellets is valuable because it…",
      ["turns waste into a useful raw material", "creates more waste", "wastes energy for nothing", "pollutes more"], "turns waste into a useful raw material",
      "Pelletising turns waste plastic into a reusable raw material.", "ERR_TECH_G9PRA4_VALUE", 2),
    TF("Recycling helps reduce the amount of plastic litter in the environment.", "True",
      "Recycling keeps plastic in use and out of the environment as litter.", "ERR_TECH_G9PRA4_LITTER", 1),
    MC("A plastics recycling project is best described in a systems diagram as…",
      ["input (waste) → process (shred/melt/mould) → output (new product)", "only an output", "only an input", "colour → weight → price"], "input (waste) → process (shred/melt/mould) → output (new product)",
      "Recycling fits input-process-output: waste in, processing, new product out.", "ERR_TECH_G9PRA4_SYSTEM", 3),
    CLOZE("Using an item again instead of discarding it is to ____ it.",
      ["reuse", "reduce", "recycle", "burn"], "reuse",
      "Reuse means using the same item again.", "ERR_TECH_G9PRA4_REUSEWORD", 1),
    MC("Why is recycling plastic better than sending it to landfill?",
      ["It saves resources and reduces pollution", "It uses more oil", "It makes more litter", "It has no benefit"], "It saves resources and reduces pollution",
      "Recycling saves raw materials and cuts pollution compared with landfill.", "ERR_TECH_G9PRA4_VSLANDFILL", 2),
    TF("Choosing products with less packaging is an example of 'reduce'.", "True",
      "Less packaging means less waste created — that is reducing.", "ERR_TECH_G9PRA4_LESSPACK", 1),
  ],
};

export default G9B;
