// ─── Technology SP — Grade 8 authored pools (part 2: ES · PR) ────────────────
// Electrical Systems & Control (Term 4) · Processing, Society & Environment (T2).
// Refs auto-assigned by build-technology-sp.mjs. Tap-only; no free text.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G8B = {
  // ════════════ ELECTRICAL SYSTEMS & CONTROL (Term 4) ═════════════════════════
  // ES.A1 · Circuit components & symbols
  "TECH.G8.ES.A1": [
    MC("In a circuit, an INPUT device…",
      ["puts energy or a signal into the circuit, like a cell", "gives out light or sound", "only holds wires", "is always a bulb"], "puts energy or a signal into the circuit, like a cell",
      "Input devices (cell, generator, solar panel) put energy/signals into the circuit.", "ERR_TECH_G8ESA1_INPUT", 1),
    MC("In a circuit, an OUTPUT device…",
      ["turns electricity into light, sound or movement", "supplies the energy", "controls the flow", "stores nothing"], "turns electricity into light, sound or movement",
      "Output devices (lamp, buzzer, motor, heater) turn electricity into a useful effect.", "ERR_TECH_G8ESA1_OUTPUT", 1),
    MC("In a circuit, a CONTROL device…",
      ["switches or controls the flow of current", "supplies the power", "gives out light", "holds the case"], "switches or controls the flow of current",
      "Control devices (switches) control whether and how current flows.", "ERR_TECH_G8ESA1_CONTROL", 1),
    MC("Which is an OUTPUT device?",
      ["A motor", "A cell", "A solar panel", "A generator"], "A motor",
      "A motor is an output (movement); cells, solar panels and generators are inputs.", "ERR_TECH_G8ESA1_MOTOR", 1),
    MC("Which is an INPUT device?",
      ["A solar (photovoltaic) panel", "A lamp", "A buzzer", "A heater"], "A solar (photovoltaic) panel",
      "A solar panel supplies energy — an input; lamps, buzzers and heaters are outputs.", "ERR_TECH_G8ESA1_SOLAR", 2),
    TF("A switch is a control device that opens or closes a circuit.", "True",
      "A switch controls the circuit by opening (off) or closing (on).", "ERR_TECH_G8ESA1_SWITCH", 1),
    CLOZE("A lamp, buzzer or motor is an ____ device.",
      ["output", "input", "control", "hidden"], "output",
      "Lamps, buzzers and motors are output devices.", "ERR_TECH_G8ESA1_OUTWORD", 1),
    MC("A short circuit is dangerous because…",
      ["current flows the wrong, easy path and can overheat", "it gives more light", "it saves the battery", "it makes no difference"], "current flows the wrong, easy path and can overheat",
      "A short circuit lets a large current take an unintended low-resistance path, which can overheat.", "ERR_TECH_G8ESA1_SHORT", 3),
    TF("Some devices can act as input, output, process or control depending on use.", "True",
      "A device's role depends on how it is used in the circuit.", "ERR_TECH_G8ESA1_DEPENDS", 2),
    MC("Why use accepted symbols for circuit components?",
      ["So any person can read the circuit clearly", "To use more ink", "To hide the design", "To slow building"], "So any person can read the circuit clearly",
      "Standard symbols make circuit diagrams universally readable.", "ERR_TECH_G8ESA1_SYMBOLS", 1),
    CLOZE("A cell or solar panel that supplies energy is an ____ device.",
      ["input", "output", "control", "broken"], "input",
      "Energy suppliers (cell, solar panel, generator) are input devices.", "ERR_TECH_G8ESA1_INWORD", 1),
    MC("A heater turns electricity into…",
      ["heat", "light only", "sound only", "movement"], "heat",
      "A heater is an output that converts electricity to heat.", "ERR_TECH_G8ESA1_HEATER", 1),
    TF("Connecting the components correctly avoids short circuits.", "True",
      "Correct connections keep current on the right path and avoid short circuits.", "ERR_TECH_G8ESA1_CONNECT", 2),
    {
      question: "Sort each component as input, output or control.",
      input_type: "sort-buckets",
      buckets: [{ id: "in", label: "Input" }, { id: "out", label: "Output" }, { id: "ctrl", label: "Control" }],
      items: [
        { id: "i1", text: "Cell / battery", correct_bucket: "in" },
        { id: "i2", text: "Solar panel", correct_bucket: "in" },
        { id: "i3", text: "Lamp", correct_bucket: "out" },
        { id: "i4", text: "Buzzer", correct_bucket: "out" },
        { id: "i5", text: "Switch", correct_bucket: "ctrl" },
      ],
      expected: "Cells and solar panels are inputs; lamps and buzzers are outputs; a switch is control.",
      pass_threshold: 0.7,
      memo: "Input = supplies energy; output = gives a useful effect; control = switches the current.", error_signals: ["ERR_TECH_G8ESA1_SORT"], difficulty: 2,
    },
    MC("A motor is best described as a device that turns electricity into…",
      ["movement", "light", "sound", "heat only"], "movement",
      "A motor converts electrical energy into movement (rotation).", "ERR_TECH_G8ESA1_MOTOROUT", 1),
    TF("A resistor can be used to limit the current in a circuit.", "True",
      "A resistor opposes current, limiting how much flows.", "ERR_TECH_G8ESA1_RESISTOR", 2),
    MC("Which group lists only OUTPUT devices?",
      ["Lamp, buzzer, motor, heater", "Cell, lamp, switch", "Solar panel, generator, cell", "Switch, switch, switch"], "Lamp, buzzer, motor, heater",
      "Lamps, buzzers, motors and heaters all turn electricity into useful effects — outputs.", "ERR_TECH_G8ESA1_GROUP", 2),
    CLOZE("A device that controls the flow of current is a ____ device.",
      ["control", "input", "output", "hidden"], "control",
      "Control devices (switches) control the current flow.", "ERR_TECH_G8ESA1_CTRLWORD", 1),
    MC("Reading a circuit diagram is easier than a photo of real parts because…",
      ["symbols are simple and standard", "photos are illegal", "symbols are colourful", "photos are heavier"], "symbols are simple and standard",
      "Standard symbols are simpler and clearer than photographs of components.", "ERR_TECH_G8ESA1_EASIER", 2),
    TF("A generator is an input device that supplies electrical energy.", "True",
      "A generator produces electrical energy — an input to the circuit.", "ERR_TECH_G8ESA1_GENERATOR", 2),
  ],

  // ES.A2 · Cells & energy sources
  "TECH.G8.ES.A2": [
    MC("What is an electrochemical cell?",
      ["A device that makes electricity from a chemical reaction", "A type of magnet", "A kind of gear", "A light bulb"], "A device that makes electricity from a chemical reaction",
      "An electrochemical cell produces electricity from a chemical reaction (a battery is made of cells).", "ERR_TECH_G8ESA2_DEF", 1),
    MC("Connecting cells in SERIES (one after another) increases the…",
      ["voltage", "colour", "weight only", "size of the wire"], "voltage",
      "Cells in series add their voltages together.", "ERR_TECH_G8ESA2_SERIES", 2),
    MC("Connecting cells in PARALLEL keeps the voltage the same but…",
      ["makes them last longer", "increases voltage", "stops them working", "changes colour"], "makes them last longer",
      "Cells in parallel keep voltage the same but supply current for longer.", "ERR_TECH_G8ESA2_PARALLEL", 3),
    TF("A 'battery' is made up of one or more cells.", "True",
      "A battery is a combination of one or more electrochemical cells.", "ERR_TECH_G8ESA2_BATTERY", 1),
    MC("A photovoltaic (solar) cell turns ____ into electricity.",
      ["sunlight", "sound", "wind", "heat from a flame"], "sunlight",
      "A photovoltaic cell converts sunlight directly into electricity.", "ERR_TECH_G8ESA2_PV", 1),
    MC("An advantage of solar cells is that they…",
      ["use free, renewable sunlight", "work best in the dark", "never wear out", "are always cheapest"], "use free, renewable sunlight",
      "Solar cells use free, renewable sunlight — a key advantage.", "ERR_TECH_G8ESA2_SOLARADV", 2),
    MC("A disadvantage of solar cells is that they…",
      ["do not work at night or in heavy cloud", "make too much noise", "use coal", "produce smoke"], "do not work at night or in heavy cloud",
      "Solar cells need sunlight, so they don't work at night or in heavy cloud.", "ERR_TECH_G8ESA2_SOLARDIS", 2),
    TF("You can make a simple cell from a fruit, vegetable or salt water.", "True",
      "Fruit, vegetable and salt-water cells are simple electrochemical cells.", "ERR_TECH_G8ESA2_FRUIT", 1),
    CLOZE("Cells joined in ____ add their voltages together.",
      ["series", "parallel", "circles", "colours"], "series",
      "Series cells add voltage; parallel cells extend life.", "ERR_TECH_G8ESA2_SERIESWORD", 2),
    MC("Three 1.5 V cells connected in series give a total voltage of…",
      ["4.5 V", "1.5 V", "0.5 V", "15 V"], "4.5 V",
      "1.5 + 1.5 + 1.5 = 4.5 V for cells in series.", "ERR_TECH_G8ESA2_45V", 3),
    TF("Cells in parallel are useful when you need the battery to last longer.", "True",
      "Parallel cells provide current for longer at the same voltage.", "ERR_TECH_G8ESA2_LASTLONGER", 2),
    CLOZE("A solar cell is also called a ____ cell.",
      ["photovoltaic", "chemical", "fuel", "dry"], "photovoltaic",
      "Solar cells are photovoltaic cells.", "ERR_TECH_G8ESA2_PVWORD", 2),
    MC("Why might a torch use cells in series?",
      ["To give enough voltage to light the bulb brightly", "To make it heavier", "To save sunlight", "To make noise"], "To give enough voltage to light the bulb brightly",
      "Series cells add voltage to drive the bulb brightly.", "ERR_TECH_G8ESA2_TORCH", 2),
    {
      question: "Sort each statement under 'Series cells' or 'Parallel cells'.",
      input_type: "sort-buckets",
      buckets: [{ id: "ser", label: "Series" }, { id: "par", label: "Parallel" }],
      items: [
        { id: "i1", text: "Adds the voltages together", correct_bucket: "ser" },
        { id: "i2", text: "Keeps voltage the same but lasts longer", correct_bucket: "par" },
        { id: "i3", text: "Three 1.5 V cells give 4.5 V", correct_bucket: "ser" },
        { id: "i4", text: "Used to supply current for longer", correct_bucket: "par" },
      ],
      expected: "Series adds voltages (e.g. 4.5 V); parallel keeps voltage but lasts longer.",
      pass_threshold: 0.75,
      memo: "Series → more voltage; parallel → same voltage, longer life.", error_signals: ["ERR_TECH_G8ESA2_SORT"], difficulty: 3,
    },
    MC("A fruit cell works because the fruit's juice acts as…",
      ["an electrolyte for the chemical reaction", "a magnet", "a switch", "a light"], "an electrolyte for the chemical reaction",
      "The acidic juice is the electrolyte that lets the cell's chemical reaction make electricity.", "ERR_TECH_G8ESA2_ELECTROLYTE", 3),
    TF("Solar cells are environmentally friendly because they produce no smoke while working.", "True",
      "While working, solar cells make no smoke or pollution — an environmental advantage.", "ERR_TECH_G8ESA2_CLEAN", 2),
    MC("Which is an INPUT (energy source) device?",
      ["An electrochemical cell", "A lamp", "A buzzer", "A motor"], "An electrochemical cell",
      "A cell supplies energy — an input device.", "ERR_TECH_G8ESA2_INPUT", 1),
    CLOZE("Two 1.5 V cells in series give ____ V.",
      ["3", "1.5", "0.75", "30"], "3",
      "1.5 + 1.5 = 3 V in series.", "ERR_TECH_G8ESA2_3V", 2),
    MC("A disadvantage of ordinary batteries is that…",
      ["they run flat and can pollute when thrown away", "they last forever", "they make sunlight", "they cannot store energy"], "they run flat and can pollute when thrown away",
      "Batteries run flat and contain chemicals that can pollute if not disposed of properly.", "ERR_TECH_G8ESA2_BATDIS", 2),
    TF("In the GET band, circuits use batteries up to a maximum of 9 V DC.", "True",
      "Safety rule: GET circuits use batteries up to 9V DC.", "ERR_TECH_G8ESA2_9V", 2),
  ],

  // ES.A3 · Generating electricity for the nation
  "TECH.G8.ES.A3": [
    MC("A thermal power station makes electricity by…",
      ["burning fuel to make steam that spins turbines", "using sunlight only", "using magnets only", "using wind only"], "burning fuel to make steam that spins turbines",
      "Thermal stations heat water to steam, which spins turbines connected to generators.", "ERR_TECH_G8ESA3_THERMAL", 2),
    MC("Which fuel is most used in South African thermal power stations?",
      ["Coal", "Sunlight", "Wind", "Water"], "Coal",
      "South Africa generates most of its electricity by burning coal.", "ERR_TECH_G8ESA3_COAL", 1),
    MC("A hydroelectric power station uses the energy of…",
      ["moving water", "burning coal", "the wind", "sunlight"], "moving water",
      "Hydroelectric stations use moving/falling water to spin turbines.", "ERR_TECH_G8ESA3_HYDRO", 1),
    MC("A wind turbine generates electricity using…",
      ["wind to spin its blades", "coal", "water", "sunlight"], "wind to spin its blades",
      "Wind turbines use the wind to turn blades that drive a generator.", "ERR_TECH_G8ESA3_WIND", 1),
    MC("The network that carries electricity across the country is the…",
      ["national grid", "national road", "internet", "river system"], "national grid",
      "The national grid is the network of power lines that distributes electricity.", "ERR_TECH_G8ESA3_GRID", 1),
    MC("A step-UP transformer is used to…",
      ["raise the voltage for sending power long distances", "lower the voltage for homes", "store electricity", "make heat"], "raise the voltage for sending power long distances",
      "Step-up transformers raise voltage so power travels efficiently over long distances.", "ERR_TECH_G8ESA3_STEPUP", 3),
    MC("A step-DOWN transformer is used to…",
      ["lower the voltage to a safe level for homes", "raise the voltage", "store energy", "make sound"], "lower the voltage to a safe level for homes",
      "Step-down transformers reduce voltage to a safe level before it reaches homes.", "ERR_TECH_G8ESA3_STEPDOWN", 3),
    TF("Coal power produces carbon dioxide and pollution, a disadvantage of thermal stations.", "True",
      "Burning coal releases CO2 and other pollution — a key disadvantage.", "ERR_TECH_G8ESA3_COALDIS", 2),
    TF("Wind and hydroelectric power are renewable and produce little pollution while running.", "True",
      "Wind and hydro are renewable and produce little pollution during operation.", "ERR_TECH_G8ESA3_RENEWABLE", 2),
    CLOZE("Power stations are connected to homes through the national ____.",
      ["grid", "road", "river", "post"], "grid",
      "The national grid distributes electricity from stations to users.", "ERR_TECH_G8ESA3_GRIDWORD", 1),
    MC("Mains electricity in the grid is usually carried as…",
      ["alternating current (AC)", "direct current only", "no current", "static only"], "alternating current (AC)",
      "The grid carries alternating current (AC), which transformers can change in voltage.", "ERR_TECH_G8ESA3_AC", 3),
    MC("A pumped-storage scheme stores energy by…",
      ["pumping water uphill to release later", "burning extra coal", "storing wind in tanks", "freezing water"], "pumping water uphill to release later",
      "Pumped storage pumps water uphill when demand is low, then releases it to generate later.", "ERR_TECH_G8ESA3_PUMPED", 3),
    TF("A disadvantage of wind power is that it only works when the wind blows.", "True",
      "Wind power depends on the wind, so output varies and can stop on calm days.", "ERR_TECH_G8ESA3_WINDDIS", 2),
    {
      question: "Sort each power source as 'Renewable' or 'Non-renewable'.",
      input_type: "sort-buckets",
      buckets: [{ id: "ren", label: "Renewable" }, { id: "non", label: "Non-renewable" }],
      items: [
        { id: "i1", text: "Wind", correct_bucket: "ren" },
        { id: "i2", text: "Hydroelectric (water)", correct_bucket: "ren" },
        { id: "i3", text: "Coal", correct_bucket: "non" },
        { id: "i4", text: "Solar", correct_bucket: "ren" },
      ],
      expected: "Wind, water and solar are renewable; coal is non-renewable.",
      pass_threshold: 0.75,
      memo: "Renewable sources (wind, water, sun) won't run out; coal is a finite, non-renewable fuel.", error_signals: ["ERR_TECH_G8ESA3_SORT"], difficulty: 2,
    },
    {
      question: "Order how electricity reaches your home from a power station.",
      input_type: "sequence",
      items: [
        { id: "a", text: "A power station generates electricity" },
        { id: "b", text: "A step-up transformer raises the voltage" },
        { id: "c", text: "Power travels along the national grid" },
        { id: "d", text: "A step-down transformer lowers the voltage for homes" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Generate → step up → grid → step down → home. High voltage carries power efficiently, then it is lowered for safety.",
      error_signals: ["ERR_TECH_G8ESA3_SEQUENCE"], difficulty: 3,
    },
    MC("Why is power sent at high voltage across long distances?",
      ["It reduces energy lost in the wires", "It makes more pollution", "It uses less copper for the station", "It is more dangerous on purpose"], "It reduces energy lost in the wires",
      "High voltage reduces current and so reduces energy lost as heat in the wires.", "ERR_TECH_G8ESA3_WHYHIGH", 3),
    TF("Industry, schools and homes all need a reliable supply of electricity.", "True",
      "A reliable supply matters for industry (jobs), schools and homes alike.", "ERR_TECH_G8ESA3_RELIABLE", 1),
    MC("Nuclear power stations make heat to boil water using…",
      ["nuclear reactions", "wind", "sunlight", "coal"], "nuclear reactions",
      "Nuclear stations use nuclear reactions as the heat source for steam turbines.", "ERR_TECH_G8ESA3_NUCLEAR", 2),
    CLOZE("A transformer that lowers voltage for safe home use is a step-____ transformer.",
      ["down", "up", "side", "off"], "down",
      "Step-down transformers lower the voltage for homes.", "ERR_TECH_G8ESA3_DOWNWORD", 2),
    MC("A balanced view of coal power is that it is…",
      ["reliable and cheap but polluting", "free of all problems", "useless", "renewable"], "reliable and cheap but polluting",
      "Coal is reliable and relatively cheap, but it pollutes — a balanced view weighs both.", "ERR_TECH_G8ESA3_BALANCE", 2),
  ],

  // ES.A4 · Ohm's law (qualitative) & logic gates
  "TECH.G8.ES.A4": [
    MC("Ohm's law (in words) says that, if resistance stays the same, more voltage gives…",
      ["more current", "less current", "no current", "more resistance"], "more current",
      "With constant resistance, increasing voltage increases the current.", "ERR_TECH_G8ESA4_OHM", 2),
    TF("Adding more cells in series to a lamp makes it brighter (more current).", "True",
      "More cells in series raise the voltage and current, making the lamp brighter.", "ERR_TECH_G8ESA4_BRIGHTER", 2),
    MC("An AND logic gate gives an output ON only when…",
      ["both inputs are ON", "either input is ON", "both inputs are OFF", "one input is OFF"], "both inputs are ON",
      "An AND gate outputs ON only when ALL its inputs are ON.", "ERR_TECH_G8ESA4_AND", 2),
    MC("An OR logic gate gives an output ON when…",
      ["either (or both) input is ON", "both inputs are OFF", "only when both are ON", "never"], "either (or both) input is ON",
      "An OR gate outputs ON when at least one input is ON.", "ERR_TECH_G8ESA4_OR", 2),
    MC("Two switches in SERIES behave like which logic gate?",
      ["AND", "OR", "NOT", "None"], "AND",
      "Switches in series both must be closed for current to flow — AND logic.", "ERR_TECH_G8ESA4_SERIESAND", 3),
    MC("Two switches in PARALLEL behave like which logic gate?",
      ["OR", "AND", "NOT", "None"], "OR",
      "Switches in parallel let current flow if either is closed — OR logic.", "ERR_TECH_G8ESA4_PARALLELOR", 3),
    TF("A truth table lists the output for every combination of inputs.", "True",
      "A truth table shows the output for each possible input combination.", "ERR_TECH_G8ESA4_TRUTHTABLE", 1),
    CLOZE("A gate that needs BOTH inputs on to give an output is an ____ gate.",
      ["AND", "OR", "OFF", "NO"], "AND",
      "AND gates require all inputs ON.", "ERR_TECH_G8ESA4_ANDWORD", 2),
    CLOZE("A gate that gives an output if EITHER input is on is an ____ gate.",
      ["OR", "AND", "NOT", "OFF"], "OR",
      "OR gates give an output if at least one input is ON.", "ERR_TECH_G8ESA4_ORWORD", 2),
    MC("A panic alarm that should trigger if EITHER of two buttons is pressed uses…",
      ["OR logic", "AND logic", "no logic", "a motor"], "OR logic",
      "Either button triggering the alarm is OR logic.", "ERR_TECH_G8ESA4_PANIC", 3),
    MC("A machine that only starts when a key is in AND the lid is closed uses…",
      ["AND logic", "OR logic", "no logic", "a buzzer"], "AND logic",
      "Both conditions required = AND logic.", "ERR_TECH_G8ESA4_MACHINE", 3),
    TF("Ohm's law in Grade 8 is treated qualitatively (no calculations).", "True",
      "Grade 8 covers Ohm's law qualitatively; calculations come in Grade 9.", "ERR_TECH_G8ESA4_QUALITATIVE", 2),
    MC("If you keep the resistance the same and lower the voltage, the current will…",
      ["decrease", "increase", "stay the same", "stop the resistor"], "decrease",
      "Lower voltage with the same resistance means lower current.", "ERR_TECH_G8ESA4_LOWER", 2),
    {
      question: "Sort each set-up by its logic.",
      input_type: "sort-buckets",
      buckets: [{ id: "and", label: "AND logic" }, { id: "or", label: "OR logic" }],
      items: [
        { id: "i1", text: "Two switches in series", correct_bucket: "and" },
        { id: "i2", text: "Two switches in parallel", correct_bucket: "or" },
        { id: "i3", text: "Both conditions needed to work", correct_bucket: "and" },
        { id: "i4", text: "Either condition makes it work", correct_bucket: "or" },
      ],
      expected: "Series / both-needed = AND; parallel / either-works = OR.",
      pass_threshold: 0.75,
      memo: "AND = series, needs all inputs on. OR = parallel, needs any input on.", error_signals: ["ERR_TECH_G8ESA4_SORT"], difficulty: 3,
    },
    MC("For an AND gate with inputs (1, 0), the output is…",
      ["0 (off)", "1 (on)", "always 1", "undefined"], "0 (off)",
      "An AND gate needs both inputs at 1; with (1,0) the output is 0.", "ERR_TECH_G8ESA4_AND10", 3),
    MC("For an OR gate with inputs (1, 0), the output is…",
      ["1 (on)", "0 (off)", "always 0", "undefined"], "1 (on)",
      "An OR gate gives 1 if either input is 1; (1,0) gives 1.", "ERR_TECH_G8ESA4_OR10", 3),
    TF("More cells (more voltage) increase current only if the resistance does not change.", "True",
      "Ohm's law links them: voltage up → current up, provided resistance is constant.", "ERR_TECH_G8ESA4_CONSTANT", 2),
    CLOZE("A table showing the output for every input combination is a ____ table.",
      ["truth", "times", "gear", "scale"], "truth",
      "A truth table lists outputs for all input combinations.", "ERR_TECH_G8ESA4_TRUTHWORD", 1),
    MC("Logic gates are useful in technology because they…",
      ["make decisions based on input conditions", "store water", "make light only", "produce heat"], "make decisions based on input conditions",
      "Logic gates let circuits 'decide' based on whether inputs are on or off.", "ERR_TECH_G8ESA4_DECISION", 2),
    TF("An AND gate output is OFF if any one of its inputs is OFF.", "True",
      "If even one input is off, an AND gate's output is off.", "ERR_TECH_G8ESA4_ANYOFF", 2),
  ],

  // ════════════ PROCESSING, SOCIETY & ENVIRONMENT (Term 2) ════════════════════
  // PR.A1 · Materials & the environment
  "TECH.G8.PR.A1": [
    MC("A 'biodegradable' material is one that…",
      ["breaks down naturally over time", "lasts forever", "is always metal", "cannot rot"], "breaks down naturally over time",
      "Biodegradable materials are broken down naturally by living things over time.", "ERR_TECH_G8PRA1_BIODEG", 1),
    TF("Many natural materials have been replaced by new or improved man-made materials.", "True",
      "Modern technology has replaced many natural materials with new or improved ones.", "ERR_TECH_G8PRA1_REPLACE", 1),
    MC("Why is a biodegradable shopping bag better for the environment than an ordinary plastic one?",
      ["It breaks down instead of lasting for years as litter", "It is heavier", "It is more colourful", "It never decomposes"], "It breaks down instead of lasting for years as litter",
      "Biodegradable bags break down, reducing long-lasting plastic litter.", "ERR_TECH_G8PRA1_BAG", 2),
    MC("A problem with ordinary plastic shopping bags is that they…",
      ["last a very long time as litter and harm wildlife", "rot in a day", "are alive", "make oxygen"], "last a very long time as litter and harm wildlife",
      "Ordinary plastic bags persist as litter for years and can harm wildlife.", "ERR_TECH_G8PRA1_PLASTICPROBLEM", 2),
    TF("Some new materials are designed to be more environmentally friendly than the ones they replace.", "True",
      "New materials are often designed to be more environmentally friendly.", "ERR_TECH_G8PRA1_FRIENDLY", 1),
    CLOZE("A material that rots away naturally is ____.",
      ["biodegradable", "permanent", "magnetic", "electric"], "biodegradable",
      "Biodegradable = breaks down naturally.", "ERR_TECH_G8PRA1_BIOWORD", 1),
    MC("Charging shoppers for thicker, reusable bags aims to…",
      ["reduce the number of bags thrown away", "increase litter", "use more plastic", "make bags weaker"], "reduce the number of bags thrown away",
      "Charging for bags encourages reuse and reduces waste.", "ERR_TECH_G8PRA1_CHARGE", 2),
    MC("Which is an example of replacing a natural material with a new one?",
      ["Using plastic instead of wood for a chair", "Using wood instead of plastic", "Using stone for everything", "Using grass for wiring"], "Using plastic instead of wood for a chair",
      "Plastic replacing wood is an example of a man-made material replacing a natural one.", "ERR_TECH_G8PRA1_EXAMPLE", 2),
    TF("Non-biodegradable plastic can stay in the environment for hundreds of years.", "True",
      "Many plastics persist for hundreds of years because they do not biodegrade.", "ERR_TECH_G8PRA1_HUNDREDS", 2),
    CLOZE("Plastic that does NOT break down is called ____.",
      ["non-biodegradable", "biodegradable", "natural", "edible"], "non-biodegradable",
      "Non-biodegradable materials do not break down naturally.", "ERR_TECH_G8PRA1_NONBIO", 2),
    MC("A positive impact of new materials can be that they are…",
      ["stronger, lighter or more environmentally friendly", "always heavier", "always more polluting", "useless"], "stronger, lighter or more environmentally friendly",
      "New materials can bring benefits like strength, lightness or being eco-friendly.", "ERR_TECH_G8PRA1_POSITIVE", 2),
    MC("Litter from plastic harms the environment mainly by…",
      ["polluting land and water and harming animals", "feeding animals", "cleaning rivers", "making soil"], "polluting land and water and harming animals",
      "Plastic litter pollutes land and water and can harm or kill animals.", "ERR_TECH_G8PRA1_LITTER", 2),
    {
      question: "Sort each material as 'Biodegradable' or 'Non-biodegradable'.",
      input_type: "sort-buckets",
      buckets: [{ id: "bio", label: "Biodegradable" }, { id: "non", label: "Non-biodegradable" }],
      items: [
        { id: "i1", text: "Paper", correct_bucket: "bio" },
        { id: "i2", text: "Banana peel", correct_bucket: "bio" },
        { id: "i3", text: "Ordinary plastic bag", correct_bucket: "non" },
        { id: "i4", text: "Glass bottle", correct_bucket: "non" },
      ],
      expected: "Paper and banana peel are biodegradable; ordinary plastic and glass are not.",
      pass_threshold: 0.75,
      memo: "Biodegradable things rot away (paper, peel); plastic and glass do not biodegrade.", error_signals: ["ERR_TECH_G8PRA1_SORT"], difficulty: 2,
    },
    TF("Writing a report to evaluate a material helps weigh its good and bad effects.", "True",
      "A balanced report weighs a material's advantages and disadvantages.", "ERR_TECH_G8PRA1_REPORT", 1),
    MC("Choosing materials with the environment in mind is part of being a…",
      ["responsible designer", "careless designer", "fast runner", "loud speaker"], "responsible designer",
      "Considering environmental impact is part of responsible design.", "ERR_TECH_G8PRA1_RESPONSIBLE", 1),
    TF("A material being 'improved' can mean it is stronger or lasts longer than before.", "True",
      "Improved materials may be stronger, lighter or longer-lasting.", "ERR_TECH_G8PRA1_IMPROVED", 1),
    MC("Which choice reduces environmental harm the most when shopping?",
      ["Reusing a sturdy bag many times", "Taking a new plastic bag each time", "Throwing bags in rivers", "Burning bags at home"], "Reusing a sturdy bag many times",
      "Reusing a sturdy bag cuts down on plastic waste.", "ERR_TECH_G8PRA1_REUSE", 2),
    CLOZE("Replacing a natural material with a man-made one is common in ____ times.",
      ["modern", "ancient", "future-only", "no"], "modern",
      "Modern technology often replaces natural materials with man-made ones.", "ERR_TECH_G8PRA1_MODERN", 1),
    MC("A balanced report on plastic bags should include…",
      ["both the benefits and the environmental problems", "only the good points", "only the bad points", "neither"], "both the benefits and the environmental problems",
      "A balanced report weighs benefits and problems together.", "ERR_TECH_G8PRA1_BALANCED", 2),
    TF("Designers can choose biodegradable materials to reduce long-term pollution.", "True",
      "Choosing biodegradable materials helps reduce long-lasting pollution.", "ERR_TECH_G8PRA1_CHOOSE", 1),
  ],

  // PR.A2 · Recycling & packaging design
  "TECH.G8.PR.A2": [
    MC("Recycling means…",
      ["turning used materials into new products", "throwing things away", "burning waste", "burying waste"], "turning used materials into new products",
      "Recycling reprocesses used materials into new products.", "ERR_TECH_G8PRA2_DEF", 1),
    MC("What is the main job of packaging?",
      ["To protect and contain a product", "To make it heavier", "To hide the price", "To waste material"], "To protect and contain a product",
      "Packaging protects, contains and helps present a product.", "ERR_TECH_G8PRA2_JOB", 1),
    TF("Waste paper and cardboard can be recycled into new packaging products.", "True",
      "Paper and cardboard are commonly recycled into new packaging.", "ERR_TECH_G8PRA2_PAPER", 1),
    MC("Good packaging design uses…",
      ["just enough material to do the job", "as much material as possible", "no material", "only metal"], "just enough material to do the job",
      "Efficient packaging uses just enough material — protecting the product without waste.", "ERR_TECH_G8PRA2_EFFICIENT", 2),
    MC("The nature of the product mainly decides the packaging's…",
      ["design and material properties", "colour of the shop", "day it is sold", "price of fuel"], "design and material properties",
      "What the product is (fragile, heavy, food) decides the packaging design and materials.", "ERR_TECH_G8PRA2_PRODUCT", 2),
    CLOZE("Turning used cardboard into new boxes is called ____.",
      ["recycling", "burning", "burying", "wasting"], "recycling",
      "Recycling reprocesses used material into new products.", "ERR_TECH_G8PRA2_RECYCLEWORD", 1),
    TF("Recycling reduces the amount of waste sent to landfill.", "True",
      "Recycling keeps materials in use and out of landfill.", "ERR_TECH_G8PRA2_LANDFILL", 1),
    MC("Fragile packaging (for eggs or glass) needs to be…",
      ["protective and cushioning", "as thin as possible", "made of stone", "very heavy"], "protective and cushioning",
      "Fragile goods need cushioning, protective packaging.", "ERR_TECH_G8PRA2_FRAGILE", 2),
    MC("A 'development' is used in packaging to…",
      ["plan the flat shape that folds into the box", "colour the product", "weigh the product", "price the box"], "plan the flat shape that folds into the box",
      "A development (net) plans how the flat sheet folds into the package.", "ERR_TECH_G8PRA2_DEVELOPMENT", 2),
    TF("Using recycled materials for packaging is more environmentally friendly.", "True",
      "Recycled packaging reduces the need for new raw materials and cuts waste.", "ERR_TECH_G8PRA2_GREEN", 1),
    CLOZE("Packaging that uses too much material is ____ for the environment.",
      ["bad", "good", "perfect", "free"], "bad",
      "Over-packaging wastes material and harms the environment.", "ERR_TECH_G8PRA2_WASTE", 2),
    MC("Which is the most environmentally friendly packaging choice?",
      ["Recyclable cardboard", "Thick non-recyclable plastic", "Foam that never breaks down", "Extra layers of plastic"], "Recyclable cardboard",
      "Recyclable cardboard is more eco-friendly than non-recyclable plastics or foam.", "ERR_TECH_G8PRA2_CHOICE", 2),
    {
      question: "Order the steps to design and make simple packaging.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Investigate the product to be packaged" },
        { id: "b", text: "Design and draw the development (net)" },
        { id: "c", text: "Cut and fold the material" },
        { id: "d", text: "Assemble and test the packaging" },
      ],
      expected_order: ["a", "b", "c", "d"],
      memo: "Investigate the product, design the net, cut and fold, then assemble and test.",
      error_signals: ["ERR_TECH_G8PRA2_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each material by whether it is easily recyclable.",
      input_type: "sort-buckets",
      buckets: [{ id: "yes", label: "Easily recyclable" }, { id: "no", label: "Hard to recycle" }],
      items: [
        { id: "i1", text: "Cardboard", correct_bucket: "yes" },
        { id: "i2", text: "Paper", correct_bucket: "yes" },
        { id: "i3", text: "Mixed-material foam tray", correct_bucket: "no" },
        { id: "i4", text: "Dirty food-soaked wrapper", correct_bucket: "no" },
      ],
      expected: "Clean cardboard and paper recycle easily; mixed foam and food-soiled wrappers are hard to recycle.",
      pass_threshold: 0.75,
      memo: "Clean paper and cardboard recycle well; mixed materials and food-soiled items are hard to recycle.", error_signals: ["ERR_TECH_G8PRA2_SORT"], difficulty: 3,
    },
    MC("Packaging that is easy to open and reseal shows good…",
      ["ergonomics (ease of use)", "weight", "colour", "price"], "ergonomics (ease of use)",
      "Easy opening and resealing is good ergonomics — ease of use.", "ERR_TECH_G8PRA2_ERGO", 2),
    TF("Over-packaging a product wastes material and money.", "True",
      "Excess packaging wastes both material and money and harms the environment.", "ERR_TECH_G8PRA2_OVER", 1),
    MC("Recycling paper into packaging is an example of technology with a…",
      ["positive impact on society and the environment", "negative impact only", "no impact", "harmful impact"], "positive impact on society and the environment",
      "Recycling paper into packaging is a positive technological impact.", "ERR_TECH_G8PRA2_POSITIVE", 2),
    CLOZE("Packaging's main job is to protect and ____ a product.",
      ["contain", "eat", "drive", "melt"], "contain",
      "Packaging protects and contains the product.", "ERR_TECH_G8PRA2_CONTAIN", 1),
    MC("Why investigate how cardboard is recycled before designing packaging?",
      ["So your design can be recycled too", "To waste time", "To copy the colour", "There is no reason"], "So your design can be recycled too",
      "Understanding recycling helps you design packaging that can also be recycled.", "ERR_TECH_G8PRA2_INVESTIGATE", 2),
    TF("Designing packaging that uses recycled material and can be recycled again is good for the planet.", "True",
      "Recycled-in and recyclable-out packaging reduces waste and resource use.", "ERR_TECH_G8PRA2_LOOP", 1),
  ],

  // PR.A3 · Impact of technology
  "TECH.G8.PR.A3": [
    MC("Technology can have…",
      ["both positive and negative impacts", "only positive impacts", "only negative impacts", "no impact at all"], "both positive and negative impacts",
      "Technology brings both benefits and harms, which must be weighed.", "ERR_TECH_G8PRA3_BOTH", 1),
    MC("Which is a POSITIVE impact of technology?",
      ["Faster, easier communication", "More air pollution", "More waste", "More noise pollution"], "Faster, easier communication",
      "Easier communication is a positive impact of technology.", "ERR_TECH_G8PRA3_POSITIVE", 1),
    MC("Which is a NEGATIVE impact of technology?",
      ["Air and water pollution", "Better medicine", "More jobs", "Cleaner energy"], "Air and water pollution",
      "Pollution is a negative impact of technology.", "ERR_TECH_G8PRA3_NEGATIVE", 1),
    TF("We can sometimes design solutions to counteract the negative impact of a technology.", "True",
      "Designers can create solutions that reduce or counteract negative impacts.", "ERR_TECH_G8PRA3_COUNTERACT", 2),
    MC("A factory pours waste into a river. A good counter-solution is to…",
      ["treat the waste before releasing it", "release more waste", "ignore it", "close the river"], "treat the waste before releasing it",
      "Treating waste before release reduces the harmful impact on the river.", "ERR_TECH_G8PRA3_TREAT", 2),
    CLOZE("A solution that reduces a technology's harm helps to ____ its negative impact.",
      ["counteract", "increase", "ignore", "hide"], "counteract",
      "To counteract means to reduce or offset the negative impact.", "ERR_TECH_G8PRA3_COUNTERWORD", 2),
    TF("Every technology should be judged by weighing its benefits against its harms.", "True",
      "Balanced judgement weighs the benefits and harms of a technology.", "ERR_TECH_G8PRA3_WEIGH", 1),
    MC("Cars give us fast transport (positive) but also cause…",
      ["air pollution (negative)", "cleaner air", "more trees", "free fuel"], "air pollution (negative)",
      "Cars provide transport but pollute the air — a clear positive-and-negative example.", "ERR_TECH_G8PRA3_CARS", 2),
    MC("A technological product with a negative social impact might be one that…",
      ["replaces many workers, causing job losses", "creates safe jobs", "helps everyone equally", "cleans the air"], "replaces many workers, causing job losses",
      "Automation that causes job losses is a negative social impact.", "ERR_TECH_G8PRA3_JOBS", 3),
    TF("A class discussion can help find solutions to counteract a technology's harm.", "True",
      "Discussing ideas helps find ways to reduce a technology's negative impact.", "ERR_TECH_G8PRA3_DISCUSS", 1),
    CLOZE("Pollution from factories is a ____ impact of technology.",
      ["negative", "positive", "neutral", "helpful"], "negative",
      "Pollution is a negative impact.", "ERR_TECH_G8PRA3_NEGWORD", 1),
    MC("Reinforcing materials or improving a product can reduce…",
      ["the negative effects of a technology", "all benefits", "the user's safety", "the product's purpose"], "the negative effects of a technology",
      "Improving or adapting a product can reduce its negative effects.", "ERR_TECH_G8PRA3_IMPROVE", 2),
    {
      question: "Sort each effect of technology as positive or negative.",
      input_type: "sort-buckets",
      buckets: [{ id: "pos", label: "Positive" }, { id: "neg", label: "Negative" }],
      items: [
        { id: "i1", text: "Vaccines prevent disease", correct_bucket: "pos" },
        { id: "i2", text: "Factory smoke pollutes the air", correct_bucket: "neg" },
        { id: "i3", text: "Phones connect families far apart", correct_bucket: "pos" },
        { id: "i4", text: "E-waste piles up in dumps", correct_bucket: "neg" },
      ],
      expected: "Vaccines and phones are positive; factory smoke and e-waste are negative.",
      pass_threshold: 0.75,
      memo: "Weigh both sides: medicine and communication help; pollution and waste harm.", error_signals: ["ERR_TECH_G8PRA3_SORT"], difficulty: 2,
    },
    MC("Evaluating a solution to a negative impact, you should check its…",
      ["effectiveness, fairness and scope", "colour only", "price of paper", "weight only"], "effectiveness, fairness and scope",
      "A solution is evaluated for effectiveness, fairness, accuracy and scope.", "ERR_TECH_G8PRA3_EVALUATE", 3),
    TF("Some technologies help one part of society while harming another.", "True",
      "A technology can benefit one group while harming another — a sign to weigh carefully.", "ERR_TECH_G8PRA3_UNEVEN", 2),
    MC("The best response to a technology's negative impact is usually to…",
      ["redesign or add a solution to reduce the harm", "ignore it", "increase the harm", "blame the user"], "redesign or add a solution to reduce the harm",
      "Redesigning to reduce harm is the responsible response.", "ERR_TECH_G8PRA3_REDESIGN", 2),
    CLOZE("Better medicine is a ____ impact of technology.",
      ["positive", "negative", "harmful", "useless"], "positive",
      "Improved medicine is a positive impact.", "ERR_TECH_G8PRA3_POSWORD", 1),
    MC("Why is it important to think about impact when designing?",
      ["So benefits are kept and harms reduced", "To make designs cost more", "To slow work", "There is no reason"], "So benefits are kept and harms reduced",
      "Considering impact lets designers keep the benefits while reducing harm.", "ERR_TECH_G8PRA3_WHY", 1),
    TF("A solution that fixes one problem but creates a bigger one is not a good solution.", "True",
      "A good solution must not cause a worse problem than the one it solves.", "ERR_TECH_G8PRA3_BIGGER", 2),
    MC("Recycling and pollution control are technologies that mainly aim to…",
      ["reduce harm to the environment", "increase waste", "use more fuel", "make noise"], "reduce harm to the environment",
      "These technologies aim to reduce environmental harm.", "ERR_TECH_G8PRA3_ENV", 1),
  ],

  // PR.A4 · Mining impact, indigenous mining & bias
  "TECH.G8.PR.A4": [
    MC("South Africa is rich in mineral resources, so mining is important for…",
      ["jobs and the economy", "making rain", "growing trees", "cooling the air"], "jobs and the economy",
      "Mining provides jobs and is a major part of South Africa's economy.", "ERR_TECH_G8PRA4_ECONOMY", 1),
    MC("A negative environmental impact of mining is…",
      ["acid mine drainage polluting water", "cleaner rivers", "more forests", "fresh air"], "acid mine drainage polluting water",
      "Acid mine drainage pollutes water — a serious negative impact of mining.", "ERR_TECH_G8PRA4_ACID", 2),
    MC("Dust pollution from mine dumps mainly affects…",
      ["the air and health of nearby residents", "the price of gold", "the colour of the sky permanently", "the internet"], "the air and health of nearby residents",
      "Dust from mine dumps pollutes the air and harms nearby residents' health.", "ERR_TECH_G8PRA4_DUST", 2),
    TF("Mining can bring wealth but also harm the environment.", "True",
      "Mining brings economic benefits but has real environmental costs.", "ERR_TECH_G8PRA4_BALANCE", 1),
    MC("Indigenous mining of iron in South Africa before the modern era shows that…",
      ["local people had their own mining technology long ago", "no one mined before today", "mining is brand new", "iron was never used"], "local people had their own mining technology long ago",
      "Indigenous communities mined and worked iron long before the modern era.", "ERR_TECH_G8PRA4_IRONAGE", 2),
    MC("What is 'gender bias' in career choices related to mining?",
      ["Unfairly favouring one gender for jobs", "Paying everyone equally", "Hiring only by skill", "Having no rules"], "Unfairly favouring one gender for jobs",
      "Gender bias unfairly favours one gender over another for opportunities.", "ERR_TECH_G8PRA4_GENDER", 2),
    TF("Bias in technology means a group can be unfairly favoured or disadvantaged.", "True",
      "Bias means unfair favouring or disadvantaging of a group.", "ERR_TECH_G8PRA4_BIAS", 1),
    CLOZE("Acid mine ____ is polluted water that leaks from mines.",
      ["drainage", "rainfall", "sunshine", "wind"], "drainage",
      "Acid mine drainage is acidic, polluted water from mines.", "ERR_TECH_G8PRA4_DRAINWORD", 2),
    MC("Mining is described as dangerous because…",
      ["deep tunnels can collapse or have rock bursts", "it is too quiet", "it uses no people", "it is always safe"], "deep tunnels can collapse or have rock bursts",
      "Deep mining risks rock bursts and cave-ins, making it dangerous work.", "ERR_TECH_G8PRA4_DANGER", 2),
    TF("Studying indigenous mining shows that valuable technology existed before modern times.", "True",
      "Indigenous mining is evidence of advanced local technology in the past.", "ERR_TECH_G8PRA4_INDIGVALUE", 2),
    CLOZE("Unfairly favouring one group over another in technology is called ____.",
      ["bias", "balance", "fairness", "colour"], "bias",
      "Bias is unfair favouring or disadvantaging of a group.", "ERR_TECH_G8PRA4_BIASWORD", 1),
    MC("A fair, balanced report on mining would include…",
      ["both the benefits and the environmental harm", "only the good", "only the bad", "nothing"], "both the benefits and the environmental harm",
      "A balanced report weighs mining's benefits and its environmental harm.", "ERR_TECH_G8PRA4_REPORT", 2),
    {
      question: "Sort each statement about mining as a 'Benefit' or a 'Harm'.",
      input_type: "sort-buckets",
      buckets: [{ id: "benefit", label: "Benefit" }, { id: "harm", label: "Harm" }],
      items: [
        { id: "i1", text: "Creates jobs and income", correct_bucket: "benefit" },
        { id: "i2", text: "Acid mine drainage pollutes water", correct_bucket: "harm" },
        { id: "i3", text: "Supplies minerals for industry", correct_bucket: "benefit" },
        { id: "i4", text: "Dust harms residents' health", correct_bucket: "harm" },
      ],
      expected: "Jobs and minerals are benefits; acid drainage and dust are harms.",
      pass_threshold: 0.75,
      memo: "Mining benefits (jobs, minerals) must be weighed against harms (water and air pollution).", error_signals: ["ERR_TECH_G8PRA4_SORT"], difficulty: 2,
    },
    MC("How can mining companies reduce their environmental harm?",
      ["Treat waste water and control dust", "Pour more waste into rivers", "Ignore the dumps", "Make bigger dumps"], "Treat waste water and control dust",
      "Treating waste water and controlling dust reduces mining's harm.", "ERR_TECH_G8PRA4_REDUCE", 2),
    TF("Mining affects, directly or indirectly, the lives of many people in society.", "True",
      "Mining and its industries touch the lives of many across society.", "ERR_TECH_G8PRA4_SOCIETY", 1),
    MC("Removing gender bias in mining careers means…",
      ["giving fair opportunities to all genders", "hiring only men", "hiring only women", "having no workers"], "giving fair opportunities to all genders",
      "Fair opportunity for all genders removes gender bias.", "ERR_TECH_G8PRA4_FAIR", 2),
    CLOZE("Mining brings ____ but also harms the environment.",
      ["wealth", "rain", "trees", "silence"], "wealth",
      "Mining creates wealth but damages the environment.", "ERR_TECH_G8PRA4_WEALTH", 1),
    MC("Why investigate the impact of mining as part of Technology?",
      ["To understand technology's effect on society and the environment", "To learn nothing", "To copy art", "To waste time"], "To understand technology's effect on society and the environment",
      "Studying mining shows how technology affects society and the environment.", "ERR_TECH_G8PRA4_WHY", 1),
    TF("Indigenous people had intellectual property in their traditional mining knowledge.", "True",
      "Traditional mining knowledge is indigenous intellectual property deserving respect.", "ERR_TECH_G8PRA4_IP", 2),
    MC("A responsible mining technology would aim to…",
      ["get minerals while protecting people and the environment", "harm as much as possible", "ignore safety", "waste minerals"], "get minerals while protecting people and the environment",
      "Responsible mining balances getting minerals with protecting people and nature.", "ERR_TECH_G8PRA4_RESPONSIBLE", 2),
  ],
};

export default G8B;
