// ─── Technology SP — Grade 9 authored pools (part 1: DG · ST · MS) ───────────
// Graphics & Drawing · Structures (Term 1) · Mechanical Systems & Control (T2).
// Refs auto-assigned by build-technology-sp.mjs. Tap-only; no free text.
// All three DG skills are image-dependent (orthographic/isometric/exploded views):
// text-answerable items only here; image-only questions HELD (see manifest).

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G9 = {
  // ════════════════════ GRAPHICS & DRAWING ════════════════════════════════════
  // DG.A1 · First-angle orthographic projection (IMAGE-DEPENDENT — text items only)
  "TECH.G9.DG.A1": [
    MC("Orthographic projection shows an object using…",
      ["several flat 2D views (front, top, side)", "one 3D view only", "a photograph", "a colour painting"], "several flat 2D views (front, top, side)",
      "Orthographic projection represents a 3D object as separate flat views.", "ERR_TECH_G9DGA1_DEF", 1),
    MC("Which three views are normally drawn in orthographic projection?",
      ["Front, top and side", "Left, right and back only", "Inside, outside and middle", "Big, small and medium"], "Front, top and side",
      "The standard set is the front view, top view and side view.", "ERR_TECH_G9DGA1_THREEVIEWS", 1),
    TF("Orthographic views are drawn to scale with correct dimensions.", "True",
      "Orthographic views use a scale, correct line types and dimensions.", "ERR_TECH_G9DGA1_SCALE", 1),
    MC("The 'front view' of an object shows…",
      ["what you see looking straight at the front", "the underside", "the inside only", "a 3D corner"], "what you see looking straight at the front",
      "The front view is the straight-on view of the front face.", "ERR_TECH_G9DGA1_FRONT", 1),
    MC("The 'top view' (plan) shows the object…",
      ["looking down from directly above", "from below", "from the side", "from inside"], "looking down from directly above",
      "The top view (plan) is what you see looking straight down.", "ERR_TECH_G9DGA1_TOP", 2),
    MC("In first-angle projection, hidden edges are drawn with…",
      ["dashed lines", "thick solid lines", "wavy lines", "no lines"], "dashed lines",
      "Hidden detail uses dashed lines, as in earlier grades.", "ERR_TECH_G9DGA1_HIDDEN", 1),
    CLOZE("Orthographic drawings show an object as separate flat ____.",
      ["views", "colours", "shadows", "photos"], "views",
      "Orthographic projection uses separate flat views.", "ERR_TECH_G9DGA1_VIEWS", 1),
    MC("Why use orthographic projection for a working drawing?",
      ["It shows true sizes and shapes for accurate making", "It looks the most artistic", "It uses no measurements", "It hides the sizes"], "It shows true sizes and shapes for accurate making",
      "Orthographic views give true, measurable shapes for accurate manufacture.", "ERR_TECH_G9DGA1_WHY", 2),
    TF("Different line types (solid, dashed, chain) each have a meaning in orthographic drawing.", "True",
      "Solid = visible, dashed = hidden, chain = centre lines — each has a set meaning.", "ERR_TECH_G9DGA1_LINETYPES", 2),
    MC("A centre line in orthographic projection is drawn as a…",
      ["chain line (dash-dot)", "thick line", "dashed line", "wavy line"], "chain line (dash-dot)",
      "Centre lines use the chain (dash-dot) line.", "ERR_TECH_G9DGA1_CENTRE", 2),
    CLOZE("The view from directly above is the ____ view (plan).",
      ["top", "front", "side", "back"], "top",
      "The top view is the plan, seen from above.", "ERR_TECH_G9DGA1_TOPWORD", 1),
    MC("If a plan will NOT actually solve the problem, the drawing should be…",
      ["penalised, even if it is neat", "praised for neatness", "ignored", "scaled up"], "penalised, even if it is neat",
      "CAPS stresses the plan must work — a neat but non-working plan is penalised.", "ERR_TECH_G9DGA1_MUSTWORK", 3),
    TF("Orthographic projection is useful for showing the exact measurements of a part.", "True",
      "Because views are flat and to scale, exact measurements can be shown and read.", "ERR_TECH_G9DGA1_MEASURE", 2),
    MC("A simple cube drawn in orthographic projection would have a front, top and side view that are all…",
      ["squares", "circles", "triangles", "different shapes"], "squares",
      "Every orthographic view of a cube is a square.", "ERR_TECH_G9DGA1_CUBE", 2),
    MC("The main difference between orthographic and isometric drawing is that orthographic shows…",
      ["flat separate views, not a single 3D picture", "only colour", "only the top", "a photograph"], "flat separate views, not a single 3D picture",
      "Orthographic gives flat separate views; isometric gives one 3D picture.", "ERR_TECH_G9DGA1_VSISO", 2),
    CLOZE("Working drawings in Grade 9 use first-angle ____ projection.",
      ["orthographic", "musical", "magnetic", "electric"], "orthographic",
      "Grade 9 working drawings use first-angle orthographic projection.", "ERR_TECH_G9DGA1_ORTHOWORD", 1),
  ],

  // DG.A2 · Working drawings & design problems (IMAGE-DEPENDENT — text items only)
  "TECH.G9.DG.A2": [
    MC("The most important thing about a working drawing of a solution is that…",
      ["the solution will actually work", "it is colourful", "it is large", "it has no dimensions"], "the solution will actually work",
      "A working drawing must show a solution that genuinely solves the problem.", "ERR_TECH_G9DGA2_WORK", 1),
    MC("A wheelchair ramp design must have a gentle enough…",
      ["gradient (slope)", "colour", "weight", "smell"], "gradient (slope)",
      "A ramp's gradient must be gentle enough for a wheelchair to use safely.", "ERR_TECH_G9DGA2_GRADIENT", 2),
    TF("A design brief for a stair should state the number of steps and the riser height.", "True",
      "The brief specifies details like number of steps, riser height and ramp gradient.", "ERR_TECH_G9DGA2_BRIEF", 2),
    MC("The 'riser' of a stair is the…",
      ["vertical height of each step", "flat part you stand on", "handrail", "landing"], "vertical height of each step",
      "The riser is the vertical face/height of each step.", "ERR_TECH_G9DGA2_RISER", 2),
    MC("A working drawing should be drawn…",
      ["to scale with correct dimensions", "any size with no measurements", "only in 3D colour", "without thinking"], "to scale with correct dimensions",
      "Working drawings are to scale with correct dimensions and line types.", "ERR_TECH_G9DGA2_SCALE", 1),
    TF("Even a very neat plan should be marked down if it would not actually solve the problem.", "True",
      "CAPS is clear: a plan that won't work must be penalised, however neat.", "ERR_TECH_G9DGA2_NEAT", 2),
    CLOZE("A ramp that is too steep is NOT ____-for-purpose for a wheelchair.",
      ["fit", "big", "red", "long"], "fit",
      "Too steep means it fails fitness-for-purpose for a wheelchair user.", "ERR_TECH_G9DGA2_FFP", 2),
    MC("Why add a handrail to a stair or ramp design?",
      ["For safety and support of users", "For decoration only", "To add weight", "To save material"], "For safety and support of users",
      "A handrail improves safety and gives users support.", "ERR_TECH_G9DGA2_HANDRAIL", 2),
    MC("A flow chart in the design process shows…",
      ["the order of steps to make the solution", "the colour scheme", "the price only", "the weather"], "the order of steps to make the solution",
      "A flow chart sets out the sequence of manufacturing steps.", "ERR_TECH_G9DGA2_FLOWCHART", 2),
    TF("A working drawing helps the maker build the solution accurately.", "True",
      "Accurate, dimensioned working drawings guide accurate making.", "ERR_TECH_G9DGA2_ACCURATE", 1),
    CLOZE("The flat part of a step you stand on is the ____.",
      ["tread", "riser", "rail", "roof"], "tread",
      "The tread is the horizontal part of a step; the riser is the vertical part.", "ERR_TECH_G9DGA2_TREAD", 3),
    MC("If a wheelchair ramp design is drawn too steep, the correct response is to…",
      ["redesign it with a gentler slope", "leave it because it is neat", "make it steeper", "ignore wheelchair users"], "redesign it with a gentler slope",
      "A too-steep ramp must be redesigned to a usable, gentler slope.", "ERR_TECH_G9DGA2_REDESIGN", 2),
    MC("A good design solution balances being workable, safe and…",
      ["affordable", "the heaviest possible", "the most colourful", "the largest possible"], "affordable",
      "Solutions should be workable, safe and affordable (cost-effective).", "ERR_TECH_G9DGA2_BALANCE", 2),
    TF("Specifications in a design brief give measurable requirements the design must meet.", "True",
      "Specifications state measurable requirements (sizes, gradient, materials).", "ERR_TECH_G9DGA2_SPECS", 2),
    MC("A working drawing for a stair should include…",
      ["dimensions, scale and correct line types", "only a sketch with no sizes", "a photo", "just a colour"], "dimensions, scale and correct line types",
      "It needs dimensions, a scale and correct line conventions to be built from.", "ERR_TECH_G9DGA2_INCLUDE", 2),
    CLOZE("A plan must, above all, actually ____ the problem.",
      ["solve", "colour", "hide", "weigh"], "solve",
      "The plan must solve the problem — that is the top priority.", "ERR_TECH_G9DGA2_SOLVE", 1),
  ],

  // DG.A3 · Artistic & exploded assembly drawing (IMAGE-DEPENDENT — text items only)
  "TECH.G9.DG.A3": [
    MC("An 'exploded' assembly drawing shows the parts…",
      ["separated but lined up to show how they fit together", "blown up by a bomb", "all hidden", "in one solid lump"], "separated but lined up to show how they fit together",
      "An exploded view separates the parts along their assembly lines to show how they fit.", "ERR_TECH_G9DGA3_EXPLODED", 1),
    MC("An artistic impression is mainly used to…",
      ["show how the finished product will look", "give exact measurements", "list the budget", "hide the design"], "show how the finished product will look",
      "Artistic impressions communicate the look of the finished product.", "ERR_TECH_G9DGA3_ARTISTIC", 1),
    TF("Single vanishing point perspective can be used to draw a realistic 3D object.", "True",
      "Single-point perspective gives a realistic 3D impression.", "ERR_TECH_G9DGA3_PERSPECTIVE", 1),
    MC("Adding wood-grain texture, colour and shadows to a drawing makes it…",
      ["more realistic", "smaller", "flat and plain", "hidden"], "more realistic",
      "Texture, colour and shadows enhance realism in an artistic drawing.", "ERR_TECH_G9DGA3_REALISM", 1),
    MC("An exploded view is most useful for showing…",
      ["how to assemble a product from its parts", "the price", "the colour only", "the weather"], "how to assemble a product from its parts",
      "Exploded views show assembly order and how parts connect.", "ERR_TECH_G9DGA3_ASSEMBLY", 2),
    CLOZE("A drawing that separates parts to show how they fit is an ____ view.",
      ["exploded", "orthographic", "flat", "hidden"], "exploded",
      "An exploded view separates and aligns the parts.", "ERR_TECH_G9DGA3_EXPWORD", 1),
    TF("Artistic drawings are usually used to communicate, not to give building measurements.", "True",
      "Artistic impressions communicate appearance; working drawings give the measurements.", "ERR_TECH_G9DGA3_COMMUNICATE", 2),
    MC("Shadows added to a perspective drawing help to show…",
      ["depth and form", "the price", "the date", "the weight"], "depth and form",
      "Shadows give a sense of depth and three-dimensional form.", "ERR_TECH_G9DGA3_SHADOWS", 2),
    MC("Which drawing would best show a customer the final look of a product?",
      ["An artistic impression in perspective", "A flat orthographic view", "A budget table", "A flow chart"], "An artistic impression in perspective",
      "An artistic perspective impression best shows the final appearance.", "ERR_TECH_G9DGA3_CUSTOMER", 2),
    TF("An exploded view usually keeps the parts in line along the direction they fit together.", "True",
      "Parts in an exploded view stay aligned along their assembly axes.", "ERR_TECH_G9DGA3_INLINE", 2),
    CLOZE("Single ____ point perspective uses one point where lines meet in the distance.",
      ["vanishing", "starting", "centre", "corner"], "vanishing",
      "Single vanishing point perspective uses one vanishing point.", "ERR_TECH_G9DGA3_VANISH", 2),
    MC("Why might a designer include an exploded view in a presentation?",
      ["To show clearly how the product is put together", "To confuse the client", "To save ink", "To hide parts"], "To show clearly how the product is put together",
      "Exploded views clearly communicate how a product assembles.", "ERR_TECH_G9DGA3_WHY", 2),
    TF("Texture in a drawing can show whether a surface is wood, metal or rough.", "True",
      "Drawn texture suggests the material and surface finish (wood grain, metal sheen).", "ERR_TECH_G9DGA3_TEXTURE", 2),
    MC("Artistic and exploded drawings are both mainly about…",
      ["communicating the design to others", "exact manufacture", "costing", "testing materials"], "communicating the design to others",
      "Both communicate the design — its look and how it fits together.", "ERR_TECH_G9DGA3_BOTH", 2),
    MC("Compared with an orthographic drawing, an exploded 3D view is better at showing…",
      ["how parts relate and assemble", "exact flat measurements", "nothing useful", "only colour"], "how parts relate and assemble",
      "Exploded 3D views show relationships and assembly; orthographic gives flat measurements.", "ERR_TECH_G9DGA3_VSORTHO", 3),
    CLOZE("Colour, texture and ____ make an artistic drawing look realistic.",
      ["shadows", "numbers", "holes", "tabs"], "shadows",
      "Shadows (with colour and texture) add realism.", "ERR_TECH_G9DGA3_SHADOWWORD", 1),
  ],

  // ════════════════════════ STRUCTURES (Term 1) ═══════════════════════════════
  // ST.A1 · Forces: static, dynamic & loads
  "TECH.G9.ST.A1": [
    MC("A STATIC force is one that…",
      ["stays still or steady, like a parked car's weight", "is always moving", "is electrical", "is magnetic"], "stays still or steady, like a parked car's weight",
      "A static force is steady and unchanging, like the weight of a stationary object.", "ERR_TECH_G9STA1_STATIC", 1),
    MC("A DYNAMIC force is one that…",
      ["changes or moves, like wind gusts or traffic", "never changes", "is always zero", "is only colour"], "changes or moves, like wind gusts or traffic",
      "A dynamic force changes or moves, like wind, waves or moving traffic.", "ERR_TECH_G9STA1_DYNAMIC", 1),
    MC("An EVEN (uniform) load is spread…",
      ["evenly across the structure", "at one point only", "randomly", "never"], "evenly across the structure",
      "An even load is distributed evenly across the structure.", "ERR_TECH_G9STA1_EVEN", 2),
    MC("An UNEVEN (point) load acts…",
      ["mostly at one place", "evenly everywhere", "only at night", "as colour"], "mostly at one place",
      "An uneven (point) load concentrates at one place.", "ERR_TECH_G9STA1_UNEVEN", 2),
    TF("The weight of people walking on a bridge is a dynamic load.", "True",
      "Moving people create a changing, dynamic load on a bridge.", "ERR_TECH_G9STA1_BRIDGE", 2),
    TF("A heavy statue standing still on a plinth applies a static load.", "True",
      "A still statue's steady weight is a static load.", "ERR_TECH_G9STA1_STATUE", 1),
    CLOZE("A force that changes or moves is a ____ force.",
      ["dynamic", "static", "still", "fixed"], "dynamic",
      "Dynamic forces change or move; static forces are steady.", "ERR_TECH_G9STA1_DYNWORD", 1),
    MC("Internal cross-bracing helps a structure resist…",
      ["twisting (torsion) and racking", "rust", "colour fading", "magnetism"], "twisting (torsion) and racking",
      "Cross-bracing resists twisting and racking by triangulating the frame.", "ERR_TECH_G9STA1_BRACING", 2),
    MC("Wind blowing in gusts against a building is an example of a…",
      ["dynamic load", "static load", "magnetic load", "no load"], "dynamic load",
      "Gusting wind is a changing, dynamic load.", "ERR_TECH_G9STA1_WIND", 2),
    CLOZE("A load spread evenly over a structure is an ____ load.",
      ["even", "uneven", "point", "moving"], "even",
      "An even load is distributed uniformly.", "ERR_TECH_G9STA1_EVENWORD", 2),
    TF("Designers must consider both static and dynamic forces when designing a structure.", "True",
      "Real structures face both steady (static) and changing (dynamic) forces.", "ERR_TECH_G9STA1_BOTH", 1),
    MC("A bookshelf loaded with books all along it carries mainly a…",
      ["even (distributed) load", "single point load", "dynamic load", "no load"], "even (distributed) load",
      "Books spread along the shelf give an even, distributed load.", "ERR_TECH_G9STA1_SHELF", 2),
    MC("A person standing on one spot of a plank applies a…",
      ["point (uneven) load", "even load", "wind load", "no load"], "point (uneven) load",
      "Weight at one spot is a point (uneven) load.", "ERR_TECH_G9STA1_POINT", 2),
    {
      question: "Sort each force/load as static or dynamic.",
      input_type: "sort-buckets",
      buckets: [{ id: "static", label: "Static" }, { id: "dynamic", label: "Dynamic" }],
      items: [
        { id: "i1", text: "Weight of a parked car on a slab", correct_bucket: "static" },
        { id: "i2", text: "Gusting wind on a tower", correct_bucket: "dynamic" },
        { id: "i3", text: "A still statue's weight", correct_bucket: "static" },
        { id: "i4", text: "Traffic moving over a bridge", correct_bucket: "dynamic" },
      ],
      expected: "Steady weights are static; moving wind and traffic are dynamic.",
      pass_threshold: 0.75,
      memo: "Static = steady/unchanging; dynamic = moving/changing.", error_signals: ["ERR_TECH_G9STA1_SORT"], difficulty: 2,
    },
    MC("Why are dynamic loads often harder on a structure than static ones?",
      ["Changing forces can cause vibration and fatigue", "They are always smaller", "They never move", "They are imaginary"], "Changing forces can cause vibration and fatigue",
      "Dynamic loads change and can cause vibration and fatigue, stressing a structure.", "ERR_TECH_G9STA1_FATIGUE", 3),
    TF("Torsion is a twisting force that structures may need to resist.", "True",
      "Torsion (twisting) is one of the forces a structure may have to resist.", "ERR_TECH_G9STA1_TORSION", 2),
    CLOZE("A single concentrated load at one place is a ____ load.",
      ["point", "even", "spread", "zero"], "point",
      "A point load is concentrated at one place.", "ERR_TECH_G9STA1_POINTWORD", 2),
    MC("A crane lifting different weights through the day puts a ____ load on its structure.",
      ["dynamic (changing)", "static (steady)", "magnetic", "zero"], "dynamic (changing)",
      "Changing lifted weights create a dynamic load.", "ERR_TECH_G9STA1_CRANE", 2),
    TF("An even load is generally easier for a structure to carry than the same total weight at one point.", "True",
      "Spreading the load reduces concentrated stress, so an even load is usually easier to carry.", "ERR_TECH_G9STA1_EASIER", 3),
    MC("Why consider the type of load before choosing a material?",
      ["So the material and shape can resist that load", "To choose a colour", "To set the price", "There is no reason"], "So the material and shape can resist that load",
      "Knowing the load lets you choose a material/shape that can resist it.", "ERR_TECH_G9STA1_WHY", 2),
  ],

  // ST.A2 · Strength of materials & cross-sections
  "TECH.G9.ST.A2": [
    MC("Why is a steel I-beam shaped like an 'I'?",
      ["The shape resists bending while saving material", "It looks like a letter", "It is easier to rust", "It is heavier"], "The shape resists bending while saving material",
      "The I-shape puts material where bending stress is greatest, saving weight.", "ERR_TECH_G9STA2_IBEAM", 2),
    MC("A hollow tube can be strong and stiff while being…",
      ["light (saving material)", "solid all through", "very heavy", "magnetic"], "light (saving material)",
      "A tube's cross-section gives strength and stiffness for little weight.", "ERR_TECH_G9STA2_TUBE", 2),
    MC("'Angle iron' (an L-shaped section) is used because the shape…",
      ["resists bending better than a flat strip", "is round", "stores electricity", "is softer"], "resists bending better than a flat strip",
      "The L-shaped cross-section stiffens the section against bending.", "ERR_TECH_G9STA2_ANGLE", 2),
    TF("Changing the cross-section of a member can make it stronger without adding much weight.", "True",
      "The right cross-section (I, tube, L) adds stiffness efficiently.", "ERR_TECH_G9STA2_CROSSSECTION", 2),
    MC("Which force stretches a material?",
      ["Tension", "Compression", "Torsion", "Shear"], "Tension",
      "Tension is a pulling/stretching force.", "ERR_TECH_G9STA2_TENSION", 1),
    MC("Which force squashes a material?",
      ["Compression", "Tension", "Torsion", "Shear"], "Compression",
      "Compression squashes; tension stretches.", "ERR_TECH_G9STA2_COMPRESSION", 1),
    TF("Internal cross-bracing helps a member resist twisting (torsion).", "True",
      "Cross-bracing inside a member resists torsion (twisting).", "ERR_TECH_G9STA2_TORSION", 2),
    CLOZE("An I-shaped beam is also called a ____.",
      ["girder", "tube", "wedge", "cam"], "girder",
      "A large I-beam is commonly called a girder.", "ERR_TECH_G9STA2_GIRDER", 2),
    MC("A T-bar or I-beam is chosen partly to…",
      ["save material while staying strong", "use as much metal as possible", "rust faster", "look pretty only"], "save material while staying strong",
      "These sections resist forces efficiently, saving material.", "ERR_TECH_G9STA2_SAVE", 2),
    MC("A bending beam is squashed on one side and stretched on the other, meaning it has…",
      ["both compression and tension", "only tension", "only compression", "no forces"], "both compression and tension",
      "Bending creates compression on one face and tension on the other.", "ERR_TECH_G9STA2_BENDING", 3),
    TF("A round tube resists bending in all directions roughly equally.", "True",
      "A circular cross-section resists bending evenly in all directions.", "ERR_TECH_G9STA2_ROUND", 3),
    CLOZE("Putting material where bending is greatest, like in an ____-beam, saves weight.",
      ["I", "O", "Z", "U"], "I",
      "The I-beam puts material in the top and bottom flanges where bending stress is highest.", "ERR_TECH_G9STA2_ISHAPE", 2),
    MC("Which would be the strongest against bending for the same amount of steel?",
      ["A well-shaped I-beam", "A thin flat strip", "A loose pile of filings", "A ball of wire"], "A well-shaped I-beam",
      "An I-beam uses the steel most efficiently to resist bending.", "ERR_TECH_G9STA2_STRONGEST", 3),
    {
      question: "Sort each section/use by the main reason it is chosen.",
      input_type: "sort-buckets",
      buckets: [{ id: "stiff", label: "For stiffness/strength" }, { id: "save", label: "To save material/weight" }],
      items: [
        { id: "i1", text: "I-beam shape", correct_bucket: "stiff" },
        { id: "i2", text: "Hollow tube instead of solid bar", correct_bucket: "save" },
        { id: "i3", text: "Angle iron edge", correct_bucket: "stiff" },
        { id: "i4", text: "Thin-walled tube for a light frame", correct_bucket: "save" },
      ],
      expected: "I-beams and angle iron add stiffness; hollow/thin tubes save weight while staying strong.",
      pass_threshold: 0.66,
      memo: "Cross-sections are chosen both to add stiffness (I-beam, angle) and to save material (tubes).", error_signals: ["ERR_TECH_G9STA2_SORT"], difficulty: 3,
    },
    MC("Reinforced concrete adds steel because concrete is weak in…",
      ["tension", "compression", "colour", "weight"], "tension",
      "Concrete is strong in compression but weak in tension, so steel is added for tensile strength.", "ERR_TECH_G9STA2_CONCRETE", 3),
    TF("Choosing the right cross-section is part of designing a strong, efficient structure.", "True",
      "Cross-section choice is key to strong, material-efficient design.", "ERR_TECH_G9STA2_DESIGN", 1),
    MC("A bicycle frame uses tubes rather than solid rods mainly to be…",
      ["strong but light", "as heavy as possible", "more colourful", "magnetic"], "strong but light",
      "Tubes give the strength and stiffness needed while keeping the frame light.", "ERR_TECH_G9STA2_BIKE", 2),
    CLOZE("Concrete is strong in compression but weak in ____.",
      ["tension", "weight", "colour", "size"], "tension",
      "Concrete handles compression well but is weak in tension.", "ERR_TECH_G9STA2_TENWORD", 3),
    MC("The cross-section of a member is…",
      ["the shape you see when you cut straight through it", "its colour", "its length only", "its price"], "the shape you see when you cut straight through it",
      "The cross-section is the shape revealed by a straight cut through the member.", "ERR_TECH_G9STA2_DEF", 2),
    TF("Hollow sections can be as strong as solid ones for many loads while using less material.", "True",
      "For bending and many loads, hollow sections match solid ones with less material.", "ERR_TECH_G9STA2_HOLLOW", 3),
  ],

  // ST.A3 · Properties of construction materials
  "TECH.G9.ST.A3": [
    MC("'Density' of a material describes…",
      ["how much mass it has for its size", "its colour", "its price", "its age"], "how much mass it has for its size",
      "Density is mass per unit volume — how heavy a material is for its size.", "ERR_TECH_G9STA3_DENSITY", 1),
    MC("'Hardness' of a material means…",
      ["how well it resists scratching or denting", "how heavy it is", "its colour", "its smell"], "how well it resists scratching or denting",
      "Hardness is resistance to scratching, denting or wear.", "ERR_TECH_G9STA3_HARDNESS", 1),
    MC("'Stiffness' (rigidity) means…",
      ["how well it resists bending", "how shiny it is", "how cheap it is", "how old it is"], "how well it resists bending",
      "Stiffness is resistance to bending or flexing.", "ERR_TECH_G9STA3_STIFFNESS", 1),
    MC("'Flexibility' means a material can…",
      ["bend without breaking", "never bend", "always rust", "glow"], "bend without breaking",
      "Flexibility is the ability to bend without breaking.", "ERR_TECH_G9STA3_FLEXIBILITY", 1),
    MC("'Corrosion' is when a material (like iron)…",
      ["is damaged by reacting with its surroundings (rusting)", "gets stronger", "changes colour for fun", "becomes lighter on purpose"], "is damaged by reacting with its surroundings (rusting)",
      "Corrosion is damage from reaction with the environment, such as iron rusting.", "ERR_TECH_G9STA3_CORROSION", 1),
    TF("Painting or galvanising metal can help prevent corrosion.", "True",
      "Coatings like paint or galvanising protect metal from corrosion.", "ERR_TECH_G9STA3_PREVENT", 1),
    CLOZE("Resistance to scratching and denting is called ____.",
      ["hardness", "density", "flexibility", "colour"], "hardness",
      "Hardness is resistance to scratching/denting.", "ERR_TECH_G9STA3_HARDWORD", 1),
    MC("Why choose a low-density material for an aircraft part?",
      ["To keep it light", "To make it heavy", "To rust faster", "To cost more"], "To keep it light",
      "Low-density (light) materials reduce weight, which matters for aircraft.", "ERR_TECH_G9STA3_AIRCRAFT", 2),
    MC("A material that resists rusting well has good…",
      ["corrosion resistance", "low hardness", "high density only", "bright colour"], "corrosion resistance",
      "Corrosion resistance means it does not rust/corrode easily.", "ERR_TECH_G9STA3_RESIST", 2),
    TF("Stainless steel resists corrosion better than ordinary steel.", "True",
      "Stainless steel is alloyed to resist corrosion far better than plain steel.", "ERR_TECH_G9STA3_STAINLESS", 2),
    CLOZE("The ability to bend without breaking is ____.",
      ["flexibility", "hardness", "density", "corrosion"], "flexibility",
      "Flexibility is bending without breaking.", "ERR_TECH_G9STA3_FLEXWORD", 1),
    MC("For a diving board you would want a material that is…",
      ["strong and flexible", "very brittle", "easily corroded", "very soft"], "strong and flexible",
      "A diving board must flex and spring back without breaking — strong and flexible.", "ERR_TECH_G9STA3_DIVING", 2),
    MC("Galvanising protects steel by coating it with…",
      ["zinc", "gold", "paper", "water"], "zinc",
      "Galvanising coats steel with zinc to prevent rust.", "ERR_TECH_G9STA3_GALVANISE", 2),
    {
      question: "Match each property to what it measures.",
      input_type: "sort-buckets",
      buckets: [{ id: "bend", label: "Resists bending" }, { id: "scratch", label: "Resists scratching" }, { id: "rust", label: "Resists rusting" }],
      items: [
        { id: "i1", text: "Stiffness", correct_bucket: "bend" },
        { id: "i2", text: "Hardness", correct_bucket: "scratch" },
        { id: "i3", text: "Corrosion resistance", correct_bucket: "rust" },
      ],
      expected: "Stiffness resists bending; hardness resists scratching; corrosion resistance resists rusting.",
      pass_threshold: 0.66,
      memo: "Stiffness ↔ bending; hardness ↔ scratching/denting; corrosion resistance ↔ rusting.", error_signals: ["ERR_TECH_G9STA3_SORT"], difficulty: 3,
    },
    MC("Choosing a construction material means matching its properties to the…",
      ["job it must do", "colour of the sky", "day of the week", "name of the builder"], "job it must do",
      "Materials are chosen so their properties suit the job.", "ERR_TECH_G9STA3_MATCH", 1),
    TF("A material can be hard but also brittle (it shatters rather than bends).", "True",
      "Hardness and brittleness can go together — hard glass shatters rather than bending.", "ERR_TECH_G9STA3_BRITTLE", 3),
    MC("Why prevent corrosion in a steel bridge?",
      ["Rust weakens the steel over time", "Rust makes it stronger", "Rust looks nice", "There is no reason"], "Rust weakens the steel over time",
      "Corrosion eats away the steel, weakening the structure over time.", "ERR_TECH_G9STA3_WHYPREVENT", 2),
    CLOZE("Coating steel with zinc to stop rust is called ____.",
      ["galvanising", "painting only", "melting", "bending"], "galvanising",
      "Galvanising is a zinc coating that prevents rust.", "ERR_TECH_G9STA3_GALVWORD", 2),
    MC("A high-density material is…",
      ["heavy for its size", "light for its size", "always weak", "always cheap"], "heavy for its size",
      "High density means a lot of mass packed into a small volume — heavy for its size.", "ERR_TECH_G9STA3_HIGHDENSITY", 2),
    TF("Knowing a material's properties helps a designer choose the best one for a structure.", "True",
      "Property knowledge guides the best material choice for each job.", "ERR_TECH_G9STA3_CHOOSE", 1),
  ],

  // ST.A4 · Costing & the tender process
  "TECH.G9.ST.A4": [
    MC("A 'tender' is…",
      ["a priced offer to do a job or supply something", "a type of bridge", "a magnet", "a kind of gear"], "a priced offer to do a job or supply something",
      "A tender is a formal priced bid offering to do a job.", "ERR_TECH_G9STA4_DEF", 1),
    MC("Costing a project means working out the cost of…",
      ["materials and labour", "the weather", "the colour", "the day"], "materials and labour",
      "Costing adds up the materials and the labour (and other) costs.", "ERR_TECH_G9STA4_COSTING", 1),
    TF("Labour costs (paying the workers) are part of the total cost of a project.", "True",
      "Labour is a real cost that must be included alongside materials.", "ERR_TECH_G9STA4_LABOUR", 1),
    MC("Why must a tender include realistic prices?",
      ["So the bid is fair and the work can actually be done for the price", "To win by lying", "To look colourful", "There is no reason"], "So the bid is fair and the work can actually be done for the price",
      "Realistic pricing makes a tender honest and workable.", "ERR_TECH_G9STA4_REALISTIC", 2),
    MC("Ethical practice in tendering means…",
      ["being honest and fair, with no bribery", "paying bribes to win", "lying about costs", "ignoring the rules"], "being honest and fair, with no bribery",
      "Ethical tendering is honest and fair, free of bribery or cheating.", "ERR_TECH_G9STA4_ETHICS", 2),
    CLOZE("A priced offer to carry out a job is a ____.",
      ["tender", "ramp", "gear", "cam"], "tender",
      "A tender is a priced bid to do a job.", "ERR_TECH_G9STA4_TENDERWORD", 1),
    TF("Costing is part of design because cost affects whether a solution is practical.", "True",
      "Cost is a design factor — a solution must be affordable to be practical.", "ERR_TECH_G9STA4_PARTOFDESIGN", 2),
    MC("If material costs R5 000 and labour costs R3 000, the total cost is…",
      ["R8 000", "R2 000", "R15 000", "R5 003"], "R8 000",
      "Total = materials + labour = 5 000 + 3 000 = R8 000.", "ERR_TECH_G9STA4_TOTAL", 2),
    MC("Why consider real costs when learners design a solution?",
      ["It helps make informed, practical decisions and career choices", "To waste paper", "To copy others", "There is no reason"], "It helps make informed, practical decisions and career choices",
      "Considering real costs builds practical judgement useful for careers.", "ERR_TECH_G9STA4_WHY", 2),
    TF("A tender bid that is much too cheap may mean the job cannot be done properly.", "True",
      "An unrealistically low bid can signal corners will be cut or it won't be completed.", "ERR_TECH_G9STA4_TOOCHEAP", 3),
    CLOZE("The cost of paying workers is the ____ cost.",
      ["labour", "material", "colour", "fuel-only"], "labour",
      "Labour cost is the cost of the workers' time.", "ERR_TECH_G9STA4_LABWORD", 1),
    MC("A budget for a project is…",
      ["a plan of the expected costs", "a type of drawing", "a magnet", "a kind of bridge"], "a plan of the expected costs",
      "A budget plans the expected costs of a project.", "ERR_TECH_G9STA4_BUDGET", 1),
    MC("Companies submit tenders so that the client can…",
      ["compare bids and choose the best value", "pay the most", "avoid all work", "ignore costs"], "compare bids and choose the best value",
      "Tendering lets the client compare bids and pick the best value.", "ERR_TECH_G9STA4_COMPARE", 2),
    {
      question: "Sort each item as part of 'Material cost' or 'Labour cost'.",
      input_type: "sort-buckets",
      buckets: [{ id: "mat", label: "Material cost" }, { id: "lab", label: "Labour cost" }],
      items: [
        { id: "i1", text: "Bags of cement", correct_bucket: "mat" },
        { id: "i2", text: "Steel beams", correct_bucket: "mat" },
        { id: "i3", text: "Bricklayers' wages", correct_bucket: "lab" },
        { id: "i4", text: "Hours paid to the welder", correct_bucket: "lab" },
      ],
      expected: "Cement and steel are materials; wages and paid hours are labour.",
      pass_threshold: 0.75,
      memo: "Material cost = the stuff you buy; labour cost = paying the people who do the work.", error_signals: ["ERR_TECH_G9STA4_SORT"], difficulty: 2,
    },
    MC("Including transport of materials in a cost estimate makes the estimate more…",
      ["accurate", "colourful", "secret", "magnetic"], "accurate",
      "Adding transport costs makes the total estimate more accurate.", "ERR_TECH_G9STA4_TRANSPORT", 2),
    TF("A fair tender process treats all bidding companies equally.", "True",
      "Fair tendering gives all bidders equal, honest treatment.", "ERR_TECH_G9STA4_FAIR", 2),
    MC("If a solution costs far more than the client can afford, the designer should…",
      ["redesign to reduce cost while still solving the problem", "ignore the budget", "make it more expensive", "give up"], "redesign to reduce cost while still solving the problem",
      "A good designer cuts cost without losing the function — fit and affordable.", "ERR_TECH_G9STA4_REDESIGN", 2),
    CLOZE("Comparing tenders helps a client choose the best ____.",
      ["value", "colour", "weather", "noise"], "value",
      "Comparing tenders is about finding the best value.", "ERR_TECH_G9STA4_VALUE", 1),
    MC("A realistic budget for building work should list…",
      ["materials, labour and other costs like transport", "only the cheapest item", "only colours", "nothing"], "materials, labour and other costs like transport",
      "A realistic budget lists materials, labour and other costs such as transport.", "ERR_TECH_G9STA4_BUDGETLIST", 2),
    TF("Costing helps learners make informed FET subject and career choices.", "True",
      "Real costing builds judgement that supports good FET and career choices.", "ERR_TECH_G9STA4_CAREER", 1),
  ],

  // ════════════════ MECHANICAL SYSTEMS & CONTROL (Term 2) ═════════════════════
  // MS.A1 · Hydraulics & Pascal's principle
  "TECH.G9.MS.A1": [
    MC("Pascal's principle says that pressure on a liquid in a closed system is…",
      ["passed equally in all directions", "lost quickly", "turned into light", "only felt at the top"], "passed equally in all directions",
      "Pascal's principle: pressure applied to a confined liquid spreads equally in all directions.", "ERR_TECH_G9MSA1_PASCAL", 2),
    MC("Liquids are described as 'incompressible', which means they…",
      ["cannot easily be squashed", "squash very easily", "are gases", "disappear"], "cannot easily be squashed",
      "Liquids are nearly incompressible — they cannot be squashed much.", "ERR_TECH_G9MSA1_INCOMPRESS", 1),
    MC("Gases (like air) are different from liquids because gases…",
      ["can be compressed", "cannot be compressed", "are solid", "weigh nothing"], "can be compressed",
      "Gases are compressible; liquids are not.", "ERR_TECH_G9MSA1_GASCOMPRESS", 1),
    MC("In a hydraulic system, pushing a small piston can move a large piston with…",
      ["more force (force multiplication)", "less force always", "no force", "only light"], "more force (force multiplication)",
      "A small input piston driving a large output piston multiplies the force.", "ERR_TECH_G9MSA1_MULTIPLY", 3),
    TF("When a hydraulic system multiplies force, the large piston moves a shorter distance.", "True",
      "More force on the large piston comes with less movement — force is gained, distance is lost.", "ERR_TECH_G9MSA1_DISTANCE", 3),
    MC("A hydraulic JACK is used to…",
      ["lift heavy loads like a car with little effort", "make light", "cool the engine", "play music"], "lift heavy loads like a car with little effort",
      "A hydraulic jack multiplies force to lift heavy loads with little effort.", "ERR_TECH_G9MSA1_JACK", 2),
    MC("A hydraulic PRESS is used to…",
      ["squeeze or shape material with a large force", "cool water", "store data", "make sound"], "squeeze or shape material with a large force",
      "A hydraulic press uses multiplied force to squeeze or shape materials.", "ERR_TECH_G9MSA1_PRESS", 2),
    CLOZE("Pressure in a closed liquid system is passed ____ in all directions.",
      ["equally", "unequally", "slowly", "never"], "equally",
      "Pascal's principle: pressure is transmitted equally throughout the liquid.", "ERR_TECH_G9MSA1_EQUALLY", 2),
    TF("If the driver (input) cylinder is smaller than the output cylinder, the system multiplies force.", "True",
      "A small input and large output cylinder gives force multiplication (MA > 1).", "ERR_TECH_G9MSA1_SMALLINPUT", 3),
    MC("If the input cylinder is LARGER than the output cylinder, the system gives…",
      ["force division (less force, more movement)", "more force", "no movement", "light"], "force division (less force, more movement)",
      "A large input and small output divides force but increases movement.", "ERR_TECH_G9MSA1_DIVISION", 3),
    CLOZE("Liquids are nearly ____, so they transfer force well.",
      ["incompressible", "compressible", "invisible", "magnetic"], "incompressible",
      "Being incompressible lets liquids transfer force firmly.", "ERR_TECH_G9MSA1_INCWORD", 2),
    MC("Why are hydraulics (liquid) used for heavy lifting rather than pneumatics (air)?",
      ["Liquid does not compress, so the lift is firm and controlled", "Air is stronger", "Liquid is lighter", "Air never leaks"], "Liquid does not compress, so the lift is firm and controlled",
      "Incompressible liquid gives firm, controlled, powerful lifting.", "ERR_TECH_G9MSA1_WHYLIQUID", 3),
    TF("A systems diagram can describe how a hydraulic jack works (input, process, output).", "True",
      "A jack can be modelled as input (effort), process (pressure transfer), output (lift).", "ERR_TECH_G9MSA1_SYSTEM", 2),
    {
      question: "Sort each statement under 'Liquid (hydraulic)' or 'Gas (pneumatic)'.",
      input_type: "sort-buckets",
      buckets: [{ id: "liq", label: "Liquid / hydraulic" }, { id: "gas", label: "Gas / pneumatic" }],
      items: [
        { id: "i1", text: "Cannot be compressed much", correct_bucket: "liq" },
        { id: "i2", text: "Can be squashed (compressed)", correct_bucket: "gas" },
        { id: "i3", text: "Used in a car's hydraulic jack", correct_bucket: "liq" },
        { id: "i4", text: "Feels springy under pressure", correct_bucket: "gas" },
      ],
      expected: "Liquids are incompressible and used in jacks; gases compress and feel springy.",
      pass_threshold: 0.75,
      memo: "Hydraulic (liquid) = incompressible, firm; pneumatic (gas) = compressible, springy.", error_signals: ["ERR_TECH_G9MSA1_SORT"], difficulty: 3,
    },
    MC("Evaluating a hydraulic jack 'fit-for-purpose' asks questions like…",
      ["Who is it for? Will it do the job? Is it safe?", "What colour is the sky?", "What day is it?", "How loud is it?"], "Who is it for? Will it do the job? Is it safe?",
      "Fitness-for-purpose asks who it's for, whether it works, cost, safety and ease of use.", "ERR_TECH_G9MSA1_FFP", 2),
    TF("In a hydraulic system, equal volumes of liquid are moved through the connected cylinders.", "True",
      "The same volume of incompressible liquid moves through the system, giving the distance/force trade-off.", "ERR_TECH_G9MSA1_VOLUME", 3),
    MC("Brakes on many cars are hydraulic, which means the brake pedal force is…",
      ["carried by liquid to the brakes", "carried by magnets", "carried by light", "not carried at all"], "carried by liquid to the brakes",
      "Hydraulic brakes carry the pedal force through brake fluid to the wheels.", "ERR_TECH_G9MSA1_BRAKES", 2),
    CLOZE("A device that lifts a car with little effort is a hydraulic ____.",
      ["jack", "magnet", "gear", "cam"], "jack",
      "A hydraulic jack lifts heavy loads with little effort.", "ERR_TECH_G9MSA1_JACKWORD", 1),
    MC("The trade-off in a force-multiplying hydraulic system is…",
      ["more force but less distance moved", "more force and more distance", "less force and less distance", "no change"], "more force but less distance moved",
      "You gain force but the output moves a shorter distance.", "ERR_TECH_G9MSA1_TRADEOFF", 3),
    TF("Pascal's principle is the reason a small effort on a jack can lift a heavy car.", "True",
      "Pressure spreads equally, so a small force on a small piston lifts a large load on a big piston.", "ERR_TECH_G9MSA1_WHYJACK", 3),
  ],

  // MS.A2 · Pulleys & mechanical control devices
  "TECH.G9.MS.A2": [
    MC("A single FIXED pulley mainly…",
      ["changes the direction of the pull", "multiplies the force", "stores energy", "makes light"], "changes the direction of the pull",
      "A fixed pulley changes direction; it does not multiply force.", "ERR_TECH_G9MSA2_FIXED", 2),
    MC("A single MOVEABLE pulley mainly…",
      ["multiplies the lifting force", "only changes direction", "makes sound", "stores data"], "multiplies the lifting force",
      "A moveable pulley gives a mechanical advantage (force multiplication).", "ERR_TECH_G9MSA2_MOVEABLE", 2),
    MC("A block and tackle is a system of pulleys used to…",
      ["lift heavy loads with less effort", "make light", "cool water", "play music"], "lift heavy loads with less effort",
      "A block and tackle combines pulleys to multiply force for heavy lifting.", "ERR_TECH_G9MSA2_BLOCKTACKLE", 2),
    MC("In a block and tackle, more load-bearing rope sections means…",
      ["more mechanical advantage", "less advantage", "no lifting", "more colour"], "more mechanical advantage",
      "The more rope sections supporting the load, the greater the mechanical advantage.", "ERR_TECH_G9MSA2_ROPES", 3),
    MC("A ratchet and pawl lets a mechanism…",
      ["turn one way but not slip back the other way", "spin freely both ways", "make light", "store water"], "turn one way but not slip back the other way",
      "A ratchet and pawl allows movement one way and locks against the other.", "ERR_TECH_G9MSA2_RATCHET", 2),
    MC("A disc brake slows a wheel by…",
      ["pressing pads against a spinning disc (friction)", "using a magnet only", "adding air", "removing the wheel"], "pressing pads against a spinning disc (friction)",
      "Disc brakes squeeze pads onto a disc, using friction to slow the wheel.", "ERR_TECH_G9MSA2_DISC", 2),
    TF("A bicycle brake uses friction to slow the wheel.", "True",
      "Bicycle brakes press pads against the rim/disc, using friction to slow down.", "ERR_TECH_G9MSA2_BICYCLE", 1),
    MC("A cleat is a device used to…",
      ["grip and hold a rope in place", "spin a wheel", "make light", "store charge"], "grip and hold a rope in place",
      "A cleat grips and holds a rope (as on a boat or flagpole).", "ERR_TECH_G9MSA2_CLEAT", 2),
    CLOZE("A fixed pulley changes the ____ of a force.",
      ["direction", "colour", "weight", "price"], "direction",
      "A fixed pulley changes the direction of the force.", "ERR_TECH_G9MSA2_DIRWORD", 2),
    TF("A moveable pulley gives a mechanical advantage greater than one.", "True",
      "A moveable pulley multiplies force, giving MA > 1.", "ERR_TECH_G9MSA2_MA", 2),
    MC("Why combine pulleys into a block and tackle?",
      ["To lift very heavy loads with a small effort", "To make it heavier", "To use no rope", "For colour"], "To lift very heavy loads with a small effort",
      "Combining pulleys multiplies force so a small effort lifts a heavy load.", "ERR_TECH_G9MSA2_WHYBLOCK", 2),
    CLOZE("A device that lets a wheel turn one way only is a ____ and pawl.",
      ["ratchet", "pulley", "cleat", "cam"], "ratchet",
      "A ratchet and pawl allows one-way motion.", "ERR_TECH_G9MSA2_RATCHETWORD", 2),
    TF("Control devices like brakes and ratchets help control motion, not just create it.", "True",
      "Brakes, ratchets and cleats control or restrain motion.", "ERR_TECH_G9MSA2_CONTROL", 2),
    {
      question: "Sort each device by what it mainly does.",
      input_type: "sort-buckets",
      buckets: [{ id: "lift", label: "Helps lift (force)" }, { id: "control", label: "Controls/holds motion" }],
      items: [
        { id: "i1", text: "Moveable pulley", correct_bucket: "lift" },
        { id: "i2", text: "Block and tackle", correct_bucket: "lift" },
        { id: "i3", text: "Ratchet and pawl", correct_bucket: "control" },
        { id: "i4", text: "Disc brake", correct_bucket: "control" },
      ],
      expected: "Moveable pulleys and block-and-tackle help lift; ratchets and brakes control motion.",
      pass_threshold: 0.75,
      memo: "Pulleys multiply lifting force; ratchets, brakes and cleats control or hold motion.", error_signals: ["ERR_TECH_G9MSA2_SORT"], difficulty: 3,
    },
    MC("A fixed pulley at the top of a flagpole lets you…",
      ["pull down to raise the flag up", "store electricity", "make the flag glow", "cool the air"], "pull down to raise the flag up",
      "The fixed pulley changes your downward pull into an upward lift of the flag.", "ERR_TECH_G9MSA2_FLAGPOLE", 1),
    TF("Friction is the force that brakes use to slow a moving wheel.", "True",
      "Brakes rely on friction between pads and the disc/rim to slow motion.", "ERR_TECH_G9MSA2_FRICTION", 1),
    MC("A handbrake on a bicycle or car is an example of a…",
      ["mechanical control device", "power source", "light", "magnet"], "mechanical control device",
      "A brake is a mechanical control device that restrains motion.", "ERR_TECH_G9MSA2_HANDBRAKE", 1),
    CLOZE("Pulleys arranged to multiply force form a block and ____.",
      ["tackle", "magnet", "gear", "ramp"], "tackle",
      "A block and tackle is a pulley system that multiplies force.", "ERR_TECH_G9MSA2_TACKLEWORD", 2),
    MC("Adding more pulleys to a block and tackle generally…",
      ["increases the mechanical advantage but you pull more rope", "decreases the advantage", "stops it working", "makes it lighter to build"], "increases the mechanical advantage but you pull more rope",
      "More pulleys give more force advantage, but you must pull more rope through.", "ERR_TECH_G9MSA2_MOREPULLEYS", 3),
    TF("A cleat is useful for holding a raised load or sail in place without it slipping.", "True",
      "A cleat grips the rope so a raised load or sail stays put.", "ERR_TECH_G9MSA2_HOLD", 2),
  ],

  // MS.A3 · Advanced gears
  "TECH.G9.MS.A3": [
    MC("BEVEL gears are used to…",
      ["turn the drive through a corner (90°)", "store electricity", "make light", "stop motion"], "turn the drive through a corner (90°)",
      "Bevel gears transfer rotation around a 90° corner.", "ERR_TECH_G9MSA3_BEVEL", 2),
    MC("A RACK-and-PINION turns…",
      ["rotary motion into straight-line (linear) motion", "light into sound", "heat into cold", "nothing"], "rotary motion into straight-line (linear) motion",
      "A rack (straight bar) and pinion (round gear) convert rotation into straight-line motion.", "ERR_TECH_G9MSA3_RACK", 2),
    MC("A WORM gear system is used for…",
      ["a large reduction in speed and big increase in force", "high speed only", "no change", "making light"], "a large reduction in speed and big increase in force",
      "A worm gear gives a large speed reduction and force increase in a compact form.", "ERR_TECH_G9MSA3_WORM", 2),
    TF("Rack-and-pinion steering turns the steering wheel's rotation into straight movement of the wheels.", "True",
      "Car rack-and-pinion steering converts rotation into the linear movement that steers the wheels.", "ERR_TECH_G9MSA3_STEERING", 2),
    MC("Where might you find bevel gears?",
      ["A hand drill or where drive turns a corner", "A flat conveyor only", "A torch bulb", "A magnet"], "A hand drill or where drive turns a corner",
      "Bevel gears appear where drive must turn a corner, like in a hand drill.", "ERR_TECH_G9MSA3_DRILL", 2),
    CLOZE("Gears that turn the drive through 90° are ____ gears.",
      ["bevel", "spur", "worm", "rack"], "bevel",
      "Bevel gears turn the drive through a 90° corner.", "ERR_TECH_G9MSA3_BEVELWORD", 2),
    TF("A worm gear usually cannot be driven backwards by the output (it is self-locking).", "True",
      "Worm gears are often self-locking — the output cannot easily drive the worm.", "ERR_TECH_G9MSA3_SELFLOCK", 3),
    MC("An automatic gate that slides open often uses a…",
      ["rack-and-pinion", "worm-only with no rack", "bevel only", "magnet"], "rack-and-pinion",
      "Sliding gates use rack-and-pinion to turn motor rotation into straight gate movement.", "ERR_TECH_G9MSA3_GATE", 3),
    CLOZE("A straight toothed bar driven by a round gear is a ____ and pinion.",
      ["rack", "worm", "bevel", "spur"], "rack",
      "The straight bar is the rack; the round gear is the pinion.", "ERR_TECH_G9MSA3_RACKWORD", 2),
    MC("Which gear gives the biggest speed reduction in a small space?",
      ["Worm gear", "Two equal spur gears", "An idler", "A rack"], "Worm gear",
      "A worm gear gives a very large speed reduction compactly.", "ERR_TECH_G9MSA3_BIGRED", 3),
    TF("Bevel gears can be equal or unequal in size, changing speed and force when unequal.", "True",
      "Unequal bevel gears change speed/force as well as turning the drive 90°.", "ERR_TECH_G9MSA3_UNEQUAL", 3),
    MC("A worm gear drives a worm wheel to give…",
      ["lots of force and low speed", "high speed and low force", "no motion", "light"], "lots of force and low speed",
      "Worm gearing trades speed for a large increase in force.", "ERR_TECH_G9MSA3_FORCE", 2),
    {
      question: "Match each gear type to its main use.",
      input_type: "sort-buckets",
      buckets: [{ id: "corner", label: "Turn drive 90°" }, { id: "linear", label: "Rotation → straight line" }, { id: "reduce", label: "Big speed reduction" }],
      items: [
        { id: "i1", text: "Bevel gears", correct_bucket: "corner" },
        { id: "i2", text: "Rack and pinion", correct_bucket: "linear" },
        { id: "i3", text: "Worm gear", correct_bucket: "reduce" },
      ],
      expected: "Bevel = turn a corner; rack-and-pinion = rotation to straight line; worm = big speed reduction.",
      pass_threshold: 0.66,
      memo: "Bevel turns drive 90°; rack-and-pinion makes linear motion; worm gives a large reduction.", error_signals: ["ERR_TECH_G9MSA3_SORT"], difficulty: 3,
    },
    MC("Rack-and-pinion is useful in steering because it gives…",
      ["precise straight-line control from rotation", "no control", "only speed", "light"], "precise straight-line control from rotation",
      "Rack-and-pinion converts rotation to precise linear movement, good for steering.", "ERR_TECH_G9MSA3_PRECISE", 2),
    TF("A worm gear system is compact, making it useful where space is limited.", "True",
      "Worm gears pack a big reduction into a small space.", "ERR_TECH_G9MSA3_COMPACT", 2),
    MC("Bevel gears in a hand drill let you…",
      ["turn a vertical handle to spin a horizontal bit", "store charge", "make light", "cool the bit"], "turn a vertical handle to spin a horizontal bit",
      "Bevel gears change the drive direction so a turning handle spins the drill bit.", "ERR_TECH_G9MSA3_HANDDRILL", 3),
    CLOZE("A gear system that is hard to drive backwards is said to be self-____.",
      ["locking", "lighting", "cooling", "cleaning"], "locking",
      "A self-locking gear (like a worm) cannot easily be driven in reverse.", "ERR_TECH_G9MSA3_LOCKWORD", 3),
    MC("Why might a winch use a worm gear?",
      ["It holds the load and gives strong, slow lifting", "It spins very fast", "It makes light", "It needs no effort at all"], "It holds the load and gives strong, slow lifting",
      "A worm gear's force and self-locking suit a winch holding heavy loads.", "ERR_TECH_G9MSA3_WINCH", 3),
    TF("Different gear types let designers turn corners, change motion type, or trade speed for force.", "True",
      "Bevel, rack-and-pinion and worm gears each solve a different motion problem.", "ERR_TECH_G9MSA3_VARIETY", 2),
    MC("A conveyor that must move in a straight line from a motor's rotation could use a…",
      ["rack-and-pinion", "single magnet", "bevel only with no rack", "cleat"], "rack-and-pinion",
      "Rack-and-pinion converts the motor's rotation into straight-line movement.", "ERR_TECH_G9MSA3_CONVEYOR", 3),
  ],

  // MS.A4 · Integrated systems
  "TECH.G9.MS.A4": [
    MC("An 'integrated system' combines…",
      ["two or more sub-systems, e.g. mechanical and electrical", "only one mechanism", "only colours", "nothing"], "two or more sub-systems, e.g. mechanical and electrical",
      "Integrated systems combine sub-systems (mechanical, electrical, hydraulic/pneumatic).", "ERR_TECH_G9MSA4_DEF", 1),
    MC("Why combine sub-systems in one machine?",
      ["Each part does what it is best at, giving a better solution", "To make it weaker", "To use more colours", "For no reason"], "Each part does what it is best at, giving a better solution",
      "Combining sub-systems lets each handle the part of the job it does best.", "ERR_TECH_G9MSA4_WHY", 2),
    TF("A car combines mechanical, electrical and hydraulic systems.", "True",
      "A car integrates mechanical (engine, gears), electrical (lights) and hydraulic (brakes) systems.", "ERR_TECH_G9MSA4_CAR", 1),
    MC("An electric gate with a motor and a rack-and-pinion combines…",
      ["electrical and mechanical sub-systems", "two magnets only", "only colour", "nothing"], "electrical and mechanical sub-systems",
      "An electric motor (electrical) driving a rack-and-pinion (mechanical) is an integrated system.", "ERR_TECH_G9MSA4_GATE", 2),
    MC("A digger (excavator) arm combines a mechanical structure with…",
      ["a hydraulic system to move it", "no other system", "only paint", "only sound"], "a hydraulic system to move it",
      "An excavator combines a mechanical arm with hydraulics for powerful movement.", "ERR_TECH_G9MSA4_DIGGER", 2),
    CLOZE("A machine that combines mechanical and electrical parts is an ____ system.",
      ["integrated", "single", "empty", "broken"], "integrated",
      "Combining sub-systems makes an integrated system.", "ERR_TECH_G9MSA4_INTWORD", 1),
    TF("A control device like a switch or ratchet can be part of an integrated system.", "True",
      "Integrated systems often include control devices (switches, ratchets).", "ERR_TECH_G9MSA4_CONTROL", 2),
    MC("The mechanical part of an integrated machine might include…",
      ["levers, gears, cams, cranks or pulleys", "only wires", "only a battery", "only paint"], "levers, gears, cams, cranks or pulleys",
      "Mechanical sub-systems use levers, gears, cams, cranks and pulleys.", "ERR_TECH_G9MSA4_MECHPARTS", 2),
    MC("The electrical part of an integrated machine might include…",
      ["a motor, switch or sensor", "only gears", "only a lever", "only a pulley"], "a motor, switch or sensor",
      "Electrical sub-systems use motors, switches and sensors.", "ERR_TECH_G9MSA4_ELECPARTS", 2),
    TF("A systems diagram is helpful for understanding an integrated machine.", "True",
      "Systems diagrams break an integrated machine into input-process-output parts.", "ERR_TECH_G9MSA4_SYSTEM", 1),
    CLOZE("A washing machine combines an electric motor with a ____ system to spin the drum.",
      ["mechanical", "musical", "magnetic-only", "chemical"], "mechanical",
      "A washing machine integrates an electrical motor with a mechanical drive to the drum.", "ERR_TECH_G9MSA4_WASHING", 2),
    MC("When designing an integrated system, you must make sure the parts…",
      ["work together correctly", "never touch", "are all the same", "are all magnets"], "work together correctly",
      "The sub-systems must be matched so they work together correctly.", "ERR_TECH_G9MSA4_TOGETHER", 2),
    {
      question: "Sort each part of an electric winch into its sub-system.",
      input_type: "sort-buckets",
      buckets: [{ id: "elec", label: "Electrical" }, { id: "mech", label: "Mechanical" }],
      items: [
        { id: "i1", text: "Electric motor", correct_bucket: "elec" },
        { id: "i2", text: "On/off switch", correct_bucket: "elec" },
        { id: "i3", text: "Gears and drum", correct_bucket: "mech" },
        { id: "i4", text: "Ratchet that holds the load", correct_bucket: "mech" },
      ],
      expected: "Motor and switch are electrical; gears, drum and ratchet are mechanical.",
      pass_threshold: 0.75,
      memo: "Electrical sub-system: motor, switch, sensor. Mechanical sub-system: gears, drum, ratchet.", error_signals: ["ERR_TECH_G9MSA4_SORT"], difficulty: 3,
    },
    MC("A solution that uses a motor (electrical) to drive a pulley (mechanical) is best described as…",
      ["an integrated system", "a single mechanism", "only electrical", "only mechanical"], "an integrated system",
      "Combining a motor and a pulley makes an integrated electrical-mechanical system.", "ERR_TECH_G9MSA4_MOTORPULLEY", 2),
    TF("Integrating systems can make a machine able to do a job that one system alone could not.", "True",
      "Combining sub-systems can achieve what a single system could not on its own.", "ERR_TECH_G9MSA4_CAPABILITY", 2),
    MC("A pneumatic arm controlled by an electrical switch combines…",
      ["pneumatic and electrical sub-systems", "two pulleys", "only colour", "only sound"], "pneumatic and electrical sub-systems",
      "Air power plus an electrical switch is an integrated pneumatic-electrical system.", "ERR_TECH_G9MSA4_PNEU", 2),
    CLOZE("Combining sub-systems lets each do what it does ____.",
      ["best", "worst", "slowest", "loudest"], "best",
      "Each sub-system handles the part of the task it does best.", "ERR_TECH_G9MSA4_BESTWORD", 1),
    MC("Before building an integrated machine, drawing a systems diagram helps to…",
      ["plan how the parts connect and flow", "choose a colour", "set the price", "pick the day"], "plan how the parts connect and flow",
      "A systems diagram plans how the sub-systems connect and pass input to output.", "ERR_TECH_G9MSA4_PLAN", 2),
    TF("A lift (elevator) is an integrated system using electrical, mechanical and control parts.", "True",
      "A lift combines an electric motor, mechanical cables/pulleys and control systems.", "ERR_TECH_G9MSA4_LIFT", 2),
    MC("The key challenge of an integrated design is making sure the sub-systems are…",
      ["matched and compatible", "as different as possible", "never connected", "all electrical"], "matched and compatible",
      "Sub-systems must be matched and compatible to work together.", "ERR_TECH_G9MSA4_MATCH", 2),
  ],
};

export default G9;
