// ─── Technology SP — Grade 7 authored question pools (part 1: DG · ST · MS) ───
//
// Keyed by skill id → question array. Refs are auto-assigned by the generator
// (build-technology-sp.mjs), so questions here omit `ref`. Every item is
// tap-only: choice / true-false / cloze / sequence / sort-buckets. No free text.
//
// Mechanic payload shapes (see types/technology-sp.ts):
//   choice/true-false/cloze : options[] + expected
//   sequence                : items[{id,text}] + expected_order[ids]
//   sort-buckets            : buckets[{id,label}] + items[{id,text,correct_bucket}] + pass_threshold
//
// CAPS Grade 7 strands here:
//   Design Process & Graphics · Structures · Mechanical Systems & Control
// The practical "make a model" work is reframed into tap knowledge questions.

const TF = (question, expected, memo, err, difficulty = 1) => ({
  question, input_type: "true-false", options: ["True", "False"], expected, memo, error_signals: [err], difficulty,
});
const MC = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "choice", options, expected, memo, error_signals: [err], difficulty,
});
const CLOZE = (question, options, expected, memo, err, difficulty = 1) => ({
  question, input_type: "cloze", options, expected, memo, error_signals: [err], difficulty,
});

const G7 = {
  // ════════════════ DESIGN PROCESS & GRAPHICS (Term 1) ════════════════════════
  // DG.A1 · What is Technology?
  "TECH.G7.DG.A1": [
    MC("What does Technology mean as a school subject?",
      ["Using knowledge and skills to solve people's real problems", "Only using computers and phones", "Copying pictures neatly", "Learning facts off by heart"], "Using knowledge and skills to solve people's real problems",
      "Technology means using knowledge, skills, values and resources to solve people's needs and wants with practical solutions.", "ERR_TECH_G7DGA1_DEF", 1),
    TF("Technology is about solving real problems for people, not just memorising facts.", "True",
      "Technology is a 'doing' subject — it uses knowledge to build practical solutions to real needs and wants.", "ERR_TECH_G7DGA1_DOING", 1),
    MC("Which of these is the BEST example of technology solving a need?",
      ["Designing a cheap water filter for a village", "Reciting the alphabet", "Painting a sunset for fun", "Singing a song"], "Designing a cheap water filter for a village",
      "Technology meets a real need (clean water) with a practical solution — that is exactly what the subject is about.", "ERR_TECH_G7DGA1_EXAMPLE", 2),
    CLOZE("Technology uses knowledge, skills and resources to meet people's needs and ____.",
      ["wants", "songs", "colours", "names"], "wants",
      "Technology develops practical solutions to people's needs AND wants.", "ERR_TECH_G7DGA1_NEEDS_WANTS", 1),
    MC("Which job uses technology and design every day?",
      ["A civil engineer designing a bridge", "A person watching TV", "A reader of comic books", "A sleeper"], "A civil engineer designing a bridge",
      "Engineers, architects and technicians all use the design process to solve problems — these are technology careers.", "ERR_TECH_G7DGA1_CAREER", 1),
    TF("Engineers, architects and electricians are all careers that use technology.", "True",
      "Technology introduces learners to careers like civil, mechanical and electrical engineering and architecture.", "ERR_TECH_G7DGA1_CAREERS_TRUE", 1),
    MC("Why was Technology added to the school curriculum?",
      ["To build a technologically literate population and future engineers and artisans", "To give learners less to do", "To replace reading", "To stop people inventing things"], "To build a technologically literate population and future engineers and artisans",
      "Technology was introduced to produce engineers, technicians and artisans, and a technologically literate society.", "ERR_TECH_G7DGA1_WHY", 2),
    CLOZE("A person who designs and builds machines is a ____ engineer.",
      ["mechanical", "happy", "tall", "loud"], "mechanical",
      "Mechanical engineers design machines; civil engineers design structures; electrical engineers design wiring.", "ERR_TECH_G7DGA1_MECH", 2),
    MC("Technology asks us to think about society and the environment when we design. Why?",
      ["Our solutions affect people and the planet", "It makes the work longer", "Teachers say so", "It has no real reason"], "Our solutions affect people and the planet",
      "Good technology weighs the impact on society and the environment — solutions must not harm people or the planet.", "ERR_TECH_G7DGA1_SOCIETY", 2),
    TF("In Technology you must be able to USE knowledge, not just remember it.", "True",
      "Knowledge matters, but Technology assesses whether you can apply it to solve a problem.", "ERR_TECH_G7DGA1_USE", 1),
    MC("Which skill is NOT a main part of technology?",
      ["Guessing without any plan", "Investigating", "Designing", "Making"], "Guessing without any plan",
      "Technology uses investigating, designing, making, evaluating and communicating — not random guessing.", "ERR_TECH_G7DGA1_NOTSKILL", 2),
    MC("A 'technologically literate' person is someone who can…",
      ["understand and use technology sensibly in daily life", "build a rocket alone", "name every machine ever made", "avoid all technology"], "understand and use technology sensibly in daily life",
      "Technological literacy means being able to understand, use and judge technology in everyday life.", "ERR_TECH_G7DGA1_LITERATE", 2),
    CLOZE("Technology helps prepare learners to make ____ choices at the end of Grade 9.",
      ["career", "lunch", "sleeping", "music"], "career",
      "Technology gives learners experience that helps them choose FET subjects and careers at the end of Grade 9.", "ERR_TECH_G7DGA1_CAREER_CHOICE", 2),
    TF("Technology only happens inside a classroom and never in the real world.", "False",
      "Technology uses authentic, real-world contexts — problems from outside the classroom.", "ERR_TECH_G7DGA1_REALWORLD", 1),
    MC("Which is a 'want' rather than a 'need'?",
      ["A games console", "Clean water", "Food", "Shelter"], "A games console",
      "Needs are things we must have to live (water, food, shelter); wants make life nicer but are not essential.", "ERR_TECH_G7DGA1_WANT", 1),
    MC("An artisan is best described as…",
      ["a skilled worker who makes or fixes things by hand", "someone who never works", "a type of computer", "a kind of bridge"], "a skilled worker who makes or fixes things by hand",
      "Artisans are skilled trades-people (like welders or electricians) — a key technology career path.", "ERR_TECH_G7DGA1_ARTISAN", 2),
    TF("Technology develops creative and critical thinking and teamwork.", "True",
      "The subject builds creative thinking, problem solving, time and resource management, and teamwork.", "ERR_TECH_G7DGA1_THINKING", 1),
    CLOZE("Designing the electrical wiring for a lamp is the work of an ____.",
      ["electrician", "author", "actor", "athlete"], "electrician",
      "An electrician designs and installs electrical wiring — an electrical-technology career.", "ERR_TECH_G7DGA1_ELECTRICIAN", 2),
    {
      question: "Sort each activity into 'Technology' or 'Not technology'.",
      input_type: "sort-buckets",
      buckets: [{ id: "tech", label: "Technology" }, { id: "not", label: "Not technology" }],
      items: [
        { id: "i1", text: "Designing a stronger school desk", correct_bucket: "tech" },
        { id: "i2", text: "Building a model crane to lift a load", correct_bucket: "tech" },
        { id: "i3", text: "Daydreaming in class", correct_bucket: "not" },
        { id: "i4", text: "Reciting a poem from memory", correct_bucket: "not" },
      ],
      expected: "Designing a desk and building a crane solve real problems (technology); daydreaming and reciting do not.",
      pass_threshold: 0.75,
      memo: "Technology means solving a real problem with a practical solution — making and designing, not just remembering.", error_signals: ["ERR_TECH_G7DGA1_SORT"], difficulty: 2,
    },
    MC("The best short definition of technology is using resources to…",
      ["solve problems and meet needs", "make life harder", "waste materials", "avoid thinking"], "solve problems and meet needs",
      "Technology = using knowledge, skills and resources to solve problems and meet people's needs and wants.", "ERR_TECH_G7DGA1_SHORTDEF", 1),
  ],

  // DG.A2 · The design process (IDMEC)
  "TECH.G7.DG.A2": [
    MC("What do the letters in the design process IDMEC stand for?",
      ["Investigate, Design, Make, Evaluate, Communicate", "Imagine, Draw, Move, Eat, Count", "Invent, Decide, Measure, End, Close", "Inspect, Detail, Mark, Erase, Copy"], "Investigate, Design, Make, Evaluate, Communicate",
      "The design process is Investigate, Design, Make, Evaluate, Communicate — the backbone of Technology.", "ERR_TECH_G7DGA2_IDMEC", 1),
    TF("The design process is the steps we follow to develop a solution to a problem.", "True",
      "The design process is a systematic way of moving from a problem to a working solution.", "ERR_TECH_G7DGA2_PURPOSE", 1),
    MC("In which stage do you find out about the problem and existing products?",
      ["Investigate", "Make", "Communicate", "Evaluate"], "Investigate",
      "Investigating means finding out about the context, the need, and existing products.", "ERR_TECH_G7DGA2_INVESTIGATE", 1),
    MC("In which stage do you write a design brief and sketch ideas?",
      ["Design", "Investigate", "Make", "Evaluate"], "Design",
      "Designing includes writing the design brief and specifications and sketching initial ideas.", "ERR_TECH_G7DGA2_DESIGN", 1),
    MC("In which stage do you actually build the model or product?",
      ["Make", "Design", "Communicate", "Investigate"], "Make",
      "Making is where you draw working plans and build the item or model.", "ERR_TECH_G7DGA2_MAKE", 1),
    MC("What happens in the Evaluate stage?",
      ["You judge how well the solution works against the brief", "You start the problem again", "You throw the work away", "You only colour it in"], "You judge how well the solution works against the brief",
      "Evaluating means checking your design and product against the design brief and criteria.", "ERR_TECH_G7DGA2_EVALUATE", 2),
    MC("What is the Communicate stage about?",
      ["Presenting and recording your solution with drawings and notes", "Hiding your work", "Sleeping", "Eating lunch"], "Presenting and recording your solution with drawings and notes",
      "Communicating means presenting your solution and recording it in drawings and a report.", "ERR_TECH_G7DGA2_COMMUNICATE", 1),
    CLOZE("A short written statement of what you must design is called a design ____.",
      ["brief", "lunch", "sketch", "memory"], "brief",
      "The design brief states the problem and what the solution must do.", "ERR_TECH_G7DGA2_BRIEF", 1),
    TF("Specifications are the exact requirements the solution must meet.", "True",
      "Specifications spell out the requirements (size, cost, materials, safety) the solution must satisfy.", "ERR_TECH_G7DGA2_SPECS", 2),
    CLOZE("Limits you must work within, like cost or time, are called ____.",
      ["constraints", "colours", "drawings", "snacks"], "constraints",
      "Constraints are the limits — money, time, materials — that you must work within.", "ERR_TECH_G7DGA2_CONSTRAINTS", 2),
    TF("The design process must always be followed in a strict one-way order and you may never go back.", "False",
      "The design process is non-linear — you can investigate or evaluate at any point and go back to improve a design.", "ERR_TECH_G7DGA2_NONLINEAR", 2),
    MC("You build your model and find a part is too weak, so you change the design. This shows the process is…",
      ["non-linear — you can go back and improve", "broken", "finished", "wrong"], "non-linear — you can go back and improve",
      "Going back to improve a design when you hit a problem is normal — the process is non-linear.", "ERR_TECH_G7DGA2_LOOP", 2),
    MC("Which comes first for a brand-new problem?",
      ["Investigate the need", "Build the final model", "Present to the class", "Throw it away"], "Investigate the need",
      "You begin by investigating the problem, need or opportunity before designing.", "ERR_TECH_G7DGA2_FIRST", 1),
    CLOZE("Choosing the best idea from several sketches uses your ____ skills.",
      ["evaluation", "running", "singing", "sleeping"], "evaluation",
      "Evaluation skills are used to compare ideas and choose the best one.", "ERR_TECH_G7DGA2_EVAL_CHOOSE", 2),
    {
      question: "Put the design process stages in their usual order.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Investigate the problem and need" },
        { id: "b", text: "Design ideas and choose the best" },
        { id: "c", text: "Make the model or product" },
        { id: "d", text: "Evaluate how well it works" },
        { id: "e", text: "Communicate the solution" },
      ],
      expected_order: ["a", "b", "c", "d", "e"],
      memo: "The usual order is Investigate, Design, Make, Evaluate, Communicate — though you may loop back at any time.",
      error_signals: ["ERR_TECH_G7DGA2_SEQUENCE"], difficulty: 2,
    },
    {
      question: "Sort each task into the correct design-process stage.",
      input_type: "sort-buckets",
      buckets: [{ id: "inv", label: "Investigate" }, { id: "des", label: "Design" }, { id: "mk", label: "Make" }],
      items: [
        { id: "i1", text: "Look at how existing desks are built", correct_bucket: "inv" },
        { id: "i2", text: "Sketch two ideas for a new desk", correct_bucket: "des" },
        { id: "i3", text: "Write the design brief", correct_bucket: "des" },
        { id: "i4", text: "Cut and join the parts to build the desk", correct_bucket: "mk" },
      ],
      expected: "Looking at existing desks is investigating; sketching and writing the brief are designing; cutting and joining is making.",
      pass_threshold: 0.75,
      memo: "Each task belongs to a stage: investigate (find out), design (plan/sketch), make (build).", error_signals: ["ERR_TECH_G7DGA2_SORT"], difficulty: 3,
    },
    TF("Investigating can only happen at the very start and never again.", "False",
      "Investigation can happen at any point in the design process, not only at the beginning.", "ERR_TECH_G7DGA2_INV_ANYTIME", 2),
    MC("Why is the Communicate stage important?",
      ["So others understand and can use your solution", "So nobody sees the work", "To waste time", "To lose the drawings"], "So others understand and can use your solution",
      "Communicating shares the solution clearly so a client or class understands it.", "ERR_TECH_G7DGA2_COMM_WHY", 1),
    MC("The design process is the 'backbone' of Technology because…",
      ["it structures how every task is tackled", "it is the hardest part", "it is never used", "it is only for art"], "it structures how every task is tackled",
      "Every Technology task is structured around the design process from start to finish.", "ERR_TECH_G7DGA2_BACKBONE", 2),
    MC("A learner keeps changing a design after testing each version. This shows the design process is…",
      ["repeated and improved over time", "done only once", "never useful", "purely random"], "repeated and improved over time",
      "Designing is iterative — you test, evaluate and improve again and again.", "ERR_TECH_G7DGA2_ITERATE", 2),
  ],

  // DG.A3 · Design considerations & fitness-for-purpose
  "TECH.G7.DG.A3": [
    MC("'Fitness-for-purpose' asks one key question. Which is it?",
      ["Will it do the job it was made for?", "Is it the most expensive?", "Is it the biggest?", "Is it the newest colour?"], "Will it do the job it was made for?",
      "Fit-for-purpose means the product actually does the job it was designed to do.", "ERR_TECH_G7DGA3_FFP", 1),
    MC("What does 'ergonomics' consider in a design?",
      ["How easy and comfortable it is for people to use", "Its colour only", "Its price only", "Its weight only"], "How easy and comfortable it is for people to use",
      "Ergonomics is about how comfortable and easy a product is to use for people.", "ERR_TECH_G7DGA3_ERGO", 2),
    MC("What does 'aesthetics' mean when judging a design?",
      ["How good it looks", "How heavy it is", "How loud it is", "How old it is"], "How good it looks",
      "Aesthetics is about how attractive or good-looking a product is.", "ERR_TECH_G7DGA3_AESTH", 1),
    TF("A safe design is an important design consideration.", "True",
      "Safety is a key design criterion — a product must be safe to make and to use.", "ERR_TECH_G7DGA3_SAFE", 1),
    CLOZE("Getting good value for the money spent is called cost ____.",
      ["effectiveness", "colour", "weight", "noise"], "effectiveness",
      "Cost-effectiveness (value for money) means the product is worth what it costs.", "ERR_TECH_G7DGA3_COST", 2),
    MC("A wheelchair ramp is judged 'fit-for-purpose' if it…",
      ["lets a wheelchair user get up safely and easily", "looks shiny", "is very steep", "is made of gold"], "lets a wheelchair user get up safely and easily",
      "Fit-for-purpose means it does its job — here, letting a wheelchair user get up safely.", "ERR_TECH_G7DGA3_RAMP", 2),
    TF("A beautiful product that does not do its job is still a good design.", "False",
      "If a product does not do its job it is NOT fit-for-purpose, no matter how good it looks.", "ERR_TECH_G7DGA3_LOOKS_ONLY", 2),
    MC("Which question is about environmental impact?",
      ["Is it environmentally friendly?", "Does it look good?", "Is it cheap?", "Is it big?"], "Is it environmentally friendly?",
      "Environmental impact asks whether the product harms or helps the environment.", "ERR_TECH_G7DGA3_ENV", 2),
    CLOZE("Designs should be checked against set requirements, called the design ____.",
      ["criteria", "noises", "snacks", "colours"], "criteria",
      "Design criteria are the points a design is checked against (cost, safety, looks, etc.).", "ERR_TECH_G7DGA3_CRITERIA", 2),
    MC("Who should a designer think about first?",
      ["The user the product is for", "Nobody", "Only themselves", "A robot"], "The user the product is for",
      "Good design starts with the user — who is it for and what do they need?", "ERR_TECH_G7DGA3_USER", 1),
    MC("Which is a sign of poor ergonomics?",
      ["A handle too small and sharp to hold comfortably", "A comfortable grip", "Easy-to-reach buttons", "A clear display"], "A handle too small and sharp to hold comfortably",
      "Poor ergonomics makes a product uncomfortable or hard to use, like a sharp, tiny handle.", "ERR_TECH_G7DGA3_POOR_ERGO", 2),
    TF("Designers should think about whether a product could unfairly disadvantage a group of people.", "True",
      "Good design considers bias — whether a product favours or disadvantages certain groups.", "ERR_TECH_G7DGA3_BIAS", 2),
    CLOZE("How easy a product is to manufacture is called ease of ____.",
      ["manufacture", "sleeping", "eating", "singing"], "manufacture",
      "Ease of manufacture is a design criterion — can it be made simply and cheaply?", "ERR_TECH_G7DGA3_EASE", 2),
    MC("A torch designed for elderly users should mainly be…",
      ["easy to grip and switch on", "as small as possible", "as heavy as possible", "very complicated"], "easy to grip and switch on",
      "Designing for the user (the elderly) means easy grip and simple switching — good ergonomics.", "ERR_TECH_G7DGA3_TORCH", 2),
    {
      question: "Match each design word to what it checks. Sort them into the right group.",
      input_type: "sort-buckets",
      buckets: [{ id: "look", label: "About how it looks" }, { id: "use", label: "About using it" }, { id: "money", label: "About cost" }],
      items: [
        { id: "i1", text: "Aesthetics", correct_bucket: "look" },
        { id: "i2", text: "Ergonomics", correct_bucket: "use" },
        { id: "i3", text: "Safety", correct_bucket: "use" },
        { id: "i4", text: "Cost-effectiveness", correct_bucket: "money" },
      ],
      expected: "Aesthetics is about looks; ergonomics and safety are about using it; cost-effectiveness is about money.",
      pass_threshold: 0.75,
      memo: "Aesthetics = looks; ergonomics & safety = using it; cost-effectiveness = value for money.", error_signals: ["ERR_TECH_G7DGA3_SORT"], difficulty: 3,
    },
    TF("Fitness-for-purpose means the product suits the job it was designed for.", "True",
      "Fit-for-purpose = the product is suitable for, and does, its intended job.", "ERR_TECH_G7DGA3_FFP2", 1),
    MC("Which design would be the most fit-for-purpose for carrying hot food?",
      ["An insulated container with a tight lid", "A paper bag with holes", "An open dish", "A net"], "An insulated container with a tight lid",
      "Fit-for-purpose for hot food means keeping heat in and not spilling — an insulated sealed container.", "ERR_TECH_G7DGA3_HOTFOOD", 2),
    MC("Why consider cost when designing?",
      ["So the user can afford it and it gives value", "Cost never matters", "To make it as expensive as possible", "To waste money"], "So the user can afford it and it gives value",
      "Cost matters so the product is affordable and offers value for money.", "ERR_TECH_G7DGA3_WHYCOST", 1),
    CLOZE("A product that is comfortable and easy to use has good ____.",
      ["ergonomics", "weather", "music", "spelling"], "ergonomics",
      "Good ergonomics means a product fits the user comfortably and is easy to use.", "ERR_TECH_G7DGA3_ERGO2", 1),
    TF("A design that is dangerous to use should be improved, even if it looks good.", "True",
      "Safety outranks looks — an unsafe design must be improved before it is acceptable.", "ERR_TECH_G7DGA3_SAFEFIRST", 2),
  ],

  // DG.A4 · Graphical communication & line types
  "TECH.G7.DG.A4": [
    MC("Why do we use drawings in Technology?",
      ["To develop ideas and communicate them clearly", "To waste paper", "Only to look pretty", "To hide the design"], "To develop ideas and communicate them clearly",
      "Graphics serve two purposes: developing ideas and communicating them to others.", "ERR_TECH_G7DGA4_PURPOSE", 1),
    MC("How are the visible outlines of an object usually drawn?",
      ["Thick/dark solid lines", "Thin dashed lines", "Wavy lines", "No lines"], "Thick/dark solid lines",
      "Outlines (the visible edges) are drawn as thick, dark, solid lines.", "ERR_TECH_G7DGA4_OUTLINE", 1),
    MC("How is hidden detail (an edge you cannot see) shown on a drawing?",
      ["A dashed line", "A thick solid line", "A red line", "No line at all"], "A dashed line",
      "Hidden detail is drawn with dashed lines to show edges that are behind the object.", "ERR_TECH_G7DGA4_HIDDEN", 1),
    MC("What are construction lines used for?",
      ["Light guide lines to help build the drawing", "The final dark outline", "Hidden edges", "Dimensions"], "Light guide lines to help build the drawing",
      "Construction lines are thin and feint — light guide lines you draw first to position things.", "ERR_TECH_G7DGA4_CONSTRUCTION", 2),
    TF("Construction lines should be drawn thin and feint (light).", "True",
      "Construction lines are feint guide lines, drawn lightly so they don't clutter the final drawing.", "ERR_TECH_G7DGA4_FEINT", 1),
    CLOZE("Numbers on a drawing that show the size of parts are called ____.",
      ["dimensions", "colours", "shadows", "names"], "dimensions",
      "Dimensions are the measurements written on a drawing to show sizes.", "ERR_TECH_G7DGA4_DIMENSIONS", 1),
    MC("What does 'scale' mean on a drawing?",
      ["The drawing is a set number of times bigger or smaller than the real object", "The drawing weighs something", "The colour of the paper", "The thickness of the pencil"], "The drawing is a set number of times bigger or smaller than the real object",
      "Scale relates the size of the drawing to the real object (e.g. 1:2 means half size).", "ERR_TECH_G7DGA4_SCALE", 2),
    TF("A free-hand sketch is drawn quickly without using a ruler.", "True",
      "Free-hand sketching is done quickly by hand, without instruments, to capture ideas.", "ERR_TECH_G7DGA4_SKETCH", 1),
    MC("A working drawing of one face of an object is drawn in…",
      ["2D (two dimensions)", "5D", "no dimensions", "only colour"], "2D (two dimensions)",
      "A working drawing of one face is a flat, 2D drawing using conventions and dimensions.", "ERR_TECH_G7DGA4_2D", 2),
    CLOZE("Visible edges of an object are drawn as thick, ____ lines.",
      ["dark", "dashed", "feint", "invisible"], "dark",
      "Outlines are thick and dark; construction lines are thin and feint; hidden detail is dashed.", "ERR_TECH_G7DGA4_DARK", 1),
    MC("Which line type would show the edge of a hole drilled through the back of a block (not visible from the front)?",
      ["Dashed line", "Thick solid line", "Thin feint line", "No line"], "Dashed line",
      "An edge you cannot see is hidden detail, shown with a dashed line.", "ERR_TECH_G7DGA4_HOLE", 2),
    TF("Drawing conventions are agreed rules so everyone reads a drawing the same way.", "True",
      "Conventions are shared rules (line types, dimensions, scale) so any reader understands the drawing.", "ERR_TECH_G7DGA4_CONVENTION", 2),
    MC("Why write dimensions on a working drawing?",
      ["So the maker knows the exact sizes to build", "To decorate it", "To make it longer", "There is no reason"], "So the maker knows the exact sizes to build",
      "Dimensions tell the maker the exact sizes needed to build the object.", "ERR_TECH_G7DGA4_WHYDIM", 1),
    CLOZE("Drawing something half its real size uses a scale of 1 to ____.",
      ["2", "10", "1", "0"], "2",
      "A scale of 1:2 means the drawing is half the size of the real object.", "ERR_TECH_G7DGA4_HALFSCALE", 2),
    {
      question: "Match each line use to the correct line type.",
      input_type: "sort-buckets",
      buckets: [{ id: "dark", label: "Thick/dark line" }, { id: "feint", label: "Thin/feint line" }, { id: "dash", label: "Dashed line" }],
      items: [
        { id: "i1", text: "A visible outer edge", correct_bucket: "dark" },
        { id: "i2", text: "A light guide line used while drawing", correct_bucket: "feint" },
        { id: "i3", text: "An edge hidden behind the object", correct_bucket: "dash" },
        { id: "i4", text: "The final visible shape", correct_bucket: "dark" },
      ],
      expected: "Visible edges and the final shape are thick/dark; guide lines are thin/feint; hidden edges are dashed.",
      pass_threshold: 0.75,
      memo: "Thick/dark = visible edges; thin/feint = construction guides; dashed = hidden detail.", error_signals: ["ERR_TECH_G7DGA4_SORT"], difficulty: 3,
    },
    MC("Two main reasons we draw in Technology are to develop ideas and to…",
      ["communicate ideas to others", "fill time", "use up ink", "confuse people"], "communicate ideas to others",
      "Graphics develop ideas in your head and communicate them clearly to others.", "ERR_TECH_G7DGA4_TWO", 1),
    TF("Scale lets you draw a large object, like a tower, on a small piece of paper.", "True",
      "Scaling down lets big objects be drawn to fit on paper while keeping the proportions correct.", "ERR_TECH_G7DGA4_SCALEDOWN", 2),
    MC("Which is drawn first when starting a careful drawing?",
      ["Feint construction lines", "Thick dark outlines", "Dimensions", "Shading"], "Feint construction lines",
      "You start with feint construction lines to position the drawing, then darken the final outlines.", "ERR_TECH_G7DGA4_ORDER", 2),
    CLOZE("Hidden edges of an object are shown using ____ lines.",
      ["dashed", "thick", "red", "wavy"], "dashed",
      "Dashed lines show hidden detail — edges that are there but not visible.", "ERR_TECH_G7DGA4_DASHED2", 1),
    MC("A drawing is labelled 'scale 1:5'. This means the real object is…",
      ["5 times bigger than the drawing", "5 times smaller than the drawing", "the same size", "made of 5 parts"], "5 times bigger than the drawing",
      "Scale 1:5 means 1 unit on the drawing equals 5 units on the real object — the object is 5× bigger.", "ERR_TECH_G7DGA4_SCALE15", 3),
  ],

  // DG.A5 · Drawing techniques (IMAGE-DEPENDENT — text-answerable items only)
  "TECH.G7.DG.A5": [
    MC("In 3D oblique drawing, the front face is drawn true shape and the depth lines go back at…",
      ["45 degrees", "90 degrees", "10 degrees", "180 degrees"], "45 degrees",
      "Oblique drawing shows the front face true, with depth lines going back at 45°.", "ERR_TECH_G7DGA5_OBLIQUE45", 2),
    MC("Which drawing technique makes things look smaller as they go into the distance, meeting at one point?",
      ["Single vanishing point perspective", "Oblique", "Flat 2D", "A list"], "Single vanishing point perspective",
      "Single-point perspective uses one vanishing point so things shrink into the distance.", "ERR_TECH_G7DGA5_PERSPECTIVE", 2),
    TF("A working drawing shows exact sizes and is used to build the object.", "True",
      "Working drawings carry dimensions and conventions so the object can be built accurately.", "ERR_TECH_G7DGA5_WORKING", 1),
    MC("Which technique is best for quickly capturing a first idea?",
      ["A free-hand sketch", "A scaled working drawing", "An exploded assembly view", "A budget"], "A free-hand sketch",
      "Free-hand sketching is the fast way to get early ideas down on paper.", "ERR_TECH_G7DGA5_SKETCHFIRST", 1),
    CLOZE("Oblique and perspective are both ways of drawing in ____.",
      ["3D", "2D", "1D", "words"], "3D",
      "Oblique and perspective are 3D drawing techniques; a working drawing of one face is 2D.", "ERR_TECH_G7DGA5_3D", 1),
    MC("A single vanishing point perspective drawing usually has…",
      ["one point where lines meet in the distance", "no points", "five points", "a price tag"], "one point where lines meet in the distance",
      "Single-point perspective has exactly one vanishing point.", "ERR_TECH_G7DGA5_ONEPOINT", 2),
    TF("Oblique drawings are often done on squared (quadrant) paper to help keep the 45° depth.", "True",
      "Squared paper helps draw the 45° depth lines neatly in oblique projection.", "ERR_TECH_G7DGA5_SQUARED", 2),
    MC("Which is a 2D drawing?",
      ["A flat working drawing of one face", "An oblique 3D view", "A perspective view", "A photograph from an angle"], "A flat working drawing of one face",
      "A working drawing of a single face is two-dimensional (flat).", "ERR_TECH_G7DGA5_FLAT", 2),
    CLOZE("Adding colour, texture and shading helps a drawing look more ____.",
      ["realistic", "flat", "blank", "boring"], "realistic",
      "Artistic techniques like colour, texture and shading make a drawing look realistic.", "ERR_TECH_G7DGA5_REALISM", 2),
    MC("Which drawing would you give to someone to BUILD the object accurately?",
      ["The working drawing with dimensions", "A rough sketch", "An artistic impression", "A colourful poster"], "The working drawing with dimensions",
      "The dimensioned working drawing is the one used to build accurately.", "ERR_TECH_G7DGA5_BUILDFROM", 2),
    TF("An artistic impression is mainly used to communicate how the finished product will look.", "True",
      "Artistic impressions (perspective, colour, shading) communicate the look of the final product.", "ERR_TECH_G7DGA5_ARTISTIC", 2),
    MC("Free-hand sketching is best described as…",
      ["drawing quickly by hand without instruments", "drawing only with a computer", "measuring with a ruler", "painting walls"], "drawing quickly by hand without instruments",
      "Free-hand sketching is fast hand drawing without rulers or instruments.", "ERR_TECH_G7DGA5_FREEHAND", 1),
    CLOZE("In oblique drawing the depth lines go back at ____ degrees.",
      ["45", "90", "30", "60"], "45",
      "Oblique projection uses 45° for the depth lines.", "ERR_TECH_G7DGA5_45AGAIN", 2),
    {
      question: "Match each drawing type to its best use.",
      input_type: "sort-buckets",
      buckets: [{ id: "idea", label: "Capture an idea fast" }, { id: "build", label: "Build accurately" }, { id: "show", label: "Show the final look" }],
      items: [
        { id: "i1", text: "Free-hand sketch", correct_bucket: "idea" },
        { id: "i2", text: "Dimensioned working drawing", correct_bucket: "build" },
        { id: "i3", text: "Perspective artistic impression", correct_bucket: "show" },
      ],
      expected: "Sketches capture ideas, working drawings are for building, artistic impressions show the final look.",
      pass_threshold: 0.66,
      memo: "Sketch = fast ideas; working drawing = accurate building; artistic impression = final appearance.", error_signals: ["ERR_TECH_G7DGA5_SORT"], difficulty: 3,
    },
  ],

  // ════════════════════════ STRUCTURES (Term 2) ═══════════════════════════════
  // ST.A1 · Purpose & classification of structures
  "TECH.G7.ST.A1": [
    MC("What is a structure?",
      ["Something built to support a load or hold things together", "Any liquid", "A type of food", "A kind of song"], "Something built to support a load or hold things together",
      "A structure supports a load and holds its shape — it can contain, support, protect or span.", "ERR_TECH_G7STA1_DEF", 1),
    MC("Which is a job a structure can do?",
      ["Span a gap, like a bridge", "Sing a tune", "Cook a meal", "Tell the time"], "Span a gap, like a bridge",
      "Structures contain, support, protect or span. A bridge spans a gap.", "ERR_TECH_G7STA1_JOB", 1),
    MC("A dam wall mainly works to…",
      ["contain water", "span a road", "play music", "cook food"], "contain water",
      "A dam wall is a structure that contains (holds back) water.", "ERR_TECH_G7STA1_CONTAIN", 2),
    MC("Which is a NATURAL structure?",
      ["A spider's web", "A steel bridge", "A brick house", "A car"], "A spider's web",
      "Natural structures are made by nature (webs, nests, bones); man-made structures are built by people.", "ERR_TECH_G7STA1_NATURAL", 1),
    MC("Which is a MAN-MADE structure?",
      ["A telephone tower", "A honeycomb", "A tree", "A bird's nest"], "A telephone tower",
      "Man-made structures are built by people, like towers and bridges.", "ERR_TECH_G7STA1_MANMADE", 1),
    TF("A bird's nest is an example of a natural structure.", "True",
      "A nest is built by an animal from natural materials — a natural structure.", "ERR_TECH_G7STA1_NEST", 1),
    CLOZE("A helmet is a structure that works to ____ your head.",
      ["protect", "feed", "weigh", "colour"], "protect",
      "A helmet protects — one of the jobs of a structure.", "ERR_TECH_G7STA1_PROTECT", 1),
    TF("All structures are made by people.", "False",
      "Many structures are natural (webs, bones, shells); only some are man-made.", "ERR_TECH_G7STA1_ALLMANMADE", 1),
    MC("A roof beam mainly works to…",
      ["support a load", "contain a liquid", "make sound", "give light"], "support a load",
      "A beam supports the load above it — supporting is a key structural job.", "ERR_TECH_G7STA1_SUPPORT", 2),
    CLOZE("Bridges are structures that ____ a gap.",
      ["span", "eat", "sing", "boil"], "span",
      "Spanning means reaching across a gap — what a bridge does.", "ERR_TECH_G7STA1_SPAN", 1),
    MC("Which list shows only structures?",
      ["Bridge, tower, house", "Bridge, water, music", "Tower, song, soup", "House, wind, idea"], "Bridge, tower, house",
      "Bridges, towers and houses are all structures; water, music and ideas are not.", "ERR_TECH_G7STA1_LIST", 2),
    TF("A human skeleton is a natural structure that supports the body.", "True",
      "Bones form a natural structure that supports and protects the body.", "ERR_TECH_G7STA1_SKELETON", 2),
    MC("A fence around a garden mainly works to…",
      ["protect or enclose an area", "span a river", "store electricity", "make light"], "protect or enclose an area",
      "A fence encloses and protects an area — a structural job.", "ERR_TECH_G7STA1_FENCE", 2),
    CLOZE("Structures built by people are called ____ structures.",
      ["man-made", "natural", "liquid", "musical"], "man-made",
      "Man-made structures are built by people; natural ones occur in nature.", "ERR_TECH_G7STA1_MANMADE2", 1),
    {
      question: "Sort each structure into 'Natural' or 'Man-made'.",
      input_type: "sort-buckets",
      buckets: [{ id: "nat", label: "Natural" }, { id: "man", label: "Man-made" }],
      items: [
        { id: "i1", text: "Spider's web", correct_bucket: "nat" },
        { id: "i2", text: "Steel bridge", correct_bucket: "man" },
        { id: "i3", text: "Beehive honeycomb", correct_bucket: "nat" },
        { id: "i4", text: "Cell phone tower", correct_bucket: "man" },
      ],
      expected: "Webs and honeycomb are natural; bridges and towers are man-made.",
      pass_threshold: 0.75,
      memo: "Natural structures are made by nature; man-made structures are built by people.", error_signals: ["ERR_TECH_G7STA1_SORT"], difficulty: 2,
    },
    {
      question: "Sort each structure by the main job it does.",
      input_type: "sort-buckets",
      buckets: [{ id: "support", label: "Support" }, { id: "contain", label: "Contain" }, { id: "span", label: "Span" }],
      items: [
        { id: "i1", text: "Roof truss", correct_bucket: "support" },
        { id: "i2", text: "Water tank", correct_bucket: "contain" },
        { id: "i3", text: "Footbridge", correct_bucket: "span" },
        { id: "i4", text: "Table legs", correct_bucket: "support" },
      ],
      expected: "A truss and table legs support; a water tank contains; a footbridge spans.",
      pass_threshold: 0.75,
      memo: "Structures can support a load, contain something, protect, or span a gap.", error_signals: ["ERR_TECH_G7STA1_SORT2"], difficulty: 3,
    },
    MC("Which best lists the jobs a structure can do?",
      ["Contain, support, protect, span", "Eat, sleep, run, jump", "Sing, dance, paint, read", "Boil, freeze, melt, burn"], "Contain, support, protect, span",
      "The four structural jobs are to contain, support, protect and span.", "ERR_TECH_G7STA1_JOBS", 1),
    TF("A tortoise shell is a natural structure that protects the animal.", "True",
      "The shell is a natural protective structure.", "ERR_TECH_G7STA1_SHELL", 1),
    MC("A grain silo is a structure that mainly…",
      ["contains stored grain", "spans a valley", "produces electricity", "lights a room"], "contains stored grain",
      "A silo contains and stores grain — a containing structure.", "ERR_TECH_G7STA1_SILO", 2),
    MC("Which of these is NOT a job that structures do?",
      ["Producing electricity by itself", "Supporting a load", "Protecting something", "Spanning a gap"], "Producing electricity by itself",
      "Structures contain, support, protect or span — generating electricity is not a structural job.", "ERR_TECH_G7STA1_NOTJOB", 2),
  ],

  // ST.A2 · Types of structures: shell, frame, solid
  "TECH.G7.ST.A2": [
    MC("What are the three main types of structures?",
      ["Shell, frame and solid", "Big, medium and small", "Red, blue and green", "Fast, slow and still"], "Shell, frame and solid",
      "The three structure types are shell, frame and solid.", "ERR_TECH_G7STA2_THREE", 1),
    MC("A frame structure is made of…",
      ["bars or members joined together", "one solid lump", "a thin hollow skin", "only water"], "bars or members joined together",
      "A frame structure is built from bars (members) joined together, like a tower or truss.", "ERR_TECH_G7STA2_FRAME", 1),
    MC("A shell structure is best described as…",
      ["a thin, hollow outer covering", "a solid block", "a frame of bars", "a heap of sand"], "a thin, hollow outer covering",
      "A shell structure is a thin hollow form, like an egg, a dome or a drink can.", "ERR_TECH_G7STA2_SHELL", 1),
    MC("A solid structure is…",
      ["made from one solid mass of material", "hollow inside", "made only of thin bars", "always moving"], "made from one solid mass of material",
      "A solid structure is one full mass, like a brick wall or a dam wall.", "ERR_TECH_G7STA2_SOLID", 1),
    MC("Which is a frame structure?",
      ["An electricity pylon", "An egg", "A brick", "A dam wall"], "An electricity pylon",
      "A pylon is built from joined bars — a frame structure.", "ERR_TECH_G7STA2_PYLON", 2),
    MC("Which is a shell structure?",
      ["A drink can", "A steel tower", "A solid brick", "A wooden beam"], "A drink can",
      "A drink can is a thin hollow covering — a shell structure.", "ERR_TECH_G7STA2_CAN", 2),
    MC("Which is a solid structure?",
      ["A concrete dam wall", "A bird cage", "An egg shell", "A bicycle frame"], "A concrete dam wall",
      "A dam wall is one solid mass — a solid structure.", "ERR_TECH_G7STA2_DAM", 2),
    TF("An egg is an example of a shell structure.", "True",
      "An egg is a thin hollow covering — a natural shell structure.", "ERR_TECH_G7STA2_EGG", 1),
    TF("A bicycle frame is a frame structure made of joined tubes.", "True",
      "A bicycle frame is built from joined tubes (members) — a frame structure.", "ERR_TECH_G7STA2_BIKE", 1),
    CLOZE("A structure made of a thin, hollow skin is a ____ structure.",
      ["shell", "frame", "solid", "loud"], "shell",
      "Shell structures are thin and hollow, like cans, domes and eggs.", "ERR_TECH_G7STA2_SHELLWORD", 1),
    CLOZE("A structure built from bars joined together is a ____ structure.",
      ["frame", "shell", "solid", "liquid"], "frame",
      "Frame structures use joined bars (members), like towers and trusses.", "ERR_TECH_G7STA2_FRAMEWORD", 1),
    MC("Why might a frame structure use less material than a solid one of the same size?",
      ["It is mostly open space between the bars", "It is heavier", "It is fully filled in", "It uses gold"], "It is mostly open space between the bars",
      "Frames are mostly open, so they use less material while still being strong.", "ERR_TECH_G7STA2_LESSMAT", 2),
    TF("A dome over a stadium is a shell structure.", "True",
      "A thin curved dome covering a space is a shell structure.", "ERR_TECH_G7STA2_DOME", 2),
    MC("Which structure type is a high-voltage tower most likely to be?",
      ["Frame", "Shell", "Solid", "Liquid"], "Frame",
      "Pylons/towers are frame structures built of joined steel members.", "ERR_TECH_G7STA2_TOWERTYPE", 2),
    {
      question: "Sort each object into shell, frame or solid.",
      input_type: "sort-buckets",
      buckets: [{ id: "shell", label: "Shell" }, { id: "frame", label: "Frame" }, { id: "solid", label: "Solid" }],
      items: [
        { id: "i1", text: "Tin can", correct_bucket: "shell" },
        { id: "i2", text: "Electricity pylon", correct_bucket: "frame" },
        { id: "i3", text: "Brick", correct_bucket: "solid" },
        { id: "i4", text: "Roof truss", correct_bucket: "frame" },
        { id: "i5", text: "Egg", correct_bucket: "shell" },
      ],
      expected: "Tin can and egg are shells; pylon and truss are frames; a brick is solid.",
      pass_threshold: 0.7,
      memo: "Shell = thin hollow skin; frame = joined bars; solid = one full mass.", error_signals: ["ERR_TECH_G7STA2_SORT"], difficulty: 3,
    },
    TF("A solid structure is always hollow inside.", "False",
      "A solid structure is one full mass — it is NOT hollow. Hollow thin forms are shells.", "ERR_TECH_G7STA2_SOLIDHOLLOW", 1),
    MC("A worksheet asks you to classify a wire bird cage. It is a…",
      ["frame structure", "shell structure", "solid structure", "liquid"], "frame structure",
      "A bird cage is made of joined wire bars — a frame structure.", "ERR_TECH_G7STA2_CAGE", 2),
    MC("Which pair are both shell structures?",
      ["A helmet and a drink can", "A pylon and a truss", "A brick and a dam", "A ladder and a crane"], "A helmet and a drink can",
      "A helmet and a can are both thin hollow coverings — shell structures.", "ERR_TECH_G7STA2_PAIR", 2),
    CLOZE("A brick wall is an example of a ____ structure.",
      ["solid", "shell", "frame", "hollow"], "solid",
      "A brick wall is one solid mass — a solid structure.", "ERR_TECH_G7STA2_WALL", 1),
    TF("A car body that is a thin hollow shell is an example of a shell structure.", "True",
      "A car body is a thin hollow outer covering — a shell structure.", "ERR_TECH_G7STA2_CARBODY", 2),
  ],

  // ST.A3 · Stiffening & reinforcing
  "TECH.G7.ST.A3": [
    MC("What does it mean to 'stiffen' a material?",
      ["Make it harder to bend", "Make it heavier only", "Make it a different colour", "Make it longer"], "Make it harder to bend",
      "Stiffening makes a material more rigid — harder to bend or flex.", "ERR_TECH_G7STA3_STIFFEN", 1),
    MC("Folding a flat sheet of paper into a fan shape makes it…",
      ["stiffer and harder to bend", "weaker", "heavier than steel", "invisible"], "stiffer and harder to bend",
      "Folding (corrugating) a sheet stiffens it so it resists bending.", "ERR_TECH_G7STA3_FOLD", 2),
    MC("Rolling a sheet of paper into a tube makes it…",
      ["stronger and stiffer than the flat sheet", "weaker", "melt", "shrink to nothing"], "stronger and stiffer than the flat sheet",
      "Rolling paper into a tube greatly stiffens it — tubing is a reinforcing method.", "ERR_TECH_G7STA3_TUBE", 2),
    MC("What is triangulation in a structure?",
      ["Adding diagonal members to form triangles for rigidity", "Painting it in three colours", "Making it round", "Removing all the bars"], "Adding diagonal members to form triangles for rigidity",
      "Triangulation adds diagonals to make triangles, which keep a frame rigid.", "ERR_TECH_G7STA3_TRIANGLE", 1),
    TF("A triangle is a very rigid shape used to stiffen frame structures.", "True",
      "Triangles do not deform under load, so triangulating a frame stiffens it.", "ERR_TECH_G7STA3_RIGID", 1),
    TF("A square frame is more rigid than a triangulated frame.", "False",
      "A plain square can rack (lean over); adding a diagonal to triangulate it makes it rigid.", "ERR_TECH_G7STA3_SQUARE", 2),
    CLOZE("Adding diagonals to make triangles in a frame is called ____.",
      ["triangulation", "painting", "melting", "folding"], "triangulation",
      "Triangulation = adding diagonal members so the frame is full of rigid triangles.", "ERR_TECH_G7STA3_TRIWORD", 1),
    MC("A bookshelf sags in the middle under heavy books. Best way to stiffen it?",
      ["Add a support or a folded edge to the shelf", "Paint it", "Add more books", "Make it thinner"], "Add a support or a folded edge to the shelf",
      "A support or a folded/upturned edge stiffens the shelf so it stops sagging.", "ERR_TECH_G7STA3_SHELF", 2),
    MC("Corrugated cardboard is strong for its weight because…",
      ["the wavy folded layer stiffens it", "it is solid", "it is made of metal", "it is wet"], "the wavy folded layer stiffens it",
      "The corrugated (folded, wavy) middle layer stiffens cardboard while staying light.", "ERR_TECH_G7STA3_CORRUGATE", 2),
    CLOZE("Rolling a flat sheet into a round shape to stiffen it is called ____.",
      ["tubing", "frying", "freezing", "singing"], "tubing",
      "Tubing means rolling a sheet into a tube to stiffen it.", "ERR_TECH_G7STA3_TUBING", 1),
    MC("Why do cranes and towers have many diagonal bars?",
      ["The triangles make them stiff and stable", "To use more steel for fun", "To make them heavier", "For decoration only"], "The triangles make them stiff and stable",
      "Diagonals form triangles (triangulation) that give towers and cranes their rigidity.", "ERR_TECH_G7STA3_CRANE", 2),
    TF("Gussets and webs can be added at joints to strengthen a frame.", "True",
      "Gussets and triangular webs reinforce the joints of a frame structure.", "ERR_TECH_G7STA3_GUSSET", 2),
    MC("Which change would stiffen a thin steel ruler the most?",
      ["Bending an L-shape along its length", "Making it shorter only", "Polishing it", "Heating it slightly"], "Bending an L-shape along its length",
      "Adding a fold or bend along the length (changing the cross-section) greatly stiffens a thin strip.", "ERR_TECH_G7STA3_LSHAPE", 3),
    CLOZE("A shape that keeps its form and does not bend easily is called ____.",
      ["rigid", "floppy", "soft", "wet"], "rigid",
      "Rigid means stiff — it keeps its shape under load.", "ERR_TECH_G7STA3_RIGIDWORD", 1),
    {
      question: "Sort each method by what it mainly does to stiffen a structure.",
      input_type: "sort-buckets",
      buckets: [{ id: "fold", label: "Folding/corrugating" }, { id: "tube", label: "Tubing/rolling" }, { id: "tri", label: "Triangulation" }],
      items: [
        { id: "i1", text: "Pleating card into a fan", correct_bucket: "fold" },
        { id: "i2", text: "Rolling paper into a dowel", correct_bucket: "tube" },
        { id: "i3", text: "Adding a diagonal brace to a square", correct_bucket: "tri" },
        { id: "i4", text: "Corrugated roof sheeting", correct_bucket: "fold" },
      ],
      expected: "Pleating and corrugating are folding; rolling into a dowel is tubing; adding a diagonal is triangulation.",
      pass_threshold: 0.75,
      memo: "Three ways to stiffen: fold/corrugate, roll into a tube, or triangulate with diagonals.", error_signals: ["ERR_TECH_G7STA3_SORT"], difficulty: 3,
    },
    MC("The main reason to stiffen a structure is to…",
      ["stop it bending or flexing under load", "make it cost more", "make it heavier", "change its colour"], "stop it bending or flexing under load",
      "Stiffening stops a structure bending or flexing when a load is applied.", "ERR_TECH_G7STA3_WHY", 1),
    TF("Triangulation is used in roof trusses, pylons and cranes.", "True",
      "Triangulation gives rigidity to trusses, pylons and cranes.", "ERR_TECH_G7STA3_USES", 1),
    MC("Which everyday item is stiffened by corrugation (folding)?",
      ["A cardboard box", "A glass of water", "A cotton ball", "A balloon"], "A cardboard box",
      "Cardboard boxes use a corrugated (folded) inner layer for stiffness.", "ERR_TECH_G7STA3_BOX", 1),
    CLOZE("Triangles are used because, unlike squares, they do not ____ out of shape.",
      ["bend", "shine", "smell", "float"], "bend",
      "A triangle holds its shape under load; a square can bend (rack) over.", "ERR_TECH_G7STA3_NOBEND", 2),
    MC("Gussets are added to a frame mainly to…",
      ["strengthen the joints", "add colour", "reduce strength", "store water"], "strengthen the joints",
      "Gussets reinforce the joints where members meet, strengthening the frame.", "ERR_TECH_G7STA3_GUSSET2", 2),
  ],

  // ST.A4 · Frame structures & stability
  "TECH.G7.ST.A4": [
    MC("What makes a structure 'stable'?",
      ["It does not easily topple over", "It is very colourful", "It is very tall only", "It is very light only"], "It does not easily topple over",
      "Stability means a structure resists toppling over.", "ERR_TECH_G7STA4_STABLE", 1),
    MC("A wide base makes a structure…",
      ["more stable", "less stable", "invisible", "lighter than air"], "more stable",
      "A wider base spreads the support and makes a structure more stable.", "ERR_TECH_G7STA4_WIDEBASE", 1),
    MC("A low centre of gravity makes a structure…",
      ["harder to topple (more stable)", "easier to topple", "float", "disappear"], "harder to topple (more stable)",
      "Keeping the weight low (low centre of gravity) makes a structure more stable.", "ERR_TECH_G7STA4_LOWCOG", 2),
    TF("A tall, narrow, top-heavy structure topples more easily.", "True",
      "Tall, narrow and top-heavy structures have a high centre of gravity and topple easily.", "ERR_TECH_G7STA4_TOPHEAVY", 1),
    MC("Why are cell phone towers often triangulated?",
      ["To give them strength, rigidity and stability", "To make them pretty", "To make them heavier", "To use more steel"], "To give them strength, rigidity and stability",
      "Triangulation gives towers the strength, rigidity and stability they need to stand up to wind.", "ERR_TECH_G7STA4_TOWERTRI", 2),
    CLOZE("The point where all the weight of a structure seems to act is its centre of ____.",
      ["gravity", "colour", "noise", "paper"], "gravity",
      "The centre of gravity is where the weight seems concentrated; keeping it low aids stability.", "ERR_TECH_G7STA4_COG", 2),
    MC("To make a tall model tower more stable, you should…",
      ["widen its base", "narrow its base", "add weight to the top", "make it taller"], "widen its base",
      "Widening the base lowers the chance of toppling — improving stability.", "ERR_TECH_G7STA4_WIDEN", 2),
    TF("Adding heavy weights to the top of a structure improves its stability.", "False",
      "Weight at the top raises the centre of gravity and makes a structure LESS stable.", "ERR_TECH_G7STA4_TOPWEIGHT", 2),
    MC("Wind is a force that acts on a tall tower. To resist it, designers use…",
      ["triangulation and a wide, anchored base", "bright paint", "soft foam", "loose joints"], "triangulation and a wide, anchored base",
      "Triangulation plus a wide, anchored base helps a tower resist wind without toppling.", "ERR_TECH_G7STA4_WIND", 2),
    CLOZE("A structure with a wide base and low weight is more ____.",
      ["stable", "wobbly", "colourful", "expensive"], "stable",
      "Wide base + low centre of gravity = greater stability.", "ERR_TECH_G7STA4_STABLEWORD", 1),
    MC("Which structure is the most stable?",
      ["A pyramid (wide bottom, narrow top)", "A tall thin pole on a small foot", "A ball on a point", "A pencil on its tip"], "A pyramid (wide bottom, narrow top)",
      "A pyramid has a wide base and low centre of gravity, making it very stable.", "ERR_TECH_G7STA4_PYRAMID", 2),
    TF("Triangulation adds rigidity, which also helps a frame structure stay stable.", "True",
      "Rigidity from triangulation keeps the frame from racking, helping overall stability.", "ERR_TECH_G7STA4_RIGIDSTABLE", 2),
    MC("A racing car is built low and wide mainly to…",
      ["keep a low centre of gravity for stability", "look fast", "save fuel", "carry more people"], "keep a low centre of gravity for stability",
      "Low and wide gives a low centre of gravity and broad base — stable at speed.", "ERR_TECH_G7STA4_RACECAR", 3),
    MC("Disguising a cell phone tower as a tree mainly reduces…",
      ["visual pollution", "its strength", "its height", "the wind"], "visual pollution",
      "Disguising towers reduces visual pollution so they blend into the environment.", "ERR_TECH_G7STA4_DISGUISE", 2),
    {
      question: "Sort each change by its effect on a tower's stability.",
      input_type: "sort-buckets",
      buckets: [{ id: "more", label: "More stable" }, { id: "less", label: "Less stable" }],
      items: [
        { id: "i1", text: "Widen the base", correct_bucket: "more" },
        { id: "i2", text: "Add a heavy load on top", correct_bucket: "less" },
        { id: "i3", text: "Lower the centre of gravity", correct_bucket: "more" },
        { id: "i4", text: "Make it tall and narrow", correct_bucket: "less" },
      ],
      expected: "Widening the base and lowering the weight add stability; top weight and tall-narrow shapes reduce it.",
      pass_threshold: 0.75,
      memo: "Stability rises with a wider base and a lower centre of gravity; it falls when top-heavy or tall and narrow.", error_signals: ["ERR_TECH_G7STA4_SORT"], difficulty: 3,
    },
    MC("Internal cross-bracing in a frame mainly improves…",
      ["rigidity and stability", "colour", "smell", "taste"], "rigidity and stability",
      "Cross-bracing triangulates the frame, improving rigidity and stability.", "ERR_TECH_G7STA4_BRACING", 2),
    TF("A structure can be strong but still topple if it is unstable.", "True",
      "Strength stops it breaking; stability stops it toppling — they are different needs.", "ERR_TECH_G7STA4_STRONGVSTABLE", 2),
    MC("Mine headgear and windmills are strengthened by…",
      ["triangulation", "loose ropes", "soft padding", "extra paint"], "triangulation",
      "Tall frame structures like headgear and windmills use triangulation for strength and stability.", "ERR_TECH_G7STA4_HEADGEAR", 2),
    CLOZE("A structure that easily falls over has poor ____.",
      ["stability", "colour", "smell", "sound"], "stability",
      "Easily toppling means poor stability.", "ERR_TECH_G7STA4_POOR", 1),
    MC("Why is a tightrope walker's long pole helpful for balance?",
      ["It lowers and spreads the centre of gravity to aid stability", "It makes them heavier only", "It looks impressive", "It has no effect"], "It lowers and spreads the centre of gravity to aid stability",
      "A long pole spreads weight and helps keep the centre of gravity over the rope, aiding stability.", "ERR_TECH_G7STA4_TIGHTROPE", 3),
  ],

  // ════════════════ MECHANICAL SYSTEMS & CONTROL (Term 1) ═════════════════════
  // MS.A1 · Levers & mechanical advantage
  "TECH.G7.MS.A1": [
    MC("What is a lever?",
      ["A stiff bar that turns about a pivot to move a load", "A type of liquid", "A kind of magnet", "A colour"], "A stiff bar that turns about a pivot to move a load",
      "A lever is a rigid bar that pivots about a fulcrum to move a load with an effort.", "ERR_TECH_G7MSA1_DEF", 1),
    MC("The fixed point a lever turns about is called the…",
      ["fulcrum (pivot)", "load", "effort", "handle"], "fulcrum (pivot)",
      "The fulcrum (pivot) is the fixed point about which a lever turns.", "ERR_TECH_G7MSA1_FULCRUM", 1),
    MC("In a FIRST-class lever, the fulcrum is…",
      ["between the effort and the load", "at one end only", "next to the load only", "removed"], "between the effort and the load",
      "First-class lever: the fulcrum sits between the effort and the load (like a seesaw).", "ERR_TECH_G7MSA1_FIRST", 1),
    MC("In a SECOND-class lever, the load is…",
      ["between the fulcrum and the effort", "at the fulcrum", "outside the bar", "missing"], "between the fulcrum and the effort",
      "Second-class lever: the load sits between the fulcrum and the effort (like a wheelbarrow).", "ERR_TECH_G7MSA1_SECOND", 2),
    MC("In a THIRD-class lever, the effort is…",
      ["between the fulcrum and the load", "at the load", "removed", "at the fulcrum"], "between the fulcrum and the load",
      "Third-class lever: the effort is between the fulcrum and the load (like tweezers).", "ERR_TECH_G7MSA1_THIRD", 2),
    MC("What is 'mechanical advantage'?",
      ["When a machine lets a small effort move a big load", "When a machine is colourful", "When a machine is heavy", "When a machine is broken"], "When a machine lets a small effort move a big load",
      "Mechanical advantage means a small effort can move a larger load.", "ERR_TECH_G7MSA1_MA", 1),
    TF("A second-class lever always gives a mechanical advantage.", "True",
      "Because the load is closer to the fulcrum than the effort, a second-class lever always has MA greater than 1.", "ERR_TECH_G7MSA1_SECONDMA", 2),
    TF("A third-class lever never gives a mechanical advantage greater than 1.", "True",
      "In a third-class lever the effort is closer to the fulcrum, so MA is always less than 1.", "ERR_TECH_G7MSA1_THIRDMA", 2),
    MC("A wheelbarrow is an example of which lever?",
      ["Second-class", "Third-class", "No lever", "A pulley"], "Second-class",
      "A wheelbarrow has the load between the wheel (fulcrum) and the handles (effort) — second class.", "ERR_TECH_G7MSA1_WHEELBARROW", 2),
    MC("A seesaw is an example of which lever?",
      ["First-class", "Second-class", "Third-class", "No lever"], "First-class",
      "A seesaw has the pivot in the middle, between the two people — first class.", "ERR_TECH_G7MSA1_SEESAW", 1),
    MC("A pair of tweezers is which class of lever?",
      ["Third-class", "First-class", "Second-class", "A gear"], "Third-class",
      "Tweezers have the effort between the fulcrum and the load — third class.", "ERR_TECH_G7MSA1_TWEEZERS", 2),
    CLOZE("The thing a lever moves is called the ____.",
      ["load", "fulcrum", "colour", "switch"], "load",
      "The load is the resistance or weight the lever moves; the effort is the force you apply.", "ERR_TECH_G7MSA1_LOAD", 1),
    CLOZE("The force you apply to a lever is called the ____.",
      ["effort", "load", "pivot", "noise"], "effort",
      "Effort is the force applied; load is what it moves; fulcrum is the pivot.", "ERR_TECH_G7MSA1_EFFORT", 1),
    MC("Moving the effort further from the fulcrum on a first-class lever…",
      ["increases the mechanical advantage", "removes the load", "breaks the bar", "changes its colour"], "increases the mechanical advantage",
      "A longer effort arm increases mechanical advantage on a first-class lever.", "ERR_TECH_G7MSA1_ARM", 3),
    TF("In a first-class lever, the mechanical advantage depends on where the fulcrum is.", "True",
      "Moving the fulcrum changes the effort and load arm lengths, changing the mechanical advantage.", "ERR_TECH_G7MSA1_FIRSTDEPENDS", 2),
    {
      question: "Order the three parts of a lever from the names used in Technology.",
      input_type: "sequence",
      items: [
        { id: "a", text: "Effort (the force you apply)" },
        { id: "b", text: "Fulcrum (the pivot)" },
        { id: "c", text: "Load (what is moved)" },
      ],
      expected_order: ["a", "b", "c"],
      memo: "A lever has three parts: the effort you apply, the fulcrum it pivots on, and the load it moves.",
      error_signals: ["ERR_TECH_G7MSA1_SEQUENCE"], difficulty: 1,
    },
    {
      question: "Sort each tool by its lever class.",
      input_type: "sort-buckets",
      buckets: [{ id: "first", label: "First-class" }, { id: "second", label: "Second-class" }, { id: "third", label: "Third-class" }],
      items: [
        { id: "i1", text: "Seesaw", correct_bucket: "first" },
        { id: "i2", text: "Wheelbarrow", correct_bucket: "second" },
        { id: "i3", text: "Tweezers", correct_bucket: "third" },
        { id: "i4", text: "Crowbar prising a nail", correct_bucket: "first" },
      ],
      expected: "Seesaw and crowbar are first class; wheelbarrow is second class; tweezers are third class.",
      pass_threshold: 0.75,
      memo: "First: fulcrum in the middle. Second: load in the middle. Third: effort in the middle.", error_signals: ["ERR_TECH_G7MSA1_SORT"], difficulty: 3,
    },
    MC("Which lever class is used to get a strong gripping force in a nutcracker?",
      ["Second-class", "Third-class", "No class", "A pulley"], "Second-class",
      "A nutcracker is a second-class lever (load between fulcrum and effort), giving a strong force.", "ERR_TECH_G7MSA1_NUTCRACKER", 2),
    MC("Why use a long crowbar to lift a heavy rock?",
      ["The long effort arm gives a bigger mechanical advantage", "It looks better", "It is lighter", "It is a third-class lever"], "The long effort arm gives a bigger mechanical advantage",
      "A long effort arm increases mechanical advantage so a small effort lifts a big load.", "ERR_TECH_G7MSA1_CROWBAR", 2),
    CLOZE("A machine that lets a small effort move a large load gives a mechanical ____.",
      ["advantage", "colour", "weight", "sound"], "advantage",
      "Mechanical advantage = a small effort moves a larger load.", "ERR_TECH_G7MSA1_MAWORD", 1),
  ],

  // MS.A2 · Linkages in tools
  "TECH.G7.MS.A2": [
    MC("What is a linkage?",
      ["Levers joined together to work as a system", "A single magnet", "A type of paint", "A kind of food"], "Levers joined together to work as a system",
      "A linkage is two or more levers joined so they move together.", "ERR_TECH_G7MSA2_DEF", 1),
    MC("A pair of scissors is made of…",
      ["two linked first-class levers", "one pulley", "a single gear", "a battery"], "two linked first-class levers",
      "Scissors are two first-class levers linked at a central pivot.", "ERR_TECH_G7MSA2_SCISSORS", 1),
    MC("A pair of pliers works as…",
      ["linked first-class levers", "a second-class pulley", "a single magnet", "a spring only"], "linked first-class levers",
      "Pliers are linked first-class levers — squeezing the handles grips with the jaws.", "ERR_TECH_G7MSA2_PLIERS", 2),
    MC("An office hole punch is an example of linked…",
      ["second-class levers", "third-class pulleys", "magnets", "gears"], "second-class levers",
      "A hole punch uses linked second-class levers to give a strong punching force.", "ERR_TECH_G7MSA2_PUNCH", 2),
    MC("A light-duty office stapler is an example of a linked…",
      ["third-class lever", "second-class pulley", "magnet", "gear train"], "third-class lever",
      "A light stapler is a third-class lever — the effort is between the pivot and the staple.", "ERR_TECH_G7MSA2_STAPLER", 2),
    TF("Linkages can change the direction or size of a movement.", "True",
      "Linkages transfer and can change the direction or amount of movement between parts.", "ERR_TECH_G7MSA2_CHANGE", 2),
    CLOZE("Two or more levers joined to move together form a ____.",
      ["linkage", "battery", "magnet", "shell"], "linkage",
      "A linkage is levers joined to move together.", "ERR_TECH_G7MSA2_WORD", 1),
    MC("Hedge-trimming shears with long handles and short blades give…",
      ["a large cutting force (mechanical advantage)", "no force at all", "light only", "sound only"], "a large cutting force (mechanical advantage)",
      "Long handles and short blades give linked levers a large cutting force.", "ERR_TECH_G7MSA2_SHEARS", 2),
    MC("Why do nutcrackers and bolt cutters have long handles?",
      ["To increase the force at the jaws", "To look nice", "To be heavier", "To save metal"], "To increase the force at the jaws",
      "Long handles give a bigger mechanical advantage, increasing the gripping/cutting force.", "ERR_TECH_G7MSA2_LONGHANDLE", 2),
    TF("A more complex linkage can have more than one pivot.", "True",
      "Complex linkages use several pivots to make more complicated movements.", "ERR_TECH_G7MSA2_MULTIPIVOT", 2),
    MC("In scissors, where is the pivot (fulcrum)?",
      ["In the middle, between handles and blades", "At the very tip", "Outside the scissors", "There is none"], "In the middle, between handles and blades",
      "The pivot of scissors is central — making each side a first-class lever.", "ERR_TECH_G7MSA2_PIVOT", 1),
    CLOZE("Pliers and scissors are both linked ____-class levers.",
      ["first", "second", "third", "fourth"], "first",
      "Both pliers and scissors are pairs of first-class levers.", "ERR_TECH_G7MSA2_FIRSTLINK", 2),
    MC("Which everyday tool is a linkage of two levers?",
      ["A pair of pliers", "A torch bulb", "A magnet", "A battery"], "A pair of pliers",
      "Pliers are a linkage of two levers; a bulb, magnet and battery are not levers.", "ERR_TECH_G7MSA2_TOOL", 1),
    TF("Tweezers are a single third-class lever rather than a linked pair.", "False",
      "Tweezers are two third-class levers linked together (joined at one end).", "ERR_TECH_G7MSA2_TWEEZERS", 2),
    {
      question: "Sort each tool by the lever class of its linkage.",
      input_type: "sort-buckets",
      buckets: [{ id: "first", label: "Linked first-class" }, { id: "second", label: "Linked second-class" }, { id: "third", label: "Linked third-class" }],
      items: [
        { id: "i1", text: "Scissors", correct_bucket: "first" },
        { id: "i2", text: "Pliers", correct_bucket: "first" },
        { id: "i3", text: "Office hole punch", correct_bucket: "second" },
        { id: "i4", text: "Light office stapler", correct_bucket: "third" },
      ],
      expected: "Scissors and pliers are linked first-class; a hole punch is linked second-class; a light stapler is linked third-class.",
      pass_threshold: 0.75,
      memo: "Scissors/pliers = first class; hole punch = second class; light stapler/tweezers = third class.", error_signals: ["ERR_TECH_G7MSA2_SORT"], difficulty: 3,
    },
    MC("The main purpose of a linkage in a tool is to…",
      ["pass on or change a movement or force", "store electricity", "make light", "play sound"], "pass on or change a movement or force",
      "Linkages transfer and change movement or force between the parts of a tool.", "ERR_TECH_G7MSA2_PURPOSE", 1),
    TF("Squeezing the handles of pliers makes the jaws move closer together.", "True",
      "The linked levers turn handle movement into jaw movement to grip.", "ERR_TECH_G7MSA2_GRIP", 1),
    MC("Bigger handles on bolt cutters mainly change the…",
      ["force at the cutting jaws", "colour", "weight only", "sound"], "force at the cutting jaws",
      "Longer handles increase the force the linkage delivers at the jaws.", "ERR_TECH_G7MSA2_BOLT", 2),
    CLOZE("A tool with several pivots is a ____ linkage.",
      ["complex", "simple", "broken", "single"], "complex",
      "More than one pivot makes a complex linkage.", "ERR_TECH_G7MSA2_COMPLEX", 2),
    MC("Garden secateurs (pruning shears) are linked levers designed mainly to…",
      ["cut branches with a strong force", "make light", "store water", "play sound"], "cut branches with a strong force",
      "Secateurs are linked levers that give a strong cutting force at the blades.", "ERR_TECH_G7MSA2_SECATEURS", 2),
  ],

  // MS.A3 · Pneumatics & hydraulics
  "TECH.G7.MS.A3": [
    MC("What does a PNEUMATIC system use to transfer force?",
      ["Air (a gas)", "Water (a liquid)", "Sand", "Electricity"], "Air (a gas)",
      "Pneumatic systems use compressed air (a gas) to transfer force.", "ERR_TECH_G7MSA3_PNEUMATIC", 1),
    MC("What does a HYDRAULIC system use to transfer force?",
      ["A liquid such as water or oil", "Air only", "Light", "Sound"], "A liquid such as water or oil",
      "Hydraulic systems use a liquid (water or oil) to transfer force.", "ERR_TECH_G7MSA3_HYDRAULIC", 1),
    TF("In these systems, force is transferred through a tube from one syringe to another.", "True",
      "Pushing one syringe pushes the fluid through the tube, moving the other syringe.", "ERR_TECH_G7MSA3_TRANSFER", 1),
    MC("Which fluid can be squashed (compressed) more easily?",
      ["Air (a gas)", "Water (a liquid)", "Both equally", "Neither"], "Air (a gas)",
      "Gases like air are compressible; liquids like water are almost incompressible.", "ERR_TECH_G7MSA3_COMPRESS", 2),
    TF("Liquids are almost impossible to squash, which makes hydraulics feel firm.", "True",
      "Liquids are incompressible, so hydraulic systems feel solid and transfer force well.", "ERR_TECH_G7MSA3_INCOMPRESS", 2),
    MC("Pushing a small syringe connected to a LARGER syringe will…",
      ["move the large piston with more force but less distance", "do nothing", "make light", "freeze the water"], "move the large piston with more force but less distance",
      "A small input to a large cylinder gives more force over a shorter movement — a mechanical advantage.", "ERR_TECH_G7MSA3_LARGE", 3),
    CLOZE("A system that uses compressed air to do work is called ____.",
      ["pneumatic", "hydraulic", "magnetic", "electric"], "pneumatic",
      "Pneumatic = powered by compressed air.", "ERR_TECH_G7MSA3_PNEUWORD", 1),
    CLOZE("A system that uses a liquid to do work is called ____.",
      ["hydraulic", "pneumatic", "magnetic", "solar"], "hydraulic",
      "Hydraulic = powered by a liquid.", "ERR_TECH_G7MSA3_HYDWORD", 1),
    MC("Which machine uses hydraulics?",
      ["A digger's (excavator's) arm", "A paper kite", "A candle", "A book"], "A digger's (excavator's) arm",
      "Excavator arms use hydraulic cylinders to push and lift with great force.", "ERR_TECH_G7MSA3_DIGGER", 2),
    MC("Why might 'Jaws of Life' rescue tools use hydraulics?",
      ["To produce a very large force to cut or spread metal", "To make light", "To be colourful", "To play music"], "To produce a very large force to cut or spread metal",
      "Hydraulics multiply force, giving rescue tools the power to cut and spread metal.", "ERR_TECH_G7MSA3_JAWS", 2),
    TF("Air brakes on a bus are an example of a pneumatic system.", "True",
      "Air (pneumatic) brakes use compressed air to operate the brakes.", "ERR_TECH_G7MSA3_AIRBRAKE", 2),
    MC("A pneumatic system feels 'springy' compared with a hydraulic one because…",
      ["air can be compressed", "air is heavier", "air is a liquid", "air is solid"], "air can be compressed",
      "Air compresses, so pneumatic systems feel springy; hydraulics feel firm.", "ERR_TECH_G7MSA3_SPRINGY", 3),
    CLOZE("Force is transferred between two syringes through the connecting ____.",
      ["tube", "wire", "magnet", "battery"], "tube",
      "The fluid carries the force through the connecting tube.", "ERR_TECH_G7MSA3_TUBE", 1),
    MC("Two EQUAL-sized syringes connected by a tube will move…",
      ["the same distance as each other", "very different distances", "in opposite seasons", "not at all"], "the same distance as each other",
      "Equal syringes move equal distances; force and movement are unchanged.", "ERR_TECH_G7MSA3_EQUAL", 2),
    {
      question: "Sort each example into 'Pneumatic' or 'Hydraulic'.",
      input_type: "sort-buckets",
      buckets: [{ id: "pneu", label: "Pneumatic (air)" }, { id: "hyd", label: "Hydraulic (liquid)" }],
      items: [
        { id: "i1", text: "Bus air brakes", correct_bucket: "pneu" },
        { id: "i2", text: "Excavator digging arm", correct_bucket: "hyd" },
        { id: "i3", text: "Bicycle pump pushing air", correct_bucket: "pneu" },
        { id: "i4", text: "Car hydraulic jack", correct_bucket: "hyd" },
      ],
      expected: "Air brakes and a pump are pneumatic; an excavator arm and a car jack are hydraulic.",
      pass_threshold: 0.75,
      memo: "Pneumatic systems use air; hydraulic systems use a liquid.", error_signals: ["ERR_TECH_G7MSA3_SORT"], difficulty: 2,
    },
    MC("Both pneumatic and hydraulic systems are used to…",
      ["transfer force to do work", "make sound only", "store data", "give off light"], "transfer force to do work",
      "Both transfer force through a fluid to do useful work, often with a mechanical advantage.", "ERR_TECH_G7MSA3_BOTH", 1),
    TF("Hydraulic systems can produce very large forces, which is why they lift heavy loads.", "True",
      "Because liquids are incompressible and force can be multiplied, hydraulics lift heavy loads.", "ERR_TECH_G7MSA3_HEAVY", 2),
    MC("Which is an advantage of hydraulics over pneumatics for heavy lifting?",
      ["The liquid does not compress, so movement is firm and controlled", "Air is stronger", "Liquid is lighter", "Air never leaks"], "The liquid does not compress, so movement is firm and controlled",
      "Incompressible liquid gives firm, controlled, powerful movement for heavy lifting.", "ERR_TECH_G7MSA3_ADV", 3),
    CLOZE("Gases can be compressed, but liquids are nearly ____.",
      ["incompressible", "invisible", "magnetic", "electric"], "incompressible",
      "Liquids are nearly incompressible; gases compress easily.", "ERR_TECH_G7MSA3_INCOMP2", 2),
    MC("A dentist's chair that is raised by foot-pumping a lever most likely uses a…",
      ["hydraulic system", "magnet", "pulley belt", "gear box"], "hydraulic system",
      "Dentist and barber chairs are commonly raised by a hydraulic system pumped with the foot.", "ERR_TECH_G7MSA3_CHAIR", 3),
  ],

  // MS.A4 · Cranks & pulleys
  "TECH.G7.MS.A4": [
    MC("What does a crank do?",
      ["Changes round (rotary) motion into back-and-forth (reciprocating) motion", "Stores electricity", "Makes light", "Cools water"], "Changes round (rotary) motion into back-and-forth (reciprocating) motion",
      "A crank converts rotary motion into reciprocating (back-and-forth) motion, and vice versa.", "ERR_TECH_G7MSA4_CRANK", 2),
    MC("A pulley is a type of…",
      ["wheel and axle", "lever only", "magnet", "battery"], "wheel and axle",
      "A pulley is a wheel turning on an axle, often with a rope or belt around it.", "ERR_TECH_G7MSA4_PULLEY", 1),
    TF("A crank is an adaptation of a second-class lever.", "True",
      "CAPS describes the crank as an adapted second-class lever.", "ERR_TECH_G7MSA4_CRANKLEVER", 2),
    MC("What is one common use of a pulley?",
      ["Lifting a load with a rope over a wheel", "Storing data", "Making sound", "Boiling water"], "Lifting a load with a rope over a wheel",
      "Pulleys are used to lift loads and to change the direction of a pulling force.", "ERR_TECH_G7MSA4_USE", 1),
    MC("A single fixed pulley mainly changes the…",
      ["direction of the pulling force", "colour of the rope", "temperature", "sound"], "direction of the pulling force",
      "A fixed pulley changes the direction of the force — you pull down to raise a load up.", "ERR_TECH_G7MSA4_FIXED", 2),
    CLOZE("A crank turns rotary motion into ____ motion.",
      ["reciprocating", "electrical", "magnetic", "musical"], "reciprocating",
      "A crank changes rotary motion into reciprocating (back-and-forth) motion.", "ERR_TECH_G7MSA4_RECIP", 2),
    TF("A pulley can be used to make lifting a load easier.", "True",
      "Pulley systems can give a mechanical advantage, making lifting easier.", "ERR_TECH_G7MSA4_EASIER", 1),
    MC("Where would you find a crank in everyday life?",
      ["The pedals of a bicycle", "A glass of water", "A wall poster", "A pillow"], "The pedals of a bicycle",
      "Bicycle pedals use a crank to turn your legs' motion into rotation of the wheel.", "ERR_TECH_G7MSA4_BICYCLE", 2),
    MC("A flagpole uses a pulley at the top to…",
      ["raise and lower the flag by pulling a rope", "store electricity", "make the flag glow", "cool the air"], "raise and lower the flag by pulling a rope",
      "A flagpole pulley lets you raise the flag by pulling down on the rope.", "ERR_TECH_G7MSA4_FLAGPOLE", 1),
    TF("All complex machines are built from combinations of simple mechanisms.", "True",
      "Complex machinery is made by combining simple mechanisms like levers, cranks and pulleys.", "ERR_TECH_G7MSA4_COMBINE", 2),
    CLOZE("A wheel turning on an axle with a rope around it is a ____.",
      ["pulley", "lever", "magnet", "spring"], "pulley",
      "That description is a pulley — a wheel-and-axle with a rope or belt.", "ERR_TECH_G7MSA4_PULLEYWORD", 1),
    MC("A hand drill turned by a handle uses a crank to…",
      ["turn the handle's motion into rotation of the drill", "make light", "cool the bit", "store charge"], "turn the handle's motion into rotation of the drill",
      "The crank handle converts your hand movement into rotation of the drill bit.", "ERR_TECH_G7MSA4_DRILL", 2),
    MC("Why might a crane combine a frame structure with a pulley and crank?",
      ["The frame supports it while the pulley and crank lift and move loads", "For decoration", "To make noise", "To cool down"], "The frame supports it while the pulley and crank lift and move loads",
      "A crane uses a rigid triangulated frame plus a pulley and crank mechanism to lift loads.", "ERR_TECH_G7MSA4_CRANE", 3),
    TF("A pulley can change both the direction and (with more wheels) the amount of force.", "True",
      "A fixed pulley changes direction; adding moveable pulleys multiplies the force.", "ERR_TECH_G7MSA4_DIRFORCE", 2),
    {
      question: "Sort each mechanism by what it mainly does.",
      input_type: "sort-buckets",
      buckets: [{ id: "crank", label: "Crank" }, { id: "pulley", label: "Pulley" }],
      items: [
        { id: "i1", text: "Turns rotary motion into back-and-forth motion", correct_bucket: "crank" },
        { id: "i2", text: "Lifts a load with a rope over a wheel", correct_bucket: "pulley" },
        { id: "i3", text: "Bicycle pedal arm", correct_bucket: "crank" },
        { id: "i4", text: "Flagpole rope wheel", correct_bucket: "pulley" },
      ],
      expected: "A crank changes rotary to reciprocating motion (bicycle pedal); a pulley lifts loads with a rope (flagpole).",
      pass_threshold: 0.75,
      memo: "Crank = converts rotary↔reciprocating motion; pulley = wheel-and-axle for lifting and changing force direction.", error_signals: ["ERR_TECH_G7MSA4_SORT"], difficulty: 3,
    },
    MC("Levers, cranks and pulleys are all examples of…",
      ["simple mechanisms", "electronic chips", "liquids", "magnets"], "simple mechanisms",
      "Levers, cranks and pulleys are simple mechanisms that make work easier.", "ERR_TECH_G7MSA4_SIMPLE", 1),
    TF("A pulley belt can transfer rotation from one wheel to another.", "True",
      "A belt around two pulleys transfers rotation from a driver wheel to a driven wheel.", "ERR_TECH_G7MSA4_BELT", 2),
    MC("To lift a load straight up by pulling down on a rope, you would use a…",
      ["fixed pulley", "magnet", "battery", "lever only"], "fixed pulley",
      "A fixed pulley changes your downward pull into an upward lift.", "ERR_TECH_G7MSA4_LIFTUP", 2),
    CLOZE("A crank is described as an adapted ____-class lever.",
      ["second", "first", "third", "fourth"], "second",
      "CAPS treats the crank as an adapted second-class lever.", "ERR_TECH_G7MSA4_SECONDCLASS", 2),
    MC("Two pulleys joined by a belt are used to…",
      ["transfer rotation from one shaft to another", "store electricity", "make a magnet", "boil water"], "transfer rotation from one shaft to another",
      "A belt over two pulleys carries rotation from a driver wheel to a driven wheel.", "ERR_TECH_G7MSA4_BELT2", 2),
  ],
};

export default G7;
