// ─── Reading Diagnostic Task Bank ─────────────────────────────────────────────
// 18 tasks administered once per student to determine reading placement.
// Full test always administered — no early exit.

export type DiagnosticTaskMode = "voice" | "text" | "tap" | "voice-timed";

export interface DiagnosticItem {
  id: string;
  prompt: string;       // shown on screen and spoken via TTS
  expected: string;     // correct answer (normalised lowercase)
  options?: string[];   // for tap mode only
}

export interface DiagnosticTask {
  id: string;
  domain: string;
  mode: DiagnosticTaskMode;
  description: string;
  instruction: string;  // student-facing instruction
  items: DiagnosticItem[];
  passThreshold: number;   // 0–1 fraction of items that must pass
  mapsToSkill: string;     // entry skill if this task is the first failure
  isHardGateSignal?: boolean;
}

export const DIAGNOSTIC_TASKS: DiagnosticTask[] = [
  {
    id: "D01",
    domain: "Phonological Awareness",
    mode: "voice",
    description: "Rhyme detection and syllable segmentation",
    instruction: "Listen to each question and say your answer out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R1.T2.A1",
    items: [
      { id: "D01-01", prompt: 'Do "cat" and "bat" rhyme? Say yes or no.', expected: "yes" },
      { id: "D01-02", prompt: 'Do "dog" and "log" rhyme? Say yes or no.', expected: "yes" },
      { id: "D01-03", prompt: 'Do "sun" and "cup" rhyme? Say yes or no.', expected: "no" },
      { id: "D01-04", prompt: 'How many syllables in "elephant"? Say the number.', expected: "3" },
      { id: "D01-05", prompt: 'How many syllables in "cat"? Say the number.', expected: "1" },
      { id: "D01-06", prompt: 'How many syllables in "banana"? Say the number.', expected: "3" },
    ],
  },
  {
    id: "D01B",
    domain: "Syllable Segmentation",
    mode: "tap",
    description: "Segment spoken words into syllables and blend syllable sequences",
    instruction: "Listen to each question and tap the correct answer.",
    passThreshold: 0.75,
    mapsToSkill: "R1.T2.A2",
    items: [
      { id: "D01B-01", prompt: 'How many syllables in "rabbit"?', expected: "2", options: ["1", "2", "3"] },
      { id: "D01B-02", prompt: 'How many syllables in "umbrella"?', expected: "3", options: ["2", "3", "4"] },
      { id: "D01B-03", prompt: 'Blend these syllables into a word: "but – ter – fly". What word?', expected: "butterfly", options: ["blueberry", "butterfly", "buttercup"] },
      { id: "D01B-04", prompt: 'How many syllables in "pencil"?', expected: "2", options: ["1", "2", "3"] },
    ],
  },
  {
    id: "D02",
    domain: "Phoneme Isolation",
    mode: "voice",
    description: "Onset and coda phoneme identification",
    instruction: "Listen to each word and say the sound I ask for.",
    passThreshold: 0.8,
    mapsToSkill: "R1.T2.A1",
    items: [
      { id: "D02-01", prompt: 'What is the first sound in "cat"?', expected: "k" },
      { id: "D02-02", prompt: 'What is the first sound in "fish"?', expected: "f" },
      { id: "D02-03", prompt: 'What is the first sound in "big"?', expected: "b" },
      { id: "D02-04", prompt: 'What is the last sound in "map"?', expected: "p" },
      { id: "D02-05", prompt: 'What is the last sound in "bed"?', expected: "d" },
      { id: "D02-06", prompt: 'What is the last sound in "log"?', expected: "g" },
    ],
  },
  {
    id: "D02B",
    domain: "Full Phoneme Segmentation",
    mode: "tap",
    description: "Count the individual phonemes in spoken words",
    instruction: "Listen to the word and tap how many sounds you hear.",
    passThreshold: 0.75,
    mapsToSkill: "R1.T3.A2",
    items: [
      { id: "D02B-01", prompt: 'How many sounds are in "cat"? (/k/ /a/ /t/)', expected: "3", options: ["2", "3", "4"] },
      { id: "D02B-02", prompt: 'How many sounds are in "ship"? (/sh/ /i/ /p/)', expected: "3", options: ["2", "3", "4"] },
      { id: "D02B-03", prompt: 'How many sounds are in "flag"? (/f/ /l/ /a/ /g/)', expected: "4", options: ["3", "4", "5"] },
      { id: "D02B-04", prompt: 'What is the last sound in "dog"?', expected: "/g/", options: ["/d/", "/o/", "/g/"] },
    ],
  },
  {
    id: "D03",
    domain: "Letter Sound — Consonants",
    mode: "voice",
    description: "Consonant letter-sound correspondence",
    instruction: "Tell me the sound each letter makes.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T1.A1",
    items: [
      { id: "D03-01", prompt: 'What sound does the letter "b" make?', expected: "b" },
      { id: "D03-02", prompt: 'What sound does the letter "d" make?', expected: "d" },
      { id: "D03-03", prompt: 'What sound does the letter "f" make?', expected: "f" },
      { id: "D03-04", prompt: 'What sound does the letter "g" make?', expected: "g" },
      { id: "D03-05", prompt: 'What sound does the letter "h" make?', expected: "h" },
      { id: "D03-06", prompt: 'What sound does the letter "l" make?', expected: "l" },
      { id: "D03-07", prompt: 'What sound does the letter "m" make?', expected: "m" },
      { id: "D03-08", prompt: 'What sound does the letter "n" make?', expected: "n" },
      { id: "D03-09", prompt: 'What sound does the letter "p" make?', expected: "p" },
      { id: "D03-10", prompt: 'What sound does the letter "s" make?', expected: "s" },
    ],
  },
  {
    id: "D04",
    domain: "Letter Sound — Vowels",
    mode: "voice",
    description: "Short vowel letter-sound correspondence",
    instruction: "Tell me the short sound each vowel makes.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T1.A1",
    items: [
      { id: "D04-01", prompt: 'What is the short sound of "a", like in "cat"?', expected: "a" },
      { id: "D04-02", prompt: 'What is the short sound of "e", like in "bed"?', expected: "e" },
      { id: "D04-03", prompt: 'What is the short sound of "i", like in "sit"?', expected: "i" },
      { id: "D04-04", prompt: 'What is the short sound of "o", like in "hot"?', expected: "o" },
      { id: "D04-05", prompt: 'What is the short sound of "u", like in "cup"?', expected: "u" },
    ],
  },
  {
    id: "D05",
    domain: "CVC Decoding",
    mode: "voice",
    description: "Unfamiliar CVC word decoding",
    instruction: "Read each made-up word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T1.A1",
    items: [
      { id: "D05-01", prompt: 'Read this made-up word: "zib"', expected: "zib" },
      { id: "D05-02", prompt: 'Read this made-up word: "fot"', expected: "fot" },
      { id: "D05-03", prompt: 'Read this made-up word: "vem"', expected: "vem" },
      { id: "D05-04", prompt: 'Read this made-up word: "dak"', expected: "dak" },
      { id: "D05-05", prompt: 'Read this made-up word: "wup"', expected: "wup" },
    ],
  },
  {
    id: "D06",
    domain: "CVC Encoding",
    mode: "text",
    description: "CVC sound-to-spelling encoding — Hard Gate",
    instruction: "Listen to the sounds and type the word they make.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T1.A1",
    isHardGateSignal: true,
    items: [
      { id: "D06-01", prompt: 'Type the word made by these sounds: /b/ /i/ /g/', expected: "big" },
      { id: "D06-02", prompt: 'Type the word made by these sounds: /s/ /u/ /n/', expected: "sun" },
      { id: "D06-03", prompt: 'Type the word made by these sounds: /m/ /e/ /p/', expected: "mep" },
    ],
  },
  {
    id: "D07",
    domain: "Digraph Recognition",
    mode: "voice",
    description: "Common digraph decoding (sh, ch, th, ck)",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T2.A1",
    items: [
      { id: "D07-01", prompt: 'Read this word: "shop"', expected: "shop" },
      { id: "D07-02", prompt: 'Read this word: "chip"', expected: "chip" },
      { id: "D07-03", prompt: 'Read this word: "that"', expected: "that" },
      { id: "D07-04", prompt: 'Read this word: "back"', expected: "back" },
    ],
  },
  {
    id: "D08",
    domain: "Consonant Blend Decoding",
    mode: "voice",
    description: "CCVC and CVCC blend word decoding",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T2.A1",
    items: [
      { id: "D08-01", prompt: 'Read this word: "frog"', expected: "frog" },
      { id: "D08-02", prompt: 'Read this word: "slim"', expected: "slim" },
      { id: "D08-03", prompt: 'Read this word: "blot"', expected: "blot" },
      { id: "D08-04", prompt: 'Read this word: "lamp"', expected: "lamp" },
      { id: "D08-05", prompt: 'Read this word: "mist"', expected: "mist" },
    ],
  },
  {
    id: "D09",
    domain: "Long Vowel — Silent E",
    mode: "voice",
    description: "CVCe word decoding",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T2.A3",
    items: [
      { id: "D09-01", prompt: 'Read this word: "cake"', expected: "cake" },
      { id: "D09-02", prompt: 'Read this word: "kite"', expected: "kite" },
      { id: "D09-03", prompt: 'Read this word: "hope"', expected: "hope" },
      { id: "D09-04", prompt: 'Read this word: "tube"', expected: "tube" },
    ],
  },
  {
    id: "D10",
    domain: "Vowel Teams",
    mode: "voice",
    description: "Common vowel team word decoding (ai, ea, oa, oo)",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T3.A1",
    items: [
      { id: "D10-01", prompt: 'Read this word: "rain"', expected: "rain" },
      { id: "D10-02", prompt: 'Read this word: "leaf"', expected: "leaf" },
      { id: "D10-03", prompt: 'Read this word: "boat"', expected: "boat" },
      { id: "D10-04", prompt: 'Read this word: "moon"', expected: "moon" },
    ],
  },
  {
    id: "D10B",
    domain: "Phoneme Sequence Blending",
    mode: "tap",
    description: "Blend a spoken phoneme sequence into a word with multi-phoneme clusters",
    instruction: "Listen to the sounds and tap the word they make.",
    passThreshold: 0.75,
    mapsToSkill: "R2.T3.A3",
    items: [
      { id: "D10B-01", prompt: "Blend these sounds: /s/ /t/ /r/ /ee/ /t/ — what word?", expected: "street", options: ["streak", "street", "stream"] },
      { id: "D10B-02", prompt: "Blend these sounds: /b/ /r/ /igh/ /t/ — what word?", expected: "bright", options: ["fright", "bright", "blight"] },
      { id: "D10B-03", prompt: "Blend these sounds: /f/ /l/ /oa/ /t/ — what word?", expected: "float", options: ["bloat", "float", "throat"] },
    ],
  },
  {
    id: "D11",
    domain: "Sight Words",
    mode: "voice-timed",
    description: "High-frequency word rapid recognition (1.5 s per word)",
    instruction: "Read each word as fast as you can when it appears.",
    passThreshold: 0.9,
    mapsToSkill: "R3.T1.A1",
    items: [
      { id: "D11-01", prompt: "the", expected: "the" },
      { id: "D11-02", prompt: "and", expected: "and" },
      { id: "D11-03", prompt: "said", expected: "said" },
      { id: "D11-04", prompt: "have", expected: "have" },
      { id: "D11-05", prompt: "they", expected: "they" },
      { id: "D11-06", prompt: "was", expected: "was" },
      { id: "D11-07", prompt: "from", expected: "from" },
      { id: "D11-08", prompt: "with", expected: "with" },
      { id: "D11-09", prompt: "here", expected: "here" },
      { id: "D11-10", prompt: "come", expected: "come" },
    ],
  },
  {
    id: "D12",
    domain: "R-Controlled Vowels",
    mode: "voice",
    description: "R-controlled vowel pattern decoding (ar, er, or)",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R2.T3.A2",
    items: [
      { id: "D12-01", prompt: 'Read this word: "bark"', expected: "bark" },
      { id: "D12-02", prompt: 'Read this word: "fern"', expected: "fern" },
      { id: "D12-03", prompt: 'Read this word: "corn"', expected: "corn" },
    ],
  },
  {
    id: "D13",
    domain: "Two-Syllable Decoding",
    mode: "voice",
    description: "Two-syllable decodable word reading",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R3.T2.A1",
    items: [
      { id: "D13-01", prompt: 'Read this word: "plastic"', expected: "plastic" },
      { id: "D13-02", prompt: 'Read this word: "itself"', expected: "itself" },
      { id: "D13-03", prompt: 'Read this word: "sunset"', expected: "sunset" },
      { id: "D13-04", prompt: 'Read this word: "kitten"', expected: "kitten" },
    ],
  },
  {
    id: "D13B",
    domain: "Consonant Blend Encoding",
    mode: "voice",
    description: "Spell words with CCVC and CVCC blend patterns",
    instruction: "Listen to each word and spell it out loud, letter by letter.",
    passThreshold: 0.75,
    mapsToSkill: "R3.T1.A2",
    items: [
      { id: "D13B-01", prompt: 'Spell this word: "flag"', expected: "f l a g" },
      { id: "D13B-02", prompt: 'Spell this word: "best"', expected: "b e s t" },
      { id: "D13B-03", prompt: 'Spell this word: "jump"', expected: "j u m p" },
      { id: "D13B-04", prompt: 'Spell this word: "clap"', expected: "c l a p" },
    ],
  },
  {
    id: "D13C",
    domain: "Unfamiliar Word Encoding",
    mode: "voice",
    description: "Spell phonetically regular but unfamiliar words using phonological analysis",
    instruction: "Listen to each made-up word and spell it out loud. Use the sounds to work it out.",
    passThreshold: 0.67,
    mapsToSkill: "R3.T1.A3",
    items: [
      { id: "D13C-01", prompt: 'Spell this made-up word: "nup"', expected: "n u p" },
      { id: "D13C-02", prompt: 'Spell this made-up word: "greb"', expected: "g r e b" },
      { id: "D13C-03", prompt: 'Spell this made-up word: "spav"', expected: "s p a v" },
    ],
  },
  {
    id: "D14",
    domain: "Multisyllabic Decoding",
    mode: "voice",
    description: "Three-syllable word decoding",
    instruction: "Read each word out loud.",
    passThreshold: 0.8,
    mapsToSkill: "R4.T1.A1",
    items: [
      { id: "D14-01", prompt: 'Read this word: "fantastic"', expected: "fantastic" },
      { id: "D14-02", prompt: 'Read this word: "umbrella"', expected: "umbrella" },
      { id: "D14-03", prompt: 'Read this word: "important"', expected: "important" },
    ],
  },
  {
    id: "D15",
    domain: "Prefix & Suffix Recognition",
    mode: "tap",
    description: "Morpheme identification in context",
    instruction: "Tap on the prefix or suffix in each word.",
    passThreshold: 0.75,
    mapsToSkill: "R4.T2.A1",
    items: [
      { id: "D15-01", prompt: 'Which part of "unhappy" is the prefix?', expected: "un", options: ["un", "happ", "y"] },
      { id: "D15-02", prompt: 'Which part of "jumping" is the suffix?', expected: "ing", options: ["jump", "ing", "j"] },
      { id: "D15-03", prompt: 'Which part of "redo" is the prefix?', expected: "re", options: ["re", "do", "ed"] },
      { id: "D15-04", prompt: 'Which part of "kindness" is the suffix?', expected: "ness", options: ["kind", "ness", "ki"] },
    ],
  },
  {
    id: "D15B",
    domain: "Self-Monitoring for Meaning",
    mode: "tap",
    description: "Identify when reading breaks down and apply fix-up strategies",
    instruction: "Read each question and tap the best answer.",
    passThreshold: 1.0,
    mapsToSkill: "R4.T3.A2",
    items: [
      {
        id: "D15B-01",
        prompt: 'You read a sentence and it doesn\'t make sense. What should you do?',
        expected: "reread the sentence",
        options: ["reread the sentence", "read faster", "skip to the next page"],
      },
      {
        id: "D15B-02",
        prompt: 'You read "The dog ran over the pond" but dogs can\'t run over ponds. What should you do?',
        expected: "go back and check the word",
        options: ["keep reading", "go back and check the word", "ask someone to read it for you"],
      },
    ],
  },
  {
    id: "D16",
    domain: "Oral Reading Fluency",
    mode: "voice-timed",
    description: "50-word passage read aloud — WPM and prosody",
    instruction: "Read the passage below out loud. Press Start when you are ready, then read until you finish.",
    passThreshold: 0.8, // WPM ≥ 60 maps to pass
    mapsToSkill: "R4.T1.A1",
    items: [
      {
        id: "D16-01",
        prompt: "The sun was bright and the sky was blue. A little dog ran across the green field. It stopped to sniff a flower, then kept running. A boy called out to the dog. The dog turned around and ran back to him. The boy laughed and patted the dog on its soft, brown head.",
        expected: "60", // target WPM
      },
    ],
  },
  {
    id: "D17",
    domain: "Literal Comprehension",
    mode: "tap",
    description: "Explicit information retrieval from the D16 fluency passage",
    instruction: "Read the passage, then tap the best answer to each question.",
    passThreshold: 0.8,
    mapsToSkill: "R4.T3.A1",
    items: [
      {
        id: "D17-01",
        prompt: 'Passage: "The sun was bright and the sky was blue. A little dog ran across the green field. It stopped to sniff a flower, then kept running. A boy called out to the dog. The dog turned around and ran back to him. The boy laughed and patted the dog on its soft, brown head." — What did the dog stop to sniff?',
        expected: "a flower",
        options: ["a tree", "a flower", "the boy's hand"],
      },
      {
        id: "D17-02",
        prompt: 'In the same passage — what colour was the field?',
        expected: "green",
        options: ["brown", "blue", "green"],
      },
      {
        id: "D17-03",
        prompt: 'What did the boy do after the dog ran back to him?',
        expected: "laughed and patted the dog",
        options: ["ran away", "laughed and patted the dog", "called out again"],
      },
    ],
  },
  {
    id: "D18",
    domain: "Inferential Comprehension",
    mode: "tap",
    description: "Inference and implied meaning from the D16 fluency passage",
    instruction: "Use the same passage to answer these questions. The answer is not said directly — you need to think about it.",
    passThreshold: 0.75,
    mapsToSkill: "R5.T1.A1",
    items: [
      {
        id: "D18-01",
        prompt: 'In the passage about the dog and the boy — why do you think the dog ran back to the boy?',
        expected: "the boy called it",
        options: ["it was tired", "the boy called it", "it was scared"],
      },
      {
        id: "D18-02",
        prompt: 'What does the passage tell you about how the boy feels about the dog?',
        expected: "he likes the dog",
        options: ["he is angry at the dog", "he likes the dog", "he ignores the dog"],
      },
    ],
  },
];
