// Grade 10 — Taalstrukture tier, skills TAA.01–TAA.06 (20 items each).
// All learner-facing text is Afrikaans (question + options + ruby_prompt + memo).
import { ch, tf, cz, sq, skill, insertSkills } from "./_g10_bank_lib.mjs";

const P = "AF.G10.TAA";
const E = {
  PLURAL: "ERR_AF_PLURAL", DIM: "ERR_AF_DIMINUTIVE", GENDER: "ERR_AF_GENDER",
  PRON: "ERR_AF_PRONOUN", ADJ: "ERR_AF_ADJECTIVE", COMP: "ERR_AF_COMPARISON",
  TENSE: "ERR_AF_TENSE", VERB: "ERR_AF_VERB", CONJ: "ERR_AF_CONJUNCTION",
  ORDER: "ERR_AF_WORDORDER", SENT: "ERR_AF_SENTENCETYPE", NEG: "ERR_AF_NEGATION",
  GRAM: "ERR_AF_GRAMMAR",
};

const skills = {
  ...skill(`${P}.01`, "Selfstandige naamwoorde: meervoud, verkleining, geslag",
    "Meervoude, verkleinings en geslagsvorme van Afrikaanse selfstandige naamwoorde.",
    "Taalstrukture", "T1-T4", ["choice", "cloze", "true-false"],
    "Meervoude volg patrone (dikwels -e of -s, met deelteken/kappie waar nodig); verkleinings hang af van die laaste klank van die woord.",
    [
      ch("G10TAA01.01", "Wat is die meervoud van 'boom'?", ["bome", "booms", "bomme"], "bome", "Die meervoud van 'boom' is 'bome'.", [E.PLURAL], 1),
      ch("G10TAA01.02", "Wat is die meervoud van 'kind'?", ["kinders", "kinde", "kindere"], "kinders", "Die meervoud van 'kind' is 'kinders'.", [E.PLURAL], 1),
      ch("G10TAA01.03", "Wat is die meervoud van 'man'?", ["mans", "manne", "mannens"], "mans", "Die meervoud van 'man' is 'mans'.", [E.PLURAL], 1),
      ch("G10TAA01.04", "Wat is die meervoud van 'glas'?", ["glase", "glasse", "glasies"], "glase", "Die meervoud van 'glas' is 'glase'.", [E.PLURAL], 2),
      ch("G10TAA01.05", "Wat is die meervoud van 'foto'?", ["foto's", "fotos", "fotoe"], "foto's", "By 'foto' kry die meervoud 'n afkappingsteken: 'foto's'.", [E.PLURAL], 2),
      ch("G10TAA01.06", "Wat is die meervoud van 'oog'?", ["oë", "oge", "ooge"], "oë", "Die meervoud van 'oog' is 'oë' (met 'n deelteken op die e).", [E.PLURAL], 2),
      ch("G10TAA01.07", "Wat is die meervoud van 'appel'?", ["appels", "appele", "appelle"], "appels", "Die meervoud van 'appel' is 'appels'.", [E.PLURAL], 2),
      ch("G10TAA01.08", "Wat is die meervoud van 'kar'?", ["karre", "kars", "karres"], "karre", "Die meervoud van 'kar' is 'karre' (die r verdubbel).", [E.PLURAL], 2),
      ch("G10TAA01.09", "Wat is die meervoud van 'kalf'?", ["kalwers", "kalfs", "kalwe"], "kalwers", "Die meervoud van 'kalf' is 'kalwers' (die f word w).", [E.PLURAL], 3),
      ch("G10TAA01.10", "Wat is die verkleining van 'hond'?", ["hondjie", "hondtjie", "hondetjie"], "hondjie", "Die verkleining van 'hond' is 'hondjie'.", [E.DIM], 1),
      ch("G10TAA01.11", "Wat is die verkleining van 'kat'?", ["katjie", "kattjie", "katije"], "katjie", "Die verkleining van 'kat' is 'katjie'.", [E.DIM], 1),
      ch("G10TAA01.12", "Wat is die verkleining van 'man'?", ["mannetjie", "mantjie", "manjie"], "mannetjie", "Die verkleining van 'man' is 'mannetjie'.", [E.DIM], 2),
      ch("G10TAA01.13", "Wat is die verkleining van 'blom'?", ["blommetjie", "blomtjie", "blompie"], "blommetjie", "Die verkleining van 'blom' is 'blommetjie'.", [E.DIM], 3),
      ch("G10TAA01.14", "Wat is die verkleining van 'boom'?", ["boompie", "boomtjie", "boometjie"], "boompie", "Die verkleining van 'boom' is 'boompie'.", [E.DIM], 2),
      ch("G10TAA01.15", "Wat is die vroulike vorm van 'haan'?", ["hen", "hoender", "kuiken"], "hen", "Die vroulike vorm van 'haan' is 'hen'.", [E.GENDER], 1),
      ch("G10TAA01.16", "Wat is die vroulike vorm van 'bul'?", ["koei", "kalf", "os"], "koei", "Die vroulike vorm van 'bul' is 'koei'.", [E.GENDER], 1),
      ch("G10TAA01.17", "Wat is die vroulike vorm van 'koning'?", ["koningin", "prinses", "hertogin"], "koningin", "Die vroulike vorm van 'koning' is 'koningin'.", [E.GENDER], 2),
      cz("G10TAA01.18", "Vul die meervoud in: 'Daar is drie ___ in die tuin.' (boom)", ["bome", "boom", "booms"], "bome", "'boom' word 'bome' in die meervoud.", [E.PLURAL], 2),
      cz("G10TAA01.19", "Vul die verkleining in: 'Sy het 'n klein ___ gekry.' (kat)", ["katjie", "kat", "katte"], "katjie", "Die verkleining van 'kat' is 'katjie'.", [E.DIM], 2),
      tf("G10TAA01.20", "Is 'swerm' in ''n swerm bye' 'n versamelnaam?", "Waar", "Ja, 'swerm' noem 'n groep as geheel — dit is 'n versamelnaam.", [E.GRAM], 2),
    ]),

  ...skill(`${P}.02`, "Voornaamwoorde",
    "Persoonlike, besitlike, aanwysende en betreklike voornaamwoorde.",
    "Taalstrukture", "T3", ["choice", "cloze"],
    "Kies die voornaamwoord volgens sy werk: wie doen (persoonlik), wie s'n (besitlik), wys aan (aanwysend), of verbind (betreklik).",
    [
      cz("G10TAA02.01", "Vul in: 'Die boek is ___.' (besitlik, behoort aan my)", ["myne", "my", "ek"], "myne", "'myne' is die selfstandige besitlike vorm: 'Die boek is myne.'", [E.PRON], 2),
      cz("G10TAA02.02", "Vul in: 'Dit is ___ pen.' (besitlik voor 'n naamwoord)", ["my", "myne", "ek"], "my", "Voor 'n naamwoord gebruik ons 'my': 'my pen'.", [E.PRON], 2),
      cz("G10TAA02.03", "Vul in: 'Ek sien ___.' (voorwerp van 'hy')", ["hom", "hy", "sy"], "hom", "Die voorwerpvorm van 'hy' is 'hom'.", [E.PRON], 1),
      cz("G10TAA02.04", "Vul in: '___ gee vir hom die boek.' (onderwerp)", ["Ek", "My", "Myne"], "Ek", "Die onderwerp is 'Ek'.", [E.PRON], 1),
      ch("G10TAA02.05", "Kies die korrekte aanwysende voornaamwoord: '___ boek hier is myne.'", ["Hierdie", "Daardie", "Daar"], "Hierdie", "'Hierdie' wys na iets naby; 'daardie' na iets ver.", [E.PRON], 2),
      ch("G10TAA02.06", "Kies die korrekte aanwysende voornaamwoord: '___ huis daar oorkant is groot.'", ["Daardie", "Hierdie", "Hier"], "Daardie", "'Daardie' wys na iets ver weg.", [E.PRON], 2),
      ch("G10TAA02.07", "Kies die korrekte betreklike voornaamwoord: 'Die man ___ daar staan, is my pa.'", ["wat", "wie se", "waarmee"], "wat", "'wat' verbind die bysin met die naamwoord 'man'.", [E.PRON], 2),
      ch("G10TAA02.08", "Kies die korrekte vorm: 'Die vrou ___ kar gesteel is, huil.'", ["wie se", "wat se", "wat"], "wie se", "By besit gebruik ons 'wie se': 'die vrou wie se kar'.", [E.PRON], 3),
      ch("G10TAA02.09", "Kies die korrekte vorm: 'Die mes ___ ek sny, is skerp.'", ["waarmee", "wat", "waarin"], "waarmee", "'waarmee' = met wat; jy sny mét die mes.", [E.PRON], 3),
      cz("G10TAA02.10", "Vul in: 'Hierdie tas is joune, en daardie een is ___.' (behoort aan my)", ["myne", "my", "ek"], "myne", "Aan die einde gebruik ons 'myne': 'daardie een is myne'.", [E.PRON], 2),
      cz("G10TAA02.11", "Vul in: 'Ons nooi ___ na die partytjie.' (voorwerp van 'hulle')", ["hulle", "hul", "h. hulle"], "hulle", "Die voorwerpvorm bly 'hulle': 'Ons nooi hulle.'", [E.PRON], 1),
      cz("G10TAA02.12", "Vul in: 'Sy was die kind ___.' (wederkerend, sy ... haarself?)", ["haarself", "haar", "sy"], "haarself", "Wederkerend verwys terug na die onderwerp: 'Sy was haarself.'", [E.PRON], 3),
      ch("G10TAA02.13", "Watter woord is 'n persoonlike voornaamwoord?", ["jy", "hierdie", "myne"], "jy", "'jy' is 'n persoonlike voornaamwoord.", [E.PRON], 1),
      ch("G10TAA02.14", "Watter woord is 'n besitlike voornaamwoord?", ["sy", "wat", "daardie"], "sy", "'sy' kan besit aandui: 'sy boek'.", [E.PRON], 2),
      ch("G10TAA02.15", "Watter woord is 'n vraende voornaamwoord?", ["wie", "hierdie", "hom"], "wie", "'wie' vra na 'n persoon — dit is vraend.", [E.PRON], 2),
      cz("G10TAA02.16", "Vul in: 'Die seuns help ___.' (wederkerig, vir mekaar)", ["mekaar", "hulself", "hulle"], "mekaar", "'mekaar' wys dat hulle vir mekaar iets doen.", [E.PRON], 2),
      cz("G10TAA02.17", "Vul in: 'Is hierdie fone ___ of ons s'n?' (behoort aan julle)", ["julle s'n", "jou", "joune"], "julle s'n", "Vir 'julle' gebruik ons 'julle s'n'.", [E.PRON], 3),
      cz("G10TAA02.18", "Vul in: '___ reën vandag.' (onpersoonlik)", ["Dit", "Hy", "Daar"], "Dit", "By weer gebruik ons die onpersoonlike 'Dit': 'Dit reën.'", [E.PRON], 2),
      ch("G10TAA02.19", "Kies die korrekte sin:", ["Ek en hy gaan saam.", "My en hom gaan saam.", "Ek en hom gaan saam."], "Ek en hy gaan saam.", "As onderwerp gebruik ons 'ek en hy', nie 'my en hom' nie.", [E.PRON], 3),
      cz("G10TAA02.20", "Vul in: 'Die boek ___ op die tafel lê, is myne.' (betreklik)", ["wat", "wie", "wie se"], "wat", "'wat' verbind die bysin met 'boek'.", [E.PRON], 2),
    ]),

  ...skill(`${P}.03`, "Byvoeglike naamwoorde en trappe van vergelyking",
    "Attributiewe en predikatiewe byvoeglike naamwoorde, verbuiging, en die stellende, vergrotende en oortreffende trap.",
    "Taalstrukture", "T1", ["choice", "cloze", "true-false"],
    "Die vergrotende trap kry meestal -er en die oortreffende -ste; leer die onreëlmatiges (goed-beter-beste, baie-meer-meeste).",
    [
      ch("G10TAA03.01", "Vergrotende trap: 'vinnig → ___ → vinnigste'", ["vinniger", "meer vinnig", "vinnigste"], "vinniger", "Die vergrotende trap van 'vinnig' is 'vinniger'.", [E.COMP], 1),
      ch("G10TAA03.02", "Oortreffende trap: 'groot → groter → ___'", ["grootste", "grooter", "meer groot"], "grootste", "Die oortreffende trap van 'groot' is 'grootste'.", [E.COMP], 1),
      ch("G10TAA03.03", "Vergrotende trap: 'goed → ___ → beste'", ["beter", "gooier", "meer goed"], "beter", "'goed' is onreëlmatig: goed → beter → beste.", [E.COMP], 2),
      ch("G10TAA03.04", "Oortreffende trap: 'baie → meer → ___'", ["meeste", "baiede", "meerste"], "meeste", "'baie' is onreëlmatig: baie → meer → meeste.", [E.COMP], 2),
      ch("G10TAA03.05", "Oortreffende trap: 'min → minder → ___'", ["minste", "minnerste", "mees min"], "minste", "'min' word: min → minder → minste.", [E.COMP], 2),
      ch("G10TAA03.06", "Oortreffende trap: 'naby → nader → ___'", ["naaste", "nabyste", "naderste"], "naaste", "'naby' is onreëlmatig: naby → nader → naaste.", [E.COMP], 3),
      cz("G10TAA03.07", "Vul die vergrotende trap in: 'Hierdie boek is ___ as daardie een.' (groot)", ["groter", "grootste", "meer groot"], "groter", "By 'n vergelyking tussen twee gebruik ons die vergrotende trap 'groter'.", [E.COMP], 1),
      cz("G10TAA03.08", "Vul die oortreffende trap in: 'Dit is die ___ berg in die land.' (hoog)", ["hoogste", "hoër", "meer hoog"], "hoogste", "By die hoogste van almal gebruik ons 'hoogste'.", [E.COMP], 2),
      ch("G10TAA03.09", "Kies die korrekte attributiewe vorm: 'die ___ weer' (sleg)", ["slegte", "sleg", "slegter"], "slegte", "Voor 'n naamwoord verbuig 'sleg' na 'slegte': 'die slegte weer'.", [E.ADJ], 3),
      ch("G10TAA03.10", "Kies die korrekte attributiewe vorm: 'die ___ water' (koud)", ["koue", "koud", "kouer"], "koue", "'koud' verbuig na 'koue': 'die koue water'.", [E.ADJ], 3),
      ch("G10TAA03.11", "Kies die korrekte attributiewe vorm: 'die ___ man' (oud)", ["ou", "oude", "oue"], "ou", "'oud' verbuig na 'ou' voor 'n naamwoord: 'die ou man'.", [E.ADJ], 3),
      tf("G10TAA03.12", "Is 'lank' in 'Die man is lank' predikatief gebruik?", "Waar", "Ja — die byvoeglike naamwoord staan ná die werkwoord, dus is dit predikatief.", [E.ADJ], 2),
      tf("G10TAA03.13", "Is 'lang' in 'die lang man' attributief gebruik?", "Waar", "Ja — dit staan voor die naamwoord, dus attributief.", [E.ADJ], 2),
      cz("G10TAA03.14", "Vul in: 'Jan is ___ as Piet, maar Sipho is die ___.' (lank)", ["langer ... langste", "langste ... langer", "lang ... langer"], "langer ... langste", "Tussen twee: 'langer'; van almal: 'langste'.", [E.COMP], 3),
      ch("G10TAA03.15", "Vergrotende trap: 'mooi → ___'", ["mooier", "mooiste", "meer mooi"], "mooier", "Die vergrotende trap van 'mooi' is 'mooier'.", [E.COMP], 1),
      ch("G10TAA03.16", "Oortreffende trap: 'duur → duurder → ___'", ["duurste", "durste", "mees duur"], "duurste", "'duur' word: duur → duurder → duurste.", [E.COMP], 2),
      ch("G10TAA03.17", "Watter sin gebruik die byvoeglike naamwoord korrek?", ["Die blink son skyn.", "Die blinke son skyn.", "Die son blink skyn."], "Die blink son skyn.", "'blink' bly onverbuig voor 'son': 'die blink son'.", [E.ADJ], 2),
      cz("G10TAA03.18", "Vul in: 'Vandag is dit ___ as gister.' (warm, vergrotend)", ["warmer", "warmste", "meer warm"], "warmer", "Tussen twee dae: 'warmer'.", [E.COMP], 1),
      ch("G10TAA03.19", "Oortreffende trap: 'sleg → slegter → ___'", ["slegste", "slegter", "mees sleg"], "slegste", "'sleg' word: sleg → slegter → slegste.", [E.COMP], 2),
      tf("G10TAA03.20", "Is 'beterste' die korrekte oortreffende trap van 'goed'?", "Onwaar", "Nee — die korrekte vorm is 'beste', nie 'beterste' nie.", [E.COMP], 2),
    ]),

  ...skill(`${P}.04`, "Werkwoorde en tye: teenwoordige, verlede en toekomende tyd",
    "Vorming van die teenwoordige, verlede (het ge-) en toekomende (sal) tyd, ook met skeibare werkwoorde.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Verlede tyd = het + ge-werkwoord; toekomende = sal + werkwoord. Laat die tydwoord (gister/môre) jou help.",
    [
      cz("G10TAA04.01", "Vul die verlede tyd in: 'Ek het gister ___.' (speel)", ["gespeel", "speel", "gespeelt"], "gespeel", "Verlede tyd: 'het' + 'ge' + werkwoord = 'het gespeel'.", [E.TENSE], 1),
      ch("G10TAA04.02", "Watter sin is korrek in die verlede tyd?", ["Gister het ek gewerk.", "Gister ek het gewerk.", "Gister ek gewerk het."], "Gister het ek gewerk.", "Ná 'Gister' kom die hulpwerkwoord 'het', dan die onderwerp: 'Gister het ek gewerk.'", [E.ORDER], 2),
      cz("G10TAA04.03", "Vul die toekomende tyd in: 'Ek ___ môre fliek toe gaan.' (hulpwerkwoord)", ["sal", "het", "was"], "sal", "Toekomende tyd gebruik 'sal': 'Ek sal môre gaan.'", [E.TENSE], 1),
      cz("G10TAA04.04", "Vul die teenwoordige tyd in: 'Sy ___ elke dag koffie.' (drink)", ["drink", "het gedrink", "sal drink"], "drink", "Teenwoordige tyd is bloot 'drink'.", [E.TENSE], 1),
      ch("G10TAA04.05", "Verlede tyd van 'Ek staan op':", ["Ek het opgestaan.", "Ek het op gestaan.", "Ek het geopstaan."], "Ek het opgestaan.", "By skeibare werkwoorde kom 'ge' tussenin: 'opgestaan'.", [E.TENSE], 3),
      ch("G10TAA04.06", "Verlede tyd van 'Hy maak die deur toe':", ["Hy het die deur toegemaak.", "Hy het die deur toe gemaak.", "Hy het die deur getoemaak."], "Hy het die deur toegemaak.", "'toemaak' is skeibaar: 'toegemaak'.", [E.TENSE], 3),
      cz("G10TAA04.07", "Vul in: 'Verlede week ___ ons see toe.' (gaan, verlede)", ["het ... gegaan", "gaan", "sal ... gaan"], "het ... gegaan", "Verlede tyd: 'het ons see toe gegaan'.", [E.TENSE], 2),
      tf("G10TAA04.08", "Is 'Ek het geëet' die korrekte verlede tyd van 'Ek eet'?", "Waar", "Ja — 'eet' word 'het geëet' in die verlede tyd.", [E.TENSE], 1),
      tf("G10TAA04.09", "Is 'Gister speel ek' korrek?", "Onwaar", "Nee — by 'gister' moet die verlede tyd: 'Gister het ek gespeel.'", [E.TENSE], 2),
      ch("G10TAA04.10", "Watter werkwoord kry NIE 'ge' in die verlede tyd nie?", ["verstaan", "speel", "werk"], "verstaan", "Werkwoorde met voorvoegsels soos ver-, be-, ont- kry nie 'ge' nie: 'het verstaan'.", [E.TENSE], 3),
      cz("G10TAA04.11", "Vul in: 'Ek ___ die storie reeds gelees.' (hulpwerkwoord verlede)", ["het", "sal", "word"], "het", "Verlede tyd gebruik 'het': 'Ek het gelees.'", [E.TENSE], 1),
      cz("G10TAA04.12", "Vul die toekomende tyd in: 'Hulle ___ volgende jaar trou.' ", ["sal", "het", "is"], "sal", "Toekomende tyd: 'Hulle sal trou.'", [E.TENSE], 1),
      ch("G10TAA04.13", "Teenwoordige tyd van 'Ek het gewerk':", ["Ek werk.", "Ek sal werk.", "Ek het werk."], "Ek werk.", "Die teenwoordige tyd is 'Ek werk.'", [E.TENSE], 2),
      ch("G10TAA04.14", "Verlede tyd van 'Sy bel haar ma':", ["Sy het haar ma gebel.", "Sy het haar ma bel.", "Sy het haar ma gebelt."], "Sy het haar ma gebel.", "'bel' word 'het gebel'.", [E.TENSE], 2),
      cz("G10TAA04.15", "Vul in: 'Môre ___ ek my huiswerk doen.' (toekomende)", ["sal", "het", "was"], "sal", "By 'môre' pas die toekomende tyd: 'sal ... doen'.", [E.TENSE], 1),
      ch("G10TAA04.16", "Watter sin is korrek?", ["Ek het my werk klaargemaak.", "Ek het my werk klaar gemaak.", "Ek het my werk geklaarmaak."], "Ek het my werk klaargemaak.", "'klaarmaak' is skeibaar: 'klaargemaak'.", [E.TENSE], 3),
      cz("G10TAA04.17", "Vul in: 'Sy ___ nou in die kombuis.' (staan, teenwoordig)", ["staan", "het gestaan", "sal staan"], "staan", "Teenwoordige tyd: 'Sy staan nou'.", [E.TENSE], 1),
      tf("G10TAA04.18", "Is 'Hy het die boek gekoopt' korrek?", "Onwaar", "Nee — die korrekte verlede tyd is 'gekoop', nie 'gekoopt' nie.", [E.TENSE], 2),
      cz("G10TAA04.19", "Vul in: 'Verlede jaar ___ ek baie ___.' (leer, verlede)", ["het ... geleer", "leer", "sal ... leer"], "het ... geleer", "Verlede tyd: 'het ek baie geleer'.", [E.TENSE], 2),
      ch("G10TAA04.20", "Verlede tyd van 'Ons ontmoet hulle':", ["Ons het hulle ontmoet.", "Ons het hulle geontmoet.", "Ons het hulle ontmoetet."], "Ons het hulle ontmoet.", "'ontmoet' kry nie 'ge' nie en bly 'ontmoet'.", [E.TENSE], 3),
    ]),

  ...skill(`${P}.05`, "Voegwoorde: groep 1, 2 en 3 en woordorde",
    "Verbind sinne met groep 1 (en, maar, want), groep 2 (dus, daarom) en groep 3 (omdat, terwyl, dat) — en die woordorde wat elkeen vereis.",
    "Taalstrukture", "T2", ["choice", "cloze"],
    "Groep 1 hou normale woordorde; groep 2 ruil onderwerp en werkwoord (dus kom hy); groep 3 stoot die werkwoord na die einde (...omdat hy kom).",
    [
      ch("G10TAA05.01", "Kies die sin met die korrekte woordorde:", ["Ek bly tuis omdat dit reën.", "Ek bly tuis omdat reën dit.", "Ek bly tuis omdat dit reën nie."], "Ek bly tuis omdat dit reën.", "Ná 'omdat' (groep 3) gaan die werkwoord na die einde: 'omdat dit reën'.", [E.ORDER], 2),
      ch("G10TAA05.02", "Kies die sin met die korrekte woordorde:", ["Dit reën, daarom bly ek tuis.", "Dit reën, daarom ek bly tuis.", "Dit reën, daarom tuis ek bly."], "Dit reën, daarom bly ek tuis.", "Ná 'daarom' (groep 2) ruil onderwerp en werkwoord: 'daarom bly ek'.", [E.ORDER], 3),
      ch("G10TAA05.03", "Kies die korrekte voegwoord: 'Ek is moeg ___ ek het hard gewerk.'", ["want", "omdat", "daarom"], "want", "'want' (groep 1) gee 'n rede sonder dat die woordorde verander.", [E.CONJ], 2),
      cz("G10TAA05.04", "Vul in: 'Sy hardloop vinnig ___ sy is laat.' (rede, groep 1)", ["want", "omdat", "dus"], "want", "'want' verbind die rede met normale woordorde.", [E.CONJ], 1),
      ch("G10TAA05.05", "Kies die korrekte sin (groep 3):", ["Ek weet dat hy kom.", "Ek weet dat kom hy.", "Ek weet dat hy kom nie."], "Ek weet dat hy kom.", "Ná 'dat' kom die werkwoord aan die einde: 'dat hy kom'.", [E.ORDER], 2),
      ch("G10TAA05.06", "Watter voegwoord behoort tot groep 1 (woordorde verander nie)?", ["en", "daarom", "omdat"], "en", "'en' is groep 1 — die woordorde bly dieselfde.", [E.CONJ], 1),
      ch("G10TAA05.07", "Watter voegwoord behoort tot groep 3 (werkwoord na die einde)?", ["terwyl", "en", "dus"], "terwyl", "'terwyl' is groep 3 en stoot die werkwoord na die einde.", [E.CONJ], 2),
      ch("G10TAA05.08", "Kies die korrekte sin:", ["Hy speel terwyl sy leer.", "Hy speel terwyl leer sy.", "Hy speel terwyl sy leer nie."], "Hy speel terwyl sy leer.", "Ná 'terwyl' kom die werkwoord aan die einde: 'terwyl sy leer'.", [E.ORDER], 2),
      cz("G10TAA05.09", "Vul in: 'Dit is koud, ___ trek ek 'n trui aan.' (gevolg, groep 2)", ["daarom", "want", "omdat"], "daarom", "'daarom' dui die gevolg aan en laat die woordorde omruil.", [E.CONJ], 3),
      ch("G10TAA05.10", "Kies die korrekte sin met 'maar':", ["Ek wou kom, maar ek was siek.", "Ek wou kom, maar was ek siek.", "Ek wou kom, maar ek siek was."], "Ek wou kom, maar ek was siek.", "'maar' (groep 1) hou die normale woordorde.", [E.ORDER], 2),
      cz("G10TAA05.11", "Vul in: 'Hy bly tuis ___ hy siek is.' (rede, groep 3)", ["omdat", "want", "dus"], "omdat", "'omdat' is groep 3: 'omdat hy siek is' (werkwoord aan die einde).", [E.CONJ], 2),
      ch("G10TAA05.12", "Watter voegwoord behoort tot groep 2?", ["dus", "en", "omdat"], "dus", "'dus' is groep 2 en laat onderwerp en werkwoord omruil.", [E.CONJ], 2),
      ch("G10TAA05.13", "Kies die korrekte sin (groep 3, 'indien'):", ["Indien dit reën, bly ons tuis.", "Indien reën dit, bly ons tuis.", "Indien dit reën nie, bly ons tuis."], "Indien dit reën, bly ons tuis.", "Ná 'indien' gaan die werkwoord na die einde van die bysin: 'indien dit reën'.", [E.ORDER], 3),
      cz("G10TAA05.14", "Vul in: 'Ek hou van tee ___ koffie.' (keuse, groep 1)", ["of", "omdat", "daarom"], "of", "'of' bied 'n keuse en is groep 1.", [E.CONJ], 1),
      ch("G10TAA05.15", "Kies die korrekte voegwoord: 'Hy was honger, ___ hy het 'n toebroodjie gemaak.'", ["en", "omdat", "terwyl"], "en", "'en' verbind die twee dele met normale woordorde.", [E.CONJ], 1),
      ch("G10TAA05.16", "Kies die korrekte sin:", ["Ek wag totdat jy klaar is.", "Ek wag totdat is jy klaar.", "Ek wag totdat jy klaar is nie."], "Ek wag totdat jy klaar is.", "'totdat' is groep 3: die werkwoord ('is') gaan na die einde.", [E.ORDER], 2),
      cz("G10TAA05.17", "Vul in: 'Sy lag ___ sy huil.' (teenstelling, groep 1)", ["maar", "omdat", "daarom"], "maar", "'maar' wys 'n teenstelling en is groep 1.", [E.CONJ], 1),
      ch("G10TAA05.18", "Kies die sin met die korrekte woordorde (groep 2, 'toe'):", ["Dit het gereën, toe het ons binne gespeel.", "Dit het gereën, toe ons het binne gespeel.", "Dit het gereën, toe ons binne gespeel het."], "Dit het gereën, toe het ons binne gespeel.", "Ná 'toe' ruil die woordorde om: 'toe het ons'.", [E.ORDER], 3),
      cz("G10TAA05.19", "Vul in: 'Ek sal jou help ___ jy my vra.' (voorwaarde, groep 3)", ["as", "want", "dus"], "as", "'as' is groep 3: 'as jy my vra' (werkwoord aan die einde).", [E.CONJ], 2),
      ch("G10TAA05.20", "Watter sin is heeltemal korrek?", ["Hy eet baie, want hy is honger.", "Hy eet baie, want hy honger is.", "Hy eet baie, want is hy honger."], "Hy eet baie, want hy is honger.", "'want' hou normale woordorde: 'want hy is honger'.", [E.ORDER], 2),
    ]),

  ...skill(`${P}.06`, "Sinsoorte, sinsbou en ontkenning",
    "Stel-, vraag-, bevel- en uitroepsinne; die bou van eenvoudige sinne; en die dubbele ontkenning (nie ... nie; geen ... nie).",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "Afrikaans benodig gewoonlik 'n sluitende 'nie' aan die einde van 'n ontkennende sin; pas die leesteken by die sinsoort (. ? !).",
    [
      ch("G10TAA06.01", "Watter soort sin is 'Maak die deur toe!'?", ["bevelsin", "vraagsin", "stelsin"], "bevelsin", "'Maak die deur toe!' gee 'n bevel — dit is 'n bevelsin.", [E.SENT], 1),
      ch("G10TAA06.02", "Watter soort sin is 'Hoe oud is jy?'?", ["vraagsin", "stelsin", "bevelsin"], "vraagsin", "Dit vra iets en eindig met 'n vraagteken — 'n vraagsin.", [E.SENT], 1),
      ch("G10TAA06.03", "Watter soort sin is 'Wat 'n pragtige dag!'?", ["uitroepsin", "vraagsin", "stelsin"], "uitroepsin", "Dit roep 'n gevoel uit en eindig met 'n uitroepteken.", [E.SENT], 2),
      ch("G10TAA06.04", "Watter soort sin is 'Die kinders speel in die tuin.'?", ["stelsin", "vraagsin", "bevelsin"], "stelsin", "Dit stel 'n feit — 'n stelsin.", [E.SENT], 1),
      ch("G10TAA06.05", "Kies die korrekte ontkenning van 'Ek het geld.'", ["Ek het nie geld nie.", "Ek het nie geld.", "Ek het geld nie."], "Ek het nie geld nie.", "Die dubbele ontkenning benodig 'nie ... nie': 'Ek het nie geld nie.'", [E.NEG], 1),
      ch("G10TAA06.06", "Maak ontkennend: 'Sy ken iemand hier.'", ["Sy ken niemand hier nie.", "Sy ken nie iemand hier.", "Sy ken iemand hier nie."], "Sy ken niemand hier nie.", "'iemand' word 'niemand', met 'n sluitende 'nie': 'Sy ken niemand hier nie.'", [E.NEG], 2),
      ch("G10TAA06.07", "Maak ontkennend: 'Hy het al die kos geëet.'", ["Hy het nie al die kos geëet nie.", "Hy het nie al die kos geëet.", "Hy het al die kos nie geëet."], "Hy het nie al die kos geëet nie.", "Onthou die sluitende 'nie' aan die einde.", [E.NEG], 2),
      ch("G10TAA06.08", "Kies die korrekte bevel-ontkenning:", ["Moenie hier rook nie.", "Moet nie hier rook.", "Moenie hier rook."], "Moenie hier rook nie.", "'n Ontkennende bevel: 'Moenie ... nie': 'Moenie hier rook nie.'", [E.NEG], 2),
      ch("G10TAA06.09", "Maak ontkennend: 'Daar is iets in die boks.'", ["Daar is niks in die boks nie.", "Daar is nie iets in die boks.", "Daar is iets in die boks nie."], "Daar is niks in die boks nie.", "'iets' word 'niks', met sluitende 'nie'.", [E.NEG], 2),
      ch("G10TAA06.10", "Maak ontkennend: 'Sy gaan ooit weer terug.'", ["Sy gaan nooit weer terug nie.", "Sy gaan nie ooit weer terug.", "Sy gaan ooit weer terug nie."], "Sy gaan nooit weer terug nie.", "'ooit' word 'nooit', met sluitende 'nie'.", [E.NEG], 3),
      tf("G10TAA06.11", "Is 'Ek het nie my huiswerk gedoen' 'n volledige ontkenning?", "Onwaar", "Nee — dit kort die sluitende 'nie': 'Ek het nie my huiswerk gedoen nie.'", [E.NEG], 2),
      cz("G10TAA06.12", "Vul die sluitende 'nie' in: 'Ons gaan nie vandag swem ___.'", ["nie", "nie nie", "geen"], "nie", "Die sin eindig met die tweede 'nie': '...nie vandag swem nie.'", [E.NEG], 1),
      ch("G10TAA06.13", "Watter sin is 'n enkelvoudige sin?", ["Die hond blaf.", "Die hond blaf en die kat slaap.", "Die hond blaf omdat hy honger is."], "Die hond blaf.", "'n Enkelvoudige sin het een werkwoord en een gedagte: 'Die hond blaf.'", [E.SENT], 2),
      ch("G10TAA06.14", "Watter deel van 'Die seun skop die bal' is die voorwerp?", ["die bal", "die seun", "skop"], "die bal", "Die voorwerp ontvang die handeling: 'die bal'.", [E.GRAM], 2),
      ch("G10TAA06.15", "Watter deel van 'Die seun skop die bal' is die onderwerp?", ["die seun", "die bal", "skop"], "die seun", "Die onderwerp doen die handeling: 'die seun'.", [E.GRAM], 2),
      cz("G10TAA06.16", "Vul in: 'Maak ontkennend: \"Almal het gekom.\" → ___ het gekom nie.'", ["Niemand", "Nie almal", "Geen almal"], "Niemand", "'Almal' word 'Niemand': 'Niemand het gekom nie.'", [E.NEG], 3),
      ch("G10TAA06.17", "Kies die korrekte ontkenning: 'Ek het geld om te koop.'", ["Ek het geen geld om te koop nie.", "Ek het geen geld om te koop.", "Ek het nie geen geld nie."], "Ek het geen geld om te koop nie.", "'geen ... nie' werk soos 'nie ... nie': 'geen geld ... nie'.", [E.NEG], 3),
      ch("G10TAA06.18", "Watter leesteken hoort by 'n vraagsin?", ["vraagteken (?)", "punt (.)", "uitroepteken (!)"], "vraagteken (?)", "'n Vraagsin eindig met 'n vraagteken.", [E.SENT], 1),
      tf("G10TAA06.19", "Eindig 'n bevelsin altyd met 'n vraagteken?", "Onwaar", "Nee — 'n bevelsin eindig met 'n punt of 'n uitroepteken, nie 'n vraagteken nie.", [E.SENT], 2),
      ch("G10TAA06.20", "Maak ontkennend: 'Jy mag hier parkeer.'", ["Jy mag nie hier parkeer nie.", "Jy mag nie hier parkeer.", "Jy mag hier parkeer nie."], "Jy mag nie hier parkeer nie.", "Plaas 'nie' ná 'mag' en 'n sluitende 'nie' aan die einde.", [E.NEG], 2),
    ]),
};

insertSkills(skills);
