// Grade 10 — Skryf en aanbied (writing knowledge) tier, SKR.01–SKR.06 (20 items each).
// Afrikaans-only. Tappable writing knowledge (production deferred).
import { ch, tf, cz, sq, skill, insertSkills } from "./_g10_bank_lib.mjs";

const P = "AF.G10.SKR";
const E = {
  TEXTTYPE: "ERR_AF_TEXTTYPE", PARA: "ERR_AF_PARAGRAPH", REG: "ERR_AF_REGISTER",
  EDIT: "ERR_AF_EDIT", SUM: "ERR_AF_SUMMARY", GRAM: "ERR_AF_GRAMMAR",
};
const cx = (text) => ({ context: text });

const skills = {
  ...skill(`${P}.01`, "Briewe: vriendskaplik teenoor formeel",
    "Herken die korrekte struktuur en konvensies van vriendskaplike teenoor formele briewe (adres, datum, aanhef, slot).",
    "Skryf en aanbied", "T1", ["choice", "true-false"],
    "'n Formele brief het twee adresse + 'n formele aanhef/slot; 'n vriendskaplike brief het een adres en 'n warm groet.",
    [
      ch("G10SKR01.01", "Watter aanhef pas by 'n formele brief?", ["Geagte Mevrou", "Liewe Ouma", "Hallo maat"], "Geagte Mevrou", "'Geagte Mevrou' is die korrekte formele aanhef.", [E.TEXTTYPE], 1),
      ch("G10SKR01.02", "Watter aanhef pas by 'n vriendskaplike brief?", ["Liewe Thandi", "Geagte Meneer", "Aan wie dit mag aangaan"], "Liewe Thandi", "'Liewe Thandi' is 'n warm, vriendskaplike aanhef.", [E.TEXTTYPE], 1),
      ch("G10SKR01.03", "Watter slot pas by 'n formele brief?", ["Die uwe", "Liefde", "Groetnis, jou maat"], "Die uwe", "'Die uwe' is 'n formele afsluiting.", [E.TEXTTYPE], 2),
      ch("G10SKR01.04", "Watter slot pas by 'n vriendskaplike brief?", ["Baie liefde, Sara", "Die uwe", "Hoogagtend"], "Baie liefde, Sara", "'Baie liefde' pas by 'n vriendskaplike brief.", [E.TEXTTYPE], 1),
      ch("G10SKR01.05", "Hoeveel adresse het 'n formele brief gewoonlik?", ["Twee (sender en ontvanger)", "Een", "Geen"], "Twee (sender en ontvanger)", "'n Formele brief het die skrywer se adres én die ontvanger se adres.", [E.TEXTTYPE], 2),
      ch("G10SKR01.06", "Hoeveel adresse het 'n vriendskaplike brief gewoonlik?", ["Een (die skrywer s'n)", "Twee", "Drie"], "Een (die skrywer s'n)", "'n Vriendskaplike brief het net die skrywer se adres.", [E.TEXTTYPE], 2),
      ch("G10SKR01.07", "Watter element kom heel bo in 'n brief?", ["Die skrywer se adres en datum", "Die slot", "Die handtekening"], "Die skrywer se adres en datum", "Die adres en datum staan heel bo in die brief.", [E.TEXTTYPE], 1),
      tf("G10SKR01.08", "''n Formele brief mag slengtaal en afkortings soos 'LOL' bevat.", "Onwaar", "Nee — 'n formele brief gebruik korrekte, formele taal sonder sleng.", [E.REG], 1),
      ch("G10SKR01.09", "Watter brief skryf jy aan 'n koerantredakteur?", ["'n Formele brief", "'n Vriendskaplike brief", "'n Dagboek"], "'n Formele brief", "'n Brief aan 'n redakteur is formeel.", [E.TEXTTYPE], 2),
      ch("G10SKR01.10", "Watter brief skryf jy aan 'n goeie vriend?", ["'n Vriendskaplike brief", "'n Formele brief", "'n Verslag"], "'n Vriendskaplike brief", "'n Brief aan 'n vriend is vriendskaplik.", [E.TEXTTYPE], 1),
      ch("G10SKR01.11", "Wat is fout met hierdie formele brief?", ["Die aanhef 'Hallo maat' is te informeel", "Die adres is bo", "Die datum is reg"], "Die aanhef 'Hallo maat' is te informeel", "'Hallo maat' pas nie by 'n formele brief nie; gebruik 'Geagte ...'.", [E.REG], 2, cx("Brief aan die skoolhoof: '12 Kerkstraat ... Geagte adres ... Hallo maat, Ek skryf oor die sportgeld ...'")),
      ch("G10SKR01.12", "Watter volgorde is korrek in 'n formele brief?", ["Adres → datum → aanhef → inhoud → slot", "Aanhef → adres → slot → inhoud", "Inhoud → adres → datum"], "Adres → datum → aanhef → inhoud → slot", "Die korrekte volgorde begin met adres en datum en eindig met die slot.", [E.TEXTTYPE], 2),
      tf("G10SKR01.13", "In 'n formele brief skryf jy die ontvanger se adres ook neer.", "Waar", "Ja — 'n formele brief sluit die ontvanger se adres in.", [E.TEXTTYPE], 2),
      ch("G10SKR01.14", "Watter aanhef gebruik jy as jy nie die ontvanger se naam ken nie (formeel)?", ["Geagte Heer/Mevrou", "Liewe vriend", "Haai"], "Geagte Heer/Mevrou", "Sonder 'n naam gebruik jy 'Geagte Heer/Mevrou'.", [E.TEXTTYPE], 2),
      ch("G10SKR01.15", "Watter slot pas by 'Geagte Mevrou' (naam onbekend / formeel)?", ["Die uwe", "Liefde", "Sien jou later"], "Die uwe", "By 'n formele aanhef sonder naam pas die slot 'Die uwe'.", [E.TEXTTYPE], 3),
      ch("G10SKR01.16", "Wat is die doel van 'n klagtebrief?", ["Om 'n probleem te rapporteer en regstelling te vra", "Om 'n storie te vertel", "Om 'n vriend te groet"], "Om 'n probleem te rapporteer en regstelling te vra", "'n Klagtebrief rapporteer 'n probleem en vra dat dit reggestel word.", [E.TEXTTYPE], 2),
      tf("G10SKR01.17", "Die toon van 'n vriendskaplike brief is warm en gemaklik.", "Waar", "Ja — 'n vriendskaplike brief het 'n warm, gemaklike toon.", [E.REG], 1),
      ch("G10SKR01.18", "Watter een hoort NIE in 'n formele brief nie?", ["Smileys en emojis", "'n Onderwerpreël", "'n Formele slot"], "Smileys en emojis", "Emojis pas nie in 'n formele brief nie.", [E.REG], 1),
      ch("G10SKR01.19", "Waar plaas jy jou handtekening/naam in 'n brief?", ["Heel onder, ná die slot", "Heel bo", "In die middel"], "Heel onder, ná die slot", "Jou naam/handtekening kom heel onder ná die slot.", [E.TEXTTYPE], 1),
      ch("G10SKR01.20", "Watter brief is die mees gepas om vir werk aansoek te doen?", ["'n Formele aansoekbrief", "'n Vriendskaplike brief", "'n Dagboekinskrywing"], "'n Formele aansoekbrief", "'n Werkaansoek vereis 'n formele brief.", [E.TEXTTYPE], 2),
    ]),

  ...skill(`${P}.02`, "Transaksionele tekssoorte herken",
    "Pas doel en kenmerke by die regte transaksionele teks: e-pos, uitnodiging, advertensie, dagboek, koerantberig, agenda/notule, CV.",
    "Skryf en aanbied", "T2-T3", ["choice"],
    "Pas die DOEL (inlig, nooi, oorreed, aanteken) by die tekssoort en gaan dan sy kenmerkende elemente na.",
    [
      ch("G10SKR02.01", "Watter tekssoort gebruik jy om iemand na 'n partytjie te vra?", ["'n Uitnodiging", "'n Koerantberig", "'n CV"], "'n Uitnodiging", "'n Uitnodiging nooi iemand na 'n geleentheid.", [E.TEXTTYPE], 1),
      ch("G10SKR02.02", "Watter tekssoort gebruik jy om 'n produk te verkoop?", ["'n Advertensie", "'n Dagboek", "'n Notule"], "'n Advertensie", "'n Advertensie oorreed mense om iets te koop.", [E.TEXTTYPE], 1),
      ch("G10SKR02.03", "Watter tekssoort hou 'n rekord van wat by 'n vergadering gesê is?", ["'n Notule", "'n Uitnodiging", "'n Advertensie"], "'n Notule", "'n Notule teken aan wat by 'n vergadering bespreek en besluit is.", [E.TEXTTYPE], 2),
      ch("G10SKR02.04", "Watter tekssoort lys die punte wat by 'n vergadering bespreek sal word?", ["'n Agenda", "'n Notule", "'n Dagboek"], "'n Agenda", "'n Agenda lys die sake vooraf wat bespreek gaan word.", [E.TEXTTYPE], 2),
      ch("G10SKR02.05", "Watter tekssoort vertel oor jou persoonlike, private gedagtes per dag?", ["'n Dagboekinskrywing", "'n Koerantberig", "'n CV"], "'n Dagboekinskrywing", "'n Dagboek hou jou persoonlike daaglikse gedagtes.", [E.TEXTTYPE], 1),
      ch("G10SKR02.06", "Watter tekssoort lig die publiek in oor 'n gebeurtenis wat plaasgevind het?", ["'n Koerantberig", "'n Uitnodiging", "'n Dagboek"], "'n Koerantberig", "'n Koerantberig rapporteer nuus aan die publiek.", [E.TEXTTYPE], 2),
      ch("G10SKR02.07", "Watter tekssoort lys jou opleiding en werkervaring vir 'n werkaansoek?", ["'n CV", "'n Dagboek", "'n Advertensie"], "'n CV", "'n CV (curriculum vitae) lys jou kwalifikasies en ervaring.", [E.TEXTTYPE], 2),
      ch("G10SKR02.08", "Watter element hoort by 'n koerantberig?", ["'n Opskrif en 'n byskrif", "'Liewe dagboek'", "'RSVP'"], "'n Opskrif en 'n byskrif", "'n Koerantberig het 'n opskrif en dikwels 'n foto met 'n byskrif.", [E.TEXTTYPE], 2),
      ch("G10SKR02.09", "Watter element hoort by 'n uitnodiging?", ["Datum, tyd, plek en RSVP", "'n Opskrif soos in 'n berig", "Werkervaring"], "Datum, tyd, plek en RSVP", "'n Uitnodiging gee datum, tyd, plek en vra om 'n antwoord (RSVP).", [E.TEXTTYPE], 2),
      ch("G10SKR02.10", "Watter tekssoort begin dikwels met 'Liewe dagboek'?", ["'n Dagboekinskrywing", "'n Formele brief", "'n Notule"], "'n Dagboekinskrywing", "'Liewe dagboek' is 'n tipiese dagboek-aanhef.", [E.TEXTTYPE], 1),
      ch("G10SKR02.11", "Watter tekssoort is die beste om vinnig met 'n kollega oor werk te kommunikeer?", ["'n E-pos", "'n Dagboek", "'n Advertensie"], "'n E-pos", "'n E-pos is gepas vir vinnige werkkommunikasie.", [E.TEXTTYPE], 1),
      ch("G10SKR02.12", "Watter element is uniek aan 'n e-pos?", ["'n Onderwerpreël en 'n ontvanger se e-posadres", "'n RSVP", "'n Foto-byskrif"], "'n Onderwerpreël en 'n ontvanger se e-posadres", "'n E-pos het 'n 'Aan'-adres en 'n onderwerpreël.", [E.TEXTTYPE], 2),
      ch("G10SKR02.13", "Jy wil mense oorreed om 'n konsert by te woon. Watter tekssoort?", ["'n Plakkaat / advertensie", "'n Notule", "'n CV"], "'n Plakkaat / advertensie", "'n Plakkaat/advertensie oorreed mense om die konsert by te woon.", [E.TEXTTYPE], 1),
      ch("G10SKR02.14", "Watter tekssoort gebruik die voorsitter om 'n vergadering te beplan?", ["'n Agenda", "'n Dagboek", "'n Koerantberig"], "'n Agenda", "Die voorsitter stel 'n agenda op om die vergadering te beplan.", [E.TEXTTYPE], 2),
      ch("G10SKR02.15", "Watter tekssoort is die mees PRIVAAT?", ["'n Dagboekinskrywing", "'n Advertensie", "'n Koerantberig"], "'n Dagboekinskrywing", "'n Dagboek is privaat; die ander is vir die publiek.", [E.TEXTTYPE], 2),
      ch("G10SKR02.16", "Watter tekssoort is die mees PUBLIEK?", ["'n Koerantberig", "'n Dagboek", "'n Persoonlike e-pos"], "'n Koerantberig", "'n Koerantberig is vir die breë publiek bedoel.", [E.TEXTTYPE], 1),
      ch("G10SKR02.17", "Watter element pas NIE by 'n CV nie?", ["'Liewe dagboek'", "Kontakbesonderhede", "Werkervaring"], "'Liewe dagboek'", "''Liewe dagboek' hoort by 'n dagboek, nie 'n CV nie.", [E.TEXTTYPE], 2),
      ch("G10SKR02.18", "Watter tekssoort het 'n opskrif, intro en die wie-wat-waar-wanneer feite?", ["'n Koerantberig", "'n Uitnodiging", "'n CV"], "'n Koerantberig", "'n Koerantberig gee die wie/wat/waar/wanneer onder 'n opskrif.", [E.TEXTTYPE], 2),
      ch("G10SKR02.19", "Jy wil aanteken wie teenwoordig was en wat besluit is. Watter tekssoort?", ["'n Notule", "'n Agenda", "'n Advertensie"], "'n Notule", "'n Notule teken bywoning en besluite aan.", [E.TEXTTYPE], 2),
      ch("G10SKR02.20", "Watter tekssoort gebruik kort, kragtige taal en 'n leuse om te oorreed?", ["'n Advertensie", "'n Notule", "'n Dagboek"], "'n Advertensie", "'n Advertensie gebruik kort, oorredende taal en 'n leuse.", [E.TEXTTYPE], 2),
    ]),

  ...skill(`${P}.03`, "Paragraafbou: kernsin en ondersteunende besonderhede",
    "Bou 'n samehangende Afrikaanse paragraaf: vind die kernsin (onderwerpsin), orden ondersteunende besonderhede en gebruik prosesskryf-stappe.",
    "Skryf en aanbied", "T1", ["choice", "sequence"],
    "Begin met die kernsin (hoofgedagte), dan die ondersteunende besonderhede, dan 'n slotsin — een gedagte per paragraaf.",
    [
      ch("G10SKR03.01", "Wat is die kernsin (onderwerpsin) van 'n paragraaf?", ["Die sin wat die hoofgedagte stel", "Die laaste sin", "Die langste sin"], "Die sin wat die hoofgedagte stel", "Die kernsin dra die hoofgedagte van die paragraaf.", [E.PARA], 1),
      ch("G10SKR03.02", "Waar staan die kernsin gewoonlik?", ["Aan die begin van die paragraaf", "Heel aan die einde", "In die middel weggesteek"], "Aan die begin van die paragraaf", "Die kernsin staan dikwels heel voor in die paragraaf.", [E.PARA], 1),
      ch("G10SKR03.03", "Watter sin is die kernsin?", ["Oefening is goed vir jou gesondheid.", "Dit laat jou sweet.", "Jy benodig gemaklike skoene."], "Oefening is goed vir jou gesondheid.", "Die eerste sin stel die hoofgedagte; die ander is besonderhede.", [E.PARA], 2, cx("Oefening is goed vir jou gesondheid. Dit versterk jou hart. Dit laat jou sweet. Jy benodig gemaklike skoene.")),
      ch("G10SKR03.04", "Watter sin pas NIE in die paragraaf nie (dit hoort nie by die onderwerp nie)?", ["My kat se naam is Felix.", "Honde is lojale troeteldiere.", "Hulle beskerm die huis."], "My kat se naam is Felix.", "Die paragraaf gaan oor honde; die sin oor die kat hoort nie daar nie.", [E.PARA], 2, cx("Honde is lojale troeteldiere. Hulle beskerm die huis. My kat se naam is Felix. Hulle is altyd bly om jou te sien.")),
      sq("G10SKR03.05", "Orden die sinne tot 'n logiese paragraaf:", ["Daar is baie redes om water te spaar.", "Eerstens is skoon water skaars.", "Tweedens bespaar dit geld.", "Daarom behoort almal water te bewaar."], "Begin met die kernsin, gee dan die redes in volgorde, en sluit af met die gevolgtrekking.", [E.PARA], 2, cx("Sinne: Tweedens bespaar dit geld. / Daarom behoort almal water te bewaar. / Daar is baie redes om water te spaar. / Eerstens is skoon water skaars.")),
      sq("G10SKR03.06", "Orden die prosesskryf-stappe korrek:", ["Beplanning", "Skryf 'n konsep", "Hersiening en redigering", "Proeflees en aanbieding"], "Prosesskryf begin met beplanning, dan 'n konsep, dan hersiening/redigering, en laastens proeflees en aanbieding.", [E.PARA], 1, cx("Stappe: Hersiening en redigering / Beplanning / Proeflees en aanbieding / Skryf 'n konsep.")),
      ch("G10SKR03.07", "Wat is die doel van ondersteunende besonderhede?", ["Om die kernsin te verduidelik of te bewys", "Om die paragraaf langer te maak", "Om die leser te verwar"], "Om die kernsin te verduidelik of te bewys", "Besonderhede ondersteun en verduidelik die hoofgedagte.", [E.PARA], 2),
      ch("G10SKR03.08", "Hoeveel hoofgedagtes behoort een paragraaf te hê?", ["Een", "Drie", "Vyf"], "Een", "Een paragraaf hanteer een hoofgedagte.", [E.PARA], 1),
      ch("G10SKR03.09", "Watter woord help om besonderhede in volgorde te verbind?", ["Eerstens", "Kat", "Blou"], "Eerstens", "Skakelwoorde soos 'eerstens' orden die besonderhede.", [E.PARA], 2),
      ch("G10SKR03.10", "Wat doen 'n slotsin in 'n paragraaf?", ["Dit bind die paragraaf se gedagte af", "Dit begin 'n nuwe onderwerp", "Dit gee die titel"], "Dit bind die paragraaf se gedagte af", "Die slotsin sluit die paragraaf se gedagte af.", [E.PARA], 2),
      ch("G10SKR03.11", "Watter sin is die kernsin?", ["Resikleer help die omgewing.", "Glas kan hersmelt word.", "Papier kan herwin word."], "Resikleer help die omgewing.", "Die eerste sin stel die hoofgedagte; die res is voorbeelde.", [E.PARA], 2, cx("Resikleer help die omgewing. Glas kan hersmelt word. Papier kan herwin word. So word minder rommel weggegooi.")),
      sq("G10SKR03.12", "Orden tot 'n logiese paragraaf:", ["Honde maak wonderlike troeteldiere.", "Hulle is lojaal en beskermend.", "Hulle gee jou geselskap.", "Daarom is 'n hond 'n goeie keuse."], "Begin met die kernsin, gee dan die redes, en sluit af met die gevolgtrekking.", [E.PARA], 2, cx("Sinne: Hulle gee jou geselskap. / Daarom is 'n hond 'n goeie keuse. / Honde maak wonderlike troeteldiere. / Hulle is lojaal en beskermend.")),
      ch("G10SKR03.13", "Wat is die EERSTE stap van prosesskryf?", ["Beplanning", "Proeflees", "Aanbieding"], "Beplanning", "Prosesskryf begin met beplanning.", [E.PARA], 1),
      ch("G10SKR03.14", "Wat is die LAASTE stap van prosesskryf?", ["Proeflees en aanbieding", "Beplanning", "Eerste konsep"], "Proeflees en aanbieding", "Die laaste stap is proeflees en aanbieding.", [E.PARA], 1),
      ch("G10SKR03.15", "Watter sin sou die beste slotsin wees vir 'n paragraaf oor die voordele van lees?", ["Daarom behoort almal gereeld te lees.", "My broer hou van sokker.", "Die boek was blou."], "Daarom behoort almal gereeld te lees.", "Die slotsin moet die paragraaf se gedagte saamvat en afbind.", [E.PARA], 2),
      ch("G10SKR03.16", "Wat beteken dit om 'n konsep te 'hersien'?", ["Om dit te verbeter en te verander", "Om dit weg te gooi", "Om dit te druk"], "Om dit te verbeter en te verander", "Hersiening beteken om die teks te verbeter.", [E.PARA], 2),
      ch("G10SKR03.17", "Watter sin breek die eenheid van 'n paragraaf oor gesonde eet?", ["Ek het 'n nuwe selfoon gekoop.", "Groente bevat vitamiene.", "Vrugte gee energie."], "Ek het 'n nuwe selfoon gekoop.", "Die selfoon-sin hoort nie by die onderwerp 'gesonde eet' nie.", [E.PARA], 2, cx("Gesonde eet hou jou sterk. Groente bevat vitamiene. Ek het 'n nuwe selfoon gekoop. Vrugte gee energie.")),
      ch("G10SKR03.18", "Wat moet jy doen tydens 'proeflees'?", ["Spel- en taalfoute regmaak", "Die hoofgedagte verander", "'n Nuwe onderwerp kies"], "Spel- en taalfoute regmaak", "Proeflees is die soek en regmaak van klein foute.", [E.PARA], 1),
      sq("G10SKR03.19", "Orden tot 'n logiese paragraaf:", ["Ons skool het 'n nuwe biblioteek geopen.", "Dit het duisende boeke.", "Leerders kan daar studeer.", "Almal is baie opgewonde daaroor."], "Begin met die nuus (kernsin), gee dan besonderhede, en sluit af met die reaksie.", [E.PARA], 2, cx("Sinne: Leerders kan daar studeer. / Almal is baie opgewonde daaroor. / Ons skool het 'n nuwe biblioteek geopen. / Dit het duisende boeke.")),
      ch("G10SKR03.20", "Waarom is 'n duidelike kernsin belangrik?", ["Dit wys die leser dadelik waaroor die paragraaf gaan", "Dit maak die paragraaf langer", "Dit versteek die hoofgedagte"], "Dit wys die leser dadelik waaroor die paragraaf gaan", "'n Duidelike kernsin lei die leser na die hoofgedagte.", [E.PARA], 2),
    ]),

  ...skill(`${P}.04`, "Register, styl en toon",
    "Kies die gepaste register, styl en toon (formeel/informeel) vir die gehoor en doel van 'n teks.",
    "Skryf en aanbied", "T2", ["choice", "true-false"],
    "Vra wie dit gaan lees en waarom: 'n baas/koerant verg formele taal; 'n vriend laat informele, warmer woorde toe.",
    [
      ch("G10SKR04.01", "Watter register pas by 'n brief aan die skoolhoof?", ["Formeel", "Informeel", "Sleng"], "Formeel", "'n Brief aan die hoof verg 'n formele register.", [E.REG], 1),
      ch("G10SKR04.02", "Watter register pas by 'n teksboodskap aan jou beste vriend?", ["Informeel", "Formeel", "Amptelik"], "Informeel", "'n Boodskap aan 'n vriend is informeel.", [E.REG], 1),
      ch("G10SKR04.03", "Watter sin is formeel?", ["Ek wil graag aansoek doen vir die pos.", "Haai, gee my die job!", "Yo, ek soek werk."], "Ek wil graag aansoek doen vir die pos.", "Die eerste sin gebruik gepaste, formele taal.", [E.REG], 2),
      ch("G10SKR04.04", "Watter sin is informeel?", ["Kom kuier gerus more, dis lekker!", "Ek versoek u teenwoordigheid.", "Geliewe kennis te neem."], "Kom kuier gerus more, dis lekker!", "Die eerste sin is gemaklik en warm — informeel.", [E.REG], 2),
      tf("G10SKR04.05", "Jy gebruik dieselfde toon vir 'n klagtebrief en 'n brief aan 'n vriend.", "Onwaar", "Nee — die toon verskil: formeel/ernstig vir 'n klag, warm vir 'n vriend.", [E.REG], 1),
      ch("G10SKR04.06", "Watter toon pas by 'n simpatiebrief (iemand se geliefde is oorlede)?", ["Meelewend en sag", "Vrolik en speels", "Kwaad"], "Meelewend en sag", "'n Simpatiebrief het 'n sagte, meelewende toon.", [E.REG], 2),
      ch("G10SKR04.07", "Watter toon pas by 'n klagtebrief oor swak diens?", ["Ferm maar beleefd", "Speels", "Vleiend"], "Ferm maar beleefd", "'n Klagtebrief is ferm dog steeds beleefd.", [E.REG], 2),
      ch("G10SKR04.08", "Watter woordkeuse is te informeel vir 'n formele verslag?", ["'baie cool'", "'baie effektief'", "'baie nuttig'"], "'baie cool'", "''cool' is sleng en pas nie in 'n formele verslag nie.", [E.REG], 2),
      ch("G10SKR04.09", "Vir watter gehoor sou jy die eenvoudigste, vriendelikste taal gebruik?", ["'n Groep jong kinders", "'n Paneel professore", "'n Regter"], "'n Groep jong kinders", "Jong kinders verg eenvoudige, vriendelike taal.", [E.REG], 1),
      ch("G10SKR04.10", "Wat is 'register' in skryfwerk?", ["Die vlak van formaliteit wat by die gehoor pas", "Die lengte van die teks", "Die kleur van die ink"], "Die vlak van formaliteit wat by die gehoor pas", "Register is hoe formeel of informeel jou taal is.", [E.REG], 2),
      ch("G10SKR04.11", "Watter aanhef pas by 'n formele e-pos aan 'n maatskappy?", ["Geagte Meneer/Mevrou", "Haai daar", "Yo"], "Geagte Meneer/Mevrou", "'n Formele e-pos begin met 'Geagte ...'.", [E.REG], 1),
      ch("G10SKR04.12", "Watter sin pas by 'n motiverende toespraak (om aan te moedig)?", ["Saam kan ons enigiets bereik!", "Die vergadering is verdaag.", "Sien asseblief die aangehegte vorm."], "Saam kan ons enigiets bereik!", "'n Motiverende toon is opbeurend en kragtig.", [E.REG], 2),
      tf("G10SKR04.13", "Slengwoorde en afkortings soos 'asb' pas in 'n formele aansoekbrief.", "Onwaar", "Nee — formele briewe vermy sleng en informele afkortings.", [E.REG], 1),
      ch("G10SKR04.14", "Watter sin het 'n beleefde toon?", ["Sal u my asseblief help?", "Help my nou!", "Jy moet my help."], "Sal u my asseblief help?", "'asseblief' en 'u' maak die sin beleefd.", [E.REG], 1),
      ch("G10SKR04.15", "Watter toon pas by 'n advertensie wat opwinding wil skep?", ["Energiek en oorredend", "Hartseer", "Formeel en styf"], "Energiek en oorredend", "Advertensies gebruik 'n energieke, oorredende toon.", [E.REG], 2),
      ch("G10SKR04.16", "Watter woord is meer formeel as 'kry'?", ["ontvang", "vat", "gryp"], "ontvang", "'ontvang' is die meer formele woord vir 'kry'.", [E.REG], 2),
      ch("G10SKR04.17", "Watter woord is meer formeel as 'baie groot'?", ["aansienlik", "yslik", "mega"], "aansienlik", "'aansienlik' is die meer formele keuse.", [E.REG], 3),
      ch("G10SKR04.18", "Watter sin sou jy in 'n vriendskaplike brief gebruik?", ["Ek mis jou baie, kom kuier gou!", "Geliewe my versoek te oorweeg.", "Hiermee bevestig ek ontvangs."], "Ek mis jou baie, kom kuier gou!", "Die warm, persoonlike sin pas by 'n vriend.", [E.REG], 1),
      tf("G10SKR04.19", "Die gehoor en doel bepaal watter register en toon jy kies.", "Waar", "Ja — wie lees en waarom bepaal die register en toon.", [E.REG], 1),
      ch("G10SKR04.20", "Watter toon is ongepas vir 'n simpatiekaartjie?", ["Speels en grappig", "Sag en meelewend", "Eerbiedig"], "Speels en grappig", "'n Speelse, grappige toon pas nie by 'n simpatiekaartjie nie.", [E.REG], 2),
    ]),

  ...skill(`${P}.05`, "Redigeer: vind en verbeter die taalfout",
    "Proeflees 'n Afrikaanse sin en identifiseer of verbeter die taal-, spel- of leestekenfout.",
    "Skryf en aanbied", "T1-T4", ["choice", "cloze", "true-false"],
    "Kontroleer een ding op 'n slag: ooreenstemming, tyd, spelling, dan leestekens. Lees die sin in jou kop hardop.",
    [
      ch("G10SKR05.01", "Watter sin is heeltemal korrek?", ["Ek het gister my huiswerk gedoen.", "Ek het gister my huiswerk doen.", "Ek gister my huiswerk gedoen het."], "Ek het gister my huiswerk gedoen.", "Die verlede tyd en woordorde is korrek: 'het ... gedoen'.", [E.EDIT], 1),
      ch("G10SKR05.02", "Wat is fout: 'Sy het nie geld'?", ["Die tweede 'nie' kort", "Niks is fout nie", "'geld' is verkeerd gespel"], "Die tweede 'nie' kort", "Dit moet wees: 'Sy het nie geld nie.'", [E.EDIT], 1),
      ch("G10SKR05.03", "Kies die korrek gespelde woord:", ["onmiddellik", "onmidellik", "onmiddelik"], "onmiddellik", "Die korrekte spelling is 'onmiddellik'.", [E.EDIT], 3),
      ch("G10SKR05.04", "Wat is fout: 'die boom se blare is groen.'?", ["Die sin moet met 'n hoofletter begin", "Niks is fout nie", "'blare' is verkeerd"], "Die sin moet met 'n hoofletter begin", "'die' moet 'Die' wees — sinne begin met 'n hoofletter.", [E.EDIT], 1),
      ch("G10SKR05.05", "Kies die korrekte sin:", ["Die kinders speel buite.", "Die kinders speelt buite.", "Die kinders speel buitte."], "Die kinders speel buite.", "'speel' en 'buite' is korrek gespel.", [E.EDIT], 1),
      ch("G10SKR05.06", "Watter sin het die korrekte verlede tyd?", ["Ons het die fliek gekyk.", "Ons het die fliek kyk.", "Ons het die fliek gekykt."], "Ons het die fliek gekyk.", "Die korrekte verlede tyd is 'het ... gekyk'.", [E.EDIT], 2),
      ch("G10SKR05.07", "Wat is fout: 'Waar is jy.'?", ["Dit moet met 'n vraagteken eindig", "Niks is fout nie", "'Waar' is verkeerd"], "Dit moet met 'n vraagteken eindig", "Dit is 'n vraag: 'Waar is jy?'", [E.EDIT], 1),
      ch("G10SKR05.08", "Kies die korrek gespelde woord:", ["gewoonlik", "gewoonelik", "gewonlik"], "gewoonlik", "Die korrekte spelling is 'gewoonlik'.", [E.EDIT], 2),
      ch("G10SKR05.09", "Watter sin is korrek?", ["Hy en ek gaan saam.", "Hom en my gaan saam.", "Hy en my gaan saam."], "Hy en ek gaan saam.", "As onderwerp gebruik ons 'hy en ek'.", [E.EDIT], 3),
      ch("G10SKR05.10", "Wat is fout: 'Die hond loop in die tuin en hy speel met die bal en hy blaf en hy hardloop.'?", ["Te veel 'en' — breek dit in korter sinne op", "Niks is fout nie", "'tuin' is verkeerd"], "Te veel 'en' — breek dit in korter sinne op", "Te veel 'en's maak die sin lomp; breek dit op.", [E.EDIT], 2),
      cz("G10SKR05.11", "Verbeter: 'Ek ___ môre skool toe.' (toekomende tyd)", ["sal gaan", "het gegaan", "gegaan"], "sal gaan", "Toekomende tyd: 'Ek sal môre skool toe gaan.'", [E.EDIT], 1),
      cz("G10SKR05.12", "Verbeter: 'Die meisie ___ 'n mooi rok.' (verlede: dra)", ["het ... gedra", "dra", "gedraag"], "het ... gedra", "Verlede tyd: 'het ... gedra'.", [E.EDIT], 2),
      ch("G10SKR05.13", "Kies die korrekte spelling:", ["professioneel", "profesioneel", "professionel"], "professioneel", "Die korrekte spelling is 'professioneel'.", [E.EDIT], 3),
      ch("G10SKR05.14", "Wat is fout: 'Sy het baie boek gelees.'?", ["'boek' moet meervoud wees: 'boeke'", "Niks is fout nie", "'gelees' is verkeerd"], "'boek' moet meervoud wees: 'boeke'", "By 'baie' moet die meervoud staan: 'baie boeke'.", [E.EDIT], 2),
      ch("G10SKR05.15", "Watter sin is korrek?", ["Thabo se boek lê op die tafel.", "Thabo's boek lê op die tafel.", "Thabos boek lê op die tafel."], "Thabo se boek lê op die tafel.", "Afrikaans gebruik 'se' vir besit: 'Thabo se boek'.", [E.EDIT], 2),
      cz("G10SKR05.16", "Verbeter die ontkenning: 'Ek het my boek nie gebring ___.'", ["nie", "geen", "nooit"], "nie", "Die sin eindig met die sluitende 'nie': 'Ek het my boek nie gebring nie.'", [E.EDIT], 1),
      ch("G10SKR05.17", "Wat is fout: 'gister het ek na die winkel gegaan'?", ["Begin met 'n hoofletter en eindig met 'n punt", "Niks is fout nie", "'winkel' is verkeerd"], "Begin met 'n hoofletter en eindig met 'n punt", "Dit moet wees: 'Gister het ek na die winkel gegaan.'", [E.EDIT], 1),
      ch("G10SKR05.18", "Kies die korrekte sin:", ["Hulle is gelukkig.", "Hulle is gelukig.", "Hule is gelukkig."], "Hulle is gelukkig.", "'Hulle' en 'gelukkig' is korrek gespel.", [E.EDIT], 1),
      ch("G10SKR05.19", "Wat is fout: 'Die twee seuns speel sokker, en hy wen.'?", ["'hy' moet 'hulle' wees", "Niks is fout nie", "'sokker' is verkeerd"], "'hy' moet 'hulle' wees", "Daar is twee seuns, dus 'hulle wen', nie 'hy' nie.", [E.EDIT], 2),
      ch("G10SKR05.20", "Watter sin gebruik leestekens korrek?", ["Sy vra: \"Hoe gaan dit?\"", "Sy vra: Hoe gaan dit?", "Sy vra \"hoe gaan dit\""], "Sy vra: \"Hoe gaan dit?\"", "Direkte rede kry 'n dubbelpunt, aanhalingstekens en 'n hoofletter.", [E.EDIT], 2),
    ]),

  ...skill(`${P}.06`, "Opsomming: kies die kernpunte",
    "Kies die hoofpunte vir 'n opsomming van 'n Afrikaanse teks; los voorbeelde en herhaling uit, binne 'n puntperk.",
    "Skryf en aanbied", "T1", ["choice", "true-false"],
    "Hou net punte wat die betekenis verander; los voorbeelde, herhaling en enigiets wat jy kan weglaat en steeds die teks verstaan.",
    [
      ch("G10SKR06.01", "Watter een is 'n hoofpunt vir 'n opsomming?", ["Oefening verbeter jou gesondheid.", "My niggie hou van draf.", "Skoene kan duur wees."], "Oefening verbeter jou gesondheid.", "Die hoofidee is dat oefening die gesondheid verbeter; die res is besonderhede.", [E.SUM], 2, cx("Oefening verbeter jou gesondheid. My niggie hou van draf. Dit versterk die hart en spiere. Skoene kan duur wees.")),
      ch("G10SKR06.02", "Wat moet jy UITLAAT in 'n opsomming?", ["Voorbeelde en herhaling", "Die hoofidees", "Die belangrikste feite"], "Voorbeelde en herhaling", "Voorbeelde en herhaling word weggelaat in 'n opsomming.", [E.SUM], 1),
      ch("G10SKR06.03", "Watter een is 'n ONNODIGE besonderheid (nie 'n hoofpunt nie)?", ["Die wol was 'n pragtige blou kleur.", "Skape verskaf wol.", "Wol word vir klere gebruik."], "Die wol was 'n pragtige blou kleur.", "Die kleur is 'n ekstra besonderheid, nie 'n hoofpunt nie.", [E.SUM], 2, cx("Skape verskaf wol. Die wol was 'n pragtige blou kleur. Wol word vir klere gebruik.")),
      tf("G10SKR06.04", "'n Goeie opsomming herhaal dieselfde punt op verskillende maniere.", "Onwaar", "Nee — 'n opsomming vermy herhaling.", [E.SUM], 1),
      ch("G10SKR06.05", "Hoeveel keer tel 'n herhaalde idee in 'n opsomming?", ["Een keer", "Twee keer", "Elke keer wat dit verskyn"], "Een keer", "'n Herhaalde idee tel net een keer in 'n opsomming.", [E.SUM], 2),
      ch("G10SKR06.06", "Watter een is die hoofpunt?", ["Resiklering verminder besoedeling.", "My broer resikleer blikkies.", "Blikkies is van metaal."], "Resiklering verminder besoedeling.", "Die hoofidee is dat resiklering besoedeling verminder.", [E.SUM], 2, cx("Resiklering verminder besoedeling. My broer resikleer blikkies. Blikkies is van metaal. So word minder rommel gestort.")),
      ch("G10SKR06.07", "Wat moet 'n opsomming behou?", ["Die kernbetekenis van die teks", "Al die voorbeelde", "Die skrywer se naam"], "Die kernbetekenis van die teks", "'n Opsomming behou die kernbetekenis.", [E.SUM], 1),
      tf("G10SKR06.08", "Jy moet jou eie woorde gebruik wanneer jy opsom.", "Waar", "Ja — 'n goeie opsomming gebruik jou eie woorde.", [E.SUM], 1),
      ch("G10SKR06.09", "Watter sin kan jy weglaat sonder om die betekenis te verloor?", ["Die fees was, terloops, baie kleurvol.", "Die fees vier die oes.", "Mense dans en sing by die fees."], "Die fees was, terloops, baie kleurvol.", "Die 'terloops'-sin is ekstra; die hoofpunte bly sonder dit verstaanbaar.", [E.SUM], 3, cx("Die fees vier die oes. Die fees was, terloops, baie kleurvol. Mense dans en sing by die fees.")),
      ch("G10SKR06.10", "Wat is die EERSTE ding wat jy doen wanneer jy opsom?", ["Lees die teks deur en vind die hoofidees", "Begin dadelik skryf", "Tel die woorde"], "Lees die teks deur en vind die hoofidees", "Eers lees en hoofidees identifiseer, dan opsom.", [E.SUM], 1),
      ch("G10SKR06.11", "Watter een is 'n hoofpunt?", ["Slaap is noodsaaklik vir 'n gesonde brein.", "Sommige mense snork.", "Beddens kan sag of hard wees."], "Slaap is noodsaaklik vir 'n gesonde brein.", "Die hoofidee gaan oor die belang van slaap.", [E.SUM], 2, cx("Slaap is noodsaaklik vir 'n gesonde brein. Sommige mense snork. Beddens kan sag of hard wees. Dit help die geheue.")),
      tf("G10SKR06.12", "'n Opsomming is gewoonlik korter as die oorspronklike teks.", "Waar", "Ja — 'n opsomming is altyd korter as die bron.", [E.SUM], 1),
      ch("G10SKR06.13", "Wat doen jy as twee sinne dieselfde idee gee?", ["Sluit die idee net een keer in", "Sluit altwee in", "Laat altwee uit"], "Sluit die idee net een keer in", "Dieselfde idee word net een keer ingesluit.", [E.SUM], 2),
      ch("G10SKR06.14", "Watter een is die hoofpunt?", ["Bome verskaf suurstof.", "Die boom in ons tuin is hoog.", "Voëls sit in bome."], "Bome verskaf suurstof.", "Die hoofidee is dat bome suurstof verskaf.", [E.SUM], 2, cx("Bome verskaf suurstof. Die boom in ons tuin is hoog. Voëls sit in bome. Hulle is belangrik vir die lewe.")),
      ch("G10SKR06.15", "Behoort jy jou eie mening by 'n opsomming te voeg?", ["Nee, hou by die teks se idees", "Ja, altyd", "Net aan die einde"], "Nee, hou by die teks se idees", "'n Opsomming gee net die teks se idees, nie jou mening nie.", [E.SUM], 2),
      ch("G10SKR06.16", "Watter een is 'n ONNODIGE voorbeeld?", ["soos appels, piesangs en pere", "Vrugte is gesond.", "Vrugte bevat vitamiene."], "soos appels, piesangs en pere", "Die lys voorbeelde kan weggelaat word in 'n opsomming.", [E.SUM], 2, cx("Vrugte is gesond. Vrugte bevat vitamiene, soos appels, piesangs en pere.")),
      tf("G10SKR06.17", "Jy moet binne die gegewe puntperk of woordperk bly wanneer jy opsom.", "Waar", "Ja — 'n opsomming moet binne die voorgeskrewe perk bly.", [E.SUM], 1),
      ch("G10SKR06.18", "Watter een is die hoofpunt?", ["Water is noodsaaklik vir die lewe.", "Die rivier is naby ons huis.", "Visse leef in water."], "Water is noodsaaklik vir die lewe.", "Die hoofidee is dat water noodsaaklik is.", [E.SUM], 2, cx("Water is noodsaaklik vir die lewe. Die rivier is naby ons huis. Visse leef in water. Mense en plante het ook water nodig.")),
      ch("G10SKR06.19", "Wat is die doel van 'n opsomming?", ["Om die hooftrekke kort weer te gee", "Om die teks langer te maak", "Om nuwe inligting by te voeg"], "Om die hooftrekke kort weer te gee", "'n Opsomming gee die hooftrekke kort weer.", [E.SUM], 1),
      ch("G10SKR06.20", "Watter een sou jy EERSTE skrap om 'n opsomming korter te maak?", ["'n Voorbeeld wat 'n punt illustreer", "Die hoofidee", "'n Sleutelfeit"], "'n Voorbeeld wat 'n punt illustreer", "Voorbeelde word eerste geskrap; hoofidees en sleutelfeite bly.", [E.SUM], 2),
    ]),
};

insertSkills(skills);
