// Grade 10 — Taalstrukture tier, skills TAA.07–TAA.12 (20 items each). Afrikaans-only.
import { ch, tf, cz, skill, insertSkills } from "./_g10_bank_lib.mjs";

const P = "AF.G10.TAA";
const E = {
  REPORT: "ERR_AF_REPORTEDSPEECH", PASSIVE: "ERR_AF_PASSIVE", PUNCT: "ERR_AF_PUNCTUATION",
  SEM: "ERR_AF_SEMANTICS", HOMO: "ERR_AF_HOMOPHONE", IDIOM: "ERR_AF_IDIOM",
  WORDFORM: "ERR_AF_WORDFORM", SPELL: "ERR_AF_SPELLING", GRAM: "ERR_AF_GRAMMAR",
};

const skills = {
  ...skill(`${P}.07`, "Direkte en indirekte rede",
    "Verander tussen direkte en indirekte rede: leestekens, voornaamwoorde en bywoorde van tyd/plek verander.",
    "Taalstrukture", "T1", ["choice", "cloze"],
    "Na indirekte rede: laat die aanhalingstekens weg, verskuif die voornaamwoorde, en skuif tyd-/plekwoorde (nou→toe, hier→daar, vandag→daardie dag).",
    [
      ch("G10TAA07.01", "Kies die korrekte indirekte rede: Sy sê, \"Ek gaan huis toe.\"", ["Sy sê dat sy huis toe gaan.", "Sy sê dat ek huis toe gaan.", "Sy sê dat sy gaan huis toe."], "Sy sê dat sy huis toe gaan.", "'Ek' word 'sy', en die werkwoord skuif na die einde: 'dat sy huis toe gaan'.", [E.REPORT], 2),
      ch("G10TAA07.02", "Kies die korrekte indirekte rede: Jan sê, \"Ek is moeg.\"", ["Jan sê dat hy moeg is.", "Jan sê dat ek moeg is.", "Jan sê dat hy is moeg."], "Jan sê dat hy moeg is.", "'Ek' word 'hy' en 'is' skuif na die einde: 'dat hy moeg is'.", [E.REPORT], 1),
      ch("G10TAA07.03", "Kies die korrekte indirekte rede: Hy sê, \"Ek werk vandag.\"", ["Hy sê dat hy daardie dag werk.", "Hy sê dat hy vandag werk.", "Hy sê dat ek daardie dag werk."], "Hy sê dat hy daardie dag werk.", "'vandag' word 'daardie dag' en 'ek' word 'hy'.", [E.REPORT], 3),
      ch("G10TAA07.04", "Kies die korrekte indirekte rede vir 'n vraag: Hy vra, \"Waar is die kat?\"", ["Hy vra waar die kat is.", "Hy vra waar is die kat.", "Hy vra dat waar die kat is."], "Hy vra waar die kat is.", "By 'n vraag val die aanhalingstekens weg en die werkwoord skuif na die einde: 'waar die kat is'.", [E.REPORT], 2),
      ch("G10TAA07.05", "Kies die korrekte indirekte rede vir 'n bevel: Sy sê, \"Maak die deur toe.\"", ["Sy sê dat hy die deur moet toemaak.", "Sy sê dat maak die deur toe.", "Sy sê dat hy die deur toemaak moet."], "Sy sê dat hy die deur moet toemaak.", "'n Bevel word met 'moet' weergegee: 'dat hy die deur moet toemaak'.", [E.REPORT], 3),
      cz("G10TAA07.06", "Vul in: Direkte: \"Ek hou van jou.\" → Indirekte: Hy sê dat hy van ___ hou.", ["my", "jou", "haar"], "my", "Wanneer hy met my praat, word 'jou' in die weergawe 'my'.", [E.REPORT], 2),
      ch("G10TAA07.07", "Kies die korrekte indirekte rede: Ma sê, \"Julle moet nou eet.\"", ["Ma sê dat ons toe moet eet.", "Ma sê dat julle nou moet eet.", "Ma sê dat ons nou eet moet."], "Ma sê dat ons toe moet eet.", "'Julle' word 'ons' en 'nou' word 'toe'.", [E.REPORT], 3),
      ch("G10TAA07.08", "Watter verandering gebeur met 'hier' in indirekte rede?", ["dit word 'daar'", "dit bly 'hier'", "dit word 'nou'"], "dit word 'daar'", "Plekwoorde skuif: 'hier' word 'daar'.", [E.REPORT], 2),
      ch("G10TAA07.09", "Watter verandering gebeur met 'môre' in indirekte rede?", ["dit word 'die volgende dag'", "dit bly 'môre'", "dit word 'gister'"], "dit word 'die volgende dag'", "Tydwoorde skuif: 'môre' word 'die volgende dag'.", [E.REPORT], 3),
      ch("G10TAA07.10", "Kies die korrekte direkte rede: Hy sê dat hy honger is.", ["Hy sê, \"Ek is honger.\"", "Hy sê, \"Hy is honger.\"", "Hy sê: ek is honger."], "Hy sê, \"Ek is honger.\"", "In die direkte rede gebruik ons aanhalingstekens en 'Ek': \"Ek is honger.\"", [E.REPORT], 2),
      cz("G10TAA07.11", "Vul in: Sy sê, \"Ek het gewen.\" → Sy sê dat ___ gewen het.", ["sy", "ek", "hy"], "sy", "'Ek' word 'sy'.", [E.REPORT], 1),
      ch("G10TAA07.12", "Watter leesteken val weg wanneer ons na indirekte rede gaan?", ["aanhalingstekens", "die punt", "die komma"], "aanhalingstekens", "Indirekte rede gebruik nie aanhalingstekens nie.", [E.PUNCT], 1),
      ch("G10TAA07.13", "Kies die korrekte indirekte rede: Die juffrou sê, \"Die toets is môre.\"", ["Die juffrou sê dat die toets die volgende dag is.", "Die juffrou sê dat die toets môre is.", "Die juffrou sê dat die toets die vorige dag is."], "Die juffrou sê dat die toets die volgende dag is.", "'môre' word 'die volgende dag' en die werkwoord skuif na die einde.", [E.REPORT], 3),
      cz("G10TAA07.14", "Vul in: Hy sê, \"Ons speel nou.\" → Hy sê dat hulle ___ speel.", ["toe", "nou", "later"], "toe", "'nou' word 'toe' in indirekte rede.", [E.REPORT], 2),
      ch("G10TAA07.15", "Kies die korrekte indirekte rede: Sy vra, \"Hoekom huil jy?\"", ["Sy vra hoekom ek huil.", "Sy vra hoekom huil ek.", "Sy vra dat hoekom ek huil."], "Sy vra hoekom ek huil.", "By 'n vraag skuif die werkwoord na die einde: 'hoekom ek huil'.", [E.REPORT], 2),
      ch("G10TAA07.16", "Wat gebeur met die voornaamwoord 'ek' in indirekte rede (iemand anders praat)?", ["dit word 'hy' of 'sy'", "dit bly 'ek'", "dit word 'jy'"], "dit word 'hy' of 'sy'", "Die spreker se 'ek' word 'hy' of 'sy' wanneer iemand anders dit weergee.", [E.REPORT], 1),
      cz("G10TAA07.17", "Vul in: \"Ek woon hier,\" sê hy. → Hy sê dat hy ___ woon.", ["daar", "hier", "nou"], "daar", "'hier' word 'daar'.", [E.REPORT], 2),
      ch("G10TAA07.18", "Kies die korrekte indirekte rede: Pa sê, \"Ek sal jou help.\"", ["Pa sê dat hy my sal help.", "Pa sê dat ek jou sal help.", "Pa sê dat hy my help sal."], "Pa sê dat hy my sal help.", "'Ek' word 'hy', 'jou' word 'my', en die woordorde bly met 'sal ... help'.", [E.REPORT], 3),
      tf("G10TAA07.19", "In indirekte rede skuif die werkwoord gewoonlik na die einde van die bysin.", "Waar", "Ja — ná 'dat/waar/hoekom' kom die werkwoord aan die einde.", [E.REPORT], 2),
      ch("G10TAA07.20", "Kies die korrekte direkte rede: Sy vra waar die stasie is.", ["Sy vra, \"Waar is die stasie?\"", "Sy vra, \"Waar die stasie is?\"", "Sy vra: waar is die stasie."], "Sy vra, \"Waar is die stasie?\"", "Direkte rede gebruik aanhalingstekens en normale vraagorde: \"Waar is die stasie?\"", [E.REPORT], 2),
    ]),

  ...skill(`${P}.08`, "Bedrywende en lydende vorm",
    "Verander tussen die bedrywende (aktief) en lydende (passief) vorm oor verskillende tye.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Lydend: die voorwerp word die onderwerp + word/is/was/sal ... word + ...ge-werkwoord + (deur die agent). Pas die hulpwerkwoord by die tyd.",
    [
      ch("G10TAA08.01", "Kies die korrekte lydende vorm: 'Die hond byt die man.'", ["Die man word deur die hond gebyt.", "Die man is deur die hond gebyt.", "Die man byt deur die hond."], "Die man word deur die hond gebyt.", "Teenwoordige tyd lydend gebruik 'word': 'Die man word deur die hond gebyt.'", [E.PASSIVE], 2),
      ch("G10TAA08.02", "Kies die korrekte lydende vorm (verlede tyd): 'Die kat het die muis gevang.'", ["Die muis is deur die kat gevang.", "Die muis word deur die kat gevang.", "Die muis was die kat gevang."], "Die muis is deur die kat gevang.", "Verlede tyd lydend gebruik 'is ... gevang'.", [E.PASSIVE], 3),
      ch("G10TAA08.03", "Kies die korrekte bedrywende vorm: 'Die bal word deur die seun geskop.'", ["Die seun skop die bal.", "Die bal skop die seun.", "Die seun het die bal geskop."], "Die seun skop die bal.", "Bedrywend: die doener ('die seun') word die onderwerp: 'Die seun skop die bal.'", [E.PASSIVE], 2),
      cz("G10TAA08.04", "Vul die hulpwerkwoord in (teenwoordig, lydend): 'Die brood ___ deur die bakker gebak.'", ["word", "is", "was"], "word", "Teenwoordige tyd lydend gebruik 'word'.", [E.PASSIVE], 1),
      cz("G10TAA08.05", "Vul die hulpwerkwoord in (verlede, lydend): 'Die venster ___ deur die wind gebreek.'", ["is", "word", "sal"], "is", "Verlede tyd lydend gebruik 'is ... gebreek'.", [E.PASSIVE], 2),
      cz("G10TAA08.06", "Vul in (toekomende, lydend): 'Die huis ___ deur die bouers gebou ___.'", ["sal ... word", "word ... is", "is ... word"], "sal ... word", "Toekomende lydend: 'sal ... gebou word'.", [E.PASSIVE], 3),
      ch("G10TAA08.07", "Watter sin is in die lydende vorm?", ["Die koek word deur Ma gebak.", "Ma bak die koek.", "Ma het die koek gebak."], "Die koek word deur Ma gebak.", "Die lydende vorm het 'word ... deur'.", [E.PASSIVE], 1),
      ch("G10TAA08.08", "Watter sin is in die bedrywende vorm?", ["Die kinders eet die appels.", "Die appels word geëet.", "Die appels is deur die kinders geëet."], "Die kinders eet die appels.", "Die bedrywende vorm wys die doener as onderwerp.", [E.PASSIVE], 1),
      ch("G10TAA08.09", "Kies die korrekte lydende vorm: 'Die juffrou prys die leerder.'", ["Die leerder word deur die juffrou geprys.", "Die leerder prys die juffrou.", "Die leerder is die juffrou geprys."], "Die leerder word deur die juffrou geprys.", "Teenwoordig lydend: 'word ... geprys'.", [E.PASSIVE], 2),
      ch("G10TAA08.10", "Kies die korrekte bedrywende vorm (verlede): 'Die ruit is deur die bal gebreek.'", ["Die bal het die ruit gebreek.", "Die bal breek die ruit.", "Die ruit het die bal gebreek."], "Die bal het die ruit gebreek.", "Bedrywend verlede: 'Die bal het die ruit gebreek.'", [E.PASSIVE], 2),
      cz("G10TAA08.11", "Vul die agent in: 'Die lied word ___ die koor gesing.'", ["deur", "met", "van"], "deur", "Die doener word met 'deur' aangedui: 'deur die koor'.", [E.PASSIVE], 1),
      tf("G10TAA08.12", "In die lydende vorm word die voorwerp die onderwerp van die sin.", "Waar", "Ja — dit is presies hoe die lydende vorm werk.", [E.PASSIVE], 2),
      ch("G10TAA08.13", "Kies die korrekte lydende vorm: 'Die polisie vang die dief.'", ["Die dief word deur die polisie gevang.", "Die dief vang die polisie.", "Die dief is die polisie gevang."], "Die dief word deur die polisie gevang.", "Teenwoordig lydend: 'word ... gevang'.", [E.PASSIVE], 2),
      ch("G10TAA08.14", "Watter hulpwerkwoord pas by die verlede tyd in die lydende vorm?", ["is", "word", "sal"], "is", "Verlede tyd lydend gebruik 'is'.", [E.PASSIVE], 2),
      ch("G10TAA08.15", "Watter hulpwerkwoord pas by die teenwoordige tyd in die lydende vorm?", ["word", "is", "was"], "word", "Teenwoordige tyd lydend gebruik 'word'.", [E.PASSIVE], 1),
      ch("G10TAA08.16", "Kies die korrekte lydende vorm (verlede): 'Die man het die brief geskryf.'", ["Die brief is deur die man geskryf.", "Die brief word deur die man geskryf.", "Die brief het die man geskryf."], "Die brief is deur die man geskryf.", "Verlede lydend: 'is ... geskryf'.", [E.PASSIVE], 3),
      cz("G10TAA08.17", "Vul in (teenwoordig, lydend): 'Die klas ___ deur die hoof toegespreek.'", ["word", "is", "sal"], "word", "Teenwoordig lydend gebruik 'word ... toegespreek'.", [E.PASSIVE], 2),
      ch("G10TAA08.18", "Kies die korrekte bedrywende vorm: 'Die wedstryd word deur die skeidsregter geblaas.'", ["Die skeidsregter blaas die wedstryd.", "Die wedstryd blaas die skeidsregter.", "Die skeidsregter het die wedstryd geblaas."], "Die skeidsregter blaas die wedstryd.", "Die doener ('die skeidsregter') word die onderwerp.", [E.PASSIVE], 2),
      tf("G10TAA08.19", "Is ''Die kos is deur Ouma gekook' 'n lydende sin in die verlede tyd?", "Waar", "Ja — 'is ... gekook' met 'deur' is verlede tyd lydend.", [E.PASSIVE], 2),
      ch("G10TAA08.20", "Kies die korrekte lydende vorm (toekomende): 'Die span sal die beker wen.'", ["Die beker sal deur die span gewen word.", "Die beker word deur die span gewen.", "Die beker is deur die span gewen."], "Die beker sal deur die span gewen word.", "Toekomende lydend: 'sal ... gewen word'.", [E.PASSIVE], 3),
    ]),

  ...skill(`${P}.09`, "Leestekens en punktuasie",
    "Korrekte gebruik van leestekens: komma, punt, vraagteken, dubbelpunt, kommapunt, aanhalingstekens, koppelteken en afkappingsteken.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Elke teken het 'n taak: ? sluit 'n vraag af, : lei in, ; verbind twee nou sinne, en \" \" omraam die presiese woorde wat gesê word.",
    [
      ch("G10TAA09.01", "Watter leesteken hoort aan die einde van 'Wat is jou naam'?", ["vraagteken (?)", "punt (.)", "uitroepteken (!)"], "vraagteken (?)", "'n Vraag eindig met 'n vraagteken: 'Wat is jou naam?'", [E.PUNCT], 1),
      ch("G10TAA09.02", "Watter leesteken lei 'n lys in?", ["dubbelpunt (:)", "komma (,)", "kommapunt (;)"], "dubbelpunt (:)", "Die dubbelpunt lei 'n lys of verduideliking in: 'Koop dit: brood, melk, eiers.'", [E.PUNCT], 2),
      ch("G10TAA09.03", "Kies die korrekte direkte rede:", ["Sy sê: \"Ek kom nou.\"", "Sy sê: Ek kom nou.", "Sy sê \"ek kom nou\""], "Sy sê: \"Ek kom nou.\"", "Direkte rede kry aanhalingstekens en die woorde begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G10TAA09.04", "Watter leesteken verbind twee nou verwante sinne sonder 'n voegwoord?", ["kommapunt (;)", "komma (,)", "vraagteken (?)"], "kommapunt (;)", "Die kommapunt verbind twee nou verwante hoofsinne: 'Dit reën; ons bly tuis.'", [E.PUNCT], 3),
      ch("G10TAA09.05", "Kies die korrekte gebruik van die afkappingsteken:", ["Dit is die 1990's.", "Dit is die 1990s'.", "Dit is die 1990s."], "Dit is die 1990's.", "Die afkappingsteken kom voor die meervouds-s: '1990's', 'foto's'.", [E.PUNCT], 3),
      ch("G10TAA09.06", "Watter sin gebruik die komma korrek?", ["Ek koop brood, melk en eiers.", "Ek koop brood melk, en eiers.", "Ek koop, brood melk en eiers."], "Ek koop brood, melk en eiers.", "Kommas skei items in 'n lys; die laaste twee word met 'en' verbind.", [E.PUNCT], 2),
      cz("G10TAA09.07", "Vul die regte teken in: 'Pasop___ Daar is 'n gat in die pad.'", ["!", "?", ","], "!", "'n Waarskuwing kry 'n uitroepteken: 'Pasop!'", [E.PUNCT], 1),
      ch("G10TAA09.08", "Watter sin gebruik die koppelteken korrek?", ["een-en-twintig", "een en twintig-", "een–en–twintig"], "een-en-twintig", "Getalle soos 'een-en-twintig' kry koppeltekens.", [E.PUNCT], 2),
      ch("G10TAA09.09", "Watter leesteken eindig 'n gewone stelsin?", ["punt (.)", "vraagteken (?)", "dubbelpunt (:)"], "punt (.)", "'n Stelsin eindig met 'n punt.", [E.PUNCT], 1),
      ch("G10TAA09.10", "Kies die korrek geskrewe sin:", ["\"Kom hier!\" roep sy.", "\"Kom hier\"! roep sy.", "\"kom hier!\" roep sy."], "\"Kom hier!\" roep sy.", "Die uitroepteken staan binne die aanhalingstekens en die eerste woord kry 'n hoofletter.", [E.PUNCT], 3),
      cz("G10TAA09.11", "Vul die teken in: 'My gunsteling kleure is blou___ groen en rooi.'", [",", ":", ";"], ",", "Items in 'n lys word met kommas geskei.", [E.PUNCT], 1),
      tf("G10TAA09.12", "Begin die eerste woord binne aanhalingstekens met 'n hoofletter wanneer dit 'n volsin is?", "Waar", "Ja — die aangehaalde volsin begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G10TAA09.13", "Watter sin gebruik die besitsvorm korrek?", ["Dit is Thabo se boek.", "Dit is Thabo's boek.", "Dit is Thabos boek."], "Dit is Thabo se boek.", "Afrikaans gebruik 'se' vir besit: 'Thabo se boek' (nie 's nie).", [E.PUNCT], 2),
      ch("G10TAA09.14", "Watter leesteken pas: 'Sy het een vraag gehad___ waar is die geld?'", [": ", "; ", ". "], ": ", "Die dubbelpunt lei die vraag/verduideliking in.", [E.PUNCT], 3),
      ch("G10TAA09.15", "Kies die korrekte gebruik van aanhalingstekens:", ["Hy lees die boek \"Fiela se Kind\".", "Hy lees die boek Fiela se Kind\".", "Hy lees die boek \"Fiela se Kind."], "Hy lees die boek \"Fiela se Kind\".", "Titels en aangehaalde woorde word tussen aanhalingstekens geplaas — oop en toe.", [E.PUNCT], 2),
      cz("G10TAA09.16", "Vul die teken in: 'Het jy die werk klaar___'", ["?", "!", "."], "?", "Dit is 'n vraag, dus 'n vraagteken.", [E.PUNCT], 1),
      ch("G10TAA09.17", "Watter sin gebruik die deelteken korrek?", ["Hy het reëns verwag.", "Hy het reens verwag.", "Hy het re-ens verwag."], "Hy het reëns verwag.", "Die deelteken (ë) wys dat die e apart uitgespreek word: 'reëns'.", [E.PUNCT], 3),
      tf("G10TAA09.18", "Word 'n komma binne-in 'n eenvoudige stelsin sonder lys altyd vereis?", "Onwaar", "Nee — 'n eenvoudige stelsin het nie altyd 'n komma nodig nie.", [E.PUNCT], 2),
      ch("G10TAA09.19", "Kies die korrekte sin:", ["\"Waar is jy?\" vra hy.", "\"Waar is jy\"? vra hy.", "\"waar is jy?\" vra hy."], "\"Waar is jy?\" vra hy.", "Die vraagteken staan binne die aanhalingstekens en die sin begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G10TAA09.20", "Watter teken gebruik jy om twee dele soos 'die wen-doel' te verbind?", ["koppelteken (-)", "komma (,)", "dubbelpunt (:)"], "koppelteken (-)", "Die koppelteken verbind woorddele: 'wen-doel'.", [E.PUNCT], 2),
    ]),

  ...skill(`${P}.10`, "Betekenisleer: sinonieme, antonieme, homofone",
    "Sinonieme, antonieme, homofone (ly/lei), homonieme en paronieme — woorde wat dieselfde klink of na aan mekaar lyk.",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "Sinoniem = dieselfde betekenis, antoniem = teenoorgesteld; homofone klink dieselfde maar verskil in spelling en betekenis — gebruik die sin om te kies.",
    [
      ch("G10TAA10.01", "Watter woord is 'n sinoniem vir 'bly'?", ["gelukkig", "hartseer", "kwaad"], "gelukkig", "'bly' en 'gelukkig' beteken dieselfde — hulle is sinonieme.", [E.SEM], 1),
      ch("G10TAA10.02", "Watter woord is 'n sinoniem vir 'vinnig'?", ["gou", "stadig", "swaar"], "gou", "'vinnig' en 'gou' beteken min of meer dieselfde.", [E.SEM], 1),
      ch("G10TAA10.03", "Wat is die teenoorgestelde (antoniem) van 'groot'?", ["klein", "lank", "swaar"], "klein", "Die antoniem van 'groot' is 'klein'.", [E.SEM], 1),
      ch("G10TAA10.04", "Wat is die teenoorgestelde van 'oud'?", ["jonk", "groot", "moeg"], "jonk", "Die antoniem van 'oud' is 'jonk'.", [E.SEM], 1),
      ch("G10TAA10.05", "Wat is die teenoorgestelde van 'oop'?", ["toe", "wyd", "groot"], "toe", "Die antoniem van 'oop' is 'toe'.", [E.SEM], 1),
      cz("G10TAA10.06", "Kies die korrekte homofoon: 'Hy ___ aan griep.' (om siek te wees)", ["ly", "lei", "lê"], "ly", "'ly' beteken om te swaarkry/siek wees; 'lei' beteken om te lei/wys.", [E.HOMO], 3),
      cz("G10TAA10.07", "Kies die korrekte homofoon: 'Die gids sal ons ___.' (om te wys/voor te loop)", ["lei", "ly", "lê"], "lei", "'lei' beteken om voor te loop/te wys.", [E.HOMO], 3),
      ch("G10TAA10.08", "Watter twee woorde is homofone (klink dieselfde, verskil in betekenis)?", ["ly en lei", "groot en klein", "bly en gelukkig"], "ly en lei", "'ly' en 'lei' klink dieselfde maar het verskillende betekenisse.", [E.HOMO], 2),
      ch("G10TAA10.09", "Watter woord is 'n sinoniem vir 'mooi'?", ["pragtig", "lelik", "vuil"], "pragtig", "'mooi' en 'pragtig' is sinonieme.", [E.SEM], 1),
      ch("G10TAA10.10", "Wat is die teenoorgestelde van 'vol'?", ["leeg", "swaar", "groot"], "leeg", "Die antoniem van 'vol' is 'leeg'.", [E.SEM], 1),
      ch("G10TAA10.11", "Wat is die teenoorgestelde van 'begin'?", ["eindig", "loop", "staan"], "eindig", "Die antoniem van 'begin' is 'eindig'.", [E.SEM], 2),
      ch("G10TAA10.12", "Watter woord is 'n sinoniem vir 'huis'?", ["woning", "tuin", "straat"], "woning", "'huis' en 'woning' beteken dieselfde.", [E.SEM], 2),
      cz("G10TAA10.13", "Kies die korrekte woord (paronieme): 'Die ___ van die storie is duidelik.' (boodskap, nie 'bottel' nie)", ["boodskap", "boodkap", "bootskap"], "boodskap", "'boodskap' is die korrekte spelling vir 'message'.", [E.SPELL], 2),
      ch("G10TAA10.14", "Watter woord is 'n homoniem (dieselfde spelling, twee betekenisse)? 'bank'", ["bank (sitplek én geldplek)", "bank en tafel", "bank en stoel"], "bank (sitplek én geldplek)", "'bank' kan 'n sitbank of 'n geldbank wees — een spelling, twee betekenisse.", [E.SEM], 3),
      ch("G10TAA10.15", "Wat is die teenoorgestelde van 'warm'?", ["koud", "sag", "lig"], "koud", "Die antoniem van 'warm' is 'koud'.", [E.SEM], 1),
      ch("G10TAA10.16", "Watter woord is 'n sinoniem vir 'begin'?", ["aanvang", "klaarmaak", "ophou"], "aanvang", "'begin' en 'aanvang' beteken dieselfde.", [E.SEM], 2),
      tf("G10TAA10.17", "Is 'blink' en 'dof' antonieme?", "Waar", "Ja — 'blink' en 'dof' is teenoorgesteldes.", [E.SEM], 2),
      cz("G10TAA10.18", "Kies die korrekte woord: 'Sy het 'n mooi ___ aangetrek.' (rok, nie 'rook' nie)", ["rok", "rook", "rook'"], "rok", "'rok' is 'n kledingstuk; 'rook' kom van vuur — let op die betekenis.", [E.HOMO], 2),
      ch("G10TAA10.19", "Watter woord is 'n sinoniem vir 'moeilik'?", ["swaar", "maklik", "lig"], "swaar", "'moeilik' en 'swaar' kan dieselfde beteken (iets wat moeite kos).", [E.SEM], 2),
      ch("G10TAA10.20", "Wat is die teenoorgestelde van 'waarheid'?", ["leuen", "storie", "feit"], "leuen", "Die antoniem van 'waarheid' is 'leuen'.", [E.SEM], 2),
    ]),

  ...skill(`${P}.11`, "Idiome en spreekwoorde",
    "Verstaan algemene Afrikaanse idiome, idiomatiese uitdrukkings en spreekwoorde volgens hul figuurlike betekenis.",
    "Taalstrukture", "T4", ["choice", "cloze", "true-false"],
    "Stel jou voor wat die woorde letterlik sê, en vra dan wat mense regtig daarmee bedoel; leer idiome as geheel, nie woord-vir-woord nie.",
    [
      ch("G10TAA11.01", "Wat beteken 'om die aap uit die mou te laat'?", ["om 'n geheim te verklap", "om 'n aap te hê", "om kwaad te word"], "om 'n geheim te verklap", "'die aap uit die mou laat' beteken om 'n geheim te verklap.", [E.IDIOM], 2),
      ch("G10TAA11.02", "Wat beteken 'hy het 'n hart van goud'?", ["hy is baie goedhartig", "hy is ryk", "hy dra goud"], "hy is baie goedhartig", "'n Hart van goud beteken iemand is baie gaaf en goedhartig.", [E.IDIOM], 1),
      ch("G10TAA11.03", "Wat beteken 'om iemand 'n rat voor die oë te draai'?", ["om iemand te mislei", "om te bestuur", "om iemand te help"], "om iemand te mislei", "Dit beteken om iemand te kul of te bedrieg.", [E.IDIOM], 3),
      ch("G10TAA11.04", "Wat beteken 'die koeël is deur die kerk'?", ["die besluit is finaal geneem", "daar is geskiet", "die kerk is stukkend"], "die besluit is finaal geneem", "Dit beteken die saak is afgehandel; die besluit staan vas.", [E.IDIOM], 3),
      ch("G10TAA11.05", "Wat beteken 'so siek soos 'n hond'?", ["baie siek", "lui", "honger"], "baie siek", "Die vergelyking beteken iemand is baie siek.", [E.IDIOM], 1),
      ch("G10TAA11.06", "Wat beteken die spreekwoord 'Aanhouer wen'?", ["as jy aanhou probeer, sal jy slaag", "moenie hou nie", "hou vas aan geld"], "as jy aanhou probeer, sal jy slaag", "Volharding lei tot sukses — 'Aanhouer wen'.", [E.IDIOM], 2),
      ch("G10TAA11.07", "Wat beteken die spreekwoord 'Eendrag maak mag'?", ["samewerking gee krag", "een mens is sterk", "krag maak een"], "samewerking gee krag", "Wanneer mense saamstaan, is hulle sterker.", [E.IDIOM], 2),
      ch("G10TAA11.08", "Wat beteken 'om bang te wees vir jou eie skaduwee'?", ["baie skrikkerig wees", "in die son staan", "vir die nag bang wees"], "baie skrikkerig wees", "Dit beskryf iemand wat oordrewe bang of skrikkerig is.", [E.IDIOM], 3),
      ch("G10TAA11.09", "Wat beteken 'om water in 'n mandjie te dra'?", ["om iets nutteloos te doen", "om te gaan stort", "om hard te werk"], "om iets nutteloos te doen", "Dit beteken om iets te doen wat heeltemal vergeefs is.", [E.IDIOM], 3),
      ch("G10TAA11.10", "Wat beteken 'om die hoof koel te hou'?", ["om kalm te bly", "om koud te kry", "om te dink"], "om kalm te bly", "Dit beteken om kalm en beheers te bly in 'n moeilike tyd.", [E.IDIOM], 2),
      cz("G10TAA11.11", "Voltooi die idioom: 'So bly soos 'n ___.'", ["voël", "vis", "hond"], "voël", "Die idioom is 'so bly soos 'n voëltjie' — baie gelukkig.", [E.IDIOM], 2),
      cz("G10TAA11.12", "Voltooi die spreekwoord: 'Môre is nog 'n ___.'", ["dag", "jaar", "kans"], "dag", "'Môre is nog 'n dag' — daar is altyd 'n nuwe kans.", [E.IDIOM], 1),
      ch("G10TAA11.13", "Wat beteken 'om met die deur in die huis te val'?", ["om reguit tot die punt te kom", "om te struikel", "om die deur te breek"], "om reguit tot die punt te kom", "Dit beteken om dadelik tot die saak te kom sonder inleiding.", [E.IDIOM], 3),
      ch("G10TAA11.14", "Wat beteken 'om 'n oogie oor iets te hou'?", ["om iets dop te hou", "om te slaap", "om weg te kyk"], "om iets dop te hou", "Dit beteken om iets te bewaak of in die oog te hou.", [E.IDIOM], 2),
      ch("G10TAA11.15", "Wat beteken die spreekwoord 'Wie nie waag nie, sal nie wen nie'?", ["jy moet kanse waag om te slaag", "moenie speel nie", "wen is maklik"], "jy moet kanse waag om te slaag", "Sonder om 'n kans te waag, kan jy nie sukses behaal nie.", [E.IDIOM], 2),
      ch("G10TAA11.16", "Wat beteken 'om uit jou vel te spring'?", ["baie opgewonde of ongeduldig wees", "om te val", "om koud te kry"], "baie opgewonde of ongeduldig wees", "Dit beskryf groot opgewondenheid of ongeduld.", [E.IDIOM], 3),
      tf("G10TAA11.17", "Beteken 'om die kat aan die stert beet te hê' dat jy 'n probleem heeltemal verkeerd aanpak?", "Waar", "Ja — dit beteken jy pak iets heeltemal verkeerd aan.", [E.IDIOM], 3),
      ch("G10TAA11.18", "Wat beteken 'om iemand se hand te vra'?", ["om met iemand te wil trou", "om hulp te vra", "om hande te skud"], "om met iemand te wil trou", "Dit is 'n idioom vir 'n huweliksaansoek.", [E.IDIOM], 2),
      cz("G10TAA11.19", "Voltooi die idioom: 'Hy is so arm soos 'n ___.'", ["kerkmuis", "koning", "boer"], "kerkmuis", "'so arm soos 'n kerkmuis' beteken baie arm.", [E.IDIOM], 2),
      ch("G10TAA11.20", "Wat beteken 'om olie op die vuur te gooi'?", ["om 'n saak erger te maak", "om te kook", "om te help"], "om 'n saak erger te maak", "Dit beteken om 'n moeilike situasie nog erger te maak.", [E.IDIOM], 3),
    ]),

  ...skill(`${P}.12`, "Woordvorming en spelling: afleiding, samestelling, afkortings",
    "Bou en spel woorde met voor- en agtervoegsels (afleiding), saamgestelde woorde (samestelling), en hanteer afkortings, akronieme en spelpatrone.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Afrikaans skryf die meeste saamgestelde woorde as EEN woord; 'n voor-/agtervoegsel verander die betekenis (on- = nie, -loos = sonder) — bou vanaf die stam.",
    [
      ch("G10TAA12.01", "Hoe skryf 'n mens 'tafel' + 'doek' korrek?", ["tafeldoek", "tafel doek", "tafel-doek"], "tafeldoek", "Saamgestelde woorde word as een woord geskryf: 'tafeldoek'.", [E.WORDFORM], 1),
      ch("G10TAA12.02", "Hoe skryf 'n mens 'sokker' + 'veld' korrek?", ["sokkerveld", "sokker veld", "sokker-veld"], "sokkerveld", "Een woord: 'sokkerveld'.", [E.WORDFORM], 1),
      cz("G10TAA12.03", "Voeg '-loos' by 'werk': ___", ["werkloos", "werkeloos", "werkloos'"], "werkloos", "'-loos' beteken 'sonder': 'werkloos' = sonder werk.", [E.WORDFORM], 2),
      cz("G10TAA12.04", "Voeg 'on-' by 'gelukkig': ___", ["ongelukkig", "ongeluk", "on gelukkig"], "ongelukkig", "Die voorvoegsel 'on-' beteken 'nie': 'ongelukkig'.", [E.WORDFORM], 1),
      ch("G10TAA12.05", "Waarvoor staan die afkorting 'bv.'?", ["byvoorbeeld", "bevel", "bladsy"], "byvoorbeeld", "'bv.' is die afkorting vir 'byvoorbeeld'.", [E.SPELL], 1),
      ch("G10TAA12.06", "Waarvoor staan die afkorting 'ens.'?", ["ensovoorts", "eindelik", "enkel"], "ensovoorts", "'ens.' staan vir 'ensovoorts'.", [E.SPELL], 1),
      ch("G10TAA12.07", "Waarvoor staan die afkorting 'dr.'?", ["dokter", "draai", "dronk"], "dokter", "'dr.' is die afkorting vir 'dokter'.", [E.SPELL], 1),
      ch("G10TAA12.08", "Watter een is 'n akroniem?", ["SABS", "byvoorbeeld", "tafeldoek"], "SABS", "'n Akroniem word uit die eerste letters gevorm, bv. SABS.", [E.SPELL], 2),
      cz("G10TAA12.09", "Voeg '-baar' by 'eet': ___ (kan geëet word)", ["eetbaar", "etebaar", "eet baar"], "eetbaar", "'-baar' beteken 'kan ge...word': 'eetbaar'.", [E.WORDFORM], 2),
      cz("G10TAA12.10", "Voeg 'her-' by 'gebruik': ___ (om weer te gebruik)", ["hergebruik", "her gebruik", "hergebruike"], "hergebruik", "'her-' beteken 'weer': 'hergebruik'.", [E.WORDFORM], 2),
      ch("G10TAA12.11", "Hoe skryf 'n mens 'rekenaar' + 'skerm' korrek?", ["rekenaarskerm", "rekenaar skerm", "rekenaar-skerm"], "rekenaarskerm", "Een woord: 'rekenaarskerm'.", [E.WORDFORM], 1),
      ch("G10TAA12.12", "Watter woord is 'n afleiding van 'lees'?", ["leser", "leesboek", "leestyd"], "leser", "'leser' is afgelei deur '-er' by 'lees' te voeg; die ander is samestellings.", [E.WORDFORM], 3),
      ch("G10TAA12.13", "Watter woord is korrek gespel?", ["onmiddellik", "onmidellik", "onmiddelik"], "onmiddellik", "Die korrekte spelling is 'onmiddellik'.", [E.SPELL], 3),
      ch("G10TAA12.14", "Watter woord is korrek gespel?", ["gewoonlik", "gewoonelik", "gewonlik"], "gewoonlik", "Die korrekte spelling is 'gewoonlik'.", [E.SPELL], 2),
      cz("G10TAA12.15", "Voeg '- heid' by 'gesond': ___", ["gesondheid", "gesond heid", "gesonheid"], "gesondheid", "'-heid' maak 'n naamwoord: 'gesondheid'.", [E.WORDFORM], 2),
      ch("G10TAA12.16", "Waarvoor staan 'a.g.v.'?", ["as gevolg van", "agter geveg van", "almal gaan voor"], "as gevolg van", "'a.g.v.' staan vir 'as gevolg van'.", [E.SPELL], 2),
      ch("G10TAA12.17", "Hoe skryf 'n mens 'see' + 'water' korrek?", ["seewater", "see water", "see-water"], "seewater", "Een woord: 'seewater'.", [E.WORDFORM], 1),
      tf("G10TAA12.18", "Word 'tafel doek' korrek as twee aparte woorde geskryf?", "Onwaar", "Nee — dit is 'n samestelling en word as een woord geskryf: 'tafeldoek'.", [E.WORDFORM], 2),
      ch("G10TAA12.19", "Watter woord is korrek gespel?", ["professioneel", "profesioneel", "professionel"], "professioneel", "Die korrekte spelling is 'professioneel'.", [E.SPELL], 3),
      cz("G10TAA12.20", "Voeg 'wan-' by 'orde': ___ (gebrek aan orde)", ["wanorde", "wan orde", "wanordes"], "wanorde", "Die voorvoegsel 'wan-' dui 'n gebrek/foutiewe toestand aan: 'wanorde'.", [E.WORDFORM], 3),
    ]),
};

insertSkills(skills);
