// Grade 11 — Taalstrukture tier, skills TAA.07–TAA.12 (20 items each). Afrikaans-only.
// Deepens Grade 10: reported speech incl. questions & commands; passive across all tenses;
// punctuation (extended); semantics + polisemie; wider idioms; word-formation +
// samestellende afleiding & akronieme.
import { ch, tf, cz, skill, insertSkills } from "./_g11_bank_lib.mjs";

const P = "AF.G11.TAA";
const E = {
  REPORT: "ERR_AF_REPORTEDSPEECH", PASSIVE: "ERR_AF_PASSIVE", PUNCT: "ERR_AF_PUNCTUATION",
  SEM: "ERR_AF_SEMANTICS", HOMO: "ERR_AF_HOMOPHONE", POLY: "ERR_AF_POLYSEMY",
  IDIOM: "ERR_AF_IDIOM", WORDFORM: "ERR_AF_WORDFORM", SPELL: "ERR_AF_SPELLING", GRAM: "ERR_AF_GRAMMAR",
};

const skills = {
  ...skill(`${P}.07`, "Direkte en indirekte rede, ook vrae en bevele",
    "Verander tussen direkte en indirekte rede vir stellings, vrae én bevele: leestekens, voornaamwoorde, woordorde en tyd-/plekwoorde verander.",
    "Taalstrukture", "T1", ["choice", "cloze"],
    "Na indirekte rede: laat aanhalingstekens weg, verskuif die voornaamwoorde en tyd-/plekwoorde; 'n vraag hou sy vraagwoord met die werkwoord aan die einde; 'n bevel gebruik 'moet'.",
    [
      ch("G11TAA07.01", "Kies die korrekte indirekte rede: Sy sê, \"Ek gaan more huis toe.\"", ["Sy sê dat sy die volgende dag huis toe gaan.", "Sy sê dat ek more huis toe gaan.", "Sy sê dat sy gaan more huis toe."], "Sy sê dat sy die volgende dag huis toe gaan.", "'Ek' word 'sy', 'more' word 'die volgende dag', en die werkwoord skuif na die einde.", [E.REPORT], 3),
      ch("G11TAA07.02", "Kies die korrekte indirekte rede vir 'n VRAAG: Hy vra, \"Waar woon jy?\"", ["Hy vra waar ek woon.", "Hy vra waar woon ek.", "Hy vra dat waar ek woon."], "Hy vra waar ek woon.", "By 'n vraag val die aanhalingstekens weg en die werkwoord skuif na die einde: 'waar ek woon'.", [E.REPORT], 2),
      ch("G11TAA07.03", "Kies die korrekte indirekte rede vir 'n BEVEL: Sy sê, \"Maak die venster oop.\"", ["Sy sê dat hy die venster moet oopmaak.", "Sy sê dat maak die venster oop.", "Sy sê dat hy die venster oopmaak moet."], "Sy sê dat hy die venster moet oopmaak.", "'n Bevel word met 'moet' weergegee: 'dat hy die venster moet oopmaak'.", [E.REPORT], 3),
      ch("G11TAA07.04", "Kies die korrekte indirekte rede: Jan sê, \"Ek is trots op my werk.\"", ["Jan sê dat hy trots op sy werk is.", "Jan sê dat ek trots op my werk is.", "Jan sê dat hy is trots op sy werk."], "Jan sê dat hy trots op sy werk is.", "'Ek' word 'hy', 'my' word 'sy', en die werkwoord skuif na die einde.", [E.REPORT], 2),
      ch("G11TAA07.05", "Kies die korrekte indirekte rede vir 'n VRAAG: Sy vra, \"Hoekom huil die kind?\"", ["Sy vra hoekom die kind huil.", "Sy vra hoekom huil die kind.", "Sy vra dat hoekom die kind huil."], "Sy vra hoekom die kind huil.", "By 'n vraag skuif die werkwoord na die einde: 'hoekom die kind huil'.", [E.REPORT], 2),
      cz("G11TAA07.06", "Vul in: \"Ek hou van jou,\" sê hy vir my. → Hy sê dat hy van ___ hou.", ["my", "jou", "haar"], "my", "Wanneer hy met my praat, word 'jou' in die weergawe 'my'.", [E.REPORT], 2),
      ch("G11TAA07.06b", "Kies die korrekte indirekte rede vir 'n BEVEL: Ma sê, \"Doen jou huiswerk.\"", ["Ma sê dat ek my huiswerk moet doen.", "Ma sê dat doen jou huiswerk.", "Ma sê dat ek my huiswerk doen moet."], "Ma sê dat ek my huiswerk moet doen.", "'n Bevel word met 'moet' weergegee, en 'jou' word 'my'.", [E.REPORT], 3),
      ch("G11TAA07.08", "Watter verandering gebeur met 'vandag' in indirekte rede?", ["dit word 'daardie dag'", "dit bly 'vandag'", "dit word 'gister'"], "dit word 'daardie dag'", "Tydwoorde skuif: 'vandag' word 'daardie dag'.", [E.REPORT], 2),
      ch("G11TAA07.09", "Watter verandering gebeur met 'hier' in indirekte rede?", ["dit word 'daar'", "dit bly 'hier'", "dit word 'nou'"], "dit word 'daar'", "Plekwoorde skuif: 'hier' word 'daar'.", [E.REPORT], 2),
      ch("G11TAA07.10", "Kies die korrekte DIREKTE rede: Hy sê dat hy moeg is.", ["Hy sê, \"Ek is moeg.\"", "Hy sê, \"Hy is moeg.\"", "Hy sê: ek is moeg."], "Hy sê, \"Ek is moeg.\"", "In die direkte rede gebruik ons aanhalingstekens en 'Ek': \"Ek is moeg.\"", [E.REPORT], 2),
      cz("G11TAA07.11", "Vul in: Sy sê, \"Ek het gewen.\" → Sy sê dat ___ gewen het.", ["sy", "ek", "hy"], "sy", "'Ek' word 'sy'.", [E.REPORT], 1),
      ch("G11TAA07.12", "Wat gebeur met die werkwoord in 'n indirekte VRAAG?", ["dit skuif na die einde van die bysin", "dit bly vooraan", "dit verdwyn"], "dit skuif na die einde van die bysin", "By 'n indirekte vraag skuif die werkwoord na die einde: 'waar die kat is'.", [E.REPORT], 2),
      ch("G11TAA07.13", "Kies die korrekte indirekte rede: Die juffrou sê, \"Die toets is more.\"", ["Die juffrou sê dat die toets die volgende dag is.", "Die juffrou sê dat die toets more is.", "Die juffrou sê dat die toets die vorige dag is."], "Die juffrou sê dat die toets die volgende dag is.", "'more' word 'die volgende dag' en die werkwoord skuif na die einde.", [E.REPORT], 3),
      cz("G11TAA07.14", "Vul in: Hy sê, \"Ons werk nou.\" → Hy sê dat hulle ___ werk.", ["toe", "nou", "later"], "toe", "'nou' word 'toe' in indirekte rede.", [E.REPORT], 2),
      ch("G11TAA07.15", "Kies die korrekte indirekte rede vir 'n BEVEL: Die afrigter sê, \"Hardloop vinniger!\"", ["Die afrigter sê dat hulle vinniger moet hardloop.", "Die afrigter sê dat hardloop vinniger.", "Die afrigter sê dat hulle vinniger hardloop moet."], "Die afrigter sê dat hulle vinniger moet hardloop.", "'n Bevel word met 'moet' weergegee: 'dat hulle vinniger moet hardloop'.", [E.REPORT], 3),
      ch("G11TAA07.16", "Wat gebeur met die voornaamwoord 'ek' wanneer iemand anders die woorde weergee?", ["dit word 'hy' of 'sy'", "dit bly 'ek'", "dit word 'jy'"], "dit word 'hy' of 'sy'", "Die spreker se 'ek' word 'hy' of 'sy' wanneer iemand anders dit weergee.", [E.REPORT], 1),
      cz("G11TAA07.17", "Vul in: \"Ek bly hier,\" sê sy. → Sy sê dat sy ___ bly.", ["daar", "hier", "nou"], "daar", "'hier' word 'daar'.", [E.REPORT], 2),
      ch("G11TAA07.18", "Kies die korrekte indirekte rede: Pa sê, \"Ek sal jou kom haal.\"", ["Pa sê dat hy my sal kom haal.", "Pa sê dat ek jou sal kom haal.", "Pa sê dat hy my kom haal sal."], "Pa sê dat hy my sal kom haal.", "'Ek' word 'hy', 'jou' word 'my', en die woordorde bly met 'sal ... kom haal'.", [E.REPORT], 3),
      ch("G11TAA07.19", "Kies die korrekte DIREKTE rede: Sy vra waar die stasie is.", ["Sy vra, \"Waar is die stasie?\"", "Sy vra, \"Waar die stasie is?\"", "Sy vra: waar is die stasie."], "Sy vra, \"Waar is die stasie?\"", "Direkte rede gebruik aanhalingstekens en normale vraagorde: \"Waar is die stasie?\"", [E.REPORT], 2),
      ch("G11TAA07.20", "Kies die korrekte indirekte rede vir 'n VRAAG: Hy vra, \"Het jy geld?\"", ["Hy vra of ek geld het.", "Hy vra het jy geld.", "Hy vra dat ek geld het."], "Hy vra of ek geld het.", "'n Ja/nee-vraag word met 'of' weergegee: 'Hy vra of ek geld het.'", [E.REPORT], 3),
    ]),

  ...skill(`${P}.08`, "Bedrywende en lydende vorm oor alle tye",
    "Verander tussen die bedrywende (aktief) en lydende (passief) vorm oor die teenwoordige, verlede en toekomende tyd.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Lydend: die voorwerp word die onderwerp + word (teenwoordig) / is (verlede) / sal ... word (toekomend) + ...ge-werkwoord + (deur die agent).",
    [
      ch("G11TAA08.01", "Kies die korrekte lydende vorm (teenwoordig): 'Die hond jaag die kat.'", ["Die kat word deur die hond gejaag.", "Die kat is deur die hond gejaag.", "Die kat jaag deur die hond."], "Die kat word deur die hond gejaag.", "Teenwoordige tyd lydend gebruik 'word'.", [E.PASSIVE], 2),
      ch("G11TAA08.02", "Kies die korrekte lydende vorm (verlede): 'Die kat het die muis gevang.'", ["Die muis is deur die kat gevang.", "Die muis word deur die kat gevang.", "Die muis was die kat gevang."], "Die muis is deur die kat gevang.", "Verlede tyd lydend gebruik 'is ... gevang'.", [E.PASSIVE], 3),
      ch("G11TAA08.03", "Kies die korrekte lydende vorm (toekomende): 'Die span sal die beker wen.'", ["Die beker sal deur die span gewen word.", "Die beker word deur die span gewen.", "Die beker is deur die span gewen."], "Die beker sal deur die span gewen word.", "Toekomende tyd lydend: 'sal ... gewen word'.", [E.PASSIVE], 3),
      ch("G11TAA08.04", "Kies die korrekte bedrywende vorm: 'Die brood word deur die bakker gebak.'", ["Die bakker bak die brood.", "Die brood bak die bakker.", "Die bakker het die brood gebak."], "Die bakker bak die brood.", "Bedrywend: die doener ('die bakker') word die onderwerp.", [E.PASSIVE], 2),
      cz("G11TAA08.05", "Vul die hulpwerkwoord in (teenwoordig, lydend): 'Die lied ___ deur die koor gesing.'", ["word", "is", "was"], "word", "Teenwoordige tyd lydend gebruik 'word'.", [E.PASSIVE], 1),
      cz("G11TAA08.06", "Vul die hulpwerkwoord in (verlede, lydend): 'Die ruit ___ deur die bal gebreek.'", ["is", "word", "sal"], "is", "Verlede tyd lydend gebruik 'is ... gebreek'.", [E.PASSIVE], 2),
      cz("G11TAA08.07", "Vul in (toekomende, lydend): 'Die paaie ___ volgende jaar herstel ___.'", ["sal ... word", "word ... is", "is ... word"], "sal ... word", "Toekomende lydend: 'sal ... herstel word'.", [E.PASSIVE], 3),
      ch("G11TAA08.08", "Watter sin is in die lydende vorm?", ["Die wedstryd word deur die skeidsregter gefluit.", "Die skeidsregter fluit die wedstryd.", "Die skeidsregter het die wedstryd gefluit."], "Die wedstryd word deur die skeidsregter gefluit.", "Die lydende vorm het 'word ... deur'.", [E.PASSIVE], 1),
      ch("G11TAA08.09", "Watter sin is in die bedrywende vorm?", ["Die leerlinge skryf die eksamen.", "Die eksamen word geskryf.", "Die eksamen is deur die leerlinge geskryf."], "Die leerlinge skryf die eksamen.", "Die bedrywende vorm wys die doener as onderwerp.", [E.PASSIVE], 1),
      ch("G11TAA08.10", "Kies die korrekte lydende vorm (verlede): 'Die man het die brief geskryf.'", ["Die brief is deur die man geskryf.", "Die brief word deur die man geskryf.", "Die brief het die man geskryf."], "Die brief is deur die man geskryf.", "Verlede lydend: 'is ... geskryf'.", [E.PASSIVE], 3),
      cz("G11TAA08.11", "Vul die agent in: 'Die gedig word ___ die digter voorgelees.'", ["deur", "met", "van"], "deur", "Die doener word met 'deur' aangedui: 'deur die digter'.", [E.PASSIVE], 1),
      tf("G11TAA08.12", "In die lydende vorm word die voorwerp die onderwerp van die sin.", "Waar", "Ja — dit is presies hoe die lydende vorm werk.", [E.PASSIVE], 2),
      ch("G11TAA08.13", "Kies die korrekte lydende vorm (toekomende): 'Die maatskappy sal nuwe werkers aanstel.'", ["Nuwe werkers sal deur die maatskappy aangestel word.", "Nuwe werkers word deur die maatskappy aangestel.", "Nuwe werkers is deur die maatskappy aangestel."], "Nuwe werkers sal deur die maatskappy aangestel word.", "Toekomende lydend: 'sal ... aangestel word'.", [E.PASSIVE], 3),
      ch("G11TAA08.14", "Watter hulpwerkwoord pas by die verlede tyd in die lydende vorm?", ["is", "word", "sal"], "is", "Verlede tyd lydend gebruik 'is'.", [E.PASSIVE], 2),
      ch("G11TAA08.15", "Watter hulpwerkwoorde pas by die toekomende tyd in die lydende vorm?", ["sal ... word", "is ... word", "word ... was"], "sal ... word", "Toekomende tyd lydend gebruik 'sal ... word'.", [E.PASSIVE], 2),
      ch("G11TAA08.16", "Kies die korrekte bedrywende vorm (verlede): 'Die kos is deur Ouma gekook.'", ["Ouma het die kos gekook.", "Ouma kook die kos.", "Die kos het Ouma gekook."], "Ouma het die kos gekook.", "Bedrywend verlede: 'Ouma het die kos gekook.'", [E.PASSIVE], 2),
      cz("G11TAA08.17", "Vul in (teenwoordig, lydend): 'Die nuus ___ deur die aanbieder gelees.'", ["word", "is", "sal"], "word", "Teenwoordig lydend gebruik 'word ... gelees'.", [E.PASSIVE], 2),
      ch("G11TAA08.18", "Kies die korrekte lydende vorm (teenwoordig): 'Die polisie ondersoek die saak.'", ["Die saak word deur die polisie ondersoek.", "Die saak ondersoek die polisie.", "Die saak is deur die polisie ondersoek."], "Die saak word deur die polisie ondersoek.", "Teenwoordig lydend: 'word ... ondersoek'.", [E.PASSIVE], 2),
      tf("G11TAA08.19", "Is 'Die brug sal deur die ingenieurs gebou word' 'n toekomende lydende sin?", "Waar", "Ja — 'sal ... gebou word' met 'deur' is toekomende tyd lydend.", [E.PASSIVE], 2),
      ch("G11TAA08.20", "Kies die korrekte lydende vorm (verlede): 'Die kunstenaar het die muurskildery geskep.'", ["Die muurskildery is deur die kunstenaar geskep.", "Die muurskildery word deur die kunstenaar geskep.", "Die muurskildery het die kunstenaar geskep."], "Die muurskildery is deur die kunstenaar geskep.", "Verlede lydend: 'is ... geskep'.", [E.PASSIVE], 3),
    ]),

  ...skill(`${P}.09`, "Leestekens en punktuasie",
    "Korrekte gebruik van leestekens: komma, punt, vraagteken, dubbelpunt, kommapunt, aanhalingstekens, koppelteken, afkappingsteken, deelteken en gedagtestreep.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Elke teken het 'n taak: ? sluit 'n vraag af, : lei in, ; verbind twee nou sinne, \" \" omraam die presiese woorde, en – ('n gedagtestreep) sonder iets af of dui 'n breuk aan.",
    [
      ch("G11TAA09.01", "Watter leesteken pas die beste: 'Sy het net een doel gehad___ om te wen.'", ["dubbelpunt (:)", "vraagteken (?)", "komma (,)"], "dubbelpunt (:)", "Die dubbelpunt lei die verduideliking in: '...een doel gehad: om te wen.'", [E.PUNCT], 3),
      ch("G11TAA09.02", "Watter leesteken sonder 'n ingevoegde gedagte af: 'Die wenner — en almal het dit geweet — was sy.'?", ["gedagtestreep (–)", "komma (,)", "dubbelpunt (:)"], "gedagtestreep (–)", "Die gedagtestreep (–) sonder 'n ingevoegde gedagte af.", [E.PUNCT], 3),
      ch("G11TAA09.03", "Kies die korrekte direkte rede:", ["Sy roep: \"Pasop!\"", "Sy roep: Pasop!", "Sy roep \"pasop\""], "Sy roep: \"Pasop!\"", "Direkte rede kry 'n dubbelpunt, aanhalingstekens en 'n hoofletter.", [E.PUNCT], 2),
      ch("G11TAA09.04", "Watter leesteken verbind twee nou verwante hoofsinne sonder 'n voegwoord?", ["kommapunt (;)", "komma (,)", "vraagteken (?)"], "kommapunt (;)", "Die kommapunt verbind twee nou verwante hoofsinne: 'Dit reën; ons bly tuis.'", [E.PUNCT], 3),
      ch("G11TAA09.05", "Kies die korrekte gebruik van die afkappingsteken:", ["Dit was in die 1980's.", "Dit was in die 1980s'.", "Dit was in die 1980s."], "Dit was in die 1980's.", "Die afkappingsteken kom voor die meervouds-s: '1980's', 'foto's'.", [E.PUNCT], 3),
      ch("G11TAA09.06", "Watter sin gebruik die komma korrek?", ["Ná die wedstryd, moeg en honger, het ons huis toe gegaan.", "Ná die wedstryd moeg en honger het ons, huis toe gegaan.", "Ná, die wedstryd moeg en honger het ons huis toe gegaan."], "Ná die wedstryd, moeg en honger, het ons huis toe gegaan.", "Die ingevoegde stukkie ('moeg en honger') word met kommas afgesonder.", [E.PUNCT], 3),
      cz("G11TAA09.07", "Vul die regte teken in: 'Sy het drie dinge gekoop___ brood, melk en eiers.'", [":", "?", ","], ":", "Die dubbelpunt lei die lys in: '...gekoop: brood, melk en eiers.'", [E.PUNCT], 2),
      ch("G11TAA09.08", "Watter sin gebruik die koppelteken korrek?", ["die een-en-twintigste verjaardag", "die een en twintigste- verjaardag", "die een–en–twintigste verjaardag"], "die een-en-twintigste verjaardag", "Getalle soos 'een-en-twintigste' kry koppeltekens.", [E.PUNCT], 2),
      ch("G11TAA09.09", "Watter leesteken eindig 'n gewone stelsin?", ["punt (.)", "vraagteken (?)", "dubbelpunt (:)"], "punt (.)", "'n Stelsin eindig met 'n punt.", [E.PUNCT], 1),
      ch("G11TAA09.10", "Kies die korrek geskrewe sin:", ["\"Pasop!\" het sy geskree.", "\"Pasop\"! het sy geskree.", "\"pasop!\" het sy geskree."], "\"Pasop!\" het sy geskree.", "Die uitroepteken staan binne die aanhalingstekens en die eerste woord kry 'n hoofletter.", [E.PUNCT], 3),
      cz("G11TAA09.11", "Vul die teken in: 'My gunsteling vakke is wiskunde___ wetenskap en kuns.'", [",", ":", ";"], ",", "Items in 'n lys word met kommas geskei.", [E.PUNCT], 1),
      tf("G11TAA09.12", "'n Gedagtestreep (–) kan gebruik word om 'n skielike breuk of 'n ingevoegde gedagte aan te dui.", "Waar", "Ja — die gedagtestreep dui 'n breuk of 'n ingevoegde gedagte aan.", [E.PUNCT], 2),
      ch("G11TAA09.13", "Watter sin gebruik die besitsvorm korrek?", ["Dit is die maatskappy se beleid.", "Dit is die maatskappy's beleid.", "Dit is die maatskappys beleid."], "Dit is die maatskappy se beleid.", "Afrikaans gebruik 'se' vir besit: 'die maatskappy se beleid'.", [E.PUNCT], 2),
      ch("G11TAA09.14", "Watter leesteken pas: 'Daar was net een probleem___ daar was geen geld nie.'", [": ", "; ", ". "], ": ", "Die dubbelpunt lei die verduideliking in.", [E.PUNCT], 3),
      ch("G11TAA09.15", "Kies die korrekte gebruik van aanhalingstekens vir 'n titel:", ["Ons lees die gedig \"Winternag\".", "Ons lees die gedig Winternag\".", "Ons lees die gedig \"Winternag."], "Ons lees die gedig \"Winternag\".", "'n Titel word tussen aanhalingstekens geplaas — oop en toe.", [E.PUNCT], 2),
      cz("G11TAA09.16", "Vul die teken in: 'Het jy al klaar gewerk___'", ["?", "!", "."], "?", "Dit is 'n vraag, dus 'n vraagteken.", [E.PUNCT], 1),
      ch("G11TAA09.17", "Watter sin gebruik die deelteken korrek?", ["Hy het die reëls oortree.", "Hy het die reels oortree.", "Hy het die re-els oortree."], "Hy het die reëls oortree.", "Die deelteken (ë) wys dat die e apart uitgespreek word: 'reëls'.", [E.PUNCT], 3),
      tf("G11TAA09.18", "'n Komma kan twee onafhanklike hoofsinne sonder 'n voegwoord korrek verbind.", "Onwaar", "Nee — daarvoor gebruik 'n mens 'n kommapunt of 'n voegwoord, nie 'n blote komma nie.", [E.PUNCT], 3),
      ch("G11TAA09.19", "Kies die korrekte sin:", ["\"Wanneer kom jy?\" vra sy.", "\"Wanneer kom jy\"? vra sy.", "\"wanneer kom jy?\" vra sy."], "\"Wanneer kom jy?\" vra sy.", "Die vraagteken staan binne die aanhalingstekens en die sin begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G11TAA09.20", "Watter teken gebruik jy om 'n woorddeel soos 'see-eend' te verbind (en botsing van klinkers te keer)?", ["koppelteken (-)", "komma (,)", "dubbelpunt (:)"], "koppelteken (-)", "Die koppelteken verbind woorddele en keer botsende klinkers: 'see-eend'.", [E.PUNCT], 2),
    ]),

  ...skill(`${P}.10`, "Betekenisleer: sinonieme, antonieme, homofone, polisemie",
    "Sinonieme, antonieme, homofone (ly/lei), homonieme, paronieme en polisemie (een woord met verskeie verwante betekenisse).",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "Sinoniem = dieselfde betekenis, antoniem = teenoorgesteld; homofone klink dieselfde maar verskil in spelling; polisemie is EEN woord met verskeie verwante betekenisse (kop = liggaamsdeel, bergtop, beker).",
    [
      ch("G11TAA10.01", "Watter woord is 'n sinoniem vir 'dapper'?", ["moedig", "bang", "lui"], "moedig", "'dapper' en 'moedig' beteken dieselfde — sinonieme.", [E.SEM], 1),
      ch("G11TAA10.02", "Wat is die teenoorgestelde (antoniem) van 'oorwinning'?", ["nederlaag", "wedstryd", "span"], "nederlaag", "Die antoniem van 'oorwinning' is 'nederlaag'.", [E.SEM], 2),
      ch("G11TAA10.03", "POLISEMIE: 'die kop van die berg' gebruik 'kop' in watter sin?", ["Die boonste/hoogste deel", "'n Liggaamsdeel", "'n Beker"], "Die boonste/hoogste deel", "'kop' het verwante betekenisse; hier beteken dit die boonste deel van die berg.", [E.POLY], 3),
      ch("G11TAA10.04", "POLISEMIE: 'die voet van die berg' gebruik 'voet' in watter sin?", ["Die onderste deel", "'n Liggaamsdeel", "'n Maateenheid"], "Die onderste deel", "'voet' het verwante betekenisse; hier beteken dit die onderste deel van die berg.", [E.POLY], 3),
      ch("G11TAA10.05", "Wat is 'polisemie'?", ["Een woord met verskeie verwante betekenisse", "Twee woorde wat dieselfde klink", "Twee teenoorgestelde woorde"], "Een woord met verskeie verwante betekenisse", "Polisemie is een woord met verskeie verwante betekenisse.", [E.POLY], 2),
      cz("G11TAA10.06", "Kies die korrekte homofoon: 'Sy ___ swaar onder die siekte.' (om te swaarkry)", ["ly", "lei", "lê"], "ly", "'ly' beteken om te swaarkry; 'lei' beteken om voor te loop.", [E.HOMO], 3),
      cz("G11TAA10.07", "Kies die korrekte homofoon: 'Die paadjie ___ na die rivier.' (om te wys/loop na)", ["lei", "ly", "lê"], "lei", "'lei' beteken om te lei/loop na 'n plek.", [E.HOMO], 3),
      ch("G11TAA10.08", "POLISEMIE: 'die blad van die boek' teenoor 'die blad van die boom' — wat wys dit?", ["Een woord ('blad') met verwante betekenisse", "Twee teenoorgestelde woorde", "Twee woorde wat dieselfde klink maar niks in gemeen het nie"], "Een woord ('blad') met verwante betekenisse", "'blad' (bladsy / boomblaar / skouerblad) is een woord met verwante betekenisse — polisemie.", [E.POLY], 3),
      ch("G11TAA10.09", "Watter woord is 'n sinoniem vir 'moeilik'?", ["ingewikkeld", "maklik", "lig"], "ingewikkeld", "'moeilik' en 'ingewikkeld' is sinonieme.", [E.SEM], 2),
      ch("G11TAA10.10", "Wat is die teenoorgestelde van 'tydelik'?", ["permanent", "vinnig", "kort"], "permanent", "Die antoniem van 'tydelik' is 'permanent'.", [E.SEM], 2),
      ch("G11TAA10.11", "Wat is die teenoorgestelde van 'meerderheid'?", ["minderheid", "groep", "almal"], "minderheid", "Die antoniem van 'meerderheid' is 'minderheid'.", [E.SEM], 2),
      ch("G11TAA10.12", "Watter woord is 'n sinoniem vir 'belangrik'?", ["gewigtig", "gering", "klein"], "gewigtig", "'belangrik' en 'gewigtig' beteken dieselfde.", [E.SEM], 2),
      cz("G11TAA10.13", "Kies die korrekte woord (paronieme): 'Die dokter het die ___ ondersoek.' (pasiënt, nie 'passaat' nie)", ["pasiënt", "passiënt", "pasient"], "pasiënt", "'pasiënt' is die korrekte spelling vir die persoon by die dokter.", [E.SPELL], 3),
      ch("G11TAA10.14", "POLISEMIE: 'die oog van die naald' gebruik 'oog' in watter sin?", ["Die gaatjie waardeur die garing gaan", "'n Liggaamsdeel", "'n Storm se middel"], "Die gaatjie waardeur die garing gaan", "'oog' het verwante betekenisse; by 'n naald is dit die gaatjie vir die garing.", [E.POLY], 3),
      ch("G11TAA10.15", "Wat is die teenoorgestelde van 'toelaat'?", ["verbied", "gee", "open"], "verbied", "Die antoniem van 'toelaat' is 'verbied'.", [E.SEM], 2),
      ch("G11TAA10.16", "Watter woord is 'n sinoniem vir 'gelukkig'?", ["tevrede", "hartseer", "kwaad"], "tevrede", "'gelukkig' en 'tevrede' lê naby mekaar — sinonieme.", [E.SEM], 2),
      tf("G11TAA10.17", "By polisemie het een woord verskeie betekenisse wat met mekaar verband hou.", "Waar", "Ja — die betekenisse van 'n polisemiese woord is verwant.", [E.POLY], 2),
      cz("G11TAA10.18", "Kies die korrekte homofoon: 'Hy het 'n nuwe ___ gekoop.' (kledingstuk, nie 'pak slae' nie)", ["pak", "bak", "tak"], "pak", "''n pak' kan 'n kledingstuk wees; let op die betekenis in die sin.", [E.HOMO], 2),
      ch("G11TAA10.19", "Watter woord is 'n sinoniem vir 'vinnig'?", ["rats", "stadig", "swaar"], "rats", "'vinnig' en 'rats' beteken min of meer dieselfde.", [E.SEM], 2),
      ch("G11TAA10.20", "Wat is die teenoorgestelde van 'oorvloed'?", ["tekort", "baie", "genoeg"], "tekort", "Die antoniem van 'oorvloed' is 'tekort'.", [E.SEM], 2),
    ]),

  ...skill(`${P}.11`, "Idiome en spreekwoorde",
    "Verstaan 'n wyer stel Afrikaanse idiome, idiomatiese uitdrukkings en spreekwoorde volgens hul figuurlike betekenis.",
    "Taalstrukture", "T4", ["choice", "cloze", "true-false"],
    "Stel jou voor wat die woorde letterlik sê, en vra dan wat mense regtig daarmee bedoel; leer idiome as geheel, nie woord-vir-woord nie.",
    [
      ch("G11TAA11.01", "Wat beteken 'om die kop in die nek te gooi'?", ["om uitdagend of opstandig te wees", "om te slaap", "om te val"], "om uitdagend of opstandig te wees", "'om die kop in die nek te gooi' beteken om trots, uitdagend of opstandig op te tree.", [E.IDIOM], 3),
      ch("G11TAA11.02", "Wat beteken 'om 'n appeltjie met iemand te skil'?", ["om 'n geskil met iemand uit te praat", "om kos te maak", "om vrugte te eet"], "om 'n geskil met iemand uit te praat", "Dit beteken om 'n meningsverskil met iemand reguit te bespreek.", [E.IDIOM], 3),
      ch("G11TAA11.03", "Wat beteken 'om iets onder die knie te kry'?", ["om iets goed te bemeester", "om te val", "om te buig"], "om iets goed te bemeester", "Dit beteken om iets goed te leer of te bemeester.", [E.IDIOM], 2),
      ch("G11TAA11.04", "Wat beteken die spreekwoord 'Sagte heelmeesters maak stinkende wonde'?", ["Te toegeeflik wees maak die probleem erger", "Sagte mense is wreed", "Wonde ruik sleg"], "Te toegeeflik wees maak die probleem erger", "Dit beteken dat te sag of toegeeflik optree 'n probleem laat vererger.", [E.IDIOM], 3),
      ch("G11TAA11.05", "Wat beteken 'om met vuur te speel'?", ["om iets gevaarliks of riskant te doen", "om kos te braai", "om warm te kry"], "om iets gevaarliks of riskant te doen", "Dit beteken om jou aan gevaar of risiko bloot te stel.", [E.IDIOM], 2),
      ch("G11TAA11.06", "Wat beteken die spreekwoord 'Al dra 'n aap 'n goue ring, hy is en bly 'n lelike ding'?", ["Uiterlike versiering verander nie iemand se ware aard nie", "Ape hou van ringe", "Goud is lelik"], "Uiterlike versiering verander nie iemand se ware aard nie", "Dit beteken mooi versiering verander nie 'n mens se ware aard nie.", [E.IDIOM], 3),
      ch("G11TAA11.07", "Wat beteken die spreekwoord 'Stille waters, diepe grond'?", ["'n Stil mens kan baie meer wees as wat dit lyk", "Water is altyd diep", "Stilte is gevaarlik"], "'n Stil mens kan baie meer wees as wat dit lyk", "Dit beteken 'n stil persoon het dikwels verborge dieptes.", [E.IDIOM], 3),
      ch("G11TAA11.08", "Wat beteken 'om jou hande in onskuld te was'?", ["om te ontken dat jy enige skuld het", "om jou hande te was", "om skoon te maak"], "om te ontken dat jy enige skuld het", "Dit beteken om alle verantwoordelikheid of skuld te ontken.", [E.IDIOM], 3),
      ch("G11TAA11.09", "Wat beteken 'om die spit af te byt'?", ["om die swaarste deel eerste te verduur", "om te eet", "om te baklei"], "om die swaarste deel eerste te verduur", "Dit beteken om die moeilikste of eerste, swaarste deel te dra.", [E.IDIOM], 3),
      ch("G11TAA11.10", "Wat beteken 'om jou ore te spits'?", ["om aandagtig te luister", "om te slaap", "om weg te hardloop"], "om aandagtig te luister", "Dit beteken om skerp en aandagtig te luister.", [E.IDIOM], 2),
      cz("G11TAA11.11", "Voltooi die spreekwoord: 'Aanhouer ___.'", ["wen", "verloor", "val"], "wen", "'Aanhouer wen' — volharding lei tot sukses.", [E.IDIOM], 2),
      cz("G11TAA11.12", "Voltooi die spreekwoord: 'Daar is meer as een manier om 'n ___ te vil.'", ["kat", "hond", "skaap"], "kat", "'Daar is meer as een manier om 'n kat te vil' — daar is verskeie maniere om iets te doen.", [E.IDIOM], 2),
      ch("G11TAA11.13", "Wat beteken 'om iemand om die bos te lei'?", ["om iemand te mislei of te bedrieg", "om in die bos te loop", "om te help"], "om iemand te mislei of te bedrieg", "Dit beteken om iemand te kul of te bedrieg.", [E.IDIOM], 2),
      ch("G11TAA11.14", "Wat beteken 'om kop in een mus te wees'?", ["om dit heeltemal met mekaar eens te wees", "om 'n mus te dra", "om koud te kry"], "om dit heeltemal met mekaar eens te wees", "Dit beteken om volkome saam te stem of saam te span.", [E.IDIOM], 3),
      ch("G11TAA11.15", "Wat beteken die spreekwoord 'Hoë bome vang baie wind'?", ["Mense in hoë posisies kry meer kritiek", "Bome is gevaarlik", "Wind is sterk"], "Mense in hoë posisies kry meer kritiek", "Dit beteken prominente mense trek meer kritiek en aandag.", [E.IDIOM], 3),
      ch("G11TAA11.16", "Wat beteken 'om die handdoek in te gooi'?", ["om op te gee", "om te was", "om te swem"], "om op te gee", "Dit beteken om tou op te gooi of op te gee.", [E.IDIOM], 2),
      tf("G11TAA11.17", "Beteken 'om van 'n muggie 'n olifant te maak' dat 'n mens iets klein erg oordryf?", "Waar", "Ja — dit beteken om iets onbenulligs erg te oordryf.", [E.IDIOM], 3),
      ch("G11TAA11.18", "Wat beteken 'om jou skepe agter jou te verbrand'?", ["om jouself sonder 'n uitweg te laat", "om te kook", "om te seil"], "om jouself sonder 'n uitweg te laat", "Dit beteken om jou só te verbind dat daar geen pad terug is nie.", [E.IDIOM], 3),
      cz("G11TAA11.19", "Voltooi die idioom: 'Hy het die ___ in die kruitvat gesteek.' (groot moeilikheid begin)", ["lont", "vuur", "kers"], "lont", "'die lont in die kruitvat steek' — iets doen wat groot moeilikheid laat losbars.", [E.IDIOM], 3),
      ch("G11TAA11.20", "Wat beteken die spreekwoord 'Een swael maak nie 'n somer nie'?", ["Een teken is nie genoeg om seker te wees nie", "Voëls bring die somer", "Somers is kort"], "Een teken is nie genoeg om seker te wees nie", "Dit beteken een enkele aanduiding bewys nog nie 'n hele patroon nie.", [E.IDIOM], 3),
    ]),

  ...skill(`${P}.12`, "Woordvorming en spelling: afleiding, samestelling, samestellende afleiding, akronieme",
    "Bou en spel woorde met voor- en agtervoegsels (afleiding), saamgestelde woorde (samestelling), samestellende afleiding, en hanteer afkortings, akronieme en spelpatrone.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Afrikaans skryf die meeste saamgestelde woorde as EEN woord; 'n afleiding voeg 'n voorvoegsel/agtervoegsel by; 'n samestellende afleiding stel saam én lei tegelyk af (driewieler); 'n akroniem word as 'n woord gelees.",
    [
      ch("G11TAA12.01", "Watter woord is 'n SAMESTELLENDE AFLEIDING?", ["driewieler", "tafeldoek", "onbekend"], "driewieler", "'driewieler' (drie + wiel + -er) stel saam én lei tegelyk af — 'n samestellende afleiding.", [E.WORDFORM], 3),
      ch("G11TAA12.02", "Watter woord is 'n samestellende afleiding?", ["viervoeter", "seewater", "onveilig"], "viervoeter", "'viervoeter' (vier + voet + -er) stel saam én lei af — 'n samestellende afleiding.", [E.WORDFORM], 3),
      ch("G11TAA12.03", "Watter woord is 'n SAMESTELLING (twee stamme saam)?", ["sonsondergang", "werkloos", "ongeluk"], "sonsondergang", "'sonsondergang' kombineer stamme — 'n samestelling.", [E.WORDFORM], 2),
      ch("G11TAA12.04", "Watter woord is 'n AFLEIDING (stam + voor-/agtervoegsel)?", ["vriendelik", "tafellap", "boomhuis"], "vriendelik", "'vriendelik' is 'vriend' + '-lik' — 'n afleiding.", [E.WORDFORM], 2),
      ch("G11TAA12.05", "Watter een is 'n AKRONIEM (gelees as 'n woord)?", ["VIGS", "byvoorbeeld", "tafeldoek"], "VIGS", "'VIGS' word as 'n woord uitgespreek — 'n akroniem.", [E.SPELL], 2),
      ch("G11TAA12.06", "Waarvoor staan die afkorting 'a.g.v.'?", ["as gevolg van", "agter geveg van", "almal gaan voor"], "as gevolg van", "'a.g.v.' staan vir 'as gevolg van'.", [E.SPELL], 2),
      ch("G11TAA12.07", "Waarvoor staan die afkorting 't.o.v.'?", ["ten opsigte van", "tot oor van", "te vinde op"], "ten opsigte van", "'t.o.v.' staan vir 'ten opsigte van'.", [E.SPELL], 2),
      cz("G11TAA12.08", "Voeg '-baar' by 'breek': ___ (kan gebreek word)", ["breekbaar", "brekebaar", "breek baar"], "breekbaar", "'-baar' beteken 'kan ge...word': 'breekbaar'.", [E.WORDFORM], 2),
      cz("G11TAA12.09", "Voeg 'wan-' by 'begrip': ___ (verkeerde begrip)", ["wanbegrip", "wan begrip", "wanbegrippe"], "wanbegrip", "Die voorvoegsel 'wan-' dui 'n verkeerde/foutiewe toestand aan: 'wanbegrip'.", [E.WORDFORM], 2),
      ch("G11TAA12.10", "Hoe skryf 'n mens 'lugreis' korrek?", ["lugreis", "lug reis", "lug-reis"], "lugreis", "Saamgestelde woorde word as een woord geskryf: 'lugreis'.", [E.WORDFORM], 1),
      ch("G11TAA12.11", "Wat is die verskil tussen 'n samestelling en 'n afleiding?", ["'n Samestelling voeg stamme saam; 'n afleiding voeg 'n voor-/agtervoegsel by", "Hulle is presies dieselfde", "'n Afleiding is altyd twee woorde"], "'n Samestelling voeg stamme saam; 'n afleiding voeg 'n voor-/agtervoegsel by", "Samestelling = stam + stam; afleiding = stam + affiks.", [E.WORDFORM], 3),
      ch("G11TAA12.12", "Watter woord is 'n samestellende afleiding?", ["tweedehands", "sokkerveld", "ongeskik"], "tweedehands", "'tweedehands' (twee + hand + -s) stel saam én lei af.", [E.WORDFORM], 3),
      ch("G11TAA12.13", "Watter woord is korrek gespel?", ["aktiwiteit", "aktiviteit", "aktivteit"], "aktiwiteit", "Die korrekte spelling is 'aktiwiteit'.", [E.SPELL], 3),
      ch("G11TAA12.14", "Watter woord is korrek gespel?", ["geleentheid", "geleentheit", "gelentheid"], "geleentheid", "Die korrekte spelling is 'geleentheid'.", [E.SPELL], 2),
      cz("G11TAA12.15", "Voeg '-heid' by 'eerlik': ___", ["eerlikheid", "eerlik heid", "eerliksheid"], "eerlikheid", "'-heid' maak 'n abstrakte naamwoord: 'eerlikheid'.", [E.WORDFORM], 2),
      ch("G11TAA12.16", "Waarvoor staan die akroniem 'SAUK'?", ["Suid-Afrikaanse Uitsaaikorporasie", "Suid-Afrika Universiteit Kollege", "Sentrale Afrika Uniale Kongres"], "Suid-Afrikaanse Uitsaaikorporasie", "'SAUK' staan vir die Suid-Afrikaanse Uitsaaikorporasie.", [E.SPELL], 3),
      ch("G11TAA12.17", "Hoe skryf 'n mens 'hoërskoolleerder' se dele saam?", ["hoërskoolleerder", "hoër skool leerder", "hoër-skool-leerder"], "hoërskoolleerder", "Die samestelling word as een woord geskryf: 'hoërskoolleerder'.", [E.WORDFORM], 2),
      tf("G11TAA12.18", "'n Akroniem word as 'n woord uitgespreek, terwyl 'n gewone afkorting letter-vir-letter gelees word.", "Waar", "Ja — 'n akroniem (VIGS) word as 'n woord gelees; 'n afkorting (bv.) nie.", [E.SPELL], 2),
      ch("G11TAA12.19", "Watter woord is korrek gespel?", ["onmiddellik", "onmidellik", "onmiddelik"], "onmiddellik", "Die korrekte spelling is 'onmiddellik'.", [E.SPELL], 3),
      cz("G11TAA12.20", "Voeg 'her-' by 'bou': ___ (om weer te bou)", ["herbou", "her bou", "herboue"], "herbou", "'her-' beteken 'weer': 'herbou'.", [E.WORDFORM], 2),
    ]),
};

insertSkills(skills);
