// Grade 11 — Taalstrukture tier, skills TAA.01–TAA.06 (20 items each). Afrikaans-only.
// Deepens Grade 10: noun extensions (versamelname/abstrakte/dubbele meervoude); pronoun
// extensions (betreklik/onbepaald/wederkerend); adjectives & comparison; verbs + deelwoorde
// + infinitief; conjunctions & word order; sentence analysis (sinsdele) + types + negation.
import { ch, tf, cz, skill, insertSkills } from "./_g11_bank_lib.mjs";

const P = "AF.G11.TAA";
const E = {
  PLURAL: "ERR_AF_PLURAL", DIM: "ERR_AF_DIMINUTIVE", NOUNTYPE: "ERR_AF_NOUNTYPE",
  PRON: "ERR_AF_PRONOUN", ADJ: "ERR_AF_ADJECTIVE", COMP: "ERR_AF_COMPARISON",
  TENSE: "ERR_AF_TENSE", VERB: "ERR_AF_VERB", PART: "ERR_AF_PARTICIPLE", INF: "ERR_AF_INFINITIVE",
  CONJ: "ERR_AF_CONJUNCTION", ORDER: "ERR_AF_WORDORDER",
  SINSDEEL: "ERR_AF_SINSDEEL", SENT: "ERR_AF_SENTENCETYPE", NEG: "ERR_AF_NEGATION", GRAM: "ERR_AF_GRAMMAR",
};

const skills = {
  ...skill(`${P}.01`, "Selfstandige naamwoorde: meervoud, verkleining, geslag, versamelname",
    "Meervoude (ook dubbele meervoude), verkleinings en geslagsvorme, plus versamelname en abstrakte naamwoorde.",
    "Taalstrukture", "T1-T4", ["choice", "cloze", "true-false"],
    "Meervoude volg patrone (-e, -s, -ers, met deelteken/kappie waar nodig); 'n versamelnaam noem 'n groep as een; 'n abstrakte naamwoord noem iets wat jy nie kan aanraak nie.",
    [
      ch("G11TAA01.01", "Wat is die meervoud van 'blad'?", ["blaaie", "blads", "blade"], "blaaie", "Die meervoud van 'blad' is 'blaaie'.", [E.PLURAL], 2),
      ch("G11TAA01.02", "Wat is die meervoud van 'stad'?", ["stede", "stads", "stadde"], "stede", "Die meervoud van 'stad' is 'stede' (klankverandering).", [E.PLURAL], 2),
      ch("G11TAA01.03", "Wat is die meervoud van 'gas' (besoeker)?", ["gaste", "gasse", "gase"], "gaste", "Die meervoud van 'gas' (besoeker) is 'gaste'.", [E.PLURAL], 2),
      ch("G11TAA01.04", "Watter een is 'n DUBBELE meervoud?", ["kinders (kind + er + s)", "boeke", "tafels"], "kinders (kind + er + s)", "'kinders' dra twee meervoudsmerkers (-er en -s) — 'n dubbele meervoud.", [E.PLURAL], 3),
      ch("G11TAA01.05", "Wat is die meervoud van 'lied'?", ["liedere", "liede", "lieds"], "liedere", "Die meervoud van 'lied' is 'liedere' — 'n dubbele meervoud (-er + -e).", [E.PLURAL], 3),
      ch("G11TAA01.06", "Wat is die meervoud van 'lam'?", ["lammers", "lamme", "lams"], "lammers", "Die meervoud van 'lam' is 'lammers' — 'n dubbele meervoud.", [E.PLURAL], 3),
      ch("G11TAA01.07", "Wat is die meervoud van 'museum'?", ["museums", "musea", "museume"], "museums", "Die gewone meervoud van 'museum' is 'museums'.", [E.PLURAL], 2),
      ch("G11TAA01.08", "Wat is die verkleining van 'tafel'?", ["tafeltjie", "tafeltije", "tafelpie"], "tafeltjie", "Die verkleining van 'tafel' is 'tafeltjie'.", [E.DIM], 2),
      ch("G11TAA01.09", "Wat is die verkleining van 'koning'?", ["koninkie", "koningtjie", "koningie"], "koninkie", "Die verkleining van 'koning' is 'koninkie' (die g word k).", [E.DIM], 3),
      ch("G11TAA01.10", "Watter een is 'n VERSAMELNAAM?", ["'n trop skape", "'n groot skaap", "die wol"], "'n trop skape", "'trop' noem 'n groep skape as een geheel — 'n versamelnaam.", [E.NOUNTYPE], 1),
      ch("G11TAA01.11", "Watter versamelnaam pas by 'druiwe'?", ["'n tros", "'n trop", "'n swerm"], "'n tros", "'n Mens praat van 'n 'tros druiwe'.", [E.NOUNTYPE], 2),
      ch("G11TAA01.12", "Watter versamelnaam pas by 'voëls' (wat saam vlieg)?", ["'n vlug", "'n kudde", "'n bos"], "'n vlug", "'n Mens praat van 'n 'vlug voëls'.", [E.NOUNTYPE], 2),
      ch("G11TAA01.13", "Watter versamelnaam pas by 'beeste'?", ["'n kudde", "'n swerm", "'n tros"], "'n kudde", "'n Mens praat van 'n 'kudde beeste'.", [E.NOUNTYPE], 2),
      ch("G11TAA01.14", "Watter woord is 'n ABSTRAKTE naamwoord?", ["vryheid", "tafel", "hond"], "vryheid", "'vryheid' noem iets wat jy nie kan aanraak nie — 'n abstrakte naamwoord.", [E.NOUNTYPE], 2),
      ch("G11TAA01.15", "Watter woord is 'n ABSTRAKTE naamwoord?", ["eerlikheid", "boom", "skoen"], "eerlikheid", "'eerlikheid' is iets wat 'n mens nie kan aanraak nie — abstrak.", [E.NOUNTYPE], 2),
      tf("G11TAA01.16", "Is 'liefde' 'n abstrakte naamwoord?", "Waar", "Ja — 'liefde' kan nie aangeraak word nie en is dus abstrak.", [E.NOUNTYPE], 1),
      ch("G11TAA01.17", "Wat is die vroulike vorm van 'hings'?", ["merrie", "vul", "perd"], "merrie", "Die vroulike vorm van 'hings' is 'merrie'.", [E.GRAM], 2),
      cz("G11TAA01.18", "Vul die meervoud in: 'Daar is baie ___ in die land.' (stad)", ["stede", "stad", "stads"], "stede", "Die meervoud van 'stad' is 'stede'.", [E.PLURAL], 2),
      cz("G11TAA01.19", "Vul die versamelnaam in: ''n ___ bye het om die korf gevlieg.'", ["swerm", "kudde", "tros"], "swerm", "'n Mens praat van 'n 'swerm bye'.", [E.NOUNTYPE], 2),
      ch("G11TAA01.20", "Wat is die meervoud van 'kalf'?", ["kalwers", "kalfs", "kalwe"], "kalwers", "Die meervoud van 'kalf' is 'kalwers' (die f word w) — 'n dubbele meervoud.", [E.PLURAL], 3),
    ]),

  ...skill(`${P}.02`, "Voornaamwoorde: betreklik, onbepaald, wederkerend",
    "Persoonlike, besitlike, aanwysende, betreklike, onbepaalde en wederkerende/wederkerige voornaamwoorde.",
    "Taalstrukture", "T3", ["choice", "cloze"],
    "Kies die voornaamwoord volgens sy werk: wie doen (persoonlik), wie s'n (besitlik), verbind (betreklik: wat/wie se), onbepaald (iemand/niemand), of terug na die onderwerp (wederkerend: homself / wederkerig: mekaar).",
    [
      ch("G11TAA02.01", "Kies die korrekte betreklike voornaamwoord: 'Die vrou ___ kar gesteel is, is ontsteld.'", ["wie se", "wat se", "wat"], "wie se", "By besit gebruik ons 'wie se': 'die vrou wie se kar'.", [E.PRON], 3),
      ch("G11TAA02.02", "Kies die korrekte betreklike voornaamwoord: 'Die boek ___ op die rak staan, is nuut.'", ["wat", "wie", "wie se"], "wat", "'wat' verbind die bysin met die naamwoord 'boek'.", [E.PRON], 2),
      ch("G11TAA02.03", "Kies die korrekte vorm: 'Die pen ___ ek skryf, is leeg.'", ["waarmee", "wat", "waarin"], "waarmee", "'waarmee' = met wat; jy skryf mét die pen.", [E.PRON], 3),
      ch("G11TAA02.04", "Kies die korrekte vorm: 'Die huis ___ ek woon, is groot.'", ["waarin", "waarmee", "wat se"], "waarin", "'waarin' = in wat; jy woon ín die huis.", [E.PRON], 3),
      ch("G11TAA02.05", "Watter woord is 'n ONBEPAALDE voornaamwoord?", ["iemand", "hierdie", "myne"], "iemand", "'iemand' verwys na 'n onbepaalde persoon — 'n onbepaalde voornaamwoord.", [E.PRON], 2),
      ch("G11TAA02.06", "Watter woord is 'n ONBEPAALDE voornaamwoord?", ["niks", "hierdie", "hy"], "niks", "'niks' is onbepaald — dit dui geen bepaalde ding aan nie.", [E.PRON], 2),
      cz("G11TAA02.07", "Vul die WEDERKERENDE voornaamwoord in: 'Hy het ___ in die spieël gesien.'", ["homself", "hom", "hy"], "homself", "Wederkerend verwys terug na die onderwerp: 'Hy het homself gesien.'", [E.PRON], 2),
      cz("G11TAA02.08", "Vul die WEDERKERIGE voornaamwoord in: 'Die twee spanne respekteer ___.'", ["mekaar", "hulself", "hulle"], "mekaar", "'mekaar' wys hulle doen iets vír mekaar — wederkerig.", [E.PRON], 2),
      ch("G11TAA02.09", "Wat is die verskil tussen 'homself' en 'mekaar'?", ["'homself' verwys terug na een; 'mekaar' wys 'n handeling tussen twee of meer", "Hulle is dieselfde", "'mekaar' is enkelvoud"], "'homself' verwys terug na een; 'mekaar' wys 'n handeling tussen twee of meer", "Wederkerend (homself) = terug na die onderwerp; wederkerig (mekaar) = tussen twee/meer.", [E.PRON], 3),
      cz("G11TAA02.10", "Vul in: 'Hierdie tas is joune; daardie een is ___.' (behoort aan my)", ["myne", "my", "ek"], "myne", "Aan die einde gebruik ons 'myne'.", [E.PRON], 2),
      cz("G11TAA02.11", "Vul die onbepaalde voornaamwoord in: '___ het die werk gedoen, want die kamer was leeg.'", ["Niemand", "Iemand", "Hy"], "Niemand", "Die leë kamer wys 'niemand' het dit gedoen — onbepaald.", [E.PRON], 2),
      ch("G11TAA02.12", "Kies die korrekte sin (wederkerend):", ["Sy het haarself gewas.", "Sy het haar gewas self.", "Sy het self haar gewas haarself."], "Sy het haarself gewas.", "Die wederkerende vorm is 'haarself': 'Sy het haarself gewas.'", [E.PRON], 2),
      ch("G11TAA02.13", "Watter woord is 'n BETREKLIKE voornaamwoord?", ["wat", "iemand", "hierdie"], "wat", "'wat' verbind 'n bysin met 'n naamwoord — 'n betreklike voornaamwoord.", [E.PRON], 1),
      ch("G11TAA02.14", "Kies die korrekte vorm: 'Die man ___ daar staan, is my oom.'", ["wat", "wie se", "waarmee"], "wat", "'wat' verbind die bysin met 'man'.", [E.PRON], 2),
      cz("G11TAA02.15", "Vul die onbepaalde voornaamwoord in: 'Is daar ___ in die boks? Dit voel leeg.'", ["iets", "niks", "alles"], "iets", "Die vraag soek of daar 'iets' is — onbepaald.", [E.PRON], 2),
      ch("G11TAA02.16", "Watter sin gebruik 'wederkerig' korrek?", ["Die vriende help mekaar.", "Die vriende help homself.", "Die vriend help mekaar."], "Die vriende help mekaar.", "'mekaar' pas by twee of meer wat iets vir mekaar doen.", [E.PRON], 2),
      cz("G11TAA02.17", "Vul in: 'Ek het myself seergemaak,' en 'Sy het ___ seergemaak.'", ["haarself", "haar", "sy"], "haarself", "Die wederkerende vorm vir 'sy' is 'haarself'.", [E.PRON], 2),
      cz("G11TAA02.18", "Vul die aanwysende voornaamwoord in: '___ boek hier is nuut, maar daardie een daar is oud.'", ["Hierdie", "Daardie", "Daar"], "Hierdie", "'Hierdie' wys na iets naby; 'daardie' na iets ver.", [E.PRON], 2),
      ch("G11TAA02.19", "Kies die korrekte sin:", ["Almal moet hul eie pen bring.", "Almal moet sy eie pen bring nie.", "Almal moet hulself pen bring."], "Almal moet hul eie pen bring.", "'Almal' word met 'hul eie' opgevolg.", [E.PRON], 3),
      cz("G11TAA02.20", "Vul die betreklike voornaamwoord in: 'Die fiets ___ ek gery het, is gebreek.'", ["wat", "wie", "wie se"], "wat", "'wat' verbind die bysin met 'fiets'.", [E.PRON], 2),
    ]),

  ...skill(`${P}.03`, "Byvoeglike naamwoorde en trappe van vergelyking",
    "Attributiewe en predikatiewe byvoeglike naamwoorde, verbuiging, en die trappe van vergelyking insluitend onreëlmatiges.",
    "Taalstrukture", "T1", ["choice", "cloze", "true-false"],
    "Die vergrotende trap kry meestal -er en die oortreffende -ste; leer die onreëlmatiges (goed-beter-beste, baie-meer-meeste, min-minder-minste, naby-nader-naaste, graag-liewer-liefste).",
    [
      ch("G11TAA03.01", "Vergrotende trap: 'graag → ___ → liefste'", ["liewer", "graer", "meer graag"], "liewer", "'graag' is onreëlmatig: graag → liewer → liefste.", [E.COMP], 3),
      ch("G11TAA03.02", "Oortreffende trap: 'naby → nader → ___'", ["naaste", "nabyste", "naderste"], "naaste", "'naby' is onreëlmatig: naby → nader → naaste.", [E.COMP], 2),
      ch("G11TAA03.03", "Vergrotende trap: 'goed → ___ → beste'", ["beter", "gooier", "meer goed"], "beter", "'goed' is onreëlmatig: goed → beter → beste.", [E.COMP], 2),
      ch("G11TAA03.04", "Oortreffende trap: 'baie → meer → ___'", ["meeste", "baiede", "meerste"], "meeste", "'baie' is onreëlmatig: baie → meer → meeste.", [E.COMP], 2),
      ch("G11TAA03.05", "Oortreffende trap: 'min → minder → ___'", ["minste", "minnerste", "mees min"], "minste", "'min' word: min → minder → minste.", [E.COMP], 2),
      ch("G11TAA03.06", "Vergrotende trap: 'oud → ___ → oudste'", ["ouer", "ouder", "meer oud"], "ouer", "Die vergrotende trap van 'oud' is 'ouer'.", [E.COMP], 2),
      cz("G11TAA03.07", "Vul die oortreffende trap in: 'Van al die leerlinge werk sy die ___.' (hard)", ["hardste", "harder", "mees hard"], "hardste", "By die meeste van almal gebruik ons 'hardste'.", [E.COMP], 2),
      cz("G11TAA03.08", "Vul in: 'Jan is ___ as Piet, maar Sipho is die ___.' (goed)", ["beter ... beste", "beste ... beter", "goeie ... beter"], "beter ... beste", "Tussen twee: 'beter'; van almal: 'beste'.", [E.COMP], 3),
      ch("G11TAA03.09", "Kies die korrekte attributiewe vorm: 'die ___ weer' (sleg)", ["slegte", "sleg", "slegter"], "slegte", "Voor 'n naamwoord verbuig 'sleg' na 'slegte': 'die slegte weer'.", [E.ADJ], 3),
      ch("G11TAA03.10", "Kies die korrekte attributiewe vorm: 'die ___ gebou' (hoog)", ["hoë", "hoog", "hoër"], "hoë", "'hoog' verbuig na 'hoë': 'die hoë gebou'.", [E.ADJ], 3),
      ch("G11TAA03.11", "Kies die korrekte attributiewe vorm: 'die ___ oggend' (vroeg)", ["vroeë", "vroeg", "vroeër"], "vroeë", "'vroeg' verbuig na 'vroeë': 'die vroeë oggend'.", [E.ADJ], 3),
      tf("G11TAA03.12", "Is 'gelukkig' in 'Die kind is gelukkig' predikatief gebruik?", "Waar", "Ja — die byvoeglike naamwoord staan ná die werkwoord, dus predikatief.", [E.ADJ], 2),
      tf("G11TAA03.13", "Is 'lang' in 'die lang pad' attributief gebruik?", "Waar", "Ja — dit staan voor die naamwoord, dus attributief.", [E.ADJ], 2),
      cz("G11TAA03.14", "Vul in: 'Sy hou ___ van tee as van koffie.' (graag, vergrotend)", ["liewer", "graer", "meer graag"], "liewer", "Die vergrotende trap van 'graag' is 'liewer'.", [E.COMP], 3),
      ch("G11TAA03.15", "Vergrotende trap: 'duur → ___'", ["duurder", "durste", "meer duur"], "duurder", "Die vergrotende trap van 'duur' is 'duurder'.", [E.COMP], 1),
      ch("G11TAA03.16", "Oortreffende trap: 'sleg → slegter → ___'", ["slegste", "slegter", "mees sleg"], "slegste", "'sleg' word: sleg → slegter → slegste.", [E.COMP], 2),
      ch("G11TAA03.17", "Watter sin gebruik die byvoeglike naamwoord korrek?", ["Die dooie boom het omgeval.", "Die dood boom het omgeval.", "Die doodte boom het omgeval."], "Die dooie boom het omgeval.", "'dood' verbuig na 'dooie' voor 'n naamwoord: 'die dooie boom'.", [E.ADJ], 3),
      cz("G11TAA03.18", "Vul in: 'Hierdie roete is ___ as die ander een.' (kort, vergrotend)", ["korter", "kortste", "meer kort"], "korter", "Tussen twee roetes: 'korter'.", [E.COMP], 1),
      ch("G11TAA03.19", "Kies die korrekte attributiewe vorm: 'die ___ man' (blind)", ["blinde", "blind", "blinder"], "blinde", "'blind' verbuig na 'blinde': 'die blinde man'.", [E.ADJ], 2),
      tf("G11TAA03.20", "Is 'meeste' die korrekte oortreffende trap van 'baie'?", "Waar", "Ja — baie → meer → meeste.", [E.COMP], 2),
    ]),

  ...skill(`${P}.04`, "Werkwoorde, tye, deelwoorde en infinitief",
    "Teenwoordige, verlede (het ge-) en toekomende (sal) tyd, ook skeibare werkwoorde, plus deelwoorde en die infinitief (om te + werkwoord).",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Verlede tyd = het + ge-werkwoord; toekomende = sal + werkwoord; 'n deelwoord kan beskryf ('die lagende kind'); die infinitief is 'om te + werkwoord'.",
    [
      cz("G11TAA04.01", "Vul die verlede tyd in: 'Ons het die hele dag ___.' (werk)", ["gewerk", "werk", "gewerkt"], "gewerk", "Verlede tyd: 'het' + 'ge' + werkwoord = 'het gewerk'.", [E.TENSE], 1),
      ch("G11TAA04.02", "Watter sin gebruik die INFINITIEF korrek?", ["Sy hou daarvan om te lees.", "Sy hou daarvan om lees.", "Sy hou daarvan te lees om."], "Sy hou daarvan om te lees.", "Die infinitief is 'om te + werkwoord': 'om te lees'.", [E.INF], 2),
      ch("G11TAA04.03", "Watter woord is 'n DEELWOORD wat beskryf?", ["die lagende kind", "die kind lag", "die kind het gelag"], "die lagende kind", "'lagende' is 'n deelwoord wat die kind beskryf.", [E.PART], 2),
      cz("G11TAA04.04", "Vul die infinitief in: 'Dit is belangrik ___ gereeld ___.' (oefen)", ["om te oefen", "te oefen om", "oefen om"], "om te oefen", "Die infinitief is 'om te oefen'.", [E.INF], 2),
      ch("G11TAA04.05", "Verlede tyd van 'Ek staan vroeg op':", ["Ek het vroeg opgestaan.", "Ek het vroeg op gestaan.", "Ek het vroeg geopstaan."], "Ek het vroeg opgestaan.", "By skeibare werkwoorde kom 'ge' tussenin: 'opgestaan'.", [E.TENSE], 3),
      ch("G11TAA04.06", "Watter sin bevat 'n deelwoord?", ["Die gebroke venster moet vervang word.", "Die venster breek.", "Hy het die venster gebreek."], "Die gebroke venster moet vervang word.", "'gebroke' is 'n deelwoord wat die venster beskryf.", [E.PART], 3),
      cz("G11TAA04.07", "Vul in: 'Verlede week ___ ons die wedstryd ___.' (wen, verlede)", ["het ... gewen", "wen", "sal ... wen"], "het ... gewen", "Verlede tyd: 'het ons die wedstryd gewen'.", [E.TENSE], 2),
      tf("G11TAA04.08", "Is 'om te swem' die korrekte infinitief?", "Waar", "Ja — die infinitief is 'om te + werkwoord': 'om te swem'.", [E.INF], 1),
      ch("G11TAA04.09", "Watter werkwoord kry NIE 'ge' in die verlede tyd nie?", ["ontvang", "speel", "werk"], "ontvang", "Werkwoorde met voorvoegsels soos ont-, ver-, be- kry nie 'ge' nie: 'het ontvang'.", [E.TENSE], 3),
      cz("G11TAA04.10", "Vul die toekomende tyd in: 'Hulle ___ volgende maand verhuis.'", ["sal", "het", "is"], "sal", "Toekomende tyd: 'Hulle sal verhuis.'", [E.TENSE], 1),
      ch("G11TAA04.11", "Watter sin gebruik 'n deelwoord as beskrywing?", ["Die kokende water het oorgeloop.", "Die water kook.", "Die water het gekook."], "Die kokende water het oorgeloop.", "'kokende' beskryf die water — 'n deelwoord.", [E.PART], 2),
      cz("G11TAA04.12", "Vul die infinitief in: 'Hy het besluit ___ universiteit toe ___.' (gaan)", ["om te gaan", "te gaan om", "gaan te"], "om te gaan", "Die infinitief is 'om te gaan'.", [E.INF], 2),
      ch("G11TAA04.13", "Verlede tyd van 'Sy maak die werk klaar':", ["Sy het die werk klaargemaak.", "Sy het die werk klaar gemaak.", "Sy het die werk geklaarmaak."], "Sy het die werk klaargemaak.", "'klaarmaak' is skeibaar: 'klaargemaak'.", [E.TENSE], 3),
      tf("G11TAA04.14", "Is 'Hy het die brief geskryf' die korrekte verlede tyd?", "Waar", "Ja — 'skryf' word 'het geskryf' in die verlede tyd.", [E.TENSE], 1),
      cz("G11TAA04.15", "Vul in: 'Môre ___ ek die hele dag ___.' (studeer, toekomende)", ["sal ... studeer", "het ... studeer", "studeer"], "sal ... studeer", "Toekomende tyd: 'sal ek die hele dag studeer'.", [E.TENSE], 2),
      ch("G11TAA04.16", "Watter een is die korrekte verlede tyd van 'verstaan'?", ["Ek het dit verstaan.", "Ek het dit geverstaan.", "Ek het dit verstaant."], "Ek het dit verstaan.", "'verstaan' kry nie 'ge' nie en bly 'verstaan'.", [E.TENSE], 3),
      cz("G11TAA04.17", "Vul in: 'Sy ___ nou by die venster.' (staan, teenwoordig)", ["staan", "het gestaan", "sal staan"], "staan", "Teenwoordige tyd: 'Sy staan nou'.", [E.TENSE], 1),
      tf("G11TAA04.18", "Is 'die slapende baba' 'n deelwoord wat die baba beskryf?", "Waar", "Ja — 'slapende' is 'n deelwoord wat die baba beskryf.", [E.PART], 2),
      ch("G11TAA04.19", "Watter sin is korrek in die verlede tyd?", ["Toe ek klein was, het ek baie gespeel.", "Toe ek klein was, het ek baie speel.", "Toe ek klein gewees het, ek het baie gespeel."], "Toe ek klein was, het ek baie gespeel.", "Die verlede tyd en woordorde is korrek: 'was ... het ek ... gespeel'.", [E.TENSE], 3),
      ch("G11TAA04.20", "Verlede tyd van 'Ons beloof om te help':", ["Ons het belowe om te help.", "Ons het gebeloof om te help.", "Ons het beloof gehelp."], "Ons het belowe om te help.", "'beloof/belowe' kry nie 'ge' nie: 'het belowe', en die infinitief 'om te help' bly.", [E.TENSE], 3),
    ]),

  ...skill(`${P}.05`, "Voegwoorde: groep 1, 2 en 3 en woordorde",
    "Verbind sinne met groep 1 (en, maar, want), groep 2 (dus, daarom) en groep 3 (omdat, terwyl, dat) — en die woordorde wat elkeen vereis.",
    "Taalstrukture", "T2", ["choice", "cloze"],
    "Groep 1 hou normale woordorde; groep 2 ruil onderwerp en werkwoord (dus kom hy); groep 3 stoot die werkwoord na die einde (...omdat hy kom).",
    [
      ch("G11TAA05.01", "Kies die sin met die korrekte woordorde:", ["Ek bly tuis omdat ek siek voel.", "Ek bly tuis omdat ek voel siek.", "Ek bly tuis omdat voel ek siek."], "Ek bly tuis omdat ek siek voel.", "Ná 'omdat' (groep 3) gaan die werkwoord na die einde: 'omdat ek siek voel'.", [E.ORDER], 2),
      ch("G11TAA05.02", "Kies die sin met die korrekte woordorde:", ["Dit was laat, daarom het ons gery.", "Dit was laat, daarom ons het gery.", "Dit was laat, daarom gery het ons."], "Dit was laat, daarom het ons gery.", "Ná 'daarom' (groep 2) ruil onderwerp en werkwoord: 'daarom het ons'.", [E.ORDER], 3),
      ch("G11TAA05.03", "Kies die korrekte voegwoord: 'Ek is moeg ___ ek het laat geslaap.'", ["want", "omdat", "daarom"], "want", "'want' (groep 1) gee 'n rede sonder dat die woordorde verander.", [E.CONJ], 2),
      cz("G11TAA05.04", "Vul in: 'Sy oefen elke dag ___ sy wil wen.' (rede, groep 1)", ["want", "omdat", "dus"], "want", "'want' verbind die rede met normale woordorde.", [E.CONJ], 1),
      ch("G11TAA05.05", "Kies die korrekte sin (groep 3):", ["Ek hoop dat hy betyds kom.", "Ek hoop dat kom hy betyds.", "Ek hoop dat hy betyds kom nie."], "Ek hoop dat hy betyds kom.", "Ná 'dat' kom die werkwoord aan die einde: 'dat hy betyds kom'.", [E.ORDER], 2),
      ch("G11TAA05.06", "Watter voegwoord behoort tot groep 1?", ["maar", "daarom", "omdat"], "maar", "'maar' is groep 1 — die woordorde bly dieselfde.", [E.CONJ], 1),
      ch("G11TAA05.07", "Watter voegwoord behoort tot groep 3 (werkwoord na die einde)?", ["sodat", "en", "dus"], "sodat", "'sodat' is groep 3 en stoot die werkwoord na die einde.", [E.CONJ], 2),
      ch("G11TAA05.08", "Kies die korrekte sin:", ["Hy lees sodat hy kan slaag.", "Hy lees sodat kan hy slaag.", "Hy lees sodat hy slaag kan."], "Hy lees sodat hy kan slaag.", "Ná 'sodat' kom die werkwoord aan die einde: 'sodat hy kan slaag'.", [E.ORDER], 3),
      cz("G11TAA05.09", "Vul in: 'Dit reën hard, ___ kan ons nie speel nie.' (gevolg, groep 2)", ["daarom", "want", "omdat"], "daarom", "'daarom' dui die gevolg aan en laat die woordorde omruil.", [E.CONJ], 3),
      ch("G11TAA05.10", "Kies die korrekte sin met 'maar':", ["Ek het probeer, maar ek het misluk.", "Ek het probeer, maar het ek misluk.", "Ek het probeer, maar ek misluk het."], "Ek het probeer, maar ek het misluk.", "'maar' (groep 1) hou die normale woordorde.", [E.ORDER], 2),
      cz("G11TAA05.11", "Vul in: 'Hy bly weg ___ hy bang is.' (rede, groep 3)", ["omdat", "want", "dus"], "omdat", "'omdat' is groep 3: 'omdat hy bang is' (werkwoord aan die einde).", [E.CONJ], 2),
      ch("G11TAA05.12", "Watter voegwoord behoort tot groep 2?", ["gevolglik", "en", "omdat"], "gevolglik", "'gevolglik' is groep 2 en laat onderwerp en werkwoord omruil.", [E.CONJ], 3),
      ch("G11TAA05.13", "Kies die korrekte sin (groep 3, 'voordat'):", ["Was jou hande voordat jy eet.", "Was jou hande voordat eet jy.", "Was jou hande voordat jy eet nie."], "Was jou hande voordat jy eet.", "Ná 'voordat' gaan die werkwoord na die einde: 'voordat jy eet'.", [E.ORDER], 3),
      cz("G11TAA05.14", "Vul in: 'Jy kan loop ___ ry — die keuse is joune.' (keuse, groep 1)", ["of", "omdat", "daarom"], "of", "'of' bied 'n keuse en is groep 1.", [E.CONJ], 1),
      ch("G11TAA05.15", "Kies die korrekte voegwoord: 'Sy was honger, ___ sy het kos gemaak.'", ["en", "omdat", "terwyl"], "en", "'en' verbind die twee dele met normale woordorde.", [E.CONJ], 1),
      ch("G11TAA05.16", "Kies die korrekte sin:", ["Ek wag totdat die reën ophou.", "Ek wag totdat ophou die reën.", "Ek wag totdat die reën ophou nie."], "Ek wag totdat die reën ophou.", "'totdat' is groep 3: die werkwoord ('ophou') gaan na die einde.", [E.ORDER], 2),
      cz("G11TAA05.17", "Vul in: 'Sy is jonk, ___ sy is baie wys.' (teenstelling, groep 1)", ["maar", "omdat", "daarom"], "maar", "'maar' wys 'n teenstelling en is groep 1.", [E.CONJ], 1),
      ch("G11TAA05.18", "Kies die sin met die korrekte woordorde (groep 2, 'nogtans'):", ["Dit was moeilik, nogtans het hy aangehou.", "Dit was moeilik, nogtans hy het aangehou.", "Dit was moeilik, nogtans aangehou het hy."], "Dit was moeilik, nogtans het hy aangehou.", "Ná 'nogtans' ruil die woordorde om: 'nogtans het hy'.", [E.ORDER], 3),
      cz("G11TAA05.19", "Vul in: 'Ek sal kom ___ ek tyd het.' (voorwaarde, groep 3)", ["indien", "want", "dus"], "indien", "'indien' is groep 3: 'indien ek tyd het' (werkwoord aan die einde).", [E.CONJ], 2),
      ch("G11TAA05.20", "Watter sin is heeltemal korrek?", ["Hy slaap vroeg, want hy is moeg.", "Hy slaap vroeg, want hy moeg is.", "Hy slaap vroeg, want is hy moeg."], "Hy slaap vroeg, want hy is moeg.", "'want' hou normale woordorde: 'want hy is moeg'.", [E.ORDER], 2),
    ]),

  ...skill(`${P}.06`, "Sinsontleding: sinsdele, sinsoorte en ontkenning",
    "Identifiseer sinsdele (onderwerp, gesegde, voorwerp), klassifiseer sinsoorte (stel-, vraag-, bevel-, uitroepsin) en pas die dubbele ontkenning toe.",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "Vind WIE/WAT die handeling doen (onderwerp), die werkwoorddeel (gesegde) en WAT dit ontvang (voorwerp); en onthou Afrikaans sluit 'n ontkenning gewoonlik met 'nie' af.",
    [
      ch("G11TAA06.01", "Wat is die ONDERWERP in 'Die jong seun skop die bal'?", ["Die jong seun", "die bal", "skop"], "Die jong seun", "Die onderwerp doen die handeling: 'Die jong seun'.", [E.SINSDEEL], 2),
      ch("G11TAA06.02", "Wat is die VOORWERP in 'Die jong seun skop die bal'?", ["die bal", "Die jong seun", "skop"], "die bal", "Die voorwerp ontvang die handeling: 'die bal'.", [E.SINSDEEL], 2),
      ch("G11TAA06.03", "Wat is die GESEGDE (werkwoorddeel) in 'Die meisie lees 'n boek'?", ["lees", "Die meisie", "'n boek"], "lees", "Die gesegde is die werkwoorddeel: 'lees'.", [E.SINSDEEL], 2),
      ch("G11TAA06.04", "Wat is die onderwerp in 'Gister het die hond hard geblaf'?", ["die hond", "Gister", "geblaf"], "die hond", "Die onderwerp is 'die hond' — dit doen die handeling.", [E.SINSDEEL], 3),
      ch("G11TAA06.05", "Wat is die voorwerp in 'Die vrou bak 'n koek'?", ["'n koek", "Die vrou", "bak"], "'n koek", "Die voorwerp ontvang die handeling: ''n koek'.", [E.SINSDEEL], 2),
      ch("G11TAA06.06", "Watter soort sin is 'Sit asseblief stil!'?", ["bevelsin", "vraagsin", "stelsin"], "bevelsin", "'Sit asseblief stil!' gee 'n bevel — 'n bevelsin.", [E.SENT], 1),
      ch("G11TAA06.07", "Watter soort sin is 'Hoekom is jy laat?'?", ["vraagsin", "stelsin", "bevelsin"], "vraagsin", "Dit vra iets en eindig met 'n vraagteken — 'n vraagsin.", [E.SENT], 1),
      ch("G11TAA06.08", "Watter soort sin is 'Wat 'n heerlike verrassing!'?", ["uitroepsin", "vraagsin", "stelsin"], "uitroepsin", "Dit roep 'n gevoel uit en eindig met 'n uitroepteken.", [E.SENT], 2),
      ch("G11TAA06.09", "Maak ontkennend: 'Sy ken iemand in die dorp.'", ["Sy ken niemand in die dorp nie.", "Sy ken nie iemand in die dorp.", "Sy ken iemand in die dorp nie."], "Sy ken niemand in die dorp nie.", "'iemand' word 'niemand', met 'n sluitende 'nie'.", [E.NEG], 2),
      ch("G11TAA06.10", "Maak ontkennend: 'Hy het al sy werk gedoen.'", ["Hy het nie al sy werk gedoen nie.", "Hy het nie al sy werk gedoen.", "Hy het al sy werk nie gedoen."], "Hy het nie al sy werk gedoen nie.", "Onthou die sluitende 'nie' aan die einde.", [E.NEG], 2),
      ch("G11TAA06.11", "Kies die korrekte ontkennende bevel:", ["Moenie op die gras loop nie.", "Moet nie op die gras loop.", "Moenie op die gras loop."], "Moenie op die gras loop nie.", "'n Ontkennende bevel: 'Moenie ... nie'.", [E.NEG], 2),
      ch("G11TAA06.12", "Maak ontkennend: 'Daar is iets fout.'", ["Daar is niks fout nie.", "Daar is nie iets fout.", "Daar is iets fout nie."], "Daar is niks fout nie.", "'iets' word 'niks', met sluitende 'nie'.", [E.NEG], 2),
      ch("G11TAA06.13", "Maak ontkennend: 'Hy gaan ooit weer terug.'", ["Hy gaan nooit weer terug nie.", "Hy gaan nie ooit weer terug.", "Hy gaan ooit weer terug nie."], "Hy gaan nooit weer terug nie.", "'ooit' word 'nooit', met sluitende 'nie'.", [E.NEG], 3),
      tf("G11TAA06.14", "Is 'Ek het nie die boek gelees' 'n volledige ontkenning?", "Onwaar", "Nee — dit kort die sluitende 'nie': 'Ek het nie die boek gelees nie.'", [E.NEG], 2),
      ch("G11TAA06.15", "Wat is die ONDERWERP in 'In die tuin speel die kinders vrolik'?", ["die kinders", "In die tuin", "speel"], "die kinders", "Die onderwerp is 'die kinders' — dit doen die handeling.", [E.SINSDEEL], 3),
      cz("G11TAA06.16", "Vul in: Maak ontkennend: 'Almal het geslaag.' → ___ het geslaag nie.", ["Niemand", "Nie almal", "Geen almal"], "Niemand", "'Almal' word 'Niemand': 'Niemand het geslaag nie.'", [E.NEG], 3),
      ch("G11TAA06.17", "Watter sin is 'n enkelvoudige sin?", ["Die voël vlieg.", "Die voël vlieg en die kat slaap.", "Die voël vlieg omdat hy bang is."], "Die voël vlieg.", "'n Enkelvoudige sin het een werkwoord en een gedagte: 'Die voël vlieg.'", [E.SENT], 2),
      ch("G11TAA06.18", "Wat is die voorwerp in 'Die onderwyser prys die slim leerder'?", ["die slim leerder", "Die onderwyser", "prys"], "die slim leerder", "Die voorwerp ontvang die handeling: 'die slim leerder'.", [E.SINSDEEL], 2),
      ch("G11TAA06.19", "Kies die korrekte ontkenning: 'Ek het geld om te leen.'", ["Ek het geen geld om te leen nie.", "Ek het geen geld om te leen.", "Ek het nie geen geld nie."], "Ek het geen geld om te leen nie.", "'geen ... nie' werk soos 'nie ... nie': 'geen geld ... nie'.", [E.NEG], 3),
      ch("G11TAA06.20", "Maak ontkennend: 'Jy mag hier rook.'", ["Jy mag nie hier rook nie.", "Jy mag nie hier rook.", "Jy mag hier rook nie."], "Jy mag nie hier rook nie.", "Plaas 'nie' ná 'mag' en 'n sluitende 'nie' aan die einde.", [E.NEG], 2),
    ]),
};

insertSkills(skills);
