#!/usr/bin/env node
// One-shot inserter: append Grade 12 (Level 12) to data/afrikaans-skill-tree.json.
// CRLF-aware splice before the final `  ]\n}`; Levels 1-6/10 untouched. Idempotent.
// NOTE: soft prerequisites chain to the Grade 10 counterpart (AF.G10.*), which is
// guaranteed present in this working tree. Grade 11 is authored in a parallel chat;
// once all merge, the G12->G10 hint can optionally be re-pointed to G11. Prereqs are
// soft (practice-through: blocks_progress=false) so this is cosmetic, not functional.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TREE = join(ROOT, "data", "afrikaans-skill-tree.json");

const PROG = {
  model: "practice-through",
  complete_when: "all_items_correct_once",
  reteach_on_error: true,
  requeue_missed: true,
  allow_scaffolding: true,
  blocks_progress: false,
};

const s = (id, title, description, prerequisites, templates, error_signatures, recovery_strategy) => ({
  id, bank_skill_id: id, title, description, caps_term: "T1-T4",
  prerequisites, templates, error_signatures, recovery_strategy, progression: PROG,
});
const e = (type, description, example) => ({ type, description, example });
const P = "AF.G12";
const G10 = (suffix) => [`AF.G10.${suffix}`]; // cross-grade chain to the built Grade 10 skill

const tiers = [
  {
    id: `${P}.LUI`,
    title: "Luister (Listening comprehension)",
    description:
      "Receptive listening only (Praat / speaking-aloud deferred). af-ZA audio plays a Grade 12 Afrikaans text (news / autobiographical / job interview, formal speech, report-back); the learner taps/chooses. Matric level: viewpoint, tone and critical listening dominate.",
    atomic_skills: [
      s(`${P}.LUI.01`, "Luister vir spesifieke inligting (onderhoud, nuus, werksonderhoud)",
        "Listen to a Grade 12 Afrikaans text (interview, news item, job interview) and pick out specific facts: names, dates, figures, conditions.",
        G10("LUI.01"), ["audio", "choice"],
        [e("key_detail_missed", "A key fact (date / figure / name) is missed", "Audio says salaris R12 000; learner picks R20 000."),
         e("distractor_confused", "Picks a plausible but unstated detail", "Names the wrong company/role.")],
        "Read the question before the replay; note the exact key word as you hear it."),
      s(`${P}.LUI.02`, "Luister vir hoofgedagte, opsomming en verslag",
        "Listen to a longer Afrikaans text and identify the main idea, the best summary, and the gist of a report-back.",
        G10("LUI.02"), ["audio", "choice"],
        [e("detail_as_main", "Picks a supporting detail as the main idea", "Names one statistic as the whole point."),
         e("topic_too_broad", "Picks a too-broad option", "Talk on youth unemployment; learner picks 'the economy'.")],
        "Say the text in one sentence; if a detail wouldn't fit that sentence, it is support, not the main idea."),
      s(`${P}.LUI.03`, "Luister vir houding, toon en standpunt",
        "Listen to an Afrikaans opinion or autobiographical interview and identify the speaker's attitude, tone (incl. sarcasm) and viewpoint with reasons.",
        G10("LUI.03"), ["audio", "choice"],
        [e("viewpoint_reversed", "Identifies the opposite position", "Speaker FOR; learner says AGAINST."),
         e("tone_misread", "Misreads tone such as irony", "Sarcasm read as praise.")],
        "Mark the opinion words ('ek dink', 'na my mening') and the reason words ('want', 'omdat') separately."),
      s(`${P}.LUI.04`, "Kritiese luister: vooroordeel, aannames en manipulasie",
        "Listen critically to a persuasive Afrikaans text and detect bias, assumptions, generalisation and emotive/manipulative language.",
        G10("LUI.04"), ["audio", "choice", "true-false"],
        [e("bias_unnoticed", "Treats a one-sided text as neutral", "Accepts 'almal weet...' as proof."),
         e("emotive_missed", "Does not flag loaded wording", "Misses 'skokkende', 'gevaarlike'.")],
        "Ask who benefits and who is left out; loaded words and 'almal/altyd/nooit' are bias signals."),
    ],
  },
  {
    id: `${P}.LEE`,
    title: "Lees en kyk (Reading & viewing comprehension)",
    description:
      "A written or visual Afrikaans text is shown on screen; the learner answers tappable comprehension questions. Matric Vraestel 1 (Taal in konteks) skill set: strategies, fact/opinion/intention, the writer's viewpoint, inference & evaluation, visual literacy and critical language awareness.",
    atomic_skills: [
      s(`${P}.LEE.01`, "Leesstrategieë en lees vir inligting volgens doel",
        "Use skim/scan/close reading to locate explicit information in a Grade 12 Afrikaans passage and read according to purpose.",
        G10("LEE.01"), ["choice", "true-false"],
        [e("info_not_located", "Cannot find the stated answer", "Answer is in the passage; learner guesses."),
         e("wrong_section", "Answers from the wrong part", "Pulls a detail from the wrong paragraph.")],
        "Scan for the key word from the question, then read the whole sentence around it."),
      s(`${P}.LEE.02`, "Feit, mening en bedoeling",
        "Distinguish fact from opinion and infer the writer's intention behind a statement in an Afrikaans text.",
        G10("LEE.02"), ["choice", "true-false"],
        [e("opinion_as_fact", "Labels an opinion as fact", "'Dit is die beste plan' read as fact."),
         e("intention_missed", "Misses why the writer says it", "Reads a persuasive line as neutral.")],
        "A fact can be proved; an opinion shows a view; the intention is WHY the writer chose to say it."),
      s(`${P}.LEE.03`, "Skrywer se houding, standpunt en bedoeling",
        "Identify and justify the writer's attitude, viewpoint and purpose in an article, letter or media text.",
        G10("LEE.03"), ["choice"],
        [e("attitude_misread", "Misreads the attitude", "Critical article read as supportive."),
         e("no_evidence", "Cannot point to evidence", "Chooses an attitude with no textual support.")],
        "Find the feeling-words (positive/negative) and let them point to the writer's stance and aim."),
      s(`${P}.LEE.04`, "Afleidings, gevolgtrekkings en evaluering",
        "Infer implied meaning, draw conclusions, and evaluate the strength/validity of a claim in an Afrikaans text.",
        G10("LEE.04"), ["choice"],
        [e("literal_only", "Stays literal, misses the implied meaning", "Misses an implied consequence."),
         e("overreach", "Draws an unsupported conclusion", "Adds information the text does not imply.")],
        "Combine a clue from the text with what you know: clue + knowledge = inference; then weigh the evidence."),
      s(`${P}.LEE.05`, "Visuele tekste: advertensies, spotprente, grafieke en diagramme",
        "Read visual Afrikaans texts — adverts, cartoons, graphs and diagrams — for message, persuasion, data and humour.",
        G10("LEE.05"), ["choice", "true-false"],
        [e("visual_literal", "Reads a cartoon/advert literally", "Misses the irony in a spotprent."),
         e("data_misread", "Misreads a graph/diagram value or trend", "Reads a falling line as rising.")],
        "Ask what the visual WANTS you to think/do, and read axes/labels carefully before judging a trend."),
      s(`${P}.LEE.06`, "Kritiese taalbewustheid: denotasie, konnotasie en manipulasie",
        "Detect bias, stereotyping, assumptions, manipulation, and denotation vs connotation in Afrikaans media texts.",
        G10("LEE.06"), ["choice", "true-false"],
        [e("bias_unnoticed", "Treats a slanted text as neutral", "Accepts a one-sided report as balanced."),
         e("connotation_missed", "Misses a loaded word's connotation", "Reads 'goedkoop' only as 'low price'.")],
        "Separate what a word literally says (denotasie) from the feeling it carries (konnotasie); ask who gains."),
    ],
  },
  {
    id: `${P}.LET`,
    title: "Letterkunde (Literature)",
    description:
      "Transferable literary skills on short original / public-domain Afrikaans passages and poems (no set-works). Matric Vraestel 2 depth: theme, character & narrator, plot/conflict/time & space, the full range of figures of speech and style figures, and close poem analysis.",
    atomic_skills: [
      s(`${P}.LET.01`, "Tema, motief en boodskap",
        "Identify the central theme/motif and message of a short Afrikaans story or poem and trace how it develops.",
        G10("LET.01"), ["choice"],
        [e("plot_as_theme", "Gives the plot instead of the theme", "'A man loses his job' instead of 'dignity / resilience'."),
         e("theme_too_narrow", "Picks a surface detail as the theme", "Names a single event, not the bigger idea.")],
        "The theme is the big idea (courage, loss, justice); the plot is only what happens."),
      s(`${P}.LET.02`, "Karakter, karakterisering en verteller/perspektief",
        "Analyse characters and how they are revealed, and identify the narrator / point of view of a text.",
        G10("LET.02"), ["choice", "true-false"],
        [e("trait_unsupported", "Names a trait with no evidence", "Calls a character 'brave' without support."),
         e("narrator_confused", "Confuses narrator with character/author", "Treats a first-person narrator as the author.")],
        "Judge a character by what they say/do and how others react; ask WHO is telling the story and from what angle."),
      s(`${P}.LET.03`, "Intrige, konflik, tyd en ruimte",
        "Identify plot structure, type of conflict, and the role of time and space (setting) in an Afrikaans story or drama.",
        G10("LET.03"), ["choice", "sequence"],
        [e("climax_misplaced", "Misidentifies the climax", "Picks a minor event as the turning point."),
         e("conflict_mistyped", "Names the wrong conflict type", "Calls an inner struggle 'mens teen mens'.")],
        "Track setup → conflict builds → climax → resolution; and ask how the time/place shapes events."),
      s(`${P}.LET.04`, "Beeldspraak: vergelyking, metafoor, personifikasie, metonimia, simboliek",
        "Identify and interpret the full range of figures of speech and link them to meaning.",
        G10("LET.04"), ["choice", "true-false"],
        [e("simile_metaphor_confused", "Confuses simile and metaphor", "Calls 'soos die wind' a metaphor."),
         e("symbol_missed", "Reads a symbol literally", "'Die duif' read only as a bird, not peace.")],
        "Vergelyking uses 'soos/asof'; metafoor says one IS another; simboliek = one thing stands for a bigger idea."),
      s(`${P}.LET.05`, "Stylfigure en retoriese middele",
        "Recognise irony, satire, hyperbole, contrast, repetition, euphemism, climax and paradox, and explain their effect.",
        G10("LET.05"), ["choice"],
        [e("irony_missed", "Takes ironic/sarcastic words at face value", "Reads satire as sincerity."),
         e("device_mislabelled", "Names the wrong device", "Calls contrast 'repetition'.")],
        "Ask what effect the writer wanted (emphasis, mockery, surprise) and match the device that creates it."),
      s(`${P}.LET.06`, "Gedigontleding: bou, rym, ritme, beeld en effek",
        "Analyse a poem's outer form (stanzas, rhyme, rhythm) and inner build (mood, turn, imagery) and link form to meaning.",
        G10("LET.06"), ["choice", "true-false"],
        [e("rhyme_misread", "Mislabels the rhyme scheme", "Calls aabb an abab pattern."),
         e("form_content_split", "Cannot link form to meaning", "Notes a stanza break but not its effect.")],
        "Mark line-end sounds for the rhyme scheme; then ask how a break, rhythm or image supports the mood."),
    ],
  },
  {
    id: `${P}.SKR`,
    title: "Skryf en aanbied (Writing knowledge)",
    description:
      "Writing as tappable knowledge (essay/oral PRODUCTION deferred). Matric Vraestel 3 planning/editing half: essay structure (narrative/descriptive/reflective), the transactional set incl. CV + covering letter and report, register, editing and summary by paraphrase.",
    atomic_skills: [
      s(`${P}.SKR.01`, "Briewe: formeel (brief aan die pers, klagte) en begeleidingsbrief",
        "Identify the correct structure and conventions of formal letters (to the press, complaint) and a covering letter.",
        G10("SKR.01"), ["choice", "true-false"],
        [e("format_mixed", "Mixes formal and informal conventions", "'Liewe Redakteur' to open a letter to the press."),
         e("element_missing", "Omits a required element", "Formal letter without both addresses.")],
        "A formal letter needs two addresses + a formal salutation/closing; a covering letter sells you for a specific post."),
      s(`${P}.SKR.02`, "Transaksionele tekssoorte: CV, begeleidingsbrief, verslag, onderhoud",
        "Match purpose and key features to the right transactional text: CV, covering letter, report, interview, agenda/minutes, e-mail.",
        G10("SKR.02"), ["choice"],
        [e("texttype_confused", "Wrong text-type for the purpose", "Picks 'dagboek' to apply for a job."),
         e("feature_misplaced", "Assigns a feature to the wrong text", "Puts a byline on a CV.")],
        "Match the PURPOSE (apply, inform, record, persuade) to the text-type, then check its signature features."),
      s(`${P}.SKR.03`, "Opstelbou: verhalend, beskrywend en bespiegelend",
        "Identify the structure of narrative, descriptive and reflective (bespiegelend) essays and order paragraphs coherently.",
        G10("SKR.03"), ["choice", "sequence"],
        [e("structure_wrong", "Mismatches structure to essay type", "A reflective essay built as a step list."),
         e("order_illogical", "Orders paragraphs illogically", "Conclusion before the body.")],
        "Narrative tells a story over time; descriptive paints a picture; reflective explores an idea — lead each paragraph with its main point."),
      s(`${P}.SKR.04`, "Register, styl en toon vir doel en gehoor",
        "Choose the appropriate register, style and tone for the purpose and audience of a Grade 12 text.",
        G10("SKR.04"), ["choice", "true-false"],
        [e("register_mismatch", "Wrong register for the audience", "Slang in a letter to an employer."),
         e("tone_inappropriate", "Tone does not fit the purpose", "Jokey tone in a complaint.")],
        "Ask who reads it and why: an employer/newspaper needs formal language; a friend allows informal, warmer wording."),
      s(`${P}.SKR.05`, "Redigeer: vind en verbeter die taalfout",
        "Proofread a Grade 12 Afrikaans sentence and identify or correct the language, spelling or punctuation error.",
        G10("SKR.05"), ["choice", "cloze", "true-false"],
        [e("error_unseen", "Does not spot the error", "Passes a wrong tense / agreement."),
         e("wrong_fix", "Applies an incorrect correction", "‘Corrects’ a right word.")],
        "Check one thing at a time: agreement, tense, spelling, then punctuation. Read the sentence in your head."),
      s(`${P}.SKR.06`, "Opsomming: parafraseer en kies kernpunte",
        "Select main points and paraphrase them in your own words for a summary, within a point limit, dropping examples and repetition.",
        G10("SKR.06"), ["choice", "true-false"],
        [e("detail_included", "Keeps a minor detail/example", "Lists an example instead of the main idea."),
         e("not_paraphrased", "Copies wording instead of paraphrasing", "Lifts the sentence verbatim.")],
        "Keep only points that change the meaning; then say each in your own words — drop examples and repetition."),
    ],
  },
  {
    id: `${P}.TAA`,
    title: "Taalstrukture en -konvensies (Language structures & conventions)",
    description:
      "The grammar core at Matric level, taught explicitly and tappable: nouns, pronouns, adjectives & comparison, verbs & tenses, conjunctions, sentence analysis & negation, direct/indirect speech, active/passive across tenses, punctuation, semantics, idioms, and word-formation incl. denotation/connotation. Assessed in Vraestel 1.",
    atomic_skills: [
      s(`${P}.TAA.01`, "Selfstandige naamwoorde: meervoud, verkleining, geslag, versamel/abstrak",
        "Form noun plurals, diminutives and gender forms, and recognise collective and abstract nouns.",
        G10("TAA.01"), ["choice", "cloze", "true-false"],
        [e("plural_rule_wrong", "Wrong plural rule", "'kalf' → 'kalfs' instead of 'kalwers'."),
         e("noun_type_confused", "Confuses collective/abstract nouns", "Calls 'liefde' a collective noun.")],
        "Plurals follow patterns (deelteken/kappie where needed); a versamelnaam names a group, an abstrak names an idea."),
      s(`${P}.TAA.02`, "Voornaamwoorde (alle soorte)",
        "Use personal, possessive, demonstrative, relative, indefinite and reflexive pronouns correctly.",
        G10("TAA.02"), ["choice", "cloze"],
        [e("possessive_wrong", "Wrong possessive form", "'die boek is my' instead of 'myne'."),
         e("relative_wrong", "Wrong relative pronoun", "'die man wat se' instead of 'die man wie se'.")],
        "Match the pronoun to its job: doer (persoonlik), owner (besitlik), pointer (aanwysend), joiner (betreklik)."),
      s(`${P}.TAA.03`, "Byvoeglike naamwoorde, verbuiging en trappe van vergelyking",
        "Use attributive/predicative adjectives, inflection, and degrees of comparison incl. irregulars.",
        G10("TAA.03"), ["choice", "cloze", "true-false"],
        [e("inflection_wrong", "Wrong adjective inflection", "'die slegte weer' vs 'die sleg weer'."),
         e("comparison_irregular", "Wrong comparative/superlative", "'goed → gooder' instead of 'beter'.")],
        "Vergrotende trap usually adds -er, oortreffende -ste; learn irregulars (goed-beter-beste)."),
      s(`${P}.TAA.04`, "Werkwoorde en tye: teenwoordige, verlede en toekomende tyd",
        "Form present, past (het ge-) and future (sal) tense, incl. separable verbs and deelwoorde.",
        G10("TAA.04"), ["choice", "cloze", "true-false"],
        [e("past_form_wrong", "Wrong past-tense formation", "'het kom' instead of 'het gekom'."),
         e("tense_mismatch", "Tense does not match the time marker", "'Gister speel ek' instead of 'het gespeel'.")],
        "Verlede = het + ge-werkwoord; toekomende = sal + werkwoord; let the time word cue the tense."),
      s(`${P}.TAA.05`, "Voegwoorde: groep 1, 2 en 3 en woordorde",
        "Join clauses with groups 1 (en, maar, want), 2 (dus, daarom) and 3 (omdat, terwyl, dat) and apply the word order each needs.",
        G10("TAA.05"), ["choice", "cloze"],
        [e("word_order_wrong", "Wrong word order after the conjunction", "Verb not sent to the end after 'omdat'."),
         e("conjunction_group_confused", "Conjunction from the wrong group", "Treats 'daarom' like 'en'.")],
        "Groep 1 normal order; groep 2 swaps subject/verb (dus kom hy); groep 3 pushes the verb to the end."),
      s(`${P}.TAA.06`, "Sinsoorte, sinsdele (sinsontleding) en ontkenning",
        "Identify sentence types, analyse sentence parts (onderwerp, gesegde, voorwerp, bepalings), and apply the double negative.",
        G10("TAA.06"), ["choice", "cloze", "true-false"],
        [e("double_negative_wrong", "Drops the closing 'nie'", "'Ek het nie geld' instead of '...nie geld nie'."),
         e("sentence_part_confused", "Mislabels a sentence part", "Calls the object the subject.")],
        "Afrikaans usually needs a closing 'nie'; in sinsontleding find who does it (onderwerp), the verb (gesegde) and what receives it (voorwerp)."),
      s(`${P}.TAA.07`, "Direkte en indirekte rede (stel, vra, beveel)",
        "Convert statements, questions and commands between direct and indirect speech: punctuation, pronouns, adverbs of time/place.",
        G10("TAA.07"), ["choice", "cloze"],
        [e("pronoun_not_shifted", "Pronouns not adjusted", "'Ek' kept instead of 'hy/sy'."),
         e("time_marker_kept", "Time/place word not shifted", "'vandag' not changed to 'daardie dag'.")],
        "Drop the quotation marks, shift the pronouns, and move time/place words (nou→toe, hier→daar); questions/commands change form too."),
      s(`${P}.TAA.08`, "Bedrywende en lydende vorm (alle tye)",
        "Convert between active and passive voice across present, past and future, using word/is/was/sal ... word.",
        G10("TAA.08"), ["choice", "cloze", "true-false"],
        [e("aux_wrong", "Wrong passive auxiliary for the tense", "Present passive built with 'is' instead of 'word'."),
         e("agent_misplaced", "Loses or misplaces the 'deur' agent", "Passive without 'deur die ...'.")],
        "Passive: object becomes subject + word/is/was + ...ge-werkwoord + (deur die agent). Match the helper to the tense."),
      s(`${P}.TAA.09`, "Leestekens en punktuasie",
        "Apply punctuation correctly: komma, punt, vraagteken, dubbelpunt, kommapunt, aanhalingstekens, koppelteken, afkappingsteken.",
        G10("TAA.09"), ["choice", "cloze", "true-false"],
        [e("quotation_wrong", "Quotation punctuation incorrect", "Misplaces comma/quotes in direct speech."),
         e("apostrophe_wrong", "Wrong apostrophe / 'se' use", "'Thabo's boek' instead of 'Thabo se boek'.")],
        "Each mark has a job: ? ends a question, : introduces, ; links two close sentences, “ ” frame the exact words."),
      s(`${P}.TAA.10`, "Betekenisleer: sinonieme, antonieme, homofone, homonieme, paronieme",
        "Work with synonyms, antonyms, homophones, homonyms, paronyms and polysemy in context.",
        G10("TAA.10"), ["choice", "cloze", "true-false"],
        [e("homophone_confused", "Confuses homophones", "'ly' (suffer) vs 'lei' (lead)."),
         e("antonym_synonym_swapped", "Gives a synonym when an antonym is asked", "Asked the opposite, gives a similar word.")],
        "Sinoniem = same meaning, antoniem = opposite; homofone sound alike but differ in spelling — use the sentence to choose."),
      s(`${P}.TAA.11`, "Idiome, spreekwoorde en uitdrukkings",
        "Interpret a wide range of Afrikaans idioms, expressions and proverbs by their figurative meaning.",
        G10("TAA.11"), ["choice", "cloze", "true-false"],
        [e("literal_interpretation", "Reads the idiom literally", "'die aap uit die mou laat' as a real monkey."),
         e("idiom_mismatched", "Picks an idiom that doesn't fit", "Uses a 'luck' idiom for a 'secret revealed' context.")],
        "Picture what the words say, then ask what people really mean; learn idioms as whole units."),
      s(`${P}.TAA.12`, "Woordvorming, spelling en denotasie/konnotasie",
        "Build/spell words (afleiding, samestelling, samestellende afleiding, akronieme) and distinguish a word's denotation from its connotation.",
        G10("TAA.12"), ["choice", "cloze", "true-false"],
        [e("compound_split", "Writes a compound as two words", "'tafel doek' instead of 'tafeldoek'."),
         e("connotation_missed", "Misses the connotation of a word", "Reads 'slang' (person) only literally.")],
        "Afrikaans writes compounds as ONE word; denotasie is the literal meaning, konnotasie the feeling it carries."),
    ],
  },
];

const level12 = {
  id: 12, grade: 12,
  title: "Graad 12 — Afrikaans Eerste Addisionele Taal",
  description:
    "CAPS FET Phase Grade 12 FAL (Matric). Highest FET level, toward the four exam papers (V1 Taal in konteks, V2 Letterkunde, V3 Skryf, V4 Mondeling). Both the question AND the answer options are in Afrikaans (immersive FET delivery). Tap/choice/true-false/cloze/sequence; deterministic grading; no free-text essay or spoken oral (Praat) — Writing is delivered as tappable structure/planning/editing knowledge (incl. CV + covering letter and reflective essays). Soft prerequisites chain to the Grade 10 counterpart (Grade 11 authored separately; re-point optional after merge). Strands: Luister, Lees en kyk, Letterkunde, Skryf en aanbied, Taalstrukture en -konvensies.",
  tiers,
};

let text = readFileSync(TREE, "utf8");
if (text.includes('"id": 12,')) { console.error("Level 12 already present — aborting."); process.exit(1); }
const EOL = text.includes("\r\n") ? "\r\n" : "\n";
const body = JSON.stringify(level12, null, 2).split("\n").map((l) => "    " + l).join(EOL);
const marker = `${EOL}  ]${EOL}}`;
const idx = text.lastIndexOf(marker);
if (idx === -1) throw new Error("could not find closing of levels array");
writeFileSync(TREE, text.slice(0, idx) + "," + EOL + body + text.slice(idx));
console.log(`Inserted Level 12 with ${tiers.reduce((n, t) => n + t.atomic_skills.length, 0)} skills across ${tiers.length} tiers.`);
