// Grade 12 — Taalstrukture, skills TAA.01–TAA.06 (20 items each). Afrikaans-only, Matric level.
import { ch, tf, cz, skill, insertSkills } from "./_g12_bank_lib.mjs";

const P = "AF.G12.TAA";
const E = {
  PLURAL: "ERR_AF_PLURAL", DIM: "ERR_AF_DIMINUTIVE", GENDER: "ERR_AF_GENDER", NOUN: "ERR_AF_NOUNTYPE",
  PRON: "ERR_AF_PRONOUN", ADJ: "ERR_AF_ADJECTIVE", COMP: "ERR_AF_COMPARISON",
  TENSE: "ERR_AF_TENSE", CONJ: "ERR_AF_CONJUNCTION", ORDER: "ERR_AF_WORDORDER",
  SENT: "ERR_AF_SENTENCETYPE", PARTS: "ERR_AF_SENTENCEPARTS", NEG: "ERR_AF_NEGATION", GRAM: "ERR_AF_GRAMMAR",
};

const skills = {
  ...skill(`${P}.01`, "Selfstandige naamwoorde: meervoud, verkleining, geslag, versamel/abstrak",
    "Meervoude, verkleinings, geslagsvorme én die herkenning van versamel- en abstrakte naamwoorde.",
    "Taalstrukture", "T1-T4", ["choice", "cloze", "true-false"],
    "Meervoude volg patrone (deelteken/kappie waar nodig); 'n versamelnaam noem 'n groep, 'n abstrakte naamwoord 'n idee of gevoel.",
    [
      ch("G12TAA01.01", "Wat is die meervoud van 'kalf'?", ["kalwers", "kalfs", "kalwe"], "kalwers", "Die meervoud van 'kalf' is 'kalwers' (die f word w).", [E.PLURAL], 2),
      ch("G12TAA01.02", "Wat is die meervoud van 'lid'?", ["lede", "lids", "lidde"], "lede", "Die meervoud van 'lid' is 'lede'.", [E.PLURAL], 3),
      ch("G12TAA01.03", "Wat is die meervoud van 'kind'?", ["kinders", "kindere", "kinde"], "kinders", "Die meervoud van 'kind' is 'kinders'.", [E.PLURAL], 1),
      ch("G12TAA01.04", "Wat is die meervoud van 'gas' (besoeker)?", ["gaste", "gasse", "gase"], "gaste", "Die meervoud van 'gas' (besoeker) is 'gaste'.", [E.PLURAL], 3),
      ch("G12TAA01.05", "Wat is die meervoud van 'paradys'?", ["paradyse", "paradyss", "paradies"], "paradyse", "Die meervoud van 'paradys' is 'paradyse'.", [E.PLURAL], 2),
      ch("G12TAA01.06", "Watter woord is 'n versamelnaam?", ["'n trop skape", "'n skaap", "die skaapwol"], "'n trop skape", "'trop' noem 'n groep skape — 'n versamelnaam.", [E.NOUN], 2),
      ch("G12TAA01.07", "Watter woord is 'n versamelnaam vir voëls?", ["'n swerm", "'n vlerk", "'n nes"], "'n swerm", "'n Groep voëls is 'n 'swerm' — 'n versamelnaam.", [E.NOUN], 2),
      ch("G12TAA01.08", "Watter woord is 'n abstrakte naamwoord?", ["liefde", "tafel", "boom"], "liefde", "'liefde' is 'n gevoel/idee wat jy nie kan aanraak nie — 'n abstrakte naamwoord.", [E.NOUN], 2),
      ch("G12TAA01.09", "Watter woord is 'n abstrakte naamwoord?", ["vryheid", "stoel", "hond"], "vryheid", "'vryheid' is 'n abstrakte begrip.", [E.NOUN], 2),
      ch("G12TAA01.10", "Wat is die verkleining van 'tak'?", ["takkie", "taktjie", "takie"], "takkie", "Die verkleining van 'tak' is 'takkie'.", [E.DIM], 2),
      ch("G12TAA01.11", "Wat is die verkleining van 'storie'?", ["storietjie", "storitjie", "storiepie"], "storietjie", "Die verkleining van 'storie' is 'storietjie'.", [E.DIM], 3),
      ch("G12TAA01.12", "Wat is die vroulike vorm van 'akteur'?", ["aktrise", "akteuse", "akteurin"], "aktrise", "Die vroulike vorm van 'akteur' is 'aktrise'.", [E.GENDER], 3),
      ch("G12TAA01.13", "Wat is die vroulike vorm van 'held'?", ["heldin", "heldes", "heldinne"], "heldin", "Die vroulike vorm van 'held' is 'heldin'.", [E.GENDER], 2),
      cz("G12TAA01.14", "Vul die meervoud in: 'Die span het drie nuwe ___ gekry.' (lid)", ["lede", "lids", "lidde"], "lede", "'lid' word 'lede' in die meervoud.", [E.PLURAL], 2),
      cz("G12TAA01.15", "Vul in: 'Sy het met groot ___ van die nuus gehoor.' (abstrak: vreugde)", ["vreugde", "vreugdes", "vreugdetjie"], "vreugde", "'vreugde' is 'n abstrakte naamwoord en bly hier enkelvoud.", [E.NOUN], 2),
      ch("G12TAA01.16", "Wat is die meervoud van 'museum'?", ["museums", "musea", "museume"], "museums", "Die algemeenste meervoud van 'museum' is 'museums'.", [E.PLURAL], 3),
      ch("G12TAA01.17", "Watter woord is 'n versamelnaam vir bye?", ["'n swerm", "'n korf", "'n angel"], "'n swerm", "'n Groep bye is 'n 'swerm'.", [E.NOUN], 2),
      tf("G12TAA01.18", "Is 'eerlikheid' 'n abstrakte naamwoord?", "Waar", "Ja — 'eerlikheid' is 'n eienskap/idee, dus abstrak.", [E.NOUN], 1),
      ch("G12TAA01.19", "Wat is die meervoud van 'genie' (slim mens)?", ["genieë", "genies", "geniee"], "genieë", "Die meervoud van 'genie' is 'genieë' (met deelteken).", [E.PLURAL], 3),
      cz("G12TAA01.20", "Vul die verkleining in: 'Net 'n ___ brood was oor.' (stukkie van stuk)", ["stukkie", "stuktjie", "stukie"], "stukkie", "Die verkleining van 'stuk' is 'stukkie'.", [E.DIM], 2),
    ]),

  ...skill(`${P}.02`, "Voornaamwoorde (alle soorte)",
    "Persoonlike, besitlike, aanwysende, betreklike, onbepaalde en wederkerende/wederkerige voornaamwoorde.",
    "Taalstrukture", "T3", ["choice", "cloze"],
    "Kies die voornaamwoord volgens sy werk: wie doen, wie s'n, wys aan, verbind ('n bysin), onbepaald, of verwys terug.",
    [
      cz("G12TAA02.01", "Vul in: 'Die prys is ___, nie joune nie.' (behoort aan ons)", ["ons s'n", "ons", "onse"], "ons s'n", "Die selfstandige besitlike vorm vir 'ons' is 'ons s'n'.", [E.PRON], 2),
      ch("G12TAA02.02", "Kies die korrekte betreklike voornaamwoord: 'Die kunstenaar ___ skildery gewen het, is jonk.'", ["wie se", "wat se", "waarvan"], "wie se", "By besit gebruik ons 'wie se': 'die kunstenaar wie se skildery'.", [E.PRON], 3),
      ch("G12TAA02.03", "Kies die korrekte vorm: 'Die gereedskap ___ hy werk, is duur.'", ["waarmee", "wat", "waarin"], "waarmee", "'waarmee' = met wat; hy werk mét die gereedskap.", [E.PRON], 3),
      ch("G12TAA02.04", "Kies die korrekte vorm: 'Die saak ___ ek praat, is dringend.'", ["waaroor", "wat", "waarmee"], "waaroor", "'waaroor' = oor wat; jy praat óór die saak.", [E.PRON], 3),
      cz("G12TAA02.05", "Vul die wederkerende voornaamwoord in: 'Hy was ___ vinnig aan.'", ["homself", "hom", "sy"], "homself", "Wederkerend verwys terug na die onderwerp: 'Hy was homself aan.'", [E.PRON], 2),
      cz("G12TAA02.06", "Vul die wederkerige voornaamwoord in: 'Die twee lande respekteer ___.'", ["mekaar", "hulself", "hulle"], "mekaar", "'mekaar' wys hulle doen iets vir/aan mekaar.", [E.PRON], 2),
      cz("G12TAA02.07", "Vul die onbepaalde voornaamwoord in: '___ het by die huis ingebreek.' (onbekende persoon)", ["Iemand", "Hy", "Hierdie"], "Iemand", "'Iemand' is 'n onbepaalde voornaamwoord — die persoon is onbekend.", [E.PRON], 2),
      cz("G12TAA02.08", "Vul in: 'Daar is ___ in die boks.' (onbepaald, 'n ding)", ["iets", "dit", "hy"], "iets", "'iets' is 'n onbepaalde voornaamwoord vir 'n onbekende ding.", [E.PRON], 1),
      ch("G12TAA02.09", "Watter voornaamwoord is betreklik?", ["wie se", "iemand", "myne"], "wie se", "'wie se' verbind 'n bysin met 'n naamwoord — dit is betreklik.", [E.PRON], 2),
      ch("G12TAA02.10", "Watter voornaamwoord is onbepaald?", ["niemand", "hierdie", "joune"], "niemand", "'niemand' verwys na geen bepaalde persoon nie — onbepaald.", [E.PRON], 2),
      cz("G12TAA02.11", "Vul in: 'Die brug ___ ons gery het, is oud.' (betreklik, oor wat)", ["waaroor", "wat", "waarmee"], "waaroor", "Jy ry óór die brug, dus 'waaroor'.", [E.PRON], 3),
      cz("G12TAA02.12", "Vul in: 'Hierdie tas is myne; daardie een is ___.' (behoort aan jou)", ["joune", "jou", "jy"], "joune", "Die selfstandige besitlike vorm is 'joune'.", [E.PRON], 2),
      ch("G12TAA02.13", "Kies die korrekte sin:", ["Ek en sy het gewen.", "My en haar het gewen.", "Ek en haar het gewen."], "Ek en sy het gewen.", "As onderwerp gebruik ons 'ek en sy'.", [E.PRON], 3),
      cz("G12TAA02.14", "Vul in: '___ reën al drie dae lank.' (onpersoonlik)", ["Dit", "Hy", "Daar"], "Dit", "By weer gebruik ons die onpersoonlike 'Dit'.", [E.PRON], 1),
      ch("G12TAA02.15", "Kies die korrekte vorm: 'Die rede ___ hy gekom het, is onduidelik.'", ["waarom", "wat", "waarmee"], "waarom", "'waarom' = om watter rede; dit verbind die rede met die bysin.", [E.PRON], 3),
      cz("G12TAA02.16", "Vul in: 'Sy het ___ in die spieël bekyk.' (wederkerend)", ["haarself", "haar", "sy"], "haarself", "Wederkerend: 'Sy het haarself bekyk.'", [E.PRON], 2),
      cz("G12TAA02.17", "Vul in: '___ weet wat môre gaan gebeur.' (onbepaald: geen mens)", ["Niemand", "Iemand", "Hy"], "Niemand", "'Niemand' is 'n onbepaalde voornaamwoord (geen persoon).", [E.PRON], 2),
      ch("G12TAA02.18", "Watter sin gebruik die betreklike voornaamwoord korrek?", ["Die man met wie ek praat, is my oom.", "Die man met wat ek praat, is my oom.", "Die man wie ek praat, is my oom."], "Die man met wie ek praat, is my oom.", "By 'n persoon ná 'n voorsetsel gebruik ons 'met wie'.", [E.PRON], 3),
      cz("G12TAA02.19", "Vul in: 'Dit is die dorp ___ ek gebore is.' (waarin/waar)", ["waar", "wat", "wie"], "waar", "'waar' verwys na die plek: 'die dorp waar ek gebore is'.", [E.PRON], 2),
      cz("G12TAA02.20", "Vul in: 'Almal moet ___ gereed maak vir die toets.' (wederkerend, hulle ... self)", ["hulself", "hulle", "mekaar"], "hulself", "Wederkerend vir 'almal': 'hulself gereed maak'.", [E.PRON], 3),
    ]),

  ...skill(`${P}.03`, "Byvoeglike naamwoorde, verbuiging en trappe van vergelyking",
    "Attributiewe/predikatiewe byvoeglike naamwoorde, verbuiging, en die stellende, vergrotende en oortreffende trap (ook onreëlmatig).",
    "Taalstrukture", "T1", ["choice", "cloze", "true-false"],
    "Verbuig die byvoeglike naamwoord voor 'n naamwoord waar die reël dit vereis (koud→koue); leer die onreëlmatige trappe (goed-beter-beste).",
    [
      ch("G12TAA03.01", "Kies die korrekte attributiewe vorm: 'die ___ besluit' (vinnig)", ["vinnige", "vinnig", "vinniger"], "vinnige", "Voor 'n naamwoord verbuig 'vinnig' na 'vinnige': 'die vinnige besluit'.", [E.ADJ], 2),
      ch("G12TAA03.02", "Kies die korrekte attributiewe vorm: 'die ___ aand' (koud)", ["koue", "koud", "kouer"], "koue", "'koud' verbuig na 'koue': 'die koue aand'.", [E.ADJ], 3),
      ch("G12TAA03.03", "Kies die korrekte attributiewe vorm: 'die ___ grap' (lawwe?)", ["lawwe", "lawe", "law"], "lawwe", "'laf' verbuig na 'lawwe': 'die lawwe grap'.", [E.ADJ], 3),
      ch("G12TAA03.04", "Kies die korrekte attributiewe vorm: 'die ___ berg' (hoog)", ["hoë", "hoog", "hoër"], "hoë", "'hoog' verbuig na 'hoë': 'die hoë berg'.", [E.ADJ], 3),
      ch("G12TAA03.05", "Vergrotende trap: 'goed → ___ → beste'", ["beter", "gooier", "meer goed"], "beter", "Onreëlmatig: goed → beter → beste.", [E.COMP], 2),
      ch("G12TAA03.06", "Oortreffende trap: 'min → minder → ___'", ["minste", "minnerste", "mees min"], "minste", "min → minder → minste.", [E.COMP], 2),
      ch("G12TAA03.07", "Oortreffende trap: 'naby → nader → ___'", ["naaste", "nabyste", "naderste"], "naaste", "Onreëlmatig: naby → nader → naaste.", [E.COMP], 3),
      ch("G12TAA03.08", "Vergrotende trap: 'veel/baie → ___ → meeste'", ["meer", "baier", "veelder"], "meer", "baie → meer → meeste.", [E.COMP], 2),
      cz("G12TAA03.09", "Vul die oortreffende trap in: 'Dit was die ___ ervaring van my lewe.' (sleg)", ["slegste", "slegter", "mees sleg"], "slegste", "Van almal: 'slegste'.", [E.COMP], 2),
      cz("G12TAA03.10", "Vul die vergrotende trap in: 'Hierdie roete is ___ as die ander.' (kort)", ["korter", "kortste", "meer kort"], "korter", "Tussen twee: 'korter'.", [E.COMP], 1),
      tf("G12TAA03.11", "Is 'lank' in 'Die toespraak was lank' predikatief gebruik?", "Waar", "Ja — dit staan ná die werkwoord, dus predikatief.", [E.ADJ], 2),
      tf("G12TAA03.12", "Is 'beterste' die korrekte oortreffende trap van 'goed'?", "Onwaar", "Nee — die korrekte vorm is 'beste'.", [E.COMP], 2),
      ch("G12TAA03.13", "Kies die korrekte attributiewe vorm: 'die ___ water' (warm)", ["warm", "warme", "warmer"], "warm", "'warm' bly onverbuig voor 'water': 'die warm water'.", [E.ADJ], 2),
      ch("G12TAA03.14", "Kies die korrekte attributiewe vorm: 'die ___ man' (oud)", ["ou", "oude", "oue"], "ou", "'oud' verbuig na 'ou' voor 'n naamwoord: 'die ou man'.", [E.ADJ], 3),
      ch("G12TAA03.15", "Oortreffende trap: 'duur → duurder → ___'", ["duurste", "durste", "mees duur"], "duurste", "duur → duurder → duurste.", [E.COMP], 2),
      cz("G12TAA03.16", "Vul in: 'Van al die kandidate is sy die ___.' (bekwaam, oortreffend)", ["bekwaamste", "bekwamer", "mees bekwaam"], "bekwaamste", "Oortreffende trap van 'bekwaam' is 'bekwaamste'.", [E.COMP], 3),
      ch("G12TAA03.17", "Watter sin gebruik die byvoeglike naamwoord korrek?", ["Die slim student wen.", "Die slimme student wen.", "Die student slim wen."], "Die slim student wen.", "'slim' bly onverbuig voor 'student': 'die slim student'.", [E.ADJ], 2),
      ch("G12TAA03.18", "Kies die korrekte attributiewe vorm: 'die ___ pad' (sleg)", ["slegte", "sleg", "slegter"], "slegte", "'sleg' verbuig na 'slegte' voor 'n naamwoord.", [E.ADJ], 2),
      cz("G12TAA03.19", "Vul in: 'Sy is ___ as haar suster, maar haar broer is die ___.' (oud)", ["ouer ... oudste", "oudste ... ouer", "ou ... ouer"], "ouer ... oudste", "Tussen twee: 'ouer'; van almal: 'oudste'.", [E.COMP], 3),
      tf("G12TAA03.20", "Verbuig 'mooi' na 'mooie' in 'die mooi blom'?", "Onwaar", "Nee — 'mooi' bly onverbuig: 'die mooi blom'.", [E.ADJ], 2),
    ]),

  ...skill(`${P}.04`, "Werkwoorde en tye: teenwoordige, verlede en toekomende tyd",
    "Vorming van die drie tye, ook met skeibare werkwoorde, werkwoorde met voorvoegsels (ver-/be-/ont-) en deelwoorde.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Verlede = het + ge-werkwoord (maar ver-/be-/ont- kry nie 'ge' nie); toekomende = sal + werkwoord; let op skeibare werkwoorde.",
    [
      ch("G12TAA04.01", "Verlede tyd van 'Ek verstaan die vraag':", ["Ek het die vraag verstaan.", "Ek het die vraag geverstaan.", "Ek het die vraag verstaant."], "Ek het die vraag verstaan.", "Werkwoorde met 'ver-' kry nie 'ge' nie: 'het verstaan'.", [E.TENSE], 3),
      ch("G12TAA04.02", "Verlede tyd van 'Sy beloof om te kom':", ["Sy het beloof om te kom.", "Sy het gebeloof om te kom.", "Sy het belowet om te kom."], "Sy het beloof om te kom.", "'be-' kry nie 'ge' nie: 'het beloof'.", [E.TENSE], 3),
      ch("G12TAA04.03", "Verlede tyd van 'Hulle ontmoet die span':", ["Hulle het die span ontmoet.", "Hulle het die span geontmoet.", "Hulle het die span ontmoetet."], "Hulle het die span ontmoet.", "'ont-' kry nie 'ge' nie en bly 'ontmoet'.", [E.TENSE], 3),
      ch("G12TAA04.04", "Verlede tyd van 'Ek staan vroeg op':", ["Ek het vroeg opgestaan.", "Ek het vroeg op gestaan.", "Ek het vroeg geopstaan."], "Ek het vroeg opgestaan.", "Skeibaar: 'ge' kom tussenin — 'opgestaan'.", [E.TENSE], 3),
      cz("G12TAA04.05", "Vul die toekomende tyd in: 'Ons ___ volgende week die uitslae kry.'", ["sal", "het", "was"], "sal", "Toekomende tyd: 'Ons sal ... kry.'", [E.TENSE], 1),
      ch("G12TAA04.06", "Watter sin is korrek in die verlede tyd?", ["Verlede jaar het ek hard gewerk.", "Verlede jaar ek het hard gewerk.", "Verlede jaar ek hard gewerk het."], "Verlede jaar het ek hard gewerk.", "Ná die tydsbepaling kom 'het', dan die onderwerp.", [E.ORDER], 2),
      cz("G12TAA04.07", "Vul in: 'Sy ___ die projek reeds ___.' (voltooi, verlede)", ["het ... voltooi", "het ... gevoltooi", "sal ... voltooi"], "het ... voltooi", "'voltooi' het 'n voorvoegsel-agtige vorm en kry nie 'ge' nie: 'het voltooi'.", [E.TENSE], 3),
      ch("G12TAA04.08", "Verlede tyd van 'Hy herken haar dadelik':", ["Hy het haar dadelik herken.", "Hy het haar dadelik geherken.", "Hy het haar dadelik herkent."], "Hy het haar dadelik herken.", "'her-' kry nie 'ge' nie: 'het herken'.", [E.TENSE], 3),
      tf("G12TAA04.09", "Is 'Ek het die boek begin lees' korrek in die verlede tyd?", "Waar", "Ja — 'begin' kry nie 'ge' nie en die sin is korrek.", [E.TENSE], 2),
      cz("G12TAA04.10", "Vul in: 'Môre ___ ek my aansoek ___.' (indien/inhandig, toekomend)", ["sal ... indien", "het ... ingedien", "sal ... ingedien"], "sal ... indien", "Toekomende tyd: 'sal ... indien'.", [E.TENSE], 2),
      ch("G12TAA04.11", "Teenwoordige tyd van 'Ek het die nuus gehoor':", ["Ek hoor die nuus.", "Ek sal die nuus hoor.", "Ek het die nuus hoor."], "Ek hoor die nuus.", "Teenwoordige tyd: 'Ek hoor die nuus.'", [E.TENSE], 2),
      ch("G12TAA04.12", "Verlede tyd van 'Ons bespreek die plan':", ["Ons het die plan bespreek.", "Ons het die plan gebespreek.", "Ons het die plan bespreekt."], "Ons het die plan bespreek.", "'be-' kry nie 'ge' nie: 'het bespreek'.", [E.TENSE], 3),
      cz("G12TAA04.13", "Vul in: 'Gister ___ die mense vroeg ___.' (vertrek, verlede)", ["het ... vertrek", "het ... gevertrek", "sal ... vertrek"], "het ... vertrek", "'ver-' kry nie 'ge' nie: 'het vertrek'.", [E.TENSE], 3),
      ch("G12TAA04.14", "Watter werkwoord kry WEL 'ge' in die verlede tyd?", ["werk", "verstaan", "beloof"], "werk", "'werk' kry 'ge': 'het gewerk'; die ander het voorvoegsels.", [E.TENSE], 2),
      cz("G12TAA04.15", "Vul in: 'Sy ___ die deur saggies ___.' (toemaak, verlede)", ["het ... toegemaak", "het ... toe gemaak", "het ... getoemaak"], "het ... toegemaak", "Skeibaar: 'toegemaak'.", [E.TENSE], 2),
      tf("G12TAA04.16", "Is 'Hy het die geld geleen' korrek?", "Waar", "Ja — 'leen' kry 'ge': 'het geleen'.", [E.TENSE], 1),
      ch("G12TAA04.17", "Verlede tyd van 'Die plan misluk':", ["Die plan het misluk.", "Die plan het gemisluk.", "Die plan het misluket."], "Die plan het misluk.", "'mis-' kry hier nie 'ge' nie: 'het misluk'.", [E.TENSE], 3),
      ch("G12TAA04.18", "Watter sin gebruik die toekomende tyd korrek?", ["Ek sal jou later bel.", "Ek sal jou later gebel.", "Ek het jou later bel."], "Ek sal jou later bel.", "Toekomende tyd: 'sal' + werkwoord = 'sal bel'.", [E.TENSE], 1),
      cz("G12TAA04.19", "Vul in: 'Verlede week ___ ons die saak ___.' (ondersoek, verlede)", ["het ... ondersoek", "het ... geondersoek", "sal ... ondersoek"], "het ... ondersoek", "'onder-' kry nie 'ge' nie: 'het ondersoek'.", [E.TENSE], 3),
      ch("G12TAA04.20", "Verlede tyd van 'Sy beantwoord die brief':", ["Sy het die brief beantwoord.", "Sy het die brief gebeantwoord.", "Sy het die brief beantwoordt."], "Sy het die brief beantwoord.", "'be-' kry nie 'ge' nie: 'het beantwoord'.", [E.TENSE], 3),
    ]),

  ...skill(`${P}.05`, "Voegwoorde: groep 1, 2 en 3 en woordorde",
    "Verbind sinne met groep 1 (en, maar, want), groep 2 (dus, daarom, toe) en groep 3 (omdat, terwyl, dat, sodat) — met die regte woordorde.",
    "Taalstrukture", "T2", ["choice", "cloze"],
    "Groep 1 hou normale woordorde; groep 2 ruil onderwerp en werkwoord om; groep 3 stoot die werkwoord na die einde van die bysin.",
    [
      ch("G12TAA05.01", "Kies die sin met die korrekte woordorde:", ["Ek het laat geslaap omdat ek moeg was.", "Ek het laat geslaap omdat was ek moeg.", "Ek het laat geslaap omdat ek was moeg."], "Ek het laat geslaap omdat ek moeg was.", "Ná 'omdat' (groep 3) gaan die werkwoord na die einde: 'omdat ek moeg was'.", [E.ORDER], 2),
      ch("G12TAA05.02", "Kies die korrekte woordorde:", ["Dit was donker, daarom het ons die lig aangesit.", "Dit was donker, daarom ons het die lig aangesit.", "Dit was donker, daarom het die lig ons aangesit."], "Dit was donker, daarom het ons die lig aangesit.", "Ná 'daarom' (groep 2) ruil onderwerp en werkwoord: 'daarom het ons'.", [E.ORDER], 3),
      ch("G12TAA05.03", "Kies die korrekte sin (groep 3, 'sodat'):", ["Sy leer hard sodat sy kan slaag.", "Sy leer hard sodat kan sy slaag.", "Sy leer hard sodat sy slaag kan."], "Sy leer hard sodat sy kan slaag.", "Ná 'sodat' kom die werkwoordgroep aan die einde: 'sodat sy kan slaag'.", [E.ORDER], 3),
      cz("G12TAA05.04", "Vul in: 'Hy was laat ___ die trein was vol.' (rede, groep 1)", ["want", "omdat", "dus"], "want", "'want' (groep 1) gee 'n rede met normale woordorde.", [E.CONJ], 1),
      ch("G12TAA05.05", "Kies die korrekte sin (groep 3, 'dat'):", ["Ek hoop dat dit môre mooi weer is.", "Ek hoop dat is dit môre mooi weer.", "Ek hoop dat dit môre is mooi weer."], "Ek hoop dat dit môre mooi weer is.", "Ná 'dat' kom die werkwoord aan die einde: 'dat dit ... is'.", [E.ORDER], 2),
      ch("G12TAA05.06", "Watter voegwoord behoort tot groep 2?", ["nogtans", "en", "omdat"], "nogtans", "'nogtans' is groep 2 en laat die woordorde omruil.", [E.CONJ], 3),
      ch("G12TAA05.07", "Watter voegwoord behoort tot groep 3?", ["alhoewel", "maar", "dus"], "alhoewel", "'alhoewel' is groep 3 en stoot die werkwoord na die einde.", [E.CONJ], 2),
      ch("G12TAA05.08", "Kies die korrekte sin (groep 3, 'voordat'):", ["Eet eers voordat jy gaan.", "Eet eers voordat gaan jy.", "Eet eers voordat jy gaan nie."], "Eet eers voordat jy gaan.", "Ná 'voordat' kom die werkwoord aan die einde: 'voordat jy gaan'.", [E.ORDER], 2),
      cz("G12TAA05.09", "Vul in: 'Dit reën, ___ bly ons binne.' (gevolg, groep 2 — woordorde ruil)", ["daarom", "want", "omdat"], "daarom", "'daarom' (groep 2) lei tot 'daarom bly ons'.", [E.CONJ], 3),
      ch("G12TAA05.10", "Kies die korrekte sin met 'maar':", ["Sy wou help, maar sy het nie tyd gehad nie.", "Sy wou help, maar het sy nie tyd gehad nie.", "Sy wou help, maar sy nie tyd gehad het nie."], "Sy wou help, maar sy het nie tyd gehad nie.", "'maar' (groep 1) hou normale woordorde.", [E.ORDER], 2),
      cz("G12TAA05.11", "Vul in: 'Hy bly tuis ___ hy siek is.' (rede, groep 3)", ["omdat", "want", "dus"], "omdat", "'omdat' is groep 3: werkwoord aan die einde.", [E.CONJ], 2),
      ch("G12TAA05.12", "Kies die korrekte sin (groep 3, 'terwyl'):", ["Hy luister musiek terwyl hy studeer.", "Hy luister musiek terwyl studeer hy.", "Hy luister musiek terwyl hy studeer nie."], "Hy luister musiek terwyl hy studeer.", "Ná 'terwyl' kom die werkwoord aan die einde.", [E.ORDER], 2),
      ch("G12TAA05.13", "Watter voegwoord behoort tot groep 1?", ["of", "daarom", "sodat"], "of", "'of' is groep 1 — die woordorde bly normaal.", [E.CONJ], 1),
      cz("G12TAA05.14", "Vul in: 'Sy het gewen ___ sy die hardste geoefen het.' (rede, groep 3)", ["omdat", "want", "dus"], "omdat", "'omdat' stuur die werkwoord na die einde: 'omdat sy ... geoefen het'.", [E.CONJ], 2),
      ch("G12TAA05.15", "Kies die korrekte sin (groep 2, 'toe'):", ["Die fluitjie het geblaas, toe het almal opgestaan.", "Die fluitjie het geblaas, toe almal het opgestaan.", "Die fluitjie het geblaas, toe almal opgestaan het."], "Die fluitjie het geblaas, toe het almal opgestaan.", "Ná 'toe' ruil die woordorde om: 'toe het almal'.", [E.ORDER], 3),
      cz("G12TAA05.16", "Vul in: 'Ek sal wag ___ jy terugkom.' (tyd, groep 3)", ["totdat", "want", "dus"], "totdat", "'totdat' is groep 3: 'totdat jy terugkom' (werkwoord aan die einde).", [E.CONJ], 2),
      ch("G12TAA05.17", "Watter sin is heeltemal korrek?", ["Hy is moeg, want hy het laat gewerk.", "Hy is moeg, want het hy laat gewerk.", "Hy is moeg, want hy laat gewerk het."], "Hy is moeg, want hy het laat gewerk.", "'want' (groep 1) hou normale woordorde: 'want hy het laat gewerk'.", [E.ORDER], 2),
      cz("G12TAA05.18", "Vul in: 'Sy het hard geoefen; ___ het sy die wedloop gewen.' (gevolg, groep 2)", ["gevolglik", "want", "omdat"], "gevolglik", "'gevolglik' (groep 2) lei tot 'gevolglik het sy'.", [E.CONJ], 3),
      ch("G12TAA05.19", "Kies die korrekte sin (groep 3, 'indien'):", ["Indien jy laat is, sal jy die bus mis.", "Indien jy laat is, sal die bus jy mis.", "Indien is jy laat, sal jy die bus mis."], "Indien jy laat is, sal jy die bus mis.", "Ná 'indien' gaan die werkwoord na die einde van die bysin: 'indien jy laat is'.", [E.ORDER], 3),
      cz("G12TAA05.20", "Vul in: 'Ek hou van die plan ___ ek dink dit is duur.' (teenstelling, groep 1)", ["maar", "omdat", "sodat"], "maar", "'maar' wys 'n teenstelling en is groep 1.", [E.CONJ], 1),
    ]),

  ...skill(`${P}.06`, "Sinsoorte, sinsdele (sinsontleding) en ontkenning",
    "Stel-, vraag-, bevel- en uitroepsinne; sinsontleding (onderwerp, gesegde, voorwerp, bepalings); en die dubbele ontkenning.",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "In sinsontleding: vind wie doen (onderwerp), die werkwoord (gesegde) en wat die handeling ontvang (voorwerp); ontkennings eindig met 'n sluitende 'nie'.",
    [
      ch("G12TAA06.01", "Wat is die onderwerp in 'Die ywerige student skryf die eksamen'?", ["Die ywerige student", "die eksamen", "skryf"], "Die ywerige student", "Die onderwerp doen die handeling: 'Die ywerige student'.", [E.PARTS], 2),
      ch("G12TAA06.02", "Wat is die gesegde (werkwoord) in 'Die kinders speel in die park'?", ["speel", "Die kinders", "in die park"], "speel", "Die gesegde is die werkwoord: 'speel'.", [E.PARTS], 2),
      ch("G12TAA06.03", "Wat is die voorwerp in 'Die hond jaag die kat'?", ["die kat", "Die hond", "jaag"], "die kat", "Die voorwerp ontvang die handeling: 'die kat'.", [E.PARTS], 2),
      ch("G12TAA06.04", "Wat is die bywoordelike bepaling van plek in 'Sy werk by die hospitaal'?", ["by die hospitaal", "Sy", "werk"], "by die hospitaal", "'by die hospitaal' sê WAAR — 'n bywoordelike bepaling van plek.", [E.PARTS], 3),
      ch("G12TAA06.05", "Wat is die bywoordelike bepaling van tyd in 'Ons vertrek môre vroeg'?", ["môre", "Ons", "vertrek"], "môre", "'môre' sê WANNEER — 'n bywoordelike bepaling van tyd.", [E.PARTS], 2),
      ch("G12TAA06.06", "Watter soort sin is 'Moenie laat wees nie!'?", ["bevelsin", "vraagsin", "stelsin"], "bevelsin", "Dit gee 'n bevel — 'n bevelsin.", [E.SENT], 1),
      ch("G12TAA06.07", "Watter soort sin is 'Hoekom is die vergadering uitgestel?'?", ["vraagsin", "stelsin", "uitroepsin"], "vraagsin", "Dit vra iets — 'n vraagsin.", [E.SENT], 1),
      ch("G12TAA06.08", "Maak ontkennend: 'Almal het die opdrag verstaan.'", ["Niemand het die opdrag verstaan nie.", "Nie almal het die opdrag verstaan.", "Almal het die opdrag nie verstaan."], "Niemand het die opdrag verstaan nie.", "'Almal' word 'Niemand', met 'n sluitende 'nie'.", [E.NEG], 2),
      ch("G12TAA06.09", "Maak ontkennend: 'Sy gaan ooit weer terug.'", ["Sy gaan nooit weer terug nie.", "Sy gaan nie ooit weer terug.", "Sy gaan ooit weer terug nie."], "Sy gaan nooit weer terug nie.", "'ooit' word 'nooit', met sluitende 'nie'.", [E.NEG], 3),
      ch("G12TAA06.10", "Maak ontkennend: 'Daar is iewers 'n fout.'", ["Daar is nêrens 'n fout nie.", "Daar is nie iewers 'n fout.", "Daar is iewers nie 'n fout nie."], "Daar is nêrens 'n fout nie.", "'iewers' word 'nêrens', met sluitende 'nie'.", [E.NEG], 3),
      cz("G12TAA06.11", "Vul die sluitende 'nie' in: 'Hy het die antwoord nie geken ___.'", ["nie", "geen", "nooit"], "nie", "Die sin eindig met die tweede 'nie': '...nie geken nie'.", [E.NEG], 1),
      ch("G12TAA06.12", "Wat is die onderwerp in 'Gister het die nuwe onderwyser ons klas besoek'?", ["die nuwe onderwyser", "ons klas", "Gister"], "die nuwe onderwyser", "Die doener is 'die nuwe onderwyser', al staan dit ná die werkwoord.", [E.PARTS], 3),
      ch("G12TAA06.13", "Wat is die voorwerp in 'Die komitee het 'n nuwe voorsitter gekies'?", ["'n nuwe voorsitter", "Die komitee", "gekies"], "'n nuwe voorsitter", "Die voorwerp is dit wat gekies word: ''n nuwe voorsitter'.", [E.PARTS], 2),
      ch("G12TAA06.14", "Watter soort sin is 'Wat 'n ongelooflike prestasie!'?", ["uitroepsin", "vraagsin", "stelsin"], "uitroepsin", "Dit roep 'n gevoel uit en eindig met 'n uitroepteken.", [E.SENT], 2),
      ch("G12TAA06.15", "Maak ontkennend: 'Jy mag binne rook.'", ["Jy mag nie binne rook nie.", "Jy mag nie binne rook.", "Jy mag binne rook nie."], "Jy mag nie binne rook nie.", "Plaas 'nie' ná 'mag' en 'n sluitende 'nie' aan die einde.", [E.NEG], 2),
      ch("G12TAA06.16", "Wat is die bywoordelike bepaling van wyse in 'Sy het die nuus kalm ontvang'?", ["kalm", "Sy", "die nuus"], "kalm", "'kalm' sê HOE — 'n bywoordelike bepaling van wyse.", [E.PARTS], 3),
      tf("G12TAA06.17", "In 'Die seun gee die bal vir sy maat', is 'die bal' die voorwerp.", "Waar", "Ja — 'die bal' is dit wat gegee word, dus die voorwerp.", [E.PARTS], 2),
      ch("G12TAA06.18", "Maak ontkennend: 'Iemand het die deur oopgelos.'", ["Niemand het die deur oopgelos nie.", "Nie iemand het die deur oopgelos.", "Iemand het die deur nie oopgelos."], "Niemand het die deur oopgelos nie.", "'Iemand' word 'Niemand', met sluitende 'nie'.", [E.NEG], 2),
      ch("G12TAA06.19", "Watter soort sin is 'Die uitslae word môre bekend gemaak.'?", ["stelsin", "vraagsin", "bevelsin"], "stelsin", "Dit stel 'n feit — 'n stelsin.", [E.SENT], 1),
      cz("G12TAA06.20", "Vul in (ontkenning): 'Hy het ___ geld vir die reis nie.' (geen)", ["geen", "nie", "nooit"], "geen", "'geen ... nie' werk soos 'nie ... nie': 'geen geld ... nie'.", [E.NEG], 2),
    ]),
};

insertSkills(skills);
