// Grade 12 — Skryf en aanbied (writing knowledge) tier, SKR.01–SKR.06 (20 items each).
// Afrikaans-only, Matric level. Tappable writing knowledge (production deferred).
import { ch, tf, cz, sq, skill, insertSkills } from "./_g12_bank_lib.mjs";

const P = "AF.G12.SKR";
const E = {
  TEXTTYPE: "ERR_AF_TEXTTYPE", PARA: "ERR_AF_PARAGRAPH", REG: "ERR_AF_REGISTER",
  EDIT: "ERR_AF_EDIT", SUM: "ERR_AF_SUMMARY", ESSAY: "ERR_AF_ESSAY",
};
const cx = (text) => ({ context: text });

const skills = {
  ...skill(`${P}.01`, "Briewe: formeel (brief aan die pers, klagte) en begeleidingsbrief",
    "Herken die korrekte struktuur en konvensies van formele briewe (aan die pers, klagte) en 'n begeleidingsbrief.",
    "Skryf en aanbied", "T1", ["choice", "true-false"],
    "'n Formele brief het twee adresse + 'n formele aanhef/slot; 'n begeleidingsbrief 'verkoop' jou vir 'n spesifieke pos saam met jou CV.",
    [
      ch("G12SKR01.01", "Watter aanhef pas by 'n formele brief aan 'n koerantredakteur?", ["Geagte Redakteur", "Liewe maat", "Hallo daar"], "Geagte Redakteur", "'Geagte Redakteur' is die korrekte formele aanhef.", [E.TEXTTYPE], 1),
      ch("G12SKR01.02", "Watter slot pas by 'n formele brief (naam onbekend)?", ["Die uwe", "Baie liefde", "Groete"], "Die uwe", "By 'n formele aanhef sonder naam pas die slot 'Die uwe'.", [E.TEXTTYPE], 2),
      ch("G12SKR01.03", "Wat is die doel van 'n begeleidingsbrief?", ["Om jou CV te begelei en jou vir 'n spesifieke pos voor te stel", "Om 'n storie te vertel", "Om 'n vriend te groet"], "Om jou CV te begelei en jou vir 'n spesifieke pos voor te stel", "'n Begeleidingsbrief stel jou voor en motiveer waarom jy by die pos pas.", [E.TEXTTYPE], 2),
      ch("G12SKR01.04", "Hoeveel adresse het 'n formele brief gewoonlik?", ["Twee (sender en ontvanger)", "Een", "Geen"], "Twee (sender en ontvanger)", "'n Formele brief het die skrywer se én die ontvanger se adres.", [E.TEXTTYPE], 2),
      ch("G12SKR01.05", "Wat hoort heel bo in 'n formele brief?", ["Die skrywer se adres en datum", "Die slot", "Die handtekening"], "Die skrywer se adres en datum", "Die adres en datum staan heel bo.", [E.TEXTTYPE], 1),
      ch("G12SKR01.06", "Watter element hoort in 'n klagtebrief?", ["'n Duidelike beskrywing van die probleem en wat jy verwag", "'n Grappige slot", "'n Resep"], "'n Duidelike beskrywing van die probleem en wat jy verwag", "'n Klagtebrief beskryf die probleem en die regstelling wat jy verwag.", [E.TEXTTYPE], 2),
      tf("G12SKR01.07", "'n Formele brief mag sleng en emojis bevat.", "Onwaar", "Nee — 'n formele brief gebruik korrekte, formele taal sonder sleng of emojis.", [E.REG], 1),
      ch("G12SKR01.08", "Wat is fout met hierdie brief aan 'n werkgewer?", ["Die aanhef 'Haai baas' is te informeel", "Die adres is bo", "Die datum is reg"], "Die aanhef 'Haai baas' is te informeel", "'Haai baas' pas nie by 'n formele aansoek nie; gebruik 'Geagte ...'.", [E.REG], 2, cx("Aansoekbrief: '15 Hoofweg ... Geagte adres ... Haai baas, Ek wil graag vir die pos aansoek doen ...'")),
      ch("G12SKR01.09", "Watter volgorde is korrek in 'n formele brief?", ["Adres → datum → aanhef → inhoud → slot → naam", "Aanhef → adres → inhoud → naam", "Inhoud → adres → slot"], "Adres → datum → aanhef → inhoud → slot → naam", "Die korrekte volgorde begin met adres/datum en eindig met die slot en naam.", [E.TEXTTYPE], 2),
      ch("G12SKR01.10", "Wat moet 'n begeleidingsbrief saam met aanstuur?", ["'n CV", "'n Dagboek", "'n Foto van jou troeteldier"], "'n CV", "'n Begeleidingsbrief vergesel jou CV.", [E.TEXTTYPE], 2),
      ch("G12SKR01.11", "Watter toon pas by 'n klagtebrief?", ["Ferm maar beleefd", "Speels", "Vleiend"], "Ferm maar beleefd", "'n Klagtebrief is ferm dog steeds beleefd.", [E.REG], 2),
      tf("G12SKR01.12", "In 'n formele brief skryf jy ook die ontvanger se adres neer.", "Waar", "Ja — 'n formele brief sluit die ontvanger se adres in.", [E.TEXTTYPE], 2),
      ch("G12SKR01.13", "Watter aanhef gebruik jy as jy die ontvanger se naam ken (formeel)?", ["Geagte mnr./mev. [Van]", "Liewe vriend", "Haai"], "Geagte mnr./mev. [Van]", "Met 'n bekende naam: 'Geagte mnr./mev. [Van]'.", [E.TEXTTYPE], 2),
      ch("G12SKR01.14", "Watter slot pas by 'Geagte mnr. Botha' (naam bekend)?", ["Vriendelike groete", "Die uwe", "Baie liefde"], "Vriendelike groete", "By 'n bekende naam pas 'Vriendelike groete' (of 'Hoogagtend').", [E.TEXTTYPE], 3),
      ch("G12SKR01.15", "Wat moet 'n begeleidingsbrief beklemtoon?", ["Hoekom jy by die spesifieke pos pas", "Jou gunsteling kos", "Jou vakansieplanne"], "Hoekom jy by die spesifieke pos pas", "Dit beklemtoon jou geskiktheid vir die pos.", [E.TEXTTYPE], 2),
      ch("G12SKR01.16", "Watter een hoort NIE in 'n formele brief nie?", ["LOL en emojis", "'n Onderwerpreël", "'n Formele slot"], "LOL en emojis", "Sleng/emojis pas nie in 'n formele brief nie.", [E.REG], 1),
      ch("G12SKR01.17", "Waar plaas jy jou naam/handtekening in 'n brief?", ["Heel onder, ná die slot", "Heel bo", "In die middel"], "Heel onder, ná die slot", "Jou naam/handtekening kom heel onder ná die slot.", [E.TEXTTYPE], 1),
      ch("G12SKR01.18", "Watter sin pas by die opening van 'n klagtebrief?", ["Ek skryf om my ontevredenheid oor ... uit te spreek.", "Raai wat het gebeur!", "Hoe gaan dit met jou?"], "Ek skryf om my ontevredenheid oor ... uit te spreek.", "Die formele opening stel die doel van die klag duidelik.", [E.REG], 2),
      tf("G12SKR01.19", "'n Begeleidingsbrief en 'n CV is dieselfde dokument.", "Onwaar", "Nee — die CV lys jou besonderhede; die begeleidingsbrief motiveer waarom jy pas.", [E.TEXTTYPE], 2),
      ch("G12SKR01.20", "Watter sin sluit 'n formele brief gepas af?", ["Ek sien uit na u terugvoer.", "Sien jou later, maat!", "Totsiens, liefling."], "Ek sien uit na u terugvoer.", "'n Formele afsluiting bly beleefd en sakelik.", [E.REG], 2),
    ]),

  ...skill(`${P}.02`, "Transaksionele tekssoorte: CV, begeleidingsbrief, verslag, onderhoud",
    "Pas doel en kenmerke by die regte transaksionele teks: CV, begeleidingsbrief, verslag, onderhoud, agenda/notule, e-pos.",
    "Skryf en aanbied", "T4", ["choice"],
    "Pas die DOEL (aansoek doen, inlig, aanteken, oorreed) by die tekssoort en gaan dan sy kenmerkende elemente na.",
    [
      ch("G12SKR02.01", "Watter teks lys jou opleiding, ervaring en vaardighede vir 'n werkaansoek?", ["'n CV", "'n Dagboek", "'n Advertensie"], "'n CV", "'n CV lys jou kwalifikasies, ervaring en vaardighede.", [E.TEXTTYPE], 1),
      ch("G12SKR02.02", "Watter teks teken aan wat by 'n vergadering bespreek en besluit is?", ["'n Notule", "'n Agenda", "'n CV"], "'n Notule", "'n Notule teken die verloop en besluite van 'n vergadering aan.", [E.TEXTTYPE], 2),
      ch("G12SKR02.03", "Watter teks lys vooraf die sake wat by 'n vergadering bespreek sal word?", ["'n Agenda", "'n Notule", "'n Verslag"], "'n Agenda", "'n Agenda lys vooraf die sake vir bespreking.", [E.TEXTTYPE], 2),
      ch("G12SKR02.04", "Watter teks gee 'n formele, gestruktureerde verslag van 'n gebeurtenis of ondersoek?", ["'n Verslag", "'n Dagboek", "'n Uitnodiging"], "'n Verslag", "'n Verslag gee 'n formele, gestruktureerde weergawe van feite/bevindinge.", [E.TEXTTYPE], 2),
      ch("G12SKR02.05", "Watter teks gee 'n gesprek tussen 'n onderhoudvoerder en 'n persoon weer?", ["'n Onderhoud", "'n Advertensie", "'n CV"], "'n Onderhoud", "'n Onderhoud gee 'n vraag-en-antwoord-gesprek weer.", [E.TEXTTYPE], 2),
      ch("G12SKR02.06", "Watter element hoort in 'n CV?", ["Kontakbesonderhede, opleiding en werkervaring", "'Liewe dagboek'", "'n RSVP"], "Kontakbesonderhede, opleiding en werkervaring", "'n CV bevat kontakbesonderhede, opleiding en ervaring.", [E.TEXTTYPE], 2),
      ch("G12SKR02.07", "Watter element is uniek aan 'n e-pos?", ["'n Onderwerpreël en die ontvanger se e-posadres", "'n RSVP", "'n Foto-byskrif"], "'n Onderwerpreël en die ontvanger se e-posadres", "'n E-pos het 'n 'Aan'-adres en 'n onderwerpreël.", [E.TEXTTYPE], 2),
      ch("G12SKR02.08", "Watter struktuur het 'n formele verslag gewoonlik?", ["Titel, inleiding, bevindinge en gevolgtrekking/aanbevelings", "Aanhef en RSVP", "'n Byskrif en opskrif"], "Titel, inleiding, bevindinge en gevolgtrekking/aanbevelings", "'n Verslag het 'n titel, inleiding, bevindinge en gevolgtrekking/aanbevelings.", [E.TEXTTYPE], 3),
      ch("G12SKR02.09", "Jy doen aansoek vir 'n pos. Watter twee tekste stuur jy saam?", ["'n CV en 'n begeleidingsbrief", "'n Dagboek en 'n notule", "'n Advertensie en 'n RSVP"], "'n CV en 'n begeleidingsbrief", "'n Aansoek bestaan uit 'n CV plus 'n begeleidingsbrief.", [E.TEXTTYPE], 2),
      ch("G12SKR02.10", "Watter element hoort in 'n notule?", ["Teenwoordiges, verskonings en besluite", "'n Leuse", "'n RSVP"], "Teenwoordiges, verskonings en besluite", "'n Notule noteer wie teenwoordig was, verskonings en besluite.", [E.TEXTTYPE], 3),
      ch("G12SKR02.11", "Watter teks gebruik die voorsitter om 'n vergadering te beplan?", ["'n Agenda", "'n Notule", "'n CV"], "'n Agenda", "Die voorsitter stel 'n agenda op om die vergadering te beplan.", [E.TEXTTYPE], 2),
      ch("G12SKR02.12", "Watter element pas NIE by 'n CV nie?", ["'Liewe dagboek'", "Verwysings", "Vaardighede"], "'Liewe dagboek'", "''Liewe dagboek' hoort by 'n dagboek, nie 'n CV nie.", [E.TEXTTYPE], 2),
      ch("G12SKR02.13", "Watter teks is die mees gepas om 'n werkgewer vinnig 'n dokument te stuur?", ["'n E-pos met aanhegsel", "'n Dagboek", "'n Notule"], "'n E-pos met aanhegsel", "'n E-pos met 'n aanhegsel is gepas vir vinnige, formele kommunikasie.", [E.TEXTTYPE], 1),
      ch("G12SKR02.14", "Watter teks gee feite en aanbevelings ná 'n ondersoek?", ["'n Verslag", "'n Uitnodiging", "'n Poskaart"], "'n Verslag", "'n Verslag gee bevindinge en aanbevelings ná 'n ondersoek.", [E.TEXTTYPE], 2),
      ch("G12SKR02.15", "Wat is die doel van 'n begeleidingsbrief?", ["Om 'n CV te begelei en jou motivering te gee", "Om 'n storie te vertel", "Om 'n geleentheid te adverteer"], "Om 'n CV te begelei en jou motivering te gee", "'n Begeleidingsbrief begelei die CV en gee jou motivering.", [E.TEXTTYPE], 2),
      ch("G12SKR02.16", "Watter teks gebruik 'n vraag-en-antwoord-formaat?", ["'n Onderhoud", "'n Verslag", "'n Advertensie"], "'n Onderhoud", "'n Onderhoud gebruik 'n vraag-en-antwoord-formaat.", [E.TEXTTYPE], 1),
      ch("G12SKR02.17", "Watter inligting moet 'n CV se kontakafdeling hê?", ["Naam, telefoonnommer en e-posadres", "Jou gunsteling fliek", "Jou daaglikse roetine"], "Naam, telefoonnommer en e-posadres", "Die kontakafdeling het naam, telefoonnommer en e-posadres.", [E.TEXTTYPE], 1),
      ch("G12SKR02.18", "Watter teks is gepas om mense in te lig oor die uitslag van 'n skoolprojek?", ["'n Verslag", "'n Dagboek", "'n Uitnodiging"], "'n Verslag", "'n Verslag is gepas om die uitslag/bevindinge oor te dra.", [E.TEXTTYPE], 2),
      ch("G12SKR02.19", "Wat is die korrekte volgorde van 'n notule se kop?", ["Datum, plek, teenwoordiges, verskonings", "Besluite, datum, leuse", "RSVP, opskrif, byskrif"], "Datum, plek, teenwoordiges, verskonings", "'n Notule begin met datum, plek, teenwoordiges en verskonings.", [E.TEXTTYPE], 3),
      ch("G12SKR02.20", "Watter teks moet bondig, akkuraat en in die derde persoon geskryf word?", ["'n Notule/verslag", "'n Persoonlike e-pos aan 'n vriend", "'n Dagboek"], "'n Notule/verslag", "'n Notule/verslag is bondig, akkuraat en gewoonlik in die derde persoon.", [E.TEXTTYPE], 3),
    ]),

  ...skill(`${P}.03`, "Opstelbou: verhalend, beskrywend en bespiegelend",
    "Identifiseer die struktuur van verhalende, beskrywende en bespiegelende (reflektiewe) opstelle en orden paragrawe samehangend.",
    "Skryf en aanbied", "T3", ["choice", "sequence"],
    "'n Verhalende opstel vertel 'n storie oor tyd; 'n beskrywende skep 'n beeld; 'n bespiegelende ondersoek 'n idee — begin elke paragraaf met sy kerngedagte.",
    [
      ch("G12SKR03.01", "Watter opstel vertel 'n storie met 'n begin, middel en einde?", ["'n Verhalende opstel", "'n Beskrywende opstel", "'n Bespiegelende opstel"], "'n Verhalende opstel", "'n Verhalende opstel vertel 'n storie oor tyd.", [E.ESSAY], 1),
      ch("G12SKR03.02", "Watter opstel skep 'n lewendige beeld van 'n plek, persoon of ding?", ["'n Beskrywende opstel", "'n Verhalende opstel", "'n Bespiegelende opstel"], "'n Beskrywende opstel", "'n Beskrywende opstel skilder 'n beeld met sintuiglike besonderhede.", [E.ESSAY], 1),
      ch("G12SKR03.03", "Watter opstel ondersoek 'n idee of vraag en deel die skrywer se gedagtes daaroor?", ["'n Bespiegelende opstel", "'n Verhalende opstel", "'n Beskrywende opstel"], "'n Bespiegelende opstel", "'n Bespiegelende (reflektiewe) opstel dink hardop oor 'n idee of vraag.", [E.ESSAY], 2),
      ch("G12SKR03.04", "Wat is die kernsin van 'n paragraaf?", ["Die sin wat die hoofgedagte stel", "Die laaste sin", "Die langste sin"], "Die sin wat die hoofgedagte stel", "Die kernsin dra die hoofgedagte van die paragraaf.", [E.PARA], 1),
      sq("G12SKR03.05", "Orden die dele van 'n opstel korrek:", ["Inleiding", "Liggaam: eerste hoofgedagte", "Liggaam: tweede hoofgedagte", "Slot"], "'n Opstel begin met die inleiding, dan die liggaamsparagrawe, en eindig met die slot.", [E.ESSAY], 1, cx("Dele: Liggaam: tweede hoofgedagte / Slot / Inleiding / Liggaam: eerste hoofgedagte.")),
      ch("G12SKR03.06", "Wat is die doel van die inleiding van 'n opstel?", ["Om die leser te boei en die onderwerp/standpunt voor te stel", "Om die storie te beëindig", "Om bronne te lys"], "Om die leser te boei en die onderwerp/standpunt voor te stel", "Die inleiding boei die leser en stel die onderwerp/standpunt.", [E.ESSAY], 2),
      ch("G12SKR03.07", "Wat is die doel van die slot van 'n opstel?", ["Om die hoofgedagtes saam te vat en af te sluit", "Om 'n nuwe onderwerp te begin", "Om bronne te lys"], "Om die hoofgedagtes saam te vat en af te sluit", "Die slot vat saam en sluit die opstel bevredigend af.", [E.ESSAY], 2),
      sq("G12SKR03.08", "Orden die sinne tot 'n logiese beskrywende paragraaf:", ["Die ou markplein bruis van lewe.", "Stalletjies vol vrugte staan in 'n ry.", "Die geur van vars brood hang in die lug.", "Oral klink stemme en gelag."], "Begin met die kernsin, gee dan sintuiglike besonderhede wat die beeld opbou.", [E.PARA], 2, cx("Sinne: Stalletjies vol vrugte staan in 'n ry. / Die ou markplein bruis van lewe. / Oral klink stemme en gelag. / Die geur van vars brood hang in die lug.")),
      ch("G12SKR03.09", "Watter sin pas die beste in 'n bespiegelende opstel?", ["Wat beteken dit werklik om vry te wees?", "Toe spring die hond oor die heining.", "Die berg was hoog en blou."], "Wat beteken dit werklik om vry te wees?", "'n Bespiegelende opstel ondersoek 'n idee, dikwels met 'n vraag.", [E.ESSAY], 3),
      ch("G12SKR03.10", "Hoeveel hoofgedagtes behoort een paragraaf te hê?", ["Een", "Drie", "Vyf"], "Een", "Een paragraaf hanteer een hoofgedagte.", [E.PARA], 1),
      sq("G12SKR03.11", "Orden die prosesskryf-stappe korrek:", ["Beplanning", "Eerste konsep", "Hersiening en redigering", "Proeflees en aanbieding"], "Beplan, skryf 'n konsep, hersien/redigeer, en proeflees/aanbied.", [E.PARA], 1, cx("Stappe: Hersiening en redigering / Beplanning / Proeflees en aanbieding / Eerste konsep.")),
      ch("G12SKR03.12", "Watter skakelwoord pas die beste om 'n nuwe punt by te voeg?", ["Verder", "Egter", "Daarom"], "Verder", "'Verder' voeg 'n nuwe punt by; 'egter' wys teenstelling; 'daarom' wys gevolg.", [E.PARA], 2),
      ch("G12SKR03.13", "Watter skakelwoord wys 'n teenstelling?", ["Daarteenoor", "Verder", "Boonop"], "Daarteenoor", "'Daarteenoor' wys 'n teenstelling.", [E.PARA], 2),
      ch("G12SKR03.14", "Watter kenmerk is sterk in 'n beskrywende opstel?", ["Sintuiglike besonderhede (sien, hoor, ruik)", "'n Lys argumente", "'n Notule-formaat"], "Sintuiglike besonderhede (sien, hoor, ruik)", "Beskrywende skryfwerk leun op sintuiglike besonderhede.", [E.ESSAY], 2),
      ch("G12SKR03.15", "Watter sin sou 'n goeie kernsin vir 'n verhalende paragraaf wees?", ["Dit was die dag wat alles verander het.", "Honde is lojale diere.", "Die berg is 2 000 meter hoog."], "Dit was die dag wat alles verander het.", "'n Verhalende kernsin stel 'n gebeurtenis/wending voor.", [E.ESSAY], 2),
      sq("G12SKR03.16", "Orden tot 'n logiese bespiegelende paragraaf:", ["Sukses beteken nie vir almal dieselfde nie.", "Vir party is dit geld en mag.", "Vir ander is dit vrede en geluk.", "Miskien lê die waarheid êrens tussenin."], "Begin met die kernidee, gee dan twee sienings, en sluit met 'n bespiegelende gedagte af.", [E.PARA], 3, cx("Sinne: Vir ander is dit vrede en geluk. / Sukses beteken nie vir almal dieselfde nie. / Miskien lê die waarheid êrens tussenin. / Vir party is dit geld en mag.")),
      ch("G12SKR03.17", "Wat moet jy doen tydens hersiening?", ["Die inhoud en struktuur verbeter", "Net die spelling nagaan", "Die titel kies"], "Die inhoud en struktuur verbeter", "Hersiening verbeter die inhoud en struktuur (proeflees hanteer klein foute).", [E.PARA], 2),
      ch("G12SKR03.18", "Watter sin breek die eenheid van 'n paragraaf oor 'n storm?", ["My niggie hou van inkopies doen.", "Die wind het die dakke geruk.", "Die reën het in strome geval."], "My niggie hou van inkopies doen.", "Die inkopie-sin hoort nie by die onderwerp 'storm' nie.", [E.PARA], 2, cx("Die storm het sonder waarskuwing toegeslaan. Die wind het die dakke geruk. My niggie hou van inkopies doen. Die reën het in strome geval.")),
      ch("G12SKR03.19", "Wat is die effek van 'n sterk slotsin in 'n opstel?", ["Dit laat 'n blywende indruk en rond die opstel af", "Dit begin 'n nuwe gedagte", "Dit gee die titel"], "Dit laat 'n blywende indruk en rond die opstel af", "'n Sterk slot laat 'n blywende indruk en sluit die opstel af.", [E.ESSAY], 2),
      ch("G12SKR03.20", "Watter benadering pas 'n bespiegelende opstel die beste?", ["'n Idee van verskillende kante ondersoek", "Net 'n reeks gebeure vertel", "Net 'n plek beskryf"], "'n Idee van verskillende kante ondersoek", "'n Bespiegelende opstel weeg 'n idee van verskillende kante.", [E.ESSAY], 3),
    ]),

  ...skill(`${P}.04`, "Register, styl en toon vir doel en gehoor",
    "Kies die gepaste register, styl en toon vir die doel en gehoor van 'n Graad 12-teks.",
    "Skryf en aanbied", "T2", ["choice", "true-false"],
    "Vra wie dit gaan lees en waarom: 'n werkgewer/koerant verg formele taal; 'n vriend laat informele, warmer woorde toe.",
    [
      ch("G12SKR04.01", "Watter register pas by 'n aansoekbrief aan 'n maatskappy?", ["Formeel", "Informeel", "Sleng"], "Formeel", "'n Aansoekbrief verg 'n formele register.", [E.REG], 1),
      ch("G12SKR04.02", "Watter register pas by 'n boodskap aan 'n goeie vriend?", ["Informeel", "Formeel", "Amptelik"], "Informeel", "'n Boodskap aan 'n vriend is informeel.", [E.REG], 1),
      ch("G12SKR04.03", "Watter sin is die mees formeel?", ["Ek wil graag u aandag vestig op die volgende kwessie.", "Yo, check hierdie probleem uit.", "Hoor hier, daar's 'n probleem."], "Ek wil graag u aandag vestig op die volgende kwessie.", "Die eerste sin gebruik gepaste, formele taal.", [E.REG], 2),
      ch("G12SKR04.04", "Watter woord is meer formeel as 'kry'?", ["ontvang", "vat", "gryp"], "ontvang", "'ontvang' is die meer formele woord vir 'kry'.", [E.REG], 2),
      ch("G12SKR04.05", "Watter woord is meer formeel as 'baie groot'?", ["aansienlik", "yslik", "mega"], "aansienlik", "'aansienlik' is die meer formele keuse.", [E.REG], 3),
      tf("G12SKR04.06", "Jy gebruik dieselfde toon vir 'n simpatiebrief en 'n advertensie.", "Onwaar", "Nee — die toon verskil: sag/meelewend teenoor energiek/oorredend.", [E.REG], 1),
      ch("G12SKR04.07", "Watter toon pas by 'n simpatiebrief?", ["Meelewend en sag", "Vrolik en speels", "Kwaad"], "Meelewend en sag", "'n Simpatiebrief het 'n sagte, meelewende toon.", [E.REG], 2),
      ch("G12SKR04.08", "Watter toon pas by 'n motiveringstoespraak?", ["Inspirerend en kragtig", "Hartseer", "Onverskillig"], "Inspirerend en kragtig", "'n Motiveringstoespraak is inspirerend en kragtig.", [E.REG], 2),
      ch("G12SKR04.09", "Watter woordkeuse is te informeel vir 'n formele verslag?", ["'awesome'", "'doeltreffend'", "'effektief'"], "'awesome'", "'awesome' is sleng en pas nie in 'n formele verslag nie.", [E.REG], 2),
      ch("G12SKR04.10", "Wat is 'register' in skryfwerk?", ["Die vlak van formaliteit wat by die gehoor pas", "Die lengte van die teks", "Die kleur van die ink"], "Die vlak van formaliteit wat by die gehoor pas", "Register is hoe formeel of informeel jou taal is.", [E.REG], 2),
      ch("G12SKR04.11", "Watter aanhef pas by 'n formele e-pos aan 'n onbekende amptenaar?", ["Geagte Meneer/Mevrou", "Haai daar", "Yo"], "Geagte Meneer/Mevrou", "'n Formele e-pos begin met 'Geagte Meneer/Mevrou'.", [E.REG], 1),
      ch("G12SKR04.12", "Watter sin het 'n beleefde, formele toon?", ["Sou u my asseblief kon help met hierdie navraag?", "Help my nou!", "Jy moet my help."], "Sou u my asseblief kon help met hierdie navraag?", "'asseblief' en 'u' maak die versoek beleefd en formeel.", [E.REG], 1),
      tf("G12SKR04.13", "Slengwoorde pas in 'n formele aansoekbrief.", "Onwaar", "Nee — formele briewe vermy sleng.", [E.REG], 1),
      ch("G12SKR04.14", "Vir watter gehoor sou jy die eenvoudigste taal gebruik?", ["'n Groep jong kinders", "'n Paneel kundiges", "'n Regter"], "'n Groep jong kinders", "Jong kinders verg eenvoudige, vriendelike taal.", [E.REG], 1),
      ch("G12SKR04.15", "Watter toon pas by 'n klagtebrief?", ["Ferm maar beleefd", "Speels", "Vleiend"], "Ferm maar beleefd", "'n Klagtebrief is ferm dog beleefd.", [E.REG], 2),
      ch("G12SKR04.16", "Watter woord is meer formeel as 'begin'?", ["aanvang", "kickstart", "afskop"], "aanvang", "'aanvang' is die meer formele woord vir 'begin'.", [E.REG], 3),
      ch("G12SKR04.17", "Watter sin sou jy in 'n vriendskaplike brief gebruik?", ["Ek kan nie wag om jou weer te sien nie!", "Geliewe my versoek te oorweeg.", "Hiermee bevestig ek ontvangs."], "Ek kan nie wag om jou weer te sien nie!", "Die warm, persoonlike sin pas by 'n vriend.", [E.REG], 1),
      tf("G12SKR04.18", "Die gehoor en die doel bepaal watter register en toon jy kies.", "Waar", "Ja — wie lees en waarom bepaal die register en toon.", [E.REG], 1),
      ch("G12SKR04.19", "Watter toon is ongepas vir 'n formele verslag?", ["Speels en grappig", "Sakelik en objektief", "Neutraal"], "Speels en grappig", "'n Verslag is sakelik en objektief, nie speels nie.", [E.REG], 2),
      ch("G12SKR04.20", "Watter sin pas by 'n formele uitnodiging?", ["Ons nooi u vriendelik uit na die geleentheid.", "Kom kuier, dit gaan wild wees!", "Yo, kom partytjie!"], "Ons nooi u vriendelik uit na die geleentheid.", "Die formele uitnodiging gebruik beleefde, formele taal.", [E.REG], 2),
    ]),

  ...skill(`${P}.05`, "Redigeer: vind en verbeter die taalfout",
    "Proeflees 'n Graad 12 Afrikaanse sin en identifiseer of verbeter die taal-, spel- of leestekenfout.",
    "Skryf en aanbied", "T1-T4", ["choice", "cloze", "true-false"],
    "Kontroleer een ding op 'n slag: ooreenstemming, tyd, spelling, dan leestekens. Lees die sin in jou kop.",
    [
      ch("G12SKR05.01", "Watter sin is heeltemal korrek?", ["Ek het gister my aansoek ingedien.", "Ek het gister my aansoek indien.", "Ek gister my aansoek ingedien het."], "Ek het gister my aansoek ingedien.", "Die verlede tyd en woordorde is korrek: 'het ... ingedien'.", [E.EDIT], 1),
      ch("G12SKR05.02", "Wat is fout: 'Sy het nie die werk voltooi'?", ["Die sluitende 'nie' kort", "Niks is fout nie", "'voltooi' is verkeerd"], "Die sluitende 'nie' kort", "Dit moet wees: 'Sy het nie die werk voltooi nie.'", [E.EDIT], 1),
      ch("G12SKR05.03", "Kies die korrek gespelde woord:", ["professioneel", "profesioneel", "professionel"], "professioneel", "Die korrekte spelling is 'professioneel'.", [E.EDIT], 3),
      ch("G12SKR05.04", "Wat is fout: 'die maatskappy het sy beleid verander.'?", ["Die sin moet met 'n hoofletter begin", "Niks is fout nie", "'beleid' is verkeerd"], "Die sin moet met 'n hoofletter begin", "'die' moet 'Die' wees — sinne begin met 'n hoofletter.", [E.EDIT], 1),
      ch("G12SKR05.05", "Watter sin het die korrekte verlede tyd?", ["Ons het die saak bespreek.", "Ons het die saak gebespreek.", "Ons het die saak bespreekt."], "Ons het die saak bespreek.", "'be-' kry nie 'ge' nie: 'het bespreek'.", [E.EDIT], 2),
      ch("G12SKR05.06", "Wat is fout: 'Wanneer begin die vergadering.'?", ["Dit moet met 'n vraagteken eindig", "Niks is fout nie", "'vergadering' is verkeerd"], "Dit moet met 'n vraagteken eindig", "Dit is 'n vraag: 'Wanneer begin die vergadering?'", [E.EDIT], 1),
      ch("G12SKR05.07", "Kies die korrek gespelde woord:", ["onmiddellik", "onmidellik", "onmiddelik"], "onmiddellik", "Die korrekte spelling is 'onmiddellik'.", [E.EDIT], 3),
      ch("G12SKR05.08", "Watter sin is korrek?", ["Hy en ek het die projek voltooi.", "Hom en my het die projek voltooi.", "Hy en my het die projek voltooi."], "Hy en ek het die projek voltooi.", "As onderwerp gebruik ons 'hy en ek'.", [E.EDIT], 3),
      ch("G12SKR05.09", "Wat is fout: 'Sy het baie boek gelees.'?", ["'boek' moet meervoud wees: 'boeke'", "Niks is fout nie", "'gelees' is verkeerd"], "'boek' moet meervoud wees: 'boeke'", "By 'baie' moet die meervoud staan: 'baie boeke'.", [E.EDIT], 2),
      cz("G12SKR05.10", "Verbeter: 'Volgende week ___ ek my eksamen ___.' (skryf, toekomend)", ["sal ... skryf", "het ... geskryf", "geskryf"], "sal ... skryf", "Toekomende tyd: 'sal ... skryf'.", [E.EDIT], 2),
      cz("G12SKR05.11", "Verbeter: 'Hy ___ die brief gister ___.' (pos/stuur, verlede: pos)", ["het ... gepos", "pos", "geposeer"], "het ... gepos", "Verlede tyd: 'het ... gepos'.", [E.EDIT], 2),
      ch("G12SKR05.12", "Watter sin gebruik die besitsvorm korrek?", ["Die direkteur se besluit was finaal.", "Die direkteur's besluit was finaal.", "Die direkteurs besluit was finaal."], "Die direkteur se besluit was finaal.", "Afrikaans gebruik 'se' vir besit: 'die direkteur se besluit'.", [E.EDIT], 2),
      ch("G12SKR05.13", "Wat is fout: 'Die twee spanne speel, en hy wen.'?", ["'hy' moet 'hulle' wees (verkeerde verwysing)", "Niks is fout nie", "'speel' is verkeerd"], "'hy' moet 'hulle' wees (verkeerde verwysing)", "Daar is twee spanne — die verwysing moet pas; 'hulle wen' (of noem die wenspan).", [E.EDIT], 3),
      ch("G12SKR05.14", "Kies die korrekte spelling:", ["geleentheid", "geleentheit", "gelentheid"], "geleentheid", "Die korrekte spelling is 'geleentheid'.", [E.EDIT], 2),
      cz("G12SKR05.15", "Verbeter die ontkenning: 'Ek het hom nie gesien ___.'", ["nie", "geen", "nooit"], "nie", "Die sin eindig met die sluitende 'nie': 'Ek het hom nie gesien nie.'", [E.EDIT], 1),
      ch("G12SKR05.16", "Wat is fout: 'Die verslag, is gister ingedien.'?", ["Die komma ná 'verslag' is verkeerd", "Niks is fout nie", "'verslag' is verkeerd"], "Die komma ná 'verslag' is verkeerd", "Daar hoort nie 'n komma tussen die onderwerp en die werkwoord nie.", [E.EDIT], 3),
      ch("G12SKR05.17", "Watter sin is korrek?", ["Hulle is verantwoordelik vir die projek.", "Hulle is verantwoordelik vir die projek nie.", "Hulle verantwoordelik is vir die projek."], "Hulle is verantwoordelik vir die projek.", "Die woordorde en spelling is korrek.", [E.EDIT], 1),
      ch("G12SKR05.18", "Wat is fout: 'Sy het die taak voltooi en sy het dit ingehandig en sy het huis toe gegaan.'?", ["Te veel 'en' — breek dit op in korter sinne", "Niks is fout nie", "'voltooi' is verkeerd"], "Te veel 'en' — breek dit op in korter sinne", "Te veel 'en's maak die sin lomp; breek dit op.", [E.EDIT], 2),
      ch("G12SKR05.19", "Watter sin gebruik leestekens in direkte rede korrek?", ["Sy sê: \"Die saak is afgehandel.\"", "Sy sê: Die saak is afgehandel.", "Sy sê \"die saak is afgehandel\""], "Sy sê: \"Die saak is afgehandel.\"", "Direkte rede kry 'n dubbelpunt, aanhalingstekens en 'n hoofletter.", [E.EDIT], 2),
      ch("G12SKR05.20", "Wat is fout: 'Ons het verlede jaar baie geleer en gegroei.'?", ["Niks is fout nie — die sin is korrek", "'geleer' moet 'leer' wees", "Daar kort 'n komma"], "Niks is fout nie — die sin is korrek", "Die sin is grammatikaal korrek in die verlede tyd.", [E.EDIT], 3),
    ]),

  ...skill(`${P}.06`, "Opsomming: parafraseer en kies kernpunte",
    "Kies hoofpunte en parafraseer dit in jou eie woorde vir 'n opsomming, binne 'n puntperk, sonder voorbeelde en herhaling.",
    "Skryf en aanbied", "T1", ["choice", "true-false"],
    "Hou net punte wat die betekenis verander; sê elkeen in jou eie woorde, en los voorbeelde en herhaling uit.",
    [
      ch("G12SKR06.01", "Watter een is 'n hoofpunt vir 'n opsomming?", ["Oefening verbeter geestesgesondheid.", "My broer draf elke oggend.", "Drafskoene kan duur wees."], "Oefening verbeter geestesgesondheid.", "Die hoofidee is dat oefening die geestesgesondheid verbeter.", [E.SUM], 2, cx("Oefening verbeter geestesgesondheid. My broer draf elke oggend. Dit verminder stres en verbeter slaap. Drafskoene kan duur wees.")),
      ch("G12SKR06.02", "Wat moet jy UITLAAT in 'n opsomming?", ["Voorbeelde en herhaling", "Die hoofidees", "Die sleutelfeite"], "Voorbeelde en herhaling", "Voorbeelde en herhaling word weggelaat.", [E.SUM], 1),
      tf("G12SKR06.03", "Jy moet die punte in jou eie woorde parafraseer, nie verbatim kopieer nie.", "Waar", "Ja — 'n goeie opsomming parafraseer in jou eie woorde.", [E.SUM], 1),
      ch("G12SKR06.04", "Watter een is 'n ONNODIGE besonderheid?", ["Die studie het 1 200 mense betrek.", "Roetine-oefening verlaag bloeddruk.", "Oefening versterk die hart."], "Die studie het 1 200 mense betrek.", "Die presiese steekproefgrootte is 'n besonderheid, nie 'n hoofpunt nie.", [E.SUM], 2, cx("Roetine-oefening verlaag bloeddruk. Die studie het 1 200 mense betrek. Oefening versterk die hart.")),
      ch("G12SKR06.05", "Hoeveel keer tel 'n herhaalde idee in 'n opsomming?", ["Een keer", "Twee keer", "Elke keer wat dit verskyn"], "Een keer", "'n Herhaalde idee tel net een keer.", [E.SUM], 2),
      ch("G12SKR06.06", "Watter parafrase dra 'Skoon water is noodsaaklik vir gesondheid' die beste oor?", ["Mense het skoon water nodig om gesond te bly.", "Water is nat.", "Skoon water is noodsaaklik vir gesondheid."], "Mense het skoon water nodig om gesond te bly.", "Die eerste opsie sê dieselfde idee in eie woorde — 'n goeie parafrase.", [E.SUM], 3),
      ch("G12SKR06.07", "Wat moet 'n opsomming behou?", ["Die kernbetekenis van die teks", "Al die voorbeelde", "Die skrywer se naam"], "Die kernbetekenis van die teks", "'n Opsomming behou die kernbetekenis.", [E.SUM], 1),
      tf("G12SKR06.08", "'n Opsomming behoort korter te wees as die oorspronklike teks.", "Waar", "Ja — 'n opsomming is altyd korter as die bron.", [E.SUM], 1),
      ch("G12SKR06.09", "Watter sin kan jy weglaat sonder om die betekenis te verloor?", ["Die fees was, terloops, baie kleurvol.", "Die fees vier die oes.", "Mense van oral kom na die fees."], "Die fees was, terloops, baie kleurvol.", "Die 'terloops'-sin is ekstra; die hoofpunte bly sonder dit verstaanbaar.", [E.SUM], 3, cx("Die fees vier die oes. Die fees was, terloops, baie kleurvol. Mense van oral kom na die fees.")),
      ch("G12SKR06.10", "Wat is die EERSTE ding wat jy doen wanneer jy opsom?", ["Lees die teks deur en identifiseer die hoofidees", "Begin dadelik skryf", "Tel die woorde"], "Lees die teks deur en identifiseer die hoofidees", "Eers lees en hoofidees identifiseer, dan opsom.", [E.SUM], 1),
      ch("G12SKR06.11", "Watter een is 'n hoofpunt?", ["Tegnologie het kommunikasie versnel.", "My foon is blou.", "Sommige programme is gratis."], "Tegnologie het kommunikasie versnel.", "Die hoofidee gaan oor tegnologie se uitwerking op kommunikasie.", [E.SUM], 2, cx("Tegnologie het kommunikasie versnel. My foon is blou. Boodskappe reis nou binne sekondes. Sommige programme is gratis.")),
      ch("G12SKR06.12", "Watter parafrase is die beste vir 'Die projek was 'n groot sukses'?", ["Die projek het uitstekend afgeloop.", "Die projek was 'n groot sukses.", "Die projek was groot."], "Die projek het uitstekend afgeloop.", "Die eerste opsie sê dieselfde idee in eie woorde.", [E.SUM], 2),
      ch("G12SKR06.13", "Wat doen jy as twee sinne dieselfde idee gee?", ["Sluit die idee net een keer in", "Sluit altwee in", "Laat altwee uit"], "Sluit die idee net een keer in", "Dieselfde idee word net een keer ingesluit.", [E.SUM], 2),
      ch("G12SKR06.14", "Watter een is 'n ONNODIGE voorbeeld?", ["soos appels, pere en lemoene", "Vrugte bevat vesel.", "Vrugte is gesond."], "soos appels, pere en lemoene", "Die lys voorbeelde kan weggelaat word.", [E.SUM], 2, cx("Vrugte is gesond. Vrugte bevat vesel, soos appels, pere en lemoene.")),
      ch("G12SKR06.15", "Behoort jy jou eie mening by 'n opsomming te voeg?", ["Nee, hou by die teks se idees", "Ja, altyd", "Net aan die einde"], "Nee, hou by die teks se idees", "'n Opsomming gee net die teks se idees, nie jou mening nie.", [E.SUM], 2),
      tf("G12SKR06.16", "Jy moet binne die gegewe punt- of woordperk bly.", "Waar", "Ja — 'n opsomming moet binne die perk bly.", [E.SUM], 1),
      ch("G12SKR06.17", "Watter een is 'n hoofpunt?", ["Bome verbeter lugkwaliteit.", "Die boom in ons straat is hoog.", "Voëls nes in bome."], "Bome verbeter lugkwaliteit.", "Die hoofidee gaan oor bome se uitwerking op lugkwaliteit.", [E.SUM], 2, cx("Bome verbeter lugkwaliteit. Die boom in ons straat is hoog. Voëls nes in bome. Hulle gee ook skadu.")),
      ch("G12SKR06.18", "Wat is die doel van 'n opsomming?", ["Om die hooftrekke kort en in eie woorde weer te gee", "Om die teks langer te maak", "Om nuwe inligting by te voeg"], "Om die hooftrekke kort en in eie woorde weer te gee", "'n Opsomming gee die hooftrekke kort, in eie woorde, weer.", [E.SUM], 1),
      ch("G12SKR06.19", "Watter een sou jy EERSTE skrap om 'n opsomming korter te maak?", ["'n Voorbeeld wat 'n punt illustreer", "Die hoofidee", "'n Sleutelfeit"], "'n Voorbeeld wat 'n punt illustreer", "Voorbeelde word eerste geskrap; hoofidees bly.", [E.SUM], 2),
      ch("G12SKR06.20", "Watter parafrase dra 'Die diere is met uitwissing bedreig' die beste oor?", ["Die diere loop gevaar om uit te sterf.", "Die diere is bedreig.", "Diere is mooi."], "Die diere loop gevaar om uit te sterf.", "Die eerste opsie sê dieselfde idee duidelik in eie woorde.", [E.SUM], 3),
    ]),
};

insertSkills(skills);
