// Grade 12 — Taalstrukture, skills TAA.07–TAA.12 (20 items each). Afrikaans-only, Matric level.
import { ch, tf, cz, skill, insertSkills } from "./_g12_bank_lib.mjs";

const P = "AF.G12.TAA";
const E = {
  REPORT: "ERR_AF_REPORTEDSPEECH", PASSIVE: "ERR_AF_PASSIVE", PUNCT: "ERR_AF_PUNCTUATION",
  SEM: "ERR_AF_SEMANTICS", HOMO: "ERR_AF_HOMOPHONE", IDIOM: "ERR_AF_IDIOM",
  WORDFORM: "ERR_AF_WORDFORM", SPELL: "ERR_AF_SPELLING", CONN: "ERR_AF_CONNOTATION",
};

const skills = {
  ...skill(`${P}.07`, "Direkte en indirekte rede (stel, vra, beveel)",
    "Verander stellings, vrae én bevele tussen direkte en indirekte rede: leestekens, voornaamwoorde en bywoorde van tyd/plek verander.",
    "Taalstrukture", "T1", ["choice", "cloze"],
    "Laat die aanhalingstekens weg, verskuif die voornaamwoorde, en skuif tyd-/plekwoorde; vrae en bevele kry hul eie vorm (vra ... of/waar; sê dat ... moet).",
    [
      ch("G12TAA07.01", "Kies die korrekte indirekte rede: Sy sê, \"Ek het die toets geslaag.\"", ["Sy sê dat sy die toets geslaag het.", "Sy sê dat ek die toets geslaag het.", "Sy sê dat sy die toets het geslaag."], "Sy sê dat sy die toets geslaag het.", "'Ek' word 'sy' en die werkwoordgroep skuif na die einde.", [E.REPORT], 2),
      ch("G12TAA07.02", "Kies die korrekte indirekte rede (vraag): Hy vra, \"Wanneer begin die vergadering?\"", ["Hy vra wanneer die vergadering begin.", "Hy vra wanneer begin die vergadering.", "Hy vra dat wanneer die vergadering begin."], "Hy vra wanneer die vergadering begin.", "By 'n vraag val die aanhalingstekens weg en die werkwoord skuif na die einde.", [E.REPORT], 2),
      ch("G12TAA07.03", "Kies die korrekte indirekte rede (ja/nee-vraag): Sy vra, \"Kom jy saam?\"", ["Sy vra of ek saamkom.", "Sy vra dat ek saamkom.", "Sy vra kom ek saam."], "Sy vra of ek saamkom.", "'n Ja/nee-vraag word met 'of' weergegee: 'of ek saamkom'.", [E.REPORT], 3),
      ch("G12TAA07.04", "Kies die korrekte indirekte rede (bevel): Die afrigter sê, \"Hardloop vinniger!\"", ["Die afrigter sê dat hulle vinniger moet hardloop.", "Die afrigter sê hardloop vinniger.", "Die afrigter sê dat vinniger hardloop hulle."], "Die afrigter sê dat hulle vinniger moet hardloop.", "'n Bevel word met 'moet' weergegee: 'dat hulle ... moet hardloop'.", [E.REPORT], 3),
      ch("G12TAA07.05", "Kies die korrekte indirekte rede: Pa sê, \"Ek sal julle môre kom haal.\"", ["Pa sê dat hy ons die volgende dag sal kom haal.", "Pa sê dat hy julle môre sal kom haal.", "Pa sê dat ek ons die volgende dag sal haal."], "Pa sê dat hy ons die volgende dag sal kom haal.", "'Ek'→'hy', 'julle'→'ons', 'môre'→'die volgende dag'.", [E.REPORT], 3),
      cz("G12TAA07.06", "Vul in: \"Ek woon hier,\" sê sy. → Sy sê dat sy ___ woon.", ["daar", "hier", "nou"], "daar", "'hier' word 'daar' in indirekte rede.", [E.REPORT], 2),
      cz("G12TAA07.07", "Vul in: \"Ons speel nou,\" sê hulle. → Hulle sê dat hulle ___ speel.", ["toe", "nou", "later"], "toe", "'nou' word 'toe'.", [E.REPORT], 2),
      ch("G12TAA07.08", "Kies die korrekte direkte rede: Sy vra of hy honger is.", ["Sy vra: \"Is jy honger?\"", "Sy vra: \"Is hy honger?\"", "Sy vra of: is jy honger."], "Sy vra: \"Is jy honger?\"", "Direkte rede gebruik aanhalingstekens en die normale vraagvorm.", [E.REPORT], 2),
      ch("G12TAA07.09", "Watter verandering gebeur met 'gister' in indirekte rede?", ["dit word 'die vorige dag'", "dit bly 'gister'", "dit word 'môre'"], "dit word 'die vorige dag'", "Tydwoorde skuif: 'gister' word 'die vorige dag'.", [E.REPORT], 3),
      ch("G12TAA07.10", "Kies die korrekte indirekte rede (bevel): Sy sê, \"Moenie laat wees nie.\"", ["Sy sê dat hulle nie laat moet wees nie.", "Sy sê dat moenie laat wees nie.", "Sy sê dat hulle nie laat wees moet."], "Sy sê dat hulle nie laat moet wees nie.", "'n Ontkennende bevel: 'dat hulle nie laat moet wees nie'.", [E.REPORT], 3),
      cz("G12TAA07.11", "Vul in: Hy sê, \"Ek is trots op jou.\" → Hy sê dat hy trots op ___ is.", ["my", "jou", "hom"], "my", "Wanneer hy met my praat, word 'jou' in die weergawe 'my'.", [E.REPORT], 2),
      ch("G12TAA07.12", "Watter leesteken val weg in indirekte rede?", ["aanhalingstekens", "die punt", "die komma"], "aanhalingstekens", "Indirekte rede gebruik nie aanhalingstekens nie.", [E.PUNCT], 1),
      ch("G12TAA07.13", "Kies die korrekte indirekte rede (vraag): Sy vra, \"Waarom is jy laat?\"", ["Sy vra waarom ek laat is.", "Sy vra waarom is ek laat.", "Sy vra dat waarom ek laat is."], "Sy vra waarom ek laat is.", "Die werkwoord skuif na die einde: 'waarom ek laat is'.", [E.REPORT], 2),
      cz("G12TAA07.14", "Vul in: \"Ek sal vandag klaarmaak,\" sê hy. → Hy sê dat hy ___ sal klaarmaak.", ["daardie dag", "vandag", "môre"], "daardie dag", "'vandag' word 'daardie dag'.", [E.REPORT], 3),
      ch("G12TAA07.15", "Kies die korrekte indirekte rede: Die juffrou sê, \"Maak julle boeke oop.\"", ["Die juffrou sê dat hulle hul boeke moet oopmaak.", "Die juffrou sê maak julle boeke oop.", "Die juffrou sê dat oopmaak hulle hul boeke."], "Die juffrou sê dat hulle hul boeke moet oopmaak.", "'n Bevel word met 'moet' weergegee en 'julle'→'hulle'.", [E.REPORT], 3),
      ch("G12TAA07.16", "Wat gebeur met 'ek' wanneer iemand anders die woorde weergee?", ["dit word 'hy' of 'sy'", "dit bly 'ek'", "dit word 'jy'"], "dit word 'hy' of 'sy'", "Die spreker se 'ek' word 'hy' of 'sy'.", [E.REPORT], 1),
      cz("G12TAA07.17", "Vul in: \"Ons wen môre,\" sê die span. → Die span sê dat hulle ___ wen.", ["die volgende dag", "môre", "gister"], "die volgende dag", "'môre' word 'die volgende dag'.", [E.REPORT], 3),
      ch("G12TAA07.18", "Kies die korrekte indirekte rede (ja/nee-vraag): Hy vra, \"Het jy geëet?\"", ["Hy vra of ek geëet het.", "Hy vra dat ek geëet het.", "Hy vra het ek geëet."], "Hy vra of ek geëet het.", "'n Ja/nee-vraag word met 'of' weergegee, werkwoord aan die einde.", [E.REPORT], 3),
      tf("G12TAA07.19", "By 'n bevel in indirekte rede gebruik ons gewoonlik die woord 'moet'.", "Waar", "Ja — 'n bevel word weergegee as 'sê dat ... moet ...'.", [E.REPORT], 2),
      ch("G12TAA07.20", "Kies die korrekte direkte rede: Sy vra waar die kantoor is.", ["Sy vra: \"Waar is die kantoor?\"", "Sy vra: \"Waar die kantoor is?\"", "Sy vra waar: is die kantoor."], "Sy vra: \"Waar is die kantoor?\"", "Direkte rede gebruik aanhalingstekens en normale vraagorde.", [E.REPORT], 2),
    ]),

  ...skill(`${P}.08`, "Bedrywende en lydende vorm (alle tye)",
    "Verander tussen die bedrywende (aktief) en lydende (passief) vorm oor die teenwoordige, verlede en toekomende tyd.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Lydend: die voorwerp word die onderwerp + word/is/was/sal ... word + ...ge-werkwoord + (deur die agent). Pas die hulpwerkwoord by die tyd.",
    [
      ch("G12TAA08.01", "Kies die korrekte lydende vorm (teenwoordig): 'Die rekenaar verwerk die data.'", ["Die data word deur die rekenaar verwerk.", "Die data is deur die rekenaar verwerk.", "Die data verwerk deur die rekenaar."], "Die data word deur die rekenaar verwerk.", "Teenwoordig lydend gebruik 'word ... verwerk'.", [E.PASSIVE], 2),
      ch("G12TAA08.02", "Kies die korrekte lydende vorm (verlede): 'Die komitee het die voorstel goedgekeur.'", ["Die voorstel is deur die komitee goedgekeur.", "Die voorstel word deur die komitee goedgekeur.", "Die voorstel was die komitee goedgekeur."], "Die voorstel is deur die komitee goedgekeur.", "Verlede lydend gebruik 'is ... goedgekeur'.", [E.PASSIVE], 3),
      ch("G12TAA08.03", "Kies die korrekte lydende vorm (toekomende): 'Die maatskappy sal die produk bekendstel.'", ["Die produk sal deur die maatskappy bekendgestel word.", "Die produk word deur die maatskappy bekendgestel.", "Die produk is deur die maatskappy bekendgestel."], "Die produk sal deur die maatskappy bekendgestel word.", "Toekomende lydend: 'sal ... bekendgestel word'.", [E.PASSIVE], 3),
      ch("G12TAA08.04", "Kies die korrekte bedrywende vorm: 'Die wedstryd word deur die skeidsregter gefluit.'", ["Die skeidsregter fluit die wedstryd.", "Die wedstryd fluit die skeidsregter.", "Die skeidsregter het die wedstryd gefluit."], "Die skeidsregter fluit die wedstryd.", "Bedrywend: die doener ('die skeidsregter') word die onderwerp.", [E.PASSIVE], 2),
      cz("G12TAA08.05", "Vul die hulpwerkwoord in (teenwoordig, lydend): 'Die verslag ___ deur die direkteur onderteken.'", ["word", "is", "was"], "word", "Teenwoordig lydend gebruik 'word'.", [E.PASSIVE], 1),
      cz("G12TAA08.06", "Vul die hulpwerkwoord in (verlede, lydend): 'Die brug ___ in 1950 gebou.'", ["is", "word", "sal"], "is", "Verlede lydend gebruik 'is ... gebou'.", [E.PASSIVE], 2),
      cz("G12TAA08.07", "Vul in (toekomende, lydend): 'Die wenners ___ môre aangekondig ___.'", ["sal ... word", "word ... is", "is ... word"], "sal ... word", "Toekomende lydend: 'sal ... aangekondig word'.", [E.PASSIVE], 3),
      ch("G12TAA08.08", "Watter sin is in die lydende vorm?", ["Die besluit word deur die raad geneem.", "Die raad neem die besluit.", "Die raad het die besluit geneem."], "Die besluit word deur die raad geneem.", "Die lydende vorm het 'word ... deur'.", [E.PASSIVE], 1),
      ch("G12TAA08.09", "Kies die korrekte lydende vorm (verlede): 'Die polisie het die verdagte gearresteer.'", ["Die verdagte is deur die polisie gearresteer.", "Die verdagte word deur die polisie gearresteer.", "Die verdagte het die polisie gearresteer."], "Die verdagte is deur die polisie gearresteer.", "Verlede lydend: 'is ... gearresteer'.", [E.PASSIVE], 2),
      ch("G12TAA08.10", "Kies die korrekte bedrywende vorm (verlede): 'Die venster is deur die wind gebreek.'", ["Die wind het die venster gebreek.", "Die wind breek die venster.", "Die venster het die wind gebreek."], "Die wind het die venster gebreek.", "Bedrywend verlede: 'Die wind het die venster gebreek.'", [E.PASSIVE], 2),
      cz("G12TAA08.11", "Vul die agent in: 'Die toespraak word ___ die president gelewer.'", ["deur", "met", "van"], "deur", "Die doener word met 'deur' aangedui: 'deur die president'.", [E.PASSIVE], 1),
      tf("G12TAA08.12", "In die lydende vorm word die voorwerp die onderwerp van die sin.", "Waar", "Ja — dit is hoe die lydende vorm werk.", [E.PASSIVE], 2),
      ch("G12TAA08.13", "Watter hulpwerkwoord pas by die toekomende tyd in die lydende vorm?", ["sal ... word", "is", "word"], "sal ... word", "Toekomende lydend gebruik 'sal ... word'.", [E.PASSIVE], 2),
      ch("G12TAA08.14", "Kies die korrekte lydende vorm (teenwoordig): 'Die skool reik die sertifikate uit.'", ["Die sertifikate word deur die skool uitgereik.", "Die sertifikate is deur die skool uitgereik.", "Die skool word die sertifikate uitgereik."], "Die sertifikate word deur die skool uitgereik.", "Teenwoordig lydend: 'word ... uitgereik'.", [E.PASSIVE], 3),
      ch("G12TAA08.15", "Watter hulpwerkwoord pas by die verlede tyd in die lydende vorm?", ["is", "word", "sal"], "is", "Verlede lydend gebruik 'is'.", [E.PASSIVE], 2),
      cz("G12TAA08.16", "Vul in (verlede, lydend): 'Die gedig ___ deur 'n leerder geskryf.'", ["is", "word", "sal"], "is", "Verlede lydend: 'is ... geskryf'.", [E.PASSIVE], 2),
      ch("G12TAA08.17", "Kies die korrekte bedrywende vorm: 'Die prys sal deur die beste student gewen word.'", ["Die beste student sal die prys wen.", "Die prys sal die beste student wen.", "Die beste student het die prys gewen."], "Die beste student sal die prys wen.", "Bedrywend toekomend: 'Die beste student sal die prys wen.'", [E.PASSIVE], 3),
      tf("G12TAA08.18", "Is 'Die kos word deur die sjef voorberei' teenwoordige tyd lydend?", "Waar", "Ja — 'word ... voorberei' met 'deur' is teenwoordig lydend.", [E.PASSIVE], 2),
      ch("G12TAA08.19", "Kies die korrekte lydende vorm (verlede): 'Hulle het die ou gebou gesloop.'", ["Die ou gebou is deur hulle gesloop.", "Die ou gebou word deur hulle gesloop.", "Die ou gebou het hulle gesloop."], "Die ou gebou is deur hulle gesloop.", "Verlede lydend: 'is ... gesloop'.", [E.PASSIVE], 3),
      ch("G12TAA08.20", "Kies die korrekte lydende vorm (toekomende): 'Die raad sal die begroting goedkeur.'", ["Die begroting sal deur die raad goedgekeur word.", "Die begroting word deur die raad goedgekeur.", "Die begroting is deur die raad goedgekeur."], "Die begroting sal deur die raad goedgekeur word.", "Toekomende lydend: 'sal ... goedgekeur word'.", [E.PASSIVE], 3),
    ]),

  ...skill(`${P}.09`, "Leestekens en punktuasie",
    "Korrekte gebruik van leestekens: komma, punt, vraagteken, dubbelpunt, kommapunt, aanhalingstekens, koppelteken, afkappingsteken en deelteken.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Elke teken het 'n taak: : lei in, ; verbind twee nou sinne, “ ” omraam die presiese woorde, en 'se' (nie 's nie) wys besit in Afrikaans.",
    [
      ch("G12TAA09.01", "Watter leesteken verbind twee nou verwante hoofsinne sonder voegwoord?", ["kommapunt (;)", "komma (,)", "vraagteken (?)"], "kommapunt (;)", "Die kommapunt verbind twee nou verwante hoofsinne: 'Dit reën; ons bly tuis.'", [E.PUNCT], 3),
      ch("G12TAA09.02", "Watter leesteken lei 'n lys of verduideliking in?", ["dubbelpunt (:)", "kommapunt (;)", "komma (,)"], "dubbelpunt (:)", "Die dubbelpunt lei 'n lys/verduideliking in.", [E.PUNCT], 2),
      ch("G12TAA09.03", "Kies die korrekte direkte rede:", ["Sy fluister: \"Wees stil.\"", "Sy fluister: Wees stil.", "Sy fluister \"wees stil\""], "Sy fluister: \"Wees stil.\"", "Direkte rede kry 'n dubbelpunt, aanhalingstekens en 'n hoofletter.", [E.PUNCT], 2),
      ch("G12TAA09.04", "Watter sin gebruik die besitsvorm korrek?", ["Dit is die maatskappy se beleid.", "Dit is die maatskappy's beleid.", "Dit is die maatskappys beleid."], "Dit is die maatskappy se beleid.", "Afrikaans gebruik 'se' vir besit (nie 's nie).", [E.PUNCT], 2),
      ch("G12TAA09.05", "Kies die korrekte gebruik van die afkappingsteken:", ["Dit het in die 1980's gebeur.", "Dit het in die 1980s' gebeur.", "Dit het in die 1980s gebeur."], "Dit het in die 1980's gebeur.", "Die afkappingsteken kom voor die meervouds-s: '1980's'.", [E.PUNCT], 3),
      ch("G12TAA09.06", "Watter sin gebruik kommas korrek?", ["Sy het melk, brood en eiers gekoop.", "Sy het melk brood, en eiers gekoop.", "Sy het, melk brood en eiers gekoop."], "Sy het melk, brood en eiers gekoop.", "Kommas skei items in 'n lys; die laaste twee word met 'en' verbind.", [E.PUNCT], 2),
      ch("G12TAA09.07", "Kies die korrek geskrewe sin:", ["\"Pasop!\" skreeu hy.", "\"Pasop\"! skreeu hy.", "\"pasop!\" skreeu hy."], "\"Pasop!\" skreeu hy.", "Die uitroepteken staan binne die aanhalingstekens en die woord kry 'n hoofletter.", [E.PUNCT], 2),
      ch("G12TAA09.08", "Watter leesteken pas: 'Daar was net een probleem___ daar was geen geld nie.'", [": ", "; ", ", "], ": ", "Die dubbelpunt lei die verduideliking in.", [E.PUNCT], 3),
      ch("G12TAA09.09", "Watter sin gebruik die deelteken korrek?", ["Hy het die reëls oortree.", "Hy het die reels oortree.", "Hy het die re-els oortree."], "Hy het die reëls oortree.", "Die deelteken (ë) wys dat die e apart uitgespreek word: 'reëls'.", [E.PUNCT], 3),
      ch("G12TAA09.10", "Watter sin gebruik die koppelteken korrek?", ["een-en-twintig", "een en twintig", "een–en–twintig"], "een-en-twintig", "Getalle soos 'een-en-twintig' kry koppeltekens.", [E.PUNCT], 2),
      cz("G12TAA09.11", "Vul die regte teken in: 'Het jy die kontrak geteken___'", ["?", "!", "."], "?", "Dit is 'n vraag, dus 'n vraagteken.", [E.PUNCT], 1),
      tf("G12TAA09.12", "Die eerste woord van 'n aangehaalde volsin begin met 'n hoofletter.", "Waar", "Ja — die aangehaalde volsin begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G12TAA09.13", "Kies die korrekte sin:", ["\"Waar gaan jy heen?\" vra sy.", "\"Waar gaan jy heen\"? vra sy.", "\"waar gaan jy heen?\" vra sy."], "\"Waar gaan jy heen?\" vra sy.", "Die vraagteken staan binne die aanhalingstekens en die sin begin met 'n hoofletter.", [E.PUNCT], 2),
      ch("G12TAA09.14", "Watter leesteken eindig 'n gewone stelsin?", ["punt (.)", "dubbelpunt (:)", "kommapunt (;)"], "punt (.)", "'n Stelsin eindig met 'n punt.", [E.PUNCT], 1),
      cz("G12TAA09.15", "Vul die teken in: 'My gunstelinge is die volgende___ lees, stap en kook.'", [":", ";", ","], ":", "Die dubbelpunt lei die lys in.", [E.PUNCT], 2),
      ch("G12TAA09.16", "Watter sin gebruik aanhalingstekens vir 'n titel korrek?", ["Ons bestudeer die roman \"Fiela se Kind\".", "Ons bestudeer die roman Fiela se Kind\".", "Ons bestudeer die roman \"Fiela se Kind."], "Ons bestudeer die roman \"Fiela se Kind\".", "Titels word tussen aanhalingstekens geplaas — oop en toe.", [E.PUNCT], 2),
      tf("G12TAA09.17", "''Thabo's boek' is die korrekte Afrikaanse besitsvorm.", "Onwaar", "Nee — Afrikaans gebruik 'Thabo se boek', nie ''s nie.", [E.PUNCT], 2),
      ch("G12TAA09.18", "Watter teken verbind woorddele soos 'wen-doel'?", ["koppelteken (-)", "komma (,)", "dubbelpunt (:)"], "koppelteken (-)", "Die koppelteken verbind woorddele.", [E.PUNCT], 1),
      ch("G12TAA09.19", "Kies die korrekte sin met 'n bywoordelike inleiding en komma:", ["Ná die wedstryd, het die span gaan eet.", "Ná die wedstryd het die span gaan eet.", "Ná, die wedstryd het die span gaan eet."], "Ná die wedstryd het die span gaan eet.", "Ná 'n kort bywoordelike inleiding is die komma in Afrikaans gewoonlik nie nodig nie.", [E.PUNCT], 3),
      cz("G12TAA09.20", "Vul die teken in: 'Wat 'n pragtige uitsig___'", ["!", "?", "."], "!", "'n Uitroep kry 'n uitroepteken.", [E.PUNCT], 1),
    ]),

  ...skill(`${P}.10`, "Betekenisleer: sinonieme, antonieme, homofone, homonieme, paronieme",
    "Sinonieme, antonieme, homofone, homonieme, paronieme en polisemie — woorde wat dieselfde klink, lyk of meer as een betekenis het.",
    "Taalstrukture", "T2", ["choice", "cloze", "true-false"],
    "Sinoniem = dieselfde betekenis, antoniem = teenoorgesteld; homofone klink dieselfde maar verskil in spelling; polisemie = een woord met verwante betekenisse.",
    [
      ch("G12TAA10.01", "Watter woord is 'n sinoniem vir 'belangrik'?", ["noodsaaklik", "onnodig", "klein"], "noodsaaklik", "'belangrik' en 'noodsaaklik' beteken min of meer dieselfde.", [E.SEM], 2),
      ch("G12TAA10.02", "Wat is die teenoorgestelde (antoniem) van 'tydelik'?", ["permanent", "kort", "vinnig"], "permanent", "Die antoniem van 'tydelik' is 'permanent'.", [E.SEM], 2),
      ch("G12TAA10.03", "Wat is die teenoorgestelde van 'oorvloed'?", ["tekort", "baie", "groot"], "tekort", "Die antoniem van 'oorvloed' is 'tekort'.", [E.SEM], 3),
      cz("G12TAA10.04", "Kies die korrekte homofoon: 'Die boer ___ sy skape na die veld.' (om voor te loop)", ["lei", "ly", "lê"], "lei", "'lei' beteken om voor te loop/te wys; 'ly' beteken om swaar te kry.", [E.HOMO], 3),
      cz("G12TAA10.05", "Kies die korrekte homofoon: 'Baie mense ___ aan armoede.' (om swaar te kry)", ["ly", "lei", "lê"], "ly", "'ly' beteken om swaar te kry; 'lei' beteken om te lei.", [E.HOMO], 3),
      ch("G12TAA10.06", "Watter twee woorde is homofone?", ["wei en wy", "groot en klein", "blink en dof"], "wei en wy", "'wei' (gras eet) en 'wy' (toewy) klink dieselfde maar verskil in betekenis.", [E.HOMO], 3),
      ch("G12TAA10.07", "Watter woord is 'n sinoniem vir 'moeilik'?", ["ingewikkeld", "maklik", "eenvoudig"], "ingewikkeld", "'moeilik' en 'ingewikkeld' is sinonieme.", [E.SEM], 2),
      ch("G12TAA10.08", "Wat is die teenoorgestelde van 'toelaat'?", ["verbied", "gee", "open"], "verbied", "Die antoniem van 'toelaat' is 'verbied'.", [E.SEM], 2),
      ch("G12TAA10.09", "Watter woord toon polisemie (een woord, verwante betekenisse)? 'voet'", ["voet (liggaamsdeel én onderkant van 'n berg)", "voet en hand", "voet en kop"], "voet (liggaamsdeel én onderkant van 'n berg)", "'voet' het verwante betekenisse (van die liggaam, van 'n berg) — polisemie.", [E.SEM], 3),
      ch("G12TAA10.10", "Watter woord is 'n homoniem (dieselfde spelling, twee onverwante betekenisse)? 'kraan'", ["kraan (water-kraan én hyskraan)", "kraan en pyp", "kraan en water"], "kraan (water-kraan én hyskraan)", "'kraan' kan 'n watertoestel of 'n hyskraan wees — een spelling, twee betekenisse.", [E.SEM], 3),
      ch("G12TAA10.11", "Watter woord is 'n sinoniem vir 'gelukkig'?", ["tevrede", "hartseer", "kwaad"], "tevrede", "'gelukkig' en 'tevrede' lê naby mekaar in betekenis.", [E.SEM], 1),
      ch("G12TAA10.12", "Wat is die teenoorgestelde van 'verminder'?", ["vermeerder", "verklein", "verdwyn"], "vermeerder", "Die antoniem van 'verminder' is 'vermeerder'.", [E.SEM], 2),
      cz("G12TAA10.13", "Kies die korrekte paronieme: 'Die ___ van die ondersoek is duidelik.' (uitslag, nie 'uitstal' nie)", ["uitslag", "uitstal", "uitlaat"], "uitslag", "'uitslag' (resultaat) is hier korrek; moenie met soortgelyke woorde verwar nie.", [E.SPELL], 3),
      ch("G12TAA10.14", "Watter woord is 'n sinoniem vir 'begin'?", ["aanvang", "beëindig", "ophou"], "aanvang", "'begin' en 'aanvang' is sinonieme.", [E.SEM], 2),
      ch("G12TAA10.15", "Wat is die teenoorgestelde van 'oorwinning'?", ["nederlaag", "wedstryd", "prys"], "nederlaag", "Die antoniem van 'oorwinning' is 'nederlaag'.", [E.SEM], 2),
      tf("G12TAA10.16", "Is 'ryk' en 'arm' antonieme?", "Waar", "Ja — 'ryk' en 'arm' is teenoorgesteldes.", [E.SEM], 1),
      cz("G12TAA10.17", "Kies die korrekte woord: 'Hy het 'n wyse ___ gegee.' (raad, nie 'raat' nie)", ["raad", "raat", "raat'"], "raad", "'raad' is advies; 'raat' is 'n geneesmiddel — let op die betekenis.", [E.HOMO], 3),
      ch("G12TAA10.18", "Watter woord is 'n sinoniem vir 'vinnig'?", ["rats", "stadig", "swaar"], "rats", "'vinnig' en 'rats' lê naby mekaar in betekenis.", [E.SEM], 2),
      ch("G12TAA10.19", "Wat is die teenoorgestelde van 'eerlik'?", ["oneerlik", "vriendelik", "stil"], "oneerlik", "Die antoniem van 'eerlik' is 'oneerlik'.", [E.SEM], 1),
      ch("G12TAA10.20", "Watter woord het meer as een verwante betekenis (polisemie)? 'blad'", ["blad ('n papierblad én 'n boomblaar)", "blad en boek", "blad en pen"], "blad ('n papierblad én 'n boomblaar)", "'blad' het verwante betekenisse (papier, plant) — polisemie.", [E.SEM], 3),
    ]),

  ...skill(`${P}.11`, "Idiome, spreekwoorde en uitdrukkings",
    "Verstaan 'n wye verskeidenheid Afrikaanse idiome, idiomatiese uitdrukkings en spreekwoorde volgens hul figuurlike betekenis.",
    "Taalstrukture", "T4", ["choice", "cloze", "true-false"],
    "Stel jou voor wat die woorde letterlik sê, en vra dan wat mense regtig daarmee bedoel; leer idiome as geheel.",
    [
      ch("G12TAA11.01", "Wat beteken 'om olie op die vuur te gooi'?", ["om 'n situasie erger te maak", "om te kook", "om te help"], "om 'n situasie erger te maak", "Dit beteken om 'n moeilike situasie nog erger te maak.", [E.IDIOM], 2),
      ch("G12TAA11.02", "Wat beteken 'om die hand in eie boesem te steek'?", ["om jou eie skuld te erken", "om koud te kry", "om te soek"], "om jou eie skuld te erken", "Dit beteken om by jouself te kyk en jou eie aandeel/skuld te erken.", [E.IDIOM], 3),
      ch("G12TAA11.03", "Wat beteken 'om iemand om die bos te lei'?", ["om iemand te mislei", "om te gaan stap", "om te help soek"], "om iemand te mislei", "Dit beteken om iemand te bedrieg of te kul.", [E.IDIOM], 3),
      ch("G12TAA11.04", "Wat beteken 'die wêreld is sy oester'?", ["alle moontlikhede lê voor hom oop", "hy hou van see", "hy is ryk"], "alle moontlikhede lê voor hom oop", "Dit beteken alle geleenthede lê vir hom oop.", [E.IDIOM], 3),
      ch("G12TAA11.05", "Wat beteken die spreekwoord 'Hoë bome vang baie wind'?", ["belangrike mense kry baie kritiek", "bome is gevaarlik", "wind is sterk"], "belangrike mense kry baie kritiek", "Mense in hoë/belangrike posisies trek meer kritiek.", [E.IDIOM], 3),
      ch("G12TAA11.06", "Wat beteken 'om jou ywer te bekoel'?", ["om kalmer/minder geesdriftig te word", "om koud te kry", "om te rus"], "om kalmer/minder geesdriftig te word", "Dit beteken om minder geesdriftig of opgewonde te raak.", [E.IDIOM], 3),
      ch("G12TAA11.07", "Wat beteken die spreekwoord 'Sagte heelmeesters maak stinkende wonde'?", ["te toegeeflik wees, maak dinge erger", "dokters is sag", "wonde ruik sleg"], "te toegeeflik wees, maak dinge erger", "As jy te sag/toegeeflik is, los jy probleme nie behoorlik op nie.", [E.IDIOM], 3),
      ch("G12TAA11.08", "Wat beteken 'om met twee monde te praat'?", ["om teenstrydige dinge te sê", "om vinnig te praat", "om te eet"], "om teenstrydige dinge te sê", "Dit beteken om verskillende, teenstrydige dinge te sê.", [E.IDIOM], 3),
      ch("G12TAA11.09", "Wat beteken 'om die spit af te byt'?", ["om die swaarste deel te verduur", "om te eet", "om kwaad te word"], "om die swaarste deel te verduur", "Dit beteken om die moeilikste/swaarste deel te deurstaan.", [E.IDIOM], 3),
      ch("G12TAA11.10", "Wat beteken 'om iets onder die knie te kry'?", ["om iets te bemeester", "om te val", "om te knyp"], "om iets te bemeester", "Dit beteken om iets goed te leer doen / te bemeester.", [E.IDIOM], 2),
      cz("G12TAA11.11", "Voltooi die idioom: 'Hy het die ___ in eie boesem gesteek.'", ["hand", "voet", "kop"], "hand", "Die idioom is 'die hand in eie boesem steek'.", [E.IDIOM], 3),
      cz("G12TAA11.12", "Voltooi die spreekwoord: 'Al lyk die aap ook hoe mooi, hy bly 'n ___.'", ["aap", "kat", "hond"], "aap", "Die spreekwoord is 'Al lyk die aap ook hoe mooi, hy bly 'n aap' — jou ware aard kom uit.", [E.IDIOM], 3),
      ch("G12TAA11.13", "Wat beteken 'om bakhand te staan'?", ["om te smeek of afhanklik te wees", "om te help", "om te klap"], "om te smeek of afhanklik te wees", "Dit beteken om te bedel/smeek of van ander afhanklik te wees.", [E.IDIOM], 3),
      ch("G12TAA11.14", "Wat beteken 'om die tande op mekaar te byt'?", ["om deur te druk ondanks moeilikheid", "om kwaad te wees", "om te eet"], "om deur te druk ondanks moeilikheid", "Dit beteken om vol te hou ten spyte van swaarkry.", [E.IDIOM], 2),
      ch("G12TAA11.15", "Wat beteken die spreekwoord 'Stille waters, diepe grond'?", ["'n stil mens kan diep/onverwags wees", "water is gevaarlik", "grond is nat"], "'n stil mens kan diep/onverwags wees", "Dit beteken 'n stil persoon het dikwels verborge dieptes.", [E.IDIOM], 3),
      ch("G12TAA11.16", "Wat beteken 'om iemand 'n hak te slaan'?", ["om iemand te dwarsboom", "om iemand te help", "om te dans"], "om iemand te dwarsboom", "Dit beteken om iemand se planne te dwarsboom/in die wiele te ry.", [E.IDIOM], 3),
      tf("G12TAA11.17", "Beteken 'om die hoof in die nek te gooi' dat iemand uitdagend/trots is?", "Waar", "Ja — dit dui op 'n trotse, uitdagende houding.", [E.IDIOM], 3),
      ch("G12TAA11.18", "Wat beteken 'om jou skape op die droë te hê'?", ["om finansieel veilig te wees", "om boer te wees", "om te swem"], "om finansieel veilig te wees", "Dit beteken om finansieel goed gevestig/veilig te wees.", [E.IDIOM], 3),
      cz("G12TAA11.19", "Voltooi die idioom: 'Sy het die ___ uit die mou gelaat.'", ["aap", "kat", "hond"], "aap", "'die aap uit die mou laat' — 'n geheim verklap.", [E.IDIOM], 2),
      ch("G12TAA11.20", "Wat beteken 'om die kool en die geit te probeer spaar'?", ["om twee teenstrydige belange te wil bevredig", "om kos te spaar", "om geld te bêre"], "om twee teenstrydige belange te wil bevredig", "Dit beteken om almal/alles tegelyk tevrede te wil hou.", [E.IDIOM], 3),
    ]),

  ...skill(`${P}.12`, "Woordvorming, spelling en denotasie/konnotasie",
    "Bou en spel woorde (afleiding, samestelling, samestellende afleiding, akronieme) en onderskei tussen 'n woord se denotasie en konnotasie.",
    "Taalstrukture", "T3", ["choice", "cloze", "true-false"],
    "Afrikaans skryf samestellings as EEN woord; denotasie is die letterlike betekenis, konnotasie die gevoel wat 'n woord dra.",
    [
      ch("G12TAA12.01", "Hoe skryf 'n mens 'rekenaar' + 'program' korrek?", ["rekenaarprogram", "rekenaar program", "rekenaar-program"], "rekenaarprogram", "Samestellings word as een woord geskryf.", [E.WORDFORM], 1),
      ch("G12TAA12.02", "Watter woord is 'n samestellende afleiding?", ["langasem", "tafeldoek", "leser"], "langasem", "'langasem' (lang + asem + afleiding-uitgang) is 'n samestellende afleiding.", [E.WORDFORM], 3),
      cz("G12TAA12.03", "Voeg '-loos' by 'doel': ___ (sonder doel)", ["doelloos", "doeleloos", "doel loos"], "doelloos", "'-loos' = sonder: 'doelloos'.", [E.WORDFORM], 2),
      cz("G12TAA12.04", "Voeg 'wan-' by 'begrip': ___ (verkeerde begrip)", ["wanbegrip", "wan begrip", "wanbegrippe"], "wanbegrip", "'wan-' dui 'n verkeerde/foutiewe vorm aan: 'wanbegrip'.", [E.WORDFORM], 3),
      ch("G12TAA12.05", "Waarvoor staan die akroniem 'SAID' (belasting)?", ["Suid-Afrikaanse Inkomstediens", "Suid-Afrikaanse Internet Diens", "Stad Aan Die See"], "Suid-Afrikaanse Inkomstediens", "'SAID' staan vir die Suid-Afrikaanse Inkomstediens.", [E.SPELL], 2),
      ch("G12TAA12.06", "Wat is die DENOTASIE (letterlike betekenis) van 'slang'?", ["'n reptiel sonder bene", "'n verraderlike persoon", "iets gevaarliks"], "'n reptiel sonder bene", "Die denotasie is die letterlike woordeboekbetekenis.", [E.CONN], 2),
      ch("G12TAA12.07", "Wat is die KONNOTASIE van om iemand 'n 'slang' te noem?", ["verraderlik / onbetroubaar", "lank", "groen"], "verraderlik / onbetroubaar", "Die konnotasie dra 'n negatiewe gevoel: verraderlik/onbetroubaar.", [E.CONN], 3),
      ch("G12TAA12.08", "Watter woord het 'n POSITIEWE konnotasie?", ["spaarsaam", "suinig", "vrekkig"], "spaarsaam", "'spaarsaam' klink positief; 'suinig'/'vrekkig' negatief — al lê hulle naby in betekenis.", [E.CONN], 3),
      ch("G12TAA12.09", "Hoe skryf 'n mens 'see' + 'water' korrek?", ["seewater", "see water", "see-water"], "seewater", "Een woord: 'seewater'.", [E.WORDFORM], 1),
      ch("G12TAA12.10", "Watter woord is 'n afleiding van 'lees'?", ["leser", "leesboek", "leestyd"], "leser", "'leser' is afgelei met '-er'; die ander is samestellings.", [E.WORDFORM], 2),
      ch("G12TAA12.11", "Watter woord is korrek gespel?", ["onmiddellik", "onmidellik", "onmiddelik"], "onmiddellik", "Die korrekte spelling is 'onmiddellik'.", [E.SPELL], 3),
      ch("G12TAA12.12", "Watter woord is korrek gespel?", ["aanvanklik", "aanvankelik", "aanvanlik"], "aanvanklik", "Die korrekte spelling is 'aanvanklik'.", [E.SPELL], 3),
      cz("G12TAA12.13", "Voeg '-heid' by 'eerlik': ___", ["eerlikheid", "eerlik heid", "eerelikheid"], "eerlikheid", "'-heid' maak 'n abstrakte naamwoord: 'eerlikheid'.", [E.WORDFORM], 2),
      ch("G12TAA12.14", "Waarvoor staan die afkorting 'i.p.v.'?", ["in plaas van", "in particuliere voorkeur", "is presies van"], "in plaas van", "'i.p.v.' staan vir 'in plaas van'.", [E.SPELL], 2),
      ch("G12TAA12.15", "Watter woord het 'n NEGATIEWE konnotasie?", ["goedkoop (van swak gehalte)", "bekostigbaar", "billik"], "goedkoop (van swak gehalte)", "'goedkoop' dra dikwels die konnotasie 'swak gehalte'; 'bekostigbaar/billik' klink positief.", [E.CONN], 3),
      ch("G12TAA12.16", "Hoe skryf 'n mens 'hoof' + 'kantoor' korrek?", ["hoofkantoor", "hoof kantoor", "hoof-kantoor"], "hoofkantoor", "Een woord: 'hoofkantoor'.", [E.WORDFORM], 1),
      tf("G12TAA12.17", "Word 'see water' korrek as twee woorde geskryf?", "Onwaar", "Nee — dit is 'n samestelling: 'seewater' (een woord).", [E.WORDFORM], 1),
      ch("G12TAA12.18", "Watter woord is korrek gespel?", ["geleentheid", "geleentheit", "gelentheid"], "geleentheid", "Die korrekte spelling is 'geleentheid'.", [E.SPELL], 2),
      cz("G12TAA12.19", "Voeg 'her-' by 'struktureer': ___ (om te herorganiseer)", ["herstruktureer", "her struktureer", "herstruktureerd"], "herstruktureer", "'her-' = weer/oor: 'herstruktureer'.", [E.WORDFORM], 3),
      ch("G12TAA12.20", "Wat is die verskil tussen denotasie en konnotasie?", ["denotasie is die letterlike betekenis; konnotasie die gevoelswaarde", "hulle is dieselfde", "denotasie is die gevoel; konnotasie die feit"], "denotasie is die letterlike betekenis; konnotasie die gevoelswaarde", "Denotasie = letterlike betekenis; konnotasie = die gevoel/assosiasie.", [E.CONN], 2),
    ]),
};

insertSkills(skills);
